### PR TITLE
🚨🚨 🐛 Source TikTok Marketing: fix error while converting `mobile_app_id` column to int in AudienceReports streams

### LINKED ISSUE #19757: 🐛 Source TikTok Marketing - Error while converting `mobile_app_id` column to int in AudienceReports streams
## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **Source Connector and version**: TikTok Marketing version 0.1.17
- **Destination Connector and version**: BigQuery 1.1.11
- **Step where error happened**: Sync job

## Current Behavior
When syncing `*_audience_reports` streams, I got an error while converting the `mobile_app_id` column to integer. The value it contains is a string. The sync job thus fails because of the conversion error.

## Expected Behavior
The conversion is successful for this column and the sync job is in success when syncing `audience_reports` streams.

## Logs
[logs-999.txt](https://github.com/airbytehq/airbyte/files/10076113/logs-999.txt)

## Steps to Reproduce
1. Set up a connection using TikTok Marketing source. My use case is with a BigQuery destination. Not sure if there is the same thing with other destinations.
2. In Replication, select at least one `audience_reports` streams like `ads_audience_reports_daily`.
3. Sync

## Are you willing to submit a PR?

Yes 😄

### PR DESCRIPTION
**Pull request by achaussende**
## What

Fixing the `audience_reports` schema only for the `mobile_app_id` that should be a string instead of an integer.

Closes #19757

## How
Update `mobile_app_id` type from `integer` to `string` in `schemas/audience_reports.json` file.

## 🚨 User Impact 🚨

The impact is a change in column type in the destination: from `integer` to `string`.

The AudienceReports streams only works if the `mobile_app_id` is an integer value. From [TikTok Marketing API documentation](https://ads.tiktok.com/marketing_api/docs?id=1707957217727489), an integer value in `mobile_app_id` means that the app is only coming from Apple's App Store. But it's possible to have string values in this column for Android devices. Also according to the API spec, the column is a string.

So this PR is a breaking change if users have setup the replication of `audience_reports` streams. But the replication is faulty so it may actually fix the connection.

## Pre-merge Checklist

__Updating a connector__

### Community member or Airbyter

- [X] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [X] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [ ] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by alafanechere** [comment]
The failing test that is not related to the backward incompatibility should be resolved by this PR: https://github.com/airbytehq/airbyte/pull/19806 

@achaussende feel free to rebase your branch once it's merged

**Comment by alafanechere** [comment]
@achaussende I updated your branch an re-ran the tests. Failing test due to missing stream in the catalog should be gone.

**Comment by alafanechere** [comment]
@davydov-d / @YowanR may I ask you for a review and balance for our cloud users on the benefit of this fix vs the backward incompatibility that introduces the schema change?

**Review by davydov-d — APPROVED** [review]

**Comment by YowanR** [comment]
@davydov-d Before we move ahead here, let's do a quick audit on the impact on customers please. Are you able to pull that data? We don't want to break any customer syncs without giving them a heads-up. 
cc @erica-airbyte as FYI

**Comment by erica-airbyte** [comment]
@YowanR and @davydov-d ideally if we can get around having to have customers run a schema reset that would be idea but please loop me in if there is customer impact and who we need to reach out to! Thanks.

**Comment by erica-airbyte** [comment]
@davydov-d one this fixes goes out the customer needs to refresh their schema and run a reset for the AudienceReports streams?

**Comment by davydov-d** [comment]
@erica-airbyte yes! but resync should be made for **all of the** `AudienceReports` streams (there may be multiple streams of this type, see first connection link for example)

**Comment by erica-airbyte** [comment]
@davydov-d we are reaching out to customer today. When is this going to cloud?

**Comment by erica-airbyte** [comment]
Customer comms have been sent out to [those noted in this comment] letting know the update that will go out tomorrow 12-16 UTC (https://github.com/airbytehq/airbyte/pull/19758#issuecomment-1339836357)

**Comment by erica-airbyte** [comment]
@davydov-d any update when this might go out?

**Comment by davydov-d** [comment]
I missed that the integration tests are failing :confused: 
Combined with our new workflow retry strategy it leads to endless builds..

**Comment by davydov-d** [comment]
@achaussende could you please also make the change like this? I'm not able to push the changes to your branch by myself
image
(this is acceptance-test-config.yml file)

**Comment by davydov-d** [comment]
@erica-airbyte well I have figured out what needs to be done but I can not do it on my own :point_up: 
as soon as we fix the acceptance tests, things should start working. Hope for assistance from @achaussende

**Comment by achaussende** [comment]
@davydov-d Done in e9358f9 ✅

**Comment by erica-airbyte** [comment]
@davydov-d please lmk when this is on cloud and then we can circle back to users!

**Comment by davydov-d** [comment]
@erica-airbyte done!
thanks @achaussende!

**Pull request merged**
