### PR TITLE
Source Stripe: fix schema

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/oncall/issues/1299

## How
Fix `Invoices` stream schema

### CODE REVIEW

**Review by roman-yermilov-gl — APPROVED** [review]

**Review by lazebnyi — APPROVED** [review]

**Comment by davydov-d** [comment]
@pedroslopez thanks for flagging this. No, it's not intentional. For some reason there we changes from this [PR](https://github.com/airbytehq/airbyte/pull/22309). I've merged latest master and now there are no more non-related changes

**Comment by davydov-d** [comment]
strictness level will be changed [here](https://github.com/airbytehq/airbyte/pull/21419)

**Review by alafanechere — APPROVED** [review]
Is it failing for all the stripe connection using the `invoice` stream? If yes I think the backward incompatibility is legit. Please sync with @airbytehq/cloud-support before merge to make sure the breaking change introduction is understood and if a customer outreach is required.

**Comment by alafanechere** [comment]
The QA checks are likely to fail, feel free to pull the changes from this PR https://github.com/airbytehq/airbyte/pull/22886

**Comment by davydov-d** [comment]
> The QA checks are likely to fail, feel free to pull the changes from this PR #22886

Thanks, pulled the changes from your PR! Regarding the release, it has already been scheduled with TCS and the outreach should have been made already

**Review by lazebnyi — APPROVED** [review]
Required CI builds looks good. Only one CI job is failed, because not enabled high strictness for GA. It will be implemented in https://github.com/airbytehq/airbyte/pull/21419. We can move next to fix on-call issue.

**Comment by octavia-approvington** [comment]
This is really good <br/> simply the best

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
