### PR TITLE
Change main class in strict-encrypt destination and bump versions on …

### LINKED ISSUE #21507: Clickhouse destination allows turning off SSL
## What
Clickhouse destination in cloud does not hide "SSL Connection" toggle. The code in destination-clickhouse-strict-encrypt looks like it should hide it, but for whatever reason, it does not:
Screen Shot 2023-01-17 at 4 28 41 PM

### PR DESCRIPTION
**Pull request by grishick**
Fixes https://github.com/airbytehq/airbyte/issues/21507

Change main class in strict-encrypt destination and bump versions on both destinations to keep them in sync

### CODE REVIEW

**Review by akashkulk — APPROVED** [review]
So all this while, there was no difference between strict-encrypt variant of destination-clickouse?

**Comment by grishick** [comment]
Going to merge this change w/o integration tests, because the tests are broken (`test_update_secrets.py` is failing). There are no functional changes in this PR and the bug is an urgent security problem.

**Pull request merged**
