### PR TITLE
Improve performance of list connection operations

### LINKED ISSUE #19849: Trim Connection List Endpoint
The connections/list endpoint has some fields that are unnecessary for the frontend. To improve performance we should slim down this endpoint to be closer to _just_ what the frontend needs.

1. Remove `sourceId` and `destinationId` from the response since they are not used for the primary use case of this endpoint, and can be found in the attached source and destination objects.
2. Scope down the source portion of the response to only `sourceId`, `sourceName`, `name`, and `icon`.
3. Scope down the destination portion of the response to only `destinationId`, `destinationName`, `name`, and `icon`.
4. **The connectionConfiguration should be removed from the source and destination objects.**
5. [LOW] Remove `latestSyncJobCreatedAt` from the response. It's only used on Source and Destination list pages. This should be done after [getEntityTableData](https://github.com/airbytehq/airbyte/issues/19852) is migrated to the backend.

Depends on #20264, need to create PR against the branch in this PR.

### PR DESCRIPTION
**Pull request by gosusnp**
## What

Backend:
* Enable source/destination when querying connections
* Trim the response to contain what is being used by the FE

Resolves https://github.com/airbytehq/airbyte/issues/19849, https://github.com/airbytehq/airbyte/issues/19850, and https://github.com/airbytehq/airbyte/issues/20667

## How

Backend:
* Update API payload and ConfigRepository querying to support source/destination filtering
* Add new object for trimmed Source/Destination for the API response
* Removed a redundant db query to fetch schema changes

## Recommended reading order
1. ConfigRepository and WebBackendConnectionHandler contain most of the backend changes

## 🚨 User Impact 🚨
Faster load times

### CODE REVIEW

**Comment by gosusnp** [comment]
Note for the backend, we're running into some fairly coupled interfaces changes here, the idea is to add the frontend to this PR to avoid the extra API changes back and forth.

**Review by alovew — APPROVED** [review]

**Review by benmoriceau — APPROVED** [review]

**Comment by krishnaglick** [comment]
Vlad is taking the FE work here. We may need to add sourceDefinitionId and destinationDefinitionId back to the source and destination objects respectively, but waiting for Vlad to confir,

**Comment by krishnaglick** [comment]
I believe this PR should cover https://github.com/airbytehq/airbyte/issues/19850 too? Correct me if I'm wrong please!

**Comment by gosusnp** [comment]
@krishnaglick, yes both https://github.com/airbytehq/airbyte/issues/19849 and https://github.com/airbytehq/airbyte/issues/19850 are mentioned in the description.

**Comment by gosusnp** [comment]
@krishnaglick, @dizel852, I added `sourceDefinitionId` to `SourceSnippetRead` and `destinationDefinitionId` to `DestinationSnippetRead`.
Let me know if anything else is missing.

**Review by krishnaglick — APPROVED** [review]
Tested locally, LGTM!

**Pull request merged**
