### PR TITLE
Turn off default httpavailabilitystrategy for source-iterable (GA)

### PR DESCRIPTION
**Pull request by erohmensing**
See https://github.com/airbytehq/airbyte/pull/21888 for description

### CODE REVIEW

**Review by evantahler — APPROVED** [review]

**Comment by erohmensing** [comment]
Same errors as in #connector-health

**Comment by erohmensing** [comment]
/publish connector=connectors/source-iterable run-tests=false

**Comment by erohmensing** [comment]
Looking like run-tests=false is still running unit tests, which is why this one still fails 🤔

**Comment by erohmensing** [comment]
Tests were fixed here 🙌 https://github.com/airbytehq/airbyte/pull/22202

**Pull request merged**
