### PR TITLE
Source Gridly: add icon and make `grid_id` parameter required

### PR DESCRIPTION
**Pull request by hntan**
*Add icon for source-gridly*
*Mark grid_id as required field*

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@hntan can you sign the CLA or check the user you submit the change?

**Comment by hntan** [comment]
> @hntan can you sign the CLA or check the user you submit the change?

Signed, I was accidentally using my company email but login Github with personal account.

**Comment by hntan** [comment]
> @hntan would be possible to find a bigger icon?

Yes, added new bigger icon. Can you help to have a a look again?

**Review by marcosmarxm — APPROVED** [review]
Thanks

**Review by marcosmarxm — APPROVED** [review]
Thanks @hntan

**Pull request merged**
