### PR TITLE
🎉 New Source: Retently

### PR DESCRIPTION
**Pull request by subhash-kloudio**
## What
- Source connector for [Retently](https://www.retently.com/)
- Syncs customers, companies and reports from the SaaS application

## How
- HTTP API based source connector

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
  
- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

### CODE REVIEW

**Comment by subhash-kloudio** [comment]
Fixes https://github.com/airbytehq/hacktoberfest-2021/issues/66

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
sorry for the delay in review! some small changes. I'll try to run tests locally to validate the code. Thanks @subhash-kloudio

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Some comments, integration tests are working. After solving the comments we can merge this. Please make sure to resolve all problems when running `./gradlew format` there is some libs imported and not used.

**Review by marcosmarxm — APPROVED** [review]
LGTM! Great work @subhash-kloudio

**Pull request merged**
