### PR TITLE
Source Instagram: Update facebook-business from 18 version to 19

### PR DESCRIPTION
**Pull request by aldogonzalez8**
## What
Resolving [Source Instagram: Migrate connector to new 19 Graph API](https://github.com/airbytehq/airbyte-internal-issues/issues/6569)

## How
Updating `facebook-business = "==19.0.3"` in pyproject.toml and updating poetry.lock

Context:
The facebook-business Python library, also known as the Facebook Business SDK, is a tool provided by Facebook to help developers interact with various Facebook APIs, including the Instagram Graph API, Facebook Ads API, and more. This library enables developers to automate and manage their marketing campaigns, access business data, and interact with Facebook's and Instagram's services programmatically.

## User Impact
It shouldn't be affected. The current source Instagram connector uses Graph API 18, and there is no sunset date set for this version.

## Can this PR be safely reverted and rolled back?
- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by aldogonzalez8** [comment]
Unit and Integrations tests were completed.

image

**Comment by aldogonzalez8** [comment]
The API upgrade tool didn't show method changes for our app

image

**Comment by aldogonzalez8** [comment]
For the [live test results](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/manual/master/1716405542/5237a1f289560d6de4577714db791f8c4afe2230/source-instagram/3.0.8/output.html), I noticed that the Target URL still points to v18, probably because the connection selected was using that version? Not sure if there is a way to force to try with v19

image

Also, there are a few differences for TestDataIntegrity.test_all_records_are_the_same_with_state
image

@maxi297 @bazarnov, do you know if this is something to follow up on?

**Comment by aldogonzalez8** [comment]
Update: Thanks to @maxi297, who provided feedback on how to test locally the difference between both versions (18 vs. 19). I tested all the streams with a script that checked record count and record differences.

I used a script that @maxi297 designed to use local changes and a docker container with the latest current image of the source, in this case, Instagram.

I picked a few [connection ids from live tests](https://airbyte.metabaseapp.com/dashboard/2815-live-tests-connection-finder?connector_name_contains=instagram&connection_id_contains=&sync_mode=&stream=) connection finder as not everyone had data on every stream, there were minor differences like:

1. Normally, the fields that contain a URL (profile_picture_url, thumbnail_url, etc.) with static data that come from a CDN have a few params like "_nc_ohc" or "oh," which contain data related to the CDN itself, like cluster and server names, so even when two URLs look a little bit different, they contain the same information.
2. Other live data like Views, Likes, Plays could differ but the numbers were pretty similar and always the last resource in reading the endpoint was showing greater numbers than the other e.g. {'likes': '1254 != 1255', 'saved': '11 != 12'}

**Review by ChristoGrab — APPROVED** [review]
LGTM! Thanks for sharing the live-test report as well

**Pull request merged**
