### PR TITLE
🐛 Source Marketo: fix encoding error for Lead sync

### PR DESCRIPTION
**Pull request by CyprienBarbault**
## What
This is a fix for an issue I reported -> https://github.com/airbytehq/airbyte/issues/20641

When syncing Marketo lead, it appears that those with name containing non-latin character would make the sync fail.  In particular we have a Lead whose name is Vietnamese (cf https://en.wikipedia.org/wiki/Vietnamese_name for exemple names)

In fact, the response from the marketo API was being fall-backed to the default encoding `ISO-8859-1` instead of `utf-8`  (cf https://github.com/psf/requests/issues/5445#issuecomment-661654120)

## How
Forcing the encoding to `utf-8` fixed the issue

## Recommended reading order
1. `source.py`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

I'm not sure but I don't think so

## Pre-merge Checklist

<summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

## Tests

<details><summary><strong>Unit</strong></summary>

[unit_test_result.txt](https://github.com/airbytehq/airbyte/files/10338292/unit_test_result.txt)

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by koconder** [comment]
@CyprienBarbault hope you are well, thanks for your contribution. I’m one of the maintainers here at Airbyte. I'll take a look at your changes, please bear with me.

**Comment by CyprienBarbault** [comment]
@koconder Thank you for your help. What are the next steps  ?

**Comment by koconder** [comment]
@CyprienBarbault I’ll need to add some additional changes to your PR to add the version number increase and then run a few more checks, once this is all OK we will release alongside other changes. If Marketo connector is a GA connector I'll also get another code-reviewer to double check the work.

As its just after the holidays, just bear with us as we clear through the backlog 👍

**Comment by christo-olivier-sp** [comment]
We are encountering a similar issue. Our Marketo data ingest fails because we have non latin character names and this breaks the correct parsing of the CSV response to JSON.

This PR fixes the issue.

**Review by vincentkoc — APPROVED** [review]

**Comment by koconder** [comment]
Needs additional review from another airbyte reviewer as this is a connector in GA.

**Comment by evantahler** [comment]
@marcosmarxm this PR published a version of the connector, but it was never published, and it's causing trouble for https://github.com/airbytehq/airbyte/pull/22015

**Comment by marcosmarxm** [comment]
> 

It was published but not merged, probably this is causing the issue?
@erohmensing let me know if you need assistance here!

**Comment by erohmensing** [comment]
Yep, that's what's causing the issue. If tests are passing I'm happy to get it in before merging mine, but I also noticed that our #connector-health tests for this source started failing on the same date that it was published, and I'm not sure if it's related. Running the tests now to see what we get

**Review by erohmensing — APPROVED** [review]
To me this seems like a pretty innocuous change, and most likely not causing the issues seen in the tests, as they also appear on the master branch. I'm going to go ahead and get this merged so that the repo reflects whats available on docker hub. 

It's more complicated now that someone has already released a newer version, which is what I was trying to avoid - technically these changes aren't in 1.0.0. I'll try to make that reflected as much as possible

**Comment by erohmensing** [comment]
regular CI won't run on the fork due to lack of access to the PAT, but confirmed that the failure is the same on master, and formatting looks fine. Merging

**Pull request merged**
