### PR TITLE
 🎉 Python CDK: change minimum python version to 3.7.0

### PR DESCRIPTION
**Pull request by yaroslav-dudar**
## What
https://github.com/airbytehq/airbyte/issues/3578  Allow Python CDK to work with Python 3.7.X

## How
Updated python version in `setup.py`

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

## Recommended reading order
1. `setup.py`

### CODE REVIEW

**Review by sherifnada — APPROVED** [review]
great job looking for & updating the relevant docs. A couple more things we need to do to ensure that this works correctly: 

1. change `.github/workflows/publish-cdk.yaml` to use python 3.7.0 so we can test that this works correctly on the advertised version
2. bump the CDK version in setup.py
3. Using a version manager like [pyenv](https://github.com/pyenv/pyenv) verify that the tests work locally on this python version. You can run tests using `./type_check_and_test.sh`
4. if all looks good, push and comment `/publish-cdk` to do a dry run
5. if it succeeds publish with `dry-run=false` to publish to actual CDK
6. Update the changelog and follow any other steps in our [DoD](https://docs.google.com/document/d/1cVWEHqW1Q6oc9_yKkEqZft7-sf2HqCJOcnBJuS8ILfU/edit?usp=sharing)
7. merge this PR

PS: this should have gone to internal review first, but it LGTM so no worries 🙂

**Review by bazarnov — APPROVED** [review]

**Review by TymoshokDmytro — APPROVED** [review]

**Comment by yaroslav-dudar** [comment]
I see that python `3.7.0` is not available in `actions/setup-python@v2` . There is `3.7.1` but not `3.7.0` https://github.com/actions/python-versions/blob/main/versions-manifest.json

**Review by sherifnada — APPROVED** [review]

**Pull request merged**
