### PR TITLE
Edit secret input

### LINKED ISSUE #1695: Secrets record tab as password.
## Expected Behavior
* Using tab should bring me to the next field. 

## Current Behavior
* Instead it inserts Tab as password.

gif of the behavior (a little hard to tell from the gif, but i'm just hitting tab over and over again):
Screen Cast 2021-01-18 at 10 15 25 AM

corresponding http request made if i submit the form from the gif:
Screen Shot 2021-01-18 at 10 17 44 AM

### PR DESCRIPTION
**Pull request by jamakase**
Closes #1695

### CODE REVIEW

**Comment by Jamakase** [comment]
**Secret input** 
secret with btn


**Secret input when user click `edit` button**
secret

**Comment by cgardens** [comment]
i will try this out now!

**Review by cgardens — COMMENTED** [review]
Discussed offline. I'd like to try out the following flow. There is some concern that it might be a little overboard, but for now I think it the right thing because the other solutions we've had so far have not been that clear.

The flow I am thinking of:
1. when the user hits edit on a secrets field. two buttons appear on the right side "done" and "cancel"
2. when the user hits "done" the current state of the text field is kept. a message appears below it saying "for your changes to take effect, you must hit the 'save changes' button below".
3. when the user hits cancel the value reverts back to whatever it previously was.

the validation should still work the same as it does today. red with message if not passing validation and a user should not be able to hit done if it is not passing validation. they should be allowed to hit cancel.

**Review by cgardens — APPROVED** [review]
looks good. will follow up on the other bug i discussed in a separate issue.

**Pull request merged**
