### PR TITLE
Connectors: Fix AirbyteLogger() for source-google-ads, source-instagram, source-salesforce, source-s3

### PR DESCRIPTION
**Pull request by grubberr**
Signed-off-by: Sergey Chvalyuk <grubberr@gmail.com>

## Connectors:
source-google-ads
source-instagram
source-salesforce
source-s3

## What
Change deprecated `AirbyteLogger() -> logging.getLogger("airbyte")` for integration_tests
because `logging.getLogger("airbyte")` returns new logger which supports `extra` kwargs

### CODE REVIEW

**Comment by grubberr** [comment]
@brianjlai I decided to create less code  PR (then this https://github.com/airbytehq/airbyte/pull/14780) 
to fix logger problem for specific connectors

**Review by lazebnyi — APPROVED** [review]

**Review by brianjlai — APPROVED** [review]
change looks good!

**Pull request merged**
