### PR TITLE
Cleanup React Key error on Source and Destination Settings Pages

### PR DESCRIPTION
**Pull request by krishnaglick**
## What
React was spitting out an error about a lack of keys

## How
Add key

### CODE REVIEW

**Review by timroes — APPROVED** [review]
Code LGTM, have not tested locally.

**Review by dizel852 — APPROVED** [review]
LGTM
Not tested locally

**Comment by octavia-approvington** [comment]
Myomoto says it looks good <br/> thats a niiice

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
