### PR TITLE
🧹doc: update connectors README and remove acceptance-test-docker.sh

### PR DESCRIPTION
**Pull request by alafanechere**
## What
Relates to #30767
Our connectors README were stale because:
* Connectors are not built via docker build or (gradle for python connectors) anymore
* CAT is not run via docker run but wrapped into `airbyte-ci`, which makes its Dockerfile and `acceptance-test-docker.sh` script legacy

## How
* Remove all reference to Gradle from the python connector README
* Update README to reflect the up-to-date way of building/testing/publishing connectors
* Remove all `acceptance-test-docker.sh` scripts

### CODE REVIEW

**Comment by alafanechere** [comment]
Current dependencies on/for this PR:
* master
  * **PR #32209** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/32209" target="_blank">Graphite</a>  👈
    * **PR #32210** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/32210" target="_blank">Graphite</a> 
      * **PR #32211** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/32211" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/airbytehq/airbyte/32209?utm_source=stack-comment).

**Review by evantahler — APPROVED** [review]
Nice!
Is there a template we need to update as well?

**Comment by alafanechere** [comment]
> Nice!
Is there a template we need to update as well?

@evantahler https://github.com/airbytehq/airbyte/pull/32211

**Review by bazarnov — APPROVED** [review]

**Comment by octavia-approvington** [comment]
Check that box <br/> TODO complete

**Review by octavia-approvington — APPROVED** [review]

**Comment by AF414** [comment]
Looks like the [Iterable README](airbyte-integrations/connectors/source-iterable/README.md) got mixed up with the Coinmarketcap README? Happy to make a PR. just want to confirm.

**Comment by alafanechere** [comment]
@AF414 yes indeed! Sorry for this. Feel free to make the PR and ask a review from me.

**Pull request merged**
