### PR TITLE
🐛 Add method field on spec.json connectors (snowflake and postgres)

### LINKED ISSUE #3935: AWS S3 Staging for Snowflake Destinations not working correctly
## Expected Behavior
I expect that the connector would first drop the data ingestion to an S3 location then copy to the snowflake destination when complete.

## Current Behavior
When running data ingestion (from mySQL) data is working as if it is in "Standard Inserts" configuration. Also selecting the "AWS S3 Staging" configuration doesn't seem to be saving.

## More Information
AWS S3 Staging for the Snowflake Destination connector is not currently working. The proper information is added, all connection tests pass, but when running ingestion instead of the files being staged into S3 first THEN copied into snowflake, the regular "Standard Inserts" method is used instead. It seems like when selecting the "AWS S3 Staging" it just doesn't stick. If I select it, test connections (pass), go out then back into the Snowflake destination settings, the "Standard Inserts" is back as the default again.

## Steps to Reproduce
1. Set Up Snowflake Destination
2. Select AWS S3 Staging
3. Save configuration and exit
4. Go back into Snowflake Destination Settings
5. Notice that "AWS S# Staging has reverted BACK to "Standard Inserts"

## Severity of the bug for you
Medium

## Airbyte Version
Airbyte version: 0.24.4-alpha
airbyte/destination-snowflake:0.3.7
airbyte/source-mysql:0.3.5

### LINKED ISSUE #3950: EU-central-1 missing as S3 staging alternative in Snowflake connector
## Expected Behavior
When selecting Snowflake as destination, and "AWS S3 staging" as Loading Method, I would expect EU-central-1 as an alternative to choose from, as it is included in the documentation links to aws.

## Current Behavior
EU-central-1 is not a part of the selection list

## Steps to Reproduce
1. Select destinations
2. Put in Snowflake credentials
3. Select "AWS S3 staging" as loading method

## Severity of the bug for you
Very low

## Airbyte Version
0.24.7-alpha

## Connector Version (if applicable)
destination-snowflake

### PR DESCRIPTION
**Pull request by marcosmarxm**
## What
Closes #3935 and I took the opportunity to closes #3950 too

## How
Add `method` field when using `oneOf` property.

## Recommended reading order
1. `snowflake/spec.json`
2. `postres/spec.json`

## Pre-merge Checklist
Expand the checklist which is relevant for this PR.

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@jrhizor added you to evaluate if this change won't break back compatibility or if you have any suggestion about that.

**Comment by marcosmarxm** [comment]
Visiting the destination page after creating it.

### Snowflake
image


### Postgres
image

**Review by sherifnada — CHANGES_REQUESTED** [review]
@marcosmarxm concerned about backwards incompatibility. Will this break configs for existing users?

**Comment by marcosmarxm** [comment]
> @marcosmarxm concerned about backwards incompatibility. Will this break configs for existing users?

yes, we can remove `method` from being required but don't sure if this will ensure backwards incompatibility because we're using default values.

**Review by cgardens — APPROVED** [review]

**Comment by cgardens** [comment]
@sherifnada can you walk me through what will be backwards incompatible? That's actually a bit of a trick question, because my hunch is that given some of the nuance of when we validate we won't have backwards incompatibility issues.

Here's how I think it works (for better or for worse). If we find out what the truth is here, we can then document it (and iterate if we don't like the existing behavior. Below do not assume validation happens unless I explicitly say it.

## User creates / updates a connector 
* User enters configuration for connector
* FE validates it
* Sent to the API.
* API validates it.
* API saves it.

## Sync job runs
* config is fetched from db
* it is passed to the worker and executed (_no validation happens_)

So my hunch is that as long as the connector can run without the new field (which I think is true in this implementation), then already configured connectors will be fine.

**Comment by cgardens** [comment]
@marcosmarxm this makes sense to me! Thanks.

**Review by sherifnada — APPROVED** [review]
ty for the clarification marcos, shipit

**Review by michel-tricot — CHANGES_REQUESTED** [review]
it doesn't follow the convention we've been using so far to work around `oneof`

We need to be careful about this one as it is in spec.json. Meaning it becomes part of the connector iface.

**Comment by marcosmarxm** [comment]
> it doesn't follow the convention we've been using so far to work around `oneof`
> 
> We need to be careful about this one as it is in spec.json. Meaning it becomes part of the connector iface.

@michel-tricot could you check @cgardens https://github.com/airbytehq/airbyte/issues/3935#issuecomment-856925592. I think what I added **is** the workaround to deal with oneOf.

**Review by michel-tricot — APPROVED** [review]
Talked with @cgardens. 

Good with the hack for now but we need to fix it ASAP before we lose control of it.

**Pull request merged**
