### PR TITLE
🎉 Source Stripe: extend schema for events.request field

### LINKED ISSUE #8803: 🐛 Source stripe: events stream error parsing JSON
## Environment
- **Airbyte version**: 0.33.12-alpha
- **OS Version / Instance**: Amazon Linux 2
- **Deployment**: Kubernetes
- **Source Connector and version**: Stripe 0.1.23 
- **Destination Connector and version**: Snowflake 0.3.20 
- **Severity**: High
- **Step where error happened**: Sync Job

## Current Behavior
Events stream from the Strip connector fails with the following error while normalization:
```
normalization - 2021-12-15 01:55:22 INFO LineGobbler(voidCall):82 - 01:55:22 | 1 of 2 START table model STRIPE_EVENTS.EVENTS................................................................ [RUN]
normalization - 2021-12-15 01:55:24 INFO LineGobbler(voidCall):82 - 01:55:24 | 1 of 2 OK created table model STRIPE_EVENTS.EVENTS........................................................... [SUCCESS 1 in 1.73s]
normalization - 2021-12-15 01:55:24 INFO LineGobbler(voidCall):82 - 01:55:24 | 2 of 2 START table model STRIPE_EVENTS.EVENTS_REQUEST........................................................ [RUN]
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - 01:55:25 | 2 of 2 ERROR creating table model STRIPE_EVENTS.EVENTS_REQUEST............................................... [ERROR in 1.37s]
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - 01:55:25 | 
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - 01:55:25 | Finished running 2 table models in 4.83s.
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - 
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - Completed with 1 error and 0 warnings:
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - 
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - Database Error in model EVENTS_REQUEST (models/generated/airbyte_tables/STRIPE_EVENTS/EVENTS_REQUEST.sql)
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 -   100069 (22P02): Error parsing JSON: unknown keyword "req_OfvdWqHxblArvk", pos 19
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/STRIPE_EVENTS/EVENTS_REQUEST.sql
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - 
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
2021-12-15 01:55:27 INFO KubePodProcess(getReturnCode):591 - Exit code for pod normalization-sync-14397-2-krhgu is 1
```
## Expected Behavior
Events stream should be synced without errors

### PR DESCRIPTION
**Pull request by grubberr**
Signed-off-by: Sergey Chvalyuk <grubberr@gmail.com>

## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [x] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [x] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [x] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

### CODE REVIEW

**Review by annalvova05 — APPROVED** [review]

**Review by antixar — APPROVED** [review]
Looks good!
Please publish your changes.

**Comment by jagannathsrs** [comment]
Hey @grubberr , thanks for the quick fix! Although it does not seem to have resolved the issue. I changed the Stripe version to 0.1.26 and ran the sync and getting the same error again.

**Comment by grubberr** [comment]
Hello @jagannathsrs, is it possible you DROP all tables on snowflake and do full_refresh sync again?
I am not sure how it works if snowflake already has old tables with outdated structure.

**Comment by jagannathsrs** [comment]
That did not help as well, I even synced it to a new schema.

**Comment by jagannathsrs** [comment]
That and a schema_refresh from the UI worked. Apologies. 

Thank you again!

**Pull request merged**
