### PR TITLE
Source Amazon Seller Partner: add stream FbaReplacementsReports

### PR DESCRIPTION
**Pull request by monai**
## What

This PR adds stream `FbaReplacementsReports` (`GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_REPLACEMENT_DATA`).

In addition, the PR updates report generation status handling according to  (ProcessingStatuses)[https://developer-docs.amazon.com/sp-api/docs/reports-api-v2020-09-01-reference#processingstatuses] enum as follows:

`CANCELED` - log a warning message
`FAILED` - throw an exception

Before this PR, `FAILED` reports log warning messages and pretend that the report has 0 entries. Meanwhile, the documentation explicitly states that report wasn't generated:

> FATAL | The report was aborted due to a fatal error.
> -- | --

## How
*Describe the solution*

## Recommended reading order
1. `streams.py`

## 🚨 User Impact 🚨

The connector will throw an error for `FATAL` processing status while previously, the error was silently ignored.

#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated 
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

### CODE REVIEW

**Comment by marcosmarxm** [comment]
The code looks great @monai can you share the output from `./gradlew airbyte-integrations:connectors:source-amazon-sp:integrationTest`? You can disable the other reports and only run the one you'd added.

**Comment by monai** [comment]
```
connector_image: airbyte/source-amazon-seller-partner:dev
tests:
  spec:
    - spec_path: "source_amazon_seller_partner/spec.json"
  connection:
    # - config_path: "secrets/config.json"
    #   status: "succeed"
    #   timeout_seconds: 60
    - config_path: "integration_tests/invalid_config.json"
      status: "failed"
      timeout_seconds: 60
  discovery:
    - config_path: "secrets/config.json"
# TODO: uncomment when at least one record exist
  basic_read:
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog.json"
#      empty_streams:
#        [
#          "Orders",
#          "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL",
#          "GET_MERCHANT_LISTINGS_ALL_DATA",
#          "GET_FBA_INVENTORY_AGED_DATA",
#          "GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL",
#          "GET_FLAT_FILE_OPEN_LISTINGS_DATA",
#          "GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA",
#          "GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA",
#          "GET_VENDOR_INVENTORY_HEALTH_AND_PLANNING_REPORT",
#          "VendorDirectFulfillmentShipping",
#        ]
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog_brand_analytics_alternate_purchase.json"
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog_brand_analytics_item_comparison.json"
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog_brand_analytics_market_basket.json"
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog_brand_analytics_repeat_purchase.json.json"
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog_brand_analytics_search_terms.json"
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog_fba_fulfillment_customer_shipment_replacement_data.json"
# TODO: uncomment when Orders (or any other incremental) stream is filled with data
#  incremental:
#   - config_path: "secrets/config.json"
#     configured_catalog_path: "integration_tests/configured_catalog.json"
#     future_state_path: "integration_tests/future_state.json"
#     cursor_paths:
#       Orders: ["LastUpdateDate"]
#  full_refresh:
#   - config_path: "secrets/config.json"
#     configured_catalog_path: "integration_tests/configured_catalog.json"
```

```
Test session starts (platform: darwin, Python 3.9.10, pytest 6.1.2, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /Users/juozas/projects/lt/airbyte, configfile: pytest.ini
plugins: cov-2.12.1, sugar-0.9.4, mock-3.6.1, timeout-1.4.2
collecting ...
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_match_expected[inputs0] ✓                                                                                                8% ▉
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_required[inputs0] ✓                                                                                                     17% █▋
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_optional[inputs0] ✓                                                                                                     25% ██▌
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_has_secret[inputs0] ✓                                                                                                   33% ███▍
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_secret_never_in_the_output[inputs0] ✓                                                                                   42% ████▎
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_defined_refs_exist_in_json_spec_file[inputs0] ✓                                                                         50% █████
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_oauth_flow_parameters[inputs0] ✓                                                                                        58% █████▉
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestConnection.test_check[inputs0] ✓                                                                                                  67% ██████▋
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_discover[inputs0] ✓                                                                                                75% ███████▌
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_cursors_exist_in_schema[inputs0] ✓                                                                         83% ████████▍
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_refs_exist_in_schema[inputs0] ✓                                                                            92% █████████▎
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestBasicRead.test_read[inputs0] ✓                                                                                                   100% ██████████
============================================================================================================ short test summary info =============================================================================================================
SKIPPED [1] ../../bases/source-acceptance-test/source_acceptance_test/plugin.py:56: Skipping TestFullRefresh.test_sequential_reads because not found in the config
SKIPPED [1] ../../bases/source-acceptance-test/source_acceptance_test/plugin.py:56: Skipping TestIncremental.test_two_sequential_reads because not found in the config

Results (72.48s):
      12 passed
```

**Comment by alafanechere** [comment]
Hi @monai, the acceptance tests are failing because of some missing modules: https://github.com/airbytehq/airbyte/actions/runs/1791101084

**Comment by monai** [comment]
@alafanechere I've just merged master into this branch, recreated virtualenv, and run unit tests locally. Everything is fine. I guess this issue is related to CI environment.

However, it looks like #9768 broke the acceptance tests. See attached log. The PR was merged 12 days ago, and [the line in question](https://github.com/airbytehq/airbyte/blame/ea1ad99fe7e49c4e918adbcac0eba3fe4426bf0a/airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py#L654) is five months old.

```
~/projects/lt/airbyte/airbyte-integrations/connectors/source-amazon-seller-partner (amazon-sp-GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_REPLACEMENT_DATA) [m] python -m pytest -p integration_tests.acceptance        [.venv]
Test session starts (platform: darwin, Python 3.9.9, pytest 6.2.5, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /Users/juozas/projects/lt/airbyte, configfile: pytest.ini
plugins: sugar-0.9.4, mock-3.7.0, timeout-1.4.2
collecting ...
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_config_match_spec[inputs0] ✓                                                                     6% ▋
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_match_expected[inputs0] ✓                                                                       12% █▎
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_docker_env[inputs0] ✓                                                                           18% █▊
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_oneof_usage[inputs0] ✓                                                                          24% ██▍
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_required[inputs0] ✓                                                                             29% ██▉
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_optional[inputs0] ✓                                                                             35% ███▌
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_has_secret[inputs0] ✓                                                                           41% ████▎
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_secret_never_in_the_output[inputs0] ✓                                                           47% ████▊
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_defined_refs_exist_in_json_spec_file[inputs0] ✓                                                 53% █████▍
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_oauth_flow_parameters[inputs0] ✓                                                                59% █████▉
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestConnection.test_check[inputs0] ✓                                                                          65% ██████▌
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_discover[inputs0] ✓                                                                        71% ███████▏
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_cursors_exist_in_schema[inputs0] ✓                                                 76% ███████▋
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_refs_exist_in_schema[inputs0] ✓                                                    82% ████████▎
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_keyword_exist_in_schema[inputs0-allOf] ✓                                           88% ████████▉
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_keyword_exist_in_schema[inputs0-not] ✓                                             94% █████████▌

―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― TestDiscovery.test_primary_keys_exist_in_schema[inputs0] ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

self = <source_acceptance_test.tests.test_core.TestDiscovery object at 0x112dc6430>
discovered_catalog = {'GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL': AirbyteStream(name='GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL', json...fresh'>], source_defined_cursor=None, default_cursor_field=None, source_defined_primary_key=None, namespace=None), ...}

    def test_primary_keys_exist_in_schema(self, discovered_catalog: Mapping[str, Any]):
        """Check that all primary keys are present in catalog."""
        for stream_name, stream in discovered_catalog.items():
            for pk in stream.source_defined_primary_key or []:
                schema = stream.json_schema
                pk_path = "/properties/".join(pk)
                pk_field_location = dpath.util.search(schema["properties"], pk_path)
>               assert pk_field_location, f"One of the PKs ({pk}) is not specified in discover schema for {stream_name} stream"
E               AssertionError: One of the PKs (['labelData', 'packageIdentifier']) is not specified in discover schema for VendorDirectFulfillmentShipping stream
E               assert {}

../../bases/source-acceptance-test/source_acceptance_test/tests/test_core.py:218: AssertionError

 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_primary_keys_exist_in_schema[inputs0] ⨯                                                   100% ██████████
================================================================================================ short test summary info =================================================================================================
SKIPPED [1] ../../bases/source-acceptance-test/source_acceptance_test/plugin.py:56: Skipping TestBasicRead.test_read because not found in the config
SKIPPED [1] ../../bases/source-acceptance-test/source_acceptance_test/plugin.py:56: Skipping TestFullRefresh.test_sequential_reads because not found in the config
SKIPPED [1] ../../bases/source-acceptance-test/source_acceptance_test/plugin.py:56: Skipping TestIncremental.test_two_sequential_reads because not found in the config
FAILED ../../bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery::test_primary_keys_exist_in_schema[inputs0] - AssertionError: One of the PKs (['labelData', 'packageIdentifier']) is...

Results (13.75s):
      16 passed
       1 failed
         - airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py:211 TestDiscovery.test_primary_keys_exist_in_schema[inputs0]
````

**Comment by monai** [comment]
It turns out the current `primary_key` property in the stream `VendorDirectFulfillmentShipping` is flawed. It point's to a key of an object in an array of objects. It doesn't make any sense. So I fixed the error by setting the `primary_key = None`. In addition, the source data object [ShippingLabel](https://github.com/amzn/selling-partner-api-docs/blob/main/references/vendor-direct-fulfillment-shipping-api/vendorDirectFulfillmentShippingV1.md#shippinglabel) doesn't appear to have any uniquely identifying property, and the stream is full refresh, so `primary_key` isn't used at all.

**Comment by monai** [comment]
@alafanechere the PR is ready for review.

**Review by alafanechere — APPROVED** [review]

**Comment by alafanechere** [comment]
@monai, thanks again for this quality contribution! 🎉

**Pull request merged**
