### PR TITLE
Remove duplication in manifest, fix updated_at[gt] query param

### LINKED ISSUE #42883: [source-salesloft] incremental stream date format issue, error code 500
### Connector Name

source-salesloft

### Connector Version

1.2.11

### What step the error happened?

During the sync

### Relevant information

The jobs are lasting >120 hours, only "partially" succeeding, and I keep getting this error message:
`
Request URL: https://api.salesloft.com/v2/accounts?created_at%5Bgt%5D=2023-06-01T00%3A00%3A00Z&updated_at%5Bgt%5D=%7B%7B+%0A+++format_datetime%28%0A+++%28config%5B%27start_date%27%5D+if+stream_state%5B%27updated_at%27%5D+is+not+defined+else%0A+++%28stream_state.updated_at+if+stream_state.updated_at+%3C+now_utc%28%29+else+now_utc%28%29%29%29%2C+%0A+++%27%25Y-%25m-%25dT%25H%3A%25M%3A%25S.%25fZ%27%0A+++%29+%0A+%7D%7D&per_page=100, Response Code: 500, Response Text: {"status":500,"error":"Internal Server Error"}
`
reformatted:
`
https://api.salesloft.com/v2/accounts?created_at[gt]=2023-06-01T00:00:00Z&updated_at[gt]={{+
+++format_datetime(
+++(config['start_date']+if+stream_state['updated_at']+is+not+defined+else
+++(stream_state.updated_at+if+stream_state.updated_at+<+now_utc()+else+now_utc())),+
+++'%Y-%m-%dT%H:%M:%S.%fZ'
+++)+
+}}&per_page=100,ResponseCode:500,ResponseText:{"status":500,"error":"InternalServerError"}
`

Reached out to Salesloft Support who said "I suspect that the issue is due to how the date variable is being referenced in the API call. Can you verify that the variable set in this API call is being changed to a date/time value before being sent to Salesloft?"

image

### Relevant log output

```shell
2024-07-20 02:20:08 source > Giving up _send(...) after 5 tries (airbyte_cdk.sources.streams.http.exceptions.UserDefinedBackoffException: Request URL: https://api.salesloft.com/v2/accounts?created_at%5Bgt%5D=2023-06-01T00%3A00%3A00Z&updated_at%5Bgt%5D=%7B%7B+%0A+++format_datetime%28%0A+++%28config%5B%27start_date%27%5D+if+stream_state%5B%27updated_at%27%5D+is+not+defined+else%0A+++%28stream_state.updated_at+if+stream_state.updated_at+%3C+now_utc%28%29+else+now_utc%28%29%29%29%2C+%0A+++%27%25Y-%25m-%25dT%25H%3A%25M%3A%25S.%25fZ%27%0A+++%29+%0A+%7D%7D&per_page=100, Response Code: 500, Response Text: {"status":500,"error":"Internal Server Error"})
2024-07-20 02:20:08 source > Max retry limit reached. Request: <PreparedRequest [GET]>, Response: <Response [500]>
2024-07-20 02:20:08 source > Encountered an exception while reading stream accounts
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 237, in _read_stream
    for record_data_or_message in record_iterator:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/core.py", line 145, in read
    for record_data_or_message in records:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 120, in read_records
    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 324, in read_records
    for stream_data in self._read_pages(record_generator, self.state, _slice):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 288, in _read_pages
    response = self._fetch_next_page(stream_state, stream_slice, next_page_token)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 263, in _fetch_next_page
    return self.requester.send_request(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 460, in send_request
    response = self._send_with_retry(request, log_formatter=log_formatter)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 506, in _send_with_retry
    return backoff_handler(user_backoff_handler)(request, log_formatter=log_formatter)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 545, in _send
    raise UserDefinedBackoffException(backoff=custom_backoff_time, request=request, response=response)
airbyte_cdk.sources.streams.http.exceptions.UserDefinedBackoffException: Request URL: https://api.salesloft.com/v2/accounts?created_at%5Bgt%5D=2023-06-01T00%3A00%3A00Z&updated_at%5Bgt%5D=%7B%7B+%0A+++format_datetime%28%0A+++%28config%5B%27start_date%27%5D+if+stream_state%5B%27updated_at%27%5D+is+not+defined+else%0A+++%28stream_state.updated_at+if+stream_state.updated_at+%3C+now_utc%28%29+else+now_utc%28%29%29%29%2C+%0A+++%27%25Y-%25m-%25dT%25H%3A%25M%3A%25S.%25fZ%27%0A+++%29+%0A+%7D%7D&per_page=100, Response Code: 500, Response Text: {"status":500,"error":"Internal Server Error"}
2024-07-20 02:20:08 source > Marking stream accounts as STOPPED
2024-07-20 02:20:08 replication-orchestrator > Stream status TRACE received of status: INCOMPLETE for stream accounts
2024-07-20 02:20:08 replication-orchestrator > Sending update for accounts - RUNNING -> INCOMPLETE
2024-07-20 02:20:08 replication-orchestrator > Stream Status Update Received: accounts - INCOMPLETE
2024-07-20 02:20:08 source > Finished syncing accounts
2024-07-20 02:20:08 replication-orchestrator > Updating status: accounts - INCOMPLETE
2024-07-20 02:20:08 source > SourceSalesloft runtimes:
Syncing stream accounts 0:28:26.059568
```

### Contribute

- [ ] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by pabloescoder**
## What

Resolves https://github.com/airbytehq/airbyte/issues/42883 

- There was a lot of duplication in the manifest, the stream definitions were repeated, schemas were repeated, etc. This PR removes the duplication.
- Also fixes the updated_at[gt] query param which contained unnecessary verbose logic, since we're using incremental sync, I simplified the field value accordingly.

(Apologies for the large diff, there was a lot of duplication in the manifest.)

## How

Used the Builder to fix the manifest

## Review guide

1. manifest.yaml

## User Impact

No Impact

## Can this PR be safely reverted and rolled back?

- [x] YES 💚

### CODE REVIEW

**Review by ChristoGrab — COMMENTED** [review]
@pabloescoder Thanks for the contribution! Always happy to see a few thousand lines of duplicated code removed :D

One thing I'm not clear on is the changes specifically to incremental logic. I believe I grasp the issue with the overly verbose jinja logic in the query param, but it seems we've removed incremental components entirely from the manifest? I ran a round of regression tests and the [results do seem to indicate that all streams are now running in full refresh mode regardless of the declared sync mode](https://github.com/airbytehq/airbyte/actions/runs/12129188380/job/33817117902).

I also see that incremental acceptance tests are [explicitly commented out for this connector](https://github.com/airbytehq/airbyte/blob/68eb278c16a94e29fca5804e27fe5170144d4b84/airbyte-integrations/connectors/source-salesloft/acceptance-test-config.yml#L27), but I'm not sure if that's just a holdover from an earlier iteration.

**Comment by pabloescoder** [comment]
@ChristoGrab Incremental Sync shouldn't be entirely removed, I'll look into the manifest to see why every stream is running in full refresh. 
If I remember correctly, there were 15 incremental streams out of 29. 
As for the incremental sync acceptance tests, those were disabled in the prior version too, I didn't make any changes to that file. Should I enable those?

**Comment by pabloescoder** [comment]
@ChristoGrab The incremental block was already present in the manifest for incremental streams, the issue was that the sync mode was `full_refresh` and `overwrite` in the catalog even for incremental streams, so I changed those to `incremental` and `append`
Also, enabled incremental acceptance tests.

**Review by ChristoGrab — APPROVED** [review]
@pabloescoder Gotcha, thanks for the clarification! I think the size of the diff in the catalog may have also caused some issues with my search as I wasn't able to find any `incremental` components in the updated manifest when searching through the file. Was able to find them when inspecting the file directly though, and I've run some tests locally to verify the behavior. Regression tests are currently borked, but I think we're ok to merge with just CATs. Thanks again for your patience!

**Pull request merged**
