### PR TITLE
🐛 Source Facebook Marketing: add `complete_oauth_server_output_specification` to spec

### PR DESCRIPTION
**Pull request by arsenlosenko**
## What
Resolving this OC issue:
https://github.com/airbytehq/oncall/issues/2239
After changes made previously [here](https://github.com/airbytehq/airbyte/pull/26941), some users were not able to use connector properly due to missing entry in `advanced_auth` declaration.

## How
Update `advanced_auth` declaration in spec and add `complete_oauth_server_output_specification` entry.

### CODE REVIEW

**Comment by arsenlosenko** [comment]
/publish connector=connectors/source-facebook-marketing pre-release=true run-tests=false

**Comment by arsenlosenko** [comment]
/legacy-publish connector=connectors/source-facebook-marketing pre-release=true run-tests=false

**Review by lazebnyi — APPROVED** [review]

**Review by girarda — APPROVED** [review]

**Comment by bnchrch** [comment]
@arsenlosenko It looks like `source_facebook_marketing/source.py` needs to be run through the formatter.

Let me know if you need a hand with that :)

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`7a71a0cad6`](https://github.com/airbytehq/airbyte/pull/27201/commits/7a71a0cad6fe76e30f88902fb20f6f590e823145)) - ❌

⏲️  Total pipeline duration: 4827 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check.                                                  | ✅        |
| Connector version increment check.                                               | ✅        |
| QA checks                                                                        | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5270987184)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by alafanechere** [comment]
@arsenlosenko please do not use /legacy-publish to publish pre-release connector as the build logic is different now. What you publish with /legacy-test might not match what eventually gets published. 
Please use [this workflow](https://github.com/airbytehq/airbyte/actions/workflows/publish_connectors.yml) on your branch.

**Comment by arsenlosenko** [comment]
@alafanechere understood, thanks for pointing that out

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`3ceb09dc09`](https://github.com/airbytehq/airbyte/pull/27201/commits/3ceb09dc09ff16f55037f0cb5ab29749aeb0c15e)) - ✅

⏲️  Total pipeline duration: 3451 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check.                                                  | ✅        |
| Connector version increment check.                                               | ✅        |
| QA checks                                                                        | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5276131050)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Pull request merged**
