### PR TITLE
Fix bq standard mode

### PR DESCRIPTION
**Pull request by benmoriceau**
## What
the standard mode of Big Query was only emitting the last state. It is failing with a per stream state because the aggregated state was partial.

This is emitting all the state that will then be aggregated by the destination lifecycle manager.

more context can be found in:
- https://airbytehq-team.slack.com/archives/C03AS1GAQV6/p1659377818820729
- https://github.com/airbytehq/oncall/issues/382

### CODE REVIEW

**Review by grishick — APPROVED** [review]

**Review by tuliren — APPROVED** [review]

**Review by jdpgrailsdev — APPROVED** [review]
:shipit: @benmoriceau  The Mongo DB destination has the exact same code (https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-mongodb/src/main/java/io/airbyte/integrations/destination/mongodb/MongodbRecordConsumer.java#L68).  Should we update that as part of this PR or are you planning on doing a separate PR for that connector?

**Comment by benmoriceau** [comment]
> :shipit: @benmoriceau The Mongo DB destination has the exact same code (https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-mongodb/src/main/java/io/airbyte/integrations/destination/mongodb/MongodbRecordConsumer.java#L68). Should we update that as part of this PR or are you planning on doing a separate PR for that connector?

I'll do it in another PR in order to fix the OC first.

**Comment by benmoriceau** [comment]
> /test connector=connectors/destination-bigquery
> 
> > 🕑 connectors/destination-bigquery https://github.com/airbytehq/airbyte/actions/runs/2778782105
> > ✅ connectors/destination-bigquery https://github.com/airbytehq/airbyte/actions/runs/2778782105
> > Python tests coverage:
> 
> ```
> Name                                                              Stmts   Miss  Cover
> -------------------------------------------------------------------------------------
> normalization/transform_config/__init__.py                            2      0   100%
> normalization/transform_catalog/reserved_keywords.py                 13      0   100%
> normalization/transform_catalog/__init__.py                           2      0   100%
> normalization/destination_type.py                                    13      0   100%
> normalization/__init__.py                                             4      0   100%
> normalization/transform_catalog/destination_name_transformer.py     157      8    95%
> normalization/transform_catalog/table_name_registry.py              174     34    80%
> normalization/transform_config/transform.py                         168     34    80%
> normalization/transform_catalog/utils.py                             51     14    73%
> normalization/transform_catalog/dbt_macro.py                         22      7    68%
> normalization/transform_catalog/catalog_processor.py                147     80    46%
> normalization/transform_catalog/transform.py                         61     38    38%
> normalization/transform_catalog/stream_processor.py                 589    394    33%
> -------------------------------------------------------------------------------------
> TOTAL                                                              1403    609    57%
> ```
> 
> > 
> 
> ### Build Passed
> Test summary info:
> 
> ```
> All Passed
> ```

It was meant to be a publish, I ran the wrong command yesterday evening 🤦

**Comment by benmoriceau** [comment]
/publish connector=connectors/destination-bigquery-denormalized

**Pull request merged**
