### PR TITLE
Normalization - BigQuery use `json_extract_string_array` for array of simple types

### LINKED ISSUE #13154: :bug: Destination BigQuery : normalization incorrectly processes arrays
## Current Behavior
The normalization surrounds all incoming values by brackets `"` and then fails or stores it as surrounded text. 

#### Test data: [data_type_array_test_messages.txt](https://github.com/airbytehq/airbyte/files/8766131/data_type_array_test_messages.txt)

1. Date fail example:
The result column contains a normalization error instead of data. The root cause of the error is that value is surrounded by brackets.
Screenshot from 2022-05-24 23-50-41

2. Text example:
The value is double surrounded by brackets which leads to an error when you read this data.
Screenshot from 2022-05-24 23-52-54

### PR DESCRIPTION
**Pull request by grubberr**
Signed-off-by: Sergey Chvalyuk <grubberr@gmail.com>

## What
For array extraction use better BigQuery json function
```
json_extract_array -> json_extract_string_array
```

it produce correct strings inside array
before:
```
['"2022-11-22T01:23:45+05:00"', '"9999-12-21T01:23:45-05:00"']
```
after:
```
['2022-11-22T01:23:45+05:00', '9999-12-21T01:23:45-05:00']
```

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Review by DoNotPanicUA — APPROVED** [review]

**Review by evantahler — CHANGES_REQUESTED** [review]
Nice work!

Date parsing is evil - please add a test (maybe [here](airbyte-integrations/connectors/source-bigquery/src/test-integration/java/io/airbyte/integrations/source/bigquery/BigQuerySourceDatatypeTest.java)) to show that the example from the description really does work:

before:
```
['"2022-11-22T01:23:45+05:00"', '"9999-12-21T01:23:45-05:00"']
```
after:
```
['2022-11-22T01:23:45+05:00', '9999-12-21T01:23:45-05:00']
```

**Comment by evantahler** [comment]
There may be a similar issue with Postgres as well - https://github.com/airbytehq/airbyte/issues/13380

**Review by evantahler — APPROVED** [review]
Ah, got it. The A/B Test makes sense now that I know the 'date' part isn't included

**Comment by DoNotPanicUA** [comment]
The PR is about the Destination fix.
But also include a small fix for source tests. The destination cases including dates and all other possible values are tested by DAT (Destination Acceptance Test).
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/standard-destination-test/src/main/resources/data_type_array_test_messages.txt
Here you can find test data for arrays and checked values.

**Review by evantahler — APPROVED** [review]

**Comment by grubberr** [comment]
I cannot PASS tests because writing to MSSQL failed on network for some reason
```
Connection is not available, request timed out after 60001ms.
```
https://github.com/airbytehq/airbyte/runs/6825088834?check_suite_focus=true#step:17:8426

I CAN pass this test on local machine

publishing without tests

**Comment by evantahler** [comment]
Working on fixing normalization here https://github.com/airbytehq/airbyte/pull/13693

**Comment by bazarnov** [comment]
Hi, guys, this change seems to break DAT test for Redshift, Snowflake, Postgres, since there is no `JSON_EXTRACT_ARRAY` function in these databases, but the default macro applies it to all other except of BigQuery, please take a look everyone involved into the change. 
Here is the Issue created based on all above:
https://github.com/airbytehq/airbyte/issues/13875

**Pull request merged**
