### PR TITLE
p0-stripe-schema-broken - revert stripe to 3.15.0

### PR DESCRIPTION
**Pull request by maxi297**

### CODE REVIEW

**Review by sherifnada — APPROVED** [review]

**Comment by octavia-approvington** [comment]
Trying to merge your PR using a bot?
Comment this on the PR:
```
/approve-and-merge reason="<STATE YOUR REASON HERE>"
```
Make sure you've reviewed the [docs](https://internal-docs.airbyte.io/How-Tos/Overriding-PR-Merge-Rules)!

**Comment by octavia-approvington** [comment]
This code is at peace with itself <br/> imagine karate kid approving

**Review by octavia-approvington — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`1a8f46c91b`](https://github.com/airbytehq/airbyte/pull/28820/commits/1a8f46c91b6d481616aa4f106c66b2f4f021c978)) - ✅

⏲️  Total pipeline duration: 12mn28s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297_p0-stripe-schema-broken/1690504233/1a8f46c91b6d481616aa4f106c66b2f4f021c978/source-stripe/3.17.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Pull request merged**
