### PR TITLE
Destination BigQuery - remove file_buffer_count

### LINKED ISSUE #32275: Destination BigQuery - remove file_buffer_count

### PR DESCRIPTION
**Pull request by evantahler**
The config option `file_buffer_count` doesn't matter now that these destinations have been async'd.  Let's remove it!

Closes https://github.com/airbytehq/airbyte/issues/32275

### CODE REVIEW

**Review by edgao — APPROVED** [review]

**Comment by evantahler** [comment]
@cynthiaxyin I ran a number of the failing redshift tests locally and they seem to be OK... is this flaky test behavior expected for destination-redshift?

Note: to run the DATs locally, you'll need to change `useLocalCdk = true` in redshift's gradlefile and then tell InteliJ to "reload all gradle projects"

**Comment by cynthiaxyin** [comment]
@evantahler Hmm I'm not sure I haven't run destination-redshift tests recently.

**Comment by evantahler** [comment]
@tryangul or @benmoriceau - can you confirm that `getSerializedMessageConsumer()` should not be used by Redshift any more?  Things are compiling, and most of the tests pass, but the flakiness of the tests is giving me pause

**Comment by tryangul** [comment]
@evantahler Last I was in this code `getSerializedMessageConsumer` was the code that setup the async destination and was a critical piece. Is there a new a new path to trigger this? I'm spelunking around right now, but it's been a while since I've been in here.

**Comment by evantahler** [comment]
Ok, I'm scoping this PR down to be just bigquery changes, as those tests are passing

**Review by edgao — APPROVED** [review]

**Pull request merged**
