### PR TITLE
update snowflake normalization test output

### PR DESCRIPTION
**Pull request by edgao**
## What
There's been some drift here. Ran the snowflake integration tests locally on master; this was the diff.

### CODE REVIEW

**Comment by ChristopheDuong** [comment]
drift seems to be due to merging a contributor's PR: #7620

**Comment by edgao** [comment]
integration tests look happy at least; regenerated some of the destinations.

Had trouble getting mysql/mssql/oracle normalization integration tests to run locally, so haven't regenerated those. Will try and figure them out tomorrow. (error is some sort of timeout when connecting to the DB)

**Comment by edgao** [comment]
closing in favor of https://github.com/airbytehq/airbyte/pull/9072

**Pull request closed without merging**
