### PR TITLE
🐛 Destination Databricks: handle optional and object types in input schema (azure only)

### PR DESCRIPTION
**Pull request by IgSaf**
## What
Resolving (only Azure):
- https://github.com/airbytehq/airbyte/issues/21193

It is a fix for the situation when the types in input streams are specified with arrays.
For example, schema for the input stream from `google ads` source looks like
```
{"type":"object","$schema":"http://json-schema.org/draft-07/schema#","properties":{"campaign.id":{"type":["integer","null"]},"campaign.name":{"type":["string","null"]},"segments.date":{"type":["string","null"],"format":"date"},"metrics.clicks":{"type":["integer","null"]},"metrics.conversions":{"type":["number","null"]},"metrics.cost_micros":{"type":["integer","null"]},"metrics.impressions":{"type":["integer","null"]},"user_location_view.country_criterion_id":{"type":["integer","null"]}},"additionalProperties":true}
```
As a result, the below line of code gains empty string.
```(java)
final String type = node.get("type").asText()
```
And "CREATE TABLE" statement is formed without types and therefore incorrect.
Simplified example
```(sql)
CREATE TABLE <table> (_airbyte_ab_id string, _airbyte_emitted_at string, `campaign.id` , `metrics.clicks` , `segments.date`) USING csv LOCATION '<location>' options ("header" = "true", "multiLine" = "true")
```

## How
- for optional input types (e.g. optional string: `["string", "null"]`) it would be `string` (databricks treats it optional as default anyway).
- for an input `object` type the function will fall back to a `string` type.
- fallback for any other cases - `string`

Without `escape` option set to `"`, a column with an input `object` type will have double quotes (e.g. `"{""key"": ""val""}"`) in the target table.

## Pre-merge Checklist

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

</details>

## Tests
Currently Azure Databricks tests are disabled with no cluster for them, so I launched my own cluster and made sure all tests pass.
I have not committed changes to the current tests because that could get impactful (I am just choosing a tool for data ingestion).

### CODE REVIEW

**Comment by IgSaf** [comment]
I have no idea why the "Report connectors dependency" has failed.
Quick search though the failed action [Readme](https://github.com/marketplace/actions/create-or-update-comment) tells

> Note: In public repositories this action does not work in pull_request workflows when triggered by forks. Any attempt will be met with the error, Resource not accessible by integration. This is due to token restrictions put in place by GitHub Actions. Private repositories can be configured to [enable workflows](https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#enabling-workflows-for-private-repository-forks) from forks to run without restriction. See [here](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#restrictions-on-repository-forks) for further explanation. Alternatively, use the [pull_request_target](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) event to comment on pull requests.

I believe this is the case and it will pass if the PR will be created with a branch in this repository

**Comment by MoritzLampert** [comment]
Hi,
thank you for your fast fix. I just tried it and I get another error now: 
```
== SQL ==
CREATE TABLE public._airbyte_tmp_ubg_flights (_airbyte_ab_id string, _airbyte_emitted_at string, `ActualElapsedTime` double, `AirTime` double, `Airline` string, `ArrDel15` double, `ArrDelay` double, `ArrDelayMinutes` double, `ArrTime` double, `ArrTimeBlk` string, `ArrivalDelayGroups` double, `CRSArrTime` integer, `CRSDepTime` integer, `CRSElapsedTime` double, `Cancelled` boolean, `DOT_ID_Marketing_Airline` integer, `DOT_ID_Operating_Airline` integer, `DayOfWeek` integer, `DayofMonth` integer, `DepDel15` double, `DepDelay` double, `DepDelayMinutes` double, `DepTime` double, `DepTimeBlk` string, `DepartureDelayGroups` double, `Dest` string, `DestAirportID` integer, `DestAirportSeqID` integer, `DestCityMarketID` integer, `DestCityName` string, `DestState` string, `DestStateFips` integer, `DestStateName` string, `DestWac` integer, `Distance` double, `DistanceGroup` integer, `DivAirportLandings` double, `Diverted` boolean, `FlightDate` string, `Flight_Number_Marketing_Airline` integer, `Flight_Number_Operating_Airline` integer, `IATA_Code_Marketing_Airline` string, `IATA_Code_Operating_Airline` string, `Marketing_Airline_Network` string, `Month` integer, `Operated_or_Branded_Code_Share_Partners` string, `Operating_Airline` string, `Origin` string, `OriginAirportID` integer, `OriginAirportSeqID` integer, `OriginCityMarketID` integer, `OriginCityName` string, `OriginState` string, `OriginStateFips` integer, `OriginStateName` string, `OriginWac` integer, `Quarter` integer, `Tail_Number` string, `TaxiIn` double, `TaxiOut` double, `WheelsOff` double, `WheelsOn` double, `Year` integer, `__index_level_0__` integer, `_ab_additional_properties` object, `_ab_source_file_last_modified` string, `_ab_source_file_url` string) USING csv LOCATION 'abfss:REDACTED_LOCAL_PART@REDACTED.dfs.core.windows.net/REDACTED/public/_airbyte_tmp_ubg_flights/' options ("header" = "true", "multiLine" = "true")
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^^^
	at org.apache.spark.sql.errors.QueryParsingErrors$.dataTypeUnsupportedError(QueryParsingErrors.scala:249)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.$anonfun$visitPrimitiveDataType$1(AstBuilder.scala:3006)
	at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:169)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.visitPrimitiveDataType(AstBuilder.scala:2976)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.visitPrimitiveDataType(AstBuilder.scala:69)
```
There is no `object` datatype in Spark, so this datatype probably needs to be converted to some kind of [complex type](https://spark.apache.org/docs/latest/sql-ref-datatypes.html).

**Comment by IgSaf** [comment]
Thank you for your example.

I see two options:
- write some clever parser that will be able to convert complex types to databricks representation
- put another `if` and cast a value to `string`

I will implement the second because it is faster and safer (though uglier)

**Comment by IgSaf** [comment]
@natalyjazzviolin The code works, but actions fail because the branch from my fork and not in this repository. Can I do anything about it?

**Comment by evantahler** [comment]
@IgSaf can you rebase and fix the merge conflicts please?

**Comment by IgSaf** [comment]
The Databrics connector is in the beta now and stores all the data in one column, so these changes are not relevant anymore.

**Pull request closed without merging**
