### PR TITLE
:bug: fixed OOM error when splitting a stream into several files

### LINKED ISSUE #5277: Out of memory error when using S3 as staging storage for Snowflake
## Enviroment
- **Airbyte version**:  example is 0.29.1-alpha
- **OS Version / Instance**: t2.xlarge
- **Deployment**: Docker
- **Source Connector and version**: MySQL 0.4.0
- **Destination Connector and version**: Snowflake 0.3.11
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
Enabling AWS S3 staging for the Snowflake destination results in out of memory errors. Standard inserts work but a 12 GB sync takes 3+ hours.

## Expected Behavior
MySQL to Snowflake sync with S3 as staging storage works and is faster than standard inserts.

## Logs

<details>
<summary>LOG</summary> 

[logs-sugar-s3.txt](https://github.com/airbytehq/airbyte/files/6955004/logs-sugar-s3.txt)

</details>

## Steps to Reproduce
1. Set up MySQL source with large database (12 GB)
2. Set up Snowflake destination with S3 as staging
3. Sync

## Are you willing to submit a PR?
No

### LINKED ISSUE #5664: AWS S3 Staging COPY is writing records from different table in the same raw table
## Enviroment
- **Airbyte version**:  0.29.11-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: MySQL 0.4.3
- **Destination Connector and version**: Snowflake 0.3.12
- **Severity**: Critical
- **Step where error happened**: Sync

## Current Behavior
in the `_AIRBYTE_RAW_MYTABLE` i am seeing json blobs in `_AIRBYTE_DATA` column that are pertaining to two different tables.

i can give two examples where this happens. both of which have similar table names
e.g.
* `user` and `user_invites` tables
* `entrydispute` and `entrydisputeevent` tables

in the first table, there are JSON blobs with schemas pertaining to the second table. and so the resulting `_scd` and final tables contain NULL records because `_AIRBYTE_RAW_USER` has a record (row) with raw json data having the schema of `_AIRBYTE_RAW_USER_INVITES` and so the columns in this raw (in the final `_scd` and final table) are NULL because that row doesn't have any data with columns relating to the original table.

It appears that the AWS S3 Staging COPY is copying data from one table into the other

## Expected Behavior
Each table should have `_AIRBYTE_RAW_<TABLE>` with _only_ that table's data

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1. I am not entirely sure. I have modified connectors to use standard and then S3 staging (changing this feature back and forth) as well as CDC vs standard (changing this feature back and forth)
2. I have re-used the same source for different connections (and different tables)
3. I have made two of the same connections (one using standard and the other using S3 staging)

## Are you willing to submit a PR?

Remove this with your answer.

### PR DESCRIPTION
**Pull request by andriikorotkov**
## What
AWS S3 Staging COPY is writing records from different table in the same raw table

## How
It is optimal to write every 10,000,000 records to a new file. This will make it easier to work with files and speed up the recording of large amounts of data. In addition, for a large number of records, we will not get a drop in the copy request to QUERY_TIMEOUT when the records from the file are copied to the staging table.

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Comment by andriikorotkov** [comment]
@tuliren, you are right, this is not entirely true. I saw that contributors in the troubleshooting group had an OOM error at this point. I tested this again with a lot of data (as you can see it in the screenshots) and fixed it in no time. If you have time, I would like to know your opinion on this fix and get any remarks from you.

**Review by alexandr-shegeda — APPROVED** [review]

**Review by tuliren — CHANGES_REQUESTED** [review]

**Review by tuliren — APPROVED** [review]
I separated the filename generation logic to its own class, `StagingFilenameGenerator`, so that the logics can be unit tested. It turns out that there was an off-by-one bug in the original code, which has been fixed now.

**Pull request merged**
