### PR TITLE
destination-s3-glue: build against latest CDK

### PR DESCRIPTION
**Pull request by stephane-airbyte**
## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by stephane-airbyte** [comment]
* **#47201** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/47201?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @stephane-airbyte and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by blarghmatey** [comment]
The current patch is erroring during the build with the following stderr output:
```
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.6/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build 
> Task :buildSrc:extractPluginRequests FROM-CACHE
> Task :buildSrc:generatePluginAdapters FROM-CACHE
> Task :buildSrc:compileJava FROM-CACHE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:compileGroovyPlugins FROM-CACHE
> Task :buildSrc:pluginDescriptors
> Task :buildSrc:processResources
> Task :buildSrc:classes
> Task :buildSrc:jar
> Task :airbyte-integrations:connectors:destination-s3-glue:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :airbyte-integrations:connectors:destination-s3-glue:compileKotlin NO-SOURCE
> Task :airbyte-integrations:connectors:destination-s3-glue:compileJava

> Task :airbyte-integrations:connectors:destination-s3-glue:compileJava FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.6/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
8 actionable tasks: 4 executed, 4 from cache

Publishing build scan...
https://gradle.com/s/zmppv3toaq43w

```

**Comment by blarghmatey** [comment]
@stephane-airbyte is this ready to be reviewed and merged?

**Comment by blarghmatey** [comment]
@stephane-airbyte just following up to see if this is still on track to get merged to master? Is there anything else that's needed to move it from draft mode?

**Review by blarghmatey — APPROVED** [review]

**Review by edgao — APPROVED** [review]

**Comment by octavia-approvington** [comment]
Merged using the approve bot.

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
