### PR TITLE
Include tcp port in Clickhouse destination configuration for normalization

### PR DESCRIPTION
**Pull request by ChristopheDuong**
## What
Follow-up to https://github.com/airbytehq/airbyte/pull/9072

destination-clickhouse uses HTTP port
normalization-clickhouse uses TCP port

see slack thread: https://airbytehq.slack.com/archives/C01MFR03D5W/p1641468681019500?thread_ts=1641461068.011100&cid=C01MFR03D5W

## How
Both ports should be declared in destination configuration

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

#### Community member or Airbyter
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated 
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [x] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [x] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [x] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [x] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [x] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

### CODE REVIEW

**Review by marcosmarxm — APPROVED** [review]

**Comment by marcosmarxm** [comment]
@ChristopheDuong Clickhouse normalization is not working from the connector tests?

**Comment by ChristopheDuong** [comment]
> @ChristopheDuong Clickhouse normalization is not working from the connector tests?

I also tried to enable the custom dbt for clickhouse but it didn't work out so I disabled it and the tests are passing now.

I can't seem to be able to run the acceptance tests locally with clickhouse to have more details on the failure though

**Comment by ChristopheDuong** [comment]
Will publish normalization in another PR

**Pull request merged**
