### PR TITLE
✨ Source Asana: Add Portfolios stream

### LINKED ISSUE #16804: Source Asana: new stream Portfolios
## Tell us about the problem you're trying to solve
A portfolio gives a high-level overview of the status of multiple initiatives in Asana. Portfolios provide a dashboard overview of the state of multiple projects, including a progress report and the most recent [status update](https://developers.asana.com/docs/asana-statuses). Portfolios have some restrictions on size. Each portfolio has a max of 500 items and, like projects, a max of 20 custom fields.

## Describe the solution you’d like
Research pros and cons for implemting this stream.
Depending on your roles witihin Asana you may have no access to this stream:
image

### PR DESCRIPTION
**Pull request by topefolorunso**
## What
Add Asana Portfolios stream resolves #16804

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by sajarin** [comment]
@topefolorunso According to the Asana [docs](https://developers.asana.com/reference/getportfolios), this endpoint requires an owner field to passed into the request to successfully fetch records, currently the read command for this stream is not working, can you look into fixing this?

**Comment by topefolorunso** [comment]
> @topefolorunso According to the Asana [docs](https://developers.asana.com/reference/getportfolios), this endpoint requires an owner field to passed into the request to successfully fetch records, currently the read command for this stream is not working, can you look into fixing this?

Not sure about this @sajarin. Only the workspace parameter is required. If the owner parameter is not specified, all portfolios under the workspace will be returned. This is according to the asana docs.

image

**Comment by sajarin** [comment]
@topefolorunso I tested the request myself using the api explorer and the api errors out with "owner" value is missing. This is also causing the integration tests to fail in the linked PR. If you don't believe me, you can try simulating a request yourself to the API using credentials. 

Either way, the current implementation of the stream is broken.

**Comment by sajarin** [comment]
Any update here @topefolorunso?

**Comment by topefolorunso** [comment]
> Any update here @topefolorunso?

apologies @sajarin , got caught up with other issues. I'm trying to see the best way we can get the owner value for the stream - stream to partition from or from config

**Comment by sajarin** [comment]
@topefolorunso this should most likely be fetched from a stream slice, let me know if you're able to continue working on this

**Comment by topefolorunso** [comment]
> @topefolorunso this should most likely be fetched from a stream slice, let me know if you're able to continue working on this

@sajarin Yes I can continue working on this. But one issue, what stream will I slice from? I was thinking the `Users` stream and the `gid` property of the stream, but I don't see anywhere in the API documentation where it states that this property maps with the owner parameter we need.

**Review by sajarin — APPROVED** [review]

**Pull request merged**
