### PR TITLE
1s1t: move expected records into destination-bigquery

### PR DESCRIPTION
**Pull request by edgao**
this is step 1 of addressing https://github.com/airbytehq/airbyte/issues/28636

step 2 is to copy these files into https://github.com/airbytehq/airbyte/pull/28677 + edit them to have microseconds precision in timestamps

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery-denormalized test report (commit [`b46615876b`](https://github.com/airbytehq/airbyte/pull/28752/commits/b46615876bb0b44ae65941c634111dc7e42cd516)) - ✅

⏲️  Total pipeline duration: 25mn12s 

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ✅        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-bigquery-denormalized docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery-denormalized:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_1s1t_expected_records_per_destination/1690405615/b46615876bb0b44ae65941c634111dc7e42cd516/destination-bigquery-denormalized/1.5.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

**Review by evantahler — APPROVED** [review]
Screenshot 2023-07-26 at 2 58 38 PM
lol, thanks Github

I think you are moving the test fixtures into the destination's directory.  Yay!

**Comment by edgao** [comment]
github pls

yeah these are all no-change renames from `base-typing-deduping-test` to `destination-bigquery`, e.g. 
`renamed: airbyte-integrations/bases/base-typing-deduping-test/src/main/resources/sync1_expectedrecords_dedup_final.jsonl ⟶   airbyte-integrations/connectors/destination-bigquery/src/test-integration/resources/sync1_expectedrecords_dedup_final.jsonl`

image

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`b46615876b`](https://github.com/airbytehq/airbyte/pull/28752/commits/b46615876bb0b44ae65941c634111dc7e42cd516)) - ✅

⏲️  Total pipeline duration: 43mn02s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_1s1t_expected_records_per_destination/1690405615/b46615876bb0b44ae65941c634111dc7e42cd516/destination-bigquery/1.5.7/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Pull request merged**
