### PR TITLE
🐛  Source Intercom: switching from scroll to standard endpoints

### PR DESCRIPTION
**Pull request by antixar**
## What
At same time companies' "scroll" logic can be used by one script only. 
OnCall https://github.com/airbytehq/oncall/issues/39

## How
Implementation of the following new hybrid logic:
1) Initially the stream `companies` tries to load data by "scroll" endpoints.
2) try to wait a "scroll" request  within a minute (3 attempts with delay 20,5 seconds) if "stroll" is busy by another script
3) switch to using of the "standard" endpoint.

## Recommended reading order
1. `x.java`
2. `y.python`

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

### CODE REVIEW

**Review by sherifnada — APPROVED** [review]
it may make things a little faster to first request the non-scroll endpoints, read the `total_count` field and if `>=10k` then use the scroll endpoint, but not a significant improvement over this logic here.

**Comment by antixar** [comment]
@sherifnada ,
The main problem is to the "scroll" endpoint can be busy by another script permanently. In such cases we have to use "non-scroll" one only no matter total_count value. My implementation has one flaw that sometimes the connector will force to wait 1 minute for switching to another endpoints.

**Comment by antixar** [comment]
/publish connector=connectors/source-intercom run-tests=false

**Comment by antixar** [comment]
was published without tests because at that time there was some CI runners' failure. All tests were pass locally.

**Pull request merged**
