### PR TITLE
perf(airbyte-cdk): performance enhancement

### PR DESCRIPTION
**Pull request by artem1205**
## What

Resolving https://github.com/airbytehq/airbyte-internal-issues/issues/8859

## How

- migrate from if-else to match-case;
- remove pydantic deprecated;
- use cache

## Follow up

- remove `@deprecated` decorator for heavily used methods: 
  - `get_updated_state`

## Review guide

1. `airbyte-cdk/python/airbyte_cdk/entrypoint.py`
2. `airbyte-cdk/python/airbyte_cdk/sources/abstract_source.py`
3. `airbyte-cdk/python/airbyte_cdk/utils/message_utils.py`
4. `airbyte-cdk/python/airbyte_cdk/sources/streams/core.py`
5. `airbyte-cdk/python/airbyte_cdk/sources/utils/record_helper.py`

### Profiling tests: source-hardcoded-records; 100_000 records

Before 13980 ms
image

After 8513 ms
image

### Test in Docker; 1_000_000 records
`/usr/bin/time -h docker run --rm -v $(pwd)/secrets:/secrets -v $(pwd)/integration_tests:/integration_tests airbyte/source-hardcoded-records:dev read --config /secrets/config.json --catalog /integration_tests/configured_catalog.json > /tmp/test.txt`

| TIME | real | user | sys |
|--------|--------|--------|--------|
| Before | 1m35.22s | 5.30s | 15.46s |
| After | 1m22.68s | 4.37s | 13.03s | 

## User Impact

>[!CAUTION]
>non compatible with python `3.9`

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by bazarnov** [comment]
@artem1205 As for the `source-zen desk-support` fail, please merge with the master; the fix was merged today.

**Review by bazarnov — APPROVED** [review]

**Comment by natikgadzhi** [comment]
@artem1205 one tricky thing: Connector Builder currently runs Python 3.9. We have a PR to upgrade it to 3.10 here: https://github.com/airbytehq/airbyte-platform-internal/pull/13191 

But that PR is waiting on another PR (move all our images to Corretto). Probably not a big deal with our usual lag of CDK-to-builder shipping, but be aware.

**Comment by natikgadzhi** [comment]
> remove @deprecated decorator for heavily used methods:
> get_updated_state 

This might blow up deprecated blocks reporting in connector ingishts. I'll keep an eye on it.

Now that this is merged, we need to prioritize Builder 3.10 image, I'll try and unblock it.

**Pull request merged**
