### PR TITLE
Fix Normalization failing with "adapter" does not exist

### LINKED ISSUE #2879: deduping on a float column fails on bigquery
## Expected Behavior
I expect the append dedupe sync mode to work correctly when the column being deduped is a float. 

## Current Behavior
A sync from PG to BQ seems to break on Airbyte 0.19.0-alpha. 

## Logs
[logs-failed_incr.txt](https://github.com/airbytehq/airbyte/files/6307307/logs-failed_incr.txt)

## Steps to Reproduce
TBD

## Severity of the bug for you
medium

## Airbyte Version
found in the logs

## Connector Version (if applicable)
found in the logs

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368101500294) by [Unito](https://www.unito.io)

### LINKED ISSUE #2919: Normalization failing with "adapter" does not exist
## Expected Behavior
*Tell us what should happen.*

## Current Behavior
*Tell us what happens instead of the expected behavior.*

## Logs
[logs-368-0.txt](https://github.com/airbytehq/airbyte/files/6326307/logs-368-0.txt)

image (11)

relevant log lines
```
2021-04-16 07:18:16 INFO (/tmp/workspace/368/0) LineGobbler(voidCall):69 - 
2021-04-16 07:18:16 INFO (/tmp/workspace/368/0) LineGobbler(voidCall):69 - [31mCompleted with 1 error and 0 warnings:[0m
2021-04-16 07:18:16 INFO (/tmp/workspace/368/0) LineGobbler(voidCall):69 - 
2021-04-16 07:18:16 INFO (/tmp/workspace/368/0) LineGobbler(voidCall):69 - [33mDatabase Error in model public_brokers_scd (models/generated/airbyte_tables/bi_market_units_service_data/public_brokers_scd.sql)[0m
2021-04-16 07:18:16 INFO (/tmp/workspace/368/0) LineGobbler(voidCall):69 -   schema "adapter" does not exist
2021-04-16 07:18:16 INFO (/tmp/workspace/368/0) LineGobbler(voidCall):69 -   LINE 106:         partition by cast(adapter.quote('id') as 
2021-04-16 07:18:16 INFO (/tmp/workspace/368/0) LineGobbler(voidCall):69 -                                       ^
2021-04-16 07:18:16 INFO (/tmp/workspace/368/0) LineGobbler(voidCall):69 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/bi_market_units_service_data/public_brokers_scd.sql
2021-04-16 07:18:16 INFO (/tmp/workspace/368/0) LineGobbler(voidCall):69 - 
2021-04-16 07:18:16 INFO (/tmp/workspace/368/0) LineGobbler(voidCall):69 - Done. PASS=0 WARN=0 ERROR=1 SKIP=1 TOTAL=2
2021-04-16 07:18:17 INFO (/tmp/workspace/368/0) TemporalAttemptExecution(lambda$getWorkerThread$2):140 - Completing future exceptionally...
io.airbyte.workers.WorkerException: Normalization Failed.
```

## Airbyte Version
Found in the .env file in the root of the project.

## Connector Version (if applicable)
Found in the admin page in the UI in the respective Source or Destination tab.

## Additional context
*Environment, version, integration...*

### PR DESCRIPTION
**Pull request by ChristopheDuong**
## What
Closes #2919 

## How
Missing jinja brackets around macro in generated DBT models

## Pre-merge Checklist
- [x] *Run integration tests*
- [x] *Publish Docker images*

### CODE REVIEW

**Review by cgardens — APPROVED** [review]
thanks!

can you describe what cases this would affect? it seems like we were only seeing this bug show up sometimes? I want to understand what cases it affects.

**Comment by ChristopheDuong** [comment]
> thanks!
> 
> can you describe what cases this would affect? it seems like we were only seeing this bug show up sometimes? I want to understand what cases it affects.

This happens when the primary key is a column that needs to be quoted.

So for example the column "id" is a reserved word in Postgres destinations.

The bug was that the dedup SQL was not putting the jinja macro brackets (adapter.quote is a jinja macro) in those cases.
(I even had a unit test for this but the test was wrong too)

**Pull request merged**
