### PR TITLE
🎉 New Source: Elasticsearch

### PR DESCRIPTION
**Pull request by nilkamalthakuria**
## What
*In this PR I am adding a new source Elasticsearch connector.*

## How
*Written in Java using Elasticsearch's High Level Rest Client [HLRC](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high.html)*

## Recommended reading order
1. `ElasticsearchSource.java`
2. `ElasticsearchConnection.java`
3. `ElasticsearchTypeMapper.java`

## 🚨 User Impact 🚨
New connector now has type mappings for objects, which are handled recursively, along with other Elasticsearch data types.
The previous [PR](https://github.com/airbytehq/airbyte/pull/7099) lacked this feature.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [x] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>
Screen Shot 2022-06-24 at 12 31 49 PM

</details>

<details><summary><strong>Integration</strong></summary>

Screen Shot 2022-07-01 at 11 40 24 AM

</details>

<details><summary><strong>Acceptance</strong></summary>

```

```

</details>

### CODE REVIEW

**Comment by nilkamalthakuria** [comment]
Would be grateful if someone could point me the fix for the missing docker image. I built the connector using `docker build . -t airbyte/source-elasticsearch:dev`, but it shows as missing during integration testing.

**Comment by marcosmarxm** [comment]
> Would be grateful if someone could point me the fix for the missing docker image. I built the connector using `docker build . -t airbyte/source-elasticsearch:dev`, but it shows as missing during integration testing.

Please run `./gradlew airbyte-integrations:connectors:source-elasticsearch:dev`

**Comment by nilkamalthakuria** [comment]
@marcosmarxm Here are the acceptance test logs. Screenshot is attached in the first comment.
[Test Results — ElasticsearchSourceAcceptanceTest .pdf](https://github.com/airbytehq/airbyte/files/9026729/Test.Results.ElasticsearchSourceAcceptanceTest.pdf)

**Comment by marcosmarxm** [comment]
./gradlew airbyte-integrations:connectors:source-elasticsearch:integrationTest

**Review by marcosmarxm — APPROVED** [review]
thanks @nilkamalthakuria

**Pull request merged**
