### PR TITLE
Source Yahoo-Finance-Price: Migrate to manifest-only

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
Source Yahoo-Finance-Price is migrated to manifest only format

## How
CI
Manual parameter correction

### CODE REVIEW

**Comment by btkcodedev** [comment]
/bump-version type="minor" changelog="Converting to manifest-only format"

**Comment by natikgadzhi** [comment]
@btkcodedev you have a bunch of new failing tests here:

```
-test_incremental.py::TestIncremental::test_two_sequential_reads[inputs0]
-test_incremental.py::TestIncremental::test_state_with_abnormally_large_values[inputs0]
-test_core.py::TestBasicRead::test_read[inputs0]
-test_full_refresh.py::TestFullRefresh::test_sequential_reads[inputs0]
```

**Comment by natikgadzhi** [comment]
Rerunning CI, there seemed to be a network outage.

**Comment by natikgadzhi** [comment]
I disabled pypi registry so the QA check calms down. 

This is the acceptance test that is failing: 

```
________________ TestFullRefresh.test_sequential_reads[inputs0] ________________

self = <connector_acceptance_test.tests.test_full_refresh.TestFullRefresh object at 0x7f1051715810>
connector_config = SecretDict(******)
configured_catalog = ConfiguredAirbyteCatalog(streams=[ConfiguredAirbyteStream(stream=AirbyteStream(name='price', json_schema={'type': 'obj...tionSyncMode.overwrite: 'overwrite'>, primary_key=None, generation_id=None, minimum_generation_id=None, sync_id=None)])
ignored_fields = {}
docker_runner = <connector_acceptance_test.utils.connector_runner.ConnectorRunner object at 0x7f1051714490>
detailed_logger = <Logger detailed_logger /test_input/acceptance_tests_logs/test_full_refresh.py__TestFullRefresh__test_sequential_reads[inputs0].txt (DEBUG)>

    async def test_sequential_reads(
        self,
        connector_config: SecretDict,
        configured_catalog: ConfiguredAirbyteCatalog,
        ignored_fields: Optional[Mapping[str, List[IgnoredFieldsConfiguration]]],
        docker_runner: ConnectorRunner,
        detailed_logger: Logger,
    ):
        configured_catalog = full_refresh_only_catalog(configured_catalog)
        output_1 = await docker_runner.call_read(
            connector_config,
            configured_catalog,
            enable_caching=False,
        )
        records_1 = [message.record for message in output_1 if message.type == Type.RECORD]
    
        # sleep to ensure that the emitted_at timestamp is different
        time.sleep(0.1)
    
        output_2 = await docker_runner.call_read(connector_config, configured_catalog, enable_caching=False)
        records_2 = [message.record for message in output_2 if message.type == Type.RECORD]
    
>       self.assert_emitted_at_increase_on_subsequent_runs(records_1, records_2)

/app/connector_acceptance_test/tests/test_full_refresh.py:77: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <connector_acceptance_test.tests.test_full_refresh.TestFullRefresh object at 0x7f1051715810>
first_read_records = [], second_read_records = []

    def assert_emitted_at_increase_on_subsequent_runs(self, first_read_records, second_read_records):
        first_read_records_data = [record.data for record in first_read_records]
>       assert first_read_records_data, "At least one record should be read using provided catalog"
E       AssertionError: At least one record should be read using provided catalog
E       assert []

```

I think this is dependent on the specific data, and we can probably ignore this.

**Comment by btkcodedev** [comment]
Yeah, the price varies upon time which cause sequential read to fail I guess

**Comment by natikgadzhi** [comment]
yolog

**Pull request merged**
