### PR TITLE
Source Facebook Marketing: handle config errors

### LINKED ISSUE #25686: Categorize Facebook Marketing config errors
A user can receive the following errors due to the setup of their config, which are currently categorized as system errors.

These all should be categorized as config errors. 

For this error, the error message indicates we cannot verify the Account ID. The external error message should read: "The Account ID is invalid. Refer to Facebook Marketing's [docs](https://www.facebook.com/business/help/1492627900875762) to find your Account ID"

There should also be a change to the connector spec which validates that the Account ID follows the format of only containing numbers, and should not accept any text.

- Error: 100, Missing permissions. Please also verify your Account ID: See the https://www.facebook.com/business/help/1492627900875762 for more information.
- Error: 100, Unsupported get request. Object with ID 'act_1288784415293272;1181817321833895' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api. Please also verify your Account ID: See the https://www.facebook.com/business/help/1492627900875762 for more information.
- Error: 100, Unsupported get request. Object with ID 'act_1288784415293272,1181817321833895,454424629048340,102471553244411,468318420850703,1692250867457202' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api. Please also verify your Account ID: See the https://www.facebook.com/business/help/1492627900875762 for more information.
- Error: 100, Unsupported get request. Object with ID 'act_act_05768070981957' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api. Please also verify your Account ID: See the https://www.facebook.com/business/help/1492627900875762 for more information.

The error message below should instead read, "The custom field `unique_clicks` is not a valid configuration for `metrics_by_account'. Review Facebook Marketing's [docs](https://developers.facebook.com/docs/marketing-api/reference/ads-action-stats/) for valid breakdowns.
- Please remove Following fields from the Custom metrics_by_account fields list due to possible errors on Facebook side: {'unique_clicks'}

### PR DESCRIPTION
**Pull request by artem1205**
## What
Resolve https://github.com/airbytehq/airbyte/issues/25686

## How
handle permission specific errors (`code` `100`) as `config_error`, validate `accountID` (digits only)

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨

no breaking changes

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Review by lazebnyi — APPROVED** [review]
LGTM

**Review by alafanechere — APPROVED** [review]
LGTM. Even if this is a pattern addition restricting the input I think this is backward compatible because no user should have correctly set up an account id with inputs not matching the pattern so far.

**Pull request merged**
