### PR TITLE
Redshift T&D SQL statements moved to debug log level

### PR DESCRIPTION
**Pull request by evantahler**
Like https://github.com/airbytehq/airbyte/pull/33084, but for redshift
Helps close https://github.com/airbytehq/airbyte/issues/29956

### CODE REVIEW

**Comment by evantahler** [comment]
I'm not bumping the CDK or connector versions because we'll roll this small change into the next update we do

**Review by gisripa — APPROVED** [review]

**Comment by gisripa** [comment]
@evantahler  fwiw. In dv2 redshift, they are printed in a single line instead of indented SQL

**Comment by evantahler** [comment]
@gisripa I'm seeing some failing tests... should I be worried?

**Comment by gisripa** [comment]
> @gisripa I'm seeing some failing tests... should I be worried?

🤔 
```
RedshiftInsertDestinationAcceptanceTest > testEntrypointEnvVar() FAILED
    org.jooq.exception.DataAccessException: SQL [DROP SCHEMA IF EXISTS diff_source_namespace_test_20231203_rutmc CASCADE]; ERROR: The schema "diff_source_namespace_test_20231203_rutmc" was dropped by a concurrent transaction
```

**Comment by evantahler** [comment]
Ok, the tests are fine now, it's metadata that's failing... merging!

**Pull request merged**
