### PR TITLE
🐛Source Trustpilot: Fix refresh token URL

### LINKED ISSUE #42854: [Source Trustpilot] - Refresh token error - Bad request
### Connector Name

source-trustpilot

### Connector Version

0.2.1

### What step the error happened?

During the sync

### Relevant information

Reported by Airbyte User:
Reference: https://github.com/airbytehq/airbyte/pull/40267#issuecomment-2255151622

### Relevant log output

```shell
File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py", line 56, in check_availability
    is_available, reason = self.handle_http_error(stream, logger, source, error)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py", line 85, in handle_http_error
    raise error
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py", line 50, in check_availability
    get_first_record_for_slice(stream, stream_slice)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py", line 40, in get_first_record_for_slice
    return next(records_for_slice)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 128, in read_records
    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 375, in read_records
    for stream_data in self._read_pages(record_generator, self.state, _slice):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 298, in _read_pages
    response = self._fetch_next_page(stream_state, stream_slice, next_page_token)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 273, in _fetch_next_page
    return self.requester.send_request(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 301, in send_request
    headers=self._request_headers(stream_state, stream_slice, next_page_token, request_headers),
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 190, in _request_headers
    headers = self._get_request_options(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 174, in _get_request_options
    auth_options_method(),
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 56, in get_auth_header
    return {"Authorization": f"Bearer {self.get_access_token()}"}
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 61, in get_access_token
    token, expires_in = self.refresh_access_token()
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 150, in refresh_access_token
    response_json = self._get_refresh_access_token_response()
  File "/usr/local/lib/python3.10/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 132, in _get_refresh_access_token_response
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.trustpilot.com/v1/oauth/oauth-business-users-for-applications/accesstoken?response_type=token
2024-07-29 07:20:55 ERROR i.a.w.i.VersionedAirbyteStreamFactory(internalLog):304 - Check failed
2024-07-29 07:20:55 INFO i.a.c.ConnectorMessageProcessor(updateConfigFromControlMessage):231 - Checking for optional control message...
2024-07-29 07:20:55 INFO i.a.c.ConnectorWatcher(run):134 - Writing output of d7e23ea6-d741-4314-9209-a33c91a2e945_15400100_0_check to the doc store
2024-07-29 07:20:55 INFO i.a.c.ConnectorWatcher(run):136 - Marking workload as successful
2024-07-29 07:20:56 INFO i.a.c.ConnectorWatcher(exitProperly):189 - Deliberately exiting process with code 0.
2024-07-29 07:20:56 INFO i.a.c.i.LineGobbler(voidCall):166 - 
2024-07-29 07:20:56 INFO i.a.c.i.LineGobbler(voidCall):166 - ----- END CHECK -----
2024-07-29 07:20:59 platform > Retry State: RetryManager(completeFailureBackoffPolicy=BackoffPolicy(minInterval=PT10S, maxInterval=PT30M, base=3), partialFailureBackoffPolicy=null, successiveCompleteFailureLimit=5, totalCompleteFailureLimit=5, successivePartialFailureLimit=1000, totalPartialFailureLimit=20, successiveCompleteFailures=1, totalCompleteFailures=1, successivePartialFailures=0, totalPartialFailures=0)
 Backoff before next attempt: 10 seconds
2024-07-29 07:20:44 INFO i.a.w.l.c.WorkloadApiClient(claim):75 - Claimed: true for d7e23ea6-d741-4314-9209-a33c91a2e945_15400100_0_check via API for aws-eu-paris-queue-1
2024-07-29 07:20:44 INFO i.a.w.l.p.s.m.Stage(apply):39 - APPLY Stage: CHECK_STATUS — (workloadId = d7e23ea6-d741-4314-9209-a33c91a2e945_15400100_0_check) — (dataplaneId = aws-eu-paris-queue-1)
2024-07-29 07:20:44 INFO i.a.w.l.p.s.CheckStatusStage(applyStage):59 - No pod found running for workload d7e23ea6-d741-4314-9209-a33c91a2e945_15400100_0_check
2024-07-29 07:20:44 INFO i.a.w.l.p.s.m.Stage(apply):39 - APPLY Stage: BUILD — (workloadId = d7e23ea6-d741-4314-9209-a33c91a2e945_15400100_0_check) — (dataplaneId = aws-eu-paris-queue-1)
2024-07-29 07:20:45 INFO i.a.w.l.p.s.m.Stage(apply):39 - APPLY Stage: MUTEX — (workloadId = d7e23ea6-d741-4314-9209-a33c91a2e945_15400100_0_check) — (dataplaneId = aws-eu-paris-queue-1)
2024-07-29 07:20:45 INFO i.a.w.l.p.s.EnforceMutexStage(applyStage):50 - No mutex key specified for workload: d7e23ea6-d741-4314-9209-a33c91a2e945_15400100_0_check. Continuing...
2024-07-29 07:20:45 INFO i.a.w.l.p.s.m.Stage(apply):39 - APPLY Stage: LAUNCH — (workloadId = d7e23ea6-d741-4314-9209-a33c91a2e945_15400100_0_check) — (dataplaneId = aws-eu-paris-queue-1)
2024-07-29 07:20:54 INFO i.a.w.l.c.WorkloadApiClient(updateStatusToLaunched):60 - Attempting to update workload: d7e23ea6-d741-4314-9209-a33c91a2e945_15400100_0_check to LAUNCHED.
2024-07-29 07:20:54 INFO i.a.w.l.p.h.SuccessHandler(accept):60 - Pipeline completed for workload: d7e23ea6-d741-4314-9209-a33c91a2e945_15400100_0_check.
2024-07-29 07:20:59 platform > Failing job: 15400100, reason: Connection Check Failed 212cf3b7-ab21-4b41-b54b-501e4d688b67
```

### Contribute

- [ ] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
Closes https://github.com/airbytehq/airbyte/issues/42854

## How
According to the documentation, the current URL 
https://api.trustpilot.com/v1/oauth/oauth-business-users-for-applications/accesstoken should be working fine
But the previous connector shows error during sync, thus using the first URL for refresh
https://api.trustpilot.com/v1/oauth/oauth-business-users-for-applications/refresh

Fix: Refresh token URL
Documentation URL:
https://documentation-apidocumentation.trustpilot.com/authentication#client-credentials

### CODE REVIEW

**Comment by btkcodedev** [comment]
@valentinfily Due to credential limitations, can you please take a pull of this [URL](https://github.com/airbytehq/airbyte/pull/42855) branch and verify the working?
Everything seems aligned with Trustpilot documentation

**Comment by valentinfily** [comment]
Thank you @btkcodedev 
Looks like I have the same issue with this one.

I'm very surprised as I follow the instructions to input the right credentials and had this working in production for more than a year without issue.

Are you able to test it yourself with a production key ?

```
2024-07-30 15:00:24 ERROR i.a.w.i.VersionedAirbyteStreamFactory(internalLog):304 - Encountered an error trying to connect to stream configured_business_units. Error: 
 Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/checks/check_stream.py", line 42, in check_connection
    stream_is_available, reason = availability_strategy.check_availability(stream, logger)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py", line 46, in check_availability
    self.get_first_record_for_slice(stream, stream_slice)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/availability_strategy.py", line 75, in get_first_record_for_slice
    return next(records_for_slice)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 136, in read_records
    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 375, in read_records
    for stream_data in self._read_pages(record_generator, self.state, _slice):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 298, in _read_pages
    response = self._fetch_next_page(stream_state, stream_slice, next_page_token)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 273, in _fetch_next_page
    return self.requester.send_request(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 312, in send_request
    headers=self._request_headers(stream_state, stream_slice, next_page_token, request_headers),
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 201, in _request_headers
    headers = self._get_request_options(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/requesters/http_requester.py", line 185, in _get_request_options
    auth_options_method(),
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 56, in get_auth_header
    return {"Authorization": f"Bearer {self.get_access_token()}"}
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 61, in get_access_token
    token, expires_in = self.refresh_access_token()
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 150, in refresh_access_token
    response_json = self._get_refresh_access_token_response()
  File "/usr/local/lib/python3.10/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py", line 132, in _get_refresh_access_token_response
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.trustpilot.com/v1/oauth/oauth-business-users-for-applications/refresh
2024-07-30 15:00:24 ERROR i.a.w.i.VersionedAirbyteStreamFactory(internalLog):304 - Check failed
2024-07-30 15:00:24 INFO i.a.c.ConnectorMessageProcessor(updateConfigFromControlMessage):231 - Checking for optional control message...
2024-07-30 15:00:24 INFO i.a.c.ConnectorWatcher(run):134 - Writing output of c44bdbb4-6e80-4707-aaaa-567d4a33231b_15473270_0_check to the doc store
2024-07-30 15:00:25 INFO i.a.c.ConnectorWatcher(run):136 - Marking workload as successful
2024-07-30 15:00:25 INFO i.a.c.ConnectorWatcher(exitProperly):189 - Deliberately exiting process with code 0.
2024-07-30 15:00:25 INFO i.a.c.i.LineGobbler(voidCall):166 - 
2024-07-30 15:00:25 INFO i.a.c.i.LineGobbler(voidCall):166 - ----- END CHECK -----
2024-07-30 15:00:28 platform > Retry State: RetryManager(completeFailureBackoffPolicy=BackoffPolicy(minInterval=PT10S, maxInterval=PT30M, base=3), partialFailureBackoffPolicy=null, successiveCompleteFailureLimit=5, totalCompleteFailureLimit=5, successivePartialFailureLimit=1000, totalPartialFailureLimit=20, successiveCompleteFailures=1, totalCompleteFailures=1, successivePartialFailures=0, totalPartialFailures=0)
 Backoff before next attempt: 10 seconds
2024-07-30 15:00:17 INFO i.a.w.l.c.WorkloadApiClient(claim):75 - Claimed: true for c44bdbb4-6e80-4707-aaaa-567d4a33231b_15473270_0_check via API for aws-eu-paris-queue-1
2024-07-30 15:00:17 INFO i.a.w.l.p.s.m.Stage(apply):39 - APPLY Stage: CHECK_STATUS — (workloadId = c44bdbb4-6e80-4707-aaaa-567d4a33231b_15473270_0_check) — (dataplaneId = aws-eu-paris-queue-1)
2024-07-30 15:00:17 INFO i.a.w.l.p.s.CheckStatusStage(applyStage):59 - No pod found running for workload c44bdbb4-6e80-4707-aaaa-567d4a33231b_15473270_0_check
2024-07-30 15:00:17 INFO i.a.w.l.p.s.m.Stage(apply):39 - APPLY Stage: BUILD — (workloadId = c44bdbb4-6e80-4707-aaaa-567d4a33231b_15473270_0_check) — (dataplaneId = aws-eu-paris-queue-1)
2024-07-30 15:00:17 INFO i.a.w.l.p.s.m.Stage(apply):39 - APPLY Stage: MUTEX — (workloadId = c44bdbb4-6e80-4707-aaaa-567d4a33231b_15473270_0_check) — (dataplaneId = aws-eu-paris-queue-1)
2024-07-30 15:00:17 INFO i.a.w.l.p.s.EnforceMutexStage(applyStage):50 - No mutex key specified for workload: c44bdbb4-6e80-4707-aaaa-567d4a33231b_15473270_0_check. Continuing...
2024-07-30 15:00:17 INFO i.a.w.l.p.s.m.Stage(apply):39 - APPLY Stage: LAUNCH — (workloadId = c44bdbb4-6e80-4707-aaaa-567d4a33231b_15473270_0_check) — (dataplaneId = aws-eu-paris-queue-1)
2024-07-30 15:00:22 INFO i.a.w.l.c.WorkloadApiClient(updateStatusToLaunched):60 - Attempting to update workload: c44bdbb4-6e80-4707-aaaa-567d4a33231b_15473270_0_check to LAUNCHED.
2024-07-30 15:00:22 INFO i.a.w.l.p.h.SuccessHandler(accept):60 - Pipeline completed for workload: c44bdbb4-6e80-4707-aaaa-567d4a33231b_15473270_0_check.
2024-07-30 15:00:28 platform > Failing job: 15473270, reason: Connection Check Failed 05b8e378-6b90-488d-bcd9-49197d34727a
```

**Comment by btkcodedev** [comment]
@valentinfily There are some limitations in Oauth 2.0 credentials for checking right now as it's a community connector, can you try out with builder and try to fetch streams with oauth?
Or if there is any test creds that you could share on slack, it would be very useful?

**Comment by valentinfily** [comment]
Tried again with the current connector and looks like the issue is with refreshing the token. I will share this Trustpilot support too.

The initial connection works fine.
SCR-20240731-iygh-2

but when I click on "Retest saved source" I have the same issue :
SCR-20240731-iyne-2

**Review by natikgadzhi — APPROVED** [review]
The change here looks valid, let me go check what we used in the previous version.

**Comment by natikgadzhi** [comment]
The refresh token URL changed [here](https://github.com/airbytehq/airbyte/pull/36955/files#r1699206099). There are other changes, too — the expires_in format for example, but let's see if this solves it.

**Comment by valentinfily** [comment]
> The refresh token URL changed [here](https://github.com/airbytehq/airbyte/pull/36955/files#r1699206099). There are other changes, too — the expires_in format for example, but let's see if this solves it.

Thanks @natikgadzhi. Still have the same issue : I cannot refresh the token, could it be the expires_in format ?

**Comment by valentinfily** [comment]
Hello this source is still broken in v0.2.6

**Comment by natikgadzhi** [comment]
Ehhhhhh. 

@valentinfily would you be open to lending me your oauth / refresh token in a secure way (got to figure that out first), or invite me to your trustpilot org? I'd need a token to go in and try and debug this.

**Comment by natikgadzhi** [comment]
@btkcodedev I'm blocked with other things, but @valentinfily reached out to me and happy to work with us on this. 

I'll figure out a chat or something — let's make sure we resolve this so it stops being a problem for users.

**Comment by btkcodedev** [comment]
Yes sure

**Pull request merged**
