### PR TITLE
Delete `requirements.txt` on poetry managed connectors

### PR DESCRIPTION
**Pull request by alafanechere**
## What
Closes https://github.com/airbytehq/airbyte-internal-issues/issues/6301

## How
Remove `requirements.txt` file of python connectors migrated to poetry.

All these `requirements.txt` file content is:
```
-e .
```
Which was used to install the connector in `editable` mode for development.
`poetry run` already enables `editable` mode by default.

### CODE REVIEW

**Comment by alafanechere** [comment]
* `master`
  * **#35406** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/35406?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alafanechere and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by brianjlai — APPROVED** [review]
🔪

**Comment by octavia-approvington** [comment]
After a careful ML study, <br/> we think this looks okay.  <br/> imagine code being okay

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
