### PR TITLE
Running CI checks for Source Twilio #27323

### PR DESCRIPTION
**Pull request by sajarin**
Running CI checks for Source Twilio #27323

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-twilio test report (commit [`357507595a`](https://github.com/airbytehq/airbyte/pull/27368/commits/357507595a5593bbab8883088ffe736967d52484)) - ❌

⏲️  Total pipeline duration: 3628 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-twilio/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-twilio docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5270247722)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-twilio test
```

**Comment by octavia-squidington-iii** [comment]
##  source-twilio test report (commit [`917e744472`](https://github.com/airbytehq/airbyte/pull/27368/commits/917e74447246c3014117d6a2de80f2f1a3638e1c)) - ❌

⏲️  Total pipeline duration: 3703 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-twilio/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-twilio docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5270284992)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-twilio test
```

**Comment by sajarin** [comment]
Note to self: tests are failing because of expected_records, need to update expected records for the new stream, push to the contributor branch, rebase this branch off that and rerun the ci jobs.

**Comment by octavia-squidington-iii** [comment]
##  source-twilio test report (commit [`df39da70a2`](https://github.com/airbytehq/airbyte/pull/27368/commits/df39da70a29be7974052235d32ab94172767a6d6)) - ❌

⏲️  Total pipeline duration: 3480 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-twilio/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-twilio docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5270978405)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-twilio test
```

**Comment by octavia-squidington-iii** [comment]
##  source-twilio test report (commit [`a177a9b8a1`](https://github.com/airbytehq/airbyte/pull/27368/commits/a177a9b8a1b3d769361fa56c2de1e07712e44487)) - ✅

⏲️  Total pipeline duration: 3449 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-twilio/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-twilio docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5271449908)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-twilio test
```

**Pull request closed without merging**
