### PR TITLE
 Add dataset location to BigQuery connector (issue #3277)

### LINKED ISSUE #3277: Allow to specify data location in BigQuery destination
## Tell us about the problem you're trying to solve
I want Airbyte to put data to EU region instead of default one (usually US).
It happens when Airbyte creates a new dataset in BQ.

## Describe the solution you’d like
Add a data location option to the destination configuration (like EU, US, us-west2, and so on)

## Describe the alternative you’ve considered or used
At the moment I create datasets manually in EU region so tables inherit this configuration

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368107101350) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by ChristopheDuong**
## What
Closes #3277 
Replicates https://github.com/airbytehq/airbyte/pull/3887

## Pre-merge Checklist
Expand the checklist which is relevant for this PR. 

<details><summary> <strong> Connector checklist </strong> </summary>
<p>

- [x] Issue acceptance criteria met
- [x] Unit & integration tests added as appropriate (and are passing)
- [x] `/test` command documented [here]() is passing. 
    * Community members can skip this, Airbyters will run this for you. 
- [x] Code reviews completed
- [x] Credentials added to Github CI if needed and not already present. [instructions for injecting secrets into CI](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#using-credentials-in-ci). 
- [x] Documentation updated 
    - [ ] README
    - [x] CHANGELOG.md
    - [x] Reference docs in the `docs/integrations/` directory.
- [x] Build is successful
- [x] Connector version bumped like described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] No major blockers
- [ ] PR merged into master branch
- [ ] Follow up tickets have been created
- [ ] Associated tickets have been closed & stakeholders notified
</p>
</details>

### CODE REVIEW

**Comment by akoshterek** [comment]
I see the build is failing. Should we make some changes to fix it?

**Comment by ChristopheDuong** [comment]
> I see the build is failing. Should we make some changes to fix it?

No, we just need to publish the docker image to get that build error fixed., I'm just waiting for an approval from someone else (I can't approve it myself)

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
