### PR TITLE
Only add definitions updater cron when enabled

### PR DESCRIPTION
**Pull request by gosusnp**
## What

I keep seeing the definitions updater cron spinning up for no reason. We should not have the task scheduled if it is disabled.

## How

Use `@requires` to restrict the bean to when it's enabled.

### CODE REVIEW

**Review by pedroslopez — APPROVED** [review]
Nice!

**Review by pedroslopez — COMMENTED** [review]
We probably don't need to track `shouldUpdateDefinitions` anymore if this is the case

**Comment by gosusnp** [comment]
@pedroslopez, yep, I was wondering about that, removed the flag.

**Review by pedroslopez — APPROVED** [review]

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Pull request merged**
