### PR TITLE
🎉  Server logging S3 credentials: switch to DefaultCredentialsProvider

### LINKED ISSUE #10570: Server log storage on S3 should use DefaultAWSCredentialsProviderChain
## Environment
- **Airbyte version**:  0.35.32-alpha
- **OS Version / Instance**: AWS EKS
- **Deployment**: Kubernetes
- **Source Connector and version**: n/a
- **Destination Connector and version**: n/a
- **Severity**: High
- **Step where error happened**: Server start

## Current Behavior
Starting the server does not use DefaultAWSCredentialsProviderChain when building the S3 client for server log storage - it assumes that `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are set when running on AWS. These env vars don't apply when running on EKS and using IRSA.

## Expected Behavior
When running the server using a service account correctly configured with IRSA, the server should start and be able to read/write to the S3 log bucket.

## Logs

```
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable AWS_ACCESS_KEY_ID: ''
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable AWS_SECRET_ACCESS_KEY: ''
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_MAIN_CONTAINER_CPU_REQUEST: 'null'
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_MAIN_CONTAINER_CPU_LIMIT: 'null'
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_MAIN_CONTAINER_MEMORY_REQUEST: 'null'
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_MAIN_CONTAINER_MEMORY_LIMIT: 'null'
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_KUBE_TOLERATIONS: ''
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_KUBE_NODE_SELECTORS: ''
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_KUBE_MAIN_CONTAINER_IMAGE_PULL_SECRET: ''
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_KUBE_MAIN_CONTAINER_IMAGE_PULL_POLICY: 'IfNotPresent'
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_KUBE_SOCAT_IMAGE: 'alpine/socat:1.7.4.1-r1'
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_KUBE_BUSYBOX_IMAGE: 'busybox:1.28'
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable JOB_KUBE_CURL_IMAGE: 'curlimages/curl:7.77.0'
2022-02-23 06:57:23 INFO i.a.c.EnvConfigs(getEnvOrDefault):788 - Using default value for environment variable DEFAULT_WORKER_STATUS_CHECK_INTERVAL: 'PT30S'
2022-02-23 06:57:23 ERROR i.a.s.ServerApp(main):238 - Server failed
java.lang.IllegalArgumentException: null
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:131) ~[guava-31.0.1-jre.jar:?]
    at io.airbyte.config.storage.DefaultS3ClientFactory.validateBase(DefaultS3ClientFactory.java:36) ~[io.airbyte.airbyte-config-models-0.35.32-alpha.jar:?]
    at io.airbyte.config.storage.DefaultS3ClientFactory.validate(DefaultS3ClientFactory.java:31) ~[io.airbyte.airbyte-config-models-0.35.32-alpha.jar:?]
    at io.airbyte.config.storage.DefaultS3ClientFactory.<init>(DefaultS3ClientFactory.java:24) ~[io.airbyte.airbyte-config-models-0.35.32-alpha.jar:?]
    at io.airbyte.config.helpers.CloudLogs.createCloudLogClient(CloudLogs.java:44) ~[io.airbyte.airbyte-config-models-0.35.32-alpha.jar:?]
    at io.airbyte.config.helpers.LogClientSingleton.createCloudClientIfNull(LogClientSingleton.java:162) ~[io.airbyte.airbyte-config-models-0.35.32-alpha.jar:?]
    at io.airbyte.config.helpers.LogClientSingleton.setWorkspaceMdc(LogClientSingleton.java:149) ~[io.airbyte.airbyte-config-models-0.35.32-alpha.jar:?]
    at io.airbyte.server.ServerApp.getServer(ServerApp.java:146) ~[io.airbyte-airbyte-server-0.35.32-alpha.jar:?]
    at io.airbyte.server.ServerApp.main(ServerApp.java:236) [io.airbyte-airbyte-server-0.35.32-alpha.jar:?]
```

## Steps to Reproduce
1. Deploy server to EKS
2. Run under service account with IRSA

## Are you willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by adamschmidt**
## What

Resolves #10570: Switches the means by which the AWS credentials for setting up the logging S3 client are collected on startup.

## How

For AWS S3 specifically (Minio and GCP are unaffected by this change), the way that we now fetch the AWS credentials switches from `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables to `software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider`. This gives the platform and operators greater flexibility in terms of how the platform is run on AWS, and enables AWS EKS/IRSA deployments.

This change is transparent to how current implementations (and tests) run the Airbyte services. By switching to `DefaultCredentialsProvider`, there is a _chain_ of discovering credentials in addition to the existing usage of environment variables.

Additional AWS dependencies have been added to the root `build.gradle` to support the default provider chain.

**Note:** There are a lot of connectors in the solution where this same change needs to be applied. This change is focused _just_ on the server component.

## Recommended reading order
1. `airbyte-config/models/src/main/java/io/airbyte/config/storage/DefaultS3ClientFactory.java`
2. `airbyte-config/models/src/main/java/io/airbyte/config/EnvConfigs.java`

## 🚨 User Impact 🚨

No user-facing change.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

## Tests

<details><summary><strong>Unit</strong></summary>

```
> Task :buildSrc:extractPluginRequests UP-TO-DATE
> Task :buildSrc:generatePluginAdapters UP-TO-DATE
> Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy UP-TO-DATE
> Task :buildSrc:compileGroovyPlugins UP-TO-DATE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE
> Task :airbyte-json-validation:processResources NO-SOURCE
> Task :airbyte-protocol:models:processResources UP-TO-DATE
> Task :airbyte-protocol:models:generateJsonSchema2Pojo UP-TO-DATE
> Task :airbyte-config:models:processResources UP-TO-DATE
> Task :airbyte-config:models:generateJsonSchema2Pojo UP-TO-DATE
> Task :airbyte-config:models:processTestResources NO-SOURCE
> Task :airbyte-commons:compileJava UP-TO-DATE
> Task :airbyte-commons:processResources UP-TO-DATE
> Task :airbyte-commons:classes UP-TO-DATE
> Task :airbyte-commons:jar UP-TO-DATE
> Task :airbyte-json-validation:compileJava UP-TO-DATE
> Task :airbyte-json-validation:classes UP-TO-DATE
> Task :airbyte-json-validation:jar UP-TO-DATE
> Task :airbyte-protocol:models:compileJava UP-TO-DATE
> Task :airbyte-protocol:models:classes UP-TO-DATE
> Task :airbyte-protocol:models:jar UP-TO-DATE
> Task :airbyte-config:models:compileJava UP-TO-DATE
> Task :airbyte-config:models:classes UP-TO-DATE
> Task :airbyte-config:models:compileTestJava UP-TO-DATE
> Task :airbyte-config:models:testClasses UP-TO-DATE
> Task :airbyte-config:models:test
Mar 02, 2022 10:24:08 PM org.junit.platform.launcher.core.EngineDiscoveryOrchestrator lambda$logTestDescriptorExclusionReasons$7
INFO: 0 containers and 5 tests were excluded because tags match tag expression(s): [log4j2-config,logger-client]
ConfigSchemaTest > testFile() PASSED
ConfigSchemaTest > testPrepareKnownSchemas() PASSED
DataTypeEnumTest > testConversionFromJsonSchemaPrimitiveToDataType() PASSED
2022-03-02 11:24:10 INFO i.a.c.EnvConfigs(getEnvOrDefault):827 - Using default value for environment variable JOB_KUBE_NODE_SELECTORS: ''
2022-03-02 11:24:10 INFO i.a.c.EnvConfigs(getEnvOrDefault):827 - Using default value for environment variable DISCOVER_JOB_KUBE_NODE_SELECTORS: ''
2022-03-02 11:24:10 INFO i.a.c.EnvConfigs(getEnvOrDefault):827 - Using default value for environment variable PUBLISH_METRICS: 'false'
2022-03-02 11:24:10 INFO i.a.c.EnvConfigs(getEnvOrDefault):827 - Using default value for environment variable PUBLISH_METRICS: 'false'
2022-03-02 11:24:10 INFO i.a.c.EnvConfigs(getEnvOrDefault):827 - Using default value for environment variable SPEC_JOB_KUBE_NODE_SELECTORS: ''
2022-03-02 11:24:10 INFO i.a.c.EnvConfigs(getEnvOrDefault):827 - Using default value for environment variable CHECK_JOB_KUBE_NODE_SELECTORS: ''
2022-03-02 11:24:10 INFO i.a.c.EnvConfigs(getEnvOrDefault):827 - Using default value for environment variable TRACKING_STRATEGY: 'LOGGING'
2022-03-02 11:24:10 INFO i.a.c.EnvConfigs(lambda$getTrackingStrategy$17):680 - abc not recognized, defaulting to LOGGING
2022-03-02 11:24:10 INFO i.a.c.EnvConfigs(getEnvOrDefault):827 - Using default value for environment variable WORKSPACE_DOCKER_MOUNT: 'abc/def'
2022-03-02 11:24:10 INFO i.a.c.EnvConfigs(getEnvOrDefault):827 - Using default value for environment variable DOCKER_NETWORK: 'host'
2022-03-02 11:24:10 INFO i.a.c.EnvConfigs(getEnvOrDefault):827 - Using default value for environment variable LOCAL_DOCKER_MOUNT: 'abc/def'
2022-03-02 11:24:10 INFO i.a.c.EnvConfigs(getEnvOrDefault):827 - Using default value for environment variable JOB_KUBE_TOLERATIONS: ''
2022-03-02 11:24:10 WARN i.a.c.EnvConfigs(parseToleration):454 - Ignoring toleration key=k,value=v, missing one of key,effect or operator
2022-03-02 11:24:10 INFO i.a.c.EnvConfigs(getEnvOrDefault):827 - Using default value for environment variable CHECK_JOB_MAIN_CONTAINER_MEMORY_REQUEST: '1'
2022-03-02 11:24:10 INFO i.a.c.EnvConfigs(getEnvOrDefault):827 - Using default value for environment variable CHECK_JOB_MAIN_CONTAINER_CPU_REQUEST: '1'
2022-03-02 11:24:10 INFO i.a.c.EnvConfigs(getEnvOrDefault):827 - Using default value for environment variable CHECK_JOB_MAIN_CONTAINER_CPU_LIMIT: '1'
2022-03-02 11:24:10 INFO i.a.c.EnvConfigs(getEnvOrDefault):827 - Using default value for environment variable CHECK_JOB_MAIN_CONTAINER_MEMORY_LIMIT: '1'
EnvConfigsTest > testAirbyteVersion() PASSED
EnvConfigsTest > testGetDatabaseUrl() PASSED
EnvConfigsTest > testEmptyEnvMapRetrieval() PASSED
EnvConfigsTest > testJobKubeNodeSelectors() PASSED
EnvConfigsTest > testWorkspaceRoot() PASSED
EnvConfigsTest > ensureGetEnvBehavior() PASSED
EnvConfigsTest > testLocalRoot() PASSED
EnvConfigsTest > testDiscoverKubeNodeSelectors() PASSED
EnvConfigsTest > testPublishMetrics() PASSED
EnvConfigsTest > testConfigRoot() PASSED
EnvConfigsTest > testGetDatabasePassword() PASSED
EnvConfigsTest > testSpecKubeNodeSelectors() PASSED
EnvConfigsTest > testAirbyteRole() PASSED
EnvConfigsTest > testCheckKubeNodeSelectors() PASSED
EnvConfigsTest > testTrackingStrategy() PASSED
EnvConfigsTest > testGetWorkspaceDockerMount() PASSED
EnvConfigsTest > testDockerNetwork() PASSED
EnvConfigsTest > testGetLocalDockerMount() PASSED
EnvConfigsTest > testGetDatabaseUser() PASSED
EnvConfigsTest > testEnvMapRetrieval() PASSED
EnvConfigsTest > testworkerKubeTolerations() PASSED
EnvConfigsTest > CheckJobResourceSettings > checkJobCpuRequest should take precedent if set PASSED
EnvConfigsTest > CheckJobResourceSettings > checkJobMemoryLimit should take precedent if set PASSED
EnvConfigsTest > CheckJobResourceSettings > checkJobMemoryRequest should take precedent if set PASSED
EnvConfigsTest > CheckJobResourceSettings > should default to JobMainMemoryRequest if not set PASSED
EnvConfigsTest > CheckJobResourceSettings > should default to JobMainCpuRequest if not set PASSED
EnvConfigsTest > CheckJobResourceSettings > checkJobCpuLimit should take precedent if set PASSED
EnvConfigsTest > CheckJobResourceSettings > should default to JobMainCpuLimit if not set PASSED
EnvConfigsTest > CheckJobResourceSettings > should default to JobMainMemoryLimit if not set PASSED
CloudLogsClientTest > createCloudLogClientTestAws() PASSED
CloudLogsClientTest > createCloudLogClientTestGcs() PASSED
CloudLogsClientTest > createCloudLogClientTestMinio() PASSED
LogClientSingletonTest > testGetJobLogFileNullPath() PASSED
LogClientSingletonTest > testGetJobLogFileEmptyPath() PASSED
LogClientSingletonTest > testGetJobLogFileK8s() PASSED
ScheduleHelpersTest > testGetSecondsInUnit() PASSED
ScheduleHelpersTest > testAllOfTimeUnitEnumValues() PASSED
YamlListToStandardDefinitionsTest > verifyAndConvertToModelList > should error out on bad data PASSED
YamlListToStandardDefinitionsTest > verifyAndConvertToModelList > should error out on duplicate name PASSED
YamlListToStandardDefinitionsTest > verifyAndConvertToModelList > should correctly read yaml file PASSED
YamlListToStandardDefinitionsTest > verifyAndConvertToModelList > should error out on duplicate id PASSED
YamlListToStandardDefinitionsTest > verifyAndConvertToModelList > should error out on empty file PASSED
YamlListToStandardDefinitionsTest > vertifyAndConvertToJsonNode > should error out on bad data PASSED
YamlListToStandardDefinitionsTest > vertifyAndConvertToJsonNode > should error out on duplicate name PASSED
YamlListToStandardDefinitionsTest > vertifyAndConvertToJsonNode > should correctly read yaml file PASSED
YamlListToStandardDefinitionsTest > vertifyAndConvertToJsonNode > should error out on duplicate id PASSED
YamlListToStandardDefinitionsTest > vertifyAndConvertToJsonNode > should error out on empty file PASSED
CloudLogsClientTest > testGcs() PASSED
CloudLogsClientTest > testGcsMissingBucket() PASSED
DefaultS3ClientFactoryTest > testS3() PASSED
DefaultS3ClientFactoryTest > testIAMPropertiesFail() PASSED
DefaultS3ClientFactoryTest > testS3RegionNotSet() PASSED
MinioS3ClientFactoryTest > testMinio() PASSED
MinioS3ClientFactoryTest > testMinioEndpointMissing() PASSED
> Task :airbyte-config:models:jacocoTestReport
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 29s
```
</details>

### CODE REVIEW

**Review by alafanechere — APPROVED** [review]
Hey @adamschmidt, thanks you for this improvements!
Do you mind updating this [documentation section](https://github.com/airbytehq/airbyte/blob/master/docs/operator-guides/configuring-airbyte.md#logging) (rendered in this [page](https://docs.airbyte.com/operator-guides/configuring-airbyte#logging-1)). I'd be nice if you could remind  in this doc the credentials discovery *chain* you mention. Is it the same as Boto:
1. Passing credentials as parameters to the client
2. Passing credentials as parameters when creating a Session object
3. Environment variables
4. Shared credential file (~/.aws/credentials)
5. AWS config file (~/.aws/config)
6. Assume Role provider
7. Instance metadata service on an Amazon EC2 instance that has an IAM role configured.

I'll request a second review from @davinchia

**Comment by adamschmidt** [comment]
@alafanechere I've updated the docs with a couple of edits:

* Moved the logging config all under the one **Logging** heading
* A section specifically for AWS deployments

While this change applies only to the server for the purposes of logging, it should also be applied to any other components/services in the stack that utilise AWS services. I'm keen to tackle that under a separate PR.

**Comment by davinchia** [comment]
@adamschmidt have you run an airbyte deployment with these changes to confirm this change in compatible with the logging set up?

**Comment by davinchia** [comment]
Got it. So we'll still use the DefaultCreditProvider except it'll be from aws v1?

Thanks. Please tag me once you are ready.

**Comment by alafanechere** [comment]
@adamschmidt FYI there's another open PR that tries to add instance profile support to the S3 source connector: https://github.com/airbytehq/airbyte/pull/10676

**Comment by alafanechere** [comment]
Hey @adamschmidt, I converted the PR to draft as you said you've ongoing work about dependencies. Feel free to convert it to ready for review once you push new commits!

**Comment by alafanechere** [comment]
Hey @adamschmidt, I allow myself to close this PR due to no-recent activities on this branch. Feel free to re-open whenever you like!

**Comment by gvillafanetapia** [comment]
Hi I was looking for this fix. Problem is that since I need to send logs to S3 I'm forced to setup AWS Credentials and then on both S3 sources and destinations will try to use these instead of IRSA.

Was this fixed at all?

**Comment by gilandose** [comment]
I'm going to try and open a PR for this if this has been abandoned as this is blocking IRSA

**Pull request closed without merging**
