### PR TITLE
Source Recurly: adds `state_checkpoint_interval` to streams

### PR DESCRIPTION
**Pull request by mohamagdy**
## What
Add `state_checkpoint_interval` to Recurly source connector

## 🚨 User Impact 🚨
No user impact expected

## Pre-merge Checklist

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

## Tests

<details><summary><strong>Unit</strong></summary>

```shell
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_account_coupon_redemptions_read_records ✓                                                                                           5% ▌
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_account_notes_read_records ✓                                                                                                       10% ▉
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_accounts_methods_client_method_name ✓                                                                                              14% █▌
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_add_ons_client_method_name ✓                                                                                                       19% █▉
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_billing_infos_client_method_name ✓                                                                                                 24% ██▍
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_coupons_methods_client_method_name ✓                                                                                               29% ██▉
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_credit_payments_read_records ✓                                                                                                     33% ███▍
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_export_dates_read_records ✓                                                                                                        38% ███▊
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_get_updated_state ✓                                                                                                                43% ████▍
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_invoices_methods_client_method_name ✓                                                                                              48% ████▊
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_line_items_methods_client_method_name ✓                                                                                            52% █████▎
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_measured_unit_client_method_name ✓                                                                                                 57% █████▊
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_plans_client_method_name ✓                                                                                                         62% ██████▎
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_read_records ✓                                                                                                                     67% ██████▋
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_read_records_with_begin_time ✓                                                                                                     71% ███████▎
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_read_records_with_end_time ✓                                                                                                       76% ███████▋
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_shipping_addresses_client_method_name ✓                                                                                            81% ████████▏
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_shipping_methods_client_method_name ✓                                                                                              86% ████████▋
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_subscriptions_client_method_name ✓                                                                                                 90% █████████▏
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_transactions_client_method_name ✓                                                                                                  95% █████████▌
 airbyte-integrations/connectors/source-recurly/unit_tests/test_streams.py::TestStreams.test_unique_coupons_read_records ✓                                                                                                     100% ██████████

Results (0.69s):
      21 passed
```

</details>

<details><summary><strong>Integration</strong></summary>

```shell
(3.9.7/envs/airbyte-recurly) ➜  source-recurly git:(add-state-checkpoint-to-recurly-stream) ✗ python -m pytest integration_tests.acceptance
Test session starts (platform: darwin, Python 3.9.7, pytest 6.1.2, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /Users/mohamedmagdy/projects/airbyte/airbyte, configfile: pytest.ini
plugins: sugar-0.9.4, timeout-1.4.2
collecting ...

Results (0.02s):
```

</details>

### CODE REVIEW

**Review by marcosmarxm — APPROVED** [review]
please bump the Dockerfile version and the documentation.

**Comment by mohamagdy** [comment]
> please bump the Dockerfile version and the documentation.

Thanks @marcosmarxm for the review. Bumped the version of the Recurly connector to `0.4.1` here https://github.com/airbytehq/airbyte/pull/13685/commits/d8c462b60f004f5d12f662dd332798f223e58bfd

**Comment by marcosmarxm** [comment]
Sorry @mohamagdy havving problems with our CI.

**Comment by marcosmarxm** [comment]
@mohamagdy I'm blocked to merge this waiting https://github.com/airbytehq/airbyte/issues/14778. I'll be on vacation and only return 26-jul maybe after I'll have some time to fix that

**Pull request merged**
