### PR TITLE
Prettier: no `proseWrap`

### PR DESCRIPTION
**Pull request by natikgadzhi**
## What

I've met @aaronsteers last week and we talked about formatting Markdown, and how we can't enforce 80 or 120 character width because 1) it's prone to breaking anyway, and 2) annoying for some, 3) we have CATs for connector docs that are breaking on smaller line lengths because they assume connector name and certain things are on the same line. 

But, we still do want clean markdown otherwise.

Hence this PR — keeps the `.prettierrc` file, and runs `prettier --write **/*.md` in two separate commits for readability.

We allegedly run `prettier -w` on changed files with `airbyte-ci format`, but it's only on change sets, and sometimes we `/approve-and-merge`. As a result, running Prettier changed quite a few files. This just cleans the slate. Python cleanup to follow.

## How to get this in

- [x] Did the docs site build successfully?
- [x] Did the CI flow pass?

## Can this PR be safely reverted and rolled back?
- [x] YES 💚
- [ ] NO ❌

> [!Warning]
> This PR is set to auto merge on green CI and an approval.

### CODE REVIEW

**Comment by natikgadzhi** [comment]
Add labels check is freaking out about a non-existend label or something, ignore it!

**Review by alafanechere — APPROVED** [review]
Does prettier has something to format markdown tables? Would be a cool addition

**Review by aaronsteers — APPROVED** [review]
❤️ this!

**Comment by natikgadzhi** [comment]
Thank you for the reviews! Since I get a week to cosplay a jetlagged engineer, I want to focus this down. Before merging, I want to understand: 
1. Can I also format tables nicely?
2. Why did I think that `airbyte-ci format check` only checks diffs? Does it error out on previous master with previous config, or was it "ain't broke not gonna fix it" situation?
3. Why are so many things on CI failing on this PR?

I'll try to keep notes for posterity here.

**Comment by natikgadzhi** [comment]
Oh my lordy PLEASE I have been re-doing this three times already to grab new updated docs from master.

**Comment by natikgadzhi** [comment]
The pattern I noticed is that in some spots, some of our checks (connectors_qa docs tests for example) compare generated markdown file to formatted existing file as strings. I tweaked the templates, but alternative approach would be to just add a formatting step to the pipeline of generating the new docs file.

**Pull request merged**
