### PR TITLE
Download external DBT dependencies when building normalization docker image

### LINKED ISSUE #1519: Download external DBT dependencies when building normalization docker image
## Tell us about the problem you're trying to solve
Currently, normalization pulls external dbt_utls dependency every time it is run into the job workspace, resulting in many unnecessary `git clone` commands.

## Describe the solution you’d like
This could be done once as part of building the normalization docker image instead

### PR DESCRIPTION
**Pull request by ChristopheDuong**
Closes #1519

## Pre-merge Checklist
- [x] *Run integration tests*
- [X] *Publish Docker images*

### CODE REVIEW

**Review by michel-tricot — APPROVED** [review]
Looks great! don't forget to add reviewers to your PRs

**Review by cgardens — COMMENTED** [review]
nice.

**Pull request merged**
