### PR TITLE
[Source-Postgres] Update PostgresConverter to correctly stringify BigDecimals without scientific notation

### PR DESCRIPTION
**Pull request by nguyenaiden**
### Description
Update how the PostgresConverter's `registerNumber` method to use `toPlainString()` instead of `toString()` to stringify decimals in standard form and not scientific notation.
Added a test to address #28303.

### CODE REVIEW

**Review by rodireich — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`3614089f2c`](https://github.com/airbytehq/airbyte/pull/31309/commits/3614089f2c9afba016da3f39c54ebe05bc024496)) - ❌

⏲️  Total pipeline duration: 29mn38s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build connector tar                                             | ✅        |
| Build source-postgres docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                       | ✅        |
| Java Connector Integration Tests                                | ❌        |
| Acceptance tests                                                | ✅        |
| Validate metadata for source-postgres                           | ✅        |
| Connector version semver check                                  | ✅        |
| QA checks                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cdc-postgres-bad-int/1697132800/3614089f2c9afba016da3f39c54ebe05bc024496/source-postgres/3.1.11/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:3614089f2c9afba016da3f39c54ebe05bc024496)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`7b656c7ce9`](https://github.com/airbytehq/airbyte/pull/31309/commits/7b656c7ce932f3e2fe7eb551505bdbb3c94e7573)) - ❌

⏲️  Total pipeline duration: 02mn14s 

| Step                                  | Result   |
|:--------------------------------------|:---------|
| Build connector tar                   | ❌        |
| Validate metadata for source-postgres | ✅        |
| Connector version semver check        | ✅        |
| Connector version increment check     | ✅        |
| QA checks                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cdc-postgres-bad-int/1697136578/7b656c7ce932f3e2fe7eb551505bdbb3c94e7573/source-postgres/3.1.12/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7b656c7ce932f3e2fe7eb551505bdbb3c94e7573)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres-strict-encrypt test report (commit [`7b656c7ce9`](https://github.com/airbytehq/airbyte/pull/31309/commits/7b656c7ce932f3e2fe7eb551505bdbb3c94e7573)) - ❌

⏲️  Total pipeline duration: 55.75s 

| Step                                                 | Result   |
|:-----------------------------------------------------|:---------|
| Build connector tar                                  | ❌        |
| Validate metadata for source-postgres-strict-encrypt | ✅        |
| Connector version semver check                       | ✅        |
| QA checks                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cdc-postgres-bad-int/1697136578/7b656c7ce932f3e2fe7eb551505bdbb3c94e7573/source-postgres-strict-encrypt/3.1.12/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7b656c7ce932f3e2fe7eb551505bdbb3c94e7573)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres-strict-encrypt test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres-strict-encrypt test report (commit [`c66f19def5`](https://github.com/airbytehq/airbyte/pull/31309/commits/c66f19def5852b9a718e1faa809347b974250c9a)) - ❌

⏲️  Total pipeline duration: 01mn34s 

| Step                                                 | Result   |
|:-----------------------------------------------------|:---------|
| Build connector tar                                  | ❌        |
| Validate metadata for source-postgres-strict-encrypt | ✅        |
| Connector version semver check                       | ✅        |
| QA checks                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cdc-postgres-bad-int/1697144667/c66f19def5852b9a718e1faa809347b974250c9a/source-postgres-strict-encrypt/3.1.12/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:c66f19def5852b9a718e1faa809347b974250c9a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres-strict-encrypt test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`c66f19def5`](https://github.com/airbytehq/airbyte/pull/31309/commits/c66f19def5852b9a718e1faa809347b974250c9a)) - ❌

⏲️  Total pipeline duration: 01mn38s 

| Step                                  | Result   |
|:--------------------------------------|:---------|
| Build connector tar                   | ❌        |
| Validate metadata for source-postgres | ✅        |
| Connector version semver check        | ✅        |
| Connector version increment check     | ✅        |
| QA checks                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cdc-postgres-bad-int/1697144667/c66f19def5852b9a718e1faa809347b974250c9a/source-postgres/3.1.12/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:c66f19def5852b9a718e1faa809347b974250c9a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`843f5b2cb6`](https://github.com/airbytehq/airbyte/pull/31309/commits/843f5b2cb684a303d9ceac56a54ce880ae258f59)) - ❌

⏲️  Total pipeline duration: 02mn18s 

| Step                                  | Result   |
|:--------------------------------------|:---------|
| Build connector tar                   | ❌        |
| Validate metadata for source-postgres | ✅        |
| Connector version semver check        | ✅        |
| Connector version increment check     | ✅        |
| QA checks                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cdc-postgres-bad-int/1697149094/843f5b2cb684a303d9ceac56a54ce880ae258f59/source-postgres/3.1.12/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:843f5b2cb684a303d9ceac56a54ce880ae258f59)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres-strict-encrypt test report (commit [`843f5b2cb6`](https://github.com/airbytehq/airbyte/pull/31309/commits/843f5b2cb684a303d9ceac56a54ce880ae258f59)) - ❌

⏲️  Total pipeline duration: 01mn04s 

| Step                                                 | Result   |
|:-----------------------------------------------------|:---------|
| Build connector tar                                  | ❌        |
| Validate metadata for source-postgres-strict-encrypt | ✅        |
| Connector version semver check                       | ✅        |
| QA checks                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cdc-postgres-bad-int/1697149094/843f5b2cb684a303d9ceac56a54ce880ae258f59/source-postgres-strict-encrypt/3.1.12/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:843f5b2cb684a303d9ceac56a54ce880ae258f59)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres-strict-encrypt test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`843f5b2cb6`](https://github.com/airbytehq/airbyte/pull/31309/commits/843f5b2cb684a303d9ceac56a54ce880ae258f59)) - ✅

⏲️  Total pipeline duration: 29mn05s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build connector tar                                             | ✅        |
| Build source-postgres docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                       | ✅        |
| Java Connector Integration Tests                                | ✅        |
| Acceptance tests                                                | ✅        |
| Validate metadata for source-postgres                           | ✅        |
| Connector version semver check                                  | ✅        |
| Connector version increment check                               | ✅        |
| QA checks                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cdc-postgres-bad-int/1697152250/843f5b2cb684a303d9ceac56a54ce880ae258f59/source-postgres/3.1.12/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:843f5b2cb684a303d9ceac56a54ce880ae258f59)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres-strict-encrypt test report (commit [`843f5b2cb6`](https://github.com/airbytehq/airbyte/pull/31309/commits/843f5b2cb684a303d9ceac56a54ce880ae258f59)) - ✅

⏲️  Total pipeline duration: 08mn05s 

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Build connector tar                                                            | ✅        |
| Build source-postgres-strict-encrypt docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                      | ✅        |
| Java Connector Integration Tests                                               | ✅        |
| Acceptance tests                                                               | ✅        |
| Validate metadata for source-postgres-strict-encrypt                           | ✅        |
| Connector version semver check                                                 | ✅        |
| QA checks                                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cdc-postgres-bad-int/1697152250/843f5b2cb684a303d9ceac56a54ce880ae258f59/source-postgres-strict-encrypt/3.1.12/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:843f5b2cb684a303d9ceac56a54ce880ae258f59)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres-strict-encrypt test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres-strict-encrypt test report (commit [`e558bea7e7`](https://github.com/airbytehq/airbyte/pull/31309/commits/e558bea7e712d3821e4aca6f9414a62862e9d868)) - ✅

⏲️  Total pipeline duration: 11mn20s 

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Build connector tar                                                            | ✅        |
| Build source-postgres-strict-encrypt docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                      | ✅        |
| Java Connector Integration Tests                                               | ✅        |
| Acceptance tests                                                               | ✅        |
| Validate metadata for source-postgres-strict-encrypt                           | ✅        |
| Connector version semver check                                                 | ✅        |
| QA checks                                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cdc-postgres-bad-int/1697155781/e558bea7e712d3821e4aca6f9414a62862e9d868/source-postgres-strict-encrypt/3.1.13/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e558bea7e712d3821e4aca6f9414a62862e9d868)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres-strict-encrypt test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`e558bea7e7`](https://github.com/airbytehq/airbyte/pull/31309/commits/e558bea7e712d3821e4aca6f9414a62862e9d868)) - ✅

⏲️  Total pipeline duration: 28mn57s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build connector tar                                             | ✅        |
| Build source-postgres docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                       | ✅        |
| Java Connector Integration Tests                                | ✅        |
| Acceptance tests                                                | ✅        |
| Validate metadata for source-postgres                           | ✅        |
| Connector version semver check                                  | ✅        |
| Connector version increment check                               | ✅        |
| QA checks                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cdc-postgres-bad-int/1697155781/e558bea7e712d3821e4aca6f9414a62862e9d868/source-postgres/3.1.13/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e558bea7e712d3821e4aca6f9414a62862e9d868)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`d94788be03`](https://github.com/airbytehq/airbyte/pull/31309/commits/d94788be03ac5567c618b405dcf5c3c19c338158)) - ✅

⏲️  Total pipeline duration: 29mn58s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build connector tar                                             | ✅        |
| Build source-postgres docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                       | ✅        |
| Java Connector Integration Tests                                | ✅        |
| Acceptance tests                                                | ✅        |
| Validate metadata for source-postgres                           | ✅        |
| Connector version semver check                                  | ✅        |
| Connector version increment check                               | ✅        |
| QA checks                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cdc-postgres-bad-int/1697214701/d94788be03ac5567c618b405dcf5c3c19c338158/source-postgres/3.1.13/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d94788be03ac5567c618b405dcf5c3c19c338158)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres-strict-encrypt test report (commit [`d94788be03`](https://github.com/airbytehq/airbyte/pull/31309/commits/d94788be03ac5567c618b405dcf5c3c19c338158)) - ✅

⏲️  Total pipeline duration: 08mn14s 

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Build connector tar                                                            | ✅        |
| Build source-postgres-strict-encrypt docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                      | ✅        |
| Java Connector Integration Tests                                               | ✅        |
| Acceptance tests                                                               | ✅        |
| Validate metadata for source-postgres-strict-encrypt                           | ✅        |
| Connector version semver check                                                 | ✅        |
| QA checks                                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cdc-postgres-bad-int/1697214701/d94788be03ac5567c618b405dcf5c3c19c338158/source-postgres-strict-encrypt/3.1.13/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d94788be03ac5567c618b405dcf5c3c19c338158)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres-strict-encrypt test
```

**Pull request merged**
