### PR TITLE
CDC sources: avoid busy wait when pushing to queue

### PR DESCRIPTION
**Pull request by edgao**
`queue.put` is equivalent to the while-offer loop, but uses locks to avoid the busy wait. This is a pretty minor optimization for the case where debezium is outpacing our ability to consume records from the queue.

### CODE REVIEW

**Review by tuliren — APPROVED** [review]
Neat!

**Review by ryankfu — APPROVED** [review]
nice performance improvement

**Comment by edgao** [comment]
/publish connector=connectors/source-postgres,connectors/source-postgres-strict-encrypt,connectors/source-mysql,connectors/source-mysql-strict-encrypt parallel=true run-tests=false

**Pull request merged**
