### PR TITLE
source-when-i-work contribution from btkcodedev

### PR DESCRIPTION
**Pull request by btkcodedev**
Closes https://github.com/airbytehq/airbyte-internal-issues/issues/9773
Auto-generated PR by the Connector Builder for source-when-i-work

### CODE REVIEW

**Review by natikgadzhi — APPROVED** [review]
Overall good, we can merge as is or figure out session Authenticator

**Comment by btkcodedev** [comment]
Oh! that could work

**Comment by btkcodedev** [comment]
On it

**Comment by btkcodedev** [comment]
Session Auth added and tested :white_check_mark:

**Pull request merged**
