### PR TITLE
Remove legacy sentry code from java connectors

### PR DESCRIPTION
**Pull request by Phlair**
## What
java connector part of https://github.com/airbytehq/airbyte/issues/13335

## How
Removing code.
I'm not planning to publish new versions of the connectors with this PR as i'm just removing redundant code.

### CODE REVIEW

**Comment by grishick** [comment]
Looks good. Please run integration tests for each of the affected connectors

**Comment by Phlair** [comment]
@grishick tests all looking good, you ok to approve?

**Review by grishick — APPROVED** [review]

**Pull request merged**
