### PR TITLE
🐛 SAT: Update DictWithHash class in test_sequential_reads

### LINKED ISSUE #5735: SAT: TestIncremental.test_two_sequential_reads failed for equal data in array
While testing the new Close.com connector, an error was found in the `test_two_sequential_reads` acceptance test.

There are two equal Records with not sorted data in the "permissions" field
```
{
    'date_created': '0001-01-01T00:00:00',
    'date_updated': '0001-01-01T00:00:00',
    'editable': False,
    'id': 'superuser',
    'name': 'Super User',
    'organization_id': 'orga_ya3w9oMjeLtWe7zFGZr63Dz8ruBbjybG0EIUdUXaESi',
    'permissions': [
      'merge_leads',
      'delete_leads',
      'manage_others_activities',
      'delete_own_activities',
      'call_coach_listen',
      'manage_others_opportunities',
      'manage_customizations',
      'bulk_sequence_subscriptions',
      'delete_own_tasks',
      'bulk_import',
      'manage_group_numbers',
      'bulk_edit',
      'bulk_email',
      'manage_team_smart_views',
      'delete_own_opportunities',
      'call_coach_barge',
      'manage_team_email_templates',
      'manage_email_sequences',
      'calling',
      'export',
      'bulk_delete',
      'manage_others_tasks'
    ]
  } 
```
and 
```
{
    'date_created': '0001-01-01T00:00:00',
    'date_updated': '0001-01-01T00:00:00',
    'editable': False,
    'id': 'superuser',
    'name': 'Super User',
    'organization_id': 'orga_ya3w9oMjeLtWe7zFGZr63Dz8ruBbjybG0EIUdUXaESi',
    'permissions': [
      'call_coach_listen',
      'bulk_import',
      'merge_leads',
      'manage_others_opportunities',
      'delete_leads',
      'delete_own_activities',
      'bulk_edit',
      'bulk_delete',
      'call_coach_barge',
      'export',
      'bulk_sequence_subscriptions',
      'manage_team_email_templates',
      'calling',
      'bulk_email',
      'manage_others_activities',
      'manage_email_sequences',
      'manage_group_numbers',
      'delete_own_tasks',
      'manage_customizations',
      'manage_others_tasks',
      'delete_own_opportunities',
      'manage_team_smart_views'
    ]
  }
```
Test failed due to incorrect hash comparison in `airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/compare.py`.

**Solution**: add one more magic method `__eq__` and wrap `DictWithHash` class to `@functools.total_ordering` decorator.

### PR DESCRIPTION
**Pull request by annalvova05**
## What
Update function for the comparison test with equal data in an array.

## How
Overwrite magic methods in DictWithHash class for `test_sequential_reads` acceptance test. 

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by antixar — APPROVED** [review]
Thanks!

**Comment by sherifnada** [comment]
assigning @keu as SAT empror

**Comment by avida** [comment]
We have unit_tests/  directory with unittests for SAT. Could you test_utils.py file for "serialize" function with this case please?

**Comment by annalvova05** [comment]
> We have unit_tests/ directory with unittests for SAT. Could you add test_utils.py file with test for "serialize" function for this case please?

@avida Thanks! Added tests

**Review by avida — APPROVED** [review]

**Pull request merged**
