### PR TITLE
🐛 Source Strava: fix start date format in manifest

### LINKED ISSUE #41960: [source-strava] unconverted data remains: Z
### Connector Name

source-strava

### Connector Version

0.2.10

### What step the error happened?

During the sync

### Relevant information

Connector tests successfully and I see API calls in my Strava profile. 

### Relevant log output

```shell
source


destination


platform


other

2024-07-15 14:00:57 source > Starting syncing SourceStrava
2024-07-15 14:00:57 source > Marking stream activities as STARTED
2024-07-15 14:00:57 source > Syncing stream: activities 
2024-07-15 14:00:57 source > Encountered an exception while reading stream activities
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 236, in _read_stream
    for record_data_or_message in record_iterator:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/core.py", line 126, in read
    slices = self.stream_slices(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 142, in stream_slices
    return self.retriever.stream_slices()
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 375, in stream_slices
    return self.stream_slicer.stream_slices()
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 168, in stream_slices
    start_datetime = self._calculate_earliest_possible_value(self._select_best_end_datetime())
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 173, in _calculate_earliest_possible_value
    earliest_possible_start_datetime = min(self._start_datetime.get_datetime(self.config), end_datetime)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/datetime/min_max_datetime.py", line 58, in get_datetime
    time = self._parser.parse(str(self.datetime.eval(config, **additional_parameters)), datetime_format)  # type: ignore # datetime is always cast to an interpolated string
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/datetime/datetime_parser.py", line 33, in parse
    parsed_datetime = datetime.datetime.strptime(str(date), format)
  File "/usr/local/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.10/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: Z
2024-07-15 14:00:57 source > Marking stream activities as STOPPED
2024-07-15 14:00:57 source > Finished syncing activities
2024-07-15 14:00:57 source > SourceStrava runtimes:
Syncing stream activities 0:00:00.010146
2024-07-15 14:00:57 source > During the sync, the following streams did not sync successfully: activities: AirbyteTracedException('unconverted data remains: Z')
2024-07-15 14:00:57 source > None
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 8, in <module>
    run()
  File "/airbyte/integration_code/source_strava/run.py", line 14, in run
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py", line 235, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.read(source_spec, config, config_catalog, state))
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py", line 166, in read
    for message in self.source.read(self.logger, config, catalog, state):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py", line 167, in read
    yield from super().read(logger, config, catalog, state)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 184, in read
    raise AirbyteTracedException(message=error_message, failure_type=FailureType.config_error)
airbyte_cdk.utils.traced_exception.AirbyteTracedException: None
```

### Contribute

- [ ] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by data-wrights**
## What
Closes #41960

## How
Manifest was missing the trailing Z in its expected format for UTC 0 offset required by the connector config.

## Review guide
1. manifest.yaml

## User Impact
As far as I can tell the connector did not function at all with the current manifest. This change allows the connector to properly function.

Screenshot testing the connector before the fix is implemented
image

Screenshot testing the connector after the fix is implemented
image

## Can this PR be safely reverted and rolled back?
- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by natikgadzhi — APPROVED** [review]
Thank you! The change looks good. One thing the CI will yell at you about is the changlog entry in `docs/integrations/strava.md` — please add it there. Otherwise, once tests pass, this is good to merge.

**Comment by sql-chris-albert** [comment]
Thanks for the review. Docs have been updated.

**Comment by marcosmarxm** [comment]
Tests failed:
> [35m75:[0m [1.26s] {"type": "TRACE", "trace": {"type": "ERROR", "emitted_at": 1721655585942.7158, "error": **{"message": "During the sync, the following streams did not sync successfully: activities: AirbyteTracedException(\"time data '2016-01-01T00:00:00' does not match format '%Y-%m-%dT%H:%M:%SZ'\")",** "internal_message": null, "stack_trace": "Traceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 8, in <module>\n    run()\n  File \"/airbyte/integration_code/source_strava/run.py\", line 14, in run\n    launch(source, sys.argv[1:])\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py\", line 235, in launch\n    for message in source_entrypoint.run(parsed_args):\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py\", line 122, in run\n    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.read(source_spec, config, config_catalog, state))\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py\", line 166, in read\n    for message in self.source.read(self.logger, config, catalog, state):\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py\", line 167, in read\n    yield from super().read(logger, config, catalog, state)\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py\", line 184, in read\n    raise AirbyteTracedException(message=error_message, failure_type=FailureType.config_error)\nairbyte_cdk.utils.traced_exception.AirbyteTracedException: None\n", "failure_type": "config_error", "stream_descriptor": null}}}

**Comment by sql-chris-albert** [comment]
> Tests failed:
> 
> > �[35m75:�[0m [1.26s] {"type": "TRACE", "trace": {"type": "ERROR", "emitted_at": 1721655585942.7158, "error": **{"message": "During the sync, the following streams did not sync successfully: activities: AirbyteTracedException("time data '2016-01-01T00:00:00' does not match format '%Y-%m-%dT%H:%M:%SZ'")",** "internal_message": null, "stack_trace": "Traceback (most recent call last):\n  File "/airbyte/integration_code/main.py", line 8, in \n    run()\n  File "/airbyte/integration_code/source_strava/run.py", line 14, in run\n    launch(source, sys.argv[1:])\n  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py", line 235, in launch\n    for message in source_entrypoint.run(parsed_args):\n  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py", line 122, in run\n    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.read(source_spec, config, config_catalog, state))\n  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py", line 166, in read\n    for message in self.source.read(self.logger, config, catalog, state):\n  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py", line 167, in read\n    yield from super().read(logger, config, catalog, state)\n  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 184, in read\n    raise AirbyteTracedException(message=error_message, failure_type=FailureType.config_error)\nairbyte_cdk.utils.traced_exception.AirbyteTracedException: None\n", "failure_type": "config_error", "stream_descriptor": null}}}

Not sure where to go from here. [acceptance-test-config.yml](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-strava/acceptance-test-config.yml#L11) has a reference that doesn't exist in the codebase.

**Comment by natikgadzhi** [comment]
We’re a bit backlogged, but I would love to lend a hand when we’re out of
the woods with a couple of internal projects.

Marcos, can you dig in a bit more and see if you can help debug this?

**Comment by marcosmarxm** [comment]
Hello your feedback matters a lot to us. Can you spare just 2 minutes to complete a [survey](https://form.typeform.com/to/DOBqejte)? We’re dedicated to making the contributor experience even better, and your input is key to achieving excellence. Thank you for helping us improve!

**Pull request merged**
