### PR TITLE
Add deployment parameter for AzureOpenAIEmbeddings

### PR DESCRIPTION
**Pull request by hwaxxer**
Just adding the required deployment parameter.

### CODE REVIEW

**Review by flash1293 — APPROVED** [review]
LGTM, thanks for the addition!

**Comment by hwaxxer** [comment]
Use embedders from CDK instead, this closes #29659

**Comment by hwaxxer** [comment]
Alright, I'll open up a new PR to master with CDK embeddings for langchain, and then another PR adding Azure embedders. I removed the other stuff from this PR so this PR only considers the `deployment` config which is necessary for Azure.

**Comment by hwaxxer** [comment]
@flash1293 Maybe I should close this polluted PR :) Your branch and master diverged and I rebased this branch with master which makes this look super messy when it's actually only a few changes. Not sure if it gets fixed if you rebase this branch with master.

Anyway, the deployment parameter still needs to be added, and the `embed_texts` method changed in master since.

**Pull request closed without merging**
