### PR TITLE
[DNM] tests for PR #31535

### PR DESCRIPTION
**Pull request by postamar**
See #31535

This PR exercises the changes in that branch by making no-op changes to source-mysql and source-mssql. Let's see how airbyte-ci handles things.

### CODE REVIEW

**Review by stephane-airbyte — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-mysql test report (commit [`07bf5ec55e`](https://github.com/airbytehq/airbyte/pull/31580/commits/07bf5ec55e9cf9de3c3b801195386812728915a8)) - ❌

⏲️  Total pipeline duration: 20mn54s 

| Step                                                         | Result   |
|:-------------------------------------------------------------|:---------|
| Build connector tar                                          | ✅       |
| Java Connector Unit Tests                                    | ✅       |
| Build source-mysql docker image for platform(s) linux/x86_64 | ✅       |
| Acceptance tests                                             | ✅       |
| Java Connector Integration Tests                             | ✅       |
| Validate metadata for source-mysql                           | ✅       |
| Connector version semver check                               | ✅       |
| Connector version increment check                            | ❌       |
| QA checks                                                    | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/postamar_better-gradle-caching-test-dnm/1697658992/07bf5ec55e9cf9de3c3b801195386812728915a8/source-mysql/3.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:07bf5ec55e9cf9de3c3b801195386812728915a8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-mssql test report (commit [`07bf5ec55e`](https://github.com/airbytehq/airbyte/pull/31580/commits/07bf5ec55e9cf9de3c3b801195386812728915a8)) - ❌

⏲️  Total pipeline duration: 15mn02s 

| Step                                                         | Result   |
|:-------------------------------------------------------------|:---------|
| Build connector tar                                          | ✅       |
| Java Connector Unit Tests                                    | ✅       |
| Build source-mssql docker image for platform(s) linux/x86_64 | ✅       |
| Acceptance tests                                             | ✅       |
| Java Connector Integration Tests                             | ✅       |
| Validate metadata for source-mssql                           | ✅       |
| Connector version semver check                               | ✅       |
| Connector version increment check                            | ❌       |
| QA checks                                                    | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/postamar_better-gradle-caching-test-dnm/1697658992/07bf5ec55e9cf9de3c3b801195386812728915a8/source-mssql/2.0.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:07bf5ec55e9cf9de3c3b801195386812728915a8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mssql test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-mssql test report (commit [`8d54db1139`](https://github.com/airbytehq/airbyte/pull/31580/commits/8d54db1139dfee05ca4ec352f63d8fe88f673345)) - ❌

⏲️  Total pipeline duration: 18mn01s 

| Step                                                         | Result   |
|:-------------------------------------------------------------|:---------|
| Build connector tar                                          | ✅       |
| Java Connector Unit Tests                                    | ✅       |
| Build source-mssql docker image for platform(s) linux/x86_64 | ✅       |
| Acceptance tests                                             | ✅       |
| Java Connector Integration Tests                             | ✅       |
| Validate metadata for source-mssql                           | ✅       |
| Connector version semver check                               | ✅       |
| Connector version increment check                            | ❌       |
| QA checks                                                    | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/postamar_better-gradle-caching-test-dnm/1697661354/8d54db1139dfee05ca4ec352f63d8fe88f673345/source-mssql/2.0.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8d54db1139dfee05ca4ec352f63d8fe88f673345)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mssql test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-mysql test report (commit [`8d54db1139`](https://github.com/airbytehq/airbyte/pull/31580/commits/8d54db1139dfee05ca4ec352f63d8fe88f673345)) - ❌

⏲️  Total pipeline duration: 19mn34s 

| Step                                                         | Result   |
|:-------------------------------------------------------------|:---------|
| Build connector tar                                          | ✅       |
| Java Connector Unit Tests                                    | ✅       |
| Build source-mysql docker image for platform(s) linux/x86_64 | ✅       |
| Acceptance tests                                             | ✅       |
| Java Connector Integration Tests                             | ✅       |
| Validate metadata for source-mysql                           | ✅       |
| Connector version semver check                               | ✅       |
| Connector version increment check                            | ❌       |
| QA checks                                                    | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/postamar_better-gradle-caching-test-dnm/1697661354/8d54db1139dfee05ca4ec352f63d8fe88f673345/source-mysql/3.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8d54db1139dfee05ca4ec352f63d8fe88f673345)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Pull request closed without merging**
