### PR TITLE
🐛 Source Dynamodb: Fix reserved words in expression

### LINKED ISSUE #19739: Source DynamoDB - Reserved Keyword Issue
## Environment
- **Source Connector and version**: dynamodb 0.1.0
- **Step where error happened**:  Sync job 

## Current Behavior
If DynamoDB tables contains any reserved keyword in dynamo expressions it results in this error while running sync.

## Expected Behavior
This should not happen, field_names should be added in dynamo query as placeholder shown in the solution on [StackOverflow](https://stackoverflow.com/questions/36698945/scan-function-in-dynamodb-with-reserved-keyword-as-filterexpression-nodejs)
List of reserved keywords [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ReservedWords.html) 

## Logs

```
2022-11-23 05:35:35 [DEBUG] -
{"type":"TRACE","trace":{"type":"ERROR","emitted_at":1.669181735072E12,"error":{"message":"Something went wrong in the connector. See the logs for more
details.","internal_message":"software.amazon.awssdk.services.dynamodb.model.DynamoDbException: Invalid ProjectionExpression: Attribute name is a reserved keyword; reserved
keyword: name (Service: DynamoDb, Status Code: 400, Request ID:
NHCNIL7CDBVM1ABAU2573P0C4VVV4KQNSO5AEMVJF66Q9ASUAAJG)","stack_trace":"software.amazon.awssdk.services.dynamodb.model.DynamoDbException: Invalid ProjectionExpression: Attribute name is a reserved keyword; reserved
keyword: name (Service: DynamoDb, Status Code: 400, Request ID:
NHCNIL7CDBVM1ABAU2573P0C4VVV4KQNSO5AEMVJF66Q9ASUAAJG)\n\tat
software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)\n\tat
software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)\n\tat
software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)\n\tat
software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)\n\tat
software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)\n\tat
software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)\n\tat
software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)\n\tat
software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)\n\tat
software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)\n\tat
software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)\n\tat
software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)\n\tat
software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)\n\tat
software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)\n\tat
software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)\n\tat
software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)\n\tat
software.amazon.awssdk.services.dynamodb.DefaultDynamoDbClient.scan(DefaultDynamoDbClient.java:4876)\n\tat
software.amazon.awssdk.services.dynamodb.paginators.ScanIterable$ScanResponseFetcher.nextPage(ScanIterable.java:134)\n\tat
software.amazon.awssdk.services.dynamodb.paginators.ScanIterable$ScanResponseFetcher.nextPage(ScanIterable.java:125)\n\tat
software.amazon.awssdk.core.pagination.sync.PaginatedResponsesIterator.next(PaginatedResponsesIterator.java:58)\n\tat
io.airbyte.integrations.source.dynamodb.DynamodbOperations.scanTable(DynamodbOperations.java:139)\n\tat
io.airbyte.integrations.source.dynamodb.DynamodbSource.scanFullRefresh(DynamodbSource.java:181)\n\tat
io.airbyte.integrations.source.dynamodb.DynamodbSource.lambda$read$1(DynamodbSource.java:106)\n\tat
java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\n\tat
java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)\n\tat
java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)\n\tat
java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)\n\tat
java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)\n\tat
java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)\n\tat
java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)\n\tat
java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)\n\tat
java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)\n\tat
io.airbyte.integrations.source.dynamodb.DynamodbSource.read(DynamodbSource.java:108)\n\tat
io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:136)\n\tat
io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:97)\n\tat
io.airbyte.integrations.source.dynamodb.DynamodbSource.main(DynamodbSource.java:46)\n","failure_type":"system_error"}}} 
```

## Are you willing to submit a PR?

I am, but I'm no good at Java. Help would be much appreciated.

### PR DESCRIPTION
**Pull request by itaseskii**
## What
Fixes https://github.com/airbytehq/airbyte/issues/19739

## How

Using placeholders for attributes in the filter expression.

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [x] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Review by vincentkoc — CHANGES_REQUESTED** [review]
Missing the docker version bump and notes

**Comment by koconder** [comment]
@itaseskii can you please update the link in the PR to the exact issue that this is resolving for full context of the change?

**Comment by piyushsingariya** [comment]
> @itaseskii can you please update the link in the PR to the exact issue that this is resolving for full context of the change?

@koconder the PR has been linked to the issue already, could you re-review the PR again?

**Review by vincentkoc — DISMISSED** [review]

**Comment by itaseskii** [comment]
> @itaseskii see publish image error logs, something is not right. Its not liking the code changes for some reason.

@koconder there were some changes in the protocol model which made the connector incompatible. the issue should be fixed now, please try again.

**Comment by renecouto** [comment]
I tried using the connector image built by this PR (version 0.1.1) and still got the same problems. Cases in which the source exits with an exception:
- fields named `name`
- fields starting with underscore: `_fieldName`
- fields with `-` in them: `field-name`

**Comment by itaseskii** [comment]
> I tried using the connector image built by this PR (version 0.1.1) and still got the same problems. Cases in which the source exits with an exception:
> 
>     * fields named `name`
> 
>     * fields starting with underscore: `_fieldName`
> 
>     * fields with `-` in them: `field-name`

@renecouto that is really weird... can you please send me the full stack trace? :)

**Comment by renecouto** [comment]
```
Stack Trace: software.amazon.awssdk.services.dynamodb.model.DynamoDbException: Invalid ProjectionExpression: Attribute name is a reserved keyword; reserved keyword: read (Service: DynamoDb, Status Code: 400, Request ID: C3SPNEI080O2B3F7T2G1V8C65NVV4KQNSO5AEMVJF66Q9ASUAAJG)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.dynamodb.DefaultDynamoDbClient.scan(DefaultDynamoDbClient.java:4876)
	at software.amazon.awssdk.services.dynamodb.paginators.ScanIterable$ScanResponseFetcher.nextPage(ScanIterable.java:134)
	at software.amazon.awssdk.services.dynamodb.paginators.ScanIterable$ScanResponseFetcher.nextPage(ScanIterable.java:125)
	at software.amazon.awssdk.core.pagination.sync.PaginatedResponsesIterator.next(PaginatedResponsesIterator.java:58)
	at io.airbyte.integrations.source.dynamodb.DynamodbOperations.scanTable(DynamodbOperations.java:146)
	at io.airbyte.integrations.source.dynamodb.DynamodbSource.scanFullRefresh(DynamodbSource.java:185)
	at io.airbyte.integrations.source.dynamodb.DynamodbSource.lambda$read$1(DynamodbSource.java:111)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at io.airbyte.integrations.source.dynamodb.DynamodbSource.read(DynamodbSource.java:113)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:138)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:98)
	at io.airbyte.integrations.source.dynamodb.DynamodbSource.main(DynamodbSource.java:50)
```

**Comment by murat-cetinkaya** [comment]
Looking forward to this PR to be merged! Thank you all 🙏🏼

**Comment by koconder** [comment]
@itaseskii is this good to go, what are we waiting for?

**Comment by murat-cetinkaya** [comment]
> > I tried using the connector image built by this PR (version 0.1.1) and still got the same problems. Cases in which the source exits with an exception:
> > ```
> > * fields named `name`
> > 
> > * fields starting with underscore: `_fieldName`
> > 
> > * fields with `-` in them: `field-name`
> > ```
> 
> @renecouto that is really weird... can you please send me the full stack trace? :)

@itaseskii I encountered a similar error and opened [this issue](https://github.com/airbytehq/airbyte/issues/22508). Please let me know if this PR will solve the issue  `fields with `-` in them`  too, so I can close my issue. Thank you 🙏🏼

**Comment by murat-cetinkaya** [comment]
> Hey @murat-cetinkaya 👋 yes! The implementation should cover attribute names having '-' as a special character both when used in the projection and filter expression of the query.

I just noticed it. Thank you for the reply and the fix 🙏🏼

**Comment by murat-cetinkaya** [comment]
[koconder](https://github.com/koconder) any opinion when this PR can be reviewed?

**Review by vincentkoc — APPROVED** [review]

**Comment by koconder** [comment]
Fyi we need to republish the image as changes had to be made again @itaseskii

**Comment by akashkulk** [comment]
FYI you will need to bump up the version and re-publish

**Comment by sh4sh** [comment]
Can we get the merge conflicts resolved, update the branch from master and bump up the version to 0.1.2? I'll rerun the tests and CI and then we can publish/merge the pr

**Comment by murat-cetinkaya** [comment]
Thanks to @itaseskii and @sh4sh  for resolving the conflicts and running the actions. 👏🏼👏🏼
It seems to be waiting for the final review. Does anyone know who can do that? I believe this PR can be merged before the next release.

**Review by sh4sh — CHANGES_REQUESTED** [review]
Please bump the dockerfile version to 0.1.2 (since https://github.com/airbytehq/airbyte/pull/22682 was published as 0.1.1) and update the changelog. Then we should be able to publish the new version and merge

**Comment by itaseskii** [comment]
> Please bump the dockerfile version to 0.1.2 (since #22682 was published as 0.1.1) and update the changelog. Then we should be able to publish the new version and merge

@sh4sh The changelog has already been updated. Shouldn't the Dockerfile be bumped as part of the publishing/releasing processor from the reviewer?

**Comment by sh4sh** [comment]
Sorry about that @itaseskii , I see it now. Thanks very much for the quick reply. Waiting on CI now.

**Review by sh4sh — APPROVED** [review]

**Comment by piyushdatazip** [comment]
CI cleared, Let's get it merged now!

**Comment by Rhiyo** [comment]
Thanks everyone for doing work on this!

**Comment by sh4sh** [comment]
Published but checks failing now... hang on

**Comment by sh4sh** [comment]
Something is amiss with connectors.md that is causing the build to fail. I'll take a look tomorrow morning, for now I have rolled back the above /publish.

**Comment by sh4sh** [comment]
The connectors.md issue was resolved, but now getting `GitHub self-hosted runner registration error` on the Connectors Base: Start Build EC2 Runner step which i think is a transient error. Fortunately the connectors base build passed before so I think we are probably in the clear. Re-running now.

**Comment by sh4sh** [comment]
Please ignore the above message ^ these changes have been merged into source-dynamodb:0.1.2

**Comment by murat-cetinkaya** [comment]
Thanks @sh4sh 👏🏼

**Comment by murat-cetinkaya** [comment]
I upgraded to v0.42 which includes this fix but I'm still getting the same error (`DynamoDbException: Invalid ProjectionExpression: Syntax error; token: "-", `). 
I wonder about your experiences.

**Comment by itaseskii** [comment]
@murat-cetinkaya have you included the attribute name in the config property `reserved_attribute_names`?
https://github.com/airbytehq/airbyte/pull/20172/files#diff-bbb3f5b986d2e1b08e22436ca88d58dc55a6617addd6e2db46051ac8246db33fR58

**Pull request merged**
