### PR TITLE
Source Netsuite: retry with next dateformat in list

### PR DESCRIPTION
**Pull request by ChloeBellm**
## What
[Issue: Netsuite source connector dateformat error](https://github.com/airbytehq/airbyte/issues/21965)

## How
Loops through the possible date formats.

### Community member or Airbyter

- [X] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [X] Secrets in the connector's spec are annotated with `airbyte_secret`
- [X] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [X] Documentation updated
    - [X] Connector's `README.md`
    - [X] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [X] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [X] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Comment by YowanR** [comment]
@bazarnov is this a dupilciate: https://github.com/airbytehq/airbyte/issues/21871

**Comment by bazarnov** [comment]
@YowanR At least 2 different date formats caused the issues:
- `"%d/%m/%Y"` for  https://github.com/airbytehq/airbyte/pull/21971
- `"dd.MM.yy"` for https://github.com/airbytehq/airbyte/issues/21871

I'm afraid there are more of them coming. 

The problem is that we cannot determine the API date format for the request input upfront using REST, as there is no method to fetch this info without accessing the `account` property and details programmatically. 

We can approve and merge these 2 PRs after the code-freeze, but there are tons of other date formats we could not predict customers are using with Netsuite.

**Comment by YowanR** [comment]
Thanks for explaining @ChloeConnor and @bazarnov. For now, let's proceed with these fixes once main is green. We'll assess the next steps here if we see more of these issues cropping up

**Comment by bazarnov** [comment]
Adding @marcosmarxm for the assistance. @marcosmarxm we do need you in this one as well, once the code-freeze ends, please.

**Comment by bazarnov** [comment]
@ChloeConnor are you blocked on this currently? If so, please consider to apply your fix and build the connector locally, if "time is money" for you now, this way you would be able to use the connector, after the code-freeze ends - we are going to merge your contribution. Thank you!

**Comment by rilla** [comment]
Using a trial-and-error approach to determine the input date format by testing against `DateFormatException` may not be a reliable solution. This is because a date like **Dec 1st 2023** could be represented in multiple ways, such as `dd/mm/YY` (01/12/2023) or `mm/dd/YY` (12/01/2023). Both representations are ambiguous and can be parsed incorrectly using either `%d/%m/%Y` or `%m/%d/%Y` without causing an exception.

I've opened #25487 with an alternate approach where the format can be declared as a configurable property in the connector.

**Comment by bmcgilli** [comment]
Hi @ChloeConnor 

I've closed this pull request, as we won't be able to review it in a timely manner.  

For the time being, Airbyte is focused on improving the quality and performance of other connectors and not able to prioritize this PR for Netsuite.  We owe you a response, and unfortunately that is a 'no' to this change, at this time.

In the future, we will definitely focus on improving more connectors such as Netsuite, and welcome PRs from OSS contributors like yourself.  Please be sure to join our slack community so that you'll be able to learn when we are ready for more contributions like this again. We'll keep you in mind for Netsuite improvements in the future. 

Learn more here: https://airbyte.com/blog/upgrading-our-community-pull-requests-experience

**Pull request closed without merging**
