### PR TITLE
🐛 Source Kafka: fix empty airbyte_data after airbyte version 0.50.4 for AvroFormat

### PR DESCRIPTION
**Pull request by carlonuccio**
fixed empty airbyte_data when using AvroFormat

## What
Starting from version 0.50.4, the airbyte_data is empty when using SchemaRegistry Avro Format

## How
Put the json value in the "value" key

## Recommended reading order
1. `AvroFormat.java`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by AmareshB** [comment]
Looks like Airbyte expects `value`  to be the top level key to be present.
I passed in the data as `{"value":{"foo":"bar"}}`  in avro format and the data was parsed correctly and the `airbyte_data` has the data.

**Comment by marcosmarxm** [comment]
Thanks for the contribution @carlonuccio I'll run tests during the week and return to do the review.

**Comment by AmareshB** [comment]
@marcosmarxm does this mean with this change there is no need for the top level `value` key?

**Comment by goromlagche** [comment]
Thanks for the tip. The same problem exists for JsonFormat too. It will be good to get this fixed. :crossed_fingers:

**Comment by marcosmarxm** [comment]
Running CI tests for the changes.

**Review by marcosmarxm — APPROVED** [review]
LGTM

**Pull request merged**
