### PR TITLE
📃 Redesign doc header

### PR DESCRIPTION
**Pull request by timroes**
Redesigns the headers in the doc:

* Changes styling a bit
* Make the "Try Cloud" button more prominent
* Move cloud items to the right side
* Add a GitHub link to the header
* Actually indicate the current cloud status via a small color circle in front of the link
* Remove weird "pseudo centering" of logo

**Before**

**After**

### CODE REVIEW

**Comment by erohmensing** [comment]
The styling looks great! I just realized that I've literally never looked at those top link outs. I don't know why, but I'm not a huge fan of the emojis, maybe because they don't match the rest of the branding? but they make those things I never looked at before stand out more, so I don't have a strong opinion about it.

**Comment by timroes** [comment]
You'd prefer it more that way?

**Comment by nataliekwong** [comment]
Yay styling changes!

Where do we get the icons for the product? Those tend to render more nicely than emojis, maybe we could use them here for the top nav?

**Comment by timroes** [comment]
@nataliekwong so that would look aroundish like this (maybe we'd want to chose different icons):



Given those three options, I'd be against emojis, but have no strong preference between simple icons and no icons at all. Your thoughts?

**Comment by nataliekwong** [comment]
Hm I actually have a slight preference for no icons.

**Comment by timroes** [comment]
Logos removed and some minor adjustments:

**Comment by michel-tricot** [comment]
Any chance we could add a link to Self-managed enterprise as well?

**Review by nataliekwong — APPROVED** [review]

**Pull request merged**
