### PR TITLE
🐛 Source Clickhouse-strict-encrypt: fix tests

### LINKED ISSUE #9105: Source Clickhouse-strict-encrypt: failed ClickHouseStrictEncryptJdbcSourceAcceptanceTest
## Current Behavior
`testSpec() `fails for source Clickhouse-strict-encrypt:

## Logs

<details>
<summary>LOG</summary> 

```

ClickHouseStrictEncryptJdbcSourceAcceptanceTest > testSpec() FAILED
    java.lang.AssertionError: expected:<io.airbyte.protocol.models.ConnectorSpecification@2e66340[documentationUrl=https://docs.airbyte.io/integrations/destinations/clickhouse,changelogUrl=<null>,connectionSpecification=***"$schema":"http://json-schema.org/draft-07/schema#","title":"ClickHouse Source Spec","type":"object","required":["host","port","database","username"],"additionalProperties":false,"properties":***"host":***"description":"Host Endpoint of the Clickhouse Cluster","type":"string"***,"port":***"description":"Port of the database.","type":"integer","minimum":0,"maximum":65536,"default":8123,"examples":["8123"]***,"database":***"description":"Name of the database.","type":"string","examples":["default"]***,"username":***"description":"Username to use to access the database.","type":"string"***,"password":***"description":"Password associated with the username.","type":"string","airbyte_secret":true***,"tunnel_method":***"type":"object","title":"SSH Tunnel Method","description":"Whether to initiate an SSH tunnel before connecting to the database, and if so, which kind of authentication to use.","oneOf":[***"title":"No Tunnel","required":["tunnel_method"],"properties":***"tunnel_method":***"description":"No ssh tunnel needed to connect to database","type":"string","const":"NO_TUNNEL","order":0***,***"title":"SSH Key Authentication","required":["tunnel_method","tunnel_host","tunnel_port","tunnel_user","ssh_key"],"properties":***"tunnel_method":***"description":"Connect through a jump server tunnel host using username and ssh key","type":"string","const":"SSH_KEY_AUTH","order":0***,"tunnel_host":***"title":"SSH Tunnel Jump Server Host","description":"Hostname of the jump server host that allows inbound ssh tunnel.","type":"string","order":1***,"tunnel_port":***"title":"SSH Connection Port","description":"Port on the proxy/jump server that accepts inbound ssh connections.","type":"integer","minimum":0,"maximum":65536,"default":22,"examples":["22"],"order":2***,"tunnel_user":***"title":"SSH Login Username","description":"OS-level username for logging into the jump server host.","type":"string","order":3***,"ssh_key":***"title":"SSH Private Key","description":"OS-level user account ssh key credentials in RSA PEM format ( created with ssh-keygen -t rsa -m PEM -f myuser_rsa )","type":"string","airbyte_secret":true,"multiline":true,"order":4***,***"title":"Password Authentication","required":["tunnel_method","tunnel_host","tunnel_port","tunnel_user","tunnel_user_password"],"properties":***"tunnel_method":***"description":"Connect through a jump server tunnel host using username and password authentication","type":"string","const":"SSH_PASSWORD_AUTH","order":0***,"tunnel_host":***"title":"SSH Tunnel Jump Server Host","description":"Hostname of the jump server host that allows inbound ssh tunnel.","type":"string","order":1***,"tunnel_port":***"title":"SSH Connection Port","description":"Port on the proxy/jump server that accepts inbound ssh connections.","type":"integer","minimum":0,"maximum":65536,"default":22,"examples":["22"],"order":2***,"tunnel_user":***"title":"SSH Login Username","description":"OS-level username for logging into the jump server host","type":"string","order":3***,"tunnel_user_password":***"title":"Password","description":"OS-level password for logging into the jump server host","type":"string","airbyte_secret":true,"order":4***]***,supportsIncremental=<null>,supportsNormalization=false,supportsDBT=false,supportedDestinationSyncModes=[],authSpecification=<null>,advancedAuth=<null>,additionalProperties=***]> but was:<io.airbyte.protocol.models.ConnectorSpecification@6671ec3b[documentationUrl=https://docs.airbyte.io/integrations/destinations/clickhouse,changelogUrl=<null>,connectionSpecification=***"$schema":"http://json-schema.org/draft-07/schema#","title":"ClickHouse Source Spec","type":"object","required":["host","port","database","username"],"additionalProperties":false,"properties":***"host":***"description":"The host endpoint of the Clickhouse cluster.","title":"Host","type":"string"***,"port":***"description":"The port of the database.","title":"Port","type":"integer","minimum":0,"maximum":65536,"default":8123,"examples":["8123"]***,"database":***"description":"The name of the database.","title":"Database","type":"string","examples":["default"]***,"username":***"description":"The username which is used to access the database.","title":"Username","type":"string"***,"password":***"description":"The password associated with this username.","title":"Password","type":"string","airbyte_secret":true***,"tunnel_method":***"type":"object","title":"SSH Tunnel Method","description":"Whether to initiate an SSH tunnel before connecting to the database, and if so, which kind of authentication to use.","oneOf":[***"title":"No Tunnel","required":["tunnel_method"],"properties":***"tunnel_method":***"description":"No ssh tunnel needed to connect to database","type":"string","const":"NO_TUNNEL","order":0***,***"title":"SSH Key Authentication","required":["tunnel_method","tunnel_host","tunnel_port","tunnel_user","ssh_key"],"properties":***"tunnel_method":***"description":"Connect through a jump server tunnel host using username and ssh key","type":"string","const":"SSH_KEY_AUTH","order":0***,"tunnel_host":***"title":"SSH Tunnel Jump Server Host","description":"Hostname of the jump server host that allows inbound ssh tunnel.","type":"string","order":1***,"tunnel_port":***"title":"SSH Connection Port","description":"Port on the proxy/jump server that accepts inbound ssh connections.","type":"integer","minimum":0,"maximum":65536,"default":22,"examples":["22"],"order":2***,"tunnel_user":***"title":"SSH Login Username","description":"OS-level username for logging into the jump server host.","type":"string","order":3***,"ssh_key":***"title":"SSH Private Key","description":"OS-level user account ssh key credentials in RSA PEM format ( created with ssh-keygen -t rsa -m PEM -f myuser_rsa )","type":"string","airbyte_secret":true,"multiline":true,"order":4***,***"title":"Password Authentication","required":["tunnel_method","tunnel_host","tunnel_port","tunnel_user","tunnel_user_password"],"properties":***"tunnel_method":***"description":"Connect through a jump server tunnel host using username and password authentication","type":"string","const":"SSH_PASSWORD_AUTH","order":0***,"tunnel_host":***"title":"SSH Tunnel Jump Server Host","description":"Hostname of the jump server host that allows inbound ssh tunnel.","type":"string","order":1***,"tunnel_port":***"title":"SSH Connection Port","description":"Port on the proxy/jump server that accepts inbound ssh connections.","type":"integer","minimum":0,"maximum":65536,"default":22,"examples":["22"],"order":2***,"tunnel_user":***"title":"SSH Login Username","description":"OS-level username for logging into the jump server host","type":"string","order":3***,"tunnel_user_password":***"title":"Password","description":"OS-level password for logging into the jump server host","type":"string","airbyte_secret":true,"order":4***]***,supportsIncremental=<null>,supportsNormalization=false,supportsDBT=false,supportedDestinationSyncModes=[],authSpecification=<null>,advancedAuth=<null>,additionalProperties=***]>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.airbyte.integrations.io.airbyte.integration_tests.sources.ClickHouseStrictEncryptJdbcSourceAcceptanceTest.testSpec(ClickHouseStrictEncryptJdbcSourceAcceptanceTest.java:145)


```

</details>

## Steps to Reproduce
1. Run ClickHouseStrictEncryptJdbcSourceAcceptanceTest

## Are you willing to submit a PR?

Remove this with your answer.

### PR DESCRIPTION
**Pull request by yurii-bidiuk**
## What
Fixes #9105 

## How
fixed expected_spec.json

## Recommended reading order
1. `expected_spec.json`

## 🚨 User Impact 🚨
There is no user impact

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>

#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by andriikorotkov — APPROVED** [review]

**Review by alexandertsukanov — APPROVED** [review]
LGTM

**Comment by yurii-bidiuk** [comment]
Since it's a minor fix and there is no UX impact, I'll continue publishing and merging without Airbyte review

**Comment by yurii-bidiuk** [comment]
/publish connector=connectors/source-clickhouse-strict-encrypt

**Pull request merged**
