### PR TITLE
:bug: Source Google Ads: fix query template

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/oncall/issues/2393

## How
By making end date **always** be inclusive as well as start date in GAQL queries.

In previous versions there was an inconsistent date slicing which was dependent on a slice size. For slice sizes = 1 day, the sequence was as follows
```
2020-01-01 - 2020-01-02
2020-01-02 - 2020-01-03
2020-01-03 - 2020-01-04
...
```
and the end date was exclusive,

while bigger slices were generated as follows
```
2020-01-01 - 2020-01-03
2020-01-04 - 2020-01-06
2020-01-07 - 2020-01-09
```
with end date and start date inclusive.

In version 0.3.1, I refactored the code so that slice dates would not ever overlap, but did not make sure to make both dates inclusive. Now I have fixed it.

## 🚨 User Impact 🚨
No impact

### CODE REVIEW

**Review by alafanechere — CHANGES_REQUESTED** [review]
@davydov-d can we reproduce the original error of 0.3.1 with a specific config using our test account? If yes I'd love to add this config to `acceptance-test-config.yaml` to assess the fix works and guarantee no future regression.

**Comment by davydov-d** [comment]
@alafanechere according to the current CAT config, this stream is empty. I'll see what we can do, perhaps adding another config with different date-time ranges

**Comment by alafanechere** [comment]
@davydov-d an i[nternal sync](https://cloud.airbyte.com/workspaces/d705a766-e9e3-4689-85cb-52143422317d/connections/edab8673-de1b-4fb9-97ae-f034efc47ec0/job-history#2889625::2) was affected by the 0.3.1 bug. I suggest you copy its connection into a new CAT config, wdyt? 

If we can't do it could you publish a pre-release version for 0.3.2 and try it out on this [connection](https://cloud.airbyte.com/workspaces/d705a766-e9e3-4689-85cb-52143422317d/connections/edab8673-de1b-4fb9-97ae-f034efc47ec0/job-history)?

**Comment by octavia-squidington-iii** [comment]
##  source-google-ads test report (commit [`f2a5e8916c`](https://github.com/airbytehq/airbyte/pull/27835/commits/f2a5e8916cafd173810cbcf2c5325ecd2022aceb)) - ✅

⏲️  Total pipeline duration: 13mn57s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-google-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-google-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_2393-source-google-ads-fix-query-template/1688049857/f2a5e8916cafd173810cbcf2c5325ecd2022aceb/source-google-ads/0.3.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-google-ads test report (commit [`7e30cef7ce`](https://github.com/airbytehq/airbyte/pull/27835/commits/7e30cef7ce68e6da999583254481facd1073b967)) - ✅

⏲️  Total pipeline duration: 13mn42s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-google-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-google-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_2393-source-google-ads-fix-query-template/1688050774/7e30cef7ce68e6da999583254481facd1073b967/source-google-ads/0.3.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-google-ads test report (commit [`4d71f5a25f`](https://github.com/airbytehq/airbyte/pull/27835/commits/4d71f5a25f00c7f2bfd67d997905eed256e6bb81)) - ✅

⏲️  Total pipeline duration: 14mn20s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-google-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-google-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_2393-source-google-ads-fix-query-template/1688381081/4d71f5a25f00c7f2bfd67d997905eed256e6bb81/source-google-ads/0.3.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-ads test
```

**Comment by davydov-d** [comment]
@alafanechere I both added config + catalog to CAT to cover this case and published pre-release version and tested it on internal connection which succeeded: https://cloud.airbyte.com/workspaces/d705a766-e9e3-4689-85cb-52143422317d/connections/edab8673-de1b-4fb9-97ae-f034efc47ec0/job-history#2960833::0

**Review by alafanechere — APPROVED** [review]
Thank you for the thorough testing!

**Pull request merged**
