### PR TITLE
Destinations v2: Do not dedup raw table

### LINKED ISSUE #30710: T&D Should not dedupe raw table (and maintain current CDC delete behavior)
One of the options we have to speed up T&D is to skip deduplication on the raw table, e.g ([code](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/typing_deduping/SnowflakeSqlGenerator.java#L475-L489)):

```sql
DELETE FROM ${raw_table_id}
  WHERE "_airbyte_raw_id" NOT IN (
     SELECT "_AIRBYTE_RAW_ID" FROM ${final_table_id}
  );
```

Working on this story includes:
1. Learning what old normalization did.  I *think* that old normalization did not dedupe the raw table.  This means that we've been comfortable trading increased disk usage for faster performance/lower cost.  I think that, at least for cloud data warehouses, this is a reasonable tradeoff (storage is very cheap, compute is expensive).  As we partition tables by extracted_at, we are already in a good position to ignore old raw records in future T&D runs
2. Confirm that removing the deduplication of the raw tables saves significant time or expense.  We should only do this if there's a clear win here
3. Decide if we disable raw-table-deduplication for all syncs, or if this becomes another advanced option (e.g. https://github.com/airbytehq/airbyte/issues/30454)

### PR DESCRIPTION
**Pull request by edgao**
closes https://github.com/airbytehq/airbyte/issues/30710

Stop deduping the raw table. This necessitates some changes to how T+D works overall. There are also a _huge_ amount of test changes to fix the raw table expectations. (many of these are purely organizational - e.g. combining the dedup/nondedup raw expected records files, since they're now identical)

The final tables remain (almost) identical to previous behavior. The only difference is in how we handle typing failures in the `_ab_cdc_deleted_at` column. Given that connectors generate that column internally (i.e. we have perfect control over it) I don't think that matters.

previous T+D logic:
1. insert new raw records into the final table (`where loaded_at is null OR deleted_at is not null`)
2. delete duplicate records from final table (`where row_number != 1`)
3. delete duplicate records from raw table (`where raw_id not in final_table`)
4. CDC deletes (`where raw_id not in (select from raw_table where deleted_at is not null)`)
5. commit raw table

new logic:
1. insert new raw records into the final table (`(where loaded_at is null OR deleted_at is not null) AND row_number = 1`)
    1. These are now deduped before they even make it to the final table. This isn't strictly necessary yet, but it _will_ be needed for the `merge`-based T+D implementation (where each existing final row must match at most one new raw row).
2. delete duplicate records from final table (`where row_number != 1`)
3. CDC deletes (`where deleted_at is not null`)
    1. This is a significant change from the old logic. Because we're keeping all the old raw records, the logic of deleting records with a deletion raw record is no longer valid.
    2. But we're still behaving correctly. The old deletion tombstone records are reinserted in step 1 on every T+D invocation, so if the deletion record is the most-recent record then we'll still correctly trigger the delete.
    3. This _does_ mean we now only execute CDC deletions if the `cast` call is successful.
4. commit raw table

(upcoming `merge` logic: replace steps 1, 2, and 3 with a single `merge` statement that does an upsert+CDC deletes in one step)

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`73c54e7ea6`](https://github.com/airbytehq/airbyte/pull/31520/commits/73c54e7ea617fbe5bbdf1ff47e012419ee7ef72c)) - ❌

⏲️  Total pipeline duration: 06mn41s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅       |
| Java Connector Unit Tests                                            | ✅       |
| Build destination-bigquery docker image for platform(s) linux/x86_64 | ✅       |
| Java Connector Integration Tests                                     | ✅       |
| Validate metadata for destination-bigquery                           | ✅       |
| Connector version semver check                                       | ✅       |
| Connector version increment check                                    | ❌       |
| QA checks                                                            | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_skip_raw_dedup/1697585259/73c54e7ea617fbe5bbdf1ff47e012419ee7ef72c/destination-bigquery/2.1.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:73c54e7ea617fbe5bbdf1ff47e012419ee7ef72c)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`73c54e7ea6`](https://github.com/airbytehq/airbyte/pull/31520/commits/73c54e7ea617fbe5bbdf1ff47e012419ee7ef72c)) - ❌

⏲️  Total pipeline duration: 06mn26s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅       |
| Java Connector Unit Tests                                             | ✅       |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ✅       |
| Java Connector Integration Tests                                      | ✅       |
| Validate metadata for destination-snowflake                           | ✅       |
| Connector version semver check                                        | ✅       |
| Connector version increment check                                     | ❌       |
| QA checks                                                             | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_skip_raw_dedup/1697585259/73c54e7ea617fbe5bbdf1ff47e012419ee7ef72c/destination-snowflake/3.2.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:73c54e7ea617fbe5bbdf1ff47e012419ee7ef72c)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`5db5b3603e`](https://github.com/airbytehq/airbyte/pull/31520/commits/5db5b3603ef81de4ca49736c56bd9cbe054ccf19)) - ❌

⏲️  Total pipeline duration: 08mn02s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅       |
| Java Connector Unit Tests                                             | ✅       |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ✅       |
| Java Connector Integration Tests                                      | ✅       |
| Validate metadata for destination-snowflake                           | ✅       |
| Connector version semver check                                        | ✅       |
| Connector version increment check                                     | ❌       |
| QA checks                                                             | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_skip_raw_dedup/1697586569/5db5b3603ef81de4ca49736c56bd9cbe054ccf19/destination-snowflake/3.2.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:5db5b3603ef81de4ca49736c56bd9cbe054ccf19)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`5db5b3603e`](https://github.com/airbytehq/airbyte/pull/31520/commits/5db5b3603ef81de4ca49736c56bd9cbe054ccf19)) - ❌

⏲️  Total pipeline duration: 07mn05s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅       |
| Java Connector Unit Tests                                            | ✅       |
| Build destination-bigquery docker image for platform(s) linux/x86_64 | ✅       |
| Java Connector Integration Tests                                     | ✅       |
| Validate metadata for destination-bigquery                           | ✅       |
| Connector version semver check                                       | ✅       |
| Connector version increment check                                    | ❌       |
| QA checks                                                            | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_skip_raw_dedup/1697586569/5db5b3603ef81de4ca49736c56bd9cbe054ccf19/destination-bigquery/2.1.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:5db5b3603ef81de4ca49736c56bd9cbe054ccf19)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`55e5506ca7`](https://github.com/airbytehq/airbyte/pull/31520/commits/55e5506ca7d554316ad475b7c08178ab236945eb)) - ❌

⏲️  Total pipeline duration: 03mn56s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅       |
| Java Connector Unit Tests                                             | ✅       |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ✅       |
| Java Connector Integration Tests                                      | ✅       |
| Validate metadata for destination-snowflake                           | ✅       |
| Connector version semver check                                        | ✅       |
| Connector version increment check                                     | ❌       |
| QA checks                                                             | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_skip_raw_dedup/1697590457/55e5506ca7d554316ad475b7c08178ab236945eb/destination-snowflake/3.2.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:55e5506ca7d554316ad475b7c08178ab236945eb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`55e5506ca7`](https://github.com/airbytehq/airbyte/pull/31520/commits/55e5506ca7d554316ad475b7c08178ab236945eb)) - ❌

⏲️  Total pipeline duration: 08mn18s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅       |
| Java Connector Unit Tests                                            | ✅       |
| Build destination-bigquery docker image for platform(s) linux/x86_64 | ✅       |
| Java Connector Integration Tests                                     | ✅       |
| Validate metadata for destination-bigquery                           | ✅       |
| Connector version semver check                                       | ✅       |
| Connector version increment check                                    | ❌       |
| QA checks                                                            | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_skip_raw_dedup/1697590457/55e5506ca7d554316ad475b7c08178ab236945eb/destination-bigquery/2.1.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:55e5506ca7d554316ad475b7c08178ab236945eb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`55a4470dfb`](https://github.com/airbytehq/airbyte/pull/31520/commits/55a4470dfbcea934504566e58f0ee34381545494)) - ❌

⏲️  Total pipeline duration: 08mn05s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅       |
| Java Connector Unit Tests                                            | ✅       |
| Build destination-bigquery docker image for platform(s) linux/x86_64 | ✅       |
| Java Connector Integration Tests                                     | ✅       |
| Validate metadata for destination-bigquery                           | ✅       |
| Connector version semver check                                       | ✅       |
| Connector version increment check                                    | ❌       |
| QA checks                                                            | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_skip_raw_dedup/1697665251/55a4470dfbcea934504566e58f0ee34381545494/destination-bigquery/2.1.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:55a4470dfbcea934504566e58f0ee34381545494)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`55a4470dfb`](https://github.com/airbytehq/airbyte/pull/31520/commits/55a4470dfbcea934504566e58f0ee34381545494)) - ❌

⏲️  Total pipeline duration: 06mn43s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅       |
| Java Connector Unit Tests                                             | ✅       |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ✅       |
| Java Connector Integration Tests                                      | ✅       |
| Validate metadata for destination-snowflake                           | ✅       |
| Connector version semver check                                        | ✅       |
| Connector version increment check                                     | ❌       |
| QA checks                                                             | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_skip_raw_dedup/1697665251/55a4470dfbcea934504566e58f0ee34381545494/destination-snowflake/3.2.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:55a4470dfbcea934504566e58f0ee34381545494)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by edgao** [comment]
confirmed via manual test that downgrading from this version to current master results in us re-deduping the raw table (i.e. rollback works as expected). (cc @jbfbell )

**Review by gisripa — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`3b60147237`](https://github.com/airbytehq/airbyte/pull/31520/commits/3b601472370c1f59064adaa8d17c4cfe3cbbbf4f)) - ❌

⏲️  Total pipeline duration: 09mn57s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Build connector tar                                                 | ✅       |
| Java Connector Unit Tests                                           | ✅       |
| Build destination-bigquery docker image for platform(s) linux/amd64 | ✅       |
| Java Connector Integration Tests                                    | ✅       |
| Validate metadata for destination-bigquery                          | ✅       |
| Connector version semver check                                      | ✅       |
| Connector version increment check                                   | ❌       |
| QA checks                                                           | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_skip_raw_dedup/1698167047/3b601472370c1f59064adaa8d17c4cfe3cbbbf4f/destination-bigquery/2.1.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:3b601472370c1f59064adaa8d17c4cfe3cbbbf4f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`3b60147237`](https://github.com/airbytehq/airbyte/pull/31520/commits/3b601472370c1f59064adaa8d17c4cfe3cbbbf4f)) - ❌

⏲️  Total pipeline duration: 07mn48s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅       |
| Java Connector Unit Tests                                            | ✅       |
| Build destination-snowflake docker image for platform(s) linux/amd64 | ✅       |
| Java Connector Integration Tests                                     | ✅       |
| Validate metadata for destination-snowflake                          | ✅       |
| Connector version semver check                                       | ✅       |
| Connector version increment check                                    | ❌       |
| QA checks                                                            | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_skip_raw_dedup/1698167047/3b601472370c1f59064adaa8d17c4cfe3cbbbf4f/destination-snowflake/3.2.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:3b601472370c1f59064adaa8d17c4cfe3cbbbf4f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Review by jbfbell — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`b0ca13a992`](https://github.com/airbytehq/airbyte/pull/31520/commits/b0ca13a992504a5bdc0d7b6dfa5dc451b054340a)) - ✅

⏲️  Total pipeline duration: 09mn08s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅       |
| Java Connector Unit Tests                                            | ✅       |
| Build destination-snowflake docker image for platform(s) linux/amd64 | ✅       |
| Java Connector Integration Tests                                     | ✅       |
| Validate metadata for destination-snowflake                          | ✅       |
| Connector version semver check                                       | ✅       |
| Connector version increment check                                    | ✅       |
| QA checks                                                            | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_skip_raw_dedup/1698249769/b0ca13a992504a5bdc0d7b6dfa5dc451b054340a/destination-snowflake/3.3.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b0ca13a992504a5bdc0d7b6dfa5dc451b054340a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Pull request merged**
