### PR TITLE
Run Prettier on md, js, and yml files

### PR DESCRIPTION
**Pull request by natikgadzhi**
## What

This PR is just formatting — result of running prettier on all markdown files, js files, and yml files in the repo. [See more context on Slack](https://airbytehq-team.slack.com/archives/C02TL38U5L7/p1711145270566689). 

The goal is to get all formatting done in one pass so we don't have to get distracted by it in the future PRs.

### CODE REVIEW

**Review by postamar — COMMENTED** [review]
Could you break this down into one PR per filetype?
Also, `airbyte-ci format fix all` doesn't apply to `.yml` files?

**Comment by natikgadzhi** [comment]
I can decouple them, sure — that's why I've put them commit by commit. 

`airbyte format` seems to run `prettier --write . --list-different`, and looking at our `.editorconfig`, that would include yamls. I'm not entirely sure, though.

**Comment by postamar** [comment]
Whoops, sorry didn't notice that

**Review by postamar — APPROVED** [review]
LGTM

**Comment by postamar** [comment]
The .yml files that were touched are in `base-normalization` which will be gone in a quarter or so, so the point is moot. This is fine. Do we need to add anything for `.md` files in `.editorconfig`? If so, it doesn't need to be in this PR (probably shouldn't, in fact).

**Comment by postamar** [comment]
The CI test failures, some of them at least, seem legit. It seems like we make assertions on the contents of some markdown files. These assertions now fail.

**Comment by natikgadzhi** [comment]
1. Removed yml files from this PR.
2. I need to take a look at markdown assertion failures — I'll wait for the CI to run and check out what's up.

**Comment by natikgadzhi** [comment]
Oh gawd, we have tests that indeed depend on markdown format with long strings. https://github.com/airbytehq/airbyte/blob/118a864ea2cb6fb4228b019df32e81f164136789/airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py#L1553

**Comment by natikgadzhi** [comment]
I'll add connector directories to prettier-ignore.

**Comment by postamar** [comment]
> I'll add connector directories to prettier-ignore.

If you do that, check that `airbyte-ci format` isn't affected

**Comment by natikgadzhi** [comment]
Closing in favor of #38032.

**Pull request closed without merging**
