### PR TITLE
🚨🚨✨ Source Trustpilot: migrate to low code

### LINKED ISSUE #30879: TrustPilot

### PR DESCRIPTION
**Pull request by DDynamic**
## What
- Migrate Trustpilot connector to low-code. Closes #30879.

## 🚨 User Impact 🚨
- This PR also streamlines the authentication configuration by requiring an only API key and secret, so the user no longer needs to go through the OAuth flow as a prerequisite. An access token is now retrieved from Trustpilot and is valid for 4 days, at which a new access token will be requested using the client ID / secret. A client_credentials grant does not provide a refresh token. https://documentation-apidocumentation.trustpilot.com/authentication#client-credentials

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by natikgadzhi** [comment]
I'm so sorry for the delay here ;-( @DDynamic would you be open to rebasing this? This actually looks pretty good, and we've improved our CI since December, so I think we could get this in rather quickly if you clean it up a bit.

**Comment by DDynamic** [comment]
@natikgadzhi no problem, I went ahead and rebased today.

**Comment by natikgadzhi** [comment]
Thank you! Let me run tests on this real quick

**Comment by DDynamic** [comment]
@natikgadzhi any update?

**Comment by marcosmarxm** [comment]
closing in favor of https://github.com/airbytehq/airbyte/pull/36955

**Pull request closed without merging**
