### PR TITLE
✨Source Klaviyo: make start_date optional

### PR DESCRIPTION
**Pull request by askarpets**
## What

- Make `start_date` config parameter optional
- Add a descriptive message in case a code of 401 or 403 is received on check connection

## How
Mark the field as optional in the `spec.json` file and align `streams.py`

## Recommended reading order
1. `spec.json`
2. `source.py`
3. `streams.py`

## 🚨 User Impact 🚨
No breaking changes

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-klaviyo test report (commit [`897be5ab4e`](https://github.com/airbytehq/airbyte/pull/31710/commits/897be5ab4e34d069a78f7c207d2c74bddc4320f6)) - ❌

⏲️  Total pipeline duration: 02mn58s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Build source-klaviyo docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                    | ✅       |
| Acceptance tests                                              | ✅       |
| Check our base image is used                                  | ✅       |
| Code format checks                                            | ❌       |
| Validate metadata for source-klaviyo                          | ✅       |
| Connector version semver check                                | ✅       |
| Connector version increment check                             | ✅       |
| QA checks                                                     | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sourceklaviyo-start-date-optional/1698075849/897be5ab4e34d069a78f7c207d2c74bddc4320f6/source-klaviyo/1.1.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:897be5ab4e34d069a78f7c207d2c74bddc4320f6)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-klaviyo test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-klaviyo test report (commit [`912a7218cd`](https://github.com/airbytehq/airbyte/pull/31710/commits/912a7218cdbb030fc61b6b810acb886fd61ec7c1)) - ✅

⏲️  Total pipeline duration: 03mn02s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Build source-klaviyo docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                    | ✅       |
| Acceptance tests                                              | ✅       |
| Check our base image is used                                  | ✅       |
| Code format checks                                            | ✅       |
| Validate metadata for source-klaviyo                          | ✅       |
| Connector version semver check                                | ✅       |
| Connector version increment check                             | ✅       |
| QA checks                                                     | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sourceklaviyo-start-date-optional/1698077361/912a7218cdbb030fc61b6b810acb886fd61ec7c1/source-klaviyo/1.1.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:912a7218cdbb030fc61b6b810acb886fd61ec7c1)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-klaviyo test
```

**Review by bazarnov — APPROVED** [review]

**Review by davydov-d — CHANGES_REQUESTED** [review]
let's add a parametrized unit test covering all these changes please

**Review by davydov-d — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-klaviyo test report (commit [`3305c043f1`](https://github.com/airbytehq/airbyte/pull/31710/commits/3305c043f14fb06ff5cdc87ccf32b836c11a588d)) - ✅

⏲️  Total pipeline duration: 04mn00s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Build source-klaviyo docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                    | ✅       |
| Acceptance tests                                              | ✅       |
| Check our base image is used                                  | ✅       |
| Code format checks                                            | ✅       |
| Validate metadata for source-klaviyo                          | ✅       |
| Connector version semver check                                | ✅       |
| Connector version increment check                             | ✅       |
| QA checks                                                     | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sourceklaviyo-start-date-optional/1698135465/3305c043f14fb06ff5cdc87ccf32b836c11a588d/source-klaviyo/1.1.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:3305c043f14fb06ff5cdc87ccf32b836c11a588d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-klaviyo test
```

**Pull request merged**
