### PR TITLE
🪟 🐛 Update `<ConditionSection />` to update values after form validation is updated

### LINKED ISSUE #12457: Empty config objects inside oneOfs cannot be saved
When I create a destination-snowflake connector using the `AWS S3 Staging` mode, then refresh the page and try to switch to the `[Recommended] Internal Staging` option, the `Save changes and retest` button remains grayed out:
Screen Shot 2022-04-28 at 3 07 25 PM

The spec, for reference (this is on master): https://github.com/airbytehq/airbyte/blob/e3bcbc86ca223c5a85e5b313290ebdc2db3621cc/airbyte-integrations/connectors/destination-snowflake/src/main/resources/spec.json#L145-L157

This seems to happen for any empty object inside a oneOf, e.g. I see the same behavior on a [branch](https://github.com/airbytehq/airbyte/pull/12452) where I've added another empty object: https://github.com/airbytehq/airbyte/blob/2e14eacdb5b00aa7386a243e968bc5000a355606/airbyte-integrations/connectors/destination-snowflake/src/main/resources/spec.json#L258-L271

### PR DESCRIPTION
**Pull request by edmundito**
## What
Fixes #12457 

This updates the `ConditionSection` component only to update the value after form validation has been set because otherwise, it tries to validate the fields before the validation is updated. This case is specific to when the condition has no values to fill out.

## How
In the `ConditionSection` component, both the form `value` and `widgetsInfo` would be updated one after the other. When `widgetsInfo` is updated, it updates the form validation because the form shape has changed (from the previously selected condition to the new one). Now it re-runs validation after `widgetsInfo` updates the component flagged for re-validation.

## Recommended reading order
- One file to read

## Tests

- Tested on snowflake destination

### CODE REVIEW

**Review by teallarson — APPROVED** [review]
Code LGTM. I can't get a Snowflake/S3 destination set up with the credentials in lastpass so have not tested the usecase from the original issue.

**Comment by timroes** [comment]
When I reviewed this, I was thinking: Don't we have code that does exactly that revalidation of a form when the validation schema changes, and came across: https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/views/Connector/ServiceForm/useBuildForm.tsx#L127-L129

Digging a bit deeper, it seems this does currently not work because of a Formik bug (https://github.com/jaredpalmer/formik/issues/2092) that simply always returns `undefined` when trying to get the validationSchema from the formik context (no matter that there is actually a proper validationSchema).

I opened a PR trying to fix that high-level code: https://github.com/airbytehq/airbyte/pull/15109 which could superseed this PR. From what I've tested this should fix the problem as well, and gets rid of the high level non-working code anymore (in `useBuildForm`). Could you maybe double check if that fixes the same issue, and if we can superseed this PR by #15109?

**Comment by timroes** [comment]
Digging into this I also created https://github.com/airbytehq/airbyte/issues/15108, which I believe is what we should eventually trying to go for and not have validationSchemas changing over time.

**Comment by edmundito** [comment]
Replaced by #15109 - Tested after merge and fixes the issue.

**Pull request closed without merging**
