### PR TITLE
Octavia CLI: fix help message in commands

### PR DESCRIPTION
**Pull request by BenoitFayolle**
Fix typo in octavia generate connection CLI help strings

## What 
typo in octavia generate connection CLI help strings

## How
change "fine" into "file"

## 🚨 User Impact 🚨
no break

### CODE REVIEW

**Review by juweins — APPROVED** [review]
Hey @BenoitFayolle ! Thanks for this input! 💪🏽

Make sure to sign the CLA in order to process this PR!

LGTM, @marcosmarxm

**Review by marcosmarxm — APPROVED** [review]
Thanks @BenoitFayolle

**Comment by octavia-approvington** [comment]
After a careful ML study, <br/> we think this looks okay.  <br/> imagine code being okay

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
