### PR TITLE
Bnchrch/metadata/add missing metadata files

### PR DESCRIPTION
**Pull request by bnchrch**
## What
This hopefully is the last manual metadata file update

In this PR we
1. Brought existing metadata files up to date with their registry equivalents
2. Added a couple of new metadata files that had bee missed when adding new connectors
3. Removed the ghc.io and faros connectors as they already exist in the [third party folder](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/third-party)
4. Mark the metadata validation as required for all connector folders (also added it to required checks in the github UI

After these changes the diffs are
1. [oss](https://storage.googleapis.com/prod-airbyte-cloud-connector-metadata-service/generated_reports/dev/oss_registry_diff_report.json)
2. [cloud](https://storage.googleapis.com/prod-airbyte-cloud-connector-metadata-service/generated_reports/dev/cloud_registry_diff_report.json)

## Note for reviewers
These are mostly harmless updates as the registry is not yet in use

### CODE REVIEW

**Comment by bnchrch** [comment]
@airbytehq/dbsources @airbytehq/destinations just a heads up this is a PR to update the new metadata files (likely the last time) so that the new registry is identical to the old registry.

No changes have been made to the connector itself and merging this PR wont publish new connectors

**Comment by bnchrch** [comment]
Validation ran locally
image

But [failed in ci](https://github.com/airbytehq/airbyte/actions/runs/4919358803/jobs/8786874198?pr=25899)

[Rerunning](https://github.com/airbytehq/airbyte/actions/runs/4919358803) flaky pipeline. cc: @cpdeethree @alafanechere

**Comment by octavia-approvington** [comment]
Lets do it! <br/> giddddy-up

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
