### PR TITLE
✨Source S3 (v4): Set decimal_as_float to True for parquet files

### LINKED ISSUE #29227: S3 source: Legacy parquet configs should set decimal_as_float to True
## What
The CDK parquet parser converts decimal fields to string by default to ensure there is no loss in precision.

The legacy S3 source returns decimal fields as numbers.

Legacy parquet configs should be adapted to set decimal_as_float to True

## Acceptance criteria
- [ ] Legacy S3 avro configs set decimal_as_float to True

### PR DESCRIPTION
**Pull request by girarda**
## What
* Set `decimal_as_float` on ParquetFormat for backwards compatibility
* Closes https://github.com/airbytehq/airbyte/issues/29227

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`f9fc565b24`](https://github.com/airbytehq/airbyte/pull/29342/commits/f9fc565b246d76849466f9b8744cb6e3f53d278c)) - ❌

⏲️  Total pipeline duration: 22mn21s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ❌        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ❌        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_s3_parquet_adapter/1691764384/f9fc565b246d76849466f9b8744cb6e3f53d278c/source-s3/3.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f9fc565b246d76849466f9b8744cb6e3f53d278c)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`8c2572823f`](https://github.com/airbytehq/airbyte/pull/29342/commits/8c2572823f077d7db90394f5dbfe14095e9eec75)) - ❌

⏲️  Total pipeline duration: 11mn05s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ❌        |
| Connector version increment check                                | ❌        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_s3_parquet_adapter/1691769969/8c2572823f077d7db90394f5dbfe14095e9eec75/source-s3/3.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8c2572823f077d7db90394f5dbfe14095e9eec75)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by girarda** [comment]
Noting that CATs are failing because the PR isn't based off an updated master (see https://airbytehq-team.slack.com/archives/C02UF50V9HA/p1691765570710209)

**Review by clnoll — APPROVED** [review]
⛴!

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`5b0c44fa98`](https://github.com/airbytehq/airbyte/pull/29342/commits/5b0c44fa982865995fff15f6df33dce45ed57fc3)) - ❌

⏲️  Total pipeline duration: 11mn42s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ❌        |
| Connector version increment check                                | ❌        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_s3_parquet_adapter/1692039885/5b0c44fa982865995fff15f6df33dce45ed57fc3/source-s3/3.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:5b0c44fa982865995fff15f6df33dce45ed57fc3)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`408f9605bc`](https://github.com/airbytehq/airbyte/pull/29342/commits/408f9605bcfb24b4ca83df9edb121b8b24022ab9)) - ❌

⏲️  Total pipeline duration: 13mn38s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ❌        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_s3_parquet_adapter/1692054225/408f9605bcfb24b4ca83df9edb121b8b24022ab9/source-s3/3.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:408f9605bcfb24b4ca83df9edb121b8b24022ab9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-approvington** [comment]
Our work here is done <br/> done

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
