### PR TITLE
rollback source-github to 1.5.7

### PR DESCRIPTION
**Pull request by pedroslopez**
## What

Cloud rollback for https://github.com/airbytehq/oncall/issues/4240

### CODE REVIEW

**Comment by pedroslopez** [comment]
> /approve-and-merge reason="rollback connector for OC"

Is this restricted now or am I doing it wrong?

**Comment by octavia-approvington** [comment]
Myomoto says it looks good <br/> thats a niiice

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
