### PR TITLE
🐛 source-google-sheets: correctly fails syncs when rate limit has been reached

### PR DESCRIPTION
**Pull request by henriquemeloo**
## What
* Google Sheets syncs would eventually silently fail due to rate limits being simply logged, and not raising an exception. This would lead to an incomplete sync marked as "Success".
* Related issue: https://github.com/airbytehq/airbyte/issues/36900

## How
* Raises an error when rate limits are reached instead of just logging.

## Review guide
1. `airbyte-integrations/connectors/source-google-sheets/source_google_sheets/source.py`
2. `airbyte-integrations/connectors/source-google-sheets/unit_tests/test_stream.py`

## User Impact
* No more incomplete syncs due to rate limits will be marked as "Success"

## Can this PR be safely reverted and rolled back?
- [X] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by marcosmarxm — COMMENTED** [review]
Running CI tests, please don't update your branch until request. @henriquemeloo the changes look good but need final approval from the connector team.

**Comment by marcosmarxm** [comment]
Tests are green. Now it need final review from the connector team, @airbytehq/dev-python can someone take a look into this change?

**Review by bazarnov — APPROVED** [review]

**Comment by henriquemeloo** [comment]
@marcosmarxm looks like this is approved. Do you need any more actions on my side on this?

**Comment by henriquemeloo** [comment]
@marcosmarxm this now has conflicts. Do I resolve them myself? Besides that, do I need to complete anything else here?

**Comment by marcosmarxm** [comment]
@henriquemeloo can you resolve them I'm going to ask the connector team take a look and final approval and merge your change.

**Comment by henriquemeloo** [comment]
@marcosmarxm done

**Comment by marcosmarxm** [comment]
@henriquemeloo there is a small block to run regression tests in fork. The team is working to fix them and unblock to merge your contribution. Need to wait 📦

**Comment by marcosmarxm** [comment]
Hello your feedback matters a lot to us. Can you spare just 2 minutes to complete a [survey](https://form.typeform.com/to/DOBqejte)? We’re dedicated to making the contributor experience even better, and your input is key to achieving excellence. Thank you for helping us improve!

**Pull request merged**
