### PR TITLE
Set isResumeable flag in catalog

### PR DESCRIPTION
**Pull request by xiaohansong**
## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by rodireich** [comment]
Looks good to me
Question: one existing connections, will upgrade be seamless? upon first discover the saved catalog will be updated with `isResumable` flag?
Or user intervention needed/

Same question for roll back - any intervention needed?

**Comment by xiaohansong** [comment]
@rodireich I think rolling forward or back shouldn't impact us. We are not using that field on sources side, and platform will always accept this field (since they are not rolling back)

**Review by rodireich — APPROVED** [review]

**Comment by xiaohansong** [comment]
Will merge this on Thursday morning (may.30th). Ping me if I blocked you!

**Pull request merged**
