### PR TITLE
✨ Source S3: Add `region` to config

### LINKED ISSUE #20860: Enable to choose non-AWS regions in S3 Connector
## Environment
- **Airbyte version**:  0.40.25
- **OS Version / Instance**:  Ubuntu 22.10
- **Deployment**: Kubernetes deploy env via helm
- **Destination Connector and version**: S3
- **Step where error happened**: Destination Creation

## Current Behavior
When creating a destination to a S3 bucket that is not on AWS, it allows to provide a custom endpoint, but it forces you to select a region from AWS.
In my specific example Im trying to create a connection a OVHcloud S3 bucket (https://www.ovhcloud.com/en/public-cloud/object-storage/) with endpoint https://s3.gra.io.cloud.ovh.net/ where the region is "gra" (Graveline).

Error message is :

## Expected Behavior
Interface should allow to either choose a non-AWS region, or not propose a fixed list (which may become quickly obsolete each time AWS adds a region) or bypass the selected region if custom endpoint is entered (and contains the region).

## Logs
_

> the connection tests failed.
> Could not connect to the S3 bucket with the provided configuration. The authorization header is malformed; the region '' is wrong; expecting 'gra' (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: txbf1ce5f2a868480aac030-0063a5ac34; S3 Extended Request ID: null; Proxy: null)

_

## Steps to Reproduce
1. Start creating a connection to a  S3 destination
2. See that you can only choose a Region from a limited list of AWS region.
3. See that even if you enter a non-aws end point, the connection fails due to wrong region (see error message).

## Are you willing to submit a PR?
No, simply because I do not have the competence to code the solution.

### PR DESCRIPTION
**Pull request by hawkaa**
Fixes airbytehq/airbyte#20860

## What
Adds support for specifying region as a part of specifying the S3 source connector.

Screenshot 2023-10-23 at 12 36 04

## How
Adds a new config item and passes it to the S3 client.

## 🚨 User Impact 🚨
No breaking changes. The new field is optional

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks for the contribution @hawkaa sorry the lack of update. Are you still interested in continuing the contribution?

**Comment by hawkaa** [comment]
> Thanks for the contribution @hawkaa sorry the lack of update. Are you still interested in continuing the contribution?

Yeah, would love to! What's next? I assume that I need to rebase the changes at the very least?

**Comment by marcosmarxm** [comment]
> > Thanks for the contribution @hawkaa sorry the lack of update. Are you still interested in continuing the contribution?
> 
> Yeah, would love to! What's next? I assume that I need to rebase the changes at the very least?

Yes please.

**Comment by hawkaa** [comment]
> > > Thanks for the contribution @hawkaa sorry the lack of update. Are you still interested in continuing the contribution?
> > 
> > 
> > Yeah, would love to! What's next? I assume that I need to rebase the changes at the very least?
> 
> Yes please.

Done!

**Comment by tolik0** [comment]
@hawkaa, Could you please update your branch to the latest version? It would be best if you also populated the AWS region for the IAM client.

**Comment by hawkaa** [comment]
> @hawkaa, Could you please update your branch to the latest version? It would be best if you also populated the AWS region for the IAM client.

Done!

**Comment by tolik0** [comment]
@hawkaa [The PR](https://github.com/airbytehq/airbyte/pull/34842) with your changes is merged. Thank you for your contribution!

**Pull request closed without merging**
