### PR TITLE
Fix Mongo dest

### PR DESCRIPTION
**Pull request by benmoriceau**
## What
make the mongoDB to emit all the state

### CODE REVIEW

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Comment by benmoriceau** [comment]
> /publish connector=connectors/mongodb

Made a mistake by running publish instead of test, will cancel once launched

**Comment by benmoriceau** [comment]
/publish connector=connectors/destination-mongodb-strict-encrypt

**Comment by benmoriceau** [comment]
/publish connector=connectors/destination-mongodb-strict-encrypt

**Comment by benmoriceau** [comment]
/publish connector=connectors/destination-mongodb-strict-encrypt

**Pull request merged**
