### PR TITLE
Destination S3: Adapt kotlin CDK

### PR DESCRIPTION
**Pull request by gisripa**

### CODE REVIEW

**Comment by gisripa** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/36869?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#36869** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/36869?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#36868** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/36868?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @gisripa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by evantahler — COMMENTED** [review]
Double checking that moving to the new CDK doesn't implicitly add support for the Async framework or anything like that... that's a future project, yes?

**Review by edgao — APPROVED** [review]

**Comment by gisripa** [comment]
> Double checking that moving to the new CDK doesn't implicitly add support for the Async framework or anything like that... that's a future project, yes?

@evantahler  Yes. well its not even an straightforward feat, our "Async" framework only works with the assumption of CSV Buffers atm.

**Comment by gisripa** [comment]
[Parquet Run](https://cloud.airbyte.com/workspaces/2c817306-57f8-4b59-bf34-d8784680946c/connections/ee67f94f-8465-4011-a89b-b210597ed92c/job-history#10240560::0)
[Avro Run](https://cloud.airbyte.com/workspaces/2c817306-57f8-4b59-bf34-d8784680946c/connections/5952da24-9340-4401-a750-9b6c9e436107/job-history#10239346::0)
[CSV Run](https://cloud.airbyte.com/workspaces/2c817306-57f8-4b59-bf34-d8784680946c/connections/6973ea38-a151-4c72-a866-44891103a838/job-history#10239081::0)

**Pull request merged**
