### PR TITLE
Source Salesforce: fix properties chunk length count

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/airbyte/issues/20703
_**this is a followup for oncall https://github.com/airbytehq/oncall/issues/1403**_
## How
When counting the length of the URL we should take into account that properties and the separator will be URL-encoded

### CODE REVIEW

**Review by bazarnov — APPROVED** [review]

**Review by lazebnyi — APPROVED** [review]

**Comment by davydov-d** [comment]
temporary unable to publish changes because of exceeding the rate limit 
image

**Comment by davydov-d** [comment]
this is a followup for oncall https://github.com/airbytehq/oncall/issues/1403

**Review by lazebnyi — APPROVED** [review]
CI tests looks good. We can move next to fix issue related to on-call issue. LGTM!

**Review by bazarnov — APPROVED** [review]

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
