### PR TITLE
Salesforce, Marketo, and Hubspot connector license to Elv2

### PR DESCRIPTION
**Pull request by evantahler**
See https://github.com/airbytehq/airbyte/issues/27724

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`6dfd6faf0c`](https://github.com/airbytehq/airbyte/pull/27726/commits/6dfd6faf0c3c07380ec0d306f1cef6ab9367aa5d)) - ❌

⏲️  Total pipeline duration: 823 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-hubspot-salseforce-marketo/1687821119/6dfd6faf0c3c07380ec0d306f1cef6ab9367aa5d/source-hubspot/0.9.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by octavia-squidington-iii** [comment]
##  source-marketo test report (commit [`6dfd6faf0c`](https://github.com/airbytehq/airbyte/pull/27726/commits/6dfd6faf0c3c07380ec0d306f1cef6ab9367aa5d)) - ✅

⏲️  Total pipeline duration: 4854 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-marketo/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-marketo docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-hubspot-salseforce-marketo/1687821119/6dfd6faf0c3c07380ec0d306f1cef6ab9367aa5d/source-marketo/1.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-marketo test
```

**Comment by evantahler** [comment]
Note: Source hubspot tests are failing on master

**Comment by octavia-squidington-iii** [comment]
##  source-salesforce test report (commit [`6dfd6faf0c`](https://github.com/airbytehq/airbyte/pull/27726/commits/6dfd6faf0c3c07380ec0d306f1cef6ab9367aa5d)) - ✅

⏲️  Total pipeline duration: 9794 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-salesforce/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-salesforce docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Integration tests                                                        | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-hubspot-salseforce-marketo/1687821119/6dfd6faf0c3c07380ec0d306f1cef6ab9367aa5d/source-salesforce/2.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-salesforce test
```

**Comment by evantahler** [comment]
/accept-and-merge message="connector licenses to Elv2 - hubspot tests are already failing on master"

**Comment by octavia-approvington** [comment]
This is really good <br/> simply the best

**Review by octavia-approvington — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`afab1a4379`](https://github.com/airbytehq/airbyte/pull/27726/commits/afab1a4379387142c4915b6c568979516171821a)) - ❌

⏲️  Total pipeline duration: 668 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ❌        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-hubspot-salseforce-marketo/1687849867/afab1a4379387142c4915b6c568979516171821a/source-hubspot/0.9.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by octavia-squidington-iii** [comment]
##  source-marketo test report (commit [`afab1a4379`](https://github.com/airbytehq/airbyte/pull/27726/commits/afab1a4379387142c4915b6c568979516171821a)) - ❌

⏲️  Total pipeline duration: 4806 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-marketo/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ❌        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-marketo docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-hubspot-salseforce-marketo/1687849867/afab1a4379387142c4915b6c568979516171821a/source-marketo/1.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-marketo test
```

**Comment by octavia-squidington-iii** [comment]
##  source-salesforce test report (commit [`afab1a4379`](https://github.com/airbytehq/airbyte/pull/27726/commits/afab1a4379387142c4915b6c568979516171821a)) - ❌

⏲️  Total pipeline duration: 5611 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-salesforce/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-salesforce docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Integration tests                                                        | ✅        |
| Acceptance tests                                                         | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-hubspot-salseforce-marketo/1687849867/afab1a4379387142c4915b6c568979516171821a/source-salesforce/2.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-salesforce test
```

**Pull request merged**
