### PR TITLE
Source SalesForce: update service level

### PR DESCRIPTION
**Pull request by artem1205**
## What
update service elvel

## How
update metadata

## Recommended reading order
1. `metadata.yaml`

## 🚨 User Impact 🚨
no breaking changes

## Pre-merge Actions
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Review by bnchrch — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-salesforce test report (commit [`2fd9e4155c`](https://github.com/airbytehq/airbyte/pull/29403/commits/2fd9e4155c8030c30b38c7e2ac41c75c94ad783e)) - ❌

⏲️  Total pipeline duration: 57mn45s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-salesforce/metadata.yaml | ❌        |
| Connector version semver check                                           | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-salesforce docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Integration tests                                                        | ✅        |
| Acceptance tests                                                         | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-salesforce-update-internal-sl/1692032047/2fd9e4155c8030c30b38c7e2ac41c75c94ad783e/source-salesforce/2.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:2fd9e4155c8030c30b38c7e2ac41c75c94ad783e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-salesforce test
```

**Comment by artem1205** [comment]
@bnchrch , I guess we're a little rushed with changes, as metadata validation tests failed:

> Validating metadata.yaml...
metadata.yaml is not a valid ConnectorMetadataDefinitionV0 YAML file.
Validation error: 1 validation error for ConnectorMetadataDefinitionV0
data -> ab_internal -> sl
  unexpected value; permitted: 100, 200, 300 (type=value_error.const; given=400; permitted=(100, 200, 300))

**Comment by bnchrch** [comment]
@artem1205 Ah! I had made a mistake in the docs.

We should be changing `data.ab_internal.ql` to 400

not `data.ab_internal.sl`

**Comment by octavia-squidington-iii** [comment]
##  source-salesforce test report (commit [`51d5b98a47`](https://github.com/airbytehq/airbyte/pull/29403/commits/51d5b98a47ca4bac048b69734e6db0604d4cc2ac)) - ✅

⏲️  Total pipeline duration: 85mn14s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-salesforce/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-salesforce docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Integration tests                                                        | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-salesforce-update-internal-sl/1692037794/51d5b98a47ca4bac048b69734e6db0604d4cc2ac/source-salesforce/2.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:51d5b98a47ca4bac048b69734e6db0604d4cc2ac)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-salesforce test
```

**Pull request merged**
