### PR TITLE
:sparkles: Source TikTok Marketing: use default availability strategy

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/airbyte/issues/22272

## How
Use the default availability strategy

### CODE REVIEW

**Review by tolik0 — APPROVED** [review]

**Review by bazarnov — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-tiktok-marketing test report (commit [`d0741a40b6`](https://github.com/airbytehq/airbyte/pull/31537/commits/d0741a40b6e10a4fea4d7b0bed6c017112244837)) - ❌

⏲️  Total pipeline duration: 43mn40s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Build source-tiktok-marketing docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                              | ✅       |
| Acceptance tests                                                        | ❌       |
| Code format checks                                                      | ✅       |
| Validate metadata for source-tiktok-marketing                           | ✅       |
| Connector version semver check                                          | ✅       |
| Connector version increment check                                       | ✅       |
| QA checks                                                               | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_22272-source-tiktok-use-default-availability-strategy/1697627182/d0741a40b6e10a4fea4d7b0bed6c017112244837/source-tiktok-marketing/3.6.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d0741a40b6e10a4fea4d7b0bed6c017112244837)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-tiktok-marketing test report (commit [`d0741a40b6`](https://github.com/airbytehq/airbyte/pull/31537/commits/d0741a40b6e10a4fea4d7b0bed6c017112244837)) - ❌

⏲️  Total pipeline duration: 16mn05s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Build source-tiktok-marketing docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                              | ✅       |
| Acceptance tests                                                        | ❌       |
| Code format checks                                                      | ✅       |
| Validate metadata for source-tiktok-marketing                           | ✅       |
| Connector version semver check                                          | ✅       |
| Connector version increment check                                       | ✅       |
| QA checks                                                               | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_22272-source-tiktok-use-default-availability-strategy/1697632410/d0741a40b6e10a4fea4d7b0bed6c017112244837/source-tiktok-marketing/3.6.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d0741a40b6e10a4fea4d7b0bed6c017112244837)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-tiktok-marketing test report (commit [`49b7cbd5ab`](https://github.com/airbytehq/airbyte/pull/31537/commits/49b7cbd5abf4e1eaaed82573e58c5ae32652491b)) - ❌

⏲️  Total pipeline duration: 16mn08s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Build source-tiktok-marketing docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                              | ✅       |
| Acceptance tests                                                        | ❌       |
| Code format checks                                                      | ✅       |
| Validate metadata for source-tiktok-marketing                           | ✅       |
| Connector version semver check                                          | ✅       |
| Connector version increment check                                       | ✅       |
| QA checks                                                               | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_22272-source-tiktok-use-default-availability-strategy/1697634322/49b7cbd5abf4e1eaaed82573e58c5ae32652491b/source-tiktok-marketing/3.6.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:49b7cbd5abf4e1eaaed82573e58c5ae32652491b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-tiktok-marketing test report (commit [`12b08bd290`](https://github.com/airbytehq/airbyte/pull/31537/commits/12b08bd290ad0264579238a8a6655f3530780145)) - ❌

⏲️  Total pipeline duration: 16mn32s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Build source-tiktok-marketing docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                              | ✅       |
| Acceptance tests                                                        | ❌       |
| Code format checks                                                      | ✅       |
| Validate metadata for source-tiktok-marketing                           | ✅       |
| Connector version semver check                                          | ✅       |
| Connector version increment check                                       | ✅       |
| QA checks                                                               | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_22272-source-tiktok-use-default-availability-strategy/1697636470/12b08bd290ad0264579238a8a6655f3530780145/source-tiktok-marketing/3.6.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:12b08bd290ad0264579238a8a6655f3530780145)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-tiktok-marketing test report (commit [`2edad390c5`](https://github.com/airbytehq/airbyte/pull/31537/commits/2edad390c5b30ff26b7d1fee24eb4958469e3e9a)) - ✅

⏲️  Total pipeline duration: 16mn41s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Build source-tiktok-marketing docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                              | ✅       |
| Acceptance tests                                                        | ✅       |
| Code format checks                                                      | ✅       |
| Validate metadata for source-tiktok-marketing                           | ✅       |
| Connector version semver check                                          | ✅       |
| Connector version increment check                                       | ✅       |
| QA checks                                                               | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_22272-source-tiktok-use-default-availability-strategy/1697639934/2edad390c5b30ff26b7d1fee24eb4958469e3e9a/source-tiktok-marketing/3.6.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:2edad390c5b30ff26b7d1fee24eb4958469e3e9a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Pull request merged**
