### PR TITLE
[source-mysql]: support Planetscale MySQL's per-query row limit

### PR DESCRIPTION
**Pull request by theyueli**
Fixes https://github.com/airbytehq/oncall/issues/5051

Planet MySQL has defined multiple system limits. One of our customers has been hitting the 100K per-query row limit, making our connector emit system errors. This patch defines a chunk size limit for our connector, by default it is the largest long, and if we find it is a Planetscale MySQL, we will adjust to 100K.

### CODE REVIEW

**Review by akashkulk — COMMENTED** [review]
I think you've made the change to Mssql?

**Comment by theyueli** [comment]
> I think you've made the change to Mssql?

oops, my mistake... these two files are almost identical.. and I got confused by their names... fixed now. Thanks!

**Review by evantahler — APPROVED** [review]

**Review by akashkulk — APPROVED** [review]

**Comment by lincolnremi** [comment]
@theyueli @akashkulk @evantahler: It doesn't look like this fix made it into the V2 version of the connector that @rodireich @xiaohansong and @clnoll merged in https://github.com/airbytehq/airbyte/pull/48369

We at [Remi](https://www.remihq.com/) are also running into the 100k per-query row limit when using Airbyte's MySQL connector to replicate PlanetScale to BigQuery (the PlanetScale connector is not working for us either).

Can you point us in the direction of what a fix for this would look like? We're highly motivated to fix this and happy to submit a PR if your team is open to it.

**Comment by lincolnremi** [comment]
I don't know if this is the correct approach but I took stab at fixing this in https://github.com/airbytehq/airbyte/pull/51055.

**Pull request merged**
