### PR TITLE
📝 New documentation page: orchestrating Airbyte and Airbyte Cloud syncs with Kestra

### PR DESCRIPTION
**Pull request by anna-geller**
This PR adds documentation about Kestra integration.

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks for the contribution @anna-geller I request our team to review it.

**Review by marcosmarxm — APPROVED** [review]
Thanks @anna-geller

**Comment by octavia-approvington** [comment]
A job well done <br/> nice job

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
