### PR TITLE
Add secrets handling in UI

### LINKED ISSUE #986: Improve Secrets Handling
## Tell us about the problem you're trying to solve
* When requesting previously configured connectors, secrets are returned from from the API and viewable in plain text.
* Out of scope: Obscuring secrets as I type them the first time.

## Describe the solution you’d like
* _credit for this impl goes to @michel-tricot , i'm just writing it down._ 
* Add support for an attribute / convention in our jsonschema for sensitive fields. e.g.
    ```
    "password": {
      "type": "string",
      "sensitive": true
    }
    ```
* API Get / List: For fields with this flag, the API should remove the value when returning it on a read request and instead insert the value `**********`
* API Put: For for fields with this flag, if the value returned from the API is `**********`, then the API keeps the previous value of the field. Performs a merge of the object provided in the PUT and the existing object.
  * Note: This breaks our original contract in our API docs around puts (that we always replace the whole object. we should document this)
* UI Read: When it receives from the API a field with this flag it can act as normal, it just displays `**********`
* UI Update: This has some edge cases.
  * If user updates config but does not touch sensitive field, UI sends `**********` to the API (which means it is a no op)
  * If user deletes the field (removes all of the `*`), then UI sends empty value to API, which gets interpretted as deleting the value.
  * If user does something in the middle? Deletes some of the dots. Goes to enter a new password and then realized they don't want to edit that field? 
       * talked to artem, ui will have a special secrets component to handle this case.
       * ~~@michel-tricot - I don't think we discussed this case.~~
       * ~~options:~~
            1. ~~any number of asterisk. (handles first case well but doesn't handle second case)~~
            1. ~~add a reset button. (more works but handles both cases)~~

## Additional context
* Preferring this over adding patch updates to the API.
* Whoever takes this on, please create child tickets, one for API and one for UI.

### LINKED ISSUE #1055: Handle secrets in the UI
## Tell us about the problem you're trying to solve
#1022 changed the airbyte API to obfuscate secrets in the top-level of a connector's config as described in #986 **with the difference that only top-level secrets are handled**. This issue concerns having the UI handle secrets in line with that change. Specifically: 

* UI Read: When it receives from the API a field with the `airbyte_secret` flag set to `true`, it can act as normal, it just displays `**********`
* UI Update: This has some edge cases.
  * If user updates config but does not touch sensitive field, UI sends `**********` (the exact same value sent by the API) to the API (which means it is a no op).
  * If user edits the secret field in any way then UI sends the updated value to the API. If the value is anything other than the exact obfuscated value sent by the API, the API regards this as an update.

### PR DESCRIPTION
**Pull request by jamakase**
Closes #1055 

# What
adds `type=password` for secrets

### CODE REVIEW

**Review by michel-tricot — APPROVED** [review]

**Comment by cgardens** [comment]
@Jamakase  is their anything blocking merging this?

**Review by cgardens — APPROVED** [review]
were we going to do something where you had to click on something in order to be able to edit the secret, so that people didn't accidentally do it? I think we talked about that originally but maybe that was replaced by your suggestion in slack here:

> when we try to modify password field - do we expect input to be cleared on every focus + key press? Or some other behaviour

if so that's fine for now.

**Comment by cgardens** [comment]
@Jamakase can we merge this?

**Comment by Jamakase** [comment]
@cgardens I was investigating a bit how to handle it from UX point of view in a more appropriate form. Need to have small fix and then we can merge.

**Pull request merged**
