### PR TITLE
:bug:  Updated source-mongodb-v2 performance

### LINKED ISSUE #6544: Performance issues in new Mongo Source Connector
## Enviroment
- **Airbyte version**:  0.29.21-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**:  Docker
- **Source Connector and version**: Mongodb-v2 0.1.1  
- **Destination Connector and version**: Redshift 0.3.14
- **Severity**: High
- **Step where error happened**: New Connector + Sync

## Current Behavior
When setting up a new source with this connector, schema discovery takes close to 50 minutes, and appears to be scanning entire collections from source Mongo database  

When syncing records, an incremental load of 1 stream/collection < 10k records is taking > 1 hour. Comparing to the old Mongo connector, I can refresh 20 streams/collections in around 8 minutes. The connector seems to be scanning the entire collection in a much different manner than the old Ruby source

## Expected Behavior
Comparable performance to old connector, no 50 minute delay in retrieving records

## Logs
Attaching logs from initial full sync. Note the 50 minute gap before records are returned

Also including logs from the next incremental sync. Same gap

<details>
<summary>LOG from initial Full Sync</summary> 

```

2021-09-24 15:09:24 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-24 15:09:24 INFO i.a.i.d.j.c.s.S3StreamCopier(<init>):142 - {} - S3 upload part size: 10 MB
2021-09-24 15:09:25 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-24 15:09:25 INFO c.m.d.l.SLF4JLogger(info):71 - {} - Opened connection [connectionId{localValue:3, serverValue:44254}] to sufferfestproduction-shard-00-03-naqnz.mongodb.net:27017
2021-09-24 15:09:25 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-24 15:09:25 INFO a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - {} - Initiated multipart upload to wahoo-rivery/8e240244-550f-4dfb-b8f1-e0fb3cafc251/parse/svl_Activity with full ID nd8i3Mpxr3A16tt81CwVaJyr_9vQSwG55mhvr3PaEYsAU90IrZZrsRYKhurCy5CiHuZSkjyE49BWFC92Y1pNI8k0GxFR_DtpbvLnO4ABkDN3olwES2URygz1KzaSqJqw
2021-09-24 15:09:25 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-24 15:09:25 INFO i.a.i.d.b.BufferedStreamConsumer(startTracked):143 - {} - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
2021-09-24 15:59:39 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):223 - Records read: 1000

```

</details>

<details>
<summary>LOG from incremental sync</summary> 

```

2021-09-24 18:02:03 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-24 18:02:03 INFO i.a.i.d.b.BufferedStreamConsumer(startTracked):143 - {} - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
2021-09-24 18:52:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-24 18:52:01 INFO i.a.i.s.r.StateDecoratingIterator(computeNext):80 - {} - State Report: stream name: AirbyteStreamNameNamespacePair{name='Activity', namespace='parse'}, original cursor field: _updated_at, original cursor 2021-09-24T17:14:22Z, cursor field: _updated_at, new cursor: 2021-09-24T18:51:11Z
2021-09-24 18:52:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-24 18:52:01 INFO i.a.i.s.r.AbstractDbSource(lambda$read$2):141 - {} - Closing database connection pool.
2021-09-24 18:52:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-24 18:52:01 INFO i.a.i.s.r.AbstractDbSource(lambda$read$2):143 - {} - Closed database connection pool.
2021-09-24 18:52:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-24 18:52:01 INFO i.a.i.b.IntegrationRunner(run):153 - {} - Completed integration: io.airbyte.integrations.source.mongodb.MongoDbSource
2021-09-24 18:52:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-24 18:52:01 INFO i.a.i.s.m.MongoDbSource(main):84 - {} - completed source: class io.airbyte.integrations.source.mongodb.MongoDbSource
2021-09-24 18:52:02 INFO () DefaultReplicationWorker(run):141 - Source thread complete.

```

</details>

## Steps to Reproduce
1. Setup new MongoDB Connection, Connect Redshift Destination, notice delay in schema discovery. Observe long running full scans on MongoDB instance
2. Execute full or incremental load of any stream from new Mongo connector --> destination

## Are you willing to submit a PR?
Unfortunately cannot at this time

### PR DESCRIPTION
**Pull request by andriikorotkov**
## What
Updated the method for reading unique document fields in a collection and their types. The task indicates that the processing of one stream with 10 thousand records took 20 minutes. After the changes have been made, the processing of the same stream takes 2 minutes and 30 seconds.

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by VitaliiMaltsev — APPROVED** [review]

**Review by sashaNeshcheret — APPROVED** [review]

**Review by alexandr-shegeda — APPROVED** [review]
LGTM. we can proceed with publish/merge without airbyte review

**Comment by JCWahoo** [comment]
I don't believe this resolves the issue. 0.1.5 is showing no difference in performance vs the previous version

**Comment by andriikorotkov** [comment]
@JCWahoo,  I opened this task again and see how else I can improve the performance.

**Comment by JCWahoo** [comment]
Thanks - Looking at the Mongo side it appears during schema discovery is
trying to parse the entire collection and not a sample of records

**Pull request merged**
