### PR TITLE
introduce jvm flag MaxRAMPercentage for java connectors

### PR DESCRIPTION
**Pull request by subodh1810**
Issue : https://github.com/airbytehq/airbyte/issues/3440
The flag `MaxRAMPercentage` allows us to set the max heap limit of the JVM based on the containers limit i.e. whatever value we set for the flag (which is set in %), the JVM heap size can grow upto that % of the container memory limit.  More info can be found [here](https://www.baeldung.com/java-jvm-parameters-rampercentage) 

To test this out I introduced the following piece of code in MySQL source and re-built the image and triggered a sync with and without the flag `MaxRAMPercentage`

```
  public static void printRamUsage() {
    int mb = 1024 * 1024;
    MemoryMXBean memoryBean = ManagementFactory.getMemoryMXBean();
    long xmx = memoryBean.getHeapMemoryUsage().getMax() / mb;
    long xms = memoryBean.getHeapMemoryUsage().getInit() / mb;
    LOGGER.info("Initial Memory (xms) : " + xms + "mb");
    System.out.println("Initial Memory (xms) : " + xms + "mb");
    LOGGER.info("Max Memory (xmx) : " + xmx + "mb");
    System.out.println("Max Memory (xmx) : " + xmx + "mb");
  }
  ```
  
My docker setting is set to provide a `Total Memory: 3.842GiB` limit to each container that spawns. 
  
When we run the connector without the JVM flag `MaxRAMPercentage`, the output is 
```
2021-09-12 22:02:51 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):73 - {} - 2021-09-12 22:02:51 INFO i.a.i.s.m.MySqlSource(main):250 - {} - starting source: class io.airbyte.integrations.source.mysql.MySqlSource
2021-09-12 22:02:51 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):73 - {} - 2021-09-12 22:02:51 INFO i.a.i.s.m.MySqlSource(printRamUsage):268 - {} - Initial Memory (xms) : 62mb
2021-09-12 22:02:51 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):73 - {} - Initial Memory (xms) : 62mb
2021-09-12 22:02:51 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):73 - {} - 2021-09-12 22:02:51 INFO i.a.i.s.m.MySqlSource(printRamUsage):270 - {} - Max Memory (xmx) : 984mb
2021-09-12 22:02:51 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):73 - {} - Max Memory (xmx) : 984mb
```

As you can see above the xmx limit was set to 984mb which is 1/4th of 3.842GiB. 
Screenshots : 

without_flag_2

without_flag

After this, I ran the connector with the flag `MaxRAMPercentage` and the value set for the flag was 75.0 which means the heap space can grow upto 75% of the available memory. Take a look a the output of from that run, 
```
2021-09-12 22:10:19 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):73 - {} - 2021-09-12 22:10:19 INFO i.a.i.s.m.MySqlSource(main):250 - {} - starting source: class io.airbyte.integrations.source.mysql.MySqlSource
2021-09-12 22:10:19 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):73 - {} - 2021-09-12 22:10:19 INFO i.a.i.s.m.MySqlSource(printRamUsage):268 - {} - Initial Memory (xms) : 62mb
2021-09-12 22:10:19 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):73 - {} - Initial Memory (xms) : 62mb
2021-09-12 22:10:19 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):73 - {} - 2021-09-12 22:10:19 INFO i.a.i.s.m.MySqlSource(printRamUsage):270 - {} - Max Memory (xmx) : 2952mb
2021-09-12 22:10:19 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):73 - {} - Max Memory (xmx) : 2952mb
```

As you can see, xmx is at 2952mb which is 75% of the container limit (3.842GiB)
Screenshots:
with_flag
with_flag_2

Since we are using the gradle application [plugin](https://docs.gradle.org/current/userguide/application_plugin.html) for our java connectors the only way I could pass the flag was using the `applicationDefaultJvmArgs`. 

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Comment by subodh1810** [comment]
For kube deployment (docker-desktop) as well similar behaviour was observed as explained in the description of the PR, take a look at the following screenshots :
Without JVM flag :
kube_without_flag

With JVM flag
kube_with_flag

**Comment by davinchia** [comment]
@subodh1810 to make sure I understand, this sets the java connectors to use 75% of the memory allocated with [these flags](https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/java/io/airbyte/config/EnvConfigs.java#L87-L88) (I suppose the limit flag is what we are concerned about), both on docker and kubernetes, yes?

And the remaining 25% is a buffer for non-heap memory?

**Comment by subodh1810** [comment]
@davinchia yes..whatever limit you define, the xmx is set at 75% of that value. The rest 25% is for non-heap memory an other OS operations

**Review by davinchia — APPROVED** [review]
Nice.

Let's create a follow up issue to either figure out a way so we don't have to set this in all the java connectors, or enforce it in gradle that if the java application plugin is present, this value needs to be set.

Can we also update the documentation in https://github.com/airbytehq/airbyte/blob/master/docs/operator-guides/scaling-airbyte.md to reflect this change?

Can we also do add these flags for the scheduler and server apps so we will be able to start specifying memory requirements?

**Review by jrhizor — APPROVED** [review]
Thanks for the clear verification walkthrough. Very helpful.

Agreed with what Davin said about adding this as a default for core/new projects as well in the future.

**Review by cgardens — APPROVED** [review]
agreed with preceding reviewers. nice work.

**Comment by subodh1810** [comment]
Hey guys sorry for the delay in sharing the test results for this change on GKE. 
The Cluster on which I deployed Airbyte had the following configuration :
Number of nodes : 3
Total vCPUs : 3
Total memory : 5.1GB
Screenshot 2021-09-20 at 5 26 20 PM

I built mysql source image with and without the JVM flag but added the following method in both the images to see the xmx and xms values
```
  public static void printRamUsage() {
    int mb = 1024 * 1024;
    MemoryMXBean memoryBean = ManagementFactory.getMemoryMXBean();
    long xmx = memoryBean.getHeapMemoryUsage().getMax() / mb;
    long xms = memoryBean.getHeapMemoryUsage().getInit() / mb;
    LOGGER.info("Initial Memory (xms) : " + xms + "mb");
    System.out.println("Initial Memory (xms) : " + xms + "mb");
    LOGGER.info("Max Memory (xmx) : " + xmx + "mb");
    System.out.println("Max Memory (xmx) : " + xmx + "mb");
  }  
```
**First deployment - Without any RESOURCE_MEMORY_REQUEST and RESOURCE_MEMORY_LIMIT :** 
As you can see in the following screenshot, even when we didn't specify any resource limits for the pods, there was still a value for xmx. 
Results with JVM flag `-XX:MaxRAMPercentage=75.0`:
xmx was set to 906 MB
mysql-source-with-jvm-flag

Results without JVM flag : 
xmx was set to 303 MB
mysql-source-without-jvm-flag


**Second deployment - With RESOURCE_MEMORY_REQUEST set at 64Mi and RESOURCE_MEMORY_LIMIT set at 1Gi:**
The JVM flag respects the limits enforced on the POD. Take a look at the following screenshots
Results with JVM flag `-XX:MaxRAMPercentage=75.0`:
xmx was set to 742 MB which is around 75% of the RESOURCE_MEMORY_LIMIT i.e. 1GB
mysql_source_with_jvm_flag
 
Results without JVM flag :
xmx was set to 247 MB which is around 25% of the RESOURCE_MEMORY_LIMIT i.e. 1GB
mysql_source_without_jvm_flag

**Comment by subodh1810** [comment]
Let me know if you need any other form of testing to be done or if its good enough and I can merge the PR. 
I have created an issue https://github.com/airbytehq/airbyte/issues/6313 to enforce the flag on connectors and another issue https://github.com/airbytehq/airbyte/issues/6314 to add the JVM flag to Airbyte core containers

**Comment by davinchia** [comment]
Super!

Results are as expected, which is great. Feel free to merge whenever.

Reminder to update the scaling airbyte document as well as add these flags for the server and scheduler before we merge this in. Thanks!

**Pull request merged**
