### PR TITLE
Destinations V2 Remove Soft Reset

### PR DESCRIPTION
**Pull request by jbfbell**
Stop doing soft resets after a migration, this should happen anyway during the normal table preparation process because we'll detect that a table does not match the expected schema.

### CODE REVIEW

**Review by edgao — APPROVED** [review]

**Comment by octavia-approvington** [comment]
Trying to merge your PR using a bot?
Comment this on the PR:
```
/approve-and-merge reason="<STATE YOUR REASON HERE>"
```
Make sure you've reviewed the [docs](https://internal-docs.airbyte.io/How-Tos/Overriding-PR-Merge-Rules)!

**Comment by octavia-approvington** [comment]
This code is at peace with itself <br/> imagine karate kid approving

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
