### PR TITLE
🚨🚨 Source PayPal Transactions: Rename field in `Balances` schema

### PR DESCRIPTION
**Pull request by artem1205**
## What

Update `Balances` schema

## How

Rename balance -> balances property; make it list of objects

## Recommended reading order
1. `balances.json`

## 🚨 User Impact 🚨

`Balances` schema update.

Playbook: https://docs.google.com/document/d/1xcy6QYlbCfnDRY3ogAzUHnLXX0rsZ-TWg1AtVnZAPk0/edit

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-paypal-transaction test report (commit [`bdf8f467f2`](https://github.com/airbytehq/airbyte/pull/27916/commits/bdf8f467f2543cc3c388b691112e339655f016a5)) - ❌

⏲️  Total pipeline duration: 01mn49s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-paypal-transaction/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-paypal-transaction docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-paypal-27900/1688393675/bdf8f467f2543cc3c388b691112e339655f016a5/source-paypal-transaction/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Review by davydov-d — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-paypal-transaction test report (commit [`6804ecfdbd`](https://github.com/airbytehq/airbyte/pull/27916/commits/6804ecfdbdc06683fc9ec4b6b6b8048f55ffff65)) - ❌

⏲️  Total pipeline duration: 03mn11s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-paypal-transaction/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-paypal-transaction docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-paypal-27900/1688413026/6804ecfdbdc06683fc9ec4b6b6b8048f55ffff65/source-paypal-transaction/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Comment by octavia-squidington-iii** [comment]
##  source-paypal-transaction test report (commit [`a46e64b859`](https://github.com/airbytehq/airbyte/pull/27916/commits/a46e64b859e69da2c1847964df35de95d5fc4e14)) - ❌

⏲️  Total pipeline duration: 03mn45s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-paypal-transaction/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-paypal-transaction docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-paypal-27900/1688454723/a46e64b859e69da2c1847964df35de95d5fc4e14/source-paypal-transaction/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Comment by octavia-squidington-iii** [comment]
##  source-paypal-transaction test report (commit [`f90140a17e`](https://github.com/airbytehq/airbyte/pull/27916/commits/f90140a17e5ca973c9113f4a3ba56e7525c7bc9d)) - ❌

⏲️  Total pipeline duration: 04mn13s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-paypal-transaction/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-paypal-transaction docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-paypal-27900/1688465187/f90140a17e5ca973c9113f4a3ba56e7525c7bc9d/source-paypal-transaction/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Comment by octavia-squidington-iii** [comment]
##  source-paypal-transaction test report (commit [`37d05bece4`](https://github.com/airbytehq/airbyte/pull/27916/commits/37d05bece418657612264b57e3c6de7d39e4204e)) - ✅

⏲️  Total pipeline duration: 04mn11s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-paypal-transaction/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-paypal-transaction docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Acceptance tests                                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-paypal-27900/1688482423/37d05bece418657612264b57e3c6de7d39e4204e/source-paypal-transaction/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Review by alafanechere — COMMENTED** [review]
@artem1205 I believe you can split this PR:
* The spec change, even if detected as a breaking one, is likely not a real breaking change as the `client_id` and `client_secret` must be there to connect to the api. (correct me if I'm wront)
* The stream schema change is indeed a breaking change

Could you please separate these PR so that the spec change can be shipped first?
Please also share access to the breaking change playbook.

**Comment by artem1205** [comment]
> @artem1205 I believe you can split this PR:
> 
> * The spec change, even if detected as a breaking one, is likely not a real breaking change as the `client_id` and `client_secret` must be there to connect to the api. (correct me if I'm wrong)

You're right, changes in `spec` won't break anything (we can think about these changes as like moving field presence validation to FE)

> Could you please separate these PR so that the spec change can be shipped first? Please also share access to the breaking change playbook.

I can separate this PR, but `acceptance tests` will still fail, due to incorrect balance schema.

**Review by lazebnyi — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-paypal-transaction test report (commit [`7e42eb62c9`](https://github.com/airbytehq/airbyte/pull/27916/commits/7e42eb62c940f39b9501047dc92d2fa020f0d74b)) - ✅

⏲️  Total pipeline duration: 04mn42s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-paypal-transaction/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-paypal-transaction docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Acceptance tests                                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-paypal-27900/1688582733/7e42eb62c940f39b9501047dc92d2fa020f0d74b/source-paypal-transaction/2.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Comment by octavia-squidington-iii** [comment]
##  source-paypal-transaction test report (commit [`05759802c3`](https://github.com/airbytehq/airbyte/pull/27916/commits/05759802c3d4d9a519dd31a1b66db73da4b57a5a)) - ✅

⏲️  Total pipeline duration: 04mn08s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-paypal-transaction/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-paypal-transaction docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Acceptance tests                                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-paypal-27900/1688583677/05759802c3d4d9a519dd31a1b66db73da4b57a5a/source-paypal-transaction/2.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Pull request merged**
