### PR TITLE
Source Hubspot: revert latest public version to 1.2.0

### PR DESCRIPTION
**Pull request by clnoll**
https://github.com/airbytehq/oncall/issues/2677

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`35ae930f53`](https://github.com/airbytehq/airbyte/pull/29192/commits/35ae930f5310e6fab5f6b9f15b3cd987e8cc3210)) - ❌

⏲️  Total pipeline duration: 56.48s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ❌        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/p0-hubspot-authentication-errors-8-7-23-rollback-public-version-too/1691445746/35ae930f5310e6fab5f6b9f15b3cd987e8cc3210/source-hubspot/1.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:35ae930f5310e6fab5f6b9f15b3cd987e8cc3210)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Review by girarda — APPROVED** [review]
:shipit:

**Comment by octavia-approvington** [comment]
What are we doing again? <br/> merge and squash

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
