### PR TITLE
Fix broken link to Google Sheet source example

### PR DESCRIPTION
**Pull request by LeoTheGriff**
## What
Broken link in docs.

## How
Fix broken link to Google Sheet source example

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

### CODE REVIEW

**Review by marcosmarxm — APPROVED** [review]
Thanks @LeoTheGriff

**Comment by LeoTheGriff** [comment]
Cheers, how do I merge?

**Comment by marcosmarxm** [comment]
This week the codebase is freeze to merge because of holidays. Next week I'll merge the contribution.

**Comment by octavia-approvington** [comment]
You did it! <br/> finish line

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
