### PR TITLE
Base Normalization: improve error msg if `cursor_field` missed in schema

### PR DESCRIPTION
**Pull request by grubberr**
Signed-off-by: Sergey Chvalyuk <grubberr@gmail.com>

## What
Related to this oncall https://github.com/airbytehq/oncall/issues/573

if in "configured_catalog" `cursor_field` missed in schema fields, we get hard to understand exception

```
Traceback (most recent call last):
...
  File "/home/user/airbyte/airbyte-integrations/bases/base-normalization/normalization/transform_catalog/stream_processor.py", line 1023, in get_cursor_field
    cursor = column_names[self.cursor_field[0]][0]
KeyError: 'date_start'
```

## How
```
Traceback (most recent call last):
...
  File "/home/user/airbyte/airbyte-integrations/bases/base-normalization/normalization/transform_catalog/stream_processor.py", line 1025, in get_cursor_field
    raise ValueError(f"cursor field: '{cursor_field}' missed in schema for stream '{self.stream_name}'")
ValueError: cursor field: 'date_start' missed in schema for stream 'custom_campaign__insights_by_dma'
```

### CODE REVIEW

**Review by edgao — APPROVED** [review]
nice! I think it's worth adding a unit test for this case, but otherwise LGTM :ship:

I am curious though - how does this happen? Shouldn't the source's catalog only list cursors that are present in the schema?

**Comment by grubberr** [comment]
@edgao 
https://github.com/airbytehq/oncall/issues/573#issuecomment-1265136243

it's stream with dynamically generated schema

**Comment by edgao** [comment]
right, but even if it's dynamically generated, why is the source putting a field as a valid cursor if it doesn't actually exist in the stream?

E.g. it looks like for the `custom_campaign__insights_by_dma` stream, the cursor is `date_start`, which isn't present in the stream's fields at all. Is that expected behavior from source-facebook-marketing?

**Comment by edgao** [comment]
ah, got it. I guess they just need to refresh schema to get the bugfix the?

(btw, none of this is blocking; feel free to merge + file an issue to add the unit test later if this is causing OC problems)

**Comment by grubberr** [comment]
@edgao yes I will deploy on cloud and notify that they still need to refresh schema

about this PR I will add tests as you asked and publish after (this PR not blocks me)

**Comment by abhishekgahlot2** [comment]
@grubberr i wanted to ask how to test this locally. i want to modify base-normalization image on my local running airbyte for this pr.

**Comment by edgao** [comment]
@abhishekgahlot2 what are you trying to solve? base-normalization is slated for deletion in favor of implementing normalizatoin-ish stuff directly inside connectors (related: https://docs.airbyte.com/using-airbyte/core-concepts/typing-deduping#what-is-destinations-v2)

this PR in particular is now addressed in the platform https://github.com/airbytehq/airbyte/issues/30341

**Pull request closed without merging**
