### PR TITLE
Parameterize test_empty_streams and test_stream_with_1_airbyte_column by destination

### LINKED ISSUE #18194: Base normalization always runs test_ephemeral.py integration test for postgres even if a different target is specified
This code causes test_epehemral to always be ran for Postgres even when `NORMALIZATION_TEST_TARGET` environment variable is set for a different destination. This is pretty annoying, because it slows down developer iterations.
```
@pytest.fixture(scope="module", autouse=True)
def before_all_tests(request):
    destinations_to_test = dbt_test_utils.get_test_targets()
    # set clean-up args to clean target destination after the test
    clean_up_args = {
        "destination_type": [d for d in DestinationType if d.value in destinations_to_test],
        "test_type": "ephemeral",
        "tmp_folders": temporary_folders,
    }
    if DestinationType.POSTGRES.value not in destinations_to_test:
        destinations_to_test.append(DestinationType.POSTGRES.value)
```

### PR DESCRIPTION
**Pull request by grishick**
## What
Instead of always running test_stream_with_1_airbyte_column and test_empty_streams on Postgres, parameterize these two tests by destination similar to all other tests.

### CODE REVIEW

**Comment by grishick** [comment]
Adding @ChristopheDuong as a reviewer, because you added these lines a year ago. Please take a quick look to make sure I am not undoing something important.

**Review by ryankfu — COMMENTED** [review]
Changes make sense, however since the context of how come Postgres is always added to the list of `destinations_to_test` isn't clear so will defer to Chris to make sure this doesn't have downstream effects

EDIT: ~~How come this PR is being made, are the tests for normalization running slow because Airbyte is always testing for Postgres?~~ Nevermind, ignore comment as I see the linked github issue

**Comment by ChristopheDuong** [comment]
there two tests in that file that always need a postgres to run `test_empty_streams` and `test_stream_with_1_airbyte_column` so those two lines were making sure the db is setup before running any such tests

https://github.com/airbytehq/airbyte/blob/2e1209e78ff90a076be197606756e547e16c1825/airbyte-integrations/bases/base-normalization/integration_tests/test_ephemeral.py#L89

I'm not sure why the tests are now passing even though the postgres for those tests is not prepared anymore...

**Comment by grishick** [comment]
> there two tests in that file that always need a postgres to run `test_empty_streams` and `test_stream_with_1_airbyte_column` so those two lines were making sure the db is setup before running any such tests
> 
> https://github.com/airbytehq/airbyte/blob/2e1209e78ff90a076be197606756e547e16c1825/airbyte-integrations/bases/base-normalization/integration_tests/test_ephemeral.py#L89
> 
> I'm not sure why the tests are now passing even though the postgres for those tests is not prepared anymore...

@ChristopheDuong if I am testing Redshift or BigQuery, why would I want/need to run these tests for Postgres?

**Comment by ChristopheDuong** [comment]
> @ChristopheDuong that is a good question.. 😕 also if I am testing Redshift or BigQuery, why would I want/need to run these tests for Postgres and also not run these tests for Redshift or BigQuery?

These Normalization tests used to run for all destinations at once, you couldn't do it for one destination at a time.

**Comment by grishick** [comment]
> > @ChristopheDuong that is a good question.. 😕 also if I am testing Redshift or BigQuery, why would I want/need to run these tests for Postgres and also not run these tests for Redshift or BigQuery?
> 
> These Normalization tests used to run for all destinations at once, you couldn't do it for one destination at a time.

Looks like these tests can be run for one destination at a time now with these changes unless I am missing something. Does this change make sense to you?

**Comment by ChristopheDuong** [comment]
> Looks like these tests can be run for one destination at a time now with these changes unless I am missing something. Does this change make sense to you?

Maybe? I guess?

I'm not aware of the latest changes regarding normalization integration tests, maybe check with @edgao?

**Comment by edgao** [comment]
nah nothing recently affecting this part of the tests. This change makes sense to me :shipit:

**Comment by grishick** [comment]
> nah nothing recently affecting this part of the tests. This change makes sense to me :shipit:

✅  please ?

**Review by edgao — APPROVED** [review]

**Pull request merged**
