### PR TITLE
source-monday: ensure inline schemas, updated cdk, poetry (where possible)

### PR DESCRIPTION
**Pull request by bleonard**
This was created from a set of automated scripts. In each case, not every update was needed for every connector, but overall here is what happened:

 * `auto-schema update -s all description`: added descriptions to json and inline schemas
 * `connector-code migrate_to_yaml -c all --type source`: migrates json schemas to connectors with a manifest
 * `airbyte-ci connectors --name=<all modified connectors from above> migrate_to_base_image`: makes sure that each is using a base docker image and updates docs
 * `airbyte-ci connectors --name=<all modified connectors from above> migrate-to-poetry`: moves connectors not already using poetry to do so and updates documentation
 * `airbyte-ci connectors --name=<all modified connectors from above> up_to_date`: updated the CDK to newer (0.80.0) version

The version number and changelogs were also bumped using the `connector-code pulls` command.

### CODE REVIEW

**Comment by bleonard** [comment]
Looks like bad credentials. @DanyloGL  can you look?

**Comment by DanyloGL** [comment]
> Looks like bad credentials. @DanyloGL can you look?

GSM creds `config_api_token` and `config_api_token` updated with new token. Now should work.

**Comment by bleonard** [comment]
Thanks! Looks like some unit test issues now with URL matching. Is master passing?

**Comment by bleonard** [comment]
still seeing this issue
```
self = <connector_acceptance_test.tests.test_core.TestConnection object at 0x7f76f49c3190>
connector_config = SecretDict(******)
inputs = ConnectionTestConfig(config_path='secrets/config_api_token.json', status=<Status.Succeed: 'succeed'>, timeout_seconds=None, deployment_mode=None)
docker_runner = <connector_acceptance_test.utils.connector_runner.ConnectorRunner object at 0x7f76f49c0a30>

    async def test_check(self, connector_config, inputs: ConnectionTestConfig, docker_runner: ConnectorRunner):
        if inputs.status == ConnectionTestConfig.Status.Succeed:
            output = await docker_runner.call_check(config=connector_config)
            con_messages = filter_output(output, Type.CONNECTION_STATUS)
    
            assert len(con_messages) == 1, "Connection status message should be emitted exactly once"
>           assert con_messages[0].connectionStatus.status == Status.SUCCEEDED
E           AssertionError: assert equals failed
E             -<Status.FAILED: 'FAILED'>   +<Status.SUCCEEDED: 'SUCCEE 
E                                         +DED'>
```

**Comment by bleonard** [comment]
This is too complicated for me to inline at the moment. 
The code in GraphQLRequester assumes the json files are there.
```
    def _get_schema_root_properties(self):
        schema_loader = JsonFileSchemaLoader(config=self.config, parameters={"name": self.name})
        schema = schema_loader.get_json_schema()["properties"]
```

**Pull request closed without merging**
