### PR TITLE
destination-langchain: remove workaround for pyyaml

### PR DESCRIPTION
**Pull request by girarda**
## What
* The pyyaml workaround isn't required now that pyyaml 6.0.1 pins the cython version they use

## How
* Remove the workaround

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  destination-langchain test report (commit [`81f4630ed7`](https://github.com/airbytehq/airbyte/pull/28443/commits/81f4630ed78e140dc8cb02cf2882f76777962ce7)) - ❌

⏲️  Total pipeline duration: 03mn36s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-langchain/metadata.yaml | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Code format checks                                                           | ✅        |
| Connector package install                                                    | ✅        |
| Build destination-langchain docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_remove_langchain_workaround/1689719954/81f4630ed78e140dc8cb02cf2882f76777962ce7/destination-langchain/0.0.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-langchain test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-langchain test report (commit [`f62f94de80`](https://github.com/airbytehq/airbyte/pull/28443/commits/f62f94de800dc8e5abb330ce9e064ba99d506a01)) - ❌

⏲️  Total pipeline duration: 02mn00s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-langchain/metadata.yaml | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Code format checks                                                           | ✅        |
| Connector package install                                                    | ✅        |
| Build destination-langchain docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_remove_langchain_workaround/1689720258/f62f94de800dc8e5abb330ce9e064ba99d506a01/destination-langchain/0.0.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-langchain test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-langchain test report (commit [`e1a094c016`](https://github.com/airbytehq/airbyte/pull/28443/commits/e1a094c016c26ba45399d0756422bb37b4e9764a)) - ❌

⏲️  Total pipeline duration: 02mn16s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-langchain/metadata.yaml | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Code format checks                                                           | ✅        |
| Connector package install                                                    | ✅        |
| Build destination-langchain docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_remove_langchain_workaround/1689720460/e1a094c016c26ba45399d0756422bb37b4e9764a/destination-langchain/0.0.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-langchain test
```

**Comment by flash1293** [comment]
This is blocked on https://github.com/airbytehq/airbyte/issues/28458

**Pull request closed without merging**
