### PR TITLE
Destination ClickHouse: Fix destination IllegalStateException

### PR DESCRIPTION
**Pull request by jzcruiser**
## What
Sync from mysql to clickhouse keeps failing due to the following IllegalStateException:

```
2021-12-21 05:48:35 destination > 2021-12-21 05:48:35 INFO r.y.c.ClickHouseDriver(<clinit>):49 - {} - Driver registered
2021-12-21 05:48:35 destination > Exception in thread "main" java.lang.IllegalStateException: jdbc destinations must specify a schema.
2021-12-21 05:48:35 destination > 	at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
2021-12-21 05:48:35 destination > 	at io.airbyte.integrations.destination.jdbc.JdbcBufferedConsumerFactory.createWriteConfigs(JdbcBufferedConsumerFactory.java:71)
2021-12-21 05:48:35 destination > 	at io.airbyte.integrations.destination.jdbc.JdbcBufferedConsumerFactory.create(JdbcBufferedConsumerFactory.java:54)
2021-12-21 05:48:35 destination > 	at io.airbyte.integrations.destination.jdbc.AbstractJdbcDestination.getConsumer(AbstractJdbcDestination.java:99)
2021-12-21 05:48:35 destination > 	at io.airbyte.integrations.base.ssh.SshWrappedDestination.getConsumer(SshWrappedDestination.java:58)
2021-12-21 05:48:35 destination > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:127)
2021-12-21 05:48:35 destination > 	at io.airbyte.integrations.destination.clickhouse.ClickhouseDestination.main(ClickhouseDestination.java:89)
```

## How
* Noticed that there's a similar implementation in MySQLSqlOperations.java, override `ClickhouseDestination.java`'s `isSchemaRequired` method by returning false

### CODE REVIEW

**Comment by alafanechere** [comment]
Hi @jzcruiser thanks for this fix! Could you please provide some evidence that the acceptance tests are passing? Could you bump the connector version in the `Dockerfile` + in `airbyte-config/init/src/main/resources/seed/destination_definitions.yaml`

**Comment by jzcruiser** [comment]
@alafanechere sure, thanks.

**Comment by jzcruiser** [comment]
Hi @alafanechere, I added version changes to this pr and ...
```
./gradlew :airbyte-integrations:connectors:destination-clickhouse:integrationTest
```
ended with no errors:

image

Please kindly take a look.

**Review by alafanechere — APPROVED** [review]
I updated the changelog and the destination specs, waiting for the platform build to pass an then we're ready to merge.

**Comment by alafanechere** [comment]
Thanks for the patch @jzcruiser!

**Comment by jzcruiser** [comment]
> Thanks for the patch @jzcruiser!

cheers!

**Pull request merged**
