### PR TITLE
connectors-ci: add dagger logs url to report + better run duration formatting

### LINKED ISSUE #27731: Link to full dagger log should be in connector HTML reports
We dont have an explicit link to the raw log file
https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/edgao_better_namespace_handling/1687819690/8b1eb950c3c0ef372ce11e0aa249e5eca71c7679/dagger-logs.txt

### PR DESCRIPTION
**Pull request by alafanechere**
## What
Closes #27731 
Getting the URL in the test HTML report can be useful for additional debbuging.

## How
* Infer the dagger logs url before they are actually written
* Add the `dagger_logs_url` to the context object
* Add the `dagger_logs_url` in HTML report, from the context object

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-openweather test report (commit [`c53d189bce`](https://github.com/airbytehq/airbyte/pull/27820/commits/c53d189bce88750529c4b32d8ac8bce667f8a310)) - ✅

⏲️  Total pipeline duration: 15.15s seconds

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-openweather/metadata.yaml | ✅        |
| Connector version semver check                                            | ✅        |
| QA checks                                                                 | ✅        |
| Code format checks                                                        | ✅        |
| Connector package install                                                 | ✅        |
| Build source-openweather docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                | ✅        |
| Acceptance tests                                                          | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/augustin_connectors-ci_incremental-logging-improvements/1688027672/c53d189bce88750529c4b32d8ac8bce667f8a310/source-openweather/0.1.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-openweather test
```

**Comment by octavia-squidington-iii** [comment]
##  source-openweather test report (commit [`fdaf5eef16`](https://github.com/airbytehq/airbyte/pull/27820/commits/fdaf5eef16cfd0b77a8b12e526af967adabded3e)) - ✅

⏲️  Total pipeline duration: 22.44s seconds

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-openweather/metadata.yaml | ✅        |
| Connector version semver check                                            | ✅        |
| QA checks                                                                 | ✅        |
| Code format checks                                                        | ✅        |
| Connector package install                                                 | ✅        |
| Build source-openweather docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                | ✅        |
| Acceptance tests                                                          | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/augustin_connectors-ci_incremental-logging-improvements/1688027983/fdaf5eef16cfd0b77a8b12e526af967adabded3e/source-openweather/0.1.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-openweather test
```

**Comment by octavia-squidington-iii** [comment]
##  source-openweather test report (commit [`a00c92ea0f`](https://github.com/airbytehq/airbyte/pull/27820/commits/a00c92ea0f2384b7a37028a1303d399473684890)) - ✅

⏲️  Total pipeline duration: 20.12s seconds

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-openweather/metadata.yaml | ✅        |
| Connector version semver check                                            | ✅        |
| QA checks                                                                 | ✅        |
| Code format checks                                                        | ✅        |
| Connector package install                                                 | ✅        |
| Build source-openweather docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                | ✅        |
| Acceptance tests                                                          | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/augustin_connectors-ci_incremental-logging-improvements/1688028491/a00c92ea0f2384b7a37028a1303d399473684890/source-openweather/0.1.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-openweather test
```

**Comment by octavia-approvington** [comment]
It's time <br/> fine lets go

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
