### PR TITLE
Source GitLab: Add Deployments Stream

### PR DESCRIPTION
**Pull request by benshaaw**
## What
Add support for [Deployments API](https://docs.gitlab.com/ee/api/deployments.html) as a stream to the GitLab Source connector.

## How
Include new Deployments stream class, schema, unit and integration tests.

## Recommended reading order
1. `streams.py`
2. `source.py`
3. JSON schema
4. Tests and Dockerfile changes

## 🚨 User Impact 🚨
A schema refresh may be required.

## Pre-merge Actions
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@benshaaw can you make sure all contributions sign the CLA?

**Comment by benshaaw** [comment]
> @benshaaw can you make sure all contributions sign the CLA?

Hi @marcosmarxm - I will ensure that my colleague signs it tomorrow. Are we unable to proceed with review until this is done?

**Comment by marcosmarxm** [comment]
> > @benshaaw can you make sure all contributions sign the CLA?
> 
> Hi @marcosmarxm - I will ensure that my colleague signs it tomorrow. Are we unable to proceed with review until this is done?

Hello @benshaaw another team is responsible for the review. I'll ping them.

**Comment by bmcgilli** [comment]
Hi @benshaaw can you please provide us a script to populate our own sandbox account with some deployments? Otherwise integration tests don’t pass. And it will help speed us the review, thank you! 
cc @lazebnyi to assign in the interim

**Comment by benshaaw** [comment]
> Hi @benshaaw can you please provide us a script to populate our own sandbox account with some deployments? Otherwise integration tests don’t pass. And it will help speed us the review, thank you! cc @lazebnyi to assign in the interim

Hi @bmcgilli - we have added extra test cases that might be a starting point. Do you mean a script that will call the GitLab API to create a deployment? I will try whipping one up based off of the project IDs I can already find in the repository but make it so they can easily be overridden with env variables.

**Comment by benshaaw** [comment]
> Hi @benshaaw can you please provide us a script to populate our own sandbox account with some deployments? Otherwise integration tests don’t pass. And it will help speed us the review, thank you! cc @lazebnyi to assign in the interim

Hi @bmcgilli @lazebnyi - were you looking for something like this as a population script (bash/curl)?

```bash
#!/usr/bin/env bash

set -eu

GITLAB_PROJECT_ID=${GITLAB_PROJECT_ID:=25157276}
COMMIT_SHA=${COMMIT_SHA:=2831d897ba0214f8d3168647e8ad4232b83987ef}
COMMIT_TAG=${COMMIT_TAG:=fake-tag-6}

curl -XPOST \
  -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
  -H "Content-Type: application/json" \
  "https://${GITLAB_DOMAIN_PREFIX:=}gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/deployments" \
  -d "{\"id\":\"${GITLAB_PROJECT_ID}\",\"environment\":\"sandbox\",\"sha\":\"${COMMIT_SHA}\",\"ref\":\"${COMMIT_TAG}\",\"tag\":true,\"status\":\"success\"}"
```

I've tried to set defaults based off data included in the expected integration tests, but you can override them with environment variables like so:

```shell
GITLAB_TOKEN="THIS_IS_MANDATORY" GITLAB_PROJECT_ID="15278573" COMMIT_SHA="fac5bcd6fa6894202f42b8f5b8a9ff00a6ee77f8" COMMIT_TAG="1.0.0" ./create_deployment.sh
```

**Comment by benshaaw** [comment]
Hi @bmcgilli @lazebnyi - is there anything outstanding you need from us to move on this PR?

We also are intending to make a subsequent PR that will introduce the ability to fetch timeline events linked to incidents, however this is still being developed internally on our end, do you have any recommendations that we can do now ahead of time to ease the review process?

**Comment by darynaishchenko** [comment]
@benshaaw Hi, I've faced the problem while working with your PR. Here is my pr https://github.com/airbytehq/airbyte/pull/31183 from your branch + updates for expected records and some format fixes. I need to push this changes to your branch to pass CI checks and merge your pr, but I can't push to master in your fork(permission denied). Can you create another pr using [contributor guide](https://docs.airbyte.com/contributing-to-airbyte/), so I can push my changes to another branch, or if you don't mind I can merge my pr with your commits?

**Comment by benshaaw** [comment]
> @benshaaw Hi, I've faced the problem while working with your PR. Here is my pr #31183 from your branch + updates for expected records and some format fixes. I need to push this changes to your branch to pass CI checks and merge your pr, but I can't push to master in your fork(permission denied). Can you create another pr using [contributor guide](https://docs.airbyte.com/contributing-to-airbyte/), so I can push my changes to another branch, or if you don't mind I can merge my pr with your commits?

Hi @darynaishchenko, thank you for taking a look!

I think I have added you as a contributor to my repository, which hopefully will allow you to push to my branch. However, please feel free to do what is easiest for you (if you merge your PR) given that our commits are in your PR, to get this merged into `airbytehq:master`. Hopefully this works, however please let me know if not!

**Comment by darynaishchenko** [comment]
@benshaaw Thanks, I've merged PR https://github.com/airbytehq/airbyte/pull/31183

**Pull request closed without merging**
