### PR TITLE
Move `docs.airbyte.com` hosting to Vercel

### PR DESCRIPTION
**Pull request by evantahler**
Currently, we host docs.airbyte.com on GithubPage.  This is starting to show some cracks due to:
* Regular downtime when we deploy ([slack](https://airbytehq-team.slack.com/archives/C032Y32T065/p1695145955978729)).  Our repo is big and builds take a long time.
* Git shenanigans.  Since we are force-pushing to our repo on every publish, our git history is huge
* Slow.  Let's host somewhere with more than one pop (point-of-presence)

We already use Vercel, and Vercel has a simple-to-use Docusaurus integration. 
1. We get per-PR previews (see below in this PR for the comment added by Vercel with a preview link)
2. We get faster and non-blocking builds
3. Build-in Github Action testing so you can't merge if the build fails
4. We get slack integration from them (no need for custom code)
Screenshot 2023-09-19 at 1 59 18 PM

## TODO per-mege: 
* Update the CNAME for docs.airbyte.com 

## TODO post-merge:
* delete the gh-pages branch

### CODE REVIEW

**Review by pedroslopez — APPROVED** [review]
Previews are so nice - LGTM as long as we make the relevant DNS changes wherever that needs to happen

**Comment by evantahler** [comment]
Screenshot 2023-09-19 at 2 06 13 PM
I've updated the project settings so previews will only happen if the ./docusaurus or ./docs folders change in the PR

**Comment by octavia-approvington** [comment]
This looks fine!  <br/> Merged! <br/> Imagine it being fine

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
