### PR TITLE
🐛 Source Zendesk Support: use cursor pagination only

### LINKED ISSUE #26353: Source Zendesk Support: notification
### Topic

Zendesk cursors

### Revelant information

Hi,
We received a notification from Zendesk warning us that they are adding limits to the Offset based pagination to steer users to use the cursor-based pagination instead.
Here is the message:

"Hello,

Starting August 22, 2023, Zendesk is [introducing stricter limits](https://app.hello.zendesk.com/e/er?s=2136619493&lid=59802&elqTrackId=87af7cd2303d487fa08f6151e2f52628&elq=4b27e1779c1f487dba2fbfb639c36e76&elqaid=78755&elqat=1) on API requests made using offset-based pagination (OBP). You are receiving this email because according to our API usage data, your account will be affected by these upcoming limits. To minimize potential disruption to your business, we want to share additional details.

**Why is Zendesk making this change?**
Zendesk currently offers both [offset-based pagination](https://app.hello.zendesk.com/e/er?s=2136619493&lid=59801&elqTrackId=1b98444ff5e84f039b20e476ace5b3ed&elq=4b27e1779c1f487dba2fbfb639c36e76&elqaid=78755&elqat=1) (OBP) and [cursor-based pagination](https://app.hello.zendesk.com/e/er?s=2136619493&lid=59799&elqTrackId=a7b0730875144e9a8463d96dbaf8e3be&elq=4b27e1779c1f487dba2fbfb639c36e76&elqaid=78755&elqat=1) (CBP) for most API endpoints. CBP offers many [advantages](https://app.hello.zendesk.com/e/er?s=2136619493&lid=59800&elqTrackId=05aa85ba74f64d799a5dcb593af8a918&elq=4b27e1779c1f487dba2fbfb639c36e76&elqaid=78755&elqat=1) over OBP and will be the primary method of pagination offered at Zendesk in the near future. In an effort to provide a better, faster experience for our customers we are taking steps to encourage a transition to CBP.

**What does this mean for me?**
The first phase of this effort involves introducing stricter limits on high-offset OBP requests. After August 22, 2023, requests made beyond the first 10,000 records (100 pages) will result in an error message: “400 Bad Request.” In order to request data sets larger than 10,000 records, you will need to [transition to CBP](https://app.hello.zendesk.com/e/er?s=2136619493&lid=59799&elqTrackId=b8c06e1d0bb84aab8ffb96643506fdab&elq=4b27e1779c1f487dba2fbfb639c36e76&elqaid=78755&elqat=1).

Please note that OBP requests for fewer than 10,000 records will not be affected, nor will requests made using the CBP model.

What do I need to do?
We strongly encourage you to make the switch to CBP as soon as possible to avoid being affected by these limits – both now and in the future. If you do not know which integrations or applications may be going over the limit, we suggest partnering with your team responsible for managing Zendesk integrations and apps to investigate and determine what this change means for you.

Should you have questions or need additional support, please [contact us](https://app.hello.zendesk.com/e/er?s=2136619493&lid=55652&elqTrackId=3c8dac44f0714b3783707370c389a630&elq=4b27e1779c1f487dba2fbfb639c36e76&elqaid=78755&elqat=1) and we’ll be happy to help.

Thanks for being a valued customer,

The Zendesk team"

Since we are only using Airbyte to access Zendesk data, we assume this is related to how it pulls data from its API.

There are still several months to the deadline, but I believe it is worth having this in mind to have enough time.

### PR DESCRIPTION
**Pull request by artem1205**
## What

Resolve https://github.com/airbytehq/airbyte/issues/26353

## How

Replace `offset` pagination with `cursor` pagination

## Recommended reading order
1. `stream.py`

## 🚨 User Impact 🚨

no breaking changes

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-zendesk-support test report (commit [`c5afb26380`](https://github.com/airbytehq/airbyte/pull/28096/commits/c5afb263807d86fc24f64107a5755d058b18f831)) - ❌

⏲️  Total pipeline duration: 44.16s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zendesk-support/metadata.yaml | ✅        |
| Connector version semver check                                                | ✅        |
| Connector version increment check                                             | ✅        |
| QA checks                                                                     | ✅        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build source-zendesk-support docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-zendesk-offset-pagination-26353/1689017911/c5afb263807d86fc24f64107a5755d058b18f831/source-zendesk-support/0.10.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-support test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zendesk-support test report (commit [`c5afb26380`](https://github.com/airbytehq/airbyte/pull/28096/commits/c5afb263807d86fc24f64107a5755d058b18f831)) - ❌

⏲️  Total pipeline duration: 40.62s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zendesk-support/metadata.yaml | ✅        |
| Connector version semver check                                                | ✅        |
| Connector version increment check                                             | ✅        |
| QA checks                                                                     | ✅        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build source-zendesk-support docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-zendesk-offset-pagination-26353/1689018041/c5afb263807d86fc24f64107a5755d058b18f831/source-zendesk-support/0.10.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-support test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zendesk-support test report (commit [`4d4e0b75ee`](https://github.com/airbytehq/airbyte/pull/28096/commits/4d4e0b75ee975c3a5b9fe068ddaef19dd1ebbdf8)) - ❌

⏲️  Total pipeline duration: 16mn17s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zendesk-support/metadata.yaml | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build source-zendesk-support docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ✅        |
| Acceptance tests                                                              | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-zendesk-offset-pagination-26353/1689031479/4d4e0b75ee975c3a5b9fe068ddaef19dd1ebbdf8/source-zendesk-support/0.10.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-support test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zendesk-support test report (commit [`3e1d506f62`](https://github.com/airbytehq/airbyte/pull/28096/commits/3e1d506f620615a7aa291b7dfe1f8f89c35dc5fc)) - ❌

⏲️  Total pipeline duration: 40.12s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zendesk-support/metadata.yaml | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build source-zendesk-support docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-zendesk-offset-pagination-26353/1689059684/3e1d506f620615a7aa291b7dfe1f8f89c35dc5fc/source-zendesk-support/0.10.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-support test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zendesk-support test report (commit [`6fb39ff500`](https://github.com/airbytehq/airbyte/pull/28096/commits/6fb39ff50027b766aebe1a616db6749d4f63410d)) - ❌

⏲️  Total pipeline duration: 24mn07s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zendesk-support/metadata.yaml | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build source-zendesk-support docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ✅        |
| Acceptance tests                                                              | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-zendesk-offset-pagination-26353/1689064367/6fb39ff50027b766aebe1a616db6749d4f63410d/source-zendesk-support/0.10.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-support test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zendesk-support test report (commit [`e75d280e20`](https://github.com/airbytehq/airbyte/pull/28096/commits/e75d280e202205f1b4756293b0a484153c03368c)) - ✅

⏲️  Total pipeline duration: 16mn01s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zendesk-support/metadata.yaml | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build source-zendesk-support docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ✅        |
| Acceptance tests                                                              | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-zendesk-offset-pagination-26353/1689067730/e75d280e202205f1b4756293b0a484153c03368c/source-zendesk-support/0.10.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-support test
```

**Review by lazebnyi — APPROVED** [review]

**Comment by swapnasam** [comment]
I dont see these changes in master branch

**Pull request merged**
