### PR TITLE
Toggle off and on set -x when DOCKER_TOKEN is used

### PR DESCRIPTION
**Pull request by noahkawasaki-airbyte**
## What
This is why I'm not a fan of merging `set -x` into a repo :(

Toggling it on and off whenever the `DOCKER_TOKEN` is used. 

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

### CODE REVIEW

**Comment by noahkawasaki-airbyte** [comment]
Testing here https://github.com/airbytehq/airbyte/actions/runs/2398823593

**Comment by noahkawasaki-airbyte** [comment]
/publish connector=connectors/source-faker run-tests=false auto-bump-version=true

**Comment by evantahler** [comment]
We do use DOCKER_PASSWORD in a few other scripts, but not via curl (e.g. `docker login --username airbytebot --password "${DOCKER_PASSWORD}"`). I don't think this outputs anything sensitive

**Review by evantahler — APPROVED** [review]

**Comment by noahkawasaki-airbyte** [comment]
Yeah, more importantly they are actual Github Secrets so GHA knows to mask them. The reason the tokens were an issue was because they are created during runtime..

**Comment by evantahler** [comment]
probably should modify the following files as well:
* https://github.com/airbytehq/airbyte/blob/master/tools/bin/gke-kube-acceptance-test/acceptance_test_kube_gke.sh#L47
*

**Comment by noahkawasaki-airbyte** [comment]
I dont see `set -x` in that file anywhere so that one should not be a problem. But I guess there is still a risk that someone adds in later

**Comment by evantahler** [comment]
> Yeah, more importantly they are actual Github Secrets so GHA knows to mask them. The reason the tokens were an issue was because they are created during runtime..

Fascinating! if we set an empty secret would github have masked the output?

**Comment by noahkawasaki-airbyte** [comment]
That might be the solution actually, yeah.

**Comment by noahkawasaki-airbyte** [comment]
Confirmed this removes logging of tokens

**Pull request merged**
