### PR TITLE
Use full enquoted table name for max cursor query

### PR DESCRIPTION
**Pull request by rodireich**
## What
Fix max cursor query for tables containing capital letters.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-alloydb test report (commit [`dbfece1706`](https://github.com/airbytehq/airbyte/pull/28954/commits/dbfece1706d73acc54d0e4fa57635b96e24b8ff2)) - ❌

⏲️  Total pipeline duration: 09mn03s 

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-alloydb/metadata.yaml     | ✅        |
| Connector version semver check                                            | ✅        |
| QA checks                                                                 | ✅        |
| Build connector tar                                                       | ✅        |
| Build source-alloydb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-alloydb:integrationTest | ✅        |
| Acceptance tests                                                          | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/2603-source-postgres-orgpostgresqlutilpsqlexception-error-relation-roboadvicescores-does-not-exist-via-sentry/1690929402/dbfece1706d73acc54d0e4fa57635b96e24b8ff2/source-alloydb/3.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-alloydb test
```

**Review by prateekmukhedkar — APPROVED** [review]

**Review by nguyenaiden — APPROVED** [review]
+1. Maybe worth it for us to start using the ORM like Hibernate instead of raw SQL, especially if we're writing queries that aren't too complex.

**Comment by rodireich** [comment]
/legacy-test connector=connectors/source-postgres-strict-encrypt

**Comment by octavia-approvington** [comment]
Jerry would be proud <br/> Spongebob

**Review by octavia-approvington — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`dbfece1706`](https://github.com/airbytehq/airbyte/pull/28954/commits/dbfece1706d73acc54d0e4fa57635b96e24b8ff2)) - ❌

⏲️  Total pipeline duration: 307mn24s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ❌        |
| QA checks                                                                  | ❌        |
| Build connector tar                                                        | ✅        |
| Build source-postgres docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres:integrationTest | ❌        |
| Acceptance tests                                                           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/2603-source-postgres-orgpostgresqlutilpsqlexception-error-relation-roboadvicescores-does-not-exist-via-sentry/1690929402/dbfece1706d73acc54d0e4fa57635b96e24b8ff2/source-postgres/3.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by octavia-squidington-iii** [comment]
##  source-postgres-strict-encrypt test report (commit [`dbfece1706`](https://github.com/airbytehq/airbyte/pull/28954/commits/dbfece1706d73acc54d0e4fa57635b96e24b8ff2)) - ❌

⏲️  Total pipeline duration: 10mn14s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                            | ❌        |
| QA checks                                                                                 | ❌        |
| Build connector tar                                                                       | ✅        |
| Build source-postgres-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                          | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/2603-source-postgres-orgpostgresqlutilpsqlexception-error-relation-roboadvicescores-does-not-exist-via-sentry/1690929402/dbfece1706d73acc54d0e4fa57635b96e24b8ff2/source-postgres-strict-encrypt/3.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-alloydb-strict-encrypt test report (commit [`dbfece1706`](https://github.com/airbytehq/airbyte/pull/28954/commits/dbfece1706d73acc54d0e4fa57635b96e24b8ff2)) - ❌

⏲️  Total pipeline duration: 09mn19s 

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-alloydb-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                           | ❌        |
| QA checks                                                                                | ✅        |
| Build connector tar                                                                      | ✅        |
| Build source-alloydb-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-alloydb-strict-encrypt:integrationTest | ✅        |
| Acceptance tests                                                                         | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/2603-source-postgres-orgpostgresqlutilpsqlexception-error-relation-roboadvicescores-does-not-exist-via-sentry/1690929402/dbfece1706d73acc54d0e4fa57635b96e24b8ff2/source-alloydb-strict-encrypt/3.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-alloydb-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-alloydb-strict-encrypt test report (commit [`8b65c4268d`](https://github.com/airbytehq/airbyte/pull/28954/commits/8b65c4268d3c512e8dbae05311927e252edf59eb)) - ❌

⏲️  Total pipeline duration: 08mn47s 

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-alloydb-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                           | ✅        |
| QA checks                                                                                | ❌        |
| Build connector tar                                                                      | ✅        |
| Build source-alloydb-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-alloydb-strict-encrypt:integrationTest | ✅        |
| Acceptance tests                                                                         | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/2603-source-postgres-orgpostgresqlutilpsqlexception-error-relation-roboadvicescores-does-not-exist-via-sentry/1690950178/8b65c4268d3c512e8dbae05311927e252edf59eb/source-alloydb-strict-encrypt/3.1.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-alloydb-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-alloydb test report (commit [`8b65c4268d`](https://github.com/airbytehq/airbyte/pull/28954/commits/8b65c4268d3c512e8dbae05311927e252edf59eb)) - ❌

⏲️  Total pipeline duration: 08mn19s 

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-alloydb/metadata.yaml     | ✅        |
| Connector version semver check                                            | ✅        |
| QA checks                                                                 | ❌        |
| Build connector tar                                                       | ✅        |
| Build source-alloydb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-alloydb:integrationTest | ✅        |
| Acceptance tests                                                          | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/2603-source-postgres-orgpostgresqlutilpsqlexception-error-relation-roboadvicescores-does-not-exist-via-sentry/1690950178/8b65c4268d3c512e8dbae05311927e252edf59eb/source-alloydb/3.1.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-alloydb test
```

**Comment by octavia-squidington-iii** [comment]
##  source-postgres-strict-encrypt test report (commit [`8b65c4268d`](https://github.com/airbytehq/airbyte/pull/28954/commits/8b65c4268d3c512e8dbae05311927e252edf59eb)) - ❌

⏲️  Total pipeline duration: 10mn09s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                            | ✅        |
| QA checks                                                                                 | ❌        |
| Build connector tar                                                                       | ✅        |
| Build source-postgres-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                          | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/2603-source-postgres-orgpostgresqlutilpsqlexception-error-relation-roboadvicescores-does-not-exist-via-sentry/1690950178/8b65c4268d3c512e8dbae05311927e252edf59eb/source-postgres-strict-encrypt/3.1.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`8b65c4268d`](https://github.com/airbytehq/airbyte/pull/28954/commits/8b65c4268d3c512e8dbae05311927e252edf59eb)) - ❌

⏲️  Total pipeline duration: 307mn21s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ❌        |
| QA checks                                                                  | ❌        |
| Build connector tar                                                        | ✅        |
| Build source-postgres docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres:integrationTest | ❌        |
| Acceptance tests                                                           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/2603-source-postgres-orgpostgresqlutilpsqlexception-error-relation-roboadvicescores-does-not-exist-via-sentry/1690950178/8b65c4268d3c512e8dbae05311927e252edf59eb/source-postgres/3.1.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Pull request merged**
