### PR TITLE
Get default configured catalog from discover command

### LINKED ISSUE #7955: SAT: Configured catalog should be taken from discovery result by default
## Tell us about the problem you're trying to solve
Currently SAT runs using configured catalogs from files like `integration_tests/configured_catalog.json` etc
This makes it difficult to track if all streams were tested. Testing not all streams should be an exceptional scenario, so by default SAT will take configured catalog from discovery command and use the default configuration.

## Describe the solution you’d like
If you commit `configured_catalog_path` in `acceptance-test-config.yml` file it will default to generated catalog from discovery command.

## Describe the alternative you’ve considered or used
Generate configured catalog with the following script:
```python
from airbyte_cdk.models import ConfiguredAirbyteCatalog, AirbyteMessage, ConfiguredAirbyteStream, DestinationSyncMode


record = AirbyteMessage.parse_raw(input())
for stream in record.catalog.streams:
    stream.json_schema = {}
streams = [
    ConfiguredAirbyteStream(
        stream=stream,
        sync_mode=stream.supported_sync_modes[0],
        destination_sync_mode=DestinationSyncMode.append
    ) for stream in record.catalog.streams
]
configured_catalog = ConfiguredAirbyteCatalog(streams=streams)
print(configured_catalog.json(indent=4))
```

## Are you willing to submit a PR?
yes

### PR DESCRIPTION
**Pull request by augan-rymkhan**
## What
By default SAT should take configured catalog from discovery command and use the default configuration.

## How

1) if `configured_catalog_path` is not provided then generate `ConfiguredAirbyteCatalog` from `discovered_catalog` fixture (result of discover command) in [configured_catalog_fixture](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/conftest.py#L63).

2) Remove default value from `configured_catalog_path` in [config.py](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/config.py#L17)

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? If yes, please make sure to include it here and in any changelogs with the 🚨🚨 emoji
What is the end result perceived by the user?

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>

#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by eliziario — APPROVED** [review]

**Review by keu — APPROVED** [review]

**Review by sherifnada — COMMENTED** [review]
One thing i'm not sure about: do we currently require the developer to opt out explicitly of syncing some streams? 

for example if there are streams A and B and the user provides a configured catalog containing only A, does the test fail? IMO it should unless the user explicitly configured an option saying that they are skipping the stream, as well as providing a reason

**Comment by augan-rymkhan** [comment]
> One thing i'm not sure about: do we currently require the developer to opt out explicitly of syncing some streams?
> 
> for example if there are streams A and B and the user provides a configured catalog containing only A, does the test fail? IMO it should unless the user explicitly configured an option saying that they are skipping the stream, as well as providing a reason



> One thing i'm not sure about: do we currently require the developer to opt out explicitly of syncing some streams?
> 
> for example if there are streams A and B and the user provides a configured catalog containing only A, does the test fail? IMO it should unless the user explicitly configured an option saying that they are skipping the stream, as well as providing a reason

No, it will not fail, in that case. 
The code change in this PR implements the following, If `configured_catalog_path` is not provided in `acceptance-test-config.yaml` then SAT takes configured catalog from `discover` command's result.

- So, you require, that all streams must be in the file specified by `configured_catalog_path`, to test all the existing streams?
 
- If developer wants to skip tests for some streams, those streams must be marked explicitly as skipped with the reason

  Correct?

**Comment by sherifnada** [comment]
Correct. The idea is that this test should verify data is coming from all streams.

**Comment by augan-rymkhan** [comment]
@sherifnada 
Discussed it with the team on standup call.  
I created a[ new ticket](https://github.com/airbytehq/airbyte/issues/8481) for that. If it's ok can we merge this PR?

**Review by sherifnada — APPROVED** [review]
separate issue for the comment is good w me 👍🏼

**Pull request merged**
