### PR TITLE
:bug: Source Stripe: add availability strategy

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/airbyte/issues/22270

## How
- Remove customer 403 error handling in favor of availability strategy
- Add unit test
- Fix schema errors

## 🚨 User Impact 🚨
No impact

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`d6a282fcf9`](https://github.com/airbytehq/airbyte/pull/28911/commits/d6a282fcf9a486b56b31659990bbd5237653d48c)) - ❌

⏲️  Total pipeline duration: 03mn43s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_22270-source-stripe-add-availability-strategy/1690890135/d6a282fcf9a486b56b31659990bbd5237653d48c/source-stripe/3.17.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`7bb100376e`](https://github.com/airbytehq/airbyte/pull/28911/commits/7bb100376ead8064dccbd6946d9ed22eb74f9990)) - ❌

⏲️  Total pipeline duration: 08mn47s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ❌        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_22270-source-stripe-add-availability-strategy/1690891766/7bb100376ead8064dccbd6946d9ed22eb74f9990/source-stripe/3.17.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`3a533b7218`](https://github.com/airbytehq/airbyte/pull/28911/commits/3a533b7218750ae477fdf7a08436537fcb28dfda)) - ❌

⏲️  Total pipeline duration: 03mn26s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| QA checks                                                            | ❌        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_22270-source-stripe-add-availability-strategy/1690893770/3a533b7218750ae477fdf7a08436537fcb28dfda/source-stripe/3.17.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`3a533b7218`](https://github.com/airbytehq/airbyte/pull/28911/commits/3a533b7218750ae477fdf7a08436537fcb28dfda)) - ✅

⏲️  Total pipeline duration: 09mn59s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_22270-source-stripe-add-availability-strategy/1690894272/3a533b7218750ae477fdf7a08436537fcb28dfda/source-stripe/3.17.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Review by lazebnyi — APPROVED** [review]

**Pull request merged**
