### PR TITLE
Allow for sources without spec.json or spec.yaml

### PR DESCRIPTION
**Pull request by maxi297**
## What
The extensibility team would like for the spec to be pushed completely to the manifest.yaml to allow for the Connector Builder to import sources more easily. However, CATs are failing if a spec is not provided. The only reason is that it compares the spec returned by the connector with the spec.json/spec.yaml file to ensure they are the same. We have agreed that if a connector needs this validation, it can do it as part of a unit/integration test.

Also relates to pain points users had: https://github.com/airbytehq/airbyte/issues/21155

## How
Have the connector_spec fixture return None on FileNotFoundError and use actual_connector_spec for spec validation

## 🚨 User Impact 🚨
Allows connector maintainer through the Connector Builder to delete spec.json/spec.yaml and rely only on the manifest.yaml

### CODE REVIEW

**Review by pedroslopez — APPROVED** [review]
Swapping the usages of the connector spec to the actual one rather than the file makes total sense to me! 

Also seems fine to make the assertion optional (though perhaps it should be required for high strictness level - ok to leave as is for now)

Do we need to update some docs to reflect that this is now optional?

**Comment by maxi297** [comment]
Thanks for the review @pedroslopez ! I checked the documentation and don't see any place where it says that spec.json/spec.yaml is mandatory. It says that it's how the AbstractSource finds the spec but more really. Do you have a specific section I should double check?

**Comment by maxi297** [comment]
> Also seems fine to make the assertion optional (though perhaps it should be required for high strictness level - ok to leave as is for now)

Which assertion are you referring to? The one where the `actual_connector_spec == connector_spec`? For no-code connector, this would never apply as spec.json/spec.yaml will not exist. Does that mean that we will never enable the high strictness level for those?

**Review by girarda — APPROVED** [review]

**Comment by maxi297** [comment]
/publish connector=bases/connector-acceptance-test auto-bump-version=false

**Comment by maxi297** [comment]
/legacy-update connector=bases/connector-acceptance-test auto-bump-version=false

**Comment by maxi297** [comment]
/legacy-publish connector=bases/connector-acceptance-test auto-bump-version=false

**Pull request merged**
