### PR TITLE
:bug: Source-MySql: do not check cdc required param binlog_row_image for standard replication

### LINKED ISSUE #7404: Error connecting to MariaDB (binlog_row_image could not be queried)
## Enviroment
- **Airbyte version**:  example is 0.29.0-alpha
- **OS Version / Instance**: Windows
- **Deployment**: Docker
- **Source Connector and version**:MySQL 0.3.8
- **Severity**: High
- **Step where error happened**: Setup new connection

## Current Behavior
Appears error message: "Could not query the variable binlog_row_image". 
It seems to be due to the version of the MariaDB database we want to extract info from, but we cannot update the database as we are not the owners of the DB. 
Is there a possibility to change anything in the connector to make it work as we cannot update the version of the DB?

### PR DESCRIPTION
**Pull request by mkhokh-33**
## What
We currently check param binlog_row_image for standard replication fro MySql connector.
This param in db should be only required for cdc replication not for standard

## How
Made changes in MySqlSource method getCheckOperations in order do not check cdc required params for standard replication 

## Recommended reading order
1. `MySqlSource.java`
2. `x.java`
2. `y.json`
3. `md.json`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>

#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [x] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [x] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [x] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [x] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Comment by mkhokh-33** [comment]
@DoNotPanicUA , @andriikorotkov please pay attention only on MySqlSource.java, other changes are related to code formatting.

**Review by andriikorotkov — APPROVED** [review]

**Review by DoNotPanicUA — CHANGES_REQUESTED** [review]
Please exclude the changes which are not related to your change.
If there is a formatting change outside the MySql source, it should be fixed by another PR.

**Comment by andriikorotkov** [comment]
@DoNotPanicUA, Maria asked this question in the internal chat. Sasha gave permission to add these changes in this pull request.

**Comment by mkhokh-33** [comment]
> @DoNotPanicUA, Maria asked this question in the internal chat. Sasha gave permission to add these changes in this pull request.

done :)

**Review by DoNotPanicUA — APPROVED** [review]
LGFM.
as a potential improvement - all three checks are very similar. we could create a method with input params and decrease code dupe a bit.

**Review by DoNotPanicUA — APPROVED** [review]
perfect 👍

**Review by tuliren — APPROVED** [review]
Thanks for DRYing the code!

**Review by tuliren — COMMENTED** [review]
Does it mean that the latest MySQL source connector will always fail? It does not look like the case though.

Also is this issue not caught by any unit test? I just checked that the config for MySQL source integration test is on standard replication, but does not have the `binlog_row_image`. Why does the integration test not fail before this PR?

**Comment by mkhokh-33** [comment]
> Does it mean that the latest MySQL source connector will always fail? It does not look like the case though.
> 
> Also is this issue not caught by any unit test? I just checked that the config for MySQL source integration test is on standard replication, but does not have the `binlog_row_image`. Why does the integration test not fail before this PR?

In integration tests we use for testcontainer docker image version "mysql:8.0" and what I see from mysql doc 8.0 https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_binlog_row_image that **binlog_image_row** is already present and by default the value is **"FULL"**
So I assume that test didn't fail before because there was no way to catch situation when **binlog_image_row** is absent or has another value then **"FULL"**

It can be absent for older db versions, as I can see from release notes it was introduced for mysql from  5.6 - https://dev.mysql.com/doc/refman/5.6/en/mysql-nutshell.html 

On the issue users paid attention that the problem appeared for mariaDB version 5.5.60 and the changes related to **binlog_image_row**  for MariaDB seems to be introduced latter 
https://mariadb.com/kb/en/replication-and-binary-log-system-variables/#binlog_row_image for version MariaDB 10.1.6 .

**Pull request merged**
