### PR TITLE
Maxi297/test GitHub UI maintenance process

### PR DESCRIPTION
**Pull request by maxi297**
## What
* Updating wikipedia-pageviews connector as it was broken and I wanted to test the process for the connector maintenance

## How
Issues with the connector:
* Invalid datetime format
* top stream was using start as an end hence only fetching one slice

Note that to clarify those changes in terms of code, I did create [a specific commit](https://github.com/airbytehq/airbyte/pull/28484/commits/a5dbc2e3929994648ad482b0015cc4fd8021b432) just for the issue per se. That being said, with this commit, it is quite hard to review...

## 🚨 User Impact 🚨
In practice, none as this connector isn't used

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-wikipedia-pageviews test report (commit [`ddc1552b8c`](https://github.com/airbytehq/airbyte/pull/28484/commits/ddc1552b8cd6b2dec17cd00fd1c972cb9946722b)) - ❌

⏲️  Total pipeline duration: 01mn25s 

| Step                                                                              | Result   |
|:----------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-wikipedia-pageviews/metadata.yaml | ✅        |
| Connector version semver check                                                    | ✅        |
| Connector version increment check                                                 | ❌        |
| QA checks                                                                         | ✅        |
| Code format checks                                                                | ✅        |
| Connector package install                                                         | ✅        |
| Build source-wikipedia-pageviews docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297_test-github-ui-maintenance-process/1689790257/ddc1552b8cd6b2dec17cd00fd1c972cb9946722b/source-wikipedia-pageviews/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-wikipedia-pageviews test
```

**Comment by octavia-squidington-iii** [comment]
##  source-wikipedia-pageviews test report (commit [`dab0bdd889`](https://github.com/airbytehq/airbyte/pull/28484/commits/dab0bdd889906c2e32471b9237a68aca95e034c3)) - ❌

⏲️  Total pipeline duration: 10mn02s 

| Step                                                                              | Result   |
|:----------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-wikipedia-pageviews/metadata.yaml | ✅        |
| Connector version semver check                                                    | ✅        |
| Connector version increment check                                                 | ❌        |
| QA checks                                                                         | ✅        |
| Code format checks                                                                | ✅        |
| Connector package install                                                         | ✅        |
| Build source-wikipedia-pageviews docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                                  | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297_test-github-ui-maintenance-process/1689790438/dab0bdd889906c2e32471b9237a68aca95e034c3/source-wikipedia-pageviews/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-wikipedia-pageviews test
```

**Comment by octavia-squidington-iii** [comment]
##  source-wikipedia-pageviews test report (commit [`756f9aa24d`](https://github.com/airbytehq/airbyte/pull/28484/commits/756f9aa24d8ccf136087fb70e4245feb9f1db2d7)) - ❌

⏲️  Total pipeline duration: 06mn59s 

| Step                                                                              | Result   |
|:----------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-wikipedia-pageviews/metadata.yaml | ✅        |
| Connector version semver check                                                    | ✅        |
| Connector version increment check                                                 | ❌        |
| QA checks                                                                         | ✅        |
| Code format checks                                                                | ✅        |
| Connector package install                                                         | ✅        |
| Build source-wikipedia-pageviews docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                                  | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297_test-github-ui-maintenance-process/1689795017/756f9aa24d8ccf136087fb70e4245feb9f1db2d7/source-wikipedia-pageviews/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-wikipedia-pageviews test
```

**Comment by maxi297** [comment]
Only a test

**Pull request closed without merging**
