### PR TITLE
🐛 Source zenloop: update to state per partition

### PR DESCRIPTION
**Pull request by maxi297**
PR because I can't merge anything at the same time since it relies on CDK changes so I'm recreating this PR

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-zenloop test report (commit [`82066b8477`](https://github.com/airbytehq/airbyte/pull/27556/commits/82066b847785ec706eb9b8ab80ab81fceea0161f)) - ❌

⏲️  Total pipeline duration: 179 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zenloop/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ❌        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-zenloop docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5336680128)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zenloop test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zenloop test report (commit [`82066b8477`](https://github.com/airbytehq/airbyte/pull/27556/commits/82066b847785ec706eb9b8ab80ab81fceea0161f)) - ❌

⏲️  Total pipeline duration: 158 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zenloop/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ❌        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-zenloop docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5336773263)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zenloop test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zenloop test report (commit [`82066b8477`](https://github.com/airbytehq/airbyte/pull/27556/commits/82066b847785ec706eb9b8ab80ab81fceea0161f)) - ❌

⏲️  Total pipeline duration: 144 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zenloop/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ❌        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-zenloop docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5336778144)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zenloop test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zenloop test report (commit [`f2a43b4334`](https://github.com/airbytehq/airbyte/pull/27556/commits/f2a43b433468f02b3d6a7c82ed3585e89165e72a)) - ❌

⏲️  Total pipeline duration: 144 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zenloop/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ❌        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-zenloop docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5336914796)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zenloop test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zenloop test report (commit [`53e9e6792e`](https://github.com/airbytehq/airbyte/pull/27556/commits/53e9e6792e2853b6d9ef40618d651eb41d391767)) - ❌

⏲️  Total pipeline duration: 153 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zenloop/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-zenloop docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5337060309)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zenloop test
```

**Comment by maxi297** [comment]
There are breaking changes but no user on cloud so nothing to do there

**Comment by octavia-squidington-iii** [comment]
##  source-zenloop test report (commit [`6d10df0355`](https://github.com/airbytehq/airbyte/pull/27556/commits/6d10df03557e672f3e8c437e289cb5cec7363cf5)) - ✅

⏲️  Total pipeline duration: 177 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zenloop/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-zenloop docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5338481089)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zenloop test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zenloop test report (commit [`60560fe46c`](https://github.com/airbytehq/airbyte/pull/27556/commits/60560fe46cb23474ad017710224b7dce61c9336b)) - ✅

⏲️  Total pipeline duration: 170 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zenloop/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-zenloop docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5345636455)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zenloop test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zenloop test report (commit [`cbcaba584d`](https://github.com/airbytehq/airbyte/pull/27556/commits/cbcaba584def39bad9d008a30b85a5f54c65f6e9)) - ✅

⏲️  Total pipeline duration: 175 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zenloop/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-zenloop docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5346001286)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zenloop test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zenloop test report (commit [`eb3fa98968`](https://github.com/airbytehq/airbyte/pull/27556/commits/eb3fa98968b9c5f7b4960f215a0022a497eccfc7)) - ✅

⏲️  Total pipeline duration: 201 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zenloop/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-zenloop docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/issue-26607_zenloop-migration-to-per-partition-cursor-2/1687440044/eb3fa98968b9c5f7b4960f215a0022a497eccfc7/source-zenloop/0.1.7/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zenloop test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zenloop test report (commit [`26aabf4180`](https://github.com/airbytehq/airbyte/pull/27556/commits/26aabf4180849d4661ae472d5f20d7dd37c12307)) - ✅

⏲️  Total pipeline duration: 134 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zenloop/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-zenloop docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/issue-26607_zenloop-migration-to-per-partition-cursor-2/1687440513/26aabf4180849d4661ae472d5f20d7dd37c12307/source-zenloop/0.1.7/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zenloop test
```

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
