### PR TITLE
Bump versions of langchain and langchain_core

### PR DESCRIPTION
**Pull request by sidoh**
## What
Update `langchain` and `langchain_core` to latest versions as of Jun 21, 2024.

https://github.com/airbytehq/airbyte/issues/40206

## How
Updated versions in `pyproject.toml` and ran `poetry update langchain langchain_core`

## User Impact
langchan 0.2 has some breaking changes: https://python.langchain.com/v0.2/docs/versions/v0_2/deprecations/, but didn't see anything listed that shows up in [destinations/vector_db_based](https://github.com/airbytehq/airbyte/tree/master/airbyte-cdk/python/airbyte_cdk/destinations/vector_db_based)

## Can this PR be safely reverted and rolled back?
- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by natikgadzhi — COMMENTED** [review]
Thanks @sidoh! Kicked off the tests. I'll wait for @aaronsteers to give it a read and double-check that our destinations are fine with 0.2.5.

**Comment by aaronsteers** [comment]
@sidoh -  Do you have a specific connector in mind that you are hoping to update? And by chance have you been able to test that locally or with a relative CDK reference?

**Comment by sidoh** [comment]
Hey @aaronsteers! Unfortunately not. Actually working on a project which uses airbyte-cdk as an upstream dependency.  There was not a way to ignore deps flagged as extra in poetry as far as I was able to tell.

**Comment by natikgadzhi** [comment]
@aaronsteers I need to at least switch destination-langchain to Poetry and base image, and figured I might as well try and get this over the finish line. Any objections? Do you know which other connectors are exposed to langchain directly and should be checked for compatibility?

**Comment by natikgadzhi** [comment]
@aaronsteers welp, langchain was archived, so that's not the greatest fit. But I figured if tests pass, we should probably roll this into a CDK minor version bump release. 

@girarda any objections?

**Comment by marcosmarxm** [comment]
@aaronsteers @girarda what are nex steps here?

**Comment by natikgadzhi** [comment]
Ah dammit I rebased this but can't push back into the PR. 

The CI failure looks mysterious. It could be just a formatting thing (but why would there be linter/formatter problems on a thing that is just a dependency), or an actual compatibility problem, and I haven't read into it too much.

But, it's generally a good idea to update I think.

**Comment by aaronsteers** [comment]
@natikgadzhi - I think I'll defer to you on this PR. While I prefer to pair CDK changes with an adapted connector (proving the change works), I understand this may be a special case. I'm going to drop my name from the PR reviewers: as this is a simple version bump, the bigger question is the downstream code. Feel free to bring me back as a reviewer if the PR grows or if you want an extra pair of eyes. Thanks!

**Comment by natikgadzhi** [comment]
/shrug Personally, I don't have an opinion and I don't know how much work will be there to upgrade our langchain destinations. But, I think there are security vulnerabilities, so that should be on @airbytehq/dev-python generally to get them up to date.

**Pull request closed without merging**
