### PR TITLE
Move qa engine to aibyte-ci

### LINKED ISSUE #25510: Move qa enginer to airbyte_ci (and update to use registry)

### PR DESCRIPTION
**Pull request by bnchrch**
## What
1. moves qa-engine to airbyte-ci
2. updates the project to use poetry
3. updates the automatic connector release to target `airbyte`

closes #25510 

## TODO
- [x] assign to issue
- [x] refactor tests
- [x] test locally
- [x] add readme

### CODE REVIEW

**Review by alafanechere — APPROVED** [review]
Neat! Thanks for the migration

**Comment by alafanechere** [comment]
Did you try to run the QA engine workflow from your branch?

**Comment by alafanechere** [comment]
I really love the fact that now enabling a connector for cloud is just changing the metadata.yaml and not opening a PR on another repo 👏

**Comment by alafanechere** [comment]
@bnchrch can you make sure all the connectors that were explicitly disabled from cloud in the late definitions masks file are correctly disabled according to their metadata file?

**Comment by bnchrch** [comment]
PR created all looks good. https://github.com/airbytehq/airbyte/pull/26818/files

**Pull request merged**
