### PR TITLE
🎉 Source Pipedrive - Missing Product Tables + relations

### LINKED ISSUE #19008: Source Pipedrive - Missing Product Tables + relations
## Tell us about the problem you're trying to solve
What are you trying to do, and why is it hard? A clear and concise description of what the problem is. Ex. I'm always frustrated when [THere is no way to get deal products, person related fields and deal related fields]

## Describe the solution you’d like

1. Add the followign missing content fron the following api endpoints:

    For missing products in deals:
     - https://developers.pipedrive.com/docs/api/v1/Products
     - https://developers.pipedrive.com/docs/api/v1/ProductFields

The next to endpoints will help discovering the relation between a deal and a product.
     - https://developers.pipedrive.com/docs/api/v1/Deals#getDealProducts
     - https://developers.pipedrive.com/docs/api/v1/Products#getProductDeals

3.   For missing persons relations with custom fields:
     The "persons fields" table should contain the field pipedrive id, wich is named as KEY.
     The "persons" table should columnized the custom fields KEY.

### PR DESCRIPTION
**Pull request by vidaletti**
## What
Fix and feat for Pipedrive source connector
- Fix missing products in deals
- Add relation between a deal and a product

Closes #19008 

## How
- Add the followign missing content fron the following api endpoints:

For missing products in deals:

https://developers.pipedrive.com/docs/api/v1/Products
https://developers.pipedrive.com/docs/api/v1/ProductFields

The next to endpoints will help discovering the relation between a deal and a product.
- https://developers.pipedrive.com/docs/api/v1/Deals#getDealProducts
- https://developers.pipedrive.com/docs/api/v1/Products#getProductDeals

- For missing persons relations with custom fields:
The "persons fields" table should contain the field pipedrive id, wich is named as KEY.
The "persons" table should columnized the custom fields KEY.
## Recommended reading order
1. airbyte-integrations/connectors/source-pipedrive/integration_tests/configured_catalog.json
2. airbyte-integrations/connectors/source-pipedrive/source_pipedrive/schemas/deal_products.json
3. airbyte-integrations/connectors/source-pipedrive/source_pipedrive/schemas/product_fields.json
4. airbyte-integrations/connectors/source-pipedrive/source_pipedrive/schemas/products.json
5. airbyte-integrations/connectors/source-pipedrive/source_pipedrive/source.py
6. airbyte-integrations/connectors/source-pipedrive/source_pipedrive/streams.py
7. airbyte-integrations/connectors/source-pipedrive/unit_tests/test_streams.py

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [x] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

### Unit
airbyte_unit_pipedrive

### CODE REVIEW

**Comment by vidaletti** [comment]
airbyte_unit_pipedrive

**Comment by vidaletti** [comment]
airbyte_unit_pipedrive

**Comment by sh4sh** [comment]
Woot! @vidaletti tag me once it's ready for review and I'll take a look

**Comment by vidaletti** [comment]
@sh4sh Released for review. My acceptance tests are generating timeout. I think it's because of the high volume of data.

**Comment by sh4sh** [comment]
@vidaletti thanks for the info, I've triggered a test run in https://github.com/airbytehq/airbyte/pull/22672 and will check back for the results.

In the meantime can you review and sign the CLA?

**Comment by marcosmarxm** [comment]
This was solved in https://github.com/airbytehq/airbyte/pull/23789
@vidaletti please update your Pipedrive connector to latest version.

**Pull request closed without merging**
