### PR TITLE
normalization: Fix failing mypy checks

### PR DESCRIPTION
**Pull request by alafanechere**
## What
After propagation of changes of this [PR](https://github.com/airbytehq/airbyte/pull/18387) in the CDK, the normalization mypy-check fails:
```
2022-10-26T22:03:54.7723746Z > Task :airbyte-integrations:bases:base-normalization:mypyCheck
2022-10-26T22:03:54.7724433Z 	 normalization/transform_catalog/stream_processor.py:11:1: error: Module
2022-10-26T22:03:54.7725391Z 	 "airbyte_cdk.models" does not explicitly export attribute "DestinationSyncMode";
2022-10-26T22:03:54.7726114Z 	 implicit reexport disabled  [attr-defined]
2022-10-26T22:03:54.7726623Z 	     from airbyte_cdk.models import DestinationSyncMode, SyncMode
```
## How

Use explicit imports:
`from airbyte_cdk.models.airbyte_protocol import DestinationSyncMode, SyncMode`

### CODE REVIEW

**Review by girarda — APPROVED** [review]

**Comment by edgao** [comment]
@alafanechere did you run normalization integration tests locally? (would be good to do a `/test connector=bases/base-normalization` if not, just for safety)

**Review by evantahler — APPROVED** [review]
The build is green so 👍!

**Review by edgao — APPROVED** [review]
one test failed because our redshift cluster is being dumb (we've seen this occasionally on other PRs). Other test cases all passed, :shipit:

```
	 15:43:53  Database Error in model stream_with_1000_columnsdngmx (models/generated/airbyte_tables/test_ephemeral_saecm/stream_with_1000_columnsdngmx.sql)
	 15:43:53    Out Of Memory: 
	 15:43:53    DETAIL:  
	 15:43:53      -----------------------------------------------
	 15:43:53      error:  Out Of Memory: 
	 15:43:53      code:      1004
	 15:43:53      context:   alloc(1048486,MtPartiQL)
	 15:43:53      query:     13359964
	 15:43:53      location:  alloc.cpp:493
	 15:43:53      process:   query0_120_13359964 [pid=18694]
	 15:43:53      -----------------------------------------------
```

**Pull request merged**
