### PR TITLE
🎉 Source Sentry: Add Releases stream

### PR DESCRIPTION
**Pull request by keiththompson**
## What
Added a new Releases Stream for the Sentry Connector

## How
*I just added an incremental stream for releases.*

## 🚨 User Impact 🚨
No breaking changes - Just a new stream so bumped the MINOR version, as per Semvar. 

## Pre-merge Checklist

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Comment by keiththompson** [comment]
<details><summary><strong>Unit Tests:</strong></summary>

```bash
❯ ./gradlew :airbyte-integrations:connectors:source-sentry:unitTest
Building all of Airbyte.
/Users/Keith/airbyte/airbyte-integrations/connectors

Task :airbyte-integrations:connectors:source-sentry:checkPython
Using python 3.9.11 from /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/.venv (.venv/bin/python)
Using pip 21.3.1 from /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/.venv/lib/python3.9/site-packages/pip (python 3.9)

Task :airbyte-integrations:connectors:source-sentry:pipInstall
[python] .venv/bin/python -m pip install pip==21.3.1
         Requirement already satisfied: pip==21.3.1 in ./.venv/lib/python3.9/site-packages (21.3.1)
         WARNING: You are using pip version 21.3.1; however, version 23.0.1 is available.
         You should consider upgrading via the '/Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/.venv/bin/python -m pip install --upgrade pip' command.
[python] .venv/bin/python -m pip list --format=columns
         Package                   Version   Editable project location
         ------------------------- --------- -------------------------------------------------------------------------
         airbyte-cdk               0.30.1
         airbyte-protocol-models   1.0.0
         attrs                     22.2.0
         backoff                   2.2.1
         black                     22.3.0
         cachetools                5.3.0
         cattrs                    22.2.0
         certifi                   2022.12.7
         charset-normalizer        3.1.0
         click                     8.1.3
         connector-acceptance-test 0.0.0     /Users/Keith/airbyte/airbyte-integrations/bases/connector-acceptance-test
         coverage                  6.3.1
         deepdiff                  5.8.1
         Deprecated                1.2.13
         docker                    5.0.3
         dpath                     2.0.8
         exceptiongroup            1.1.0
         fancycompleter            0.9.1
         flake8                    4.0.1
         genson                    1.2.2
         hypothesis                6.54.6
         hypothesis-jsonschema     0.20.1
         icdiff                    1.9.1
         idna                      3.4
         inflection                0.5.1
         iniconfig                 2.0.0
         isodate                   0.6.1
         isort                     5.6.4
         Jinja2                    3.1.2
         jsonref                   0.2
         jsonschema                3.2.0
         MarkupSafe                2.1.2
         mccabe                    0.6.1
         mypy                      0.930
         mypy-extensions           1.0.0
         ordered-set               4.1.0
         packaging                 23.0
         pathspec                  0.11.0
         pdbpp                     0.10.3
         pendulum                  2.1.2
         pip                       21.3.1
         platformdirs              3.1.0
         pluggy                    1.0.0
         pprintpp                  0.4.0
         py                        1.11.0
         pycodestyle               2.8.0
         pydantic                  1.9.2
         pyflakes                  2.4.0
         Pygments                  2.14.0
         pyproject-flake8          0.0.1a2
         pyrepl                    0.9.0
         pyrsistent                0.19.3
         pytest                    6.2.5
         pytest-cov                3.0.0
         pytest-mock               3.6.1
         pytest-sugar              0.9.6
         pytest-timeout            1.4.2
         python-dateutil           2.8.2
         pytzdata                  2020.1
         PyYAML                    5.4.1
         requests                  2.28.2
         requests-cache            1.0.0
         requests-mock             1.9.3
         setuptools                58.1.0
         six                       1.16.0
         sortedcontainers          2.4.0
         source-sentry             0.0.0
         termcolor                 2.2.0
         toml                      0.10.2
         tomli                     2.0.1
         typing_extensions         4.5.0
         url-normalize             1.4.3
         urllib3                   1.26.14
         websocket-client          1.5.1
         wmctrl                    0.4
         wrapt                     1.15.0
         WARNING: You are using pip version 21.3.1; however, version 23.0.1 is available.
         You should consider upgrading via the '/Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/.venv/bin/python -m pip install --upgrade pip' command.

Task :airbyte-integrations:connectors:source-sentry:_unitTestCoverage
[python] .venv/bin/python -m coverage run --data-file=unit_tests/.coverage.unitTest --rcfile=/Users/Keith/airbyte/pyproject.toml -m pytest -s unit_tests -c /Users/Keith/airbyte/pyproject.toml
         ============================= test session starts ==============================
         platform darwin -- Python 3.9.11, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/.venv/bin/python
         cachedir: .pytest_cache
         hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/.hypothesis/examples')
         rootdir: /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/unit_tests, configfile: ../../../../pyproject.toml
         plugins: hypothesis-6.54.6, requests-mock-1.9.3, mock-3.6.1, sugar-0.9.6, timeout-1.4.2, cov-3.0.0
         collecting ... collected 24 items
         
         unit_tests/test_source.py::test_source_wrong_credentials PASSED
         unit_tests/test_source.py::test_check_connection PASSED
         unit_tests/test_source.py::test_streams PASSED
         unit_tests/test_streams.py::test_next_page_token PASSED
         unit_tests/test_streams.py::test_next_page_token_is_none PASSED
         unit_tests/test_streams.py::test_next_page_token_raises[response0] PASSED
         unit_tests/test_streams.py::test_next_page_token_raises[response1] PASSED
         unit_tests/test_streams.py::test_events_path PASSED
         unit_tests/test_streams.py::test_issues_path PASSED
         unit_tests/test_streams.py::test_projects_path PASSED
         unit_tests/test_streams.py::test_project_detail_path PASSED
         unit_tests/test_streams.py::test_sentry_stream_pagination_request_params PASSED
         unit_tests/test_streams.py::test_events_request_params PASSED
         unit_tests/test_streams.py::test_issues_request_params PASSED
         unit_tests/test_streams.py::test_projects_request_params PASSED
         unit_tests/test_streams.py::test_project_detail_request_params PASSED
         unit_tests/test_streams.py::test_validate_state_value[No State] PASSED
         unit_tests/test_streams.py::test_validate_state_value[State is Empty String] PASSED
         unit_tests/test_streams.py::test_validate_state_value[State is 'None'] PASSED
         unit_tests/test_streams.py::test_validate_state_value[State is present] PASSED
         unit_tests/test_streams.py::test_get_state_value[No State] PASSED
         unit_tests/test_streams.py::test_get_state_value[State is Empty String] PASSED
         unit_tests/test_streams.py::test_get_state_value[State is 'None'] PASSED
         unit_tests/test_streams.py::test_get_state_value[State is present] PASSED
         
         =============================== warnings summary ===============================
         test_source.py::test_source_wrong_credentials
           /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/unit_tests/test_source.py:14: DeprecationWarning: Call to deprecated class AirbyteLogger. (Use logging.getLogger('airbyte') instead) -- Deprecated since version 0.1.47.
             status, error = source.check_connection(logger=AirbyteLogger(), config={"auth_token": "test_auth_token"})
         
         test_source.py::test_source_wrong_credentials
         test_source.py::test_check_connection
           /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/source_sentry/source.py:21: DeprecationWarning: Call to deprecated class TokenAuthenticator. (Use airbyte_cdk.sources.streams.http.requests_native_auth.TokenAuthenticator instead) -- Deprecated since version 0.1.20.
             authenticator=TokenAuthenticator(token=config["auth_token"]),
         
         test_source.py: 10 warnings
         test_streams.py: 21 warnings
           /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/.venv/lib/python3.9/site-packages/deprecated/classic.py:173: DeprecationWarning: Call to deprecated class HttpAuthenticator. (Use requests.auth.AuthBase instead) -- Deprecated since version 0.1.20.
             return old_new1(cls, *args, **kwargs)
         
         test_source.py: 7 warnings
         test_streams.py: 21 warnings
           /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py:45: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
             self._authenticator: HttpAuthenticator = NoAuth()
         
         test_source.py::test_streams
           /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/source_sentry/source.py:31: DeprecationWarning: Call to deprecated class TokenAuthenticator. (Use airbyte_cdk.sources.streams.http.requests_native_auth.TokenAuthenticator instead) -- Deprecated since version 0.1.20.
             "authenticator": TokenAuthenticator(token=config["auth_token"]),
         
         -- Docs: https://docs.pytest.org/en/stable/warnings.html
         ======================= 24 passed, 63 warnings in 0.34s ========================

Task :airbyte-integrations:connectors:source-sentry:unitTest
Name                        Stmts   Miss  Cover
-----------------------------------------------
source_sentry/source.py        18      0   100%
source_sentry/__init__.py       2      0   100%
source_sentry/streams.py      109     16    85%
-----------------------------------------------
TOTAL                         129     16    88%

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 6s
17 actionable tasks: 4 executed, 13 up-to-date
```

</details>

I don't believe I have the capacity to run the integration tests or acceptance tests from my machine. I get a lot of errors for missing files that I think only maintainers have access to.

**Comment by keiththompson** [comment]
@marcosmarxm An update on tests: I've removed the new stream from `integration_tests/configured_catalog.json` because I can't update the fixtures in `integration_tests/expected_records.jsonl` without access to the Sentry project that's configured on the maintainers side. 

I'm still seeing issue's that I think are unrelated to my changes:

<detail><summary>Output</summary>

```shell
./gradlew :airbyte-integrations:connectors:source-sentry:integrationTest

Building all of Airbyte.
/Users/Keith/airbyte/airbyte-integrations/connectors

> Task :airbyte-integrations:connectors:source-sentry:checkPython
Using python 3.9.11 from /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/.venv (.venv/bin/python)
Using pip 21.3.1 from /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/.venv/lib/python3.9/site-packages/pip (python 3.9)

> Task :airbyte-integrations:connectors:source-sentry:pipInstall
[python] .venv/bin/python -m pip install pip==21.3.1
         Requirement already satisfied: pip==21.3.1 in ./.venv/lib/python3.9/site-packages (21.3.1)
         WARNING: You are using pip version 21.3.1; however, version 23.0.1 is available.
         You should consider upgrading via the '/Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/.venv/bin/python -m pip install --upgrade pip' command.
[python] .venv/bin/python -m pip list --format=columns
         Package                   Version   Editable project location
         ------------------------- --------- -------------------------------------------------------------------------
         airbyte-cdk               0.30.1
         airbyte-protocol-models   1.0.0
         attrs                     22.2.0
         backoff                   2.2.1
         black                     22.3.0
         cachetools                5.3.0
         cattrs                    22.2.0
         certifi                   2022.12.7
         charset-normalizer        3.1.0
         click                     8.1.3
         connector-acceptance-test 0.0.0     /Users/Keith/airbyte/airbyte-integrations/bases/connector-acceptance-test
         coverage                  6.3.1
         deepdiff                  5.8.1
         Deprecated                1.2.13
         docker                    5.0.3
         dpath                     2.0.8
         exceptiongroup            1.1.0
         fancycompleter            0.9.1
         flake8                    4.0.1
         genson                    1.2.2
         hypothesis                6.54.6
         hypothesis-jsonschema     0.20.1
         icdiff                    1.9.1
         idna                      3.4
         inflection                0.5.1
         iniconfig                 2.0.0
         isodate                   0.6.1
         isort                     5.6.4
         Jinja2                    3.1.2
         jsonref                   0.2
         jsonschema                3.2.0
         MarkupSafe                2.1.2
         mccabe                    0.6.1
         mypy                      0.930
         mypy-extensions           1.0.0
         ordered-set               4.1.0
         packaging                 23.0
         pathspec                  0.11.0
         pdbpp                     0.10.3
         pendulum                  2.1.2
         pip                       21.3.1
         platformdirs              3.1.0
         pluggy                    1.0.0
         pprintpp                  0.4.0
         py                        1.11.0
         pycodestyle               2.8.0
         pydantic                  1.9.2
         pyflakes                  2.4.0
         Pygments                  2.14.0
         pyproject-flake8          0.0.1a2
         pyrepl                    0.9.0
         pyrsistent                0.19.3
         pytest                    6.2.5
         pytest-cov                3.0.0
         pytest-mock               3.6.1
         pytest-sugar              0.9.6
         pytest-timeout            1.4.2
         python-dateutil           2.8.2
         pytzdata                  2020.1
         PyYAML                    5.4.1
         requests                  2.28.2
         requests-cache            1.0.0
         requests-mock             1.9.3
         setuptools                58.1.0
         six                       1.16.0
         sortedcontainers          2.4.0
         source-sentry             0.0.0
         termcolor                 2.2.0
         toml                      0.10.2
         tomli                     2.0.1
         typing_extensions         4.5.0
         url-normalize             1.4.3
         urllib3                   1.26.14
         websocket-client          1.5.1
         wmctrl                    0.4
         wrapt                     1.15.0
         WARNING: You are using pip version 21.3.1; however, version 23.0.1 is available.
         You should consider upgrading via the '/Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/.venv/bin/python -m pip install --upgrade pip' command.

> Task :airbyte-integrations:connectors:source-sentry:isortFormat
[python] .venv/bin/python -m isort --settings-file=/Users/Keith/airbyte/pyproject.toml ./
         Skipped 2 files

> Task :airbyte-integrations:connectors:source-sentry:blackFormat
[python] .venv/bin/python -m black --config /Users/Keith/airbyte/pyproject.toml ./
         All done! ✨ 🍰 ✨
         5 files left unchanged.

> Task :airbyte-integrations:connectors:source-sentry:flakeCheck
[python] .venv/bin/python -m pflake8 --config /Users/Keith/airbyte/pyproject.toml ./

> Task :airbyte-integrations:connectors:source-sentry:_unitTestCoverage
[python] .venv/bin/python -m coverage run --data-file=unit_tests/.coverage.unitTest --rcfile=/Users/Keith/airbyte/pyproject.toml -m pytest -s unit_tests -c /Users/Keith/airbyte/pyproject.toml
         ============================= test session starts ==============================
         platform darwin -- Python 3.9.11, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/.venv/bin/python
         cachedir: .pytest_cache
         hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/.hypothesis/examples')
         rootdir: /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/unit_tests, configfile: ../../../../pyproject.toml
         plugins: hypothesis-6.54.6, requests-mock-1.9.3, mock-3.6.1, sugar-0.9.6, timeout-1.4.2, cov-3.0.0
         collecting ... collected 24 items
         
         unit_tests/test_source.py::test_source_wrong_credentials PASSED
         unit_tests/test_source.py::test_check_connection PASSED
         unit_tests/test_source.py::test_streams PASSED
         unit_tests/test_streams.py::test_next_page_token PASSED
         unit_tests/test_streams.py::test_next_page_token_is_none PASSED
         unit_tests/test_streams.py::test_next_page_token_raises[response0] PASSED
         unit_tests/test_streams.py::test_next_page_token_raises[response1] PASSED
         unit_tests/test_streams.py::test_events_path PASSED
         unit_tests/test_streams.py::test_issues_path PASSED
         unit_tests/test_streams.py::test_projects_path PASSED
         unit_tests/test_streams.py::test_project_detail_path PASSED
         unit_tests/test_streams.py::test_sentry_stream_pagination_request_params PASSED
         unit_tests/test_streams.py::test_events_request_params PASSED
         unit_tests/test_streams.py::test_issues_request_params PASSED
         unit_tests/test_streams.py::test_projects_request_params PASSED
         unit_tests/test_streams.py::test_project_detail_request_params PASSED
         unit_tests/test_streams.py::test_validate_state_value[No State] PASSED
         unit_tests/test_streams.py::test_validate_state_value[State is Empty String] PASSED
         unit_tests/test_streams.py::test_validate_state_value[State is 'None'] PASSED
         unit_tests/test_streams.py::test_validate_state_value[State is present] PASSED
         unit_tests/test_streams.py::test_get_state_value[No State] PASSED
         unit_tests/test_streams.py::test_get_state_value[State is Empty String] PASSED
         unit_tests/test_streams.py::test_get_state_value[State is 'None'] PASSED
         unit_tests/test_streams.py::test_get_state_value[State is present] PASSED
         
         =============================== warnings summary ===============================
         test_source.py::test_source_wrong_credentials
           /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/unit_tests/test_source.py:14: DeprecationWarning: Call to deprecated class AirbyteLogger. (Use logging.getLogger('airbyte') instead) -- Deprecated since version 0.1.47.
             status, error = source.check_connection(logger=AirbyteLogger(), config={"auth_token": "test_auth_token"})
         
         test_source.py::test_source_wrong_credentials
         test_source.py::test_check_connection
           /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/source_sentry/source.py:21: DeprecationWarning: Call to deprecated class TokenAuthenticator. (Use airbyte_cdk.sources.streams.http.requests_native_auth.TokenAuthenticator instead) -- Deprecated since version 0.1.20.
             authenticator=TokenAuthenticator(token=config["auth_token"]),
         
         test_source.py: 10 warnings
         test_streams.py: 21 warnings
           /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/.venv/lib/python3.9/site-packages/deprecated/classic.py:173: DeprecationWarning: Call to deprecated class HttpAuthenticator. (Use requests.auth.AuthBase instead) -- Deprecated since version 0.1.20.
             return old_new1(cls, *args, **kwargs)
         
         test_source.py: 7 warnings
         test_streams.py: 21 warnings
           /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py:45: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
             self._authenticator: HttpAuthenticator = NoAuth()
         
         test_source.py::test_streams
           /Users/Keith/airbyte/airbyte-integrations/connectors/source-sentry/source_sentry/source.py:31: DeprecationWarning: Call to deprecated class TokenAuthenticator. (Use airbyte_cdk.sources.streams.http.requests_native_auth.TokenAuthenticator instead) -- Deprecated since version 0.1.20.
             "authenticator": TokenAuthenticator(token=config["auth_token"]),
         
         -- Docs: https://docs.pytest.org/en/stable/warnings.html
         ======================= 24 passed, 63 warnings in 0.93s ========================

> Task :airbyte-integrations:connectors:source-sentry:unitTest
Name                        Stmts   Miss  Cover
-----------------------------------------------
source_sentry/source.py        18      0   100%
source_sentry/__init__.py       2      0   100%
source_sentry/streams.py      109     16    85%
-----------------------------------------------
TOTAL                         129     16    88%

> Task :airbyte-integrations:connectors:source-sentry:airbyteDocker
#1 [internal] load build definition from Dockerfile
#1 sha256:2ad9f8670b9dc5755be051ac9edd3b85ea4ac816238c899c08957b2f8bf634d1
#1 transferring dockerfile: 37B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:854adb1d4c3f0afee8c890a98f176b16ee945d92af930fd38f7f023879897082
#2 transferring context: 34B 0.0s done
#2 DONE 0.1s

#3 [internal] load metadata for docker.io/library/python:3.9.11-alpine3.15
#3 sha256:4bb51603261f45ba702ac1be2ba97d7e21b2516f8ff633d494a9d8042fc7d4c1
#3 DONE 0.7s

#4 [base 1/1] FROM docker.io/library/python:3.9.11-alpine3.15@sha256:45ddd216e6b4efee0617e15d541e9148ffd6898203fcbe86a9f5bf906ce7837f
#4 sha256:042a70464014ac01ebaff317544a292e38ffd78827f76150347277458594da67
#4 DONE 0.0s

#7 [internal] load build context
#7 sha256:724c29a1b7ed24c399590136e4354eab3f32455feeb3d3fb4aecc19e8525f73c
#7 transferring context: 878B done
#7 DONE 0.0s

#9 [builder 4/4] RUN pip install --prefix=/install .
#9 sha256:71813eeb2e0add2e27d5a681543d5a5fed3c6e1e7c220a44a19e85b522fe4e02
#9 CACHED

#10 [stage-2 2/7] COPY --from=builder /install /usr/local
#10 sha256:54e4d3ebc25522f3d10fb0f8bf434567a8c3ee1717cbbe3b3013e7748e1a56a3
#10 CACHED

#5 [builder 1/4] WORKDIR /airbyte/integration_code
#5 sha256:452f1f6f942ae7dfe39a4688b1c027eb0fe89491d7c84a70c4a597f3b9956df6
#5 CACHED

#8 [builder 3/4] COPY setup.py ./
#8 sha256:f343710766c07af10b071ebcaf29d82000d041f301a8ac5224a97cbf1cdb6ecb
#8 CACHED

#11 [stage-2 3/7] COPY --from=builder /usr/share/zoneinfo/Etc/UTC /etc/localtime
#11 sha256:24eb23cde777be3948205a10fd1e55e16f9fc618b5ebcbd7b39f9a5451ecdd28
#11 CACHED

#12 [stage-2 4/7] RUN echo "Etc/UTC" > /etc/timezone
#12 sha256:b5908a52aaca9cace38a8e49af099862e8f8f34e0d1c4902c51cc577ead8c73d
#12 CACHED

#14 [stage-2 6/7] COPY main.py ./
#14 sha256:f545719fd140e6da125254c986e5f87dc8744f27b91a5f74e15e48e7ccee7a64
#14 CACHED

#13 [stage-2 5/7] RUN apk --no-cache add bash
#13 sha256:1352ade94e1e040584826354f51ba5cde48de05c17ee576deff62cc8b176e177
#13 CACHED

#6 [builder 2/4] RUN apk --no-cache upgrade     && pip install --upgrade pip     && apk --no-cache add tzdata build-base
#6 sha256:9df3c507293e8fbd43ddab6c0e25fc1e8d41055d7798c311fcb7cbf055fbaed4
#6 CACHED

#15 [stage-2 7/7] COPY source_sentry ./source_sentry
#15 sha256:c8b9e3dc1057a4c4c70aaedb5ca73058c1d385c68eafaf520aaba76bd75b112d
#15 CACHED

#16 exporting to image
#16 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#16 exporting layers done
#16 writing image sha256:67c155d9431f520605cb2fb48b299ed8efda739d328c864efa2b2b99d29f474b done
#16 naming to docker.io/airbyte/source-sentry:dev done
#16 DONE 0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

> Task :airbyte-integrations:connectors:source-sentry:connectorAcceptanceTest
latest: Pulling from airbyte/connector-acceptance-test
Digest: sha256:586ac71a07285ec74ae4c57245113fc8312357591d4778fbb52135109c1d0347
Status: Image is up to date for airbyte/connector-acceptance-test:latest
docker.io/airbyte/connector-acceptance-test:latest
============================= test session starts ==============================
platform linux -- Python 3.9.11, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /test_input
plugins: requests-mock-1.9.3, timeout-1.4.2, sugar-0.9.6, mock-3.6.1, hypothesis-6.54.6, cov-3.0.0
collected 38 items

test_core.py ..................s............E.                           [ 86%]
test_full_refresh.py .E                                                  [ 92%]
test_incremental.py ...                                                  [100%]


==================================== ERRORS ====================================
______________ ERROR at setup of TestBasicRead.test_read[inputs0] ______________

test_strictness_level = <TestStrictnessLevel.high: 'high'>
configured_catalog = ConfiguredAirbyteCatalog(streams=[ConfiguredAirbyteStream(stream=AirbyteStream(name='events', json_schema={'$schema': ...'>, cursor_field=['dateCreated'], destination_sync_mode=<DestinationSyncMode.append: 'append'>, primary_key=[['id']])])
empty_streams = set()
expect_records_config = ExpectedRecordsConfig(bypass_reason=None, path=PosixPath('integration_tests/expected_records.jsonl'), extra_fields=False, exact_order=False, extra_records=True)
base_path = PosixPath('/test_input')

    @pytest.fixture(name="expected_records_by_stream")
    def expected_records_by_stream_fixture(
        test_strictness_level: Config.TestStrictnessLevel,
        configured_catalog: ConfiguredAirbyteCatalog,
        empty_streams: Set[EmptyStreamConfiguration],
        expect_records_config: ExpectedRecordsConfig,
        base_path,
    ) -> MutableMapping[str, List[MutableMapping]]:
        def enforce_high_strictness_level_rules(expect_records_config, configured_catalog, empty_streams, records_by_stream) -> Optional[str]:
            error_prefix = "High strictness level error: "
            if expect_records_config is None:
                pytest.fail(error_prefix + "expect_records must be configured for the basic_read test.")
            elif expect_records_config.path:
                not_seeded_streams = find_not_seeded_streams(configured_catalog, empty_streams, records_by_stream)
                if not_seeded_streams:
                    pytest.fail(
                        error_prefix
                        + f"{', '.join(not_seeded_streams)} streams are declared in the catalog but do not have expected records. Please add expected records to {expect_records_config.path} or declare these streams in empty_streams."
                    )
            else:
                if not getattr(expect_records_config, "bypass_reason", None):
                    pytest.fail(error_prefix / "A bypass reason must be filled if no path to expected records is provided.")
    
        expected_records_by_stream = {}
        if expect_records_config:
            if expect_records_config.path:
                expected_records_file_path = str(base_path / expect_records_config.path)
                with open(expected_records_file_path, "r") as f:
                    all_records = [AirbyteRecordMessage.parse_raw(line) for line in f]
                    expected_records_by_stream = TestBasicRead.group_by_stream(all_records)
    
        if test_strictness_level is Config.TestStrictnessLevel.high:
>           enforce_high_strictness_level_rules(expect_records_config, configured_catalog, empty_streams, expected_records_by_stream)

/usr/local/lib/python3.9/site-packages/connector_acceptance_test/conftest.py:252: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

expect_records_config = ExpectedRecordsConfig(bypass_reason=None, path=PosixPath('integration_tests/expected_records.jsonl'), extra_fields=False, exact_order=False, extra_records=True)
configured_catalog = ConfiguredAirbyteCatalog(streams=[ConfiguredAirbyteStream(stream=AirbyteStream(name='events', json_schema={'$schema': ...'>, cursor_field=['dateCreated'], destination_sync_mode=<DestinationSyncMode.append: 'append'>, primary_key=[['id']])])
empty_streams = set()
records_by_stream = defaultdict(<class 'list'>, {'events': [{'id': '998767def62640f99ecc2720da60b798', 'groupID': '3879509212', 'eventID':...{'organizationUrl': 'https://airbyte-09.sentry.io', 'regionUrl': 'https://us.sentry.io'}, 'hasAuthProvider': False}}]})

    def enforce_high_strictness_level_rules(expect_records_config, configured_catalog, empty_streams, records_by_stream) -> Optional[str]:
        error_prefix = "High strictness level error: "
        if expect_records_config is None:
            pytest.fail(error_prefix + "expect_records must be configured for the basic_read test.")
        elif expect_records_config.path:
            not_seeded_streams = find_not_seeded_streams(configured_catalog, empty_streams, records_by_stream)
            if not_seeded_streams:
>               pytest.fail(
                    error_prefix
                    + f"{', '.join(not_seeded_streams)} streams are declared in the catalog but do not have expected records. Please add expected records to {expect_records_config.path} or declare these streams in empty_streams."
                )
E               Failed: High strictness level error: releases streams are declared in the catalog but do not have expected records. Please add expected records to integration_tests/expected_records.jsonl or declare these streams in empty_streams.

/usr/local/lib/python3.9/site-packages/connector_acceptance_test/conftest.py:235: Failed
_______ ERROR at setup of TestFullRefresh.test_sequential_reads[inputs1] _______

base_path = PosixPath('/test_input')
connector_config_path = PosixPath('/test_input/secrets/config_limited_scopes.json')

    @pytest.fixture(name="connector_config")
    def connector_config_fixture(base_path, connector_config_path) -> SecretDict:
>       with open(str(connector_config_path), "r") as file:
E       FileNotFoundError: [Errno 2] No such file or directory: '/test_input/secrets/config_limited_scopes.json'

/usr/local/lib/python3.9/site-packages/connector_acceptance_test/conftest.py:122: FileNotFoundError
=========================== short test summary info ============================
ERROR test_core.py::TestBasicRead::test_read[inputs0] - Failed: High strictne...
ERROR test_full_refresh.py::TestFullRefresh::test_sequential_reads[inputs1]
SKIPPED [1] ../usr/local/lib/python3.9/site-packages/connector_acceptance_test/tests/test_core.py:100: The previous and actual specifications are identical.
============== 35 passed, 1 skipped, 2 errors in 62.08s (0:01:02) ==============

> Task :airbyte-integrations:connectors:source-sentry:connectorAcceptanceTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':airbyte-integrations:connectors:source-sentry:connectorAcceptanceTest'.
> Process 'command 'docker'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 19s
27 actionable tasks: 9 executed, 18 up-to-date
```

</detail>

**Comment by keiththompson** [comment]
@marcosmarxm - I'm not sure how I proceed here, any advice?

**Comment by marcosmarxm** [comment]
@keiththompson the changes you made looks good. I'm testing in https://github.com/airbytehq/airbyte/pull/24768/ because I don't have permission to push commits to your branch. Thanks!

**Review by marcosmarxm — APPROVED** [review]

**Comment by marcosmarxm** [comment]
Published in https://github.com/airbytehq/airbyte/pull/24768

**Comment by jrolom** [comment]
@marcosmarxm I noticed this was closed 3 weeks ago - what's the next steps to merge this PR? Thanks

**Comment by marcosmarxm** [comment]
You need to update the version in the UI to latest one.

**Comment by marcosmarxm** [comment]
> @marcosmarxm I noticed this was closed 3 weeks ago - what's the next steps to merge this PR? Thanks

The PR was merged at Published in https://github.com/airbytehq/airbyte/pull/24768

**Pull request closed without merging**
