### PR TITLE
🐛 Destination Typesense: fix writing multiple streams

### LINKED ISSUE #29816: Destination Typesense: data written to single index
### Connector Name

destination-typesense

### Connector Version

`>=0.1.0`

### What step the error happened?

Configuring a new connector

### Revelant information

Destination typesense suffers the same bug as #19205. Indexes are created for all streams but all records are written to the first index.

I have a fix that I will add in the comments.

### Relevant log output

_No response_

### Contribute

- [X] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by gmanninglive**
Fixes #29816

## What
Records for all streams are written to only the first index

## How
1. Move write loop out of index creation loop
2. Pass stream name to queue_write_operation method.
3. Within flush method, group write_buffer elements by stream name, and iterate to flush
4. Update integration test to assert multiple streams written to their respective indexes  

## Recommended reading order
1. destination.py
2. writer.py
3. integration_test.py

## 🚨 User Impact 🚨
Should make this destination usable for multiple streams

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by RaphaPlato** [comment]
@marcosmarxm if you get a chance to take a look at this PR, seems related to another PR you approved recently

**Comment by mbrimmer83** [comment]
Need this urgently

**Comment by gmanninglive** [comment]
@mbrimmer83
> @gmanninglive Do you know what the hold up is with this PR?

Nothing from my side, It just hasn't been reviewed yet. #27692 is in the same situation.

@marcosmarxm I'm sure you've got a lot on your plate, but any updates on the state of this PR / issue #29816, would be really appreciated.

**Comment by marcosmarxm** [comment]
Sorry the delay @gmanninglive and lack of updates. I'll return a review during the week, thanks!

**Review by marcosmarxm — APPROVED** [review]

**Comment by mbrimmer83** [comment]
@gmanninglive @marcosmarxm I just upgraded my Typesense destination after the release and the connector is working beautifully so far. Thanks for getting this in today.

**Pull request merged**
