### PR TITLE
Fix spec orders for yugabyte, sftp-bulk, gnews

### PR DESCRIPTION
**Pull request by flash1293**
The `order` property in specs should not be duplicated. As some specs have been doing this, this PR is adjusting them

Related to https://github.com/airbytehq/airbyte/pull/24055

### CODE REVIEW

**Comment by flash1293** [comment]
@bnchrch The test failures for source-gnews don't look related to this very small change, I would like to publish this even with failing tests. Are you OK with that?

**Comment by flash1293** [comment]
@bnchrch The test failures for source-gnews don't look related to this very small change, I would like to publish this even with failing tests. Are you OK with that?

**Review by bnchrch — APPROVED** [review]

**Comment by bnchrch** [comment]
And @flash1293 i'd say we should be safe to merge gnews, I dont think the failure is related and its alpha

**Comment by flash1293** [comment]
Gnews is causing problems - it did release a version but it's broken:
```
➜  airbyte git:(fix-specs) ✗ docker run airbyte/source-gnews:0.1.4 spec
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 12, in <module>
    source = SourceGnews()
  File "/airbyte/integration_code/source_gnews/source.py", line 18, in __init__
    super().__init__(**{"path_to_yaml": "manifest.yaml"})
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/yaml_declarative_source.py", line 21, in __init__
    super().__init__(source_config, debug)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py", line 76, in __init__
    self._validate_source()
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py", line 166, in _validate_source
    for stream_config in self._stream_configs(self._legacy_source_config)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py", line 194, in _stream_configs
    s["type"] = "DeclarativeStream"
TypeError: 'str' object does not support item assignment
```

I think it's related to the recent CDK version bump @brianjlai could you take a look whether we can fix this forward? If it's a larger job I would like to split out gnews from this PR as it needs more work anyway

**Comment by flash1293** [comment]
@brianjlai Maybe I found the problem with gnews - it had the CDK pinned to a specific pretty old version. I updated to the most recent one and at least the spec command works again. Running full tests via CI

**Pull request merged**
