### PR TITLE
New destination: databend (community PR #19815)

### LINKED ISSUE #21140: Assist Databend destination contribution
A community member sumbitted a new destination connector for [Databend](https://www.databend.com/) in this [PR](https://github.com/airbytehq/airbyte/pull/19815). This tracking the work on getting this PR reviewed and merged, and getting the connector tested and published.
Work is being done in this PR: https://github.com/airbytehq/airbyte/pull/20909

### PR DESCRIPTION
**Pull request by grishick**
Fixes https://github.com/airbytehq/airbyte/issues/21140

Taking this community [PR](https://github.com/airbytehq/airbyte/pull/19815) last mile to rebase and add integration tests.

### CODE REVIEW

**Comment by flash1293** [comment]
We don't have good documentation around this yet (it's [planned though](https://github.com/airbytehq/airbyte/issues/20864)), but ideally all connector icons are square and have a padding around them - there is a PR open fixing this for a lot of existing connectors here: https://github.com/airbytehq/airbyte/pull/20547

Could we try to do this from the start for this one? I can also help with this if necessary.

**Comment by grishick** [comment]
Will have to remove normalization from the first version, because:
 1.` dbt-databend`  doesn't support `ephemeral`; 
 2. There are some functions that databend kernel not support such as `lag`

**Comment by grishick** [comment]
> We don't have good documentation around this yet (it's [planned though](https://github.com/airbytehq/airbyte/issues/20864)), but ideally all connector icons are square and have a padding around them - there is a PR open fixing this for a lot of existing connectors here: #20547
> 
> Could we try to do this from the start for this one? I can also help with this if necessary.

What are the requirements/parameters for the icon other than being square? E.g., min/max dimension,  amount of padding, transparent or not?

**Comment by flash1293** [comment]
Rhe dimension shouldn't matter as it's a vector graphic, transparent background is a clear yes, I'm not sure about the padding. Do you know @josephkmh ?

**Comment by josephkmh** [comment]
> The dimensions shouldn't matter as it's a vector graphic, transparent background is a clear yes, I'm not sure about the padding. Do you know @josephkmh ?

I'm afraid I don't know the rules for padding, and I can't tell what they should be based on the [open PR](https://github.com/airbytehq/airbyte/pull/20547). I think @timroes or @Upmitt would have to chime in here.

For this PR I assume it would suffice to submit a square icon, and the padding can be added later.

**Comment by grishick** [comment]
> PR

I updated the logo with a new file @hantmac sent me. Please check.

**Comment by josephkmh** [comment]
@grishick I just pushed [a commit](https://github.com/airbytehq/airbyte/pull/20909/commits/552481e8fa7bbe1e22bf250a7eea2807b8392fa3) to make the logo square, that should be good for now!

**Comment by grishick** [comment]
Adding @etsybaev to reviewers as current OC

**Review by natalyjazzviolin — APPROVED** [review]
LGTM!

**Pull request merged**
