### PR TITLE
🎉 New Destination: Typesense

### PR DESCRIPTION
**Pull request by cirdes**
## What
[Typesense](https://typesense.org/) is a modern, privacy-friendly, open source search engine built from the ground up using cutting-edge search algorithms, that take advantage of the latest advances in hardware capabilities.

It is an alternative to Elasticsearch, Algolia and Meilisearch

## How
This PR adds Typesense as a destination

## Recommended reading order
1. `spec.yaml`
2. `destionation.py`
3. `writer.py`

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

```
 python -m pytest -s -vv unit_tests
==================================================================================================== test session starts =====================================================================================================
platform darwin -- Python 3.9.11, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 --
cachedir: .pytest_cache
collected 2 items

unit_tests/unit_test.py::test_queue_write_operation PASSED
unit_tests/unit_test.py::test_flush {"type": "LOG", "log": {"level": "INFO", "message": "flushing 2 records"}}
PASSED

===================================================================================================== 2 passed in 0.52s ======================================================================================================

```

</details>

<details><summary><strong>Integration</strong></summary>

```
❯ python -m pytest -s -vv integration_tests
==================================================================================================== test session starts =====================================================================================================
platform darwin -- Python 3.9.11, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
cachedir: .pytest_cache
collected 3 items

integration_tests/integration_test.py::test_check_valid_config PASSED
integration_tests/integration_test.py::test_check_invalid_config PASSED
integration_tests/integration_test.py::test_write {"type": "LOG", "log": {"level": "INFO", "message": "flushing 2 records"}}
PASSED

===================================================================================================== 3 passed in 10.14s =====================================================================================================
```

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

Screen Shot 2022-10-23 at 8 18 19 PM

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks for the contribution @cirdes someone will review during the week.

**Review by marcosmarxm — COMMENTED** [review]
I tested using credentials but it is failing. I'll try to create a cloud account in Typesense. Thanks for the contribution @cirdes

**Review by marcosmarxm — APPROVED** [review]

**Comment by T4Eskynet** [comment]
@cirdes @marcosmarxm Typesense has a geopoint field type that expects an array 
https://typesense.org/docs/0.24.1/api/geosearch.html#searching-within-a-radius
e.g:
```
let document = {
  'title': 'Louvre Museuem',
  'location': [48.86093481609114, 2.33698396872901]
}
```

When fetching data from some sources, airbyte converts it to String, adding quotation marks and the migration fails.
Typsense receives 
 'location': **"**[48.86093481609114, 2.33698396872901]**"**.
instead of
 'location': [48.86093481609114, 2.33698396872901],

**Pull request merged**
