### PR TITLE
fix(concurrent-cdk): follow-up #44946 update state to state_manager state in convert to concurrent stream

### PR DESCRIPTION
**Pull request by lazebnyi**
## What

Following: https://github.com/airbytehq/airbyte/pull/44946

The `convert_to_concurrent_stream` method defines the state as the cursor state if the state is defined. However, this impacts cases where the state is already defined, and the legacy state should be passed to the stream factory for correct parsing.

## How
Change the state definition to use the `state_manager` stream state instead of the cursor.

## User Impact
No

## Can this PR be safely reverted and rolled back?
- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by brianjlai — COMMENTED** [review]
No issues with the code change itself since its seems pretty straightforward. However, what I want to make sure I understand is what the bug in the code was and how things were able to work prior to your fix and intended behavior

Let's call the incoming stream state we receive from the platform the raw stream state. Right now we instantiate the cursor we set the concurrent state from `self._get_concurrent_state(stream_state)`. And this is the translated concurrent state which the existing stream's weren't expecting? So hence we pass in the raw state from the state manager.

Two questions:

- What was the previous behavior before the fix, were our streams unable to parse the now transformed state and failing?
- Would this become a problem on the second sync? On the first sync we take raw state and pass it to the stream. And as we update and manage state through the sync, we eventually persist the concurrent state messages back to the platform. And on the next sync both the raw and concurrent states would be the same

**Comment by lazebnyi** [comment]
For the [previous behavior](https://github.com/airbytehq/airbyte/blob/56d1650e669373c6c8db0c8d6f3a0f80b7f16687/airbyte-integrations/connectors/source-salesforce/source_salesforce/source.py#L238), we use the state manager because it is the only component that stores the legacy state format.

No, this should be fine since we convert the legacy state to the new format using [convert_from_sequential_state](https://github.com/airbytehq/airbyte/blob/56d1650e669373c6c8db0c8d6f3a0f80b7f16687/airbyte-cdk/python/airbyte_cdk/sources/streams/concurrent/state_converters/abstract_stream_state_converter.py#L87). After conversion, we emit the state in the old format as shown here: [cursor emit state](https://github.com/airbytehq/airbyte/blob/56d1650e669373c6c8db0c8d6f3a0f80b7f16687/airbyte-cdk/python/airbyte_cdk/sources/streams/concurrent/cursor.py#L236).

**Review by brianjlai — APPROVED** [review]
@lazebnyi thanks for updating the ticket w/ our discussions from earlier today. lgtm

**Pull request merged**
