### PR TITLE
 ✨Source Hubplanner: Migrate Python CDK to Low-code CDK

### LINKED ISSUE #29285: Hubplanner
https://docs.airbyte.com/integrations/sources/hubplanner

### PR DESCRIPTION
**Pull request by avirajsingh7**
## What
Migrating Source pipedrive to Low-Code CDK
Closes #29285

## How
Developed using (Configuration Based Source) low-code CDK

## Recommended reading order

1. manifest.yaml
2. schemas/*

## 🚨 User Impact 🚨

*Are there any breaking changes? What is the end result perceived by the user?*
added some new properties in schema as per response from API

 ##  Test
<details>
<summary>Acceptance Test</summary>
Screenshot 2023-08-10 at 3 05 00 AM

</details>

<details>
<summary>Migrate Connector : Source Hubplanner</summary>

- [x] **Community Member? Grant Edit Access to Maintainers [instructions](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests)**
- [x] **Secrets in the Connector's Spec**
- [x] **Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run ./gradlew :airbyte-integrations:connectors:<name>:integrationTest.**
- [x] **Code Reviews Completed**
  - [x] **Documentation Updated**
  - [x] **Connector's README.md**
  - [x] **Connector's bootstrap.md**
  - [x] **docs/integrations/<source or destination>/<name>.md (including changelog. See changelog example)**
  - [x] **docs/integrations/README.md**
  - [x] **airbyte-integrations/builds.md**
- [x] **PR Name follows PR Naming Conventions**
</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hello 👋 , right now Airbyte's integration tests are failing for this connector and I'm going to work during the week to fix them. Due a high number of contributions we have a backlog and your contribution will be review next week. We ask to you share the integration test from your side whatever possible and if you don't have credentials to run tests to get in touch with @RealChrisSean as soon as possible. Also some common missing steps contributors does migrating to low code are (and you can double check to make sure you implemented this): 
* adding paginator
* update the documentation changelog + metadata file and dockerfile version
* if the connector has `start_date` parameter you must implement incremental syncs

**Comment by marcosmarxm** [comment]
@avirajsingh7 can you give me access to your branch to push some changes?

**Comment by avirajsingh7** [comment]
@marcosmarxm send you a collabrator request

**Review by marcosmarxm — APPROVED** [review]
Thanks @avirajsingh7

**Comment by octavia-approvington** [comment]
A crack team of mammals has made a decision.  <br/> imagine a seal of approval

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
