### PR TITLE
use latest CDK in certified connectors

### PR DESCRIPTION
**Pull request by stephane-airbyte**

### CODE REVIEW

**Comment by stephane-airbyte** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33447?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #33357** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33357?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #33358** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33358?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #33270** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33270?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #33439** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33439?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #33440** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33440?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #33441** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33441?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #33442** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33442?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #33443** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33443?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                  * **PR #33444** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33444?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                    * **PR #33445** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33445?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                      * **PR #33446** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33446?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                        * **PR #33447** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33447?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/airbytehq/airbyte/33447?utm_source=stack-comment).

**Comment by stephane-airbyte** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33447?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #33357** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33357?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #33358** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33358?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #33270** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33270?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #33439** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33439?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #33440** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33440?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #33441** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33441?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #33442** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33442?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #33443** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33443?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                  * **PR #33444** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33444?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                    * **PR #33445** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33445?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                      * **PR #33446** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33446?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                        * **PR #33447** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33447?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/airbytehq/airbyte/33447?utm_source=stack-comment).

**Comment by stephane-airbyte** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33447?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #33357** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33357?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #33358** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33358?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #33270** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33270?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #33439** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33439?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #33440** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33440?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #33441** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33441?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #33442** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33442?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #33443** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33443?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                  * **PR #33444** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33444?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                    * **PR #33445** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33445?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                      * **PR #33446** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33446?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                        * **PR #33447** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33447?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/airbytehq/airbyte/33447?utm_source=stack-comment).

**Review by postamar — APPROVED** [review]

**Review by postamar — APPROVED** [review]

**Comment by lazebnyi** [comment]
Hey @stephane-airbyte 
Are you still in need of this pull request?

**Comment by stephane-airbyte** [comment]
@lazebnyi yeah, I won't merge it anytime soon because merging those PRs with CDK changes is super painful, and we're planning on making it a lot easier.

**Review by lazebnyi — APPROVED** [review]

**Comment by evantahler** [comment]
This should probably be closed

**Pull request closed without merging**
