### PR TITLE
Source Tiktok Marketing: add new fields to ad reports streams

### PR DESCRIPTION
**Pull request by marcosmarxm**
## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Checklist
*Expand the relevant checklist and delete the others.*

### CODE REVIEW

**Comment by marcosmarxm** [comment]
/publish connector=connectors/source-tiktok-marketing run-tests=false pre-release=true

**Comment by marcosmarxm** [comment]
/publish connector=connectors/source-tiktok-marketing run-tests=false pre-release=true

**Comment by octavia-squidington-iii** [comment]
##  source-tiktok-marketing test report (commit [`73782cbd25`](https://github.com/airbytehq/airbyte/pull/25423/commits/73782cbd25c197a893aeae422e065ee57d98bd78)) - ❌

⏲️  Total pipeline duration: 103 seconds

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-tiktok-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                 | ✅        |
| Connector version increment check                                              | ❌        |
| QA checks                                                                      | ✅        |
| Code format checks                                                             | ❌        |
| Connector package install                                                      | ✅        |
| Build source-tiktok-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                     | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/marcos_tiktok-add-purchase-fields/1687804717/73782cbd25c197a893aeae422e065ee57d98bd78/source-tiktok-marketing/3.2.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-tiktok-marketing test report (commit [`1737a4a978`](https://github.com/airbytehq/airbyte/pull/25423/commits/1737a4a97830ab556b5b1afc6a44f2c6fd16f863)) - ❌

⏲️  Total pipeline duration: 857 seconds

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-tiktok-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                 | ✅        |
| Connector version increment check                                              | ✅        |
| QA checks                                                                      | ✅        |
| Code format checks                                                             | ❌        |
| Connector package install                                                      | ✅        |
| Build source-tiktok-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                     | ✅        |
| Acceptance tests                                                               | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/marcos_tiktok-add-purchase-fields/1687818042/1737a4a97830ab556b5b1afc6a44f2c6fd16f863/source-tiktok-marketing/3.2.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-tiktok-marketing test report (commit [`92e4dadb9a`](https://github.com/airbytehq/airbyte/pull/25423/commits/92e4dadb9aa54c7dd0098eb1de891eb8cf851582)) - ❌

⏲️  Total pipeline duration: 15mn12s 

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-tiktok-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                 | ✅        |
| QA checks                                                                      | ✅        |
| Code format checks                                                             | ✅        |
| Connector package install                                                      | ✅        |
| Build source-tiktok-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                     | ✅        |
| Acceptance tests                                                               | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/marcos_tiktok-add-purchase-fields/1688581241/92e4dadb9aa54c7dd0098eb1de891eb8cf851582/source-tiktok-marketing/3.2.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-tiktok-marketing test report (commit [`ffe252bab2`](https://github.com/airbytehq/airbyte/pull/25423/commits/ffe252bab2c546915fa775a847a826e2d2fe79db)) - ❌

⏲️  Total pipeline duration: 14mn06s 

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-tiktok-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                 | ✅        |
| QA checks                                                                      | ✅        |
| Code format checks                                                             | ✅        |
| Connector package install                                                      | ✅        |
| Build source-tiktok-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                     | ✅        |
| Acceptance tests                                                               | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/marcos_tiktok-add-purchase-fields/1688583270/ffe252bab2c546915fa775a847a826e2d2fe79db/source-tiktok-marketing/3.2.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-tiktok-marketing test report (commit [`394c508590`](https://github.com/airbytehq/airbyte/pull/25423/commits/394c5085909c5de4a9b98df5cae211cec5e6d818)) - ❌

⏲️  Total pipeline duration: 01mn04s 

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-tiktok-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                 | ✅        |
| QA checks                                                                      | ✅        |
| Code format checks                                                             | ❌        |
| Connector package install                                                      | ✅        |
| Build source-tiktok-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                     | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/marcos_tiktok-add-purchase-fields/1688685895/394c5085909c5de4a9b98df5cae211cec5e6d818/source-tiktok-marketing/3.3.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-tiktok-marketing test report (commit [`912e1cd765`](https://github.com/airbytehq/airbyte/pull/25423/commits/912e1cd7650d0cd193e059f05d5e7a2f31385d42)) - ❌

⏲️  Total pipeline duration: 30mn07s 

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-tiktok-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                 | ✅        |
| QA checks                                                                      | ✅        |
| Code format checks                                                             | ✅        |
| Connector package install                                                      | ✅        |
| Build source-tiktok-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                     | ✅        |
| Acceptance tests                                                               | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/marcos_tiktok-add-purchase-fields/1688743897/912e1cd7650d0cd193e059f05d5e7a2f31385d42/source-tiktok-marketing/3.3.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-tiktok-marketing test report (commit [`83a65d62bf`](https://github.com/airbytehq/airbyte/pull/25423/commits/83a65d62bfa733a6b204379834b849a2b911aae1)) - ❌

⏲️  Total pipeline duration: 28mn30s 

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-tiktok-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                 | ✅        |
| QA checks                                                                      | ✅        |
| Code format checks                                                             | ✅        |
| Connector package install                                                      | ✅        |
| Build source-tiktok-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                     | ✅        |
| Acceptance tests                                                               | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/marcos_tiktok-add-purchase-fields/1689005100/83a65d62bfa733a6b204379834b849a2b911aae1/source-tiktok-marketing/3.3.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-tiktok-marketing test report (commit [`28031ae610`](https://github.com/airbytehq/airbyte/pull/25423/commits/28031ae610a3361cf9604a93b892bbac0e4380fa)) - ❌

⏲️  Total pipeline duration: 28mn37s 

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-tiktok-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                 | ✅        |
| QA checks                                                                      | ✅        |
| Code format checks                                                             | ✅        |
| Connector package install                                                      | ✅        |
| Build source-tiktok-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                     | ✅        |
| Acceptance tests                                                               | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/marcos_tiktok-add-purchase-fields/1689349615/28031ae610a3361cf9604a93b892bbac0e4380fa/source-tiktok-marketing/3.3.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-tiktok-marketing test report (commit [`2b64754a05`](https://github.com/airbytehq/airbyte/pull/25423/commits/2b64754a05b62456ee906183e39a97b41f545b40)) - ✅

⏲️  Total pipeline duration: 31mn36s 

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-tiktok-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                 | ✅        |
| QA checks                                                                      | ✅        |
| Code format checks                                                             | ✅        |
| Connector package install                                                      | ✅        |
| Build source-tiktok-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                     | ✅        |
| Acceptance tests                                                               | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/marcos_tiktok-add-purchase-fields/1690216313/2b64754a05b62456ee906183e39a97b41f545b40/source-tiktok-marketing/3.3.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Review by sajarin — APPROVED** [review]

**Pull request merged**
