### PR TITLE
Add primary_key noop to docs and PokeAPI connector.

### PR DESCRIPTION
**Pull request by avaidyanatha**
## Main Changes
- We launched a change that isn't currently released yet that makes Python builds of connectors fail without stream classes having a `primary_key`
- This simply adds a `primary_key` noop to the Python HTTP CDK tutorial

## Misc Changes
- Also adds the noop for the PokeAPI connector
- Fixes a random grammar error in the Airbyte vs. Meltano FAQ

### CODE REVIEW

**Review by sherifnada — APPROVED** [review]
To publish this you'll also want to bump the versions in Dockerfile and YAML and JSON files then run the `/publish` command

**Review by michel-tricot — CHANGES_REQUESTED** [review]
@sherifnada  
Shouldn't we make noop a default so you don't have to think about it? also an empty string looks really hacky, why is it not `None` ?

**Comment by sherifnada** [comment]
@michel-tricot 
1. agree that empty string looks hacky. We should use `None`. @avaidyanatha we should make that change in the docs most importantly but the Poke API also. 
2. forcing `primary_key` to be abstract is powerful because it nudges people towards specifying primary keys which enables nice features for normalization downstream. Plus, most data has a primary key, so this will have a snowball effect.

**Comment by michel-tricot** [comment]
Agree with 2! good thinking

**Comment by avaidyanatha** [comment]
@sherifnada @michel-tricot 

Done, just switched it to `None`.

**Review by davinchia — APPROVED** [review]

**Comment by sherifnada** [comment]
🚢

**Review by michel-tricot — APPROVED** [review]

**Pull request merged**
