### PR TITLE
fix(airbyte-cdk): bump nltk and requests

### LINKED ISSUE #45121: [airbyte-cd]  upgrade nltk package `>3.8.1`
### Topic

package dependencies

### Relevant information

 i am using `llama-index-core`. the package conflicted with nltk's version. 
[nltk update ](https://github.com/nltk/nltk/issues/3305) 
currently airbyte-cdk locked at 3.8.1  please upgrade to enable more features and compatibility with other repos

### PR DESCRIPTION
**Pull request by natikgadzhi**
## What

Bumps up the `nltk` and `requests` packages in airbyte-cdk, fixes a few security vulnerabilities.

Fixes #45121.
Fixes https://github.com/airbytehq/airbyte-internal-issues/issues/10490

### CODE REVIEW

**Review by aldogonzalez8 — APPROVED** [review]
Approved

**Review by aaronsteers — APPROVED** [review]
I've been watching the `nltk` alert for a while. If this can pass tests I'm 100% in favor! I vaguely recall a langchain or vector-store-related dependency linked to this - lmk if so and I'll be happy to jump in to help if needed.

**Comment by maxi297** [comment]
There are dependency issues in the CI. Is it related to those changes?

**Review by wennergr — APPROVED** [review]
LGTM! 

Thanks for getting this going1

**Comment by aaronsteers** [comment]
Working on nltk here:

- https://github.com/airbytehq/airbyte-python-cdk/pull/43

I think we can probably close this PR and move effort to the new one in the new repo.

Over there, I'm still dealing with test failures (fwiw).

**Comment by natikgadzhi** [comment]
@aldogonzalez8  and @aaronsteers did this in the new repo, closing this one.

**Pull request closed without merging**
