### PR TITLE
:bug: Source Bing Ads: retry DNS failure

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/oncall/issues/2209

## How
Retry DNS failure

## 🚨 User Impact 🚨
No impact

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-bing-ads test report (commit [`3cf08812c6`](https://github.com/airbytehq/airbyte/pull/27619/commits/3cf08812c63fd67d90a6c69f993db512d7d9f36b)) - ❌

⏲️  Total pipeline duration: 35 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-bing-ads/metadata.yaml | ✅        |
| Connector version semver check.                                        | ✅        |
| Connector version increment check.                                     | ✅        |
| QA checks                                                              | ✅        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-bing-ads docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/ddavydov_#2209-source-bing-ads-retry-dns-failure/1687458809/3cf08812c63fd67d90a6c69f993db512d7d9f36b/source-bing-ads/0.1.24/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-bing-ads test
```

**Comment by alafanechere** [comment]
@davydov-d FYI the link to logs is not working because of a special character in your branch name ...
The build step is failing because it's calling the `spec` command.
The `spec` command is broken on this connector:
`TypeError: unsupported operand type(s) for |: 'type' and 'type'`

**Comment by davydov-d** [comment]
> @davydov-d FYI the link to logs is not working because of a special character in your branch name ... The build step is failing because it's calling the `spec` command. The `spec` command is broken on this connector: `TypeError: unsupported operand type(s) for |: 'type' and 'type'`

thanks @alafanechere! is there a way to handle those special characters in branch names?

**Comment by octavia-squidington-iii** [comment]
##  source-bing-ads test report (commit [`948544ab41`](https://github.com/airbytehq/airbyte/pull/27619/commits/948544ab41cf297bf7e95469bb0d2169a62c0dcc)) - ✅

⏲️  Total pipeline duration: 662 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-bing-ads/metadata.yaml | ✅        |
| Connector version semver check.                                        | ✅        |
| Connector version increment check.                                     | ✅        |
| QA checks                                                              | ✅        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-bing-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/ddavydov_#2209-source-bing-ads-retry-dns-failure/1687459803/948544ab41cf297bf7e95469bb0d2169a62c0dcc/source-bing-ads/0.1.24/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-bing-ads test
```

**Review by bnchrch — APPROVED** [review]

**Pull request merged**
