### PR TITLE
source-mysql*: force-pin jooq version

### PR DESCRIPTION
**Pull request by postamar**
This PR gets the source-mysql* connectors tests to succeed. They had been broken since the java CDK PR had merged.

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-mysql test report (commit [`087f687b6e`](https://github.com/airbytehq/airbyte/pull/30939/commits/087f687b6e82158cb370e556e148c47a94621717)) - ✅

⏲️  Total pipeline duration: 13mn14s 

| Step                                                      | Result   |
|:----------------------------------------------------------|:---------|
| Build connector tar                                       | ✅        |
| Build source-mysql docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                 | ✅        |
| Java Connector Integration Tests                          | ✅        |
| Acceptance tests                                          | ✅        |
| Validate metadata for source-mysql                        | ✅        |
| Connector version semver check                            | ✅        |
| QA checks                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/postamar_fix-source-mysql-dependencies/1696014896/087f687b6e82158cb370e556e148c47a94621717/source-mysql/3.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:087f687b6e82158cb370e556e148c47a94621717)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Review by rodireich — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-mysql-strict-encrypt test report (commit [`0e4a4286e8`](https://github.com/airbytehq/airbyte/pull/30939/commits/0e4a4286e84beab241085f688f4b60d799da3bc3)) - ❌

⏲️  Total pipeline duration: 11mn53s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build connector tar                                                      | ✅        |
| Build source-mysql-strict-encrypt docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                | ❌        |
| Java Connector Integration Tests                                         | ✅        |
| Acceptance tests                                                         | ✅        |
| Validate metadata for source-mysql-strict-encrypt                        | ✅        |
| Connector version semver check                                           | ✅        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/postamar_fix-source-mysql-dependencies/1696020377/0e4a4286e84beab241085f688f4b60d799da3bc3/source-mysql-strict-encrypt/3.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:0e4a4286e84beab241085f688f4b60d799da3bc3)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql-strict-encrypt test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-mysql test report (commit [`0e4a4286e8`](https://github.com/airbytehq/airbyte/pull/30939/commits/0e4a4286e84beab241085f688f4b60d799da3bc3)) - ✅

⏲️  Total pipeline duration: 04mn00s 

| Step                                                      | Result   |
|:----------------------------------------------------------|:---------|
| Build connector tar                                       | ✅        |
| Build source-mysql docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                 | ✅        |
| Java Connector Integration Tests                          | ✅        |
| Acceptance tests                                          | ✅        |
| Validate metadata for source-mysql                        | ✅        |
| Connector version semver check                            | ✅        |
| QA checks                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/postamar_fix-source-mysql-dependencies/1696020377/0e4a4286e84beab241085f688f4b60d799da3bc3/source-mysql/3.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:0e4a4286e84beab241085f688f4b60d799da3bc3)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-mysql test report (commit [`d225277cf2`](https://github.com/airbytehq/airbyte/pull/30939/commits/d225277cf2c02435255cc67f232bf1cb32e5004f)) - ✅

⏲️  Total pipeline duration: 05mn47s 

| Step                                                      | Result   |
|:----------------------------------------------------------|:---------|
| Build connector tar                                       | ✅        |
| Build source-mysql docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                 | ✅        |
| Java Connector Integration Tests                          | ✅        |
| Acceptance tests                                          | ✅        |
| Validate metadata for source-mysql                        | ✅        |
| Connector version semver check                            | ✅        |
| QA checks                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/postamar_fix-source-mysql-dependencies/1696021543/d225277cf2c02435255cc67f232bf1cb32e5004f/source-mysql/3.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d225277cf2c02435255cc67f232bf1cb32e5004f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-mysql-strict-encrypt test report (commit [`d225277cf2`](https://github.com/airbytehq/airbyte/pull/30939/commits/d225277cf2c02435255cc67f232bf1cb32e5004f)) - ✅

⏲️  Total pipeline duration: 10mn20s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build connector tar                                                      | ✅        |
| Build source-mysql-strict-encrypt docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                | ✅        |
| Java Connector Integration Tests                                         | ✅        |
| Acceptance tests                                                         | ✅        |
| Validate metadata for source-mysql-strict-encrypt                        | ✅        |
| Connector version semver check                                           | ✅        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/postamar_fix-source-mysql-dependencies/1696021543/d225277cf2c02435255cc67f232bf1cb32e5004f/source-mysql-strict-encrypt/3.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d225277cf2c02435255cc67f232bf1cb32e5004f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql-strict-encrypt test
```

**Pull request merged**
