### PR TITLE
🐛 Modify INFO log printing sensitive information

### PR DESCRIPTION
**Pull request by anjshrg**
## What
*Describe what the change is solving*
*It modifies logger statement which prints sensitive information*

## How
*Describe the solution*
Modifies AbstractFormat.java to not print JAAS config along with entire protocol Config

## Recommended reading order
1. `AbstractFormat.java`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*
No breaking changes, sensitive info will not be printed on console/UI or synced to log

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hello @anjshrg thanks for the contribution. Please sign the CLA to continue the review process.

**Comment by anjshrg** [comment]
I have signed it. Not sure why it's not reflecting here.

**Comment by marcosmarxm** [comment]
@anjshrg make sure the user you push the commits are the same you're doing the contribution.

**Comment by marcosmarxm** [comment]
Closed because user didn't sign the CLA. @anjshrg make sure you commit with the same user you sign the CLA.

**Pull request closed without merging**
