### PR TITLE
✨Source Primetric: Migrate Python CDK to Low-code CDK

### LINKED ISSUE #36507: ✨Source Primetric: Migrate Python CDK to Low-code CDK
### Topic

Migrate Primetric Source to Low-code CDK

### Relevant information

https://docs.airbyte.com/integrations/sources/primetric

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
*Migrating Source Primetric to Low-Code CDK*
Closes airbytehq/airbyte-internal-issues#7029

## How
*Developed using (Configuration Based Source) low-code CDK*

## Recommended reading order
1. `spec.yaml`
2. `manifest.yaml`
3. `schemas/*`

## Tests

<details open><summary><strong>Integration & Acceptance</strong></summary>

 - Build Successfull
 
image

</details>

## 🚨 User Impact 🚨
- Spec Breaking changes, migration to low-code

### CODE REVIEW

**Comment by btkcodedev** [comment]
- Built using connector builder,
- Build successfull
 - Awating review :)

**Comment by marcosmarxm** [comment]
@CodiumAI-Agent /review

**Comment by btkcodedev** [comment]
Added latest poetry version, pytest version, poetry lock file, updated docs
Build is getting passed.
Comments awaited if any

**Comment by btkcodedev** [comment]
Continued in https://github.com/airbytehq/airbyte/pull/36957

**Pull request closed without merging**
