### PR TITLE
Align strict-encrypt connector version with the actual connector

### PR DESCRIPTION
**Pull request by grishick**
Change the version of destination-oracle-strict-encrypt to match the version of destination-oracle connector

### CODE REVIEW

**Review by edgao — APPROVED** [review]
ugh, I always forget these variants exist.

I can't find the specifics, but didn't liren/davin make this process better during hackdays?

**Review by ryankfu — APPROVED** [review]
LGTM, we talked about this but currently the build process doesn't allow for multiple updates to the several Dockerfiles at once, right? 

I remember this was my assignment from yesterday so that's my fault I dropped the ball. It's definitely a hassle to have to make multiple PRs when I can definitely see this as an auto generated from from the general database version or would that cause issues because it would be important to separate the versioning?

**Comment by grishick** [comment]
> ugh, I always forget these variants exist.
> 
> I can't find the specifics, but didn't liren/davin make this process better during hackdays?

I don't think their project is finished yet

**Comment by grishick** [comment]
> LGTM, we talked about this but currently the build process doesn't allow for multiple updates to the several Dockerfiles at once, right?
> 
> I remember this was my assignment from yesterday so that's my fault I dropped the ball. It's definitely a hassle to have to make multiple PRs when I can definitely see this as an auto generated from from the general database version or would that cause issues because it would be important to separate the versioning?

ultimately, we want to get rid of these "***-strict-encrypt" connectors in favor of a solution that @tuliren and @davinchia came up with during the last hackathon

**Comment by grishick** [comment]
/publish connector=destination-oracle-strict-encrypt run-tests=false

**Comment by grishick** [comment]
/publish connector=connectors/destination-oracle-strict-encrypt run-tests=false

**Pull request merged**
