### PR TITLE
migrate GA source connectors to per-stream state

### PR DESCRIPTION
**Pull request by alafanechere**
## What
Migrate the following GA connectors to per-stream state: 
source-amplitude
source-bing-ads
source-google-ads
source-google-analytics-v4
source-google-sheets
source-harvest
~~source-hubspot~~ (already done in https://github.com/airbytehq/airbyte/pull/17120)
~~source-instagram~~ (already done in https://github.com/airbytehq/airbyte/pull/17110)
source-intercom
source-linkedin-ads
source-mailchimp
source-surveymonkey
source-tiktok-marketing
source-zendesk-chat
source-zendesk-support

## How
* Update `*_state.json` files used for SAT tests
* Republishing the connectors will make them use the latest version of CDK which is using per-stream states.

### CODE REVIEW

**Review by pedroslopez — APPROVED** [review]
LGTM, note that the bing-ads test failed

**Comment by alafanechere** [comment]
/publish connector=connectors/source-amplitude,connectors/source-google-ads,connectors/source-google-analytics-v4,connectors/source-google-sheets,connectors/source-harvest,connectors/source-intercom,connectors/source-linkedin-ads,connectors/source-mailchimp,connectors/source-surveymonkey,connectors/source-tiktok-marketing,connectors/source-zendesk-chat,connectors/source-zendesk-support run-tests=false

**Comment by alafanechere** [comment]
TODO: publish bing-ads once our sandbox creds are refreshed on GSM.

**Comment by alafanechere** [comment]
Won't publish `source-bing-ads` and `source-google-ads` as SAT are not passing

**Pull request merged**
