### PR TITLE
deprecate import / export endpoints

### PR DESCRIPTION
**Pull request by cgardens**
## What
* These are no longer used for migrations and it is easy to use them in a way that will shoot the user in the foot by accident.

## Follow up
* This PR just kills the endpoints. A follow up will delete the handlers associated with it as they are no longer needed and it will remove a lot of tricky code.

### CODE REVIEW

**Review by sherifnada — APPROVED** [review]
is there a corresponding UI change?

**Review by davinchia — APPROVED** [review]
Yeah, I think we might need to remove these from the frontend. 

cc @timroes 
Screenshot 2022-08-31 at 10 38 01 AM

We can do so in a follow up PR too. As long as we do it before we publish the next release.

Looks like this is the only usage for now, so I think the entire ArchiveHandler can be removed too. We can also do that in a follow up PR. Not sure if we want to. Mainly calling out.

**Comment by davinchia** [comment]
Screenshot 2022-08-31 at 10 40 43 AM

Not sure why my screenshot didn't upload

**Comment by davinchia** [comment]
Looks like this is failing the Octavia CLI build - @alafanechere are the import/export routes needed for the CLI?

**Comment by alafanechere** [comment]
> Looks like this is failing the Octavia CLI build - @alafanechere are the import/export routes needed for the CLI?

Nope, but CLI builds depends on `airbyte-webapp` which is failing: 
```
Execution failed for task ':airbyte-webapp:npm_run_build'.
```

**Comment by evantahler** [comment]
I'm 👍 on removing _dangerous_ old endpoints, but we probably should do /all/ the removing in one PR... which is probably needed to get the build to pass.  We don't have a great track record of remembering to clean up aftewrods...  

I can help @cgardens and do the FE cleanup.

**Comment by evantahler** [comment]
https://github.com/airbytehq/airbyte/pull/16186 has the UI updates and the build is green :D

**Comment by cgardens** [comment]
Screen Shot 2022-08-31 at 4 38 24 PM

Updated FE code to remove dep on these API endpoints. @timroes

**Comment by evantahler** [comment]
There are a few other things you can remove from https://github.com/airbytehq/airbyte/pull/16186 that aren't in use after removing the config upload and download
* the `react-dropzone` dependency in `package.json`
* the dropZone locale strings in `airbyte-webapp/src/locales/en.json`
* the `components/FileDropZone` component

**Review by evantahler — APPROVED** [review]

**Review by edmundito — APPROVED** [review]

**Comment by cgardens** [comment]
@krishnaglick yeah. I think octavia CLI is your best bet. You should be able to get the same behavior.

**Comment by andresbravog** [comment]
Question here, we have been using this feature for both store daily backups of the Airbyte configuration and state being able to back to a past state for all connections if something critical happens. 

My understanding is that Octavia's client does not extract/store/modify connection state and cursors. Is that correct?

**Comment by cgardens** [comment]
yeah. that's correct.

**Pull request merged**
