### PR TITLE
✨ Source MongoDB V2: Record statistics about MongoDB source connection

### PR DESCRIPTION
**Pull request by jdpgrailsdev**
## What
* Gather data to determine the version, collection size and server configuration of each MongoDB source connection in use in Cloud.

## How
* Record statistics when performing various operations in the source connector

## Recommended reading order
1. `MongoDatabase.java`
2. `MongoDbSource.java`

The plan is to publish a build from this PR first to test it out via a connector override before merging.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  destination-tidb test report (commit [`f144f7cec8`](https://github.com/airbytehq/airbyte/pull/28527/commits/f144f7cec8bb35eaa1caf92f143c90c5fc5d5d83)) - ✅

⏲️  Total pipeline duration: 23mn59s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-tidb/metadata.yaml     | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |
| Build connector tar                                                         | ✅        |
| Build destination-tidb docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-tidb:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-tidb:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_mongodb-stats/1689871326/f144f7cec8bb35eaa1caf92f143c90c5fc5d5d83/destination-tidb/0.1.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-tidb test
```

**Review by colesnodgrass — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-db2 test report (commit [`9cb58bf23b`](https://github.com/airbytehq/airbyte/pull/28527/commits/9cb58bf23b1f778536d5b28158d630d2f218854e)) - ❌

⏲️  Total pipeline duration: 05mn40s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-db2/metadata.yaml     | ✅        |
| Connector version semver check                                        | ✅        |
| QA checks                                                             | ✅        |
| Build connector tar                                                   | ✅        |
| Build source-db2 docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-db2:integrationTest | ❌        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_mongodb-stats/1689957713/9cb58bf23b1f778536d5b28158d630d2f218854e/source-db2/0.1.20/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-db2 test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-kafka test report (commit [`9cb58bf23b`](https://github.com/airbytehq/airbyte/pull/28527/commits/9cb58bf23b1f778536d5b28158d630d2f218854e)) - ❌

⏲️  Total pipeline duration: 09mn04s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-kafka/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build destination-kafka docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-kafka:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_mongodb-stats/1689957713/9cb58bf23b1f778536d5b28158d630d2f218854e/destination-kafka/0.1.10/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-kafka test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-pulsar test report (commit [`9cb58bf23b`](https://github.com/airbytehq/airbyte/pull/28527/commits/9cb58bf23b1f778536d5b28158d630d2f218854e)) - ✅

⏲️  Total pipeline duration: 15mn31s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-pulsar/metadata.yaml     | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Build connector tar                                                           | ✅        |
| Build destination-pulsar docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-pulsar:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_mongodb-stats/1689957713/9cb58bf23b1f778536d5b28158d630d2f218854e/destination-pulsar/0.1.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-pulsar test
```

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`9cb58bf23b`](https://github.com/airbytehq/airbyte/pull/28527/commits/9cb58bf23b1f778536d5b28158d630d2f218854e)) - ✅

⏲️  Total pipeline duration: 10mn05s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ✅        |
| Build source-postgres docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres:integrationTest | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_mongodb-stats/1689957713/9cb58bf23b1f778536d5b28158d630d2f218854e/source-postgres/3.0.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mysql test report (commit [`9cb58bf23b`](https://github.com/airbytehq/airbyte/pull/28527/commits/9cb58bf23b1f778536d5b28158d630d2f218854e)) - ❌

⏲️  Total pipeline duration: 15mn52s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql/metadata.yaml     | ✅        |
| Connector version semver check                                          | ✅        |
| QA checks                                                               | ✅        |
| Build connector tar                                                     | ✅        |
| Build source-mysql docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mysql:integrationTest | ❌        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_mongodb-stats/1689957713/9cb58bf23b1f778536d5b28158d630d2f218854e/source-mysql/2.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-teradata test report (commit [`9cb58bf23b`](https://github.com/airbytehq/airbyte/pull/28527/commits/9cb58bf23b1f778536d5b28158d630d2f218854e)) - ✅

⏲️  Total pipeline duration: 13mn34s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-teradata/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-teradata docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-teradata:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_mongodb-stats/1689957713/9cb58bf23b1f778536d5b28158d630d2f218854e/destination-teradata/0.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-teradata test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-tidb test report (commit [`9cb58bf23b`](https://github.com/airbytehq/airbyte/pull/28527/commits/9cb58bf23b1f778536d5b28158d630d2f218854e)) - ✅

⏲️  Total pipeline duration: 14mn40s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-tidb/metadata.yaml     | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |
| Build connector tar                                                         | ✅        |
| Build destination-tidb docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-tidb:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-tidb:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_mongodb-stats/1689957713/9cb58bf23b1f778536d5b28158d630d2f218854e/destination-tidb/0.1.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-tidb test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mysql-strict-encrypt test report (commit [`76d1c68ee2`](https://github.com/airbytehq/airbyte/pull/28527/commits/76d1c68ee260ac0c0cb391c0103d489d45c7fe5d)) - ❌

⏲️  Total pipeline duration: 5.88s 

| Step                                                                                    | Result   |
|:----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mysql-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                          | ✅        |
| QA checks                                                                               | ✅        |
| Build connector tar                                                                     | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_mongodb-stats/1690202478/76d1c68ee260ac0c0cb391c0103d489d45c7fe5d/destination-mysql-strict-encrypt/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mysql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mssql-strict-encrypt test report (commit [`76d1c68ee2`](https://github.com/airbytehq/airbyte/pull/28527/commits/76d1c68ee260ac0c0cb391c0103d489d45c7fe5d)) - ❌

⏲️  Total pipeline duration: 25mn30s 

| Step                                                                                        | Result   |
|:--------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mssql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                              | ✅        |
| QA checks                                                                                   | ✅        |
| Build connector tar                                                                         | ✅        |
| Build destination-mssql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mssql:dev                                                       | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mssql-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_mongodb-stats/1690202478/76d1c68ee260ac0c0cb391c0103d489d45c7fe5d/destination-mssql-strict-encrypt/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mssql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-v2 test report (commit [`76d1c68ee2`](https://github.com/airbytehq/airbyte/pull/28527/commits/76d1c68ee260ac0c0cb391c0103d489d45c7fe5d)) - ❌

⏲️  Total pipeline duration: 11mn27s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-v2:integrationTest | ❌        |
| Acceptance tests                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_mongodb-stats/1690202478/76d1c68ee260ac0c0cb391c0103d489d45c7fe5d/source-mongodb-v2/0.2.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

**Comment by octavia-approvington** [comment]
Check that box <br/> TODO complete

**Review by octavia-approvington — APPROVED** [review]

**Comment by klsoper** [comment]
hey @jdpgrailsdev! could this have caused or be related to [this](https://github.com/airbytehq/alpha-beta-issues/issues/1653) ?

**Comment by jdpgrailsdev** [comment]
@klsoper Yes and it has been fixed in #28692.  That change has already been released and should be in use on Cloud now if the customer wants to try again to verify the fix.

**Comment by klsoper** [comment]
Thank you @jdpgrailsdev !

**Comment by klsoper** [comment]
@jdpgrailsdev the issue is persisting with the user. Is there anything required of the user before they should see success?

**Comment by jdpgrailsdev** [comment]
@klsoper No...the sync should just pickup the latest connector.  Could you please provide a link to the connection so I can see what is going on?  Thanks.

**Comment by klsoper** [comment]
@jdpgrailsdev Linked [here](https://cloud.airbyte.com/workspaces/56aac60a-dd3b-4712-ba92-650a4d63b8f0/connections/1fb5cad8-6758-406c-be09-f2575ec0d82d/job-history)

**Comment by jdpgrailsdev** [comment]
Version 0.2.2 of the connector with the fix the issue identified above is now live on Cloud.  This should address this specific issue going forward.

**Pull request merged**
