### PR TITLE
✨Source Asana: Add new stream Portfolio Memberships

### LINKED ISSUE #16805: Source Asana: new stream Portfolio Memberships
## Tell us about the problem you're trying to solve
Returns a list of portfolio memberships in compact representation. You must specify portfolio, portfolio and user, or workspace and user.

## Describe the solution you’d like
Research pros and cons for implemting this stream.
Depending on your role within Asana you may have no access to this stream
image

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
Closes #16805

## Enhancement
New streams: 

- Portfolio Memberships

## Recommended reading order
1. `source_asana/configured_catalog.json`
2. `source_asana/source.py`
3.  `source_asana/schemas/*`

## 🚨 User Impact 🚨
No breaking changes

## Pre-merge Checklist
<details open><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter [Yes]

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Issue acceptance criteria met
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [x] Documentation which references the generator is updated as needed

### CODE REVIEW

**Review by archangelic — COMMENTED** [review]
Currently, this does not sync any data. [This endpoint](https://developers.asana.com/reference/getportfoliomemberships) requires that a `workspace` or `portfolio` is passed in the query parameters in order to work. This functionality will need to be added.

**Comment by sajarin** [comment]
@btkcodedev are you able to address the issue mentioned above here?

**Comment by btkcodedev** [comment]
@sajarin @archangelic Sorry for the delay, 
I've added the parent stream for slices
Portfolio requires Workspace param :white_check_mark: 
Portfolio memberships require portfolio param :white_check_mark: 

Added both slices as parameters

**Comment by sajarin** [comment]
@btkcodedev 

1. Can you rebase on master? 
2. Check this [linked comment](https://github.com/airbytehq/airbyte/pull/31114#issuecomment-1775926854) for the same error with the Portfolios stream (Owner value is required and missing, despite what the docs say)

**Comment by sajarin** [comment]
@btkcodedev any update here?

**Comment by btkcodedev** [comment]
@sajarin I've added owner slice from [project details](https://developers.asana.com/reference/getproject) stream
Hope it works.

**Comment by btkcodedev** [comment]
Also rebased to master, Its ready

**Review by sajarin — APPROVED** [review]

**Pull request merged**
