### PR TITLE
source-deputy contribution from aazam-gh

### LINKED ISSUE #47416: [connector-request] Deputy
This is a suggestion to create a connector for Deputy using the UI Connector Builder.
The website for the connector is https://www.deputy.com/

### PR DESCRIPTION
**Pull request by aazam-gh**
## What

This PR adds a new connector for source Deputy (source-deputy).

Contributor-provided connector description:

This is the Deputy source that ingests data from the Deputy API.

Deputy is a software that simplifies employee scheduling, timesheets and HR in one place https://www.deputy.com/

In order to use this source you must first create an account on Deputy.
Once logged in, your Deputy install will have a specific URL in the structure of https://{installname}.{geo}.deputy.com - This is the same URL that will be the base API url .

To obtain your bearer token to use the API, follow the steps shown here https://developer.deputy.com/deputy-docs/docs/the-hello-world-of-deputy
This will have you create an oauth application and create an access token. Enter the access token in the input field.

You can learn more about the API here https://developer.deputy.com/deputy-docs/reference/getlocations
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key.  |  |
| `base_url` | `string` | Base URL. The base url for your deputy account to make API requests |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| locations | Id | No pagination | ✅ |  ❌  |
| employees | Id | No pagination | ✅ |  ❌  |
| award_lists | AwardCode | No pagination | ✅ |  ❌  |
| departments | Id | No pagination | ✅ |  ❌  |
| timesheets | Id | No pagination | ✅ |  ❌  |
| tasks | Id | No pagination | ✅ |  ❌  |
| news_feed | Id | No pagination | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by aazam-gh** [comment]
Fixes #47416

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
To make the connector usable it requires to implement Resource API endpoints. 
One example is addresses: https://developer.deputy.com/deputy-docs/reference/getaddresses

Let me know if you want to implement the new endpoints and continue this work.

**Comment by aazam-gh** [comment]
Sure, will add those endpoints

**Comment by marcosmarxm** [comment]
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

Make sure you have pagination properly working, the API doesn't have pagination please left a comment making my review easier.
Make sure have a square svg icon
Make sure credentials are valid.

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
