### PR TITLE
Source Faker: Bump CDK and mimesis dependencies

### PR DESCRIPTION
**Pull request by aaronsteers**
## What

Bumps CDK to 2.0 ~~and `memesis` to v11 (from v6)~~.

~~Also bumps min Python version from 3.9 to 3.10 (required by latest `memesis` version).~~

## User Impact

Should be none. Possible perf boost from bumping `memesis` to latest.

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

> ⚠️ Auto-Merge Enabled

### CODE REVIEW

**Comment by aaronsteers** [comment]
@natikgadzhi, @erohmensing - Do we have a valid 3.10-based Python image?

**Review by evantahler — APPROVED** [review]
How much faster is it going to be!?

**Comment by evantahler** [comment]
We've got a faker sync on our [performance dashboard](https://airbyte.metabaseapp.com/dashboard/234-cloud-speed-dashboard).  When this gets merged, we can see how much faster it got!

**Comment by aaronsteers** [comment]
@evantahler - FYI, circling back here after some time. Turns out, upgrading mimesis breaks some of the tests - apparently because expected records are coming out differently in the new version. Rather than debug or modify the tests, I'm reverting mimesis back to the previous version; we can handle that in a subsequent update if we want.

I'm not sure what the perf boost is, but thanks for sharing that dashboard. We can monitor after this upgrade to see the effect. 👍

My priority is to unblock PyAirbyte to move to Pydantic 2.0 and CDK 2.0, and since this connector is a dev dependency, I have to bump this before I can upgrade PyAirbyte. 😄 

Will keep you posted and let you know once this merges.

**Comment by aaronsteers** [comment]
@evantahler - This is merged. 🚀

**Pull request merged**
