### PR TITLE
bump testcontainers version to latest

### LINKED ISSUE #30392: bump testcontainers version to latest
### Topic

bump testcontainers version to latest 

### Revelant information

Bumping testcontainers to the latest version breaks all db-sources integration tests except for source-postgres. This seems to happen only in airbyte-ci. This seems due to a combination of a networking issue, and dagger shutting down the docker-in-docker container too early. Fix this at least for source-mysql.

Related:
https://github.com/airbytehq/airbyte/pull/30280
https://github.com/airbytehq/airbyte/pull/30032
https://airbytehq-team.slack.com/archives/C043JHEEYKG/p1694015739924069
https://github.com/airbytehq/airbyte/pull/30384

### PR DESCRIPTION
**Pull request by postamar**
This PR bumps all testcontainers package versions to the latest across the board, following up on work started by @alafanechere. We need to do this to have access to images for the architectures that we use (arm machines on aws, apple silicon locally...). The need for this was especially pressing for source-mysql apparently, airbyte-ci just doesn't work for that connector right now. 

Notice that I tie all testcontainers dependencies to one version number. This is deliberate, any testcontainers package will transitively depend on the testcontainers base package of the same version. To use a specific, different version in a connector for whatever reason, let's import it using a hardcoded string instead of a reference to deps.toml. @aaronsteers perhaps the CDK will formalize things in this respect? It seems sensible that testcontainers version pinning could happen in there.

I made a reasonable effort to test that this doesn't break anything _that I think that we care about_. This change actually breaks many connector's tests, but I haven't worried about those which were already routinely broken according to https://connectors.airbyte.com/files/generated_reports/connector_registry_report.html. The fixes, in any case, are fairly straightforward.

This PR will trigger a bunch of CI runs, which is actually desirable for a change. I'll go over the reports after the week-end, once they've had a chance to run. I did some manual tests before publishing this that verified that this fixes the source-mysql + strict-encrypt builds so this is ready for review. If any other connectors need fixing the changes are along the same lines so that shouldn't block the review. 

Informs https://github.com/airbytehq/airbyte/issues/29463

### CODE REVIEW

**Review by rodireich — APPROVED** [review]

**Review by aaronsteers — APPROVED** [review]
Makes sense! If you do note any new failures, and if you can document those for reference, that is much appreciated. That said, I now it is tricky to identify 'new' failures in cases where tests are failing already, so I wouldn't block on it either way.

**Comment by postamar** [comment]
FYI @airbytehq/connector-operations the CI hit some github rate limiter:
```
github.GithubException.RateLimitExceededException: 403 ***"message": "API rate limit exceeded for installation ID 6913263. If you reach out to GitHub Support for help, please include the request ID B91A:17CF:2795E19:28DB178:6505A23C.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"***
```
I can't imagine any scenario where this is desirable. It's bad enough that the whole thing takes several days, frankly. 

I'm going to merge this PR now and deal with the consequences later.

**Comment by octavia-approvington** [comment]
Jerry would be proud <br/> Spongebob

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
