### PR TITLE
:sparkles: Source Jira: connector health: fix unit tests

### PR DESCRIPTION
**Pull request by darynaishchenko**
## What
`TypeError: expected str, bytes or os.PathLike object, not NoneType�[0m`

## How
added request cache path env var for unittests

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`e86f81a42f`](https://github.com/airbytehq/airbyte/pull/31043/commits/e86f81a42f8dd63c23fd9cbe7d7008211a77e3c4)) - ❌

⏲️  Total pipeline duration: 09mn24s 

| Step                                                     | Result   |
|:---------------------------------------------------------|:---------|
| Connector package install                                | ✅        |
| Build source-jira docker image for platform linux/x86_64 | ✅        |
| Unit tests                                               | ✅        |
| Integration tests                                        | ✅        |
| Acceptance tests                                         | ❌        |
| Code format checks                                       | ❌        |
| Validate metadata for source-jira                        | ✅        |
| Connector version semver check                           | ✅        |
| QA checks                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-jira_fix-unittests/1696411861/e86f81a42f8dd63c23fd9cbe7d7008211a77e3c4/source-jira/0.9.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e86f81a42f8dd63c23fd9cbe7d7008211a77e3c4)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`794e862f8c`](https://github.com/airbytehq/airbyte/pull/31043/commits/794e862f8cb19db15a178958ad72f8e21124aec8)) - ❌

⏲️  Total pipeline duration: 05mn45s 

| Step                                                     | Result   |
|:---------------------------------------------------------|:---------|
| Connector package install                                | ✅        |
| Build source-jira docker image for platform linux/x86_64 | ✅        |
| Unit tests                                               | ✅        |
| Integration tests                                        | ✅        |
| Acceptance tests                                         | ❌        |
| Code format checks                                       | ✅        |
| Validate metadata for source-jira                        | ✅        |
| Connector version semver check                           | ✅        |
| QA checks                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-jira_fix-unittests/1696412758/794e862f8cb19db15a178958ad72f8e21124aec8/source-jira/0.9.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:794e862f8cb19db15a178958ad72f8e21124aec8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`c9701c78fe`](https://github.com/airbytehq/airbyte/pull/31043/commits/c9701c78fe4a35857c1d97c64c670548cc66f55e)) - ✅

⏲️  Total pipeline duration: 09mn05s 

| Step                                                     | Result   |
|:---------------------------------------------------------|:---------|
| Connector package install                                | ✅        |
| Build source-jira docker image for platform linux/x86_64 | ✅        |
| Unit tests                                               | ✅        |
| Integration tests                                        | ✅        |
| Acceptance tests                                         | ✅        |
| Code format checks                                       | ✅        |
| Validate metadata for source-jira                        | ✅        |
| Connector version semver check                           | ✅        |
| QA checks                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-jira_fix-unittests/1696414302/c9701c78fe4a35857c1d97c64c670548cc66f55e/source-jira/0.9.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:c9701c78fe4a35857c1d97c64c670548cc66f55e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Review by artem1205 — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`ade0648d5d`](https://github.com/airbytehq/airbyte/pull/31043/commits/ade0648d5d10da7e4dda815fd0f9173c15ea407f)) - ✅

⏲️  Total pipeline duration: 10mn54s 

| Step                                                        | Result   |
|:------------------------------------------------------------|:---------|
| Connector package install                                   | ✅        |
| Build source-jira docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                  | ✅        |
| Integration tests                                           | ✅        |
| Acceptance tests                                            | ✅        |
| Code format checks                                          | ✅        |
| Validate metadata for source-jira                           | ✅        |
| Connector version semver check                              | ✅        |
| QA checks                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-jira_fix-unittests/1696495876/ade0648d5d10da7e4dda815fd0f9173c15ea407f/source-jira/0.9.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ade0648d5d10da7e4dda815fd0f9173c15ea407f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Pull request merged**
