### PR TITLE
[chore] isort & black formatting

### PR DESCRIPTION
**Pull request by natikgadzhi**
## What

This PR applies isort and black to the whole repo. 

```bash
poetry run isort --settings-file pyproject.toml .
poetry run black --config pyproject.toml .
```

## Why

I was working on #37456 and noticed I messed up imports, ran black, and noticed there are a bunch of changes. Extracting them into a separate PR so it's easier to get in.

## User impact

None. 

## Can this PR be safely reverted and rolled back?
- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by natikgadzhi** [comment]
Failing tests are from connector version checks, okay to skip!

**Comment by natikgadzhi** [comment]
CDK tests are failing because of module names, looks sus.

**Comment by natikgadzhi** [comment]
I'm not attached to this — I would much rather switch to Ruff instead and reformat everything

**Comment by alafanechere** [comment]
Yes, let's merge your `ruff` related work instead!

**Pull request closed without merging**
