### PR TITLE
Bulk load CDK: move oneshot boolean to factory instance field

### PR DESCRIPTION
**Pull request by edgao**
having it in the `companion object` caused problems when I tried running multiple tests (because only the first test would complete correctly). Construct this once per factory instantiation and pass it to the task appropriately.

### CODE REVIEW

**Comment by edgao** [comment]
* **#46749** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46749?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#46922** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46922?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#46921** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46921?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#46920** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46920?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#46902** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46902?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#46925** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46925?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @edgao and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by edgao** [comment]
* **#46749** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46749?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#46922** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46922?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#46921** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46921?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#46920** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46920?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#46902** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46902?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#46925** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46925?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @edgao and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by edgao** [comment]
* **#46749** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46749?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#46922** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46922?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#46921** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46921?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#46920** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46920?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#46902** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46902?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#46925** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46925?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @edgao and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by johnny-schmidt** [comment]
This can get problematic given that more than one task needs a oneshot guard.

One alternative I considered was to make it a member of the task's _factory_, so that each instance gets created with the same one.

**Comment by edgao** [comment]
oh, creating it in the factory is much nicer. lemme do that (+ also I found the atomicbool in FailSyncTask, replacing that with an injected instance also)

**Review by johnny-schmidt — APPROVED** [review]

**Pull request merged**
