### PR TITLE
Add test reproducing catalog diff issue

### PR DESCRIPTION
**Pull request by malikdiarra**
Airbyte cloud is failing to compute the diff for some catalog as observed [here](https://github.com/airbytehq/oncall/issues/463). This test reproduce the issue observed in production .

### CODE REVIEW

**Comment by evantahler** [comment]
Nice! The test fails https://github.com/airbytehq/airbyte/runs/8258699224#r49

**Comment by evantahler** [comment]
It's probably great to merge in a failing test (as no one else will have a green build from that point onward).  @malikdiarra do you need help fixing that test?

**Comment by evantahler** [comment]
was this closed by https://github.com/airbytehq/airbyte/pull/16513?

**Comment by evantahler** [comment]
Ping @malikdiarra 

> was this closed by #16513?

**Comment by malikdiarra** [comment]
> Ping @malikdiarra
> 
> > was this closed by #16513?

Yes, closing this.

**Pull request closed without merging**
