### PR TITLE
normalization: Do not return NULL for MySQL column values > 512 chars 

### PR DESCRIPTION
**Pull request by jonico**
## What

* If not specified by a RETURNING clause, the [JSON_VALUE()](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-value) function's return type is VARCHAR(512)
* If the value of a column contains more than 512 characters, the current implementation will return NULL (default behavior if no ON ERROR clause is used.)

image

## How

* by explicitly specifying CHAR as return type, also values > 512 characters will be properly returned

image

## Recommended reading order
1. `json_operations.sql`

## 🚨 User Impact 🚨

* as we are expecting a string value in all cases (and do the explicit CAST in a next step), there is no other behavioral change other than longer strings being properly returned as well

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

Not sure in which category this fix belongs to as it applies to dbt transformations.

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@ChristopheDuong can you review this contribution?

**Review by ChristopheDuong — APPROVED** [review]
Thanks, @jonico for the contribution!

I'm not too familiar with the specificities of MySQL but from the description of this PR, this sounds good.

@marcosmarxm, you can also double-check with the connector team on DB destinations (@grishick ?)

> Not sure in which category this fix belongs to as it applies to dbt transformations.

This is similar to a connector fix and the normalization image would have to be updated/published in a similar way. Then the PR would be merged to the main branch and released as part of the Airbyte platform to be available/useable by users.

**Comment by marcosmarxm** [comment]
Testing in our integration account:
image

**Comment by alafanechere** [comment]
Hey @jonico, thank you for this contribution. I'm waiting for https://github.com/airbytehq/airbyte/pull/11470 to be merged before merging this PR.

**Review by alafanechere — APPROVED** [review]
✅ The change looks legit
✅ Tests are passing on base-normalization
✅ Version is bumped

Thank you for your patience @jonico 
I'd just need an additional quick review from @edgao / @grishick in they think additional testing should be done.

**Review by edgao — APPROVED** [review]
nice! It would be great to extend our automated tests so that we can avoid regressions - this should be as simple as adding an entry to [messages.txt](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/integration_tests/resources/test_nested_streams/data_input/messages.txt) and then updating the various `nested_streams_XYZ_run_row_counts.sql` files (i.e. [nested_streams_first_run_row_counts.sql](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/integration_tests/resources/test_nested_streams/dbt_test_config/dbt_data_tests_tmp/nested_streams_first_run_row_counts.sql) and [nested_streams_second_run_row_counts.sql](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/integration_tests/resources/test_nested_streams/dbt_test_config/dbt_data_tests_tmp_incremental/nested_streams_second_run_row_counts.sql)).

(but no pressure - I can definitely handle this later since we've manually verified it works)

**Comment by jonico** [comment]
@edgao: I would propose to approach the tests in a FUP PR as my family is just heading towards summer vacations 😊. I will add it to my project list with the goal to complete before end of August.

**Comment by grishick** [comment]
It looks like this change broke the build. My CI tests are failing while checking if the new version of normalization exists 
`Checking normalization images with version 0.2.7 exist...`
`
Pulling normalization-clickhouse ... error
Pulling normalization-oracle     ... error
Pulling normalization-mysql      ... error
Pulling normalization-redshift   ... error
Pulling normalization-snowflake  ... error
Pulling normalization            ... error
Pulling normalization-mssql      ... error
`

**Comment by grishick** [comment]
and indeed https://hub.docker.com/repository/docker/airbyte/normalization - no version 0.2.7

**Pull request merged**
