### PR TITLE
✨Source Wikipedia PageViews: Make Connector Compatible with Builder

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
* Make the connector compatible with the builder

## How
* Import schema to manifest
* Update docs, 
* Completely made compatible with the builder

## User Impact
* No impact, chore for maintainability.

## Can this PR be safely reverted and rolled back?
- [x] YES 💚

### CODE REVIEW

**Comment by btkcodedev** [comment]
Creds expired, Needs updates

**Review by natikgadzhi — APPROVED** [review]
Source changes okay! Let's see if incremental test comparison will let this merge

**Comment by btkcodedev** [comment]
Nope, Still CI fails due to connection check failure

**Comment by natikgadzhi** [comment]
Are you blocked, or have everything you need to debug?

**Pull request merged**
