### PR TITLE
🎉 New Source: Appsflyer

### LINKED ISSUE #5718: Source Appsflyer with CDK
## Tell us about the problem you're trying to solve
Develop connector Appsflyer using CDK

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

### PR DESCRIPTION
**Pull request by asyarif93**
## What
Adding new connector Appsflyer using CDK
Resolves #5718

## How
*Describe the solution*

## Recommended reading order
1. `spec.json`
2. `source.py`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

#### Community member or Airbyter
   
- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

### CODE REVIEW

**Comment by asyarif93** [comment]
<details>
<summary> Unit test result: </summary>
<pre><code>
python -m pytest -s unit_tests                                                               ─╯
Test session starts (platform: linux, Python 3.8.10, pytest 6.2.5, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /home/lpt393/projects/airbyte, configfile: pytest.ini
plugins: timeout-1.4.2, mock-3.6.1, sugar-0.9.4
collecting ... 
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_cursor_field ✓2% ▎         
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_cursor_field_in_app_events ✓4% ▌         
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_cursor_field_uninstall_events ✓6% ▋         
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_cursor_field_retargeting_in_app_events ✓8% ▉         
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_cursor_field_installs ✓10% █▏        
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_cursor_field_retargeting_conversions ✓12% █▍        
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_cursor_field_partners_report ✓15% █▌        
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_cursor_field_daily_report ✓17% █▋        
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_cursor_field_geo_report ✓19% █▉        
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_request_params_in_app_events ✓21% ██▏       
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_request_params_installs ✓23% ██▍       
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_request_params_retargeting_in_app_events ✓25% ██▌       
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_request_params_retargeting_conversions ✓27% ██▊       
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_request_params_uninstall_events ✓29% ██▉       
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_request_params_partners_report ✓31% ███▎      
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_request_params_daily_report ✓33% ███▍      
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_request_params_geo_report ✓35% ███▋      
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_request_params_retargeting_partners_report ✓38% ███▊      
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_request_params_retargeting_daily_report ✓40% ███▉      
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_request_params_retargeting_geo_report ✓42% ████▎     
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_get_updated_state_all_exists ✓44% ████▍     
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_get_updated_state_empty_current_stream_and_empty_latest_record ✓46% ████▋     
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_get_updated_state_empty_current_stream_and_exists_latest_record ✓48% ████▊     
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_get_updated_state_exists_current_stream_and_empty_latest_record ✓50% █████     
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_stream_slices ✓52% █████▎    
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_supports_incremental ✓54% █████▌    
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_source_defined_cursor ✓56% █████▋    
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_incremental_streams.py::test_stream_checkpoint_interval ✓58% █████▉    
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_source.py::test_check_connection_expected_ok ✓60% ██████▏   
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_source.py::test_check_connection_expected_app_id_invalid ✓62% ██████▍   
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_source.py::test_check_connection_expected_api_token_invalid ✓65% ██████▌   {"type": "LOG", "log": {"level": "INFO", "message": "Using start_date: 2021-09-13T01:00:00+00:00, end_date: 2021-09-29T14:31:47.450424+00:00"}}

 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_source.py::test_streams ✓67% ██████▋   
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_streams.py::test_request_params ✓69% ██████▉   
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_streams.py::test_parse_response_return_ok ✓71% ███████▏  
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_streams.py::test_parse_response_return_empty_row ✓73% ███████▍  
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_streams.py::test_http_method ✓75% ███████▌  
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_streams.py::test_should_retry[HTTPStatus.OK-False] ✓77% ███████▊  
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_streams.py::test_should_retry[HTTPStatus.BAD_REQUEST-False] ✓79% ███████▉  
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_streams.py::test_should_retry[HTTPStatus.TOO_MANY_REQUESTS-True] ✓81% ████████▎ 
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_streams.py::test_should_retry[HTTPStatus.INTERNAL_SERVER_ERROR-True] ✓83% ████████▍ 
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_streams.py::test_should_retry_raw_data ✓85% ████████▋ 
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_streams.py::test_should_retry_aggregate_data ✓88% ████████▊ 
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_streams.py::test_backoff_time_default[HTTPStatus.OK-None] ✓90% ████████▉ 
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_streams.py::test_backoff_time_default[HTTPStatus.BAD_REQUEST-None] ✓92% █████████▎
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_streams.py::test_backoff_time_default[HTTPStatus.TOO_MANY_REQUESTS-None] ✓94% █████████▍
 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_streams.py::test_backoff_time_default[HTTPStatus.INTERNAL_SERVER_ERROR-None] ✓96% █████████▋{"type": "LOG", "log": {"level": "INFO", "message": "Rate limit exceded. Retry in 60 seconds."}}

 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_streams.py::test_backoff_time_aggregate_data ✓98% █████████▊{"type": "LOG", "log": {"level": "INFO", "message": "Rate limit exceded. Retry in 34092 seconds."}}

 airbyte-integrations/connectors/source-appsflyer/unit_tests/test_streams.py::test_backoff_time_raw_data ✓100% ██████████

Results (0.31s):
      48 passed
</code></pre>
</details>

**Comment by asyarif93** [comment]
<details>
<summary> Acceptance test result: </summary>
<pre><code>
python -m pytest -p integration_tests.acceptance                                                               ─╯
Test session starts (platform: linux, Python 3.8.10, pytest 6.2.5, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /home/lpt393/projects/airbyte, configfile: pytest.ini
plugins: timeout-1.4.2, mock-3.6.1, sugar-0.9.4
collecting ... 
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_match_expected[inputs0] ✓     8% ▊         
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_required[inputs0] ✓          15% █▋        
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_optional[inputs0] ✓          23% ██▍       
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_has_secret[inputs0] ✓        31% ███▏      
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_secret_never_in_the_output[inputs0] ✓38% ███▉      
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestConnection.test_check[inputs0] ✓       46% ████▋     
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestConnection.test_check[inputs1] ✓       54% █████▍    
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_discover[inputs0] ✓     62% ██████▎   
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestD0] ✓69% ██████▉   
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestBasicRead.test_read[inputs0] ✓77% ███████▊  
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_full_refresh.py::TestFullRefresh.test_sequential_reads[inputs0] ✓85% ████████▌ 
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py::TestIncremental.test_two_sequential_reads[inputs0] ✓92% █████████▎
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py::TestIncremental.test_state_with_abnormally_large_values[inputs0] ✓100% ██████████

Results (506.83s):
      13 passed
</code></pre>
</details>

**Comment by harshithmullapudi** [comment]
Hey @asyarif93 thanks for your contribution 🔥 . We are currently focusing cloud launch we will be able to get back and review early next week.

**Review by avida — CHANGES_REQUESTED** [review]
Main point is to use CDK transform class instead of custom transformation code. It super easy to config just with one line. Here is details : https://docs.airbyte.io/connector-development/cdk-python/schemas#default-type-transformation

**Comment by asyarif93** [comment]
I still wondering how to transform some data. for date-time and decimal type seems provided transform class can get the job done. for some other cases like i had to replace `na` with `None`, i might need implement CustomSchemaNormalization. is there any connector that use those class? i only see facebook marketing as primary example.

Also, seems I have realize that i'm using USD currencies while write fieldname with IDR suffix which is a bug. I have yet to decide, should I force everything in USD or allow user to chose their preference, If the latter, I might need override `Stream.get_json_schema` and check if currency code is ISO 4217 valid.

**Comment by avida** [comment]
@asyarif93,
> I still wondering how to transform some data. for date-time and decimal type seems provided transform class can get the job done. for some other cases, e.g. i had to replace na with None, i might need implement CustomSchemaNormalization. is there any connector that use those class? i only see facebook marketing as primary example.

This feature is new, AFAIK o connector using it so far. You can find examples of custom transformation in docs: https://docs.airbyte.io/connector-development/cdk-python/schemas#custom-schema-type-transformation

```python
class MyStream(Stream):
    ...
    transformer = Transformer(TransformConfig.DefaultSchemaNormalization | TransformConfig.CustomSchemaNormalization)
    ...

    @transformer.registerCustomTransform
    def transform_function(orginal_value: Any, field_schema: Dict[str, Any]) -> Any:
        if orginal_value == 'na':
               return None
        return transformed_value
```
Note that transform_function should not take self argument.

> (edit) seems my airbyte-cdk was before airbyte_cdk.sources.utils.transform available (my version was 0.1.17). is there anything i need to change after update airbyte-cdk to 0.1.25?

You have to set CDK version in dependencies and add 
```python
transformer = Transformer(TransformConfig.DefaultSchemaNormalization)
```
to your class member variables ([details](https://docs.airbyte.io/connector-development/cdk-python/schemas#default-type-transformation))

**Review by avida — APPROVED** [review]
Nice one, thanks for the commitment and special thanks for  great unit tests.

**Comment by asyarif93** [comment]
I still need to add Documentation, and maybe a feature to allow user use their prefered currency first.

**Comment by dapearce** [comment]
Hi, is it possible to use this connector in Airbyte open-source?

**Pull request merged**
