### PR TITLE
🐛 Source Chargebee: add tests + fix broken `coupon` stream

### LINKED ISSUE #10192: Improve code quality for chargebee
[airbyte](https://github.com/airbytehq/airbyte)/[airbyte-integrations](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations)/[connectors](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors)/[source-chargebee](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-chargebee)
See details in #10174

### LINKED ISSUE #10447: Source Chargebee: `coupon` stream is broken
## Current Behavior
`read` command for `coupon` stream is outputting error message.
image

Also schema for `coupon` stream has some errors.

## Expected Behavior
`read` command should output either records or nothing but not an error.

## Steps to Reproduce
1. run `read` command for `coupon` stream
2. see `InvalidRequestError` message

## Are you willing to submit a PR?
Yes.

### PR DESCRIPTION
**Pull request by Zirochkaa**
## What
Closes #10192 and #10447.

## How
Add tests to `/unit_tests` folder.
Send correct request parameter for sorting for `coupon` stream.

## 🚨 User Impact 🚨
Are there any breaking changes?
No.

## Pre-merge Checklist

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### CODE REVIEW

**Comment by Zirochkaa** [comment]
SAT:
image

Unit tests:
image

**Review by sergei-solonitcyn — APPROVED** [review]

**Pull request merged**
