### PR TITLE
🐛Source Klaviyo: add availability strategy

### LINKED ISSUE #22258: Source source-klaviyo: implement AvailabilityStrategy
## What
We want GA connectors to make use of an AvailabilityStrategy in their streams to be able to perform error handling on the
stream level. The base use case supported by the `HttpAvailabilityStrategy` is for stream-based permissions,
in order to be able to skip a stream that the connector no longer has access to (because of e.g. scope
changes on an Oauth user config). An `AvailabilityStrategy` can be used to address any error that may occur
on a stream level, to avoid hitting errors, or having to except the same error for every record in a stream,
instead of skipping that stream altogether.

## How
There are a few different ways to go about this, usually depending on how much custom error handling we already
do in a connector, but also due to how the connector works.
- If we have no custom error handling: Inherit the default HttpAvailabilityStrategy. This is as simple as removing the override setting that currently sets
  the AvailabilityStrategy for the streams to `None`. This is useful if we don't currently do much custom error handling
  in the connector.
- If we have custom error handling for 403: Forbidden errors: Do the above to inherit the HttpAvailabilityStrategy,
  removing the custom error handling, but continuing any testing we have that 403s are handled gracefully by the connector
- If we have custom error handling for lots of per-stream errors: Extend the HttpAvailabilityStrategy. You can subclass
  the HttpAvailabilityStrategy to change the `reasons_for_unavailable_status_codes` method to except more error codes and
  provide messages for those error codes.
- If there is a smarter way to determine availability than trying to read the first record and excepting errors: Inherit
  the AvailabilityStrategy base class. For example, if there are clearly defined scopes required to access each stream in
  a given source, you might instead determine whether a stream is available by checking the scopes on the authenticator to
  see if it has the scopes required by the stream.

Note that the AvailabilityStrategy is defined on each stream. For most cases, it is easiest to set it in your stream's
base stream class, where the override is, but for some use cases, different streams might have different availability strategies -
and that's totally fine.

### PR DESCRIPTION
**Pull request by askarpets**
## What
Enable `AvailabilityStrategy` for both `KlaviyoStreamLatest` and `KlaviyoStreamV1`
https://github.com/airbytehq/airbyte/issues/22258

## How
For the `KlaviyoStreamV1`, removed override of `availability_strategy` method, which previously returned `None`, so now it uses `HttpAvailabilityStrategy`.
For the `KlaviyoStreamLatest`, implemented `KlaviyoAvailabilityStrategyLatest`, which extends the list of `unavailable_status_codes` with code of `401`.

## Recommended reading order
1. `availability_strategy.py`
2. `streams.py`

## 🚨 User Impact 🚨
No breaking changes

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-klaviyo test report (commit [`d0e276ab39`](https://github.com/airbytehq/airbyte/pull/31379/commits/d0e276ab39cd66fb2da6c5fd17c4f4080da8ab46)) - ❌

⏲️  Total pipeline duration: 03mn18s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build source-klaviyo docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                     | ✅        |
| Acceptance tests                                               | ❌        |
| Code format checks                                             | ✅        |
| Validate metadata for source-klaviyo                           | ✅        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ❌        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/22258-source-klaviyo-availability-strategy/1697193931/d0e276ab39cd66fb2da6c5fd17c4f4080da8ab46/source-klaviyo/0.3.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d0e276ab39cd66fb2da6c5fd17c4f4080da8ab46)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-klaviyo test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-klaviyo test report (commit [`ba2240e12e`](https://github.com/airbytehq/airbyte/pull/31379/commits/ba2240e12ed52daad4a928148132e8ffcea01b6a)) - ❌

⏲️  Total pipeline duration: 03mn34s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build source-klaviyo docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                     | ✅        |
| Acceptance tests                                               | ❌        |
| Code format checks                                             | ✅        |
| Validate metadata for source-klaviyo                           | ✅        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ✅        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/22258-source-klaviyo-availability-strategy/1697195801/ba2240e12ed52daad4a928148132e8ffcea01b6a/source-klaviyo/0.3.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ba2240e12ed52daad4a928148132e8ffcea01b6a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-klaviyo test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-klaviyo test report (commit [`b6bec8ed7d`](https://github.com/airbytehq/airbyte/pull/31379/commits/b6bec8ed7df2140c8803dfbcbb8ee813e9b9e6c2)) - ❌

⏲️  Total pipeline duration: 02mn46s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build source-klaviyo docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                     | ✅       |
| Acceptance tests                                               | ❌       |
| Code format checks                                             | ✅       |
| Validate metadata for source-klaviyo                           | ✅       |
| Connector version semver check                                 | ✅       |
| Connector version increment check                              | ✅       |
| QA checks                                                      | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/22258-source-klaviyo-availability-strategy/1697450883/b6bec8ed7df2140c8803dfbcbb8ee813e9b9e6c2/source-klaviyo/0.3.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b6bec8ed7df2140c8803dfbcbb8ee813e9b9e6c2)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-klaviyo test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-klaviyo test report (commit [`b6bec8ed7d`](https://github.com/airbytehq/airbyte/pull/31379/commits/b6bec8ed7df2140c8803dfbcbb8ee813e9b9e6c2)) - ❌

⏲️  Total pipeline duration: 03mn20s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build source-klaviyo docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                     | ✅       |
| Acceptance tests                                               | ❌       |
| Code format checks                                             | ✅       |
| Validate metadata for source-klaviyo                           | ✅       |
| Connector version semver check                                 | ✅       |
| Connector version increment check                              | ✅       |
| QA checks                                                      | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/22258-source-klaviyo-availability-strategy/1697451767/b6bec8ed7df2140c8803dfbcbb8ee813e9b9e6c2/source-klaviyo/0.3.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b6bec8ed7df2140c8803dfbcbb8ee813e9b9e6c2)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-klaviyo test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-klaviyo test report (commit [`e024801cbd`](https://github.com/airbytehq/airbyte/pull/31379/commits/e024801cbd5e387fd1c29c28156bc9f12df17099)) - ❌

⏲️  Total pipeline duration: 01mn48s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build source-klaviyo docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                     | ✅       |
| Acceptance tests                                               | ❌       |
| Code format checks                                             | ✅       |
| Validate metadata for source-klaviyo                           | ✅       |
| Connector version semver check                                 | ✅       |
| Connector version increment check                              | ✅       |
| QA checks                                                      | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/22258-source-klaviyo-availability-strategy/1697453135/e024801cbd5e387fd1c29c28156bc9f12df17099/source-klaviyo/0.3.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e024801cbd5e387fd1c29c28156bc9f12df17099)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-klaviyo test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-klaviyo test report (commit [`098b659c5b`](https://github.com/airbytehq/airbyte/pull/31379/commits/098b659c5b1533870187fcd0ed171a8f8d7c0292)) - ✅

⏲️  Total pipeline duration: 02mn38s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build source-klaviyo docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                     | ✅       |
| Acceptance tests                                               | ✅       |
| Code format checks                                             | ✅       |
| Validate metadata for source-klaviyo                           | ✅       |
| Connector version semver check                                 | ✅       |
| Connector version increment check                              | ✅       |
| QA checks                                                      | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/22258-source-klaviyo-availability-strategy/1697456365/098b659c5b1533870187fcd0ed171a8f8d7c0292/source-klaviyo/0.3.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:098b659c5b1533870187fcd0ed171a8f8d7c0292)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-klaviyo test
```

**Review by bazarnov — APPROVED** [review]
Please bind the issues and PR together.

**Pull request merged**
