### PR TITLE
✨ Source KYVE: Include support to KYVE's mainnet data and KYVE storage

### PR DESCRIPTION
**Pull request by cgkournelos-rf**
## What
Add new schema for Tendermint chain data that are available in KYVE's mainnet. Moreover, the KYVE data storage is added in addition to arweave.

This PR aims to resolve the issue https://github.com/airbytehq/airbyte/issues/29153.

## Recommended reading order
1. `source_kyve/stream.py`
2. `source_kyve/schemas/tendermint/dataItem.json`
3. `source_kyve/spec.yaml`

## 🚨 User Impact 🚨
The users will be able to fetch data from KYVE's mainnet and testnet.  KYVE Network consists of three individual networks: *Korellia* is the `devnet` used for development purposes, *Kaon* is the `testnet` used for testing purposes, and **`mainnet`** is the official network. Although through Kaon and Korellia validated data can be used for development purposes, it is recommended to only trust the data validated on Mainnet.

Users can specify the endpoint which will be requested in **`KYVE-API URL Base`**. By default, the official KYVE **`mainnet`** 
endpoint will be used, providing the data of [these pools](https://app.kyve.network/#/pools).

## Tests

Acceptance Test Results : 

image

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

### CODE REVIEW

**Comment by cgkournelos-rf** [comment]
this PR is ready for review

**Comment by cgkournelos-rf** [comment]
@marcosmarxm this PR is ready for review.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Can you remove the test.json file?

**Comment by christopherbrumm** [comment]
@marcosmarxm Done!

**Comment by cgkournelos-rf** [comment]
@marcosmarxm The requested changes are now fixed.

**Comment by cgkournelos-rf** [comment]
@marcosmarxm is there anything else that we should do to close this PR?

**Comment by marcosmarxm** [comment]
@cgkournelos-rf sorry the missing updates here. Unit tests and acceptance tests aren't working, can you show they work for you?

**Comment by cgkournelos-rf** [comment]
@marcosmarxm There was some issue with the acceptance tests. Now we have fixed them and the acceptance test has been passed successfully (see attached image).
image

**Comment by christopherbrumm** [comment]
Friendly reminder @marcosmarxm to finally merge it.

**Comment by cgkournelos-rf** [comment]
@marcosmarxm this is reminder to merge this PR for our source

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Unit tests are failing, can you check them? After that I'll prioritize to merge the changes. Sorry the delay to return here.

**Comment by christopherbrumm** [comment]
This PR should be closed because the core changes are already outdated.

A new PR has been created with (#32492) that needs to be reviewed.

@marcosmarxm

**Comment by cgkournelos-rf** [comment]
This PR is obsolete. A new PR #32492 will be merged with a different approach on KYVE source.

**Pull request closed without merging**
