### PR TITLE
[Non-Forked] ✨Source Retently: Migrate Python CDK to Low-code CDK

### LINKED ISSUE #28118: Retently

### PR DESCRIPTION
**Pull request by sajarin**
## What
Run ci checks for #29040
Migrating Source retently to Low-Code CDK
Closes https://github.com/airbytehq/airbyte/issues/28118

## How
Developed using (Configuration Based Source) low-code CDK

## Recommended reading order

1. manifest.yaml
2. schemas/*

 ##  Test
<details>
<summary>Acceptance Test</summary>
Screenshot 2023-08-03 at 6 52 13 PM
</details>

# 🚨 User Impact 🚨
**No breaking changes**, migration to low-code
<details>
<summary>Migrate Connector : Source retently</summary>

- [x] **Community Member? Grant Edit Access to Maintainers [instructions](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests)**
- [x] **Secrets in the Connector's Spec**
- [x] **Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run ./gradlew :airbyte-integrations:connectors:<name>:integrationTest.**
- [x] **Code Reviews Completed**
  - [x] **Documentation Updated**
  - [x] **Connector's README.md**
  - [x] **Connector's bootstrap.md**
  - [x] **docs/integrations/<source or destination>/<name>.md (including changelog. See changelog example)**
  - [x] **docs/integrations/README.md**
  - [x] **airbyte-integrations/builds.md**
- [x] **PR Name follows PR Naming Conventions**
</details>

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-retently test report (commit [`4d0203bd9f`](https://github.com/airbytehq/airbyte/pull/29164/commits/4d0203bd9fd7892de608cce639d4108bd0793ac5)) - ❌

⏲️  Total pipeline duration: 03mn06s 

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-retently/metadata.yaml | ❌        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ✅        |
| QA checks                                                              | ❌        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-retently docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/saj_retently-low/1691422436/4d0203bd9fd7892de608cce639d4108bd0793ac5/source-retently/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:4d0203bd9fd7892de608cce639d4108bd0793ac5)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-retently test
```

**Comment by octavia-squidington-iii** [comment]
##  source-retently test report (commit [`5a18bdc4f9`](https://github.com/airbytehq/airbyte/pull/29164/commits/5a18bdc4f9ddd0b6f289c0417f2b7ee23abec708)) - ❌

⏲️  Total pipeline duration: 02mn06s 

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-retently/metadata.yaml | ❌        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ✅        |
| QA checks                                                              | ✅        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-retently docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/saj_retently-low/1691423776/5a18bdc4f9ddd0b6f289c0417f2b7ee23abec708/source-retently/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:5a18bdc4f9ddd0b6f289c0417f2b7ee23abec708)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-retently test
```

**Comment by octavia-squidington-iii** [comment]
##  source-retently test report (commit [`bdf75c88ec`](https://github.com/airbytehq/airbyte/pull/29164/commits/bdf75c88ec9bcd57f5550282e5aac3cf17357481)) - ✅

⏲️  Total pipeline duration: 03mn46s 

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-retently/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ✅        |
| QA checks                                                              | ✅        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-retently docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/saj_retently-low/1691507615/bdf75c88ec9bcd57f5550282e5aac3cf17357481/source-retently/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:bdf75c88ec9bcd57f5550282e5aac3cf17357481)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-retently test
```

**Comment by octavia-squidington-iii** [comment]
##  source-retently test report (commit [`e9b2b05a8a`](https://github.com/airbytehq/airbyte/pull/29164/commits/e9b2b05a8a4ec38bc97f6a2d8e5ed77b6c203144)) - ✅

⏲️  Total pipeline duration: 02mn18s 

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-retently/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ✅        |
| QA checks                                                              | ✅        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-retently docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/saj_retently-low/1691509471/e9b2b05a8a4ec38bc97f6a2d8e5ed77b6c203144/source-retently/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e9b2b05a8a4ec38bc97f6a2d8e5ed77b6c203144)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-retently test
```

**Review by marcosmarxm — APPROVED** [review]
Aamzing job Saj

**Comment by octavia-squidington-iii** [comment]
##  source-retently test report (commit [`e08a749f09`](https://github.com/airbytehq/airbyte/pull/29164/commits/e08a749f09856857e75faae099f88b881547ad6c)) - ✅

⏲️  Total pipeline duration: 02mn29s 

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-retently/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ✅        |
| QA checks                                                              | ✅        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-retently docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/saj_retently-low/1691511935/e08a749f09856857e75faae099f88b881547ad6c/source-retently/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e08a749f09856857e75faae099f88b881547ad6c)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-retently test
```

**Pull request merged**
