### PR TITLE
[source-airtable] - Updates CDK to ^3

### PR DESCRIPTION
**Pull request by pnilan**
## What
- Updates source-airtable to CDK v3.0.0
- Ref: https://github.com/airbytehq/airbyte-internal-issues/issues/8593

## How
- Removes `should_retry` and `backoff_time` methods from `AirtableStream` and `AirtableBases`
- Adds custom backoff strategy to handle 429 responses per previous implementation
- Adds custom error mapping to fail on 422 status code.
- Adds custom error handling to parse 403 responses for inadequate permissions error message.
- Removes should_retry/backoff_time unit tests
- Adds new unit tests for custom backoff strategy and error handler
- Bumps minor version

### Recommended Reading Order
1. `streams.py`
2. `airtable_error_handler.py`
3. `airtable_backoff_strategy.py`
4. tests

## User Impact
- None 

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by pnilan** [comment]
/approve-regression-test
[Regression Test Job](https://github.com/airbytehq/airbyte/actions/runs/9864648977/job/27240000399)

**Review by bazarnov — APPROVED** [review]

**Comment by pnilan** [comment]
Regression Test: https://github.com/airbytehq/airbyte/actions/runs/9978289293

**Comment by aldogonzalez8** [comment]
[Here](https://ff1dc771106eeb2a40756cb884e0f4d84cd0cfe8568d6bbb9c660e1-apidata.googleusercontent.com/download/storage/v1/b/airbyte-ci-reports-multi/o/airbyte-ci%2Fconnectors%2Ftest%2Fmanual%2Fmaster%2F1721306391%2F3cbd292154a8b8e942348e079404ae3a5146181c%2Fsource-shopify%2F2.4.13%2Foutput.html?jk=AYBlUPDsOq4V58d0Dia50zxZLlMD6AQYXq3utgsRbU-vaRFu8FLwx3rrmDnE7QlQv8dHzpk8An2GfN0CnkVy7fR07uvOfymPD-3pfsZLtP2MYdWLDYtAEoMl94QxBpUPY1H1Cx6pnyCL3TS5k7PDU7u6rpTuTa54Wqog7Y7zpz2iaDE4NOpQO44FScp3gtlP3KwAk9R0uVzDoxBiWOMxkt3WeoIDdMtmqFQjKmcpMPINVHC6rrNGMKWCGbDy1hKCfEUFA7T9freucehi2PMTwZHA8R6CpJ6WvCwYVGk3e96Pq4CXWZ8-PSyrBuMmn_CgvW6ESAlnQH39BMCnIH0ervb0XQ68W8PMczXZcesCgkouHhI27Cw3ZbWaFhoGuEVQfxRcboDRavN8q35InqBRprVanNk5M8TP7aMdh5dfESDja64z0uJTvlXFRkRHUqbP7OAfVK1pqabph3lFfUwq69W5ex9plAMo2KNkmcuas6AbSQby-Fcj9YzYJvLTIstaHiX2YQkqFw0QFHXFmwMZUvwpx4GxVAXEioA4weyBTGtLC4MU7pkzBZtfSMmvnkwUoiAXZsN81LiifaSPL5aF52IEzC5dMe7SlirfRvn83KSw2ie9bpGY5qN51LyquFjk-ktu515WYvQYmCCCtwjaDXcDA4ZYwV8nUuSTU_-IdnhSK3mwwN8D3z3vAsZPitYz4t794hntHNCLcKkwvdw6VeDghoanjKwPmM4-rFyZxK34o5_ryqS-Syv5V5I3eR3ccwwbMJxxUYhsrNez_PDFgn1WPGortWyXTzgfev23i3cHO0RmMm-dDmBqWUBe2-CgNJY2GUH7LS7kRgxDCcaLBtyn8VLisdk8bOMo2pTt8M6VWu3c43y85eB-F0sa1C3s5b_VGSvGtwepRyL0c2s76daZ9SsMdDCk_UiH7SFn-nCKVKNhCvrXIOnj9Xd-BF6kubUN_zWup0Hf_j3x8OhHVGWQT6Th9bm7pE7wb5gJUHjj7AY469VY_PxYlwe7Emj5ssiMvrrWxvaUBRjFdFctWX0tjZJhXN3yxTQ6Iwun83GJm3Nj7JWLn6B9OLyclXD7TBOxPygR1ltK06QwV8s1441ilh7ZwR0LMgNqp5zNkpoo5O0W0DBafUJ005FOyP-PsGATyI3z-sLmHFUaKxAl79r-pXNxYA2mIV5c67T8bVsd05T0IALkM2SgMbDe4rosB7urw7Wm3_ZYCMlOsjmV0f7KKtU0FdCe0Cvi10MAF2Y-O7kJ0kLzI0fxCOOeea6ZeXFL5YruuyrXT9pkVfAIj3sBDTUNNTtVuQ8MG-UT5raa8ZUlIjmQ42Pi9yP6NCk6tXXgDzBThKH5N2pA&isca=1) you can find the results of the regression tests

**Pull request merged**
