### PR TITLE
Langchain destination: Use embedders from CDK

### PR DESCRIPTION
**Pull request by hwaxxer**
## What
Uses embedders from the CDK for destination-langchain, fixing airbytehq/airbyte-internal-issues#2056 

## How
Replaces custom embedders written in the connector.

### CODE REVIEW

**Comment by flash1293** [comment]
I added a changelog and bumped the version

Running PR here: https://github.com/airbytehq/airbyte/pull/30294

**Review by flash1293 — APPROVED** [review]
Change looks good to me, but it doesn't fix https://github.com/airbytehq/airbyte/issues/29659 just yet (as custom document processor and writer implementation has to be removed as well)

CI got a green run here: https://github.com/airbytehq/airbyte/pull/30294

**Comment by hwaxxer** [comment]
@flash1293 Ah I see. Happy to add that although it's not entirely clear how the `DocumentProcessor` should be replaced as per #29659 since the functionality is slightly different. The custom one truncates the metadata based on a size parameter that's passed to the constructor. Should this functionality be kept or tossed?

**Comment by flash1293** [comment]
@hwaxxer It should be moved into the indexer: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-pinecone/destination_pinecone/indexer.py#L67

But as mentioned, not necessary to do it as part of this PR

**Review by flash1293 — APPROVED** [review]

**Pull request merged**
