### PR TITLE
fix pyyaml/cython dependency issue when building base-normalization

### PR DESCRIPTION
**Pull request by pedroslopez**
## What

Applies a workaround for https://github.com/yaml/pyyaml/issues/601

This error is introduced by `COPY --from=airbyte/base-airbyte-protocol-python:0.1.1 /airbyte /airbyte`. When we get to installing dependencies in the dockerfile for this image here:

```
# Install python dependencies
WORKDIR /airbyte/base_python_structs
RUN pip install .
```

We error out with the `cython_sources` error. 

airbyte/base-airbyte-protocol-python has only been published once, 2 years ago. It is unclear where this image comes from, what's in it, and how it was built. This isn't a great spot to be in, but we can workaround it for now with this fix until we know more.

### CODE REVIEW

**Review by evantahler — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  destination-mysql-strict-encrypt test report (commit [`ca28112095`](https://github.com/airbytehq/airbyte/pull/28451/commits/ca28112095b29532d1dafadb265fcc3eb84b6439)) - ❌

⏲️  Total pipeline duration: 30mn01s 

| Step                                                                                        | Result   |
|:--------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mysql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                              | ✅        |
| QA checks                                                                                   | ✅        |
| Build connector tar                                                                         | ✅        |
| Build destination-mysql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mysql:dev                                                       | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mysql-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/pedroslopez_fix-base-normalization/1689728337/ca28112095b29532d1dafadb265fcc3eb84b6439/destination-mysql-strict-encrypt/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mysql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-exasol test report (commit [`ca28112095`](https://github.com/airbytehq/airbyte/pull/28451/commits/ca28112095b29532d1dafadb265fcc3eb84b6439)) - ❌

⏲️  Total pipeline duration: 07mn51s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-exasol/metadata.yaml     | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ❌        |
| Build connector tar                                                           | ✅        |
| Build destination-exasol docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-exasol:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/pedroslopez_fix-base-normalization/1689728337/ca28112095b29532d1dafadb265fcc3eb84b6439/destination-exasol/0.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-exasol test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-redshift test report (commit [`ca28112095`](https://github.com/airbytehq/airbyte/pull/28451/commits/ca28112095b29532d1dafadb265fcc3eb84b6439)) - ✅

⏲️  Total pipeline duration: 28mn28s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-redshift/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-redshift docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-redshift:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-redshift:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/pedroslopez_fix-base-normalization/1689728337/ca28112095b29532d1dafadb265fcc3eb84b6439/destination-redshift/0.6.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redshift test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mssql-strict-encrypt test report (commit [`ca28112095`](https://github.com/airbytehq/airbyte/pull/28451/commits/ca28112095b29532d1dafadb265fcc3eb84b6439)) - ❌

⏲️  Total pipeline duration: 24mn51s 

| Step                                                                                        | Result   |
|:--------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mssql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                              | ✅        |
| QA checks                                                                                   | ✅        |
| Build connector tar                                                                         | ✅        |
| Build destination-mssql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mssql:dev                                                       | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mssql-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/pedroslopez_fix-base-normalization/1689728337/ca28112095b29532d1dafadb265fcc3eb84b6439/destination-mssql-strict-encrypt/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mssql-strict-encrypt test
```

**Comment by pedroslopez** [comment]
Connectors Base build failure was due to a failing test on airbyte-cdk that has been fixed in master

**Comment by octavia-approvington** [comment]
Send it! <br/> rocket socks

**Review by octavia-approvington — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  destination-rockset test report (commit [`08ad92b9eb`](https://github.com/airbytehq/airbyte/pull/28451/commits/08ad92b9eb1e21a81fcb31afe0de7c227b391c82)) - ❌

⏲️  Total pipeline duration: 10mn53s 

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-rockset/metadata.yaml     | ✅        |
| Connector version semver check                                                 | ✅        |
| QA checks                                                                      | ❌        |
| Build connector tar                                                            | ✅        |
| Build destination-rockset docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-rockset:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/pedroslopez_fix-base-normalization/1689741324/08ad92b9eb1e21a81fcb31afe0de7c227b391c82/destination-rockset/0.1.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-rockset test
```

**Pull request merged**
