### PR TITLE
Source Younium: Adding Booking and Account streams

### PR DESCRIPTION
**Pull request by hhagblom**
## What
We needed to get Booking with Booking lines, which are the transaction level data on an order as well as the Account stream. 

This is to fix issue #24654

## How
Added the booking and account stream to the existing source connecting

## 🚨 User Impact 🚨
No breaking changes, when the connector is refreshed the two new streams should appear for syncing.

## Pre-merge Checklist
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Connector version is set to `0.0.1`
    - [ ] `Dockerfile` has version `0.0.1`
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### CODE REVIEW

**Comment by hhagblom** [comment]
Younium Sync Airbyte
Screenshot of sucessful syncing of two new streams.

**Comment by hhagblom** [comment]
Younium Connector passing tests
Younium Integration Test Run
Screenshot of passing unit-tests, there seem to be no integration tests running at the moment.

**Comment by marcosmarxm** [comment]
Sorry for the long delay in getting this reviewed and merged. Our team is currently finishing the August Hackathon review contributions over the next two weeks, and after that, we will return to the community backlog.

**Comment by hhagblom** [comment]
Thanks for considering it. While you're at it could you reconsider the Fortnox Connector pull request that we supplied or give us a reason why it was closed. It would be a waste to not accept it if there is no good reason for it.

**Comment by sajarin** [comment]
hey @hhagblom any chance you could rebase this branch on master, it has been many months (apologies for not getting to this sooner.)

In addition, there are some minor review changes which i'd like to just fix and commit directly to your branch but I don't have push permissions to your branch (likely for a good reason since it's a branch from your company's fork of Airbyte.)

**Comment by sajarin** [comment]
hey @hhagblom this has been merged in #31064 (since I couldn't push changes to your branch here)

Thanks for the contribution and apologies for the delay!

**Comment by hhagblom** [comment]
> hey @hhagblom this has been merged in #31064 (since I couldn't push changes to your branch here)
> 
> Thanks for the contribution and apologies for the delay!

Ok, sorry about not getting to it and thanks for sorting it out!

**Pull request closed without merging**
