### PR TITLE
source-front contribution from btkcodedev

### PR DESCRIPTION
**Pull request by btkcodedev**
Closes https://github.com/airbytehq/airbyte-internal-issues/issues/9777
Auto-generated PR by the Connector Builder for source-front

### CODE REVIEW

**Comment by natikgadzhi** [comment]
This is awesome.

**Comment by ZackMattor** [comment]
Going to be trying this out this week, thanks for the contribution! :)

**Comment by natikgadzhi** [comment]
Nice! @ZackMattor tell me how that goes.

**Pull request merged**
