### PR TITLE
🎉 New Source: Auth0 [python cdk]

### PR DESCRIPTION
**Pull request by YiyangLi**
## What
- Full import and incremental are supported
- OAuth2 and Access Token are supported
- Only `users` stream is added
- Added unit tests and ensure all acceptance tests are passed locally
- It's free to create a new account in Auth0, so it's free to setup an integration account.
- Related to: https://github.com/airbytehq/connector-contest/issues/119

## How
The API Responses from Auth0 offer 2 schemas, enveloped with pagination or a naked entity list. It depends on the request parameter `include_totals`. 
When it's a full import, include_totals is true, and the parse_response will read data from `json.get($entities)`, for example, `json.get("users")`
When it's an incremental import, include_totals is false, and page index is always 0. The query parameter will include `sort` and `q`, in order to sort responses in descending order and pass the cursor value to filter responses. 

## Recommended reading order
1. `source.py`
2. `spec.json`

## 🚨 User Impact 🚨
No, it's a new source connector

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Unit Tests

<details><summary><strong>Unit</strong></summary>

collecting ... 
 airbyte-integrations/connectors/source-auth0/unit_tests/test_source.py::TestAuthentication.test_init_token_authentication_init ✓                                                                                                                                  4% ▍         
 airbyte-integrations/connectors/source-auth0/unit_tests/test_source.py::TestAuthentication.test_init_oauth2_authentication_init ✓                                                                                                                                 7% ▊         
 airbyte-integrations/connectors/source-auth0/unit_tests/test_source.py::TestAuthentication.test_init_oauth2_authentication_wrong_credentials_record ✓                                                                                                            11% █▏        
 airbyte-integrations/connectors/source-auth0/unit_tests/test_source.py::TestAuthentication.test_init_oauth2_authentication_wrong_oauth_config_bad_auth_type ✓                                                                                                    14% █▌        
 airbyte-integrations/connectors/source-auth0/unit_tests/test_source.py::TestAuthentication.test_check_connection_ok ✓                                                                                                                                            18% █▊        
 airbyte-integrations/connectors/source-auth0/unit_tests/test_source.py::TestAuthentication.test_check_connection_error_status_code ✓                                                                                                                             21% ██▎       
 airbyte-integrations/connectors/source-auth0/unit_tests/test_source.py::TestAuthentication.test_check_connection_error_with_exception ✓                                                                                                                          25% ██▌       
 airbyte-integrations/connectors/source-auth0/unit_tests/test_source.py::TestAuthentication.test_check_streams ✓                                                                                                                                                  29% ██▉       
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestAuth0Stream.test_auth0_stream_request_params ✓                                                                                                                                      32% ███▎      
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestAuth0Stream.test_auth0_stream_parse_response ✓                                                                                                                                      36% ███▋      
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestAuth0Stream.test_auth0_stream_backoff_time ✓                                                                                                                                        39% ███▉      
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestAuth0Stream.test_auth0_stream_incremental_request_params ✓                                                                                                                          43% ████▍     
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestAuth0Stream.test_incremental_auth0_stream_parse_response ✓                                                                                                                          46% ████▋     
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestAuth0Stream.test_incremental_auth0_stream_backoff_time ✓                                                                                                                            50% █████     
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestAuth0Stream.test_auth0_stream_incremental_backoff_time_empty ✓                                                                                                                      54% █████▍    
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestAuth0Stream.test_auth0_stream_incremental_back_off_now ✓                                                                                                                            57% █████▊    
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestAuth0Stream.test_auth0_stream_incremental_get_updated_state ✓                                                                                                                       61% ██████▏   
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestAuth0Stream.test_auth0_stream_http_method ✓                                                                                                                                         64% ██████▌   
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestNextPageToken.test_next_page_token ✓                                                                                                                                                68% ██████▊   
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestNextPageToken.test_next_page_token_invalid_cursor ✓                                                                                                                                 71% ███████▎  
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestNextPageToken.test_next_page_token_missing_cursor ✓                                                                                                                                 75% ███████▌  
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestNextPageToken.test_next_page_token_one_page_only ✓                                                                                                                                  79% ███████▉  
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestNextPageToken.test_next_page_token_last_page_incomplete ✓                                                                                                                           82% ████████▎ 
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestNextPageToken.test_next_page_token_last_page_complete ✓                                                                                                                             86% ████████▋ 
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestStreamUsers.test_stream_users ✓                                                                                                                                                     89% ████████▉ 
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestStreamUsers.test_users_request_params_out_of_next_page_token ✓                                                                                                                      93% █████████▍
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestStreamUsers.test_users_source_request_params_have_next_cursor ✓                                                                                                                     96% █████████▋
 airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py::TestStreamUsers.test_users_source_parse_response ✓                                                                                                                                     100% ██████████
=============================================================================================================================== warnings summary ===============================================================================================================================
airbyte-integrations/connectors/source-auth0/unit_tests/test_source.py: 1 warning
airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py: 20 warnings
  /Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-auth0/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py:43: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    self._authenticator: HttpAuthenticator = NoAuth()

airbyte-integrations/connectors/source-auth0/unit_tests/test_source.py: 1 warning
airbyte-integrations/connectors/source-auth0/unit_tests/test_streams.py: 20 warnings
  /Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-auth0/.venv/lib/python3.9/site-packages/deprecated/classic.py:173: DeprecationWarning: Call to deprecated class HttpAuthenticator. (Use requests.auth.AuthBase instead) -- Deprecated since version 0.1.20.
    return old_new1(cls, *args, **kwargs)

-- Docs: https://docs.pytest.org/en/stable/warnings.html

Results (0.29s):
      28 passed

</details>

## Integration Tests

<details><summary><strong>Integration</strong></summary>

Test session starts (platform: darwin, Python 3.9.13, pytest 6.2.5, pytest-sugar 0.9.5)
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-auth0/.hypothesis/examples')
rootdir: /Users/bartdev/Playground/airbyte, configfile: pytest.ini
plugins: hypothesis-6.54.6, sugar-0.9.5, requests-mock-1.9.3, mock-3.6.1, timeout-1.4.2, cov-3.0.0
collecting ... 

Results (0.12s):

</details>

<details><summary><strong>Acceptance</strong></summary>

Test session starts (platform: darwin, Python 3.9.13, pytest 6.2.5, pytest-sugar 0.9.5)
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-auth0/.hypothesis/examples')
rootdir: /Users/bartdev/Playground/airbyte, configfile: pytest.ini
plugins: hypothesis-6.54.6, sugar-0.9.5, requests-mock-1.9.3, mock-3.6.1, timeout-1.4.2, cov-3.0.0
collecting ... 
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_config_match_spec[inputs0] ✓                                                                                                                           3% ▍         
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_match_expected[inputs0] ✓                                                                                                                              6% ▋         
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_docker_env[inputs0] ✓                                                                                                                                 10% █         
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_oneof_usage[inputs0] ✓                                                                                                                                13% █▍        
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_required[inputs0] ✓                                                                                                                                   16% █▋        
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_optional[inputs0] ✓                                                                                                                                   19% █▉        
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_has_secret[inputs0] ✓                                                                                                                                 23% ██▍       
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_secret_never_in_the_output[inputs0] ✓                                                                                                                 26% ██▋       
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_defined_refs_exist_in_json_spec_file[inputs0] ✓                                                                                                       29% ██▉       
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_oauth_flow_parameters[inputs0] ✓                                                                                                                      32% ███▎      Pulling docker image airbyte/source-auth0:latest
{"type": "LOG", "log": {"level": "WARN", "message": "\n We did not find the airbyte/source-auth0:latest image for this connector. This probably means this version has not yet been published to an accessible docker registry like DockerHub."}}

 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_backward_compatibility[inputs0] s                                                                                                                     35% ███▋      
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_additional_properties_is_true[inputs0] ✓                                                                                                              39% ███▉      
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestConnection.test_check[inputs0] ✓                                                                                                                                42% ████▎     
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestConnection.test_check[inputs1] ✓                                                                                                                                45% ████▌     
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestConnection.test_check[inputs2] ✓                                                                                                                                48% ████▉     
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestConnection.test_check[inputs3] ✓                                                                                                                                52% █████▎    
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_discover[inputs0] ✓                                                                                                                              55% █████▌    
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_cursors_exist_in_schema[inputs0] ✓                                                                                                       58% █████▊    
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_refs_exist_in_schema[inputs0] ✓                                                                                                          61% ██████▎   
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_keyword_exist_in_schema[inputs0-allOf] ✓                                                                                                 65% ██████▌   
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_keyword_exist_in_schema[inputs0-not] ✓                                                                                                   68% ██████▊   
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_primary_keys_exist_in_schema[inputs0] ✓                                                                                                          71% ███████▏  
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_streams_has_sync_modes[inputs0] ✓                                                                                                                74% ███████▌  
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_additional_properties_is_true[inputs0] ✓                                                                                                         77% ███████▊  Pulling docker image airbyte/source-auth0:latest
{"type": "LOG", "log": {"level": "WARN", "message": "\n We did not find the airbyte/source-auth0:latest image for this connector. This probably means this version has not yet been published to an accessible docker registry like DockerHub."}}

 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_backward_compatibility[inputs0] s                                                                                                                81% ████████▏ {"type": "LOG", "log": {"level": "WARN", "message": "Unable to parse connector's output state is updated!\n, error: 1 validation error for AirbyteMessage\n__root__\n  Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=state is updated!\n; pos=0; lineno=1; colno=1)"}}
{"type": "LOG", "log": {"level": "WARN", "message": "Unable to parse connector's output state is updated!\n, error: 1 validation error for AirbyteMessage\n__root__\n  Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=state is updated!\n; pos=0; lineno=1; colno=1)"}}

 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestBasicRead.test_read[inputs0] ✓                                                                                                                                  84% ████████▍ {"type": "LOG", "log": {"level": "ERROR", "message": "Docker container failed, code 1, error:\n{\"type\": \"TRACE\", \"trace\": {\"type\": \"ERROR\", \"emitted_at\": 1666498485719.954, \"error\": {\"message\": \"Something went wrong in the connector. See the logs for more details.\", \"internal_message\": \"2 validation errors for ConfiguredAirbyteCatalog\\nstreams -> 0 -> sync_mode\\n  value is not a valid enumeration member; permitted: 'full_refresh', 'incremental' (type=type_error.enum; enum_values=[<SyncMode.full_refresh: 'full_refresh'>, <SyncMode.incremental: 'incremental'>])\\nstreams -> 0 -> destination_sync_mode\\n  value is not a valid enumeration member; permitted: 'append', 'overwrite', 'append_dedup' (type=type_error.enum; enum_values=[<DestinationSyncMode.append: 'append'>, <DestinationSyncMode.overwrite: 'overwrite'>, <DestinationSyncMode.append_dedup: 'append_dedup'>])\", \"stack_trace\": \"Traceback (most recent call last):\\n  File \\\"/airbyte/integration_code/main.py\\\", line 13, in <module>\\n    launch(source, sys.argv[1:])\\n  File \\\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\\\", line 131, in launch\\n    for message in source_entrypoint.run(parsed_args):\\n  File \\\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\\\", line 119, in run\\n    config_catalog = self.source.read_catalog(parsed_args.catalog)\\n  File \\\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/source.py\\\", line 90, in read_catalog\\n    return ConfiguredAirbyteCatalog.parse_obj(self.read_config(catalog_path))\\n  File \\\"/usr/local/lib/python3.9/site-packages/pydantic/main.py\\\", line 521, in parse_obj\\n    return cls(**obj)\\n  File \\\"/usr/local/lib/python3.9/site-packages/pydantic/main.py\\\", line 341, in __init__\\n    raise validation_error\\npydantic.error_wrappers.ValidationError: 2 validation errors for ConfiguredAirbyteCatalog\\nstreams -> 0 -> sync_mode\\n  value is not a valid enumeration member; permitted: 'full_refresh', 'incremental' (type=type_error.enum; enum_values=[<SyncMode.full_refresh: 'full_refresh'>, <SyncMode.incremental: 'incremental'>])\\nstreams -> 0 -> destination_sync_mode\\n  value is not a valid enumeration member; permitted: 'append', 'overwrite', 'append_dedup' (type=type_error.enum; enum_values=[<DestinationSyncMode.append: 'append'>, <DestinationSyncMode.overwrite: 'overwrite'>, <DestinationSyncMode.append_dedup: 'append_dedup'>])\\n\", \"failure_type\": \"system_error\"}}}\n"}}

 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestBasicRead.test_airbyte_trace_message_on_failure[inputs0] ✓                                                                                                      87% ████████▊ {"type": "LOG", "log": {"level": "WARN", "message": "Unable to parse connector's output state is updated!\n, error: 1 validation error for AirbyteMessage\n__root__\n  Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=state is updated!\n; pos=0; lineno=1; colno=1)"}}
{"type": "LOG", "log": {"level": "WARN", "message": "Unable to parse connector's output state is updated!\n, error: 1 validation error for AirbyteMessage\n__root__\n  Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=state is updated!\n; pos=0; lineno=1; colno=1)"}}
{"type": "LOG", "log": {"level": "WARN", "message": "Unable to parse connector's output state is updated!\n, error: 1 validation error for AirbyteMessage\n__root__\n  Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=state is updated!\n; pos=0; lineno=1; colno=1)"}}
{"type": "LOG", "log": {"level": "WARN", "message": "Unable to parse connector's output state is updated!\n, error: 1 validation error for AirbyteMessage\n__root__\n  Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=state is updated!\n; pos=0; lineno=1; colno=1)"}}

 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_full_refresh.py::TestFullRefresh.test_sequential_reads[inputs0] ✓                                                                                                            90% █████████ {"type": "LOG", "log": {"level": "WARN", "message": "Unable to parse connector's output state is updated!\n, error: 1 validation error for AirbyteMessage\n__root__\n  Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=state is updated!\n; pos=0; lineno=1; colno=1)"}}
{"type": "LOG", "log": {"level": "WARN", "message": "Unable to parse connector's output state is updated!\n, error: 1 validation error for AirbyteMessage\n__root__\n  Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=state is updated!\n; pos=0; lineno=1; colno=1)"}}
{"type": "LOG", "log": {"level": "WARN", "message": "Unable to parse connector's output state is updated!\n, error: 1 validation error for AirbyteMessage\n__root__\n  Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=state is updated!\n; pos=0; lineno=1; colno=1)"}}

 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py::TestIncremental.test_two_sequential_reads[inputs0] ✓                                                                                                         94% █████████▍{"type": "LOG", "log": {"level": "WARN", "message": "Unable to parse connector's output state is updated!\n, error: 1 validation error for AirbyteMessage\n__root__\n  Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=state is updated!\n; pos=0; lineno=1; colno=1)"}}
{"type": "LOG", "log": {"level": "WARN", "message": "Unable to parse connector's output state is updated!\n, error: 1 validation error for AirbyteMessage\n__root__\n  Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=state is updated!\n; pos=0; lineno=1; colno=1)"}}
{"type": "LOG", "log": {"level": "WARN", "message": "Unable to parse connector's output state is updated!\n, error: 1 validation error for AirbyteMessage\n__root__\n  Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=state is updated!\n; pos=0; lineno=1; colno=1)"}}

 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py::TestIncremental.test_read_sequential_slices[inputs0] ✓                                                                                                       97% █████████▋{"type": "LOG", "log": {"level": "WARN", "message": "Unable to parse connector's output state is updated!\n, error: 1 validation error for AirbyteMessage\n__root__\n  Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=state is updated!\n; pos=0; lineno=1; colno=1)"}}

 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py::TestIncremental.test_state_with_abnormally_large_values[inputs0] ✓                                                                                          100% ██████████
{"type": "LOG", "log": {"level": "INFO", "message": "/Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-auth0 - SAT run - 6445d04719397fefe5a4138a909ded8f198ba956 - PASSED"}}

=============================================================================================================================== warnings summary ===============================================================================================================================
airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py: 24 warnings
airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_full_refresh.py: 1 warning
airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py: 3 warnings
  /Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-auth0/.venv/lib/python3.9/site-packages/docker/utils/utils.py:52: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    s1 = StrictVersion(v1)

airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py: 24 warnings
airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_full_refresh.py: 1 warning
airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py: 3 warnings
  /Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-auth0/.venv/lib/python3.9/site-packages/docker/utils/utils.py:53: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    s2 = StrictVersion(v2)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================================================================================================================== short test summary info ============================================================================================================================
SKIPPED [1] ../../bases/source-acceptance-test/source_acceptance_test/tests/test_core.py:51: The previous connector image could not be retrieved.
SKIPPED [1] ../../bases/source-acceptance-test/source_acceptance_test/tests/test_core.py:229: The previous connector image could not be retrieved.

Results (26.41s):
      29 passed
       2 skipped

</details>

### CODE REVIEW

**Comment by YiyangLi** [comment]
Test summary info:
```
Could not find result summary
```

I don't think there's an integration setup for Auth0. @sajarin do you know the process? I have a test account, and I can invite the integration test email to the account, grant the account a super admin role and share with you the config.json for the integration tests.

**Comment by YiyangLi** [comment]
@sajarin , Marcos activated the auth0 account for integration tests in CI. But the tests still fail. Can you help? I shared the credentials with you via LastPass. It's nothing but the config.json used to run the acceptance tests, the json contains client id and client secret for the OAuth2.

**Review by sajarin — APPROVED** [review]

**Comment by sajarin** [comment]
Thanks @YiyangLi for the PR and @koconder for the review!

**Pull request merged**
