### PR TITLE
Source Stripe: Update expected records

### PR DESCRIPTION
**Pull request by pnilan**
## What

Updates to Stripe's expected records and acceptance-test-config.yaml file. Removed the "extra_fields", "exact_order", and "extra_records" references in the acceptance test config file. Default values were used. Note that the values should be boolean.

### CODE REVIEW

**Review by lazebnyi — APPROVED** [review]
lgtm

**Comment by katmarkham** [comment]
@girarda can you take a look? I know you guys are doing things with Stripe and I don't want to merge anything without your knowledge

**Review by girarda — APPROVED** [review]
do we know why there's a new record in the dataset? is that intentional?

**Comment by pnilan** [comment]
> do we know why there's a new record in the dataset? is that intentional?

Unclear but it looks like it may stem from PR #31553 on Oct 19 where the initial seed data disappeared/was replaced.

**Review by katmarkham — APPROVED** [review]

**Pull request merged**
