### PR TITLE
:bug: Source Gitlab: disallow http in cloud, disallow endpoints in URLs

### PR DESCRIPTION
**Pull request by davydov-d**
## What
Partially revert version 1.0.4, which allows URLs in the input config like `http://gitlab.com`, `gitlab.com/api/v4`. We can not allow bare http requests in cloud as well as storing URLs including path, this can break compatibility with OAuth flow implementation and bring in inconsistency in case we decide to upgrade the connector in the future and make in utilize more recent api versions.

## How
- Validate input config: URL should not start with `http` if it is a cloud env
- Validate input config: URL should not contain path
- Do not use urlparse. It only works as expected if the input URL contains scheme

### CODE REVIEW

**Review by lazebnyi — APPROVED** [review]

**Comment by davydov-d** [comment]
:point_up: tests were successful, only the "http" QA check failed, but this is due to a deliberate code change

**Comment by octavia-squidington-iii** [comment]
##  source-gitlab test report (commit [`4ede6bad99`](https://github.com/airbytehq/airbyte/pull/27346/commits/4ede6bad999d2263f76290f2e098a3d1e021522b)) - ❌

⏲️  Total pipeline duration: 973 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-gitlab/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ❌        |
| Connector package install                                            | ✅        |
| Build source-gitlab docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5270785626)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Comment by octavia-squidington-iii** [comment]
##  source-gitlab test report (commit [`40f1da60c9`](https://github.com/airbytehq/airbyte/pull/27346/commits/40f1da60c9ed8e8f23fc23eb536c3917adb1ecce)) - ❌

⏲️  Total pipeline duration: 784 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-gitlab/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ❌        |
| Connector package install                                            | ✅        |
| Build source-gitlab docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5275428590)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Comment by octavia-squidington-iii** [comment]
##  source-gitlab test report (commit [`3fb5cdc2b9`](https://github.com/airbytehq/airbyte/pull/27346/commits/3fb5cdc2b9aa40b710d743dd4e698f81c585c890)) - ✅

⏲️  Total pipeline duration: 887 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-gitlab/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-gitlab docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5276219812)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Pull request merged**
