### PR TITLE
Allow schema name null

### PR DESCRIPTION
**Pull request by xiaohansong**
## What
Some DB (mysql) does not have this field and tend to ignore schema_pattern when requested. It'll use catalog instead. Thus, this PR tries to make the query as an open function and remove restriction for null check of schema name in result set.

I'm not sure how this delegate pattern works! All I want is to tweak a little bit on jdbc getTable query so I feel inheritance may work better? 

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by postamar — CHANGES_REQUESTED** [review]
The way to implement this change is to implement something like this in source-mysql-v2:
```kotlin

class MySqlMetadataQuerier(
  val delegate: JdbcMetadataQuerier,
) : MetadataQuerier by delegate {

   ...

   @Singleton
   @Primary
   class Factory( ... ) : JdbcMetadataQuerier.Factory {
...
   } 
}
```

Look at what oracle does for inspiration. The answer, in any case, does not involve open classes and abstract methods.

**Comment by xiaohansong** [comment]
@postamar thanks! I think I get the principle of this pattern. In that case I can just overwrite streamNames instead.

**Comment by postamar** [comment]
I just had another idea: we can make the CDK's JdbcMetadataQuerier configurable. This might be preferable, as this problem might reoccur for other databases. I'll whip up a PR.

**Comment by postamar** [comment]
See https://github.com/airbytehq/airbyte/pull/44767 for something which might actually be preferable to what I suggested last week. Apologies for the confusion!

**Pull request closed without merging**
