### PR TITLE
🐛 Source Hubspot : Fix engagements streams associations configurations

### LINKED ISSUE #43352: 🐛 [source-hubspot] Engagements associations not retrieved in Incremental sync
### Connector Name

source-hubspot

### Connector Version

4.2.14

### What step the error happened?

During the sync

### Relevant information

Hello 👋 

We are currently using Hubspot source connector `v4.2.14` to retrieve distinct `Engagements` via their respective streams (ie `Engagements calls`, `Engagements emails`, etc) in `Incremental` to GCS:

Capture d’écran 2024-08-07 à 10 44 15

---
We launched 2 sync:
1. First incremental sync, starting from `2024-08-01T00:00:00Z`, with empty connector `state` => very long to run: >10 hours
2. Second incremental sync, forcing the connector `state` to start from `2024-08-01T00:00:00Z` for each stream (
[cf connection-state.json](https://github.com/user-attachments/files/16520949/connection-state.json)) in order to extract and compare same data scopes => quite fast to run: 15 min

Capture d’écran 2024-08-07 à 11 31 23

---
We observed below results in output (read via BigQuery external table over the AVRO GCS files):
Capture d’écran 2024-08-07 à 10 54 28

---
**⚠️ Issues identified**:
1. the `Companies` field is properly retrieved for the First incremental sync (row 1) BUT **wrongly empty** for the Second incremental sync (row 2)
2. above issue is the same:
- for `Contacts` and `Deals` associations also
- over **all** `Engagements` objects types (calls, meetings, notes, emails, tasks)
3. I also noticed in the stream logs a `schema validation error` specific to the `contacts` (eg: ```Schema validation errors found for stream _engagements_meetings. Error messages: [$.contacts[2]: integer found, [null, string] expected, $.contacts[1]: integer found, [null, string] expected, $.contacts[0]: integer found, [null, string] expected]```)
 
**Complementary question**: why is first sync so long ?

---
**Hypothesis**: there is a difference [if state is set or not](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py#L1184) at associations reading time, leading to using `_read_associations` VS `_flat_associations` methods (as `EngagementsXxx` inherits from `CRMSearchStream`)

NB: [according to the doc](https://docs.airbyte.com/integrations/sources/hubspot#notes-on-the-engagements-stream), the `EngagementsAll` and `EngagementsRecent` Python classes are not used for the specific engagements streams.

Thank you for your help 🙏 

### Relevant log output

Full Airbyte logs to debug the 3 issues:
- [first incremental sync](https://github.com/user-attachments/files/16520977/default_workspace_logs_239_txt.txt)
- [second incremental sync](https://github.com/user-attachments/files/16520978/default_workspace_logs_242_txt.txt)

### Contribute

- [x] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by kev-datams**
## What
Partially fixes https://github.com/airbytehq/airbyte/issues/43352
-> if `state` is filled, the `Incremental` sync was not properly retrieving `Deals` and `Companies` associations for all `Engagements` specific streams (emails, calls, meetings, tasks, notes).

NB: it will not solve the third point: `I also noticed in the stream logs a schema validation error specific to the contacts (eg: Schema validation errors found for stream _engagements_meetings. Error messages: [$.contacts[2]: integer found, [null, string] expected, $.contacts[1]: integer found, [null, string] expected, $.contacts[0]: integer found, [null, string] expected])`
=> perhaps adding a `str()` somewhere in the code ? 🤔 

## How
Fix the `associations` configuration of `EngagementsXxx` Python classes to use plural (the same way it was used for `Contacts` that properly worked)

## Review guide
- `stream.py` is the only impacted file

## User Impact
Collected data quality improved ❤️ 

## Can this PR be safely reverted and rolled back?
- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by aldogonzalez8** [comment]
@kev-datams The Changes make sense to me. I just wanted to check the regression results, but we have some problem rendering them for now. I will check if I can get that fixed.

In the meantime, some unit tests are broken, probably because of the change In the requests. Can you take a look at those?

image

**Comment by aldogonzalez8** [comment]
> @kev-datams The Changes make sense to me. I just wanted to check the regression results, but we have some problem rendering them for now. I will check if I can get that fixed.
> 
> In the meantime, some unit tests are broken, probably because of the change In the requests. Can you take a look at those?
> 
> image

Also please when fixing the test rebase from master, seems is what we need to have regression working on the branch. Thanks!

**Comment by kev-datams** [comment]
Hi @aldogonzalez8,
Just fixed the unit tests, no remaining failure right now 👍 
Also rebased from master as requested
Please could you have a look and accept/merge ASAP ? 🙏 

NB: any idea about the complementary fix on the "third point" of the issue ?

**Comment by aldogonzalez8** [comment]
There was a problem in unit tests unrelated to your changes that I just fixed. Can you please rebase from master again? I will rerun tests after that.

**Comment by kev-datams** [comment]
> Hi @kev-datams,  there was a problem in unit tests unrelated to your changes that I just fixed. Can you please rebase from master again? I will rerun tests after that.

Hi @aldogonzalez8, done 🙏

**Comment by aldogonzalez8** [comment]
@kev-datams I was just informed that regression won't work in the CI process for a fork, but I can clone your repository locally and run regression from here. Your changes seem pretty straightforward, but I want to be sure. I will get back to you on this.

**Comment by kev-datams** [comment]
> @kev-datams I was just informed that regression won't work in the CI process for a fork, but I can clone your repository locally and run regression from here. Your changes seem pretty straightforward, but I want to be sure. I will get back to you on this.

@aldogonzalez8, do you know if there is any alternative on our side to save time for future PR and limit workload on your side?

but OK, waiting for your confirmation to merge 🙏

**Comment by aldogonzalez8** [comment]
Sorry for the delay, I can see your changes in the regressions report, and the response data seems now contain info related to the request :)

image

**Review by aldogonzalez8 — APPROVED** [review]
APPROVED

**Comment by kev-datams** [comment]
> APPROVED

thanks @aldogonzalez8 🔥 
what is the next step to merge it and generate the updated connector ?

**Comment by aldogonzalez8** [comment]
If squash and merge available for you? If not, maybe it is something I have to push.

**Comment by kev-datams** [comment]
> If squash and merge available for you? If not, maybe it is something I have to push.

image
Unfortunately, I am not granted...

**Comment by aldogonzalez8** [comment]
Ok, I just merged, the new version should be available in a few minutes.

**Comment by kev-datams** [comment]
Thanks a lot !

**Pull request merged**
