### PR TITLE
🪟 Add Segment event for 'Buy Credits'

### PR DESCRIPTION
**Pull request by dizel852**
## What
Closes [#1863](https://github.com/airbytehq/airbyte-cloud/issues/1863)

## How
Add Segment event for 'Buy Credits'

Screenshot at Aug 05 17-23-08

### CODE REVIEW

**Comment by tealjulia** [comment]
I'd check with @nataliekwong on the wording (her issue mentioned "buy credits" but this says "proceed to checkout").  Otherwise it looks good!

**Comment by dizel852** [comment]
@nataliekwong what event name you'd prefer the most?
`Airbyte.UI.Credits.BuyCredits` or `Airbyte.UI.Credits.ProceedToCheckout` or `your option` ?

**Review by edmundito — APPROVED** [review]
The code looks good. Please wait to confirm the event names before merge.

**Comment by nataliekwong** [comment]
Hey @dizel852  - let's follow the structure that other Segment events use with [noun] [verb]. I'm not tied to "Buy Credits" as the button text could change in the future. 

My suggestion is to use: Checkout Start

**Pull request merged**
