### PR TITLE
Add METRIC_CLIENT and OTEL_COLLECTOR_ENDPOINT to .env files to fix kube deployments

### LINKED ISSUE #13796: Error: couldn't find key METRIC_CLIENT in ConfigMap airbyte/airbyte-env
Hello there! I'm following the guide at https://docs.airbyte.com/deploying-airbyte/on-kubernetes/#launch-airbyte for trying Airbyte out, but I'm facing a few missing keys for the ConfigMap `airbyte-env`:

- `METRIC_CLIENT` (this was the first one)
- `OTEL_COLLECTOR_ENDPOINT`

## Environment
- **Airbyte version**:  0.39.18-alpha
- **OS Version / Instance**: Ubuntu Focal
- **Deployment**: I've just followed the guide mentioned, but modified kustomization for different namespace
- **Step where error happened**: Deployment

## Current Behavior
Worker wouldn't deploy as those keys were missing

It seems that there were missing two entries on the `.env` file at `kube/overlays/stable/`:

```
METRIC_CLIENT=
OTEL_COLLECTOR_ENDPOINT=
```

After adding those, worker is successfully deployed.

### PR DESCRIPTION
**Pull request by lmossman**
## What
Resolves https://github.com/airbytehq/airbyte/issues/13796

[This PR](https://github.com/airbytehq/airbyte/pull/13701) added the `METRIC_CLIENT` and `OTEL_COLLECTOR_ENDPOINT` env vars to the airbyte worker deployment manifest, but it did not add the default empty values to the various `.env` files in the kube overlays. 

This means anyone trying to deploy airbyte on kube on the most recent version will run into errors like the following in the airbyte worker (see this issue as an example: https://github.com/airbytehq/airbyte/issues/13796):
```
  Warning  Failed     7m16s (x12 over 9m29s)  kubelet            Error: couldn't find key METRIC_CLIENT in ConfigMap default/airbyte-env-cftc4t5587
```

## How
This PR fixes the issue by adding default blank values to the various `.env` files, which should allow worker pods to be successfully created with these default values.

### CODE REVIEW

**Review by xiaohansong — APPROVED** [review]
thanks for the fix!

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Comment by yiyangli-heap** [comment]
Is it okay to sync the environment variables to the helm charts as well? 

I tried to upgrade the version, and metrics from datadog are gone, I was blocked for hours until I realized the required field. 

https://github.com/heap/airbyte/commit/26c86a04527562987508f7fd0c67b0e172db08d2#diff-6f2647f2aed4a58e6f608dc5f977d94e39e237dd313adc6de33e66b8ced6482dR79

**Comment by xiaohansong** [comment]
Hi! Thanks for your message. Sorry about that!

Are you suggesting we set the default value of `METRIC_CLIENT` to datadog? The reason I left it empty is to make sure people who don't setup any monitoring could still use airbyte without some weird error messages.

https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/templates/env-configmap.yaml#L56

**Pull request merged**
