### PR TITLE
destination-s3-glue: Add stringify option for nested objects in JSON Lines output

### PR DESCRIPTION
**Pull request by quazi-h**
## What
*When creating JSON Lines output using the S3 Glue connector, nested JSON objects are not being escaped as strings, causing issues downstream when attempting to query the data in the object.*

## How
*We have added an option to the JSONL serialization that will serialize nested documents as strings in the output before they are written to the s3-glue destination.*

## Recommended reading order
1. `airbyte-integrations/bases/base-java-s3/src/main/java/io/airbyte/integrations/destination/s3/jsonl/JsonLSerializedBuffer.java`
2. `airbyte-integrations/bases/base-java-s3/src/main/java/io/airbyte/integrations/destination/s3/util/Stringify.java`

## 🚨 User Impact 🚨

*This is a minor version change that adds a non-required parameter to the Destination-S3-Glue connector spec.
The additional option will be visible in the connector settings under the "Output Format" options.
Users will have the option to use the required parameter in the future.
This should not affect any existing implementations of the S3 Glue connector because the default setting for this option will be not stringifying nested objects - preserving existing functionality.*

## Pre-merge Checklist
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Connector version is set to `0.1.8`
    - [x] `Dockerfile` has version `0.1.8`
- [ ] Documentation updated
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing) (THIS LINK NEEDS TO BE UPDATED)
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Connector version has been incremented
    - [x] Version has been bumped according to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines
    - [x] `Dockerfile` has updated version
- [ ] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` with an entry for the new version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)

- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

### CODE REVIEW

**Comment by quazi-h** [comment]
Update: Tobias was able to update our connector in QA to include the changes in this branch without hitting the spec issue I was seeing previously. This branch still needs more work because objects are still not being escaped properly. I will update here once those changes have been made and the appropriate tests have been added. Thank you.

**Comment by blarghmatey** [comment]
@marcosmarxm this is ready to review if you have the time. We have successfully run this through an end-to-end validation flow in our self-managed instance of Airbyte.

**Comment by marcosmarxm** [comment]
@quazi-h can you check the commits and make the PR is even with main branch?

**Comment by marcosmarxm** [comment]
@quazi-h can you make sure to delete all files won't exist in main branch anymore?

**Comment by quazi-h** [comment]
> @quazi-h can you make sure to delete all files won't exist in main branch anymore?

@marcosmarxm We have removed the extra file (airbyte-config-oss/init-oss/src/main/resources/seed/oss_catalog.json).
Please let us know if there's anything else we should address. Thanks!

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
@quazi-h the pull request is doing two changes one for the base java s3 which will touch a GA connector (destination-s3) and destination-s3-glue. Can we break the changes into two PR. 
1. doing the base change I'll ask the destination team to review and approve them
2. the change to the destination s3 glue connector with the previous one accepted.

**Comment by quazi-h** [comment]
Hi Marcos, I have broken this larger PR into two new ones for each connector.
Destination S3 changes: https://github.com/airbytehq/airbyte/pull/27129
Destination S3 Glue changes: https://github.com/airbytehq/airbyte/pull/27134

**Pull request closed without merging**
