### PR TITLE
Source acceptance test: bugfix

### PR DESCRIPTION
**Pull request by davydov-d**
## What
- change `latest_state` to `stream_name_to_per_stream_state` in `get_next_state_input` so that returned input state is not the same each time the function is called
- remove `latest_state` from `get_next_state_input` args as it is no more used
- simplify building checkpoint message groups as the record messages are not used as well

### CODE REVIEW

**Review by arsenlosenko — APPROVED** [review]

**Review by brianjlai — APPROVED** [review]
changes look good. but let's run this against a couple more different connector just to verify no regressions. Hubspot is an especially good one because some streams have enough records to result in multiple slices in a sync.

**Comment by davydov-d** [comment]
builds passed, except for tiktok (failed due to timeout), so I'm publishing this change

**Comment by davydov-d** [comment]
/publish connector=bases/source-acceptance-test auto-bump-version=false

**Comment by davydov-d** [comment]
/publish connector=bases/source-acceptance-test auto-bump-version=false

**Comment by davydov-d** [comment]
/publish connector=bases/source-acceptance-test auto-bump-version=false

**Comment by davydov-d** [comment]
/publish connector=bases/source-acceptance-test auto-bump-version=false

**Comment by davydov-d** [comment]
/publish connector=bases/source-acceptance-test auto-bump-version=false

**Comment by davydov-d** [comment]
/publish connector=bases/source-acceptance-test auto-bump-version=false

**Pull request merged**
