### PR TITLE
source-zoho-campaign contribution from bishalbera

### LINKED ISSUE #46094: [connector-request] Zoho Campaigns
This is a **suggestion** to create a connector for **Zoho Campaigns** using the UI Connector Builder.
The website for the connector is https://www.zoho.com/campaigns.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

### PR DESCRIPTION
**Pull request by bishalbera**
## What
Closes #46094 

This PR adds a new connector for source Zoho Campaign (source-zoho-campaign).

Contributor-provided connector description:

The Zoho Campaigns connector enables seamless integration of mailing lists, campaign data, and subscriber management into your data workflows. Easily extract subscriber information, campaign reports, and list details to sync with your data warehouse or BI tools, automating marketing insights and analytics
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `client_id_2` | `string` | Client ID.  |  |
| `client_secret_2` | `string` | Client secret.  |  |
| `client_refresh_token` | `string` | Refresh token.  |  |
| `domain` | `string` | Domain.  |  |
| `campaign_recipients_data_action` | `string` | Campaign Recipients Data Action.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| campaigns | campaign_key | No pagination | ✅ |  ❌  |
| subscribers | contact_email | No pagination | ✅ |  ❌  |
| lists | listkey | No pagination | ✅ |  ❌  |
| campaignrecipients | contactid | No pagination | ✅ |  ❌  |
| campaignreports | campaign_name | No pagination | ✅ |  ❌  |
| recentcampaigns | campaign_key | No pagination | ✅ |  ❌  |
| recentsentcampaigns | campaign_key | No pagination | ✅ |  ❌  |
| mailinglists | listunino | No pagination | ✅ |  ❌  |
| totalcontacts |  | No pagination | ✅ |  ❌  |
| topics | topicId | No pagination | ✅ |  ❌  |
| campaigndetails | campaign_name | No pagination | ✅ |  ❌  |
| alltags |  | No pagination | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
`Domain` change to `Data Center` and make this a enum type and add all options available.

Some streams like `mailinglists` are missing pagination.

It is really important to make sure the endpoint `/recentcampaigns` captures all campaigns. Can you add at least 7+ and try to simulate pagination?

> Using this API, you can see the details of the five most recent campaigns that has been created in your organization.



`campaigns` and `recentcampaigns` are identifical, please remove recent campaigns.

**Comment by marcosmarxm** [comment]
Hello 👋 Due to the numerous contributions happening, I decided to create this [view](https://github.com/orgs/airbytehq/projects/104/views/3) to help you know when I plan to review your contribution. If your connector has some limited-time credential feel free to reach me out.

**Comment by marcosmarxm** [comment]
@bishalbera did you check my last review?

**Comment by marcosmarxm** [comment]
Move date to next review to 4-Nov.

**Comment by bishalbera** [comment]
> @bishalbera did you check my last review?

campaign and mailinglists are causing some issue when I'm applying pagination. some other streams are linked to campaign so they are also giving warnings @marcosmarxm

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
