### PR TITLE
Make publish command work with private repos by adding JWT into curl headers

### LINKED ISSUE #12584: The publish command no longer works for private docker repository
## Current Behavior
- In https://github.com/airbytehq/airbyte/pull/11654, a tag check was introduced to the publish command.
- However, the URL does not work for private connector like `destination-databricks.

## Expected Behavior
- The publish command should work for private connectors as well.

## Logs
https://github.com/airbytehq/airbyte/runs/6294841743?check_suite_focus=true
```
+ TAG_URL=https://hub.docker.com/v2/repositories/airbyte/destination-databricks/tags/0.1.5
++ curl --silent --output /dev/null --write-out '%***http_code***' https://hub.docker.com/v2/repositories/airbyte/destination-databricks/tags/0.1.5
+ DOCKERHUB_RESPONSE_CODE=404
+ [[ 404 == \4\0\4 ]]
+ echo 'Tag 0.1.5 was not registered on DockerHub for image airbyte/destination-databricks, please try to bump the version again.'
+ exit 1
Tag 0.1.5 was not registered on DockerHub for image airbyte/destination-databricks, please try to bump the version again.
Error: Process completed with exit code 1.
```

## Potential Solution
- Solution 1. Use a URL that works for private repositories as well.
- Solution 2. Add a `skip-tag-check` parameter to bypass the tag check.

### PR DESCRIPTION
**Pull request by noahkawasaki-airbyte**
## What
Make private docker images work in the publish command by getting a docker token back and adding it into the curl command. The docker login command that runs in the GHA beforehand doesnt seem to provide the auth needed.

Here's logs showing this worked on an image I created manually to test this out

```
+ image_name=airbyte/private-repo-test
+ image_version=0.1.0
+ TAG_URL=https://hub.docker.com/v2/repositories/airbyte/private-repo-test/tags/0.1.0
++ curl --silent --output /dev/null --write-out '%***http_code***' -H 'Authorization: JWT *****' https://hub.docker.com/v2/repositories/airbyte/private-repo-test/tags/0.1.0
+ DOCKERHUB_RESPONSE_CODE=200
+ [[ 200 == \4\0\4 ]]
```

Ran here: https://github.com/airbytehq/airbyte/actions/runs/2379418746

Closes #12584

## How
*Describe the solution*

### CODE REVIEW

**Comment by noahkawasaki-airbyte** [comment]
/publish connector=connectors/destination-snowflake run-tests=false

**Comment by noahkawasaki-airbyte** [comment]
/publish connector=connectors/destination-snowflake run-tests=false

**Review by tuliren — APPROVED** [review]
Nice!

What private connector images do we have? I thought we don't have one anymore after Databricks has been made public.

**Comment by noahkawasaki-airbyte** [comment]
I just manually made one called `private-repo-test` for the sake of testing. Not sure how many connectors are private, just saw the ticket and it looked like a quick thing so I took it lol

**Pull request merged**
