### PR TITLE
Jira Source: Added resolutiondate to fields on issues stream 

### PR DESCRIPTION
**Pull request by Mainara**
## What
This PR solves the problem of mapping the date and time when an issue was completed, which is extremely important for projects that use Airbyte to pull data from Jira and monitor the progress of activities.

## How
I added the resolutiondate field in the `fields` object present in the stream `issues`,

## Recommended reading order
1. `x.java`
2. `y.python`

## User Impact
There is no breakchanges, just more information being returned in the stream `issues`.

## Pre-merge Checklist

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@Mainara thanks, can you sign the CLA and bump the Dockerfile version?

**Review by marcosmarxm — APPROVED** [review]

**Comment by Mainara** [comment]
> @Mainara thanks, can you sign the CLA and bump the Dockerfile version?

@marcosmarxm I made the changes. :smiley:

**Review by vincentkoc — APPROVED** [review]

**Comment by marcosmarxm** [comment]
/publish connector=connectors/source-mixpanel auto-bump-version=false

**Comment by marcosmarxm** [comment]
/publish connector=connectors/source-jira auto-bump-version=false

**Comment by marcosmarxm** [comment]
/publish connector=connectors/source-jira auto-bump-version=false

**Pull request merged**
