### PR TITLE
Source Intercom: Migrate to manifest only format with components

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
Closes https://github.com/airbytehq/airbyte-internal-issues/issues/11089
Source Intercom: Migrate to manifest-only formats with components

## How
Migrated to inline schemas
Migrated spec
Migrated to manifest only with ci

## Migration report
image

### CODE REVIEW

**Review by ChristoGrab — CHANGES_REQUESTED** [review]
@btkcodedev Danylo and I were going over the changes and it does seem like streams which were previously reading successfully are now throwing 422 errors (company_attributes stream is an example). I recommend running the connector locally to test it out, it's possible the issue is with the custom component code not functioning after the CDK upgrade, we may need to make some updates. Let us know if you have any trouble with testing!

**Comment by btkcodedev** [comment]
@ChristoGrab I've made some changes and tested the streams in local, removed some unwanted parameters and fully revised code to new version
Errors cleared!

**Comment by ChristoGrab** [comment]
@btkcodedev Looks like we're getting very close! CAT tests show both the incremental substreams (conversation_parts and company_segments) failing on the future-state test. Looking at the abnormal_state file, I think part of the issue might just be with the way the state object is constructed. Since they're substreams, I would expect the state object to use per-partition states, and look something like:

```
  {
    "type": "STREAM",
    "stream": {
      "stream_descriptor": {
        "name": "company_segments"
      },
      "stream_state": {
        "states": [
          {
            "partition": {
              "id": "<some_parent_id>",
              "parent_slice": {}
            },
            "cursor": {
              "updated_at": 9626086649
            }
          },
          {
            "partition": {
              "id": "<some_other_parent_id>",
              "parent_slice": {}
            },
            "cursor": {
              "updated_at": 9626086649
            }
          }
        ]
      }
    }
  }    
```

Trying to get a round of regression tests kicked off so I can verify the behavior, in the meantime this is probably a good starting point to investigate to make sure the tests are giving us accurate results

**Comment by btkcodedev** [comment]
@ChristoGrab, I am out of ideas about abnormally large state errors,
Could you help me to debug and tell which things could go wrong

**Comment by btkcodedev** [comment]
If the `IncrementalSubstreamSlicerCursor` component is present, the `company_segments` streams do not receive any data, but if it's changed to `IncrementalSingleSliceCursor`, it receives a response but does not pass the future state.
Please comment your thoughts on debug

**Comment by btkcodedev** [comment]
@ChristoGrab Necessary tests passed with Intercom, 
Please continue review
I think its ready.

**Comment by btkcodedev** [comment]
Aha, We've got an interesting condition here @ChristoGrab.
If we change the base image to 6.10.0, Then unit tests are passing, but the incremental sync is failing while checking in abnormal values
Conversely, if the base image is 5.14.0, then acceptance tests and abnormal large value checks are passing, but the unit tests fail. :smile_cat: 

So my opinion is to remove the unit tests as it is purely manifest with components right now.

**Comment by ChristoGrab** [comment]
@btkcodedev Taking a look! You're right, and I think the issue may be that we switched to using concurrent reads in CDK 6 by default, which may have an impact on incremental substream behavior. I commented out the unit tests for now, running a fresh round of tests to verify.

**Review by ChristoGrab — APPROVED** [review]
Marking as a release candidate for progressive rollout. Thanks for your hard work @btkcodedev!

**Comment by btkcodedev** [comment]
Continued in https://github.com/airbytehq/airbyte/pull/49936

**Pull request merged**
