### PR TITLE
🚨Source Outbrain Amplify: Migrate to poetry

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
Migrating to poetry

## Can this PR be safely reverted and rolled back?
- [x] YES 💚

### CODE REVIEW

**Comment by btkcodedev** [comment]
Currently the CDK is set <1, to make the CI pass, It will fail due to deprecated authenticators with version above 1, We can fix it  with another PR

**Comment by btkcodedev** [comment]
@ChristoGrab All checks passed

**Comment by btkcodedev** [comment]
@ChristoGrab, is everything fine for this?

**Comment by ChristoGrab** [comment]
@btkcodedev Sorry for the delay; our sandbox creds are expired and I can't log in to the account, so I tried running regression tests against a live connection. No data was being fetched, but according to the tests this was also true when running the existing connector. So even though I can't fully verify the connector works I don't have any reason to believe we've broken anything 😅 

@natikgadzhi I'm of the opinion we merge since this is not a high-use connector and I have no evidence we've broken anything that works, any objections? [Link to regression test results](https://github.com/airbytehq/airbyte/actions/runs/9847252572/job/27225601974)

**Review by natikgadzhi — APPROVED** [review]
@ChristoGrab feel free to approve those yourself, too!

**Pull request merged**
