### PR TITLE
[ISSUE #35112] clean acceptance-test-config.yml

### PR DESCRIPTION
**Pull request by maxi297**
## What
Clean up following https://github.com/airbytehq/airbyte-internal-issues/issues/6376 and https://github.com/airbytehq/airbyte-internal-issues/issues/6377

### extra_records
`for file in source-*/acceptance-test-config.yml; sed -i '' '/extra_records/d' $file`

### extra_fields
`for file in source-*/acceptance-test-config.yml; sed -i '' '/extra_fields/d' $file`

### basic_read.ignored_fields
Manual clean up after identification using this script:
```
import glob
import yaml


def _get_ignored_fields(test):
    ignored_fields_by_config_path = {}
    for test in test_config.get("acceptance_tests", {}).get(test, {}).get("tests", []):
        if test.get("ignored_fields"):
            ignored_fields_by_config_path[test.get("config_path", "secrets/config.json")] = test.get("ignored_fields")
    return ignored_fields_by_config_path


to_clean_up = []
for file_name in glob.glob("source-*/acceptance-test-config.yml"):
    with open(file_name) as file:
        test_config = yaml.safe_load(file)
        basic_read_ignored_fields = _get_ignored_fields("basic_read")
        if basic_read_ignored_fields:
            to_clean_up.append(file_name)

print(to_clean_up)
print(len(to_clean_up))
```

## 🚨 User Impact 🚨
None as these fields shouldn't be use. The clean up will remove confusion

### CODE REVIEW

**Review by girarda — APPROVED** [review]

**Review by bazarnov — APPROVED** [review]
LGTM

**Review by octavia-approvington — APPROVED** [review]

**Comment by octavia-approvington** [comment]
This looks fine!  <br/> Merged! <br/> Imagine it being fine

**Comment by natikgadzhi** [comment]
@maxi297 can you pretty please also update the documentation spec in https://docs.airbyte.com/connector-development/testing-connectors/connector-acceptance-tests-reference?

**Comment by maxi297** [comment]
> @maxi297 can you pretty please also update the documentation spec in https://docs.airbyte.com/connector-development/testing-connectors/connector-acceptance-tests-reference?
> 
> One sec, I'll extract this into a separate issue.

Some documentation has been updated as part of https://github.com/airbytehq/airbyte/pull/35645. This is only the cleaning. Is there more documentation to update?

**Pull request merged**
