### PR TITLE
✨ Source Airtable: add new stream `Views`

### LINKED ISSUE #23895: Source Airtable: new stream Views
## Tell us about the problem you're trying to solve
Lists basic information of base views. [List Views](https://airtable.com/developers/web/api/list-views)

## Describe the solution you’d like
Research pros and cons for implementing this stream

### PR DESCRIPTION
**Pull request by gittysachin**
## What
Closes #23895

## Enhancement
New streams:

* Views

## Recommended reading order
1. `streams.py`
2. `source.py`

## 🚨 User Impact 🚨
No breaking changes

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by jrolom** [comment]
@marcosmarxm  can we add this PR in the review funnel please? This is @gittysachin  first contribution.

**Comment by marcosmarxm** [comment]
@archangelic will review the contribution.

**Comment by gittysachin** [comment]
@archangelic I'll try to fix the tests and will let you know in sometime.

**Comment by gittysachin** [comment]
@archangelic can you please tell how can I replicate the integration tests failure and fix those?

**Comment by marcosmarxm** [comment]
> @archangelic can you please tell how can I replicate the integration tests failure and fix those?

You can check the tests: https://connectors.airbyte.com/files/generated_reports/connector_registry_report.html

**Comment by gittysachin** [comment]
Thanks, @marcosmarxm @archangelic! Please let me know if any changes are required in the PR to fix the tests. Or, kindly inform me when the integration tests are fixed, so that the PR can be merged.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Sorry the long delay to review your PR @gittysachin CI is working again. Can you explain how this is going to work? It will generate a new table only with the metadata of lists?

**Comment by marcosmarxm** [comment]
@gittysachin there are 2 unit test failing please fix them you can run locally without integraton credentials.

**Comment by gittysachin** [comment]
@marcosmarxm I'll fix the tests.

**Pull request closed without merging**
