### PR TITLE
fix: Disable CDC checkpointing using a flag

### PR DESCRIPTION
**Pull request by sergio-ropero**
## What
There is an issue when we try to read the offset file at the same time Debezium is writing into it, making syncs to fail.

## How
We disable CDC checkpointing using a flag until we finished the investigation with reading Offset file during syncs.
Also, with this solution, it can be enabled per each connector individually, so only one connector will be impacted at the time.

## Test
Performed the following tests:
- CDC Sync from scratch: 1M records loaded
- 2nd CDC Sync: No records (no changes)
- Reset stream: Clean all statuses
- CDC Sync again: 1M records loaded

See image below:
Screenshot 2023-03-21 at 11 11 47

### CODE REVIEW

**Review by subodh1810 — APPROVED** [review]

**Comment by sergio-ropero** [comment]
> /publish connector=connectors/source-postgres
> 
> > 🕑 Publishing the following connectors:connectors/source-postgreshttps://github.com/airbytehq/airbyte/actions/runs/4478480281
> 
> 
> Connector	Did it publish?	Were definitions generated?
> connectors/source-postgres	✅	❌

Published manually

**Comment by sergio-ropero** [comment]
> /publish connector=connectors/source-mysql
> 
> > 🕑 Publishing the following connectors:connectors/source-mysqlhttps://github.com/airbytehq/airbyte/actions/runs/4478478589
> 
> 
> Connector	Did it publish?	Were definitions generated?
> connectors/source-mysql	✅	❌

Generated definitions manually

**Comment by sergio-ropero** [comment]
> /publish connector=connectors/source-mssql
> 
> > 🕑 Publishing the following connectors:connectors/source-mssqlhttps://github.com/airbytehq/airbyte/actions/runs/4478479646
> 
> 
> Connector	Did it publish?	Were definitions generated?

Published fine, Generated definitions manually

**Comment by sergio-ropero** [comment]
/publish connector=connectors/source-mssql-strict-encrypt auto-bump-version=false

**Comment by sergio-ropero** [comment]
/publish connector=connectors/source-mssql-strict-encrypt auto-bump-version=false run-tests=false

**Comment by sergio-ropero** [comment]
/publish connector=connectors/source-postgres-strict-encrypt auto-bump-version=false run-tests=false

**Pull request merged**
