### PR TITLE
📝 Updated Qdrant destination icon

### PR DESCRIPTION
**Pull request by Anush008**
## What
This PR intends to update the Qdrant destination icon with added padding to better fit the catalog card.

#### Current preview at https://airbyte.com/connectors
Screenshot 2024-02-09 at 22 12 45

### CODE REVIEW

**Review by kacperlukawski — APPROVED** [review]

**Comment by marcosmarxm** [comment]
Thanks @Anush008 I'm going to ask to our design team validate the change and if the icon follows the standard.

**Comment by Anush008** [comment]
Hi @marcosmarxm. Did you hear back from them?

**Review by marcosmarxm — APPROVED** [review]

**Comment by marcosmarxm** [comment]
Sorry for the delay folks! This is approved... talking to the team to get this updated asap.

**Comment by octavia-approvington** [comment]
Our work here is done <br/> done

**Review by octavia-approvington — APPROVED** [review]

**Comment by Anush008** [comment]
Hello guys. The icon change doesn't seem to be reflecting at https://airbyte.com/connectors.
Is this change not deployed?

**Comment by evantahler** [comment]
I think the icon will be updated on the next version bump of the connector (cc @marcosmarxm)

**Pull request merged**
