### PR TITLE
New Source: AWS Cognito (WIP)

### PR DESCRIPTION
**Pull request by Rhiyo**
Work in Progress - making a PR here so it gets attention and I'm more inclined to actual finish this.

This is something I build internally for a startup I worked with - thought I'd move it to actually be a part of the airbyte project.

It gets users from [AWS Cognito](https://aws.amazon.com/cognito/)

The streams are all user pools and the groups within those pools. Pools are separate streams as you can only find out whether a user is in a group by either listing all users in that group or looking at the user individually with a call. I thought this would be better as it gives you the option to filter for groups or pull in all groups and do a join later to see what groups the user is a part of.

To do:

- Documentation
- Incremental support (Still have to look through all users AWS side as can't filter on API calls)
- Tests

This was built on a much earlier version of Airbyte - may need some general updating as well.

### CODE REVIEW

**Comment by marcosmarxm** [comment]
At the moment the project is only accepting new sources using the low-code or the connector builder. This is a strategy to have more stable connectors are easy to maintain. You can build and use the connector for your company project or share with the community. Airbyte team is working to add more features to the builder to make possible to use and build more type of connectors in the future. Hope you understand and thanks a lot for your contribution.

**Comment by Rhiyo** [comment]
> At the moment the project is only accepting new sources using the low-code or the connector builder. This is a strategy to have more stable connectors are easy to maintain. You can build and use the connector for your company project or share with the community. Airbyte team is working to add more features to the builder to make possible to use and build more type of connectors in the future. Hope you understand and thanks a lot for your contribution.

I understand - but doesn't that make it hard for AWS services where you only have options for SDK or CLI access?

**Comment by hpereira98** [comment]
> At the moment the project is only accepting new sources using the low-code or the connector builder. This is a strategy to have more stable connectors are easy to maintain. You can build and use the connector for your company project or share with the community. Airbyte team is working to add more features to the builder to make possible to use and build more type of connectors in the future. Hope you understand and thanks a lot for your contribution.

Hey @marcosmarxm! Is this still the policy in place? I can help updating @Rhiyo's code to the latest Airbyte version, as such connectors would be a great help when setting up connections to AWS services.

**Comment by marcosmarxm** [comment]
Yes, the rule didn't change from last time.

**Pull request closed without merging**
