### PR TITLE
🐛 Source Pipedrive: update expected records

### PR DESCRIPTION
**Pull request by arsenlosenko**
## What
Fix failed CAT run for Source Pipedrive

## How
Updated expected records:
*  updated value of `order_nr` field, in stream `organization_fields`
*  new field `display_field` in stream `product_fields`

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-pipedrive test report (commit [`fc1c638f1d`](https://github.com/airbytehq/airbyte/pull/27967/commits/fc1c638f1da4f1d66cbedd8b0383d0b4846318c9)) - ✅

⏲️  Total pipeline duration: 07mn23s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-pipedrive/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-pipedrive docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Integration tests                                                       | ✅        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_source-pipedrive-fix-expected-records-05-07/1688550971/fc1c638f1da4f1d66cbedd8b0383d0b4846318c9/source-pipedrive/0.1.18/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-pipedrive test
```

**Review by lazebnyi — CHANGES_REQUESTED** [review]
Why weren't the new fields added to the schema when they were added to the stream?

**Comment by arsenlosenko** [comment]
> Why weren't the new fields added to the schema when they were added to the stream?

@lazebnyi good point, I'll add these fields to schema and request your review again

**Comment by octavia-squidington-iii** [comment]
##  source-pipedrive test report (commit [`6bee4f5d2f`](https://github.com/airbytehq/airbyte/pull/27967/commits/6bee4f5d2f0b28385bf7d8f51e1e2a0cbec750be)) - ✅

⏲️  Total pipeline duration: 05mn16s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-pipedrive/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-pipedrive docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Integration tests                                                       | ✅        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_source-pipedrive-fix-expected-records-05-07/1688558464/6bee4f5d2f0b28385bf7d8f51e1e2a0cbec750be/source-pipedrive/0.1.19/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-pipedrive test
```

**Review by lazebnyi — APPROVED** [review]

**Pull request merged**
