### PR TITLE
source-mssql: double MSSQL_MEMORY_LIMIT_MB value

### PR DESCRIPTION
**Pull request by postamar**

### CODE REVIEW

**Comment by postamar** [comment]
Looks like I've found the culprit. 
cc @rodireich @stephane-airbyte

**Review by evantahler — APPROVED** [review]
Approved for the quick fix, but... this _feels_ like another point in favor of dropping test containers... 

Also, what changed recently that the test containers need more memory?

**Review by stephane-airbyte — APPROVED** [review]

**Comment by postamar** [comment]
> Approved for the quick fix, but... this feels like another point in favor of dropping test containers...

sorry, what?

**Comment by postamar** [comment]
> Also, what changed recently that the test containers need more memory?

I think the CDC test containers in particular have always required more memory than non-CDC containers, but how we were able to set the memory cap without triggering a test failure remains a mystery to me.

**Pull request merged**
