### PR TITLE
🎉  Support FB Marketing API v10

### LINKED ISSUE #2230: Support FB Marketing API v10
## Tell us about the problem you're trying to solve
For a user to use Airbyte's FB connector, they need to create a FB app. Access tokens generated from FB Apps can only be used with the latest API version present at the time of creating the FB app. 

Facebook just released [v10 of the marketing API](https://developers.facebook.com/docs/graph-api/changelog/version10.0#graph-api), and a user just reported being unable to use the FB connector since their app only supports v10. 

We should upgrade to FB marketing API v10 so we do not have this issue. We should verify that apps were initialized on older API versions will not be impacted.

### PR DESCRIPTION
**Pull request by yevhenii-ldv**
## What
*update facebook_business version to 10.0.0 with Graph API v10.*

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

## Recommended reading order
1. `test.java`
1. `component.ts`
1. the rest

### CODE REVIEW

**Review by vitaliizazmic — APPROVED** [review]
LGTM

**Review by sherifnada — APPROVED** [review]
LGTM -- publish at will

**Comment by sherifnada** [comment]
@eugene-kulak restore branch and publish should work

**Comment by keu** [comment]
oh, my bad

**Pull request merged**
