### PR TITLE
#10307 Fixes inconsistent casing on OperationID for Operations API 

### PR DESCRIPTION
**Pull request by sdairs**
See https://github.com/airbytehq/airbyte/issues/10307

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@sdairs this is generated automatically and those fields are related to the OperationId object.

**Comment by sdairs** [comment]
@marcosmarxm happy to be corrected on the appropriate fix - but please see the linked issue. No other API, nor other operation endpoints, use PascalCase - they all use camelCase, this makes it very counter-intuitive to use the operation API.

**Review by alafanechere — APPROVED** [review]
@sdairs thank you for fixing this! I regenerated the doc to propagate the change in the openapi config.

**Review by alafanechere — APPROVED** [review]
I confirm I was able to build the platform and create a custom transformation from the API.

**Pull request merged**
