### PR TITLE
Bump up the CDK version for Postgres/MySQL

### PR DESCRIPTION
**Pull request by akashkulk**
Fail sync when Debezium fails to shutdown properly

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-mysql test report (commit [`14357fa773`](https://github.com/airbytehq/airbyte/pull/31803/commits/14357fa7732fabda4bf205ccaf4d16aff901918b)) - ❌

⏲️  Total pipeline duration: 22mn20s 

| Step                                                        | Result   |
|:------------------------------------------------------------|:---------|
| Build connector tar                                         | ✅       |
| Java Connector Unit Tests                                   | ✅       |
| Build source-mysql docker image for platform(s) linux/amd64 | ✅       |
| Acceptance tests                                            | ✅       |
| Java Connector Integration Tests                            | ✅       |
| Validate metadata for source-mysql                          | ✅       |
| Connector version semver check                              | ✅       |
| QA checks                                                   | ❌       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698189478/14357fa7732fabda4bf205ccaf4d16aff901918b/source-mysql/3.1.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:14357fa7732fabda4bf205ccaf4d16aff901918b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-mysql test report (commit [`efb248811d`](https://github.com/airbytehq/airbyte/pull/31803/commits/efb248811df6b37703a2fe552fd80310e3cd3bb1)) - ✅

⏲️  Total pipeline duration: 20mn33s 

| Step                                                        | Result   |
|:------------------------------------------------------------|:---------|
| Build connector tar                                         | ✅       |
| Java Connector Unit Tests                                   | ✅       |
| Build source-mysql docker image for platform(s) linux/amd64 | ✅       |
| Acceptance tests                                            | ✅       |
| Java Connector Integration Tests                            | ✅       |
| Validate metadata for source-mysql                          | ✅       |
| Connector version semver check                              | ✅       |
| QA checks                                                   | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698191551/efb248811df6b37703a2fe552fd80310e3cd3bb1/source-mysql/3.1.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:efb248811df6b37703a2fe552fd80310e3cd3bb1)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`efb248811d`](https://github.com/airbytehq/airbyte/pull/31803/commits/efb248811df6b37703a2fe552fd80310e3cd3bb1)) - ❌

⏲️  Total pipeline duration: 18mn22s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build connector tar                                            | ✅       |
| Java Connector Unit Tests                                      | ❌       |
| Build source-postgres docker image for platform(s) linux/amd64 | ✅       |
| Acceptance tests                                               | ✅       |
| Java Connector Integration Tests                               | ✅       |
| Validate metadata for source-postgres                          | ✅       |
| Connector version semver check                                 | ✅       |
| QA checks                                                      | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698191551/efb248811df6b37703a2fe552fd80310e3cd3bb1/source-postgres/3.2.14/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:efb248811df6b37703a2fe552fd80310e3cd3bb1)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Review by rodireich — APPROVED** [review]

**Review by bazarnov — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-nasa test report (commit [`6edbb65948`](https://github.com/airbytehq/airbyte/pull/31803/commits/6edbb6594847e6a562aa2be08d24d4202a4d8331)) - ❌

⏲️  Total pipeline duration: 01mn42s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Build source-nasa docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                 | ✅       |
| Acceptance tests                                           | ❌       |
| Code format checks                                         | ✅       |
| Validate metadata for source-nasa                          | ✅       |
| Connector version semver check                             | ❌       |
| Connector version increment check                          | ❌       |
| QA checks                                                  | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698248136/6edbb6594847e6a562aa2be08d24d4202a4d8331/source-nasa/0.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6edbb6594847e6a562aa2be08d24d4202a4d8331)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-nasa test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-mailchimp test report (commit [`6edbb65948`](https://github.com/airbytehq/airbyte/pull/31803/commits/6edbb6594847e6a562aa2be08d24d4202a4d8331)) - ❌

⏲️  Total pipeline duration: 02mn11s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build source-mailchimp docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                      | ✅       |
| Acceptance tests                                                | ❌       |
| Check our base image is used                                    | ❌       |
| Code format checks                                              | ✅       |
| Validate metadata for source-mailchimp                          | ✅       |
| Connector version semver check                                  | ❌       |
| Connector version increment check                               | ❌       |
| QA checks                                                       | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698248136/6edbb6594847e6a562aa2be08d24d4202a4d8331/source-mailchimp/0.4.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6edbb6594847e6a562aa2be08d24d4202a4d8331)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mailchimp test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-qdrant test report (commit [`6edbb65948`](https://github.com/airbytehq/airbyte/pull/31803/commits/6edbb6594847e6a562aa2be08d24d4202a4d8331)) - ✅

⏲️  Total pipeline duration: 02mn23s 

| Step                                                              | Result   |
|:------------------------------------------------------------------|:---------|
| Build destination-qdrant docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                        | ✅       |
| Code format checks                                                | ✅       |
| Validate metadata for destination-qdrant                          | ✅       |
| Connector version semver check                                    | ✅       |
| QA checks                                                         | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698248136/6edbb6594847e6a562aa2be08d24d4202a4d8331/destination-qdrant/0.0.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6edbb6594847e6a562aa2be08d24d4202a4d8331)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-qdrant test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-pinecone test report (commit [`6edbb65948`](https://github.com/airbytehq/airbyte/pull/31803/commits/6edbb6594847e6a562aa2be08d24d4202a4d8331)) - ✅

⏲️  Total pipeline duration: 03mn21s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Build destination-pinecone docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                          | ✅       |
| Integration tests                                                   | ✅       |
| Acceptance tests                                                    | ✅       |
| Check our base image is used                                        | ✅       |
| Code format checks                                                  | ✅       |
| Validate metadata for destination-pinecone                          | ✅       |
| Connector version semver check                                      | ✅       |
| QA checks                                                           | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698248136/6edbb6594847e6a562aa2be08d24d4202a4d8331/destination-pinecone/0.0.17/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6edbb6594847e6a562aa2be08d24d4202a4d8331)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-pinecone test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-milvus test report (commit [`6edbb65948`](https://github.com/airbytehq/airbyte/pull/31803/commits/6edbb6594847e6a562aa2be08d24d4202a4d8331)) - ✅

⏲️  Total pipeline duration: 03mn15s 

| Step                                                              | Result   |
|:------------------------------------------------------------------|:---------|
| Build destination-milvus docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                        | ✅       |
| Integration tests                                                 | ✅       |
| Acceptance tests                                                  | ✅       |
| Check our base image is used                                      | ✅       |
| Code format checks                                                | ✅       |
| Validate metadata for destination-milvus                          | ✅       |
| Connector version semver check                                    | ✅       |
| QA checks                                                         | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698248136/6edbb6594847e6a562aa2be08d24d4202a4d8331/destination-milvus/0.0.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6edbb6594847e6a562aa2be08d24d4202a4d8331)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-milvus test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-weaviate test report (commit [`6edbb65948`](https://github.com/airbytehq/airbyte/pull/31803/commits/6edbb6594847e6a562aa2be08d24d4202a4d8331)) - ✅

⏲️  Total pipeline duration: 03mn15s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Build destination-weaviate docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                          | ✅       |
| Integration tests                                                   | ✅       |
| Acceptance tests                                                    | ✅       |
| Check our base image is used                                        | ✅       |
| Code format checks                                                  | ✅       |
| Validate metadata for destination-weaviate                          | ✅       |
| Connector version semver check                                      | ✅       |
| QA checks                                                           | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698248136/6edbb6594847e6a562aa2be08d24d4202a4d8331/destination-weaviate/0.2.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6edbb6594847e6a562aa2be08d24d4202a4d8331)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-weaviate test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-chroma test report (commit [`6edbb65948`](https://github.com/airbytehq/airbyte/pull/31803/commits/6edbb6594847e6a562aa2be08d24d4202a4d8331)) - ✅

⏲️  Total pipeline duration: 03mn08s 

| Step                                                              | Result   |
|:------------------------------------------------------------------|:---------|
| Build destination-chroma docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                        | ✅       |
| Code format checks                                                | ✅       |
| Validate metadata for destination-chroma                          | ✅       |
| Connector version semver check                                    | ✅       |
| QA checks                                                         | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698248136/6edbb6594847e6a562aa2be08d24d4202a4d8331/destination-chroma/0.0.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6edbb6594847e6a562aa2be08d24d4202a4d8331)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-chroma test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-paypal-transaction test report (commit [`6edbb65948`](https://github.com/airbytehq/airbyte/pull/31803/commits/6edbb6594847e6a562aa2be08d24d4202a4d8331)) - ❌

⏲️  Total pipeline duration: 03mn12s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build source-paypal-transaction docker image for platform(s) linux/amd64 | ✅       |
| Acceptance tests                                                         | ✅       |
| Check our base image is used                                             | ✅       |
| Code format checks                                                       | ✅       |
| Validate metadata for source-paypal-transaction                          | ✅       |
| Connector version semver check                                           | ❌       |
| Connector version increment check                                        | ❌       |
| QA checks                                                                | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698248136/6edbb6594847e6a562aa2be08d24d4202a4d8331/source-paypal-transaction/2.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6edbb6594847e6a562aa2be08d24d4202a4d8331)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-younium test report (commit [`6edbb65948`](https://github.com/airbytehq/airbyte/pull/31803/commits/6edbb6594847e6a562aa2be08d24d4202a4d8331)) - ❌

⏲️  Total pipeline duration: 02mn05s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Build source-younium docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                    | ✅       |
| Acceptance tests                                              | ❌       |
| Code format checks                                            | ✅       |
| Validate metadata for source-younium                          | ✅       |
| Connector version semver check                                | ❌       |
| Connector version increment check                             | ❌       |
| QA checks                                                     | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698248136/6edbb6594847e6a562aa2be08d24d4202a4d8331/source-younium/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6edbb6594847e6a562aa2be08d24d4202a4d8331)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-younium test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`6edbb65948`](https://github.com/airbytehq/airbyte/pull/31803/commits/6edbb6594847e6a562aa2be08d24d4202a4d8331)) - ❌

⏲️  Total pipeline duration: 21mn30s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build connector tar                                            | ✅       |
| Java Connector Unit Tests                                      | ❌       |
| Build source-postgres docker image for platform(s) linux/amd64 | ✅       |
| Acceptance tests                                               | ✅       |
| Java Connector Integration Tests                               | ✅       |
| Validate metadata for source-postgres                          | ✅       |
| Connector version semver check                                 | ✅       |
| QA checks                                                      | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698248136/6edbb6594847e6a562aa2be08d24d4202a4d8331/source-postgres/3.2.14/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6edbb6594847e6a562aa2be08d24d4202a4d8331)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-s3 test report (commit [`6edbb65948`](https://github.com/airbytehq/airbyte/pull/31803/commits/6edbb6594847e6a562aa2be08d24d4202a4d8331)) - ❌

⏲️  Total pipeline duration: 22mn35s 

| Step                                                     | Result   |
|:---------------------------------------------------------|:---------|
| Build source-s3 docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                               | ✅       |
| Acceptance tests                                         | ✅       |
| Check our base image is used                             | ✅       |
| Code format checks                                       | ✅       |
| Validate metadata for source-s3                          | ✅       |
| Connector version semver check                           | ❌       |
| Connector version increment check                        | ❌       |
| QA checks                                                | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698248136/6edbb6594847e6a562aa2be08d24d4202a4d8331/source-s3/4.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6edbb6594847e6a562aa2be08d24d4202a4d8331)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-bing-ads test report (commit [`6edbb65948`](https://github.com/airbytehq/airbyte/pull/31803/commits/6edbb6594847e6a562aa2be08d24d4202a4d8331)) - ❌

⏲️  Total pipeline duration: 31mn42s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build source-bing-ads docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                     | ✅       |
| Acceptance tests                                               | ❌       |
| Check our base image is used                                   | ✅       |
| Code format checks                                             | ✅       |
| Validate metadata for source-bing-ads                          | ✅       |
| Connector version semver check                                 | ❌       |
| Connector version increment check                              | ❌       |
| QA checks                                                      | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698248136/6edbb6594847e6a562aa2be08d24d4202a4d8331/source-bing-ads/1.1.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6edbb6594847e6a562aa2be08d24d4202a4d8331)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-bing-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-mysql test report (commit [`6edbb65948`](https://github.com/airbytehq/airbyte/pull/31803/commits/6edbb6594847e6a562aa2be08d24d4202a4d8331)) - ✅

⏲️  Total pipeline duration: 21mn26s 

| Step                                                        | Result   |
|:------------------------------------------------------------|:---------|
| Build connector tar                                         | ✅       |
| Java Connector Unit Tests                                   | ✅       |
| Build source-mysql docker image for platform(s) linux/amd64 | ✅       |
| Acceptance tests                                            | ✅       |
| Java Connector Integration Tests                            | ✅       |
| Validate metadata for source-mysql                          | ✅       |
| Connector version semver check                              | ✅       |
| QA checks                                                   | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698248136/6edbb6594847e6a562aa2be08d24d4202a4d8331/source-mysql/3.1.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6edbb6594847e6a562aa2be08d24d4202a4d8331)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`6edbb65948`](https://github.com/airbytehq/airbyte/pull/31803/commits/6edbb6594847e6a562aa2be08d24d4202a4d8331)) - ❌

⏲️  Total pipeline duration: 08mn50s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Build connector tar                                                 | ✅       |
| Java Connector Unit Tests                                           | ❌       |
| Build destination-bigquery docker image for platform(s) linux/amd64 | ✅       |
| Java Connector Integration Tests                                    | ✅       |
| Validate metadata for destination-bigquery                          | ✅       |
| Connector version semver check                                      | ✅       |
| QA checks                                                           | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698248136/6edbb6594847e6a562aa2be08d24d4202a4d8331/destination-bigquery/2.1.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6edbb6594847e6a562aa2be08d24d4202a4d8331)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-tiktok-marketing test report (commit [`6edbb65948`](https://github.com/airbytehq/airbyte/pull/31803/commits/6edbb6594847e6a562aa2be08d24d4202a4d8331)) - ❌

⏲️  Total pipeline duration: 54mn19s 

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Build source-tiktok-marketing docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                             | ✅       |
| Acceptance tests                                                       | ✅       |
| Check our base image is used                                           | ✅       |
| Code format checks                                                     | ✅       |
| Validate metadata for source-tiktok-marketing                          | ✅       |
| Connector version semver check                                         | ❌       |
| Connector version increment check                                      | ❌       |
| QA checks                                                              | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698248136/6edbb6594847e6a562aa2be08d24d4202a4d8331/source-tiktok-marketing/3.9.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6edbb6594847e6a562aa2be08d24d4202a4d8331)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Pull request closed without merging**
