### PR TITLE
Source Jira: add expand on lead field

### PR DESCRIPTION
**Pull request by jkleinkauff**
## What
The current project stream is not getting information for the **lead** field. This PR expands the stream to **lead** so we will be able to use that information.

https://github.com/airbytehq/airbyte/issues/26851

## How
Expand the project stream to lead field. `params["expand"] = "description,lead"`

### CODE REVIEW

**Comment by jkleinkauff** [comment]
@alafanechere Hey, could you help me with this one? Thank you so much!

**Comment by alafanechere** [comment]
@marcosmarxm / @sajarin could you please run tests on a non-forked branch?

**Comment by marcosmarxm** [comment]
@sh4sh can you review and run the tests?

**Comment by marcosmarxm** [comment]
> [CLA assistant check](https://cla-assistant.io/airbytehq/airbyte?pullRequest=26920) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=26920) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=26920) it.

@jkleinkauff please make sure to sign the CLA.

**Comment by jkleinkauff** [comment]
> > [CLA assistant check](https://cla-assistant.io/airbytehq/airbyte?pullRequest=26920) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=26920) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=26920) it.
> 
> @jkleinkauff please make sure to sign the CLA.

@marcosmarxm Just signed. Thank you !!

**Comment by jkleinkauff** [comment]
Hey @sh4sh is there anything missing from my side?

**Review by marcosmarxm — APPROVED** [review]
Thanks @jkleinkauff the contribution looks good. I need to push some changes to make test work properly. I'll publish later today.

**Pull request merged**
