### PR TITLE
Airbyte-ci: Remove gradle task `connectorAcceptanceTest`

### LINKED ISSUE #30306: Nightly CI tests: `connectorAcceptanceTest' not found`
Java connectors on the nightly tests are now failing with:

```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'connectorAcceptanceTest' not found in root project 'airbyte' and its subprojects.
```

But... those tests do pass on master?

### PR DESCRIPTION
**Pull request by bnchrch**
## What
We no longer need or support running the `connectorAcceptanceTest` gradle task to run CAT tests.

And having this test around is causing failures in some connector test builds

(closes #30306)
(blocked by https://github.com/airbytehq/airbyte/pull/30461

## How
So lets remove it
1. Removes `connectorAcceptanceTest` as a gradle command
2. Removes `airbyte-connector-acceptance-test` plugin from all gradle files
3. Remove `-x connectorAcceptanceTest` from airbyte-ci

### CODE REVIEW

**Comment by bnchrch** [comment]
Cancelled connectors test (too many)

Started new test on subset
```
--name=destination-bigquery --name=source-chargebee --name=source-postgres --name=destination-postgres
````

https://github.com/airbytehq/airbyte/actions/runs/6152201971

**Comment by bnchrch** [comment]
Running legacy test

**Comment by bnchrch** [comment]
Run regular test for destination-redshift and destination-snowflake: https://github.com/airbytehq/airbyte/actions/runs/6153895861

**Review by postamar — APPROVED** [review]
LGTM! Kill it with fire.

By the way, the script `tools/bin/ci_integration_test.sh` calls gradle with the `integrationTest` target and expects to run the acceptance tests. To this end it sets properties on the command line like ` -PconnectorAcceptanceTest.useLocalCdk=`. Can you get rid of these please? FYI this script is what's called in the `legacy-test-command.yml` workflow.

**Review by rodireich — APPROVED** [review]

**Comment by octavia-approvington** [comment]
It's time <br/> fine lets go

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
