### PR TITLE
CDK: remove redundant error status retry logic

### LINKED ISSUE #11291: Python CDK `should_retry` behavior nullified by `default_backoff_handler`
## Environment
- **Airbyte version**:  example is 0.35.58-alpha
- **OS Version / Instance**: macOS, GCP n2.
- **Deployment**: Docker
- **Source Connector and version**: Kyriba - https://github.com/wjwatkinson/airbyte/blob/source-kyriba/airbyte-integrations/connectors/source-kyriba/source_kyriba/source.py
- **Destination Connector and version**: BigQuery
- **Severity**: Medium
- **Step where error happened**: Sync job
## Current Behavior
The [source `should_retry` method evaluates to True](https://github.com/wjwatkinson/airbyte/blob/source-kyriba/airbyte-integrations/connectors/source-kyriba/source_kyriba/source.py#L64), but the request is never retried because [`should_give_up` in `rate_limiting.py` evaluates to True](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/streams/http/rate_limiting.py#L33).

## Expected Behavior
If `should_retry` evaluates to True the request should be retried.

## Logs
[logs-50.txt](https://github.com/airbytehq/airbyte/files/8315842/logs-50.txt)

```
2022-03-19 21:52:58 source > Giving up for returned HTTP status: 401
2022-03-19 21:52:58 source > Giving up _send(...) after 1 tries (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException)
```

## Steps to Reproduce
1. Overwrite the `should_retry` method in your `HttpStream` to include a status between `400` and `500` other than `429`.
2. Run your stream, so it encounters this error status.
3. Watch the stream not retry.

## Are you willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by wjwatkinson**
## What
Fixes #11291
`HttpStream.should_retry` already determines what statuses should be retried. The default is 429 and 500-600. This logic was duplicated within the `rate_limiting.py` `default_backoff_handler` method. This meant that even if a developer overwrote the `should_retry` method to customize the behavior for a specific source this would not be respected by the `default_backoff_handler` and the request would not be retried.

## How
Remove `give_up` logic from `default_backoff_handler`.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

187 passed, 137 warnings in 3.49s

</details>

### CODE REVIEW

**Comment by wjwatkinson** [comment]
The CLA page does not have anything for me to review, or anywhere for me to sign.
image

**Comment by alafanechere** [comment]
> The CLA page does not have anything for me to review, or anywhere for me to sign. image

Is your GitHub account email address the same as the one you used to commit (your gmail address)? Could you also please retry as Github had some failures today.

**Comment by wjwatkinson** [comment]
> /publish-cdk dry-run=true
> 
> > ❌  https://github.com/airbytehq/airbyte/actions/runs/2162449252
> > ❌  https://github.com/airbytehq/airbyte/actions/runs/2162449252
> > ❌  https://github.com/airbytehq/airbyte/actions/runs/2162449252

🤔 looking at the errors they don't seem to have anything to do with my change, which is unexpected.

**Comment by pedroslopez** [comment]
@alafanechere The failing build-cdk action was fixed in #12019 so you should be able to try this again. Note that there's been a CDK release since when this was submitted.

**Comment by alafanechere** [comment]
Hey @wjwatkinson I reached out to the CDK team and they told me:
* The issue is valid, the `should_retry` method should allow custom override but it is being negated by the backoff handler.
* Instead of removing the `giveup=`  in the backoff handler, I think ideally we propagate `should_retry` to the backoff handler's giveup (possibly it would be NOT `should_retry` to be the same as `should_give_up`)
This re-enables intended use of `should_retry` to allow user override.

Sorry for raising this now but this is a critical part of the CDK.

(cc. @Phlair )

**Comment by alafanechere** [comment]
> @alafanechere That makes sense. I took a look and it seems like implementing what you are suggesting is a more complex change that is going to require me becoming more familiar with the python cdk and the backoff package to implement well. I am currently pretty swamped, so I am not sure when I will have time.

This is something our team might eventually refactor. I'm closing the PR now but feel free to reopen if you want to work on this when your bandwidth allows. Thank you!

**Pull request closed without merging**
