### PR TITLE
Error Prone PMD rules

### PR DESCRIPTION
**Pull request by alovew**
Apply the following PMD rules from the Error Prone category:

AssignmentInOperand
AvoidAccessibilityAlteration
AvoidBranchingStatementAsLastInLoop
AvoidCatchingNPE
AvoidCatchingThrowable
AvoidDuplicateLiterals

AvoidDuplicateLiterals is where most changes were required, so there are a lot of new variables for duplicate literals, especially in tests.

### CODE REVIEW

**Review by cgardens — APPROVED** [review]
I'm not 100% convinced that turning literally every single string in test classes into constants is that useful. I don't mind it either. Mostly curious to hear from @alovew would if you felt it was worthwhile.

Thanks for doing this!

**Comment by alovew** [comment]
@cgardens We want to apply the same PMD rules in OSS that we have applied in Cloud, so it was a predetermined list - I'm not sure who was involved in the original choice of rules to implement, but it's not just to fix the existing errors but to enforce the rule going forward.

**Comment by jdpgrailsdev** [comment]
@alovew It looks like there are now some PMD violations in the acceptance tests: 

```
> 42 PMD rule violations were found. See the report at: file:///actions-runner/_work/airbyte/airbyte/airbyte-tests/build/reports/pmd/acceptanceTests.html
```

**Comment by alovew** [comment]
@jdpgrailsdev ah yes, this always happens with PMD violations where some of them are not caught when I try to run the check locally. Do you know how to get these violations to show up in the local run?

**Comment by jdpgrailsdev** [comment]
> @jdpgrailsdev ah yes, this always happens with PMD violations where some of them are not caught when I try to run the check locally. Do you know how to get these violations to show up in the local run?

@alovew A PMD task is generated for each configuration (e.g. `pmdMain`, `pmdTest`, `pmdAcceptanceTest`, etc) and those are suppose to be added as dependency tasks on `check`.  Therefore, make sure that you run with `check` and not just `test` or `build` locally and that should catch it.  If you are running `check` and its not doing it, let me know and I can look into what is going on.

**Comment by alovew** [comment]
@jdpgrailsdev how can I see all of the configurations? I knew about pmdMain and pmdTest, but not pmdAcceptanceTest (or any others)

**Comment by jdpgrailsdev** [comment]
> @jdpgrailsdev how can I see all of the configurations? I knew about pmdMain and pmdTest, but not pmdAcceptanceTest (or any others)

@alovew I am not aware of a built-in Gradle way to do this.  We would need to add a custom task the prints the configuration names.  Of course, this would be on a sub-project by sub-project basis, as some projects will declare different configurations from others.

**Comment by jdpgrailsdev** [comment]
@alovew Not exactly what you are looking for, but `./gradlew tasks --all | grep pmd` will show all of the pmd tasks generated across all of the subprojects in the project.  The majority will be `pmdMain` and `pmdTest`, but you can also see the others, such as `pmdPerformanceTestJava`, `pmdIntegrationTestJava` and `pmdAcceptanceTests`, to name a few of the custom configurations present that get PMD tasks.

**Pull request merged**
