### PR TITLE
:sparkles: Source Stripe: updated: connector health: invoice_line_items stream schema, unit tests, expected records

### PR DESCRIPTION
**Pull request by darynaishchenko**
## What
`TypeError: expected str, bytes or os.PathLike object, not NoneType�[0m`
validation error for invoice_line_items stream schema
expected records

## How
added request cache path env var for unittests.
added margins field for invoice_line_items stream schema.
updated expected records

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-stripe test report (commit [`dd552c4be9`](https://github.com/airbytehq/airbyte/pull/31046/commits/dd552c4be93735db5a35d43f47e676783943bd11)) - ❌

⏲️  Total pipeline duration: 10mn22s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Connector package install                                  | ✅        |
| Build source-stripe docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                 | ✅        |
| Acceptance tests                                           | ✅        |
| Code format checks                                         | ❌        |
| Validate metadata for source-stripe                        | ✅        |
| Connector version semver check                             | ✅        |
| Connector version increment check                          | ✅        |
| QA checks                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-stripe_fix-unittest/1696419674/dd552c4be93735db5a35d43f47e676783943bd11/source-stripe/4.3.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:dd552c4be93735db5a35d43f47e676783943bd11)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-stripe test report (commit [`18785d6285`](https://github.com/airbytehq/airbyte/pull/31046/commits/18785d62852a0abb046bc392498538d44c3c90a5)) - ✅

⏲️  Total pipeline duration: 10mn58s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Connector package install                                  | ✅        |
| Build source-stripe docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                 | ✅        |
| Acceptance tests                                           | ✅        |
| Code format checks                                         | ✅        |
| Validate metadata for source-stripe                        | ✅        |
| Connector version semver check                             | ✅        |
| Connector version increment check                          | ✅        |
| QA checks                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-stripe_fix-unittest/1696421589/18785d62852a0abb046bc392498538d44c3c90a5/source-stripe/4.3.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:18785d62852a0abb046bc392498538d44c3c90a5)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-stripe test report (commit [`d3d9cdcc0c`](https://github.com/airbytehq/airbyte/pull/31046/commits/d3d9cdcc0c783fce682d9aa1d300a7ac1cc02dac)) - ✅

⏲️  Total pipeline duration: 10mn15s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Connector package install                                  | ✅        |
| Build source-stripe docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                 | ✅        |
| Acceptance tests                                           | ✅        |
| Code format checks                                         | ✅        |
| Validate metadata for source-stripe                        | ✅        |
| Connector version semver check                             | ✅        |
| Connector version increment check                          | ✅        |
| QA checks                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-stripe_fix-unittest/1696426619/d3d9cdcc0c783fce682d9aa1d300a7ac1cc02dac/source-stripe/4.4.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d3d9cdcc0c783fce682d9aa1d300a7ac1cc02dac)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-stripe test report (commit [`042ff87828`](https://github.com/airbytehq/airbyte/pull/31046/commits/042ff87828926f9e44b8f432671c4909b4ac1619)) - ✅

⏲️  Total pipeline duration: 10mn05s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Connector package install                                     | ✅        |
| Build source-stripe docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ✅        |
| Acceptance tests                                              | ✅        |
| Code format checks                                            | ✅        |
| Validate metadata for source-stripe                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-stripe_fix-unittest/1696502524/042ff87828926f9e44b8f432671c4909b4ac1619/source-stripe/4.4.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:042ff87828926f9e44b8f432671c4909b4ac1619)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Review by roman-yermilov-gl — APPROVED** [review]

**Pull request merged**
