### PR TITLE
✨Add common async methods

### PR DESCRIPTION
**Pull request by benmoriceau**
## What
Implement the async methods for the common classes that weren't using it.

## How
Implement the methods needed by the async framework in the shared destination class.

## Recommended reading order
1. `SwitchingDestination.java`
2. `SshWrappedDestination.java`
3. `SerializedAirbyteMessageConsumer.java`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

### CODE REVIEW

**Review by tryangul — APPROVED** [review]
🚢

**Review by evantahler — APPROVED** [review]

**Comment by octavia-approvington** [comment]
Enough! Let's do this <br/> goooooo!

**Review by octavia-approvington — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  destination-mariadb-columnstore test report (commit [`ea74e1dc71`](https://github.com/airbytehq/airbyte/pull/29003/commits/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3)) - ❌

⏲️  Total pipeline duration: 91mn08s 

| Step                                                                                       | Result   |
|:-------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mariadb-columnstore/metadata.yaml     | ✅        |
| Connector version semver check                                                             | ✅        |
| QA checks                                                                                  | ✅        |
| Build connector tar                                                                        | ✅        |
| Build destination-mariadb-columnstore docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mariadb-columnstore:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/bmoric_comn-class-t-async-framewotk/1691006549/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3/destination-mariadb-columnstore/0.1.7/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mariadb-columnstore test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-elasticsearch-strict-encrypt test report (commit [`ea74e1dc71`](https://github.com/airbytehq/airbyte/pull/29003/commits/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3)) - ❌

⏲️  Total pipeline duration: 05mn59s 

| Step                                                                                                | Result   |
|:----------------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-elasticsearch-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                                      | ✅        |
| QA checks                                                                                           | ✅        |
| Build connector tar                                                                                 | ✅        |
| Build destination-elasticsearch-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-elasticsearch-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/bmoric_comn-class-t-async-framewotk/1691006549/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3/destination-elasticsearch-strict-encrypt/0.1.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-elasticsearch-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-dynamodb test report (commit [`ea74e1dc71`](https://github.com/airbytehq/airbyte/pull/29003/commits/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3)) - ✅

⏲️  Total pipeline duration: 15mn50s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-dynamodb/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-dynamodb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-dynamodb:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/bmoric_comn-class-t-async-framewotk/1691006549/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3/destination-dynamodb/0.1.7/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-dynamodb test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-postgres test report (commit [`ea74e1dc71`](https://github.com/airbytehq/airbyte/pull/29003/commits/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3)) - ❌

⏲️  Total pipeline duration: 31mn32s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-postgres docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-postgres:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/bmoric_comn-class-t-async-framewotk/1691006549/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3/destination-postgres/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-postgres test
```

**Comment by octavia-squidington-iii** [comment]
##  source-alloydb test report (commit [`ea74e1dc71`](https://github.com/airbytehq/airbyte/pull/29003/commits/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3)) - ❌

⏲️  Total pipeline duration: 05mn34s 

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-alloydb/metadata.yaml     | ✅        |
| Connector version semver check                                            | ✅        |
| QA checks                                                                 | ✅        |
| Build connector tar                                                       | ✅        |
| Build source-alloydb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-alloydb:integrationTest | ✅        |
| Acceptance tests                                                          | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/bmoric_comn-class-t-async-framewotk/1691006549/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3/source-alloydb/3.1.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-alloydb test
```

**Comment by octavia-squidington-iii** [comment]
##  source-clickhouse-strict-encrypt test report (commit [`ea74e1dc71`](https://github.com/airbytehq/airbyte/pull/29003/commits/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3)) - ❌

⏲️  Total pipeline duration: 303mn20s 

| Step                                                                                        | Result   |
|:--------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-clickhouse-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                              | ✅        |
| QA checks                                                                                   | ✅        |
| Build connector tar                                                                         | ✅        |
| Build source-clickhouse-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-clickhouse-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                            | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/bmoric_comn-class-t-async-framewotk/1691006549/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3/source-clickhouse-strict-encrypt/0.1.17/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-clickhouse-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-teradata test report (commit [`ea74e1dc71`](https://github.com/airbytehq/airbyte/pull/29003/commits/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3)) - ✅

⏲️  Total pipeline duration: 12mn53s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-teradata/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ✅        |
| Build source-teradata docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-teradata:integrationTest | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/bmoric_comn-class-t-async-framewotk/1691006549/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3/source-teradata/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-teradata test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-yugabytedb test report (commit [`ea74e1dc71`](https://github.com/airbytehq/airbyte/pull/29003/commits/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3)) - ❌

⏲️  Total pipeline duration: 24mn46s 

| Step                                                                              | Result   |
|:----------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-yugabytedb/metadata.yaml     | ✅        |
| Connector version semver check                                                    | ✅        |
| QA checks                                                                         | ✅        |
| Build connector tar                                                               | ✅        |
| Build destination-yugabytedb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-yugabytedb:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/bmoric_comn-class-t-async-framewotk/1691006549/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3/destination-yugabytedb/0.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-yugabytedb test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-tidb test report (commit [`ea74e1dc71`](https://github.com/airbytehq/airbyte/pull/29003/commits/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3)) - ✅

⏲️  Total pipeline duration: 17mn40s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-tidb/metadata.yaml     | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |
| Build connector tar                                                         | ✅        |
| Build destination-tidb docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-tidb:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-tidb:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/bmoric_comn-class-t-async-framewotk/1691006549/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3/destination-tidb/0.1.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-tidb test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mssql-strict-encrypt test report (commit [`ea74e1dc71`](https://github.com/airbytehq/airbyte/pull/29003/commits/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3)) - ❌

⏲️  Total pipeline duration: 16mn40s 

| Step                                                                                   | Result   |
|:---------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mssql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                         | ✅        |
| QA checks                                                                              | ✅        |
| Build connector tar                                                                    | ✅        |
| Build source-mssql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mssql-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/bmoric_comn-class-t-async-framewotk/1691006549/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3/source-mssql-strict-encrypt/1.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mssql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-local-json test report (commit [`ea74e1dc71`](https://github.com/airbytehq/airbyte/pull/29003/commits/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3)) - ✅

⏲️  Total pipeline duration: 05mn28s 

| Step                                                                              | Result   |
|:----------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-local-json/metadata.yaml     | ✅        |
| Connector version semver check                                                    | ✅        |
| QA checks                                                                         | ✅        |
| Build connector tar                                                               | ✅        |
| Build destination-local-json docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-local-json:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/bmoric_comn-class-t-async-framewotk/1691006549/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3/destination-local-json/0.2.11/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-local-json test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-oracle test report (commit [`ea74e1dc71`](https://github.com/airbytehq/airbyte/pull/29003/commits/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3)) - ❌

⏲️  Total pipeline duration: 303mn43s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-oracle/metadata.yaml     | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Build connector tar                                                           | ✅        |
| Build destination-oracle docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-oracle:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-oracle:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/bmoric_comn-class-t-async-framewotk/1691006549/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3/destination-oracle/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-oracle test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-strict-encrypt test report (commit [`ea74e1dc71`](https://github.com/airbytehq/airbyte/pull/29003/commits/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3)) - ❌

⏲️  Total pipeline duration: 04mn22s 

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                           | ✅        |
| QA checks                                                                                | ❌        |
| Build connector tar                                                                      | ✅        |
| Build source-mongodb-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/bmoric_comn-class-t-async-framewotk/1691006549/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3/source-mongodb-strict-encrypt/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-vertica test report (commit [`ea74e1dc71`](https://github.com/airbytehq/airbyte/pull/29003/commits/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3)) - ❌

⏲️  Total pipeline duration: 01mn43s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-vertica/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/bmoric_comn-class-t-async-framewotk/1691006549/ea74e1dc71d75f4fdc49b161f4e0ad43a6711aa3/destination-vertica/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-vertica test
```

**Pull request merged**
