### PR TITLE
fix: return correct language tag when using Kotlin build script

### PR DESCRIPTION
**Pull request by jdpgrailsdev**
## What
* Ensure language tag check passes for projects that use the Kotlin Gradle build script

## How
* Add conditional logic to check for `build.gradle.kts` file when looking for language tags

## Review guide
1. `consts.py`
2. `metadata.py`

## Can this PR be safely reverted and rolled back?
- [X] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by alafanechere — APPROVED** [review]
LGTM! Please bump the package version in pyproject.toml and add a changelog entry in the README file.

**Review by gosusnp — APPROVED** [review]

**Comment by jdpgrailsdev** [comment]
> LGTM! Please bump the package version in pyproject.toml and add a changelog entry in the README file.

@alafanechere D'oh -- totally forgot to do that.  Will do and then will merge.

**Comment by edgao** [comment]
@alafanechere now I'm curious - what does the metadata.yaml language tag do, if we have this language inference thing?

**Comment by alafanechere** [comment]
> @alafanechere now I'm curious - what does the metadata.yaml language tag do, if we have this language inference thing?

@edgao in this context we run a check to make sure the language tag is consistent with the inferred one. The check could be simplified and not be opinionated (just check the tag existence), but we introduced it to solve some inconsistency issue we had (python vs low-code vs manifest only etc.).

And to answer "what does it do": I think the language tag is solely used in our registry / for analytics. The CI control flow are mostly based on a[ language detection](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/connector_ops/connector_ops/utils.py#L406) based on the similar kind of inferences

**Pull request merged**
