### PR TITLE
🐛 Source zendesk-support: make ticket_metrics stream stop requesting data after start_date

### LINKED ISSUE #48424: [zendesk-support] `ticket_metrics` stream doesn't respect `start_date` set at source config
### Connector Name

zendesk-support

### Connector Version

4.3.3

### What step the error happened?

During the sync

### Relevant information

- The connectors `ticket_metrics` stream returns records until the start date, then stops yielding records. However it doesn't mark the stream as complete until all ticket metrics have been fetched from the API. This means the stream takes a long time to complete and makes unneeded API calls for data that is not captured by Airbyte.
- This can be viewed in the logs when running the connector locally with `--debug` enabled. I haven't included logs below as they contain the response data as well.
- I have a fix for this which I'll link in a PR

### Relevant log output

_No response_

### Contribute

- [x] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by willbowditch**
## What

The `ticket_metrics` stream fetches data from the API from most recent to least recent. The state of the most recent record is kept as a cursor for the next stream.

If a start_date is set in the config, the stream should stop fetching data once we have reached that page, however it currently keeps importing data until no more pages are remaining. (The data is queried from the API but not yielded as a record).

The PR stores the oldest seen record and stops fetching data if that is older than the start date.

Closes https://github.com/airbytehq/airbyte/issues/48424

## How

- Keep track of the oldest seen record
- If the oldest seen record is older than the start_date, don't request the next page

## Review guide

- Small change to zendesk-support streams logic

## User Impact

- In cases where the start date has been set the initial stream will complete faster.

## Can this PR be safely reverted and rolled back?
- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by marcosmarxm — COMMENTED** [review]
Sorry the delay to review your contribution @willbowditch I started the test pipeline and request connector team to do final review to your changes.

**Comment by pnilan** [comment]
@marcosmarxm  @willbowditch 

If I understand the goal of this PR, it's to shorten the sync time for `ticket_metrics` by not returning a `next_page_token` when a record is observed with a cursor value older than the configured `start_date` value.

Unfortunately, I don't think we can make the assumption that observing a record with an `updated_at` value older than the configured `start_date` means there would be no other records with `updated_at` values more recent than the `start_date`.

The stateless ticket metrics stream endpoint (`GET /ticket_metrics`) returns records in descending order by `created_at` per the [API documentation](https://developer.zendesk.com/api-reference/ticketing/tickets/ticket_metrics/#list-ticket-metrics).  Meaning it's technically possible for a ticket that was created a long time ago to have an `updated_at` value more recent than the `start_date`.

Example:
```
config start_date = 11/18/2024

ticket_100, created_at = 11/18/2024, updated_at = 11/18/2024 (record extracted, because updated_at >= start_date)
ticket_99, created_at = 11/17/2024, updated_at = 11/18/2024 (record extracted, because updated_at >= start_date)
ticket_98, created_at = 11/16/2024, updated_at = 11/17/2024 (not extracted, because updated_at < start_date)
ticket_97, created_at = 11/15/2024, updated_at = 11/18/2024 (record extracted, because updated_at >= start_date)
...
ticket_1, created_at = 01/01/2024, updated_at = 11/18/2024 (record extracted, because updated_at >= start_date)
```

**Review by pnilan — CHANGES_REQUESTED** [review]
See comment from yesterday. Please let me know if there is something I'm not considering here. Otherwise I'll close this PR this week.

https://github.com/airbytehq/airbyte/pull/48427#issuecomment-2484227164

**Comment by willbowditch** [comment]
@pnilan ah I see, that makes sense. So instead we should track the `created_at` timestamp and stop going through the pages if `created_at` < `start_date`? I'm happy to update the PR to that

**Comment by marcosmarxm** [comment]
@pnilan can you check last comment made by @willbowditch ?

**Comment by pnilan** [comment]
Sorry for the delayed response (holiday last week).

> So instead we should track the created_at timestamp and stop going through the pages if created_at < start_date? I'm happy to update the PR to that>

Unfortunately this won't work either because we use the `updated_at` cursor value to track what has changed (because we care about when a ticket has been resolved, etc so we need to retrieve the record after it's been updated). If we retrieve records based on `created_at` cursor values we would only neglect all tickets created before the `start_date` but updated after the `start_date`. I don't see a way around this given that the data is returned sorted by `created_at` and not `updated_at` and even the first ever ticket created could have been updated as recently as yesterday (not likely, but means we can't assume anything about tickets created a long time before a given `start_date`).

**Pull request closed without merging**
