### PR TITLE
Destination MongoDB: use SHA256 instead of MD5

### PR DESCRIPTION
**Pull request by yort-feng**
## What
*SpotBugs report shows that the algorithms MD2, MD4 and MD5 are not a recommended MessageDigest*
*The security of the MD5 hash function is severely compromised.*

## How
*use SHA256 instead of MD5*

### CODE REVIEW

**Comment by alafanechere** [comment]
Thank you for this contribution @yort-feng , our team will review it soon. 
I'm running the acceptance tests, could you also share their output on your side?
```
./gradlew :airbyte-integrations:connectors:destination-mongodb:integrationTest
```

**Comment by marcosmarxm** [comment]
/publish connector=connectors/destination-mongodb-strict-encrypt

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
