### PR TITLE
Generate connector with templating

### LINKED ISSUE #512: Script for java destination template
## Tell us about the problem you're trying to solve
* In order to use the java-template-destination module, the developer has to perform alot of basic manual steps themselves (e.g. copying the template and fixing path names, etc).

## Describe the solution you’d like
* We should provide a script that does this boilerplate. e.g. `./tools/new_java_destination <destination name>` and it handles all of the command line stuff.

### PR DESCRIPTION
**Pull request by tuliren**
## What
- Currently users need to follow a relatively long procedure to create new connectors.
- Most of the procedures are setting up boilerplate code, which can be automatically.
- Why writing code if they can be generated for us? Why reading blocks of documentation if we can just run a command?
- So here comes this PR.

## How
- [`plop`](https://github.com/plopjs/plop) is an awesome templating framework. This PR leverages this framework and replaces the manual procedure with interactive prompts and automatic code generation.
- Just type `npm run generate`, and follow the prompt.

  [asciicast](https://asciinema.org/a/lMTGcg5t0Pbam04Gw7O9pGBhZ?s=7&t=0:02)

## Comments
- Since this is mostly a Java / Python codebase, introducing js package here may not be ideal.
- I have tried to find a comparable templating framework in Python. However, none of the ones I found is as good.
- Let me know if it is alright to use this approach. If so, I will finish the remaining two generators for python and singer.

## Checklist
- [x] Implement java connector generator.
- [ ] Implement python connector generator.
- [ ] Implement singer connector generator.

## Recommended reading order
- `airbyte-integrations/plopfile.js`
  - This is the templating definition file.
- Template files under `airbyte-integrations/connector-templates/java-destination`
  - The template files are in [handlebars](https://handlebarsjs.com/) format. We can reference input variable with double curly braces.
  - `plop` has handy helpers that convert names to different cases.
- The rest.

This PR resolves #512.

### CODE REVIEW

**Comment by ChristopheDuong** [comment]
Hi! 

I was thinking of doing something similar too.

> I have tried to find a comparable templating framework in Python. However, none of the ones I found is as good.

Usually in Python, the standard templating framework that i've seen being widely used is [cookiecutter](https://cookiecutter.readthedocs.io/en/1.7.2/url)

There's almost 5k [repositories using it already on github](https://github.com/search?q=cookiecutter&type=Repositories)

However I am not too familiar with plopjs so i don't know how they compare. What do you think?

**Comment by cgardens** [comment]
@tuliren, Thanks for sharing this! 100% agreed that some templating could remove all of these manual steps. I have no preference on the templating library.

**Comment by tuliren** [comment]
@ChristopheDuong, thanks for pointing out cookiecutter. I will give it a try and report back.

**Comment by tuliren** [comment]
Hey @sherifnada, I have created the cookiecutter version for the java destination generator: #717.

Here is my personal opinion:
- From developer's perspective, `plop` is better. It is more straightforward to configure and write templates. All specifications are in one js file.
- From user's perspective, `cookiecutter` is better because it is just Python and there is no need to introduce Node.

**Comment by sherifnada** [comment]
@tuliren Amazing. Thanks so much for the thorough work on this. I'll take a look tonight and merge one of these PRs.

**Review by sherifnada — APPROVED** [review]
@tuliren thanks for your awesome PR. Given Plop has a slightly nicer experience for the end user than Cookiecutter, we'll go with it. Thanks for your contribution and welcome to the codebase! ;)

**Pull request merged**
