### PR TITLE
🎉 Source JDBC: changed the column type info log to debug log

### PR DESCRIPTION
**Pull request by arditarapi**
## What
On SQL integrations (MySQL, Postgres, BigQuery, ..etc), we see many log entries that follow this pattern:
Table {} column {} (type {}[{}], nullable {}) -> {}
Table _family_file column rfam_acc (type VARCHAR[7], nullable false) -> JsonSchemaType({type=string})
In big schemas these can go more than 3000 lines.  
Screenshot 2023-04-04 at 5 30 41 PM

## How
Changed the info to debug log

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks @arditarapi for the suggestion. @airbytehq/dbsources can someone take a look in this?

**Review by akashkulk — APPROVED** [review]

**Comment by akashkulk** [comment]
Actually, this has been fixed in https://github.com/airbytehq/airbyte/pull/25227. 
The next publish of the various JDBC sources will pick up this change. 
This issue can be closed

**Comment by marcosmarxm** [comment]
Thanks for the contribution @arditarapi as @akashkulk said this was merged in https://github.com/airbytehq/airbyte/pull/25227/files

**Comment by arditarapi** [comment]
@akashkulk @marcosmarxm I noticed that source-snowflake and source-bigquery are still producing the logs. And based on snowflake changelogs the last release is 0.1.34 | 2023-03-30. Any plans on creating a new release ?

**Pull request closed without merging**
