### PR TITLE
Source S3: Add virtual-hosted-style option

### LINKED ISSUE #18902: add virtual-hosted-style option for S3
## Tell us about the problem you're trying to solve
I need add Aliyun OSS(S3 compatible) as source and destination, which only support virtual hosted style endpoint.

## Describe the solution you’d like
Provider an option for both S3 source and destination to enable/disable virtual hosted style.

## Are you willing to submit a PR?
Yes, I will submit a PR.

### LINKED ISSUE #19005: add virtual-hosted-style option for S3 source
## Tell us about the problem you're trying to solve
I need to add Aliyun OSS(S3 compatible) as my source, which only support virtual hosted style endpoint.

## Describe the solution you’d like
Provider an option for S3 source to enable/disable virtual hosted style.

## Are you willing to submit a PR?
Yes, I will submit a PR.

### PR DESCRIPTION
**Pull request by Xingyuan-Chen**
*I add a virtual-hosted-style option for S3 source
*It helps to make S3 source support Non-Amazon S3 endpoint who only support virtual hosted style like Aliyun OSS.
This PR closes #18902

### CODE REVIEW

**Comment by koconder** [comment]
@Xingyuan-Chen thanks for splitting the source and destination, I’ll take a look.

**Comment by koconder** [comment]
Tests passing, in S3 boto3 client the default is auto for `addressing style` so this is a safe change. No issues with passing these changes. See https://docs.aws.amazon.com/cli/latest/topic/s3-config.html

```
addressing_style - Specifies which addressing style to use. This controls if the bucket name is in the hostname or part of the URL. Value values are: path, virtual, and auto. The default value is auto.
```

**Review by vincentkoc — APPROVED** [review]

**Pull request merged**
