### PR TITLE
🐛 Destination BigQuery (+denormalized): correctly parse buffer count

### PR DESCRIPTION
**Pull request by edgao**
we're not actually parsing the config correctly (it's nested under the `loading_method` object). Extract it correctly.

also swap the order of parameters in the `assertEquals` calls. The convention is `assertEquals(expected, actual)`.

### CODE REVIEW

**Review by ryankfu — APPROVED** [review]
LGTM, thanks for getting this up!

**Comment by edgao** [comment]
/publish connector=connectors/destination-bigquery,connectors/destination-bigquery-denormalized

**Pull request merged**
