### PR TITLE
source-usda-fas contribution from ombhardwajj

### LINKED ISSUE #47975: [connector-request] USDA FAS
This is a suggestion to create a connector for USDA FAS using the UI Connector Builder.
The website for the connector is https://apps.fas.usda.gov/opendatawebV2/#/home

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to step 3).
3. Describe steps to get credentials.
4. Create the connector using the UI Builder.   

> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> This is a suggestion, and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend following the steps above.

### PR DESCRIPTION
**Pull request by ombhardwajj**
This closes #47975
## What

This PR adds a new connector for source USDA FAS (source-usda-fas).

Contributor-provided connector description:

This provides access to publicly available agricultural commodity data from the Export Sales Report (ESR), Global Agricultural Trade System (GATS), and Production, Supply &amp; Distribution (PSD) databases.
Docs : https://apps.fas.usda.gov/opendatawebV2/#/home
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key.  |  |
| `market_year` | `integer` | Market Year.  | 2023 |
| `country_codes` | `array` | ESR Country Codes.  |  |
| `commodities_codes` | `array` | ESR Commodities Codes.  |  |
| `gats_reporter_codes` | `array` | GATS Reporter Codes.  |  |
| `psd_commodities_codes` | `array` | PSD Commodities Codes.  |  |
| `psd_country_codes` | `array` | PSD Country Codes.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| gats_commodity_import_data |  | No pagination | ✅ |  ❌  |
| gats_commodity_export_data |  | No pagination | ✅ |  ❌  |
| esr_export_data |  | No pagination | ✅ |  ❌  |
| psd_forcecastnumber |  | No pagination | ✅ |  ❌  |
| psd_forecastnumber_commodity |  | No pagination | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by marcosmarxm** [comment]
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
There only couple of endpoints really provide data can be useful to more large analysis.
Please remove all not useful endpoints and include an array to inform what commodity and country user want to analyze.
Also it must have it must be incremental.

Please make this changes by Nov 12 Tue

**Comment by ombhardwajj** [comment]
I've removed all the non useful streams and added user inputs (arrays) for the commodity codes and country codes they need data for. 🙇 
The really useful endpoints which return really large datasets dont support incremental sync 😞 
@marcosmarxm

**Comment by marcosmarxm** [comment]
Thanks for the contritbution but having paths limit to year it isn't a good option for Builder connectors to make analytics use cases. Because of that I'm declining the contribution

**Pull request closed without merging**
