### PR TITLE
:tada: Source Facebook Marketing - add new Custom Audience stream

### LINKED ISSUE #29396: Source: Facebook Marketing - add new CustomAudience stream
https://developers.facebook.com/docs/marketing-api/reference/custom-audience

Custom Audience

Endpoint:
curl -G \
  -d 'access_token=<ACCESS_TOKEN>' \
  https://graph.facebook.com/v2.11/<CUSTOM_AUDIENCE_ID>
  
  
https://developers.facebook.com/tools/explorer/?method=GET&path=act_212551616838260%2Fcustomaudiences%3Ffields%3Did%2Cdescription%2Clookalike_audience_ids%2Clookalike_spec%2Cname%2Coperation_status%2Cpage_deletion_marked_delete_time%2Cpermission_for_actions%2Cis_value_based%2Ctime_created%2Ctime_updated&version=v17.0

### PR DESCRIPTION
**Pull request by midavadim**
## What
add new Custom Audience stream

## How
https://developers.facebook.com/docs/marketing-api/reference/custom-audience

Custom Audience

curl -G \
  -d 'access_token=<ACCESS_TOKEN>' \
  https://graph.facebook.com/v2.11/<CUSTOM_AUDIENCE_ID>
  
  
  
https://developers.facebook.com/tools/explorer/?method=GET&path=act_212551616838260%2Fcustomaudiences%3Ffields%3Did%2Cdescription%2Clookalike_audience_ids%2Clookalike_spec%2Cname%2Coperation_status%2Cpage_deletion_marked_delete_time%2Cpermission_for_actions%2Cis_value_based%2Ctime_created%2Ctime_updated&version=v17.0

## 🚨 User Impact 🚨
No breaking changes

## Pre-merge Actions
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`3376b0897e`](https://github.com/airbytehq/airbyte/pull/29412/commits/3376b0897e24c0c5f0446087aad378cd7a5aeb81)) - ❌

⏲️  Total pipeline duration: 01mn20s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ❌        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ❌        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/midavadim_29396-facebook-marketing-custom-audience-stream/1692043968/3376b0897e24c0c5f0446087aad378cd7a5aeb81/source-facebook-marketing/1.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:3376b0897e24c0c5f0446087aad378cd7a5aeb81)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`5d04c7ce0e`](https://github.com/airbytehq/airbyte/pull/29412/commits/5d04c7ce0ed81ce62206638c23a5b364031aa24d)) - ❌

⏲️  Total pipeline duration: 01mn17s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ❌        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/midavadim_29396-facebook-marketing-custom-audience-stream/1692044344/5d04c7ce0ed81ce62206638c23a5b364031aa24d/source-facebook-marketing/1.1.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:5d04c7ce0ed81ce62206638c23a5b364031aa24d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`4be01c946e`](https://github.com/airbytehq/airbyte/pull/29412/commits/4be01c946e586c6f1ccd0d7b96c5d6f9d003d43f)) - ❌

⏲️  Total pipeline duration: 82mn06s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/midavadim_29396-facebook-marketing-custom-audience-stream/1692115308/4be01c946e586c6f1ccd0d7b96c5d6f9d003d43f/source-facebook-marketing/1.1.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:4be01c946e586c6f1ccd0d7b96c5d6f9d003d43f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Review by lazebnyi — CHANGES_REQUESTED** [review]
Please update PR description.

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`9bd11b02f9`](https://github.com/airbytehq/airbyte/pull/29412/commits/9bd11b02f91c7d41fdffb029edcd4117c9125825)) - ❌

⏲️  Total pipeline duration: 02mn02s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ❌        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/midavadim_29396-facebook-marketing-custom-audience-stream/1692184508/9bd11b02f91c7d41fdffb029edcd4117c9125825/source-facebook-marketing/1.1.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:9bd11b02f91c7d41fdffb029edcd4117c9125825)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by midavadim** [comment]
> Please update PR description.
@lazebnyi 
updated

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`49c9d93534`](https://github.com/airbytehq/airbyte/pull/29412/commits/49c9d9353486c6fe710d5da0fd7723365204e023)) - ❌

⏲️  Total pipeline duration: 73mn59s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/midavadim_29396-facebook-marketing-custom-audience-stream/1692201033/49c9d9353486c6fe710d5da0fd7723365204e023/source-facebook-marketing/1.1.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:49c9d9353486c6fe710d5da0fd7723365204e023)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`f2f991dd53`](https://github.com/airbytehq/airbyte/pull/29412/commits/f2f991dd53a040182432b83917a325269cc02890)) - ✅

⏲️  Total pipeline duration: 59mn12s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/midavadim_29396-facebook-marketing-custom-audience-stream/1692213794/f2f991dd53a040182432b83917a325269cc02890/source-facebook-marketing/1.1.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f2f991dd53a040182432b83917a325269cc02890)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Review by lazebnyi — APPROVED** [review]

**Pull request merged**
