### PR TITLE
🎉 New Source: Freshservices

### PR DESCRIPTION
**Pull request by tuanchris**
## What
- Add new source Freshservices
- Participating in hacktoberfest-2021 https://github.com/airbytehq/hacktoberfest-2021/issues/55

## How

image
Connector created successfully
image
Airbyte finishes syncing
image
Local JSON files
image
Example output from a JSON file

## Pre-merge Checklist

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Awesome work @tuanchris can you try to run this with a local postgres docker container and use the basic normalization?
Also please fill the checklist so we can follow up the step you're. We're going to review this tomorrow or max by Friday.

**Comment by Zirochkaa** [comment]
@tuanchris hello. Thanks for your contribution. Could you please provide credentials (`domain_name`, `api_key` and `start_date`) for sandbox account so we can test it?

**Comment by Zirochkaa** [comment]
> @Zirochkaa Sent you the credentials in Slack. Let me know if all is good.

Got them. Everything is working, thanks.

**Review by Zirochkaa — CHANGES_REQUESTED** [review]
@tuanchris thanks for your contribution. I would love to get this merged into the codebase, but have some requests for changes to ensure a great user experience. If you have any questions feel free to ask me.

**Review by marcosmarxm — APPROVED** [review]
LGTM is working with integration tests.

@tuanchris for unit tests one suggestion:
```python
@mock.patch("source_freshservice.streams.Tickets.read_records", return_value=iter([1]))
def test_check_connection_success(mocker):
    source = SourceFreshservice()
    logger_mock = MagicMock()
    test_config = MagicMock()
    assert source.check_connection(logger_mock, test_config) == (True, None)


def test_check_connection_failure(mocker, test_config):
    source = SourceFreshservice()
    logger_mock = MagicMock()
    response = source.check_connection(logger_mock, test_config)

    assert response[0] is False
    assert type(response[1]) == HTTPError
```

Please make sure to run `./gradlew format` to format all files, after this I'll merge this contribution.

**Review by marcosmarxm — APPROVED** [review]
LGTM awesome work @tuanchris

**Pull request merged**
