### PR TITLE
Source freshdesk - fix schema

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/oncall/issues/1038

## How
Change `twitter_id` type to string according to their API doc

### CODE REVIEW

**Review by darynaishchenko — APPROVED** [review]

**Review by girarda — APPROVED** [review]
lgtm but Cloud users will need to reset their data because of the schema change @YowanR @TBernstein4

**Comment by YowanR** [comment]
Cc @erica-airbyte for the customer o
[outreach] (https://github.com/airbytehq/airbyte/pull/19496#pullrequestreview-1186945250) bit.

**Comment by erica-airbyte** [comment]
@YowanR and @girarda is this ALL customers that have Freshdesk will need to run a reset?

**Comment by erica-airbyte** [comment]
@girarda do we have that list of customers?

**Comment by pedroslopez** [comment]
@erica-airbyte just pulled the list of active connections syncing `contacts` - looks like two connections and one is internal:

- amalia-airbyte [Freshdesk <> BigQuery - Amalia Test
](https://cloud.airbyte.io/workspaces/af3594f0-6bb3-4f93-888c-c578619d2890/connections/4b42ecf8-3a2e-4e61-b887-f53bb46d9b0b/status)
- Worksuite Inc. [Freshdesk <> Snowflake](https://cloud.airbyte.io/workspaces/f6aee5fd-500e-49a0-8d97-545691b1c19d/connections/09b7efa8-7919-43cd-8e39-c7134b8b7732/status)

**Review by alafanechere — APPROVED** [review]
Approving the changes made to `acceptance-test-config.yml` on behalf of connector operations team. @davydov-d please sync with TCS (@erica-airbyte ) before publishing the new version to ensure they are ready to send customer outreach for reset.

**Comment by erica-airbyte** [comment]
@davydov-d to confirm this only affects customers with the `contacts` stream, correct?

**Comment by davydov-d** [comment]
@erica-airbyte that's right

**Comment by TBernstein4** [comment]
@davydov-d  Comms have been sent out to customers. They were told the update would be deployed between 1 PM UTC - 7 PM UTC tomorrow.

**Pull request merged**
