### PR TITLE
🐛 Source Shopify: Add very low load on Shopify rate limiter

### LINKED ISSUE #32818: 🐛 Source Shopify: not acknowledging higher Shopify plus rate limits
### Connector Name

source-shopify

### Connector Version

1.1.4

### What step the error happened?

Other

### Relevant information

Extracting time from Shopify is slower than needed on the Shopify Plus plan.

Because of Shopify's rate limits, there is a rate limiter code in the source that introduces a wait time between API calls. 

Currently, the lowest wait time (on_low_load) is 0.2 seconds (200 milliseconds). In reality, this produces about 2.5 requests/second, which is 8x lower than what Shopify Plus offers (20 requests/second).

Would it be possible to introduce an even lower wait time to make the extraction of data from Shopify shops with lots of traffic more manageable?

### Relevant log output

_No response_

### Contribute

- [x] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by tejastrzinar**
## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*
It addresses this open issue: https://github.com/airbytehq/airbyte/issues/32818

Speeds up number of requests per second where unnecessarily slow. There was always a hold (wait_time) between each API call even when the bucket is emptied much faster than it is being filled. When the bucket is (almost) empty, there is no need to wait between each API call. 

Before
image
After
image

## How
*Describe the solution*
I added another option in the Shopify rate limiter. Before, the fastest option was a hold of 200 miliseconds between API calls. This was when the bucket was less than half full. 

Now this is true only when the bucket is between 25% and 50% full. When bucket is less than 25% full, it should not hold (wait_time is 0 miliseconds) between the API calls. 

For Shopify Plus users this means that most of the time, there won't be any unnecessary hold, because each API call processeing by this connector already takes more time (cca 200 miliseconds/request) than Shopify is able to process (50 miliseconds/request). For all the other users, they might see a slight speed improvement, but the existing rate limiter will still cover existing loads with conservative holds, so this change should not introduce new limit errors.

## Recommended reading order
1. `source_shopify/utils.py`
2. `source-shopify/unit_tests/test_control_rate_limit.py`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*
No breaking changes. 
End user will see a slight performance improvement at per entity API requests, up to 2x.

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***
Patch (Syncs will be faster)

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter
If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

### CODE REVIEW

**Comment by bazarnov** [comment]
@tejastrzinar Thank you for your contribution! We need to do additional tests before further approval. I'll do my best to review this one shortly.

**Comment by bazarnov** [comment]
@marcosmarxm @tejastrzinar The changes suggested look useful to me. LGTM.

**Comment by bazarnov** [comment]
Moved to `On Hold` indicating the PR merge preps.

**Comment by marcosmarxm** [comment]
Current Shopify tests are failing. Waiting a fix to release this change. Thanks for the patience @tejastrzinar

**Comment by bazarnov** [comment]
@marcosmarxm I encourage everyone involved in this change, to just wait until this one: https://github.com/airbytehq/airbyte/pull/32345 is merged, to avoid regressions.

**Comment by marcosmarxm** [comment]
Is #32345 make this contribution obsolete or invalid this code change?

**Comment by tejastrzinar** [comment]
Just checking... Are you waiting for me to do something here or is this now in your hands?

**Comment by tejastrzinar** [comment]
@bazarnov @marcosmarxm I would like to finish this PR but I'm not certain what I need to do for this to happen.

**Comment by bazarnov** [comment]
> @bazarnov @marcosmarxm I would like to finish this PR but I'm not certain what I need to do for this to happen.

Hello again @tejastrzinar,

I think we should:
1) merge with the latest master (re-base)
2) make your changes on top of it
3) make sure your unit tests are passing locally
4) bump the version in `metadata.yaml` by 1 (last digit - patch)
5) bump the version In `pyproject.toml` by 1 (last digit - patch)
6) format the code properly by running `airbyte-ci format fix all`
7) add the changelog in `docs/integrations/sources/shopify.md` (by following the previous examples in the end of the file)
8) push the changes to the branch
4) poke @bazarnov or @marcosmarxm to finalize it from our side (more tests)

**Comment by bazarnov** [comment]
@marcosmarxm @tejastrzinar 

The changes from this PR are transferred to [this one](https://github.com/airbytehq/airbyte/pull/37589), because there are no movements for the current.

This PR will be closed, as soon as https://github.com/airbytehq/airbyte/pull/37589 is merged into master. 

Just FYI.

**Comment by tejastrzinar** [comment]
Thank you!

**Comment by bazarnov** [comment]
Closing this PR, since the updates are merged into master.

**Pull request closed without merging**
