### PR TITLE
source-infobip contribution from aazam-gh

### LINKED ISSUE #47721: [connector-request] Infobip
### Topic

_No response_

### Relevant information

Topic
New connector request

Relevant information
This is a suggestion to create a connector for Infobip using the UI Connector Builder. The website for the connector is https://infobip.com

### PR DESCRIPTION
**Pull request by aazam-gh**
## What

This PR adds a new connector for source Infobip (source-infobip).

Contributor-provided connector description:

This is the Infobip source that ingests data from the infobip API.

Infobip drives deeper customer engagement with secure, personalized communications across SMS, RCS, Email, Voice, WhatsApp, and more https://www.infobip.com/

In order to use this source, you must first create an Infobip account. Once logged in, you can head over to Developer Tools in the sidebar and click on API Keys. Here you can generate a new API key for authenticating.

You can learn more about the API here https://www.infobip.com/docs/api
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key. The API key associated with your account. |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| people | id | DefaultPaginator | ✅ |  ❌  |
| companies | id | DefaultPaginator | ✅ |  ❌  |
| custom_attributes | name | DefaultPaginator | ✅ |  ❌  |
| forms | id | DefaultPaginator | ✅ |  ❌  |
| conversations | id | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by aazam-gh** [comment]
fixes #47721

**Comment by marcosmarxm** [comment]
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

Make sure you have pagination properly working, the API doesn't have pagination please left a comment making my review easier.
Make sure have a square svg icon
Make sure credentials are valid.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Infobip is message platform and the connector isn't implementing most of messaging platforms available: email, sms, whatsapp etc. If your sandbox account doesn't have permission to this data unfortunately I can't accept the contribution.

Waiting return by Monday if not updates I'm going to close the contribution.

**Comment by aazam-gh** [comment]
This connector will not be possible to implement.

**Pull request closed without merging**
