### PR TITLE
Destination Snowflake: upgrade to latest snowflake jdbc driver

### LINKED ISSUE #25849: Update Snowflake Drivers
> This announcement is to let you know that all partner and customer Snowflake accounts hosted on Google Cloud must update their client drivers to at least the minimum versions listed below by November 1, 2023. These new minimum versions, and all subsequent versions, provide critical fixes needed to continue accessing Snowflake on Google Cloud. Snowflake will therefore no longer support versions older than the new minimum versions for Google Cloud accounts. 
>
> Please note that the deprecation does not impact AWS or Azure partners or customers, who can continue to use driver versions released within the last two years as per the Snowflake Support policy. 
>
> WHY ARE CLIENT UPGRADES REQUIRED FOR GOOGLE CLOUD CUSTOMERS?
Historically, presigned URL API requests to Snowflake GCP buckets only required the payload to be signed. However Google now requires both the request headers and payload to be signed. After the cutover date, once this requirement is enforced, GET and PUT requests to the stage from clients below the minimum version will fail with HTTP Error 400.
>
> To avoid these failures, Snowflake has decided in consultation with Google to switch all drivers from using presigned URL authentication to using GCS downscoped token authentication. 
>
> ACTION TO TAKE:
In response to Google’s changes, Snowflake has released a new set of drivers. All customers with their Snowflake account hosted on Google Cloud must update their client drivers to these minimum versions or later listed below by November 1, 2023.
>
> Partners should also upgrade drivers for their SaaS environments, and should test, and bundle, or recommend at least the minimum supported driver versions for GCP accounts for their customer managed environments. Note that all customers with Snowflake accounts hosted on GCP will receive a communication about this change, so they may reach out to you to ensure that you’re using a supported client driver.
>
> Snowflake will ensure that the older drivers continue to work for GCP accounts until Nov 1, 2023. They will be supported as per the Snowflake Client and Version Support policy for this duration.
>
> After the cutover date, the GET and PUT requests from client drivers below the minimum version will fail with HTTP Error 400. Please see this [KB article for more details](https://go.snowflake.net/MjUyLVJGTy0yMjcAAAGLQ4R7SqWTersInzGkOuD0qClFKQ7JQEQ5NsXaOCdYhhYNNFwGATMBz9aiUshz45Cv0qJ8oQ0=). Please see [this article](https://go.snowflake.net/MjUyLVJGTy0yMjcAAAGLQ4R7SxKvfbmKBo89Kqi9m_53O-eSw-vEKu0yT7zMikoFj0PhWYFkPX_8w_fh2Q03Tc28Dds=) for more information on how to check your current client driver versions in Snowflake.

### PR DESCRIPTION
**Pull request by edgao**
closes https://github.com/airbytehq/airbyte/issues/25849

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-snowflake test report (commit [`bba88a135e`](https://github.com/airbytehq/airbyte/pull/30938/commits/bba88a135ee7bf6769c81253e643e994de578b71)) - ❌

⏲️  Total pipeline duration: 09mn10s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Build connector tar                                           | ✅        |
| Build source-snowflake docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                     | ✅        |
| Java Connector Integration Tests                              | ❌        |
| Acceptance tests                                              | ✅        |
| Validate metadata for source-snowflake                        | ✅        |
| Connector version semver check                                | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_snowflake_jdbc_driver/1696011347/bba88a135ee7bf6769c81253e643e994de578b71/source-snowflake/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:bba88a135ee7bf6769c81253e643e994de578b71)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`bba88a135e`](https://github.com/airbytehq/airbyte/pull/30938/commits/bba88a135ee7bf6769c81253e643e994de578b71)) - ❌

⏲️  Total pipeline duration: 09mn40s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build connector tar                                                | ✅        |
| Build destination-snowflake docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                          | ✅        |
| Java Connector Integration Tests                                   | ✅        |
| Validate metadata for destination-snowflake                        | ✅        |
| Connector version semver check                                     | ✅        |
| Connector version increment check                                  | ❌        |
| QA checks                                                          | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_snowflake_jdbc_driver/1696011347/bba88a135ee7bf6769c81253e643e994de578b71/destination-snowflake/3.1.16/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:bba88a135ee7bf6769c81253e643e994de578b71)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Review by jbfbell — APPROVED** [review]

**Review by evantahler — APPROVED** [review]
lol... that's it?!  It works now?
Maybe we fixed stuff along the Dv2 journey

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`86612c9973`](https://github.com/airbytehq/airbyte/pull/30938/commits/86612c99733ddeeb99ded36d0b26ccaaee9efb0d)) - ✅

⏲️  Total pipeline duration: 09mn04s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build connector tar                                                | ✅        |
| Build destination-snowflake docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                          | ✅        |
| Java Connector Integration Tests                                   | ✅        |
| Validate metadata for destination-snowflake                        | ✅        |
| Connector version semver check                                     | ✅        |
| Connector version increment check                                  | ✅        |
| QA checks                                                          | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_snowflake_jdbc_driver/1696022801/86612c99733ddeeb99ded36d0b26ccaaee9efb0d/destination-snowflake/3.1.17/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:86612c99733ddeeb99ded36d0b26ccaaee9efb0d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by edgao** [comment]
snowflake also released 3.14.x of the driver, and our previous attempt was on 3.13 :P but either way - someone fixed something, somewhere

**Pull request merged**
