### PR TITLE
Add metadata for file secure and bump

### PR DESCRIPTION
**Pull request by bnchrch**
## What
We need to publish the file-secure image since we updated source-file
https://github.com/airbytehq/airbyte/pull/25819/files

Oh and add a metadata file!

### CODE REVIEW

**Review by evantahler — APPROVED** [review]
Thanks! I did not know this existed 😓.

Approving because the failures are metadata related (docs, changelog)

**Comment by bnchrch** [comment]
@evantahler thanks for the approval! and its ok... Our qa-engine also didnt know about this strict encrypt ish version (hence the failing test)

Updating then ill publish and merge

**Comment by bnchrch** [comment]
/publish connector=connectors/source-file-secure run-tests=false

**Pull request merged**
