### PR TITLE
🐛 Source Quickbooks: update following state management changes in the CDK

### PR DESCRIPTION
**Pull request by maxi297**
## What
Breaking changes were done as part of https://github.com/airbytehq/airbyte/commit/a45a1e33413eacccb2b8a83450d1638c48fd2042. This PR fixes the breaking changes for quickbooks.

## How
Updating the interfaces that were affected by breaking changes.

## 🚨 User Impact 🚨
None as the code should have the exact same behavior

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-quickbooks test report (commit [`92ba6dc17b`](https://github.com/airbytehq/airbyte/pull/27803/commits/92ba6dc17b8db7f55c7332115e28eadda88e2b2e)) - ❌

⏲️  Total pipeline duration: 75 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-quickbooks/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-quickbooks docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_quickbooks/1687977454/92ba6dc17b8db7f55c7332115e28eadda88e2b2e/source-quickbooks/2.0.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-quickbooks test
```

**Comment by octavia-squidington-iii** [comment]
##  source-quickbooks test report (commit [`350336e51f`](https://github.com/airbytehq/airbyte/pull/27803/commits/350336e51f87c578238f985c2323c6be2a891b52)) - ✅

⏲️  Total pipeline duration: 479 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-quickbooks/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-quickbooks docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_quickbooks/1687980079/350336e51f87c578238f985c2323c6be2a891b52/source-quickbooks/2.0.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-quickbooks test
```

**Review by artem1205 — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-quickbooks test report (commit [`59520c4633`](https://github.com/airbytehq/airbyte/pull/27803/commits/59520c463339520aff8d265c03cce575d6c19371)) - ✅

⏲️  Total pipeline duration: 484 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-quickbooks/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-quickbooks docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_quickbooks/1687980671/59520c463339520aff8d265c03cce575d6c19371/source-quickbooks/2.0.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-quickbooks test
```

**Comment by octavia-squidington-iii** [comment]
##  source-quickbooks test report (commit [`b9a652896b`](https://github.com/airbytehq/airbyte/pull/27803/commits/b9a652896b4e836f0687d0c71bfc7764672c114b)) - ❌

⏲️  Total pipeline duration: 60 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-quickbooks/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-quickbooks docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_quickbooks/1687991174/b9a652896b4e836f0687d0c71bfc7764672c114b/source-quickbooks/2.0.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-quickbooks test
```

**Comment by octavia-squidington-iii** [comment]
##  source-quickbooks test report (commit [`3f464a991a`](https://github.com/airbytehq/airbyte/pull/27803/commits/3f464a991a3431913aee8ae708ef2233aff37c96)) - ✅

⏲️  Total pipeline duration: 386 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-quickbooks/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-quickbooks docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_quickbooks/1687991600/3f464a991a3431913aee8ae708ef2233aff37c96/source-quickbooks/2.0.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-quickbooks test
```

**Comment by octavia-squidington-iii** [comment]
##  source-quickbooks test report (commit [`cc846bc487`](https://github.com/airbytehq/airbyte/pull/27803/commits/cc846bc487a6be8bd3d319093871d3684ed0bfdd)) - ✅

⏲️  Total pipeline duration: 427 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-quickbooks/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-quickbooks docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_quickbooks/1688043314/cc846bc487a6be8bd3d319093871d3684ed0bfdd/source-quickbooks/2.0.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-quickbooks test
```

**Comment by octavia-squidington-iii** [comment]
##  source-quickbooks test report (commit [`2b390c73b8`](https://github.com/airbytehq/airbyte/pull/27803/commits/2b390c73b8260e455c204d2681cd1badef79d6ab)) - ✅

⏲️  Total pipeline duration: 393 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-quickbooks/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-quickbooks docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_quickbooks/1688043857/2b390c73b8260e455c204d2681cd1badef79d6ab/source-quickbooks/2.0.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-quickbooks test
```

**Pull request merged**
