### PR TITLE
Include credentials in API requests

### PR DESCRIPTION
**Pull request by bkrausz**
## What
I have an nginx proxy in front of the app/API that does HTTPS and [auth](https://github.com/vouch/vouch-proxy) on different subdomains (e.g. `https://airbyte.example.team` & `https://airbyte-api.example.team`). It does this via a cookie on the domain.

I can use nginx to setup all the rules I need for the api-side (specifically CORS), but unless the frontend passes `credentials: 'include'` to `fetch`, the cookie never gets sent through and the auth fails.

Given that Airbyte doesn't offer auth yet, this seems like a pattern others are likely to repeat, so default including credentials seems correct. Additionally, once Airbyte does provide some kind of auth, this will likely be necessary anyway (assuming cookie-based auth is chosen).

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

### CODE REVIEW

**Comment by michel-tricot** [comment]
@bkrausz this is amazing! I had this exact issue recently as I was trying to use GCP Identity-Aware Proxy, but never got to fix it.

I will let @Jamakase do the review!

**Comment by Jamakase** [comment]
Thank you for this request, I have not even thought about such a case with auth.

@bkrausz I suppose adding it only in `AirbyteRequestService` is not enough. `fetch` is also used directly in `BaseResource` so probably it's required to add it there too, otherwise not all the requests will send the credentials.

The overall idea is, of course, to use `AirbyteRequestService.fetch` in all services, but I have not finished migration to it yet.

However, I am not sure that this will work with changes on UI only. According to [docs](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) for `credentials`:

```
Access-Control-Allow-Origin is prohibited from using a wildcard for requests with credentials: 'include'. In such cases, the exact origin must be provided; even if you are using a CORS unblocker extension, the requests will still fail.
```

What is more, shouldn't we also add `Access-Control-Allow-Credentials` to the response of backend Options request?

Finally, what about security? Is it possible that we somehow make it less secure for all other users? What about CSRF? I can't figure out the case out of my head, but changing `credentials` from `same-origin` to `include` should be always considered as a potential security downgrade. ( @michel-tricot )

**Review by jamakase — CHANGES_REQUESTED** [review]
Additional changes required on both FE and BE side based on my comment above.

**Comment by bkrausz** [comment]
Thanks for the review @Jamakase. Some responses:

> I suppose adding it only in AirbyteRequestService is not enough. fetch is also used directly in BaseResource so probably it's required to add it there too, otherwise not all the requests will send the credentials.

Good catch, will dig deeper and get a full implementation out.

> However, I am not sure that this will work with changes on UI only.
> What is more, shouldn't we also add Access-Control-Allow-Credentials to the response of backend Options request?

The goal here is not to enable Airbyte to work directly with subdomains, it's to make it possible to set that up without changing the source code. I'm using Airbyte behind an nginx proxy, where I do:

```
      add_header Access-Control-Allow-Origin      "https://airbyte.example.team" always;
      add_header Access-Control-Allow-Credentials "true" always;
      add_header Access-Control-Allow-Headers     "Content-Type" always;
      add_header Access-Control-Allow-Methods     "GET,HEAD,PUT,PATCH,POST,DELETE" always;

      if ($request_method = 'OPTIONS') {
        return 204;
      }

      proxy_pass http://airbyte-tunnel:8001/;
```

This effectively solves the backend portion of things. While it would be great to have native support for this, there are questions like configuration that need to be answered. Given that Airbyte doesn't support SSL or auth yet, it seems like running behind an nginx proxy will be popular (we do this with all of our internal services), and built-in CORS backend support can be answered once SSL and auth is addressed.

I'm happy to put together a guide on setting up nginx in front of Airbyte so that other users can more easily benefit from this immediately.

> Finally, what about security?

The bigger security implications come from the use of CORS headers, where lazy configuration of those (for ex, setting `Access-Control-Allow-Origin` to `*`) can have major implications for things like CSRF. From my experience (not as a dedicated security expert but as someone who pays a fair bit of attention to these edge cases), `credentials: "include"` is safe when used with a correctly CORS headers.

If you have any specific concerns there happy to think through them. I definitely agree that a `credentials` downgrade should be considered carefully, but in this case I believe it's peaceful.


LMK if you're OK with just the frontend side given above. If so, I can get a more thorough `fetch` update out tomorrow.

**Comment by Jamakase** [comment]
@bkrausz Thank you for your detailed response. It really clarifies some things for me.

Based on your response, I suppose that the fix with `credentials: include` will work with only some additional changes for nginx or some sort of proxy, because currently, frontend calls backend directly and as backend has next configuration

```
    responseContext.getHeaders().add(ALLOW_ORIGIN, "*");
    responseContext.getHeaders().add(ALLOW_HEADERS, "Origin, Content-Type, Accept, Content-Encoding");
    responseContext.getHeaders().add(ALLOW_METHODS, "GET, POST, PUT, DELETE, OPTIONS, HEAD");
```

I am quite confident that changing it only on UI side will break the current interaction with backend because headers won't fit correctly.

> If you have any specific concerns there happy to think through them. I definitely agree that credentials downgrade should > be considered carefully, but in this case I believe it's peaceful.

Yeah, I think that it is not critical too, but I just want to consider all the downsides of such a decision.

It is totally possible though, that we may want to have it some sort of config for webapp, so when user wants - he can specify cookie policy otherwise it is a default configuration. If we merge the changes above it means that it will work fine with only backend hidden under nginx, because it will start to reject requests with `strict-origin-when-cross-origin` and `has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.`

Probably, the backend team could help us here with the best way to go. I see that Charles joined here too, so @cgardens let us know what you think.

**Comment by bkrausz** [comment]
Ah, I completely missed that in my initial dig into the source code. Seems like we could either add the `-Credentials` header to backend (unnecessary but would avoid any configuration needs) or expose the appropriate config to override fetch credentials and/or backend CORS headers. Will defer to @cgardens on the best approach but I'm happy to help implement anything you decide.

**Comment by bkrausz** [comment]
I realized I had gotten a bit single-minded with getting `credentials: "include"` in as my solution, when instead I could put the API and app on the same domain. For future Airbyte users, here's the general shape of nginx config:

```
server {
    listen 10000;
    server_name airbyte.example.team;

    # ... bunch of auth redirect stuff ...

    location /api {
      proxy_pass http://airbyte-tunnel:8001/api;
    }

    location / {
      proxy_pass http://airbyte-tunnel:8000/;
    }
}
```

Easy squeezy! Gonna close this out given the number of open questions and lack of a personal use case, but if it is still desirable let me know, happy to implement some changes to get this out regardless.

**Comment by cgardens** [comment]
Thanks for sharing this! Created a follow up issue to figure out if we should do more here.

**Pull request closed without merging**
