### PR TITLE
Destination Bigquery: add AIRBYTE_ENTRYPOINT env var for kube process

### PR DESCRIPTION
**Pull request by edgao**
## What
When running in kube, airbyte overrides the entrypoint using AIRBYTE_ENTRYPOINT. Set that variable correctly.

### CODE REVIEW

**Comment by edgao** [comment]
/publish connector=connectors/destination-bigquery pre-release=true run-tests=false

**Comment by edgao** [comment]
/publish connector=connectors/destination-bigquery pre-release=true run-tests=false

**Comment by edgao** [comment]
/publish connector=connectors/destination-bigquery pre-release=true run-tests=false

**Review by jbfbell — APPROVED** [review]

**Pull request merged**
