### PR TITLE
db-sources-java-cdk: fix logic to calculate the state stats count in db sources iterator

### PR DESCRIPTION
**Pull request by subodh1810**
Issue : https://github.com/airbytehq/airbyte/issues/34918

### CODE REVIEW

**Review by xiaohansong — APPROVED** [review]
thanks for the fix!

**Review by akashkulk — DISMISSED** [review]
As discussed in slack, can you bump Postgres version and bump the cdk it is using too?

**Comment by subodh1810** [comment]
Postgres tests pass with the cdk changes
Screenshot 2024-02-08 at 1 15 48 AM

**Pull request merged**
