### PR TITLE
Destination Snowflake: add snowflake transaction wrapper for rollback support

### LINKED ISSUE #46936: [destination-snowflake] incorrect transaction handling leads to missing data
### Connector Name

destination-snowflake

### Connector Version

3.11.7

### What step the error happened?

During the sync

### Relevant information

I believe there is a critical bug in snowflake destination. When you run a snowflake destination with `append+deduped`, it generates the following structure (more or less):
```sql
begin transaction;
  insert into table ...;
  delete from table ...;
  ...
commit;
```
The begin transaction; and commit; parts are added by some utility function called transactionally.
The issue with snowflake is that the commits are session level and not transaction level. So in case the delete fails, the insert will still be committed. Airbyte then detects the failure and reruns the transaction. Now we have inserted the same records twice, and when the delete runs, the way it is written, it deletes both of the records. I believe this to be a major issue.
What should work for snowflake is to wrap the transaction in a script block and handle the exception. Something like:
```sql
BEGIN
  begin transaction;
    INSERT INTO table ...;
    DELETE FROM table ...;
  commit;
EXCEPTION
WHEN OTHER THEN
  ROLLBACK;
END;
```
I believe the fix is small, but not sure where to do it as I don't understand the architecture very well.

To reproduce snowflake's behaviour, you can run:
```sql
begin transaction;
INSERT INTO employees (employee_ID, last_name, department_ID) VALUES

    (107, 'Richards', 1),

    (108, 'Paulson',  1),

    (109, 'Johnson',  2);

INSERT INTO employees (employee_ID, last_name, department_ID) VALUES

    (107, 'Richards', 1),

    (108, 'Paulson',  1),

    (109, 'Johnson',  2),
    
    ('kuku', 'Johnson',  2);
commit;
```
You will see that the first insert was indeed committed, although the second one fails.
This code does the job:
```sql
BEGIN
begin transaction;
INSERT INTO employees (employee_ID, last_name, department_ID) VALUES

    (107, 'Richards', 1),

    (108, 'Paulson',  1),

    (109, 'Johnson',  2);

INSERT INTO employees (employee_ID, last_name, department_ID) VALUES

    (107, 'Richards', 1),

    (108, 'Paulson',  1),

    (109, 'Johnson',  2),

    ('kuku', 'Johnson',  2);
commit;
EXCEPTION
WHEN OTHER THEN
    ROLLBACK;
END;
```

### Relevant log output

_No response_

### Contribute

- [x] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by zeev-finaloop**
## What
This PR is solving transaction rollback in Snowflake.
Currently in destination-snowflake we may have corrupt state of data in the destination due to incorrect assumptions on snowflake transaction management.

fixes #46936

## How
We have added a dedicated transactionally method for snowflake that wraps the transaction in a script block, catches an exceptions and rolls back the changes.

## Review guide
1. `SnowflakeDestinationHandler.kt`

## User Impact
No visible impact

## Can this PR be safely reverted and rolled back?
- [X] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by natikgadzhi** [comment]
/bump-version type="patch" changelog="Adding Snowflake transaction wrapper"

**Comment by natikgadzhi** [comment]
Thank you for this! 

I kicked off the CI and bumped the version of the connector. This needs a proper review from @airbytehq/destinations team.

**Review by edgao — COMMENTED** [review]
does this work if instead of manually wrapping the sql, you replace the `sql.asSqlStrings` (line 249) call with this: (I'm probably getting the syntax wrong, but approximately something like it)
```kotlin
val transactions = sql.asSqlStrings(
  "BEGIN; BEGIN TRANSACTION",
  """
  COMMIT;
  EXCEPTION
    WHEN OTHER THEN
      ROLLBACK;
      BEGIN
      RAISE;
        END;
  END;
  """.trimIndent()
)
```

**Comment by zeev-finaloop** [comment]
> does this work if instead of manually wrapping the sql, you replace the `sql.asSqlStrings` (line 249) call with this: (I'm probably getting the syntax wrong, but approximately something like it)
> 
> ```kotlin
> val transactions = sql.asSqlStrings(
>   "BEGIN; BEGIN TRANSACTION",
>   """
>   COMMIT;
>   EXCEPTION
>     WHEN OTHER THEN
>       ROLLBACK;
>       BEGIN
>       RAISE;
>         END;
>   END;
>   """.trimIndent()
> )
> ```

@edgao I think this may work with slight changes. I wanted to separate between transaction wrapping and snowflake script block wrapping. As I thought about it, `sql.asSqlStrings` would handle the transaction wrap and the new method adds the script block. Would you prefer me to implement as you suggested? I can make the change and run it

**Comment by edgao** [comment]
yeah I think it would be preferable to use the same string-wrapper for both, to avoid future maintainers needing to notice the separate implementation

(obviously if it makes things really messy for some reason, we can go with what you have though)

**Comment by zeev-finaloop** [comment]
> yeah I think it would be preferable to use the same string-wrapper for both, to avoid future maintainers needing to notice the separate implementation
> 
> (obviously if it makes things really messy for some reason, we can go with what you have though)

change submitted, please trigger the pipeline

**Review by edgao — APPROVED** [review]
@marcosmarxm how do I trigger CI 😀

**Comment by marcosmarxm** [comment]
Done for you

**Pull request merged**
