### PR TITLE
Better formatting/logging for pre-sync data

### PR DESCRIPTION
**Pull request by akashkulk**
Better logging includes
- Human readable formatting for table estimates + number of rows
- Include cursor information with indexes to quickly verify if cursor field is indexed

### CODE REVIEW

**Review by rodireich — APPROVED** [review]

**Comment by akashkulk** [comment]
/publish connector=connectors/source-postgres run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-postgres-strict-encrypt run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-postgres run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-postgres-strict-encrypt run-tests=false

**Comment by akashkulk** [comment]
Need to fix failing checks. Have deleted published images for now, so will need to go back and take a look

**Comment by akashkulk** [comment]
/publish connector=connectors/source-postgres run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-postgres-strict-encrypt run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-postgres run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-postgres-strict-encrypt run-tests=false

**Pull request merged**
