### PR TITLE
✨ Destination Databricks: connector supports schema evolution (schemaMerge) #26658

### LINKED ISSUE #26658: Destination Databricks: connector should support schema evolution (schemaMerge)
### What area the feature impact?

Connectors

### Revelant Information

Databricks and its delta tables support schema evolution via the `COPY INTO` command parameter's `mergeSchema=true`. The connector should provide a parameter to enable or disable schema evolution.

In https://github.com/airbytehq/airbyte/pull/26942, we added an option in the connector configuration interface to enable or disable schema evolution:
image

This option, once enabled, sets the following parameter to the [COPY INTO](https://docs.databricks.com/sql/language-manual/delta-copy-into.html#parameters) statement used to load the data into the destination table (set to `false` by default): `COPY_OPTIONS ('mergeSchema' = 'true')`

We conducted some tests locally and it works great so far. We planned on running it in production in the coming weeks.

### PR DESCRIPTION
**Pull request by gpodevijn**
Destination Databicks: connector should support schema evolution (schemaMerge) closes #26658

## What
In this PR, we extend the Databricks destination connector to support schema evolution, i.e., when a source schema is changed in the source and that the schema changed is approved in the UI, the Databricks connector is able to replicate the schema changes in the destination. We added an option in the connector's configuration to enable or disable schema evolution. When enabled, schema evolution is supported for all streams.

image

## How
Databricks' `COPY INTO` has [options](https://docs.databricks.com/sql/language-manual/delta-copy-into.html#parameters) to control the operation of ifs command. One of this options is the boolean `mergeSchema`, which, if set to `true`, makes the schema evolved according to the incoming data.

Based on the newly added option that can be configured in the connector's configuration (see screenshot above), the value of this `mergeSchema` option is either set to `true` or `false` (default).

## Recommended reading order
1. `airbyte-integrations/connectors/destination-databricks/src/main/java/io/airbyte/integrations/destination/databricks/s3/DatabricksS3StreamCopier.java`
2. `airbyte-integrations/connectors/destination-databricks/src/main/java/io/airbyte/integrations/destination/databricks/utils/DatabricksConstants.java`
3. `airbyte-integrations/connectors/destination-databricks/src/main/java/io/airbyte/integrations/destination/databricks/DatabricksDestinationConfig.java`
4. `airbyte-integrations/connectors/destination-databricks/src/main/resources/spec.json`
5. `airbyte-integrations/connectors/destination-databricks/src/test/java/io/airbyte/integrations/destination/databricks/DatabricksDestinationConfigTest.java`
6. `airbyte-integrations/connectors/destination-databricks/src/test/resources/config.json`
7. `airbyte-integrations/connectors/destination-databricks/Dockerfile`
8. `airbyte-integrations/connectors/destination-databricks/metadata.yaml`
9. `docs/integrations/destinations/databricks.md`

## 🚨 User Impact 🚨

There are no breaking changes. The end-user can enable or disable schema evolution in the Databricks destination connector from the UI.

We bumped the `minor` code of the connector semantic version because the PR adds a non-required parameter to the connector.

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Review by evantahler — CHANGES_REQUESTED** [review]
These changes look pretty good!  I like the default option and the test.  Well done!

Can you please rebase this on master and also update the metadata.yaml file with the new version?

**Comment by gpodevijn** [comment]
> These changes look pretty good! I like the default option and the test. Well done!
> 
> Can you please rebase this on master and also update the metadata.yaml file with the new version?

Thank you @evantahler. I rebased from master, but I'm not sure if you're talking about another [manifest file than this one](https://github.com/airbytehq/airbyte/pull/26942/files#diff-77bd4907bd00b03976379066e7cc5051eebcf940c74fc05bbaf2fa7aa813ee82) (or if my PR is wrong about it) ?

**Comment by evantahler** [comment]
> Thank you @evantahler. I rebased from master, but I'm not sure if you're talking about another [manifest file than this one](https://github.com/airbytehq/airbyte/pull/26942/files#diff-77bd4907bd00b03976379066e7cc5051eebcf940c74fc05bbaf2fa7aa813ee82) (or if my PR is wrong about it) ?

That's the one! I think this PR is 🟢!

**Review by evantahler — APPROVED** [review]

**Pull request merged**
