### PR TITLE
Source Hubspot: set `threadId` to string in  `engagements` stream

### LINKED ISSUE #28236: Source Hubspot: Engagement stream on Bigquery(denormalized) - field: metadata incompatible type
### Connector Name

source-hubspot

### Connector Version

1.0.1

### What step the error happened?

During the sync

### Revelant information

The Hubspot engagement stream is failing on sync when using Bigquery(denormalized-typed-struct) destination due to incompatible data type for certain field. 

The stream will sync successfully if the metadata field is disabled. 

The same stream did not have any issue using the regular version of Bigquery destination. 

### Relevant log output

```shell
For more details see Big Query Error collection: BigQueryError{reason=invalidQuery, location=query, message=Field metadata.threadId has incompatible types. Configured schema: string; Avro file: record.}:
```

### Contribute

- [ ] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by arsenlosenko**
## What
Resolve issue describe here:
https://github.com/airbytehq/airbyte/issues/28236

## How
Specified `threadId` property in `engagements` metadata to string, as this is the correct type which is returned during reading of this stream.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`d518e461bf`](https://github.com/airbytehq/airbyte/pull/29248/commits/d518e461bfdaa1c6a77982bbcde5c19eb807401f)) - ❌

⏲️  Total pipeline duration: 11mn48s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_28236-source-hubspot-update-engagements-metadata/1691582065/d518e461bfdaa1c6a77982bbcde5c19eb807401f/source-hubspot/1.3.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d518e461bfdaa1c6a77982bbcde5c19eb807401f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`fe3f21d906`](https://github.com/airbytehq/airbyte/pull/29248/commits/fe3f21d906afe8bcb6441bbf96fde500878b9027)) - ❌

⏲️  Total pipeline duration: 11mn10s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_28236-source-hubspot-update-engagements-metadata/1691582903/fe3f21d906afe8bcb6441bbf96fde500878b9027/source-hubspot/1.3.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:fe3f21d906afe8bcb6441bbf96fde500878b9027)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`fb0df2077d`](https://github.com/airbytehq/airbyte/pull/29248/commits/fb0df2077d3eca29f200006176348aa053ff8c36)) - ✅

⏲️  Total pipeline duration: 11mn42s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_28236-source-hubspot-update-engagements-metadata/1691583771/fb0df2077d3eca29f200006176348aa053ff8c36/source-hubspot/1.3.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:fb0df2077d3eca29f200006176348aa053ff8c36)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Review by bazarnov — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`39445597a3`](https://github.com/airbytehq/airbyte/pull/29248/commits/39445597a397c69dfa3219bbd8f02e65ac0f9b3e)) - ✅

⏲️  Total pipeline duration: 11mn49s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_28236-source-hubspot-update-engagements-metadata/1691665132/39445597a397c69dfa3219bbd8f02e65ac0f9b3e/source-hubspot/1.3.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:39445597a397c69dfa3219bbd8f02e65ac0f9b3e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Review by lazebnyi — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`b1bdb40f1d`](https://github.com/airbytehq/airbyte/pull/29248/commits/b1bdb40f1d5b5580655b1dacd14001bbb336a77e)) - ✅

⏲️  Total pipeline duration: 11mn13s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_28236-source-hubspot-update-engagements-metadata/1691753494/b1bdb40f1d5b5580655b1dacd14001bbb336a77e/source-hubspot/1.3.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b1bdb40f1d5b5580655b1dacd14001bbb336a77e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Pull request merged**
