### PR TITLE
🐛 Source Google Ads: fix stream *Campaigns* primary keys for incremental load

### PR DESCRIPTION
**Pull request by hanslemm**
## What
Original PR discussion [here](https://github.com/airbytehq/airbyte/pull/23764) - I've accidentally closed it. 
The current version of the GAds API returns, for the *Campaigns* stream, the `segments.hour` field. This field is part of the composite key that uniquely identifies each row, but currently is not considered, leading to a wrong incremental process. 

## How
I've simply added the `segments.hour` field to the stream code that pre-selects the candidate columns to be used for the SCD strategy.

## Recommended reading order
1. `/airbyte-integrations/connectors/source-google-ads/source_google_ads/streams.py`

## 🚨 User Impact 🚨
No user impact. 

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Comment by hanslemm** [comment]
@evantahler Sorry I've accidentally closed the original PR.

**Comment by evantahler** [comment]
No problem! Add the changelog entry back and this should be good to go!

**Review by evantahler — APPROVED** [review]

**Comment by octavia-approvington** [comment]
Trying to merge your PR using a bot?
Comment this on the PR:
```
/approve-and-merge reason="<STATE YOUR REASON HERE>"
```
Make sure you've reviewed the [docs](https://internal-docs.airbyte.io/How-Tos/Overriding-PR-Merge-Rules)!

**Comment by octavia-approvington** [comment]
Send it! <br/> rocket socks

**Review by octavia-approvington — APPROVED** [review]

**Comment by hbd** [comment]
Hey all, this is already merged, but I want to note that this is potentially a breaking change for many users of the source. Due to the change in a campaign's unique key, a pipeline which constructs a key without the new hour field will end up with only a single record (one segment hour) for a particular segment date.

**Pull request merged**
