### PR TITLE
🐛Source Rss: Fix Incremental Sync

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
Fix Incremental sync for Rss Source

## User Impact
Not breaking change

### CODE REVIEW

**Comment by btkcodedev** [comment]
Local `airbyte-ci` result: all pass
image

**Review by girarda — APPROVED** [review]
looks good! thanks for the quick turnaround

**Review by girarda — CHANGES_REQUESTED** [review]
I'll run a few tests to confirm this works as expected and re-approve

**Review by girarda — APPROVED** [review]
confirmed incremental reads work as expected

**Pull request merged**
