### PR TITLE
🎉 New Source: Azure Blob Storage

### PR DESCRIPTION
**Pull request by itaseskii**
## What
Adds new Azure Blob Storage source connector
#9374

## Recommended reading order
1. AzureBlobStorageConfig.java
2. AzureBlobStorageSource,java
3. AzureBlobStorageStateManager.java
4. AzureBlobStorageOperations.java
5. AzureBlob.java
6. AzureBlobAdditionalProperties.java
7. JsonlAzureBlobStorageOperations.java

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist

<strong>New Connector</strong>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [x] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

### CODE REVIEW

**Comment by natalyjazzviolin** [comment]
@itaseskii could you please:
1. Make sure the CLA is signed by this account.
2. Go through the new connector checklist in the main comment.
3. Run intergration tests locally and include the logs.

Thanks!

**Comment by itaseskii** [comment]
Screenshot_20230217_220003

**Comment by itaseskii** [comment]
Hey @natalyjazzviolin 

1.  Unfortunately I can't sign the CLA with my other account since it is not a Github account. This is not the first time this has happened since I change between repos/users frequently on my local machine.
2.  Done. 
3.  I have posted an [image](https://github.com/airbytehq/airbyte/pull/23222#issuecomment-1447095274) of the passing acceptance tests.

**Comment by YowanR** [comment]
@sajarin Can you take a look, please?

**Comment by sajarin** [comment]
Thanks for the contribution @itaseskii, I'll have an update for you either today or tomorrow, we'll get this merged soon!

**Comment by sajarin** [comment]
Hey @itaseskii looks good, would you happen to have any test credentials you can share?

**Comment by itaseskii** [comment]
> Hey @itaseskii looks good, would you happen to have any test credentials you can share?

Hey @sajarin, you don't need testing credentials since the connector is using the Azurite emulator for azure blob storage in order to run the acceptance tests. https://github.com/airbytehq/airbyte/pull/23222/files#diff-c242ce3e6fe5cb0655d4c912a5bcd5beb1897fb242ccf8a3d98ced74e1115246

**Comment by marcosmarxm** [comment]
@itaseskii any reasons to close the PR?

**Review by marcosmarxm — APPROVED** [review]

**Comment by marcosmarxm** [comment]
@itaseskii I'm closing this in favor of https://github.com/airbytehq/airbyte/pull/24767 to publish the connector. Thanks for the contribution!

**Pull request closed without merging**
