### PR TITLE
Remove Schema from Stream Name

### PR DESCRIPTION
**Pull request by davinchia**
## What
Rehash of https://github.com/airbytehq/airbyte/pull/2807.

This was reverted since there is a required UI change and there is a slight bug.

## How
See the previous PR.

## Pre-merge Checklist
- [x] *Run integration tests*

### CODE REVIEW

**Review by cgardens — APPROVED** [review]
this approval is a rubber stamp. not going through this terribly closely because i have reviewed each individual PR that went into it. 

if there is something you'd like me to consider again more closely, lmk and i'm happy to do it.

**Comment by davinchia** [comment]
all these tests have been run each time before merging. I'm being conservative and running them again since this change touches alot of connectors.

**Comment by davinchia** [comment]
Did a manual check to double check if this will require a migration. I started a server on master, conducted a sync, started a server on this branch. Everything worked good!

**Pull request merged**
