### PR TITLE
🎉 New Source: Attio

### PR DESCRIPTION
**Pull request by mulholo**
Re-opening https://github.com/airbytehq/airbyte/pull/34271 after surprise closure

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@mulholo, unfortunately the project isn't currently accepting new sources using the Python CDK. Right now, we're putting a lot of effort into migrating existing connectors to the low-code framework. This helps us provide stable and easy-to-maintain connectors.
You can still publish your connector and encourage Attio customers to use it to get data from the service.

**Comment by natikgadzhi** [comment]
Hey @mulholo, thank you for putting this together! @marcosmarxm is right, we're currently not able to accept new connectors built wit Python CDK, and focus on low-code CDK / declarative manifest connectors. It's pretty powerful (i.e. Slack, Notion, Gitlab, and Intercom all migrate to low-code, so it's not like it isn't capable), and we think 95%+ of connectors should be low-code manifests.

There are several example pull requests around migrating rather large sources. Would you be open to rewriting this in low-code?

**Comment by mulholo** [comment]
CleanShot 2024-04-10 at 11 52 01@2x

Looking at your docs, the limitations on dynamic schemas does, indeed, seem like it will be an issue for us.

**Comment by natikgadzhi** [comment]
@mulholo, thank you for taking a look!

I see three paths forward:

1. If there's just one particular pattern that's not in the low-code CDK, we _could_ see if we can unblock it for you. Attio is not the only dynamic schema vendor, I believe it was somewhere on our feature requests list. Let's say schemaless streams are solved, there will be more challenges — would you need _the list of streams itself_ to be dynamic, or would we provide a set of streams that are _always_ present, and another stream called `resources` let's say, and inside there would be records with `type` field? Anyway, you get the idea, we try to put the patterns in the low-code CDK, and you use them.
2. We're in conversations internally **partner-supported** connectors. That's the concept where we accept a connector into our registry and provide tools for automated testing, metadata checks, the usual CI. The connector would be available on Cloud and OSS, but we figure out a way to pipe support questions and github issues to you, and you're responsible for reasonable turnaround time on issue triage and PR review. Would that work? If yes, we could move forward with the Python CDK source. 
3. You could build the Python CDK source and I could help you run our CI against it, but when it's ready, instead of merging it in, you build it as custom source connector and tell your users to install it on their Airbyte OSS clusters as a custom connector, providing the docker image to them. Some of our current partners do that — like Planetscale. 


In terms of timing, path 2 is likely the fastest. We still have a hickup that our CI doesn't love PRs from forks, but I can copy it over so it runs checks, and work with you to align with our new guidelines and we could get it in, contingent on our partner-supported conncetors thing, which I will have more clarity on next week. 

What do you think? 

Happy to talk more if you'd like — natik at airbyte doht io

**Comment by mulholo** [comment]
## Option 1: Low-code CDK updates

> * If there's just one particular pattern that's not in the low-code CDK, we _could_ see if we can unblock it for you. Attio is not the only dynamic schema vendor, I believe it was somewhere on our feature requests list. Let's say schemaless streams are solved, there will be more challenges — would you need _the list of streams itself_ to be dynamic, or would we provide a set of streams that are _always_ present, and another stream called `resources` let's say, and inside there would be records with `type` field? Anyway, you get the idea, we try to put the patterns in the low-code CDK, and you use them.

The approach I've gone with in this PR is to make the list of streams itself dynamic. Additionally, the data within those stream is also dynamic. Furthermore, we do not merely toggle a list of attributes on/off for each stream, but those attributes are themselves expressed by a series of configuration options. For example, an attribute may be one of many types (text, checkbox, number, currency, record reference, ...), may be single or multi-select and may be restricted in other ways (e.g. record references may only be allowed to point at some kinds of objects, ...). In other words, both the tables and the columns will vary by customer, and the amount of variation we need to express in the columns is quite large.

I've done a lot in this PR to make the attributes as usable as possible for a database. As one example, I've done some work to simplify 'record reference' attributes in Attio. Attio records, such as people, companies and deals, can reference other records. For example, we have a company attribute on a person which points to a company record.

The person response we get back from Attio is something like this:

```jsonb
{
  "team": [{
    "target_record_id": "19e21043-2b44-4a12-a0ea-2196a1196863",
    "target_object": "company"
  }],
  // other values...
}
```

If we just dump the whole thing into a table with a 'team' column, we'd get a relatively unusable bit of JSON. However, we can read the attribute definition for 'team' and know that this is an attribute for a single type of object ('company') and that this will have zero or one values, not many. As a result, we can simplify the response to just the ID ("19e21043-2b44-4a12-a0ea-2196a1196863"). This is very useful in an ETL context as it means that users can now do SQL joins using this ID very easily. Otherwise, the user needs to write some awkward and erorr-prone JSON transformations in SQL. You can see the code that implements this simplification here: https://github.com/attio/airbyte/blob/b78a0fd10ed4b511cbdd01f2dcef50ae6974c42d/airbyte-integrations/connectors/source-attio/source_attio/source.py#L293

Really, what I need here is a fine-grained ability to define the schema for one stream in terms of another. In this case, I am defining records in terms of attributes.

If we can do all of that in Low-code, I'd be happy. However, it sounds from your response above that this kind of thing is a little far out in your roadmap. Please correct me if I'm wrong!

## Option 2: Partner Supported

I like this approach as it means that the current code is usable, we get a fully featured integration and a short time to delivery. Would this also mean that we get an official stamp of approval where it appears to users that Attio is an official connection?

If we go with this option, I'd love to chat with your team in detail about what we need to get this PR merged.

This is currently looking like my preferred option but I'll check in with our team about the ongoing maintenance implications. **I'll try and get back to you today with more information**.

## Option 3: Docker Image

We've got some customers chomping at the bit for this integration who have actually chanced across my PRs and gone with this approach themselves. In that sense, we're already using this option! However, this obviously requires some hacking on the customer's end and only works for Airbyte OSS. We'd love to share our connector with those using Airbyte cloud as well.

**Comment by mulholo** [comment]
> This is currently looking like my preferred option but I'll check in with our team about the ongoing maintenance implications. I'll try and get back to you today with more information.

Following up on this: we'd like to go with the partner-supported option and are happy with the maintenance burden for the immediate future. I'll follow up by email on how we concretely get this PR merged.

**Comment by natikgadzhi** [comment]
@mulholo we will move forward with another one of our partners in the coming weeks, and I would love to get this started. 

Want to dust this off and upgrade to recent CDK?

**Comment by mikobits** [comment]
im very much looking forward to this becoming part of the core

**Comment by mikobits** [comment]
@airbyte-jenny @airbyteio @cmm-airbyte @nora-airbyte Hey Airbyte guys, there are a ton of Attio users that would just like you guys to pull the great work that @mulholo has already done. 

You shouldnt force him to go low code, it doesnt make any sense at all for Attio customers nor Airbyte customers. Attio has a very dynamic schema and doesnt easliy get fixed to a static schema.

Just escalate this and make Attio an official partner and allow them to maintain the python CDK implementation you will make many customer and users happy and you will bring a lot of good traffic to you from the Attio community.

**Comment by natikgadzhi** [comment]
Uh, that's the plan, @mikobits ;)

@mulholo, we are starting our first partner connectors already, and I'm happy to help and get this merged, just want to make sure this is fresh and ready to go.

One thing I do ask for is to upgrade your the latest CDK, and make sure you're using the base image builds and poetry, I'll take a Quick Look if that's already the case.

**Pull request closed without merging**
