### PR TITLE
Make destination-clickhouse-strict-encrypt use the correct class

### PR DESCRIPTION
**Pull request by grishick**
## What
destination-clickhouse-strict-encrypt is using `ClickhouseDestination` as the `mainClass` in the build, which means that it is not removing SSL option from the UI. This change fixes `build.gradle` and bumps the version of destination-clickhouse-strict-encrypt.
This change also bumps the version of destination-clickhouse in order to keep it in sync with the strict encrypt version

### CODE REVIEW

**Review by ryankfu — APPROVED** [review]
LGTM, pending publishing connector

**Comment by grishick** [comment]
/publish connector=connectors/destination-clickhouse run-tests=false

**Comment by grishick** [comment]
/publish connector=connectors/destination-clickhouse run-tests=false

**Comment by grishick** [comment]
/publish connector=connectors/destination-clickhouse-strict-encrypt run-tests=false

**Pull request merged**
