### PR TITLE
:tada: Source Hubspot: Update Tickets, fix missing properties and change how state is updated.

### PR DESCRIPTION
**Pull request by vladimir-remar**
## What
- Update Tickets: Tickets now uses the SearchStream. This means this data is aligned with other similar ones such as Contacts or Deals. This makes incremental synchs much quicker than the current approach.
- Fix missing properties: After detecting that some properties appear in the raw data but are not collected by the schema, as a solution, it is proposed to ignore them.  This is caused by the way getting Hubspot properties work. For example, the property `hs_date_exited_6904746` is a property that is dynamically created by Hubspot when a Ticket enters the stage with id `6904746`. Then, if the stage is deleted, this property is not returned when generating the schema, but some data can still have this property. So the validation fails. I Attached extract of log..
- Update Change how state is updated: Instead of updating the state by reading the latest cursor, we propose that the new state becomes the time the last synch started. This is the solution to a problem, for example: the initial run takes around 2 hours, so if an entity was updated during this synch, with the “state strategy” used currently, won’t be gathered in the following run. With the proposed “state strategy”, it would capture all possible updated entities in incremental synch.

Log missing properties
```python
2022-08-31 14:22:06 source > Encountered an exception while reading stream tickets
Traceback (most recent call last):
  File "/airbyte/integration_code/source_hubspot/source.py", line 166, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 179, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 241, in _read_incremental
    for record_counter, record_data in enumerate(records, start=1):
  File "/airbyte/integration_code/source_hubspot/streams.py", line 904, in read_records
    records, raw_response = self._read_stream_records(
  File "/airbyte/integration_code/source_hubspot/streams.py", line 336, in _read_stream_records
    for record in self._transform(self.parse_response(response, stream_state=stream_state)):
  File "/airbyte/integration_code/source_hubspot/streams.py", line 498, in _transform
    record = self._cast_record_fields_if_needed(record)
  File "/airbyte/integration_code/source_hubspot/streams.py", line 485, in _cast_record_fields_if_needed
    declared_field_types = properties[field_name].get("type", [])
KeyError: 'hs_date_entered_6409416'
2022-08-31 14:22:06 source > Finished syncing SourceHubspot
2022-08-31 14:22:06 source > SourceHubspot runtimes:

2022-08-31 14:22:06 source > 'hs_date_entered_6409416'
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 123, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 114, in run
    for message in generator:
  File "/airbyte/integration_code/source_hubspot/source.py", line 178, in read
    raise e
  File "/airbyte/integration_code/source_hubspot/source.py", line 166, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 179, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 241, in _read_incremental
    for record_counter, record_data in enumerate(records, start=1):
  File "/airbyte/integration_code/source_hubspot/streams.py", line 904, in read_records
    records, raw_response = self._read_stream_records(
  File "/airbyte/integration_code/source_hubspot/streams.py", line 336, in _read_stream_records
    for record in self._transform(self.parse_response(response, stream_state=stream_state)):
  File "/airbyte/integration_code/source_hubspot/streams.py", line 498, in _transform
    record = self._cast_record_fields_if_needed(record)
  File "/airbyte/integration_code/source_hubspot/streams.py", line 485, in _cast_record_fields_if_needed
    declared_field_types = properties[field_name].get("type", [])
KeyError: 'hs_date_entered_6409416'
2022-08-31 14:22:06 INFO i.a.v.j.JsonSchemaValidator(test):56 - JSON schema validation failed. 
```

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by vladimir-remar** [comment]
@marcosmarxm @davydov-d Can you guys take a look on this changes? i will appreciate it :smiley:

**Comment by davydov-d** [comment]
hey @vladimir-remar thanks for your contribution again
I have a question about a state update change: have you ever run into this issue? from how I understand the state works, this problem should not ever happen because the stream is sliced before the actual sync starts: this means the maximum `updated_at` at value is the moment the sync starts so the records that are changed during the sync should be fetched during the next sync. The change you propose is risky because it may lead to a duplicate reading the same record

**Comment by vladimir-remar** [comment]
> hey @vladimir-remar thanks for your contribution again I have a question about a state update change: have you ever run into this issue? from how I understand the state works, this problem should not ever happen because the stream is sliced before the actual sync starts: this means the maximum `updated_at` at value is the moment the sync starts so the records that are changed during the sync should be fetched during the next sync. The change you propose is risky because it may lead to a duplicate reading the same record

Hi @davydov-d , yes, we have run into this issue. We should, at least, in the first run change the way the state is set up. The first run uses an endpoint that is not sorted by updated_at but is sorted by id . Thus, if a ticket has already been retrieved and gets modified during this initial run, it will not appear in the following incremental runs. We believe the approach proposed is the safest because we would never miss a record. It’s true that we will have more records in the incremental runs but there will always be duplicated entities with incremental synch mode in Hubspot. Deduplicating over the id of the entity solves this issue. If you want, we can talk over Slack (I’m on the community endpoint) and describe exactly the problem we are facing (other people should be facing it too but not realizing of the problem).

**Comment by davydov-d** [comment]
@vladimir-remar oh sorting - makes sense then. PR looks good overall, but the unit tests need to be fixed, and I'd ask to write down the described above behavior in the comments to the code and the doc.md please

maybe @marcosmarxm could help with that

**Comment by vladimir-remar** [comment]
> @vladimir-remar oh sorting - makes sense then. PR looks good overall, but the unit tests need to be fixed, and I'd ask to write down the described above behavior in the comments to the code and the doc.md please
> 
> maybe @marcosmarxm could help with that

@davydov-d Hello again, thanks for your answer, I did some changes just to clarify why we want to change the update state approach.

**Review by davydov-d — APPROVED** [review]

**Comment by davydov-d** [comment]
@vladimir-remar the build is broken now :(

> All streams should return some records, streams without records: ***'email_events', 'subscription_changes'***

**Comment by vladimir-remar** [comment]
> @vladimir-remar the build is broken now :(
> 
> > All streams should return some records, streams without records: _**'email_events', 'subscription_changes'**_

@davydov-d I will take a look ASAP.

**Comment by vladimir-remar** [comment]
> @vladimir-remar the build is broken now :(
> 
> > All streams should return some records, streams without records: _**'email_events', 'subscription_changes'**_

@davydov-d I did a custom integration test justo to verify if those streams emits records, I've check `subscription_changes` 
```bash
Test session starts (platform: linux, Python 3.9.11, pytest 6.2.5, pytest-sugar 0.9.5)
rootdir: /test_input
plugins: requests-mock-1.9.3, timeout-1.4.2, hypothesis-6.54.4, mock-3.6.1, cov-3.0.0, sugar-0.9.5
collecting ... 
 test_core.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                                                                                                                          90% █████████ 
 test_incremental.py ✓✓✓                                                                                                                                                                         100% ██████████

=========================================================================================== short test summary info ============================================================================================
SKIPPED [1] source_acceptance_test/plugin.py:60: Skipping TestFullRefresh.test_sequential_reads because not found in the config

Results (58.60s):
      29 passed

```
Since we use our hubspot API Key we are able to retrieve data from that endpoints, can you check if in your hubspot account there is some data related to 'email_events' and 'subscription_changes'

**Comment by davydov-d** [comment]
that's weird - I've just run tests locally with your changes and they passed. let's try one more time

**Comment by vladimir-remar** [comment]
@davydov-d Hello again, It seems the integration tests keeps failing, if there is something that I can help just let me know.

**Comment by vladimir-remar** [comment]
@davydov-d Hi Again, I did some changes, the idea is save the **latest** state with the value of the `initial_sync`, what do you think?

**Comment by davydov-d** [comment]
@vladimir-remar looks good! let's try another test run

**Comment by davydov-d** [comment]
@vladimir-remar take a look please https://github.com/airbytehq/airbyte/runs/8266425992?check_suite_focus=true
we should use a safe get for retrieving last slice

**Pull request merged**
