### PR TITLE
source-stripe: fix property of `invoices.lines` property

### PR DESCRIPTION
**Pull request by evantahler**
invoices.lines is an object.  Closes https://github.com/airbytehq/oncall/issues/2970

### CODE REVIEW

**Review by brianjlai — APPROVED** [review]

**Review by edgao — APPROVED** [review]

**Comment by evantahler** [comment]
For the reviewers from GL: Please double check that we have sandbox data for this stream so that testing will be relevent

**Comment by evantahler** [comment]
The test failure seems unrelated to this stream

**Review by davydov-d — APPROVED** [review]

**Comment by evantahler** [comment]
@davydov-d can you let me know what I should do about the failing test on the unrelated stream?

**Comment by davydov-d** [comment]
@evantahler fixed. I added one more stream to `empty_streams` as data its data expires every 30 days

**Pull request merged**
