### PR TITLE
🐛 Source Shopify: fix `404` for configured streams, fix missing cursor error for old records

### LINKED ISSUE #7577: Shopify Order refunds are not parsed correctly
## Enviroment
- **Airbyte version**:  0.30.8-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**:  Docker
- **Source Connector and version**: Shopify 0.1.18
- **Destination Connector and version**: N/A - present in both Postgres and BigQuery
- **Severity**:  Critical
- **Step where error happened**: Sync job

## Current Behavior
Order refunds are nested within orders from the Shopify Order API. Airbyte loads the refund as a nested column in the Order table, but also creates a separate table for refunds. Unfortunately, we've noticed that a significant number of refunds are not being unrolled correctly. We verified this by inspecting the refunds table, comparing it to tables loaded by Fivetran for the same store, and identifying Orders that had non-empty refund JSON column values and no corresponding refund records. We also verified that the refunds loaded by Airbyte did not accurately reflect the data in the Shopify dashboard.

## Expected Behavior
Refunds should be extracted and loaded for all orders.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1. Create and authenticate a Shopify source
2. Create and authenticate a Postgres destination
3. Create a connection for the two

## Are you willing to submit a PR?

Remove this with your answer.

### LINKED ISSUE #11976: Shopify historical sync fails
## Environment
- **Airbyte version**:  example is 0.35.60-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: Shopify `1.1.36`
- **Destination Connector and version**: n/1a
- **Severity**: Critical
- **Step where error happened**: Sync job

## Current Behavior
The job cannot read the `state` on the initial historical sync. Logs here:
```
File "/airbyte/integration_code/source_shopify/source.py", line 132, in filter_records_newer_than_state
    if record.get(self.cursor_field, "") >= stream_state.get(self.cursor_field):
TypeError: '>=' not supported between instances of 'NoneType' and 'str'
```

## Expected Behavior
Historical sync should be able to complete with no prior state.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*
[logs-334.txt](https://github.com/airbytehq/airbyte/files/8483143/logs-334.txt)

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

### LINKED ISSUE #15242: 🐛 Source Shopify: unavailable balance transactions causes 404 error
## Current Behavior
When using the Shopify source with a store in a country that does not support balance transactions, the whole sync fails.

## Expected Behavior
The absence of balance transactions should not break the sync.

This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1778](https://airbyte7538.zendesk.com/agent/tickets/1778)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Nataly Merezhuk

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">Is this your first time deploying Airbyte?: No</li>
<li style="padding-bottom: 10px;">OS Version / Instance: Ubuntu</li>
<li style="padding-bottom: 10px;">Memory / Disk: 14GB RAM, 20GB</li>
<li style="padding-bottom: 10px;">Deployment:  Docker on GCP GCE</li>
<li style="padding-bottom: 10px;">Airbyte Version: 0.39.39-alpha</li>
<li style="padding-bottom: 10px;">Source name/version: Shopify 0.1.37</li>
<li style="padding-bottom: 10px;">Destination name/version: BigQuery 1.1.11</li>
<li style="padding-bottom: 10px;">Step: Happens during the sync</li>
<li style="padding-bottom: 10px;">Description: Facing a problem with the description of it mentioning “Failure Origin: source, Message: Something went wrong within the source connector” when connecting Shopify to BigQuery. The logs are uploaded for reference. I don’t understand the problem because I have Admin permission to Shopify hence I would not come into problem when calling the API for the Shopify. Please help. Thanks.<br>
<a href="https://discuss.airbyte.io/uploads/short-url/meBpb6mxx7KuaAYfUxaj9aAjspk.txt" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">logs-24.txt</a> (422.4 KB)</li>
</ul> 

[<a href="https://discuss.airbyte.io/t/shopify-connector-facing-problems-during-ingestion/2082/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

### LINKED ISSUE #15386: 🐛 Source Shopify: syncing nested streams (DiscountCodes and PriceRules) fails
## Environment
- **Airbyte version**:  0.39.41-alpha
- **OS Version / Instance**:  AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: source-shopify - 0.1.37
- **Destination Connector and version**: destination-s3 - 0.3.12
- **Step where error happened**: Sync job

## Current Behavior
When syncing the DiscountCodes and its parent stream PriceRules the sync job will fail if the `updated_at` field of a returned discount code query is null. I'll upload the full log but this is the relevant stack trace.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 114, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 159, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 215, in _read_incremental
    for record_counter, record_data in enumerate(records, start=1):
  File "/airbyte/integration_code/source_shopify/source.py", line 240, in read_records
    yield from self.filter_records_newer_than_state(stream_state=stream_state, records_slice=records)
  File "/airbyte/integration_code/source_shopify/source.py", line 132, in filter_records_newer_than_state
    if record.get(self.cursor_field, "") >= stream_state.get(self.cursor_field):
TypeError: '>=' not supported between instances of 'NoneType' and 'str'
```

## Expected Behavior
If the record's cursor field isn't defined, default to yielding/including it 

## Logs 
Error starts at line 116 of the attached log
[logs-139.txt](https://github.com/airbytehq/airbyte/files/9276206/logs-139.txt)

### PR DESCRIPTION
**Pull request by bazarnov**
## What
Resolving: 
- https://github.com/airbytehq/airbyte/issues/15242
- https://github.com/airbytehq/airbyte/issues/15386
- https://github.com/airbytehq/airbyte/issues/11976
- https://github.com/airbytehq/airbyte/issues/14065
- https://github.com/airbytehq/airbyte/issues/7577

## How
- override `should_retry` logic to cover `404` status code for discovered streams, but still are not available for certain regions due to Shopify limitations.
- updated `filter_records_newer_that_state` logic to cover missing `cursor_field` for very old records.
- added correspond unit_test to cover the case. 
- removed `oauth` flow from connectors spec, leaving `client_id` `client_secret` in place for custom `oauth` usage. The primary option for authentication is `API Password` 

## 🚨 User Impact 🚨
No impact is expected.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [X] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [X] Code reviews completed
- [X] Documentation updated
    - [X] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [X] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Review by arsenlosenko — APPROVED** [review]

**Review by lazebnyi — APPROVED** [review]

**Comment by cgalliva** [comment]
I saw this got patched and updated the shopify connector, but I'm experiencing the same problem with the same record. It looks like it was only updated to handle the case where the cursor field isn't present, not when it's actually set to a null value (which is what's happening in my case: 

This is the response from calling the price rule's discount code: 
```
{
  "discount_codes": [
    {
      "id": 3...1,
      "price_rule_id": 6...9,
      "code": "B...H",
      "usage_count": 0,
      "created_at": null,
      "updated_at": null
    }
  ]
}
```

**Comment by bazarnov** [comment]
> I saw this got patched and updated the shopify connector, but I'm experiencing the same problem with the same record. It looks like it was only updated to handle the case where the cursor field isn't present, not when it's actually set to a null value (which is what's happening in my case:
> 
> This is the response from calling the price rule's discount code:
> 
> ```
> {
>   "discount_codes": [
>     {
>       "id": 3...1,
>       "price_rule_id": 6...9,
>       "code": "B...H",
>       "usage_count": 0,
>       "created_at": null,
>       "updated_at": null
>     }
>   ]
> }
> ```

@cgalliva 
Have you tried full-refresh or incremental sync after the version update?

**Comment by cgalliva** [comment]
> @cgalliva What sync mode have you tried: full-refresh or incremental sync after the version update?
> 
> Please provide the logs, thank you.
> 
> The fix is pretty straight forward, but we need to be sure that comparison takes place with `None >= str` indeed, when `cursor_field: null`
@bazarnov 
The error happens on incremental sync on a new connection with just the price_rules and discount_codes streams. Here's the traceback from the logs, if you need the full log I can share it I'll have to go through and remove any info before I upload it.
```
2022-10-14 09:25:56 [44msource[0m > Reading discount_codes for price_rule_id: 615221231639
2022-10-14 09:25:57 [44msource[0m > Encountered an exception while reading stream discount_codes
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 113, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 182, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 244, in _read_incremental
    for record_counter, record_data in enumerate(records, start=1):
  File "/airbyte/integration_code/source_shopify/source.py", line 270, in read_records
    yield from self.filter_records_newer_than_state(stream_state=stream_state, records_slice=records)
  File "/airbyte/integration_code/source_shopify/source.py", line 141, in filter_records_newer_than_state
    if record.get(self.cursor_field, self.default_state_comparison_value) >= stream_state.get(self.cursor_field):
TypeError: '>=' not supported between instances of 'NoneType' and 'str'
2022-10-14 09:25:57 [44msource[0m > Finished syncing discount_codes
2022-10-14 09:25:57 [44msource[0m > SourceShopify runtimes:
Syncing stream discount_codes 5:08:16.282306
2022-10-14 09:25:57 [44msource[0m > '>=' not supported between instances of 'NoneType' and 'str'
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 123, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 114, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 127, in read
    raise e
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 113, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 182, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 244, in _read_incremental
    for record_counter, record_data in enumerate(records, start=1):
  File "/airbyte/integration_code/source_shopify/source.py", line 270, in read_records
    yield from self.filter_records_newer_than_state(stream_state=stream_state, records_slice=records)
  File "/airbyte/integration_code/source_shopify/source.py", line 141, in filter_records_newer_than_state
    if record.get(self.cursor_field, self.default_state_comparison_value) >= stream_state.get(self.cursor_field):
TypeError: '>=' not supported between instances of 'NoneType' and 'str'
```

**Comment by bazarnov** [comment]
@cgalliva Thank you for sharing the traceback logs, we will prepare the fix asap.

**Pull request merged**
