### PR TITLE
Langchain destination: Support composite and nested primary keys for deduping

### PR DESCRIPTION
**Pull request by flash1293**
## What

This PR makes sure composite and nested primary keys are considered correctly for deduping records in the destination. Previously, in the case of composite and nested primary keys the deduplication would only consider the very first part of the key which can lead to too many documents being deleted.

## How

Concatenate all parts of the primary key in the document metadata to correctly identify the matching documents.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  destination-langchain test report (commit [`749ac1b122`](https://github.com/airbytehq/airbyte/pull/28556/commits/749ac1b1222e4f8bb5114745f334b600ece1bd1e)) - ❌

⏲️  Total pipeline duration: 02mn30s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-langchain/metadata.yaml | ❌        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Code format checks                                                           | ✅        |
| Connector package install                                                    | ✅        |
| Build destination-langchain docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                   | ✅        |
| Integration tests                                                            | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/flash1293_langchain-composite-keys/1689945743/749ac1b1222e4f8bb5114745f334b600ece1bd1e/destination-langchain/0.0.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-langchain test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-langchain test report (commit [`aec59031b9`](https://github.com/airbytehq/airbyte/pull/28556/commits/aec59031b989a083e1c1c292b597b4f512a187ab)) - ❌

⏲️  Total pipeline duration: 12.01s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-langchain/metadata.yaml | ❌        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Code format checks                                                           | ✅        |
| Connector package install                                                    | ✅        |
| Build destination-langchain docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                   | ✅        |
| Integration tests                                                            | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/flash1293_langchain-composite-keys/1689946033/aec59031b989a083e1c1c292b597b4f512a187ab/destination-langchain/0.0.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-langchain test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-langchain test report (commit [`dfecdf39ea`](https://github.com/airbytehq/airbyte/pull/28556/commits/dfecdf39ea9c8393c488991071ddbe60fccf485e)) - ✅

⏲️  Total pipeline duration: 01mn01s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-langchain/metadata.yaml | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Code format checks                                                           | ✅        |
| Connector package install                                                    | ✅        |
| Build destination-langchain docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                   | ✅        |
| Integration tests                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/flash1293_langchain-composite-keys/1689946245/dfecdf39ea9c8393c488991071ddbe60fccf485e/destination-langchain/0.0.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-langchain test
```

**Review by girarda — COMMENTED** [review]
the change looks good, but I'm not sure we should support nested primary key. We'll remove support for nested keys in other destinations too and the recommendation is now for sources to move the pks to the top level https://www.notion.so/Airbyte-Data-Warehouse-Destination-V2-Philosophy-e6081edb87084999948acdc8b9607ea1

Supporting composite keys is a good idea

**Comment by flash1293** [comment]
@girarda It's not much harder to support it and as long as it's part of the protocol it feels safer to do so IMHO

**Review by girarda — APPROVED** [review]
fair enough. approvedd

**Pull request merged**
