### PR TITLE
🎉 Source Stripe: Fix "date", "arrival_date" fields: type: number

### LINKED ISSUE #9068: 🐛  Source Stripe: Payouts and transfers streams normalization fails - invalid data(possibly date/timestamp)
## Environment
- **Airbyte version**: 0.34.2-alpha
- **OS Version / Instance**: MacOS Big Sur, Amazon Linux 2
- **Deployment**: EKS
- **Source Connector and version**: Stripe 0.1.25 
- **Destination Connector and version**: Redshift 0.3.21 
- **Severity**: High
- **Step where error happened**: Sync Job

## Current Behavior
Normalization for Payouts and Transfers fail with invalid data error when using Redshift as destination, does not happen with Snowflake. 

## Expected Behavior
Payouts and Transfers should sync and normalize without any errors.

## Logs
```
2021-12-22 20:36:02 [42mnormalization[0m > 
2021-12-22 20:36:02 [42mnormalization[0m > [31mCompleted with 2 errors and 0 warnings:[0m
2021-12-22 20:36:02 [42mnormalization[0m > 
2021-12-22 20:36:02 [42mnormalization[0m > [33mDatabase Error in model payouts (models/generated/airbyte_incremental/public/payouts.sql)[0m
2021-12-22 20:36:02 [42mnormalization[0m >   Invalid data
2021-12-22 20:36:02 [42mnormalization[0m >   DETAIL:  
2021-12-22 20:36:02 [42mnormalization[0m >     -----------------------------------------------
2021-12-22 20:36:02 [42mnormalization[0m >     error:  Invalid data
2021-12-22 20:36:02 [42mnormalization[0m >     code:      8001
2021-12-22 20:36:02 [42mnormalization[0m >     context:   Invalid format or data given: 1638316800
2021-12-22 20:36:02 [42mnormalization[0m >     query:     12803893
2021-12-22 20:36:02 [42mnormalization[0m >     location:  funcs_timestamp.cpp:274
2021-12-22 20:36:02 [42mnormalization[0m >     process:   query0_124_12803893 [pid=5795]
2021-12-22 20:36:02 [42mnormalization[0m >     -----------------------------------------------
2021-12-22 20:36:02 [42mnormalization[0m >   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/public/payouts.sql
2021-12-22 20:36:02 [42mnormalization[0m > 
2021-12-22 20:36:02 [42mnormalization[0m > [33mDatabase Error in model transfers (models/generated/airbyte_incremental/public/transfers.sql)[0m
2021-12-22 20:36:02 [42mnormalization[0m >   Invalid data
2021-12-22 20:36:02 [42mnormalization[0m >   DETAIL:  
2021-12-22 20:36:02 [42mnormalization[0m >     -----------------------------------------------
2021-12-22 20:36:02 [42mnormalization[0m >     error:  Invalid data
2021-12-22 20:36:02 [42mnormalization[0m >     code:      8001
2021-12-22 20:36:02 [42mnormalization[0m >     context:   Invalid format or data given: 1639008000
2021-12-22 20:36:02 [42mnormalization[0m >     query:     12803892
2021-12-22 20:36:02 [42mnormalization[0m >     location:  funcs_timestamp.cpp:274
2021-12-22 20:36:02 [42mnormalization[0m >     process:   query1_102_12803892 [pid=16452]
2021-12-22 20:36:02 [42mnormalization[0m >     -----------------------------------------------
2021-12-22 20:36:02 [42mnormalization[0m >   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/public/transfers.sql
2021-12-22 20:36:02 [42mnormalization[0m > 
2021-12-22 20:36:02 [42mnormalization[0m > Done. PASS=0 WARN=0 ERROR=2 SKIP=2 TOTAL=4
2021-12-22 20:36:02 [32mINFO[m i.a.w.t.TemporalAttemptExecution(lambda$getWorkerThread$2):177 - Completing future exceptionally...
io.airbyte.workers.WorkerException: Normalization Failed.
```

Complete data from the run: [stripe-redshift-data.zip](https://github.com/airbytehq/airbyte/files/7765212/stripe-redshift-data.zip)

### PR DESCRIPTION
**Pull request by grubberr**
Signed-off-by: Sergey Chvalyuk <grubberr@gmail.com>

## What
Contributer provided the richer data and we can see that `date` and `arrival_date` was incorectly described.
it's `timestamp` fields:

```
{ 
  ...
  "arrival_date": 1640131200,
  "date": 1640131200
  ...
}
```

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [x] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [x] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [x] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [x] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

### CODE REVIEW

**Review by midavadim — APPROVED** [review]

**Review by antixar — APPROVED** [review]
Please publish your changes

**Pull request merged**
