### PR TITLE
Source Jenkins: Fix data specs for jenkins connector (depth field)

### PR DESCRIPTION
**Pull request by EdsonJuniorPD**
## What

The depth field is recognizing the values ​​as a string instead of an integer. (attached image)

Airbyte_ERROR

## How

fix the data type specification for the depth field(integer).

## Recommended reading order

1. `jenkins connector spec file`

## 🚨 User Impact 🚨

The problem impacts the search for jobs, making it impossible to configure a deeper search for jobs.

## Pre-merge Checklist

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by sajarin** [comment]
Thanks for the PR @EdsonJuniorPD! This PR is part of Airbyte's Community Maintainer program and will be reviewed by a member of our community. Please be a bit more patient, someone will be assigned shortly. Thank you!

**Comment by sajarin** [comment]
assigned to @jacqueskpoty

**Comment by jacqueskpoty** [comment]
@EdsonJuniorPD Thanks for your contributions. Could you take care of the following so we can merge your changes :

1 - Update the jenkins connector's version  
2- Update the connector's ReadMe docs 
3- Follow the "Pre-merge checklist" in the PR description

**Pull request closed without merging**
