### PR TITLE
🐛 Source JIRA: Fix DBT failing normalization on `Labels` schema.

### LINKED ISSUE #4777: Source Jira: sync failed in normalization stream label doesnt have properties
## Enviroment
- **Airbyte version**:  0.27.3-alpha
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker
- **Source Connector and version**: Jira 0.2.6
- **Destination Connector and version**: Postgres 0.3.6
- **Severity**: Very Low / Low / Medium / **High** / Critical
- **Step where error happened**: Deploy / **Sync job** / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Connector can read streams but normalization failed.

Error snippet but full log is provided bellow
```
2021-07-16 00:05:02 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/catalog_processor.py", line 143, in build_stream_processor
2021-07-16 00:05:02 ERROR () LineGobbler(voidCall):85 -     properties = get_field(get_field(stream_config, "json_schema", message), "properties", message)
2021-07-16 00:05:02 ERROR () LineGobbler(voidCall):85 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/catalog_processor.py", line 233, in get_field
2021-07-16 00:05:02 ERROR () LineGobbler(voidCall):85 -     raise KeyError(message)
2021-07-16 00:05:02 ERROR () LineGobbler(voidCall):85 - KeyError: "'json_schema'.'properties' are not defined for stream labels"
2021-07-16 00:05:04 INFO () TemporalAttemptExecution(lambda$getWorkerThread$2):149 - Completing future exceptionally...
io.airbyte.workers.WorkerException: Normalization Failed.
```

## Expected Behavior
*Tell us what should happen.*

## Logs

<details>
<summary>Full sync log</summary> 

```

2021-07-15 23:55:00 INFO () WorkerRun(call):62 - Executing worker wrapper. Airbyte version: 0.27.2-alpha
2021-07-15 23:55:00 INFO () TemporalAttemptExecution(get):110 - Executing worker wrapper. Airbyte version: 0.27.2-alpha
2021-07-15 23:55:00 INFO () DefaultReplicationWorker(run):102 - start sync worker. job id: 1 attempt id: 2
2021-07-15 23:55:00 INFO () DefaultReplicationWorker(run):111 - configured sync modes: {null.workflows=full_refresh - append, null.screen_tab_fields=full_refresh - append, null.avatars=full_refresh - append, null.project_email=full_refresh - append, null.issues=full_refresh - append, null.project_types=full_refresh - append, null.issue_worklogs=full_refresh - append, null.project_components=full_refresh - append, null.project_permission_schemes=full_refresh - append, null.permission_schemes=full_refresh - append, null.issue_custom_field_contexts=full_refresh - append, null.groups=full_refresh - append, null.permissions=full_refresh - append, null.issue_fields=full_refresh - append, null.issue_field_configurations=full_refresh - append, null.jira_settings=full_refresh - append, null.screens=full_refresh - append, null.dashboards=full_refresh - append, null.issue_link_types=full_refresh - append, null.project_avatars=full_refresh - append, null.issue_watchers=full_refresh - append, null.labels=full_refresh - append, null.filters=full_refresh - append, null.workflow_status_categories=full_refresh - append, null.issue_navigator_settings=full_refresh - append, null.issue_security_schemes=full_refresh - append, null.issue_type_schemes=full_refresh - append, null.screen_tabs=full_refresh - append, null.issue_properties=full_refresh - append, null.workflow_schemes=full_refresh - append, null.issue_resolutions=full_refresh - append, null.project_categories=full_refresh - append, null.issue_type_screen_schemes=full_refresh - overwrite, null.issue_votes=full_refresh - append, null.application_roles=full_refresh - append, null.workflow_statuses=full_refresh - append, null.projects=full_refresh - append, null.filter_sharing=full_refresh - append, null.time_tracking=full_refresh - append, null.users=full_refresh - append, null.issue_remote_links=full_refresh - append, null.issue_comments=full_refresh - append, null.project_versions=full_refresh - append, null.screen_schemes=full_refresh - append, null.issue_notification_schemes=full_refresh - append, null.issue_priorities=full_refresh - append}
2021-07-15 23:55:00 INFO () DefaultAirbyteDestination(start):78 - Running destination...
2021-07-15 23:55:00 INFO () LineGobbler(voidCall):85 - Checking if airbyte/destination-postgres:0.3.6 exists...
2021-07-15 23:55:00 INFO () LineGobbler(voidCall):85 - airbyte/destination-postgres:0.3.6 was found locally.
2021-07-15 23:55:00 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/1/2 --network host --log-driver none airbyte/destination-postgres:0.3.6 write --config destination_config.json --catalog destination_catalog.json
2021-07-15 23:55:00 INFO () LineGobbler(voidCall):85 - Checking if airbyte/source-jira:0.2.6 exists...
2021-07-15 23:55:00 INFO () LineGobbler(voidCall):85 - airbyte/source-jira:0.2.6 was found locally.
2021-07-15 23:55:00 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/1/2 --network host --log-driver none airbyte/source-jira:0.2.6 read --config source_config.json --catalog source_catalog.json
2021-07-15 23:55:00 INFO () DefaultReplicationWorker(run):139 - Waiting for source thread to join.
2021-07-15 23:55:00 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):210 - Replication thread started.
2021-07-15 23:55:00 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):246 - Destination output thread started.
2021-07-15 23:55:07 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-15 23:55:07 INFO i.a.i.d.p.PostgresDestination(main):83 - {} - starting destination: class io.airbyte.integrations.destination.postgres.PostgresDestination
2021-07-15 23:55:07 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-15 23:55:07 INFO i.a.i.b.IntegrationRunner(run):78 - {} - Running integration: io.airbyte.integrations.destination.postgres.PostgresDestination
2021-07-15 23:55:07 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-15 23:55:07 INFO i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2021-07-15 23:55:07 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-15 23:55:07 INFO i.a.i.b.IntegrationRunner(run):82 - {} - Command: WRITE
2021-07-15 23:55:07 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-15 23:55:07 INFO i.a.i.b.IntegrationRunner(run):83 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2021-07-15 23:55:07 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-15 23:55:07 INFO i.a.i.d.b.BufferedStreamConsumer(startTracked):120 - {} - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
2021-07-15 23:55:07 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-15 23:55:07 INFO i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):145 - {} - Preparing tmp tables in destination started for 46 streams

```

</details>

## Steps to Reproduce
1. setup source jira using integration account
2. setup postgres with normalization enabled
3. run sync

## Are you willing to submit a PR?

Not at the moment.

### PR DESCRIPTION
**Pull request by bazarnov**
## What
#4777 - Source Jira: sync failed in normalization stream label doesn't have properties

## How
- changed the existing JSON Schema for `labels` stream
- Added test for expected_records from `labels` stream
- Tested DBT Normalisation on Postgres Destination connector (v3.6)

## Pre-merge Checklist
Expand the checklist which is relevant for this PR. 

<details><summary> <strong> Connector checklist </strong> </summary>
<p>

- [x] Issue acceptance criteria met
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [X] Unit & integration tests added as appropriate (and are passing)
        `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [X] `/test connector=connectors/<name>` command as documented [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-an-existing-connector) is passing. 
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [X] `README.md`
    - [X] Created or updated reference docs in `docs/integrations/<source or destination>/<name>`.
    - [X] Changelog in the appropriate page in `docs/integrations/...`. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] Build is successful
- [X] Connector version bumped like described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [X] No major blockers
</p>
</details>

### CODE REVIEW

**Review by antixar — APPROVED** [review]
perfect

**Review by lazebnyi — APPROVED** [review]
LGTM

**Review by sherifnada — APPROVED** [review]
well done!

**Pull request merged**
