### PR TITLE
Source S3: Add a few more CAT tests

### PR DESCRIPTION
**Pull request by girarda**
## What
Add a few CATs configs for source-s3. These tests will serve as safeguard to ensure backward compatibility as we'll upgrade to v4. 

The tests are:
- csv_custom_encoding: test with a csv file encoded as cp1252
- csv_custom_format: test with a csv file with a custom delimiter and custom escape char
- csv_no_header: test with a file that does not have a header
- csv_skip_rows: test with a file that has rows to skip before and after the header
- csv_user_schema: test with a user-defined schema
- csv_with_nulls: test with a config that converts "NONE" and "NULL" to `None`

The analogous tests for v4 will be added in a separate PR

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`47a0778409`](https://github.com/airbytehq/airbyte/pull/29069/commits/47a0778409ff84d0ec558f20380f6007346ca25f)) - ❌

⏲️  Total pipeline duration: 21mn12s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_s3_csv_tests/1691101422/47a0778409ff84d0ec558f20380f6007346ca25f/source-s3/3.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:47a0778409ff84d0ec558f20380f6007346ca25f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`73fe25e2e9`](https://github.com/airbytehq/airbyte/pull/29069/commits/73fe25e2e9453c4b5c53b717bddb4fd6dbea1710)) - ❌

⏲️  Total pipeline duration: 21mn36s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_s3_csv_tests/1691102789/73fe25e2e9453c4b5c53b717bddb4fd6dbea1710/source-s3/3.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:73fe25e2e9453c4b5c53b717bddb4fd6dbea1710)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`59a966b24d`](https://github.com/airbytehq/airbyte/pull/29069/commits/59a966b24d78e834d76dc3c049c8740772f65016)) - ❌

⏲️  Total pipeline duration: 19mn37s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_s3_csv_tests/1691109238/59a966b24d78e834d76dc3c049c8740772f65016/source-s3/3.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:59a966b24d78e834d76dc3c049c8740772f65016)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by girarda** [comment]
spec test is already failing. it should be fixed by https://github.com/airbytehq/airbyte/pull/29065

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`59a966b24d`](https://github.com/airbytehq/airbyte/pull/29069/commits/59a966b24d78e834d76dc3c049c8740772f65016)) - ❌

⏲️  Total pipeline duration: 19mn10s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_s3_csv_tests/1691110538/59a966b24d78e834d76dc3c049c8740772f65016/source-s3/3.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:59a966b24d78e834d76dc3c049c8740772f65016)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Review by clnoll — APPROVED** [review]
Looks great @girarda!

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`698ffc7d38`](https://github.com/airbytehq/airbyte/pull/29069/commits/698ffc7d38157754cc68134a5268485df601338b)) - ❌

⏲️  Total pipeline duration: 21mn37s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_s3_csv_tests/1691124036/698ffc7d38157754cc68134a5268485df601338b/source-s3/3.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:698ffc7d38157754cc68134a5268485df601338b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`dbd117a583`](https://github.com/airbytehq/airbyte/pull/29069/commits/dbd117a583beb46f85481bae1869e65e1db15062)) - ❌

⏲️  Total pipeline duration: 54.20s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_s3_csv_tests/1691180056/dbd117a583beb46f85481bae1869e65e1db15062/source-s3/3.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:dbd117a583beb46f85481bae1869e65e1db15062)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`dbd117a583`](https://github.com/airbytehq/airbyte/pull/29069/commits/dbd117a583beb46f85481bae1869e65e1db15062)) - ❌

⏲️  Total pipeline duration: 19mn26s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_s3_csv_tests/1691180654/dbd117a583beb46f85481bae1869e65e1db15062/source-s3/3.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:dbd117a583beb46f85481bae1869e65e1db15062)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`10591ff895`](https://github.com/airbytehq/airbyte/pull/29069/commits/10591ff8953c5818d645a73f24f44df929afe84c)) - ❌

⏲️  Total pipeline duration: 21mn00s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_s3_csv_tests/1691185369/10591ff8953c5818d645a73f24f44df929afe84c/source-s3/3.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:10591ff8953c5818d645a73f24f44df929afe84c)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`10591ff895`](https://github.com/airbytehq/airbyte/pull/29069/commits/10591ff8953c5818d645a73f24f44df929afe84c)) - ✅

⏲️  Total pipeline duration: 19mn13s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_s3_csv_tests/1691187020/10591ff8953c5818d645a73f24f44df929afe84c/source-s3/3.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:10591ff8953c5818d645a73f24f44df929afe84c)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Pull request merged**
