### PR TITLE
airbyte-lib: Enable tests

### PR DESCRIPTION
**Pull request by flash1293**
Enables test for airbyte-lib (currently failing because the step gets stuck)

### CODE REVIEW

**Comment by aaronsteers** [comment]
@flash1293, Thanks for creating. Just FYI, I added a dummy commit to trigger CI and repro the issue. 👍

**Comment by flash1293** [comment]
@alafanechere I did finish eventually - seems like what works on my local airbyte-ci doesn't work on Github CI... I would appreciate a look from your side how to reach the postgres docker container from within the test container.

**Comment by flash1293** [comment]
@alafanechere On second thought, let me spend half an hour on it on Monday, maybe it's not as complex as I think

**Comment by alafanechere** [comment]
The tests are running correctly in CI now.
What I did:
* Provided an optional sidecar docker engine for `airbyte-ci test`: it's used for `airbyte-lib` tests. It fixes the connection problems to the test postgres instance. I could not figure why the local execution work. I believe it has something to do with how runner access docker themselves (through a sidecar pod with socket sharing). For simplicity and diminished reliance on the available docker host I prefer the dockerd as a dagger service approach.
* Slightly changed the provisioning logic of the postgres test container:
 * Check container status before attempting connection
 * Use the docker host as postgres host if it's set as an env var (when running inside dagger)

**Review by alafanechere — APPROVED** [review]

**Pull request merged**
