### PR TITLE
alias customer id upon import of configuration data

### LINKED ISSUE #1634: When Airbyte is upgraded make sure segment identities are merged
## Tell us about the problem you're trying to solve
* As soon as the server / webapp start they `identify` in segment. The problem here is when someone upgrades, the upgrade is going to look like a new user.

## Describe the solution you’d like
* We need to make sure that when import of data is run we link / merge the user that is being overwritten with thew new user.

### PR DESCRIPTION
**Pull request by cgardens**
closes https://github.com/airbytehq/airbyte/issues/1634

## What
* Currently when someone imports data subsequent, the tracking behavior is undefined. What I think happens now is that that it will appear like we had a new user try out airbyte and then they stopped at the top of the funnel because there will be no way to link them to the newly imported data. This messes up all of our analytics.

## How
* When a new configuration is imported into Airbyte report the imported customer id as the new tracking id (identify - which is meant to be called anytime a user logs in). 
* Alias the previous customer id as a child of the imported customer id (alias)

## Checklist
- [x] *Manually test this in amplitude*
- [x] *Follow up: we need to do the same thing in the UI (a task for next week. now that we know this works it is safe for the UI part to wait until after launch, it just has to happen before our first minor version bump after launch. [issue](https://github.com/airbytehq/airbyte/issues/1797))* 

## Manual Tests Result
* deployed an airbyte instance from scratch (creating a new amplitude user)
original_user

* created some configs then exported the data

* then i tore down the airbyte instance and deployed a new one from scratch (creating another new amplitude user).
new_user

* then I imported the data from the previous instance into the new one.

the state of the original user after the:
original_user_remapped

the state of the second user after the import:
new_user_remapped

This looks like it is working reasonably correctly (note: the `remapped user id` field on the "primary" user and `remapping into user id` on the child user). Hopefully this doesn't mess up any of the analytics stuff. 

@johnlafleur  I want to make sure you grok this so that there are no surprises for you. lmk if you have any questions

### CODE REVIEW

**Comment by johnlafleur** [comment]
I need to understand how the remapping will affect the analytics on Amplitude. Does Amplitude natively support this? So that they understand it's the same user, and when we measure retention, they consider it is one and only users?

**Comment by cgardens** [comment]
Yes. Amplitude natively supports this. I don't fully understand how it will
effect analytics. I'm hoping it won't mess anything up. That would make the
most sense, but we should verify.

I think on Monday we can verify it together. Since I signed up on Friday we
should be able to figure out if my two users got combined into one in our
analytics (e.g. the funnel analysis)

**Comment by johnlafleur** [comment]
> Yes. Amplitude natively supports this. I don't fully understand how it will effect analytics. I'm hoping it won't mess anything up. That would make the most sense, but we should verify. I think on Monday we can verify it together. Since I signed up on Friday we should be able to figure out if my two users got combined into one in our analytics (e.g. the funnel analysis)

ok!

**Review by jrhizor — APPROVED** [review]

**Comment by ChristopheDuong** [comment]
So if I share an archive that I produced by my local instance with my team, and they import it into their local instances of airbyte, then everybody becomes me?

**Comment by cgardens** [comment]
> So if I share an archive that I produced by my local instance with my team, and they import it into their local instances of airbyte, then everybody becomes me? (or at least remapped to my id)

yes

**Comment by cgardens** [comment]
I confirmed that this works as we expect it should. Looked at our activation funnel downloaded all the users for that time period. Was able to find the original user id, but the one that was replaced is not there (which is what we want, we want it to just look like the original one). I

**Pull request merged**
