### PR TITLE
🐛Destination Teradata: Fix for Parameter 2 length size issue #27929

### PR DESCRIPTION
**Pull request by sc250072**
## What

Destination teradata sync is failing when _airbyte_data exceeds 64000 bytes and issue is logged with https://github.com/airbytehq/airbyte/issues/27929. _airbyte_data is defined as String to handle JSON data and teradata JDBC throwing this limitation error if json data is more than 64K bytes.

## How

Teradata JDBC driver recommending handle [JSON type](https://teradata-docs.s3.amazonaws.com/doc/connectivity/jdbc/reference/current/jdbcug_chapter_2.html#CCHJSON1) as java.sql.Struct type. Implemented new Struct type to handle JSON types and Modified JSONData has JSON instead of String in prepared statement. Implemented with reference from [Teradata JDBC JSON Example](https://teradata-docs.s3.amazonaws.com/doc/connectivity/jdbc/reference/current/samp/T21507JD.java.txt)

## Review guide

1. airbyte-integrations/connectors/destination-teradata/src/main/java/io/airbyte/integrations/destination/teradata/util/JSONStruct.java
2. airbyte-integrations/connectors/destination-teradata/src/main/java/io/airbyte/integrations/destination/teradata/TeradataSqlOperations.java
3. airbyte-integrations/connectors/destination-teradata/src/test/java/io/airbyte/integrations/destination/teradata/util/JSONStructTest.java

Teradata destination connector unit and acceptance tests status with these changes https://github.com/Teradata/airbyte/actions/runs/9478853398/job/26116144626

## User Impact

User doesn't see below error with this fix
Destination-Teradata gives error of Parameter 2 length is 70437 bytes, which is greater than the maximum 64000 bytes that can be set if the size of column exceeds 64K

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Can you bump the `metadata.yaml` connector version? This way we can run integration tests in CI.

**Comment by satish-chinthanippu** [comment]
> Can you bump the `metadata.yaml` connector version? This way we can run integration tests in CI.

Done

**Comment by satish-chinthanippu** [comment]
> Also make sure to run `airbyte-ci format fix all` to format files.

Ran the command and files are formatted now.

**Comment by natikgadzhi** [comment]
@marcosmarxm you should be able to just use `/format-fix` in a PR and it should format and commit into the PR automatically, if that's the only thing you need to get this to merge. 

@aaronsteers, can you take a quick glance to see if we haven't messed anything up here?

**Comment by satish-chinthanippu** [comment]
> > @marcosmarxm you should be able to just use /format-fix in a PR and it should format and commit into the PR automatically, if that's the only thing you need to get this to merge.
> 
> Maintainers (and bot) doesn't have access to their branch because they're using Teradata org fork. @satish-chinthanippu is it possible to enable contributions from maintainers in your fork? This will speed up the process to review the contribution.

@marcosmarxm  Can you please provide information steps doing for this fork as part of review contribution so that I can check with my admin for the possibility.

**Comment by satish-chinthanippu** [comment]
> > @marcosmarxm you should be able to just use /format-fix in a PR and it should format and commit into the PR automatically, if that's the only thing you need to get this to merge.
> 
> Maintainers (and bot) doesn't have access to their branch because they're using Teradata org fork. @satish-chinthanippu is it possible to enable contributions from maintainers in your fork? This will speed up the process to review the contribution.

@marcosmarxm  enabled contributions for you.

**Comment by marcosmarxm** [comment]
I think one problem the CI tests are having it is your branch is master from the fork.

**Comment by marcosmarxm** [comment]
Merged at https://github.com/airbytehq/airbyte/pull/40250

**Pull request closed without merging**
