### PR TITLE
[source-salesforce] Fix memory leak

### PR DESCRIPTION
**Pull request by nunofgs**
Fixes a memory leak in the Salesforce connector by closing the `requests` session.

I used [memray](https://bloomberg.github.io/memray) to find and diagnose the leak. To do this I updated `airbyte-integrations/connectors/source-salesforce/main.py` with:

```python
from source_salesforce.run import run
import gc

if __name__ == "__main__":
    run()
    gc.collect()
    run()
    gc.collect()
    run()
    gc.collect()
    run()
    gc.collect()
    run()
    gc.collect()
    run()
    gc.collect()
    run()
    gc.collect()
    run()
    gc.collect()
    run()
    gc.collect()
    run()
    gc.collect()
```

Here's a memory graph before:

Screenshot 2024-04-09 at 12 18 55

And here is with the fix in this PR:

Screenshot 2024-04-09 at 12 42 23

### CODE REVIEW

**Review by marcosmarxm — COMMENTED** [review]
Thanks for the contribution @nunofgs I'll request the connector team to take a look in this change. Can you sign the CLA?

**Comment by nunofgs** [comment]
👋 there were conflicts from a change in master. Just fixed and pushed.

**Comment by marcosmarxm** [comment]
@maxi297 @bazarnov can someone take a look in this contribution?

**Comment by maxi297** [comment]
We are not able to correlate prod OOM issues with this fix hence. From our perspective right now, it seems like the script mentioned in the PR description is only a problem because we call multiple times `run` which is not the case in a prod like use cases.

@nunofgs How are you using the connector? Is it within the Airbyte platform or you have a custom script calling the source-salesforce code?

**Comment by nunofgs** [comment]
@maxi297 I understand the connector is executed as a Docker container and thus memory is released once the container is killed, but the mem leak is still there and visible on long running syncs since `requests` stores the response contents in memory and the session is never released.

**Comment by maxi297** [comment]
Can you show that without memray without creating multiple sessions? My understanding is that there is a cost in terms of performance as we would need to initiate a new connection on every HTTP request

**Pull request closed without merging**
