### PR TITLE
Update transformations-with-airbyte.md

### PR DESCRIPTION
**Pull request by MiguelMadero**
Clarified how profiles.yml works when using custom transformations.

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@MiguelMadero can you sign the CLA?

**Comment by MiguelMadero** [comment]
done!

**Review by marcosmarxm — APPROVED** [review]

**Comment by octavia-approvington** [comment]
You did it! <br/> finish line

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
