### PR TITLE
🎉 New Source: LinkedIn Pages (old)

### PR DESCRIPTION
**Pull request by jscottpolevault**
## What
- Added a LinkedIn Pages connector to retrieve Organization data from LinkedIn organic efforts.
- Cannot get all of the tests to pass, but I think it's really close!

## How
- The Python CDK

## Recommended reading order
1. [source-linkedin-pages](https://github.com/jscottpolevault/airbyte/tree/master/airbyte-integrations/connectors/source-linkedin-pages)
2. [linkedin-pages.md](https://github.com/jscottpolevault/airbyte/blob/master/docs/integrations/sources/linkedin-pages.md)

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [X] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [X] Code reviews completed
- [X] Documentation updated
    - [X] Connector's `README.md`
    - [X] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [X] `docs/SUMMARY.md`
    - [X] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [X] `docs/integrations/README.md`
    - [X] `airbyte-integrations/builds.md`
- [X] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

FAILED unit_tests/test_incremental_streams.py

</details>

<details><summary><strong>Integration</strong></summary>

_No CustomIntegration Tests Added_

</details>

<details><summary><strong>Acceptance</strong></summary>

      17 passed
       3 failed
         - airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py:144 TestConnection.test_check[inputs0]
         - airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py:355 TestBasicRead.test_read[inputs0]
         - airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_full_refresh.py:39 TestFullRefresh.test_sequential_reads[inputs0]

</details>

### CODE REVIEW

**Comment by jscottpolevault** [comment]
> Just realized I have a duplicate endpoint/stream (UgcPosts is identical to Shares). I am editing the code now and will update this PR when I'm done.

Just finished removing the UGC Posts stream for initial Connector review. I can add it back in with the correct endpoint and header soon, because it needs a specific header with the API call that the other endpoints don't need.

**Comment by alafanechere** [comment]
Hey @jscottpolevault, thank you for the contribution. Could you please make sure the acceptance tests are passing? We will go for a first review once you have successfully run the acceptance tests, let us know if you need assistance for this.
I quickly check your changes and noticed you have a `spec.json` and a `spec.yaml` file, could you please keep one or the other and make sure there are no copy/paste from the LinkedinAds connectors?

**Comment by jscottpolevault** [comment]
Thanks @alafanechere! I'll do my best to get the tests passing, but any help you could provide would be helpful. I'm 3 weeks new to python so it just takes me a while to google myself over every hurdle, haha.

And yes - I'll remove the `spec.yaml` and check the code again for any variations of "LinkedIn Ads"

**Comment by alafanechere** [comment]
> I'll do my best to get the tests passing, but any help you could provide would be helpful. I'm 3 weeks new to python so it just takes me a while to google myself over every hurdle, haha.

Feel free to share your latest test output logs. In the meantime, I'll create an issue to create a sandbox account on our side so that we can run the tests in our CI.

**Comment by jscottpolevault** [comment]
So sorry to waste your time here... Is this helpful?
[acceptance_test_log-2022_05_18-1105_am_CT.txt](https://github.com/airbytehq/airbyte/files/8718062/acceptance_test_log-2022_05_18-1105_am_CT.txt)

**Review by alafanechere — CHANGES_REQUESTED** [review]
> So sorry to waste your time here... Is this helpful?
Don't worry, you're not wasting my time!
The tests are not passing because of an error in your schema: 
```python
>       schema_type = subschema.get("type", ["object", "null"])
E       AttributeError: 'list' object has no attribute 'get'
```

I think you messed up a bit with the commit history while rebasing: there are a lot of commits on this branch that do not belong to your new connector changes. Could you please merge the master branch in your branch / clean up the commit history.

**Comment by jscottpolevault** [comment]
Ok thanks! Yea I don't know what was going on with the commits, but I'll try to clean it up =)

I'll comment when the changes are done or if I have questions.

**Comment by jscottpolevault** [comment]
@alafanechere I was able to fix the schema issues and pass 20/21 tests. I’ll work on the last test issue next week, then I’ll open a new PR since I accidentally closed this one when cleaning up my branch 😅

**Comment by jscottpolevault** [comment]
@alafanechere - Could you help me understand how to fix the last error I'm getting with the Source Acceptance Tests? I can't figure out where/how to add in an "error trace message". I'm attaching my latest test log:

[TestBasicRead_Failure_2022-5-23.txt](https://github.com/airbytehq/airbyte/files/8755928/TestBasicRead_Failure_2022-5-23.txt)

**Comment by jscottpolevault** [comment]
Got it!! My Dockerfile had `FROM python:3.7.11-alpine3.14 as base` and when I changed it to `FROM python:3.9.11-alpine3.15 as base`, the last test passed =D.

I'll rebase my branch and submit a new PR now.

**Pull request closed without merging**
