### PR TITLE
Source stripe: revert 3.17.3

### PR DESCRIPTION
**Pull request by davydov-d**
Revert back the changes reverted in https://github.com/airbytehq/airbyte/pull/29309

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`4cf3a59588`](https://github.com/airbytehq/airbyte/pull/29425/commits/4cf3a59588db81ca32153306728338c62a229c3a)) - ❌

⏲️  Total pipeline duration: 07mn45s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_sorce-stripe-revert-3172/1692088662/4cf3a59588db81ca32153306728338c62a229c3a/source-stripe/3.17.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:4cf3a59588db81ca32153306728338c62a229c3a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Review by bnchrch — CHANGES_REQUESTED** [review]
Hey I dont think we needed to revert?

@davydov-d what prompted this PR?

**Comment by davydov-d** [comment]
> Hey I dont think we needed to revert?
> 
> @davydov-d what prompted this PR?

@bnchrch 3.17.2 is syncing successfully in the airbyte internal workspace on cloud

**Review by girarda — APPROVED** [review]

**Comment by octavia-approvington** [comment]
Our work here is done <br/> done

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
