### PR TITLE
displaySetupWizard to workspace

### PR DESCRIPTION
**Pull request by cgardens**
## What
* @Jamakase adding the boolean that we discussed to the workspace object.

### CODE REVIEW

**Review by michel-tricot — CHANGES_REQUESTED** [review]
Can't we express "not showing onboarding" with the booleans we already have? It will make the test to decide if we should show the onboarding more complex with this PR

**Comment by michel-tricot** [comment]
why did you decide to use another boolean instead of just setting the `completedOnboarding` to true?

**Review by sherifnada — COMMENTED** [review]
same Q as michel

**Comment by cgardens** [comment]
@michel-tricot @sherifnada - after I check with artem, I am probably going to drop `onboardingComplete` entirely in favor of `displaySetupWizard`. For now it is here so that this isn't a breaking change and can be safely merged to master.

Our goal now is to display or not the setup wizard (regardless of whether onboarding has been completed or not). Retaining the name `onboardingComplete` doesn't convey that meaning clearly. 

Lmk if that clears up the concern.

**Review by michel-tricot — APPROVED** [review]
Sounds good to me! let's get rid of one.

**Review by jrhizor — APPROVED** [review]

**Pull request merged**
