### PR TITLE
Add dependencies to docker-compose

### PR DESCRIPTION
**Pull request by gosusnp**
## What

The bootloader should run before the other applications.
If the bootloader fails, it is likely a sign that the setup failed and that we may have an unexpected state that is not safe for the other applications.
We should define the bootloader as a dependencies for the applications that depends on it.

## How
Use [conditional `depends_on`](https://docs.docker.com/compose/compose-file/#depends_on)

### CODE REVIEW

**Review by benmoriceau — CHANGES_REQUESTED** [review]
I think that we were not doing that because we can't do it on kube. Thus we rely on check like the DataBaseAvailabilityCheck to ensure that a service is started or not.
I think that we should do something similar here instead of relying on a functionality specific to docker compose because we will face the issues we are trying to solve in kube.

**Comment by gosusnp** [comment]
@benmoriceau, this check here is slightly different. It checks that the bootloader ran successfully to completion.

I am trying to confirm this in the code, but when I was asking about having the bootloader as a requirement a few months ago, I remember that when using the helm charts, we should fail a deploy where the bootloader did not finish successfully and therefore abort the upgrade in progress.

Also, I think we would still benefit from avoiding bad situation even if we cannot have this done in all the ways we are could be deployed.

**Comment by gosusnp** [comment]
@davinchia, can you confirm if my understand is correct? (In kube, we should fail hard if the bootloader fails, regardless if we use kustomize or helm)

**Comment by davinchia** [comment]
@gosusnp yes that is right! 

The other method we implemented to enforce this the [minimum flyway migration version checks](https://github.com/airbytehq/airbyte/blob/master/airbyte-config/config-models/src/main/java/io/airbyte/config/EnvConfigs.java#L101-L103), which we should be better at using. Today we don't enforce bumping this when we write new migrations.

We don't enforce this in the OSS Kustomise charts. We do enforce on Airbyte Cloud through [Helm pre-hooks](https://github.com/airbytehq/airbyte-cloud/blob/master/infra/kube/airbyte/charts/bootloader/templates/pod.yaml#L14).

**Review by benmoriceau — CHANGES_REQUESTED** [review]
Thanks for the explainations!

**Review by benmoriceau — APPROVED** [review]

**Pull request merged**
