### PR TITLE
chore(connector_ops): remove unused scripts

### PR DESCRIPTION
**Pull request by natikgadzhi**
## What

Part 1 or https://github.com/airbytehq/airbyte-internal-issues/issues/6897 — removes two unused scripts from `airbyte-ci/connector_ops`.

### CODE REVIEW

**Review by erohmensing — COMMENTED** [review]
@natikgadzhi just to be clear, the reason we're getting rid of these is because these checks are already covered in CAT right? I think we still want to check these things, maybe we're not using the scripts anymore though.

**Comment by natikgadzhi** [comment]
@erohmensing in spirit, I agree we probably want to keep these checks. I don't see them as CATs today (but maybe I'm holding them wrong). 

In `connectors_qa`, I see we're reusing `metadata_service/lib` validators, specifically this: https://github.com/airbytehq/airbyte/blob/fbfae4289da9185b647a0328ec7cd92ab2efe563/airbyte-ci/connectors/metadata_service/lib/metadata_service/validators/metadata_validator.py#L183

But alas, I don't see specific checks for allowedHosts and acceptance tests strictness. I don't understand the latter much, but former seems to be a required option. 

What do you think we should do? Want me to add a validator that allowedHosts are defined and contain at least one valid host?

**Comment by erohmensing** [comment]
@natikgadzhi I think there are allowed hosts checks [here](https://github.com/airbytehq/airbyte/blob/69b6ad4b3390d5bbe0a95a546f237582f9148560/airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py#L1331). I don't think I see anywhere where "x connector must have high strictness level" is implemented - @alafanechere might know more. We might be able to remove this concept in favor of quality level now, if we wanted

**Review by alafanechere — APPROVED** [review]
I believe `check-test-strictness-level` was used to validate a GA (certified) connector strictness level was set to `high`.
I'm not sure when / how / why it got removed. But if we really need it it's something I'd definitely check in `connectors-qa` (as allowed-host).

**Comment by natikgadzhi** [comment]
Okay than I'm merging this and taking a note to create a todo for the strictness level check. I don't know if we really believe in it.

**Pull request merged**
