### PR TITLE
Source Google Ads: Migrate to v13

### LINKED ISSUE #24331: Source Google Ads: Migrate to v13
The Google Ads API is sunsetting v11 on 29 March 2023 - https://developers.google.com/google-ads/api/docs/sunset-dates#:~:text=October%2026%2C%202022-,March%2029%2C%202023,-Upgrade%20from%20v11. So, we need migrate to the last one available. 

Slack thread - https://airbytehq.slack.com/archives/C02U9R3AF37/p1679325311427009

### PR DESCRIPTION
**Pull request by grubberr**
## What
Issue: https://github.com/airbytehq/airbyte/issues/24331

https://developers.google.com/google-ads/api/reference/rpc/v11/Ad
gmail_ad (deprecated)

Stream **"ad_group_ad_report"** fields removed:

```
- ad_group_ad.ad.gmail_ad.header_image
- ad_group_ad.ad.gmail_ad.teaser.logo_image
- ad_group_ad.ad.gmail_ad.marketing_image
- ad_group_ad.ad.gmail_ad.teaser.business_name
- ad_group_ad.ad.gmail_ad.teaser.description
- ad_group_ad.ad.gmail_ad.teaser.headline
- ad_group_ad.ad.gmail_ad.marketing_image_display_call_to_action.text
- ad_group_ad.ad.gmail_ad.marketing_image_display_call_to_action.text_color
- ad_group_ad.ad.gmail_ad.marketing_image_headline
- ad_group_ad.ad.gmail_ad.marketing_image_description
```

Stream **"ad_group_ads"** fields removed:

```
- ad_group_ad.ad.gmail_ad.header_image
- ad_group_ad.ad.gmail_ad.marketing_image
- ad_group_ad.ad.gmail_ad.marketing_image_description
- ad_group_ad.ad.gmail_ad.marketing_image_display_call_to_action.text
- ad_group_ad.ad.gmail_ad.marketing_image_display_call_to_action.text_color
- ad_group_ad.ad.gmail_ad.marketing_image_display_call_to_action.url_collection_id
- ad_group_ad.ad.gmail_ad.marketing_image_headline
- ad_group_ad.ad.gmail_ad.product_images
- ad_group_ad.ad.gmail_ad.product_videos
- ad_group_ad.ad.gmail_ad.teaser.business_name
- ad_group_ad.ad.gmail_ad.teaser.description
- ad_group_ad.ad.gmail_ad.teaser.headline
- ad_group_ad.ad.gmail_ad.teaser.logo_image
```

Stream **"ad_groups"** field changed:
```
- ad_group.explorer_auto_optimizer_setting.opt_in
+ ad_group.optimized_targeting_enabled
```

Stream **"campaigns"** field changed:
```
- campaign.target_cpm
+ campaign.target_cpm.target_frequency_goal.target_count
+ campaign.target_cpm.target_frequency_goal.time_unit
```

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Connector version has been incremented
    - [ ] Version has been bumped according to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/semantic-versioning-for-connectors) guidelines
    - [ ] `Dockerfile` has updated version
- [x] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` with an entry for the new version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)

- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Review by lazebnyi — COMMENTED** [review]
@grubberr For v12 LGTM! Let's try migrate to v13. 

 @erica-airbyte FYI 
 After we will merge this PR some fields are missing due to new version. May be we need communicate with the customers about that? WDYT?

**Comment by erica-airbyte** [comment]
@grubberr, Yes! Can you tell me:
- What fields will be missing?
- What action the customer needs to take in order to get their sync successful?
- When is this going out?

**Comment by grubberr** [comment]
@erica-airbyte

1. I have updated description of PR
2. No action needed
3. I have pass to internal review

**Comment by grubberr** [comment]
@lazebnyi @YowanR can you please advise whom I can added from Airbyte team to look on this PR ?

**Comment by erica-airbyte** [comment]
@grubberr it sounds like this change will not break any connection but users should be aware of the fields being removed. When is this being planned to go out this week or next?

**Review by lazebnyi — APPROVED** [review]
LGTM!

**Review by pedroslopez — APPROVED** [review]
LGTM, thanks for noting the field changes so we can inform our users.

**Pull request merged**
