### PR TITLE
Source GitLab: add `shared_runners_setting` field to groups

### PR DESCRIPTION
**Pull request by artem1205**
## What

Fix Source GitHLab Connector health report

## How

- fix expected records;
- add `shared_runners_setting` field to groups.

## Recommended reading order
1. `expected_records.jsonl`

## 🚨 User Impact 🚨

no breaking changes

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Review by davydov-d — COMMENTED** [review]
what's the purpose of adding `additionalProperties: true` to all schemas? afaik it is `true` by default

**Comment by artem1205** [comment]
> what's the purpose of adding `additionalProperties: true` to all schemas? afaik it is `true` by default

 it seems to be false by default From [nightly report](https://ff2fda4c3ee60a99e4101eefb2858d34b17309af8f0755b2e6d17d4-apidata.googleusercontent.com/download/storage/v1/b/airbyte-ci-reports-multi/o/airbyte-ci%2Fconnectors%2Ftest%2Fnightly_builds%2Fmaster%2F1688084364%2F84ddfa8a5a06570ed0e468ae68c386eebc897a33%2Fsource-gitlab%2F1.5.1%2Foutput.html?jk=AYvHSRFVz2YwMf0v-AYRdYgoMsNcm1lI3RlNA2mHboo5o_OqjpLPbKyj3RSyNj6fU6KXT_N4tR5WU-osgLC8RQ65bBWcfOZQVKOcLZN6x8ZaopHBpfNzGCoc2D_ASk0QqCQAK8NYSkq8azxFJrmN9Cj5E7bgiBlvwECXKDfjZ6tdOIhcw-bFiP0FbCsy44pkeziqPon6G9T1I6yDLWSDBOkP_4FwyA9wwAZFD2kJ2_0UcmCB0iMzlFDLajaQjBAHnp3gCmb2e8MOXDjj4KrKtj41xDMH9mL0t-8FkL_38pcwohxFQF1j2lByZVunywY85UwEWv-vPIj7WzEDpm-oeW8UcV2VFF4ywkSxB6T66uj77jrStT_DasMyeuRCeEJ2sc35sL5_eVTZvpguNz1i5bfdXPzaEaFKU2W1BNik17T0hHhyontNoqAUo6ha2Fdn4RrHUAoCqVlnUihnm05O1PEq79NdJAWn_p9PuuTdn6hEx9FA3TIp-lY8W3_MdTAr2fRl-F3FeK9sT4bnc8Tckpvi54on08X91fYwJq5kfVs1j5B0sjZG3Cta4s6_emm025tMgVLxV1FD3w4c59zWnfw2pjFRTqnGufhX51XKDaQqjF8rgpfwLIiawjOeWcaT-Rf5S_gsRfyar7cV2s1KDB2Y-mhzcKD8TBcROuhGEycAKrKzWCvK68D7ZDADROy3pSizd7-3aXKrSORxzOFZSCZsG7oHfXr3j5c1YhwjCUN9EZWytLbfzwOxwX2ME2Gv3INJ_DwLcsa2OlvBTnJRRaPav4vgmVphsUVTSlMYxJ8-Xm6rzXl78aq_rRzlfC4lil9OIgIxf_ZgMP5obqjGUBkV-daPSfCVmHH9jP1ehqEKJ2rzJVAfOTqGp7Be_5UnYvn4DQIMLgVsoJFLq8VBlAMwxlQXuytiCSh1RwXUJUYACEd4Yft2zJOBY8zM05Gx2pCfX-C-zgYRZPbiM8RdA60Q-MZA70hjSe98p7GI_1YjUHetljR_A_B5g14IZnwDBMrx_i5CF3q6ASLcWel5Fnnypnc6rf-znGI41Tgmlmjmoa-kv0gtDcK31Ngd7wf1GMS2_Xj6hikRLL0d2s9_zN3VBjgLbnzadv2SQ143d7OHK8GIlBXAIZt5RwAi-hKEVxXEcQMQjsalO12hpqCrHfOMO4Qo79pwtjVUsQdXn2TlTTK0gG4hoykkPOJAFLiuCH248jCe1tubtiQVztqV0tINqkhWDACpdTHgP6ksUamtw44WsW6EjkXoOUQsh3uzpvO7P6WAUlmoz06yFN49ctVeDfn7JwIT53k5Yd_MDO_PAhRyhF8dll29cOJR5urXSiErWqnb4y2QYI31JuuRCNEBOSB_fA&isca=1)

**Comment by octavia-squidington-iii** [comment]
##  source-gitlab test report (commit [`bb6584ff9d`](https://github.com/airbytehq/airbyte/pull/27869/commits/bb6584ff9da380f5ae548f537cc7bee53efe2866)) - ❌

⏲️  Total pipeline duration: 12mn42s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-gitlab/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-gitlab docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_con-health-gitlab/1688130107/bb6584ff9da380f5ae548f537cc7bee53efe2866/source-gitlab/1.6.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Comment by davydov-d** [comment]
> > what's the purpose of adding `additionalProperties: true` to all schemas? afaik it is `true` by default
> 
> it seems to be false by default From [nightly report](https://ff2fda4c3ee60a99e4101eefb2858d34b17309af8f0755b2e6d17d4-apidata.googleusercontent.com/download/storage/v1/b/airbyte-ci-reports-multi/o/airbyte-ci%2Fconnectors%2Ftest%2Fnightly_builds%2Fmaster%2F1688084364%2F84ddfa8a5a06570ed0e468ae68c386eebc897a33%2Fsource-gitlab%2F1.5.1%2Foutput.html?jk=AYvHSRFVz2YwMf0v-AYRdYgoMsNcm1lI3RlNA2mHboo5o_OqjpLPbKyj3RSyNj6fU6KXT_N4tR5WU-osgLC8RQ65bBWcfOZQVKOcLZN6x8ZaopHBpfNzGCoc2D_ASk0QqCQAK8NYSkq8azxFJrmN9Cj5E7bgiBlvwECXKDfjZ6tdOIhcw-bFiP0FbCsy44pkeziqPon6G9T1I6yDLWSDBOkP_4FwyA9wwAZFD2kJ2_0UcmCB0iMzlFDLajaQjBAHnp3gCmb2e8MOXDjj4KrKtj41xDMH9mL0t-8FkL_38pcwohxFQF1j2lByZVunywY85UwEWv-vPIj7WzEDpm-oeW8UcV2VFF4ywkSxB6T66uj77jrStT_DasMyeuRCeEJ2sc35sL5_eVTZvpguNz1i5bfdXPzaEaFKU2W1BNik17T0hHhyontNoqAUo6ha2Fdn4RrHUAoCqVlnUihnm05O1PEq79NdJAWn_p9PuuTdn6hEx9FA3TIp-lY8W3_MdTAr2fRl-F3FeK9sT4bnc8Tckpvi54on08X91fYwJq5kfVs1j5B0sjZG3Cta4s6_emm025tMgVLxV1FD3w4c59zWnfw2pjFRTqnGufhX51XKDaQqjF8rgpfwLIiawjOeWcaT-Rf5S_gsRfyar7cV2s1KDB2Y-mhzcKD8TBcROuhGEycAKrKzWCvK68D7ZDADROy3pSizd7-3aXKrSORxzOFZSCZsG7oHfXr3j5c1YhwjCUN9EZWytLbfzwOxwX2ME2Gv3INJ_DwLcsa2OlvBTnJRRaPav4vgmVphsUVTSlMYxJ8-Xm6rzXl78aq_rRzlfC4lil9OIgIxf_ZgMP5obqjGUBkV-daPSfCVmHH9jP1ehqEKJ2rzJVAfOTqGp7Be_5UnYvn4DQIMLgVsoJFLq8VBlAMwxlQXuytiCSh1RwXUJUYACEd4Yft2zJOBY8zM05Gx2pCfX-C-zgYRZPbiM8RdA60Q-MZA70hjSe98p7GI_1YjUHetljR_A_B5g14IZnwDBMrx_i5CF3q6ASLcWel5Fnnypnc6rf-znGI41Tgmlmjmoa-kv0gtDcK31Ngd7wf1GMS2_Xj6hikRLL0d2s9_zN3VBjgLbnzadv2SQ143d7OHK8GIlBXAIZt5RwAi-hKEVxXEcQMQjsalO12hpqCrHfOMO4Qo79pwtjVUsQdXn2TlTTK0gG4hoykkPOJAFLiuCH248jCe1tubtiQVztqV0tINqkhWDACpdTHgP6ksUamtw44WsW6EjkXoOUQsh3uzpvO7P6WAUlmoz06yFN49ctVeDfn7JwIT53k5Yd_MDO_PAhRyhF8dll29cOJR5urXSiErWqnb4y2QYI31JuuRCNEBOSB_fA&isca=1)

@artem1205 nope, it is enforced during the test run: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/utils/asserts.py#L56

but default is true https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/connector-acceptance-test/connector_acceptance_test/tests/test_core.py#L669

**Comment by octavia-squidington-iii** [comment]
##  source-gitlab test report (commit [`c4c4c7816f`](https://github.com/airbytehq/airbyte/pull/27869/commits/c4c4c7816ff735f9be1eb08678db1e301db03c4f)) - ❌

⏲️  Total pipeline duration: 13mn19s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-gitlab/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-gitlab docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_con-health-gitlab/1688135721/c4c4c7816ff735f9be1eb08678db1e301db03c4f/source-gitlab/1.6.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Comment by octavia-squidington-iii** [comment]
##  source-gitlab test report (commit [`c4c4c7816f`](https://github.com/airbytehq/airbyte/pull/27869/commits/c4c4c7816ff735f9be1eb08678db1e301db03c4f)) - ❌

⏲️  Total pipeline duration: 14mn08s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-gitlab/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-gitlab docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_con-health-gitlab/1688136706/c4c4c7816ff735f9be1eb08678db1e301db03c4f/source-gitlab/1.6.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Comment by octavia-squidington-iii** [comment]
##  source-gitlab test report (commit [`b2f16d3789`](https://github.com/airbytehq/airbyte/pull/27869/commits/b2f16d3789e7e7edf5dda60e02c8fcec36d37c40)) - ❌

⏲️  Total pipeline duration: 13mn04s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-gitlab/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-gitlab docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_con-health-gitlab/1688236181/b2f16d3789e7e7edf5dda60e02c8fcec36d37c40/source-gitlab/1.6.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Comment by octavia-squidington-iii** [comment]
##  source-gitlab test report (commit [`afe478fa0c`](https://github.com/airbytehq/airbyte/pull/27869/commits/afe478fa0cae673d213013ce23832f496c533174)) - ✅

⏲️  Total pipeline duration: 12mn51s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-gitlab/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-gitlab docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_con-health-gitlab/1688238312/afe478fa0cae673d213013ce23832f496c533174/source-gitlab/1.6.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Review by davydov-d — APPROVED** [review]

**Review by lazebnyi — APPROVED** [review]

**Pull request merged**
