### PR TITLE
Close all unsafe queries

### LINKED ISSUE #10129: Ensure every JDBC database use case that returns a stream is closed
## Problem
Some of the `JdbcDatabase` methods return a stream embedded with a database connection. The connection can only be closed when the consumption of the stream is done (in an `onClose` callback), and the closure is not automatic. There are use cases that do not manually close those streams. This is not an intuitive operation because most Java streams do not require closure, as they are not involved with resources.

## Solution
- [x] [Minimum Requirement] Check every such use case and make sure the stream is closed or put in a `try` block.
- [x] [Nice to Have] Refactor the `JdbcDatabase` methods to remove those that return streams as much as possible.

### PR DESCRIPTION
**Pull request by tuliren**
- The `unsafeQuery` methods return a stream that needs to be closed. In many of the cases, they are currently not.
- This PR closes all unclosed streams returned from `unsafeQuery`.
- Close https://github.com/airbytehq/airbyte/issues/10129.
- Maybe relate to https://github.com/airbytehq/oncall/issues/191.

### CODE REVIEW

**Comment by tuliren** [comment]
MySQL destination acceptance test has been broken for a while due to normalization. It is not obvious why it fails. Should irrelevant to this PR. Will merge the PR without fixing that.

**Review by edgao — APPROVED** [review]
nice! I only skimmed the changes since they all looked pretty similar, but if they're passing tests then it's good enough for me :shipit:

**Pull request merged**
