### PR TITLE
🐛 Source Github, Instagram, Zendesk Support / Talk - revert `spec` changes and improve

### PR DESCRIPTION
**Pull request by bazarnov**
## What
Need to revert and  improve these  changes: https://github.com/airbytehq/airbyte/pull/28910/files
Based on this thread: https://airbyte-globallogic.slack.com/archives/C02U9R3AF37/p1691051270555369

## How
- reverted `spec` changes back
- added missing fields to the `spec` and  made them optional for the user,  instead of removing,  because  of this dependency: https://github.com/airbytehq/airbyte-platform-internal/blob/186c6e194e173ab23db4aa0271e588264165bcbf/oss/airbyte-persistence/job-persistence/src/main/java/io/airbyte/persistence/job/factory/OAuthConfigSupplier.java#L198

## 🚨 User Impact 🚨
I very much hope, there is no other place where any `OAuth` issues could come up again.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-zendesk-talk test report (commit [`1ee5356788`](https://github.com/airbytehq/airbyte/pull/29031/commits/1ee53567889dbf2eff329f6bd4164ba7a546bd36)) - ✅

⏲️  Total pipeline duration: 04mn43s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zendesk-talk/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ✅        |
| QA checks                                                                  | ✅        |
| Code format checks                                                         | ✅        |
| Connector package install                                                  | ✅        |
| Build source-zendesk-talk docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                 | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-github-zendesk-support-talk-instagram-revert-spec-changes/1691058142/1ee53567889dbf2eff329f6bd4164ba7a546bd36/source-zendesk-talk/0.1.9/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1ee53567889dbf2eff329f6bd4164ba7a546bd36)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-talk test
```

**Review by arsenlosenko — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-github test report (commit [`1ee5356788`](https://github.com/airbytehq/airbyte/pull/29031/commits/1ee53567889dbf2eff329f6bd4164ba7a546bd36)) - ✅

⏲️  Total pipeline duration: 11mn02s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-github/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-github docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-github-zendesk-support-talk-instagram-revert-spec-changes/1691058142/1ee53567889dbf2eff329f6bd4164ba7a546bd36/source-github/1.0.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1ee53567889dbf2eff329f6bd4164ba7a546bd36)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zendesk-support test report (commit [`1ee5356788`](https://github.com/airbytehq/airbyte/pull/29031/commits/1ee53567889dbf2eff329f6bd4164ba7a546bd36)) - ✅

⏲️  Total pipeline duration: 12mn12s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zendesk-support/metadata.yaml | ✅        |
| Connector version semver check                                                | ✅        |
| Connector version increment check                                             | ✅        |
| QA checks                                                                     | ✅        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build source-zendesk-support docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ✅        |
| Acceptance tests                                                              | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-github-zendesk-support-talk-instagram-revert-spec-changes/1691058142/1ee53567889dbf2eff329f6bd4164ba7a546bd36/source-zendesk-support/0.10.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1ee53567889dbf2eff329f6bd4164ba7a546bd36)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-support test
```

**Review by artem1205 — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-zendesk-talk test report (commit [`1ee5356788`](https://github.com/airbytehq/airbyte/pull/29031/commits/1ee53567889dbf2eff329f6bd4164ba7a546bd36)) - ✅

⏲️  Total pipeline duration: 03mn54s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zendesk-talk/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ✅        |
| QA checks                                                                  | ✅        |
| Code format checks                                                         | ✅        |
| Connector package install                                                  | ✅        |
| Build source-zendesk-talk docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                 | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-github-zendesk-support-talk-instagram-revert-spec-changes/1691058970/1ee53567889dbf2eff329f6bd4164ba7a546bd36/source-zendesk-talk/0.1.9/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1ee53567889dbf2eff329f6bd4164ba7a546bd36)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-talk test
```

**Comment by octavia-squidington-iii** [comment]
##  source-instagram test report (commit [`1ee5356788`](https://github.com/airbytehq/airbyte/pull/29031/commits/1ee53567889dbf2eff329f6bd4164ba7a546bd36)) - ❌

⏲️  Total pipeline duration: 07mn02s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-instagram/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ❌        |
| Connector package install                                               | ✅        |
| Build source-instagram docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Integration tests                                                       | ✅        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-github-zendesk-support-talk-instagram-revert-spec-changes/1691058970/1ee53567889dbf2eff329f6bd4164ba7a546bd36/source-instagram/1.0.11/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1ee53567889dbf2eff329f6bd4164ba7a546bd36)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-instagram test
```

**Comment by octavia-squidington-iii** [comment]
##  source-github test report (commit [`1ee5356788`](https://github.com/airbytehq/airbyte/pull/29031/commits/1ee53567889dbf2eff329f6bd4164ba7a546bd36)) - ✅

⏲️  Total pipeline duration: 10mn37s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-github/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-github docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-github-zendesk-support-talk-instagram-revert-spec-changes/1691058970/1ee53567889dbf2eff329f6bd4164ba7a546bd36/source-github/1.0.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1ee53567889dbf2eff329f6bd4164ba7a546bd36)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zendesk-support test report (commit [`1ee5356788`](https://github.com/airbytehq/airbyte/pull/29031/commits/1ee53567889dbf2eff329f6bd4164ba7a546bd36)) - ✅

⏲️  Total pipeline duration: 11mn45s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zendesk-support/metadata.yaml | ✅        |
| Connector version semver check                                                | ✅        |
| Connector version increment check                                             | ✅        |
| QA checks                                                                     | ✅        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build source-zendesk-support docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ✅        |
| Acceptance tests                                                              | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-github-zendesk-support-talk-instagram-revert-spec-changes/1691058970/1ee53567889dbf2eff329f6bd4164ba7a546bd36/source-zendesk-support/0.10.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1ee53567889dbf2eff329f6bd4164ba7a546bd36)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-support test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zendesk-talk test report (commit [`b4531ac1c9`](https://github.com/airbytehq/airbyte/pull/29031/commits/b4531ac1c9fa9f2fc8482577e59515e27a0c47a5)) - ✅

⏲️  Total pipeline duration: 04mn20s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zendesk-talk/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ✅        |
| QA checks                                                                  | ✅        |
| Code format checks                                                         | ✅        |
| Connector package install                                                  | ✅        |
| Build source-zendesk-talk docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                 | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-github-zendesk-support-talk-instagram-revert-spec-changes/1691059772/b4531ac1c9fa9f2fc8482577e59515e27a0c47a5/source-zendesk-talk/0.1.9/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b4531ac1c9fa9f2fc8482577e59515e27a0c47a5)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-talk test
```

**Comment by octavia-squidington-iii** [comment]
##  source-instagram test report (commit [`b4531ac1c9`](https://github.com/airbytehq/airbyte/pull/29031/commits/b4531ac1c9fa9f2fc8482577e59515e27a0c47a5)) - ❌

⏲️  Total pipeline duration: 07mn37s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-instagram/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-instagram docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Integration tests                                                       | ✅        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-github-zendesk-support-talk-instagram-revert-spec-changes/1691059772/b4531ac1c9fa9f2fc8482577e59515e27a0c47a5/source-instagram/1.0.11/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b4531ac1c9fa9f2fc8482577e59515e27a0c47a5)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-instagram test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zendesk-support test report (commit [`b4531ac1c9`](https://github.com/airbytehq/airbyte/pull/29031/commits/b4531ac1c9fa9f2fc8482577e59515e27a0c47a5)) - ✅

⏲️  Total pipeline duration: 12mn01s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zendesk-support/metadata.yaml | ✅        |
| Connector version semver check                                                | ✅        |
| Connector version increment check                                             | ✅        |
| QA checks                                                                     | ✅        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build source-zendesk-support docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ✅        |
| Acceptance tests                                                              | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-github-zendesk-support-talk-instagram-revert-spec-changes/1691059772/b4531ac1c9fa9f2fc8482577e59515e27a0c47a5/source-zendesk-support/0.10.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b4531ac1c9fa9f2fc8482577e59515e27a0c47a5)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-support test
```

**Comment by octavia-squidington-iii** [comment]
##  source-github test report (commit [`b4531ac1c9`](https://github.com/airbytehq/airbyte/pull/29031/commits/b4531ac1c9fa9f2fc8482577e59515e27a0c47a5)) - ✅

⏲️  Total pipeline duration: 12mn25s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-github/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-github docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-github-zendesk-support-talk-instagram-revert-spec-changes/1691059772/b4531ac1c9fa9f2fc8482577e59515e27a0c47a5/source-github/1.0.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b4531ac1c9fa9f2fc8482577e59515e27a0c47a5)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zendesk-talk test report (commit [`30be305236`](https://github.com/airbytehq/airbyte/pull/29031/commits/30be3052369261f10852ec3f27256f293482ad78)) - ✅

⏲️  Total pipeline duration: 03mn59s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zendesk-talk/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ✅        |
| QA checks                                                                  | ✅        |
| Code format checks                                                         | ✅        |
| Connector package install                                                  | ✅        |
| Build source-zendesk-talk docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                 | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-github-zendesk-support-talk-instagram-revert-spec-changes/1691062337/30be3052369261f10852ec3f27256f293482ad78/source-zendesk-talk/0.1.9/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:30be3052369261f10852ec3f27256f293482ad78)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-talk test
```

**Comment by octavia-squidington-iii** [comment]
##  source-instagram test report (commit [`30be305236`](https://github.com/airbytehq/airbyte/pull/29031/commits/30be3052369261f10852ec3f27256f293482ad78)) - ✅

⏲️  Total pipeline duration: 06mn43s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-instagram/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-instagram docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Integration tests                                                       | ✅        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-github-zendesk-support-talk-instagram-revert-spec-changes/1691062337/30be3052369261f10852ec3f27256f293482ad78/source-instagram/1.0.11/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:30be3052369261f10852ec3f27256f293482ad78)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-instagram test
```

**Comment by octavia-squidington-iii** [comment]
##  source-github test report (commit [`30be305236`](https://github.com/airbytehq/airbyte/pull/29031/commits/30be3052369261f10852ec3f27256f293482ad78)) - ✅

⏲️  Total pipeline duration: 10mn31s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-github/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-github docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-github-zendesk-support-talk-instagram-revert-spec-changes/1691062337/30be3052369261f10852ec3f27256f293482ad78/source-github/1.0.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:30be3052369261f10852ec3f27256f293482ad78)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zendesk-support test report (commit [`30be305236`](https://github.com/airbytehq/airbyte/pull/29031/commits/30be3052369261f10852ec3f27256f293482ad78)) - ✅

⏲️  Total pipeline duration: 11mn54s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zendesk-support/metadata.yaml | ✅        |
| Connector version semver check                                                | ✅        |
| Connector version increment check                                             | ✅        |
| QA checks                                                                     | ✅        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build source-zendesk-support docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ✅        |
| Acceptance tests                                                              | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-github-zendesk-support-talk-instagram-revert-spec-changes/1691062337/30be3052369261f10852ec3f27256f293482ad78/source-zendesk-support/0.10.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:30be3052369261f10852ec3f27256f293482ad78)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-support test
```

**Pull request merged**
