### PR TITLE
🎉 New Source: RabbitMQ

### PR DESCRIPTION
**Pull request by amitza**
## What
Adding a new source, [RabbitMQ](https://www.rabbitmq.com), according to [This Issue](https://github.com/airbytehq/airbyte/issues/14468#issue-1296437516)

## How
The new source will read all messages from a single queue 

## Recommended reading order
1. `source.py`

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

Results (10.40s):
      12 passed
       3 failed
         - ../airbyte/source_acceptance_test/source_acceptance_test/tests/test_core.py:170 TestConnection.test_check[inputs0]
         - ../airbyte/source_acceptance_test/source_acceptance_test/tests/test_core.py:381 TestBasicRead.test_read[inputs0]
         - ../airbyte/source_acceptance_test/source_acceptance_test/tests/test_full_refresh.py:39 TestFullRefresh.test_sequential_reads[inputs0]    

</details>

### CODE REVIEW

**Comment by alafanechere** [comment]
Thank you for this contribution @amitza , could you please mark the PR as ready for review if you finished drafting it?

**Comment by alafanechere** [comment]
Could you also please share the output of the acceptance tests by running:
./gradlew :airbyte-integrations:connectors:source-rabbitmq:integrationTest

**Comment by amitza** [comment]
> Thank you for this contribution @amitza , could you please mark the PR as ready for review if you finished drafting it?

No problem, I'm having some design considerations that I can use some help with:

Replicating data from a streaming service like Kafka or RabbitMQ is a bit different from replicating from S3 or classic database.
I need to understand what's the best way to perform an ETL pipeline originating from constant stream of messages.
The connection needs to always be online, consume messages, batch a collection of messages and than, for example, create a parquet file.

I saw something about event streaming [in the docs](https://airbyte.com/connector-categories/event-streaming) but it was empty.
Maybe you have a plan for these kind of use-cases?

**Comment by marcosmarxm** [comment]
@amitza do you want to continue the work here? The PR still a draft and not to review.

**Comment by amitza** [comment]
> @amitza do you want to continue the work here? The PR still a draft and not to review.

yes, I had some medical issues that prevented me from working for several weeks but I'm fine now

**Comment by marcosmarxm** [comment]
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

**Comment by marcosmarxm** [comment]
Closing due inactivity @amitza let me know if you want to continue the work. Probably opening a new PR for that!

**Pull request closed without merging**
