### PR TITLE
🐛 Source Amazon Seller Partner: Fix non vendor accounts connector create/check issue

### PR DESCRIPTION
**Pull request by animer3009**
## What
Bug fix!
After @roman-yermilov-gl change's merge  [\#23980](https://github.com/airbytehq/airbyte/pull/23980) we got the bug.
Non vendors accounts can't create/check connector.
He changed **Orders** stream with **VendorSalesReports** in the **check_connection** function.
When reviewer asked why did he made this change, he provided this ticket:
https://github.com/airbytehq/airbyte/issues/12124

In fact itself @krisjan-oldekamp already did fix early before, just looks like ticket left open...
You can find code by @krisjan-oldekamp :

            # Additional check, since Vendor-ony accounts within Amazon Seller API will not pass the test without this exception
            if "403 Client Error" in str(e):
                return True, None

So ASAP need merge and fix this stuff.

## How
With changing Amazon Seller Partner Source connector

### CODE REVIEW

**Comment by animer3009** [comment]
@lazebnyi @bazarnov @davydov-d @sajarin
Guys please review my changes to merge.

**Review by roman-yermilov-gl — APPROVED** [review]

**Review by lazebnyi — CHANGES_REQUESTED** [review]
I requested changes to be made in order to block PR for the purpose of investigating an issue.

**Review by roman-yermilov-gl — CHANGES_REQUESTED** [review]
@animer3009 
Could you please provide us with some examples/logs/environment or anything so we can see the bug? The task I refer in my PR is about the same bug but for vendor only accounts, so if we switch back to `Orders` stream we will switch back to the previous version of this bug. It would be better not to switch between bugs from time to time but figure out the real cause of the issue

**Comment by animer3009** [comment]
@roman-yermilov-gl we are not switch between bugs!
Check the code. Issue was already fixed by  @krisjan-oldekamp. Just looks like ticket left open. Please check dates as well...

        # Additional check, since Vendor-ony accounts within Amazon Seller API will not pass the test without this exception
        if "403 Client Error" in str(e):
            return True, None

**Comment by roman-yermilov-gl** [comment]
> @roman-yermilov-gl we are not switch between bugs! Please check the code. Issue was already fixed by @krisjan-oldekamp. Just looks like ticket left open. Please check dates as well... p.s. unfortunately I have the no vendor account... Can you provide some logs that vendors have issue with old code version?
> 
> ```
>     # Additional check, since Vendor-ony accounts within Amazon Seller API will not pass the test without this exception
>     if "403 Client Error" in str(e):
>         return True, None
> ```

Ok, I see the issue https://github.com/airbytehq/airbyte/issues/12124 and PR https://github.com/airbytehq/airbyte/pull/16629 created by the same person ([krisjan-oldekamp](https://github.com/krisjan-oldekamp)) and the issue is few month older than PR. As I also don't have vendor account to check it works, I can only suppose [krisjan-oldekamp](https://github.com/krisjan-oldekamp) tested his PR using vendor account because he is a requester of chacnges related to this account type. If so, then the issue was no longer valid at that moment when I started working on it. I agree with changes in this PR

@lazebnyi 
It looks like that crime have solved

**Review by roman-yermilov-gl — APPROVED** [review]

**Comment by roman-yermilov-gl** [comment]
@animer3009 
Could you please clarify what type of bug did you get?
You are saying there is an error handler for vendor only account:
```
# Additional check, since Vendor-ony accounts within Amazon Seller API will not pass the test without this exception
if "403 Client Error" in str(e):
    return True, None
```
This error handler works both ways: having Seller account we are using `VendorSalesReports` stream to check connection. It causes request to fail with 403 error and the error handler (snippet above) should handle it for us properly.
So it means you PR makes no sense as well as mine https://github.com/airbytehq/airbyte/pull/23980

**Comment by roman-yermilov-gl** [comment]
@animer3009 
I assume there is another cause of 400 Bad Request error on check_connection on your side

**Comment by animer3009** [comment]
@roman-yermilov-gl
So why it does not work for me?
But in `Orders` case it is OK?
What if we will have two try there and will check both?

**Comment by animer3009** [comment]
@roman-yermilov-gl
What can be issue when in `Orders` case all looks good?
After about 1 hour I will update you.

**Comment by roman-yermilov-gl** [comment]
@animer3009 
Is there any other information in error response body? Or maybe you can share for us affected workspace so we can investigate it? I understand that there is something wrong but there may be various reasons: region, wrong advanced stream options, amazon account problems/permissions or whatever else

**Comment by animer3009** [comment]
@roman-yermilov-gl  Sorry but I am not authorized to share my company owned business credentials.

I tried to log it one more time...

> 2023-06-06 19:37:50 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - I am here!!!!!!
> 2023-06-06 19:37:50 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - 400 Client Error: Bad Request for url: https://sellingpartnerapi-na.amazon.com/reports/2021-06-30/reports
> 2023-06-06 19:37:50 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - I am here!!!!!!

Same for the EU with eu account credentials.

> 2023-06-06 20:10:37 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - I am here!!!!!!
2023-06-06 20:10:37 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - 400 Client Error: Bad Request for url: https://sellingpartnerapi-eu.amazon.com/reports/2021-06-30/reports
2023-06-06 20:10:37 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):312 - I am here!!!!!!

We use this connector in the production...
By rolling back this change (As Vendor's case was already solved) our case will be solved too...
Right now we are only able to create connectors using API as it skips check...

FYI - we have different accounts and we are getting reports from different regions. Just accounts are not Vendor ones and we are facing the same issue for all of them.

Another way is to make two separate checks.
If **Orders** stream will fail then we will check **VendorSalesReports**...
This is not the best solution but others also can face this issue and have no idea what to do...
I am just trying to avoid error code dependence with this...

Possibly you are right and somewhere some permission or some other issue is on our account side, but all our all stuff was done by ASP documentations and we have no idea how it can be solved.

**Comment by animer3009** [comment]
@roman-yermilov-gl
I found the reason!
**VendorSalesReports** is **GET_VENDOR_SALES_REPORT**
https://developer-docs.amazon.com/sp-api/docs/report-type-values-analytics

It at last need reportPeriod option to be set.

`{"GET_VENDOR_SALES_REPORT":{"reportPeriod": "WEEK"}}`

It helped in US region but still have issue for UK...

As users will not have set the option by default, they will also face this issue.

So I am asking merge my change and return back what was before.
Old code handles Vendors case as well.

@lazebnyi please check this stuff.

Thanks!

**Comment by marcosmarxm** [comment]
@roman-yermilov-gl if we return to `Orders` https://github.com/airbytehq/airbyte/issues/12124 won't work... maybe we must find another way to figure out how to do the check connection for Amazon Seller Partner.

**Comment by roman-yermilov-gl** [comment]
@animer3009 
In order for this to be merged we need to ensure that everything works right, so we need tests to run successfully on both vendor and seller accounts. 

@marcosmarxm I think we need to create vendor account on amazon seller partner with at least one order and then update our acceptance tests by including this account to `connection` section

**Comment by marcosmarxm** [comment]
@roman-yermilov-gl can you handle this? I don't have much knowledge on Amazon Seller Partner.

**Comment by roman-yermilov-gl** [comment]
@marcosmarxm 
I am currently busy with another stuff in scope of Q2B, so I can't spend much time on this issue

cc: @lazebnyi

**Comment by animer3009** [comment]
@marcosmarxm
@roman-yermilov-gl

Can you guys just trust me and merge code lol?
This code was already in "production" for a long time... So we can't make it worse lol :)

**Comment by animer3009** [comment]
@marcosmarxm
@roman-yermilov-gl
@lazebnyi
Guys,
any idea/any update?

**Comment by marcosmarxm** [comment]
@animer3009 you can build the connector in your side and use the changes. Right now this isn't a priority in our backlog and it will take some time to get finished and merged.

**Review by marcosmarxm — APPROVED** [review]

**Comment by nicksaroki** [comment]
@marcosmarxm, could this move up on the team's priority list? It renders the Amazon Selling Partner source as useless. Other complaints about this same issue here: #25674.

**Review by lazebnyi — APPROVED** [review]

**Comment by marcosmarxm** [comment]
@animer3009 @nicksaroki yes, I'm going to handle this week. Amazon Seller Partner tests are broken and I'm working to fix them.

**Comment by marcosmarxm** [comment]
Tests are all green https://github.com/airbytehq/airbyte/pull/28492#issuecomment-1662464551

**Pull request merged**
