### PR TITLE
🐞 Source google sheets: fix nonetype exception when no spreadsheet id is found

### PR DESCRIPTION
**Pull request by tuliren**
## What
- Resolve https://github.com/airbytehq/oncall/issues/771.

### CODE REVIEW

**Review by alafanechere — APPROVED** [review]
Thanks for the fix! Do not forget to bump the connection version in the Dockerfile + Changelog before publishing.

**Comment by tuliren** [comment]
The publication failed:

```
 > [builder 2/4] RUN apk --no-cache upgrade     && pip install --upgrade pip     && apk --no-cache add tzdata build-base:
#7 0.269 qemu: qemu_thread_create: Operation not permitted
------
error: failed to solve: executor failed running [/bin/sh -c apk --no-cache upgrade     && pip install --upgrade pip     && apk --no-cache add tzdata build-base]: exit code: 139
```

The error looks transient though.

**Comment by tuliren** [comment]
/publish connector=connectors/source-google-sheets run-tests=false

**Pull request merged**
