### PR TITLE
🎉 Migrate BigCommerce Source Connector to Low Code

### LINKED ISSUE #28111: BigCommerce
Please use the [connector builder](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/?_gl=1*13hxonw*_gcl_au*MTI0NTMzNjM3OS4xNjkwODM4MzE0*_ga*MTg2NTc3OTc0Ni4xNjUxNTk0NTQw*_ga_HDBMVFQGBH*MTY5MTAwNDEzMy4yNzIuMC4xNjkxMDA0MTMzLjAuMC4w&_ga=2.197654767.1978878.1690818922-1865779746.1651594540) for this.

### PR DESCRIPTION
**Pull request by topefolorunso**
## What
Migrating Source BigCommerce to Low-Code resolves #28111 

## How
Created the connector using the connector buider UI, then imported the manifest.yaml to the low code cdk.

## Recommended reading order
1. `manifest.yaml`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hello 👋 , right now Airbyte's integration tests are failing for this connector and I'm going to work during the week to fix them. Due a high number of contributions we have a backlog and your contribution will be review next week. We ask to you share the integration test from your side whatever possible and if you don't have credentials to run tests to get in touch with @RealChrisSean as soon as possible. Also some common missing steps contributors does migrating to low code are (and you can double check to make sure you implemented this): 
* adding paginator
* update the documentation changelog + metadata file and dockerfile version
* if the connector has `start_date` parameter you must implement incremental syncs

**Review by sajarin — CHANGES_REQUESTED** [review]

**Comment by topefolorunso** [comment]
Fixed now @sajarin, please review

**Comment by sajarin** [comment]
Thanks @topefolorunso right now, we're having some issues with our credentials so we'll be able to merge this once we get that sorted out. Thanks for being patient.

**Comment by topefolorunso** [comment]
> Thanks @topefolorunso right now, we're having some issues with our credentials so we'll be able to merge this once we get that sorted out. Thanks for being patient.

Thanks @sajarin, that's noted

**Comment by sajarin** [comment]
The issue with credentials has been resolved for now, running tests in the PR above.

**Comment by topefolorunso** [comment]
Any update on this? @sajarin

**Comment by sajarin** [comment]
hey @topefolorunso sorry for the delay, 

Not sure if you can see the failed test out in the PR linked above but I don't think the pages stream is implemented properly. In the python version, I think it is using id as the state value whereas here we seem to be using date-modified, which I could not find is a value returned by this endpoint in the API. 

Can you take a look at fixing this stream? Let me know if you are unable to view the error logs.

**Comment by topefolorunso** [comment]
I am unable to view the error logs. I will take another look at the pages stream now, and try to fix it asap. Please share the error if possible.

**Comment by sajarin** [comment]
@topefolorunso here's the log with the errors: 

[test_run.txt](https://github.com/airbytehq/airbyte/files/12602017/test_run.txt)

**Comment by topefolorunso** [comment]
Please run tests and review again @sajarin

**Review by sajarin — APPROVED** [review]

**Comment by sajarin** [comment]
Thanks for the PR @topefolorunso 🎉 glad we could get this merged!

**Comment by topefolorunso** [comment]
> Thanks for the PR @topefolorunso 🎉 glad we could get this merged!

Thank you too @sajarin for your support through the process.

**Pull request merged**
