### PR TITLE
new source connector: google ads

### PR DESCRIPTION
**Pull request by saynomoo**
## What
*A new source connector utilizing the google ads api & GAQL*

## How
*The source connector takes GAQL statements per stream as config, parses the catalog from there and pulls data accordingly*

## Recommended reading order
1. `source.py`

## Pre-merge Checklist
Expand the checklist which is relevant for this PR. 

<details><summary> <strong> Connector checklist </strong> </summary>
<p>

- [x] Issue acceptance criteria met
- [x] Unit & integration tests added as appropriate (and are passing)
    * Community members: please provide proof of this succeeding locally e.g: screenshot or copy-paste acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] `/test` command documented [here]() is passing. 
    * Community members can skip this, Airbyters will run this for you. 
- [ ] Code reviews completed
- [ ] Credentials added to Github CI if needed and not already present. [instructions for injecting secrets into CI](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#using-credentials-in-ci). 
- [ ] Documentation updated 
    - [ ] README
    - [ ] CHANGELOG.md
    - [ ] Reference docs in the `docs/integrations/` directory.
- [ ] Build is successful
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] No major blockers
- [ ] PR merged into master branch
- [ ] Follow up tickets have been created
- [ ] Associated tickets have been closed & stakeholders notified
</p>
</details>

### CODE REVIEW

**Comment by sherifnada** [comment]
@saynomoo thank you for your contribution! I really like the idea of allowing the user to input custom GAQL to define streams. 

Incredible coincidence of timing, @harshithmullapudi also just opened a PR to create the Google Ads connector, albeit in a different way #3842 . Here's how I see the two PRs: this PR allows more expressive, while the other PR follows the more standard patterns and best practices for creating a connector using the CDK. I'm wondering if there is a way to get the best of both PRs: the patterns introduced in #3842 and the flexibility exposed by your PR. Would you be open to joining forces with harshith to create a connector which contains both feature sets? 

I'm thinking there are two ways to do this: 
1. Wait for him to merge his PR and build on top of it. This will block you temporarily until his work is merged to master but you'd be building on solid ground
2. Try to build on top of that PR while it's in flight. Will reduce total turnaround but might incur more code churn due to conflicts

I recommend 1 but if you're on a tight timeline 2 might be best. 

WDYT?

**Comment by saynomoo** [comment]
I don't think it makes sense for me to start consolidating the two PRs while it is a moving target. I can take a look after #3842 is merged.

**Comment by yevhenii-ldv** [comment]
Hi, @saynomoo, #3842 already merged, than you can continue consolidating the two PRs.

**Comment by marcosmarxm** [comment]
@saynomoo do you want to continue this contribution?

**Comment by sherifnada** [comment]
@saynomoo we added the ability to run custom queries on the existing Google Ads connector a few weeks ago, closing this PR since I believe that's what it was implementing. Apologies for that initial double booking!

**Pull request closed without merging**
