### PR TITLE
Add workspaceId to intercom custom attributes

### PR DESCRIPTION
**Pull request by jamakase**
## What
Adds `workspace_id` to intercom custom attributes

### CODE REVIEW

**Review by nataliekwong — APPROVED** [review]

**Review by jrhizor — APPROVED** [review]

**Comment by nataliekwong** [comment]
@Jamakase I see an error in the branch being deployed - does that block it from being merged?

**Comment by Jamakase** [comment]
@nataliekwong TBH I am not sure what this deployed error is for. As I remember guys are deploying UI to the cloud manually via new release.

@davinchia am I right?

**Comment by davinchia** [comment]
yeap! this will be the in the next release and pulled in once we deploy to Cloud. @nataliekwong is it urgent to get this out?

**Comment by nataliekwong** [comment]
We need the workspace ID surfaced in order to launch product tours (since Intercom needs to show the product tour for a given URL, and the workspace ID is now in the URL). When do you expect the next release to be? If it's in the early part of this week / next few days, I'm fine with waiting. @davinchia

**Pull request merged**
