### PR TITLE
Bump mina-sshd from 2.7.0 to 2.8.0

### PR DESCRIPTION
**Pull request by evansmurithi**
Testing!!!## What
When creating a Postgres destination connector with SSH tunnel method 'SSH Key Authentication', one is required to provide a RSA key. Creating a `rsa-sha2-256 or rsa-sha2-512` key, will result in the error `SshException: KeyExchange signature verification failed for key type=ssh-rsa`, if you haven't enabled ssh-rsa in the SSH server's host key algorithms.

mina-sshd in version 2.7.0 uses the wrong server key signature algorithm during DH group key exchange. https://issues.apache.org/jira/browse/SSHD-1163.

## How
Bumping mina-sshd to version 2.8.0 addresses this issue. Changelog https://github.com/apache/mina-sshd/blob/master/docs/changes/2.8.0.md.

## Recommended reading order
1. https://issues.apache.org/jira/browse/SSHD-1163
2. https://github.com/apache/mina-sshd/blob/master/docs/changes/2.8.0.md

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by alafanechere** [comment]
Thank you for spotting this @Alessandro Pietrobon, I'm going to try to run our test suite on your branch to check if the test passes.

**Review by supertopher — APPROVED** [review]
these are the best numbers.
LGTM 
image

**Review by supertopher — CHANGES_REQUESTED** [review]
forgive my taking back here.  I was late to the conversation.  sorry for the mixed signal :(

**Comment by supertopher** [comment]
@evansmurithi I just wanted to explain myself here Evan, sorry for the drama.  I thought this was an internal team request which I'm more trigger happy to grant.  We will need to release a new version of every connector for this change, which is probably fine, but I want approval from that team before moving forward.  You will hear back from us soon, I just jumped the gun.  Sorry for the noise, thank you for the PR.  Your contribution is welcome and appreciated.

**Comment by evansmurithi** [comment]
@supertopher no worries. That makes sense 🙂

**Comment by alafanechere** [comment]
I confirm I was able to build and `base-java` locally from this branch:
`./gradlew :airbyte-integrations:bases:base-java:test`:
Screen Shot 2022-04-01 at 11 47 29

I also successfully ran the connector base build from this in this [PR](https://github.com/airbytehq/airbyte/pull/11588).

**Review by sherifnada — APPROVED** [review]
LGTM but please make sure to publish all dependent connector versions

**Review by supertopher — APPROVED** [review]

**Comment by sherifnada** [comment]
@alafanechere that list also includes: 
* mysql source
* cockroach source
otherwise SGTM!

**Comment by octavia-squidington-iii** [comment]
Marcos Marx commented: /test connector=connectors/destination-gcs
> :clock2: connectors/destination-gcs https://github.com/airbytehq/airbyte/actions/runs/2092366494
> :white_check_mark: connectors/destination-gcs https://github.com/airbytehq/airbyte/actions/runs/2092366494
No Python unittests run
>

**Comment by octavia-squidington-iii** [comment]
Marcos Marx commented: /test connector=connectors/destination-pubsub

> :clock2: connectors/destination-pubsub https://github.com/airbytehq/airbyte/actions/runs/2092366266
> :x: connectors/destination-pubsub https://github.com/airbytehq/airbyte/actions/runs/2092366266
> :bug: https://gradle.com/s/xrjtnmtxz2mr4
>

**Comment by octavia-squidington-iii** [comment]
Marcos Marx commented: /test connector=connectors/destination-kinesis
> :clock2: connectors/destination-kinesis https://github.com/airbytehq/airbyte/actions/runs/2092368692
> :white_check_mark: connectors/destination-kinesis https://github.com/airbytehq/airbyte/actions/runs/2092368692
No Python unittests run
>

**Comment by octavia-squidington-iii** [comment]
Marcos Marx commented: /test connector=connectors/destination-kafka
> :clock2: connectors/destination-kafka https://github.com/airbytehq/airbyte/actions/runs/2092367133
> :white_check_mark: connectors/destination-kafka https://github.com/airbytehq/airbyte/actions/runs/2092367133
No Python unittests run
>

**Comment by octavia-squidington-iii** [comment]
Marcos Marx commented: /test connector=connectors/destination-mqtt
> :clock2: connectors/destination-mqtt https://github.com/airbytehq/airbyte/actions/runs/2092372539
> :x: connectors/destination-mqtt https://github.com/airbytehq/airbyte/actions/runs/2092372539
> :bug: https://gradle.com/s/xdsaa53pg3ml2
>

**Comment by octavia-squidington-iii** [comment]
Marcos Marx commented: /test connector=connectors/destination-oracle


> :clock2: connectors/destination-oracle https://github.com/airbytehq/airbyte/actions/runs/2092379265
> :white_check_mark: connectors/destination-oracle https://github.com/airbytehq/airbyte/actions/runs/2092379265
Python tests coverage:
```
Name                                                                                                                            Stmts   Miss  Cover
---------------------------------------------------------------------------------------------------------------------------------------------------
normalization/transform_config/__init__.py                                                                                          2      0   100%
normalization/transform_catalog/reserved_keywords.py                                                                               13      0   100%
normalization/transform_catalog/__init__.py                                                                                         2      0   100%
normalization/destination_type.py                                                                                                  13      0   100%
normalization/__init__.py                                                                                                           4      0   100%
/actions-runner/_work/airbyte/airbyte/airbyte-integrations/bases/airbyte-protocol/airbyte_protocol/models/airbyte_protocol.py     124      0   100%
/actions-runner/_work/airbyte/airbyte/airbyte-integrations/bases/airbyte-protocol/airbyte_protocol/models/__init__.py               1      0   100%
/actions-runner/_work/airbyte/airbyte/airbyte-integrations/bases/airbyte-protocol/airbyte_protocol/__init__.py                      2      0   100%
normalization/transform_catalog/destination_name_transformer.py                                                                   155      8    95%
normalization/transform_config/transform.py                                                                                       168     31    82%
normalization/transform_catalog/table_name_registry.py                                                                            174     34    80%
normalization/transform_catalog/utils.py                                                                                           33      7    79%
normalization/transform_catalog/catalog_processor.py                                                                              143     77    46%
normalization/transform_catalog/transform.py                                                                                       45     26    42%
normalization/transform_catalog/stream_processor.py                                                                               524    337    36%
---------------------------------------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                                                            1403    520    63%
```
>

**Comment by grishick** [comment]
Auto-bump is currently broken (https://github.com/airbytehq/airbyte/issues/12276). Once that is fixed, this PR will be much easier to complete.

**Comment by grishick** [comment]
@evansmurithi thank you for the change. The updated docker images have been published and versions updated in OSS platform. I am merging the main change here: https://github.com/airbytehq/airbyte/pull/12376. Once the main change is merged, I'll close this PR.

**Pull request closed without merging**
