### PR TITLE
Source Trello: organizations: updated expected records

### PR DESCRIPTION
**Pull request by darynaishchenko**
## What
Stream Organizations: new field: `atlassianIntelligenceEnabled`
## How
Updated record

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-trello test report (commit [`59c1f9aff6`](https://github.com/airbytehq/airbyte/pull/28734/commits/59c1f9aff6020e5d894e60d0e12f38b8e409ccf6)) - ✅

⏲️  Total pipeline duration: 04mn49s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-trello/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-trello docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-trello_fix-expected-records/1690383755/59c1f9aff6020e5d894e60d0e12f38b8e409ccf6/source-trello/0.3.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-trello test
```

**Review by bazarnov — APPROVED** [review]

**Review by lazebnyi — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-trello test report (commit [`ea4b490292`](https://github.com/airbytehq/airbyte/pull/28734/commits/ea4b490292c3e66c55a254f7b2d8e405e74ef3c1)) - ❌

⏲️  Total pipeline duration: 03mn35s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-trello/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-trello docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-trello_fix-expected-records/1690797499/ea4b490292c3e66c55a254f7b2d8e405e74ef3c1/source-trello/0.3.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-trello test
```

**Comment by octavia-squidington-iii** [comment]
##  source-trello test report (commit [`52b6c3f5d8`](https://github.com/airbytehq/airbyte/pull/28734/commits/52b6c3f5d86204779ae9198bfb4b661dc7c251ea)) - ✅

⏲️  Total pipeline duration: 02mn47s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-trello/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-trello docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-trello_fix-expected-records/1690799963/52b6c3f5d86204779ae9198bfb4b661dc7c251ea/source-trello/0.3.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-trello test
```

**Comment by octavia-squidington-iii** [comment]
##  source-trello test report (commit [`52b6c3f5d8`](https://github.com/airbytehq/airbyte/pull/28734/commits/52b6c3f5d86204779ae9198bfb4b661dc7c251ea)) - ✅

⏲️  Total pipeline duration: 03mn44s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-trello/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-trello docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-trello_fix-expected-records/1690800287/52b6c3f5d86204779ae9198bfb4b661dc7c251ea/source-trello/0.3.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-trello test
```

**Pull request merged**
