### PR TITLE
Run CI Checks for #27412

### PR DESCRIPTION
**Pull request by marcosmarxm**
## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`09b8f8f6e3`](https://github.com/airbytehq/airbyte/pull/27412/commits/09b8f8f6e3bb0a469cc3384748953af72d8394ce)) - ❌

⏲️  Total pipeline duration: 3499 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check.                                                  | ✅        |
| Connector version increment check.                                               | ✅        |
| QA checks                                                                        | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5281588580)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`09b8f8f6e3`](https://github.com/airbytehq/airbyte/pull/27412/commits/09b8f8f6e3bb0a469cc3384748953af72d8394ce)) - ❌

⏲️  Total pipeline duration: 2696 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check.                                                  | ✅        |
| Connector version increment check.                                               | ✅        |
| QA checks                                                                        | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5281590476)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`ef1df37872`](https://github.com/airbytehq/airbyte/pull/27412/commits/ef1df3787238a26ef709673ff893fde5f6305a7a)) - ❌

⏲️  Total pipeline duration: 2865 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check.                                                  | ✅        |
| Connector version increment check.                                               | ✅        |
| QA checks                                                                        | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5290593191)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by danilo-nzyte** [comment]
This looks like it's failing because there's no `token` supplied, although the `token` is set with a secret value - has this been removed?

```

Run Automattic/action-required-review@v3
  with:
    status: A review is required from these teams: gl-python
    requirements-file: .github/connector_org_review_requirements.yaml
    fail: false
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.17/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.17/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.17/x64
    Python[2](https://github.com/airbytehq/airbyte/actions/runs/5290855679/jobs/9575594627?pr=27412#step:7:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/airbytehq/airbyte/actions/runs/5290855679/jobs/9575594627?pr=27412#step:7:3).9.17/x6[4](https://github.com/airbytehq/airbyte/actions/runs/5290855679/jobs/9575594627?pr=27412#step:7:4)
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.17/x[6](https://github.com/airbytehq/airbyte/actions/runs/5290855679/jobs/9575594627?pr=27412#step:7:6)4
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.1[7](https://github.com/airbytehq/airbyte/actions/runs/5290855679/jobs/9575594627?pr=27412#step:7:7)/x64/lib
Loaded 1 review requirement(s)
  Error: Input required and not supplied: token
  Error: Input required and not supplied: token
      at Object.getInput (/home/runner/work/_actions/Automattic/action-required-review/node_modules/.pnpm/@actions+core@1.[10](https://github.com/airbytehq/airbyte/actions/runs/5290855679/jobs/9575594627?pr=27412#step:7:10).0/node_modules/@actions/core/lib/core.js:106:1)
      at fetchReviewers (/home/runner/work/_actions/Automattic/action-required-review/v3/webpack:/required-review/src/reviewers.js:[11](https://github.com/airbytehq/airbyte/actions/runs/5290855679/jobs/9575594627?pr=27412#step:7:11):1)
      at main (/home/runner/work/_actions/Automattic/action-required-review/v3/webpack:/required-review/src/main.js:61:1)
```

**Comment by marcosmarxm** [comment]
> Hi @danilo-nzyte. This is my 1st contribution... I'm not sure if it was removed before. I didn't remove a token, or did anything related to token (as well as anything ops related).

Right now the Integration Tests are flaky not because of this change. The team is working to make the fix.

**Comment by danilo-nzyte** [comment]
> > Hi @danilo-nzyte. This is my 1st contribution... I'm not sure if it was removed before. I didn't remove a token, or did anything related to token (as well as anything ops related).
> 
> Right now the Integration Tests are flaky not because of this change. The team is working to make the fix.

Thanks for the update.

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`6c726d388d`](https://github.com/airbytehq/airbyte/pull/27412/commits/6c726d388d722637797e390056045b9546c37eaa)) - ❌

⏲️  Total pipeline duration: 3095 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check.                                                  | ✅        |
| Connector version increment check.                                               | ✅        |
| QA checks                                                                        | ❌        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5325973877)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`fb2f9f1110`](https://github.com/airbytehq/airbyte/pull/27412/commits/fb2f9f1110c8ecb38dd46073295cfe951cba9dc6)) - ❌

⏲️  Total pipeline duration: 3133 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check.                                                  | ✅        |
| Connector version increment check.                                               | ✅        |
| QA checks                                                                        | ❌        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5328078471)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Pull request closed without merging**
