### PR TITLE
🎉 Source Typeform: Full Stream Coverage

### LINKED ISSUE #12219: Full Stream Coverage
Need Webhooks, Workspaces, Images, Themes implemented.

Going through the [reference](https://developer.typeform.com/get-started/) API documentation it seems that the connector is missing the following streams:

- Webhooks -> [https://api.typeform.com/forms/{form_id}/webhooks](https://api.typeform.com/forms/%7Bform_id%7D/webhooks)
- Workspaces -> https://api.typeform.com/workspaces
- Images -> https://api.typeform.com/images
- Themes > https://api.typeform.com/themes

^^ Taken from https://github.com/airbytehq/airbyte/issues/10947#issuecomment-1089131964.

### PR DESCRIPTION
**Pull request by itaseskii**
## What
Increase Typeform connector stream coverage with Webhooks, Workspaces, Images, Themes

Closes #12219

## How
*Describe the solution*

## Recommended reading order
1. `source.py & ./schemas/`
2. `test_source.py & test_streams.py & conftest.py`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by lgomezm** [comment]
@itaseskii I see all the new streams you're adding have the same `primary_key` field (`"id"`). Maybe you can just add it to the parent `PaginatedStream` class?

```
class PaginatedStream(TypeformStream):

  primary_key = "id"
```

**Comment by lgomezm** [comment]
Could you update the integration tests to account for the new streams?

**Comment by lgomezm** [comment]
Hi @itaseskii. Your PR looks good! Just a couple minor questions. Please update the PR description to describe the solution or at least list the recommended review order.

**Comment by itaseskii** [comment]
> Could you update the integration tests to account for the new streams?

@lgomezm Done.

**Comment by itaseskii** [comment]
> @itaseskii I see all the new streams you're adding have the same `primary_key` field (`"id"`). Maybe you can just add it to the parent `PaginatedStream` class?
> 
> ```
> class PaginatedStream(TypeformStream):
> 
>   primary_key = "id"
> ```

@lgomezm I don't really agree with this. **_PaginatedStream_** has nothing to do with primary keys and its context should only contain data related to pagination. I could move the **_primary_key = "id"_** statement to the parent **_TypeformStream_** and only override it for the **_Responses_** stream but I don't think that is a good idea if it can't be guaranteed that the **__primary_key_** will be the same for every Typeform stream.

**Comment by itaseskii** [comment]
> Hi @itaseskii. Your PR looks good! Just a couple minor questions. Please update the PR description to describe the solution or at least list the recommended review order.

Thanks for the review. I have added a recommended reading order

**Review by lgomezm — APPROVED** [review]
LGTM. Thank you for this contribution.

**Comment by harshithmullapudi** [comment]
@itaseskii can you share screenshot for integration tests?

**Comment by harshithmullapudi** [comment]
@itaseskii can you fix the above tests

**Comment by itaseskii** [comment]
Hey @harshithmullapudi sorry for the late response. I will do it ASAP.

**Comment by harshithmullapudi** [comment]
Hey @itaseskii I am taking a look at this. Do you mind if I fix this and merge it?

**Comment by itaseskii** [comment]
@harshithmullapudi Yeah sure.

**Comment by harshithmullapudi** [comment]
closing this in favor of #13079

**Pull request closed without merging**
