### PR TITLE
🎉 New destination: Apache Hive

### PR DESCRIPTION
**Pull request by tovganesh**
## What
Add Apache Hive destination connector.

## How
Add a new destination for Apache Hive written using Python CDK. 
Currently supported loading methods are: SQL and S3.

## Recommended reading order
1. `spec.json`
2. `destination.py`
3. `writer.py`

## 🚨 User Impact 🚨
No breaking changes, only new destination adapter.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<strong>New Connector</strong>

### Community member or Airbyter

- [X] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [X] Secrets in the connector's spec are annotated with `airbyte_secret`
- [X] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [X] Code reviews completed
- [ ] Documentation updated
    - [X] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [X] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [X] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

Run:
<pre>
python -m pytest -vv unit_tests
</pre>

Output:
<pre>
==================================================================================== test session starts =====================================================================================
platform darwin -- Python 3.9.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/ganesh.venkateshwara/code/lab/airbyte/airbyte-integrations/connectors/destination-hive/.venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/ganesh.venkateshwara/code/lab/airbyte, configfile: pytest.ini
collected 3 items                                                                                                                                                                            

unit_test.py::test_sql_default PASSED
unit_test.py::test_sql_create[sql_writer] {"type": "LOG", "log": {"level": "INFO", "message": "\n        CREATE TABLE IF NOT EXISTS `airbyte_raw_dummy` (\n            `airbyte_ab_id` STRING,\n            `airbyte_emitted_at` STRING,\n            `airbyte_data` STRING,\n            PRIMARY KEY (`airbyte_ab_id`) disable novalidate\n        )\n        "}}
PASSED
unit_test.py::test_data_buffering PASSED

===================================================================================== 3 passed in 0.35s ======================================================================================
</pre>

</details>

<details><summary><strong>Integration</strong></summary>

Test Connection:
<pre>
docker run --rm -v $(pwd)/secrets:/secrets -v $(pwd)/integration_tests:/integration_tests airbyte/destination-hive:dev check --config /secrets/config.json
</pre>

Output:
<pre>
{"type": "LOG", "log": {"level": "INFO", "message": "Connecting to Hive"}}
[(1,)]
{"type": "LOG", "log": {"level": "INFO", "message": "Using S3 to stage data"}}
{"type": "CONNECTION_STATUS", "connectionStatus": {"status": "SUCCEEDED"}}
</pre>

Test destination writing to hive:

<pre>
cat integration_tests/messages.jsonl | docker run -a stdin -a stdout -a stderr --rm -v $(pwd)/secrets:/secrets -v $(pwd)/integration_tests:/integration_tests -i airbyte/destination-hive:dev write --config /secrets/config.json --catalog /integration_tests/configured_catalog.json 
</pre>

Output:
<pre>
{"type": "LOG", "log": {"level": "INFO", "message": "Begin writing to the destination..."}}
{"type": "LOG", "log": {"level": "INFO", "message": "Connecting to Hive"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Using S3 to stage data"}}
{"type": "LOG", "log": {"level": "INFO", "message": "DROP TABLE IF EXISTS `airbyte_raw_airbyte_acceptance_table`"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Stream airbyte_acceptance_table is wiped."}}
{"type": "LOG", "log": {"level": "INFO", "message": "\n        CREATE TABLE IF NOT EXISTS `airbyte_raw_airbyte_acceptance_table` (\n            `airbyte_ab_id` STRING,\n            `airbyte_emitted_at` STRING,\n            `airbyte_data` STRING,\n            PRIMARY KEY (`airbyte_ab_id`) disable novalidate\n        )\n        "}}
{"type": "LOG", "log": {"level": "INFO", "message": "ignoring input which can't be deserialized as Airbyte Message: \n"}}
{"type": "LOG", "log": {"level": "INFO", "message": "flushing"}}
{"type": "LOG", "log": {"level": "INFO", "message": "airbyte_acceptance_table"}}
{"type": "LOG", "log": {"level": "INFO", "message": "response = {'ResponseMetadata': {'RequestId': 'FMT4CVHYW31J0343', 'HostId': 'WXJHe38vk0emc93/bh4VJEH5Xvt3s3H51b4nUQtjYQR6XGTUppaMu9BVQORV3FGUETdYLBj9slI=', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-id-2': 'WXJHe38vk0emc93/bh4VJEH5Xvt3s3H51b4nUQtjYQR6XGTUppaMu9BVQORV3FGUETdYLBj9slI=', 'x-amz-request-id': 'FMT4CVHYW31J0343', 'date': 'Mon, 28 Nov 2022 06:51:40 GMT', 'etag': '\"31177e336ce0ca26ab97f65b93548f91\"', 'server': 'AmazonS3', 'content-length': '0'}, 'RetryAttempts': 0}, 'ETag': '\"31177e336ce0ca26ab97f65b93548f91\"'}"}}
{"type": "LOG", "log": {"level": "INFO", "message": "\n        CREATE TABLE IF NOT EXISTS `airbyte_raw_airbyte_acceptance_table` (\n            `airbyte_ab_id` STRING,\n            `airbyte_emitted_at` STRING,\n            `airbyte_data` STRING,\n            PRIMARY KEY (`airbyte_ab_id`) disable novalidate\n        )\n        "}}
{"type": "LOG", "log": {"level": "INFO", "message": "DROP TABLE IF EXISTS ex_airbyte_raw_airbyte_acceptance_table"}}
{"type": "LOG", "log": {"level": "INFO", "message": "\n        CREATE EXTERNAL TABLE IF NOT EXISTS ex_airbyte_raw_airbyte_acceptance_table (\n            `airbyte_ab_id` STRING,\n            `airbyte_emitted_at` STRING,\n            `airbyte_data` STRING\n        )\n        ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.JsonSerDe'\n        STORED AS INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'\n        OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'\n        LOCATION 's3a://cia-development-datalake/airbyte_output/1669618281_7bd6da18-7263-42c4-9e23-a359e9c522a6/airbyte_acceptance_table/'\n        TBLPROPERTIES ( 'classification'='json')\n        "}}
{"type": "LOG", "log": {"level": "INFO", "message": "\n            INSERT INTO TABLE `airbyte_raw_airbyte_acceptance_table`\n            SELECT airbyte_ab_id, airbyte_emitted_at, airbyte_data FROM ex_airbyte_raw_airbyte_acceptance_table\n        "}}
{"type": "LOG", "log": {"level": "INFO", "message": "DROP TABLE IF EXISTS ex_airbyte_raw_airbyte_acceptance_table"}}
{"type": "LOG", "log": {"level": "INFO", "message": "deleting s3 file cia-development-datalake/airbyte_output/1669618281_7bd6da18-7263-42c4-9e23-a359e9c522a6/airbyte_acceptance_table/file"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Writing complete."}}
</pre>

Run:
<pre>
python -m pytest integration_tests -vv
</pre>

Log redacted output:
<pre>
============================= test session starts ==============================
platform darwin -- Python 3.9.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/ganesh.venkateshwara/code/lab/airbyte/airbyte-integrations/connectors/destination-hive/.venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/ganesh.venkateshwara/code/lab/airbyte, configfile: pytest.ini
collected 3 items

integration_tests/integration_test.py::test_check_valid_config PASSED
integration_tests/integration_test.py::test_check_invalid_config PASSED
integration_tests/integration_test.py::test_write PASSED

======================== 3 passed in 247.64s (0:04:07) =========================
</pre>

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@tovganesh can you check your commits looks you submitted the PR with another user and our CLA is doesn't recognize it.

**Comment by marcosmarxm** [comment]
Sorry the delay to review the contribution @tovganesh someone from the team will take a look next week.

**Comment by TapasSenapati** [comment]
> [CLA assistant check](https://cla-assistant.io/airbytehq/airbyte?pullRequest=19893)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=19893) before we can accept your contribution.
> **1** out of **2** committers have signed the CLA.
> 
> ✅ TapasSenapati
> ❌ tovganesh
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=19893) it.

### 

@marcosmarxm 
The CLA was signed by me by mistake. Would you be able to revoke it.  Our legal team is going to sign this CLA>

**Comment by grishick** [comment]
@tovganesh could you sign the CLA please?

**Comment by marcosmarxm** [comment]
@tovganesh I'm closing the PR. Please submit again with the correct user and CLA signed! Thanks

**Comment by grishick** [comment]
> @tovganesh I'm closing the PR. Please submit again with the correct user and CLA signed! Thanks

we have the CLA signed by Cloudera's legal counsel

**Comment by grishick** [comment]
Looks like integration tests for this PR need a Hive cluster, which we do not have ATM.

**Comment by marcosmarxm** [comment]
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

**Comment by grishick** [comment]
@tovganesh do you know if/how Hive can be spun up in a container for integration tests?

**Comment by tovganesh** [comment]
@grishick you could use this https://hub.docker.com/r/bde2020/hive

**Comment by marcosmarxm** [comment]
CLA was not signed @tovganesh please submit the contribution again but using all the same contributor that signed the CLA.

**Pull request closed without merging**
