### PR TITLE
Change StreamKey to StreamDescriptor

### PR DESCRIPTION
**Pull request by alovew**
Change the name of the StreamKey model to StreamDescriptor.

### CODE REVIEW

**Comment by alovew** [comment]
Specs have been updated, so StreamKey is now StreamDescriptor

**Review by benmoriceau — APPROVED** [review]
LGTM, let's merge it after the presentation in case there is one mor modification

**Comment by alovew** [comment]
@benmoriceau I also just opened another PR that includes this change and the new temporal activities, so if that one looks ok it would be better to merge that one maybe - but either way is fine with me: https://github.com/airbytehq/airbyte/pull/13614

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Pull request merged**
