### PR TITLE
feat(docs): oauth refresh token updater

### PR DESCRIPTION
**Pull request by Jeroendevr**
## What
Two things
- Include a link to the YAML reference for every Authentication object
- Include some information about the `refresh_token_updater` abstracted from [declarative_component_schema](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/declarative/declarative_component_schema.yaml#L1067-L1087)

## How
n.a.

## Review guide
n.a.

## User Impact
Easier navigation to the reference

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

# Note (to self)
Seeing the [declarative_component_schema](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/declarative/declarative_component_schema.yaml#L1067-L1087) I think the YAML reference for `OAuthAuthenticator` can be improved even further as declarative_component_schema is quite extensive.

### CODE REVIEW

**Review by marcosmarxm — COMMENTED** [review]
Thanks @Jeroendevr, @girarda + @Adorism can you take a look into this doc changes?

**Review by girarda — APPROVED** [review]
this is great! thanks for your contribution @Jeroendevr

**Comment by Jeroendevr** [comment]
@girarda There are some checks waiting _[Run connectors full CI on fork](https://github.com/airbytehq/airbyte/actions/runs/9913576797/job/27390886050?pr=41555#logs),_ can I do something to have this PR merged? As updating the branch does not seems sufficient.

**Comment by marcosmarxm** [comment]
Hello your feedback matters a lot to us. Can you spare just 1 minutes to complete a [survey](https://form.typeform.com/to/DOBqejte)? We’re dedicated to making the contributor experience even better, and your input is key to achieving excellence. Thank you for helping us improve!

**Pull request merged**
