### PR TITLE
Center MongoDb connector icon

### PR DESCRIPTION
**Pull request by nora-airbyte**
MongoDB icon wasn't off-centered. Pushing a fix

## Can this PR be safely reverted and rolled back?

- [ X] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by evantahler — APPROVED** [review]

**Comment by evantahler** [comment]
This change by itself won't update the connector metadata, you would also need to bump the version in metadata.yaml with a new connector version and then add a changelog entry to the connector's markdown doc.  Or, you could skip all of that and wait until we make a change to the connector for some other reason - your call!

**Comment by lmossman** [comment]
@nora-airbyte looks like CI wants you to bump the version as Evan called out

**Comment by nora-airbyte** [comment]
Changes made (I think)!

**Review by evantahler — APPROVED** [review]

**Comment by lmossman** [comment]
@nora-airbyte looks like mongodb was updated already, so you'll need to re-bump the version.

**Comment by theyueli** [comment]
> @nora-airbyte looks like mongodb was updated already, so you'll need to re-bump the version.

I just bumped it up to 1.5.1

**Pull request merged**
