### PR TITLE
✨Source Harness: Migrate TS CDK to Low-code CDK

### LINKED ISSUE #30904: :sparkles: Source Harness : Migrate Python CDK to Low-code CDK
https://docs.airbyte.com/integrations/sources/harness

Rules for the Connectors Hackathon
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
*Migrating Source Harness to Low-Code CDK which is maintained by [Faros-ai](https://github.com/faros-ai/airbyte-connectors/blob/main/sources/harness-source)*
Closes #30904

## How
*Developed using (Configuration Based Source) low-code CDK*

## Recommended reading order
1. `spec.yaml`
2. `manifest.yaml`
3. `schemas/*`

## Tests

<details><summary><strong>Integration & Acceptance</strong></summary>
Full Test Results

</details>

## 🚨 User Impact 🚨
- No breaking changes, migration to low-code
<details><summary><strong>Migrate Connector: Source Harness</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [x] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

</details>

### CODE REVIEW

**Comment by btkcodedev** [comment]
Test results:
image

**Comment by btkcodedev** [comment]
The old stream executions in faros-ai were using GraphQL-like queries to retrieve data which is not acceptable as it is dynamic,
This migrated connector uses the REST API way of fetching the streams :)

**Comment by marcosmarxm** [comment]
Sorry the long delay to get into your contribution. Probably this week or next one the team will start the process. Are you able to run the tests in your local setup? It can speed up a lot the process if you share the integration tests results

**Comment by btkcodedev** [comment]
Test results tagged above: https://github.com/airbytehq/airbyte/pull/31103#issuecomment-1749095421

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
