### PR TITLE
docs: Add field anchors for top source docs

### PR DESCRIPTION
**Pull request by nataliekwong**
## What
Adds Field Anchors for key source docs
- Google Sheets
- Postgres
- Shopify
- File
- Facebook Marketing
- Google Ads

Replaces https://github.com/airbytehq/airbyte/pull/44092 due to merge conflicts I couldn't figure out how to resolve. Copied updates over here and made sure more recent updates to the pages were reflected.

### CODE REVIEW

**Comment by octavia-approvington** [comment]
Our work here is done <br/> done

**Review by octavia-approvington — APPROVED** [review]

**Review by lazebnyi — APPROVED** [review]

**Pull request merged**
