### PR TITLE
[file-based cdk] Remove CSV quoting_behavior config option

### LINKED ISSUE #28330: [file-based cdk] Remove CSV quoting_behavior config option
## What

We had initially added `quoting_behavior` to support the `newlines_in_values` field from the legacy S3 destination that uses pyarrow. After some testing of various CSV inputs with newlines, we should be able to support newlines as long as we pass csv.QUOTE_MINIMAL to the parser which is also the default.

## Acceptance Criteria

- [ ] The `quoting_behavior` config is removed from the CsvFormat
- [ ] When creating the new dialect in`csv_parser.py`, the `csv.QUOTE_MINIMAL` is explicitly passed. We want to explicitly use this to make it obvious which behavior we use in case the default behavior changes
- [ ] The resulting `spec` message does not have `quoting_behavior` and test configs have it removed

### PR DESCRIPTION
**Pull request by brianjlai**
Closes #28330

## What

We did some testing and this option doesn't appear to make a difference in the legacy S3 connector. We can use the default value QUOTE_MINIMAL for the CSV dialect to get the quoting behavior needed for the legacy connector (with newlines).

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`75f4c850b3`](https://github.com/airbytehq/airbyte/pull/29388/commits/75f4c850b33c570693d8857f25257ddc240a93ad)) - ✅

⏲️  Total pipeline duration: 10mn59s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/brian_remove_quoting_behavior/1691893733/75f4c850b33c570693d8857f25257ddc240a93ad/source-s3/3.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:75f4c850b33c570693d8857f25257ddc240a93ad)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Review by clnoll — APPROVED** [review]
LGTM!

**Review by girarda — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`0adec5fdba`](https://github.com/airbytehq/airbyte/pull/29388/commits/0adec5fdbac73ccd9212c63d6564730a2632a42e)) - ✅

⏲️  Total pipeline duration: 13mn19s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/brian_remove_quoting_behavior/1692046443/0adec5fdbac73ccd9212c63d6564730a2632a42e/source-s3/3.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:0adec5fdbac73ccd9212c63d6564730a2632a42e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`facb8cda0b`](https://github.com/airbytehq/airbyte/pull/29388/commits/facb8cda0bfd45ef3b4dc789757dfd25589cef23)) - ✅

⏲️  Total pipeline duration: 04mn34s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/brian_remove_quoting_behavior/1692051730/facb8cda0bfd45ef3b4dc789757dfd25589cef23/source-s3/3.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:facb8cda0bfd45ef3b4dc789757dfd25589cef23)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Pull request merged**
