### PR TITLE
🐛 [cdk] Return correct type during 'check' if config does not match schema

### PR DESCRIPTION
**Pull request by yfyf**
## What

This fixes a bug where, upon config validation against the JSON schema failure, the `run_cmd` function would `yield` the connection status message in the form of a serialized JSON (i.e. `str`). This violated the output signature of `Iterable[AirbyteMessage`] and would produce unclear errors when run from the CLI.

Curiously, `mypy` did not catch this simple type error, though pyright did.

## How

Yield the correct type upon exception.

## Review guide

It's a one-line change, except for the test.

Added a small unit test that covers this scenario.

## User Impact

When running `check --config bad-config.json`, it would throw up with:

    {"type": "LOG", "log": {"level": "FATAL", "message": "'str' object has no attribute 'json'\nTraceback <..>}}
    {"type": "TRACE", "trace": {"type": "ERROR", <..>}}

Now it produces a clear message:

     {"type": "CONNECTION_STATUS", "connectionStatus": {"status": "FAILED", "message": "Config validation error: 'foo' is a required property"}}

## Can this PR be safely reverted and rolled back?

- [X] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by marcosmarxm — COMMENTED** [review]
Thanks @yfyf adding this to the connector team backlog to review in next sprint.
@natikgadzhi fyi.

**Comment by natikgadzhi** [comment]
Uh oh, we missed it. @yfyf thank you for the fix! Let me spin up CI on this and merge if everything looks fine.

**Comment by natikgadzhi** [comment]
@alafanechere will add CDK to allowed paths to trigger community CI and then merge this :D

**Review by natikgadzhi — APPROVED** [review]
Generally LGTM, let's wait for a green CI and merge?

**Review by alafanechere — CHANGES_REQUESTED** [review]
Hey @yfyf , we run mypy on modified files in CI. Would you mind fixing the following error on the `destination.py` module?

```
airbyte-cdk/python/airbyte_cdk/destinations/destination.py:115: error: Function is missing a return type annotation  [no-untyped-def]
```

**Comment by yfyf** [comment]
@alafanechere I'm sorry, but I can't dedicate more time to this at the
moment. It is also a code maintenance change that isn't related to the bug
fix.

**Comment by natikgadzhi** [comment]
Since this is not a net new mypy error and it's unrelated to the actual change, I'll merge this as is. Thank you for the contribution, @yfyf!

**Pull request merged**
