### PR TITLE
Support Qovery as a deployment option

### PR DESCRIPTION
**Pull request by arnaudjnn**
Hi, the Airbyte team,

I added docs on deploying Airbyte to Qovery - feedback is welcome.

Arnaud.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368218604721) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by michel-tricot** [comment]
Thank you @arnaudjnn! I will test the tutorial. Do you have a sandbox account by any chance?

**Comment by arnaudjnn** [comment]
Hi @michel-tricot,

We can have a Discord chat/call for more details about this PR.

arnaudjnn#4969

**Comment by michel-tricot** [comment]
Hey @arnaudjnn I just sent you an invite for next week on LinkedIn

**Comment by michel-tricot** [comment]
Had a call with @arnaudjnn. we should be able to support Qovery after our push to support k8s fully

**Comment by cgardens** [comment]
@michel-tricot could you fill in more context in this PR so that it is clear how K8s affects this?

**Pull request closed without merging**
