### PR TITLE
🎉 New Source: Pocket [low-code CDK]

### PR DESCRIPTION
**Pull request by xlahuerta**
## What

New Source: Pocket. [https://getpocket.com](https://getpocket.com)

Screenshot from 2022-10-30 03-11-32

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [X] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [X] Secrets in the connector's spec are annotated with `airbyte_secret`
- [X] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [X] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [X] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [X] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [X] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

Screenshot from 2022-10-30 03-12-05

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

Screenshot from 2022-10-30 02-44-59

</details>

### CODE REVIEW

**Comment by Xabilahu** [comment]
`secrets/config.json` being used for integ tests is:

```json
{
  "consumer_key": "REPLACE-ME",
  "access_token": "REPLACE-ME"
}
```

Instructions on how to get them in `docs/integrations/sources/pocket.md`

**Comment by Xabilahu** [comment]
> /test connector=connectors/source-pocket
> 
> > 🕑 connectors/source-pocket https://github.com/airbytehq/airbyte/actions/runs/3356258058
> > ❌ connectors/source-pocket https://github.com/airbytehq/airbyte/actions/runs/3356258058
> > 🐛 https://gradle.com/s/ktlpbfva6k5io
> 
> ### Build Failed
> 
> Test summary info:
> 
> ```
> =========================== short test summary info ============================
> ERROR test_core.py::TestSpec::test_config_match_spec[inputs0] - FileNotFoundE...
> ERROR test_core.py::TestConnection::test_check[inputs0] - FileNotFoundError: ...
> ERROR test_core.py::TestDiscovery::test_discover[inputs0] - FileNotFoundError...
> ERROR test_core.py::TestDiscovery::test_defined_cursors_exist_in_schema[inputs0]
> ERROR test_core.py::TestDiscovery::test_defined_refs_exist_in_schema[inputs0]
> ERROR test_core.py::TestDiscovery::test_defined_keyword_exist_in_schema[inputs0-allOf]
> ERROR test_core.py::TestDiscovery::test_defined_keyword_exist_in_schema[inputs0-not]
> ERROR test_core.py::TestDiscovery::test_primary_keys_exist_in_schema[inputs0]
> ERROR test_core.py::TestDiscovery::test_streams_has_sync_modes[inputs0] - Fil...
> ERROR test_core.py::TestDiscovery::test_additional_properties_is_true[inputs0]
> ERROR test_core.py::TestBasicRead::test_read[inputs0] - FileNotFoundError: [E...
> ERROR test_core.py::TestBasicRead::test_airbyte_trace_message_on_failure[inputs0]
> ERROR test_full_refresh.py::TestFullRefresh::test_sequential_reads[inputs0]
> SKIPPED [1] ../usr/local/lib/python3.9/site-packages/source_acceptance_test/plugin.py:63: Skipping TestIncremental.test_two_sequential_reads: This connector does not implement incremental sync
> SKIPPED [1] ../usr/local/lib/python3.9/site-packages/source_acceptance_test/tests/test_core.py:51: The previous connector image could not be retrieved.
> SKIPPED [1] ../usr/local/lib/python3.9/site-packages/source_acceptance_test/tests/test_core.py:229: The previous connector image could not be retrieved.
> ================== 11 passed, 3 skipped, 13 errors in 11.10s ===================
> ```

It seems like it's missing the `secrets/config.json`. @koconder, did you create it in Github Secrets?

**Comment by koconder** [comment]
@Xabilahu this is normal as there is no test config file for this connection yet on airbyte side. Please hang tight as i review.

**Review by marcosmarxm — DISMISSED** [review]
Hello @Xabilahu, Marcos from Airbyte here 👋 . We received more than 25 new contributions along the weekend. One is yours 🎉  thank so much for! Our team is limited and maybe the review process can take longer than expected. As described in the Airbyte's Hacktoberfest your contribution was submitted before November 2nd and it is eligible to win the prize. The review process will validate other requirements. I ask to you patience until someone from the team review it. 

Because I reviewed some contributions for Hacktoberfest so far I saw some common patterns you can check in advance:
* [ ] Make sure you have added connector documentation to `/docs/integrations/`
* [ ] Remove the file `catalog` from `/integration_tests`
* [ ] Edit the `sample_config.json` inside `/integration_tests`
* [ ] For the `configured_catalog` you can use only `json_schema: {}`
* [ ] Add title to all properties in the `spec.yaml`
* [ ] Make sure the `documentationUrl` in the `spec.yaml` redirect to Airbyte's future connector page, eg: connector Airtable the `documentationUrl: https://docs.airbyte.com/integrations/sources/airtable`
* [ ] Review now new line at EOF (end-of-file) for all files.

If possible send to me a DM in Slack with the tests credentials, this process will make easier to us run integration tests and publish your connector. If you only has production keys, make sure to create a bootstrap.md explaining how to get the keys.

**Review by vincentkoc — COMMENTED** [review]
@Xabilahu looks good, i made a few small changes. I have my API keys and will test locally shortly.

**Review by vincentkoc — DISMISSED** [review]

**Comment by koconder** [comment]
@Xabilahu @marcosmarxm all local tests passing, will get this finalised soon

**Comment by koconder** [comment]
FYI @Xabilahu 

Unit Test

```
> Task :airbyte-integrations:connectors:source-pocket:unitTest
Name                         Stmts   Miss  Cover
------------------------------------------------
source_pocket/extractor.py      19      0   100%
source_pocket/__init__.py        3      0   100%
source_pocket/source.py          4      1    75%
------------------------------------------------
TOTAL                           26      1    96%
```

Acceptance Test:
```
=========================== short test summary info ============================
FAILED test_core.py::TestDiscovery::test_primary_keys_exist_in_schema[inputs0]
FAILED test_core.py::TestBasicRead::test_read[inputs0] - Failed: Timeout >300.0s
FAILED test_full_refresh.py::TestFullRefresh::test_sequential_reads[inputs0]
SKIPPED [1] ../usr/local/lib/python3.9/site-packages/source_acceptance_test/plugin.py:63: Skipping TestIncremental.test_two_sequential_reads: This connector does not implement incremental sync
SKIPPED [1] ../usr/local/lib/python3.9/site-packages/source_acceptance_test/tests/test_core.py:51: The previous connector image could not be retrieved.
SKIPPED [1] ../usr/local/lib/python3.9/site-packages/source_acceptance_test/tests/test_core.py:229: The previous connector image could not be retrieved.
============= 3 failed, 21 passed, 3 skipped in 431.34s (0:07:11) ==============
```

**Comment by Xabilahu** [comment]
> FYI @Xabilahu
> 
> Unit Test
> 
> ```
> > Task :airbyte-integrations:connectors:source-pocket:unitTest
> Name                         Stmts   Miss  Cover
> ------------------------------------------------
> source_pocket/extractor.py      19      0   100%
> source_pocket/__init__.py        3      0   100%
> source_pocket/source.py          4      1    75%
> ------------------------------------------------
> TOTAL                           26      1    96%
> ```
> 
> Acceptance Test:
> 
> ```
> =========================== short test summary info ============================
> FAILED test_core.py::TestDiscovery::test_primary_keys_exist_in_schema[inputs0]
> FAILED test_core.py::TestBasicRead::test_read[inputs0] - Failed: Timeout >300.0s
> FAILED test_full_refresh.py::TestFullRefresh::test_sequential_reads[inputs0]
> SKIPPED [1] ../usr/local/lib/python3.9/site-packages/source_acceptance_test/plugin.py:63: Skipping TestIncremental.test_two_sequential_reads: This connector does not implement incremental sync
> SKIPPED [1] ../usr/local/lib/python3.9/site-packages/source_acceptance_test/tests/test_core.py:51: The previous connector image could not be retrieved.
> SKIPPED [1] ../usr/local/lib/python3.9/site-packages/source_acceptance_test/tests/test_core.py:229: The previous connector image could not be retrieved.
> ============= 3 failed, 21 passed, 3 skipped in 431.34s (0:07:11) ==============
> ```

Taking a look 👀

**Comment by koconder** [comment]
@Xabilahu if you want to get the same results, you can run gradle from the root of airbyte using:
```sh
./gradlew :airbyte-integrations:connectors:source-pocket:sourceAcceptanceTest
```

**Comment by Xabilahu** [comment]
I'm not able to replicate these two failed test cases:

```sh
FAILED test_core.py::TestBasicRead::test_read[inputs0] - Failed: Timeout >300.0s
FAILED test_full_refresh.py::TestFullRefresh::test_sequential_reads[inputs0]
```

But for this one `FAILED test_core.py::TestDiscovery::test_primary_keys_exist_in_schema[inputs0]`, if I run ` python -m pytest integration_tests -p integration_tests.acceptance --pdb --last-failed` and print the schema, I get `{}` O.O

Looking at `source_pocket/schemas/retrieve.json`, we can double check that the primary key is in fact defined (`item_id`). Any hint about what could be happening?

**Comment by Xabilahu** [comment]
Looking at the code from `.venv/lib/python3.9/site-packages/airbyte_cdk/sources/declarative_stream.py`, I found out that if no `schema_loader` is declared in the definition YAML file, the it defaults to `EmptySchemaLoader`. Code below:

```python
@dataclass
class DeclarativeStream(Stream, JsonSchemaMixin):

...

    def __post_init__(self, options: Mapping[str, Any]):
        self.stream_cursor_field = self.stream_cursor_field or []
        self.transformations = self.transformations or []
        self._schema_loader = self.schema_loader if self.schema_loader else EmptySchemaLoader(config=self.config, options=options)
```
I tested to create an environment from scracth with the following commands,:

```sh
python -m venv .venv
source .venv/bin/activate
pip install airbyte-cdk~=0.2 --no-cache
```

And, in fact, the code is the same as above. This seems like a breaking change in `airbyte-cdk==0.5.2`

**Comment by koconder** [comment]
@Xabilahu let me know if you need any assistance and able to work-around this or this is a bug elsewhere.

**Comment by Xabilahu** [comment]
> @Xabilahu let me know if you need any assistance and able to work-around this or this is a bug elsewhere.

@koconder I added `schema_loader` property as a workaround to unblock this PR.

**Comment by koconder** [comment]
@Xabilahu still an issue, see below. Are you able to run gradle command i gave you?

```
=========================== short test summary info ============================
FAILED test_core.py::TestBasicRead::test_read[inputs0] - Failed: Timeout >300.0s
FAILED test_full_refresh.py::TestFullRefresh::test_sequential_reads[inputs0]
SKIPPED [1] ../usr/local/lib/python3.9/site-packages/source_acceptance_test/plugin.py:63: Skipping TestIncremental.test_two_sequential_reads: This connector does not implement incremental sync
SKIPPED [1] ../usr/local/lib/python3.9/site-packages/source_acceptance_test/tests/test_core.py:51: The previous connector image could not be retrieved.
SKIPPED [1] ../usr/local/lib/python3.9/site-packages/source_acceptance_test/tests/test_core.py:229: The previous connector image could not be retrieved.
============= 2 failed, 22 passed, 3 skipped in 418.23s (0:06:58) ==============
```

One of the issues, not sure where/what/why
```
JSONDecodeError: Extra data: line 1 column 5 (char 4)
```

**Comment by Xabilahu** [comment]
@kokonder, as I told you in a previous comment, I'm not able to replicate those failures that you show. For me, the build passes successfully:

```
> ./gradlew :airbyte-integrations:connectors:source-pocket:sourceAcceptanceTest

=========================== short test summary info ============================
SKIPPED [1] ../usr/local/lib/python3.9/site-packages/source_acceptance_test/plugin.py:63: Skipping TestIncremental.test_two_sequential_reads: This connector does not implement incremental sync
SKIPPED [1] ../usr/local/lib/python3.9/site-packages/source_acceptance_test/tests/test_core.py:51: The previous connector image could not be retrieved.
SKIPPED [1] ../usr/local/lib/python3.9/site-packages/source_acceptance_test/tests/test_core.py:229: The previous connector image could not be retrieved.
======================== 24 passed, 3 skipped in 59.39s ========================
```

**Comment by koconder** [comment]
@Xabilahu can you contact me on Airbyte slack, I'll share my test credentials there with you.

**Comment by Xabilahu** [comment]
The issue is that the config used for acceptance tests tries to sync a huge amount of data, which doesn't fit into the 300s limit for tests.

**Comment by koconder** [comment]
As mentioned, i will see if we can adjust the tests before I finalize this PR to save the issue from re-occurring with others that will test again in future.

**Comment by Xabilahu** [comment]
@koconder any updates? Do you need help?

**Comment by koconder** [comment]
@Xabilahu we will add the config to the Github Actions and attempt to finalise the acceptance tests. Once done we can merge and publish the connector :)

**Review by vincentkoc — APPROVED** [review]

**Pull request merged**
