### PR TITLE
Source Pinterest: changed AD_ACCOUNT_ID type to integer, updated acceptance-test-config…

### PR DESCRIPTION
**Pull request by darynaishchenko**
changed AD_ACCOUNT_ID type to integer, updated acceptance-test-config

### CODE REVIEW

**Comment by girarda** [comment]
do you have context for this change? Looking at a few response samples from https://developers.pinterest.com/docs/api/v5/#operation/campaigns, it looks like ad_account_id should be a string

```
{
"items": [
{
"data": {
"ad_account_id": "549755885175",
"name": "ACME Tools",
"status": "ACTIVE",
<...>
```

**Comment by darynaishchenko** [comment]
fixed in https://github.com/airbytehq/airbyte/pull/20242

**Pull request closed without merging**
