### PR TITLE
source-okta: add custom roles stream

### PR DESCRIPTION
**Pull request by YiyangLi**
## What
- add custom roles, which supports full refresh only

## How
In okta, each org is allowed to create at most 100 custom roles. The custom roles API returns at most 100 roles. Though the doc says the response is paginated, but the pagination strategy is not specified. Created 100 roles in my test org, and all roles are returned in one request. 

Also, unlike users, groups and logs, the payload of roles is enveloped. The response is an object with a key of `roles`, and the value is an array of custom role. 

## Recommended reading order
1. `source.py`

## 🚨 User Impact 🚨
no impact, it's a new API stream

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

```
** airbyte-integrations/connectors/source-okta/unit_tests/unit_test.py::TestPagination.test_pagination[None-XYZ-expected_npt0-Expected to receive a new page token if next header is set and self is not set] ✓                                                   25% ██▌       
 airbyte-integrations/connectors/source-okta/unit_tests/unit_test.py::TestPagination.test_pagination[ABC-XYZ-expected_npt1-Expected to receive a new page token if next and self headers have different values] ✓                                               50% █████     
 airbyte-integrations/connectors/source-okta/unit_tests/unit_test.py::TestPagination.test_pagination[ABC-ABC-None-Expected no new page token if next and self headers are the same] ✓                                                                           75% ███████▌  
 airbyte-integrations/connectors/source-okta/unit_tests/unit_test.py::TestPagination.test_pagination[ABC-None-None-Expected no new page token if next header is not set] ✓                                                                                     100% ██████████
============================================================================================================================== warnings summary ==============================================================================================================================
airbyte-integrations/connectors/source-okta/unit_tests/unit_test.py::TestPagination::test_pagination[None-XYZ-expected_npt0-Expected to receive a new page token if next header is set and self is not set]
airbyte-integrations/connectors/source-okta/unit_tests/unit_test.py::TestPagination::test_pagination[ABC-XYZ-expected_npt1-Expected to receive a new page token if next and self headers have different values]
airbyte-integrations/connectors/source-okta/unit_tests/unit_test.py::TestPagination::test_pagination[ABC-ABC-None-Expected no new page token if next and self headers are the same]
airbyte-integrations/connectors/source-okta/unit_tests/unit_test.py::TestPagination::test_pagination[ABC-None-None-Expected no new page token if next header is not set]
  /Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-okta/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py:41: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    self._authenticator: HttpAuthenticator = NoAuth()

airbyte-integrations/connectors/source-okta/unit_tests/unit_test.py::TestPagination::test_pagination[None-XYZ-expected_npt0-Expected to receive a new page token if next header is set and self is not set]
airbyte-integrations/connectors/source-okta/unit_tests/unit_test.py::TestPagination::test_pagination[ABC-XYZ-expected_npt1-Expected to receive a new page token if next and self headers have different values]
airbyte-integrations/connectors/source-okta/unit_tests/unit_test.py::TestPagination::test_pagination[ABC-ABC-None-Expected no new page token if next and self headers are the same]
airbyte-integrations/connectors/source-okta/unit_tests/unit_test.py::TestPagination::test_pagination[ABC-None-None-Expected no new page token if next header is not set]
  /Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-okta/.venv/lib/python3.9/site-packages/deprecated/classic.py:173: DeprecationWarning: Call to deprecated class HttpAuthenticator. (Use requests.auth.AuthBase instead) -- Deprecated since version 0.1.20.
    return old_new1(cls, *args, **kwargs)

-- Docs: https://docs.pytest.org/en/stable/warnings.html

Results (0.21s):
       4 passed
```

</details>

<details><summary><strong>Integration</strong></summary>

```
Test session starts (platform: darwin, Python 3.9.13, pytest 6.2.5, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /Users/bartdev/Playground/airbyte, configfile: pytest.ini
plugins: sugar-0.9.4, timeout-1.4.2
collecting ... 

Results (0.01s):
```

</details>

<details><summary><strong>Acceptance</strong></summary>

```
============================================================================================================================== warnings summary ==============================================================================================================================
airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py: 17 warnings
airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_full_refresh.py: 1 warning
airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py: 3 warnings
  /Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-okta/.venv/lib/python3.9/site-packages/docker/utils/utils.py:52: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    s1 = StrictVersion(v1)

airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py: 17 warnings
airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_full_refresh.py: 1 warning
airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py: 3 warnings
  /Users/bartdev/Playground/airbyte/airbyte-integrations/connectors/source-okta/.venv/lib/python3.9/site-packages/docker/utils/utils.py:53: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    s2 = StrictVersion(v2)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================================================================== short test summary info ===========================================================================================================================
FAILED ../../bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestBasicRead::test_read[inputs0] - Failed: Please check your json_schema in selected streams ('logs',).
FAILED ../../bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py::TestIncremental::test_state_with_abnormally_large_values[inputs0] - AssertionError: The sync should produce no records when run with the state with abnormally large values

Results (85.81s):
      22 passed
       2 failed
         - airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py:381 TestBasicRead.test_read[inputs0]
         - airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py:207 TestIncremental.test_state_with_abnormally_large_values[inputs0]
```

</details>

### CODE REVIEW

**Comment by alafanechere** [comment]
Thank for your contribution @YiyangLi , I formatted the code and will now run the acceptance tests.

**Comment by YiyangLi** [comment]
@alafanechere can you try to run the test again? 

If you don't have a custom role in your test okta org, the acceptance test will throw an error on the basic test that expects at least one record on Custom Role, the new stream I create in this PR. 

The following are the steps to create one. 

1. Go to Admin after login
2. choose Navigation drawer on the left --> Security --> Administrators --> Roles tab
3. Create a new Role
Screen Shot 2022-07-12 at 7 52 21 PM
Screen Shot 2022-07-12 at 7 52 43 PM

it's safe to create a role, as long as it's not assigned to a user or a group, there is no effect.

**Comment by alafanechere** [comment]
> The following are the steps to create one.
Thank you! I created a custom role on our test account, running the test again now.

**Review by alafanechere — APPROVED** [review]

**Pull request merged**
