### PR TITLE
Source Klaviyo: update schema validation in SAT

### LINKED ISSUE #6815: fix klaviyo source connectro build
## Current Behavior
build is failing on schema validation

## Expected Behavior
Build should succeed

### PR DESCRIPTION
**Pull request by gaart**
## What
Fix #6815

## How

There's a test which checks response schemas. Some fields can be optional (null value). Usually we mark them like `["null", "string"]`. In this connector we use pydantic which generates invalid type, e.g. for `name: Optional[str]` we expect to have 
```
{
"title": "Name",
"type": ["null", "string"]
}
```
but get
```
{
"title": "Name" ,
"type": "string"
}
```
We can skip the schema validation test since pydantic does the same during response processing and the test will fail anyway if schema is wrong.

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated 
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [x] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [x] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

### CODE REVIEW

**Review by keu — APPROVED** [review]

**Comment by keu** [comment]
> @keu @davinchia There's a test which checks response schemas. Some fields can be optional (null value). Usually we mark them like `["null", "string"]`. In this connector we use pydantic which generates invalid type, e.g. for `name: Optional[str]` we expect to have
> 
> ```
> {
> "title": "Name",
> "type": ["null", "string"]
> }
> ```
> 
> but get
> 
> ```
> {
> "title": "Name" ,
> "type": "string"
> }
> ```
> 
> We can skip the schema validation test since pydantic does the same during response processing and the test will fail anyway if schema is wrong

@gaart I see.
In some places where we use pydantic we have the following code in the base model class:
```python
        @classmethod
        def schema_extra(cls, schema: Dict[str, Any], model: Type["BaseModel"]) -> None:
            schema.pop("title", None)
            schema.pop("description", None)
            for name, prop in schema.get("properties", {}).items():
                prop.pop("title", None)
                prop.pop("description", None)
                allow_none = model.__fields__[name].allow_none
                if allow_none:
                    if "type" in prop:
                        prop["type"] = ["null", prop["type"]]
                    elif "$ref" in prop:
                        ref = prop.pop("$ref")
                        prop["oneOf"] = [{"type": "null"}, {"$ref": ref}]
```
this will produce the expected schema.
Although I think that pydantic validation is good, I see few downsides:
- performance
- validation of pydantic model and json_schema could be different as we see here.

@sherifnada what do you think, should we keep pydantic validation during the read in the connector code?

**Comment by davinchia** [comment]
This feels like we should fix the base model and not disable the validation or it will get confusing if we have many connectors doing this differently. I will defer to Sherif.

**Comment by gaart** [comment]
@keu @davinchia @sherifnada updated

**Review by sherifnada — APPROVED** [review]

**Pull request merged**
