### PR TITLE
Fix #2478: Frequency of Jobs

### LINKED ISSUE #2478: Frequency shouldn't be the time between the end of a sync and the beginning of the next one, but the time between the beginning of both
## Expected Behavior
If I set hourly as a frequency and it starts at 1.06pm, I expect it to stay X.06 on the hour. 

## Current Behavior
Right now, if it takes 2 min to sync, the next one will start 2.08pm, and then 3.10pm, etc. 

## Severity of the bug for you
Low

See screenshot
Screen Shot 2021-03-16 at 2 14 36 PM

### PR DESCRIPTION
**Pull request by ffabss**
## What
Closes #2478 
Uses "scheduleAtFixedRate" indtead of "scheduleWithFixedDelay" so that the job gets started after ```initialDelay + numberOfExecution * period```.
[Java Docs](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ScheduledExecutorService.html)

### CODE REVIEW

**Review by michel-tricot — COMMENTED** [review]
Hi @ffabss, thank you for the fix!

**Comment by cgardens** [comment]
Hiya @ffabss, what problem are you trying to solve with this change?

**Review by sherifnada — APPROVED** [review]
LGTM, thanks @ffabss !

**Comment by ffabss** [comment]
So after @cgardens pointed me in the right direction, I managed to use the frequency as the time between the beginnings of the jobs.

This can be seen in the following screenshot.
Screenshot

**Review by cgardens — APPROVED** [review]
nice! thanks for doing this!

**Pull request merged**
