### PR TITLE
Source file: fix csv schema discovery

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/alpha-beta-issues/issues/174
When trying to discover the schema of a csv file, the connector iterates over dataframes and maps columns to its types. The problem is the type is overwritten every iteration, so the final schema is equivalent to the last dataframe types

## How
Do not ignore dataframes. Do not narrow data types, make them only wider

### CODE REVIEW

**Review by grubberr — APPROVED** [review]

**Comment by lmossman** [comment]
@davydov-d since this connector is used in cloud, we also need to publish the cloud version of this (i.e. with the `-secure` suffix on the end, similar to [here](https://github.com/airbytehq/airbyte/pull/15698#issuecomment-1217915478)) otherwise this breaks the cloud build when trying to update the OSS dependency to the latest version. I'll kick off this publish below

**Comment by lmossman** [comment]
Actually I had to also bump the source-file-secure version to match the source-file version, so I opened a separate PR to do that here: https://github.com/airbytehq/airbyte/pull/15896

**Comment by davydov-d** [comment]
@lmossman thank you so much, sorry I missed that!

**Comment by lmossman** [comment]
No problem! It's really easy to miss - definitely a flaw in our current image setup that we will hopefully be addressing soon

**Pull request merged**
