### PR TITLE
destination-redshift: no more standard inserts

### PR DESCRIPTION
**Pull request by stephane-airbyte**
## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by stephane-airbyte** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/39532?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#39532** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/39532?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#39531** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/39531?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @stephane-airbyte and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by assaadhjb** [comment]
Hello @stephane-airbyte, Airbyte Cloud user here, May I ask in the roadmap where this has been determined? 

Also is it normal that as of today I do not have access to standard INSERT indeed, only COPY is available for me? 

Screenshot 2024-07-08 at 14 19 36
Thanks 🙏

**Comment by evantahler** [comment]
Hi @assaadhjb - yep, we've removed SQL/standard inserts from destination redshift on Airbyte Cloud as of https://github.com/airbytehq/airbyte/pull/38886.  Standard inserts was /at least/ 2x as slow as staging inserts (loading content to S3 first, and then using COPY to load the data), and a few other issues with content and escaping as well.  Existing connectors had a grace period to accept the migration until 2024-07-31. 

This PR should be closed as https://github.com/airbytehq/airbyte/pull/38886 is merged already

**Comment by assaadhjb** [comment]
Hello @evantahler , thanks for context
The issue remaining IMO is that COPY with S3 Staging provides only access key authentication whereas `destination-s3` offers both access key and AssumeRole, and the latter is the recommended way in general for third-party tools by AWS. I think if this option is the only one remaining we should be able to use means suited for production preferably before the said grace period. 
Thank you!

**Comment by evantahler** [comment]
@assaadhjb please open a new issue about adding AssumeRole to destination-redshift.

**Pull request closed without merging**
