### PR TITLE
:tada: Source DB2: added ssl support

### LINKED ISSUE #6434: DB2 source
## Tell us about the problem you're trying to solve
We want to support TLS encryption when connecting to the DB2 source.

Note that we do NOT need to support certificate verification as part of this issue -- just encryption of data over the wire. In other words, the focus is protecting against eavesdropping, not man-in-the-middle attacks. See the document [linked](https://docs.google.com/document/d/1Qmbcsf176CQCnudB53SrhWO0RoQuNyuWJbsMSIOdp8o/edit?usp=drivesdk) for more details.

## Describe the solution you’d like
Go through each source/destination in the must-have list. If the connector doesn't support encryption at all then create a ticket to support TLS/SSL for it.  

The acceptance criteria for each ticket is: 

- [ ] Implement encryption support in the connector if not already implemented. Where possible, support encryption by default. If encryption-by-default is a bad idea (for example, if most MySQL versions do not support encryption and would require special work from the DB administrator) then expose it as an option in the connector specification, and encrypt when the user requests it. 
- [ ] The external documentation of the connector mentions that encryption is supported
- [ ] If encryption is exposed as an option, add in the connector spec and docs a recommendation to use it (for example, MSSQL source mentions that encryption without server certification is used for testing purposes only, which is not true, see the doc above)
- [ ] Encrypted connections are tested as part of either a custom integration test or acceptance tests. Where possible, test it using a test container. If that's impossible and it must be tested on a real DB instance, create a DB instance in AWS ideally [using terraform](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/infrastructure) (but if TF is too hard just create it manually and make a ticket to encode it in TF)
- [ ] Create a PR 

## Implementation hints
There is a difference when implementing this for sources & destinations because destinations might need to change normalization as well. 

**When implementing this for sources**, it's probably as simple as setting a flag e.g: Mysql [uses the `--ssl=REQUIRED` flag](https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#option_general_ssl).

**When implementing for destinations** it might be very similar, but there will be **two** places to edit this: in the destination connector itself and in the normalization module. It might be easiest to ask the Python team to implement the piece around normalization, but it really shouldn't be that complicated e.g: if it's just adding a flag -- it's ideal if you can implement it yourself since you'll learn a bit about normalization, but this is not a primary goal of this ticket. The goal is to support TLS as soon as possible. 

## Describe the alternative you’ve considered or used
You can find an example of enabling TLS encryption for MongoDB source connector.
[Example PR of adding TLS support to the MongoDB source](https://github.com/airbytehq/airbyte/pull/6364)

### PR DESCRIPTION
**Pull request by andriikorotkov**
## What
The Source DB2 didn't support SSL.

## How
Added SSL support.

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by irynakruk — APPROVED** [review]
Please check small comment, everything else LGTM

**Review by sherifnada — CHANGES_REQUESTED** [review]
I have a concern about having our only SSL option being only available with certificate verification because like described int he [database security rfc](https://docs.google.com/document/d/1Qmbcsf176CQCnudB53SrhWO0RoQuNyuWJbsMSIOdp8o/edit?usp=drivesdk) (see "interaction between TLS and SSH") it will conflict with SSH tunnels. 

The docs seem to imply we can do TLS without cert verification. Can we switch the implementation to use that instead?

**Comment by andriikorotkov** [comment]
@sherifnada, I apologize, I have searched many sources on DB2, but unfortunately, I have not found a SSL configuration without using a certificate. As the main source I used the ibm db2 documentation - https://www.ibm.com/docs/en/db2/11.1?topic=db2-configuring-tls-support-instance

**Review by alexandr-shegeda — APPROVED** [review]

**Comment by sherifnada** [comment]
@andriikorotkov [this page ](https://www.ibm.com/docs/en/db2-for-zos/11?topic=dsdjsss-configuring-connections-under-data-server-driver-jdbc-sqlj-use-ssl) seems to imply that the truststore/certiifcate stuff is optional? I could be misreading it though. I say this because only step 1 is required, all the cert stuff are optional in that list. LMK if I'm just misreading it.

**Comment by andriikorotkov** [comment]
@sherifnada, I was looking at the page you pointed to. Unfortunately, this method does not work. @alexandr-shegeda  and I tried to find such a configuration, but we could not find any information other than this page. All the options that we tried do not work without the use of certificates. I set up the instance according to the following instructions - https://www.ibm.com/docs/en/db2/11.5?topic=db2-configuring-tls-support-instance and https://blog.toadworld.com/2017/08/21/configure-ibm-db2-luw-v11-1-for-ssl-connections-self-signed-certificate. Setting up an SSL using a certificate works well.

**Comment by sherifnada** [comment]
@andriikorotkov got it -- in that case I would say let's merge this for now then. Thanks for doing the research!

**Review by sherifnada — APPROVED** [review]

**Pull request merged**
