### PR TITLE
Docs: streams table

### PR DESCRIPTION
**Pull request by sophia-wiley**
Updated docs for the new stream table.

The UI for the new streams table has been updated, so I updated docs to reflect those changes and made new gifs to show the updated UI.

### CODE REVIEW

**Comment by sophia-wiley** [comment]
gif-single-edit-march-2023

**Comment by sophia-wiley** [comment]
gif-batch-edit-march-2023

**Review by andyjih — CHANGES_REQUESTED** [review]
Looks good! I have a few comments/edits.

**Comment by sophia-wiley** [comment]
@andyjih thanks for taking a look! I committed your suggestions.

**Review by andyjih — APPROVED** [review]

**Review by edmundito — COMMENTED** [review]
Just had some minor comments about this. I had a bigger note about how to refer to the primary keys; the user can always select multiple.

**Pull request merged**
