### PR TITLE
db data catalog jobs

### PR DESCRIPTION
**Pull request by cgardens**
## What
* Successor of this PR https://github.com/airbytehq/airbyte/pull/16427 . Catalogs the tables in the jobs db.

## To do
- [x] get feedback from subject matter experts to confirm accuracy.

### CODE REVIEW

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Comment by gosusnp** [comment]
Is the configs/jobs db split still accurate?
Looking at the current data model, we write all the tables in airbyte db. The only remnant of that split seems to be the two migrations sets we have in flyway.

**Comment by cgardens** [comment]
> Is the configs/jobs db split still accurate?
> Looking at the current data model, we write all the tables in airbyte db. The only remnant of that split seems to be the two migrations sets we have in flyway.

Yeah. I think we should consider these data stores to be supporting 2 separate services. It was a mistake that they ended up in the same db instance. I would advocate for us to just move this over in a future maintenance window, because everyone who joins asks this question. 

cc @davinchia because I know we have generally had different points of view on this one.
cc @supertopher would this be a project we could ask GL to do? (not high priority, just trying to understand if it would be a good fit).

**Comment by supertopher** [comment]
@cgardens I think this seems like work the GL team has experience in.  I made a story to [track this here](https://github.com/airbytehq/airbyte-cloud/issues/2716) 

Please make sure it sounds like the solution you are looking for since I'm getting this information a bit second hand

**Comment by davinchia** [comment]
@cgardens less of a different pov and more of a sequencing bit. I didn't think it was worth the hassle of managing 2 databases back then given we weren't sure how Cloud would evolve. I do think now is a good time to shift this over, as we scales with the goal of making it easier to manage the different scaling requirements.

@supertopher I think we should try this on a dev env first. There will be some env vars we likely need to change to make sure the applications are reading from the right database.

**Review by davinchia — APPROVED** [review]

**Comment by cgardens** [comment]
Thank you. Agreed with all of your follow ups. @supertopher @davinchia

**Pull request merged**
