### PR TITLE
Fix typo in spec.json for destination AWS Datalake

### PR DESCRIPTION
**Pull request by kattos-aws**
## What
_Describe what the change is solving_

There was a typo preventing the setup of an AWS Datalake destination (the UI would always complain about a missing `aws_secret_access_key_id`.

## How
Fixed mandatory field `aws_secret_access_key_id` to `aws_secret_access_key`.

## Recommended reading order
1. `spec.json`

## :rotating_light: User Impact :rotating_light:
None

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter
* [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
* [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
* [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
* [ ] Code reviews completed
* [ ] Documentation updated
  * [ ] Connector's `README.md`
  * [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
  * [ ] `docs/SUMMARY.md`
  * [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
  * [ ] `docs/integrations/README.md`
  * [ ] `airbyte-integrations/builds.md`
* [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter
If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

* [ ] Create a non-forked branch based on this PR and test the below items on it
* [ ] Build is successful
* [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
* [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
* [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
* [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
* [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter
* [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
* [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
* [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
* [ ] Code reviews completed
* [ ] Documentation updated
  * [ ] Connector's `README.md`
  * [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
  * [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
* [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter
If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

* [ ] Create a non-forked branch based on this PR and test the below items on it
* [ ] Build is successful
* [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
* [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
* [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
* [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
* [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

* [ ] Issue acceptance criteria met
* [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
* [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
* [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
* [ ] Documentation which references the generator is updated as needed

</details>

## Tests
<details><summary><strong>Unit</strong></summary>

_Put your unit tests output here._

</details>

<details><summary><strong>Integration</strong></summary>

_Put your integration tests output here._

</details>

<details><summary><strong>Acceptance</strong></summary>

_Put your acceptance tests output here._

</details>

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537090818) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by sherifnada — APPROVED** [review]

**Comment by marcosmarxm** [comment]
@kattos-aws can you bump the Dockerfile version to 0.1.1?

**Comment by kattos-aws** [comment]
@sherifnada @marcosmarxm Seems like the merging is blocked. Anything I can do on my end?

**Comment by sherifnada** [comment]
@kattos-aws are the local integration tests succeeding for you? Could you share a screenshot of the output of `:airbyte-integrations:connectors:destination-aws-datalake:integrationTest`? If they succeed, do you mind sharing what your sandbox account setup is like? e.g: what tables or data do you have in it?

**Comment by kattos-aws** [comment]
@sherifnada 


## integration tests are indeed currently failing

```
AwsDatalakeDestinationAcceptanceTest > testCustomDbtTransformations() PASSED
29 tests completed, 2 failed, 1 skipped
> Task :airbyte-integrations:connectors:destination-aws-datalake:integrationTestJava FAILED
FAILURE: Build failed with an exception.
```

The two tests which are failing are:
1. `testSecondSync`: Not sure what's going on here, I need to investigate further
1. `testSync` with `stream_with_nested_objects` for which there was indeed no support. I have produced a tentative implementation which seems to do the job (as tested by querying data in Athena), but I struggle with making it pass the test. I get: 
 ```
    2022-04-13 09:53:10 INFO i.a.i.s.d.DestinationAcceptanceTest(assertSameData):1189 - Expected row {"created_at":"2021-01-01","object":{"created_at":"2021-01-01T01:01:01+01"}}
    2022-04-13 09:53:10 INFO i.a.i.s.d.DestinationAcceptanceTest(assertSameData):1190 - Actual row   {"created_at":"2021-01-01","object":"{created_at=2021-01-01T01:01:01+01}"}
    2022-04-13 09:53:10 INFO i.a.i.s.d.DestinationAcceptanceTest(assertSameData):1204 - For created_at Expected "2021-01-01" vs Actual "2021-01-01"
    2022-04-13 09:53:10 INFO i.a.i.s.d.DestinationAcceptanceTest(assertSameData):1204 - For object Expected {"created_at":"2021-01-01T01:01:01+01"} vs Actual "{created_at=2021-01-01T01:01:01+01}"
```

I'm going to push a commit for that issue with nested objects and, if you have any idea how to implement the test, I would love to hear!

## Sandbox account setup

I have [updated the doc](https://github.com/airbytehq/airbyte/pull/11811/commits/572670891770b0afa8e10b48a7d29afa2efe653a) to give some directions to that. It is a bit tricky because lots of things are done solely for the purpose of passing the Destination Acceptance Tests (ex: Athena has no relevance to the connector itself; the connector is written in Python and the tests are implemented in Java).

Let me know if that helps, or if you need complements to that.

**Comment by kattos-aws** [comment]
The `testSecondSync` test runs correctly after the following [commit](https://github.com/airbytehq/airbyte/pull/11811/commits/760252c355604c2498ae0a10aa161d3b323e0cd0).

Here are the logs for the integration tests:
[airbyte-integration-tests.log.gz](https://github.com/airbytehq/airbyte/files/8482446/airbyte-integration-tests.log.gz)

The remaining error is for the nested objects test case, for which the connector now offers basic support, but I'm unsure how to reflect this in the test suite.

@sherifnada @marcosmarxm if you have any hint / advice I'd be happy to hear!

**Comment by sherifnada** [comment]
@kattos-aws is the connector supposed to support writing nested objects? Does it make sense in the context of Athena? If no it may make sense to skip that test case. @edgao is there a way to skip it? . If yes however then we’ll need to help fix. @edgao do. You have any thoughts on what’s breaking there?

**Comment by edgao** [comment]
@sherifnada your `/publish` command failed with this error:
```
    2022-04-07 22:56:47 INFO i.a.i.d.a.AthenaHelper(runQuery):118 - Athena query failed once. Retrying.
    2022-04-07 22:56:47 INFO i.a.i.d.a.AthenaHelper(runQuery):124 - Athena query failed and we are out of retries.

AwsDatalakeDestinationAcceptanceTest > testSync(String, String) > io.airbyte.integrations.destination.aws_datalake.AwsDatalakeDestinationAcceptanceTest.testSync(String, String)[2] FAILED
    java.lang.NullPointerException: Cannot invoke "software.amazon.awssdk.services.athena.paginators.GetQueryResultsIterable.iterator()" because "queryResults" is null
        at io.airbyte.integrations.destination.aws_datalake.AwsDatalakeDestinationAcceptanceTest.parseResults(AwsDatalakeDestinationAcceptanceTest.java:96)
        at io.airbyte.integrations.destination.aws_datalake.AwsDatalakeDestinationAcceptanceTest.retrieveRecords(AwsDatalakeDestinationAcceptanceTest.java:89)
```
Which seems like we just failed to query Athena, rather than any data type issues? ([direct log link](https://github.com/airbytehq/airbyte/runs/5877053456?check_suite_focus=true#step:16:1790)) Unfortunately there's no indication of why the query failed, at least that I can see. It _is_ consistently failing (at least in both your+marcos' runs) so maybe we should add some additional logging here?

---

@kattos-aws 
> turn "expected" into a string with the proper format to match "actual"

If I'm understanding you correctly, you can do this by overriding `assertSameValue` in AwsDatalakeDestinationAcceptanceTest; e.g. [MySQL](https://github.com/airbytehq/airbyte/blob/af1d087d223b08c10eaed827b1132d186497f4cd/airbyte-integrations/connectors/destination-mysql/src/test-integration/java/io/airbyte/integrations/destination/mysql/MySQLDestinationAcceptanceTest.java#L243) has special handling for boolean types.

https://github.com/airbytehq/airbyte/blob/af1d087d223b08c10eaed827b1132d186497f4cd/airbyte-integrations/bases/standard-destination-test/src/main/java/io/airbyte/integrations/standardtest/destination/DestinationAcceptanceTest.java#L1179

Which sounds reasonable to me, since it sounds like we want special handling for object values. You'd probably want something like `if (expectedValue.isObject()) { assertEqual(toAthenaishString(expectedValue), actualValue) }`.

**Comment by marcosmarxm** [comment]
The strange part of this is last week I was able to run tests and publish the same code!

**Comment by edgao** [comment]
ah I see that @kattos-aws actually added a printStacktrace to the runQuery method; rerunning tests

**Comment by edgao** [comment]
this looks like our integration test env is just borked? Not sure what it's supposed to look like, though  - @marcosmarxm have you looked at it in the past?
```
AwsDatalakeDestinationAcceptanceTest > testSync(String, String) > io.airbyte.integrations.destination.aws_datalake.AwsDatalakeDestinationAcceptanceTest.testSync(String, String)[1] STANDARD_ERROR
    software.amazon.awssdk.services.athena.model.InvalidRequestException: WorkGroup AmazonAthenaLakeFormation is not found. (Service: Athena, Status Code: 400, Request ID: 689171c1-38d6-4471-ad61-1b3e4b3d4ead, Extended Request ID: null)
```

**Comment by kattos-aws** [comment]
@edgao Setting up the test environment is not as simple as I'd like it to be. I've provided some guidance in this [commit](https://github.com/airbytehq/airbyte/pull/11811/commits/572670891770b0afa8e10b48a7d29afa2efe653a). Please let me know if that helps. If that helps, I can be available for a call  next week to go over it and maybe help set the test environment up. Let me know!

**Comment by kattos-aws** [comment]
@edgao I fixed the Destination Acceptance Tests as per your suggestion (overriding `assertSameValue`).
The tests now pass successfully on my end. Here are the logs:
[airbyte-integration-tests.log.gz](https://github.com/airbytehq/airbyte/files/8522831/airbyte-integration-tests.log.gz)

Please let me know what you think!

**Comment by marcosmarxm** [comment]
/publish connector=connectors/destination-aws-datalake auto-bump-version=false

**Comment by marcosmarxm** [comment]
@edgao can you help me here? 
```
* What went wrong:
A problem was found with the configuration of task ':airbyte-integrations:connectors:destination-aws-datalake:licenseIntegrationTestJava' (type 'LicenseCheck').
  - In plugin 'com.hierynomus.gradle.license.LicenseBasePlugin' type 'com.hierynomus.gradle.license.tasks.LicenseCheck' property 'header' specifies file '/actions-runner/_work/airbyte/airbyte/airbyte-integrations/connectors/destination-aws-datalake/LICENSE' which doesn't exist.
 ```
CI is failing with this error

**Comment by edgao** [comment]
@marcosmarxm I haven't, unfortunately. I'm actually pretty confused, because when I pull this branch locally, it errors out at that step even at commit 746c491, which has a passing test earlier in this pr (https://github.com/airbytehq/airbyte/pull/11811#issuecomment-1104459655). `touch airbyte-integrations/connectors/destination-aws-datalake/LICENSE` fixes it, but I'm not sure that's the intended action (none of our other connectors have a LICENSE file)

**Comment by kattos-aws** [comment]
@marcosmarxm @edgao Should we add this LICENCE file? If so, feel free to update with whatever you think is appropriate.

Please let me know if there's anything I can / should do on my end!

Thanks

**Comment by edgao** [comment]
@sherifnada is this (https://github.com/airbytehq/airbyte/pull/11811#issuecomment-1104540265) something you can help with? I spent some time yesterday+today trying to get this to work, but haven't really figured it out. Plausibly I'm just missing something obvious:
* no other connector even has a `licenseIntegrationTestJava` task (according to `./gradlew tasks --all`)
* manually running `:airbyte-integrations:connectors:destination-aws-datalake:licenseMain` also fails, whereas e.g. `:airbyte-integrations:connectors:destination-rabbitmq:licenseMain` passes
* these `:licenseFoo` tasks seem to only exist on Python connectors, but I didn't find any obvious configuration to make them work

**Comment by marcosmarxm** [comment]
> @marcosmarxm @edgao Should we add this LICENCE file? If so, feel free to update with whatever you think is appropriate.
> 
> Please let me know if there's anything I can / should do on my end!
> 
> Thanks

Looks is a problem with gradle running some task @kattos-aws

**Comment by sherifnada** [comment]
/publish connector=connectors/destination-aws-datalake auto-bump-version=false

**Pull request merged**
