### PR TITLE
Migrate Orb Source Connector to Low Code

### LINKED ISSUE #28952: orb

### PR DESCRIPTION
**Pull request by topefolorunso**
## What
Migrating Source Orb to Low-Code CDK resolves #28952

## How
Created the connector using the connector buider UI, then imported the manifest.yaml to the low code cdk.

## Recommended reading order
1. `manifest.yaml`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by sajarin** [comment]
Thanks for the PR, getting the following error when running the acceptance tests: 

image

**Comment by topefolorunso** [comment]
> Thanks for the PR, getting the following error when running the acceptance tests:
> 
> image

@sajarin @marcosmarxm I need help here, please. The error is resulting from one of the primary keys defined which is gotten from the config. Apparently, I can't use an interpolated string in the primary key field. It has to be a literal string.

How can I extract the value from the config without making it an interpolated string

**Comment by archangelic** [comment]
@topefolorunso I am investigating to see how this can be implemented in low code.

**Comment by topefolorunso** [comment]
Any update on this please? @archangelic

**Comment by marcosmarxm** [comment]
Hello, and thank you so much for contributing to the project during the Hackathon. Due to the high complexity of the code migration, we still have a few contributions open. I'm sending this message to update you that this contribution will be added to the final points we're going to announce tomorrow. With that said, we ask for your help to continue the process and finish the review.

**Comment by archangelic** [comment]
Thank you for your contribution and all effort to make the connectors better! During our review process we discovered this connector uses parameters from the config to transform the schema and record (add links to the code). These features aren't supported by the low code framework and because of this we're going to close the contribution for now.

**Pull request closed without merging**
