### PR TITLE
Sherif/test 27533

### PR DESCRIPTION
**Pull request by sherifnada**
teseting pr #27533

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-okta test report (commit [`8a2246e435`](https://github.com/airbytehq/airbyte/pull/27713/commits/8a2246e435f9c6e4b9382c8df7ad79dd26840b0c)) - ✅

⏲️  Total pipeline duration: 58 seconds

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sherif_test-27533/1687886274/8a2246e435f9c6e4b9382c8df7ad79dd26840b0c/source-okta/0.1.15/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-okta test
```

**Comment by octavia-squidington-iii** [comment]
##  source-okta test report (commit [`8a2246e435`](https://github.com/airbytehq/airbyte/pull/27713/commits/8a2246e435f9c6e4b9382c8df7ad79dd26840b0c)) - ✅

⏲️  Total pipeline duration: 39 seconds

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sherif_test-27533/1687937061/8a2246e435f9c6e4b9382c8df7ad79dd26840b0c/source-okta/0.1.15/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-okta test
```

**Comment by octavia-squidington-iii** [comment]
##  source-okta test report (commit [`552a17641c`](https://github.com/airbytehq/airbyte/pull/27713/commits/552a17641cd02a2f2f556a4cf97d74c68910e19c)) - ❌

⏲️  Total pipeline duration: 62 seconds

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-okta/metadata.yaml | ✅        |
| Connector version semver check                                     | ✅        |
| Connector version increment check                                  | ✅        |
| QA checks                                                          | ✅        |
| Code format checks                                                 | ❌        |
| Connector package install                                          | ✅        |
| Build source-okta docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                         | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sherif_test-27533/1687977446/552a17641cd02a2f2f556a4cf97d74c68910e19c/source-okta/0.1.15/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-okta test
```

**Comment by octavia-squidington-iii** [comment]
##  source-okta test report (commit [`5013df6288`](https://github.com/airbytehq/airbyte/pull/27713/commits/5013df628800dea0b716ff72eb07067c105f5e5c)) - ❌

⏲️  Total pipeline duration: 248 seconds

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-okta/metadata.yaml | ✅        |
| Connector version semver check                                     | ✅        |
| Connector version increment check                                  | ✅        |
| QA checks                                                          | ✅        |
| Code format checks                                                 | ❌        |
| Connector package install                                          | ✅        |
| Build source-okta docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                         | ✅        |
| Acceptance tests                                                   | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sherif_test-27533/1687977802/5013df628800dea0b716ff72eb07067c105f5e5c/source-okta/0.1.15/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-okta test
```

**Comment by octavia-squidington-iii** [comment]
##  source-okta test report (commit [`f164064f85`](https://github.com/airbytehq/airbyte/pull/27713/commits/f164064f856552f8fa8530b8e02b7e2e722365c4)) - ❌

⏲️  Total pipeline duration: 267 seconds

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-okta/metadata.yaml | ✅        |
| Connector version semver check                                     | ✅        |
| Connector version increment check                                  | ✅        |
| QA checks                                                          | ✅        |
| Code format checks                                                 | ❌        |
| Connector package install                                          | ✅        |
| Build source-okta docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                         | ✅        |
| Acceptance tests                                                   | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sherif_test-27533/1687978235/f164064f856552f8fa8530b8e02b7e2e722365c4/source-okta/0.1.15/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-okta test
```

**Comment by octavia-squidington-iii** [comment]
##  source-okta test report (commit [`4f85ede598`](https://github.com/airbytehq/airbyte/pull/27713/commits/4f85ede598679fc6bc1b4e2255a796bc71ccd1ee)) - ✅

⏲️  Total pipeline duration: 228 seconds

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-okta/metadata.yaml | ✅        |
| Connector version semver check                                     | ✅        |
| Connector version increment check                                  | ✅        |
| QA checks                                                          | ✅        |
| Code format checks                                                 | ✅        |
| Connector package install                                          | ✅        |
| Build source-okta docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                         | ✅        |
| Acceptance tests                                                   | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sherif_test-27533/1687979448/4f85ede598679fc6bc1b4e2255a796bc71ccd1ee/source-okta/0.1.15/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-okta test
```

**Comment by sherifnada** [comment]
upstream merged

**Comment by octavia-squidington-iii** [comment]
##  source-okta test report (commit [`c1ad6ecf2d`](https://github.com/airbytehq/airbyte/pull/27713/commits/c1ad6ecf2da99e76e960f480c316a1592c232264)) - ✅

⏲️  Total pipeline duration: 238 seconds

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-okta/metadata.yaml | ✅        |
| Connector version semver check                                     | ✅        |
| Connector version increment check                                  | ✅        |
| QA checks                                                          | ✅        |
| Code format checks                                                 | ✅        |
| Connector package install                                          | ✅        |
| Build source-okta docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                         | ✅        |
| Acceptance tests                                                   | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sherif_test-27533/1687980101/c1ad6ecf2da99e76e960f480c316a1592c232264/source-okta/0.1.15/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-okta test
```

**Pull request closed without merging**
