### PR TITLE
:tada: Source RD Station Marketing: migrated to advancedOAuth

### LINKED ISSUE #27974: Source RD Station Marketing: Migrate to advancedAuth
Action items:

- migrate to support new advancedAuth

### PR DESCRIPTION
**Pull request by darynaishchenko**
## What
resolved: https://github.com/airbytehq/airbyte/issues/27974

## How
Removed deprecated authSpecification, switched to advanced_auth

## Note
Acceptance test are blocked by test creds. This connector is disabled on cloud, so this part of code was not used. So PR can be merged without passed tests ([slack thread](https://airbyte-globallogic.slack.com/archives/C02U9R3AF37/p1688643296648019?thread_ts=1688643023.947839&cid=C02U9R3AF37))

### CODE REVIEW

**Review by lazebnyi — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-rd-station-marketing test report (commit [`ec72c6da65`](https://github.com/airbytehq/airbyte/pull/28009/commits/ec72c6da65ab0e823f3892404e0f55ec4c8a9b99)) - ❌

⏲️  Total pipeline duration: 02mn41s 

| Step                                                                               | Result   |
|:-----------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-rd-station-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                     | ✅        |
| Connector version increment check                                                  | ✅        |
| QA checks                                                                          | ✅        |
| Code format checks                                                                 | ✅        |
| Connector package install                                                          | ✅        |
| Build source-rd-station-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                         | ✅        |
| Acceptance tests                                                                   | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-rd-station-marketing_migrate-to-advancedauth/1688657917/ec72c6da65ab0e823f3892404e0f55ec4c8a9b99/source-rd-station-marketing/0.1.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-rd-station-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-rd-station-marketing test report (commit [`ec72c6da65`](https://github.com/airbytehq/airbyte/pull/28009/commits/ec72c6da65ab0e823f3892404e0f55ec4c8a9b99)) - ❌

⏲️  Total pipeline duration: 02mn40s 

| Step                                                                               | Result   |
|:-----------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-rd-station-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                     | ✅        |
| Connector version increment check                                                  | ✅        |
| QA checks                                                                          | ✅        |
| Code format checks                                                                 | ✅        |
| Connector package install                                                          | ✅        |
| Build source-rd-station-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                         | ✅        |
| Acceptance tests                                                                   | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-rd-station-marketing_migrate-to-advancedauth/1688662519/ec72c6da65ab0e823f3892404e0f55ec4c8a9b99/source-rd-station-marketing/0.1.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-rd-station-marketing test
```

**Comment by octavia-approvington** [comment]
You did it! <br/> finish line

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
