### PR TITLE
🎉 New Destination: Apache Doris

### PR DESCRIPTION
**Pull request by catpineapple**
## What
Add destination doris

## How
destination-doris is a destination implemented based on Doris stream load,
It works as follows:
1:  read stream and write a temp  csv file.
2: make a http put request to pre-commit this csv file.
3: make a http request commit this transaction .

## Recommended reading order
1. `DorisDestination.java`
2. `DorisConsumer.java`
3. `DorisStreamLoad.java`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

image

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@catpineapple how are you running the integration tests? do you have a local Apache Doris running? Can you add the setup to use a docker container?

**Comment by catpineapple** [comment]
> 

1. build this docker image :airbyte/destination-doris:dev  , then  add this destination at localhost:8000 -> settings -> destinations -> +new connecter.
2. installed an apache doris (1be+1fe). and create target database and tables.
3. New connection: make a sources read File(csv)  ,and make a doris destination  ( settings: Host,Port,Database,user,password). 
image

5. run task,sync data.
image

**Comment by marcosmarxm** [comment]
Can you add the setup of docker container to automate tests? Doing manual tests aren't viable.

**Comment by harshithmullapudi** [comment]
Hey @marcosmarxm did you mean add the creation of database in the testing suite in itself?

**Comment by marcosmarxm** [comment]
Yes.

**Comment by marcosmarxm** [comment]
> > 
> 
> 1. build this docker image :airbyte/destination-doris:dev  , then  add this destination at localhost:8000 -> settings -> destinations -> +new connecter.
> 2. installed an apache doris (1be+1fe). and create target database and tables.
> 3. New connection: make a sources read File(csv)  ,and make a doris destination  ( settings: Host,Port,Database,user,password).
> 
> image
> 
> 5. run task,sync data.
> 
> image

Can you add a bootstrap.md how to do this process? I don't have knowledge about Apache Doris and setup the tool is not trivial. We must have this documentation to show people how to be able to test locally and probably improve in the future.

**Comment by marcosmarxm** [comment]
@catpineapple can you check Yugabytedb destination implementation. It uses a docker-compose setup to spin-up containers to run tests automatically. Let me know what do you think about implementing it for Apache Doris.

**Comment by catpineapple** [comment]
> 

Is there any documentation to guide me to do this, I don't quite understand what kind of test this is. @marcosmarxm

**Comment by catpineapple** [comment]
> @catpineapple can you check Yugabytedb destination implementation. It uses a docker-compose setup to spin-up containers to run tests automatically. Let me know what do you think about implementing it for Apache Doris.

Sorry for my foolish, please list as many areas as possible that I need to improve, the current way is too inefficient @marcosmarxm

**Comment by marcosmarxm** [comment]
Hello! Your PR is approved but didn't have the time to publish and merge it this week. As you can check in [Chris' comment](https://airbytehq-team.slack.com/archives/C0450PCSDB2/p1667430678866629) all PRs submitted before 2-nov are eligible to win the prize. I'll be out of the office on Friday and return Monday to start publish it. Any question you can send a message in `#hacktoberfest-2022` in Airbyte's Slack.

Have a good weekend and thank you for this amazing contribution for Hacktoberfest 🎉

**Comment by catpineapple** [comment]
> 
hi，I would like to inquire about the merge progress of this pull request
and  Have a nice weekend

**Comment by marcosmarxm** [comment]
/publish connector=connectors/destination-doris run-tests=false

**Review by marcosmarxm — APPROVED** [review]
Thanks @catpineapple sorry the delay to merge this amazing contribution :)

**Comment by RealChrisSean** [comment]
Hello @catpineapple ! Can you please provide the best email to contact you about payouts. Thank you!

**Comment by catpineapple** [comment]
> Hello @catpineapple ! Can you please provide the best email to contact you about payouts. Thank you!

1391869588@qq.com

**Comment by catpineapple** [comment]
> Hello @catpineapple ! Can you please provide the best email to contact you about payouts. Thank you!

I remembered this incident recently, is there any further information?

**Pull request merged**
