### PR TITLE
Fix intercom

### PR DESCRIPTION
**Pull request by benmoriceau**
## What
Fix the intercom schema, related to https://github.com/airbytehq/oncall/issues/463

The check which is performed to see if a property/array is a oneOf/allOf/anyOf is based on the presence of the `type` field.
```
private static boolean isOneOfField(final JsonNode schema) {
    return !MoreIterators.toSet(schema.fieldNames()).contains("type");
  }
```

Because the type were specified if the oneOf is contains in an array, the array was not considered as containing a oneOf and thus was not excluded from the diff comparison which is expected.

### CODE REVIEW

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Review by davinchia — APPROVED** [review]

**Review by sherifnada — COMMENTED** [review]
@benmoriceau i would recommend removing the `anyOf` entirely and just making the object definition: 

```
       "tags": {
          "type": "array",
          "items": {
            "type": ["null", "object"],
                "properties": {
                  "type": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "id": {
                    "type": "integer"
                  }
                }
              }
        }
      }
```

same for the object below

**Comment by benmoriceau** [comment]
> @benmoriceau i would recommend removing the `anyOf` entirely and just making the object definition:
> 
> ```
>        "tags": {
>           "type": "array",
>           "items": {
>             "type": ["null", "object"],
>                 "properties": {
>                   "type": {
>                     "type": "string"
>                   },
>                   "name": {
>                     "type": "string"
>                   },
>                   "id": {
>                     "type": "integer"
>                   }
>                 }
>               }
>         }
>       }
> ```
> 
> same for the object below


Done

**Comment by sherifnada** [comment]
@benmoriceau I don't see it on the branch - do you need to git push?

**Comment by benmoriceau** [comment]
> 

@sherifnada, Yeah, I forget to push, It is updated now but I am having issue to test. It seem that the bmusko plugin version got updated today.

**Comment by nauxliu** [comment]
With the source intercom version 0.1.26, it stucks when refreshing the source schema, and I found some error logs in the server pod that seems related to this change

```
2022-09-13 16:33:12 WARN i.a.c.j.JsonSchemas(traverseJsonSchemaInternal):208 - The object is a properties key or a combo keyword. The traversal is silently stopped. Current schema: {"type":["null","object"],"items":{"type":"object","properties":{"id":{"type":["null","string"]},"type":{"type":["null","string"]}},"additionalProperties":false}}
2022-09-13 16:33:12 WARN i.a.c.j.JsonSchemas(traverseJsonSchemaInternal):208 - The object is a properties key or a combo keyword. The traversal is silently stopped. Current schema: {"type":["null","object"],"additionalProperties":true}
2022-09-13 16:33:12 ERROR i.a.s.e.UncaughtExceptionMapper(toResponse):22 - Uncaught exception
java.lang.IllegalStateException: Duplicate key [tags, tags, items] (attempted merging values {"type":["null","object"],"anyOf":[{"type":"object","properties":{"id":{"type":"integer"},"name":{"type":"string"},"type":{"type":"string"}}}]} and {"type":"object","properties":{"id":{"type":"integer"},"name":{"type":"string"},"type":{"type":"string"}}})
	at java.util.stream.Collectors.duplicateKeyException(Collectors.java:135) ~[?:?]
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at io.airbyte.protocol.models.CatalogHelpers.getStreamDiff(CatalogHelpers.java:337) ~[io.airbyte.airbyte-protocol-protocol-models-0.40.4.jar:?]
	at io.airbyte.protocol.models.CatalogHelpers.lambda$getCatalogDiff$9(CatalogHelpers.java:325) ~[io.airbyte.airbyte-protocol-protocol-models-0.40.4.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at io.airbyte.protocol.models.CatalogHelpers.getCatalogDiff(CatalogHelpers.java:321) ~[io.airbyte.airbyte-protocol-protocol-models-0.40.4.jar:?]
	at io.airbyte.server.handlers.ConnectionsHandler.getDiff(ConnectionsHandler.java:296) ~[io.airbyte-airbyte-server-0.40.4.jar:?]
	at io.airbyte.server.handlers.WebBackendConnectionsHandler.webBackendGetConnection(WebBackendConnectionsHandler.java:263) ~[io.airbyte-airbyte-server-0.40.4.jar:?]
	at io.airbyte.server.apis.ConfigurationApi.lambda$webBackendGetConnection$89(ConfigurationApi.java:825) ~[io.airbyte-airbyte-server-0.40.4.jar:?]
	at io.airbyte.server.apis.ConfigurationApi.execute(ConfigurationApi.java:886) ~[io.airbyte-airbyte-server-0.40.4.jar:?]
	at io.airbyte.server.apis.ConfigurationApi.webBackendGetConnection(ConfigurationApi.java:825) ~[io.airbyte-airbyte-server-0.40.4.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.Server.handle(Server.java:501) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
2022-09-13 16:33:12 ERROR i.a.s.RequestLogger(filter):110 - REQ 172.27.56.249 POST 500 /api/v1/web_backend/connections/get - {"connectionId":"fa20c69f-e948-43bb-8b8f-fcee2a4aa916","withRefreshedCatalog":true}
```

**Comment by benmoriceau** [comment]
Hello @nauxliu,
It is expected https://github.com/airbytehq/airbyte/pull/16513 will fix it.

**Comment by benmoriceau** [comment]
Hello @nauxliu,
The fix has been released in the version `0.40.6` of the airbyte platform.

**Pull request merged**
