### PR TITLE
Remove createDatabaseInternal()

### PR DESCRIPTION
**Pull request by akashkulk**
Some internal cleanup to remove createDatabaseInternal()

### CODE REVIEW

**Review by rodireich — APPROVED** [review]

**Comment by octavia-approvington** [comment]
Trying to merge your PR using a bot?
Comment this on the PR:
```
/approve-and-merge reason="<STATE YOUR REASON HERE>"
```
Make sure you've reviewed the [docs](https://internal-docs.airbyte.io/How-Tos/Overriding-PR-Merge-Rules)!

**Comment by octavia-approvington** [comment]
After a careful ML study, <br/> we think this looks okay.  <br/> imagine code being okay

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
