### PR TITLE
cdc: refactor to remove debezium dependency from connector packages

### PR DESCRIPTION
**Pull request by subodh1810**
There is no issue for this, this is just some refactoring that I had in mind for a long time. Using gradle's dependency sharing technique keeps things at 1 place and simpler to understand.

### CODE REVIEW

**Review by akashkulk — APPROVED** [review]

**Comment by subodh1810** [comment]
/publish connector=connectors/source-postgres,connectors/source-postgres-strict-encrypt,connectors/source-mysql,connectors/source-mysql-strict-encrypt,connectors/source-mssql,connectors/source-alloydb,connectors/source-alloydb-strict-encrypt

**Comment by subodh1810** [comment]
/publish connector=connectors/source-mssql-strict-encrypt run-tests=false

**Comment by subodh1810** [comment]
/publish connector=connectors/source-mssql-strict-encrypt run-tests=false

**Pull request merged**
