### PR TITLE
feat: added sorting for name, connector and lastsync field

### LINKED ISSUE #8754: Implement sorting for Sources & Destinations
## Tell us about the problem you're trying to solve
For workspaces with more than a handful of sources or destinations, it's difficult to manage in the current UI. 

## Describe the solution you’d like
The columns within the Sources and Destinations UI should support sorting by ascending or descending order similar to what exists today in the Connections UI. 

Specifically, the `name`, `connector`, `destination` / `source` columns should be able to be sorted. 

## Describe the alternative you’ve considered or used
Using the browser's native find functionality to manually search for sources or destinations in the list.

## Additional context
What exists today in Connections:
Airbyte  Connections 2021-12-13 at 10 36 42 AM

What's missing from Sources / Destinations:
Airbyte  Sources 2021-12-13 at 10 37 11 AM

### PR DESCRIPTION
**Pull request by harshithmullapudi**
## What
closes https://github.com/airbytehq/airbyte/issues/8754

### CODE REVIEW

**Comment by harshithmullapudi** [comment]
@timroes can you review this when you get time?

**Comment by tealjulia** [comment]
Tested locally and feature works as expected 👍

**Review by teallarson — APPROVED** [review]

**Comment by dizel852** [comment]
@timroes can we merge the PR?

**Comment by timroes** [comment]
@dizel852 usually we have it on the author (if a member of airbyte) to merge that PR. Given that this PR is now rather outdated with master, I'd suggest we bring it once more up to date with master and have CI pass on it before merging.

**Comment by dizel852** [comment]
@timroes gotcha gotcha 😄

**Comment by harshithmullapudi** [comment]
Hey I have rebased it with latest master @timroes is it ok if I merge now

**Pull request merged**
