### PR TITLE
source-campaign-monitor contribution from aazam-gh

### LINKED ISSUE #45970: [connector-request] Campaign Monitor
This is a **suggestion** to create a connector for **Campaign Monitor** using the UI Connector Builder.
The website for the connector is https://www.campaignmonitor.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

### PR DESCRIPTION
**Pull request by aazam-gh**
## What

This PR adds a new connector for source Campaign Monitor (source-campaign-monitor).

Contributor-provided connector description:

This is the setup guide for the Campaign Monitor source.

Campaign Monitor is an email marketing and services platform https://www.campaignmonitor.com/
This connector ingests a variety of endpoints from the Campaign Monitor API.
In order to use the API, you must first create an account. You can generate your API key in the account settings.
https://www.campaignmonitor.com/api/v3-3/getting-started/ 

## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `username` | `string` | Username.  |  |
| `password` | `string` | Password.  |  |
| `client_id` | `string` | Client ID. The specific ID of a client in your account |  |
| `start_date` | `string` | start_date. Date from when the sync should start |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| clients | ClientID | No pagination | ✅ |  ❌  |
| admins | EmailAddress | No pagination | ✅ |  ❌  |
| client_details |  | No pagination | ✅ |  ❌  |
| segments | SegmentID | No pagination | ✅ |  ❌  |
| templates | TemplateID | No pagination | ✅ |  ❌  |
| people | EmailAddress | No pagination | ✅ |  ❌  |
| tags | Name | No pagination | ✅ |  ❌  |
| subscriber_lists | ListID | No pagination | ✅ |  ❌  |
| suppression_lists | EmailAddress | DefaultPaginator | ✅ |  ❌  |
| sent_campaigns | CampaignID | DefaultPaginator | ✅ |  ✅  |
| draft_campaigns | CampaignID | No pagination | ✅ |  ❌  |
| scheduled_campaigns |  | No pagination | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by aazam-gh** [comment]
Journeys and Transactional endpoints are not available on the free plan.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Some comments.

**Comment by aazam-gh** [comment]
@marcosmarxm updated all streams to use parent clients stream

**Review by marcosmarxm — APPROVED** [review]
Awesome contribution

**Pull request merged**
