### PR TITLE
[ISSUE 9173] add ERD files for source-facebook-marketing

### PR DESCRIPTION
**Pull request by maxi297**
## What
Addresses https://github.com/airbytehq/airbyte-internal-issues/issues/9173 for source-facebook-marketing

## How
By running `airbyte-ci --name=source-facebook-marketing generate-erd`

The publish has been done as part of the airbyte-ci command executed locally.

Some relationships have been confirmed for this one for demo purposes.

## User Impact
ERD is now available on https://dbdocs.io/airbyteio/source-facebook-marketing

## Can this PR be safely reverted and rolled back?
- [X] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by maxi297** [comment]
@girarda do you see any value in having the discovered catalog used for the generation? It feels like this can be retrieved by doing a discover but it could help debugging (for example, to understand if a stream has been added since the last generation)

**Comment by maxi297** [comment]
Once we agree on the first PR, I'll automatically create the 9 others

**Comment by maxi297** [comment]
The effort is low. I'll format the files and merge it once I have your approval @girarda

**Review by girarda — APPROVED** [review]
the relations in source.dbml look reasonable, but I'm not able to access the ERDs from https://dbdocs.io/airbyteio/source-facebook-marketing

**Pull request merged**
