### PR TITLE
source-zonka-feedback contribution from aazam-gh

### LINKED ISSUE #47792: [connector-request] Zonka Feedback
### Topic

Connector Request

### Relevant information

Relevant information
This is a suggestion to create a connector for Zonka Feedback using the UI Connector Builder. The website for the connector is https://zonkafeedback.com/.

### PR DESCRIPTION
**Pull request by aazam-gh**
## What

This PR adds a new connector for source Zonka Feedback (source-zonka-feedback).

Contributor-provided connector description:

This is the Zonka Feedback source that ingests data from the Zonka API.

Zonka Feedback simplifies CX, allowing you to start meaningful two-way conversations with customers via powerful surveys. Design stunning surveys in minutes, gather data from all touchpoints, understand customers better with AI analytics &amp; close the feedback loop — all within one powerful platform https://www.zonkafeedback.com/

To use this source, you must first create an account. Once logged in, click on Settings -&gt; Developers -&gt; API &amp; Data Center. Note down your Data center and generate your auth token. 

For more information about the API visit https://apidocs.zonkafeedback.com/#intro
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `dc_id` | `string` | Data Center ID. The identifier for the data center, such as &#39;us1&#39; or &#39;e&#39; for EU. |  |
| `auth_token` | `string` | Auth Token. Auth token to use. Generate it by navigating to Company Settings &gt; Developers &gt; API in your Zonka Feedback account. |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| responses | id | No pagination | ✅ |  ❌  |
| workspaces | id | No pagination | ✅ |  ❌  |
| surveys | id | No pagination | ✅ |  ❌  |
| contacts | emailAddress | DefaultPaginator | ✅ |  ❌  |
| tasks | id | DefaultPaginator | ✅ |  ❌  |
| users | id | DefaultPaginator | ✅ |  ❌  |
| locations | id | No pagination | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by aazam-gh** [comment]
Fixes #47792

**Comment by marcosmarxm** [comment]
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

Make sure you have pagination properly working, the API doesn't have pagination please left a comment making my review easier.
Make sure have a square svg icon
Make sure credentials are valid.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Missing pagination and limit.
Endpoints are good.
Missing square svg icon.

Please make the changes asap.

**Comment by aazam-gh** [comment]
Changes have been addressed

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
