### PR TITLE
MySQL Source: Revert per stream logging changes

### LINKED ISSUE #25660: Connector Issue: MySQL connector raises SELECT command denied error in version 2.0.18/2.0.19 but not in 2.0.17
### Connector Name

airbyte/source-mysql

### Connector Version

2.0.18 and 2.0.19

### What step the error happened?

During the sync

### Revelant information

After upgrading the mysql connector version from 2.0.17 to 2.0.18, we encountered a `SELECT command denied` error. Upgrading to the latest version (2.0.19) did nothing, but when I downgrade the connector to version 2.0.17 it worked again. 

### Relevant log output

```shell
java.sql.SQLSyntaxErrorException: SELECT command denied to user 'USERNAME'@'IPADDRESS' for table 'TABLENAME'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
	at com.mysql.cj.jdbc.DatabaseMetaData$6.forEach(DatabaseMetaData.java:2745)
	at com.mysql.cj.jdbc.DatabaseMetaData$6.forEach(DatabaseMetaData.java:2732)
	at com.mysql.cj.jdbc.IterateBlock.doForAll(IterateBlock.java:56)
	at com.mysql.cj.jdbc.DatabaseMetaData.getIndexInfo(DatabaseMetaData.java:2802)
	at com.zaxxer.hikari.pool.ProxyDatabaseMetaData.getIndexInfo(ProxyDatabaseMetaData.java:207)
	at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getIndexInfo(HikariProxyDatabaseMetaData.java)
	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.logPreSyncDebugData(AbstractJdbcSource.java:451)
	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.logPreSyncDebugData(AbstractJdbcSource.java:86)
	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.read(AbstractDbSource.java:147)
	at io.airbyte.integrations.base.ssh.SshWrappedSource.read(SshWrappedSource.java:74)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:141)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:101)
	at io.airbyte.integrations.source.mysql.MySqlSource.main(MySqlSource.java:388)
```

### Contribute

- [ ] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by prateekmukhedkar**
## What
Closes https://github.com/airbytehq/airbyte/issues/25660
MySQL Source: Revert per stream logging changes by publishing a new version. The base class changes have already been done here https://github.com/airbytehq/airbyte/pull/25560/

### CODE REVIEW

**Comment by akashkulk** [comment]
This is a separate issue from the one I reverted/republished. Those changes did not apply to MySQL. I'm looking into this, but it's related to logging the indexes : https://github.com/airbytehq/airbyte/pull/25345

**Comment by akashkulk** [comment]
I've added a comment here : https://github.com/airbytehq/airbyte/issues/25660#issuecomment-1530189247
But the TLDR is that if the underlying table has been renamed/deleted/changed permissions. This logging would fail. 

In the actual sync, we end up silently skipping streams if we can't find them. We can take the same approach here.

**Comment by prateekmukhedkar** [comment]
@akashkulk I am seeing errors of this form and it is causing a dip in MySQL connector success reliability rate.
(below error from this [workspace](https://cloud.airbyte.com/workspaces/52cf2ac1-a23f-4498-963b-258fe288198b/connections/c2e44884-f618-499f-a5da-f40b043fe29b/job-history#2040597::2))

Can we revert back the `logPreSyncDebugData` and continue investigation?

```
2023-05-01 13:03:33 [44msource[0m > ERROR i.a.i.b.s.SshWrappedSource(read):76 Exception occurred while getting the delegate read iterator, closing SSH tunnel java.sql.SQLSyntaxErrorException: SELECT command denied to user 'airbyte'@'ec2-35-181-124-238.eu-west-3.compute.amazonaws.com' for table 'job_log'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.DatabaseMetaData$6.forEach(DatabaseMetaData.java:2745) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.DatabaseMetaData$6.forEach(DatabaseMetaData.java:2732) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.IterateBlock.doForAll(IterateBlock.java:56) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.DatabaseMetaData.getIndexInfo(DatabaseMetaData.java:2802) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.zaxxer.hikari.pool.ProxyDatabaseMetaData.getIndexInfo(ProxyDatabaseMetaData.java:207) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getIndexInfo(HikariProxyDatabaseMetaData.java) ~[HikariCP-5.0.1.jar:?]
	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.logPreSyncDebugData(AbstractJdbcSource.java:451) ~[io.airbyte.airbyte-integrations.connectors-source-jdbc-0.44.2.jar:?]
	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.logPreSyncDebugData(AbstractJdbcSource.java:86) ~[io.airbyte.airbyte-integrations.connectors-source-jdbc-0.44.2.jar:?]
	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.read(AbstractDbSource.java:147) ~[io.airbyte.airbyte-integrations.connectors-source-relational-db-0.44.2.jar:?]
	at io.airbyte.integrations.base.ssh.SshWrappedSource.read(SshWrappedSource.java:74) ~[io.airbyte.airbyte-integrations.bases-base-java-0.44.2.jar:?]
	at io.airbyte.integrations.base.spec_modification.SpecModifyingSource.read(SpecModifyingSource.java:49) ~[io.airbyte.airbyte-integrations.bases-base-java-0.44.2.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:141) ~[io.airbyte.airbyte-integrations.bases-base-java-0.44.2.jar:?]
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:101) ~[io.airbyte.airbyte-integrations.bases-base-java-0.44.2.jar:?]
	at io.airbyte.integrations.source.mysql_strict_encrypt.MySqlStrictEncryptSource.main(MySqlStrictEncryptSource.java:79) ~[io.airbyte.airbyte-integrations.connectors-source-mysql-strict-encrypt-0.44.2.jar:?]

```

**Comment by akashkulk** [comment]
Ok, in that case you will have to remove lines 448 onwards here : 
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-jdbc/src/main/java/io/airbyte/integrations/source/jdbc/AbstractJdbcSource.java#L448

and then republish Postgres/MsSQL/MySQL

**Comment by akashkulk** [comment]
I have https://github.com/airbytehq/airbyte/pull/25740 out to disable index logging altogether

**Comment by prateekmukhedkar** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/pull/25740

**Pull request closed without merging**
