### PR TITLE
✨ Source Surveymonkey: Stream `survey_responses` add field metadata.respondent.language

### PR DESCRIPTION
**Pull request by leo-schick**
## What
Sychronizing field `metadata.respondent.language` inside stream `survey_responses`

Example values returned from API request `https://api.surveymonkey.com/v3/surveys/{survey_id}/responses/{response_id}`

image

## How
Expanding the schema definitino for stream `survey_responses`

## 🚨 User Impact 🚨
Extension of schema fields, no breaking changes.

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@leo-schick please move from draft and let us know when this is ready to review! thanks for the contribution

**Comment by leo-schick** [comment]
Hello @marcosmarxm ,

I figured out that the response from Survey Monkey differs in the `metadata` section dependent on the request send to the API:
When you request a single response (GET `/surveys/{survey_id}/responses/{response_id}`), you get the metadata as shown above. The connector uses the bulk response (`GET /surveys/{id}/responses/bulk`), one does not get the metadata.

It is a pitty that the API from SurveyMonkey does not work equal here. When we would use the single response request, this would create a huge load on the API and many Airbyters would be required to book the enterprise plan which is quite expensive compared to the other plans. I am not sure how to get forward with this issue.

**Comment by sherifnada** [comment]
@leo-schick with [Destinations V2](https://github.com/airbytehq/airbyte/issues/26028) rolling out soon, nested schemas such as this one will become less relevant as they won't be expanded in the destination. Does this PR still make sense in that world?

**Comment by marcosmarxm** [comment]
@leo-schick is this ready to review?

**Comment by leo-schick** [comment]
@marcosmarxm Actually not. This needs architectual decision:

What I did in this PR is just extending the schema of the stream. But the used API endpoint currently does not delivere the data. It would be necessary to switch the endpoint (see above), what would result in many more API requests - which probably will break existing installations.

I had the idea that it could be part of the configuration which endpoint to use. Or alternatively to claim at SurveyMonkey that these API endpoints should work the same.

Nevertheless for myself I found an alternative solution and I do not require the extra configured metadata. This turned my priority away from this issue.

Maybe someone else could take up this issue when they have a need for it.

**Comment by marcosmarxm** [comment]
@leo-schick I'll close because I'm trying to clean the community contribution backlog. I'll move the discussion first to an issue.

**Pull request closed without merging**
