### PR TITLE
🐛 Source Zendesk support: add log message for 429 status code

### LINKED ISSUE #9052: 🐛  Source Zendesk support: getting stuck everytime in report ticket_metrics
## Environment
Is this your first time deploying Airbyte: No
*OS Version* / Instance: Ubuntu 20.04
*Machine type* e2-highmem-16 ( 2 CPU )
*Memory / Disk:* 16Gb / 100 GB ssd
*Deployment*: Docker
*Airbyte Version:* 0.34.4-alpha
*Source name/version:* airbyte/source-zendesk-support:0.1.10
*Destination name/version:* airbyte/destination-bigquery:0.5.1
*Description*: getting stuck everytime in report *ticket_metrics.*

 https://airbytehq.slack.com/archives/C01MFR03D5W/p1640120654180600?thread_ts=1640120654.180600&cid=C01MFR03D5W

### PR DESCRIPTION
**Pull request by annalvova05**
## What
Getting stuck everytime in report ticket_metrics.

## How
Add log message for 429 status code - how many seconds we should wait.

## Recommended reading order
1. `streams.py`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

### CODE REVIEW

**Review by grubberr — APPROVED** [review]

**Review by antixar — APPROVED** [review]

**Comment by antixar** [comment]
@annalvova05 , Please publish your changes

**Review by midavadim — APPROVED** [review]

**Pull request merged**
