### PR TITLE
🐛 Source MSSQL - Fix for invalid binary data

### LINKED ISSUE #19337: [Source-MSSQL] Invalid binary data
## Environment
- **Airbyte version**:  latest
- **OS Version / Instance**: ubuntu 20.04.1
- **Deployment**:  Docker
- **Source Connector and version**: Microsoft SQL Server (MSSQL) latest
- **Destination Connector and version**: Clickhouse latest
- **Step where error happened**: Converting binary data to string from source connector

## Current Behavior
image

That 's what mssql shows me

binary
And this is the received data already in clickhouse

clickhouse

As a result, I get the same string values _IDRRef, although they should be different

In general, I do not understand the translation of airbyte binary data into a string, if you use a regular hex editor, you should get these characters
image
But it turns out this line: ��\u0000PV�w�\u0011�}$e\u001A�

## Expected Behavior
The data in the _IDRRef column should be different

## Logs
[f2c30996_e3f4_464b_8dfb_fb642b7f10d9_logs_10_txt.txt](https://github.com/airbytehq/airbyte/files/9986476/f2c30996_e3f4_464b_8dfb_fb642b7f10d9_logs_10_txt.txt)

## Steps to Reproduce
1. Create a source connector for mssql tables with binary data
2. Set up transmission to any clickhouse location
3. Compare the data

## Are you willing to submit a PR?
No

## Decision.
Most likely the problem is the length of the binary used to convert to a string

### PR DESCRIPTION
**Pull request by NipunaPrashan**
## What
Fix #19337

Converting a binary value to a string is the issue here. This can bring invalid characters depending on the encoding method.
Therefore, we should put the value as it is to the json object. 

## How
Remove the override method.

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*
No.

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
All tests are passed.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

### CODE REVIEW

**Comment by sajarin** [comment]
Thanks for PR @NipunaPrashan since you're proposing deleting the putBinary function, could you explain how this fixes the issues with the mssql connector? Just want to understand and verify this is the correct approach. 

Can you also update the documentation files by bumping the versions? (Dockerfile, mssql.md, metadata.yaml, etc)

**Comment by rodireich** [comment]
The implementation that is taken out here was added in #7748

**Comment by NipunaPrashan** [comment]
Hi @sajarin @rodireich @marcosmarxm can any of  you explain why the mentioned code #7748 casting the binary value to a string. Why cannot we put the binary value as it is?

**Comment by rodireich** [comment]
Hi @NipunaPrashan 
I've reopened this PR.
I'm still gathering information trying to understand why this fix to `putBinary()` in the first place

**Comment by NipunaPrashan** [comment]
Thank you @rodireich.
I have done several debug sessions with several datasets. I was able to verify the mentioned invalid data issue when the binary value converted to a String value. You can simply add few data to mssql binary(32) column and use mssql connector to ingest data to any destination.

**Comment by NipunaPrashan** [comment]
`final String value = new String(bytes, Charset.defaultCharset());`

This is the culprit line. @rodireich if you put a debug log to print `value`, you can see the issue.

**Comment by NipunaPrashan** [comment]
No Progress with this yet? @rodireich

**Comment by prateekmukhedkar** [comment]
@NipunaPrashan thanks for the PR! We will be working on improved version of MS-SQL connector (timelines TBD) and during that time we will revisit how we are handling data types. Until that point we will not be able to accept this PR - thanks for your patience and contribution.

**Pull request closed without merging**
