### PR TITLE
Harvest: turn on default HttpAvailabilityStrategy

### LINKED ISSUE #21781: Source Harvest: Enable AvailabilityStrategy

### PR DESCRIPTION
**Pull request by grubberr**
This reverts commit 2f451f61cb91ea2631798ac1e04014df0e20cd3c.

## What
Issue: https://github.com/airbytehq/airbyte/issues/22254 https://github.com/airbytehq/airbyte/issues/21781
Turn on default HttpAvailabilityStrategy - it works ok for this connector

## How
*Describe the solution*

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Comment by grubberr** [comment]
2-nd attempt to merge this PR https://github.com/airbytehq/airbyte/pull/22417
@cgardens can you please look that all checks are passed and approve this PR if I can merge it to master?

**Comment by cgardens** [comment]
@grubberr you should work with whoever your normal code review is, please. from my POV, I'm just looking out that the build green.

**Comment by grubberr** [comment]
@cgardens can you please clarify do we need to check only Screenshot 2023-02-15 at 21 43 44
knobs to get permission from you to merge to master?

**Comment by grubberr** [comment]
@erohmensing can you please approve again
it's PR is duplicate of this https://github.com/airbytehq/airbyte/pull/22417 - which was reverted because I did not check CI tests

**Review by erohmensing — APPROVED** [review]
Manually bumping the definitions/specs could be hairy but since there is no publishing to be done here, makes sense. I've confirmed that this is the latest version in dockerhub

**Review by lazebnyi — APPROVED** [review]
All CI checks looks good! We can move next with this PR.

**Comment by octavia-approvington** [comment]
After a careful ML study, <br/> we think this looks okay.  <br/> imagine code being okay

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
