### PR TITLE
🐛 Source Amplitude: use `latest` CDK and fix `average session length` schema

### PR DESCRIPTION
**Pull request by bazarnov**
## What
Need to use the `latest` CDK version for `source-amplitude`  in order to pass the CAT.

## How
- edited `setup.py` (removed version dependency) 
- updated `average_session_length` stream schema, `length` property becomes `object` instead of `number` now
- updated `expected records` to align the changes

## 🚨 User Impact 🚨
This is the breaking change! For all customers, the `Average Session Length` stream should reset and re-sync the stream.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-amplitude test report (commit [`ca04b4dd87`](https://github.com/airbytehq/airbyte/pull/28913/commits/ca04b4dd87163322a00d7e5a8441507ea7f6032d)) - ❌

⏲️  Total pipeline duration: 26mn18s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amplitude/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-amplitude docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-amplitude-use-latest-cdk/1690894687/ca04b4dd87163322a00d7e5a8441507ea7f6032d/source-amplitude/0.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amplitude test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amplitude test report (commit [`ca04b4dd87`](https://github.com/airbytehq/airbyte/pull/28913/commits/ca04b4dd87163322a00d7e5a8441507ea7f6032d)) - ❌

⏲️  Total pipeline duration: 01mn47s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amplitude/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-amplitude docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-amplitude-use-latest-cdk/1690896418/ca04b4dd87163322a00d7e5a8441507ea7f6032d/source-amplitude/0.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amplitude test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amplitude test report (commit [`a542b94aa7`](https://github.com/airbytehq/airbyte/pull/28913/commits/a542b94aa7e20bc1204d5ebaf129b2ab444713a7)) - ❌

⏲️  Total pipeline duration: 02mn09s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amplitude/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ❌        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-amplitude docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-amplitude-use-latest-cdk/1690897008/a542b94aa7e20bc1204d5ebaf129b2ab444713a7/source-amplitude/0.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amplitude test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amplitude test report (commit [`102760cce2`](https://github.com/airbytehq/airbyte/pull/28913/commits/102760cce2a02b81c7a35ecfd4cc95aa0d00b35d)) - ❌

⏲️  Total pipeline duration: 23mn50s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amplitude/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-amplitude docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/baz_source-amplitude-use-latest-cdk/1690898008/102760cce2a02b81c7a35ecfd4cc95aa0d00b35d/source-amplitude/0.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amplitude test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amplitude test report (commit [`810c3fc02e`](https://github.com/airbytehq/airbyte/pull/28913/commits/810c3fc02e17780809bf4d65bf08801dfa681073)) - ✅

⏲️  Total pipeline duration: 40mn05s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amplitude/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-amplitude docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/baz_source-amplitude-use-latest-cdk/1690983765/810c3fc02e17780809bf4d65bf08801dfa681073/source-amplitude/0.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amplitude test
```

**Comment by bazarnov** [comment]
closing this  one in favor of: https://github.com/airbytehq/airbyte/pull/28942

**Pull request closed without merging**
