### PR TITLE
CI for #29200

### PR DESCRIPTION
**Pull request by sh4sh**
Checks for community pr #29200

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-braintree test report (commit [`720b65af70`](https://github.com/airbytehq/airbyte/pull/29519/commits/720b65af7039dc809970cf92307e264020ce7294)) - ❌

⏲️  Total pipeline duration: 01mn05s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-braintree/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ❌        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ❌        |
| Connector package install                                               | ✅        |
| Build source-braintree docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/braintree-no-code-connector/1692280386/720b65af7039dc809970cf92307e264020ce7294/source-braintree/0.1.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:720b65af7039dc809970cf92307e264020ce7294)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-braintree test
```

**Comment by octavia-squidington-iii** [comment]
##  source-braintree test report (commit [`b7f6994290`](https://github.com/airbytehq/airbyte/pull/29519/commits/b7f6994290d86b9d463d1e1b2b3bb0375bcbb5f0)) - ❌

⏲️  Total pipeline duration: 02mn01s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-braintree/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ❌        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ❌        |
| Connector package install                                               | ✅        |
| Build source-braintree docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/braintree-no-code-connector/1692287089/b7f6994290d86b9d463d1e1b2b3bb0375bcbb5f0/source-braintree/0.1.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b7f6994290d86b9d463d1e1b2b3bb0375bcbb5f0)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-braintree test
```

**Comment by octavia-squidington-iii** [comment]
##  source-braintree test report (commit [`6f0fd6e671`](https://github.com/airbytehq/airbyte/pull/29519/commits/6f0fd6e6713cacaf2b90e240ce7105cdd514eea0)) - ❌

⏲️  Total pipeline duration: 02mn35s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-braintree/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ❌        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-braintree docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/braintree-no-code-connector/1692288121/6f0fd6e6713cacaf2b90e240ce7105cdd514eea0/source-braintree/0.1.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6f0fd6e6713cacaf2b90e240ce7105cdd514eea0)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-braintree test
```

**Comment by octavia-squidington-iii** [comment]
##  source-braintree test report (commit [`6d51fd24c0`](https://github.com/airbytehq/airbyte/pull/29519/commits/6d51fd24c04d0262783f87bec3a89723de56ce02)) - ❌

⏲️  Total pipeline duration: 01mn18s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-braintree/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ❌        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-braintree docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/braintree-no-code-connector/1692288473/6d51fd24c04d0262783f87bec3a89723de56ce02/source-braintree/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6d51fd24c04d0262783f87bec3a89723de56ce02)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-braintree test
```

**Comment by octavia-squidington-iii** [comment]
##  source-braintree test report (commit [`8fd1c2bdd6`](https://github.com/airbytehq/airbyte/pull/29519/commits/8fd1c2bdd6e0f880d7c56932d66bb424f1f5cc4b)) - ✅

⏲️  Total pipeline duration: 01mn21s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-braintree/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-braintree docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/braintree-no-code-connector/1692290060/8fd1c2bdd6e0f880d7c56932d66bb424f1f5cc4b/source-braintree/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8fd1c2bdd6e0f880d7c56932d66bb424f1f5cc4b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-braintree test
```

**Comment by masyagin1998** [comment]
@sh4sh thank you for help with tests!!!

**Comment by sh4sh** [comment]
No prob @masyagin1998, thanks for the contribution 😁 almost over the finish line

**Comment by octavia-squidington-iii** [comment]
##  source-braintree test report (commit [`bf8f5be112`](https://github.com/airbytehq/airbyte/pull/29519/commits/bf8f5be11294d69efbc3365bd31488edbcc3488c)) - ✅

⏲️  Total pipeline duration: 01mn04s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-braintree/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-braintree docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/braintree-no-code-connector/1692291712/bf8f5be11294d69efbc3365bd31488edbcc3488c/source-braintree/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:bf8f5be11294d69efbc3365bd31488edbcc3488c)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-braintree test
```

**Pull request closed without merging**
