### PR TITLE
Source Amazon Ads: fix Nonetype error when recordId is missing

### PR DESCRIPTION
**Pull request by roman-yermilov-gl**
## What
- https://github.com/airbytehq/oncall/issues/2413

## How
*Bugfix: conditional expression was constructed wrong way*

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`73348b6d41`](https://github.com/airbytehq/airbyte/pull/28155/commits/73348b6d415f1dfc60d2821f057a6efdb8986b0f)) - ❌

⏲️  Total pipeline duration: 03mn26s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ryermilov_source-amazon-ads-fix-validation-error/1689093766/73348b6d415f1dfc60d2821f057a6efdb8986b0f/source-amazon-ads/2.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`f8aad94d2d`](https://github.com/airbytehq/airbyte/pull/28155/commits/f8aad94d2da193ef957d1093b1a0f6b5da489bd3)) - ✅

⏲️  Total pipeline duration: 02mn56s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ryermilov_source-amazon-ads-fix-validation-error/1689094420/f8aad94d2da193ef957d1093b1a0f6b5da489bd3/source-amazon-ads/2.3.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Review by erohmensing — COMMENTED** [review]
@roman-yermilov-gl thank you! is there a good way to unit test this change?

**Review by lazebnyi — APPROVED** [review]
LGTM! After adding unit test can be merged.

**Comment by roman-yermilov-gl** [comment]
> @roman-yermilov-gl thank you! is there a good way to unit test this change?

Made a refactoring and a unit test

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`d8eabbf51c`](https://github.com/airbytehq/airbyte/pull/28155/commits/d8eabbf51c74b5d747c50bf49391f43cb260d166)) - ✅

⏲️  Total pipeline duration: 03mn24s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ryermilov_source-amazon-ads-fix-validation-error/1689245737/d8eabbf51c74b5d747c50bf49391f43cb260d166/source-amazon-ads/2.3.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`d8eabbf51c`](https://github.com/airbytehq/airbyte/pull/28155/commits/d8eabbf51c74b5d747c50bf49391f43cb260d166)) - ✅

⏲️  Total pipeline duration: 03mn14s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ryermilov_source-amazon-ads-fix-validation-error/1689246119/d8eabbf51c74b5d747c50bf49391f43cb260d166/source-amazon-ads/2.3.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Pull request merged**
