### PR TITLE
🎉 New Destination: SQLite

### PR DESCRIPTION
**Pull request by yuhuishi-convect**
## What
Sqlite destination. Similarly to `local-csv` and `local-json`, it creates a single file under `/local/` mount, with each stream having its own table.

## How
Scaffolded by python destination template. 
The destination writes a configured catalog to a single file under the local mount, with each stream having its own table.

## Recommended reading order
1. `airbyte-integrations/connectors/destination-sqlite/destination_sqlite/destination.py`
2. `airbyte-integrations/connectors/destination-sqlite/integration_tests/integration_test.py`

## 🚨 User Impact 🚨
None. New destination will not impact existing functionalities.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

```
> Task :airbyte-integrations:bases:source-acceptance-test:installReqs UP-TO-DATE
> Task :airbyte-integrations:bases:source-acceptance-test:airbytePythonApply
> Task :airbyte-integrations:connectors:destination-sqlite:installLocalReqs UP-TO-DATE
> Task :airbyte-integrations:connectors:destination-sqlite:installReqs UP-TO-DATE
> Task :airbyte-integrations:connectors:destination-sqlite:installTestReqs UP-TO-DATE

> Task :airbyte-integrations:connectors:destination-sqlite:_unitTestCoverage
[python] .venv/bin/python -m coverage run --data-file=unit_tests/.coverage.unitTest --rcfile=/data/convect-dask-operator/yuhuishi-airbyte/airbyte/pyproject.toml -m pytest -s unit_tests -c /data/convect-dask-operator/yuhuishi-airbyte/airbyte/pyproject.toml
         ============================= test session starts ==============================
         platform linux -- Python 3.9.0, pytest-6.1.2, py-1.11.0, pluggy-0.13.1 -- /data/convect-dask-operator/yuhuishi-airbyte/airbyte/airbyte-integrations/connectors/destination-sqlite/.venv/bin/python
         cachedir: .pytest_cache
         rootdir: /data/convect-dask-operator/yuhuishi-airbyte/airbyte/airbyte-integrations/connectors/destination-sqlite/unit_tests, configfile: ../../../../pyproject.toml
         collecting ... collected 1 item
         
         unit_tests/unit_test.py::test_get_destination_path PASSED
         
         ============================== 1 passed in 0.22s ===============================

> Task :airbyte-integrations:connectors:destination-sqlite:unitTest
Name                                Stmts   Miss  Cover
-------------------------------------------------------
destination_sqlite/__init__.py          2      0   100%
destination_sqlite/destination.py      64     42    34%
-------------------------------------------------------
TOTAL                                  66     42    36%

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 7s
33 actionable tasks: 15 executed, 18 up-to-date
```

</details>

<details><summary><strong>Integration</strong></summary>

```
> Task :airbyte-integrations:bases:source-acceptance-test:installReqs UP-TO-DATE
> Task :airbyte-integrations:bases:source-acceptance-test:airbytePythonApply
> Task :airbyte-integrations:connectors:destination-sqlite:installLocalReqs UP-TO-DATE
> Task :airbyte-integrations:connectors:destination-sqlite:installReqs UP-TO-DATE
> Task :airbyte-integrations:connectors:destination-sqlite:installTestReqs UP-TO-DATE

> Task :airbyte-integrations:connectors:destination-sqlite:_customIntegrationTestsCoverage
[python] .venv/bin/python -m coverage run --data-file=integration_tests/.coverage.customIntegrationTests --rcfile=/data/convect-dask-operator/yuhuishi-airbyte/airbyte/pyproject.toml -m pytest -s integration_tests -c /data/convect-dask-operator/yuhuishi-airbyte/airbyte/pyproject.toml
         ============================= test session starts ==============================
         platform linux -- Python 3.9.0, pytest-6.1.2, py-1.11.0, pluggy-0.13.1 -- /data/convect-dask-operator/yuhuishi-airbyte/airbyte/airbyte-integrations/connectors/destination-sqlite/.venv/bin/python
         cachedir: .pytest_cache
         rootdir: /data/convect-dask-operator/yuhuishi-airbyte/airbyte/airbyte-integrations/connectors/destination-sqlite/integration_tests, configfile: ../../../../pyproject.toml
         collecting ... collected 3 items
         
         integration_tests/integration_test.py::test_check_fails[invalid_config] PASSED
         integration_tests/integration_test.py::test_check_succeeds[local_file_config] PASSED
         integration_tests/integration_test.py::test_write[local_file_config] PASSED
         
         =============================== warnings summary ===============================
         integration_tests/integration_test.py:94
           /data/convect-dask-operator/yuhuishi-airbyte/airbyte/airbyte-integrations/connectors/destination-sqlite/integration_tests/integration_test.py:94: PytestUnknownMarkWarning: Unknown pytest.mark.disable_autouse - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
             @pytest.mark.disable_autouse
         
         -- Docs: https://docs.pytest.org/en/stable/warnings.html
         ========================= 3 passed, 1 warning in 0.26s =========================

> Task :airbyte-integrations:connectors:destination-sqlite:customIntegrationTests
Name                                Stmts   Miss  Cover
-------------------------------------------------------
destination_sqlite/__init__.py          2      0   100%
destination_sqlite/destination.py      64     11    83%
-------------------------------------------------------
TOTAL                                  66     11    83%

> Task :airbyte-integrations:connectors:destination-sqlite:integrationTest

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 8s
33 actionable tasks: 15 executed, 18 up-to-date
```

</details>

<details><summary><strong>Acceptance</strong></summary>

Now sure how to do it with destination connectors

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hello @yuhuishi-convect this is a destination implementation and not a source, correct?

**Comment by yuhuishi-convect** [comment]
@marcosmarxm  Yes you are right. Made a silly mistake.

**Comment by marcosmarxm** [comment]
@yuhuishi-convect are you able to build the connector and use locally?

**Comment by yuhuishi-convect** [comment]
> @yuhuishi-convect are you able to build the connector and use locally?

Yes, I was able to use it from the cli, but haven't tested from UI.
Here is what I was doing

```sh

cd airbyte-integrations/connectors/destination-sqlite

docker build . -t airbyte/destination-sqlite:dev

mkdir temp

cat integration_tests/messages.jsonl |  docker run --rm -i  -v $(pwd)/temp/:/local/     -v    $(pwd)/integration_tests:/integration_tests airbyte/destination-sqlite:dev write  --config /integration_tests/config.json --catalog /integration_tests/configured_catalog.json

sqlite3 temp/sqlite.db



sqlite> select * from _airbyte_raw_airbyte_acceptance_table 
   ...> ;
fc291e96-3f67-4d43-83cb-0266d666615f|2022-08-08T20:50:57.152193|{"column1": "my_value", "column2": 221, "column3": "2021-01-01T20:10:22", "column4": 1.214, "column5": [1, 2, 3]}
358cfe80-1a1f-4f77-bf16-be5eb52d6b8c|2022-08-08T20:50:57.152278|{"column1": "my_value2", "column2": 222, "column3": "2021-01-02T22:10:22", "column5": [1, 2, null]}

```

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
