### PR TITLE
🐛 Source Stripe: Fix missing `start_date` argument + update json files for SAT

### LINKED ISSUE #6749: Source Stripe: type error missing start_date argument
## Enviroment
- **Airbyte version**:  0.30.10-alpha
- **OS Version / Instance**:  AWS EC2
- **Deployment**: Docker 
- **Source Connector and version**: Stripe 0.1.19
- **Destination Connector and version**: Redshift 0.3.14
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
Error on 4 objects: bank accounts, customer balance transactions, invoice line items, subscription items
Error message "TypeError: __init__() missing 1 required positional argument: 'start_date'"

## Expected Behavior
Success sync

## Logs
[logs-164-0.txt](https://github.com/airbytehq/airbyte/files/7282355/logs-164-0.txt)

## Investigation
This PR might have a bug on start_date https://github.com/airbytehq/airbyte/pull/6466
Reverting back to 0.1.18 solves this error

### PR DESCRIPTION
**Pull request by Zirochkaa**
## What
Closes #6749.

## Pre-merge Checklist
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated 
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [x] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

### CODE REVIEW

**Review by htrueman — APPROVED** [review]
LGTM. A few small suggestions added

**Review by sherifnada — APPROVED** [review]

**Pull request merged**
