### PR TITLE
🤖 Cloud Availability updater: new connectors to deploy [20230621]

### PR DESCRIPTION
**Pull request by octavia-squidington-iii**
The Cloud Availability Updater decided that it's the right time to make the following 5 connectors available on Cloud!

# Promoted connectors
|connector_technical_name|connector_version|      connector_definition_id       |
|------------------------|-----------------|------------------------------------|
|source-appfollow        |0.1.1            |b4375641-e270-41d3-9c20-4f9cecad87a8|
|source-coingecko-coins  |0.1.0            |9cdd4183-d0ba-40c3-aad3-6f46d4103974|
|destination-amazon-sqs  |0.1.0            |0eeee7fb-518f-4045-bacc-9619e31c43ea|
|destination-timeplus    |0.1.0            |f70a8ece-351e-4790-b37b-cb790bcd6d54|
|destination-xata        |0.1.0            |2a51c92d-0fb4-4e54-94d2-cce631f24d1f|

# Excluded but eligible connectors
|connector_technical_name|connector_version|connector_definition_id|
|------------------------|-----------------|-----------------------|

 ☝️ These eligible connectors are already in the definitions masks. They might have been explicitly pinned or excluded. We're not adding these for safety.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-appfollow test report (commit [`d45d80da44`](https://github.com/airbytehq/airbyte/pull/27542/commits/d45d80da4437236a22440ad3b92438adf49be91b)) - ❌

⏲️  Total pipeline duration: 41 seconds

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-appfollow/metadata.yaml | ✅        |
| Connector version semver check.                                         | ✅        |
| QA checks                                                               | ❌        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5330731478)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-appfollow test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-timeplus test report (commit [`d45d80da44`](https://github.com/airbytehq/airbyte/pull/27542/commits/d45d80da4437236a22440ad3b92438adf49be91b)) - ❌

⏲️  Total pipeline duration: 78 seconds

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-timeplus/metadata.yaml | ✅        |
| Connector version semver check.                                             | ✅        |
| Connector version increment check.                                          | ❌        |
| QA checks                                                                   | ❌        |
| Code format checks                                                          | ❌        |
| Connector package install                                                   | ✅        |
| Build destination-timeplus docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Integration tests                                                           | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5330731478)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-timeplus test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-amazon-sqs test report (commit [`d45d80da44`](https://github.com/airbytehq/airbyte/pull/27542/commits/d45d80da4437236a22440ad3b92438adf49be91b)) - ❌

⏲️  Total pipeline duration: 84 seconds

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-amazon-sqs/metadata.yaml | ✅        |
| Connector version semver check.                                               | ✅        |
| Connector version increment check.                                            | ❌        |
| QA checks                                                                     | ❌        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build destination-amazon-sqs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ✅        |
| Integration tests                                                             | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5330731478)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-amazon-sqs test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-xata test report (commit [`d45d80da44`](https://github.com/airbytehq/airbyte/pull/27542/commits/d45d80da4437236a22440ad3b92438adf49be91b)) - ❌

⏲️  Total pipeline duration: 86 seconds

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-xata/metadata.yaml | ✅        |
| Connector version semver check.                                         | ✅        |
| QA checks                                                               | ❌        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build destination-xata docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Integration tests                                                       | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5330731478)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-xata test
```

**Comment by octavia-squidington-iii** [comment]
##  source-coingecko-coins test report (commit [`d45d80da44`](https://github.com/airbytehq/airbyte/pull/27542/commits/d45d80da4437236a22440ad3b92438adf49be91b)) - ✅

⏲️  Total pipeline duration: 87 seconds

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5330731478)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-coingecko-coins test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-timeplus test report (commit [`0dcedea081`](https://github.com/airbytehq/airbyte/pull/27542/commits/0dcedea081ba65e456c52b57e5f590793993de94)) - ❌

⏲️  Total pipeline duration: 51 seconds

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-timeplus/metadata.yaml | ✅        |
| Connector version semver check.                                             | ✅        |
| Connector version increment check.                                          | ❌        |
| QA checks                                                                   | ❌        |
| Code format checks                                                          | ❌        |
| Connector package install                                                   | ✅        |
| Build destination-timeplus docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Integration tests                                                           | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5331273586)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-timeplus test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-amazon-sqs test report (commit [`0dcedea081`](https://github.com/airbytehq/airbyte/pull/27542/commits/0dcedea081ba65e456c52b57e5f590793993de94)) - ❌

⏲️  Total pipeline duration: 53 seconds

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-amazon-sqs/metadata.yaml | ✅        |
| Connector version semver check.                                               | ✅        |
| Connector version increment check.                                            | ❌        |
| QA checks                                                                     | ❌        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build destination-amazon-sqs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ✅        |
| Integration tests                                                             | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5331273586)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-amazon-sqs test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-xata test report (commit [`0dcedea081`](https://github.com/airbytehq/airbyte/pull/27542/commits/0dcedea081ba65e456c52b57e5f590793993de94)) - ❌

⏲️  Total pipeline duration: 61 seconds

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-xata/metadata.yaml | ✅        |
| Connector version semver check.                                         | ✅        |
| QA checks                                                               | ❌        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build destination-xata docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Integration tests                                                       | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5331273586)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-xata test
```

**Comment by octavia-squidington-iii** [comment]
##  source-coingecko-coins test report (commit [`0dcedea081`](https://github.com/airbytehq/airbyte/pull/27542/commits/0dcedea081ba65e456c52b57e5f590793993de94)) - ❌

⏲️  Total pipeline duration: 64 seconds

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-coingecko-coins/metadata.yaml | ✅        |
| Connector version semver check.                                               | ✅        |
| QA checks                                                                     | ❌        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build source-coingecko-coins docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                              | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5331273586)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-coingecko-coins test
```

**Comment by octavia-squidington-iii** [comment]
##  source-appfollow test report (commit [`0dcedea081`](https://github.com/airbytehq/airbyte/pull/27542/commits/0dcedea081ba65e456c52b57e5f590793993de94)) - ❌

⏲️  Total pipeline duration: 93 seconds

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-appfollow/metadata.yaml | ✅        |
| Connector version semver check.                                         | ✅        |
| QA checks                                                               | ❌        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-appfollow docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5331273586)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-appfollow test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-xata test report (commit [`f940f31290`](https://github.com/airbytehq/airbyte/pull/27542/commits/f940f31290ce3c42eb8db8ed7b10fe6a640e32da)) - ✅

⏲️  Total pipeline duration: 44 seconds

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-xata/metadata.yaml | ✅        |
| Connector version semver check.                                         | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build destination-xata docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Integration tests                                                       | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5331364443)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-xata test
```

**Comment by octavia-squidington-iii** [comment]
##  source-coingecko-coins test report (commit [`f940f31290`](https://github.com/airbytehq/airbyte/pull/27542/commits/f940f31290ce3c42eb8db8ed7b10fe6a640e32da)) - ❌

⏲️  Total pipeline duration: 50 seconds

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-coingecko-coins/metadata.yaml | ✅        |
| Connector version semver check.                                               | ✅        |
| QA checks                                                                     | ❌        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build source-coingecko-coins docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                              | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5331364443)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-coingecko-coins test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-amazon-sqs test report (commit [`f940f31290`](https://github.com/airbytehq/airbyte/pull/27542/commits/f940f31290ce3c42eb8db8ed7b10fe6a640e32da)) - ❌

⏲️  Total pipeline duration: 58 seconds

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-amazon-sqs/metadata.yaml | ✅        |
| Connector version semver check.                                               | ✅        |
| Connector version increment check.                                            | ❌        |
| QA checks                                                                     | ✅        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build destination-amazon-sqs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ✅        |
| Integration tests                                                             | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5331364443)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-amazon-sqs test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-timeplus test report (commit [`f940f31290`](https://github.com/airbytehq/airbyte/pull/27542/commits/f940f31290ce3c42eb8db8ed7b10fe6a640e32da)) - ❌

⏲️  Total pipeline duration: 61 seconds

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-timeplus/metadata.yaml | ✅        |
| Connector version semver check.                                             | ✅        |
| Connector version increment check.                                          | ❌        |
| QA checks                                                                   | ✅        |
| Code format checks                                                          | ❌        |
| Connector package install                                                   | ✅        |
| Build destination-timeplus docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Integration tests                                                           | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5331364443)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-timeplus test
```

**Comment by octavia-squidington-iii** [comment]
##  source-appfollow test report (commit [`f940f31290`](https://github.com/airbytehq/airbyte/pull/27542/commits/f940f31290ce3c42eb8db8ed7b10fe6a640e32da)) - ✅

⏲️  Total pipeline duration: 79 seconds

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-appfollow/metadata.yaml | ✅        |
| Connector version semver check.                                         | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-appfollow docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5331364443)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-appfollow test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-timeplus test report (commit [`deb02c178c`](https://github.com/airbytehq/airbyte/pull/27542/commits/deb02c178c6a163fd31fd9aebe6b2a8576e9d280)) - ❌

⏲️  Total pipeline duration: 31 seconds

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-timeplus/metadata.yaml | ✅        |
| Connector version semver check.                                             | ✅        |
| Connector version increment check.                                          | ❌        |
| QA checks                                                                   | ✅        |
| Code format checks                                                          | ❌        |
| Connector package install                                                   | ✅        |
| Build destination-timeplus docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Integration tests                                                           | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5331618478)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-timeplus test
```

**Comment by octavia-squidington-iii** [comment]
##  source-coingecko-coins test report (commit [`deb02c178c`](https://github.com/airbytehq/airbyte/pull/27542/commits/deb02c178c6a163fd31fd9aebe6b2a8576e9d280)) - ❌

⏲️  Total pipeline duration: 49 seconds

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-coingecko-coins/metadata.yaml | ✅        |
| Connector version semver check.                                               | ✅        |
| QA checks                                                                     | ❌        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build source-coingecko-coins docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                              | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5331618478)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-coingecko-coins test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-amazon-sqs test report (commit [`deb02c178c`](https://github.com/airbytehq/airbyte/pull/27542/commits/deb02c178c6a163fd31fd9aebe6b2a8576e9d280)) - ❌

⏲️  Total pipeline duration: 57 seconds

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-amazon-sqs/metadata.yaml | ✅        |
| Connector version semver check.                                               | ✅        |
| Connector version increment check.                                            | ❌        |
| QA checks                                                                     | ✅        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build destination-amazon-sqs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ✅        |
| Integration tests                                                             | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5331618478)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-amazon-sqs test
```

**Comment by octavia-squidington-iii** [comment]
##  source-appfollow test report (commit [`deb02c178c`](https://github.com/airbytehq/airbyte/pull/27542/commits/deb02c178c6a163fd31fd9aebe6b2a8576e9d280)) - ✅

⏲️  Total pipeline duration: 76 seconds

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-appfollow/metadata.yaml | ✅        |
| Connector version semver check.                                         | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-appfollow docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5331618478)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-appfollow test
```

**Review by alafanechere — APPROVED** [review]
Discarding coingecko as CAT are not passing, and SQS as we explicitely disabled it on Cloud

**Pull request merged**
