### PR TITLE
🎉  source Salesloft: added several new streams

### PR DESCRIPTION
**Pull request by yannibenoit**
## What

> Issue: https://github.com/airbytehq/airbyte/issues/11198
> Community Slack Message: https://airbytehq.slack.com/archives/C01VDDEGL7M/p1647435938137639

New sources added for Salesloft integration -> 

- [account_stages](https://developers.salesloft.com/api.html#!/Account_Stages/get_v2_account_stages_json)
- [account_tiers](https://developers.salesloft.com/api.html#!/Account_Tiers/get_v2_account_tiers_json)
- [accounts](https://developers.salesloft.com/api.html#!/Accounts/get_v2_accounts_json)
- [actions](https://developers.salesloft.com/api.html#!/Actions/get_v2_actions_json)
- [calls](https://developers.salesloft.com/api.html#!/Calls/get_v2_activities_calls_json)
- [emails_templates](https://developers.salesloft.com/api.html#!/Email_Templates/get_v2_email_templates_json)
- [imports](https://developers.salesloft.com/api.html#!/Imports/get_v2_imports_json)
- [notes](https://developers.salesloft.com/api.html#!/Notes/get_v2_notes_json)
- [person_stages](https://developers.salesloft.com/api.html#!/Person_Stages/get_v2_person_stages_json)
- [phone_number_assignments](https://developers.salesloft.com/api.html#!/Phone_Number_Assignments/get_v2_phone_number_assignments_json)
- [steps](https://developers.salesloft.com/api.html#!/Steps/get_v2_steps_json)
- [team_templates](https://developers.salesloft.com/api.html#!/Team_Templates/get_v2_team_templates_json)
- [crm_activities](https://developers.salesloft.com/api.html#!/CRM_Activities/get_v2_crm_activities_json)
- [crm_users](https://developers.salesloft.com/api.html#!/Crm_Users/get_v2_crm_users_json)
- [groups](https://developers.salesloft.com/api.html#!/Groups/get_v2_groups_json)
- [email_templates_attachments](https://developers.salesloft.com/api.html#!/Email_Template_Attachments/get_v2_email_template_attachments_json)
- [team_templates_attachments](https://developers.salesloft.com/api.html#!/Team_Template_Attachments/get_v2_team_template_attachments_json)
- [successes](https://developers.salesloft.com/api.html#!/Successes/get_v2_successes_json)

image

## How

For each new stream :
- Added new schema *.json for this new endpoint
- Added new `IncrementalSalesloftStream` or `SalesloftStream` class 
- Edited `streams` method in `SourceSalesloft` class to add new class in return
- Edited `test_source.py` to allow one more stream when unit testing

## Recommended reading order

1. `emails.json`
2.  `account_stages.json`
3. `account_tiers.json`
4. `accounts.json`
5. `actions.json`
6. `calls.json`
7. `email_templates.json`
8. `import.json`
9. `notes.json`
10. `person_stages.json`
11. `phone_number_assignments.json`
12. `steps.json`
13. `team_templates.json`
14. `groups.json`
15. `crm_activities.json`
16. `crm_users.json`
17. `email_template_attachments.json`
18. `team_template_attachments.json`
19. `successes.json`
20. `source.py`
21.  `test_source.py`

## 🚨 User Impact 🚨

New streams will be available in connector settings

image

New tables will be available in destination

**
image
**

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@yannibenoit ping me when this is ready to review.

**Comment by yannibenoit** [comment]
Warning: there are some API Limits errors but sync went well :)

```
2022-04-11 12:09:52 source > Caught retryable error 'Request URL: https://api.salesloft.com/v2/crm_activities?per_page=100&page=947, Response Code: 429, Response Text: {"error":"API rate limit exceeded"}
```

**Comment by yannibenoit** [comment]
Needed to edit next_page_token method to check if paging key was available in response metadata because that cause the sync stream error below

```
2022-04-11 12:38:19 source > Encountered an exception while reading stream groups
Traceback (most recent call last):
  File "/airbyte/integration_code/source_salesloft/source.py", line 33, in next_page_token
    next_page = response.json()["metadata"]["paging"].get("next_page")
KeyError: 'paging'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 119, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 159, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 248, in _read_full_refresh
    for record in records:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 376, in read_records
    next_page_token = self.next_page_token(response)
  File "/airbyte/integration_code/source_salesloft/source.py", line 36, in next_page_token
    raise KeyError(f"error parsing next_page token: {e}")
KeyError: "error parsing next_page token: 'paging'"
```

**Comment by alafanechere** [comment]
/publish connector=connectors/source-salesloft auto-bump-version=false

**Comment by alafanechere** [comment]
Thank you @yannibenoit for this big improvement!

**Pull request merged**
