### PR TITLE
chore: Removes .dockerignore and requirements.txt in connectors

### PR DESCRIPTION
**Pull request by natikgadzhi**
## What
I noticed we leave `.dockerignore` and `requirements.txt` files in connectors that  no longer use them, so thought I'd clean them up while I had a minute. 

## How

```py
# tools/find-requirements.py
import pathlib

connectors_path = pathlib.Path(__file__).parent / "../airbyte-integrations/connectors"
num_nuked_requirements = 0
num_nuked_docker_ignore = 0

for connector in connectors_path.iterdir():
    connector = connector.resolve()
    if connector.is_dir():
        print("Scanning connector:", connector)

        setup_py = connector / "setup.py"

        if not setup_py.exists():
            requirements_txt = connector / "requirements.txt"
            if requirements_txt.exists():
                print("  => No setup.py, but requirements.txt exists:", requirements_txt)
                requirements_txt.unlink()
                num_nuked_requirements += 1
                print("  => requirements.txt removed")

        dockerfile = connector / "Dockerfile"
        if not dockerfile.exists():
            docker_ignore_file = connector / ".dockerignore"
            if docker_ignore_file.exists():
                print("  => No Dockerfile, but .dockerignore exists:", docker_ignore_file)
                docker_ignore_file.unlink()
                num_nuked_docker_ignore += 1
                print("  => .dockerignore removed")

```

## User Impact
None

## Can this PR be safely reverted and rolled back?
- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by alafanechere — COMMENTED** [review]
@natikgadzhi did you only remove them for connectors using poetry / python base image?

**Comment by natikgadzhi** [comment]
@alafanechere No and yes. I removed .dockerignore only where there is no dockerfile, and requirements.txt only where there is no setup.py. 

Hypothetically this is very close or the same, but I did not perform actual metadata lookup. I _think_ this is fine.

**Comment by natikgadzhi** [comment]
@girarda can you give me a BS check here too?

**Review by girarda — APPROVED** [review]
:shipit: 

should we also update the migration airbyte-ci commands?

**Comment by natikgadzhi** [comment]
@girarda I don't think there's enough connectors left to care — only 15 migrations to go. And we've asked @btkcodedev and @pabloescoder to remove .dockerignores and requirement files. 

It's actually their PRs where I noticed that they're removing them and our scripts don't ;)

**Pull request merged**
