### PR TITLE
Replace DeleteModal with Confirmation Modal

### PR DESCRIPTION
**Pull request by edmundito**
## What / How
This replaces the Delete Modal component with the Confirmation Modal component as they both do the exact same thing. It also ensures that when delete is confirmed it navigates away from the page and to connection / source / destination list page.

## Recommended reading order
Start with `DeleteBlock`, then read from top to bottom.

### CODE REVIEW

**Comment by tealjulia** [comment]
Awesome!  I think this resolves [this issue](https://github.com/airbytehq/airbyte/issues/12250) I put in yesterday.  Was there an existing issue for this part of the deletion workflow that I didn't see?

**Comment by timroes** [comment]
A general note: I think `data-id` should be `data-testid` in all places. It seems we're not specifically using `data-id` for any logic, but just to later find that element better (in testing?), in which case we should try to stick to `data-testid`, which is the name of the parameter that [testing-library](https://testing-library.com/docs/queries/bytestid) as well as [cypress](https://docs.cypress.io/guides/core-concepts/test-runner#Uniqueness) are expecting.

**Comment by edmundito** [comment]
@timroes there are a few places where `data-id` is being used, I was adding support to what was already there. I'd like to spin this off into its own issue to do a full cleanup instead.

**Comment by edmundito** [comment]
@tealjulia What I did is very basic and I think it does deserve more work separately such as adding a notification. At least for now it will band-aid the confusion that even though it was deleted, the page is still there.

**Review by teallarson — APPROVED** [review]

**Pull request merged**
