### PR TITLE
Source GitLab: Accept api_url with or without scheme

### LINKED ISSUE #21143: Source Gitlab: Explicitly state `api_url` accepts URL without scheme (`http` or `https`)
`api_url` of source gitlab only accepts URL without scheme (`http` or `https`) which is not clearly stated. 

For example, if my gitlab instance is `https://gitlab.myorganization.com`, the `api_url` must be `gitlab.myorganization.com`, NOT `https://gitlab.myorganization.com`.

I figured out this hard way. Since I was trying to configure gitlab source with self-managed instance, I was under impression that gitlab connector not able to reach my self manages gitlab instance behind vpn, though I'm on VPN (I'm running locally)

I was getting below error when I use `api_url` with HTTPS:
```
Caught retryable error 'HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: 
/gitlab.xxxxxx.com/api/v4/groups?per_page=50
(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff8df3a880>: 
Failed to establish a new connection: [Errno -2] Name or service not known'))' after 4 tries. 
Waiting 40 seconds then retrying...
```

I believe update is required at both [`spec.json`](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-gitlab/source_gitlab/spec.json) and [docs page](https://docs.airbyte.com/integrations/sources/gitlab#step-2-set-up-the-gitlab-connector-in-airbyte)

### PR DESCRIPTION
**Pull request by pgollangi**
Make source-gitlab to accept `api_url`s with or without scheme, also accepts the URL with API endpoint included init. Currently gitlab source ONLY accept urls without scheme.

Also fixed issues with running unit tests (missing dependency) see #21372

Fixes #21143 and #21372

## User Impact 

This change will not break any of the existing GitLab configuration, but starts accepting gitlab urls without HTTP or HTTPs schemes.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

```

airbyte-integrations/connectors/source-gitlab/unit_tests/test_source.py::test_streams[gitlab.com]
airbyte-integrations/connectors/source-gitlab/unit_tests/test_source.py::test_streams[https://gitlab.com]
airbyte-integrations/connectors/source-gitlab/unit_tests/test_source.py::test_streams[https://gitlab.com/api/v4]
airbyte-integrations/connectors/source-gitlab/unit_tests/test_source.py::test_connection_success[gitlab.com]
airbyte-integrations/connectors/source-gitlab/unit_tests/test_source.py::test_connection_success[https://gitlab.com]
airbyte-integrations/connectors/source-gitlab/unit_tests/test_source.py::test_connection_success[https://gitlab.com/api/v4]
airbyte-integrations/connectors/source-gitlab/unit_tests/test_source.py::test_connection_fail[gitlab.com]
airbyte-integrations/connectors/source-gitlab/unit_tests/test_source.py::test_connection_fail[https://gitlab.com]
airbyte-integrations/connectors/source-gitlab/unit_tests/test_source.py::test_connection_fail[https://gitlab.com/api/v4]
  /Users/p.gollangi/dev/pgollangi-github/airbyte/airbyte-integrations/connectors/source-gitlab/source_gitlab/source.py:70: DeprecationWarning: Call to deprecated class TokenAuthenticator. (Use airbyte_cdk.sources.streams.http.requests_native_auth.TokenAuthenticator instead) -- Deprecated since version 0.1.20.
    auth = TokenAuthenticator(token=config["private_token"])

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================================================================================= 20 passed, 198 warnings in 0.35s =======================================================================================
```

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by pgollangi** [comment]
@yevhenii-ldv @ykurochkin @juweins could you please take a look at this? related to #21143 and #21372

**Review by juweins — COMMENTED** [review]
LGTM

**Review by juweins — APPROVED** [review]
Took some time for me to come back to this issue! Your adjustments LGTM and are reasonable. Thank you @pgollangi

**Comment by pgollangi** [comment]
@juweins thanks for the review. I see my pipelines are failing, thus merge is blocked. Any clue on this? https://github.com/airbytehq/airbyte/actions/runs/4017449728/jobs/6901816873

**Review by archangelic — APPROVED** [review]

**Comment by pgollangi** [comment]
@archangelic would you mind approve again. Github tests were failing on my branch. Latest changes from main merged to my feature branch.

**Review by marcosmarxm — APPROVED** [review]

**Review by archangelic — APPROVED** [review]

**Pull request merged**
