### PR TITLE
🐛 Source Bing Ads - Fix Missing Dimensional Columns For Reports

### LINKED ISSUE #23867: Source Bing Ads: add missing dimensional columns in reports
## Environment
- **Source Connector and version**: Bing Ads `0.1.18` (latest as of today)
- **Step where error happened**: After sync job (which is successful), when data modelling for report

## Current Behavior
Today there are two types of streams:
- dimensional-like ones (like `campaigns`, `accounts`, `ad_groups`...)
- fact-like ones (reports like `campaign_performance_report_daily`, `account_performance_report_daily`, `ad_group_performance_report_daily`,...)

To create a reporting, you would usually JOIN fact tables with dimensional one to have metrics split by dimensional columns (ex: conversion by CampaignType, CampaignName...).

However, dimensional tables do not contain data for DELETED items; so when in a report you're trying to get past data about a DELETED campaign (or ad_group or ad...) then you can't retrieve basic information like the Name or the Type of the item. The JOIN returns a NULL for deleted items and it defeats most analysis that you would do on this kind of data, like YoY performance by CampaignType for instance.

## Expected Behavior
You should be able to retrieve basic dimensional columns for reports, including for DELETED items.

## Additional Information
As it's not possible to retrieve DELETED items from dimensional tables and Bing Ads offer the possibility to add some dimensional columns to reports tables (like mentioned [here](https://learn.microsoft.com/en-us/advertising/reporting-service/campaignperformancereportcolumn?view=bingads-13#values) for CampaignReport but also available for AccountReport, AdReport...), then add them.

## Steps to Reproduce
1. Create a campaign, run it for some days, then delete it
2. Sync `campaigns` and `campaign_performance_report_daily`
3. When looking at this specific campaign, you only find its `CampaignId` in `campaign_performance_report_daily` so you join with `campaigns` to get basic info like CampaignName
4. When joining, you get NULL, and when looking for this CampaignId in `campaigns` it does not exist. It's because dimensional stream `campaigns` can't retrieve DELETED items

## Are you willing to submit a PR?
Yes, joining link very soon!

### PR DESCRIPTION
**Pull request by rach-r**
## What
Adding dimensional columns in `reports` that can't fully be retrieved in other streams; allowing users to make analysis on deleted items (and trend comparison over time).

Closes #23867. 

## How
Adding basic dimensional columns in report streams, as API and documentation allows it (example: [here](https://learn.microsoft.com/en-us/advertising/reporting-service/campaignperformancereportcolumn?view=bingads-13#values) is the list of available columns to retrieve for CampaignsPerformanceReport).

## Pre-merge Checklist

<summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
(https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

## Tests

<summary><strong>Unit</strong></summary>

image

### CODE REVIEW

**Comment by sajarin** [comment]
Hey @rach-r, this looks good thanks for the contribution! 

Could you bump the dockerfile? Also I understand that there are more missing dimensional columns that could be potentially added in a future PR. Is there something unique or compelling about the missing dimensional columns you've added here?

**Comment by rach-r** [comment]
> Hey @rach-r, this looks good thanks for the contribution!
> 
> Could you bump the dockerfile? Also I understand that there are more missing dimensional columns that could be potentially added in a future PR. Is there something unique or compelling about the missing dimensional columns you've added here?

Hey @sajarin, thanks a lot for taking time to review this PR 👋 

You're right, there are many other columns available; and for this PR I chose the most "basic" ones for a human to be able to read reports easily (at least have the Name and Type of the item). I am planning to do a comprehensive one in few weeks but I'm waiting a bit since other contributors wanted to work on it too (see #18476)

**Comment by rach-r** [comment]
@sajarin @sherifnada from my understanding the tests were failing on "expected records vs actual records" as I can't add new fields with Airbyte's sandbox account data. As we are going to have multiple PRs to add fields for this connector, I've made a small change to allow extra fields. If you're OK with this, could you relaunch `/test connector=source-bing-ads`?

Again, thanks a lot for your help 🙏

**Comment by rach-r** [comment]
So according to [this](https://docs.airbyte.com/connector-development/testing-connectors/connector-acceptance-tests-reference/) it's actually not possible to both have `extra_records` and `extra_fields` enabled:
image

So I guess I need someone who has access to the sandbox account to update the `expected_records`?...

**Comment by davydov-d** [comment]
@rach-r I don't think we should ignore those fields in the test config but rather modify expected records. @sajarin could you please help doing that? I'll approve this request after it passes tests, changes look good to me

**Comment by rach-r** [comment]
@davydov-d much better if someone can help me update the records indeed 🙏  otherwise @alafanechere gave me this workaround in case it takes too long to have someone available to do it. By the way I corrected a typo that made the last test fail on one stream, next one should be good 👍

**Comment by rach-r** [comment]
@sajarin rebase on master is done if you want to try again 🙂

**Comment by rach-r** [comment]
@sajarin I can see the tests have successfully passed after the rebase, thanks for the tip!! Should I do something else?

**Comment by marcosmarxm** [comment]
> @sajarin I can see the tests have successfully passed after the rebase, thanks for the tip!! Should I do something else?

This is incorrect. Tests are passing because the change is bypassed. We need to revert the acceptance-test.yml file changes and fix tests properly.

**Comment by alafanechere** [comment]
Just to summarize the status here:
* @rach-r shared a test output with passing tests
* We can't run the same tests suite because we don't have the fields seeded in our sandbox account
* I suggested @rach-r to mark the field as bypassed to make sure the rest of the changes are passing the tests. They do 🟢 .

@rach-r nothing else should be required from your side.
The next step are on our side:
1. Seed our account with the new fields 
2. Revert the field bypass on acceptance test config
3. Run the tests again.
4. Publish the new connector version if test are 🟢 
5. Merge

@sajarin could you take care of it ☝️ ?

@rach-r just to add a bit more context: this connector is a generally available connector with "high test strictness level". It means we want to get maximum test coverage. We would be a bit more relaxed if this connector was beta or alpha, but for stability reasons we prefer to enforce this rule.

**Comment by sajarin** [comment]
Thanks for the contribution @rach-r, your contributions have been merged in #24717

**Pull request closed without merging**
