### PR TITLE
initiailize connector release stage labels

### LINKED ISSUE #10288: label existing connectors with release stage
Add source and destination `release_stage` to each connector definition.

### PR DESCRIPTION
**Pull request by sherifnada**
## What
follow up to https://github.com/airbytehq/airbyte/pull/10225
instantiate all connectors at the `alpha` phase except for snowflake destination which is GA. 
closes #10288 

## How
use the solution provided in https://github.com/airbytehq/airbyte/pull/10051 which allows annotating the connector entry in the index with a `releaseStage`. 

## Recommended reading order
just the two files

### CODE REVIEW

**Review by jrhizor — APPROVED** [review]
Only reviewing the structure, not which connectors are labeled in which way.

Just a reminder, we're going to have an inline warning for all of these (on both Cloud and OSS) when https://github.com/airbytehq/airbyte/issues/9712 is ready in the next couple days:
https://user-images.githubusercontent.com/9026944/153908964-00cfe782-bbe9-49e5-a3f0-e19e0fb19643.png 

Except with the following text from Andy:
> "Alpha connectors are in development. We strongly discourage production use cases and do not offer support SLAs. The release may not be feature complete and breaking changes may be introduced."

**Review by subodh1810 — COMMENTED** [review]
Am curious how would this be stored in the database? Or is this not required to be stored in the DB?

**Review by subodh1810 — APPROVED** [review]

**Comment by jrhizor** [comment]
Connectors team will be responsible for updating the definitions file when a connector changes stage. Platforms shouldn't need to be involved.

**Review by cgardens — APPROVED** [review]

**Comment by sherifnada** [comment]
@jrhizor do these labels appear on OSS? if so, is there any plan for how it gets updated as users update individual connector versions?

**Comment by jrhizor** [comment]
@sherifnada:
1. Yes, they do appear in OSS.
2. Upgrades follow our current migration patterns. For OSS for example, `DatabaseConfigPersistence.updateConnectorDefinitions` clobbers the full definition on update for connectors not in use. There isn't a mechanism for updating the release stage when just upgrading one connector. Created https://github.com/airbytehq/airbyte/issues/10361 to track.

@cgardens If we want to default to `alpha`, we should make sure the migrations update the `release_stage` so users don't suddenly get these alpha warnings across the board for all of their prior connectors.

**Comment by sherifnada** [comment]
Synced with andy and we agreed that: 

1. We haven't prepared any external docs that explain what alpha/beta/GA means in detail
2. We are early in the ceritifcation process which makes all connectors look "alpha" atm

we're going to hold off on actually labelling these connectors until EOQ when we've improved on both points above. 

cc @jrhizor

**Pull request closed without merging**
