### PR TITLE
Extend SATs to capture UI limitations - fixed version

### PR DESCRIPTION
**Pull request by flash1293**
New set-up of https://github.com/airbytehq/airbyte/pull/21451 

See the second commit (https://github.com/airbytehq/airbyte/pull/21903/commits/e37f4098697d26fb0d5ec8545a65d9a4892f4fbc) for the new changes. In short, I removed the unnecessary fixture and used `connector_spec` instead.

To make sure it works fine, I tried to run it for an actual connector both via local python ( https://github.com/airbytehq/airbyte/blob/c67bfc50bb72bf2db1ceca127df86a158ccb1941/airbyte-integrations/bases/source-acceptance-test/README.md#L52 ) and via docker image ( `acceptance-test-docker.sh` in the connector code itself, make sure to use the locally built `dev` image).

We should definitely make this part of an integration test for the source acceptance tests, I will put up a separate issue for that.

### CODE REVIEW

**Review by girarda — APPROVED** [review]

**Comment by flash1293** [comment]
/publish connector=bases/source-acceptance-test auto-bump-version=false

**Pull request merged**
