### PR TITLE
🐛 Source Intercom: correct rate limit

### PR DESCRIPTION
**Pull request by bkrausz**
The rate limit was accidentally set to 1000 requests per hour, whereas it actually should be 1000 requests per minute. We should really time the request and run based off of that, but this is a super quick order of magnitude improvement without having to refactor anything.

## Pre-merge Checklist

Connector checklist

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Secrets are annotated with `airbyte_secret` in the connector's spec
- [ ] Credentials added to Github CI if needed and not already present. [instructions for injecting secrets into CI](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#using-credentials-in-ci). 
- [ ] Unit & integration tests added as appropriate (and are passing)
    * Community members: please provide proof of this succeeding locally e.g: screenshot or copy-paste acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] `/test connector=connectors/<name>` command as documented [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-an-existing-connector) is passing. 
    * Community members can skip this, Airbyters will run this for you. 
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] `README.md`
    - [ ] `docs/SUMMARY.md` if it's a new connector
    - [ ] Created or updated reference docs in `docs/integrations/<source or destination>/<name>`.
    - [ ] Changelog in the appropriate page in `docs/integrations/...`. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md` contains a reference to the new connector
    - [ ] Build status added to [build page](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md)
- [ ] Build is successful
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] No major blockers
- [ ] PR merged into master branch
- [ ] Follow up tickets have been created
- [ ] Associated tickets have been closed & stakeholders notified

### CODE REVIEW

**Review by sherifnada — APPROVED** [review]

**Comment by sherifnada** [comment]
Thanks @bkrausz ! Will merge this v soon

**Comment by lazebnyi** [comment]
Thanks, @bkrausz for your PR! Could you allow edits from maintainers for updating docs and versions?

**Comment by bkrausz** [comment]
> Thanks, @bkrausz for your PR! Could you allow edits from maintainers for updating docs and versions before merging?

Already enabled, thanks!

**Review by lazebnyi — APPROVED** [review]

**Pull request merged**
