### PR TITLE
make sure that all the secrets are remove

### PR DESCRIPTION
**Pull request by benmoriceau**
## What
explore all the nodes to mask secrets, even if they are arrays or nested at a given deep level.

It makes what has been made in https://github.com/airbytehq/airbyte/pull/8859 more generic

### CODE REVIEW

**Review by jrhizor — CHANGES_REQUESTED** [review]
I think this looks good, but it really needs to test these cases. I think that the test cases in `SecretsHelpersTest` / https://github.com/airbytehq/airbyte/tree/master/airbyte-config/persistence/src/test/resources would help. The expected output would be different but the inputs would be very similar, and they look at the base cases.

**Comment by benmoriceau** [comment]
> 

@jrhizor  I will have a look and add the test cases. I thought that having the exisiting UTest would be sufficient.

**Comment by benmoriceau** [comment]
@jrhizor That was a very wise comment! :)

**Comment by benmoriceau** [comment]
I am thinking about removing the existing UTest, because it is cover by the new UTest. Wdyt?

**Review by jrhizor — APPROVED** [review]
🎉 

The original test also includes tests for `copySecrets`. I think it's fine to remove all of the `maskSecrets` tests though.

**Review by sherifnada — APPROVED** [review]

**Pull request merged**
