### PR TITLE
airbyte-ci: use new self hosted runners

### PR DESCRIPTION
**Pull request by alafanechere**
We created new runners on the infra to support per usecase monitoring of resource usage

### CODE REVIEW

**Comment by alafanechere** [comment]
Current dependencies on/for this PR:
* master
  * **PR #32537** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/32537?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/airbytehq/airbyte/32537?utm_source=stack-comment).

**Review by evantahler — APPROVED** [review]
Was there also something that was changed in Github to register the new runner?

**Comment by alafanechere** [comment]
@

> Was there also something that was changed in Github to register the new runner?

No, it all happens infra side with this PR https://github.com/airbytehq/airbyte-infra/pull/77

**Review by bnchrch — APPROVED** [review]

**Pull request merged**
