### PR TITLE
Bump up snowflake source version

### PR DESCRIPTION
**Pull request by akashkulk**
Changes were made in this PR to fix a bug when new data is inserted at the same time the sync starts. However, they were never published. We're going to be making more changes to Snowflake source connector, so best to publish these changes prior to making additional changes here. 

Original issue : https://github.com/airbytehq/airbyte/issues/14732

https://github.com/airbytehq/airbyte/pull/15535

### CODE REVIEW

**Review by edgao — APPROVED** [review]
I'll trust that the original PR was solid, so no reason not to publish here 🚛

**Comment by akashkulk** [comment]
/publish connector=connectors/source-snowflake run-tests=false

**Pull request merged**
