### PR TITLE
:bug: Source-pipedrive: Use custom record extractor to handle records with null data

### PR DESCRIPTION
**Pull request by girarda**
## What
Create a custom record extractor for the source-pipedrive. The custom logic is required because pipedrive sometimes returns records with a null `data` field. Example:
```
  {
    "item": "file",
    "id": <an_id>,
    "data": null
  },
  {
    "item": "file",
    "id": <another_id>,
    "data": null
  },
```

## How
[This was previously handled in the python implementation](https://github.com/airbytehq/airbyte/pull/30553/files#diff-1a165a56ae76108bd160cc951cb87bdaf084c698dc324df20e540bd664f97433L82), but the migration to low-code caused a regression. This was implemented as `record = record.get(self.data_field) or record`.

This PR adds a custom record extractor that applies the same logic we used to do.

## Recommended reading order
1. `airbyte-integrations/connectors/source-pipedrive/source_pipedrive/extractor.py`
2. `airbyte-integrations/connectors/source-pipedrive/unit_tests/test_extractor.py`
3. `airbyte-integrations/connectors/source-pipedrive/source_pipedrive/manifest.yaml`

## 🚨 User Impact 🚨
The pipedrive connector syncs will properly handle records with a null data field

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/resources/pull-requests-handbook)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-pipedrive test report (commit [`2c26b053df`](https://github.com/airbytehq/airbyte/pull/31147/commits/2c26b053df63cedf59024202be4347a9986c6a0b)) - ✅

⏲️  Total pipeline duration: 03mn03s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Connector package install                                        | ✅        |
| Build source-pipedrive docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                       | ✅        |
| Acceptance tests                                                 | ✅        |
| Code format checks                                               | ✅        |
| Validate metadata for source-pipedrive                           | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ✅        |
| QA checks                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_source_pipedrive_extractor/1696630121/2c26b053df63cedf59024202be4347a9986c6a0b/source-pipedrive/2.0.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:2c26b053df63cedf59024202be4347a9986c6a0b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-pipedrive test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-pipedrive test report (commit [`34b18d5a02`](https://github.com/airbytehq/airbyte/pull/31147/commits/34b18d5a02a964c7184bc4170502f05ce019854f)) - ✅

⏲️  Total pipeline duration: 02mn38s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Connector package install                                        | ✅        |
| Build source-pipedrive docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                       | ✅        |
| Acceptance tests                                                 | ✅        |
| Code format checks                                               | ✅        |
| Validate metadata for source-pipedrive                           | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ✅        |
| QA checks                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_source_pipedrive_extractor/1696631140/34b18d5a02a964c7184bc4170502f05ce019854f/source-pipedrive/2.0.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:34b18d5a02a964c7184bc4170502f05ce019854f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-pipedrive test
```

**Review by bnchrch — APPROVED** [review]
@girarda This is so very well done. Thank you

**Comment by bnchrch** [comment]
Im just going to create a prerelease to test this out

**Comment by bnchrch** [comment]
prerelease action run: https://github.com/airbytehq/airbyte/actions/runs/6437084481

**Comment by bazarnov** [comment]
@girarda Could you please ETA when this will be merged?

**Review by bazarnov — APPROVED** [review]

**Comment by girarda** [comment]
I'll make sure this is merged today @bazarnov

**Pull request merged**
