### PR TITLE
:hammer: Source Shopify: fix inconsistent comparison 

### PR DESCRIPTION
**Pull request by ahmed-buksh**
## What
Fixes inconsistent comparison of None with a str.

## How
*Describe the solution*

## Recommended reading order
1. `airbyte-integrations/connectors/source-shopify/source_shopify/source.py`

## 🚨 User Impact 🚨
No breaking changes

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Comment by harshithmullapudi** [comment]
Hey, @ahmed-buksh thanks for the contribution. Can you help me with more info on when will this error occur?

**Comment by ahmed-buksh** [comment]
@harshithmullapudi in historic sync of Shopify this issue was being raised when `stream_state` does not have a cursor_field and that is requested in a comparison.
Reported issue with log could be found [here](https://github.com/airbytehq/airbyte/issues/11976)

**Comment by harshithmullapudi** [comment]
@ahmed-buksh can you share the screenshot for acceptance tests from local?

**Comment by harshithmullapudi** [comment]
@edmundito any thoughts on this?

**Comment by harshithmullapudi** [comment]
@ahmed-buksh is it possible to break this into 2 PR's one separate one for frontend so that we can speed up the shopify

**Comment by timroes** [comment]
@harshithmullapudi Most of the changes in the FE code here are due to wrong editor setup and are breaking with our auto formatting. It's hard to review the FE code atm, while those are still in. Thus I'd also suggest pulling the FE changes out, but at least they need to make sure to be correctly formatted before being reviewed (and merged).

**Comment by ahmed-buksh** [comment]
@harshithmullapudi closing this in favour of [PR](https://github.com/airbytehq/airbyte/pull/13163)

**Pull request closed without merging**
