### PR TITLE
🐛 Source Zendesk Chat: fix remove too high min/max. definition #23833 🚨

### LINKED ISSUE #23833: Source Zendesk Chat: Internal Server Error: For input string ending in 0
## Environment
- **Airbyte version**:  0.40.30
- **OS Version / Instance**: Ubuntu 18.04 AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: source-zendesk-chat (0.1.13)
- **Destination Connector and version**: airbyte/destination-s3 (0.3.20)
- **Step where error happened**: Setup new connection

## Current Behavior
image

## Expected Behavior
connection to be setup

## Logs
```
{"message":"Internal Server Error: For input string: \"1000000000000000000000000000000000\"","exceptionClassName":"java.lang.NumberFormatException","exceptionStack":["java.lang.NumberFormatException: For input string: \"1000000000000000000000000000000000\"","\tat java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)","\tat java.base/java.lang.Long.parseLong(Long.java:708)","\tat java.base/java.lang.Long.valueOf(Long.java:1156)","\tat org.jooq.tools.json.Yylex.yylex(Yylex.java:659)","\tat org.jooq.tools.json.JSONParser.nextToken(JSONParser.java:263)","\tat org.jooq.tools.json.JSONParser.parse(JSONParser.java:112)","\tat org.jooq.tools.json.JSONParser.parse(JSONParser.java:75)","\tat org.jooq.tools.json.JSONParser.parse(JSONParser.java:69)","\tat org.jooq.JSONB.parsed(JSONB.java:104)","\tat org.jooq.JSONB.toString(JSONB.java:131)","\tat io.airbyte.config.persistence.DbConverter.buildActorCatalog(DbConverter.java:229)","\tat java.base/java.util.Optional.map(Optional.java:260)","\tat io.airbyte.config.persistence.ConfigRepository.getActorCatalog(ConfigRepository.java:1341)","\tat io.airbyte.commons.server.handlers.SchedulerHandler.discoverSchemaForSourceFromSourceId(SchedulerHandler.java:260)","\tat io.airbyte.server.apis.SourceApiController.lambda$discoverSchemaForSource$5(SourceApiController.java:91)","\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:18)","\tat io.airbyte.server.apis.SourceApiController.discoverSchemaForSource(SourceApiController.java:91)","\tat io.airbyte.server.apis.$SourceApiController$Definition$Exec.dispatch(Unknown Source)","\tat io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)","\tat io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)","\tat io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)","\tat io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)","\tat io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)","\tat io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)","\tat reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)","\tat reactor.core.publisher.Flux.subscribe(Flux.java:8660)","\tat reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)","\tat io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)","\tat reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:172)","\tat io.micronaut.http.server.netty.RoutingInBoundHandler$4.doOnComplete(RoutingInBoundHandler.java:965)","\tat io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:79)","\tat io.micronaut.http.server.netty.jackson.JsonContentProcessor$1.doOnComplete(JsonContentProcessor.java:136)","\tat io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:79)","\tat java.base/java.util.Optional.ifPresent(Optional.java:178)","\tat io.micronaut.core.async.processor.SingleThreadedBufferingProcessor.doOnComplete(SingleThreadedBufferingProcessor.java:48)","\tat io.micronaut.jackson.core.parser.JacksonCoreProcessor.doOnComplete(JacksonCoreProcessor.java:94)","\tat io.micronaut.core.async.subscriber.SingleThreadedBufferingSubscriber.onComplete(SingleThreadedBufferingSubscriber.java:71)","\tat io.micronaut.http.server.netty.jackson.JsonContentProcessor.doOnComplete(JsonContentProcessor.java:161)","\tat io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:79)","\tat io.micronaut.http.netty.reactive.HandlerPublisher.publishMessage(HandlerPublisher.java:383)","\tat io.micronaut.http.netty.reactive.HandlerPublisher.flushBuffer(HandlerPublisher.java:470)","\tat io.micronaut.http.netty.reactive.HandlerPublisher.publishMessageLater(HandlerPublisher.java:360)","\tat io.micronaut.http.netty.reactive.HandlerPublisher.complete(HandlerPublisher.java:423)","\tat io.micronaut.http.netty.reactive.HandlerPublisher.handlerRemoved(HandlerPublisher.java:418)","\tat io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:1122)","\tat io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637)","\tat io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:477)","\tat io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423)","\tat io.micronaut.http.netty.stream.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:483)","\tat io.micronaut.http.netty.stream.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:319)","\tat io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:282)","\tat io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:134)","\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)","\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)","\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)","\tat io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)","\tat io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99)","\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)","\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)","\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)","\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)","\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)","\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)","\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)","\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)","\tat io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)","\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)","\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)","\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)","\tat io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)","\tat io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)","\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)","\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)","\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)","\tat io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:200)","\tat io.netty.handler.flow.FlowControlHandler.read(FlowControlHandler.java:139)","\tat io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:837)","\tat io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:814)","\tat io.micronaut.http.netty.reactive.HandlerPublisher.requestDemand(HandlerPublisher.java:165)","\tat io.micronaut.http.netty.stream.HttpStreamsHandler$2.requestDemand(HttpStreamsHandler.java:273)","\tat io.micronaut.http.netty.reactive.HandlerPublisher$ChannelSubscription.receivedDemand(HandlerPublisher.java:556)","\tat io.micronaut.http.netty.reactive.HandlerPublisher$ChannelSubscription.lambda$request$0(HandlerPublisher.java:494)","\tat io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)","\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)","\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)","\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)","\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)","\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)","\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)","\tat java.base/java.lang.Thread.run(Thread.java:1589)"]}
```

## Steps to Reproduce
1. Create a Zendesk Source
2. Create a s3 Destination
3. Try to set a new connection and it will fail on the discover_schema
4. Not sure if a problem specific to our data

## Are you willing to submit a PR?
yes

### PR DESCRIPTION
**Pull request by leo-schick**
## What & How
It looks like the java JSON parser does not support numbers in JSON with the size of `1e33` what is equal to `1000000000000000000000000000000000`.
I checked the [ZenDesk Chat API documentation](https://developer.zendesk.com/api-reference/live-chat/chat-api/accounts/) and there is no definition given for the `/plan/price` property of stream `accounts`, so I decided to remove the min/max. definition.

Closes #23833 

## 🚨 User Impact 🚨
This is a schema change and might break existing implementations.

@yevhenii-ldv You added the min/max. definition in the `accounts.json` file. Maybe you could give feedback about what the reason was to add this min/max. definition for property `/plan/price` in stream `accounts`.

## Pre-merge Checklist

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Connector version has been incremented
    - [ ] Version has been bumped according to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/semantic-versioning-for-connectors) guidelines
    - [ ] `Dockerfile` has updated version
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` with an entry for the new version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)

- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Review by marcosmarxm — APPROVED** [review]

**Review by bazarnov — CHANGES_REQUESTED** [review]
@marcosmarxm 
looks good, but I'm requesting changes to:
1) bump the version
2) update the changelog

**Comment by marcosmarxm** [comment]
> @marcosmarxm looks good, but I'm requesting changes to:
> 
> 1. bump the version
> 2. update the changelog

I'll handle this.

**Review by bazarnov — APPROVED** [review]

**Review by asafeunico — APPROVED** [review]

**Review by lucasfreitasunico — APPROVED** [review]

**Pull request merged**
