### PR TITLE
🐛 Source Zoom - Fix metadata validation and publish version with Oauth 

### PR DESCRIPTION
**Pull request by sajarin**
## What
*Describe what the change is solving*

Fixes the metadata.yaml validation error by including a releases section, with a note about the JWT -> Oauth breaking change

## How
*Describe the solution*

## Recommended reading order
1. `metadata.yaml`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@sajarin because we don't have credentials for OAuth you need to use the bot to merge this!

**Review by erohmensing — CHANGES_REQUESTED** [review]
@marcosmarxm can we figure out how we managed to ship a change which removed an old auth type in favor of a new one without setting up our own test credentials for the new auth method? 

I know that alpha connectors don't always pass all the tests. but without credentials on the company side, we can't run any tests _and_ we can't easily look into any issues that might arise. At that point, it seems like code that we shouldn't even have in our repo. What is the blocker toward getting us set up with oauth credentials, if those are the only credentials that can be used to run the connector?

**Comment by marcosmarxm** [comment]
> can we figure out how we managed to ship a change which removed an old auth type in favor of a new one without setting up our own test credentials for the new auth method?

Yes, integration test were using internal Airbyte account. We need to delete it. Saj created an [issue](https://github.com/airbytehq/airbyte/issues/26777) to GL to create a sandbox but never got solved.

@sajarin can you release this. Some folks want to use the connector.

**Comment by jessica-bauer** [comment]
Hi, just following up on this to see when this new Zoom connector might be released? Thank you!

**Comment by apd-bscally** [comment]
Hi, also looking to use this connector ASAP. Is there an estimated release date?

**Comment by jorgedcv** [comment]
Hi, is there an estimate of when the new version of this connector will be released?

**Comment by jcolinger3** [comment]
Also have been eagerly awaiting a fix here.
Any new information?

**Comment by jsoft88** [comment]
In the meantime, you could reuse the docker image I built for the updated zoom connector. You just need to go to Settings in the airbyte UI and under Workspace Settings, add a new Custom Connector and user the docker image I built from dockerhub: jsoft88/source-zoom:1.0.5

For me it is working and I am able to pull the data from zoom into S3

**Comment by marcosmarxm** [comment]
There is another pull request fixing the issue https://github.com/airbytehq/airbyte/pull/35369

**Pull request closed without merging**
