### PR TITLE
✨-Destination BigQuery: Updating Dataset Locations List

### PR DESCRIPTION
**Pull request by Al-Moatasem**
## What
Updating the list of [BigQuery dataset locations](https://cloud.google.com/bigquery/docs/locations), the new locations are: `europe-west12`, `me-central1`, `me-central2`, and `us-south1`.

### CODE REVIEW

**Comment by evantahler** [comment]
Thank you @Al-Moatasem! This PR looks great, except for the [oss_registry.json](https://github.com/airbytehq/airbyte/pull/32010/files#diff-5e4929b2a6757d8bea6ee1705fa407df55556bb1c727c50520e504ffa25b9be9) file. That should be git-ignored.

**Comment by evantahler** [comment]
And please check all the [boxes](https://github.com/airbytehq/airbyte/pull/32010#issuecomment-1787655898)

**Review by evantahler — CHANGES_REQUESTED** [review]
Please remove airbyte-config-oss/init-oss/src/main/resources/seed/oss_registry.json - that should be git-ignored.

**Comment by Al-Moatasem** [comment]
> And please check all the [boxes](https://github.com/airbytehq/airbyte/pull/32010#issuecomment-1787655898)

How to check them?

**Comment by evantahler** [comment]
> How to check them?
Oh! That might be something that I am to do as a reviewer - I'll do it!

**Comment by Al-Moatasem** [comment]
Regarding the locations list, these locations (`europe-central1`,`europe-west7`,`us-east2`,`us-east3`) don't exist in the [documentation](https://cloud.google.com/bigquery/docs/locations), but I am not sure if I should remove them from `spec.json` or keep them?

**Comment by Al-Moatasem** [comment]
@evantahler please let me know if there are any pending points from my side.

**Comment by evantahler** [comment]
> Regarding the locations list, these locations (europe-central1,europe-west7,us-east2,us-east3) don't exist in the [documentation](https://cloud.google.com/bigquery/docs/locations), but I am not sure if I should remove them from spec.json or keep them?

I'd leave them for now, we can remove them in a later PR

**Review by evantahler — APPROVED** [review]
I ran `gh pr checkout 32010 && airbyte-ci connectors --name="destination-bigquery" test` locally, and tests are green.  👍 from me!

**Comment by octavia-approvington** [comment]
A crack team of mammals has made a decision.  <br/> imagine a seal of approval

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
