### PR TITLE
[DONT REVIEW] Quick way to estimate how many connectors dont have tests

### PR DESCRIPTION
**Pull request by noahkawasakigoogle**
## What
Checking connector's and which ones have which tests implemented (estimation)

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

### CODE REVIEW

**Comment by noahkawasakigoogle** [comment]
Here's the current output:

```

Checking 145 sources

The following 19 sources do not implement acceptance tests
./source-zoom-singer
./source-e2e-test
./source-mongodb-v2
./source-bigquery
./source-mongodb
./source-python-http-tutorial
./source-e2e-test-cloud
./source-scaffold-java-jdbc
./source-mongodb-strict-encrypt
./source-relational-db
./source-appsflyer-singer
./source-cockroachdb
./source-redshift
./source-kafka
./source-stock-ticker-api-tutorial
./source-snowflake
./source-clickhouse
./source-appstore-singer
./source-jdbc

The following 16 sources do not implement unit tests
./source-mongodb-v2
./source-zendesk-sunshine
./source-plaid
./source-mongodb-strict-encrypt
./source-smartsheets
./source-tempo
./source-hellobaton
./source-file
./source-jira
./source-redshift
./source-kafka
./source-cockroachdb-strict-encrypt
./source-snowflake
./source-clickhouse
./source-exchange-rates
./source-clickhouse-strict-encrypt

The following 5 sources do not implement additional integration tests
./source-zoom-singer
./source-python-http-tutorial
./source-relational-db
./source-appsflyer-singer
./source-appstore-singer

Checking 45 destinations

The following 7 destinations do not implement unit tests
./destination-rockset
./destination-pubsub
./destination-mssql-strict-encrypt
./destination-oracle
./destination-bigquery-denormalized
./destination-mssql
./destination-meilisearch

The following 1 destinations do not implement additional integration tests
./destination-jdbc
```

**Comment by marcosmarxm** [comment]
@misteryeo can you check this contribution? look something we want to add to help us?

**Comment by noahkawasakigoogle** [comment]
Hey both, I recommend _not_merging this, this was just a quick and dirty way to get a general estimate for myself out of curiosity. Definitely would need some more thought and time to be merge-worthy. I also would recommend creating some directory structure standards to make a directory based implementation more reliable

**Comment by noahkawasakigoogle** [comment]
I can close this if that will help clean up the PR list

**Comment by misteryeo** [comment]
Haha, thanks @noahkawasakigoogle :) Definitely won't be merging - we'll wait for ya!

Let's close for now and revisit as we see fit!

**Pull request closed without merging**
