### PR TITLE
feat(python-cdk): bump jsonschema version to `~4.17.3`

### PR DESCRIPTION
**Pull request by cbini**
## What
Update `jsonschema` dependency to make PyAirbyte compatible with `dbt-common`. This dependency needs to be updated in the CDK in order to make it available downstream.

Closes:
* https://github.com/airbytehq/PyAirbyte/issues/398
* https://github.com/airbytehq/PyAirbyte/issues/441

## How
* Bumped `jsonschema` constraint to `~4.17.3` on `airbyte-cdk/python/pyproject.toml`
* Ran `poetry update jsonschema`

## Review guide
1. `airbyte-cdk/python/pyproject.toml`
2. `airbyte-cdk/python/poetry.lock`

## User Impact
* Users should be able to install PyAirbyte into projects alongside `dbt-common` without dependency conflicts

## Can this PR be safely reverted and rolled back?
- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by cbini** [comment]
[jsonschema>=4.18.0](https://github.com/python-jsonschema/jsonschema/releases/tag/v4.18.0) introduces major changes, deprecating `RefResolver`, which is used in a non-backward-compatible way in `airbyte-cdk`.

A handful of iterations of `test_transform` (under `airbyte-cdk/python/unit_tests/sources/utils/test_transform.py`) fail with:
```jsonschema.exceptions._RefResolutionError: Unresolvable JSON pointer: 'definitions/str_type'```

Resolving the errors would require migrating a bunch of `jsonschema` code that I'm not familiar with, but `v4.17.3` is the latest version that still passes all `airbyte-cdk` tests.

**Comment by cbini** [comment]
FYI `jsonschema` was last updated here: https://github.com/airbytehq/airbyte/pull/5161

**Review by marcosmarxm — COMMENTED** [review]
Thanks for the contribution, @cbini. Although it’s just a one-line change, it could significantly impact all Python connectors. I’ve asked the team to take a look, but I can’t guarantee they’ll be able to review or accept the change immediately. I’ll check with them and keep you updated.

@airbytehq/dev-python fyi

**Comment by aaronsteers** [comment]
@cbini - Moved to new PR here in our new Python CDK Repo:

- https://github.com/airbytehq/airbyte-python-cdk/pull/68

If tests pass, I'm inclined to merge, but let's continue the conversation over there.

**Comment by cbini** [comment]
Thanks all!

**Pull request closed without merging**
