### PR TITLE
source-reddit-ads contribution from itsxdamdam

### PR DESCRIPTION
**Pull request by itsxdamdam**
## What

This PR adds a new connector for source Reddit Ads (source-reddit-ads).

Contributor-provided connector description:

This PR adds a new connector for source Reddit Ads (source-reddit-ads)
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key_2` | `string` | API Key.  |  |
| `account_id` | `string` | account_id.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| ad_account | id.business_id.name | No pagination | ✅ |  ❌  |
| businesses |  | DefaultPaginator | ✅ |  ❌  |
| ad_groups |  | DefaultPaginator | ✅ |  ❌  |
| ads |  | DefaultPaginator | ✅ |  ❌  |
| get_business |  | No pagination | ✅ |  ❌  |
| industries |  | No pagination | ✅ |  ❌  |
| my_businesses |  | DefaultPaginator | ✅ |  ❌  |
| campaigns |  | DefaultPaginator | ✅ |  ❌  |
| custom_audiences |  | DefaultPaginator | ✅ |  ❌  |
| lead_gen_forms |  | DefaultPaginator | ✅ |  ❌  |
| me | id | No pagination | ✅ |  ❌  |
| posts |  | DefaultPaginator | ✅ |  ❌  |
| carriers |  | DefaultPaginator | ✅ |  ❌  |
| communities |  | DefaultPaginator | ✅ |  ❌  |
| search |  | DefaultPaginator | ✅ |  ❌  |
| suggestions |  | DefaultPaginator | ✅ |  ❌  |
| devices |  | DefaultPaginator | ✅ |  ❌  |
| geolocations |  | No pagination | ✅ |  ❌  |
| interests |  | No pagination | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hello 👋 Due to the numerous contributions happening, I decided to create this [view](https://github.com/orgs/airbytehq/projects/104/views/3) to help you know when I plan to review your contribution. If your connector has some limited-time credential feel free to reach me out.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
I believe there are some stream need to be fixed.
One example is `ads`
image

The declared schema is:
image

Which is wrong as showed in Reddit API Docs:
https://ads-api.reddit.com/docs/v3/operations/List%20Ads

Please check again the contribution and make sure you're reading the right data to each stream using the proper Record Selector and Paginator.

Icon must be a svg square format.


**NOTE**: I strongly recommend to you create an Airbyte cloud account and create your connector there. It make the review process easier to me :) You don't need to add credit.

**Comment by marcosmarxm** [comment]
I'm moving the next review to Nov-14

**Comment by marcosmarxm** [comment]
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

Make sure you have pagination properly working, the API doesn't have pagination please left a comment making my review easier.
Make sure have a square svg icon
Make sure credentials are valid.

**Comment by marcosmarxm** [comment]
Still no updates @itsxdamdam do you wanna continue the contribution? 
If no updates I'm going to decline the contribution by Monday

**Comment by itsxdamdam** [comment]
New PR coming in shortly

**Comment by marcosmarxm** [comment]
Contributor doesn't have enough data to test properly the connector + Reddit Ads API token expires very frequent without a good option to use an Auth in UI Builder.

**Pull request closed without merging**
