### PR TITLE
Remove workflow version check

### PR DESCRIPTION
**Pull request by jdpgrailsdev**
## What
* Improve code comprehension by removing conditional check

## How
* Remove workflow version check.  This is safe to do after we have deployed [d2911e5ec068717d518f1d3a5aa1434ffaf5e7e1](https://github.com/airbytehq/airbyte/commit/d2911e5ec068717d518f1d3a5aa1434ffaf5e7e1).

## Recommended reading order
1. `ConnectionManagerWorkflowImpl.java`

## Tests

* All tests pass
* Project builds locally

### CODE REVIEW

**Review by colesnodgrass — APPROVED** [review]

**Review by benmoriceau — APPROVED** [review]
LGTM but should we create a new OSS release before removing the version to give the chance to the OSS user to have a proper transition. I am not sure that all the OSS customer are still taking down their instance when doing a deployment.

**Review by gosusnp — APPROVED** [review]

**Comment by gosusnp** [comment]
> LGTM but should we create a new OSS release before removing the version to give the chance to the OSS user to have a proper transition. I am not sure that all the OSS customer are still taking down their instance when doing a deployment.

@benmoriceau, for a user that is using Docker, we will stop the sync upon upgrade since there is no orchestrator process. A user using Kube could run into a non deterministic exception, but I think that should be automatically restarted by the cron and that should be a one time occurence.

**Comment by benmoriceau** [comment]
> > LGTM but should we create a new OSS release before removing the version to give the chance to the OSS user to have a proper transition. I am not sure that all the OSS customer are still taking down their instance when doing a deployment.
> 
> @benmoriceau, for a user that is using Docker, we will stop the sync upon upgrade since there is no orchestrator process. A user using Kube could run into a non deterministic exception, but I think that should be automatically restarted by the cron and that should be a one time occurence.

Yeah but if we can reduce the likeliness of it that would be great. The cron is not everywhere for now: https://github.com/airbytehq/airbyte/pull/18542#discussion_r1008263348

**Comment by jdpgrailsdev** [comment]
> LGTM but should we create a new OSS release before removing the version to give the chance to the OSS user to have a proper transition. I am not sure that all the OSS customer are still taking down their instance when doing a deployment.

@benmoriceau I saw this after I merged.  Is it possible to create a release based on a commit sha?  If so, we can cut one from the previous commit on master.

**Pull request merged**
