### PR TITLE
Improve Connector logos

### PR DESCRIPTION
**Pull request by omid**
## What
Not a big change, just better logos for some connectors

### CODE REVIEW

**Comment by omid** [comment]
I cannot sign the agreement, because of “You must not submit any work that is not Your original creation.” :)
Obviously, the logos are not mine :))

**Comment by timroes** [comment]
@omid Without signing the CLA we unfortunately can't continue with this PR. The CLA applies in general to every PR you're doing against this repository, and notes that in general you commit your own work. Your own work in this case was adding the logos. Most countries (e.g. the US) have legal basis often called "fair/nominative use", that allows you do use logos to reference to the product or that company directly. 

In general: The logos we add for connectors should ideally be squared without padding, because that's how they'll be used across the UI. If you want to sign the CLA and continue on this PR, would you mind actually just using the "logo" portion of the corresponding icons i.e. the red "at-like" thing for mailgun, the green "s-like" part for seachmetrics, and the checkmark for Tempo (also I :heart: how that logo got mixed up with Tempos :D), without any padding around them.

cc @Upmitt

**Comment by omid** [comment]
OK, sure. Here you are. I also squared some more logos which were easy and obvious.
We also loled about the Tempos logo 😆

**Comment by timroes** [comment]
cc @Upmitt  (and also for back reference: https://github.com/airbytehq/airbyte/pull/14496#issuecomment-1313518808) we have at the moment two PRs open that touch the icons. Since this one here has the smaller footprint, I'd suggest to finalize this one merge it, and then continue with the other.

**Review by timroes — APPROVED** [review]
Changed LGTM. Checked all logos in the UI, looks all good and as expected.

**Pull request merged**
