### PR TITLE
✨ Source Facebook Pages: Upgrade Facebook API to v19.0

### LINKED ISSUE #25515: Source Facebook Pages: migrate API to v19.0
## Tell us about the problem you're trying to solve

Origin: https://github.com/airbytehq/oncall/issues/1888

The latest version for Facebook Pages Graph API  is v19.0.  Newly created apps can use only latest API version.

## Describe the solution you’d like
We need to migrate connector to the new version (current is v15.0).

Migration checks:

- [ ] Fields in graphQL requests
- [ ] Fields in schemas

### PR DESCRIPTION
**Pull request by airtz**
## What
- Resolve #25515

## How
- Upgrade Facebook API to v19.0

## Recommended reading order
1. `airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/manifest.yaml`

## User Impact
1. Invalid field removed: `messenger_ads_default_page_welcome_message`

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks for the contribution @airt I requested to the connector team to review it.

**Comment by marcosmarxm** [comment]
Solved by https://github.com/airbytehq/airbyte/pull/35746 sorry the lack of update here @airt

**Comment by airt** [comment]
> Solved by #35746 sorry the lack of update here @airt

@marcosmarxm Seems that #35746 is for Marketing and this one is for Pages, they are not the same source 😂

**Comment by marcosmarxm** [comment]
lol!!!! my baddd @airt

**Comment by midavadim** [comment]
I close this PR since API version was updated in another PR:
https://github.com/airbytehq/airbyte/pull/36015

**Pull request closed without merging**
