### PR TITLE
:bug:  Source Tiktok Marketing: apply minimum datetime restrictions

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/oncall/issues/2808
Some APIs return error in response to requesting data older than 2012-01-01

## How
- Set the start date to 2012-01-01 in case it is older than that + log a warning; add unit test
- Update schema and expected records to pass tests

## 🚨 User Impact 🚨
No impact

### CODE REVIEW

**Review by bazarnov — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-tiktok-marketing test report (commit [`9b7cade992`](https://github.com/airbytehq/airbyte/pull/31445/commits/9b7cade992796e99efabdc1b948af35e4fd174ea)) - ❌

⏲️  Total pipeline duration: 43.00s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Build source-tiktok-marketing docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                              | ❌       |
| Code format checks                                                      | ✅       |
| Validate metadata for source-tiktok-marketing                           | ✅       |
| Connector version semver check                                          | ✅       |
| Connector version increment check                                       | ✅       |
| QA checks                                                               | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_2808-source-tiktok-marketing-apply-minimum-datetime-restrictions/1697452757/9b7cade992796e99efabdc1b948af35e4fd174ea/source-tiktok-marketing/3.4.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:9b7cade992796e99efabdc1b948af35e4fd174ea)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-tiktok-marketing test report (commit [`528d2c9cd0`](https://github.com/airbytehq/airbyte/pull/31445/commits/528d2c9cd028d0cb877149d8c49aa24b677347d0)) - ❌

⏲️  Total pipeline duration: 47mn29s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Build source-tiktok-marketing docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                              | ✅       |
| Acceptance tests                                                        | ❌       |
| Code format checks                                                      | ✅       |
| Validate metadata for source-tiktok-marketing                           | ✅       |
| Connector version semver check                                          | ✅       |
| Connector version increment check                                       | ✅       |
| QA checks                                                               | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_2808-source-tiktok-marketing-apply-minimum-datetime-restrictions/1697455875/528d2c9cd028d0cb877149d8c49aa24b677347d0/source-tiktok-marketing/3.4.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:528d2c9cd028d0cb877149d8c49aa24b677347d0)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-tiktok-marketing test report (commit [`7fca0453e5`](https://github.com/airbytehq/airbyte/pull/31445/commits/7fca0453e55219a561757e5ea0ff23b63c6f6d2f)) - ❌

⏲️  Total pipeline duration: 50mn13s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Build source-tiktok-marketing docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                              | ✅       |
| Acceptance tests                                                        | ❌       |
| Code format checks                                                      | ✅       |
| Validate metadata for source-tiktok-marketing                           | ✅       |
| Connector version semver check                                          | ✅       |
| Connector version increment check                                       | ✅       |
| QA checks                                                               | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_2808-source-tiktok-marketing-apply-minimum-datetime-restrictions/1697463801/7fca0453e55219a561757e5ea0ff23b63c6f6d2f/source-tiktok-marketing/3.5.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7fca0453e55219a561757e5ea0ff23b63c6f6d2f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-tiktok-marketing test report (commit [`f62dbff079`](https://github.com/airbytehq/airbyte/pull/31445/commits/f62dbff07967bcb2e94fc00fcd0cba65fa19d846)) - ❌

⏲️  Total pipeline duration: 48mn02s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Build source-tiktok-marketing docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                              | ✅       |
| Acceptance tests                                                        | ❌       |
| Code format checks                                                      | ✅       |
| Validate metadata for source-tiktok-marketing                           | ✅       |
| Connector version semver check                                          | ✅       |
| Connector version increment check                                       | ✅       |
| QA checks                                                               | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_2808-source-tiktok-marketing-apply-minimum-datetime-restrictions/1697469973/f62dbff07967bcb2e94fc00fcd0cba65fa19d846/source-tiktok-marketing/3.5.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f62dbff07967bcb2e94fc00fcd0cba65fa19d846)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-tiktok-marketing test report (commit [`a822ffd3a6`](https://github.com/airbytehq/airbyte/pull/31445/commits/a822ffd3a642ae7cbd4f7c60b02d78d728da95c7)) - ❌

⏲️  Total pipeline duration: 42mn54s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Build source-tiktok-marketing docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                              | ✅       |
| Acceptance tests                                                        | ❌       |
| Code format checks                                                      | ✅       |
| Validate metadata for source-tiktok-marketing                           | ✅       |
| Connector version semver check                                          | ✅       |
| Connector version increment check                                       | ✅       |
| QA checks                                                               | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_2808-source-tiktok-marketing-apply-minimum-datetime-restrictions/1697475311/a822ffd3a642ae7cbd4f7c60b02d78d728da95c7/source-tiktok-marketing/3.5.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:a822ffd3a642ae7cbd4f7c60b02d78d728da95c7)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-tiktok-marketing test report (commit [`0da6a447b5`](https://github.com/airbytehq/airbyte/pull/31445/commits/0da6a447b50845a62168a7587629adb5c0592481)) - ✅

⏲️  Total pipeline duration: 42mn51s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Build source-tiktok-marketing docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                              | ✅       |
| Acceptance tests                                                        | ✅       |
| Code format checks                                                      | ✅       |
| Validate metadata for source-tiktok-marketing                           | ✅       |
| Connector version semver check                                          | ✅       |
| Connector version increment check                                       | ✅       |
| QA checks                                                               | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_2808-source-tiktok-marketing-apply-minimum-datetime-restrictions/1697530216/0da6a447b50845a62168a7587629adb5c0592481/source-tiktok-marketing/3.5.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:0da6a447b50845a62168a7587629adb5c0592481)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Pull request merged**
