### PR TITLE
Google Analytics v4: Added support for segments and filters

### PR DESCRIPTION
**Pull request by krisjan-oldekamp**
## What

Also see this issue: https://github.com/airbytehq/airbyte/issues/6305
Since I needed these options for a client project pretty soon, I updated the connector with the options described below (although someone else already claimed the issue in April).

### Added the "segments" request parameter to custom report options

So we can fetch segmented data from the Google Analytics API.

There are two ways to add a segment:

	1. Using the segment-ID (of prebuild segments in the GA interface) https://developers.google.com/analytics/devguides/reporting/core/v4/basics#segment_id or the (backwards compatible) segment syntax of the v3 reporing api: https://developers.google.com/analytics/devguides/reporting/core/v3/segments. Both can be inserted in the same request field.
	2. Using dynamicSegment definition (https://developers.google.com/analytics/devguides/reporting/core/v4/samples#segments)
	
Since method 1 is way simpler and can achieve most use cases (and most analylist are familier with these segment definitions), I've chosen for option 1.

When using segments, the dimension `ga:segments` has to be added, because when adding more than 1 segment, data gets multiplied (e.g. for every segment configured). The ga:segments dimension will make sure you can differentiate on segment.

**Example custom report definition**

Using a segment-ID (3) of an existing segment in the GA interface (tip: update documentation with these examples):

`[{"name": "sessions_segment", "dimensions": ["ga:date", "ga:segment"], "metrics": ["ga:pageviews","ga:sessions","ga:users","ga:transactions"], "segments": ["gaid::-3"]}]`

Using the (backwards compatible) segment syntax of the V3 api (see https://developers.google.com/analytics/devguides/reporting/core/v3/reference#segment)

`[{"name": "sessions_segment", "dimensions": ["ga:date", "ga:segment"], "metrics": ["ga:pageviews","ga:sessions","ga:users","ga:transactions"], "segments": ["sessions::condition::ga:browser==Chrome"]}]`

### Added the filter option to custom report options

Again two options available, the more complicated v4 filter syntax, or the simplified (most known) v3 format: https://developers.google.com/analytics/devguides/reporting/core/v3/reference#filters

Selected the v3 format.

**Usage (tip: update documentation with these examples):**

See filter expression list: https://developers.google.com/analytics/devguides/reporting/core/v3/reference#filters

`[{"name": "sessions_filter", "dimensions": ["ga:date", "ga:deviceCategory"], "metrics": ["ga:pageviews","ga:sessions","ga:users","ga:transactions"], "filter": "ga:deviceCategory==desktop}]`

## Testing

I tested my connector using a separate integration test catalog:

`python main.py read --config secrets/service_config.json --catalog integration_tests/configured_catalog_segment_filters.json`

Where I used these configuration values for the segments / filters -> it will only return the data for browser = Chrome (segment) and only for 2022-09-01 (put a filter on the date dimension)

`"custom_reports": "[{\"name\": \"sessions_segment\", \"dimensions\": [\"ga:date\", \"ga:segment\"], \"metrics\": [\"ga:pageviews\",\"ga:sessions\",\"ga:users\",\"ga:transactions\",\"ga:itemQuantity\"], \"segments\": [\"sessions::condition::ga:browser==Chrome\"], \"filter\": \"ga:date==20220901\"}]"`

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
No breaking changes, only extra options in the custom report fields.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by sajarin** [comment]
Thanks @krisjan-oldekamp for making this PR. This PR will be reviewed by a member of the community as part of Airbyte's Community Maintainer program. Someone will be assigned to review and help get your PR merged onto our main branch. Thanks for being patient!

**Comment by rhaegar2803** [comment]
@sajarin I can pick this one for reviewing since it was initially assigned to me :)

**Comment by itaseskii** [comment]
@sajarin I can pick this one for reviewing since it was initially assigned to me :)

**Comment by sajarin** [comment]
@itaseskii, awesome thanks for picking this up!

**Comment by krisjan-oldekamp** [comment]
@itaseskii Updated the docs and bumped the version in the Dockerfile

**Comment by itaseskii** [comment]
@krisjan-oldekamp at first look this PR seems fine and inline with how the API works as explained in https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet 

I have one question related to filtering. Is there any semantic or capability based difference between a "filtersExpression" property and a "dimensionFilterClauses"? can you filter using a "filtersExpression" on regex values, range values, case sensitivity as in the GA4 query explorer https://ga-dev-tools.web.app/ga4/query-explorer/?

**Comment by krisjan-oldekamp** [comment]
@itaseskii The tool you're referring to is related to Google Analytics 4. This connector is related to the old version of GA, Universal Analytics Core Reporting API version 4, so it's a bit confusing. So the [query explorer tool](https://ga-dev-tools.web.app/query-explorer/) for Google Universal Analytics is using the exact same methods as used in this connector (the v3 style filter expressions and dynamic segment definitions). You can use RegEx in these filters (which you could also use for ranges), but Regex in filtersExpression is case insensitive. However the v3 style definitions are pretty much industry standard for years (almost every other tool that uses the GA Core Reporting API is using the v3 style declarations).

**Comment by itaseskii** [comment]
@sajarin Can you please run the acceptance test suite? :)

**Comment by krisjan-oldekamp** [comment]
Screenshots:

Running with segment + filter (filter on date = 20220901 / succesfully only returns this data):

screenshot_with_segment_and_filter

Running with segment

screenshot_with_segment

Last lines of running configured_catalog.yaml

screenshot_lastlines

**Comment by krisjan-oldekamp** [comment]
@sajarin / @itaseskii added a fix, because the connection test didn't pass, so good to go for the acceptance test.

**Comment by YowanR** [comment]
@sajarin could you take a look at this, please?

**Review by sajarin — APPROVED** [review]

**Comment by JonasBolin** [comment]
@krisjan-oldekamp huge thanks for taking on this one!

**Comment by YowanR** [comment]
@sajarin can you confirm that we can close this given this is merged: https://github.com/airbytehq/airbyte/issues/6305?

**Comment by DaiZack** [comment]
I run into errors when using Google Analytics (Universal Analytics)

image

It seems the model is missing segments in the property:
airbyte-integrations/connectors/source-google-analytics-v4/source_google_analytics_v4/custom_reports_validator.py
row 19

image

I am just starting to use airbyte, don't know how to test from my side. Could you verify it?

**Comment by DaiZack** [comment]
I have just created a new connector with the line changed above, it works for me.

Also, it is annoying that the deleting source is missing from the GUI.

**Comment by ViniciusARZ** [comment]
@DaiZack do you have any recommendations on how to filter the data based on the column ga:isConversionEvent?
I tried multiple variations according to the documentation here, such as `"filter": "ga:isConversionEvent==true"`, tried with segments too, using `"segments": "ga:isConversionEvent==true"` and also tried with conditions, such as `"segments": ["eventCount::condition::ga:isConversionEvent==true"]`.

None of them worked. They pass through the testing on Airbyte, but the data returned comes unfiltered.

**Comment by JonasBolin** [comment]
@ViniciusARZ you might be confusing the Google Analytics Core Reporting API v4, with the Google Analytics 4 Data API.

I believe Google Analytics Core Reporting API v4 does not have the **ga:isConversionEvent** dimension, it is only present in the GA4 Data API.

**Comment by ViniciusARZ** [comment]
It actually does work. The extraction works perfectly and the isConversionEvent dimension comes with normal data, as expected. The only thing I'm not being able to achieve is filtering by it, since I wanted it to return only records with `true` as the value in the dimension.

**Comment by DaiZack** [comment]
1. There is a bug in custom_reports_validator.py as I mentioned above. I tried to submit a merge request but tucked into CI/CD process, don't know how to make the merge, but it worked on my server well. https://github.com/airbytehq/airbyte/pull/22223 
2. When using segmentation, you need also include the segmentent into the dimension, otherwise google will reject it.

**Comment by ViniciusARZ** [comment]
Do you have any recommendations on how to filter by this column? I also tried adding the segments dimension, and it still got the data unfiltered.

**Pull request merged**
