### PR TITLE
Revert "Source Zendesk Support: remove version pin"

### PR DESCRIPTION
**Pull request by clnoll**
Addressing this [page](https://airbyte.pagerduty.com/incidents/Q32BLYRO099VKS) for 400 errors. 

Reverts airbytehq/airbyte#28587

### CODE REVIEW

**Review by maxi297 — APPROVED** [review]
LGTM as the previous working versions on the three workspaces that created the alert where on 0.10.0 on their last successful run. However, I'm wondering if 0.10.1 would be fine as well since I don't see any issue for this version on Metabase. Up to you to see if it makes sense

**Comment by octavia-squidington-iii** [comment]
##  source-zendesk-support test report (commit [`c6194a9f6a`](https://github.com/airbytehq/airbyte/pull/28611/commits/c6194a9f6a42cc2e161dc93bb3284346795e0fa3)) - ✅

⏲️  Total pipeline duration: 12mn56s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zendesk-support/metadata.yaml | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build source-zendesk-support docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ✅        |
| Acceptance tests                                                              | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/revert-28587-artem1205_source-zendesk-support-remove-version-pin/1690204897/c6194a9f6a42cc2e161dc93bb3284346795e0fa3/source-zendesk-support/0.10.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-support test
```

**Comment by octavia-approvington** [comment]
What are we doing again? <br/> merge and squash

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
