### PR TITLE
fix check operation for Redshift destination

### PR DESCRIPTION
**Pull request by subodh1810**
Redshift destination is broken cause check command is not working. See https://airbytehq-team.slack.com/archives/C02U46QK5C3/p1649865322979029?thread_ts=1649860116.562399&cid=C02U46QK5C3

### CODE REVIEW

**Review by ChristopheDuong — APPROVED** [review]
It'd be nice if this would be picked up by integration tests?

**Comment by subodh1810** [comment]
@ChristopheDuong I created an issue to make sure we test the check operation across all connectors in integration tests

**Review by Tr1985 — COMMENTED** [review]
airbyte-integrations/connectors/destination-redshift/src/main/java/io/airbyte/integrations/destination/redshift/RedshiftCopyS3Destination.java

**Comment by subodh1810** [comment]
> airbyte-integrations/connectors/destination-redshift/src/main/java/io/airbyte/integrations/destination/redshift/RedshiftCopyS3Destination.java

@Tr1985 am not sure I understood the above comment

**Pull request merged**
