### PR TITLE
🎉 New Source: Strava

### PR DESCRIPTION
**Pull request by terencecho**
## What
* Add new source: Strava

## How
Add two streams for this source:
- Athlete Stats
- Activities

## Recommended reading order
1. bootstrap.md
2. docs/integrations/sources/strava.md
3. spec.json
4. Schemas under schemas/*.json
5. source.py
6. streams.py

## Tests
<details><summary> <strong> Unit Tests </strong></summary>

```
(.venv) ❰tcho❙~/code/forks/airbyte/airbyte-integrations/connectors/source-strava(git✱source-strava)❱✔≻ python3 -m pytest -s unit_tests
Test session starts (platform: darwin, Python 3.9.7, pytest 6.2.5, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /Users/tcho/code/forks/airbyte, configfile: pytest.ini
plugins: sugar-0.9.4, mock-3.6.1, timeout-1.4.2
collecting ...
 ../../airbyte/airbyte-integrations/connectors/source-strava/unit_tests/test_incremental_streams.py::test_cursor_field ✓                                                                                                         7% ▋
 ../../airbyte/airbyte-integrations/connectors/source-strava/unit_tests/test_incremental_streams.py::test_get_updated_state ✓                                                                                                   13% █▍
 ../../airbyte/airbyte-integrations/connectors/source-strava/unit_tests/test_incremental_streams.py::test_stream_slices ✓                                                                                                       20% ██
 ../../airbyte/airbyte-integrations/connectors/source-strava/unit_tests/test_incremental_streams.py::test_supports_incremental ✓                                                                                                27% ██▋
 ../../airbyte/airbyte-integrations/connectors/source-strava/unit_tests/test_incremental_streams.py::test_source_defined_cursor ✓                                                                                               33% ███▍
 ../../airbyte/airbyte-integrations/connectors/source-strava/unit_tests/test_incremental_streams.py::test_stream_checkpoint_interval ✓                                                                                          40% ████
 airbyte-integrations/connectors/source-strava/unit_tests/test_streams.py::test_request_params ✓                                                                                                                                47% ████▋
 airbyte-integrations/connectors/source-strava/unit_tests/test_streams.py::test_next_page_token ✓                                                                                                                               53% █████▍
 airbyte-integrations/connectors/source-strava/unit_tests/test_streams.py::test_request_headers ✓                                                                                                                               60% ██████
 airbyte-integrations/connectors/source-strava/unit_tests/test_streams.py::test_http_method ✓                                                                                                                                   67% ██████▋
 airbyte-integrations/connectors/source-strava/unit_tests/test_streams.py::test_should_retry[HTTPStatus.OK-False] ✓                                                                                                             73% ███████▍
 airbyte-integrations/connectors/source-strava/unit_tests/test_streams.py::test_should_retry[HTTPStatus.BAD_REQUEST-False] ✓                                                                                                    80% ████████
 airbyte-integrations/connectors/source-strava/unit_tests/test_streams.py::test_should_retry[HTTPStatus.TOO_MANY_REQUESTS-True] ✓                                                                                               87% ████████▋
 airbyte-integrations/connectors/source-strava/unit_tests/test_streams.py::test_should_retry[HTTPStatus.INTERNAL_SERVER_ERROR-True] ✓                                                                                           93% █████████▍
 airbyte-integrations/connectors/source-strava/unit_tests/test_streams.py::test_backoff_time ✓                                                                                                                                 100% ██████████
============================================================================================================== warnings summary ==============================================================================================================
airbyte-integrations/connectors/source-strava/unit_tests/test_incremental_streams.py: 6 warnings
airbyte-integrations/connectors/source-strava/unit_tests/test_streams.py: 9 warnings
  /Users/tcho/code/forks/airbyte/airbyte-integrations/connectors/source-strava/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py:37: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    self._authenticator = NoAuth()

airbyte-integrations/connectors/source-strava/unit_tests/test_incremental_streams.py: 6 warnings
airbyte-integrations/connectors/source-strava/unit_tests/test_streams.py: 9 warnings
  /Users/tcho/code/forks/airbyte/airbyte-integrations/connectors/source-strava/.venv/lib/python3.9/site-packages/deprecated/classic.py:173: DeprecationWarning: Call to deprecated class HttpAuthenticator. (Use requests.auth.AuthBase instead) -- Deprecated since version 0.1.20.
    return old_new1(cls, *args, **kwargs)

-- Docs: https://docs.pytest.org/en/stable/warnings.html

Results (0.25s):
      15 passed
```
</details>

<details><summary> <strong> Integration Tests </strong></summary>

```
(.venv) ❰tcho❙~/code/forks/airbyte/airbyte-integrations/connectors/source-strava(git✱source-strava)❱✔≻ python -m pytest -p integration_tests.acceptance
Test session starts (platform: darwin, Python 3.9.7, pytest 6.2.5, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /Users/tcho/code/forks/airbyte, configfile: pytest.ini
plugins: sugar-0.9.4, mock-3.6.1, timeout-1.4.2
collecting ...
 ../../airbyte/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_match_expected[inputs0] ✓                                                                              7% ▊
 ../../airbyte/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_required[inputs0] ✓                                                                                   14% █▌
 ../../airbyte/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_optional[inputs0] ✓                                                                                   21% ██▎
 ../../airbyte/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_has_secret[inputs0] ✓                                                                                 29% ██▉
 ../../airbyte/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_secret_never_in_the_output[inputs0] ✓                                                                 36% ███▋
 ../../airbyte/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_oauth_flow_parameters[inputs0] ✓                                                                      43% ████▍
 ../../airbyte/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestConnection.test_check[inputs0] ✓                                                                                50% █████
 ../../airbyte/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestConnection.test_check[inputs1] ✓                                                                                57% █████▊
 ../../airbyte/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_discover[inputs0] ✓                                                                              64% ██████▌
 ../../airbyte/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_cursors_exist_in_schema[inputs0] ✓                                                       71% ███████▎
 ../../airbyte/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestBasicRead.test_read[inputs0] ✓                                                                                  79% ███████▉
 ../../airbyte/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_full_refresh.py::TestFullRefresh.test_sequential_reads[inputs0] ✓                                                            86% ████████▋
 ../../airbyte/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py::TestIncremental.test_two_sequential_reads[inputs0] ✓                                                         93% █████████▍
 ../../airbyte/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py::TestIncremental.test_state_with_abnormally_large_values[inputs0] s                                          100% ██████████
========================================================================================================== short test summary info ===========================================================================================================
SKIPPED [1] ../../../../../airbyte/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py:21: `future_state_path` not specified, skipping

Results (27.68s):
      13 passed
       1 skipped
```
</details>

## Pre-merge Checklist
<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated 
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/SUMMARY.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [x] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [x] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

### CODE REVIEW

**Comment by terencecho** [comment]
Am I supposed to generate a `sourceDefinitionId` to add to the connector index myself, in accordance to the last item on the pre-merge checklist for contributors? The documentation linked only refers to updating `<uuid>.json` files that already exists when updating connectors.

**Comment by marcosmarxm** [comment]
> Am I supposed to generate a `sourceDefinitionId` to add to the connector index myself, in accordance to the last item on the pre-merge checklist for contributors? The documentation linked only refers to updating `<uuid>.json` files that already exists when updating connectors.

Yes.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Hi @terencecho I made some comments about the contribution, is it possible to share the integration credentials to test (you can send to me in Slack). I request to another member to review your code in more details.

If possible add the endpoint docs in each stream.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]

**Review by marcosmarxm — APPROVED** [review]
LGTM awesome work @terencecho

**Pull request merged**
