### PR TITLE
Fix Greenhouse employee_id type

### LINKED ISSUE #11939: Greenhouse syncs failed during the normalization step when employee IDs are not integers
## Environment
- **Airbyte version**:  v0.35.62-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Greenhouse 0.2.6
- **Destination Connector and version**: Snowflake 0.4.24
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior

Greenhouse syncs failed during the normalization step when employee IDs are not integers.

Employee IDs are defined as strings in the API doc: https://developers.greenhouse.io/harvest.html#post-add-user

## Expected Behavior

Greenhouse syncs with normalization should not fail when employee IDs are not integers.

## Logs

<details>
<summary>LOG</summary> 

```

4-11 20:06:59 [42mnormalization[0m > 20:06:54.818777 [info ] [MainThread]: [31mCompleted with 5 errors and 0 warnings:[0m
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.819133 [info ] [MainThread]: 
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.819397 [error] [MainThread]: [33mDatabase Error in model USERS (models/generated/airbyte_tables/GREENHOUSE/USERS.sql)[0m
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.819698 [error] [MainThread]:   100038 (22018): Numeric value 'A686XKEWD' is not recognized
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.819954 [error] [MainThread]:   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/GREENHOUSE/USERS.sql
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.820208 [info ] [MainThread]: 
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.820454 [error] [MainThread]: [33mDatabase Error in model APPLICATIONS_CREDITED_TO (models/generated/airbyte_tables/GREENHOUSE/APPLICATIONS_CREDITED_TO.sql)[0m
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.820729 [error] [MainThread]:   100038 (22018): Numeric value 'J2H3LZRRN' is not recognized
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.820964 [error] [MainThread]:   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/GREENHOUSE/APPLICATIONS_CREDITED_TO.sql
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.821240 [info ] [MainThread]: 
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.821490 [error] [MainThread]: [33mDatabase Error in model SCORECARDS_INTERVIEWER (models/generated/airbyte_tables/GREENHOUSE/SCORECARDS_INTERVIEWER.sql)[0m
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.821759 [error] [MainThread]:   100038 (22018): Numeric value '6F46NSAJZ' is not recognized
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.821998 [error] [MainThread]:   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/GREENHOUSE/SCORECARDS_INTERVIEWER.sql
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.822244 [info ] [MainThread]: 
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.822488 [error] [MainThread]: [33mDatabase Error in model SCORECARDS_SUBMITTED_BY (models/generated/airbyte_tables/GREENHOUSE/SCORECARDS_SUBMITTED_BY.sql)[0m
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.822759 [error] [MainThread]:   100038 (22018): Numeric value 'SI7LKZ9F1' is not recognized
2022-04-11 20:06:59 [32mINFO[m i.a.v.j.JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $.method: does not have a value in the enumeration [Standard]
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.822998 [error] [MainThread]:   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/GREENHOUSE/SCORECARDS_SUBMITTED_BY.sql
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.823245 [info ] [MainThread]: 
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.823486 [error] [MainThread]: [33mDatabase Error in model CANDIDATES_APPLICATIONS_CREDITED_TO (models/generated/airbyte_tables/GREENHOUSE/CANDIDATES_APPLICATIONS_CREDITED_TO.sql)[0m
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.823758 [error] [MainThread]:   100038 (22018): Numeric value '2R88IDXG4' is not recognized
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.824076 [error] [MainThread]:   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/GREENHOUSE/CANDIDATES_APPLICATIONS_CREDITED_TO.sql
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.824468 [info ] [MainThread]: 
2022-04-11 20:06:59 [42mnormalization[0m > 20:06:54.824723 [info ] [MainThread]: Done. PASS=79 WARN=0 ERROR=5 SKIP=0 TOTAL=84

```

</details>

## Steps to Reproduce
1. Setup Greenhouse source with normalization where employee IDs are not integer in Greenhouse
2. Sync

## Are you willing to submit a PR?

Yes.

### PR DESCRIPTION
**Pull request by remisalmon**
## What

Fixes https://github.com/airbytehq/airbyte/issues/11939

## How

Change all Employee IDs type to string (currently some streams have employee_id as integer, some as string).

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks for the contribution @remisalmon can you sign the CLA?

**Comment by remisalmon** [comment]
> Thanks for the contribution @remisalmon can you sign the CLA?

Done, thank you.

**Comment by marcosmarxm** [comment]
/publish connector=connectors/source-greenhouse auto-bump-version=false

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
