### PR TITLE
Fix casing of Advanced Auth for source-harvest

### PR DESCRIPTION
**Pull request by ChristopheDuong**
## What
Fix casing of advancedAuth for source-harvest

## How
Fix the server which is throwing an exception when trying to convert the OAuthFlowType too

## Pre-merge Checklist

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Airbyter

- [x] Build is successful
- [x] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [x] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

### CODE REVIEW

**Review by jamakase — APPROVED** [review]
I still think that we should aim to follow camelCase as we follow it everywhere in app except this place.

**Review by jrhizor — APPROVED** [review]

**Comment by ChristopheDuong** [comment]
> I still think that we should aim to follow camelCase as we follow it everywhere in-app except this place.

We're actually trying to move more protocol related classes to be snake case (as there's a bunch of TODO on old fields that we haven't been able to migrate to snake cases yet)

This is because some other classes are also following snake case and we are currently having a mix of both in the protocol. The API still stays in camelcase though.

**Pull request merged**
