### PR TITLE
🐛 Source Square: fix customers pagination

### LINKED ISSUE #30309: Source Square: Customers object not paginating
### Connector Name

source-square

### Connector Version

1.1.2

### What step the error happened?

During the sync

### Revelant information

The `customers` stream returns a maximum 100 responses because it is not paginating https://developer.squareup.com/reference/square/customers-api/list-customers#query__property-limit

### Relevant log output

_No response_

### Contribute

- [X] Yes, I want to contribute
```[tasklist]
### Tasks
- [ ] https://github.com/airbytehq/airbyte/pull/30315
```

### PR DESCRIPTION
**Pull request by juftin**
## What

This PR makes a bug fix to the `source-square` connector. Currently the `customers` stream of the connector is not paginating correctly and returns a max of 100 records.

Resolves #30309 

## How

Update the connector metadata to use the correct `retriever` - it was inadvertently using a base retriever without pagination. This fix has been tested and verified locally.

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

No

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

This is a `fix` / `patch` version bump.

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks for the contribution @juftin !

**Comment by juftin** [comment]
someone please help merge this 🙃

**Comment by marcosmarxm** [comment]
@juftin at the moment team is reviewing Hackathon contributions. After the event finish we're going to return to the community backlog. Sorry for the missing update here.

**Review by marcosmarxm — APPROVED** [review]
Thanks @juftin LGTM, only one small change needed is uncommented the `Square-Version` header to work and update the metadata file version.

**Comment by marcosmarxm** [comment]
This week codebase is freeze because of holidays. The change looks good but only will be able to merge next week.

**Comment by juftin** [comment]
Hey @marcosmarxm any chance you could take a look at this?

**Comment by juftin** [comment]
> Hey @marcosmarxm any chance you could take a look at this?

Any update @marcosmarxm?

**Comment by marcosmarxm** [comment]
Tests are broken, I'm working to fix them and get your changes merged! Sorry the long-long delay to get this done.

**Pull request merged**
