### PR TITLE
ClickHouse destination doesn't have a logo #19283

### PR DESCRIPTION
**Pull request by juweins**
## What
Neither the dropdown at source nor destination menu showed the clickhouse icon.

## How
1. Corrected typo in destination_definitions.yaml
2. Added respective icon to  source_definitions.yaml

## Recommended reading order
straight forward

## 🚨 User Impact 🚨
minimal

## Pre-merge Checklist
No checklist relevant.

- [x] First Contributor. (And proud!)

## Tests
Docker container has to be updated in order to check with local installation. Should work

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hello :wave:, first thank you for this amazing contribution. 

We really appreciate the effort you've made to improve the project.
We ask you patience for the code review. Last month our team was focused on Hacktoberfest event and that probably left some PR without the proper feedback. And this week, due to the Thanksgiving US Holiday, most our team is out of office with their families. Another important piece of information why code won't be merge this week is: as a safety measure the core team has decided to freeze merging code to main branch to keep the release stable. Next week we'll return to you with the proper code review and update the status of your contribution.

If you have any questions feel free to send me a message in Slack!
Thanks!

**Comment by juweins** [comment]
No worries. In the meantime:

Can you provide me with some infos on how & where to get these svg files? (legally correct)

I would like to contribute some from time to time!

**Review by marcosmarxm — APPROVED** [review]
Thanks!

**Comment by marcosmarxm** [comment]
The icon was there: https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/clickhouse.svg but only a naming problem.
Usually you try to get in the provider website

**Comment by juweins** [comment]
> The icon was there: https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/clickhouse.svg but only a naming problem. Usually you try to get in the provider website

Is there any standard procedure to request them from the desired company? Or is it OK to just download it from the website/html code on my own? (Aiming at copyright related issues) 

Thanks for the merge! :)

**Pull request merged**
