### PR TITLE
✨ Source Asana: add task and target data to stories compact stream

### PR DESCRIPTION
**Pull request by mr935h**
## What

Need to add task and target data to the stories compact stream to associate stories to tasks.
https://github.com/airbytehq/airbyte/issues/28939

## How

Add the task and target fields to the yaml file under the stories compact stream

## User Impact

New data added to the stories compact stream.

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by jdbranham** [comment]
Nice addition!

**Comment by marcosmarxm** [comment]
Running tests! Thanks for the contribution, @mr935h.

**Review by marcosmarxm — APPROVED** [review]
LGTM!

**Comment by marcosmarxm** [comment]
Hello your feedback matters a lot to us. Can you spare just 2 minutes to complete a [survey](https://form.typeform.com/to/DOBqejte)? We’re dedicated to making the contributor experience even better, and your input is key to achieving excellence. Thank you for helping us improve!

**Pull request merged**
