### PR TITLE
source-tmdb-popular-movie-list contribution from faria-karim-porna

### LINKED ISSUE #47134: [connector-request] TMDB
### Topic

New connector request

### Relevant information

This is a suggestion to create a connector for TMDB using the UI Connector Builder. The website for the connector is https://www.themoviedb.org.

Relevant information
https://developer.themoviedb.org/docs/getting-started

### PR DESCRIPTION
**Pull request by faria-karim-porna**
## What

This PR updates source TMDb (source-tmdb).

The contributor provided the following description of the change:

This connector integrates with the TMDB API using the UI Connector Builder, enabling seamless access to various TMDB features. It includes the following actions: Fetches a list of currently popular movies, Retrieves account-specific details, Adds a movie to the favorite list, Adds a movie to the watchlist, Retrieves the list of movies marked as favorites, Retrieves the list of movies added to the watchlist, Finds movie information based on an external ID (like IMDb ID), Fetches detailed information about a specific movie by its TMDB ID.
## Reviewer checklist
- [ ] Resolve any merge conflicts and validate file diffs (make sure the PR only includes changes intended by the contributor)
- [ ] After reviewing the changes, run the [`bump-version` Airbyte-CI command](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md#connectors-bump-version-command) locally to update the version of the connector according to the [versioning guidelines](https://docs.airbyte.io/contributor-guide/versioning-guidelines). Add `breakingChanges` to metadata if necessary.
- [ ] Ensure connector docs are up to date with any changes
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by faria-karim-porna** [comment]
Hi @marcosmarxm would you please label it as hacktoberfest and review the PR?

**Comment by marcosmarxm** [comment]
Hello 👋 Due to the numerous contributions happening, I decided to create this [view](https://github.com/orgs/airbytehq/projects/104/views/3) to help you know when I plan to review your contribution. If your connector has some limited-time credential feel free to reach me out.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Hello @faria-karim-porna this is a good start but I don't believe only endpoint adds the minimal requirements to accept the connector. Let me know if you want to work implement more endpoints to make the connector more easy to general usage. If not, I inclined to decline the contribution.

**Comment by faria-karim-porna** [comment]
Hi @marcosmarxm, Thank you for the feedback! I’d be happy to work on adding more endpoints to enhance the connector’s usability. I'll get started right away and plan to have updates by the next checkpoint on Nov 5. Could you please let me know how many additional endpoints you think would be needed to meet the minimal requirements?

**Comment by marcosmarxm** [comment]
> Hi @marcosmarxm, Thank you for the feedback! I’d be happy to work on adding more endpoints to enhance the connector’s usability. I'll get started right away and plan to have updates by the next checkpoint on Nov 5. Could you please let me know how many additional endpoints you think would be needed to meet the minimal requirements?

This is your responsibility to decide @faria-karim-porna at the moment a single endpoint is not generic enough to provide a large use cases. Moving review to Nov-14. Ping me if you have any updates.

**Comment by marcosmarxm** [comment]
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

Make sure you have pagination properly working, the API doesn't have pagination please left a comment making my review easier.
Make sure have a square svg icon
Make sure credentials are valid.

**Comment by faria-karim-porna** [comment]
Hi @marcosmarxm please check this modification. I have added more API endpoints.

Pagination is working perfectly from my side. Here is the screenshot:
tmdb-pagination

**Comment by marcosmarxm** [comment]
Declined because already exists: https://docs.airbyte.com/integrations/sources/tmdb.

**Pull request closed without merging**
