### PR TITLE
🎉 Source Shopify: Add a graphql products stream

### PR DESCRIPTION
**Pull request by PhilipCorr**
## What
Shopify have a graphQL admin API in addition to the rest admin API. Some data is only available via the graphQL api. This PR adds support for this graphQL API. It also adds the first graphQL stream for fetching products. 

There is a products stream that uses the rest API already. However, some product data can only be fetched via the use of the graphQL API. In this PR I've added the `ProductsGraphQl` stream. I've named it like this to separate it from the pre-existing rest API `Products` stream.

## How
I followed the github source as an example. This already has streams that use the github graphql api.
The main thing I copied from the github source is the use of the python `sgqlc` package.

To make full use of this package I ran the following command to generate the json representation of shopify's graphql api:
```
 python3 -m sgqlc.introspection --exclude-deprecated --exclude-description -H "X-Shopify-Access-Token: shpat_123abc" https://<my_shop>.myshopify.com/admin/api/2022-10/graphql.json shopify_schema.json
```

I then ran the folloiwng command to convert that json representation to python:
```
sgqlc-codegen schema shopify_schema.json shopify_schema.py
```
The resulting `shopify_schema.py` file is being added in this PR.
This follows the examples in the [sgqlc documentation](https://github.com/profusion/sgqlc) closely.

## Recommended reading order
1. As per the above comments, the `shopify_schema.py` file was auto-generated. Hence why it is so long.
2. `setup.py`. This was updated to add the `sgqlc` depencency.
3. `source.py`. This shows the added graphql stream.
4. `graphql.py`. This builds up the graphql queries that get sent to the graphql endpoint.
5.  `utils.py`. Here, `ShopifyRateLimiter` was updated as the graphql api uses slightly different rate limiting compared to the rest api.
6. `test_control_rate_limit.py`. This adds tests for the new graphql rate limiting.

## 🚨 User Impact 🚨
There should not be any breaking changes. The changes here are intended to be backwards compatible.

In order to simplify the changes here and to get quicker feedback, the fields requested via this stream are hard-coded as seen in `graphql.py`. Hard coding them like this follows how the GitHub source is currently implemented. 
I'm open to suggestions as to how this should be handled.
Maybe we should use the catalog here to specify which fields are included in the graphql query.

## Pre-merge Checklist
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>
I had to add pytest-mock here. I'm not sure how these tests were working in the past without that dependency.

```
TEST_REQUIREMENTS = [
    "pytest~=6.1",
    "pytest-mock~=3.10.0",
    "requests-mock",
    "source-acceptance-test",
]
```

Output:
```
(virtualenv) ➜  source-shopify git:(master) ✗ python -m pytest unit_tests               
===================================================================================================================================================================================================== test session starts ======================================================================================================================================================================================================
platform darwin -- Python 3.9.11, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/phil/Repos/airbyte/airbyte-integrations/connectors/source-shopify/virtualenv/bin/python
cachedir: .pytest_cache
rootdir: /Users/phil/Repos/airbyte, configfile: pytest.ini
plugins: mock-3.10.0, requests-mock-1.10.0
collected 72 items                                                                                                                                                                                                                                                                                                                                                                                                             

unit_tests/test_auth.py::test_shopify_authenticator_access_token PASSED
unit_tests/test_auth.py::test_shopify_authenticator_api_password PASSED
unit_tests/test_auth.py::test_raises_notimplemented_auth <ExceptionInfo for raises contextmanager>
{"type": "LOG", "log": {"level": "ERROR", "message": "Not implemented Auth method = not_implemented_auth_method"}}
PASSED
unit_tests/test_cached_stream_state.py::test_full_refresh[Sync Started. Parent.] PASSED
unit_tests/test_cached_stream_state.py::test_full_refresh[Sync Started. Child.] PASSED
unit_tests/test_cached_stream_state.py::test_incremental_sync[Sync Started. Parent] PASSED
unit_tests/test_cached_stream_state.py::test_incremental_sync[Sync Started. Child] PASSED
unit_tests/test_cached_stream_state.py::test_incremental_sync[Sync in progress. Parent] PASSED
unit_tests/test_cached_stream_state.py::test_incremental_sync[Sync in progress. Child] PASSED
unit_tests/test_control_rate_limit.py::test_rest_api_with_unknown_load PASSED
unit_tests/test_control_rate_limit.py::test_rest_api_with_low_load PASSED
unit_tests/test_control_rate_limit.py::test_rest_api_with_mid_load PASSED
unit_tests/test_control_rate_limit.py::test_rest_api_with_high_load PASSED
unit_tests/test_control_rate_limit.py::test_graphql_api_with_unknown_load PASSED
unit_tests/test_control_rate_limit.py::test_graphql_api_with_low_load PASSED
unit_tests/test_control_rate_limit.py::test_graphql_api_with_mid_load PASSED
unit_tests/test_control_rate_limit.py::test_graphql_api_with_high_load PASSED
unit_tests/test_source.py::test_customers_path[Articles-None-articles.json] PASSED
unit_tests/test_source.py::test_customers_path[Blogs-None-blogs.json] PASSED
unit_tests/test_source.py::test_customers_path[MetafieldBlogs-stream_slice2-blogs/123/metafields.json] PASSED
unit_tests/test_source.py::test_customers_path[MetafieldArticles-stream_slice3-articles/123/metafields.json] PASSED
unit_tests/test_source.py::test_customers_path[MetafieldCustomers-stream_slice4-customers/123/metafields.json] PASSED
unit_tests/test_source.py::test_customers_path[MetafieldOrders-stream_slice5-orders/123/metafields.json] PASSED
unit_tests/test_source.py::test_customers_path[MetafieldDraftOrders-stream_slice6-draft_orders/123/metafields.json] PASSED
unit_tests/test_source.py::test_customers_path[MetafieldProducts-stream_slice7-products/123/metafields.json] PASSED
unit_tests/test_source.py::test_customers_path[MetafieldProductVariants-stream_slice8-variants/123/metafields.json] PASSED
unit_tests/test_source.py::test_customers_path[MetafieldSmartCollections-stream_slice9-smart_collections/123/metafields.json] PASSED
unit_tests/test_source.py::test_customers_path[MetafieldCollections-stream_slice10-collections/123/metafields.json] PASSED
unit_tests/test_source.py::test_customers_path[MetafieldPages-stream_slice11-pages/123/metafields.json] PASSED
unit_tests/test_source.py::test_customers_path[MetafieldLocations-stream_slice12-locations/123/metafields.json] PASSED
unit_tests/test_source.py::test_customers_path[MetafieldShops-None-metafields.json] PASSED
unit_tests/test_source.py::test_customers_path[ProductImages-stream_slice14-products/123/images.json] PASSED
unit_tests/test_source.py::test_customers_path[ProductVariants-stream_slice15-products/123/variants.json] PASSED
unit_tests/test_source.py::test_customers_path[Customers-None-customers.json] PASSED
unit_tests/test_source.py::test_customers_path[Orders-None-orders.json] PASSED
unit_tests/test_source.py::test_customers_path[DraftOrders-None-draft_orders.json] PASSED
unit_tests/test_source.py::test_customers_path[Products-None-products.json] PASSED
unit_tests/test_source.py::test_customers_path[AbandonedCheckouts-None-checkouts.json] PASSED
unit_tests/test_source.py::test_customers_path[Collects-None-collects.json] PASSED
unit_tests/test_source.py::test_customers_path[TenderTransactions-None-tender_transactions.json] PASSED
unit_tests/test_source.py::test_customers_path[Pages-None-pages.json] PASSED
unit_tests/test_source.py::test_customers_path[PriceRules-None-price_rules.json] PASSED
unit_tests/test_source.py::test_customers_path[Locations-None-locations.json] PASSED
unit_tests/test_source.py::test_customers_path[Shop-None-shop.json] PASSED
unit_tests/test_source.py::test_customers_path[CustomCollections-None-custom_collections.json] PASSED
unit_tests/test_source.py::test_customers_path_with_stream_slice_param[OrderRefunds-stream_slice0-orders/12345/refunds.json] PASSED
unit_tests/test_source.py::test_customers_path_with_stream_slice_param[OrderRisks-stream_slice1-orders/12345/risks.json] PASSED
unit_tests/test_source.py::test_customers_path_with_stream_slice_param[Transactions-stream_slice2-orders/12345/transactions.json] PASSED
unit_tests/test_source.py::test_customers_path_with_stream_slice_param[DiscountCodes-stream_slice3-price_rules/12345/discount_codes.json] PASSED
unit_tests/test_source.py::test_customers_path_with_stream_slice_param[InventoryLevels-stream_slice4-locations/12345/inventory_levels.json] PASSED
unit_tests/test_source.py::test_customers_path_with_stream_slice_param[FulfillmentOrders-stream_slice5-orders/12345/fulfillment_orders.json] PASSED
unit_tests/test_source.py::test_customers_path_with_stream_slice_param[Fulfillments-stream_slice6-orders/12345/fulfillments.json] PASSED
unit_tests/test_source.py::test_check_connection PASSED
unit_tests/test_source.py::test_read_records {"type": "LOG", "log": {"level": "INFO", "message": "Reading order_refunds for order_id: None"}}
PASSED
unit_tests/test_source.py::test_request_params[OrderRefunds-expected0] PASSED
unit_tests/test_source.py::test_request_params[Orders-expected1] PASSED
unit_tests/test_source.py::test_request_params[AbandonedCheckouts-expected2] PASSED
unit_tests/test_source.py::test_get_updated_state PASSED
unit_tests/test_transform.py::test_enforcer_correct_type[transform_object0-schema0-checks0] PASSED
unit_tests/test_transform.py::test_enforcer_correct_type[transform_object1-schema1-checks1] PASSED
unit_tests/test_transform.py::test_enforcer_correct_type[transform_object2-schema2-checks2] PASSED
unit_tests/test_transform.py::test_enforcer_correct_type[transform_object3-schema3-checks3] PASSED
unit_tests/test_transform.py::test_enforcer_string_to_number[transform_object0-schema0-checks0] PASSED
unit_tests/test_transform.py::test_enforcer_string_to_number[transform_object1-schema1-checks1] PASSED
unit_tests/test_transform.py::test_enforcer_nested_object[transform_object0-schema0-checks0] PASSED
unit_tests/test_transform.py::test_enforcer_nested_array[transform_object0-schema0-checks0] PASSED
unit_tests/test_transform.py::test_enforcer_nested_array[transform_object1-schema1-checks1] PASSED
unit_tests/test_transform.py::test_enforcer_string_to_number_in_array[transform_object0-schema0-checks0] PASSED
unit_tests/unit_test.py::test_get_next_page_token PASSED
unit_tests/unit_test.py::test_privileges_validation PASSED
unit_tests/unit_test.py::test_unavailable_stream {"type": "LOG", "log": {"level": "WARN", "message": "Stream `balance_transactions` is not available, skipping..."}}
PASSED
unit_tests/unit_test.py::test_filter_records_newer_than_state {"type": "LOG", "log": {"level": "WARN", "message": "Stream `discount_codes`, Record ID: `2` missing cursor field: updated_at, record is emitted without state comparison"}}
{"type": "LOG", "log": {"level": "WARN", "message": "Stream `discount_codes`, Record ID: `4` cursor value is: None, record is emitted without state comparison"}}
PASSED

======================================================================================================================================================================================================= warnings summary =======================================================================================================================================================================================================
source_shopify/auth.py:14
  /Users/phil/Repos/airbyte/airbyte-integrations/connectors/source-shopify/source_shopify/auth.py:14: DeprecationWarning: Call to deprecated class AirbyteLogger. (Use logging.getLogger('airbyte') instead) -- Deprecated since version 0.1.47.
    logger = AirbyteLogger()

virtualenv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py:43: 2 warnings
airbyte-integrations/connectors/source-shopify/unit_tests/test_source.py: 43 warnings
airbyte-integrations/connectors/source-shopify/unit_tests/unit_test.py: 43 warnings
  /Users/phil/Repos/airbyte/airbyte-integrations/connectors/source-shopify/virtualenv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py:43: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    self._authenticator: HttpAuthenticator = NoAuth()

virtualenv/lib/python3.9/site-packages/deprecated/classic.py:173: 2 warnings
airbyte-integrations/connectors/source-shopify/unit_tests/test_source.py: 43 warnings
airbyte-integrations/connectors/source-shopify/unit_tests/unit_test.py: 43 warnings
  /Users/phil/Repos/airbyte/airbyte-integrations/connectors/source-shopify/virtualenv/lib/python3.9/site-packages/deprecated/classic.py:173: DeprecationWarning: Call to deprecated class HttpAuthenticator. (Use requests.auth.AuthBase instead) -- Deprecated since version 0.1.20.
    return old_new1(cls, *args, **kwargs)

airbyte-integrations/connectors/source-shopify/unit_tests/unit_test.py::test_unavailable_stream
  /Users/phil/Repos/airbyte/airbyte-integrations/connectors/source-shopify/source_shopify/source.py:91: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    self.logger.warn(f"Stream `{self.name}` is not available, skipping...")

airbyte-integrations/connectors/source-shopify/unit_tests/unit_test.py::test_filter_records_newer_than_state
  /Users/phil/Repos/airbyte/airbyte-integrations/connectors/source-shopify/source_shopify/source.py:157: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    self.logger.warn(

airbyte-integrations/connectors/source-shopify/unit_tests/unit_test.py::test_filter_records_newer_than_state
  /Users/phil/Repos/airbyte/airbyte-integrations/connectors/source-shopify/source_shopify/source.py:151: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    self.logger.warn(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=============================================================================================================================================================================================== 72 passed, 180 warnings in 1.22s ===============================================================================================================================================================================================
(virtualenv) ➜  source-shopify git:(master) ✗ 

```
</details>

<details><summary><strong>Integration</strong></summary>

There doesn't seem to be any integration tests here
```
(virtualenv) ➜  source-shopify git:(master) ✗ python3 -m pytest integration_tests
===================================================================================================================================================================================================== test session starts ======================================================================================================================================================================================================
platform darwin -- Python 3.9.11, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/phil/Repos/airbyte/airbyte-integrations/connectors/source-shopify/virtualenv/bin/python3
cachedir: .pytest_cache
rootdir: /Users/phil/Repos/airbyte, configfile: pytest.ini
plugins: mock-3.10.0, requests-mock-1.10.0
collected 0 items                                                                                                                                                                                                                                                                                                                                                                                                              

==================================================================================================================================================================================================== no tests ran in 0.01s =====================================================================================================================================================================================================
(virtualenv) ➜  source-shopify git:(master) ✗ 

```
</details>

<details><summary><strong>Acceptance</strong></summary>

Acceptance tests are passing except for 5 of them which are because the credentials I'm using here don't have access scope to include the articles stream. I haven't made changes to that stream so I expect all tests should pass when ran by a member of the airbyte team using airbyte credentials.

```
=================================================================================================================================================================================================== short test summary info ====================================================================================================================================================================================================
FAILED ../../bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestBasicRead::test_read[inputs0] - Failed: The articles stream you have set in /Users/phil/Repos/phil_github/airbyte/airbyte-integrations/connectors/source-shopify/integration_tests/configured_catalog.json is not part of the discovered_catalog
FAILED ../../bases/source-acceptance-test/source_acceptance_test/tests/test_full_refresh.py::TestFullRefresh::test_sequential_reads[inputs0] - Failed: The articles stream you have set in /Users/phil/Repos/phil_github/airbyte/airbyte-integrations/connectors/source-shopify/integration_tests/configured_catalog.json is not part of the discovered_catalog
FAILED ../../bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py::TestIncremental::test_two_sequential_reads[inputs0] - Failed: The articles stream you have set in /Users/phil/Repos/phil_github/airbyte/airbyte-integrations/connectors/source-shopify/integration_tests/configured_catalog.json is not part of the discovered_catalog
FAILED ../../bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py::TestIncremental::test_read_sequential_slices[inputs0] - Failed: The articles stream you have set in /Users/phil/Repos/phil_github/airbyte/airbyte-integrations/connectors/source-shopify/integration_tests/configured_catalog.json is not part of the discovered_catalog
FAILED ../../bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py::TestIncremental::test_state_with_abnormally_large_values[inputs0] - Failed: The articles stream you have set in /Users/phil/Repos/phil_github/airbyte/airbyte-integrations/connectors/source-shopify/integration_tests/configured_catalog.json is not part of the discovered_catalog

Results (99.99s):
      48 passed
       5 error

```
</details>

### CODE REVIEW

**Comment by andresbravog** [comment]
@sajarin I'm happy to continue my Review here

**Review by andresbravog — APPROVED** [review]
👏  Well done @PhilipCorr everything seems correct to me as in the original PR

**Comment by andresbravog** [comment]
@sajarin could you assign this PR to me? thanks.

@PhilipCorr you have some broken tests could you check them out?

**Comment by PhilipCorr** [comment]
Thanks @andresbravog, I'll try and get those tests sorted today!

**Comment by andresbravog** [comment]
Thanks! details are [here](https://github.com/airbytehq/airbyte/actions/runs/3566503222/jobs/5993070483#step:11:2689)

**Comment by PhilipCorr** [comment]
These tests should be passing now. I've added my acceptance test output to the Acceptance section of the PR body above.

**Comment by PhilipCorr** [comment]
Thanks @sajarin! Those tests should be passing now.

**Review by sajarin — APPROVED** [review]

**Comment by sajarin** [comment]
Thanks @PhilipCorr for the PR and thanks for @andresbravog for the review! :)

**Pull request merged**
