### PR TITLE
Ldata 278 add new packs to seed

### PR DESCRIPTION
**Pull request by dolphinxyz**
https://onefootball.atlassian.net/jira/software/projects/LDATA/boards/336?assignee=62cea5d8c537f460d44570a5&selectedIssue=LDATA-278

### CODE REVIEW

**Comment by dolphinxyz** [comment]
@sherifnada @cgardens I made a mistake and I opened a PR on this repo. Is there a way to fully delete it? I would be really grateful

**Comment by sherifnada** [comment]
@dolphinxyz can you clarify why? I think we can do it but we'll need to get in touch with GH support

**Comment by dolphinxyz** [comment]
@sherifnada thanks for your quick reply.

I forked Airbyte repo, and unfortunately, instead of pushing my code to my fork, I did it to the main one.

All the code I pushed is irrelevant to you and somehow private, would be great if you could get rid of it.

**Comment by sherifnada** [comment]
@marcosmarxm could you help make this PR be completely removed?

**Comment by marcosmarxm** [comment]
@sherifnada @dolphinxyz https://stackoverflow.com/a/18318431/16870489
@supertopher I'm not an admin anymore, just checking if you could do this.

**Comment by supertopher** [comment]
I think deleting the PR is extreme.  I'll open the request just the same.

@dolphinxyz if you want us to delete this to save some intended-to-be closed source code from the world I'm happy to help.  
if this is for the sake of making our repo look clean, opening a ticket with GitHub seems overkill.

@marcosmarxm I don't think being an admin here gives me extra powers, though I'm sure it won't hurt in the ticket

**Comment by supertopher** [comment]
ticket is open, no idea what to expect on timing.  I'm guessing this thread won't be useful for communication after that

**Pull request closed without merging**
