### PR TITLE
Source Amazon Ads: fix bug with handling: "Report date is too far in the past." (partial revert of #20662)

### PR DESCRIPTION
**Pull request by grubberr**
## What
Try to fix this oncall https://github.com/airbytehq/oncall/issues/1270

Partially revert this PR https://github.com/airbytehq/airbyte/pull/20662
We don't need that additional "check" command validation because it can break the already existing sync.

Initial idea was to validate only newly created sync
but I forget that we run the "check" command for already existing sync too.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [x] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [x] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Review by alafanechere — APPROVED** [review]
Thanks for the fix.

**Comment by octavia-approvington** [comment]
Enough! Let's do this <br/> goooooo!

**Comment by alafanechere** [comment]
It looks like the approve-and-merge command can't bypass the required check success.

**Comment by octavia-approvington** [comment]
What are we doing again? <br/> merge and squash

**Comment by supertopher** [comment]
/approve-and-merge reason="This PR is fixing a P0 issue on the Amazon ads connector. I'm confident the CI checks failures are not related to the changes in this PR and I want to release the fix asap"

trying without auto merge enabled.  (also maybe this doesn't break the slash command ¯\_(ツ)_/¯

**Comment by octavia-approvington** [comment]
This looks fine!  <br/> Merged! <br/> Imagine it being fine

**Comment by supertopher** [comment]
the bot is broken, but human topher merged this while we figure it out.  I think I'm going to disable auto-merge short term

**Pull request merged**
