### PR TITLE
mysql-source:fix tinyint unsigned handling

### PR DESCRIPTION
**Pull request by subodh1810**
Issue : https://github.com/airbytehq/airbyte/issues/17510

When we upgraded the debezium version from 1.4.2 to 1.9, the default `TinyIntOneToBooleanConverter` that is provided by debezium started converting the values for TINYINT unsigned to boolean values as well. The old version (1.4) only converted the values for TINYINT(1).
We recognise TINYINT UNSIGNED as INTEGER in the catalog and so while trying to map the boolean values `true`/`false` to INTEGER type, normalisation started failing. 

We can not identify TINYINT UNSIGNED as boolean is because it lacks the length information. MySQL8 doesn't show the length of tinyint unsigned type.
For instance take a look at the following table structure.
I used the following query to create the table `create table blah_3 (id int primary key, col_1 tinyint(1), col_2 tinyint(1) unsigned, col_3 tinyint(3), col_4 tinyint(3) unsigned);`.

If you look at the information schema details of the column types listed below and compare `col_1` which is `tinyint(1)` and `col_2` which is `tinyint(1) unsigned` , you will see that the `COLUMN_TYPE` info of both the columns is different. One clarifies its a tinyint(1) while the other one doesnt.
```
mysql> select * FROM INFORMATION_SCHEMA.COLUMNS where TABLE_SCHEMA = "models_schema" AND TABLE_NAME = "blah_3" \G;
*************************** 1. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: models_schema
              TABLE_NAME: blah_3
             COLUMN_NAME: id
        ORDINAL_POSITION: 1
          COLUMN_DEFAULT: NULL
             IS_NULLABLE: NO
               DATA_TYPE: int
CHARACTER_MAXIMUM_LENGTH: NULL
  CHARACTER_OCTET_LENGTH: NULL
       NUMERIC_PRECISION: 10
           NUMERIC_SCALE: 0
      DATETIME_PRECISION: NULL
      CHARACTER_SET_NAME: NULL
          COLLATION_NAME: NULL
             COLUMN_TYPE: int
              COLUMN_KEY: PRI
                   EXTRA: 
              PRIVILEGES: select,insert,update,references
          COLUMN_COMMENT: 
   GENERATION_EXPRESSION: 
                  SRS_ID: NULL
*************************** 2. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: models_schema
              TABLE_NAME: blah_3
             COLUMN_NAME: col_1
        ORDINAL_POSITION: 2
          COLUMN_DEFAULT: NULL
             IS_NULLABLE: YES
               DATA_TYPE: tinyint
CHARACTER_MAXIMUM_LENGTH: NULL
  CHARACTER_OCTET_LENGTH: NULL
       NUMERIC_PRECISION: 3
           NUMERIC_SCALE: 0
      DATETIME_PRECISION: NULL
      CHARACTER_SET_NAME: NULL
          COLLATION_NAME: NULL
             COLUMN_TYPE: tinyint(1)
              COLUMN_KEY: 
                   EXTRA: 
              PRIVILEGES: select,insert,update,references
          COLUMN_COMMENT: 
   GENERATION_EXPRESSION: 
                  SRS_ID: NULL
*************************** 3. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: models_schema
              TABLE_NAME: blah_3
             COLUMN_NAME: col_2
        ORDINAL_POSITION: 3
          COLUMN_DEFAULT: NULL
             IS_NULLABLE: YES
               DATA_TYPE: tinyint
CHARACTER_MAXIMUM_LENGTH: NULL
  CHARACTER_OCTET_LENGTH: NULL
       NUMERIC_PRECISION: 3
           NUMERIC_SCALE: 0
      DATETIME_PRECISION: NULL
      CHARACTER_SET_NAME: NULL
          COLLATION_NAME: NULL
             COLUMN_TYPE: tinyint unsigned
              COLUMN_KEY: 
                   EXTRA: 
              PRIVILEGES: select,insert,update,references
          COLUMN_COMMENT: 
   GENERATION_EXPRESSION: 
                  SRS_ID: NULL
*************************** 4. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: models_schema
              TABLE_NAME: blah_3
             COLUMN_NAME: col_3
        ORDINAL_POSITION: 4
          COLUMN_DEFAULT: NULL
             IS_NULLABLE: YES
               DATA_TYPE: tinyint
CHARACTER_MAXIMUM_LENGTH: NULL
  CHARACTER_OCTET_LENGTH: NULL
       NUMERIC_PRECISION: 3
           NUMERIC_SCALE: 0
      DATETIME_PRECISION: NULL
      CHARACTER_SET_NAME: NULL
          COLLATION_NAME: NULL
             COLUMN_TYPE: tinyint
              COLUMN_KEY: 
                   EXTRA: 
              PRIVILEGES: select,insert,update,references
          COLUMN_COMMENT: 
   GENERATION_EXPRESSION: 
                  SRS_ID: NULL
*************************** 5. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: models_schema
              TABLE_NAME: blah_3
             COLUMN_NAME: col_4
        ORDINAL_POSITION: 5
          COLUMN_DEFAULT: NULL
             IS_NULLABLE: YES
               DATA_TYPE: tinyint
CHARACTER_MAXIMUM_LENGTH: NULL
  CHARACTER_OCTET_LENGTH: NULL
       NUMERIC_PRECISION: 3
           NUMERIC_SCALE: 0
      DATETIME_PRECISION: NULL
      CHARACTER_SET_NAME: NULL
          COLLATION_NAME: NULL
             COLUMN_TYPE: tinyint unsigned
              COLUMN_KEY: 
                   EXTRA: 
              PRIVILEGES: select,insert,update,references
          COLUMN_COMMENT: 
   GENERATION_EXPRESSION: 
                  SRS_ID: NULL
5 rows in set (0.10 sec)

mysql> desc blah_3;
+-------+------------------+------+-----+---------+-------+
| Field | Type             | Null | Key | Default | Extra |
+-------+------------------+------+-----+---------+-------+
| id    | int              | NO   | PRI | NULL    |       |
| col_1 | tinyint(1)       | YES  |     | NULL    |       |
| col_2 | tinyint unsigned | YES  |     | NULL    |       |
| col_3 | tinyint          | YES  |     | NULL    |       |
| col_4 | tinyint unsigned | YES  |     | NULL    |       |
+-------+------------------+------+-----+---------+-------+
5 rows in set (0.01 sec)
```

This PR brings back the old behaviour and only converts tinyint column types to boolean. This also updates the document.

### CODE REVIEW

**Comment by rodireich** [comment]
Great find!

**Review by rodireich — APPROVED** [review]

**Comment by danieldiamond** [comment]
@subodh1810 awesome work! send it 🚀

**Review by akashkulk — APPROVED** [review]

**Pull request merged**
