### PR TITLE
BigQuery destination : Enable DAT tests

### PR DESCRIPTION
**Pull request by DoNotPanicUA**
## What
Enable DAT tests for BigQuery Destination where it's possible.
Found issues:

- airbytehq/airbyte-internal-issues#636
- airbytehq/airbyte#13154

### CODE REVIEW

**Comment by DoNotPanicUA** [comment]
#9444

**Review by Tr1985 — APPROVED** [review]

**Review by sashaNeshcheret — APPROVED** [review]

**Pull request merged**
