### PR TITLE
:rotating_light: :rotating_light: Source Recharge: fix stream schema

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/oncall/issues/1879

## How
Change date type of the `shopify_variant_id_not_found` field in the `Charges` stream from `integer` to `string`

## 🚨 User Impact 🚨
This is a potentially breaking change because the data type is changed

### CODE REVIEW

**Comment by davydov-d** [comment]
I'll prepare a breaking changes doc soon

**Comment by octavia-squidington-iii** [comment]
##  source-recharge test report (commit [`90719068da`](https://github.com/airbytehq/airbyte/pull/27612/commits/90719068da70e24cd896ae13dbb56995c27955e6)) - ❌

⏲️  Total pipeline duration: 437 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-recharge/metadata.yaml | ✅        |
| Connector version semver check.                                        | ✅        |
| Connector version increment check.                                     | ✅        |
| QA checks                                                              | ✅        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-recharge docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Acceptance tests                                                       | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/ddavydov_#1879-source-recharge-fix-schema/1687443684/90719068da70e24cd896ae13dbb56995c27955e6/source-recharge/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-recharge test
```

**Comment by octavia-squidington-iii** [comment]
##  source-recharge test report (commit [`da0b636b29`](https://github.com/airbytehq/airbyte/pull/27612/commits/da0b636b29942d2d3ed49ef39fd814313ffd9bc1)) - ❌

⏲️  Total pipeline duration: 415 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-recharge/metadata.yaml | ✅        |
| Connector version semver check.                                        | ✅        |
| Connector version increment check.                                     | ✅        |
| QA checks                                                              | ✅        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-recharge docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Acceptance tests                                                       | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/ddavydov_#1879-source-recharge-fix-schema/1687444216/da0b636b29942d2d3ed49ef39fd814313ffd9bc1/source-recharge/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-recharge test
```

**Review by lazebnyi — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-recharge test report (commit [`c5765ae6b0`](https://github.com/airbytehq/airbyte/pull/27612/commits/c5765ae6b0913a65f3a3ecb6efce698c3ae88c8c)) - ❌

⏲️  Total pipeline duration: 145 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-recharge/metadata.yaml | ✅        |
| Connector version semver check.                                        | ✅        |
| Connector version increment check.                                     | ✅        |
| QA checks                                                              | ✅        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-recharge docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Acceptance tests                                                       | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/ddavydov_#1879-source-recharge-fix-schema/1687460600/c5765ae6b0913a65f3a3ecb6efce698c3ae88c8c/source-recharge/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-recharge test
```

**Comment by octavia-squidington-iii** [comment]
##  source-recharge test report (commit [`d82bae5022`](https://github.com/airbytehq/airbyte/pull/27612/commits/d82bae5022f2c088c8bba0d174ef9675c6e7c43c)) - ✅

⏲️  Total pipeline duration: 451 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-recharge/metadata.yaml | ✅        |
| Connector version semver check.                                        | ✅        |
| Connector version increment check.                                     | ✅        |
| QA checks                                                              | ✅        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-recharge docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/ddavydov_#1879-source-recharge-fix-schema/1687501113/d82bae5022f2c088c8bba0d174ef9675c6e7c43c/source-recharge/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-recharge test
```

**Comment by octavia-squidington-iii** [comment]
##  source-recharge test report (commit [`33a5045a06`](https://github.com/airbytehq/airbyte/pull/27612/commits/33a5045a060c13cedf97169d518280bf98f95f33)) - ✅

⏲️  Total pipeline duration: 1192 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-recharge/metadata.yaml | ✅        |
| Connector version semver check.                                        | ✅        |
| Connector version increment check.                                     | ✅        |
| QA checks                                                              | ✅        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-recharge docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/ddavydov_1879-source-recharge-fix-schema/1687507303/33a5045a060c13cedf97169d518280bf98f95f33/source-recharge/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-recharge test
```

**Comment by bnchrch** [comment]
@davydov-d Would you mind linking the breaking change doc?

**Comment by davydov-d** [comment]
@bnchrch yep, sorru for the delay
https://docs.google.com/document/d/13DpMKwHV-xkmX7n5UhYL40IBQEyd8FnIBYRj-up0mbU/edit

**Comment by bnchrch** [comment]
No worries! Also @davydov-d I need access (ben@airbyte.io)

**Comment by davydov-d** [comment]
@bnchrch done!

**Review by bnchrch — APPROVED** [review]
Thanks @davydov-d 

Everything looks great.

Ill leave it to you to merge when TCS has a release date and its passed

**Comment by jnr0790** [comment]
@davydov-d let's schedule this for July 11th at 4 pm UTC. I'll get comms sent to the users today.

**Comment by octavia-squidington-iii** [comment]
##  source-recharge test report (commit [`dfc6f9daad`](https://github.com/airbytehq/airbyte/pull/27612/commits/dfc6f9daad8b83c9da21a36d1e70f51ddbf4f406)) - ❌

⏲️  Total pipeline duration: 347 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-recharge/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ✅        |
| QA checks                                                              | ✅        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-recharge docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Acceptance tests                                                       | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/ddavydov_1879-source-recharge-fix-schema/1687806625/dfc6f9daad8b83c9da21a36d1e70f51ddbf4f406/source-recharge/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-recharge test
```

**Comment by octavia-squidington-iii** [comment]
##  source-recharge test report (commit [`198c0551b2`](https://github.com/airbytehq/airbyte/pull/27612/commits/198c0551b2bec4af2956d4921653d8453efb96b0)) - ✅

⏲️  Total pipeline duration: 331 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-recharge/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ✅        |
| QA checks                                                              | ✅        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-recharge docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/ddavydov_1879-source-recharge-fix-schema/1687807264/198c0551b2bec4af2956d4921653d8453efb96b0/source-recharge/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-recharge test
```

**Pull request merged**
