### PR TITLE
🐛 Source Delighted: fix `Date Since` date-format bug in UI

### PR DESCRIPTION
**Pull request by bazarnov**
## What
Resolving: https://github.com/airbytehq/oncall/issues/1623

## How
- changed the pattern to catch  the  RFC3339 format, which UI uses for the date picker
- updated `manifest.yaml` to convert the input config["since"] from 2 formats (old and new) and convert it to the right format needed for the slices.

## 🚨 User Impact 🚨
No impact is expected since backward compatibility is supported for this issue.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Comment by bazarnov** [comment]
@airbytehq/connector-extensibility Please check this fix, since with the new `Date Picker` there are issues with selecting the date in the format of `RFC3339` but the connector expects a different input format. This might be a potential P0 in the future for all other connectors. 

The thing is that the date picker should be able to return the date in the format connector expects it, to support backward compatibility

**Review by evantahler — APPROVED** [review]
> No impact is expected since backward compatibility is supported for this issue.

Excellent!

Of note, this might be a good place to emit an airbyte control message to update the old format of the config to the new format so we don't need to keep `format_datetime()` around forever.  I'll write up a guide on that process later today!

**Comment by bazarnov** [comment]
> > No impact is expected since backward compatibility is supported for this issue.
> 
> Excellent!
> 
> Of note, this might be a good place to emit an airbyte control message to update the old format of the config to the new format so we don't need to keep `format_datetime()` around forever. I'll write up a guide on that process later today!

@evantahler please refer to this issue, so we have the context later on, thanks! Awesome!

**Pull request merged**
