### PR TITLE
✨Source KYVE: KYVE Mainnet support and generic normalisation

### PR DESCRIPTION
**Pull request by christopherbrumm**
## What
Create generic schemas to support all kind of KYVE data streams. Additionally, the URL base is updated with the new Mainnet endpoint.

## How
- Removing custom schemas for each runtime & updating core schema.
- Updating all static defined endpoints.
- Updating tests.

## Recommended reading order
1. `source_kyve/stream.py`
2. `source_kyve/spec.yaml`

## 🚨 User Impact 🚨
The users will be able to fetch data from KYVE's Mainnet. KYVE Network consists of three individual networks: Korellia is the `devnet` used for development purposes, Kaon is the `testnet` used for testing purposes, and `mainnet` is the official network. Although through Kaon and Korellia validated data can be used for development purposes, it is recommended to only trust the data validated on Mainnet.

Users can specify the endpoint which will be requested in KYVE-API URL Base. By default, the official KYVE mainnet
endpoint will be used, providing the data of [these pools](https://app.kyve.network/#/pools).

Besides this, the removal of the custom schemas for each runtime will change the normalisation for all kind of KYVE data, establishing a generic way of normalising.

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/resources/pull-requests-handbook)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

<details><summary><strong>Updating the Python CDK</strong></summary>

### Airbyter

Before merging:
- Pull Request description explains what problem it is solving
- Code change is unit tested
- Build and my-py check pass
- Smoke test the change on at least one affected connector
   - On Github: Run [this workflow](https://github.com/airbytehq/airbyte/actions/workflows/connectors_tests.yml), passing `--use-local-cdk --name=source-<connector>` as options
   - Locally: `airbyte-ci connectors --use-local-cdk --name=source-<connector> test`
- PR is reviewed and approved
      
After merging:
- [Publish the CDK](https://github.com/airbytehq/airbyte/actions/workflows/publish-cdk-command-manually.yml)
   - The CDK does not follow proper semantic versioning. Choose minor if this the change has significant user impact or is a breaking change. Choose patch otherwise.
   - Write a thoughtful changelog message so we know what was updated.
- Merge the platform PR that was auto-created for updating the Connector Builder's CDK version
   - This step is optional if the change does not affect the connector builder or declarative connectors.

</details>

### CODE REVIEW

**Comment by cgkournelos-rf** [comment]
This PR aims to resolve the issue https://github.com/airbytehq/airbyte/issues/29153

**Review by marcosmarxm — APPROVED** [review]
Thansk @cgkournelos-rf

**Comment by cgkournelos-rf** [comment]
@marcosmarxm The appearance of the KYVE logo will be also fixed with this PR?
Related issue #27562

**Comment by marcosmarxm** [comment]
> @marcosmarxm The appearance of the KYVE logo will be also fixed with this PR? Related issue #27562

Yes, it will appears. @christopherbrumm at the moment the codebase is freeze because of holidays and I'll be able to merge only next week your contribution. Thanks for the contribution and patience.

**Comment by christopherbrumm** [comment]
> > @marcosmarxm The appearance of the KYVE logo will be also fixed with this PR? Related issue #27562
> 
> Yes, it will appears. @christopherbrumm at the moment the codebase is freeze because of holidays and I'll be able to merge only next week your contribution. Thanks for the contribution and patience.

Thanks for the reply - we're really looking forward to finally see the PR merged!

However, not all checklist items are checked although we've included and updated everything required. It would be great to get some input in order to fix this to avoid having to wait longer than necessary for the merge.

**Pull request merged**
