### PR TITLE
🎉 New Source: Google Analytics v4 Service Account Only

### LINKED ISSUE #34258: Source Google Analytics (Universal Analytics): Enable in cloud
### Topic

_No response_

### Relevant information

See https://docs.google.com/document/d/1WWnaubjdryFioJHLJpWIVMSN3V2Ke14BqsPkjtQbr8Y/edit#heading=h.thypcey8g3u7 for more info

### PR DESCRIPTION
**Pull request by artem1205**
## What

Resolve https://github.com/airbytehq/airbyte/issues/34258

## How

enable in Cloud

## Recommended reading order
1. `airbyte-integrations/connectors/source-google-analytics-v4-service-account-only/metadata.yaml`

## 🚨 User Impact 🚨

no breaking changes

## Pre-merge Actions

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by evantahler** [comment]
Rather than make a whole new connector, which adds test and maintenance burden, I would suggest keeping just one connector and checking if we are running on cloud via environment variable.  If we are running on cloud, don't offer the oAuth option. 

cc @erohmensing, who has recently removed some of our strict-encrypt connectors, which are are similar sort of pattern - we had cloud-only connectors with a only a subtle auth or config change.

**Review by alafanechere — DISMISSED** [review]
+1 for @evantahler suggestion.
Adding a connector variant with inter connector dependency is additional maitainance and release flow complexity on our team end. 
Let us know if you have a strong reason to not use the `DEPLOYMENT_MODE` env var (which will be set to `cloud` when running on cloud) to adapt this connector behavior.

**Review by alafanechere — COMMENTED** [review]
Removing my request changes following discussion in this [thread](https://airbytehq-team.slack.com/archives/C02U9R3AF37/p1705594521435559).
There might be  additional work to consider on `airbyte-ci` in order to automatically publish the new connector when `source-google-analytics-v4` changes.

**Review by bazarnov — APPROVED** [review]

**Comment by artem1205** [comment]
@katmarkham , PR is ready, when would you like to deploy it?

**Review by katmarkham — APPROVED** [review]
thanks for updating the name!

**Pull request merged**
