### PR TITLE
🐛Destination Iceberg: Bump Iceberg to 1.5.2 and Spark to 3.5.1

### LINKED ISSUE #36441: [destination-iceberg] throws error on sync slf4j.Log4jLoggerFactory: method 'void <init>()' not found
### Connector Name

destination-iceberg

### Connector Version

0.1.5

### What step the error happened?

During the sync

### Relevant information

It set up Airbyte and Iceberg-Spark on a completely new system unsing docker.
I used the following scripts for installation: 
https://docs.airbyte.com/deploying-airbyte/local-deployment
https://iceberg.apache.org/spark-quickstart/

### Relevant log output

```shell
2024-03-25 09:52:50 destination > 2024-03-25 09:52:50 INFO i.a.c.i.b.IntegrationCliParser(parseOptions):126 - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2024-03-25 09:52:50 source > INFO main c.z.h.HikariDataSource(<init>):79 HikariPool-1 - Starting...
2024-03-25 09:52:50 destination > 2024-03-25 09:52:50 INFO i.a.c.i.b.IntegrationRunner(runInternal):132 - Running integration: io.airbyte.integrations.destination.iceberg.IcebergDestination
2024-03-25 09:52:50 destination > 2024-03-25 09:52:50 INFO i.a.c.i.b.IntegrationRunner(runInternal):133 - Command: WRITE
2024-03-25 09:52:50 destination > 2024-03-25 09:52:50 INFO i.a.c.i.b.IntegrationRunner(runInternal):134 - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2024-03-25 09:52:50 source > INFO main c.z.h.HikariDataSource(<init>):81 HikariPool-1 - Start completed.
2024-03-25 09:52:51 destination > 2024-03-25 09:52:51 WARN c.n.s.JsonMetaSchema(newValidator):278 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2024-03-25 09:52:51 destination > 2024-03-25 09:52:51 WARN c.n.s.JsonMetaSchema(newValidator):278 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2024-03-25 09:52:51 source > INFO main i.a.c.i.s.j.AbstractJdbcSource(logPreSyncDebugData):467 Data source product recognized as Microsoft SQL Server:13.00.4522
2024-03-25 09:52:51 source > INFO main i.a.i.s.m.MssqlQueryUtils(getIndexInfoForStreams):77 Discovering indexes for table "dbo"."Ledger"
2024-03-25 09:52:51 source > INFO main i.a.i.s.m.MssqlQueryUtils(getIndexInfoForStreams):88 Failed to get index for "dbo"."Ledger"
2024-03-25 09:52:51 source > INFO main i.a.c.i.s.j.AbstractJdbcSource(discoverInternal):169 Internal schemas to exclude: [spt_fallback_db, spt_monitor, cdc, spt_values, INFORMATION_SCHEMA, spt_fallback_usg, MSreplication_options, sys, spt_fallback_dev]
2024-03-25 09:52:51 destination > 2024-03-25 09:52:51 ERROR i.a.c.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.
2024-03-25 09:52:51 destination > java.lang.NoSuchMethodError: org.apache.logging.slf4j.Log4jLoggerFactory: method 'void <init>()' not found
2024-03-25 09:52:51 destination >         at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:53) ~[log4j-slf4j-impl-2.17.2.jar:2.17.2]
2024-03-25 09:52:51 destination >         at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:41) ~[log4j-slf4j-impl-2.17.2.jar:2.17.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.internal.Logging$.org$apache$spark$internal$Logging$$isLog4j2(Logging.scala:232) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.internal.Logging.initializeLogging(Logging.scala:129) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.internal.Logging.initializeLogIfNecessary(Logging.scala:115) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.internal.Logging.initializeLogIfNecessary$(Logging.scala:109) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.util.Utils$.initializeLogIfNecessary(Utils.scala:91) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.internal.Logging.initializeLogIfNecessary(Logging.scala:106) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.internal.Logging.initializeLogIfNecessary$(Logging.scala:105) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.util.Utils$.initializeLogIfNecessary(Utils.scala:91) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.internal.Logging.log(Logging.scala:53) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.internal.Logging.log$(Logging.scala:51) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.util.Utils$.log(Utils.scala:91) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.internal.Logging.logWarning(Logging.scala:73) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.internal.Logging.logWarning$(Logging.scala:72) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.util.Utils$.logWarning(Utils.scala:91) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.util.Utils$.$anonfun$findLocalInetAddress$1(Utils.scala:1067) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.util.Utils$.$anonfun$findLocalInetAddress$1$adapted(Utils.scala:1057) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at scala.collection.immutable.List.foreach(List.scala:333) ~[scala-library-2.13.10.jar:?]
2024-03-25 09:52:51 destination >         at org.apache.spark.util.Utils$.findLocalInetAddress(Utils.scala:1057) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.util.Utils$.localIpAddress$lzycompute(Utils.scala:1040) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.util.Utils$.localIpAddress(Utils.scala:1040) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at org.apache.spark.util.Utils$.$anonfun$localCanonicalHostName$1(Utils.scala:1097) ~[spark-core_2.13-3.3.2.jar:3.3.2]
2024-03-25 09:52:51 destination >         at scala.Option.getOrElse(Option.scala:201) ~[scala-library-2.13.10.jar:?]
```

### Contribute

- [x] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by nastra**
## What

This bumps the Iceberg version to the latest released (which is 1.5.2) one and aligns dependencies. It also updates Spark to 3.5.1.

Bumping the dependencies also fixes https://github.com/airbytehq/airbyte/issues/36441

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by nastra** [comment]
I've run all unit / integration tests locally and all of them passed. I also ran Airbyte locally and tested things where data was being streamed from Parquet files to the Iceberg REST catalog (as described in [this](https://tabular.io/blog/airbyte-tabular/) blogpost).

@marcosmarxm since you were reviewing earlier PRs for this destination, could you take a look please? This should also fix the error reported in #36441

**Comment by VeeraswamyGatta** [comment]
Azure related jars not added in the iceberg connector, tested for rest catalog, its failing with below error, any suggestions on fixing this issue

org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0) (destination-iceberg-write-52-4-updgj executor driver): java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.azurebfs.SecureAzureBlobFileSystem not found at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688) at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431) at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466) at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174) at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574) at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521) at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540) at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365) at org.apache.iceberg.hadoop.Util.getFs(Util.java:56) at org.apache.iceberg.hadoop.HadoopOutputFile.fromPath(HadoopOutputFile.java:53) at org.apache.iceberg.hadoop.HadoopFileIO.newOutputFile(HadoopFileIO.java:97) at org.apache.iceberg.io.ResolvingFileIO.newOutputFile(ResolvingFileIO.java:92) at

**Comment by nastra** [comment]
@VeeraswamyGatta I don't think Azure is currently supported by the Iceberg destination. Also it's not in the scope of this PR to add Azure support

**Comment by marcosmarxm** [comment]
@nastra thanks for the contribution. I need to check the current integration tests for destination iceberg, I think they're broken today.

**Comment by VeeraswamyGatta** [comment]
@nastra 

Thank you. If I want to include Azure support for this connector, do you have any suggestions on how to complete the Azure support?

**Comment by nastra** [comment]
> @nastra thanks for the contribution. I need to check the current integration tests for destination iceberg, I think they're broken today.

@marcosmarxm they were all passing for me locally when opening the PR. Do you have some details on what exactly is broken?

**Comment by nastra** [comment]
> @nastra
> 
> Thank you. If I want to include Azure support for this connector, do you have any suggestions on how to complete the Azure support?

@VeeraswamyGatta you would have to add a new storage config similar to how S3 is being handled

**Comment by VeeraswamyGatta** [comment]
@nastra Thank you

**Comment by marcosmarxm** [comment]
Running CI Tests.

**Comment by evantahler** [comment]
Can you confirm that `airbyte-ci` build works for the connector with these changes?  If so, yes, let's merge it!

**Comment by zspsole** [comment]
> Can you confirm that `airbyte-ci` build works for the connector with these changes? If so, yes, let's merge it!

Hey @evantahler, I'm that guy that said that tried it on Slack. Disclaimer: I'm not part of Airbyte team.

I checked out this PR branch and ran:
```
airbyte git:(bump-iceberg-to-1.5.2) ✗ ./gradlew :airbyte-integrations:connectors:destination-iceberg:buildConnectorImage
...
3: /Users/psole/Library/Caches/pypoetry/virtualenvs/pipelines-5vjYXjim-py3.10/bin/airbyte-ci connectors --name=destination-iceberg --disable-report-auto-open build --use-host-gradle-dist-tar
...
Build connector destination-iceberg - Build destination-iceberg docker image for platform(s) linux/arm64: ✅ was successful (duration: 13.76s)
Build connector destination-iceberg - Load airbyte/destination-iceberg:dev to the local docker host.: 🚀 Start Load airbyte/destination-iceberg:dev to the local docker host.
...
BUILD SUCCESSFUL in 58s
17 actionable tasks: 4 executed, 13 up-to-date
```

Then loaded the image on my kind k8s cluster and configured a destination connector using it.
Finally tested doing a Faker -> Iceberg-dev run using Nessie as a REST catalog and MinIO for the bucket.

Worked like a charm.

**Comment by evantahler** [comment]
Good enough for me!

**Comment by octavia-approvington** [comment]
Lets merge it <br/> sheep thumbs up

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
