### PR TITLE
mysql-source-cdc: enable compression logic for schema history

### PR DESCRIPTION
**Pull request by subodh1810**
This is a follow up PR for https://github.com/airbytehq/airbyte/pull/30289. As explained in the description of the  other PR this enables the compression logic which would allow emission of state with compressed schema history if it's greater than 3MB.

### CODE REVIEW

**Review by prateekmukhedkar — APPROVED** [review]

**Comment by subodh1810** [comment]
/legacy-test connector=connectors/source-mysql-strict-encrypt

**Comment by subodh1810** [comment]
/legacy-test connector=connectors/source-mysql-strict-encrypt

**Comment by octavia-approvington** [comment]
Lets do it! <br/> giddddy-up

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
