### PR TITLE
treat whitespace as null

### PR DESCRIPTION
**Pull request by jhsb25**
## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@jhsb25 can you update the description of your contribution and link to an existing issue? Thanks.

**Comment by natikgadzhi** [comment]
I don’t know if it’s that obvious that a white space (and not `,,`) should
be null. @girarda, what do you think?

**Review by girarda — CHANGES_REQUESTED** [review]
@jhsb25 is there a reason not to use the `null_values` with a whitespace as input value?

**Comment by jhsb25** [comment]
> @jhsb25 is there a reason not to use the `null_values` with a whitespace as input value?

I would happily use that but I'm struggling to understand how i can add a empty string to the input box none of the following work (empty string in double quotes, single quotes, \0)

image

**Pull request closed without merging**
