### PR TITLE
Exclude webapp from spotless styling

### PR DESCRIPTION
**Pull request by lmossman**
## What
This PR excludes the airbyte-webapp module from spotless styling. This module has its own auto-formatting plugins (e.g. prettier) and therefore does not also need spotless to run on it. 

Having both auto-formatters running on this module can lead to inconsistencies and broken builds, such as the situation described in this PR: https://github.com/airbytehq/airbyte/pull/16423

## How
Excludes the airbyte-webapp module from the spotless target in the top-level build.gradle.

## 🚨 User Impact 🚨
No user impact.

### CODE REVIEW

**Review by timroes — APPROVED** [review]
Code LGTM

**Comment by krishnaglick** [comment]
eslint and prettier are only configured in airbyte-webapp. We should copy those over. Or symlink them?

**Comment by lmossman** [comment]
@krishnaglick it looks like we already have some cypress-specific eslint configuration in airbyte-webapp-e2e-tests: https://github.com/airbytehq/airbyte/blob/f81c5aa6673db4d31112c906d9e5491131269d73/airbyte-webapp-e2e-tests/package.json#L11-L22
So I don't think we need to add more eslint configuration there. But I have added prettier to that module and symlinked the `.prettierrc.js` files as you recommended, and I ran prettier on that module and committed the changes to this PR

**Review by krishnaglick — APPROVED** [review]
LGTM!

**Pull request merged**
