### PR TITLE
MongoDB Source Connection String Fix

### PR DESCRIPTION
**Pull request by adhi-moves**
## What
When using MongoDB atlas, the connection was failing with the following error

```DefaultAirbyteStreamFactory(lambda$create$0):73 - W, [2021-05-14T16:07:49.870271 #8] WARN -- : MONGODB | Error running ismaster on <redacted server name>.mongodb.net:27017: SocketError: getaddrinfo: Name does not resolve
2021-05-14 16:08:50 INFO (/tmp/workspace/c0bdcfee-0a4d-48c0-8de1-560e9908d59b/0) DefaultAirbyteStreamFactory(internalLog):110 - [2021-05-14 16:07:50 +0000] WARN : | "MONGODB | Error running ismaster on <redacted server name>.mongodb.net:27017: SocketError: getaddrinfo: Name does not resolve"
2021-05-14 16:08:50 INFO (/tmp/workspace/c0bdcfee-0a4d-48c0-8de1-560e9908d59b/0) TemporalAttemptExecution(get):134 - Stopping cancellation check scheduling...
```

## How
Solution was achieved modifying the connection string by adding the  suffix to  and removing the port number.

This is a hack and a better solution would be to give the users option to provide the connection string
    directly, without having to enter their hostname, user, password, port, etc.

## Pre-merge Checklist
* [ ] _Run integration tests_
* [ ] _Publish Docker images_

## Recommended reading order
1. `test.java`
1. `component.ts`
1. the rest

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368070239349) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks @adhi-moves

**Comment by marcosmarxm** [comment]
@adhi-moves your solution is adequate with the ruby MongoDB driver. it's possible to check here: [Shared cluster connection](https://docs.mongodb.com/ruby-driver/master/tutorials/ruby-driver-create-client/index.html#sharded-cluster-connection), maybe we need to add an option `oneOf` in the `spec.json` file to select conn type: using srv uri or default conn string...
@sherifnada wdyt? 

from ruby mongodb docs:
`Mongo::Client.new("mongodb+srv://username:myRealPassword@cluster0.mongodb.net/test?w=majority")`
when using SRV you don't need to specify the ports, this is correct @adhi-moves ?

**Comment by sherifnada** [comment]
@marcosmarxm good idea! let's move forward with that suggestion.

**Comment by garyhampson** [comment]
Hi @sherifnada @marcosmarxm - Would it be possible to get an ETA as to when this might get approved and merged?

**Comment by garyhampson** [comment]
As an enhancement, perhaps adding the ability to use either a DNS Seed List connection string or Standard connection string might be most beneficial.  Here's the mongo documentation on both:

https://docs.mongodb.com/manual/reference/connection-string/

**Comment by marcosmarxm** [comment]
> Hi @sherifnada @marcosmarxm - Would it be possible to get an ETA as to when this might get approved and merged?

@garyhampson we're working to change the mongo connector from ruby to java. This work is almost finished. I'll close this PR because the ruby connector will be deprecated soon. Feel free to add any comment in https://github.com/airbytehq/airbyte/issues/3428.

**Pull request closed without merging**
