### PR TITLE
Bump local json connector

### PR DESCRIPTION
**Pull request by benmoriceau**
## What
Bump the connector version to make sure that the state lifecycle manager is included.

### CODE REVIEW

**Comment by gosusnp** [comment]
Other connectors have a changelog in their docs, for example [here](https://github.com/airbytehq/airbyte/blob/master/docs/integrations/destinations/postgres.md)
Although its usefulness is low for prod, do we want to have that for [local-json](https://github.com/airbytehq/airbyte/blob/master/docs/integrations/destinations/local-json.md) too?

**Review by gosusnp — APPROVED** [review]

**Comment by benmoriceau** [comment]
> Other connectors have a changelog in their docs, for example [here](https://github.com/airbytehq/airbyte/blob/master/docs/integrations/destinations/postgres.md) Although its usefulness is low for prod, do we want to have that for [local-json](https://github.com/airbytehq/airbyte/blob/master/docs/integrations/destinations/local-json.md) too?

I can start one for this connector. There was none, for the next review I'll create the changelog if it is missing

**Review by lmossman — APPROVED** [review]

**Pull request merged**
