### PR TITLE
Bump airbyte_cdk in source-declarative-manifest manually

### PR DESCRIPTION
**Pull request by natikgadzhi**
## What

Publishing workflow failed for airbyte_cdk 0.81.6 in upgrading source-declarative-manifest, so this PR fixed this manually.

Failed run:

### CODE REVIEW

**Comment by natikgadzhi** [comment]
* **#37331** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/37331?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @natikgadzhi and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by natikgadzhi** [comment]
Fixed dockerImageTag version, pushing up for CI

**Comment by natikgadzhi** [comment]
QA checks are failing but it's fine, we should ship. Or wait for another change to overwrite this.

**Review by girarda — APPROVED** [review]
🚢 
I'm not worried about the QA checks. They don't all apply to source-declarative-manifest

**Pull request merged**
