### PR TITLE
Typo and consistency change

### PR DESCRIPTION
**Pull request by sjmunoz**
Typo

## What
Typo on the documentation, but also capitalized titles and removed a final dot for consistency

## How
Changing the docs

## Recommended reading order
NA

## 🚨 User Impact 🚨
Consistent experience for users developing new connectors
No breaking changes

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@sjmunoz can you sign the CLA?

**Comment by marcosmarxm** [comment]
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

**Comment by sjmunoz** [comment]
@marcosmarxm Sure! Sorry about the late reply, must have missed it!

**Review by Amruta-Ranade — APPROVED** [review]
Thank you for the fixes!!

**Comment by sjmunoz** [comment]
> Thank you for the fixes!!

Is there anything else I need to do to merge this?

**Comment by timroes** [comment]
Hi @sjmunoz Thank you a lot for opening this PR. I did actually miss that we have a doc there that talks about running the webapp. We've recently exchanged the build system, why the whole file needs to be updated completely. I'll take care of adjusting this to the current development flow, and believe we can close this PR for now. I'll cherry-pick your typo fixes from here into the new PR and ping you there.

**Pull request closed without merging**
