### PR TITLE
Destination Redshift: more info in tooltip

### PR DESCRIPTION
**Pull request by 13072020**
## What

Changing the text in a tooltip from:
`The schema to write raw tables into`
to
`The schema to write raw tables into (default: airbyte_internal).`

airbyte_internal

Stylistically, this is consistent with the description for `JDBC URL Params`, also in the same file, which ends with ` (example: ...).`

## How

I assume this will work. I just ctrl + f'd for the existing text, and it is only in this `spec.json`.

A downside is that this is now hardcoded.

## User Impact

As a user, I had to experiment to confirm that this option referred to `airbyte_internal`. Seems more obvious now, but was not during my first explorations.

## Can this PR be safely reverted and rolled back?
- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by davidxiao-propeller — APPROVED** [review]

**Review by marcosmarxm — APPROVED** [review]

**Comment by marcosmarxm** [comment]
Thanks @13072020

**Comment by evantahler** [comment]
@marcosmarxm - this is fine to merge as-is, but without the connector version bump the change won't get to users.

**Comment by marcosmarxm** [comment]
@13072020 we're going to merge your contribution but it won't be release yet. You're going to be able to see the change in the next code change which will update the connector version. Thanks for this fix! 👏

**Comment by octavia-approvington** [comment]
You did it! <br/> finish line

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
