### PR TITLE
Remove M1-specific docs - Airbyte works on M1 Macs now

### PR DESCRIPTION
**Pull request by evantahler**
In a fresh environment without any special environment variables, Airbyte works just fine locally now, using the most recent published containers.

To confirm this:

```bash
# Erase any docker images & volumes you may have 
docker system prune -a # hit yes
docker volume prune # hit yes

# unset any special environment variables you may have
unset DOCKER_BUILD_PLATFORM
unset DOCKER_BUILD_ARCH
unset ALPINE_IMAGE
unset POSTGRES_IMAGE
unset JDK_VERSION

# check out the master branch
git checkout master # in the airbyte repo

# see that it just works (tm)
docker compose up
```

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537074617) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by evantahler** [comment]
As a note when testing, it looks like `POSTGRES_IMAGE` isn't in use, so that can be removed as well (https://github.com/airbytehq/airbyte/pull/11860)

**Review by sherifnada — APPROVED** [review]
Seminal work

**Comment by jrhizor** [comment]
Have you tried running acceptance tests locally on the published `amd64` images on an M1 machine? I think most of the M1-related issues people were seeing when not building the images themselves were transient exceptions or random stall outs that aren't present when building for ARM. 

If you can reliably run the acceptance tests this is 100% good to go.

**Comment by evantahler** [comment]
Ah! On my local machine (M1 Macbook Pro), I've got one consistent failure.

```bash
$ uname -a
# Yep, really using an M1 chip (ARM64 something something)
Darwin evan-airbyte-mac.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

$ SUB_BUILD=PLATFORM ./gradlew clean build
# ...
BUILD SUCCESSFUL in 4m 38s
355 actionable tasks: 318 executed, 24 from cache, 13 up-to-date

$ SUB_BUILD=PLATFORM ./gradlew :airbyte-tests:acceptanceTests

Building Airbyte Sub Build: PLATFORM

> Task :airbyte-tests:acceptanceTests

AcceptanceTests > testGetDestinationSpec() PASSED

AcceptanceTests > testFailedGet404() PASSED

AcceptanceTests > testGetSourceSpec() PASSED

AcceptanceTests > testCreateDestination() PASSED

AcceptanceTests > testDestinationCheckConnection() PASSED

AcceptanceTests > testCreateSource() PASSED

AcceptanceTests > testSourceCheckConnection() PASSED

AcceptanceTests > testDiscoverSourceSchema() PASSED

AcceptanceTests > testCreateConnection() PASSED

AcceptanceTests > testManualSync() FAILED
    org.opentest4j.AssertionFailedError: expected: <succeeded> but was: <pending>
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
        at app//io.airbyte.test.acceptance.AcceptanceTests.waitForSuccessfulJob(AcceptanceTests.java:1652)
        at app//io.airbyte.test.acceptance.AcceptanceTests.testManualSync(AcceptanceTests.java:498)

11 tests completed, 1 failed, 1 skipped

> Task :airbyte-tests:acceptanceTests FAILED
```

Initially, I couldn't even boot the app, so I thought the problemspace was more binary.  I'll try and see if I can get that test passing.

**Comment by evantahler** [comment]
Any advice on how to get the Github tests passing?

**Comment by davinchia** [comment]
can you try `./gradlew format`?

**Comment by davinchia** [comment]
@jrhizor are we actually publishing M1 images with each release now?

**Comment by davinchia** [comment]
there is an open issue on the infrastructure side to publish Airbyte M1 images that is in the last stages: https://github.com/airbytehq/airbyte-cloud/issues/801

**Comment by evantahler** [comment]
`./gradlew format` fails with a `Execution failed for task ':spotlessStyling'.`

<details>
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spotlessStyling'.
> Unexpected response status code at /prettier/format [HTTP 501] -- (Error while formatting: SyntaxError: Unexpected token (2:1)
    1 | {"stream": "incremental_leads_zoho_crm_stream", "data": {"Owner": {"name": "Jean Lafleur", "id": "4970762000000326001", "email": "integration-test@airbyte.io"}, "Company": "789", "First_Name": "8", "Last_Name": "7", "Full_Name": "8 7", "Designation": null, "Email": "test@test.com", "Phone": null, "Fax": null, "Mobile": null, "Website": null, "Lead_Source": null, "Lead_Status": null, "Industry": null, "No_of_Employees": null, "Annual_Revenue": null, "Rating": null, "Tag": [], "Created_By": {"name": "Jean Lafleur", "id": "4970762000000326001", "email": "integration-test@airbyte.io"}, "Email_Opt_Out": false, "Skype_ID": null, "Modified_By": {"name": "Jean Lafleur", "id": "4970762000000326001", "email": "integration-test@airbyte.io"}, "Created_Time": "2021-08-04T04:08:39-07:00", "Modified_Time": "2021-08-04T04:08:39-07:00", "Salutation": null, "Secondary_Email": null, "Twitter": null, "Last_Activity_Time": null, "Unsubscribed_Mode": null, "Unsubscribed_Time": null, "Street": null, "City": null, "State": "Test Texas", "Zip_Code": null, "Country": null, "Description": null, "Record_Image": null}, "emitted_at": 1647947807561}
  > 2 | {"stream": "incremental_leads_zoho_crm_stream", "data": {"Owner": {"name": "Jean Lafleur", "id": "4970762000000326001", "email": "integration-test@airbyte.io"}, "Company": "456", "First_Name": "5", "Last_Name": "4", "Full_Name": "5 4", "Designation": null, "Email": "test@test.com", "Phone": null, "Fax": null, "Mobile": null, "Website": null, "Lead_Source": null, "Lead_Status": null, "Industry": null, "No_of_Employees": null, "Annual_Revenue": null, "Rating": null, "Tag": [], "Created_By": {"name": "Jean Lafleur", "id": "4970762000000326001", "email": "integration-test@airbyte.io"}, "Email_Opt_Out": false, "Skype_ID": null, "Modified_By": {"name": "Jean Lafleur", "id": "4970762000000326001", "email": "integration-test@airbyte.io"}, "Created_Time": "2021-08-04T04:08:39-07:00", "Modified_Time": "2021-08-04T04:08:39-07:00", "Salutation": null, "Secondary_Email": null, "Twitter": null, "Last_Activity_Time": null, "Unsubscribed_Mode": null, "Unsubscribed_Time": null, "Street": null, "City": null, "State": "Test Texas", "Zip_Code": null, "Country": null, "Description": null, "Record_Image": null}, "emitted_at": 1647947807563}
      | ^
    3 | {"stream": "incremental_leads_zoho_crm_stream", "data": {"Owner": {"name": "Jean Lafleur", "id": "4970762000000326001", "email": "integration-test@airbyte.io"}, "Company": "123", "First_Name": "2", "Last_Name": "1", "Full_Name": "2 1", "Designation": null, "Email": "test@test.com", "Phone": null, "Fax": null, "Mobile": null, "Website": null, "Lead_Source": null, "Lead_Status": null, "Industry": null, "No_of_Employees": null, "Annual_Revenue": null, "Rating": null, "Tag": [], "Created_By": {"name": "Jean Lafleur", "id": "4970762000000326001", "email": "integration-test@airbyte.io"}, "Email_Opt_Out": false, "Skype_ID": null, "Modified_By": {"name": "Jean Lafleur", "id": "4970762000000326001", "email": "integration-test@airbyte.io"}, "Created_Time": "2021-08-04T04:08:39-07:00", "Modified_Time": "2021-08-04T04:08:39-07:00", "Salutation": null, "Secondary_Email": null, "Twitter": null, "Last_Activity_Time": null, "Unsubscribed_Mode": null, "Unsubscribed_Time": null, "Street": null, "City": null, "State": "Test Texas", "Zip_Code": null, "Country": null, "Description": null, "Record_Image": null}, "emitted_at": 1647947807564}
    4 | {"stream": "incremental_leads_zoho_crm_stream", "data": {"Owner": {"name": "Jean Lafleur", "id": "4970762000000326001", "email": "integration-test@airbyte.io"}, "Company": "Villa Margarita", "First_Name": "Brian", "Last_Name": "Dolan", "Full_Name": "Brian Dolan", "Designation": null, "Email": "brian@villa.com", "Phone": null, "Fax": null, "Mobile": null, "Website": null, "Lead_Source": null, "Lead_Status": null, "Industry": null, "No_of_Employees": null, "Annual_Revenue": null, "Rating": null, "Tag": [], "Created_By": {"name": "Jean Lafleur", "id": "4970762000000326001", "email": "integration-test@airbyte.io"}, "Email_Opt_Out": false, "Skype_ID": null, "Modified_By": {"name": "Jean Lafleur", "id": "4970762000000326001", "email": "integration-test@airbyte.io"}, "Created_Time": "2021-08-04T04:06:27-07:00", "Modified_Time": "2021-08-04T04:06:27-07:00", "Salutation": null, "Secondary_Email": null, "Twitter": null, "Last_Activity_Time": "2022-03-22T01:02:33-07:00", "Unsubscribed_Mode": null, "Unsubscribed_Time": null, "Street": null, "City": null, "State": "Texas", "Zip_Code": null, "Country": null, "Description": null, "Record_Image": null}, "emitted_at": 1647947807565}
    5 | {"stream": "incremental_leads_zoho_crm_stream", "data": {"Owner": {"name": "Jean Lafleur", "id": "4970762000000326001", "email": "integration-test@airbyte.io"}, "Company": "Airbyte Test", "First_Name": "Test", "Last_Name": "Airbyte", "Full_Name": "Test Airbyte", "Designation": null, "Email": "test@test.com", "Phone": null, "Fax": null, "Mobile": null, "Website": null, "Lead_Source": null, "Lead_Status": null, "Industry": null, "No_of_Employees": null, "Annual_Revenue": null, "Rating": null, "Tag": [], "Created_By": {"name": "Jean Lafleur", "id": "4970762000000326001", "email": "integration-test@airbyte.io"}, "Email_Opt_Out": false, "Skype_ID": null, "Modified_By": {"name": "Jean Lafleur", "id": "4970762000000326001", "email": "integration-test@airbyte.io"}, "Created_Time": "2021-08-04T04:06:27-07:00", "Modified_Time": "2021-08-04T04:06:27-07:00", "Salutation": null, "Secondary_Email": null, "Twitter": null, "Last_Activity_Time": null, "Unsubscribed_Mode": null, "Unsubscribed_Time": null, "Street": null, "City": null, "State": "Test Texas", "Zip_Code": null, "Country": null, "Description": null, "Record_Image": null}, "emitted_at": 1647947807565})

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 1m 6s
166 actionable tasks: 123 executed, 43 up-to-date
```
</details>

**Comment by jrhizor** [comment]
These problems running syncs with Airbyte go away when using M1-built images for the platform. We probably just need to wait for https://github.com/airbytehq/airbyte-cloud/issues/801 and then we can merge this.

**Comment by sherifnada** [comment]
it looks like ARM64 should be supportable on self-hosted runners: https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#architectures

so that's probably the first step actually, like Jared said

**Comment by davinchia** [comment]
Yeap. We can switch the AMIs out as we need to. We should build both architectures so we don't need to immediately switch those out, though we should eventually do so since AWS ARM instances are 25% cheaper than x86.

**Pull request merged**
