### PR TITLE
🎉 Source Kustomer: Clarify setup fields

### LINKED ISSUE #8697: Kustomer source connector: investigate "user_agent" deprecation
## Tell us about the problem you're trying to solve
While making titles update in [8367](https://github.com/airbytehq/airbyte/issues/8367) @sherifnada requested investigate **"user-agent"** field possibility for deprecation.

## Describe the solution you’d like
For now it is availbale in [spec.json](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-kustomer-singer/source_kustomer_singer/spec.json).
Investigate the posiibilities to remove this field without inpacting authorization issue.

### LINKED ISSUE #8698: Kustomer source connector: remove "page_limit_size" option
## Tell us about the problem you're trying to solve
While making titles update in 8367 @sherifnada requested remove "page_limit_size" option.

## Describe the solution you’d like
For now it is availbale in [spec.json](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-kustomer-singer/source_kustomer_singer/spec.json).
Investigate the posiibilities to remove this field without impacting output.

### PR DESCRIPTION
**Pull request by lazebnyi**
## What
#8697 - Kustomer source connector: investigate "user_agent" deprecation
#8698 - Kustomer source connector: remove "page_limit_size" option

## How
Deleted `user-agent`, `date_window_size`, `page_size_limit` from `spec.json` file. 
Default value for `date_window_size` and `page_size_limit` is 60 and 500.

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

### CODE REVIEW

**Review by antixar — COMMENTED** [review]
Please remove these options in other files too: [ invalid_config.json](https://github.com/airbytehq/airbyte/blob/de0d6fcae5382376ea20d9be2cea6bd9a0452110/airbyte-integrations/connectors/source-kustomer-singer/integration_tests/invalid_config.json#L5)
And please add an integration "check" test with the old config format.

**Comment by bazarnov** [comment]
Is this `Default value for date_window_size and page_size_limit is 60 and 500` agreed with the Client, or something else? How those values are picked?

**Comment by lazebnyi** [comment]
> 

@bazarnov This is the default value that is set by the singer (https://github.com/singer-io/tap-kustomer/blob/b56a2cc3646d57b8c1eb8876a335073a8968fd00/tap_kustomer/sync.py#L12). Permission for delete those fields from the config is based on[ PR description](https://github.com/airbytehq/airbyte/issues/8698) and [UX handbook](https://docs.airbyte.io/connector-development/ux-handbook).

**Review by bazarnov — APPROVED** [review]

**Review by antixar — APPROVED** [review]
Unfortunately this connector doesn't support the relevant test framework(SAT) fully. For this the connector must be migrated to CDK.  Airbyte team knows about this and has approved its publishing without adding of new tests.
@lazebnyi , please, publish this

**Pull request merged**
