### PR TITLE
fix(destination-pinecone): Replaced using `AirbyteLogger` with an `AirbyteLogMessage` instead

### PR DESCRIPTION
**Pull request by natikgadzhi**
## What

When handling an error, destination Pinecone attemted to use AirbyteLogger, which we removed before CDK 1.0, so that blew up. 

This fix uses `AirbyteLogMessage` instead. I've also updated CDK to 2.0 while I'm here.

## User Impact

When connector errors out, now it should capture the error instead of crashing.

## Can this PR be safely reverted and rolled back?
- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by natikgadzhi** [comment]
@aaronsteers I assume integration tests will run on CI, right?

**Comment by aaronsteers** [comment]
> @aaronsteers I assume integration tests will run on CI, right?

I believe so...

There's a lot going on here, but I assume integration tests would run here:

https://github.com/airbytehq/airbyte/actions/runs/9813423151/job/27099424463

**Review by aaronsteers — CHANGES_REQUESTED** [review]
@natikgadzhi - Looks like Pydantic 2.0 (aka CDK 2.0) breaks this.

```
RuntimeError: no validator found for <class 'destination_pinecone.config.PineconeIndexingModel'>, see `arbitrary_types_allowed` in Config
```

☝️ from the CI report.

**Comment by natikgadzhi** [comment]
Yep, pinning to <2.

**Comment by natikgadzhi** [comment]
@aaronsteers ready. Fixing formatting and version, but tests should pass now.

**Review by aaronsteers — APPROVED** [review]
Looks great - thanks, @natikgadzhi! 🙏

**Comment by aaronsteers** [comment]
@natikgadzhi - I see another release landed last night with the same version number for this connector, which is blocking this one now. I will see if I can resolve the conflict real quick.

**Pull request merged**
