### PR TITLE
Return full catalog from update API endpoint

### PR DESCRIPTION
**Pull request by alovew**
Resolves https://app.zenhub.com/workspaces/oss-platform-625a01eb010e82001390f49e/issues/airbytehq/airbyte/14839

The WebBackendConnectionUpdate endpoint was only returning selected streams, not all streams in the Catalog. This PR changes that endpoint so it fetches the entire catalog and returns the whole thing, with the selected streams marked selected in the Stream Config.

### CODE REVIEW

**Review by gosusnp — APPROVED** [review]
Can you add a description of the return data to the doc.
It should be part of the contract that ConnectionUpdate and WebBackendConnectionUpdate return all the streams, not just the modified ones.

**Comment by alovew** [comment]
@gosusnp do you know where this API is documented? I can't find it. My update only makes WebBackendUpdateConnection return the full catalog (in the WebBackendConnectionRead object). The ConnectionUpdate object still only has the selected streams. Is that ok? I could change the `toConnectionUpdate` method but I think that would mean changing some of the reset logic around detecting which streams were added & removed.

**Comment by alovew** [comment]
@timroes could you test this and let me know if this resolves the issue you described?

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Comment by evantahler** [comment]
@alovew note in your descriptions, if you use `Closes: {github_link}` (not the senhub link) Github will autoclose the issue and link it up in the UI

**Pull request merged**
