### PR TITLE
Destination Bigquery - Limit the number of clustering columns to 4

### PR DESCRIPTION
**Pull request by jbfbell**
## What
Big Query Limits the number of clustering columns to 4. When we have multiple PK columns, we were clustering on all of them.

https://github.com/airbytehq/oncall/issues/2565

## How
Limit the number of pk columns by taking the first 3

### CODE REVIEW

**Comment by cynthiaxyin** [comment]
Should this be merged to master instead of the spec option branch?

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery-denormalized test report (commit [`e33e979a09`](https://github.com/airbytehq/airbyte/pull/28624/commits/e33e979a09f4e3d9b155a25d046aaca60f8bc897)) - ✅

⏲️  Total pipeline duration: 17mn53s 

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ✅        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-bigquery-denormalized docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery-denormalized:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/josephbell_oncall_2565_too-many-clustering-columns/1690218901/e33e979a09f4e3d9b155a25d046aaca60f8bc897/destination-bigquery-denormalized/1.5.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`e33e979a09`](https://github.com/airbytehq/airbyte/pull/28624/commits/e33e979a09f4e3d9b155a25d046aaca60f8bc897)) - ✅

⏲️  Total pipeline duration: 30mn52s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/josephbell_oncall_2565_too-many-clustering-columns/1690218901/e33e979a09f4e3d9b155a25d046aaca60f8bc897/destination-bigquery/1.5.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by jbfbell** [comment]
Moved over to https://github.com/airbytehq/airbyte/pull/28625

**Pull request closed without merging**
