### PR TITLE
shopify connector: fix memory leak fix issue#22279

### PR DESCRIPTION
**Pull request by liorchen**
## What
Memory leak in shopify
[22279](https://github.com/airbytehq/airbyte/issues/22279)

## How
on each iteration of `ShopifySubstream` parent read records, there was an instantiation of the stream, which for some reason caused memory leak because in the constructor there's a call to `DataTypeEnforcer`.
I wrapped the `parent_stream` property in a `cached_property` so that it only created once. 

## Recommended reading order
1. `y.python`
2. `x.java`

## 🚨 User Impact 🚨
no breaking changes

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Comment by bazarnov** [comment]
@liorchen Hello, thank you for your time using and contributing to `source-shopify`! 

Could you please give more details on how you come up with this conclusion about the `@property` causing the memory leak?

**Comment by liorchen** [comment]
I'm not entirely sure. but I ran memory profiling and found that this method:

```    def _resolve_schema_references(self, raw_schema: dict) -> dict:
        """
        Resolve links to external references and move it to local "definitions" map.

        :param raw_schema jsonschema to lookup for external links.
        :return JSON serializable object with references without external dependencies.
        """

        package = importlib.import_module(self.package_name)
        base = os.path.dirname(package.__file__) + "/"
        resolved = jsonref.JsonRef.replace_refs(raw_schema, loader=JsonFileLoader(base, "schemas/shared"), base_uri=base)
        resolved = resolve_ref_links(resolved)
        return resolved
```
inside `airbyte_cdk/sources/utils/schema_helpers.py` was the source of the leak
its probably still leaking, but when you call it for each order of the shop it becomes a massive memory leak.

**Comment by bazarnov** [comment]
@liorchen got your point here, have you profiled the memory with your fix? Did the caching strategy help?

**Comment by liorchen** [comment]
@bazarnov yep
I synced a store with 13k orders and 20k customers and before the fix my 16GB RAM pod was terminating OOM. After the fix, syncing the same store,  the process is taking 70MB flat with no increase.
Also profiled and didnt see the objects with memory as before.

**Comment by bazarnov** [comment]
Awesome! 
Could you please proceed with complete sync with not just `orders` but also some other streams?  If successful - your fix will be merged right after the code freeze (unfortunately) (+- on Monday next week, is the closest time spot).

**Comment by liorchen** [comment]
yeah a full syncs with other streams like `transactions` `order_refunds` `tender_transactions` `products` are working as expected

**Comment by Tajmahal86** [comment]
Thanks to everyone working on this and Airbyte in general. :muscle:
I wonder is there any chance we will get this fix merged sooner? We have been hoping for a fix to come for quite a while now. :pray:
Without it, this connector is useless for anything other than a tiny Shopify store. :disappointed:

**Review by bazarnov — APPROVED** [review]
LGMT. 
Please consider adding the `changelog` here: https://github.com/liorchen/airbyte/blob/liorchen/shopify-connector-memory-fix/docs/integrations/sources/shopify.md

**Comment by bazarnov** [comment]
@liorchen
Would you mind me creating another PR from my side with your changes for a quick merge? Along with acceptance tests, it will be much easier to get this fix into the master.

**Comment by bazarnov** [comment]
@marcosmarxm Can you assist with publishing and merging here? or it's better to create another PR from our side?

**Comment by bazarnov** [comment]
> This has fixed the issue for us with the inventory stream in particular. We are now seeing a max memory utilisation of ~350MB when previously it would fail at 24GB. Thanks!

The fix is  going  to be merged soon, it's on the way  here: https://github.com/airbytehq/airbyte/pull/23473

**Pull request closed without merging**
