### PR TITLE
pin paypal transaction to 2.0.0 (the actual last version we were running) 

### PR DESCRIPTION
**Pull request by erohmensing**

### CODE REVIEW

**Comment by octavia-approvington** [comment]
Trying to merge your PR using a bot?
Comment this on the PR:
```
/approve-and-merge reason="<STATE YOUR REASON HERE>"
```
Make sure you've reviewed the [docs](https://internal-docs.airbyte.io/How-Tos/Overriding-PR-Merge-Rules)!

**Comment by octavia-approvington** [comment]
Jerry would be proud <br/> Spongebob

**Review by octavia-approvington — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-paypal-transaction test report (commit [`82f63466ed`](https://github.com/airbytehq/airbyte/pull/31636/commits/82f63466edee0046c057d0521a08e9d9a637d2db)) - ✅

⏲️  Total pipeline duration: 01mn16s 

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Build source-paypal-transaction docker image for platform(s) linux/x86_64 | ✅       |
| Acceptance tests                                                          | ✅       |
| Code format checks                                                        | ✅       |
| Validate metadata for source-paypal-transaction                           | ✅       |
| Connector version semver check                                            | ✅       |
| QA checks                                                                 | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/erohmensing-patch-2/1697767860/82f63466edee0046c057d0521a08e9d9a637d2db/source-paypal-transaction/2.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:82f63466edee0046c057d0521a08e9d9a637d2db)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Pull request merged**
