### PR TITLE
clean up protocol definition files & change to yamlschema

### PR DESCRIPTION
**Pull request by jrhizor**
- convert to json for consistency
- make the names of the files match the exact title of the schema
- change the invalid reference `"$ref": airbyte_schema.yaml#/definitions/AirbyteStream` to a valid `"$ref": #/definitions/AirbyteStream`

### CODE REVIEW

**Review by michel-tricot — APPROVED** [review]
I left it to be yaml for readability purposes but I am ok moving back to Json.

**Review by michel-tricot — COMMENTED** [review]
You need to change gradle to not expect yamlschema

**Comment by jrhizor** [comment]
I removed repetition of the file name in self-references across all of the types and switched everything to use yaml.

**Review by michel-tricot — APPROVED** [review]

**Comment by jrhizor** [comment]
Interesting gotcha: the folder for `singer_types` can't be named `types` since it'll get clobbered by the other `resources/types`.

**Pull request merged**
