### PR TITLE
feat(source-zendesk-support): add automations and triggers streams

### PR DESCRIPTION
**Pull request by henriblancke**
## What
Add missing streams:
* Automations
* Triggers

## User Impact
Users will be able to now sync automations and triggers

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Running CI Tests @henriblancke !

**Comment by marcosmarxm** [comment]
Running tests @henriblancke

**Review by marcosmarxm — APPROVED** [review]
Thanks @henriblancke need final approval from connector team.

**Review by aldogonzalez8 — APPROVED** [review]
LGTM

**Pull request merged**
