### PR TITLE
Emit spec from integration images

### PR DESCRIPTION
**Pull request by sherifnada**
## What
This PR makes all integration images respond to the `--spec` flag by outputting the integration's specification. 

## Todo
- [x] unit tests (will add in future PR)
- [x] define new spec schema

### CODE REVIEW

**Review by michel-tricot — APPROVED** [review]

**Review by jrhizor — APPROVED** [review]

**Review by cgardens — APPROVED** [review]
2 questions:
1. It's intentional that you're not deleting the old specs yet, right?
1. What is the schema of these new `spec.json`s? it looks like it is a subset SourceConnectinoSpecificiation DestinationConnectinoSpecificiation. Can you define the schema for these new specs (if not now in a subsequent pr)?

**Comment by sherifnada** [comment]
@cgardens 
1. Yes intentional. Old specs will be removed in a future PR. 
1. So far it is the same as the old spec schema minus the ID fields. Will define this schema.

**Comment by sherifnada** [comment]
@cgardens @michel-tricot @jrhizor I added schema definitions for source and destination specifications. If it looks good I can merge.

**Review by michel-tricot — APPROVED** [review]

**Comment by sherifnada** [comment]
Ended up adding unit tests in this PR

**Pull request merged**
