### PR TITLE
:bug: Source Gitlab, Source Hubspot, Source Snapchat-Marketing: fix builds

### PR DESCRIPTION
**Pull request by davydov-d**
## What
Fix builds for:
 - Hubspot. For stream `Tickets`, one property was removed: `hs_all_assigned_business_unit_ids`
 - Gitlab. Some records have been changed in `Projects`  stream. New fields appeared: `description_html`, `updated_at`
 - Snapchat-marketing. Some records have been changed in `Campaigns` stream. New field appeared: `creation_state`

## How
- Hubspot: Update expected records only, since the properties for tickets stream are dynamically updated in schema, based on authenticated user, account plan and permissions.
- Gitlab: Update expected records, update stream schema, bump version.
- Snapchat-marketing: Update expected records, update stream schema, bump version

### CODE REVIEW

**Review by grubberr — APPROVED** [review]

**Review by lazebnyi — APPROVED** [review]

**Review by erohmensing — APPROVED** [review]
Thank you for laying out what changed and how you fixed it in the PR description. Made the review super easy!

**Pull request merged**
