### PR TITLE
Source Chameleon: Update survey_responses schema, Make end date configuration as optional

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
Make the end date optional for source chameleon
Defaults to the current date

## How
Defaults to the current date

### CODE REVIEW

**Comment by natikgadzhi** [comment]
Hold up, but wouldn't that sync exactly zero records because you're setting end date to now?

**Comment by btkcodedev** [comment]
The default behaviour of incremental sync end date is now_utc(), isn't it?
image

**Pull request merged**
