### PR TITLE
Shopify connector license to Elv2

### PR DESCRIPTION
**Pull request by evantahler**
See https://github.com/airbytehq/airbyte/issues/27724

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-shopify test report (commit [`8e110fa936`](https://github.com/airbytehq/airbyte/pull/27732/commits/8e110fa936e63541e9fe8c78b6820029ea9d5d8e)) - ✅

⏲️  Total pipeline duration: 1796 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-shopify/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-shopify docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-shopify/1687824596/8e110fa936e63541e9fe8c78b6820029ea9d5d8e/source-shopify/0.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-shopify test
```

**Comment by octavia-squidington-iii** [comment]
##  source-shopify test report (commit [`8e110fa936`](https://github.com/airbytehq/airbyte/pull/27732/commits/8e110fa936e63541e9fe8c78b6820029ea9d5d8e)) - ✅

⏲️  Total pipeline duration: 1779 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-shopify/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-shopify docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-shopify/1687839373/8e110fa936e63541e9fe8c78b6820029ea9d5d8e/source-shopify/0.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-shopify test
```

**Comment by octavia-approvington** [comment]
Approve this <br/> imagine the commander saying yes

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
