### PR TITLE
Add Looker Source

### PR DESCRIPTION
**Pull request by yevhenii-ldv**
## Contributor Checklist
Thanks for contributing to Airbyte! Please complete the following items in order so we can review your PR.
- [x] Followed all the instructions in the locally generated checklist and your connector is functional & ready for review
- [x] Ran the standard test suite locally via `./gradlew :airbyte-integrations:connectors:source-<your_source_name>:standardSourceTestPython` and pasted the summarized output as a comment in this PR

## Reviewer Pre-merge Checklist 
- [x] Finished iterating with the PR author on the code*
- [x] Created a branch off master to merge this PR into*
- [x] Inject the credentials in CI via `./tools/integrations/ci_credentials.sh` and `.github/workflows/test-command.yml`*
- [ ] Added the credentials for this integration to Github secrets 
- [ ] Run standard tests on this branch by commenting `/test connector=<name>`*
- [x] Add entry in `airbyte-config/init/src/main/resources/seed/source_definitions.yaml` to use the new source in Airbyte core
- [ ] Deployed the connector to Dockerhub via `./tools/integrations/manage.sh publish airbyte-integrations/connectors/source-<name>`

## Documentation
- [x] Add docs in `docs/integrations/sources/` folder in line with the documentation template found in `docs/contributing-to-airbyte/templates/integration-documentation-template.md`.
- [x] Add link to create docs file to `docs/SUMMARY.md`
- [x] Include a link to the documentation in the `README.md`

### CODE REVIEW

**Comment by yevhenii-ldv** [comment]
2020-12-18 10:16:34 DEBUG i.a.w.p.DockerProcessBuilderFactory(create):103 - {} - Preparing command: docker run --rm -i -v /tmp/airbyte_tests/test14529009971018737786:/data -v /tmp/airbyte_tests/output10329928141889460084:/local -w /data/job --network host airbyte/source-looker:dev discover --config tap_config.json
2020-12-18 10:16:35 INFO i.a.i.s.s.PythonTestSource(runExecutableInternal):126 - {} - testRoot = /tmp/standard_test/pytest13347970653168084689
2020-12-18 10:16:35 INFO i.a.c.i.LineGobbler(voidCall):69 - {} - parsing
2020-12-18 10:16:35 INFO i.a.c.i.LineGobbler(voidCall):69 - {} - executing command TestAction.TEARDOWN
2020-12-18 10:16:35 INFO i.a.c.i.LineGobbler(voidCall):69 - {} - writing output
2020-12-18 10:16:35 INFO i.a.c.i.LineGobbler(voidCall):69 - {} - complete

Test run finished after 235297 ms
```
[         2 containers found        ]
[         0 containers skipped      ]
[         2 containers started      ]
[         0 containers aborted      ]
[         2 containers successful   ]
[         0 containers failed       ]
[         7 tests found             ]
[         0 tests skipped           ]
[         7 tests started           ]
[         0 tests aborted           ]
[         7 tests successful        ]
[         0 tests failed            ]
```

**Review by sherifnada — APPROVED** [review]
LGTM with a few small wording comments. We should be able to merge it tomorrow.

**Comment by sherifnada** [comment]
also @yevhenii-ldv could you add the Looker creds to lastpass so we can run tests?

**Comment by sherifnada** [comment]
merged in #1444 🎉

**Pull request closed without merging**
