### PR TITLE
:feature: adds option for extended source metadata to be added to each row

### PR DESCRIPTION
**Pull request by w-gitops**
## What
*Describe what the change is solving*
This change adds multiple options to add extended metadata about each source record, to the each records output stream.  This data is useful for future features such as incremental sync, as well as tighter integration with outside sources for reverse ETL.

It also adds the ability to add a few lines of raw JSON record data to the run log, for debugging source problems from the web gui when access to the system logs is not available.

## How
Adds boolean options in the connection settings for several types of metadata.  All are optional, and are "false" by default, so this is a non-breaking change.
Additionally, the added metadata does not become part of the output stream until the source schema is refreshed after updating.

## Recommended reading order
1. `updated smartsheet source docs`
2. `spec.json`
3. `source.py`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.
No breaking changes.  All extended options off by default.

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated 
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hello @willsargent can you check your commit, looks is adding a lot of binary files. Adding a new feature I **strongly** recommend you first open an issue to discuss with the community/team the best way to add it and see pros/cons.

**Comment by willsargent** [comment]
> 

Hmm. I didn't do that intentionally.. It's primarily limited to a few files.. Is there a file type extension that I should be looking for in particular.  Apologies as I am relatively new to this.  Thanks!

**Comment by willsargent** [comment]
> Hello @willsargent can you check your commit, looks is adding a lot of binary files. Adding a new feature I **strongly** recommend you first open an issue to discuss with the community/team the best way to add it and see pros/cons.

I see it now.. all the .class files.  The failed gradle build file issue.. Let me look into cleaning this up. thanks

**Comment by marcosmarxm** [comment]
Ok @willsargent let me know if you need anything else.

**Comment by marcosmarxm** [comment]
@willsargent I'm closing this. Let me know if you want to re-open it

**Pull request closed without merging**
