### PR TITLE
airbyte-ci: Ignore autogen files

### PR DESCRIPTION
**Pull request by edgao**
https://github.com/airbytehq/airbyte/pull/45468 adds a new test that will autogenerate these `expected-spec.json` files using Jackson's pretty printer (i.e. what we use in java connectors for json de/ser).  Exclude them from the autoformatter.

(also, submitted https://github.com/airbytehq/airbyte-internal-issues/issues/9863 b/c it would be nice to just use prettierignore)

tooling folks: I'm sure there's some changelog/version bumping stuff that I should do, can I get a pointer on how to do those things?

### CODE REVIEW

**Comment by edgao** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/45632?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#45632** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/45632?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#45113** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/45113?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#45468](https://github.com/airbytehq/airbyte/pull/45468) <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/45468?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#45611** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/45611?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#45610** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/45610?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#44874** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/44874?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#45147** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/45147?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @edgao and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by stephane-airbyte — APPROVED** [review]

**Comment by natikgadzhi** [comment]
Don’t forget to bump airbyte-ci version though. And add a changelog line.

**Comment by edgao** [comment]
@natikgadzhi can you doublecheck that I did this correctly? I patternmatched the last changelog's PR but am not familiar with this stuff :P

**Review by natikgadzhi — APPROVED** [review]

**Comment by natikgadzhi** [comment]
Awesome! Thank you for doing the thing you needed there <3 And sorry we couldn't tweak things for you quickly.

**Pull request merged**
