### PR TITLE
Bump versions for mssql strict-encrypt

### LINKED ISSUE #28543: 🐛 source-mssql: connector forces snapshot isolation level
### Connector Name

source-mssql

### Connector Version

1.1.0

### What step the error happened?

Configuring a new connector

### Revelant information

PR with proposed fix: https://github.com/airbytehq/airbyte/pull/28545

There appears to be a bug in source-mssql's support for CDC + Read Committed. Currently both snapshot isolation levels check the db for enabled full `Snapshot Isolation`, which it should not do when the `Read Committed` isolation level is selected.
 
Support for non-snapshot CDC is added here: https://github.com/airbytehq/airbyte/pull/13168 
In the connector spec we see a rework of `replication_method` to support the `Read Committed` isolation level.  `replication_method` field is renamed to `replication` for hygiene.
We can see from comments that the new implementation since 0.4.0 should use the `replication` parameter instead of the `replication_method`. More recently however, the connector was modified in https://github.com/airbytehq/airbyte/pull/16215 to use `replication_method` which has caused some problems.

In the original change to support `Read Committed` snapshot isolation level for MSSQL + CDC,  we see the new `REPLICATION_FIELD` value pulled into `CdcMssqlHelper.java`:
https://github.com/airbytehq/airbyte/blob/4284ce6b17d324887f3e51226ee481484854c7fd/airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/MssqlCdcHelper.java#L15-L20

`isCdc` checks whether CDC is enabled. It supports both `LEGACY_REPLICATION_FIELD` and `REPLICATION_FIELD`:
https://github.com/airbytehq/airbyte/blob/4284ce6b17d324887f3e51226ee481484854c7fd/airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/MssqlCdcHelper.java#L95-L107

`getSnapshotIsolationConfig` checks the snapshot isolation level:

https://github.com/airbytehq/airbyte/blob/4284ce6b17d324887f3e51226ee481484854c7fd/airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/MssqlCdcHelper.java#L109-L122

Since then, the spec parameter was modified from `replication` back to `replication_method`.  This means that the `getSnapshotIsolationConfig` function still needs `REPLICATION_FIELD` to be `hasNonNull`. Unfortunately however it's always null, because `REPLICATION_FIELD` doesn't exist anymore, we only have `LEGACY_REPLICATION_FIELD`.

So now, if we look at master branch, we observe that the connector config is not passed into some functions.
i.e.,

https://github.com/airbytehq/airbyte/blob/7e4797d90dc7ddfdef2bc1ba85d6a91550397da2/airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/MssqlCdcHelper.java#L120-L140

tl;dr quick/non-breaking-change fix is to update functions with the correct config parameter

Since this work was originally done to make naming consistent throughout CDC connectors (a reasonable goal) we should probably look at refactoring.

### Relevant log output

_No response_

### Contribute

- [X] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by rodireich**
## What
Bump and publish source-mssql-strict-encrypt, 
Similarly to source-mssql

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-mssql-strict-encrypt test report (commit [`9de8dfb59d`](https://github.com/airbytehq/airbyte/pull/28964/commits/9de8dfb59dfe9cfb68bd8f68678eada3e1cdb4d4)) - ❌

⏲️  Total pipeline duration: 17mn36s 

| Step                                                                                   | Result   |
|:---------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mssql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                         | ✅        |
| QA checks                                                                              | ✅        |
| Build connector tar                                                                    | ✅        |
| Build source-mssql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mssql-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/28543-publish-source-mssql-strict-encrypt/1690938417/9de8dfb59dfe9cfb68bd8f68678eada3e1cdb4d4/source-mssql-strict-encrypt/1.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mssql-strict-encrypt test
```

**Review by bnchrch — APPROVED** [review]
Thanks!

**Comment by rodireich** [comment]
/legacy-test connector=connectors/source-mssql-strict-encrypt

**Comment by octavia-squidington-iii** [comment]
##  source-mssql-strict-encrypt test report (commit [`5d40cdf3d5`](https://github.com/airbytehq/airbyte/pull/28964/commits/5d40cdf3d51cbaf2d87920d2e890f273c114dccf)) - ❌

⏲️  Total pipeline duration: 17mn33s 

| Step                                                                                   | Result   |
|:---------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mssql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                         | ✅        |
| QA checks                                                                              | ✅        |
| Build connector tar                                                                    | ✅        |
| Build source-mssql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mssql-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/28543-publish-source-mssql-strict-encrypt/1691006039/5d40cdf3d51cbaf2d87920d2e890f273c114dccf/source-mssql-strict-encrypt/1.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mssql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mssql-strict-encrypt test report (commit [`dc2aa72113`](https://github.com/airbytehq/airbyte/pull/28964/commits/dc2aa721134ce76bcf8f717e95b1c6b3ffcaaa4b)) - ❌

⏲️  Total pipeline duration: 3.82s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28543-publish-source-mssql-strict-encrypt/1691084598/dc2aa721134ce76bcf8f717e95b1c6b3ffcaaa4b/source-mssql-strict-encrypt/1.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:dc2aa721134ce76bcf8f717e95b1c6b3ffcaaa4b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mssql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mssql-strict-encrypt test report (commit [`86b1f20a39`](https://github.com/airbytehq/airbyte/pull/28964/commits/86b1f20a397b8c099a312b68dc261a99bf50c511)) - ❌

⏲️  Total pipeline duration: 4.69s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28543-publish-source-mssql-strict-encrypt/1691086303/86b1f20a397b8c099a312b68dc261a99bf50c511/source-mssql-strict-encrypt/1.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:86b1f20a397b8c099a312b68dc261a99bf50c511)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mssql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mssql test report (commit [`72e32866db`](https://github.com/airbytehq/airbyte/pull/28964/commits/72e32866dbd19b3be2e0065877e03c79f569c4eb)) - ❌

⏲️  Total pipeline duration: 14.09s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28543-publish-source-mssql-strict-encrypt/1691087695/72e32866dbd19b3be2e0065877e03c79f569c4eb/source-mssql/1.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:72e32866dbd19b3be2e0065877e03c79f569c4eb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mssql test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mssql-strict-encrypt test report (commit [`72e32866db`](https://github.com/airbytehq/airbyte/pull/28964/commits/72e32866dbd19b3be2e0065877e03c79f569c4eb)) - ❌

⏲️  Total pipeline duration: 3.22s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/28543-publish-source-mssql-strict-encrypt/1691087695/72e32866dbd19b3be2e0065877e03c79f569c4eb/source-mssql-strict-encrypt/1.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:72e32866dbd19b3be2e0065877e03c79f569c4eb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mssql-strict-encrypt test
```

**Comment by octavia-approvington** [comment]
Check that box <br/> TODO complete

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
