### PR TITLE
Source Zendesk Chat: Add Conversions, DepartmentEvents Streams

### LINKED ISSUE #19641: Source Zendesk Chat: Add conversion and department events streams
## Tell us about the problem you're trying to solve
Adding to extra streams for the Zendesk Chat  connector: 
- [department events](https://developer.zendesk.com/api-reference/live-chat/chat-api/incremental_export/#incremental-department-events-export)
- [conversions](https://developer.zendesk.com/api-reference/live-chat/chat-api/incremental_export/#incremental-conversions-expor)

Both of them are time incremental streams.

## Describe the solution you’d like
Create 2 classes that will extend the TimeIncrementalStream. Both of them will have as the `cursor_field` the  `timestamp`. The `data_fields` should be `department_events` and `conversions`.

## Describe the alternative you’ve considered or used
We don't use an alternative. Data from the 2 streams aren't exported.

## Are you willing to submit a PR?
I have opened a PR https://github.com/airbytehq/airbyte/pull/19351

### PR DESCRIPTION
**Pull request by topefolorunso**
## What
Fixes #19641

## How
*Describe the solution*

## Recommended reading order
1. `manifest.yaml`
2. `conversions.json`
3. `department_events.json`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@topefolorunso can you explain how did you create records to test the implementation? Today Airbyte integration account doesn't have records and we can't test the endpoint right now.

**Comment by topefolorunso** [comment]
> @topefolorunso can you explain how did you create records to test the implementation? Today Airbyte integration account doesn't have records and we can't test the endpoint right now.

Not tested yet also @marcosmarxm. Trying to contact zendesk support for a trial account but no success

**Comment by marcosmarxm** [comment]
We're trying to populate the streams but without success yet.

**Comment by marcosmarxm** [comment]
Hello @topefolorunso without updates here. We need to setup a website with the Chat widget to have data populated in these streams.

**Comment by topefolorunso** [comment]
> We need to setup a website with the Chat widget to have data populated in these streams.

Okay. What do you need me to do?

**Comment by marcosmarxm** [comment]
We're workign to have a website with the widget.

**Comment by marcosmarxm** [comment]
Closing as the high effort to add testing data to this endpoint. @topefolorunso thanks for the contribution

**Pull request closed without merging**
