### PR TITLE
🐛 CDK: fix schema inference where "type" might not be declared

### LINKED ISSUE #39133: [connector-builder] Schema inference fails on null types
### Connector Name

connector-builder

### Connector Version

0.61.0

### What step the error happened?

Configuring a new connector

### Relevant information

# Environment

**Airbyte version**: OSS
**Step where error happened**: Connector Builder: Test

# Current Behavior
When attempting to test Connector Builder configuration the process will fail during schema inference if `type` is Null or missing.

Stacktrace:
```logs
  Traceback (most recent call last):
  File \"/home/airbyte/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/connector_builder/connector_builder_handler.py\", line 66, in read_stream
    stream_read = handler.get_message_groups(source, config, configured_catalog, state, limits.max_records)
  File \"/home/airbyte/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/connector_builder/message_grouper.py\", line 125, in get_message_groups
    schema = schema_inferrer.get_stream_schema(configured_stream.stream.name)
  File \"/home/airbyte/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/utils/schema_inferrer.py\", line 209, in get_stream_schema
    self._add_required_properties(self._clean(self.stream_to_builder[stream_name].to_schema()))
  File \"/home/airbyte/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/utils/schema_inferrer.py\", line 107, in _clean
    self._clean(value)
  File \"/home/airbyte/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/utils/schema_inferrer.py\", line 107, in _clean
    self._clean(value)
  File \"/home/airbyte/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/utils/schema_inferrer.py\", line 107, in _clean
    self._clean(value)
  File \"/home/airbyte/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/utils/schema_inferrer.py\", line 112, in _clean
    if isinstance(node[\"type\"], list):
KeyError: 'type'
```

Issue seems to be when evaluating `schema_inferrer.py` at line 112:
```python
if isinstance(node["type"], list):
    if _NULL_TYPE in node["type"]:
        # we want to make sure null is always at the end as it makes schemas more readable
        node["type"].remove(_NULL_TYPE)
    node["type"].append(_NULL_TYPE)
else:
    node["type"] = [node["type"], _NULL_TYPE]
```

I was able to get around it by modifying the code locally and adding this check before line 112:
```python
if node.get("type", "") == "":
    node["type"] = "string"
```

# Expected Behavior
I think it would be great if the connector builder can implicitly convert null types to STRING.
It would also be nice if a more detailed error regarding which "Attribute" (aka Node) is causing the issue.

I can't upload the full logs. I noticed that `Secrets` are included in the logs for the Connector Builder I would rather not risk it.

### Relevant log output

_No response_

### Contribute

- [ ] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by imrehg**
## What

Schema cleaning in the CDK fails if the parsed schema node does not declare a "type" of any kind. This results in obscure failures e.g. in the connection builder when trying to validate responses.

Relevant to #39133

## How

Upon closer look, the `type` entry is missing in cases when there's an `anyOf` entry that is not decomposed by the code into regular `type` entries (ie. the `anyOf` is not just 2 entries: a basic type and a null).

Thus the cleanup code might look for a `type` when it shouldn't exists, that is when legitimate `anyOf` is still part of the cleaned up JSON Schema node.

So the code shouldn't do the `type` array final cleanup, unless it has something to operate on.

## Review guide

1. `schema_inferrer.py`

## User Impact

There shouldn't be any negative effect, the behaviour should be transparent to users.

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by marcosmarxm — COMMENTED** [review]
Thanks @imrehg, @natikgadzhi is this something your team can take a look in next sprint?

**Comment by natikgadzhi** [comment]
I’m already on it, Marcos!

**Review by natikgadzhi — COMMENTED** [review]
This makes sense to me, but I'd love @brianjlai to have a quick look and a sanity check. I'll set this to auto merge when this gets an approval, and kick off the CI again.

**Comment by tturkenitz** [comment]
Hi @brianjlai,

Have you had a chance to review this MR? Resolving this issue would be really helpful.

Thanks!

**Comment by marcosmarxm** [comment]
@brianjlai please take a look! Thanks!

**Comment by tturkenitz** [comment]
> @brianjlai please take a look! Thanks!

Hi,

It's been a little over two weeks, and I don't want to seem pushy, but I would appreciate some progress on this. It looks like Brian may be too busy or not active. Is there anyone else who can review this PR?

Thank you.

**Comment by tturkenitz** [comment]
@marcosmarxm and @natikgadzhi,

Could someone else review this PR? Brian hasn't been responding for the past two weeks, so I'm not sure if he's available.

**Comment by bazarnov** [comment]
We did something similar recently: https://github.com/airbytehq/airbyte/pull/40667 

Can we resolve conflicts for this PR, and check the result after, to understand whether or not it fixes the related described issues with missing `type` for `anyOf`?

**Comment by tturkenitz** [comment]
> We did something similar recently: #40667
> 
> Can we resolve conflicts for this PR, and check the result after, to understand whether or not it fixes the related described issues with missing `type` for `anyOf`?

@bazarnov , I've tested your fix from #40667 which was made available in v0.63.5 and it did not solve the specific use-case that this PR aims to resolve.

It would have been great if this MR had been reviewed and pushed before any new changes were made. It's been pending for almost a month now, and I think it needs some attention from the repo maintainers because the person asked to review this is not responding at all.

**Comment by tturkenitz** [comment]
It might be easier for @imrehg to handle that directly since I don't have permissions on his fork to rebase from the Airbyte master. I could create a new fork and PR, but I'll give imrehg a chance to address this first.

**Comment by tturkenitz** [comment]
@bazarnov,

I might have misunderstood the deployment flow of this project. I assumed your [MR](https://github.com/airbytehq/airbyte/pull/40667) was included in Airbyte [v0.63.5](https://github.com/airbytehq/airbyte/releases/tag/v0.63.5) since it appears in the changelog, but when I pull that version, or even later ones like v0.63.6, your changes are not reflected in `schema_inferrer.py`.

Is this a deployment issue, or do such changes only appear in minor versions and not patches?

Your MR does address some inference issues, and I think it could be extended to handle cases where it is completely missing from the node:

```python
if _ANY_OF in node:
    self._clean_any_of(node)
else:
    self._push_any_off(node)
```

**Comment by bazarnov** [comment]
@tturkenitz The CDK was not published after the change you mentioned; there were other follow-ups additionally on top of that one. Now it should be fixed, please try to get these updates with the latest Airbyte release, which is `0.63.8` (as of this moment)

**Pull request closed without merging**
