### PR TITLE
🏥 Source Connectors: Pin airbyte-cdk version to `^0`

### PR DESCRIPTION
**Pull request by tolik0**
## What
Pin the airbyte-cdk version to ^0 to fix an error in acceptance tests related to the new validation of state messages:
```
    @staticmethod
    def _validate_state_messages(state_messages: List[AirbyteMessage], configured_catalog: ConfiguredAirbyteCatalog):
        # Ensure that at least one state message is emitted for each stream
>       assert len(state_messages) >= len(
            configured_catalog.streams
        ), "At least one state message should be emitted for each configured stream."
E       AssertionError: At least one state message should be emitted for each configured stream.
```

## How
Sources that were successfully updated after increasing the CDK version include:
- Airtable
- Amazon Ads
- Github
- Google Ads
- Google Analytics v4
- Google Search Console
- Iterable
- Jira
- Klaviyo
- Linkedin Ads
- Marketo
- Mixpanel
- Pinterest
- Slack
- Snapchat Marketing

Sources that required additional fixes:
- Amazon Seller Partner - Fixed integration unit tests.
- Bing Ads - Fixed integration unit tests.
- Instagram - Fixed integration tests.
- Source File - Resolved a minor conflict with the latest CDK version.

Other fixes include:

- Google Sheets - Disabled a new test for state validation.
- Twilio - Updated the expected records.

### CODE REVIEW

**Comment by brianjlai** [comment]
@tolik0 

just noting as per some discussions on the thread too. We should not bump the ones that do not pass tests. I did some investigation yesterday and some are legitimate test failures due to upgrades to the CDK both related and unrelated to record counts

Unrelated to record counts, but fails because of a change to how low-code stream slicing due to using custom components:
`source-monday`
`source-chargebee`

Implementation issues for full refresh streams that define `get_updated_state()`
`source-google-analytics-data-api`
`source-tiktok-marketing`

^ For this one I have https://github.com/airbytehq/airbyte/pull/36302 that I was doing some testing for these two sources. I'll own that fix. This one has some weird behavior that I want to discuss w/ extensibility before putting it up for review

**Comment by tolik0** [comment]
@brianjlai Thanks for the fixes for TikTok and Google Analytics! I've updated the PR description with an explanation of the fixes.

**Review by askarpets — APPROVED** [review]
💪🫵

**Review by brianjlai — COMMENTED** [review]
We should be incrementing connector versions using the minor number instead of patch because we are effectively releasing record counts for these connectors which is a feature add not a bug fix

**Review by brianjlai — APPROVED** [review]
thank you for adjusting the minor versions instead of patch. I know it was probably tedious

**Pull request merged**
