### PR TITLE
CAT: validate stream schemas to be valid json schemas

### LINKED ISSUE #29422: Add a CAT test to ensure the catalog has valid JSON nodes
First noticed: https://github.com/airbytehq/oncall/issues/2703
Sibling Issue: https://github.com/airbytehq/airbyte-platform-internal/issues/8350

## Problem
We do not validate if the catalog emitted from a connector is valid json schema

As a result a catalog was persisted and used for months until the error was eventually caught by the Catalog Diff Method which throws an exception in this case
https://www.jsonschemavalidator.net/s/HU2gflxO
## Quick Fix
We loosened the check of the catalog diff: https://github.com/airbytehq/airbyte-protocol/pull/44

## Long term fix
We add a CAT test that checks that all property nodes are valid json objects

### PR DESCRIPTION
**Pull request by davydov-d**
## What
Fixed https://github.com/airbytehq/airbyte/issues/29422

## How
- Run json schema validation against every stream schema

### CODE REVIEW

**Review by lazebnyi — APPROVED** [review]
lgtm

**Comment by davydov-d** [comment]
@evantahler can you please take a quick look?

**Review by bnchrch — APPROVED** [review]
@lazebnyi THANK YOU SO MUCH FOR THIS! YES!

Did you have the time to run the CAT test against some connectors? 

The only reason I ask is before we merge we should be reasonably sure we wont blow up the nightly reports.

Approving in advance though.

Thanks again

**Review by tolik0 — APPROVED** [review]

**Comment by bnchrch** [comment]
@davydov-d @lazebnyi It looks like theres been a bad rebase? Could you take a look? Afterwards it seems like we should be good to merge :)

**Pull request merged**
