### PR TITLE
Update connector oneOf descriptions

### PR DESCRIPTION
**Pull request by flash1293**
## What

Related to https://github.com/airbytehq/airbyte/pull/19983

Updates the specs to use the new ability of listing options in the tooltip - right now the places specs changed in this PR have the options listed in the description of the oneOf property itself, which means it's showing twice now.

This PR moves these descriptions into the individual options instead.

### CODE REVIEW

**Review by grishick — APPROVED** [review]

**Comment by grishick** [comment]
@flash1293 you can go ahead and publish the updated connector versions using `publish` command. Don't forget to publish strict-encrypt variants after you publish the regular ones.

**Comment by flash1293** [comment]
Merging as discussed with @subodh1810

**Pull request merged**
