### PR TITLE
🐛 Destination Databricks: Fix the S3 table path to use schema from the configured schema instead of the default.

### PR DESCRIPTION
**Pull request by tanawatpan**
## What
The Airbyte Databricks Connector for S3 currently constructs table paths using a default schema value when multiple schemas contain tables with the same name, leading to potential data overlap or collisions in S3.

## How
Instead of using a default schema value, the connector will use the `schema` in the configured `Destination Namespace`. This change allows for distinct and schema-specific paths for each table.

## 🚨 User Impact 🚨
the schema of the S3 Destination location will be derived from the Destination Namespace (if specified).

## Test
image

### CODE REVIEW

**Comment by tanawatpan** [comment]
@gisripa What do you think?

**Comment by gisripa** [comment]
@tanawatpan  We had to the pin the version https://github.com/airbytehq/airbyte/blob/0adf2669aa71b040d67d6f1ab58cbf5aa748f6d3/airbyte-integrations/connectors/destination-databricks/metadata.yaml#L14 due to a library incompatibility and didn't have bandwidth to upgrade this connector. How do you feel about running a forked build for now (if it builds), we will be revamping this connector very soon.

**Comment by tanawatpan** [comment]
@gisripa Sure, I'll run a forked build for now and watch for the updated connector.

**Comment by anchitagarwal** [comment]
Hi @gisripa how soon is the revamp for databricks connector? Is there a roadmap or issue I can track?

**Pull request closed without merging**
