### PR TITLE
🐛 Update Survey Monkey Incremental Streams

### PR DESCRIPTION
**Pull request by danieldiamond**
## What
https://github.com/airbytehq/airbyte/issues/11453

## How
Fix `get_updated_state` function

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

python -m pytest unit_tests
Test session starts (platform: darwin, Python 3.9.12, pytest 6.2.4, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /Users/danieldiamond/repos/airbyte, configfile: pytest.ini
plugins: sugar-0.9.4, requests-mock-1.9.3, mock-3.7.0, timeout-1.4.2
collecting ...
 airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource.test_get_updated_state_lesser[current_state0-lesser_date_record0-expected_state0] ✓14% █▌
 airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource.test_get_updated_state_lesser[current_state1-lesser_date_record1-expected_state1] ✓29% ██▉
 airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource.test_get_updated_state_lesser[current_state2-lesser_date_record2-expected_state2] ✓43% ████▍
 airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource.test_get_updated_state_bigger[current_state0-bigger_date_record0-expected_state0] ✓57% █████▊
 airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource.test_get_updated_state_bigger[current_state1-bigger_date_record1-expected_state1] ✓71% ███████▎
 airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource.test_get_updated_state_bigger[current_state2-bigger_date_record2-expected_state2] ✓86% ████████▋
 airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource.test_get_updated_state_from_null_state ✓100% ██████████
======================================================== warnings summary ========================================================
airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource::test_get_updated_state_lesser[current_state0-lesser_date_record0-expected_state0]
airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource::test_get_updated_state_lesser[current_state1-lesser_date_record1-expected_state1]
airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource::test_get_updated_state_lesser[current_state2-lesser_date_record2-expected_state2]
airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource::test_get_updated_state_bigger[current_state0-bigger_date_record0-expected_state0]
airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource::test_get_updated_state_bigger[current_state1-bigger_date_record1-expected_state1]
airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource::test_get_updated_state_bigger[current_state2-bigger_date_record2-expected_state2]
airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource::test_get_updated_state_from_null_state
  /Users/danieldiamond/repos/airbyte/airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py:15: DeprecationWarning: Call to deprecated class TokenAuthenticator. (Use airbyte_cdk.sources.streams.http.requests_native_auth.TokenAuthenticator instead) -- Deprecated since version 0.1.20.
    authenticator = TokenAuthenticator(token=config["access_token"])

airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py: 14 warnings
  /Users/danieldiamond/.virtualenvs/airbyte/lib/python3.9/site-packages/deprecated/classic.py:173: DeprecationWarning: Call to deprecated class HttpAuthenticator. (Use requests.auth.AuthBase instead) -- Deprecated since version 0.1.20.
    return old_new1(cls, *args, **kwargs)

airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource::test_get_updated_state_lesser[current_state0-lesser_date_record0-expected_state0]
airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource::test_get_updated_state_lesser[current_state1-lesser_date_record1-expected_state1]
airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource::test_get_updated_state_lesser[current_state2-lesser_date_record2-expected_state2]
airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource::test_get_updated_state_bigger[current_state0-bigger_date_record0-expected_state0]
airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource::test_get_updated_state_bigger[current_state1-bigger_date_record1-expected_state1]
airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource::test_get_updated_state_bigger[current_state2-bigger_date_record2-expected_state2]
airbyte-integrations/connectors/source-surveymonkey/unit_tests/test_for_updated_state.py::TestSurveymonkeySource::test_get_updated_state_from_null_state
  /Users/danieldiamond/.virtualenvs/airbyte/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py:42: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    self._authenticator: HttpAuthenticator = NoAuth()

-- Docs: https://docs.pytest.org/en/stable/warnings.html

Results (0.16s):
       7 passed

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by danieldiamond** [comment]
cc'ing @grubberr @marcosmarxm

**Comment by danieldiamond** [comment]
Hold up, integration tests dont seem to include responses!

**Comment by danieldiamond** [comment]
@marcosmarxm are you able to check this works incrementally with more than 1 survey i.e. that it doesnt just use the latest cursor field for all responses when its pulling responses for a specific survey

**Comment by harshithmullapudi** [comment]
/publish connector=connectors/source-surveymonkey auto-bump-version=false

**Pull request merged**
