### PR TITLE
Update the workflow being replayed

### PR DESCRIPTION
**Pull request by benmoriceau**
## What
Update the workflow being replayed.

The workflow history we are replaying is very old and can hide some potential version issue like what happened [here](https://github.com/airbytehq/airbyte/pull/14715/files/1fa8953562dc3167e4481328532bf8ab02c5ef3f#r921634834).

This review is updating the history with a recent workflow that ran in prod.

### CODE REVIEW

**Review by evantahler — APPROVED** [review]
Nice - gotta keep that test data fresh.

Can you share how you got this workflow data?  Did you just download it from the Temporal UI?

**Review by pedroslopez — APPROVED** [review]
👍🏻 is this something that should be done any time a new version is introduced?
Also, is there any value in keeping tests with old histories to ensure they still pass?

**Comment by benmoriceau** [comment]
> Nice - gotta keep that test data fresh.
> 
> Can you share how you got this workflow data? Did you just download it from the Temporal UI?

@evantahler Yes I downloaded it from there. There is a download button on the top right of [this](https://web.prod.ebc2e.tmprl.cloud/namespaces/prod.ebc2e/workflows/connection_manager_df7e6886-4581-40ee-bae5-9e7ff271da3c/adbe51a0-6d72-4e51-afed-98f7df878e4c/history/compact) interface.

**Comment by benmoriceau** [comment]
> 👍🏻 is this something that should be done any time a new version is introduced?
> Also, is there any value in keeping tests with old histories to ensure they still pass?

Ideally yes, that will allow to avoid issue like the one you faced. We didn't enforce it so far and the test suite is not complete (doesn't include any failure or cancel or reset...)

**Pull request merged**
