### PR TITLE
Move JsonSchemaValidator into its own module airbyte-validation (#234)

### PR DESCRIPTION
**Pull request by ChristopheDuong**
## What

The JsonSchemaValidator class is in commons module so that it can be shared with the worker and few other modules, but that is not ideal because it injects these dependencies into all modules that use commons. 

Ideally this class should be split out into its own module.

## How

Creating a airbyte-validation module and moving its dependencies, JsonValidationException class and test into it

### CODE REVIEW

**Review by cgardens — APPROVED** [review]
awesome! i might call the module `airbyte-json-validation` since we are not likely to add other types of validations to this modules (because the dependencies would likely be different). just the module name though, the package name you've chosen is great! what do you think?

doing that just requires changing the name of the directory that all the module code is in from `airbyte-analytics` => `airbyte-json-validation`.

**Comment by ChristopheDuong** [comment]
Good point! I renamed both the directory and module names as you suggested and changed the build.gradle files that depend on it accordingly.

Is this what you had in mind? 

There was also the option of renaming only the folder name, keep `airbyte-validation` module and tweak the settings.gradle file to specify the projectDir but that sounded potentially confusing

**Review by michel-tricot — APPROVED** [review]
Cool!

**Comment by cgardens** [comment]
this looks great!

**Comment by ChristopheDuong** [comment]
FYI I merged master into my branch in order to resolve the conflicts (so it'll be easier to merge back to master afterward)... 
Actually, I'm not so sure if that was a good approach now...

**Comment by cgardens** [comment]
Yeah. it looks like a bunch of stuff got included that shouldn't be in there.

**Comment by ChristopheDuong** [comment]
Ok it's now fixed and in a cleaner state without conflicts for merging !!

**Review by michel-tricot — APPROVED** [review]

**Pull request closed without merging**
