### PR TITLE
connectors-ci: better connector test debugging experience (1/2)

### PR DESCRIPTION
**Pull request by alafanechere**
## What
https://github.com/airbytehq/airbyte/issues/27497
We want to better share connector test results with connector developer.
I made the test report generate an HTML page that we upload to our `airbyte-ci-reports` public bucket.
The link to the reports are shared in the test summary commented on the PR.
We'll make them available on nightly build daily report in a second PR.

## How
* Create a jinja template for reports
* Redact secrets from stdout or stderr to get the same level of secret masking we have in GHA
* Upload html reports to GCS when running in the CI, otherwise open the local HTML file in the default web browser.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-openweather test report (commit [`546e1513f0`](https://github.com/airbytehq/airbyte/pull/27550/commits/546e1513f02343aba38bded986a6f22ce8406ab2)) - ✅

⏲️  Total pipeline duration: 20 seconds

| Step                  | Result   |
|:----------------------|:---------|
| Format connector code | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/format/pull_request/augustin_connectors-ci_better-logging-ux/1687361380/546e1513f02343aba38bded986a6f22ce8406ab2/source-openweather/0.1.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-openweather test
```

**Comment by octavia-squidington-iii** [comment]
##  source-openweather test report (commit [`bf29c1c260`](https://github.com/airbytehq/airbyte/pull/27550/commits/bf29c1c260d9686093d4310db590c3cf5c1178e7)) - ✅

⏲️  Total pipeline duration: 68 seconds

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/augustin_connectors-ci_better-logging-ux/1687361430/bf29c1c260d9686093d4310db590c3cf5c1178e7/source-openweather/0.1.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-openweather test
```

**Comment by octavia-squidington-iii** [comment]
##  source-openweather test report (commit [`3a07df5a3e`](https://github.com/airbytehq/airbyte/pull/27550/commits/3a07df5a3e8963b8990bbca460bf90688c00d66a)) - ✅

⏲️  Total pipeline duration: 9 seconds

| Step                  | Result   |
|:----------------------|:---------|
| Format connector code | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/format/pull_request/augustin_connectors-ci_better-logging-ux/1687363704/3a07df5a3e8963b8990bbca460bf90688c00d66a/source-openweather/0.1.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-openweather test
```

**Comment by octavia-squidington-iii** [comment]
##  source-openweather test report (commit [`23af226828`](https://github.com/airbytehq/airbyte/pull/27550/commits/23af226828a9e86f655a5ca28423280acd24f54c)) - ❌

⏲️  Total pipeline duration: 137 seconds

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-openweather/metadata.yaml | ✅        |
| Connector version semver check.                                           | ✅        |
| Connector version increment check.                                        | ❌        |
| QA checks                                                                 | ✅        |
| Code format checks                                                        | ✅        |
| Connector package install                                                 | ✅        |
| Build source-openweather docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                | ✅        |
| Acceptance tests                                                          | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/augustin_connectors-ci_better-logging-ux/1687363738/23af226828a9e86f655a5ca28423280acd24f54c/source-openweather/0.1.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-openweather test
```

**Comment by octavia-squidington-iii** [comment]
##  source-openweather test report (commit [`91815e0fa4`](https://github.com/airbytehq/airbyte/pull/27550/commits/91815e0fa43a6fdea421cbbd465346c8bc5111d1)) - ❌

⏲️  Total pipeline duration: 93 seconds

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-openweather/metadata.yaml | ✅        |
| Connector version semver check.                                           | ✅        |
| Connector version increment check.                                        | ❌        |
| QA checks                                                                 | ✅        |
| Code format checks                                                        | ✅        |
| Connector package install                                                 | ✅        |
| Build source-openweather docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                | ✅        |
| Acceptance tests                                                          | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/augustin_connectors-ci_better-logging-ux/1687364792/91815e0fa43a6fdea421cbbd465346c8bc5111d1/source-openweather/0.1.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-openweather test
```

**Comment by octavia-squidington-iii** [comment]
##  source-openweather test report (commit [`9244f5bd67`](https://github.com/airbytehq/airbyte/pull/27550/commits/9244f5bd677307d97f379cc2cf9f9f49e1a10b92)) - ❌

⏲️  Total pipeline duration: 95 seconds

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-openweather/metadata.yaml | ✅        |
| Connector version semver check.                                           | ✅        |
| Connector version increment check.                                        | ❌        |
| QA checks                                                                 | ✅        |
| Code format checks                                                        | ✅        |
| Connector package install                                                 | ✅        |
| Build source-openweather docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                | ✅        |
| Acceptance tests                                                          | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/augustin_connectors-ci_better-logging-ux/1687365242/9244f5bd677307d97f379cc2cf9f9f49e1a10b92/source-openweather/0.1.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-openweather test
```

**Comment by octavia-squidington-iii** [comment]
##  source-pokeapi test report (commit [`f62c869853`](https://github.com/airbytehq/airbyte/pull/27550/commits/f62c869853d2a81655597d82146bf3b9278d75c7)) - ❌

⏲️  Total pipeline duration: 98 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-pokeapi/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-pokeapi docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/augustin_connectors-ci_better-logging-ux/1687365425/f62c869853d2a81655597d82146bf3b9278d75c7/source-pokeapi/0.1.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-pokeapi test
```

**Comment by octavia-squidington-iii** [comment]
##  source-pokeapi test report (commit [`8ddc9e4897`](https://github.com/airbytehq/airbyte/pull/27550/commits/8ddc9e4897272b6cbc224c98d35058d1321bda7b)) - ❌

⏲️  Total pipeline duration: 102 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-pokeapi/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ❌        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-pokeapi docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/augustin_connectors-ci_better-logging-ux/1687365649/8ddc9e4897272b6cbc224c98d35058d1321bda7b/source-pokeapi/0.1.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-pokeapi test
```

**Review by evantahler — APPROVED** [review]
Those HTML reports are :chef-kiss-emoji:!

In a later PR we will see:
* cloudflare auth + sub domain 
* links for nightly tests

**Pull request merged**
