### PR TITLE
[docs] add note on airbyte vs singer

### PR DESCRIPTION
**Pull request by swyxio**
to clarify question raised during conference, and answered by @johnlafleur 

@gosusnp i'm wondering if we need to note anything for [Protocol v1] (https://github.com/airbytehq/airbyte/pull/19846)?

### CODE REVIEW

**Review by evantahler — APPROVED** [review]
👍 for docs!

**Comment by evantahler** [comment]
@sw-yx What about https://github.com/airbytehq/airbyte/blob/ca67ee7a1ff05e4d5b5fb3a4408a72714f8137c7/docs/understanding-airbyte/airbyte-protocol.md#L902-L904

**Comment by gosusnp** [comment]
@sw-yx, what kind of notes did you have in mind?

I was looking at the change that added some changes that are going to be tagged as part of v1 (https://github.com/airbytehq/airbyte/pull/17486)
Updates have been done in place, I think we should go over those changes and keep some version specific documentation.

**Comment by sw-yx** [comment]
@evantahler it doesnt link to the comparison doc, and its position at the end makes it hard to find leading poeple to still ask us despite including that mention

@gosusnp no other notes!

**Comment by natikgadzhi** [comment]
Haven't heard the ask in a while, and Singer seems to be, ahem, more and more out of date.

**Pull request closed without merging**
