### PR TITLE
source-xsolla contribution from avirajsingh7

### LINKED ISSUE #46089: [connector-request] Xsolla
This is a **suggestion** to create a connector for **Xsolla** using the UI Connector Builder.
The website for the connector is https://xsolla.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

### PR DESCRIPTION
**Pull request by avirajsingh7**
Closing issue : #46089

## What

This PR adds a new connector for source Xsolla (source-xsolla).

Contributor-provided connector description:

The Xsolla Airbyte Connector enables seamless integration between Xsolla and various data destinations. This connector allows you to extract data from Xsolla’s APIs, such as Game Catalog, Virtual Items, Virtual Currency and more.
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key. Go to Xsolla Dashboard and from company setting get the api_key |  |
| `project_id` | `number` | Project Id. You can find this parameter in your Publisher Account next to the name of the project . Example: 44056 |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| Games Catalog | item_id | DefaultPaginator | ✅ |  ❌  |
| DRM | drm_id | No pagination | ✅ |  ❌  |
| Virtual Items | item_id | DefaultPaginator | ✅ |  ❌  |
| Virtual Currency | item_id | DefaultPaginator | ✅ |  ❌  |
| Virtual Currency Package | item_id | DefaultPaginator | ✅ |  ❌  |
| Bundles | item_id | DefaultPaginator | ✅ |  ❌  |
| Reward Chains | reward_chain_id | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Small detail, would be possible to include `promotions` stream?

**Comment by avirajsingh7** [comment]
@marcosmarxm There are many api in xsolla which are server side and particularly for promotions has base url https://api.xsolla.com/merchant/v2/ which is different than base url used for this one https://store.xsolla.com/api.

So we can rename this one as connectors as Xsolla Store 
And I can create another connector as Xsolla Subscriptions (https://developers.xsolla.com/api/subscriptions/overview/) which can have following endpoints :
Get Subscriptions
Get Promotions List
Get Plans
Get Products
Get Payments
Get Currencies

**Comment by marcosmarxm** [comment]
@avirajsingh7 let's move this way! Thanks for the investigation!

**Review by marcosmarxm — APPROVED** [review]
LGTM Awesome contribution @avirajsingh7 !

**Pull request merged**
