### PR TITLE
test breaking change validation on faker

### PR DESCRIPTION
**Pull request by erohmensing**
this is not a draft because we don't run testing/validation on drafts.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`b3d4f95ba1`](https://github.com/airbytehq/airbyte/pull/28414/commits/b3d4f95ba1202e403e74983ab151b747176c2d81)) - ❌

⏲️  Total pipeline duration: 07mn22s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| Connector version increment check                                   | ❌        |
| QA checks                                                           | ✅        |
| Code format checks                                                  | ❌        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_faker-bc/1689710099/b3d4f95ba1202e403e74983ab151b747176c2d81/source-faker/3.0.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by erohmensing** [comment]
Connector version did not increment - as expected

Black failed - I probably introduced this? 

Build image failed. Why?

**Comment by erohmensing** [comment]
trying to fix black: 
```
python -m black --config=/pyproject.toml --check .
```
doesn't run in my python environment. how do I as a connector dev make sure I can run the same black so I can fix it?

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`d51ca8393c`](https://github.com/airbytehq/airbyte/pull/28414/commits/d51ca8393cb6cab5d2dda1da44b3ddc31fe430e1)) - ❌

⏲️  Total pipeline duration: 07mn19s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ❌        |
| Connector version semver check                                      | ✅        |
| Connector version increment check                                   | ✅        |
| QA checks                                                           | ❌        |
| Code format checks                                                  | ❌        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_faker-bc/1689711154/d51ca8393cb6cab5d2dda1da44b3ddc31fe430e1/source-faker/4.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by erohmensing** [comment]
We really don't get _any_ information about what fails right now do we 
image

**Comment by erohmensing** [comment]
You can get the dagger logs, but searching them is hard: 

image

**Comment by erohmensing** [comment]
found qa check failures: 

image

**Comment by erohmensing** [comment]
while lthat is running i looked for the validation error. 

Found it, but some log coloring/separating would go a long way, cause this is real hard to read: 

image

**Comment by erohmensing** [comment]
Side note: my IDE does this, which is annoying since "spec" is required, but we fill it, I think. Maybe there should be different jsonschemas for what the connector devs need to fill in versus what a fully fleshed metadata file with generated info needs to look like 
image

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`cc65a427f0`](https://github.com/airbytehq/airbyte/pull/28414/commits/cc65a427f0a35223ee71fd100ff3311a97524681)) - ❌

⏲️  Total pipeline duration: 07mn35s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ❌        |
| Connector version semver check                                      | ✅        |
| Connector version increment check                                   | ✅        |
| QA checks                                                           | ✅        |
| Code format checks                                                  | ❌        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_faker-bc/1689712387/cc65a427f0a35223ee71fd100ff3311a97524681/source-faker/4.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by erohmensing** [comment]
it takes about 12 minutes to get results posted to the new comment. I know that the qa checks, validation etc don't take that long. it would be nice if we got each step reported when it was done for faster iteration especially for this breaking change process

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`031eb97203`](https://github.com/airbytehq/airbyte/pull/28414/commits/031eb97203734bbc62c36a67d7fa07ff72383c0e)) - ❌

⏲️  Total pipeline duration: 04mn44s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| Connector version increment check                                   | ✅        |
| QA checks                                                           | ❌        |
| Code format checks                                                  | ❌        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_faker-bc/1689712993/031eb97203734bbc62c36a67d7fa07ff72383c0e/source-faker/4.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by erohmensing** [comment]
check_migration_guide didn't give me any info as to what I was missing: 
image

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`d62f67c110`](https://github.com/airbytehq/airbyte/pull/28414/commits/d62f67c1106fad9cf0bde0cc9f6e66d2becf6c30)) - ❌

⏲️  Total pipeline duration: 04mn33s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| Connector version increment check                                   | ✅        |
| QA checks                                                           | ❌        |
| Code format checks                                                  | ❌        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_faker-bc/1689715623/d62f67c1106fad9cf0bde0cc9f6e66d2becf6c30/source-faker/4.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`e5b3d6931b`](https://github.com/airbytehq/airbyte/pull/28414/commits/e5b3d6931b2d75d498f45a96805c271fa9d261e2)) - ❌

⏲️  Total pipeline duration: 05mn10s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| Connector version increment check                                   | ✅        |
| QA checks                                                           | ❌        |
| Code format checks                                                  | ❌        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_faker-bc/1689716092/e5b3d6931b2d75d498f45a96805c271fa9d261e2/source-faker/4.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by erohmensing** [comment]
merge in master for pipeline fixes

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`504c37e7f4`](https://github.com/airbytehq/airbyte/pull/28414/commits/504c37e7f4eb778bbd118c6cce176a2807ec8957)) - ❌

⏲️  Total pipeline duration: 02mn03s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| Connector version increment check                                   | ✅        |
| QA checks                                                           | ❌        |
| Code format checks                                                  | ❌        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ✅        |
| Acceptance tests                                                    | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_faker-bc/1689776393/504c37e7f4eb778bbd118c6cce176a2807ec8957/source-faker/4.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by erohmensing** [comment]
Wanted to run qa engine locally but the installation is being complicated - its confusing that its different than airbyte-ci's installation. I'd expect them to be together

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`de052debe1`](https://github.com/airbytehq/airbyte/pull/28414/commits/de052debe1e7d9ebe5a7334f3f6e8095a3ef10d0)) - ❌

⏲️  Total pipeline duration: 02mn05s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| Connector version increment check                                   | ✅        |
| QA checks                                                           | ❌        |
| Code format checks                                                  | ❌        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ✅        |
| Acceptance tests                                                    | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_faker-bc/1689778169/de052debe1e7d9ebe5a7334f3f6e8095a3ef10d0/source-faker/4.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by erohmensing** [comment]
Hm QA checks pass locally but not in the pr, this is sus

**Comment by erohmensing** [comment]
Definitely looking cache-y 

image

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`83549329cd`](https://github.com/airbytehq/airbyte/pull/28414/commits/83549329cda11dc1dabdb95d7011e69a1d722074)) - ❌

⏲️  Total pipeline duration: 01mn16s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| Connector version increment check                                   | ✅        |
| QA checks                                                           | ❌        |
| Code format checks                                                  | ❌        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ✅        |
| Acceptance tests                                                    | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_faker-bc/1689781255/83549329cda11dc1dabdb95d7011e69a1d722074/source-faker/4.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by erohmensing** [comment]
Figured out (I think) how to format the code like ci wants me to by messing around with airbyte-ci.

Tried `airbyte-ci connectors format` but its mad because my docker-desktop daemon is not running. This is because I don't use this context for anything else, since local dev stuff is in colima

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`492f59d0a9`](https://github.com/airbytehq/airbyte/pull/28414/commits/492f59d0a995f9ac1d334d7d1747e34e5abf08ab)) - ✅

⏲️  Total pipeline duration: 03mn25s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| Connector version increment check                                   | ✅        |
| QA checks                                                           | ✅        |
| Code format checks                                                  | ✅        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ✅        |
| Acceptance tests                                                    | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_faker-bc/1689785435/492f59d0a995f9ac1d334d7d1747e34e5abf08ab/source-faker/4.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by erohmensing** [comment]
Woohoo!

**Pull request closed without merging**
