### PR TITLE
Fix typo in Java CDK

### PR DESCRIPTION
**Pull request by akashkulk**
Rename CDN_LSN -> CDC_LSN

### CODE REVIEW

**Review by nguyenaiden — APPROVED** [review]
+1.

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`e29df6f238`](https://github.com/airbytehq/airbyte/pull/31196/commits/e29df6f238a75393cc69f118bccf903076f763be)) - ❌

⏲️  Total pipeline duration: 01mn49s 

| Step                                  | Result   |
|:--------------------------------------|:---------|
| Build connector tar                   | ❌        |
| Validate metadata for source-postgres | ✅        |
| Connector version semver check        | ✅        |
| QA checks                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cdk-playground/1696890248/e29df6f238a75393cc69f118bccf903076f763be/source-postgres/3.1.9/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e29df6f238a75393cc69f118bccf903076f763be)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`e84d27fb9c`](https://github.com/airbytehq/airbyte/pull/31196/commits/e84d27fb9c056643d40c7d083b087662cfd38ecc)) - ❌

⏲️  Total pipeline duration: 11mn36s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build connector tar                                             | ✅        |
| Build source-postgres docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                       | ❌        |
| Java Connector Integration Tests                                | ❌        |
| Acceptance tests                                                | ✅        |
| Validate metadata for source-postgres                           | ✅        |
| Connector version semver check                                  | ✅        |
| QA checks                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cdk-playground/1696908943/e84d27fb9c056643d40c7d083b087662cfd38ecc/source-postgres/3.1.9/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e84d27fb9c056643d40c7d083b087662cfd38ecc)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
