### PR TITLE
Upgrade spotless version and remove jvmargs workaround

### PR DESCRIPTION
**Pull request by tisonkun**
Since https://github.com/diffplug/spotless/issues/834 got resolved in v6.7.1. We don't have to add this workaround any longer.

### CODE REVIEW

**Comment by alafanechere** [comment]
@cgardens are you still available for a review? 🙏

**Comment by cgardens** [comment]
@alafanechere this looks good to me as long as the build passes. I hit the run build button but i guess it doesn't run the platform build. can you help me out here, please?

**Comment by alafanechere** [comment]
> @alafanechere this looks good to me as long as the build passes. I hit the run build button but i guess it doesn't run the platform build. can you help me out here, please?

Yep we can't run our usual CI checks from a fork contribution. I'll open a side branch to run these and will merge if the platform build passes.

**Review by alafanechere — APPROVED** [review]
CI checks passed on https://github.com/airbytehq/airbyte/pull/14219

**Comment by etsybaev** [comment]
It seems like this change caused an issue when the project can't be normally imported to IntellijIdea if you clone and import it from scratch. Some of gradles tasks fail and IntellijIdea even can't build gradle tasks tree and import project properly. 
It works if I downgraded to version 6.6.0, but started failing since version 6.6.1


Here are more details: https://airbytehq.slack.com/archives/C02U9R3AF37/p1657111670412769

Selection_344
Selection_341
Selection_346

**Pull request merged**
