### PR TITLE
[destination-astra] Add user-agent with caller name

### PR DESCRIPTION
**Pull request by hemidactylus**
## What

This PR adds a custom user-agent header field to the Astra DB Data API requests for aggregate usage statistics on the API side.

## How

A new header is added in the AstraClient class, later used when issuing API command HTTP POST requests.

## Review guide

`destination_astra/astra_client.py`

## User Impact

No impact.

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
@hemidactylus can you bump the metadata version and add an entry in the changelog doc?

**Comment by hemidactylus** [comment]
Hello, @marcosmarxm , I have bumped the connector version.
I also created a new `airbyte-integrations/connectors/destination-astra/CHANGELOG.md` with just the entry for this version (could not successfully investigate for the past changes in the commit history). I created it there after finding analogous files in some of the other connectors (e.g. `airbyte-integrations/connectors/source-paypal-transaction/CHANGELOG.md`), please let me know if this is what you meant.

Thank you!

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Remove the changelog. You need to change the entry in the `doc/integrations/destiination-astra.md` file.

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
