### PR TITLE
🐛 Source Github: add incremental for `repositories`, `workflows`, `pull_request_comment_reactions`, `issue_reactions`, `issue_comment_reactions`, `commit_comment_reactions`

### LINKED ISSUE #12173: 🐛 Source Github: add incremental support to streams: Repositories, PullRequestCommentReactions, IssueReactions, IssueCommentReactions, CommitCommentReactions
## Tell us about the problem you're trying to solve
Add incremental support to streams: `Repositories`, `PullRequestCommentReactions`, `IssueReactions`, `IssueCommentReactions`, `CommitCommentReactions`

### LINKED ISSUE #12266: Source Github: add incremental support to workflow streams
## Tell us about the problem you're trying to solve
add incremental support to workflow streams

## Describe the solution you’d like
This cloud connection for internal usage: https://cloud.airbyte.io/workspaces/bed3b473-1518-4461-a37f-730ea3d3a848/connections/a6bfadb7-182a-4766-81fd-1bc70597e594/replication
1. Should work
2. Be able to setup incremental sync modes for those streams

## Related Context
See https://github.com/airbytehq/airbyte-warehouse/issues/79#issuecomment-1104407338

### PR DESCRIPTION
**Pull request by grubberr**
Signed-off-by: Sergey Chvalyuk <grubberr@gmail.com>

## What
Add incremental for streams: `repositories`, `workflows`, `pull_request_comment_reactions`, `issue_reactions`, `issue_comment_reactions`, `commit_comment_reactions`

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [x] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [x] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [x] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Review by annalvova05 — APPROVED** [review]

**Review by midavadim — APPROVED** [review]
PR cam be merged without Airbyte review

**Pull request merged**
