### PR TITLE
Source Greenhouse: add incremental sync mode

### PR DESCRIPTION
**Pull request by HaoWuPeloton**
JIRA: https://pelotoncycle.atlassian.net/browse/DE-890

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hello @HaoWuPeloton can you sign the CLA?

**Comment by HaoWuPeloton** [comment]
Hi, I don't have plan to merge this PR, it's just for some internal testing for now, please don't review this

**Comment by marcosmarxm** [comment]
> Hi, I don't have plan to merge this PR, it's just for some internal testing for now, please don't review this

@HaoWuPeloton why did you open this in Airbyte repo? Can I close it?

**Comment by marcosmarxm** [comment]
@HaoWuPeloton do you mind if I close this?

**Comment by marcosmarxm** [comment]
Close because user said doesn't plan to merge it.

**Pull request closed without merging**
