### PR TITLE
stop building normalization

### PR DESCRIPTION
**Pull request by edgao**
instead of building normalization, just pull from the already-published version. We're committed to phasing out legacy normalization, so it's not like we'll need to make changes here.

https://github.com/airbytehq/airbyte/pull/27845/commits/879246135b48be2c020c44741d8eb252aff6b85e does the same thing for the old airbyteDocker-style builds; I pushed it directly to the branch just to simplify some of the build investigations. This PR ports the logic to airbyte-ci.

also, this:

image

### CODE REVIEW

**Review by evantahler — COMMENTED** [review]
OK hear me out: does this mean that building normalization images is no longer a dependency of the connector?  Can we remove all of [this](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/build.gradle) gradle stuff?  You *can* still build the normalization images... but now we don't need to wait for tests and wantnot to do it.

**Comment by edgao** [comment]
definitely some of it. I don't think we can kill the entire base-normalization build.gradle, but e.g. https://github.com/airbytehq/airbyte/commit/879246135b48be2c020c44741d8eb252aff6b85e#diff-0f6023601f6e522b942f3a29626e10aeece3f0565e02bf70759ab789309498dc is gone.

we should do the same for the rest of our destinations when we get to them!

**Comment by evantahler** [comment]
Your base build failed, but for a reason that makes no sense:

```
2023-07-13T00:36:29.0158140Z * What went wrong:
2023-07-13T00:36:29.0159879Z Execution failed for task ':airbyte-integrations:connectors:destination-snowflake:compileIntegrationTestJavaJava'.
2023-07-13T00:36:29.0161231Z > Compilation failed; see the compiler error output for details.
```

**Review by evantahler — APPROVED** [review]
👍 once the tests pass... or maybe not even then

**Comment by edgao** [comment]
I think the snowflake build was broken on master for a bit - merging latest should fix 🤞

**Comment by edgao** [comment]
oh hm - this pr didn't actually trigger any test pipelines... so I missed the fact that it broke the ability to run tests >.>

pushed https://github.com/airbytehq/airbyte/pull/27936/commits/aa7b02943ab39ad6ff7fb38b89bb9a2069e623b3 to the 1s1t_redeploy branch, which seems to be working locally (or at least the tests are running now)

**Pull request merged**
