### PR TITLE
Publish 11514

### PR DESCRIPTION
**Pull request by alafanechere**
An attempt at publishing connectors impacted by #11514 to benefit from auto-bump.

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537070853) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by alafanechere** [comment]
✅ Already published but requires manual bump:
* destination-postgres
* destination-mssql
* source-clickhouse
* source-postgres
* source-mysql

**Comment by alafanechere** [comment]
/publish connector=connectors/destination-mariadb-columnstore

**Comment by alafanechere** [comment]
The `strict-encrypt` connector will have to be published then.

**Comment by grishick** [comment]
I manually bumped version for destination-postgres [here](https://github.com/airbytehq/airbyte/pull/12290)

**Comment by grishick** [comment]
destination-oracle is bumped [here](https://github.com/airbytehq/airbyte/pull/12292)

**Comment by grishick** [comment]
destination-clickhouse bumped [here](https://github.com/airbytehq/airbyte/pull/12293)

**Comment by grishick** [comment]
destination-mssql bumped [here](https://github.com/airbytehq/airbyte/pull/12291)

**Pull request closed without merging**
