### PR TITLE
🐛Source Quickbooks - Change datatype for undisclosed amount field in payments

### PR DESCRIPTION
**Pull request by pylenin**
## What
The datatype for `UnappliedAmt` is fixed as integer. The API is sending floats. Check the below logs to know more about the error.
```
18 of 337 ERROR creating incremental model _airbyte_quickbooks_4037.payments_stg........................................ [ERROR in 0.83s]
Database Error in model payments_stg (models/generated/airbyte_incremental/quickbooks_4037/payments_stg.sql)
  invalid input syntax for type bigint: "2016649.0"
Database Error in model payments_stg (models/generated/airbyte_incremental/quickbooks_4037/payments_stg.sql)
  invalid input syntax for type bigint: "2016649.0",retryable=<null>,timestamp=1685275834418,additionalProperties={}], io.airbyte.config.FailureReason@194851f8[failureOrigin=normalization,failureType=system_error,internalMessage=invalid input syntax for type bigint: "2016649.0",externalMessage=Normalization failed during the dbt run. This may indicate a problem with the data itself.,metadata=io.airbyte.config.Metadata@5c2e4a71[additionalProperties={attemptNumber=2, jobId=6366, from_trace_message=true}],stacktrace=AirbyteDbtError: 
18 of 337 ERROR creating incremental model _airbyte_quickbooks_4037.payments_stg........................................ [ERROR in 0.83s]
Database Error in model payments_stg (models/generated/airbyte_incremental/quickbooks_4037/payments_stg.sql)
  invalid input syntax for type bigint: "2016649.0"
Database Error in model payments_stg (models/generated/airbyte_incremental/quickbooks_4037/payments_stg.sql)
  invalid input syntax for type bigint: "2016649.0",retryable=<null>,timestamp=1685275834418,additionalProperties={}]],additionalProperties={}]
```

## How
In the schemas folder, the data type is being changed to number from integer.

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
No breaking changes!

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@pylenin please sign the CLA to start the review process.

**Comment by pylenin** [comment]
Hi Marcos,
I am confused as to what is the CLA. Could you please explain further!?

**Comment by pylenin** [comment]
Ok, understood what you meant! Done!

**Review by sajarin — APPROVED** [review]

**Pull request merged**
