### PR TITLE
Source Instagram: test strictness level high

### PR DESCRIPTION
**Pull request by davydov-d**
## What
Set `high` test strictness level of Instagram source 

## How
- add expected records
- fix minor bug
- refactor test config file
- add abnormal state
- add incremental catalog

### CODE REVIEW

**Review by lazebnyi — APPROVED** [review]

**Review by darynaishchenko — APPROVED** [review]

**Review by evantahler — APPROVED** [review]
Assuming the business account ID is a sandbox account, 👍!

**Pull request merged**
