### PR TITLE
(source-tiktok-marketing)  - Upgrade CDK 4.6.1

### PR DESCRIPTION
**Pull request by pnilan**
Migrates to the latest CDK version

### CODE REVIEW

**Review by brianjlai — APPROVED** [review]

**Review by brianjlai — COMMENTED** [review]
actually went to quick, is there a reason for the failing regression test run?

**Review by girarda — APPROVED** [review]
approved pending running regression tests at least once

**Review by brianjlai — APPROVED** [review]
i think we're actually on `5.0.1` now? any reservations bumping to that instead? approving, but if we move forward with that, i'll re-review if breaking

**Pull request merged**
