### PR TITLE
upgrade cloud destinations version using FailureTrackingAirbyteMessageConsumer

### PR DESCRIPTION
**Pull request by subodh1810**
related to PR https://github.com/airbytehq/airbyte/pull/10455

### CODE REVIEW

**Review by edgao — APPROVED** [review]
are you intentionally leaving this out of the changelogs?

**Comment by subodh1810** [comment]
> are you intentionally leaving this out of the changelogs?

yup.

**Comment by subodh1810** [comment]
/publish connector=connectors/destination-bigquery-denormalized

**Comment by subodh1810** [comment]
Acceptance test for Redshift and destination-bigquery-denormalized is failing. I have to make an urgent deployment so going to skip these two.

**Pull request merged**
