### PR TITLE
1349 GitHub connector

### LINKED ISSUE #1349: Github connector silently fails if the input token does not have required permissions
## Description
This was seen in #1082 , point no.3 in the issue created. The GH connector didn't have permissions to access the requested resources (which should have failed the job) but the job succeeded. 

## Acceptance Criteria for this issue: 

1. Reliably recreate the problem (and describe how it can be recreated in this issue)
2. Implement solution

### PR DESCRIPTION
**Pull request by vitaliizazmic**
## Contributor Checklist
Thanks for contributing to Airbyte! Please complete the following items in order so we can review your PR.
- [ ] Followed all the instructions in the locally generated checklist and your connector is functional & ready for review
- [ ] Ran the standard test suite locally via `./gradlew :airbyte-integrations:connectors:source-<your_source_name>:standardSourceTestPython` and pasted the summarized output as a comment in this PR

## Reviewer Pre-merge Checklist 
- [ ] Finished iterating with the PR author on the code*
- [ ] Created a branch off master to merge this PR into*
- [ ] Inject the credentials in CI via `./tools/integrations/ci_credentials.sh` and `.github/workflows/test-command.yml`*
- [ ] Added the credentials for this integration to Github secrets 
- [ ] Run standard tests on this branch by commenting `/test connector=<name>`*
- [ ] Add entry in `airbyte-config/init/src/main/resources/seed/source_definitions.yaml` to use the new source in Airbyte core
- [ ] Deployed the connector to Dockerhub via `./tools/integrations/manage.sh publish airbyte-integrations/connectors/source-<name>`

## Documentation
- [ ] Add docs in `docs/integrations/sources/` folder in line with the documentation template found in `docs/contributing-to-airbyte/templates/integration-documentation-template.md`.
- [ ] Add link to create docs file to `docs/SUMMARY.md`
- [ ] Include a link to the documentation in the `README.md`

### CODE REVIEW

**Review by sherifnada — CHANGES_REQUESTED** [review]
Thanks for adding these checks. Looks good. The only issue is that without repeating the work you did for this ticket, it’s hard to know which permissions the token is supposed to have from just reading the code ( I also noticed the [docs](https://github.com/airbytehq/airbyte/blob/master/docs/integrations/sources/github.md) don’t mention which permissions are needed). Can you: 
1. Add a comment in the code describing which permissions it is checking for
2. Update the bottom section of the [docs](https://github.com/airbytehq/airbyte/blob/master/docs/integrations/sources/github.md)  to say which scopes a user is supposed to grant the token

Separately, we'll need to bump the github connector version since this is an update in functionality. Can you bump the version in the Dockerfile, YAML, and JSON for the connector?

**Comment by eugene-kulak** [comment]
@sherifnada do we need update `Dockerfile.test` as well ?

**Comment by sherifnada** [comment]
@eugene-kulak we don't need tob ump version on test docekrfile since those are not published

**Comment by sherifnada** [comment]
@vitaliizazmic noticed the following UX issues while testing this locally: 

1. Check connection failed when checking a private personal repository (the repo is github.com/sherifnada/ios — I sent you an invite to this repo so you can access it via the API) while using `repo:all` permissions and `org:read`. I was using a personal token. Is this expected? What permissions should I enable in order to access a personal private repo? Is it different if I use an org private repo? Please use https://github.com/airbytehq/unblocker as the private org repo, and the above repo as the private non-org repo. 
For this point, could you make sure to update the documentation with the needed credentials, or let me know if I was doing something wrong on my end? 
2. Apologies for the back and forth on this point since I initially gave this guidance, but having tried this out I think the way we check for permissions right now is hard to use from a UX point of view. Specifically, we check for the “teams” permission, which a user creating the access token may not have. Therefore they may never be able to get past the “check” step if they don’t have that permission, even if they don’t want to replicate this issue. Could you make the following change:
  1. In check only verify the bare minimum permissions are available (so not every permission needed for all streams).
  2. Add another method, _check_with_catalog which takes a catalog (or names of input streams), and verifies that the provided token contains the necessary permissions for the streams we wish to replicate. If they do not, use the provided logger to log an error message containing all the missing permissions, and os.exit(1) . This method should be called at the beginning of the read method.
  3. the code currently always checks airbytehq/airbyte — could you check the repo input by the user?

**Review by sherifnada — APPROVED** [review]

**Pull request closed without merging**
