### PR TITLE
🎉Source Snowflake: Source/Destination doesn't respect DATE data type

### LINKED ISSUE #5577: Snowflake Source/Destination doesn't respect DATE data type
## Environment
* **Airbyte version**:  0.29.11-alpha
* **OS Version / Instance**: GCP COS
* **Deployment**: Docker
* **Source Connector and version**: Snowflake 0.1.1
* **Destination Connector and version**: Snowflake 0.3.12
* **Severity**: Medium
* **Step where error happened**: Schema discovery

## Current Behavior
Snowflake date types are not respected when setting up schemas

### Schema in Snowflake
image

### Schema in Airbyte
image

## Expected Behavior
TRANSACTION_DATE should be a date type

## Steps to Reproduce
1. Create table in Snowflake with a Date column type
1. Setup a source and destination snowflake to snowflake

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202102171868563/1202126680022927) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by alexandertsukanov**
## What
In https://github.com/airbytehq/airbyte/issues/5577 was reported that Snowflake source doesn't respect DATE and TIMESTAMP fields. 

There is ticket for UI part exists https://github.com/airbytehq/airbyte/issues/14671, also. However, it shouldn't be a blocker for the back-end, as the UI uses source-connector discovery schema JSON to render the field types. 

## How
Was added mapping for time-based and date-based columns to respect them in both normalization and destinations connectors.

## Recommended reading order
1. [SnowflakeSourceOperations.java](https://github.com/airbytehq/airbyte/pull/14828/files#diff-5634b31f22ac1d75ae50da9bca3cbbe8072f04e972baea8543bb7ef7739d5129)
2. Unit and integration Java tests.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Review by mkhokh-33 — APPROVED** [review]

**Review by alexandr-shegeda — APPROVED** [review]
LGTM

**Review by suhomud — APPROVED** [review]

**Review by VitaliiMaltsev — APPROVED** [review]

**Review by grishick — APPROVED** [review]

**Review by subodh1810 — APPROVED** [review]

**Comment by philippe-boyd-maxa** [comment]
It seems we now  get `The supplied date/time format type does not match the specification, expected: date` on some columns when syncing Snowflake -> Snowflake

```
...
2022-08-01 23:23:45 INFO i.a.w.g.DefaultReplicationWorker(lambda$getReplicationRunnable$6):325 - Records read: 835000 (600 MB)
2022-08-01 23:23:45 INFO i.a.w.g.DefaultReplicationWorker(lambda$getReplicationRunnable$6):325 - Records read: 836000 (600 MB)
2022-08-01 23:23:45 INFO i.a.w.g.DefaultReplicationWorker(lambda$getReplicationRunnable$6):325 - Records read: 837000 (600 MB)
2022-08-01 23:23:45 source > 2022-08-01 23:23:45 INFO i.a.d.j.s.AdaptiveStreamingQueryConfig(initialize):38 - Set initial fetch size: 10 rows
2022-08-01 23:23:50 ERROR c.n.s.DateTimeValidator(isLegalDateTime):91 - The supplied date/time format type does not match the specification, expected: date
2022-08-01 23:23:50 ERROR c.n.s.DateTimeValidator(isLegalDateTime):91 - The supplied date/time format type does not match the specification, expected: date
2022-08-01 23:23:50 ERROR c.n.s.DateTimeValidator(isLegalDateTime):91 - The supplied date/time format type does not match the specification, expected: date
2022-08-01 23:23:50 ERROR c.n.s.DateTimeValidator(isLegalDateTime):91 - The supplied date/time format type does not match the specification, expected: date
2022-08-01 23:23:50 ERROR c.n.s.DateTimeValidator(isLegalDateTime):91 - The supplied date/time format type does not match the specification, expected: date
2022-08-01 23:23:50 ERROR c.n.s.DateTimeValidator(isLegalDateTime):91 - The supplied date/time format type does not match the specification, expected: date
2022-08-01 23:23:50 ERROR c.n.s.DateTimeValidator(isLegalDateTime):91 - The supplied date/time format type does not match the specification, expected: date
2022-08-01 23:23:50 ERROR c.n.s.DateTimeValidator(isLegalDateTime):91 - The supplied date/time format type does not match the specification, expected: date
2022-08-01 23:23:50 ERROR c.n.s.DateTimeValidator(isLegalDateTime):91 - The supplied date/time format type does not match the specification, expected: date
2022-08-01 23:23:50 ERROR c.n.s.DateTimeValidator(isLegalDateTime):91 - The supplied date/time format type does not match the specification, expected: date
...
```

Could this be linked to this PR?

**Pull request merged**
