### PR TITLE
🐛 Source Harvest: updated schemas to match with Harvest API

### PR DESCRIPTION
**Pull request by jadetr**
## What
updated harvest source schema

## How
*Updated data type of some harvest schema file that were failing with BigQuery basic normalization*

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [x] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
awesome @jadetr! I'll review later today!

**Comment by jadetr** [comment]
@marcosmarxm merged with the latest changes. last commit of this source connector was still failing on my side. Those changes fix it.

**Comment by marcosmarxm** [comment]
@jadetr is it possible to you run tests locally? Now the CDK has some validations based on data returned by the API. If you need help reach me on Slack. Tests are failing: https://github.com/airbytehq/airbyte/runs/3527331020?check_suite_focus=true.

**Review by marcosmarxm — APPROVED** [review]
Awesome work @jadetr sorry took so long to review it.

**Comment by marcosmarxm** [comment]
@jadetr can you sign the CLA after I'll merge your code.

**Comment by jadetr** [comment]
@marcosmarxm CLa signed

**Comment by marcosmarxm** [comment]
Hi @jadetr this code was merged into master with PR #6516 thanks for your contribution!

**Pull request closed without merging**
