### PR TITLE
Remove config repo dependency for getStatus

### PR DESCRIPTION
**Pull request by alovew**
Remove dependency on ConfigRepo for getStatus in ConfigFetchActivityImpl

### CODE REVIEW

**Comment by jdpgrailsdev** [comment]
@benmoriceau @gosusnp:  Is this the same issue you are seeing with the Kube acceptance tests:

```
Waiting for server to be ready...
error: timed out waiting for the condition on deployments/airbyte-server
No resources found in default namespace.
```

**Comment by gosusnp** [comment]
@jdpgrailsdev, I don't think so, this looks like some maybe transient error related to kube.
The issue I am looking at currently involves everything starting, but starting connectors seem to fail due to minio config.

**Comment by alovew** [comment]
@gosusnp @jdpgrailsdev this succeeded on a retry

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Pull request merged**
