### PR TITLE
Fix `source-google-ads` on M1  Macs by pinning `protobuf==3.14`

### LINKED ISSUE #13580: `airbyte/source-google-ads` connector's SPEC command does not succeed
```
$ docker run airbyte/source-google-ads spec

{"type": "LOG", "log": {"level": "FATAL", "message": "'NoneType' object has no attribute 'message_types_by_name'\nTraceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 9, in <module>\n    from source_google_ads import SourceGoogleAds\n  File \"/airbyte/integration_code/source_google_ads/__init__.py\", line 25, in <module>\n    from .source import SourceGoogleAds\n  File \"/airbyte/integration_code/source_google_ads/source.py\", line 13, in <module>\n    from google.ads.googleads.errors import GoogleAdsException\n  File \"/usr/local/lib/python3.9/site-packages/google/ads/googleads/__init__.py\", line 16, in <module>\n    import google.ads.googleads.client\n  File \"/usr/local/lib/python3.9/site-packages/google/ads/googleads/client.py\", line 20, in <module>\n    from google.api_core.gapic_v1.client_info import ClientInfo\n  File \"/usr/local/lib/python3.9/site-packages/google/api_core/gapic_v1/__init__.py\", line 16, in <module>\n    from google.api_core.gapic_v1 import config\n  File \"/usr/local/lib/python3.9/site-packages/google/api_core/gapic_v1/config.py\", line 25, in <module>\n    from google.api_core import exceptions\n  File \"/usr/local/lib/python3.9/site-packages/google/api_core/exceptions.py\", line 29, in <module>\n    from google.rpc import error_details_pb2\n  File \"/usr/local/lib/python3.9/site-packages/google/rpc/error_details_pb2.py\", line 39, in <module>\n    _RETRYINFO = DESCRIPTOR.message_types_by_name[\"RetryInfo\"]\nAttributeError: 'NoneType' object has no attribute 'message_types_by_name'"}}
{"type": "TRACE", "trace": {"type": "ERROR", "emitted_at": 1654639830233.4658, "error": {"message": "Something went wrong in the connector. See the logs for more details.", "internal_message": "'NoneType' object has no attribute 'message_types_by_name'", "stack_trace": "Traceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 9, in <module>\n    from source_google_ads import SourceGoogleAds\n  File \"/airbyte/integration_code/source_google_ads/__init__.py\", line 25, in <module>\n    from .source import SourceGoogleAds\n  File \"/airbyte/integration_code/source_google_ads/source.py\", line 13, in <module>\n    from google.ads.googleads.errors import GoogleAdsException\n  File \"/usr/local/lib/python3.9/site-packages/google/ads/googleads/__init__.py\", line 16, in <module>\n    import google.ads.googleads.client\n  File \"/usr/local/lib/python3.9/site-packages/google/ads/googleads/client.py\", line 20, in <module>\n    from google.api_core.gapic_v1.client_info import ClientInfo\n  File \"/usr/local/lib/python3.9/site-packages/google/api_core/gapic_v1/__init__.py\", line 16, in <module>\n    from google.api_core.gapic_v1 import config\n  File \"/usr/local/lib/python3.9/site-packages/google/api_core/gapic_v1/config.py\", line 25, in <module>\n    from google.api_core import exceptions\n  File \"/usr/local/lib/python3.9/site-packages/google/api_core/exceptions.py\", line 29, in <module>\n    from google.rpc import error_details_pb2\n  File \"/usr/local/lib/python3.9/site-packages/google/rpc/error_details_pb2.py\", line 39, in <module>\n    _RETRYINFO = DESCRIPTOR.message_types_by_name[\"RetryInfo\"]\nAttributeError: 'NoneType' object has no attribute 'message_types_by_name'\n", "failure_type": "system_error"}}}
```

### PR DESCRIPTION
**Pull request by evantahler**
Closes https://github.com/airbytehq/airbyte/issues/13580.  Closes  https://github.com/airbytehq/oncall/issues/263.

Looks like newer versions of Protobuf have some problems (https://github.com/protocolbuffers/protobuf/issues/10075).  We can likely remove this version pin in the future.

### CODE REVIEW

**Review by sherifnada — APPROVED** [review]
do you know how did this pass tests before? 🤔

**Comment by evantahler** [comment]
@sherifnada no clue.  The problem only appears on M1 macs (which likely weren't used for development of this connector until now).  It's also a transitive dependency (a dep of a dep) so the version was drifting under us without us knowing.  Older versions did work.

**Review by davydov-d — APPROVED** [review]

**Comment by davydov-d** [comment]
I guess we need to make further investigation as protobuff==3.14 slows down the connector more than 3 times!

**Comment by davydov-d** [comment]
Finally, this looks much better. Docker run spec also works on Mac M1. @evantahler take a look please

**Comment by evantahler** [comment]
Thanks @davydov-d! I can't approve this PR because I started it, but approved by me!

On my M1 mac:

```bash
docker pull airbyte/source-google-ads:latest
docker run airbyte/source-google-ads:latest spec
# (error)

./gradlew :airbyte-integrations:connectors:source-google-ads:build
docker run airbyte/source-google-ads:dev spec
# (works!)
```

SPEC works!

As a note, I also tried to run integration tests locally (`./acceptance-test-docker.sh`), and they don't work... but they never did.  Things seem OK on CI, so go for it!

**Pull request merged**
