### PR TITLE
airbyte-workers: Add kube pod workers annotations and default CPU request and limit

### PR DESCRIPTION
**Pull request by tbcdns**
## What
1. Some productive Kubernetes cluster requires pod annotations, for example for configuring which ipPool to use when using [Calico as network plugin.](https://projectcalico.docs.tigera.io/networking/legacy-firewalls#restrict-a-pod-to-use-an-ip-address-range)
This PR adds the possibility to set pod annotations.
2. Some productive Kubernetes cluster also requires to set CPU + memory request and limits for all containers in a pod. This PR add default CPU request and limit for the sidecar containers
3. Add /tmp emptyDir for the 'main' container. Again, some productive k8s cluster enforce read only root fs. Some connector (such as 'destination-s3') requires to write data to /tmp.

## 🚨 User Impact 🚨
The only change that could impact users is setting the CPU limit for the sidecar containers. However, a limit at 0.2 seems enough based on my tests. (Ideally the sidecar resources should also be configurable)

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

### CODE REVIEW

**Comment by marcosmarxm** [comment]
thanks @tbcdns I'd requested to the team review your contribution

**Review by alafanechere — CHANGES_REQUESTED** [review]
Thank you @tbcdns for this beneficial contribution. 
Do you mind: 
* Resolving conflicts
* Adding documentation for the new env var you created here `docs/operator-guides/configuring-airbyte.md`, this will update this [doc page](https://docs.airbyte.com/operator-guides/configuring-airbyte).
* If you've Helm knowledge, it'd be great to propagate the new env var to our helm chart: `./charts/airbyte.`

I'd like a review from @jrhizor or @davinchia. They'd maybe detect some side effects I'm not aware of.

**Comment by tbcdns** [comment]
Hi @alafanechere , thanks for the feedback. 
I resolved the conflicts and added the new env var to the documentation.

I am not so familiar with Helm chart and my feeling is that, the var `JOB_KUBE_NODE_SELECTORS` is also not part of the Helm chart.

**Comment by davinchia** [comment]
@tbcdns thank you for the contribution! 

To make sure I understand:
- the annotation change is useful as certain clusters require certain annotations on the created pods?
- adding CPU limit and requests to all sidecars (looks like the init container is missing this).
- adding a non-root directory for connectors to use? 

The first two are pretty straightforward suggestions. The last one is something I want to discuss with our connector team to make sure we do something applicable to all connectors.

Sorry for the additional trouble - can you split your PR into 3? It's easier for us to review and test, especially since this are 3 separate features. We'll also be able to merge in the first 2 suggestions and not block the 3 one. Thanks!

**Comment by tbcdns** [comment]
Hi @davinchia , thanks for the feedback!

- the annotation change is useful as certain clusters require certain annotations on the created pods.
-> yes exactly
- adding CPU limit and requests to all sidecars (looks like the init container is missing this).
-> Correct, it was missing for the init container and, there was no resource (cpu+memory) limits, only resource requests for the sidecar containers
- adding a non-root directory for connectors to use.
-> It's a general good (security) practice to use [read only root filesystem](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#volumes-and-file-systems). However, I noticed that some connectors (typically the s3-destination) require to write some data to /tmp (I think it's actually required when using Parquet has data format, which is using some hadoop libraries where the default [hadoop tmp dir](https://hadoop.apache.org/docs/r3.3.0/hadoop-project-dist/hadoop-common/core-default.xml) is `/tmp/hadoop-${user.name}`
So, the idea is to create a new emptyDir volume mounted in `/tmp` to still allow the connector to write temporary data.

But I agree that's a better approach to split it in 3 distinct PRs, I will do it in the following days.

**Comment by alafanechere** [comment]
@davinchia thanks for the feedback. @tbcdns I'm closing this as you plan to open separate PRs.

**Pull request closed without merging**
