### PR TITLE
Fix all tests to pass on local and CI environments

### LINKED ISSUE #24708: Make all unit tests pass on both CI and local environment
## Current Behavior
Some unit tests are failing on a local macOS environment while passing on CI.
This is mainly around network dependent tests.
See [discussion](https://github.com/airbytehq/airbyte/issues/24244#issuecomment-1490539008) and [PR demonstrating how to fix](https://github.com/airbytehq/airbyte/pull/24683).

## Expected Behavior
All tests on java based connectors should pass locally.

### PR DESCRIPTION
**Pull request by rodireich**
## What
This fixes all tests that we're failing on macos.
closes #24708

## How
Some network related tests behave differently on macOS (m1?) and linux based instances that run CI slash test.
This fix is calling explicitly whether trying to read a container using an address visible from host machine,
Or using an address internal to the docker network.

### CODE REVIEW

**Comment by rodireich** [comment]
test connector=connectors/source-postgres

**Review by alafanechere — APPROVED** [review]
Thank you rodi! The tests that were failing are now passing locally. I've other[ test failures ](https://scans.gradle.com/s/szfcnt63adpe2/tests/overview) though.

**Comment by rodireich** [comment]
All integration tests passing locally now

**Comment by rodireich** [comment]
This is going to fix the local failure in java sources mentioned in https://github.com/airbytehq/airbyte/pull/24225

**Pull request merged**
