### PR TITLE
Adding the appsflyer singer based connector

### PR DESCRIPTION
**Pull request by Muriloo**
## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*
The Appsflyer connector was added.

## How
*Describe the solution*
The Appsflyer connector uses a singer-based tap to pull data from Appsflyer API.

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

## Recommended reading order
1. Look into the the folder airbyte-integrations/connectors/source-appsflyer-singer

### CODE REVIEW

**Review by cgardens — APPROVED** [review]
Awesome! This looks great. Thanks for contributing it.

**Comment by murat-cetinkaya** [comment]
Hi @cgardens . It seems that Appflyers has updated their APIs to v2 and this connector currently can't work with the new APIs. I'd appreciate if you you consider updating it.

image

**Comment by cgardens** [comment]
Hi @murat-cetinkaya ! We'd happily accept a contribution to update it. As of right now this connector is community supported.

**Comment by payme-anujmaurya** [comment]
Configuration check failed
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='hq.appsflyer.com', port=443): Max retries exceeded with url: /export/id1282142711/partners_report/v5?api_token=eyJhbGciOiJBMjU2S1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwidHlwIjoiSldUIiwiemlwIjoiREVGIn0.SANqQ5BLhNyI-hqZJlu79PG-cVCY-rE4i47kL2ZvvVURTSFMEqTwCw.umYgP0HT72GrsH7G.HPgSG0LvwHMEPIOwTVoyM5T-z7IJ4hOMAT4rcaGBBv5vHNeUUB_rBbSTuul6QZw-tBSQdx_dOE5WzUyGPTCFHJeKSkbP3eiN4QJfnrJnZ4irnaDi0uk_EolFDZd6XWbbFHG2bKzR0jzl-TAGLr6f5Fp9cAI5LB3U5mLzqO5FLEW_mWpl1oMvH4p0pmupSgnPMPipIGl5dUIgNgCvljs7j29oYi9lORUXKENN2EyQqzaTVAD8o8_EWBRVRHi_mpiiUopGlWYqC0iZPWH7oiQOaFCBbJJ7Ktjbu3oYEnYus6JfxqYcCrR-vX6yIujnssQ907pT3CsM8jZ2caac7LxBBTgz4ZE.EUzzbLm3k5wPSae_1OCpOg&from=2024-04-11&to=2024-04-11&timezone=UTC (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x723e41f321f0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))"))

**Pull request merged**
