### PR TITLE
:bug: Source Google Directory: update version in cloud to 0.2.0

### PR DESCRIPTION
**Pull request by darynaishchenko**
## What
resolved: https://github.com/airbytehq/oncall/issues/2215
`client = self.client_class(**config)
TypeError: __init__() got an unexpected keyword argument 'credentials'`
Got error for credential in config.

## How
In 0.2.0v OAuth flow was removed, and added support for old type of creds (credentials_json) which should not lead to this kind of error. 0.1.3 was pinned as stable without oauth because this connector doesn't support it.

### CODE REVIEW

**Review by lazebnyi — APPROVED** [review]

**Review by bnchrch — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-google-directory test report (commit [`f55135e5c1`](https://github.com/airbytehq/airbyte/pull/27236/commits/f55135e5c126902d8febb7203031660eb2a26336)) - ❌

⏲️  Total pipeline duration: 179 seconds

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-google-directory/metadata.yaml | ✅        |
| Connector version semver check.                                                | ✅        |
| Connector version increment check.                                             | ❌        |
| QA checks                                                                      | ✅        |
| Code format checks                                                             | ✅        |
| Connector package install                                                      | ✅        |
| Build source-google-directory docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                     | ✅        |
| Acceptance tests                                                               | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5332892563)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-directory test
```

**Comment by octavia-squidington-iii** [comment]
##  source-google-directory test report (commit [`b8295a832c`](https://github.com/airbytehq/airbyte/pull/27236/commits/b8295a832cd11f836a2cc8e72535288df1e26102)) - ❌

⏲️  Total pipeline duration: 185 seconds

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-google-directory/metadata.yaml | ✅        |
| Connector version semver check.                                                | ✅        |
| Connector version increment check.                                             | ❌        |
| QA checks                                                                      | ✅        |
| Code format checks                                                             | ✅        |
| Connector package install                                                      | ✅        |
| Build source-google-directory docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                     | ✅        |
| Acceptance tests                                                               | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/daryna_source-google-directory_oc-2215-update-version-in-cloud/1687422265/b8295a832cd11f836a2cc8e72535288df1e26102/source-google-directory/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-directory test
```

**Comment by octavia-squidington-iii** [comment]
##  source-google-directory test report (commit [`7c20ea9369`](https://github.com/airbytehq/airbyte/pull/27236/commits/7c20ea936989ec9b5f4e2e5600e83cd910855740)) - ❌

⏲️  Total pipeline duration: 137 seconds

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-google-directory/metadata.yaml | ✅        |
| Connector version semver check.                                                | ✅        |
| Connector version increment check.                                             | ❌        |
| QA checks                                                                      | ✅        |
| Code format checks                                                             | ✅        |
| Connector package install                                                      | ✅        |
| Build source-google-directory docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                     | ✅        |
| Acceptance tests                                                               | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/daryna_source-google-directory_oc-2215-update-version-in-cloud/1687425659/7c20ea936989ec9b5f4e2e5600e83cd910855740/source-google-directory/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-directory test
```

**Pull request merged**
