### PR TITLE
🪟 File and exports cleanup for Connection Create/Edit

### PR DESCRIPTION
**Pull request by teallarson**
## What
Pulls the file renaming out of https://github.com/airbytehq/airbyte/pull/16748 to make the diff for that PR more useful for review.

## How
- `ReplicationView` --> `ConnectionReplicationTab` (and its siblings)
- `/hooks/services/connection` --> `/hooks/services/connectionForm` (these services are only to be used for the forms, nothing else related to connections)
- `createConnectionContent` --> `createConnection` (this was just unnecessary and has confused multiple of us multiple times)
- Removes the `/components/` subfolders as a baby step towards implementing our new directory structure

## Recommended reading order
^following the "How" order probably makes the most sense

## 🚨 User Impact 🚨
There should be none!

### CODE REVIEW

**Review by krishnaglick — COMMENTED** [review]
Since this is just moving components, a clean build should be what we need.
Would love to get this merged quickly so the connection form refactor pt 2 can keep momentum!

**Comment by tealjulia** [comment]
@edmundito and @timroes I really just tagged both of you so either would get eyes on this and approve since KC and I worked on it together.

Hoping to get approved/merged quickly to keep momentum on the main PR and avoid a merge conflict nightmare.

**Review by dizel852 — APPROVED** [review]
Code LGTM 👍 
Didn't test locally

**Review by krishnaglick — APPROVED** [review]
If build is green LGTM

**Pull request merged**
