### PR TITLE
Source Intercom: change airbyte-cdk version to 0.2

### PR DESCRIPTION
**Pull request by roman-yermilov-gl**
## What
*Fix airbyte-cdk version: 0.2.0 -> 0.2*

## Problem
*Build failed on `pip install -r requirements.txt` command*

```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/ryermilov/development/airbyte/airbyte-integrations/connectors/source-intercom/.venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/ryermilov/development/airbyte/airbyte-integrations/connectors/source-intercom/.venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/home/ryermilov/development/airbyte/airbyte-integrations/connectors/source-intercom/.venv/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 400, in run
    requirement_set = resolver.resolve(
  File "/home/ryermilov/development/airbyte/airbyte-integrations/connectors/source-intercom/.venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/home/ryermilov/development/airbyte/airbyte-integrations/connectors/source-intercom/.venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/ryermilov/development/airbyte/airbyte-integrations/connectors/source-intercom/.venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/ryermilov/development/airbyte/airbyte-integrations/connectors/source-intercom/.venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 227, in _attempt_to_pin_criterion
    raise InconsistentCandidate(candidate, criterion)
pip._vendor.resolvelib.resolvers.InconsistentCandidate: Provided candidate LinkCandidate('https://files.pythonhosted.org/packages/48/69/09f96c07631459f05742ed325f3c4b1cde3f7c733b080669181daec4f12e/airbyte_cdk-0.4.2-py3-none-any.whl (from https://pypi.org/simple/airbyte-cdk/) (requires-python:>=3.9)') does not satisfy SpecifierRequirement('airbyte-cdk~=0.2'), SpecifierRequirement('airbyte-cdk~=0.2.0')
```

### CODE REVIEW

**Review by davydov-d — CHANGES_REQUESTED** [review]
you need to bump the connector version as well

**Comment by roman-yermilov-gl** [comment]
> you need to bump the connector version as well

Done

**Review by davydov-d — APPROVED** [review]

**Review by grubberr — APPROVED** [review]

**Pull request merged**
