### PR TITLE
Multi-Cloud MVP: Combined branch for testing and merge

### PR DESCRIPTION
**Pull request by pmossman**
## What
This branch incorporates all changes across the following sub-branches to enable the Multi-Cloud MVP:

https://github.com/airbytehq/airbyte/pull/15903
https://github.com/airbytehq/airbyte/pull/15905
https://github.com/airbytehq/airbyte/pull/15904
https://github.com/airbytehq/airbyte/pull/15902

Every commit in this branch is cherry-picked from one of the sub-branches above. 
Each PR above was reviewed/approved, so this branch is to facilitate end-to-end testing on our dev instance, and will be merged once that testing is concluded and the build is fully passing.

### CODE REVIEW

**Review by gosusnp — APPROVED** [review]

**Comment by grishick** [comment]
@pmossman I think this change broke airbyte-cloud. See this run failure trying to push OSS to cloud: https://github.com/airbytehq/airbyte-cloud/runs/8047057808?check_suite_focus=true

**Comment by pmossman** [comment]
Yeah I have a PR that addresses the Cloud side, I didn't want to upgrade Cloud on a Friday so I'll get it in first thing Monday. @grishick is this blocking anything on your side?

**Comment by pmossman** [comment]
On second thought I think I should just get Cloud fixed ASAP, it shouldn't be left in a blocking state like this even if it means upgrading over the weekend, I'll get my Cloud PR merged now

**Comment by grishick** [comment]
Thanks! The reason I was looking at it now is that we are pushing a security fix in 2 connectors

**Comment by grishick** [comment]
Maybe a good idea to have the fix ready, but merge it first thing on Monday to avoid a Sunday support escalation

**Comment by pmossman** [comment]
@grishick that sounds good if you're ok waiting. I think this PR is what we'll need for the Cloud side: https://github.com/airbytehq/airbyte-cloud/pull/2522/files#

I just need to work out some terraform details and then I can make sure it builds successfully

**Pull request merged**
