### PR TITLE
source-tinyemail contribution from ombhardwajj

### LINKED ISSUE #47971: [connector-request] Tinyemail
This is a suggestion to create a connector for Tinyemail using the UI Connector Builder.
The website for the connector is https://tinyemail.com/

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to step 3).
3. Describe steps to get credentials.
4. Create the connector using the UI Builder.   

> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> This is a suggestion, and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend following the steps above.

### PR DESCRIPTION
**Pull request by ombhardwajj**
This closes https://github.com/airbytehq/airbyte/issues/47971
## What

This PR adds a new connector for source Tinyemail (source-tinyemail).

Contributor-provided connector description:

Tinyemail is an email marketing tool.
We can extract data from campaigns and contacts streams using this connector.
Docs : https://docs.tinyemail.com/docs/tiny-email/tinyemail
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| campaigns | id | DefaultPaginator | ✅ |  ❌  |
| contacts | id | No pagination | ✅ |  ❌  |
| sender_details |  | No pagination | ✅ |  ❌  |
| contact_members |  | No pagination | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by marcosmarxm** [comment]
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

Make sure you have pagination properly working, the API doesn't have pagination please left a comment making my review easier.
Make sure have a square svg icon
Make sure credentials are valid.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Missing sender and contact details endpoint for the tiny email connector.

**Comment by marcosmarxm** [comment]
Moving next check to Nov 11

**Comment by ombhardwajj** [comment]
I've added the sender details endpoint , contacts was already there. Assuming that by contact details you meant contact_members endpoint , I've added that aswell now !!

**Comment by ombhardwajj** [comment]
Please try to review this on priority , if possible today itself as my access to this API is gonna get lost very soon
@marcosmarxm

**Comment by ombhardwajj** [comment]
@marcosmarxm Please review it today 🙏

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
