### PR TITLE
🐛 Source Github: Bugfix exception when parsing null date values, use `created_at` as cursor value for issue_milestones

### PR DESCRIPTION
**Pull request by grebessi**
## What
Issue #3150 is pointing to a parsing problem on the `github-singer` connector.
The repository [tap-github](https://github.com/airbytehq/tap-github) had an issue parsing due_on as a date when its value is null.

## How
Updated the repo with the appropriate data treatment and added unit test to it on the [Pull Request #3](https://github.com/airbytehq/tap-github/pull/3).

### CODE REVIEW

**Comment by grebessi** [comment]
Since I am not able to add @sherifnada as a reviewer on https://github.com/airbytehq/tap-github/pull/3, I am tagging you here. I hope that is ok.

**Comment by sherifnada** [comment]
@grebessi left a review!

**Review by keu — APPROVED** [review]

**Review by sherifnada — CHANGES_REQUESTED** [review]
we need to: 

1. bump docker connector version and JSON/YAML configs
2. add changelog.md describing the change
3. test/publish

**Review by sherifnada — APPROVED** [review]
Looks great. Publish whenever you are ready! (tests automatically run in the `/publish` command so it is safe to run)

**Comment by sherifnada** [comment]
@grebessi confusing thing here: syntax for publishing is different: `/publish connector=connectors/source-github-singer`

**Comment by grebessi** [comment]
My bad!

**Comment by sherifnada** [comment]
no worries! not confusing at all huh? FWIW the `/test` command also has the same syntax but we added the shorthand for convenience. Maybe it's more confusing than anything...

**Pull request merged**
