### PR TITLE
source-coassemble contribution from topefolorunso

### PR DESCRIPTION
**Pull request by topefolorunso**
## What

This PR adds a new connector for source Coassemble (source-coassemble).

Contributor-provided connector description:

Coassemble is an online training tool that connects people with the information they need - anytime, anyplace.
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `user_token` | `string` | User Token.  |  |
| `user_id` | `string` | User ID.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| courses | id | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [x] Run `/format-fix` to resolve any formatting errors
- [x] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Review by natikgadzhi — COMMENTED** [review]
@topefolorunso PRs have todo-lists now! Check off items you've done already.

If it does not apply any formatting changes, that usually means that you'd need to merge a fresh master in first. 

Everything that is in looks good, but I would love to see [trackings](https://developers.coassemble.com/api/tracking) and screen type streams. Those are "available on request only", so I think this needs a docs entry that enabling them without having them enabled on the API side would result in errors.

**Comment by topefolorunso** [comment]
> but I would love to see [trackings](https://developers.coassemble.com/api/tracking) and screen type streams. Those are "available on request only", so I think this needs a docs entry that enabling them without having them enabled on the API side would result in errors.

Correct! Do you want me to add the doc now? I think that should come in once the streams are implemented in the connector.

**Comment by topefolorunso** [comment]
> PRs have todo-lists now! Check off items you've done already.

@natikgadzhi Please clarify this part "Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs"

**Comment by topefolorunso** [comment]
@natikgadzhi please review again

**Pull request merged**
