### PR TITLE
source-youtube-analytics: Update integer to decimal rate columns

### PR DESCRIPTION
**Pull request by n-xara**
fix schema

### CODE REVIEW

**Review by n-xara — COMMENTED** [review]
Hi @edgao, @lmossman  ! Please can you review this PR? (It seems like I can not add reviewers directly)

**Comment by alafanechere** [comment]
@n-xara did you close the PR?

**Review by edgao — COMMENTED** [review]
this seems pretty reasonable to me! I'm trying to figure out why our slash-commands aren't triggering correctly here; once that's done we'll be ready to publish here :)

**Comment by edgao** [comment]
@n-xara there might be something weird happening with your repository, can you try re-creating the branch?

It looks like the `patch-2` branch doesn't exist (https://github.com/n-xara/airbyte/tree/patch-2 returns a 404, and I can't `git checkout` when I pull from your remote); pretty sure this is preventing our CI from checking out the code.

**Comment by natalyjazzviolin** [comment]
@n-xara just following up on @edgao 's comment! Would you be able to re-create the branch?

**Comment by marcosmarxm** [comment]
Closed due inactivity. @n-xara please let me know if you want to continue this work.

**Pull request closed without merging**
