### PR TITLE
Allow up to 40 minutes of initial wait for record

### PR DESCRIPTION
**Pull request by rodireich**
Allowing more time for mssql initial record in CDC.
A customer is facing a problem where current maximum is not sufficient.
This will increase the chance of success while we're looking for a root cause.

### CODE REVIEW

**Review by evantahler — APPROVED** [review]
👍 as the default didn't change.

Also... that's SO LONG :(

**Comment by bengineerdavis** [comment]
Created an issue to consolidate this work: [https://github.com/airbytehq/airbyte/issues/36533](https://github.com/airbytehq/airbyte/issues/36533)

**Pull request merged**
