### PR TITLE
🐛 Destination Redshift: use s3 bucket path for s3 staging operations

### PR DESCRIPTION
**Pull request by adam-bloom**
## What
The redshift destination is not respecting the bucket path configuration when uploading staging files to S3.

## How
1. When testing the connection, we try to write/delete from the configured bucket path/prefix.
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3Destination.java#L123-L124

Guess we better pass the config to the parameter instead of an empty string! :)
2. When actually writing staging data, all operations are based on the `stagingPath`, so that also needs to use the configured parameter. I've used the same prefix logic that was already present in the S3Destination.

## Recommended reading order
1. `x.java`
3. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by adam-bloom** [comment]
@alafanechere looks like there are many failures with the following exception:
```
    2022-06-22 16:33:32 destination > 2022-06-22 16:33:32 ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.
    2022-06-22 16:33:32 destination > java.lang.Exception: Verification error(s) occurred for WRITE. Errors: [$.uploading_method.method: must be a constant value Standard] 
    2022-06-22 16:33:32 destination > 	at io.airbyte.integrations.base.IntegrationRunner.validateConfig(IntegrationRunner.java:282) ~[io.airbyte.airbyte-integrations.bases-base-java-0.39.20-alpha.jar:?]
    2022-06-22 16:33:32 destination > 	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:162) ~[io.airbyte.airbyte-integrations.bases-base-java-0.39.20-alpha.jar:?]
    2022-06-22 16:33:32 destination > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:107) ~[io.airbyte.airbyte-integrations.bases-base-java-0.39.20-alpha.jar:?]
    2022-06-22 16:33:32 destination > 	at io.airbyte.integrations.destination.redshift.RedshiftDestination.main(RedshiftDestination.java:64) ~[io.airbyte.airbyte-integrations.connectors-destination-redshift-0.39.20-alpha.jar:?]
```

I don't think that's related to this change. Have these tests worked since b45014da6b315b87bc151b8bee633816820b2904? cc @alexandertsukanov

**Comment by alafanechere** [comment]
@adam-bloom the latest build on master [succeeded](https://github.com/airbytehq/airbyte/actions/runs/2534981895). I merged master on your branch and will re-run.

**Review by alafanechere — CHANGES_REQUESTED** [review]
Hey @adam-bloom there are some conflicts due to another PR being merged for the same connector. Do you mind fixing those conflicts? I'll run the test again afterward.

**Review by alafanechere — APPROVED** [review]
Thank you for the changes.

**Comment by alafanechere** [comment]
The new connector version is now published, thank you for this fix @adam-bloom 👏

**Pull request merged**
