### PR TITLE
Source Google Ads: Add metrics & segment to `Campaigns`

### LINKED ISSUE #27189: Source Google Ads: expand stream campaigns
### What area the feature impact?

None

### Revelant Information

https://developers.google.com/google-ads/api/fields/v14/campaign
Add metrics:

- [x] active_view_cpm
- [x] active_view_ctr
- [x] active_view_impressions
- [x] active_view_measurability
- [x] active_view_measurable_cost_micros
- [x] active_view_measurable_impressions
- [x] active_view_viewability
- [x] ad_network_type
- [x] average_cost
- [x] average_cpc
- [x] average_cpm
- [x] interactions
- [x] interaction_event_types
- [x] value_per_conversions
- [x] cost_per_conversion

### PR DESCRIPTION
**Pull request by artem1205**
## What

Resolve https://github.com/airbytehq/airbyte/issues/27189

## How

Add `metrics` and `segments` to `Campaigns` schema

## Recommended reading order
1. `campaings.json`

## 🚨 User Impact 🚨

no breaking changes

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-google-ads test report (commit [`9f0e05a554`](https://github.com/airbytehq/airbyte/pull/28042/commits/9f0e05a554d6ca083e47fd6d59dba279e6343bc4)) - ❌

⏲️  Total pipeline duration: 15mn08s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-google-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-google-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-google-ads-27189-campaigns/1688730533/9f0e05a554d6ca083e47fd6d59dba279e6343bc4/source-google-ads/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-google-ads test report (commit [`9f0e05a554`](https://github.com/airbytehq/airbyte/pull/28042/commits/9f0e05a554d6ca083e47fd6d59dba279e6343bc4)) - ❌

⏲️  Total pipeline duration: 13mn07s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-google-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-google-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-google-ads-27189-campaigns/1688731545/9f0e05a554d6ca083e47fd6d59dba279e6343bc4/source-google-ads/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-google-ads test report (commit [`758b14e063`](https://github.com/airbytehq/airbyte/pull/28042/commits/758b14e063686876ff7901bfbbcfc4bfa3a57ba5)) - ❌

⏲️  Total pipeline duration: 4.30s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-google-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-google-ads docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-google-ads-27189-campaigns/1688732425/758b14e063686876ff7901bfbbcfc4bfa3a57ba5/source-google-ads/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-google-ads test report (commit [`0104995e6b`](https://github.com/airbytehq/airbyte/pull/28042/commits/0104995e6b44ef8bd6c71cf992c537e08bfb49cb)) - ❌

⏲️  Total pipeline duration: 25mn38s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-google-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ❌        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-google-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-google-ads-27189-campaigns/1688733731/0104995e6b44ef8bd6c71cf992c537e08bfb49cb/source-google-ads/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-google-ads test report (commit [`accb050933`](https://github.com/airbytehq/airbyte/pull/28042/commits/accb0509337392ef7d68a7e8b5c0103762b1c500)) - ✅

⏲️  Total pipeline duration: 18mn19s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-google-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-google-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-google-ads-27189-campaigns/1688735346/accb0509337392ef7d68a7e8b5c0103762b1c500/source-google-ads/0.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-ads test
```

**Review by lazebnyi — APPROVED** [review]

**Pull request merged**
