### PR TITLE
🪟 🎉 Auto-detect schema changes UX flow

### LINKED ISSUE #17828: Add auto-detect schema changes flow to connection replication settings page
When changes are auto-detected:

1. Show banner below connection widget
2. Block the streams table
3. User clicks on review changes to look at diffs
4. User can save or cancel the changes

Prototype - Click on "Slack Community" to see the flow:

https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=972%3A37260&scaling=min-zoom&page-id=972%3A36208&starting-point-node-id=972%3A36212&show-proto-sidebar=1

### PR DESCRIPTION
**Pull request by edmundito**
## What
Resolves #17828

Adds the basic flow for auto-detect schema changes:

Non-breaking changes

image

* Can still enable/disable the connection
* Disappears after clicking "Review changes."

Breaking changes:

image

* Connection cannot be enabled (The connection will be disabled at the backend level, but this functionality is currently not enabled, to test, enable, set `AUTO_DETECT_SCHEMA=true` before running the server )
* Disappears after clicking "Review changes."

Additionally, updates the component to ensure that it matches the design more closely by adjusting some of the spacing and making the "Enabled" / "Disabled" text not all caps.

After clicking the review button, the connection goes through the regular refresh schema flow. If the connection is not in the replication settings tab, it switches to the replication settings tab.

## How
Leverages the connection edit service context to identify if the connection has schema changes and to trigger the refresh from any tabs on the connection item page.

In the replication settings page, to confirm discarding changes before the refresh, some changes were made to the form tracker service to return a boolean if any forms are dirty.

Adds a process env var to enable and disable the feature. This only works if the feature is enabled.

## Recommended reading order

Start with:

`airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/StatusMainInfo.tsx`
`airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/SchemaChangesDetected.tsx`
`airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx`
`airbyte-webapp/src/components/EntityTable/components/StatusCell.tsx`

### CODE REVIEW

**Comment by krishnaglick** [comment]
Still testing, but if there's changes and you hit save, the changes notification persists.

**Comment by krishnaglick** [comment]
Bulk edit appears broken
https://www.loom.com/share/025c84c6c7a04be685921712946e77b3

**Comment by krishnaglick** [comment]
> Bulk edit appears broken https://www.loom.com/share/025c84c6c7a04be685921712946e77b3

Actually this happens with any change to sync mode on any stream.

**Comment by edmundito** [comment]
>  but if there's changes and you hit save, the changes notification persists.

Pushed a change to pick up the update schemaChange value when updating the connection.

**Review by krishnaglick — APPROVED** [review]

**Pull request merged**
