### PR TITLE
🐛 Source Gitlab: fix pattern field in spec file, remove unused fields from config files, improve caching mechanism

### LINKED ISSUE #6822: Fix Gitlab connector build , add credentials to lastpass
## Current Behavior
Recent gitlab builds have been failing, we should diagnose & fix the issue. 
Also we should add the config.json to lastpass. I couldn't find the credentials there.

### PR DESCRIPTION
**Pull request by Zirochkaa**
Closes #6822.
Fix how cache is being used in this connector.
Fix pattern field in spec file.
Remove unused fields from invalid_config.json and sample_config.json files.

## Pre-merge Checklist
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated 
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [x] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

### CODE REVIEW

**Review by avida — CHANGES_REQUESTED** [review]
Please use caching features provided by CDK

**Review by avida — APPROVED** [review]
dont forget to bump version on dockerfile and airbyte-config dir

**Review by htrueman — APPROVED** [review]

**Review by davinchia — APPROVED** [review]

**Pull request merged**
