### PR TITLE
Delete airbyte-integrations/connectors/destination-postgres/encrypt

### PR DESCRIPTION
**Pull request by evantahler**
Delete errant file.  Feels like a mistake?

### CODE REVIEW

**Review by edgao — APPROVED** [review]
lgtm pending ci

(I got so excited when I saw the pr title, I thought we were getting rid of strict-encrypt 😅 )

**Comment by evantahler** [comment]
> (I got so excited when I saw the pr title, I thought we were getting rid of strict-encrypt 😅 )

One day...

**Comment by octavia-approvington** [comment]
This code is at peace with itself <br/> imagine karate kid approving

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
