### PR TITLE
🚨🚨 Source Facebook Marketing: use SDK v17

### LINKED ISSUE #27746: Facebook Marketing API App now is version 17.0.0
### Connector Name

source-facebook-marketing

### Connector Version

0.5.0

### What step the error happened?

Configuring a new connector

### Revelant information

Seems like Meta has been upgrade their API to v17.0, therefore, when we create new App in Meta Developer Pages, the App get default version as v.17.0
While Airbyte Facebook Marketing Source is using library 16.0

### Relevant log output

```shell
Configuration check failed
Error: 2635, (#2635) Your app has been upgraded to version v17.0, please use this version or newer. This can be verified in the settings tab on the App Dashboard.. Please also verify your Account ID: See the https://www.facebook.com/business/help/1492627900875762 for more information.
```

### Contribute

- [ ] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by davydov-d**
## What
Closes https://github.com/airbytehq/airbyte/issues/27746
Move to SDK version 17

## How
- Update SDK version in setup.py
- Introduce default stream fields: they are not queried from facebook; instead default values should be yielded.
- Bump version

## 🚨 User Impact 🚨
This is a breaking change since:
 - AdAccount stream no more exposes a `has_advertiser_opted_in_odax` field
 - Set of valid fields and breakdowns is changed which makes spec backwards incompatible

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`8be9a1aa14`](https://github.com/airbytehq/airbyte/pull/27563/commits/8be9a1aa14abafbe903e2c5e0a72dc981b3bf067)) - ❌

⏲️  Total pipeline duration: 95 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check.                                                  | ✅        |
| Connector version increment check.                                               | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/ddavydov_source-facebook-marketing-use-sdk-v17/1687377043/8be9a1aa14abafbe903e2c5e0a72dc981b3bf067/source-facebook-marketing/0.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`8be9a1aa14`](https://github.com/airbytehq/airbyte/pull/27563/commits/8be9a1aa14abafbe903e2c5e0a72dc981b3bf067)) - ❌

⏲️  Total pipeline duration: 62 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check.                                                  | ✅        |
| Connector version increment check.                                               | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/ddavydov_source-facebook-marketing-use-sdk-v17/1687377244/8be9a1aa14abafbe903e2c5e0a72dc981b3bf067/source-facebook-marketing/0.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`4eab8e48c3`](https://github.com/airbytehq/airbyte/pull/27563/commits/4eab8e48c3eebd490f1c08c21d50c5a6a4049aea)) - ❌

⏲️  Total pipeline duration: 3690 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check.                                                  | ✅        |
| Connector version increment check.                                               | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/ddavydov_source-facebook-marketing-use-sdk-v17/1687378119/4eab8e48c3eebd490f1c08c21d50c5a6a4049aea/source-facebook-marketing/0.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`f39169dddb`](https://github.com/airbytehq/airbyte/pull/27563/commits/f39169dddb4cdc5f548ba3f6a1d106a4a8d6a962)) - ❌

⏲️  Total pipeline duration: 100 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check.                                                  | ✅        |
| Connector version increment check.                                               | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ❌        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/ddavydov_source-facebook-marketing-use-sdk-v17/1687417938/f39169dddb4cdc5f548ba3f6a1d106a4a8d6a962/source-facebook-marketing/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`309f1816d2`](https://github.com/airbytehq/airbyte/pull/27563/commits/309f1816d2a74d46ba6fd9f37f86612951117b0f)) - ❌

⏲️  Total pipeline duration: 3469 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check.                                                  | ✅        |
| Connector version increment check.                                               | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/ddavydov_source-facebook-marketing-use-sdk-v17/1687418406/309f1816d2a74d46ba6fd9f37f86612951117b0f/source-facebook-marketing/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`9d5ebbe32c`](https://github.com/airbytehq/airbyte/pull/27563/commits/9d5ebbe32c6c78b0a2d6333ed459412c6b52324e)) - ✅

⏲️  Total pipeline duration: 3557 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check.                                                  | ✅        |
| Connector version increment check.                                               | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/ddavydov_source-facebook-marketing-use-sdk-v17/1687424088/9d5ebbe32c6c78b0a2d6333ed459412c6b52324e/source-facebook-marketing/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Review by marcosmarxm — APPROVED** [review]
Thanks @davydov-d

**Comment by davydov-d** [comment]
> Thanks @davydov-d

@marcosmarxm you're welcome. Please follow the "Breaking changes" procedure to release this changes

**Review by lazebnyi — APPROVED** [review]

**Comment by jnr0790** [comment]
Lets release this on July 5th 1030AM EST. I'm going to send comms to Facebook Marketing users on cloud.

cc @archangelic

**Comment by brianjlai** [comment]
changes look good, but for context, @davydov-d how were the breaking changes that needed to be made to the source identified? did you refer to Meta's changelog, or was it just done by bumping the version and making adjustments based on the CAT tests that failed w/ the new version?

**Comment by davydov-d** [comment]
> changes look good, but for context, @davydov-d how were the breaking changes that needed to be made to the source identified? did you refer to Meta's changelog, or was it just done by bumping the version and making adjustments based on the CAT tests that failed w/ the new version?

@brianjlai second option

**Review by brianjlai — APPROVED** [review]
got it thanks for clarifying @davydov-d . I was curious because I glanced through their changelog which was quite unhelpful so was curious how we identified these. lgtm!

**Comment by ysusuk** [comment]
Is it now? :)

**Comment by erica-airbyte** [comment]
@davydov-d did this go out today?

**Comment by davydov-d** [comment]
@erica-airbyte looks like it did not as it is not merged. This is a follow-up to the community PR[](https://github.com/airbytehq/airbyte/pull/27390) so I asked[](https://github.com/airbytehq/airbyte/pull/27563#issuecomment-1602595409)  Marcos to release it

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`dd5fb5a290`](https://github.com/airbytehq/airbyte/pull/27563/commits/dd5fb5a2908b7fb6f13b3164f85b27a17b637f5a)) - ❌

⏲️  Total pipeline duration: 66mn19s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_source-facebook-marketing-use-sdk-v17/1688592673/dd5fb5a2908b7fb6f13b3164f85b27a17b637f5a/source-facebook-marketing/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`58ad67d4f1`](https://github.com/airbytehq/airbyte/pull/27563/commits/58ad67d4f1110066cdc88d1e084ffe65167f3a0a)) - ✅

⏲️  Total pipeline duration: 58mn14s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_source-facebook-marketing-use-sdk-v17/1688659497/58ad67d4f1110066cdc88d1e084ffe65167f3a0a/source-facebook-marketing/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Pull request merged**
