### PR TITLE
Set default values as current values in editMode

### LINKED ISSUE #6791: Source Stripe: upgrade connector doesn't allow save new config
## Enviroment
- **Airbyte version**:  0.30.3-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: Stripe 0.1.19
- **Destination Connector and version**: ~
- **Severity**: Very Low / Low / **Medium** / High / Critical
- **Step where error happened**: Update Config from existing connector

## Current Behavior
I have a Stripe 0.1.19 connector and want to update to 0.1.20 where there is a new config field.
After upgrading the connector version and entered the connector config page I couldnt save the new config.

Stripe 0.1.19
image

Stripe 0.1.20 after change lookback windows variable to 30 doesnt allow me save!
image

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

### PR DESCRIPTION
**Pull request by jamakase**
## What
Closes #6791

## How
As initial patch, always set fields that are defined as defaults into form values. As a result, form values will be assumed dirty and could be updated correctly.

### CODE REVIEW

**Comment by jrhizor** [comment]
Will this change what is saved for the form or only the display?

**Comment by timroes** [comment]
Could we rebase that on master for review, due to the dependency upgrade, please.

**Comment by timroes** [comment]
Just wanted to highlight @jrhizor question again, so it doesn't get lost:

> Will this change what is saved for the form or only the display?

**Comment by Jamakase** [comment]
> Will this change what is saved for the form or only the display?

It won't change what is currently displayed as we already display default values and send then, this will just allow to correctly understand when values were changed and when not.

**Review by jrhizor — APPROVED** [review]

**Pull request merged**
