### PR TITLE
Connector for Tempo

### PR DESCRIPTION
**Pull request by thomas-vl**
## What
New connector for Tempo

## How
Using the Tempo API

## ToDo
1. Someone needs to take a look at the sample_files directory i dont know how the catalog files work
2. Someone needs to take a look at the health_check 

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

## Recommended reading order
1. `test.java`
1. `component.ts`
1. the rest

### CODE REVIEW

**Comment by ChristopheDuong** [comment]
In the health_check function, you are expected to implement how to connect to the tempo API and try one of the streams to test if the service is up and running with the credentials that were provided

**Comment by ChristopheDuong** [comment]
> Someone needs to take a look at the sample_files directory I don't know how the catalog files work

The `configured_catalog.json` or `full_configured_catalog.json` is almost the same file as the ones you provided in the `source-tempo/source_tempo/schemas/accounts.json` for example.

The difference is that you have additional JSON layers to wrap around multiple files from the schemas folder:
```
{
  "streams": [
    {
      "stream": {
        "name": "accounts",
        "json_schema": {
             ...
        }
  } ] }
```

**Comment by thomas-vl** [comment]
@ChristopheDuong Ive created the healtcheck and added the catalog file.

**Comment by thomas-vl** [comment]
I could not check the identical data because its a life system
Expected two full refresh syncs to produce the same records ==> expected: <60084> but was: <60088>

Test run finished after 1501397 ms
[         2 containers found      ]
[         0 containers skipped    ]
[         2 containers started    ]
[         0 containers aborted    ]
[         2 containers successful ]
[         0 containers failed     ]
[         7 tests found           ]
[         0 tests skipped         ]
[         7 tests started         ]
[         0 tests aborted         ]
[         6 tests successful      ]
[         1 tests failed          ]

**Comment by michel-tricot** [comment]
Thank you @thomas-vl for your contribution!

**Pull request merged**
