### PR TITLE
Upgrade temporal to latest v1.13.x

### PR DESCRIPTION
**Pull request by vr**
## What
Enforce the docker image to be built with the latest release of v1.13.4

### CODE REVIEW

**Review by juweins — CHANGES_REQUESTED** [review]
Hey @vr !
Can you provide us with some more information on why you want patch level 4 in the build? Is there any specific issue related? 

Please refer to [Issue & PR style guide](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests) for guidance. Thanks!

**Comment by vr** [comment]
Hello, 
yes, it fixes critical [CVE](https://github.com/advisories/GHSA-vc3p-29h2-gpcp) 

https://github.com/temporalio/temporal/releases/tag/v1.13.4

The best should probably be to update to latest release (v1.19.1 this day) but it will implies more testing i guess.

It looks there is no long term support policy at temporal, so we should stick to latest whenever we can imho

**Comment by juweins** [comment]
Hey @vr ! Thanks for clarification! However, I am not that into temporal and the respective implementation within airbyte (core) , so I would like to have @marcosmarxm and @sajarin involved.

ANyway , the PR itself sounds reasonable to me. 👍🏼

**Comment by marcosmarxm** [comment]
@supertopher asking you to take a look because there are some security updates in Temporal.

**Comment by vr** [comment]
this PR is for sure not enough, but if it raises consideration it's great ! 👍

**Comment by marcosmarxm** [comment]
@vr Airbyte platform code now lives in https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-temporal/Dockerfile I'm closing this here. Do you mind open a new PR in the new repository? I'll ask asap someone to review the changes.

**Pull request closed without merging**
