### PR TITLE
source-shopware contribution from Harmaton

### LINKED ISSUE #46624: [connector-request] Shopware
This is a **suggestion** to create a connector for **Shopware** using the UI Connector Builder.
The website for the connector is https://www.shopware.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

### PR DESCRIPTION
**Pull request by Harmaton**
## What

This PR adds a new connector for source Shopware (source-shopware).

Contributor-provided connector description:

Shopware source connector
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `client_id` | `string` | Client ID.  |  |
| `client_secret` | `string` | Client secret.  |  |
| `base_url` | `string` | Base Url.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| Customer List |  | DefaultPaginator | ✅ |  ❌  |
| Customer Address List |  | DefaultPaginator | ✅ |  ❌  |
| Customer Group List |  | DefaultPaginator | ✅ |  ❌  |
| Customer WishList  |  | DefaultPaginator | ✅ |  ❌  |
| Customer Wishlist Product |  | DefaultPaginator | ✅ |  ❌  |
| Delivery Time Resources |  | DefaultPaginator | ✅ |  ❌  |
| Document Resources |  | DefaultPaginator | ✅ |  ❌  |
| Order List |  | DefaultPaginator | ✅ |  ❌  |
| Order Addreses |  | DefaultPaginator | ✅ |  ❌  |
| Order Customer List |  | DefaultPaginator | ✅ |  ❌  |
| Order Delivery List |  | DefaultPaginator | ✅ |  ❌  |
| Order Delivery Positions |  | DefaultPaginator | ✅ |  ❌  |
| Order Line Items |  | DefaultPaginator | ✅ |  ❌  |
| Order Transactions |  | DefaultPaginator | ✅ |  ❌  |
| Products |  | DefaultPaginator | ✅ |  ❌  |
| Product Reviews |  | DefaultPaginator | ✅ |  ❌  |
| Countries |  | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hello 👋 Due to the numerous contributions happening, I decided to create this [view](https://github.com/orgs/airbytehq/projects/104/views/3) to help you know when I plan to review your contribution. If your connector has some limited-time credential feel free to reach me out.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
The connector is not correct. Pagination and Page Size aren't configured properly.
It looks the existing connector users API Version 5, I strongly recommend to move to the last stable which is Version 6.
For Version 5 connector users offset with parameter start which today none stream is doing properly.

@Harmaton I strongly recommend to you create the connector in Airbyte Cloud to make the review easier and share the workspace with me. Please fix the points I made in this review. I'm moving the next review to Nov-11 make sure you have a square icon included as well.

**Comment by Harmaton** [comment]
Thank you @marcosmarxm . I already invited you to my workspace and I was already using airbyte cloud.

**Comment by Harmaton** [comment]
When I raised the PR everything was working. For instance the auth is no longer working again

**Comment by Harmaton** [comment]
Seem to be an outh misconfiguration because it was working with `client_id` and `client_secret` before

**Comment by marcosmarxm** [comment]
@Harmaton can you make sure the connector is working and ping me when its resolved?

**Comment by marcosmarxm** [comment]
Waiting user return.

**Comment by marcosmarxm** [comment]
Moving review to Nov 11

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
I couldn't test the existing connector in your workspace. No endpoints are returning data.
Please check asap, Moving next check to Monday Nov 11

**Comment by marcosmarxm** [comment]
Declined: user didn't update my comments and existing connector is not working properly in cloud workspace.

**Pull request closed without merging**
