### PR TITLE
Match entry in client cert keystore to hardcoded postgres driver value

### LINKED ISSUE #17000: postgres connector - ssl connection not working
## Environment
- **Airbyte version**:  0.40.7
- **OS Version / Instance**: Debian 10
- **Deployment**: Docker
- **Source Connector and version**: Postgresql 1.0.8
- **Step where error happened**:  Setup new connection 

## Current Behavior

When I specified all the parameters for the verify-ca connection mode in psql Airbyte give me an error as seen in the image

Also I cant use the require ssl connection mode because I dont have the field to complete with the key and crt.

## Expected Behavior

To connect in verify-ca mode or require mode.

As showed in the last image I cant provide the key and crt for require mode connection

## Steps to Reproduce
1. Create a new connector
2. Specify require mode ssl or verify-ca
3. Try to set up a connection
airbyte
result
image

### PR DESCRIPTION
**Pull request by rodireich**
## What
Client certificate connection is failing against postgres db.

## How
source postgres is packaging the client cert and key in a key store. The alias used for the key+cert entry in keystore has to be set to "user".
This is due to the fact that the postgres driver is set to load a [hard coded](https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/ssl/PKCS12KeyManager.java#L155) key entry with alias "user", even though the manager has code to identified the alias of the first inserted entry in store. A potential bug

### CODE REVIEW

**Review by subodh1810 — APPROVED** [review]

**Comment by rodireich** [comment]
/publish connector=connectors/source-postgres run-tests=false

**Comment by rodireich** [comment]
/publish connector=connectors/source-postgres run-tests=false

**Comment by rodireich** [comment]
/publish connector=connectors/source-postgres-strict-encrypt auto-bump-version=false

**Pull request merged**
