### PR TITLE
gradle.yml: use a smaller runner

### PR DESCRIPTION
**Pull request by alafanechere**
Downsize the runner used on `gradle.yml` for cost control

### CODE REVIEW

**Comment by alafanechere** [comment]
* **#35547** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/35547?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alafanechere and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by evantahler — APPROVED** [review]

**Review by octavia-approvington — APPROVED** [review]

**Comment by octavia-approvington** [comment]
It's time <br/> fine lets go

**Comment by postamar** [comment]
How will this be cheaper?? The workload is parallelized very well across all cores. Since the pricing is per time and per core the cost will be just the same.

**Pull request merged**
