### PR TITLE
:tada: New Destination: Teradata Vantage

### PR DESCRIPTION
**Pull request by sc250072**
## What
*Describe what the change is solving*
Teradata Vantage is the complete cloud analytics and data platform with next-generation, cloud-native deployment and expanded analytics capabilities. This connector helps to load data to teradata from other sources and apply transformations through airbyte.
*It helps to add screenshots if it affects the frontend.* 
doesn't effect the frontend

## How
*Describe the solution*
The current version of the connector provides importing data to teradata through airbyte. The implemented version of the connector will allow for overwrite and append sync modes. Tried to implement basic and dbt normalization but facing issues on normalization process. Currently, this connector able to load data to teradata into raw tables. 

## Recommended reading order
1. `TeradataDestination.java`
2. `TeradataSqlOperations.java` and rest

## 🚨 User Impact 🚨
No breaking changes. User can load data from any airbyte supported source to teradata through airbyte.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

image

</details>

<details><summary><strong>Integration</strong></summary>

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

Integration/AcceptanceTests  requires teradata vantage instance and able to access from machine, where these tests are running. Please follow Prerequisites section of https://github.com/SatishChGit/airbyte/blob/teradata_java_dest_conn/docs/integrations/destinations/teradata.md.
To run Integration/AcceptanceTests, this connector requires config.json and failureconfig.json json files under airbyte-integrations/connectors/destination-teradata/secrets
format of config.json and failureconfig.json is
**_{ "host" : "teradatainstancehostname", "username": "username", "password": "password", "schema" : "schemaname" }_**

Below three test cases are failing and need airbyte help to resolve these.
[TeradataDestinationAcceptanceTest](https://github.com/airbytehq/airbyte/classes/io.airbyte.integrations.destination.teradata.TeradataDestinationAcceptanceTest.html). [[1] exchange_rate_messages.txt, exchange_rate_catalog.json](https://github.com/airbytehq/airbyte/classes/io.airbyte.integrations.destination.teradata.TeradataDestinationAcceptanceTest.html#testSync(String,%20String)[1])
[TeradataDestinationAcceptanceTest](https://github.com/airbytehq/airbyte/classes/io.airbyte.integrations.destination.teradata.TeradataDestinationAcceptanceTest.html). [[2] edge_case_messages.txt, edge_case_catalog.json](https://github.com/airbytehq/airbyte/classes/io.airbyte.integrations.destination.teradata.TeradataDestinationAcceptanceTest.html#testSync(String,%20String)[2])
[TeradataDestinationAcceptanceTest](https://github.com/airbytehq/airbyte/classes/io.airbyte.integrations.destination.teradata.TeradataDestinationAcceptanceTest.html). [[2] edge_case_messages.txt, edge_case_catalog.json](https://github.com/airbytehq/airbyte/classes/io.airbyte.integrations.destination.teradata.TeradataDestinationAcceptanceTest.html#testSyncWithLargeRecordBatch(String,%20String)[2])

image

</details>

### CODE REVIEW

**Comment by luistorrealbaCinfo** [comment]
Hi,

I was trying to use this connector. Can you please tell me where should I look into in order to try this connector out?

**Comment by SatishChGit** [comment]
> Hi,
> 
> I was trying to use this connector. Can you please tell me where should I look into in order to try this connector out?

Hi, please refer to https://github.com/SatishChGit/airbyte/blob/teradata_java_dest_conn/docs/integrations/destinations/teradata.md

**Comment by natalyjazzviolin** [comment]
Hi @SatishChGit ! Thanks so much for your contribution. Currently we're blocked from testing/merging this PR because we don't have a sandbox account. I've opened a request here:
https://github.com/airbytehq/airbyte/issues/19656

**Comment by SatishChGit** [comment]
> Hi @SatishChGit ! Thanks so much for your contribution. Currently we're blocked from testing/merging this PR because we don't have a sandbox account. I've opened a request here: #19656

[natalyjazzviolin](https://github.com/natalyjazzviolin) Thank you for your response. Can you check the possibility of setting up free version of Vantage Express on machines your local machines and can be used same machine for testing. Please check this possibility and let us know if you need any help on this.

If you need a new instance of Vantage, you can install a free version called Vantage Express in the cloud on [Google Cloud](https://quickstarts.teradata.com/vantage.express.gcp.html), [Azure](https://quickstarts.teradata.com/run-vantage-express-on-microsoft-azure.html), and [AWS](https://quickstarts.teradata.com/run-vantage-express-on-aws.html). You can also run Vantage Express on your local machine using [VMware](https://quickstarts.teradata.com/getting.started.vmware.html), [VirtualBox](https://quickstarts.teradata.com/getting.started.vbox.html), or [UTM](https://quickstarts.teradata.com/getting.started.utm.html).

**Comment by marcosmarxm** [comment]
Hello :wave:, first thank you for this amazing contribution. 

We really appreciate the effort you've made to improve the project.
We ask you patience for the code review. Last month our team was focused on Hacktoberfest event and that probably left some PR without the proper feedback. And this week, due to the Thanksgiving US Holiday, most our team is out of office with their families. Another important piece of information why code won't be merge this week is: as a safety measure the core team has decided to freeze merging code to main branch to keep the release stable. Next week we'll return to you with the proper code review and update the status of your contribution.

If you have any questions feel free to send me a message in Slack!
Thanks!

**Comment by luistorrealbaCinfo** [comment]
Sorry, i'm having a problem. When I enter Airbyte and click on create new destination I don't find Teradata. Can you please help me with this?

**Comment by SatishChGit** [comment]
As per suggestion from [marcosmarxm](https://github.com/marcosmarxm), creating two PR requests for vantage connector. One for Base connector without normalization and other one for normalization support.

**Pull request closed without merging**
