### PR TITLE
remove connector health page and display all connectors on the root connectors page

### LINKED ISSUE #3644: Rework connector health page
## Tell us about the documentation you'd like us to add or update
The connector health page displays build statuses for connectors. This is tricky to message correctly, as it just showed the build status of connectors, which does not necessarily correlate with whether the connector will work when deployed by a user. A vast majority of the time when a connector build is failing, it's because of a problem with the sandbox account or the API token etc.. and not because there is an actual issue with the connector. 

The correct structure here imo is: 

1. Display all connectors without build status on the root connectors page in the docs
1. Alert the Airbyte dev team when one of the . I've created a separate issue to track this here: https://github.com/airbytehq/airbyte/issues/3477

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200387488212590) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by sherifnada**
## What
The connector health page previously displayed build statuses for connectors. This is tricky to message correctly, as it just showed the build status of connectors, which does not necessarily correlate with whether the connector will work when deployed by a user. A vast majority of the time when a connector build is failing, it's because of a problem with the sandbox account or the API token etc.. and not because there is an actual issue with the connector. 

The correct structure here imo is: 

1. Display all connectors without build status on the root connectors page in the docs
1. Alert the Airbyte dev team when one of the . I've created a separate issue to track this here: https://github.com/airbytehq/airbyte/issues/3477

## How
This PR performs step 1 above.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368130780324) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by michel-tricot — APPROVED** [review]
make sure you work with @johnlafleur to also update airbyte.io

**Comment by johnlafleur** [comment]
Some comments: 
* After some thoughts, I actually wouldn't make the difference between what was provided by the community vs Airbyte. The question is was it certified. So I would change the list to "Airbyte Certified" and "Not certified yet", and it's an opportunity for what certification means
* This means that the structure would be:
** Sources
*** Airbyte Certified Sources
*** Not Certified yet
** Destinations

**Comment by sherifnada** [comment]
@johnlafleur  maybe we can break down airbyte connectors further into alpha/beta/certified etc.. but the main message is whether we provide support for something or not, in which case the distinction between community vs airbyte provided is important. WDYT?

**Comment by johnlafleur** [comment]
Are you sure we won't provide any support for community-provided connectors? Oracle DB was provided by the community. What if other important ones are?

**Comment by cgardens** [comment]
Will we still be able to access this dashboard internally somehow?

**Comment by jrhizor** [comment]
Agreed with John that we should have a commitment to maintenance not the source of the connector since we do want to adopt Oracle as a core connector but maybe not others in the future.

I think until https://github.com/airbytehq/airbyte/issues/3477 it would be useful to have a view for the build status without it being a page intended for user consumption. We can include disclaimers and not refer to it as connector health.

**Comment by sherifnada** [comment]
@jrhizor @johnlafleur would the point be addressed if we call it "Airbyte maintained" instead of "provided" ?

**Comment by johnlafleur** [comment]
It would imply that we don't maintain the others, which we may not. The thing is we will maintain the ones that are the most important and used. And some of them might be now in the not-maintained list. I feel this is not the perception we want to give. I think certified / alpha / beta is they way to go, personally.

**Comment by sherifnada** [comment]
Fixed concerns. Separated into alpha/beta/certified. Also added an MD page to find build statuses in the `integrations/` directory.

**Comment by johnlafleur** [comment]
Looks good!

**Pull request merged**
