### PR TITLE
✨Source ExchangeRatesApi: Make Connector Compatible with Builder

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
* Make the connector compatible with the builder

## How
* Import schema to manifest
* Update docs, 
* Completely made compatible with the builder

## User Impact
* No impact, chore for maintainability.

## Can this PR be safely reverted and rolled back?
- [x] YES 💚

### CODE REVIEW

**Comment by btkcodedev** [comment]
Incremental sync was broken, Fixed it

**Comment by btkcodedev** [comment]
@girarda, the connector fetches only one record on current date, I've tried recod_filter with record['date'] >= stream_interval['start_date'] but it is also not working

there is an inject option as date, I've included it, but still the same, Could you please help

**Comment by btkcodedev** [comment]
@girarda,
The latest version of this connector is also failing its incremental sync, What to do now? 
Your call.
Ref:
image

**Review by girarda — APPROVED** [review]

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
