### PR TITLE
Add devcontainer configs for "Python generic" and "Default"

### PR DESCRIPTION
**Pull request by aaronsteers**
Adds two devcontainer configs: one for Python and one for "Default".

Originally, I considered leaving out any default option - but the Codespaces UI still defaults to the undefined 'Default' even when there isn't a default config available.

image

This PR adds a Python-specific devcontainer config as well as a generic "Default" Python+Java devcontainer config. If the 'Default' is selected, a reasonably Python+Java container config is selected. Both the Default and the Python devcontainer configs now include the `make` command to install `airbyte-ci`.

### CODE REVIEW

**Comment by aaronsteers** [comment]
Attempting to run `make` and then `airbyte-ci` in this container returns the error message:

```log
@aaronsteers ➜ /workspaces/airbyte (aj/source-faker/airbytelib-entrypoints) $ airbyte-ci format
[9007] Error loading Python lib '/tmp/_MEIK0bFg7/libpython3.10.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIK0bFg7/libpython3.10.so.1.0)
@aaronsteers ➜ /workspaces/airbyte (aj/source-faker/airbytelib-entrypoints) $ airbyte-ci --help
[9489] Error loading Python lib '/tmp/_MEIQMynEr/libpython3.10.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIQMynEr/libpython3.10.so.1.0)
```


Workaround is to run this way:

```console
pipx install ./airbyte-ci/connectors/pipelines
airbyte-ci-dev format fix all
```

Based on a google search, it looks like the compiled version created by PyInstaller has a specific dependency on GLIBC, which (I think) is satisfied by Ubunty 20, but not by this container's base OS.

**Review by alafanechere — COMMENTED** [review]
I reviewed the source-faker PR before which also has the `devcontainer` changes:
https://github.com/airbytehq/airbyte/pull/34033#pullrequestreview-1810641898

I'm not requesting change as I don't want to block airbyte-lib iterations. I now realize this is to meant to be used in codespace. I'm not sure if these devcontainers / codespace is meant to be:
* A platform to use `airbyte-lib`
* A platform to iterate on connector code. 

In the later case I'd appreciate seeing the connector base image being used

Could you please clarify?

**Review by natikgadzhi — APPROVED** [review]
I love an idea of having a dev container that would allow contributors to spin up a development environment in a codespace with one click! 

This looks fine for connectors —could we expand Python connector one to allow working on Python CDK / Airbyte-CI itself? 

@aaronsteers want to add documentation about how to work on any given connector (assume custom python connector using poetry) with this, in a codespace? I would love to make a video walkthrough based on your script, covering: 
1. How to open a connector
2. How to install it's dependencies in the codespace
3. How to make changes, run tests locally
4. How to make a PR after that

I'd be very invested in this!

**Comment by aaronsteers** [comment]
@natikgadzhi - Re:

> I love an idea of having a dev container that would allow contributors to spin up a development environment in a codespace with one click!

Me too! 😄 

> This looks fine for connectors —could we expand Python connector one to allow working on Python CDK / Airbyte-CI itself?

Yep - that should already be enabled with the default devcontainer or with the Python (generic) devcontainer.

> @aaronsteers want to add documentation about how to work on any given connector (assume custom python connector using poetry) with this, in a codespace? I would love to make a video walkthrough based on your script, covering:
>
> 1. How to open a connector
> 2. How to install it's dependencies in the codespace
> 3. How to make changes, run tests locally
> 4. How to make a PR after that

I'll take this in a subsequent pass, if that's okay. The great thing is that there are default 'rails' for all of the things you note above.

> I'd be very invested in this!

Sweet. I'm going to merge per this approval, and will follow up with some loom videos on the above.

**Pull request merged**
