### PR TITLE
source-mysql : Make MySQL password a required field

### PR DESCRIPTION
**Pull request by akashkulk**
Context : https://airbytehq-team.slack.com/archives/C03088BTMFC/p1688164260395999

### CODE REVIEW

**Comment by rodireich** [comment]
No need to do the `always_show: true`?

**Review by rodireich — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-mysql test report (commit [`ca0f1438ea`](https://github.com/airbytehq/airbyte/pull/27897/commits/ca0f1438ea288de7380455ad738e0fdbd735ac24)) - ❌

⏲️  Total pipeline duration: 16mn44s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql/metadata.yaml     | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ❌        |
| QA checks                                                               | ✅        |
| Build connector tar                                                     | ✅        |
| Build source-mysql docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mysql:integrationTest | ❌        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/spec_change_mysql/1688167355/ca0f1438ea288de7380455ad738e0fdbd735ac24/source-mysql/2.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Comment by sherifnada** [comment]
@akashkulk my understanding is that password is not required by postgres. Why not use `always_show: true` instead?

**Comment by octavia-squidington-iii** [comment]
##  source-mysql-strict-encrypt test report (commit [`0cb21c29a5`](https://github.com/airbytehq/airbyte/pull/27897/commits/0cb21c29a5f50e074076814b2cd642a5a7d005f1)) - ❌

⏲️  Total pipeline duration: 12mn51s 

| Step                                                                                   | Result   |
|:---------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                         | ✅        |
| QA checks                                                                              | ✅        |
| Build connector tar                                                                    | ✅        |
| Build source-mysql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mysql-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/spec_change_mysql/1688760842/0cb21c29a5f50e074076814b2cd642a5a7d005f1/source-mysql-strict-encrypt/2.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mysql-strict-encrypt test report (commit [`0cb21c29a5`](https://github.com/airbytehq/airbyte/pull/27897/commits/0cb21c29a5f50e074076814b2cd642a5a7d005f1)) - ❌

⏲️  Total pipeline duration: 11mn58s 

| Step                                                                                   | Result   |
|:---------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                         | ✅        |
| QA checks                                                                              | ✅        |
| Build connector tar                                                                    | ✅        |
| Build source-mysql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mysql-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/spec_change_mysql/1688856216/0cb21c29a5f50e074076814b2cd642a5a7d005f1/source-mysql-strict-encrypt/2.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mysql test report (commit [`0cb21c29a5`](https://github.com/airbytehq/airbyte/pull/27897/commits/0cb21c29a5f50e074076814b2cd642a5a7d005f1)) - ❌

⏲️  Total pipeline duration: 15mn44s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql/metadata.yaml     | ✅        |
| Connector version semver check                                          | ✅        |
| QA checks                                                               | ✅        |
| Build connector tar                                                     | ✅        |
| Build source-mysql docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mysql:integrationTest | ❌        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/spec_change_mysql/1688856216/0cb21c29a5f50e074076814b2cd642a5a7d005f1/source-mysql/2.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Pull request closed without merging**
