### PR TITLE
Facebook Pages and Facebook Marketing connector license to Elv2

### PR DESCRIPTION
**Pull request by evantahler**
See https://github.com/airbytehq/airbyte/issues/27724

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-pages test report (commit [`e5a9d29b12`](https://github.com/airbytehq/airbyte/pull/27728/commits/e5a9d29b12dcde0788f1de81dea2e72c6d44b96e)) - ❌

⏲️  Total pipeline duration: 548 seconds

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-pages/metadata.yaml | ✅        |
| Connector version semver check                                               | ✅        |
| Connector version increment check                                            | ✅        |
| QA checks                                                                    | ✅        |
| Code format checks                                                           | ✅        |
| Connector package install                                                    | ✅        |
| Build source-facebook-pages docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                   | ✅        |
| Acceptance tests                                                             | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-facebook/1687821365/e5a9d29b12dcde0788f1de81dea2e72c6d44b96e/source-facebook-pages/0.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-pages test
```

**Comment by evantahler** [comment]
Note: `source-facebook-pages` is failing on master.

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`e5a9d29b12`](https://github.com/airbytehq/airbyte/pull/27728/commits/e5a9d29b12dcde0788f1de81dea2e72c6d44b96e)) - ✅

⏲️  Total pipeline duration: 3697 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-facebook/1687821365/e5a9d29b12dcde0788f1de81dea2e72c6d44b96e/source-facebook-marketing/0.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by octavia-approvington** [comment]
Myomoto says it looks good <br/> thats a niiice

**Review by octavia-approvington — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-pages test report (commit [`30bd010218`](https://github.com/airbytehq/airbyte/pull/27728/commits/30bd010218755d37867a30b15eab0b5f72a8bf3a)) - ❌

⏲️  Total pipeline duration: 487 seconds

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-pages/metadata.yaml | ✅        |
| Connector version semver check                                               | ✅        |
| Connector version increment check                                            | ❌        |
| QA checks                                                                    | ✅        |
| Code format checks                                                           | ✅        |
| Connector package install                                                    | ✅        |
| Build source-facebook-pages docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                   | ✅        |
| Acceptance tests                                                             | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-facebook/1687826057/30bd010218755d37867a30b15eab0b5f72a8bf3a/source-facebook-pages/0.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-pages test
```

**Comment by octavia-squidington-iii** [comment]
##  source-facebook-marketing test report (commit [`30bd010218`](https://github.com/airbytehq/airbyte/pull/27728/commits/30bd010218755d37867a30b15eab0b5f72a8bf3a)) - ❌

⏲️  Total pipeline duration: 3189 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ❌        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-facebook/1687826057/30bd010218755d37867a30b15eab0b5f72a8bf3a/source-facebook-marketing/0.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Pull request merged**
