### PR TITLE
🎉Source SurveyMonkey: handle 404

### LINKED ISSUE #15295: Survey Monkey 0.1.9 Error: 404 Client Error: Not Found for url
## Environment
- **Airbyte version**:  0.39.37-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Survey Monkey 0.1.9
- **Destination Connector and version**: 0.4.34
- **Severity**: High
- **Step where error happened**: Sync

## Current Behavior
Sync files

## Expected Behavior
Sync should succeed

## Logs
[logs-35422 (1).txt](https://github.com/airbytehq/airbyte/files/9259747/logs-35422.1.txt)

## Steps to Reproduce
1.
2.
3.

### PR DESCRIPTION
**Pull request by roman-yermilov-gl**
## What
- Handle 404 error for nonexistent surveys (skip failed)
- Check custom ids. Fail `test_connection` if survey does not exist

### CODE REVIEW

**Review by arsenlosenko — APPROVED** [review]

**Review by arsenlosenko — APPROVED** [review]

**Review by bazarnov — APPROVED** [review]

**Review by alafanechere — APPROVED** [review]
LGTM

**Comment by danieldiamond** [comment]
I'm running into issues now
```
Failure Origin: source, Message: User does not have the following required permissions: survey.export_results
```
whereas previously everything was working fine

**Comment by marcosmarxm** [comment]
> I'm running into issues now
> 
> ```
> Failure Origin: source, Message: User does not have the following required permissions: survey.export_results
> ```
> 
> whereas previously everything was working fine

Do you mind creating a Github issue @danieldiamond ? I'll ask the team to check asap

**Pull request merged**
