### PR TITLE
🐛 Source Shopify: fix for mismatched number of tables during normalization

### LINKED ISSUE #8353: Source Shopify throw`AssertionError: Mismatched number of tables` during normalization
## Enviroment
- **Airbyte version**:  0.32.8-alpha
- **OS Version / Instance**: macOs
- **Deployment**: Docker
- **Source Connector and version**: Shopify 0.1.24
- **Destination Connector and version**: Postgres 0.3.12
- **Severity**: Very Low / Low / Medium / **High** / Critical
- **Step where error happened**: Deploy / **Sync job** / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
I'm trying to sync all tables using Incremental Dedup and normalization is failing when checking the number of tables created.
image

## Expected Behavior
*Tell us what should happen.*

## Logs
Complete sync log: [logs-1-0 (3).txt](https://github.com/airbytehq/airbyte/files/7629630/logs-1-0.3.txt)
I tried to reset the data and got the same problem too: [logs-3-0 (2).txt](https://github.com/airbytehq/airbyte/files/7629632/logs-3-0.2.txt)

```
normalization - 2021-11-30 23:50:23 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/table_name_registry.py", line 196, in resolve_table_names
normalization - 2021-11-30 23:50:23 INFO () LineGobbler(voidCall):82 - Truncating orders_refunds_refund_line_items_subtotal_set (#45) to orders_refunds_refun_ne_items_subtotal_set (#43)
normalization - 2021-11-30 23:50:23 ERROR () LineGobbler(voidCall):82 -     assert (table_count * 2) == registry_size, f"Mismatched number of tables {table_count * 2} vs {registry_size} being resolved"
normalization - 2021-11-30 23:50:23 ERROR () LineGobbler(voidCall):82 - AssertionError: Mismatched number of tables 432 vs 384 being resolved
```

## Steps to Reproduce
1. create shopify connector using integration account
2. create postgres destination
3. run sync 💥 

## Are you willing to submit a PR?

Remove this with your answer.

### LINKED ISSUE #8487: 🐛 Source Shopify: slow orders_refunds read + InvalidChunkLength error
## Environment
- **Airbyte version**:  0.30.33-alpha
- **OS Version / Instance**: GCP (Compute Engine) / n1-standard-2
- **Deployment**: Docker
- **Source Connector and version**: Shopify 0.1.24
- **Severity**: High 
- **Step where error happened**:Sync job

## Current Behavior
A user reaching us on [slack](https://airbytehq.slack.com/archives/C01MFR03D5W/p1636807297009600) wants to perform an initial load of Shopify store data by syncinc the following streams:

* ✅ **customer** stream: 172423 records loaded in ~40mn (~70 records / second)
* ✅ **discount_code**, **draft_orders** and **locations** streams have few records and are synced without problem.
* ✅ **orders** stream: 272939 records in 3h44mn (~20 records / second)
* ❌ **orders_refunds** stream: ~90000 records read fails after 12h38mn (**~2 records / second, which is Shopify standard rate limit, but user has a Shopify Plus account that should increase the rate limit to ~4 requests / second )**

Syncing `orders_refunds` fails with the following error: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 106, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 174, in _read_incremental
    for slice in slices:
  File "/airbyte/integration_code/source_shopify/source.py", line 166, in stream_slices
    for record in parent_stream.read_records(stream_state=parent_stream_state, **kwargs):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 351, in read_records
    response = self._send_request(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 318, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 274, in _send
    response: requests.Response = self._session.send(request, **request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 697, in send
    r.content
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 836, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 761, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read
```

**Questions**:
* `order_refund` stream requires calling each order id to retrieve the refund details can be very long. The same information is already provided by the `orders.json` in a nested field. For performance improvements could we make the `order_refund` call a cached `orders.json` endpoint and extract the refunds from the nested field?
* Do you have an idea of the root cause of `InvalidChunkLength`? Could we handle this error and retry the request?

_NB: The `MAX_SYNC_TIMEOUT_DAYS` was not reached, user updated this env var for >7 days loads._

## Expected Behavior
* Users expects a successful initial data load as fast as possible. As a benchmark, according to the user, Matillion data loader loads data for the same stores in 1-2 days.

## Logs
[Available on Slack (29MB is too much for GitHub upload)](https://airbytehq.slack.com/archives/C01MFR03D5W/p1638511950310000?thread_ts=1636807297.009600&cid=C01MFR03D5W)
## Steps to Reproduce
1. Set up a connection between Shopify and BigQuery 
2. Have an account with `272 000` orders
3. Run the sync with the same stream as listed above

### PR DESCRIPTION
**Pull request by bazarnov**
## What
#8353

## How
- edited scheams: `orders, abandoned_checkouts, draft_orders, metafields`
- forced the `DataTypeEnforcer` to set `string` as `string`, in some cases.
- renamed `orders_refunds` to `order_refunds` to avoid name conflicts during normalisation process.
- fixed the issue, when `AirbyteLogger` exposes the data coming from `stream_slice`
- increased the performance of `order_refunds` stream, by polling out refund-ready information from the order.
- implemented re-use of `shop` stream in the `check_connection` method.

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [X] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [X] Documentation updated 
    - [X] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [X] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

### CODE REVIEW

**Comment by sherifnada** [comment]
@bazarnov what was the root cause for the linked issue?

**Comment by bazarnov** [comment]
> @bazarnov what was the root cause for the linked issue?

There was a conflict between `orders` stream schema and `orders_refunds` stream schema.
The `orders` schema contains the `refunds` property which is the same as the whole `orders_refunds` schema, it's duplicating as nested structure. While creating the tables for `orders_refunds` there was a conflict between of two and the tables were not created properly.

**Review by antixar — COMMENTED** [review]
Names of 2 streams were changed. will it be able to break exist user syncs?
Can we keep old ones? Or create new streams separately or add names' aliases

**Comment by bazarnov** [comment]
> Names of 2 streams were changed. will it be able to break exist user syncs? Can we keep old ones? Or create new streams separately or add names' aliases

As far as we edited the schemas, the users will have to redo the whole sync again, unfortunately. We cannot keep the old ones here.

**Comment by antixar** [comment]
> > Names of 2 streams were changed. will it be able to break exist user syncs? Can we keep old ones? Or create new streams separately or add names' aliases
> 
> As far as we edited the schemas, the users will have to redo the whole sync again, unfortunately. We cannot keep the old ones here.

Please add comment about this possible problems with old streams and obvious errors as log message for end users. With a short instruction how they have to migrate to the new ones. Maybe add a link to this PR where will be more details

**Review by antixar — APPROVED** [review]
LGTM!
Please publish your changes

**Review by lazebnyi — APPROVED** [review]

**Pull request merged**
