### PR TITLE
Source S3: Set CAT exact_order to true

### PR DESCRIPTION
**Pull request by girarda**
## What
* Assert the records read by the S3 source are read in the same order as the expected records

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`041663ad87`](https://github.com/airbytehq/airbyte/pull/29351/commits/041663ad87d06a92f49e047313e12ff74bdabc46)) - ✅

⏲️  Total pipeline duration: 22mn23s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_s3_cats_exact_order/1691713520/041663ad87d06a92f49e047313e12ff74bdabc46/source-s3/3.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:041663ad87d06a92f49e047313e12ff74bdabc46)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`041663ad87`](https://github.com/airbytehq/airbyte/pull/29351/commits/041663ad87d06a92f49e047313e12ff74bdabc46)) - ✅

⏲️  Total pipeline duration: 20mn41s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_s3_cats_exact_order/1691714983/041663ad87d06a92f49e047313e12ff74bdabc46/source-s3/3.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:041663ad87d06a92f49e047313e12ff74bdabc46)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`924e187b31`](https://github.com/airbytehq/airbyte/pull/29351/commits/924e187b31749047419aa82a6c81826413dcb2a7)) - ✅

⏲️  Total pipeline duration: 22mn32s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_s3_cats_exact_order/1691716351/924e187b31749047419aa82a6c81826413dcb2a7/source-s3/3.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:924e187b31749047419aa82a6c81826413dcb2a7)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Review by clnoll — APPROVED** [review]
LGTM but is there a reason we need to guarantee the order?

**Comment by maxi297** [comment]
> LGTM but is there a reason we need to guarantee the order?

It feel to me like a good validation to have as we are allowing for incremental syncs which track the state by dates. Also, CATs outputs are way better when exact_order is true because we don't hash the expected/actual and we can have a clear diff. 

That being said, I'm wondering what will happen of this option once will have concurrent CDK

**Review by maxi297 — APPROVED** [review]
:shipit:

**Comment by girarda** [comment]
@clnoll I mostly want the more readable CAT diffs, but i also think validating the ordering is a good default behavior for CAT

@maxi297  that’s a good question. The best we’ll be able to guarantee is ordering within a partition

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`9977d42396`](https://github.com/airbytehq/airbyte/pull/29351/commits/9977d4239690bbd066bb8e0a4d2611e72b83c934)) - ✅

⏲️  Total pipeline duration: 13mn28s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_s3_cats_exact_order/1691772382/9977d4239690bbd066bb8e0a4d2611e72b83c934/source-s3/3.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:9977d4239690bbd066bb8e0a4d2611e72b83c934)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Pull request merged**
