### PR TITLE
:window: :art: Increases GroupTitle followed divs width from 180px to 250px

### LINKED ISSUE #8130: Increase width of drop down in connector configuration menu
## Tell us about the problem you're trying to solve

The dropdown width clips the text

Screen Shot 2021-11-18 at 10 24 47 PM

## Describe the solution you’d like
I would like the dropdown to fit all the text (at least up to the width of the form)

### PR DESCRIPTION
**Pull request by YatsukBogdan1**
## What
Closes #8130 

## How
I was investigating the actual problem of the dropdown width, and find out next:
- first of all, I thought the cleanest solution would be to render all the text if possible inside the select container. I was looking into internal CSS styles of react-select components and they have complicated logic for calculating the width of the actual text inside the select component and they are using some hacks with position: absolute; so from this point seems it is hard to implement it that way
Screenshot 2022-06-21 at 13 20 52
Screenshot 2022-06-21 at 13 21 44
- the most straightforward solution here is to change the min-width of GroupTitle styled component followed divs from 180px to 250px, since they are located inside airbyte codebase, but I am not sure how this can affect other components over the application
Screenshot 2022-06-21 at 13 18 18

## Actual Result
Screenshot 2022-06-21 at 13 24 04

### CODE REVIEW

**Review by teallarson — CHANGES_REQUESTED** [review]
Yeah, react-select does some things that make this styling picky.  I tried looking for other places that this change would affect and I haven't been able to find any.

250px doesn't look quite wide enough for all Google Sheets authentication options, though.  

Screen Shot 2022-06-21 at 10 31 44 AM

**Comment by YatsukBogdan1** [comment]
I increased the min-width to 350px, but again, not sure if this is not corrupting any other place in app

**Comment by tealjulia** [comment]
It doesn't look like this affects other places in the UI.  It does make the box wrap to another line for some connectors in the side-by-side docs view.
Screen Shot 2022-07-25 at 4 47 44 PM

I'll defer to @timroes or @dizel852 on whether that's blocking or not.

**Comment by dizel852** [comment]
IMO Since the dropdown will have unpredictable width and it's hard to calculate it I'd suggest updating our form design - move the dropdown to a new line.

Like on the screenshot
image

@timroes @Upmitt guys, your thoughts?

We need to finally solve this UI issue since it is "dangling" from sprint to sprint.

**Comment by timroes** [comment]
@tealjulia @YatsukBogdan1 I've changed the code to use flexbox for this title, so that the select box will always take the remaining space between the label. Maybe you could double check this and see if this looks good for you as well. This also helped us getting rid of the weird "& > div" styling which styled children without the component really knowing what users might put as children into the `title` property.

Since this component is also used in the `ArraySection` component, I also checked e.g. the Salesforce connector where it's used without a dropdown. Please validate that during review as well.


https://user-images.githubusercontent.com/877229/183396881-eacf70c4-405e-4cce-9691-f9b8a378cf98.mp4

**Comment by YatsukBogdan1** [comment]
> @dizel852 @tealjulia @YatsukBogdan1 I've changed the code to use flexbox for this title, so that the select box will always take the remaining space between the label. Maybe you could double check this and see if this looks good for you as well. This also helped us getting rid of the weird "& > div" styling which styled children without the component really knowing what users might put as children into the `title` property.
> 
> Since this component is also used in the `ArraySection` component, I also checked e.g. the Salesforce connector where it's used without a dropdown. Please validate that during review as well.
> 
>  Peek.2022-08-08.12-20.mp4

looks good me

**Review by dizel852 — APPROVED** [review]
Code LGTM.
Tested locally (Chrome, Safari and Firefox)

**Review by teallarson — APPROVED** [review]

**Pull request merged**
