### PR TITLE
Bump oracle connector

### PR DESCRIPTION
**Pull request by benmoriceau**
## What
Bump the connector version to make sure that the state lifecycle manager is included.

### CODE REVIEW

**Review by grishick — APPROVED** [review]

**Comment by benmoriceau** [comment]
Done by connector team

**Comment by edgao** [comment]
@VitaliiMaltsev @benmoriceau I think both of your publishes failed for destination-oracle? https://github.com/airbytehq/airbyte/pull/14618#issuecomment-1184862432

**Comment by VitaliiMaltsev** [comment]
> I think both of your publishes failed for destination-oracle?

@edgao yes

**Comment by grishick** [comment]
@ryankfu and I have published destination-oracle here: https://github.com/airbytehq/airbyte/pull/14736

**Pull request closed without merging**
