### PR TITLE
source-amplitude: Only fetch date_time_fields once per request

### PR DESCRIPTION
**Pull request by clnoll**
## What
Refactor so we're only fetch `date_time_fields` once per `EventsExtractor` instance, instead of once per record.

The `_get_date_time_items_from_schema` method that fetches `date_time_fields` is doing a lot of work - instantiating a `JsonFileSchemaLoader` which reads the schema, so hopefully this will help alleviate memory pressure issues.

### CODE REVIEW

**Review by artem1205 — APPROVED** [review]

**Review by evantahler — APPROVED** [review]
Nice find!

**Review by girarda — APPROVED** [review]

**Pull request merged**
