### PR TITLE
gradle: set user timezone to UTC in all tests

### LINKED ISSUE #31060: Set user timezone for all Java tests
### Topic

_No response_

### Relevant information

In order to ensure consistent timezone generation/comparison in Java tests across the repository, set the `user.timezone` Java system property for Gradle tests at the root level:

```
test {
    systemProperty 'user.timezone', 'UTC'
}
```

### PR DESCRIPTION
**Pull request by postamar**
Fixes https://github.com/airbytehq/airbyte/issues/31060.

### CODE REVIEW

**Comment by postamar** [comment]
Testing on:
- source-postgres: https://github.com/airbytehq/airbyte/actions/runs/6487712035

**Review by evantahler — APPROVED** [review]
no idea what the side effects will be... but I love it.

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Comment by jdpgrailsdev** [comment]
> no idea what the side effects will be... but I love it.

This ensures that Java interprets all timestamps as UTC when running the unit tests.  The goal is to make the tests deterministic when using timestamps to avoid it passing on one machine, but failing on another because the timezones in use are different.  It will not impact the code at runtime, though this is something to consider setting in general to make it easy for our customers to understand how we treat timestamps.

**Pull request merged**
