### PR TITLE
🎉 Source Amazon S3: Fix docs link issue

### LINKED ISSUE #12163: Update S3 connectors title to Amazon S3
Similar to https://github.com/airbytehq/airbyte-cloud/issues/1520 - update S3 source and destination connectors to Amazon S3. Ensure docs are updated to reflect this too.

### PR DESCRIPTION
**Pull request by lazebnyi**
## What
Fix link in docs

## How
Fix name of section in docs

## Pre-merge Checklist
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Comment by Phlair** [comment]
@lazebnyi Couple of Qs:
- Does this have the potential to break existing connections because of the name change? I'm genuinely not sure so hoping you've tested that.
- What's the motivation behind this change? This connector can actually be used for non-Amazon S3 compatible storage, so it seems incorrect to call it Amazon S3...

**Comment by lazebnyi** [comment]
@Phlair 
1. Changes doesn't break existing connections. Tested locally. 
2. Agree with you. For my side I think S3 name for the connector is ok. So, @misteryeo could you approve that we can leave S3 and close [issue](https://github.com/airbytehq/airbyte/issues/12163)?

**Comment by sherifnada** [comment]
@misteryeo we need to add some notion of search terms to connectors. This is an OSS platform + Frontend change

**Comment by lazebnyi** [comment]
@Phlair Reverted name to S3. Plz review.

**Review by Phlair — APPROVED** [review]
👍

**Pull request merged**
