### PR TITLE
🎉 octavia-cli: Add ability to import existing resources

### LINKED ISSUE #14291: octavia-cli: import existing Airbyte resources to manage them with octavia-cli
If I created some Airbyte resources using the console (destination, source, connection), I want to be able to manage these with octavia without recreating these.

E.G.:
I want to run an `octavia import source <my-source-id>` command that will generate a local YAML file with the source configuration I've already set up in the Airbyte UI.

### PR DESCRIPTION
**Pull request by danieldiamond**
## What

Extending https://github.com/airbytehq/airbyte/pull/13254 by adding `import` commands to import yaml configurations for existing sources, destinations and connections

### To Do

- Add tests
- Add `connection` import capabilities
- Avoid rewriting template configuration yamls?

@alafanechere this first generates the template configuration.yaml and then updates the config section using existing. However, this means that it will always create a _new_ resource i.e. a new unique resource_id. I essentially want to avoid using `ConnectorSpecificationRenderer` but create a new configuration.yaml without needing the definition. Any suggestions?

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by alafanechere** [comment]
I made some suggestion in #14161 to:
* Manage connections
* Store a state on import to avoid creating a new resource on `apply` after import.

**Comment by alafanechere** [comment]
I removed the batch import capabilities, I think it's a cool feature that we can add to a future PR once we are sure that the current import mechanism is working. An `octavia import all` would be amazing!

**Comment by danieldiamond** [comment]
@alafanechere imported changes and added a few additional changes as `apply` was failing with the `connection` piece. See commits but the tldr is

- make `resources_requirements` optional in apply renderer
- remove `catalog_id` and `catalog_diff` from `import_configuration` in generate
- slugify the `resource_name` only in the `get_output_path` function and not that actual attribute of the instantiated class as you suggested in TODO. my reasoning here is i'm not sure where else this attribute is used and I dont want to cause unintended modifications to the rendered instance e.g. causing a new resource to be created under the slugified name

**Comment by alafanechere** [comment]
@danieldiamond I think I finished my iterations. I'll go for a final review this week. Let me know if recent changes look good to you.

**Comment by alafanechere** [comment]
I ran the integration tests in the CI from https://github.com/airbytehq/airbyte/pull/14290, they pass ✅

**Comment by danieldiamond** [comment]
this looks great! i was going to suggest something more pythonic [here](https://github.com/airbytehq/airbyte/pull/14137/commits/305bafef35374f52ca6d9c4b417858944ce21797#diff-88550c802cbab8b870e254553f7ea9c015e8c742ae78b7f64c9e770f3a0305d3R317-R325) (with pop defaults and less if statements) but i think it would detract from the readability of it. thanks for helping on the integration tests

**Comment by danieldiamond** [comment]
@alafanechere just had a thought. out of scope for this PR but maybe an enhancement for `apply`, would it be possible to run a "dry run" before applying e.g. `octavia dry-apply` so for a source, this would hit the [check_connection_for_update](https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#post-/v1/sources/check_connection_for_update) endpoint.
or even if apply automatically did a dry run before applying

**Comment by alafanechere** [comment]
> i was going to suggest something more pythonic [here](https://github.com/airbytehq/airbyte/pull/14137/commits/305bafef35374f52ca6d9c4b417858944ce21797#diff-88550c802cbab8b870e254553f7ea9c015e8c742ae78b7f64c9e770f3a0305d3R317-R325) (with pop defaults and less if statements) but i think it would detract from the readability of it. thanks for helping on the integration tests

Yes I agree it's not the most elegant piece of code. What do you think about moving it to a dedicated function. I indeed wanted to maximize readability to make sure it's easy to understand that these fields are removed from the API response because they are not used for the `apply`.

>  would it be possible to run a "dry run" before applying
There is already a kind of dry run on `apply` because users are prompted a validation of the upcoming changes. I think that before this prompt we could definitely run a `check`. I opened an issue [here](https://github.com/airbytehq/airbyte/issues/12697) to track this improvement.

**Review by alafanechere — APPROVED** [review]
👏 Nice collaboration! Thank you for the initiative

**Pull request merged**
