### PR TITLE
[MotherDuck connector] fix: Pass config to connect_args in create_engine

### PR DESCRIPTION
**Pull request by guenp**
## What
Fixes an issue where the MotherDuck token is visibly logged by SQLAlchemy

## How
Pass the MotherDuck token via the `config` via `create_engine`'s `connect_args` so it's not logged by SQLAlchemy

## Review guide
1. destination_motherduck/processors/duckdb.py

## User Impact
No longer logging the token in the stdout

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by guenp** [comment]
@aaronsteers mindful ping to review when you get the chance -- thank you! :)

**Comment by aaronsteers** [comment]
```
    def test_check_succeeds(
        config: dict[str, str],
        request,
    ):
        destination = DestinationMotherDuck()
        status = destination.check(logger=MagicMock(), config=config)
>       assert status.status == Status.SUCCEEDED, status.message
E       AssertionError: An exception occurred: ProgrammingError('(duckdb.duckdb.CatalogException) Catalog Error: unrecognized configuration parameter "saas_mode"\n\nDid you mean: "access_mode"')
```

**Comment by aaronsteers** [comment]
@guenp - I checked out locally and was able to get the tests passing via https://github.com/airbytehq/airbyte/pull/48562/commits/696493ce07bd2044ab5ef536f6f5cfac600c2ee9

Also used your method of `create_engine()` in the Colab notebook [here](https://colab.research.google.com/drive/19A9cl8wx4Z93jDYcsEhQt5_lZAKUAGQ8#scrollTo=QqPU6k4JOA0A) and confirmed that Colab/Jupysql do not print the secret when created in this way.

If tests pass, we can merge from here. 🤞

**Comment by aaronsteers** [comment]
🎉 
image

https://github.com/airbytehq/airbyte/actions/runs/12191650380/job/34010915960

https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/guenp_token-via-config/1733451507/06cbafff3997079e02a09a2ea1bb43b02548f2f3/destination-motherduck/0.1.15/output.html

**Comment by guenp** [comment]
Thank you @aaronsteers !
The `saas_mode` error can be resolved by using `motherduck_saas_mode` instead.

**Review by aaronsteers — APPROVED** [review]

**Comment by aaronsteers** [comment]
@guenp - Tests are all passing now. To not risk delaying further, I'll go ahead and merge as-is, and we can come back later and optionally move `saas_only` into the config also with the `motherduck_saas_only` rename that you mention above.

Thanks again!

**Comment by guenp** [comment]
Thanks @aaronsteers I'll open a new PR for that!

**Pull request merged**
