### PR TITLE
✨ Source Bing Ads: support PerformanceMax Campaign Type

### LINKED ISSUE #34962: Source Bing Ads: Support PerformanceMax Campaign Type
### Topic

Source Bing Ads: Support PerformanceMax Campaign Type

### Need Support For PerformanceMax

Affected Stream: campaigns

Currently, Performance Max campaigns are not returned in the campaigns stream. They are a relatively new type of campaigns that was not supported by the connector.

[Related documentation on Campaign Type](https://learn.microsoft.com/en-us/advertising/campaign-management-service/campaigntype?view=bingads-13)

As a result, campaigns with a Campaign Type of PerformanceMax are not synced by the connector. Users will be missing these campaigns.

### Will you submit a PR

Yes.

### PR DESCRIPTION
**Pull request by matthewbelair**
resolves #34962 

## What

Currently, Bing Ads campaigns with a `CampaignType` of `PerformanceMax` are not synced in the `campaigns` stream. This results in the connector not syncing campaigns that are set as Performance Max campaigns in Bing Ads.

## How

This change simply updates the `CampaignType` body parameter in the API call to the `GetCampaignsByAccountId` operation to add PerformanceMax to the existing list of campaign types.

## Recommended reading order

1. `airbyte-integrations/connectors/source-bing-ads/source_bing_ads/base_streams.py`

## 🚨 User Impact 🚨

- There are no breaking changes to be expected from this update. Users can expect Performance Max campaigns to start syncing to their destination alongside their existing campaigns.
- For the semantic versioning, this could be a new MINOR or PATCH version. Additional data will be synced, but no changes are done to the schema.

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

### CODE REVIEW

**Review by marcosmarxm — APPROVED** [review]
@matthewbelair thanks! The change looks good to me. Can you increase the connector version in the metadata file and doc changelog? I requested to the connector team make the final review.

**Review by darynaishchenko — APPROVED** [review]
lgtm, please update changelog in bing-ads.md and increase docker tag in metedata.yml. Did you test it with PerformanceMax campaign type?

**Comment by marcosmarxm** [comment]
There is an unit test failing in tests. I'm going to fix them and get the contribution merged.

**Comment by marcosmarxm** [comment]
sorry the delay to get this merged @matthewbelair waiting integration tests to get green again and after I'll merged asap.

**Comment by marcosmarxm** [comment]
@matthewbelair can you update the branch with latest master branch? It added the option to run in forks and we're going to make easier your contribution.

**Comment by matthewbelair** [comment]
@marcosmarxm let me know if that works.

**Comment by marcosmarxm** [comment]
@matthewbelair running tests! I'll take a look tomorrow in the results

**Comment by natikgadzhi** [comment]
Merged in #40746!

**Pull request closed without merging**
