### PR TITLE
Python CDK: Bump `jsonschema` and `pendulum` dependencies

### PR DESCRIPTION
**Pull request by Udit107710**
## What
- Support for Prefect 3
- Bump up jsonschema and pendulum to support Prefect 3
- [Issue](https://github.com/airbytehq/PyAirbyte/issues/365)

## How
- Upgrade to new versions
- Fix breaking changes from the newer versions

## Can this PR be safely reverted and rolled back?
- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by aaronsteers** [comment]
@Udit107710 - Is it correct that we're blocked on an upstream change in the CDK?

Also, we just release the latest version of PyAirbyte which adopts SQLalchemy 2.0 and includes a number of other version bumps as well. 

You'll want to merge in those changes from `main` - and please do let me know if you run into any unexpected issues.

**Comment by aaronsteers** [comment]
@Udit107710 - aside from tests, did you find any breaking changes in Pendulum 3.0?

If not, could we (at least here in the CDK keep support for the latest 2.x version of Pendulum as well as 3.0?

I'm wary of boxing people out of PyAirbyte if they are using something that still has a 2.x dependency, and I don't think Pendulum 3.0 adoption has been promoted as a high priority in other libraries/tools.

Lmk what you think. Thanks!

**Comment by Udit107710** [comment]
I don't think keeping support for both the versions would be possible. Take a look at the changelog [here](https://github.com/sdispater/pendulum/releases). The changes in pendulum are not backwards compatible. 
Even after reading the changelog if you still feel that we should test it out once, I will do so.

**Comment by Udit107710** [comment]
@aaronsteers What do you think about the above comment?

**Comment by s0ham075** [comment]
How did you manage to point airbyte towards your forked repo? I am also trying to do something similar

**Comment by aaronsteers** [comment]
Closing as stale/blocked. Unfortunately we do not have a path forward for the `pendulum` package. My comments here explain in detail where the blockers are and some options to move forward:

- https://github.com/airbytehq/airbyte/pull/47266#issuecomment-2442310282

There does appear to be a path forward for `jsonschema`, which we are exploring here:

- https://github.com/airbytehq/airbyte-python-cdk/pull/68

Please watch and/or comment/upvote on this issue for future updates regarding the replacement of `Pendulum` with another option:

https://github.com/airbytehq/airbyte-python-cdk/issues/69

**Pull request closed without merging**
