### PR TITLE
Update bigcommerce CDK dependency

### PR DESCRIPTION
**Pull request by erohmensing**
separating out from other pr

### CODE REVIEW

**Review by girarda — APPROVED** [review]

**Comment by erohmensing** [comment]
Not sure what's going on here. Asked GL, going to see if this test would succeed if i checkout master before the PR to revert the CDK - though I doubt it because I don't think that was in when they ran on the other PR

**Comment by erohmensing** [comment]
Can reproduce the failure locally on latest master and on the commit pre-revert: [`9cc3005`](https://github.com/airbytehq/airbyte/commit/9cc30059f6f374769089042eb9dbabce2d76cb74)

**Comment by erohmensing** [comment]
Seems to also fail on [`25b0e7ae`](https://github.com/airbytehq/airbyte/commit/25b0e7ae4215d104aea50bf7bcbdb312562af1e8), which is the commit where the changes were merged to.

**Comment by erohmensing** [comment]
According to [this comment[(https://github.com/airbytehq/airbyte/pull/20090#issuecomment-1352358134) it seems the failure is known about and currently failing, so I'll ignore it and move forward with publishing

**Comment by erohmensing** [comment]
/publish connector=connectors/source-bigcommerce run-tests=false

**Pull request merged**
