### PR TITLE
RFC: add final to local variables, params, and fields

### PR DESCRIPTION
**Pull request by cgardens**
## What
* **One time**: Make local variables, method params, and class fields final if possible. This is done using the Intellij code clean up functionality. 
* Unfortunately, I can't find a code formatter for gradle that will do this as part of our build, so I'm just doing it manually now. There are linters that we could use that will warn in these cases (and we could fail a build on it) but i'm reticent to go in that direction. My thought here is that we should not block builds on style issues that can't be automatically fixed as part of the build system.
* My read is that our team is in one of two camps: "i would like finals camp" (me) or "i don't really care don't make my life harder". So in thinking of a solution, my goal is to add any extra friction to those who don't care while still getting finals where I can for those who do.
* Here's what I propose going forward:
    * Charles (or whoever cares) periodically runs an Intellij code clean up to add the finals.
    * Add to onboarding docs instructions on how to set up save actions that will add these finals automatically. This will be encouraged but not required.
    * Never block build passing on missing final.

@tuliren @jrhizor  thoughts?

### CODE REVIEW

**Comment by sherifnada** [comment]
what is the motivation for enforcing this across the codebase? IMO `final` decreases readability while also not guaranteeing immutability. Preventing reassignment is nice I suppose but IMO the cost isn't worth it.

**Comment by tuliren** [comment]
> what is the motivation for enforcing this across the codebase? IMO `final` decreases readability while also not guaranteeing immutability. Preventing reassignment is nice I suppose but IMO the cost isn't worth it.

Second on this that `final` reduces readability. When we enforce it, it is everywhere and feels like a code pollution.

**Comment by jrhizor** [comment]
I don't have a strong preference here. Agree that it's better to use `final` in principle but it's just slightly worse for readability. Maybe could adopt Project Lombok's Kotlin-esque `val` for local variables and only add final for arguments?

**Comment by sherifnada** [comment]
@cgardens should we close this or do you still want to discuss?

**Comment by cgardens** [comment]
I want to discuss it, I'm just mulling over the most persuasive argument I can make 😆

**Comment by tuliren** [comment]
> I want to discuss it, I'm just mulling over the most persuasive argument I can make 😆

Do you want to do it in dev meeting?

**Comment by cgardens** [comment]
@tuliren all right! yes. let's schedule it for the dev meeting. we will see how persuasive i can be! give me a heads up for when it is so i can take a little time to prepare.

**Comment by tuliren** [comment]
> @tuliren all right! yes. let's schedule it for the dev meeting. we will see how persuasive i can be! give me a heads up for when it is so i can take a little time to prepare.

I have added it to next week's dev meeting.

**Comment by cgardens** [comment]
this was done in a separate PR.

**Pull request closed without merging**
