### PR TITLE
CI: Skip connector test and format on markdown only changes

### PR DESCRIPTION
**Pull request by bnchrch**
## Problem
based on approve-and-merge reason from @girarda  in: https://github.com/airbytehq/airbyte/pull/31593#issuecomment-1769572527

ci was skipped because we were running it on a docs only pr

## Solution
have format and connector test skip when the PR is markdown only

### CODE REVIEW

**Review by evantahler — COMMENTED** [review]
I think I want formatting to run on markdown files.  They are a mess right now, and we often mess up tables.  Can we leave this, but make formatting fast?

**Review by erohmensing — APPROVED** [review]
TIL we don't have a formatter/linter for markdown! In any case it would probably be our docs build that would want to enforce fixing any warnings/failing on errors, not this, so 👍🏻

**Comment by bnchrch** [comment]
@evantahler I agree we should be formatting markdown!

But are we currently? Im not aware of any tool doing that atm

**Comment by bnchrch** [comment]
If we arent currently formatting markdown then I think this is a good quick solution to reduce the usage of approve and merge

**Comment by evantahler** [comment]
> If we arent currently formatting markdown then I think this is a good quick solution to reduce the usage of approve and merge
 
Fair!

**Review by evantahler — APPROVED** [review]

**Pull request merged**
