### PR TITLE
[airbyte-cdk] Fix dpath.util.* deprecation warnings

### PR DESCRIPTION
**Pull request by natikgadzhi**
## What

Fixes the new Dpath deprecation warnings when using `dpath.util.*` by replacing all invocations with `dpath.*`.

This should not have any impact on functionality and compatibility. This should not require a version bump on it's own.

## How
Search and replace `dpath.util.` with `dpath.`. This fixes approximately 1100 test warnings. There are 1300 more warnings, I'll see if I can fix them.

## Can this PR be safely reverted and rolled back?
- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by natikgadzhi** [comment]
Applying formatters now. Since this is a chore and merely a rename, I will ignore mypy checks.

**Review by aaronsteers — APPROVED** [review]
Looks good!

**Pull request merged**
