### PR TITLE
🐛 Source MySQL/MsSQL Disable index logging for MySQL

### LINKED ISSUE #25660: Connector Issue: MySQL connector raises SELECT command denied error in version 2.0.18/2.0.19 but not in 2.0.17
### Connector Name

airbyte/source-mysql

### Connector Version

2.0.18 and 2.0.19

### What step the error happened?

During the sync

### Revelant information

After upgrading the mysql connector version from 2.0.17 to 2.0.18, we encountered a `SELECT command denied` error. Upgrading to the latest version (2.0.19) did nothing, but when I downgrade the connector to version 2.0.17 it worked again. 

### Relevant log output

```shell
java.sql.SQLSyntaxErrorException: SELECT command denied to user 'USERNAME'@'IPADDRESS' for table 'TABLENAME'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
	at com.mysql.cj.jdbc.DatabaseMetaData$6.forEach(DatabaseMetaData.java:2745)
	at com.mysql.cj.jdbc.DatabaseMetaData$6.forEach(DatabaseMetaData.java:2732)
	at com.mysql.cj.jdbc.IterateBlock.doForAll(IterateBlock.java:56)
	at com.mysql.cj.jdbc.DatabaseMetaData.getIndexInfo(DatabaseMetaData.java:2802)
	at com.zaxxer.hikari.pool.ProxyDatabaseMetaData.getIndexInfo(ProxyDatabaseMetaData.java:207)
	at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getIndexInfo(HikariProxyDatabaseMetaData.java)
	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.logPreSyncDebugData(AbstractJdbcSource.java:451)
	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.logPreSyncDebugData(AbstractJdbcSource.java:86)
	at io.airbyte.integrations.source.relationaldb.AbstractDbSource.read(AbstractDbSource.java:147)
	at io.airbyte.integrations.base.ssh.SshWrappedSource.read(SshWrappedSource.java:74)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:141)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:101)
	at io.airbyte.integrations.source.mysql.MySqlSource.main(MySqlSource.java:388)
```

### Contribute

- [ ] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by akashkulk**
Context : https://github.com/airbytehq/airbyte/pull/25729#issuecomment-1530517374

Disable this until we have RCA. Re-opening https://github.com/airbytehq/airbyte/pull/25740#issue-1691554535, Closes https://github.com/airbytehq/airbyte/issues/25660

### CODE REVIEW

**Review by prateekmukhedkar — APPROVED** [review]
Approving. Don't we want to publish source-postgres also?

**Comment by akashkulk** [comment]
> Approving. Don't we want to publish source-postgres also?

There isn't any logical change in `source-postgres` here. I'm actually just removing the common logging and moving it into Postgres override. AFAIK in the dashboards, we are only seeing errors in `source-mysql`.

My preference is to keep the `source-postgres` logging as it's been useful in helping customers identify issues with their indexes, debugging slow queries, etc

**Comment by akashkulk** [comment]
/publish connector=connectors/source-mysql-strict-encrypt run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-mssql-strict-encrypt run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-mysql-strict-encrypt run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-mssql-strict-encrypt run-tests=false

**Pull request merged**
