### PR TITLE
Reorganize CDK documentation directory structure to be less nested

### PR DESCRIPTION
**Pull request by avaidyanatha**
## Main Changes
- The initial structure of the CDK docs was very nested and was very difficult to walk through, this moves the CDK docs up a level and removes an unnecessary level of nesting, which should address the problem overall.

### CODE REVIEW

**Comment by johnlafleur** [comment]
I don't understand why we have "Connector Development Kit (Python)" at the root, and then a dedicated level "Python CDK Tutorial" under tutorial. Aren't we already within a root (Python) level. It feels like the "Python CDK Tutorial" level is not needed. That is unless the root will change to "Connector Development Kit" and we'll have several tutorials.

**Comment by avaidyanatha** [comment]
> I don't understand why we have "Connector Development Kit (Python)" at the root, and then a dedicated level "Python CDK Tutorial" under tutorial. Aren't we already within a root (Python) level? It feels like the "Python CDK Tutorial" level is not needed. That is unless the root will change to "Connector Development Kit" and we'll have several tutorials.

Fair point @johnlafleur. My only thought is that we are likely going to have multiple tutorials for the Python CDK. So we'll need levels for each individual tutorial - would it be sufficient to rename it to "Creating a HTTP Source with the Python CDK"?

**Comment by johnlafleur** [comment]
> > I don't understand why we have "Connector Development Kit (Python)" at the root, and then a dedicated level "Python CDK Tutorial" under tutorial. Aren't we already within a root (Python) level? It feels like the "Python CDK Tutorial" level is not needed. That is unless the root will change to "Connector Development Kit" and we'll have several tutorials.
> 
> Fair point @johnlafleur. My only thought is that we are likely going to have multiple tutorials for the Python CDK. So we'll need levels for each individual tutorial - would it be sufficient to rename it to "Creating a HTTP Source"?

Ok, that works!

**Comment by avaidyanatha** [comment]
> > > I don't understand why we have "Connector Development Kit (Python)" at the root, and then a dedicated level "Python CDK Tutorial" under tutorial. Aren't we already within a root (Python) level? It feels like the "Python CDK Tutorial" level is not needed. That is unless the root will change to "Connector Development Kit" and we'll have several tutorials.
> > 
> > 
> > Fair point @johnlafleur. My only thought is that we are likely going to have multiple tutorials for the Python CDK. So we'll need levels for each individual tutorial - would it be sufficient to rename it to "Creating a HTTP Source"?
> 
> Ok, that works!

Done!

**Review by sherifnada — APPROVED** [review]

**Pull request merged**
