### PR TITLE
🐛 📝 actually fix postgres standby error message by using the latest CDK

### LINKED ISSUE #31357: Update Postgres standby error message to point towards correct link
Context : https://airbytehq-team.slack.com/archives/C043JHEEYKG/p1697069687329289

We have an error message which reads : Failure reason: We're having issues syncing from a Postgres replica that is configured as a hot standby server. Please see https://docs.airbyte.com/integrations/sources/postgres/#sync-data-from-postgres-hot-standby-server for options and workarounds

However, this link is now stale. We should update it to point to : https://docs.airbyte.com/integrations/sources/postgres/postgres-troubleshooting#sync-data-from-postgres-hot-standby-server

Better yet : We can change links for source connectors from https://docs.airbyte.com/ to a short-url with Airbyte domain. I am checking on bitly credentials

### PR DESCRIPTION
**Pull request by stephane-airbyte**
## What
fixes #31357 (2 of 2)
All postgres connectors should use the CDK version pushed in #31792 
Incidentally, this will also get #31674 into the source postgres connector, allowing the sync to fail when debezeum fails to shutdown properly

## 🚨 User Impact 🚨
no breaking change

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  destination-postgres-strict-encrypt test report (commit [`792c525f44`](https://github.com/airbytehq/airbyte/pull/31804/commits/792c525f44d9500c0b7be0b9d5c695bfd013878e)) - ❌

⏲️  Total pipeline duration: 03mn28s 

| Step                                                      | Result   |
|:----------------------------------------------------------|:---------|
| Build connector tar                                       | ❌       |
| Validate metadata for destination-postgres-strict-encrypt | ✅       |
| Connector version semver check                            | ✅       |
| QA checks                                                 | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sgeneix-31357b/1698253450/792c525f44d9500c0b7be0b9d5c695bfd013878e/destination-postgres-strict-encrypt/0.4.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:792c525f44d9500c0b7be0b9d5c695bfd013878e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-postgres-strict-encrypt test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-postgres test report (commit [`792c525f44`](https://github.com/airbytehq/airbyte/pull/31804/commits/792c525f44d9500c0b7be0b9d5c695bfd013878e)) - ❌

⏲️  Total pipeline duration: 32.92s 

| Step                                       | Result   |
|:-------------------------------------------|:---------|
| Build connector tar                        | ❌       |
| Validate metadata for destination-postgres | ✅       |
| Connector version semver check             | ✅       |
| QA checks                                  | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sgeneix-31357b/1698253450/792c525f44d9500c0b7be0b9d5c695bfd013878e/destination-postgres/0.4.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:792c525f44d9500c0b7be0b9d5c695bfd013878e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-postgres test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`792c525f44`](https://github.com/airbytehq/airbyte/pull/31804/commits/792c525f44d9500c0b7be0b9d5c695bfd013878e)) - ❌

⏲️  Total pipeline duration: 01mn19s 

| Step                                  | Result   |
|:--------------------------------------|:---------|
| Build connector tar                   | ❌       |
| Validate metadata for source-postgres | ✅       |
| Connector version semver check        | ✅       |
| QA checks                             | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sgeneix-31357b/1698253450/792c525f44d9500c0b7be0b9d5c695bfd013878e/source-postgres/3.2.14/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:792c525f44d9500c0b7be0b9d5c695bfd013878e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Review by akashkulk — COMMENTED** [review]
Couple of comments : 
1. We can remove everything related to destination-postgres. 
2. For the commit log for source-postgres, can you add that this also fixes silent failures in debezium, as this is pulling in the changes I made here : https://github.com/airbytehq/airbyte/pull/31674. For this use case, I think it's fine since these are 2 small changes.
3. You'll also have to update this file : https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/CdkImportTest.java

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`4ef58fb04e`](https://github.com/airbytehq/airbyte/pull/31804/commits/4ef58fb04e8d1e3013128450d1cc25c1532d27da)) - ❌

⏲️  Total pipeline duration: 03mn09s 

| Step                                  | Result   |
|:--------------------------------------|:---------|
| Build connector tar                   | ❌       |
| Validate metadata for source-postgres | ✅       |
| Connector version semver check        | ✅       |
| QA checks                             | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sgeneix-31357b/1698256413/4ef58fb04e8d1e3013128450d1cc25c1532d27da/source-postgres/3.2.14/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:4ef58fb04e8d1e3013128450d1cc25c1532d27da)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`bc75716232`](https://github.com/airbytehq/airbyte/pull/31804/commits/bc7571623284eacbe2d2c5997d2b775391ea6a2d)) - ❌

⏲️  Total pipeline duration: 01mn54s 

| Step                                  | Result   |
|:--------------------------------------|:---------|
| Build connector tar                   | ❌       |
| Validate metadata for source-postgres | ✅       |
| Connector version semver check        | ✅       |
| QA checks                             | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sgeneix-31357b/1698256744/bc7571623284eacbe2d2c5997d2b775391ea6a2d/source-postgres/3.2.14/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:bc7571623284eacbe2d2c5997d2b775391ea6a2d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`11dced9fae`](https://github.com/airbytehq/airbyte/pull/31804/commits/11dced9fae16da4d447cdfb639be9f8539b4efee)) - ❌

⏲️  Total pipeline duration: 03mn30s 

| Step                                  | Result   |
|:--------------------------------------|:---------|
| Build connector tar                   | ❌       |
| Validate metadata for source-postgres | ✅       |
| Connector version semver check        | ✅       |
| QA checks                             | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sgeneix-31357b/1698258228/11dced9fae16da4d447cdfb639be9f8539b4efee/source-postgres/3.2.14/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:11dced9fae16da4d447cdfb639be9f8539b4efee)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`85f4db1f39`](https://github.com/airbytehq/airbyte/pull/31804/commits/85f4db1f395bf5c8ecf7031e4a0e288c65fb6bb3)) - ❌

⏲️  Total pipeline duration: 18mn03s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build connector tar                                            | ✅       |
| Java Connector Unit Tests                                      | ❌       |
| Build source-postgres docker image for platform(s) linux/amd64 | ✅       |
| Acceptance tests                                               | ✅       |
| Java Connector Integration Tests                               | ✅       |
| Validate metadata for source-postgres                          | ✅       |
| Connector version semver check                                 | ✅       |
| QA checks                                                      | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sgeneix-31357b/1698260635/85f4db1f395bf5c8ecf7031e4a0e288c65fb6bb3/source-postgres/3.2.14/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:85f4db1f395bf5c8ecf7031e4a0e288c65fb6bb3)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Review by akashkulk — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`ac4ce74474`](https://github.com/airbytehq/airbyte/pull/31804/commits/ac4ce74474822fcd1e7511fd5c4d21129ac6301e)) - ❌

⏲️  Total pipeline duration: 18mn12s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build connector tar                                            | ✅       |
| Java Connector Unit Tests                                      | ❌       |
| Build source-postgres docker image for platform(s) linux/amd64 | ✅       |
| Acceptance tests                                               | ✅       |
| Java Connector Integration Tests                               | ✅       |
| Validate metadata for source-postgres                          | ✅       |
| Connector version semver check                                 | ✅       |
| QA checks                                                      | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sgeneix-31357b/1698265947/ac4ce74474822fcd1e7511fd5c4d21129ac6301e/source-postgres/3.2.14/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ac4ce74474822fcd1e7511fd5c4d21129ac6301e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`d4f9e9dcad`](https://github.com/airbytehq/airbyte/pull/31804/commits/d4f9e9dcad5b9a4e5522ac88b79ad84ab6fc77d1)) - ✅

⏲️  Total pipeline duration: 18mn14s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build connector tar                                            | ✅       |
| Java Connector Unit Tests                                      | ✅       |
| Build source-postgres docker image for platform(s) linux/amd64 | ✅       |
| Acceptance tests                                               | ✅       |
| Java Connector Integration Tests                               | ✅       |
| Validate metadata for source-postgres                          | ✅       |
| Connector version semver check                                 | ✅       |
| QA checks                                                      | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sgeneix-31357b/1698270110/d4f9e9dcad5b9a4e5522ac88b79ad84ab6fc77d1/source-postgres/3.2.14/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d4f9e9dcad5b9a4e5522ac88b79ad84ab6fc77d1)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Pull request merged**
