### PR TITLE
🎉 New Source: Brevo [low-code cdk]

### PR DESCRIPTION
**Pull request by mickaelandrieu**
## What

As Sendinblue is renamed Brevo, we should create a new source for the people who want to migrate right now.

## How

I've checked and until now, the REST api endpoints are similar except for the change of domain name (from sendinblue to brevo).

So it was just about renaming and everything works as expected.

## Recommended reading order
1. `schemas/*.json`
2. `manifest.yaml`

## 🚨 User Impact 🚨

No changes, it's a new connector. I'd say we should add a note into the SendingBlue connector documentation about Brevo ASAP.

## Pre-merge Actions

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

**As a note**: it's my first contribution and I don't know how to test or improve my work but I'm willing to learn. We need more documentation on how to create, test and contribute a new connector 🙏 As a former web developer, I may be able to maintain most of the "REST HTTP based" connectors once I'm aware how to do it 🙂

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi everyone, do I need to do something here ?

**Comment by marcosmarxm** [comment]
> As Sendinblue is renamed Brevo, we should create a new source for the people who want to migrate right now.

@mickaelandrieu why not rename the connector and change the endpoint? Whats the point to keep Sendinblue connector?

**Comment by marcosmarxm** [comment]
The old endpoint still works for Sendinblue?

> I don't know about how you manage BC breaks but when I update a connector, I expect it to work, not to break.

If its a breaking change it is expected to break. I'm asking to check if the previous endpoint doesn't work anymore we can already update the connector to become Brevo.

**Comment by mickaelandrieu** [comment]
The endpoint is still working but a developer from Brevo was not allowed to tell me until then.

**Comment by marcosmarxm** [comment]
Hello @mickaelandrieu I discussed this with the team and it is better to migrate the existing connector to be called Brevo (Sendinblue) and made the changes to use the new endpoints. Adding a new connector will duplicate code and maintenance. For this reason I'm closing this contribution, you're welcome to submit as a change to the existing connector and make a breaking change. Also this path will make easier to people already using Sendinblue where they don't need to create new connections and only update to use the new endpoints.
You're welcome to submit the change to the existing connector, thanks for all the effort.

**Pull request closed without merging**
