### PR TITLE
Increase `source-faker` Resource Requirements

### PR DESCRIPTION
**Pull request by evantahler**
Now that Faker can take advantage of multiple cores to be faster (https://github.com/airbytehq/airbyte/pull/20741) we want to ensure that it gets the resources it needs!

This PR updates the CPU limit and Request for Faker to match the default parallelism of 4 processes. 

---

I'm having trouble testing this.  I can see my changes reflected in my local actor catalog, but we [log out](https://github.com/airbytehq/airbyte/blob/a28f93747ffb7c8ad9e30a4a90ceada9d0d7dc0e/airbyte-commons-worker/src/main/java/io/airbyte/workers/process/DockerProcessFactory.java#L120) that the container was launched without the changes:

```
airbyte-worker | 2023-01-03 17:21:58 INFO i.a.w.p.DockerProcessFactory(create):120 - Creating docker container = source-faker-read-54-0-wlfev with resources io.airbyte.config.ResourceRequirements@673d0a42[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=]
```

Screenshot 2023-01-03 at 9 23 46 AM

### CODE REVIEW

**Comment by evantahler** [comment]
A question for reviewers:  Do I need to make these same changes to the resource_requirements in airbyte_cloud, or will this information be copied over?

cc @pedroslopez perhaps?

**Review by colesnodgrass — APPROVED** [review]

**Comment by pedroslopez** [comment]
> A question for reviewers: Do I need to make these same changes to the resource_requirements in airbyte-cloud, or will this information be copied over?

Nope - this will be used by the cloud definitions as long as cloud is not overriding it in the masks.

**Review by pedroslopez — APPROVED** [review]
LGTM, though not sure why the acceptance tests are failing on this branch

**Comment by evantahler** [comment]
Still trying to validate if this it working, I got Airbyte running locally on K8s:

`docker stats` seems to show the source using lots of CPU:

```
7a59916bcb59   k8s_main_source-faker-read-2-0-dkkjw_default_cf3bfdd4-e34e-4bf8-a9b7-619310a6ac43_0                                                             346.42%   133.5MiB / 17.55GiB   0.74%     0B / 0B   258kB / 3.29MB   12
```

But there are no resource settings in the local pod config for the source:

```
(snip)

spec:
  containers:
  - command:
    - sh
    (snip)
      exit $EXIT_STATUS
    env:
    - name: DEPLOYMENT_MODE
      value: OSS
    - name: USE_STREAM_CAPABLE_STATE
      value: "true"
    - name: WORKER_ENVIRONMENT
      value: KUBERNETES
    - name: AIRBYTE_ROLE
    - name: WORKER_JOB_ATTEMPT
      value: "0"
    - name: WORKER_CONNECTOR_IMAGE
      value: airbyte/source-faker:dev
    - name: AUTO_DETECT_SCHEMA
      value: "false"
    - name: AIRBYTE_VERSION
      value: dev
    - name: WORKER_JOB_ID
      value: "2"
    image: airbyte/source-faker:dev
    imagePullPolicy: IfNotPresent
    name: main
    resources: {} # <-- HERE
(snip)
```

Is this expected?

**Comment by evantahler** [comment]
Screenshot 2023-01-05 at 3 12 42 PM

Looking at the temporal job arguments, it doesn't seem to be getting enqueued with resourceRequirements

**Comment by evantahler** [comment]
Screenshot 2023-01-05 at 3 40 33 PM
It is might be that this change isn't needed... now that we give 3 CPUs to every source by default

**Comment by evantahler** [comment]
I have been unable to test this.
@davinchia should I yolo this into master, or give up for now?

**Comment by davinchia** [comment]
There is some confusion here and I have not been able to get to the bottom of this - if this isn't urgent, let's hold off for now!

**Comment by evantahler** [comment]
This is not urgent!  Would it be helpful to merge this in so there's something to test with on `master`?

**Comment by evantahler** [comment]
@davinchia - any thoughts on if this is safe to YOLO into cloud?

**Comment by davinchia** [comment]
Hmm, still haven't yet confirmed this works. However, should be safe to YOLO!

**Comment by evantahler** [comment]
giphy

**Pull request merged**
