### PR TITLE
Turn off default httpavailabilitystrategy for source-marketo (GA)

### PR DESCRIPTION
**Pull request by erohmensing**
See https://github.com/airbytehq/airbyte/pull/21888 for description

### CODE REVIEW

**Review by evantahler — APPROVED** [review]

**Comment by erohmensing** [comment]
Same failure as in [#connector-health](https://airbytehq-team.slack.com/archives/C02TYE9QL9M/p1674824837998149)

**Comment by evantahler** [comment]
Then I think it's probably OK to merge

**Comment by erohmensing** [comment]
Thanks, will do. Double-checking all others for which this is the case and posting those as well!

**Comment by erohmensing** [comment]
Apparently this version was published 11 days ago without a changelog, coming back to look into it

**Comment by erohmensing** [comment]
It was released off of this PR that was never merged: https://github.com/airbytehq/airbyte/pull/20973. Seems to have been published by a contributor while skipping the tests

**Comment by erohmensing** [comment]
If I try to push a new version of the connector, I'd essentially be undoing the changes from this PR for the latest version of the connector published. That would affect OSS users who upgraded to this version because they were seeing the issue linked in that PR. 

However, cloud is still seeing 0.1.11, since the cloud catalog was never updated, since the PR was merged. Therefore cloud users should see no effects of going from 0.1.11 to 0.1.13. Users who want 0.1.12 in OSS can still use that version as they see fit, and then when that PR is merged, the changes will be reflected in 0.1.14 (or whatever version is next when it goes in) for both cloud and OSS users. Does that sound good @evantahler? 

I suppose I'd add the changelog entry from 0.1.12 too, and make it clear that 0.1.13 reverts those changes

**Comment by evantahler** [comment]
> However, cloud is still seeing 0.1.11, since the cloud catalog was never updated, since the PR was merged. Therefore cloud users should see no effects of going from 0.1.11 to 0.1.13. Users who want 0.1.12 in OSS can still use that version as they see fit, and then when that PR is merged, the changes will be reflected in 0.1.14 (or whatever version is next when it goes in) for both cloud and OSS users. Does that sound good @evantahler?

Yep! Although, it's a shame we got into this position.

Alternatively, you could merge in https://github.com/airbytehq/airbyte/pull/20973 and then merge this after?

**Comment by erohmensing** [comment]
I would, except for the fact that the acceptance tests went from consistently succeeding to consistently failing. I think that PR needs some more work before it goes in 😕 will run tests on that branch

**Comment by erohmensing** [comment]
Actually, now that I think about it, it seems weird that the connector would start failing tests on the #connector-health check since they're built off of master. So maybe that is actually unrelated

**Comment by erohmensing** [comment]
Merged the contributor PR - someone had already released a newer version. Releasing this version should re-introduce the contributor's changes lost in the 1.0.0 version as well as add my changes.

**Pull request merged**
