### PR TITLE
docs(postgres): fix initial time and heartbeat links

### PR DESCRIPTION
**Pull request by hongbo-miao**
## What

Fix Postgres initial time and heartbeat links.

I opened another related pull request at https://github.com/airbytehq/terraform-provider-airbyte/pull/119

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by theyueli — APPROVED** [review]
Thanks for the fix!

**Comment by marcosmarxm** [comment]
@hongbo-miao can you confirm you enabled maintainers to edit your branch/fork?

**Comment by hongbo-miao** [comment]
Hi @marcosmarxm I did and I always check this option 😃
image

**Comment by marcosmarxm** [comment]
Thanks @hongbo-miao the problem we have one check making sure contributions doesn't change protected paths. I'll ask the team to take a look and get this merged asap.

**Comment by marcosmarxm** [comment]
@airbytehq/dev-tooling I need someone to review this contribution. Is this the correct way to update the information inside the `airbyte-ci` metadata file?

**Comment by marcosmarxm** [comment]
Hello your feedback matters a lot to us. Can you spare just 2 minutes to complete a [survey](https://form.typeform.com/to/DOBqejte)? We’re dedicated to making the contributor experience even better, and your input is key to achieving excellence. Thank you for helping us improve!

**Pull request merged**
