### PR TITLE
🎉 New Source: Ringcentral [Low code CDK]

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
*Developing new connector for the source: Ringcentral*

Resolves:
[Ringcentral](https://github.com/airbytehq/DeveloperWeek-Connector-Contest/issues/8)

## How
*Developed using (Configuration Based Source) low-code CDK*

## Recommended reading order
1. `spec.yaml`
2. `manifest.yaml`
3. `schemas/*`

## Tests

<details open><summary><strong>Integration & Acceptance</strong></summary>
Full Test Results

image

</details>

## 🚨 User Impact 🚨
- No breaking changes, Just addition of new source
<details><summary><strong>New Connector: Source Ringcentral</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [x] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

</details>

### CODE REVIEW

**Comment by btkcodedev** [comment]
Ping via Slack for getting credentials
Added every stream available with the free tier,
other team messaging, video, webinar & analytics streams require higher privileges which need a subscription.
Test results - Passed state

image

**Comment by btkcodedev** [comment]
@marcosmarxm Request for review here
And also please add hackathon-developer-week label

**Comment by btkcodedev** [comment]
Little Bump Here :) Due date for the hackathon is 1day away 😅

**Comment by btkcodedev** [comment]
Little Bump Here :) Due date for the hackathon is 1day away 😅
@marcosmarxm @archangelic @sh4sh

**Comment by btkcodedev** [comment]
@marcosmarxm @archangelic @sh4sh
I'd really appreciate a review here.
(Due: 5th May midnight) 😅😅

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
