### PR TITLE
fix(jsonSchemas) fix json schema array traversal when items property not provided

### PR DESCRIPTION
**Pull request by terussell85**
## What
When a connector spec definition includes a type of `array`, but does not include an associated `items` property, the `JsonSchemas` traversal logic attempts to load the node at `items` and dies with the following error:

```
java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.isObject()" because "jsonSchemaNode" is null
```

We first encountered this error when upgrading from 0.30.5-alpha to [v0.39.20-alpha](https://github.com/airbytehq/airbyte/releases/tag/v0.39.20-alpha).  We could not save a new instance of a custom connector due to this error. Upon investigation, it was determined that this logic did not exist previously and our `spec` call returned `type: ["array", "object", "string"]` without an `items` property.

Based on https://json-schema.org/understanding-json-schema/reference/array.html, I believe that `items` is an optional property, however, if `airbyte` wants to treat it as required, we can update the logic to log an error instead of skipping.

Possible resolution to https://github.com/airbytehq/airbyte/issues/13406, https://github.com/airbytehq/airbyte/issues/13015, and https://github.com/airbytehq/airbyte/issues/12862.

## How
Check for the presence of `items` before recursively iterating it.

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

None that are known.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

None of the included checklists felt applicable, but let me know if I need to follow a different one.

### CODE REVIEW

**Review by alafanechere — CHANGES_REQUESTED** [review]
Thank you for opening this PR!
> Based on https://json-schema.org/understanding-json-schema/reference/array.html, I believe that items is an optional property, however, if airbyte wants to treat it as required, we can update the logic to log an error instead of skipping.

@benmoriceau told me we'd prefer not to respect JSON schema spec for this specific use case and make the `items` field not optional. Could you please update the logic to log an error as you suggested?

**Comment by terussell85** [comment]
@alafanechere @benmoriceau Thanks for the added insight.

I've updated the code to mimic similar throwing logic in the `OBJECT_TYPE` case.  This should at least provide a bit clearer error message to users while still maintaining the contract/intent of `SpecFormatTest`.

**Review by cgardens — APPROVED** [review]
Thanks @terussell85 . I think the new version of this PR that fails more explicitly is great! Thanks for the contribution.

**Review by benmoriceau — APPROVED** [review]

**Comment by alafanechere** [comment]
Confirmed that CI checks passed in https://github.com/airbytehq/airbyte/pull/14108

**Review by alafanechere — APPROVED** [review]
I had to reformat the code. I confirm that the CI check passed afterward on https://github.com/airbytehq/airbyte/pull/14108

**Pull request merged**
