### PR TITLE
🎉Source Paypal Transactions: Removed OAuth option

### LINKED ISSUE #15518: Source Paypal Transactions: Remove OAuth option
**Problem**
We prematurely introduced the OAuth authentication method for Paypal Transactions before realizing we need to be formally part of the Paypal Partner Program. We run into this error:

> "You are not authorized to perform 3rd party calls for this API. You need to be part of the PayPal Partner Program for the same. Please reach out to your Partner Manager for more information."

**Desired Outcome**
We should remove this option entirely, and only retain the username / password authentication method.

### PR DESCRIPTION
**Pull request by lazebnyi**
## What
#15518 - Source Paypal Transactions: Remove OAuth option

## How
Shifted `client_id` and `client_secret` fields to top. 
 
## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

</details>

### CODE REVIEW

**Review by bazarnov — APPROVED** [review]

**Review by sherifnada — CHANGES_REQUESTED** [review]
is `client_id` / `client_secret` authentication the equivalent of username/password? I.e: the user can independently obtain it? the param names make it sound like it's an oauth option. 

If yes, then why are we moving this to the top level instead of simply removing the `oneOf` option? Aren't we going to need to add this back in the future once we enter paypal's partner program? why make 2 backwards breaking changes?

**Comment by lazebnyi** [comment]
No, `client_id` / `client_secret` is not the equivalent of username/password. More details - [here](https://developer.paypal.com/docs/platforms/get-started/) 

I think better for UI/UX leave only `client_id` / `client_secret`. We already have logic to support backwards compatibility - [here](https://github.com/airbytehq/airbyte/blob/7779df95c1ee1f04505658cbb2563355ce39af61/airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/source.py#L437), so I think we didn't have problem when we rollback OAuth support.

**Comment by sherifnada** [comment]
@lazebnyi so the idea is that in the future we will re-add the `refresh_token` as needed? 

Also, have you manually verified that a connector created with the previous version in the UI will continue to function when you visit the settings page for that connector? e.g: create connector with old versino, upgrade version, go to that connector's setup page, does it continue to work?

**Comment by sherifnada** [comment]
I guess it seems to me like there is a lot of risks involved in making this backwards breaking change, because it's not just the connector which makes assumptions about the shape. It's the platform too. There is almost no downside to keeping the current structure and just removing one of the `oneOf` options until we have config migrations. Does it make sense why that's the case?

**Comment by lazebnyi** [comment]
@sherifnada Yes, for all combination auth will be work:

**Old config** -  `{"client_id": "client_id", "secret": "secret"}` - Supported

**OAuth config** -  `{"credentials": {"auth_method": "oauth2.0", "client_id": "client_id", "client_secret": "client_secret", "refresh_token": "refresh_token" }}` - Supported

**Private OAuth** -  `{"credentials": {"auth_method": "private_oauth", "client_id": "client_id", "client_secret": "client_secret"}}` - Supported

**New config** - `{"client_id": "client_id", "secret": "secret"}` or `{"client_id": "client_id", "secret": "secret", "refresh_token": "refresh_token"}` - Supported

**Review by sherifnada — APPROVED** [review]

**Review by bazarnov — APPROVED** [review]

**Pull request merged**
