### PR TITLE
:bug: Validate incorrect \n symbols in ssh key

### LINKED ISSUE #7194: Source Postgres: add validation step for SSH keys when has `\n` when creating a source
## Enviroment
- **Airbyte version**:  Cloud
- **Source Connector and version**: airbyte/source-postgres-strict-encrypt | 0.1.0
- **Destination Connector and version**: ~
- **Severity**: Very Low / Low / Medium / **High** / Critical
- **Step where error happened**: Creating a Source

## Current Behavior
I'm trying to create a new Postgres with SSH Key Method and got NPE error. This happens because Airbyte doesnt remove the `\n` from my key.
1. Airbyte should validate using regex and tell me that my keys is incorrect, or;
2. The code should remove the \n and use the right format.

## Logs
```
2021-10-19 20:41:58 ERROR Exception in thread "main" java.lang.NullPointerException
2021-10-19 20:41:58 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.getPrivateKeyPair(SshTunnel.java:237)
2021-10-19 20:41:58 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.openTunnel(SshTunnel.java:267)
2021-10-19 20:41:58 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.<init>(SshTunnel.java:134)
2021-10-19 20:41:58 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.getInstance(SshTunnel.java:185)
2021-10-19 20:41:58 ERROR 	at io.airbyte.integrations.base.ssh.SshTunnel.sshWrap(SshTunnel.java:204)
2021-10-19 20:41:58 ERROR 	at io.airbyte.integrations.base.ssh.SshWrappedSource.check(SshWrappedSource.java:37)
2021-10-19 20:41:58 ERROR 	at io.airbyte.integrations.base.spec_modification.SpecModifyingSource.check(SpecModifyingSource.java:38)
2021-10-19 20:41:58 ERROR 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:102)
2021-10-19 20:41:58 ERROR 	at io.airbyte.integrations.source.postgres.PostgresSourceStrictEncrypt.main(PostgresSourceStrictEncrypt.java:34)
```

Complete logs:
[logs-98e168e0-9318-42f2-9a08-fb28194f1c73-.txt](https://github.com/airbytehq/airbyte/files/7376687/logs-98e168e0-9318-42f2-9a08-fb28194f1c73-.txt)

## Steps to Reproduce
1. Select Postgres connector
2. Set with integration account using SSH Key method
3. Wait error 

## Are you willing to submit a PR?

Remove this with your answer.

### PR DESCRIPTION
**Pull request by sashaNeshcheret**
## What
Previously if ssh key contains \n symbol it was recognized as separate symbols \ and n, and parsing key was incorrect.

## How
Now we validate it and replace it with EOL symbol.

## Recommended reading order
1. `x.java`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>

#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [ ] Documentation updated 
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by andriikorotkov — APPROVED** [review]

**Review by andriikorotkov — APPROVED** [review]

**Comment by sashaNeshcheret** [comment]
/publish connector=connectors/destination-mariadb-columnstore

**Comment by sashaNeshcheret** [comment]
/publish connector=connectors/destination-mssql-strict-encrypt

**Comment by sashaNeshcheret** [comment]
/publish connector=connectors/destination-mysql-strict-encrypt

**Comment by sashaNeshcheret** [comment]
/publish connector=connectors/destination-postgres-strict-encrypt

**Comment by sashaNeshcheret** [comment]
/publish connector=connectors/source-clickhouse-strict-encrypt

**Comment by sashaNeshcheret** [comment]
/publish connector=connectors/destination-mysql-strict-encrypt

**Comment by sashaNeshcheret** [comment]
/publish connector=connectors/destination-postgres-strict-encrypt

**Comment by sashaNeshcheret** [comment]
/publish connector=connectors/destination-mysql-strict-encrypt

**Review by alexandr-shegeda — APPROVED** [review]
LGTM. we can proceed with publishing without airbyte review

**Review by DoNotPanicUA — APPROVED** [review]

**Pull request merged**
