### PR TITLE
Speed up BQ by having 2 queries, and not an OR

### LINKED ISSUE #27923: Destinations V2: `This exceeds the ratio supported by the on-demand pricing model`
V2 Type and Dedupe queries fail on the second batch.  The first write was OK because the table was empty.  Subsequent writes to the final table have this problem.  Maybe the delete statement is jank.  Since we are logging the queries, we can try them out!

```
2023-07-03 17:15:13 destination > ERROR i.a.i.d.b.BigQueryStagingConsumerFactory(lambda$flushBufferFunction$5):280 Failed to flush and commit buffer data into destination's raw table: com.google.cloud.bigquery.BigQueryException: Query exceeded resource limits. This query used 520154 CPU seconds but would charge only 353M Analysis bytes. This exceeds the ratio supported by the on-demand pricing model. Please consider moving this workload to the flat-rate reservation pricing model, which does not have this limit. 520154 CPU seconds were used, and this query must use less than 90300 CPU seconds. at [224:1]
```

Ideas of what to investigate:
* `JSON_TYPE(JSON_QUERY(`_airbyte_data`, '$._ab_cdc_deleted_at')) = 'null'` does not exist in the example queries
* `AND (SAFE_CAST(JSON_VALUE(`_airbyte_data`, '$.height') as STRING) IS NULL)` does not exist in the example queries

### PR DESCRIPTION
**Pull request by evantahler**
Close https://github.com/airbytehq/airbyte/issues/27923, replaces https://github.com/airbytehq/airbyte/pull/27937.  related to https://github.com/airbytehq/typing-and-deduping-sql/pull/19

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery-denormalized test report (commit [`846b928fdc`](https://github.com/airbytehq/airbyte/pull/27981/commits/846b928fdcbc8c6cb3b8fde88731e30115d1f274)) - ✅

⏲️  Total pipeline duration: 18mn16s 

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ✅        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-bigquery-denormalized docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery-denormalized:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_no-or-queries/1688575000/846b928fdcbc8c6cb3b8fde88731e30115d1f274/destination-bigquery-denormalized/1.5.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`846b928fdc`](https://github.com/airbytehq/airbyte/pull/27981/commits/846b928fdcbc8c6cb3b8fde88731e30115d1f274)) - ✅

⏲️  Total pipeline duration: 28mn13s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_no-or-queries/1688575000/846b928fdcbc8c6cb3b8fde88731e30115d1f274/destination-bigquery/1.5.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Review by edgao — APPROVED** [review]
:shipit:

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery-denormalized test report (commit [`846b928fdc`](https://github.com/airbytehq/airbyte/pull/27981/commits/846b928fdcbc8c6cb3b8fde88731e30115d1f274)) - ✅

⏲️  Total pipeline duration: 02mn34s 

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ✅        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-bigquery-denormalized docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery-denormalized:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_no-or-queries/1688579040/846b928fdcbc8c6cb3b8fde88731e30115d1f274/destination-bigquery-denormalized/1.5.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`846b928fdc`](https://github.com/airbytehq/airbyte/pull/27981/commits/846b928fdcbc8c6cb3b8fde88731e30115d1f274)) - ✅

⏲️  Total pipeline duration: 03mn30s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_no-or-queries/1688579040/846b928fdcbc8c6cb3b8fde88731e30115d1f274/destination-bigquery/1.5.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Pull request merged**
