### PR TITLE
BigQuery locations update

### PR DESCRIPTION
**Pull request by ChristopheDuong**
## What
Closes https://github.com/airbytehq/oncall/issues/60

Updates locations names from https://cloud.google.com/bigquery/docs/locations

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@ChristopheDuong can you update from bigquery-denormalized too?

**Review by marcosmarxm — APPROVED** [review]
lgtm :+1:

**Comment by marcosmarxm** [comment]
Don't forget to run `./gradlew airbyte-config:init:processResources` and bump the config files version

**Comment by ChristopheDuong** [comment]
/publish connector=connectors/destination-bigquery-denormalized

**Pull request merged**
