### PR TITLE
Source facebook-marketing: add friendly messages and tests

### PR DESCRIPTION
**Pull request by aldogonzalez8**
## What
- "Error code 1: Please reduce the amount of data you're asking for, then retry your request." -> raises a config error with a humanized error message telling the user they should use smaller batches or unselect problematic fields
- Service temporarily unavailable -> raises a transient error with a humanized error message
- "3018 The start date of the time range cannot be beyond 37 months from the current date" -> raises a config error with a humanized error message

Issues ref:
- https://github.com/airbytehq/oncall/issues/4020
- https://github.com/airbytehq/oncall/issues/3009
- https://github.com/airbytehq/oncall/issues/3857

## How
Add friendly messages to traced_exception handler.

## Review guide

1. `airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/common.py`: add new friendly messages for "reducing fields" and "start date" errors.
2. `airbyte-integrations/connectors/source-facebook-marketing/unit_tests/test_errors.py`: new tests to cover these scenarios.

## User Impact
Users will read friendly errors when sync fails.

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by bazarnov — APPROVED** [review]

**Comment by aldogonzalez8** [comment]
Regression [run](https://github.com/airbytehq/airbyte/actions/runs/10110925157) and [resuls](https://ff4294c98d06475f045edc816a20cc26c2f6d7a5d46ff13fcb075e3-apidata.googleusercontent.com/download/storage/v1/b/airbyte-ci-reports-multi/o/airbyte-ci%2Fconnectors%2Ftest%2Fmanual%2Fmaster%2F1721995554%2F046c4b7bf6697ddab955d7c3a0a4b88efe7ab8f6%2Fsource-facebook-marketing%2F3.3.14%2Foutput.html?jk=AYBlUPAxE7pz0dBVmlLlewNH1Tn1S4hdpRN8ihaLgHfDBEWqyHsxQPnDv_YCOKEZIu1kikKJxKABo6M2nIljcqCg25OF1tMKzOEclQYRedon5MtnGXyEMh6lxyerABNXKSadx1pev3s_WNXv4fIIbDqzqf5UhMKZfnfaWgzYaTkm-tr4Legqyuu0lSQiF_oSrMIy8sJhdepQp644xOVG_0CDeFnN1DyUCTtL9CSFXAGpcqiaJ-jqyKWwA0uaEZbZFEiq884vUn-5jWUFQJZ3kvZDRxTOrB0mKScDKHRK5HcqV1v2KU5Ka774RXyeYBFFzLJjW3Nou556w0rvL5PnJ0DEjadezT91g4eVukydqYVI_3j66j5AXtT35T5FQCN4_gue2ctlbrLfH2Er_2lN6h2BhJufD61nC29KIzGWLVaqBvPmSm2617rc5i2Bt_LGUI4BA6MDMT7kAx5EyTDkMDR_jofVx_R23iTqtUqvwZOQlISZsGl_tWl7gc-wLhXpjhlxrrSDvIgKBJ_NmhE10Tz7qm0b5nXROXed4b3xlAbHHQFursMiTRZChybMEumTXtARJjcce6HYsciOanXKMumu_w_ANp6NvbZ6ZxcknpxdgPadRK8Ay5I9_uAFhaftDAztVuzsAG7zqw_ctv1nfa-blrlVZikWElu3piESdP36lm-mwcaeG1St5dx21IqK6LiFQbgWOnLkxrxkEoLOufH2kOdvXvsylY1lNZ_deM-E-ZXt-pEYZKIZYDBKzOFDn-CriXGWvYg9Bx73wbyvlxwFG9zkRtp_snPZZO9Utzmq17CXCxmQNeFizU7mwCw6O0bX8ZLGJutU7fEUkpgwkfcOsWe5nZI6MbshxLy02Rs1EAruiT64XK0hiwHU6V6MAEI3n3hQCMe_AtOCFSfalKwl6QHPmlRFVgoSZg2XDQMsePLqnIzZHVneFBzLMjIfZAIyANRm5FcAqbBOP-AgByRTCX6xudfiZNlGekAQY2CK9fQnk8XBZSkhi4_ISvEmyS_Q4D9w5LTl6I-ZaeOr3KvO4lf6g8bMDisc-9O9JAXOVHx_sJht8JZP4Q-O1nrkbdepr656NX6XXF-oXTDDCdhbPHzSM4En1YsQkPzXz6aK-lunjAvqRwp0PXHZtwHjLxsngKG23OfXtYihZ_LYDr6-fu8kURXp72sdiJczA7Atqx9BwyDy2XEZkfR7--qxZ9CzQude8NaFgZNkNDnNodb5ZM-kSSpdN5yN3Gee7vHard4dqg2LU3uqMiluuFysyRsDN3XeiFrCNS-2eH1kYzi2wYdBnNAk04ccWp2HbuhPCZgUw-TWV-3xwCvyoJgopOC4QpLxPlrPPxNrJecUcjGkuIKIU3gbLw&isca=1)

image

**Comment by aldogonzalez8** [comment]
A [run](https://github.com/airbytehq/airbyte/actions/runs/10111650272/job/27964017144) an [report](https://ff6c03e141dd2178e777bf9bb83b414dfeca0119de0c8e347d9d3bd-apidata.googleusercontent.com/download/storage/v1/b/airbyte-ci-reports-multi/o/airbyte-ci%2Fconnectors%2Ftest%2Fmanual%2Faldogonzalez8_source_facebook-marketing_8651-humanize-facebook-errors%2F1721998716%2F4d5aa423979b80a69d8a9993b125663ea6f02777%2Fsource-facebook-marketing%2F3.3.15%2Foutput.html?jk=AYBlUPBRf7W4LMh_OsNrauUE3QqebbdWNYAIp1k_3qQxP8UROOlx_cn8l169qB9hadZxDWShYXiL-Zw_HiPNG5TZHPYkL_AH8CehtJrSTw0RmAMUuIxVaUg4z4bYd9KXzDSuiOXB1zz-iNhwPULGChSjuzssPC5UXuSA7-uQCT4LhAl2mBehSFQm5x2P_9bQro41bkGIKPrOlIqSDkOiJI0Vl40SSWGfiVCvOZQDNaO31CDgSpO6k7iu70Er7Pnk_VU_T9YkUT1B9dROGGD34_4hUCIbVVmfYLy8aFY8DQ7u88Rt6k_bOVkT0g7a5TWXosshB5JLlhmf3ZBpPfbuYA83P11XkhhLXQti1ng5uK9pTFJvu1oJx404w3akG1hF09_IBkgKSWjq25ue3FmTRaKGmgN7GYumWQJrBzQmOdZFq4qenPVxNuwdNq5EpgkkDprFCDomPH7S86v-VAOOFAvirs1Y_pZNEvUSBN4l_Fc5FLuF4SR7ZAdUN4JGHv_EzqNN5Au07wDdReI0IH9YqZ6PBU0hvpBC6KmfJgn--Bj11RKBZT6_ygXKO1fV_7loD9o-dHjmwuJstH4Nqj9RU8rTFQFe_G-qvvfPHSdsFws37NYkRMsVXSJK0uOavposIMOfVbMS9Cl1xdMsqV5HfD4rDT1Zg62b54j4ifsQjfs6TTVX3rkvYdnZTAoYtlH0RpP6MBIrFh47FsmZwF7Z-FkQhO8t8_paa-YJ3OKVAA7pEs6W0AM5-T2sDR6w0_CSDTS7nCm7ADgGLJ9yS8IzrrslScpd-nuthiaS0neT3MdSzw0_v7QEHu0UnRsW-p2Ev5DRdfrR0-lxkHtAd4p8SizKPZkyD560qowL2UJJ9658JYalqcR6VXo9li7SWuPiSVHQQK0-nJWu9_8rfyfr9HQrQTIL7EPvmE3BCcWOf2asmTJ1OchsLnn7bO97BEi-H26ECy5gTFeBGWdk8Eg8CYEhJLbq7HaNORLs-CjO2s3TFhQntXe-dwDAbOxtkSeIyI5khB-1tSCTpJX5Th03vaTb5B0mlFgoq7CiDQZei7WGjbC5FAqV0jwJfacZQbZvQ5gpUfanA5YiIW77bFJMN8t9YL7Y2j2tKMraJ133bvPfV7kWDKEFqw6sdgcU8H9MeZQlgreGzKGfLVPQCHRyRrDC7yY77UGtduANAOTS20pw1ZT4wbKpshDFRRwkOF4uA6-352JAzBkbCaqlT55n2Bg-EIH8dHTDVQI5ZWQglRPn7gYxFJ7_olw6bwFWod9DRhAJeWyvZUlGFejMKC6_lULD_awhXYiUx3bcJNm0CEQgj2PEHYx1hgpfcG2BKIYNY71u1V6AdbVM3-AYVY_AzZKEzk9XEy-lCYkQL2RG8bUAHKYV3Zz5SO37GJqGkqyKtwz_PE6oQ_dzchhMuZVkLDLr-yD70ABMquNYZFujkk8CgFJJgxBCzw&isca=1) with all the available streams

image

image

image

image

**Comment by nataliekwong** [comment]
Hi @aldogonzalez8 , I'm seeing the message `"Error code 1: Please reduce the amount of data you're asking for, then retry your request." -> raises a config error with a humanized error message telling the user they should use smaller batches or unselect problematic fields` come up in an active sales engagement [workspace](https://cloud.airbyte.com/workspaces/6c4ae8b2-3098-481d-a07f-5bb43474603f/connections/9930c580-4779-4d3f-ae16-d7691e1fb1cb/timeline): 

Does this message mean there are too many fields being requested across the connection, or within a given stream? These are the parameters being requested for the stream that is surfacing the error, and it's surprising this is the error given the small number of streams.

> Params:  {'level': 'campaign', 'action_breakdowns': '["action_type","action_target_id","action_destination"]', 'action_report_time': 'mixed', 'breakdowns': '["dma"]', 'fields': '["campaign_id"]', 'action_attribution_windows': '["1d_click","7d_click","28d_click","1d_view","7d_view","28d_view"]', 'filtering': '[{"field":"ad.effective_status","operator":"IN","value":"**********"}]', 'time_range': '{"since":"2022-09-01","until":"2022-09-30"}'}

If the user wants to sync all the fields, do you think the following options are equally viable to resolving the issue? 
1) splitting up the connection by stream so less fields in total are being requested 
2) for the stream that is erroring, syncing a subset of the columns in one connection, and creating a second connection with the other fields

Or is one option a better alternative to the other?

**Comment by aldogonzalez8** [comment]
> Hi @aldogonzalez8 , I'm seeing the message `"Error code 1: Please reduce the amount of data you're asking for, then retry your request." -> raises a config error with a humanized error message telling the user they should use smaller batches or unselect problematic fields` come up in an active sales engagement [workspace](https://cloud.airbyte.com/workspaces/6c4ae8b2-3098-481d-a07f-5bb43474603f/connections/9930c580-4779-4d3f-ae16-d7691e1fb1cb/timeline):
> 
> Does this message mean there are too many fields being requested across the connection, or within a given stream? These are the parameters being requested for the stream that is surfacing the error, and it's surprising this is the error given the small number of streams.
> 
> > Params:  {'level': 'campaign', 'action_breakdowns': '["action_type","action_target_id","action_destination"]', 'action_report_time': 'mixed', 'breakdowns': '["dma"]', 'fields': '["campaign_id"]', 'action_attribution_windows': '["1d_click","7d_click","28d_click","1d_view","7d_view","28d_view"]', 'filtering': '[{"field":"ad.effective_status","operator":"IN","value":"**********"}]', 'time_range': '{"since":"2022-09-01","until":"2022-09-30"}'}
> 
> If the user wants to sync all the fields, do you think the following options are equally viable to resolving the issue?
> 
> 1. splitting up the connection by stream so less fields in total are being requested
> 2. for the stream that is erroring, syncing a subset of the columns in one connection, and creating a second connection with the other fields
> 
> Or is one option a better alternative to the other?

Each of these streams is failing, so I think it is possible that even if you split the connection, you will see the problem again. Still, actually, I would try that first as we are not sure what is exactly the problem or how FB API will determine to throw that error (they never told us) but also that was always something possible and still we needed [to have this other change](https://github.com/airbytehq/airbyte/pull/41958). If you still have the error, then I would try to start unselecting fields; I am not sure if this problem is caused by the account asking for too much data or individual call level, but at least now we can try both approaches. Also, can you let us know how it goes? It seems something we can document. 

```
[{
  "failureOrigin" : "source",
  "failureType" : "config_error",
  "internalMessage" : "Please reduce the amount of data you're asking for, then retry your request",
  "externalMessage" : "Please reduce the number of fields requested. Go to the schema tab, select your source, and unselect the fields you do not need.",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 15745281,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/airbyte/integration_code/source_facebook_marketing/api.py\", line 169, in call\n    response = super().call(method, path, params, headers, files, url_override, api_version)\n  File \"/usr/local/lib/python3.10/site-packages/facebook_business/api.py\", line 336, in call\n    raise fb_response.error()\nfacebook_business.exceptions.FacebookRequestError: \n\n  Message: Call was not successful\n  Method:  GET\n  Path:    https://graph.facebook.com/v19.0/act_1452452104821631/insights\n  Params:  {'level': 'campaign', 'action_breakdowns': '[\"action_type\",\"action_target_id\",\"action_destination\"]', 'action_report_time': 'mixed', 'breakdowns': '[]', 'fields': '[\"campaign_id\"]', 'action_attribution_windows': '[\"1d_click\",\"7d_click\",\"28d_click\",\"1d_view\",\"7d_view\",\"28d_view\"]', 'filtering': '[{\"field\":\"ad.effective_status\",\"operator\":\"IN\",\"value\":[\"ACTIVE\",\"ADSET_PAUSED\",\"ARCHIVED\",\"CAMPAIGN_PAUSED\",\"DELETED\",\"DISAPPROVED\",\"IN_PROCESS\",\"PAUSED\",\"PENDING_BILLING_INFO\",\"PENDING_REVIEW\",\"PREAPPROVED\",\"WITH_ISSUES\"]}]', 'time_range': '{\"since\":\"2023-02-16\",\"until\":\"2023-03-17\"}'}\n\n  Status:  500\n  Response:\n    {\n      \"error\": {\n        \"code\": 1,\n        \"message\": \"Please reduce the amount of data you're asking for, then retry your request\"\n      }\n    }\n\n",
  "timestamp" : 1722812145386,
  "streamDescriptor" : {
    "name" : "ads_insights"
  }
}, {
  "failureOrigin" : "source",
  "failureType" : "config_error",
  "internalMessage" : "Please reduce the amount of data you're asking for, then retry your request",
  "externalMessage" : "Please reduce the number of fields requested. Go to the schema tab, select your source, and unselect the fields you do not need.",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 15745281,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/airbyte/integration_code/source_facebook_marketing/api.py\", line 169, in call\n    response = super().call(method, path, params, headers, files, url_override, api_version)\n  File \"/usr/local/lib/python3.10/site-packages/facebook_business/api.py\", line 336, in call\n    raise fb_response.error()\nfacebook_business.exceptions.FacebookRequestError: \n\n  Message: Call was not successful\n  Method:  GET\n  Path:    https://graph.facebook.com/v19.0/act_1452452104821631/insights\n  Params:  {'level': 'campaign', 'action_breakdowns': '[\"action_type\",\"action_target_id\",\"action_destination\"]', 'action_report_time': 'mixed', 'breakdowns': '[\"age\",\"gender\"]', 'fields': '[\"campaign_id\"]', 'action_attribution_windows': '[\"1d_click\",\"7d_click\",\"28d_click\",\"1d_view\",\"7d_view\",\"28d_view\"]', 'filtering': '[{\"field\":\"ad.effective_status\",\"operator\":\"IN\",\"value\":[\"ACTIVE\",\"ADSET_PAUSED\",\"ARCHIVED\",\"CAMPAIGN_PAUSED\",\"DELETED\",\"DISAPPROVED\",\"IN_PROCESS\",\"PAUSED\",\"PENDING_BILLING_INFO\",\"PENDING_REVIEW\",\"PREAPPROVED\",\"WITH_ISSUES\"]}]', 'time_range': '{\"since\":\"2022-07-27\",\"until\":\"2022-08-25\"}'}\n\n  Status:  500\n  Response:\n    {\n      \"error\": {\n        \"code\": 1,\n        \"message\": \"Please reduce the amount of data you're asking for, then retry your request\"\n      }\n    }\n\n",
  "timestamp" : 1722830222742,
  "streamDescriptor" : {
    "name" : "ads_insights_age_and_gender"
  }
}, {
  "failureOrigin" : "source",
  "failureType" : "config_error",
  "internalMessage" : "Please reduce the amount of data you're asking for, then retry your request",
  "externalMessage" : "Please reduce the number of fields requested. Go to the schema tab, select your source, and unselect the fields you do not need.",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 15745281,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/airbyte/integration_code/source_facebook_marketing/api.py\", line 169, in call\n    response = super().call(method, path, params, headers, files, url_override, api_version)\n  File \"/usr/local/lib/python3.10/site-packages/facebook_business/api.py\", line 336, in call\n    raise fb_response.error()\nfacebook_business.exceptions.FacebookRequestError: \n\n  Message: Call was not successful\n  Method:  GET\n  Path:    https://graph.facebook.com/v19.0/act_1452452104821631/insights\n  Params:  {'level': 'campaign', 'action_breakdowns': '[\"action_type\"]', 'action_report_time': 'mixed', 'breakdowns': '[\"publisher_platform\",\"platform_position\",\"impression_device\"]', 'fields': '[\"campaign_id\"]', 'action_attribution_windows': '[\"1d_click\",\"7d_click\",\"28d_click\",\"1d_view\",\"7d_view\",\"28d_view\"]', 'filtering': '[{\"field\":\"ad.effective_status\",\"operator\":\"IN\",\"value\":[\"ACTIVE\",\"ADSET_PAUSED\",\"ARCHIVED\",\"CAMPAIGN_PAUSED\",\"DELETED\",\"DISAPPROVED\",\"IN_PROCESS\",\"PAUSED\",\"PENDING_BILLING_INFO\",\"PENDING_REVIEW\",\"PREAPPROVED\",\"WITH_ISSUES\"]}]', 'time_range': '{\"since\":\"2022-08-01\",\"until\":\"2022-08-30\"}'}\n\n  Status:  500\n  Response:\n    {\n      \"error\": {\n        \"code\": 1,\n        \"message\": \"Please reduce the amount of data you're asking for, then retry your request\"\n      }\n    }\n\n",
  "timestamp" : 1722841570899,
  "streamDescriptor" : {
    "name" : "ads_insights_platform_and_device"
  }
}, {
  "failureOrigin" : "source",
  "failureType" : "config_error",
  "internalMessage" : "Please reduce the amount of data you're asking for, then retry your request",
  "externalMessage" : "Please reduce the number of fields requested. Go to the schema tab, select your source, and unselect the fields you do not need.",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 15745281,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/airbyte/integration_code/source_facebook_marketing/api.py\", line 169, in call\n    response = super().call(method, path, params, headers, files, url_override, api_version)\n  File \"/usr/local/lib/python3.10/site-packages/facebook_business/api.py\", line 336, in call\n    raise fb_response.error()\nfacebook_business.exceptions.FacebookRequestError: \n\n  Message: Call was not successful\n  Method:  GET\n  Path:    https://graph.facebook.com/v19.0/act_1452452104821631/\n  Params:  {'fields': 'id,age,name,owner,tax_id,balance,partner,rf_spec,business,currency,fb_entity,io_number,spend_cap,account_id,user_tasks,is_personal,tax_id_type,timezone_id,amount_spent,business_zip,capabilities,created_time,line_numbers,media_agency,tos_accepted,business_city,business_name,tax_id_status,timezone_name,account_status,business_state,disable_reason,end_advertiser,funding_source,business_street,business_street2,min_daily_budget,user_tos_accepted,is_tax_id_required,end_advertiser_name,business_country_code,failed_delivery_checks,is_direct_deals_enabled,has_migrated_permissions,is_notifications_enabled,timezone_offset_hours_utc,can_create_brand_lift_study,offsite_pixels_tos_accepted,min_campaign_group_spend_cap,extended_credit_invoice_group,is_attribution_spec_system_default,is_in_3ds_authorization_enabled_market'}\n\n  Status:  500\n  Response:\n    {\n      \"error\": {\n        \"code\": 1,\n        \"message\": \"Please reduce the amount of data you're asking for, then retry your request\"\n      }\n    }\n\n",
  "timestamp" : 1722841729743,
  "streamDescriptor" : {
    "name" : "ad_account"
  }
}, {
  "failureOrigin" : "source",
  "failureType" : "config_error",
  "internalMessage" : "Please reduce the amount of data you're asking for, then retry your request",
  "externalMessage" : "Please reduce the number of fields requested. Go to the schema tab, select your source, and unselect the fields you do not need.",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 15745281,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/airbyte/integration_code/source_facebook_marketing/api.py\", line 169, in call\n    response = super().call(method, path, params, headers, files, url_override, api_version)\n  File \"/usr/local/lib/python3.10/site-packages/facebook_business/api.py\", line 336, in call\n    raise fb_response.error()\nfacebook_business.exceptions.FacebookRequestError: \n\n  Message: Call was not successful\n  Method:  GET\n  Path:    https://graph.facebook.com/v19.0/act_1452452104821631/insights\n  Params:  {'level': 'campaign', 'action_breakdowns': '[\"action_type\"]', 'action_report_time': 'mixed', 'breakdowns': '[]', 'fields': '[\"campaign_id\"]', 'action_attribution_windows': '[\"1d_click\",\"7d_click\",\"28d_click\",\"1d_view\",\"7d_view\",\"28d_view\"]', 'filtering': '[{\"field\":\"ad.effective_status\",\"operator\":\"IN\",\"value\":[\"ACTIVE\",\"ADSET_PAUSED\",\"ARCHIVED\",\"CAMPAIGN_PAUSED\",\"DELETED\",\"DISAPPROVED\",\"IN_PROCESS\",\"PAUSED\",\"PENDING_BILLING_INFO\",\"PENDING_REVIEW\",\"PREAPPROVED\",\"WITH_ISSUES\"]}]', 'time_range': '{\"since\":\"2023-05-14\",\"until\":\"2023-06-12\"}'}\n\n  Status:  500\n  Response:\n    {\n      \"error\": {\n        \"code\": 1,\n        \"message\": \"Please reduce the amount of data you're asking for, then retry your request\"\n      }\n    }\n\n",
  "timestamp" : 1722854059554,
  "streamDescriptor" : {
    "name" : "ads_insights_action_type"
  }
}, {
  "failureOrigin" : "source",
  "failureType" : "config_error",
  "internalMessage" : "Please reduce the amount of data you're asking for, then retry your request",
  "externalMessage" : "Please reduce the number of fields requested. Go to the schema tab, select your source, and unselect the fields you do not need.",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 15745281,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/airbyte/integration_code/source_facebook_marketing/api.py\", line 169, in call\n    response = super().call(method, path, params, headers, files, url_override, api_version)\n  File \"/usr/local/lib/python3.10/site-packages/facebook_business/api.py\", line 336, in call\n    raise fb_response.error()\nfacebook_business.exceptions.FacebookRequestError: \n\n  Message: Call was not successful\n  Method:  GET\n  Path:    https://graph.facebook.com/v19.0/act_1452452104821631/insights\n  Params:  {'level': 'campaign', 'action_breakdowns': '[\"action_type\",\"action_target_id\",\"action_destination\"]', 'action_report_time': 'mixed', 'breakdowns': '[\"country\"]', 'fields': '[\"campaign_id\"]', 'action_attribution_windows': '[\"1d_click\",\"7d_click\",\"28d_click\",\"1d_view\",\"7d_view\",\"28d_view\"]', 'filtering': '[{\"field\":\"ad.effective_status\",\"operator\":\"IN\",\"value\":[\"ACTIVE\",\"ADSET_PAUSED\",\"ARCHIVED\",\"CAMPAIGN_PAUSED\",\"DELETED\",\"DISAPPROVED\",\"IN_PROCESS\",\"PAUSED\",\"PENDING_BILLING_INFO\",\"PENDING_REVIEW\",\"PREAPPROVED\",\"WITH_ISSUES\"]}]', 'time_range': '{\"since\":\"2022-10-02\",\"until\":\"2022-10-31\"}'}\n\n  Status:  500\n  Response:\n    {\n      \"error\": {\n        \"code\": 1,\n        \"message\": \"Please reduce the amount of data you're asking for, then retry your request\"\n      }\n    }\n\n",
  "timestamp" : 1722864450408,
  "streamDescriptor" : {
    "name" : "ads_insights_country"
  }
}, {
  "failureOrigin" : "source",
  "failureType" : "config_error",
  "internalMessage" : "Please reduce the amount of data you're asking for, then retry your request",
  "externalMessage" : "Please reduce the number of fields requested. Go to the schema tab, select your source, and unselect the fields you do not need.",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 15745281,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/airbyte/integration_code/source_facebook_marketing/api.py\", line 169, in call\n    response = super().call(method, path, params, headers, files, url_override, api_version)\n  File \"/usr/local/lib/python3.10/site-packages/facebook_business/api.py\", line 336, in call\n    raise fb_response.error()\nfacebook_business.exceptions.FacebookRequestError: \n\n  Message: Call was not successful\n  Method:  GET\n  Path:    https://graph.facebook.com/v19.0/act_1452452104821631/insights\n  Params:  {'level': 'campaign', 'action_breakdowns': '[\"action_type\",\"action_target_id\",\"action_destination\"]', 'action_report_time': 'mixed', 'breakdowns': '[\"region\"]', 'fields': '[\"campaign_id\"]', 'action_attribution_windows': '[\"1d_click\",\"7d_click\",\"28d_click\",\"1d_view\",\"7d_view\",\"28d_view\"]', 'filtering': '[{\"field\":\"ad.effective_status\",\"operator\":\"IN\",\"value\":[\"ACTIVE\",\"ADSET_PAUSED\",\"ARCHIVED\",\"CAMPAIGN_PAUSED\",\"DELETED\",\"DISAPPROVED\",\"IN_PROCESS\",\"PAUSED\",\"PENDING_BILLING_INFO\",\"PENDING_REVIEW\",\"PREAPPROVED\",\"WITH_ISSUES\"]}]', 'time_range': '{\"since\":\"2023-05-24\",\"until\":\"2023-06-22\"}'}\n\n  Status:  500\n  Response:\n    {\n      \"error\": {\n        \"code\": 1,\n        \"message\": \"Please reduce the amount of data you're asking for, then retry your request\"\n      }\n    }\n\n",
  "timestamp" : 1723110040298,
  "streamDescriptor" : {
    "name" : "ads_insights_region"
  }
}, {
  "failureOrigin" : "source",
  "failureType" : "config_error",
  "internalMessage" : "Please reduce the amount of data you're asking for, then retry your request",
  "externalMessage" : "Please reduce the number of fields requested. Go to the schema tab, select your source, and unselect the fields you do not need.",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 15745281,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/airbyte/integration_code/source_facebook_marketing/api.py\", line 169, in call\n    response = super().call(method, path, params, headers, files, url_override, api_version)\n  File \"/usr/local/lib/python3.10/site-packages/facebook_business/api.py\", line 336, in call\n    raise fb_response.error()\nfacebook_business.exceptions.FacebookRequestError: \n\n  Message: Call was not successful\n  Method:  GET\n  Path:    https://graph.facebook.com/v19.0/act_1452452104821631/insights\n  Params:  {'level': 'campaign', 'action_breakdowns': '[\"action_type\",\"action_target_id\",\"action_destination\"]', 'action_report_time': 'mixed', 'breakdowns': '[\"dma\"]', 'fields': '[\"campaign_id\"]', 'action_attribution_windows': '[\"1d_click\",\"7d_click\",\"28d_click\",\"1d_view\",\"7d_view\",\"28d_view\"]', 'filtering': '[{\"field\":\"ad.effective_status\",\"operator\":\"IN\",\"value\":[\"ACTIVE\",\"ADSET_PAUSED\",\"ARCHIVED\",\"CAMPAIGN_PAUSED\",\"DELETED\",\"DISAPPROVED\",\"IN_PROCESS\",\"PAUSED\",\"PENDING_BILLING_INFO\",\"PENDING_REVIEW\",\"PREAPPROVED\",\"WITH_ISSUES\"]}]', 'time_range': '{\"since\":\"2022-09-01\",\"until\":\"2022-09-30\"}'}\n\n  Status:  500\n  Response:\n    {\n      \"error\": {\n        \"code\": 1,\n        \"message\": \"Please reduce the amount of data you're asking for, then retry your request\"\n      }\n    }\n\n",
  "timestamp" : 1723119108845,
  "streamDescriptor" : {
    "name" : "ads_insights_dma"
  }
}, {
  "failureOrigin" : "source",
  "failureType" : "config_error",
  "externalMessage" : "During the sync, the following streams did not sync successfully: ads_insights: AirbyteTracedException(\"Please reduce the amount of data you're asking for, then retry your request\")\nads_insights_age_and_gender: AirbyteTracedException(\"Please reduce the amount of data you're asking for, then retry your request\")\nads_insights_platform_and_device: AirbyteTracedException(\"Please reduce the amount of data you're asking for, then retry your request\")\nad_account: AirbyteTracedException(\"Please reduce the amount of data you're asking for, then retry your request\")\nads_insights_action_type: AirbyteTracedException(\"Please reduce the amount of data you're asking for, then retry your request\")\nads_insights_country: AirbyteTracedException(\"Please reduce the amount of data you're asking for, then retry your request\")\nads_insights_region: AirbyteTracedException(\"Please reduce the amount of data you're asking for, then retry your request\")\nads_insights_dma: AirbyteTracedException(\"Please reduce the amount of data you're asking for, then retry your request\")",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 15745281,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 9, in <module>\n    run()\n  File \"/airbyte/integration_code/source_facebook_marketing/run.py\", line 19, in run\n    launch(source, sys.argv[1:])\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py\", line 235, in launch\n    for message in source_entrypoint.run(parsed_args):\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py\", line 122, in run\n    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.read(source_spec, config, config_catalog, state))\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py\", line 166, in read\n    for message in self.source.read(self.logger, config, catalog, state):\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py\", line 191, in read\n    raise AirbyteTracedException(message=error_message, failure_type=FailureType.config_error)\nairbyte_cdk.utils.traced_exception.AirbyteTracedException: None\n",
  "timestamp" : 1723119108847
}
]
```

**Pull request merged**
