### PR TITLE
Source: Amazon Seller Partner - Updated Report API version + New reports

### LINKED ISSUE #15539: Source Amazon seller partner: Add support for GET_SALES_AND_TRAFFIC_REPORT
## Tell us about the problem you're trying to solve
Pull report GET_SALES_AND_TRAFFIC_REPORT for Amazon seller partner

### PR DESCRIPTION
**Pull request by krisjan-oldekamp**
## What

Fixed #15539 

### Updated Amazon Seller Reports API verison

Updated version to version 2020-09-04 to 2021-06-30. 
- Changes: No decryption necesary anymore + the data return field changed (response is not in the "payload" property anymore, so removed this).
- See https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference

### Updated connector test

The connector assumed that the "Orders" report is available for every account. So it used the "Orders" endpoint to check if authenticated successfully. However this is not the case for Vendor-only accounts within Amazon Seller API. So did an alternative check.
When you enter invalid credentials, this is the error message:

	Exception('Error while refreshing access token: 401 Client Error: Unauthorized for url: https://api.amazon.com/auth/o2/token')"}}

However, when you do have valid credentials, but do not have access to the "Orders" endpoint (since thats not available for Vendor only accounts):

	HTTPError('403 Client Error: Forbidden for url: https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?LastUpdatedAfter=xxxx

So I've added an additional check, that checks if "403 Client Error" is in the the error response, and if so, let the connection test pass.

### Added new reports

- **GET_VENDOR_SALES_REPORT** > Incremental, it has to make a request for every day, otherwise the data is will be aggregated for the requested datarange. Also make sure you have configured the required params in reportOptions and set Period In Days setting to 1 > https://developer-docs.amazon.com/sp-api/docs/report-type-values#vendor-retail-analytics-reports
- **GET_VENDOR_INVENTORY_REPORT** > Full-refresh. Also added a check / data delay param, because data availability SLA is in place (data available after 72 hours) > https://developer-docs.amazon.com/sp-api/docs/report-type-values#vendor-retail-analytics-reports
- **GET_AFN_INVENTORY_DATA** > FBA (Fullfillment by Amazon) Inventory data. Full refresh > https://developer-docs.amazon.com/sp-api/docs/report-type-values#fulfillment-by-amazon-fba-reports
- **GET_AFN_INVENTORY_DATA_BY_COUNTRY** > FBA (Fullfillment by Amazon) Inventory data. Full refresh. Only available in Europe > https://developer-docs.amazon.com/sp-api/docs/report-type-values#fulfillment-by-amazon-fba-reports
- **GET_SALES_AND_TRAFFIC_REPORT** > Incremental. Its has to make a request for every day, otherwise the data is will be aggregated for the requested datarange. The reponse returns two iterables, by date level and by ASIN (= amazon product-id) level. I've selected the ASIN level, so there is no data param in the response, so I've added it manually. >https://developer-docs.amazon.com/sp-api/docs/report-type-values#seller-retail-analytics-reports 

## 🚨 User Impact 🚨
No. API version update does not alter fieldnames etc.

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by sajarin** [comment]
Hi @krisjan-oldekamp thanks for the PR. This PR is part of Airbyte's Community Maintainer program and someone from our community will be assigned to review your PR and help it get merged. Thanks for being patient and thanks for improving this connector.

**Comment by tuanchris** [comment]
Hi @krisjan-oldekamp, can you post the logs of passing integration tests and unit test? I tried running your code locally with Airbyte's credentials and was faced with this error: 
```403 Client Error: Forbidden for url: https://sellingpartnerapi-na.amazon.com/reports/2021-06-30/reports```

@sajarin can you help check with the team to see if they should update the permissions for the new endpionts?

**Comment by krisjan-oldekamp** [comment]
@tuanchris what report are you trying to fetch? The multi-country inventory report is only available in Europe (and I see you're trying to request a report in North America -> https://sellingpartnerapi-**na**.amazon.com/reports/2021-06-30/reports).

[amazon-seller-partner-unit-tests.txt](https://github.com/airbytehq/airbyte/files/9598779/amazon-seller-partner-unit-tests.txt)

**Comment by tuanchris** [comment]
@krisjan-oldekamp Oh that can be the case. I'm testing the new streams that you implemented. Can you share the integration tests passing also?

**Comment by krisjan-oldekamp** [comment]
@tuanchris see logs attached (deleted some of the result data).

Good to know, you need to configure these report options, since some of the parameters are mandatory:

`{`
`"GET_VENDOR_INVENTORY_REPORT": {"reportPeriod": "WEEK", "distributorView": "MANUFACTURING", "sellingProgram": "RETAIL"},`
`"GET_VENDOR_SALES_REPORT": {"reportPeriod": "DAY", "distributorView": "MANUFACTURING", "sellingProgram": "RETAIL"},`
`"GET_SALES_AND_TRAFFIC_REPORT": {"dateGranularity": "DAY", "asinGranularity": "CHILD"}`
`}`
[amazon-seller-partner-integration-tests.txt](https://github.com/airbytehq/airbyte/files/9605771/amazon-seller-partner-integration-tests.txt)

I also commited some small changes, as I encountered these issues today.

**Review by tuanchris — CHANGES_REQUESTED** [review]
Hi @krisjan-oldekamp, I left a minor comment below, please have a look. Can you also: 
- run: `./gradlew :airbyte-integrations:connectors:source-amazon-seller-partner:airbytePythonFormat` and fix some errors? 
- clean up the codes that you commented out 
- I'm not too familiar with the Amazon seller partner API, can you confirm if bumping API version to 2021-06-30 would require users to reconfigure permissions?

**Comment by krisjan-oldekamp** [comment]
@tuanchris 

- I've removed commented out code
- Updated the connection test doc
- I've spend a couple of hours to get the Gradle tests to work(....), but I keep getting errors unrelated to the Amazon Seller Partner source, so could you or somebody else run the format test and pass me the things to fix?

**Comment by tuanchris** [comment]
@krisjan-oldekamp I was able to run it and created a pull request on your branch here https://github.com/stacktonic-com/airbyte/pull/1

**Comment by krisjan-oldekamp** [comment]
@tuanchris Thanks a lot, merged the pull request. And I can confirm users don't have to reconfigure permissions when bumping the API version (I was able to fetch all the reports from the previous and the current version with the same credentials that were created months ago / withouth reconfiguring).

**Comment by tuanchris** [comment]
Thank you @krisjan-oldekamp 
@sajarin good to merge from my end.

**Comment by sajarin** [comment]
@krisjan-oldekamp, not sure I have permission to push to your branch. 

Can you bump the version in the Dockerfile and add a line to the changelog in docs/integrations/sources/amazon-seller-partner.md?

**Comment by krisjan-oldekamp** [comment]
@sajarin Done!

**Comment by krisjan-oldekamp** [comment]
@sajarin hmm, access seems to be related to this issue: https://github.com/community/community/discussions/5634 I;ve added you and octavia-squidington-iii as a maintainer manually, but not sure if this would work (since status in "pending invite")

**Comment by krisjan-oldekamp** [comment]
@sajarin Is it possible for octavia-squidington-iii to accept the invitation or do you see other ways to fix the access issue?

**Review by sajarin — APPROVED** [review]

**Comment by sajarin** [comment]
@krisjan-oldekamp, I think it should be good to merge.

**Comment by sajarin** [comment]
Thanks @krisjan-oldekamp for the PR and @tuanchris for the review!

**Pull request merged**
