### PR TITLE
Source Jira: change wording for description of array fields

### PR DESCRIPTION
**Pull request by alafanechere**
This description for the array fields can be misleading for users: 

>  Comma-separated list of Jira project keys to replicate data for. (e.g. PROJ1, PROJ2) 

Some are filling this field like this:
Screen Shot 2022-03-03 at 17 15 58
But it should be filled like this:
Screen Shot 2022-03-03 at 17 16 41

I received the feedback from [this slack conversation](https://airbytehq-team.slack.com/archives/C01MFR03D5W/p1646138392039319): 

> Hi! Got the exact same issue a while ago. It turned out that I was misled by the text in the config : “Projects - Comma-separated list of Jira project keys to replicate data for. (e.g. PROJ1, PROJ2)“.
> What works is entering the keys of the projects, and validating them one by one, something like this. With commas, it fails

I'm suggesting removing "comma-separated" from the description, but feel free to suggest better wording!

### CODE REVIEW

**Comment by alafanechere** [comment]
@misteryeo I'm curious if we have a common way of describing array fields on other connectors and if it is a kind of feedback you already got.

**Comment by misteryeo** [comment]
@alafanechere haven't seen this feedback come up but curious to dig into the behavior here.

How does the field recognize that you're entering different items in the array? What triggers this separation - is it by pressing the space bar or by separating the different items using a comma?

**Comment by misteryeo** [comment]
I just came across this in our Google Ads source and I'm not seeing the UI resolve the different items separated by commas: 
Airbyte  Sources  Google Ads 2022-03-04 at 1 27 43 PM

**Comment by marcosmarxm** [comment]
> I just came across this in our Google Ads source and I'm not seeing the UI resolve the different items separated by commas: Airbyte Sources Google Ads 2022-03-04 at 1 27 43 PM

This is because this field is a string and the connector code map to a list.
https://github.com/airbytehq/airbyte/blob/754452c2208dd5ff71446a6e3b68de4781e783cd/airbyte-integrations/connectors/source-google-ads/source_google_ads/spec.json#L52-L58

Jira connector use the array data type in the specification
https://github.com/airbytehq/airbyte/blob/754452c2208dd5ff71446a6e3b68de4781e783cd/airbyte-integrations/connectors/source-jira/source_jira/spec.json#L44-L52

**Comment by marcosmarxm** [comment]
> @alafanechere haven't seen this feedback come up but curious to dig into the behavior here.
> 
> How does the field recognize that you're entering different items in the array? What triggers this separation - is it by pressing the space bar or by separating the different items using a comma?

pressing enter, there is an issue complaining you cann't only paste the value from the clipboard.

**Comment by misteryeo** [comment]
@timroes curious to understand your thoughts here. I feel like the UI behavior is not ideal.

There's another issue raised here about the similar challenge: https://github.com/airbytehq/airbyte/issues/8630.

My sense is that the expected behavior here should be:

1. The item becomes defined when I use a 'comma' not a 'space'.
2. If I copy and paste a list of comma separated fields here, the commas automatically separate each individual item.

Does that resonate? I think this is a UI challenge rather than a wording challenge.

**Comment by timroes** [comment]
Usually this input fields will require a press of Enter to create an "item" in the list. There is also no hint for that in the UI while typing and no way of pasting a list already in, that will automatically be separated. Usually an input like this should offer pasting in something that will automatically be separated into tokens by a separator character. I'd say we should still improve the wording here to remove the `comma-separated`, but should also try to improve this UI control to allow for pasting values as well as giving better guidance. I've created https://github.com/airbytehq/airbyte/issues/10985 to track this.

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Array Fields](https://app.harvestr.io/components/0/list/m8eVzxM7k)

**Review by harshithmullapudi — APPROVED** [review]

**Pull request merged**
