### PR TITLE
SAT: check `future_state` only for incremental streams.

### PR DESCRIPTION
**Pull request by grubberr**
Signed-off-by: Sergey Chvalyuk <grubberr@gmail.com>

## What
- in **test_strictness_level="high"** `incremental` block check that all streams in `configured_catalog_path` has to be in `future_state` file. I have improved to check only incremental streams (not all streams)
- add `sleep` for `test_connector_config_path_fixture` test to avoid side-effect when 2 files created with the same `ctime`

## How
*Describe the solution*

### CODE REVIEW

**Review by bazarnov — APPROVED** [review]

**Comment by grubberr** [comment]
@alafanechere Can you please look in this PR?
I have changed code to check abnormal_state file only for streams which support incremental

**Review by alafanechere — APPROVED** [review]
Thank you for this improvement!
Do you know how to publish a new SAT version? Let me know if you want me to publish it.

**Comment by grubberr** [comment]
@alafanechere I have seen in another PRs how to do it, thank you for help

**Comment by grubberr** [comment]
/publish connector=bases/source-acceptance-test auto-bump-version=false

**Pull request merged**
