### PR TITLE
Helm: Remove unused PVCs in Helm Chart

### LINKED ISSUE #12386: Helm: Server workspace volume persistence should be optional
## Tell us about the problem you're trying to solve
In general, Kubernetes (k8s) still handles persistent storage poorly, and many implementations disable PVs and PVCs entirely. Kubernetes really excels at running stateless container workloads. Statefulness in Kubernetes is convoluted at best and most environments prefer offloading this to a managed database provider if possible. In my opinion, the airbyte helm chart should facilitate this pattern (even encourage it).

Right now, the helm chart creates the `RELEASE-NAME-airbyte-data` PVC which is mounted to the server container, and it cannot be disabled.

I found the following indications that this volume is indeed no longer necessary:
- https://github.com/airbytehq/airbyte/pull/5850
- https://github.com/airbytehq/airbyte/pull/4670

## Describe the solution you’d like
We should expose a configuration option `server.persistence.enabled` in the helm chart `values.yaml` to allow disabling the volume creation. It should be set to `true` by default for backwards compatibility.

Edit: Feedback from @alafanechere told me the PVCs are in fact already unused and can be safely removed. That solution works just as well (actually better). See PR.

## Describe the alternative you’ve considered or used
I've created this option and it seems to run fine locally - however **I'd love some advice on what potentials risks there are with running airbyte in this way.**

## Are you willing to submit a PR?
Yes, to follow shortly.

### PR DESCRIPTION
**Pull request by martimors**
## What
Resolves https://github.com/airbytehq/airbyte/issues/12386

## How
After feedback from @alafanechere , turns out the PVCs are completely reduntant already. This PR removes them entirely.

## Recommended reading order
:man_shrugging: 

## 🚨 User Impact 🚨

None afaik.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by dingobar** [comment]
I guess one question that comes to mind is whether or not this warrants a version bump of the helm chart (`version` in `Chart.yaml`)?

**Comment by alafanechere** [comment]
Yes feel free to bump, but as a patch as its not changing the default behavior of the chart. I saw from the issue that you did not succeed in deploying a working Airbyte without the PVC. Is it still the case?

**Comment by dingobar** [comment]
Not the case, works fine afaict! Sorry for the confusion. I'll bump the patch.

**Comment by dingobar** [comment]
Rebased the master branch on this one to resolve some merge conflicts in the helm chart `README.md`. Sorry about the force-pushes, figured we prefer to have a clean git history.

**Review by alafanechere — CHANGES_REQUESTED** [review]
@dingobar, I had a chat with @davinchia . You can completely discard the PVC and it's usage in the chart. The backward compatibility is not required anymore since we remove its usage in the platform since last september.

**Comment by dingobar** [comment]
Hi @alafanechere , Based on your feedback, I've re-done this PR to just removing the PVCs altogether. There are some extra changes to the README.md which were auto-generated by `ci.sh update-docs`, probably someone forgot to run them previously.

I've tested it locally with an S3 -> S3 job, and it works perfectly.

What do you think? Can we merge it?

**Review by alafanechere — APPROVED** [review]
Thank you @dingobar for the modifications!
Ready to merge.

**Pull request merged**
