### PR TITLE
✨ Source Recurly : Migrate Python CDK to Low-code CDK

### PR DESCRIPTION
**Pull request by ariesgun**
## What
Migrate Source Recurlyfrom Python CDK to Low-code CDK.
Fix issue #30920

## How
Developed using (Configuration Based Source) low-code CDK

## Recommended reading order
1. manifest.yaml
2. schemas/*

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions

<summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

Test Summary

image

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Sorry the long delay to get into your contribution. Probably this week or next one the team will start the process. Are you able to run the tests in your local setup? It can speed up a lot the process if you share the integration tests results

**Comment by marcosmarxm** [comment]
@ariesgun is this ready to start the review?

**Comment by ariesgun** [comment]
> @ariesgun is this ready to start the review?

Yeah it is ready.

**Comment by ariesgun** [comment]
> Sorry the long delay to get into your contribution. Probably this week or next one the team will start the process. Are you able to run the tests in your local setup? It can speed up a lot the process if you share the integration tests results

How can I run the integration tests?
Is it this one `docker run --rm -v $(pwd)/secrets:/secrets -v $(pwd)/integration_tests:/integration_tests airbyte/source-recurly:dev read --config /secrets/config.json --catalog /integration_tests/configured_catalog.json`?

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
I made some changes but the connector is not working. Can you share the integration tests or what part you need help?

**Comment by ariesgun** [comment]
> I made some changes but the connector is not working. Can you share the integration tests or what part you need help?

```
ubuntu@ip-172-31-49-95:~/projects/airbyte/airbyte-integrations/connectors/source-recurly$ docker run --rm -v $(pwd)/secrets:/secrets airbyte/source-recurly:dev check --config /secrets/config.json
{"type": "LOG", "log": {"level": "ERROR", "message": "Encountered an error trying to connect to stream accounts. Error: \n Traceback (most recent call last):\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/checks/check_stream.py\", line 42, in check_connection\n    stream_is_available, reason = availability_strategy.check_availability(stream, logger, source)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py\", line 36, in check_availability\n    stream_slice = get_first_stream_slice(stream)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py\", line 21, in get_first_stream_slice\n    stream.stream_slices(\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py\", line 126, in stream_slices\n    return self.retriever.stream_slices()\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py\", line 348, in stream_slices\n    return self.stream_slicer.stream_slices()\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 140, in stream_slices\n    end_datetime = self._select_best_end_datetime()\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 154, in _select_best_end_datetime\n    return min(self.end_datetime.get_datetime(self.config), now)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/datetime/min_max_datetime.py\", line 58, in get_datetime\n    time = self._parser.parse(str(self.datetime.eval(config, **additional_parameters)), datetime_format)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/datetime/datetime_parser.py\", line 33, in parse\n    parsed_datetime = datetime.datetime.strptime(str(date), format)\n  File \"/usr/local/lib/python3.9/_strptime.py\", line 568, in _strptime_datetime\n    tt, fraction, gmtoff_fraction = _strptime(data_string, format)\n  File \"/usr/local/lib/python3.9/_strptime.py\", line 349, in _strptime\n    raise ValueError(\"time data %r does not match format %r\" %\nValueError: time data \"{{ format_datetime(config.end_time or today_utc(), '%Y-%m-%dT%H:%M:%SZ') }}\" does not match format '%Y-%m-%dT%H:%M:%SZ'\n"}}
{"type": "LOG", "log": {"level": "ERROR", "message": "Check failed"}}
{"type": "CONNECTION_STATUS", "connectionStatus": {"status": "FAILED", "message": "'Unable to connect to stream accounts - time data \"{{ format_datetime(config.end_time or today_utc(), \\'%Y-%m-%dT%H:%M:%SZ\\') }}\" does not match format \\'%Y-%m-%dT%H:%M:%SZ\\''"}}
```

**Comment by ariesgun** [comment]
> > I made some changes but the connector is not working. Can you share the integration tests or what part you need help?
> 
> I got the following error. The timeformat looks okay, don't know why it throws this error
> 
> ```
> ubuntu@ip-172-31-49-95:~/projects/airbyte/airbyte-integrations/connectors/source-recurly$ docker run --rm -v $(pwd)/secrets:/secrets airbyte/source-recurly:dev check --config /secrets/config.json
> {"type": "LOG", "log": {"level": "ERROR", "message": "Encountered an error trying to connect to stream accounts. Error: \n Traceback (most recent call last):\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/checks/check_stream.py\", line 42, in check_connection\n    stream_is_available, reason = availability_strategy.check_availability(stream, logger, source)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py\", line 36, in check_availability\n    stream_slice = get_first_stream_slice(stream)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py\", line 21, in get_first_stream_slice\n    stream.stream_slices(\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py\", line 126, in stream_slices\n    return self.retriever.stream_slices()\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py\", line 348, in stream_slices\n    return self.stream_slicer.stream_slices()\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 140, in stream_slices\n    end_datetime = self._select_best_end_datetime()\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 154, in _select_best_end_datetime\n    return min(self.end_datetime.get_datetime(self.config), now)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/datetime/min_max_datetime.py\", line 58, in get_datetime\n    time = self._parser.parse(str(self.datetime.eval(config, **additional_parameters)), datetime_format)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/datetime/datetime_parser.py\", line 33, in parse\n    parsed_datetime = datetime.datetime.strptime(str(date), format)\n  File \"/usr/local/lib/python3.9/_strptime.py\", line 568, in _strptime_datetime\n    tt, fraction, gmtoff_fraction = _strptime(data_string, format)\n  File \"/usr/local/lib/python3.9/_strptime.py\", line 349, in _strptime\n    raise ValueError(\"time data %r does not match format %r\" %\nValueError: time data \"{{ format_datetime(config.end_time or today_utc(), '%Y-%m-%dT%H:%M:%SZ') }}\" does not match format '%Y-%m-%dT%H:%M:%SZ'\n"}}
> {"type": "LOG", "log": {"level": "ERROR", "message": "Check failed"}}
> {"type": "CONNECTION_STATUS", "connectionStatus": {"status": "FAILED", "message": "'Unable to connect to stream accounts - time data \"{{ format_datetime(config.end_time or today_utc(), \\'%Y-%m-%dT%H:%M:%SZ\\') }}\" does not match format \\'%Y-%m-%dT%H:%M:%SZ\\''"}}
> ```

Okay, I found a way to fix this. 
Now, I encountered these errors when running the acceptance tests.

```
FAILED test_core.py::TestSpec::test_backward_compatibility[inputs0] - connect...
FAILED test_incremental.py::TestIncremental::test_read_sequential_slices[inputs0]
ERROR test_core.py::TestSpec::test_match_expected[inputs0] - pydantic.error_w...
ERROR test_core.py::TestDiscovery::test_backward_compatibility[inputs0] - Ind...
SKIPPED [1] ../app/connector_acceptance_test/tests/test_core.py:728: This tests currently leads to too much failures. We need to fix the connectors at scale first.
== 2 failed, 37 passed, 1 skipped, 72 warnings, 2 errors in 163.61s (0:02:43) ==
```

There is a backward compatibility error.
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

fake_previous_config = SecretDict(******)

    @given(from_schema(remove_date_time_pattern_format(prev_con_spec)))
    @settings(
        max_examples=number_of_configs_to_generate,
        verbosity=Verbosity.verbose,
        suppress_health_check=(HealthCheck.too_slow, HealthCheck.filter_too_much),
    )
    def check_fake_previous_config_against_actual_spec(fake_previous_config):
        if isinstance(fake_previous_config, dict):  # Looks like hypothesis-jsonschema not only generate dict objects...
            fake_previous_config = SecretDict(fake_previous_config)
            filtered_fake_previous_config = {key: value for key, value in fake_previous_config.data.items() if not key.startswith("_")}
            try:
                jsonschema.validate(instance=filtered_fake_previous_config, schema=actual_connector_spec.connectionSpecification)
            except jsonschema.exceptions.ValidationError as err:
>               raise NonBackwardCompatibleError(err, BackwardIncompatibilityContext.SPEC)
E               connector_acceptance_test.utils.backward_compatibility.NonBackwardCompatibleError: BackwardIncompatibilityContext.SPEC - '0000-00-00T00:00:00' does not match '^$|^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$'
E
E               Failed validating 'pattern' in schema['properties']['begin_time']:
E                   {'examples': ['2021-12-01T00:00:00Z'],
E                    'order': 1,
E                    'pattern': '^$|^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$',
E                    'title': 'begin_time',
E                    'type': 'string'}
E
E               On instance['begin_time']:
E                   '0000-00-00T00:00:00'
E               Falsifying example: check_fake_previous_config_against_actual_spec(
E                   fake_previous_config={'api_key': '', 'begin_time': '0000-00-00T00:00:00'},
E               )

/app/connector_acceptance_test/utils/backward_compatibility.py:238: NonBackwardCompatibleError
```
Is there a way to fix this?

Here is the log for the failing incremental test.
```
    async def test_read_sequential_slices(
        self, inputs: IncrementalConfig, connector_config, configured_catalog_for_incremental, docker_runner: ConnectorRunner
    ):
        """
        Incremental test that makes calls to the read method without a state checkpoint. Then we partition the results by stream and
        slice checkpoints.
        Then we make additional read method calls using the state message and verify the correctness of the
        messages in the response.
        """
        if inputs.skip_comprehensive_incremental_tests:
            pytest.skip("Skipping new incremental test based on acceptance-test-config.yml")
            return

        output_1 = await docker_runner.call_read(connector_config, configured_catalog_for_incremental)
        records_1 = filter_output(output_1, type_=Type.RECORD)
        states_1 = filter_output(output_1, type_=Type.STATE)

        # We sometimes have duplicate identical state messages in a stream which we can filter out to speed things up
        unique_state_messages = [message for index, message in enumerate(states_1) if message not in states_1[:index]]

        # Important!

        # There is only a small subset of assertions we can make
        # in the absense of enforcing that all connectors return 3 or more state messages
        # during the first read.

        # To learn more: https://github.com/airbytehq/airbyte/issues/29926
        if len(unique_state_messages) < 3:
            pytest.skip("Skipping test because there are not enough state messages to test with")
            return

        assert records_1, "First Read should produce at least one record"

        # For legacy state format, the final state message contains the final state of all streams. For per-stream state format,
        # the complete final state of streams must be assembled by going through all prior state messages received
        is_per_stream = is_per_stream_state(states_1[-1])

        # To avoid spamming APIs we only test a fraction of batches (10%) and enforce a minimum of 10 tested
        min_batches_to_test = 5
        sample_rate = len(unique_state_messages) // min_batches_to_test

        mutating_stream_name_to_per_stream_state = dict()
        for idx, state_message in enumerate(unique_state_messages):
            assert state_message.type == Type.STATE

            # if first state message, skip
            # this is because we cannot assert if the first state message will result in new records
            # as in this case it is possible for a connector to return an empty state message when it first starts.
            # e.g. if the connector decides it wants to let the caller know that it has started with an empty state.
            if idx == 0:
                continue

            # if last state message, skip
            # this is because we cannot assert if the last state message will result in new records
            # as in this case it is possible for a connector to return a previous state message.
            # e.g. if the connector is using pagination and the last page is only partially full
            if idx == len(unique_state_messages) - 1:
                continue

            # if batching required, and not a sample, skip
            if len(unique_state_messages) >= min_batches_to_test and idx % sample_rate != 0:
                continue

            state_input, mutating_stream_name_to_per_stream_state = self.get_next_state_input(
                state_message, mutating_stream_name_to_per_stream_state, is_per_stream
            )

            output_N = await docker_runner.call_read_with_state(connector_config, configured_catalog_for_incremental, state=state_input)
            records_N = filter_output(output_N, type_=Type.RECORD)
            assert (
                records_N
            ), f"Read {idx + 2} of {len(unique_state_messages)} should produce at least one record.\n\n state: {state_input} \n\n records_{idx + 2}: {records_N}"

            diff = naive_diff_records(records_1, records_N)
>           assert (
                diff
            ), f"Records for subsequent reads with new state should be different.\n\n records_1: {records_1} \n\n state: {state_input} \n\n records_{idx + 2}: {records_N} \n\n diff: {diff}"
E           AssertionError: Records for subsequent reads with new state should be different.
E
...
state: [{'type': 'STREAM', 'stream': {'stream_descriptor': {'name': 'account_notes'}, 'stream_state': {'states': [{'partition': {'parent_id': 'tq6lr5epg7l8', 'parent_slice': {'end_time': '2023-10-25T00:00:00Z', 'start_time': '2023-09-25T17:16:55Z'}}, 'cursor': {'created_at': '2023-10-25T00:00:00Z'}}, {'partition': {'parent_id': 'tpkaae80mhp9', 'parent_slice': {'end_time': '2023-10-25T00:00:00Z', 'start_time': '2023-09-25T17:16:55Z'}}, 'cursor': {'created_at': '2023-10-25T00:00:00Z'}}]}}}]
```
What i noticed is that the state is not complete. It contains the state for the `account_notes` stream while the records contain records from several streams. 

Any suggestion on how to fix this? @marcosmarxm

**Comment by marcosmarxm** [comment]
@ariesgun I'll review during the week. Probably something need to fix in incremental/date slices.

**Comment by marcosmarxm** [comment]
Thanks a lot for the contribution 👋 and sorry the lack of updates. A lot of changes were released after the contribution was made and there is a task force to migrate the remaining python connectors to low-code framework. For that reason I'm closing this contribution as it has a new one resolving all conflicts.

**Pull request closed without merging**
