### PR TITLE
✨ Source Iterable: add userId to applicable streams

### LINKED ISSUE #30854: Add userId to applicable Iterable streams
### What area the feature impact?

Connectors

### Revelant Information

In November 2022, Iterable released the ability to uniquely identify users using an ID field instead of an email address: https://support.iterable.com/hc/en-us/articles/5670417757588-2022-Release-Notes-#userid-based-projects. We should update the schemas for the following streams to pull in `userId` from the Iterable API:
- email_bounce
- email_click
- email_complaint
- email_open
- email_send
- email_send_skip
- email_subscribe
- email_unsubscribe
- events
- list_users

### PR DESCRIPTION
**Pull request by DDynamic**
## What
In November 2022, Iterable released the ability to uniquely identify users using an ID field instead of an email address: https://support.iterable.com/hc/en-us/articles/5670417757588-2022-Release-Notes-#userid-based-projects.
Resolves #30854

## How
We should update the schemas for the applicable streams to pull in userId from the Iterable API.

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks @DDynamic the contribution looks good. It is only introducing a new field doesn't substitute the primary key. It only helps identify the user. I added the contribution to our team backlog and they'll return in a couple days with an update.

**Comment by DDynamic** [comment]
Hey, @marcosmarxm any update on the review timeline?

**Review by askarpets — CHANGES_REQUESTED** [review]
Hi @DDynamic, thanks for submitting your PR!
I left some small comments, however, I wasn't able to find mentions of the `userId` field in [Iterable API docs](https://support.iterable.com/hc/en-us/articles/204780579-API-Overview-and-Sample-Payloads-) for the streams you've updated. Could you please double check if this field is being returned for these streams?

**Comment by DDynamic** [comment]
Hey @askarpets - thanks for the review! I have addressed all of your feedback.

For all of the modified streams, the following endpoint is used: https://api.iterable.com/api/docs#export_exportDataJson.

None of the response fields are documented, but I have an attached an example response below.

Screen Shot 2023-11-17 at 10 46 25 AM

**Comment by DDynamic** [comment]
@askarpets @oustynova bumping when you get a chance. 🙏

**Comment by askarpets** [comment]
@DDynamic sorry for the delay. Everything looks good, approving!

@marcosmarxm please proceed with merge.

Thanks!

**Review by askarpets — APPROVED** [review]

**Comment by marcosmarxm** [comment]
At the moment all tests for Iterable are failing. I'll work to fix them and get the contribution merged.

**Comment by DDynamic** [comment]
@askarpets @marcosmarxm do you need me to take care of conflicts on this? Any luck with getting the tests fixed?

**Pull request merged**
