### PR TITLE
bump e2e connector versions

### PR DESCRIPTION
**Pull request by alovew**
Bump the versions of e2e source and destination connectors

### CODE REVIEW

**Comment by alovew** [comment]
# to run integration tests for the connector
# Example: /test connector=connectors/source-hubspot
/test connector=connectors/source-e2e-test
/test connector=connectors/destination-e2e-test

# to run integration tests, publish the connector, and use the updated connector version in our config/metadata files
# Example: /publish connector=connectors/source-hubspot
/publish connector=connectors/source-e2e-test
/publish connector=connectors/destination-e2e-test

**Review by gosusnp — APPROVED** [review]

**Pull request merged**
