### PR TITLE
Destinations v2: better namespace handling

### PR DESCRIPTION
**Pull request by edgao**
part 1 of https://github.com/airbytehq/airbyte/issues/27581

trying to rip out all the catalog-mangling stuff. Once this is done we should be in a better position to extract all the 1s1t logic into a sharable class.

I've run syncs with all combinations of (gcs vs standard inserts) and (legacy vs 1s1t) successfully.

general idea for standard inserts:
* BigQueryDestination#getConsumer (i.e. entrypoint to `write`) sets the default namespace on streams with null namespace, so the rest of the connector doesn't need to worry about it anymore
* stop overwriting the namespace to `airbyte` on the ConfiguredAirbyteCatalog
* BigQueryDestination#getUploaderMap switches between the 1s1t and legacy target table name (i.e. the raw table name)
* BigQueryUploaderFactory#getUploader switches between using the 1s1t raw table namespace and the legacy namespace

gcs mode is pretty similar:
* `BufferedStreamConsumer` now takes a defaultNamespace and overrides `null` namespaces on record messages
* BigQueryStagingConsumerFactory [passes](https://github.com/airbytehq/airbyte/pull/27682/files#diff-b72ae800333481a6ced0d0507886d8dbb44b8b60766f2ed18bd459c10edfd9c1L170-R148) the original namespace into the writeconfig

# recommended review order
1. BigQueryDestination (this is mostly deleting all the `stream.setNamespace("airbyte")` stuff)
2. Standard inserts:
    1. BigQueryUploaderFactory (now responsible for choosing the raw table dataset ID between 1s1t and legacy)
    2. BigQueryRecordConsumer - now that the `AbstractBigQueryUploader` inherently has the right dataset, we can delete a lot of namespace munging in this class
3. GCS:
    1. BufferedStreamConsumer - stop mangling the catalog, do a better mangle on the record: set the destination default namespace (so that nobody else needs to deal with this) instead of setting `airbyte`
    2. BigQueryStagingConsumerFactory - clean up the namespace munging
4. Everything else - a couple relevant changes to pass around useful values, mixed in with some autoformatting

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`8b1eb950c3`](https://github.com/airbytehq/airbyte/pull/27682/commits/8b1eb950c3c0ef372ce11e0aa249e5eca71c7679)) - ❌

⏲️  Total pipeline duration: 455 seconds

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ✅        |
| QA checks                                                                   | ❌        |
| Build connector tar                                                         | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/edgao_better_namespace_handling/1687819690/8b1eb950c3c0ef372ce11e0aa249e5eca71c7679/destination-bigquery/1.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by jbfbell** [comment]
This looks good to me, I think its ok to merge and fix forward in the destinations-v2 common branch if its just tests that are failing.

**Review by jbfbell — APPROVED** [review]
Love seeing all the deletes

**Comment by edgao** [comment]
for the record: DATs have a ton of failures because we're not initializing the DestinationConfig singleton. These should be pretty easy to fix; we can do that on the common branch. E.g.:
```
#12 210.2 BigQueryDestinationTest > testWritePartitionOverUnpartitioned(String) > io.airbyte.integrations.destination.bigquery.BigQueryDestinationTest.testWritePartitionOverUnpartitioned(String)[2] FAILED
#12 210.2     java.lang.IllegalStateException: Singleton not initialized.
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`9149a5d32d`](https://github.com/airbytehq/airbyte/pull/27682/commits/9149a5d32d7ce3b9f9d2c2b0939a6c1652aab4d6)) - ❌

⏲️  Total pipeline duration: 1124 seconds

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ✅        |
| QA checks                                                                   | ❌        |
| Build connector tar                                                         | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Build airbyte/normalization:dev                                             | ✅        |
| Integration tests                                                           | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/edgao_better_namespace_handling/1687823331/9149a5d32d7ce3b9f9d2c2b0939a6c1652aab4d6/destination-bigquery/1.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Pull request merged**
