### PR TITLE
Java DB Source connector licenses to Elv2

### PR DESCRIPTION
**Pull request by evantahler**
See https://github.com/airbytehq/airbyte/issues/27724

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-snowflake test report (commit [`28e9a01e9b`](https://github.com/airbytehq/airbyte/pull/27737/commits/28e9a01e9be4df683bc9cfd00d99a02e55171aae)) - ❌

⏲️  Total pipeline duration: 707 seconds

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-snowflake/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Build connector tar                                                     | ✅        |
| Build source-snowflake docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Integration tests                                                       | ❌        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-db-sources/1687826494/28e9a01e9be4df683bc9cfd00d99a02e55171aae/source-snowflake/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-snowflake test
```

**Comment by octavia-squidington-iii** [comment]
##  source-bigquery test report (commit [`28e9a01e9b`](https://github.com/airbytehq/airbyte/pull/27737/commits/28e9a01e9be4df683bc9cfd00d99a02e55171aae)) - ✅

⏲️  Total pipeline duration: 1087 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-bigquery/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ✅        |
| QA checks                                                              | ✅        |
| Build connector tar                                                    | ✅        |
| Build source-bigquery docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Integration tests                                                      | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-db-sources/1687826494/28e9a01e9be4df683bc9cfd00d99a02e55171aae/source-bigquery/0.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-bigquery test
```

**Review by rodireich — APPROVED** [review]

**Comment by evantahler** [comment]
Merging in master... I would have expected a lot more tests to have run...

**Comment by evantahler** [comment]
@alafanechere I added you as a reviewer because I'm not really sure what to do since the connector tests aren't running

**Comment by octavia-squidington-iii** [comment]
##  source-mysql test report (commit [`445f3b7838`](https://github.com/airbytehq/airbyte/pull/27737/commits/445f3b78385eb6fc31ab3d93e31fd599dad920cf)) - ❌

⏲️  Total pipeline duration: 1898 seconds

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| Connector version increment check                                   | ✅        |
| QA checks                                                           | ✅        |
| Build connector tar                                                 | ✅        |
| Build source-mysql docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ✅        |
| Integration tests                                                   | ❌        |
| Acceptance tests                                                    | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-db-sources/1687926875/445f3b78385eb6fc31ab3d93e31fd599dad920cf/source-mysql/2.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Comment by octavia-squidington-iii** [comment]
##  source-postgres-strict-encrypt test report (commit [`445f3b7838`](https://github.com/airbytehq/airbyte/pull/27737/commits/445f3b78385eb6fc31ab3d93e31fd599dad920cf)) - ✅

⏲️  Total pipeline duration: 417 seconds

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-db-sources/1687926875/445f3b78385eb6fc31ab3d93e31fd599dad920cf/source-postgres-strict-encrypt/2.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mssql test report (commit [`445f3b7838`](https://github.com/airbytehq/airbyte/pull/27737/commits/445f3b78385eb6fc31ab3d93e31fd599dad920cf)) - ❌

⏲️  Total pipeline duration: 2177 seconds

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mssql/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| Connector version increment check                                   | ✅        |
| QA checks                                                           | ✅        |
| Build connector tar                                                 | ✅        |
| Build source-mssql docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ✅        |
| Integration tests                                                   | ❌        |
| Acceptance tests                                                    | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-db-sources/1687926875/445f3b78385eb6fc31ab3d93e31fd599dad920cf/source-mssql/1.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mssql test
```

**Comment by alafanechere** [comment]
@evantahler the test did run and started on [28e9a01e9b](https://github.com/airbytehq/airbyte/pull/27737/commits/28e9a01e9be4df683bc9cfd00d99a02e55171aae), but the `source-mssql-strict-encrypt` unit tests have a problem and never finish, the [workflow](https://github.com/airbytehq/airbyte/actions/runs/5384352721/jobs/9772169875) was killed after 24H.
When you merged in master with [445f3b7838](https://github.com/airbytehq/airbyte/pull/27737/commits/445f3b78385eb6fc31ab3d93e31fd599dad920cf) the tests [restarted](https://github.com/airbytehq/airbyte/actions/runs/5395120477/jobs/9799082812), other connector were tested before mssql but the workllow is now at mssql again and that will probably block the rest of the connectors test.

When I run: `./gradlew :airbyte-integrations:connectors:source-mssql-strict-encrypt:test` locally the test are indeed stuck at setup... 

To prevent this situation from happening I could declare a fixed timeout to java connectors tests. I did not do it so far globally on tests because we have python connectors that are very long to test due to rate limits (`source-mixpanel` test can run for ~3hours...)

**Comment by alafanechere** [comment]
/legacy-test connector=connectors/source-mssql-strict-encrypt

**Comment by alafanechere** [comment]
@evantahler I think I'm understanding the problem with `source-mssql-strict-encrypt`.
When running `./gradlew :airbyte-integrations:connectors:source-mssql-strict-encrypt:test` the gradle task idles forever, I don't know exactly why. We run the `test` gradle task to run unit tests.
`/test` is running a different gradle task: `integrationTest`.

I originally split unit and integration test for Java connectors by running `test` and `integrationTestJava`. I believe this assumption is not correct for all connectors... 

I'm trying switching  to `integrationTest` only in https://github.com/airbytehq/airbyte/pull/27794

**Comment by octavia-squidington-iii** [comment]
##  source-oracle test report (commit [`2ad90796c9`](https://github.com/airbytehq/airbyte/pull/27737/commits/2ad90796c92e0b564eddbf73929a53d48ab26d0c)) - ❌

⏲️  Total pipeline duration: 287 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-oracle/metadata.yaml     | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Build connector tar                                                      | ✅        |
| Build source-oracle docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-oracle:integrationTest | ❌        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-db-sources/1687976750/2ad90796c92e0b564eddbf73929a53d48ab26d0c/source-oracle/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-oracle test
```

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`2ad90796c9`](https://github.com/airbytehq/airbyte/pull/27737/commits/2ad90796c92e0b564eddbf73929a53d48ab26d0c)) - ✅

⏲️  Total pipeline duration: 715 seconds

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ✅        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ✅        |
| Build source-postgres docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres:integrationTest | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-db-sources/1687976750/2ad90796c92e0b564eddbf73929a53d48ab26d0c/source-postgres/2.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by octavia-squidington-iii** [comment]
##  source-bigquery test report (commit [`2ad90796c9`](https://github.com/airbytehq/airbyte/pull/27737/commits/2ad90796c92e0b564eddbf73929a53d48ab26d0c)) - ✅

⏲️  Total pipeline duration: 772 seconds

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-bigquery/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ✅        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ✅        |
| Build source-bigquery docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-bigquery:integrationTest | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-db-sources/1687976750/2ad90796c92e0b564eddbf73929a53d48ab26d0c/source-bigquery/0.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-bigquery test
```

**Comment by octavia-squidington-iii** [comment]
##  source-snowflake test report (commit [`2ad90796c9`](https://github.com/airbytehq/airbyte/pull/27737/commits/2ad90796c92e0b564eddbf73929a53d48ab26d0c)) - ❌

⏲️  Total pipeline duration: 593 seconds

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-snowflake/metadata.yaml     | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ✅        |
| QA checks                                                                   | ✅        |
| Build connector tar                                                         | ✅        |
| Build source-snowflake docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-snowflake:integrationTest | ❌        |
| Acceptance tests                                                            | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-db-sources/1687976750/2ad90796c92e0b564eddbf73929a53d48ab26d0c/source-snowflake/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-snowflake test
```

**Comment by octavia-squidington-iii** [comment]
##  source-oracle-strict-encrypt test report (commit [`2ad90796c9`](https://github.com/airbytehq/airbyte/pull/27737/commits/2ad90796c92e0b564eddbf73929a53d48ab26d0c)) - ❌

⏲️  Total pipeline duration: 1076 seconds

| Step                                                                                    | Result   |
|:----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-oracle-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                          | ✅        |
| Connector version increment check                                                       | ✅        |
| QA checks                                                                               | ✅        |
| Build connector tar                                                                     | ✅        |
| Build source-oracle-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-oracle-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                        | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-db-sources/1687976750/2ad90796c92e0b564eddbf73929a53d48ab26d0c/source-oracle-strict-encrypt/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-oracle-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-redshift test report (commit [`2ad90796c9`](https://github.com/airbytehq/airbyte/pull/27737/commits/2ad90796c92e0b564eddbf73929a53d48ab26d0c)) - ❌

⏲️  Total pipeline duration: 631 seconds

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-redshift/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ✅        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ✅        |
| Build source-redshift docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-redshift:integrationTest | ✅        |
| Acceptance tests                                                           | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-db-sources/1687976750/2ad90796c92e0b564eddbf73929a53d48ab26d0c/source-redshift/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-redshift test
```

**Comment by octavia-squidington-iii** [comment]
##  source-postgres-strict-encrypt test report (commit [`2ad90796c9`](https://github.com/airbytehq/airbyte/pull/27737/commits/2ad90796c92e0b564eddbf73929a53d48ab26d0c)) - ❌

⏲️  Total pipeline duration: 359 seconds

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                            | ✅        |
| Connector version increment check                                                         | ✅        |
| QA checks                                                                                 | ✅        |
| Build connector tar                                                                       | ✅        |
| Build source-postgres-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres-strict-encrypt:integrationTest | ✅        |
| Acceptance tests                                                                          | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-db-sources/1687976750/2ad90796c92e0b564eddbf73929a53d48ab26d0c/source-postgres-strict-encrypt/2.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mssql test report (commit [`2ad90796c9`](https://github.com/airbytehq/airbyte/pull/27737/commits/2ad90796c92e0b564eddbf73929a53d48ab26d0c)) - ❌

⏲️  Total pipeline duration: 1150 seconds

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mssql/metadata.yaml     | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Build connector tar                                                     | ✅        |
| Build source-mssql docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mssql:integrationTest | ❌        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-db-sources/1687976750/2ad90796c92e0b564eddbf73929a53d48ab26d0c/source-mssql/1.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mssql test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-v2 test report (commit [`2ad90796c9`](https://github.com/airbytehq/airbyte/pull/27737/commits/2ad90796c92e0b564eddbf73929a53d48ab26d0c)) - ❌

⏲️  Total pipeline duration: 652 seconds

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| Connector version increment check                                            | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-v2:integrationTest | ❌        |
| Acceptance tests                                                             | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-db-sources/1687976750/2ad90796c92e0b564eddbf73929a53d48ab26d0c/source-mongodb-v2/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mysql-strict-encrypt test report (commit [`2ad90796c9`](https://github.com/airbytehq/airbyte/pull/27737/commits/2ad90796c92e0b564eddbf73929a53d48ab26d0c)) - ❌

⏲️  Total pipeline duration: 778 seconds

| Step                                                                                   | Result   |
|:---------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                         | ✅        |
| Connector version increment check                                                      | ✅        |
| QA checks                                                                              | ✅        |
| Build connector tar                                                                    | ✅        |
| Build source-mysql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mysql-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-db-sources/1687976750/2ad90796c92e0b564eddbf73929a53d48ab26d0c/source-mysql-strict-encrypt/2.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mysql test report (commit [`2ad90796c9`](https://github.com/airbytehq/airbyte/pull/27737/commits/2ad90796c92e0b564eddbf73929a53d48ab26d0c)) - ❌

⏲️  Total pipeline duration: 982 seconds

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql/metadata.yaml     | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Build connector tar                                                     | ✅        |
| Build source-mysql docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mysql:integrationTest | ❌        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-db-sources/1687976750/2ad90796c92e0b564eddbf73929a53d48ab26d0c/source-mysql/2.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-strict-encrypt test report (commit [`2ad90796c9`](https://github.com/airbytehq/airbyte/pull/27737/commits/2ad90796c92e0b564eddbf73929a53d48ab26d0c)) - ❌

⏲️  Total pipeline duration: 269 seconds

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                           | ✅        |
| Connector version increment check                                                        | ✅        |
| QA checks                                                                                | ❌        |
| Build connector tar                                                                      | ✅        |
| Build source-mongodb-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-db-sources/1687976750/2ad90796c92e0b564eddbf73929a53d48ab26d0c/source-mongodb-strict-encrypt/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-strict-encrypt test
```

**Comment by evantahler** [comment]
I think this is safe to merge!
* Some of the connectors passed all the tests
* There are no failing metadata problems
* There's one QA check failure (`source-mongodb-strict-encrypt`), and I think this is real, but it is the same way on master (source-mongodb-strict-encrypt maps to source-mongodb-v2 for some reason, so the lookup for icons etc doesn't work

**Comment by nataliekwong** [comment]
Hey @evantahler , a community member raised that we don't have a license file in the file or same directory, so it isn't clear that these are now under Elv2. Do you know who could help to add those? (Not sure between Connector Ops/DB Sources?) 

https://github.com/airbytehq/airbyte/issues/31503

**Pull request merged**
