### PR TITLE
Use role-based permissions for source-postgres

### LINKED ISSUE #10649: 🐛  Source Postgres: cannot retrieve all tables accessible to the user
## Environment
- **Airbyte version**:
- **OS Version / Instance**:
- **Deployment**:
- **Source Connector and version**: source postgres 0.4.8
- **Destination Connector and version**:
- **Severity**: Medium
- **Step where error happened**:

## Context
Slack [thread](https://airbytehq-team.slack.com/archives/C01VDDEGL7M/p1645725516903079)

> I’m using the latest 0.4.8 source-postgres source and I have a problem where I’m not able to list any tables in my source even though my user is able to select from the tables.
> I see there are a couple relevant tickets.
> * https://github.com/airbytehq/airbyte/pull/9875
> * https://github.com/airbytehq/airbyte/pull/10173
> I debugged and found that in AbstractJdbcSource.discoverInternal() where it filters tables with `excludeNotAccessibleTables`
> ```java
> protected Predicate<JsonNode> excludeNotAccessibleTables(final Set<String> internalSchemas,
>                                                            final Set<JdbcPrivilegeDto> tablesWithSelectGrantPrivilege) {
> the tablesWithSelectGrantPrivilege variable was empty.
> ```
>
> So because of that it entered this branch:
> ```java
> if (tablesWithSelectGrantPrivilege.isEmpty()) {
>   return isNotInternalSchema(jsonNode, internalSchemas);
> }
> ```
> and the PostgresSource has commented out the isNotInternalSchema() method to always filter out the
> ```java
> @Override
> protected boolean isNotInternalSchema(JsonNode jsonNode, Set<String> internalSchemas) {
>   return false;
> }
> ```
> If the `isNotInternalSchema` wasn’t overriden by postgres then my tables show up properly.
> I’m trying to understand the logic behind this?
> Whether the problem is with `getPrivilegesTableForCurrentUser` or that the `isNotInternalSchema` should not be overridden?
> Can someone shed some light on the philosophy behind how the `AbstractJdbcSource.excludeNotAccessibleTables` is supposed to work and the reasoning behind the
`PostgresSource.isNotInternalSchema` overriding?

Quick diagnosis:
- It looks like `isNotInternalSchema` was a new method introduced between PR #9875 and PR #10173.
- When PR #10173 tried to revert PR #9875, it added the `isNotInternalSchema` with a default implementation without thinking about what it meant.
- This is probably a bug.

### LINKED ISSUE #12635: Failure to discover streams from Postgres source
- Is this your first time deploying Airbyte?: No
- OS Version / Instance: AWS linux 2?
- Memory / Disk: m5n.xlarge
- Deployment: Kubernetes
- Airbyte Version: 0.36.9-alpha & 0.35.49
- Source name/version: Postgres 0.4.12 (also tried 0.4.10)
- Destination name/version: Snowflake 0.4.25
- Step: Connection setup. Sync
- Description: The Postgres source after 0.4.10 is no longer finding tables in my schema. Setting up a source, destination, and connection in an entirely new instance shows no available tables/view streams to sync. Same goes for the discover_schema API endpoint which returns an empty list. The same connection works fine when rolling back to Postgres source 0.4.4.
 [Discourse post]

### PR DESCRIPTION
**Pull request by radostyle**
Modify permissions query to add recursive lookup of role-based
permissions. This solves problems users are having with not being able
to list tables for postgres souces.

Fixes [#10649](https://github.com/airbytehq/airbyte/issues/10649)

## What
This solves problems users are having with not being able to list tables using the source-postgres connector.
The current implementation requires tables to be granted individually to a user.
Using roles is often a better way to manage permissions in postgres and should be supported.
This patch adds support for determining the tables a user has access to based on his role.

## How
The accessible table are currently determined using a postgres query over the roles tables.  This patch adds one more UNION condition to the existing query with a recursive role based query so that the roles work as expected by users.

## Recommended reading order
1. `airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSource.java`

## 🚨 User Impact 🚨
When the user has created a postgres source and any target. The user then goes to create the connection.  When listing the tables to sync under the `Replication` tab.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks for the contribution @radostyle, can you sign the CLA?

**Comment by marcosmarxm** [comment]
Waiting user to sign the CLA. @radostyle ping

**Comment by radostyle** [comment]
I just signed it, but it is not showing signed on the ticket.

**Comment by radostyle** [comment]
There was an issue with the email used for the commit, but I fixed it.  It is showing signed now.

**Review by tuliren — COMMENTED** [review]
Thank you for the contribution!

Would you mind adding some unit tests? One example is `testUserDoesntHasPrivilegesToSelectTable` in [`PostgresSourceTest.java`](https://github.com/airbytehq/airbyte/blob/v0.36.3-alpha/airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/PostgresSourceTest.java#L230). Ideally the tests should verify that:
- When the user has SELECT privilege on a table, `getPrivilegesTableForCurrentUser` will include that that table in the returned result.
- When the user has no SELECT privilege on a table, that table won't be included in the return result.

It's also fine though if you don't have bandwidth to work on the unit test.

**Comment by radostyle** [comment]
I included a unit test that tests the discovery logic. `testUserDoesntHasPrivilegesToSelectTable` seems to test that you can get the changes when you've already configured the table.

**Review by tuliren — APPROVED** [review]
Confirmed that this PR fixed the bug. Thanks a lot!

I will merge and publish a new version in a separate PR.

**Pull request merged**
