### PR TITLE
re-enable mssql integration test

### PR DESCRIPTION
**Pull request by jrhizor**
Should work now.

### CODE REVIEW

**Review by cgardens — APPROVED** [review]
did you figure out what was breaking this originally? or is it just a non issue since we split them up.

**Comment by jrhizor** [comment]
Didn't find out the underlying issue, but it is a non-issue since we're breaking this up. I suspect reverting some combination of the Docker optimizations _might_ let it work when run together. 

I think it's worth having it working separately at the cost of maybe failing together just so the code doesn't go out of date. Like right now that integration test doesn't even compile...

**Pull request merged**
