### PR TITLE
Jamakase/implement auth

### LINKED ISSUE #5644: UI: when displaying an oauth connector's spec, hide any oauth init parameters from the user
## Tell us about the problem you're trying to solve
What are you trying to do, and why is it hard? A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

### LINKED ISSUE #5645: UI: when displaying an oauth connector's spec, show an "authorize" button to initiate the oauth flow
## Tell us about the problem you're trying to solve

Mockup: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=27283%3A94025

## Describe the solution you’d like
when displaying an oauth connector's spec, show an "authorize" button to initiate the oauth flow. We can identify that a connector is oauth-based if its spec has an `auth` property which has a property `type: oauth2.0` e.g: 

```
{
  “connectorSpecification: {
    “Client_id”: <string>, 
    “Client_secret”: <string>, 
    “Developer”_token”: <string> 
    “Start_date”: <datetime>,
    “ad_Account_id”: <integer>, 
  },
  “auth”: {
	“type”: “oauth2.0”,
	// this array points to the params in the connectorSpecification needed to kick off the oauth flow
// this would be a 2d array to handle nesting
    “oauth_flow_init_parameters”: [[“client_id”], [“client_secret”], [“developer_token”]]
  }
}
```
Screen Shot 2021-08-26 at 8 16 57 AM

When this button is clicked, it should hit the endpoint implemented in https://github.com/airbytehq/airbyte/issues/5639 which will return the URL to which a user should be redirected to grant oauth consent

### LINKED ISSUE #5646: UI: integrate with oauth endpoints
Tracks any work the UI needs to do to integrate with the two oauth endpoints: 
- [x] #5644
- [x] #5645

### LINKED ISSUE #5770: UI/Webserver: Expose an endpoint to which a user should be redirected after granting Oauth consent
Once a user grants consent and is redirected back to airbyte, they should be redirected to an endpoint which will do the following: 

1. call `complete_auth_request` on the backend server, providing the following inputs:
    1. connector definition ID
    2. current workspace ID
    3. any query params found in the redirect URL
2. `complete_auth_request` will return an object containing some properties related to oauth e.g: `{refresh_token: XYZ, access_token: XYZ, ...}`. Using this response, the UI should pre-fill any fields with the same name. For example, if the spec has only `{refresh_token: {type: string}}` then the UI should pre-fill that field with the value returned from the API. 
3. Display the spec as normal and allow the user to fill it out like normal

The below diagram illustrates how this would work. See the portion after "Redirect user to airbyte with auth code". 

Screen Shot 2021-08-30 at 5 27 25 PM

### LINKED ISSUE #6027: Only hide Oauth inputs if UI is running for cloud
Today the UI by default hides all the parameters specified in the `authSpecification.oauth2Spec.oauthFlowInitParameters` field. 

However, if we release this as it is in the OSS version then most users will not be able to use any oauth connetors, since Oauth params will not be set in the OSS version (not by default at least), and the oauth process is not well documented. 

So when running in OSS we should not hide any oauth fields in the user input forms

### PR DESCRIPTION
**Pull request by jamakase**
## What
Adds oauth support for connectors.

Closes #5646 
Closes #6027 
Closes #5770 
Closes #5645 
Closes #5644 

## How
image

1. As soon as user has consent URL he opens new window with it and starts to listen for new messages (`window.postMessage` ) sent from child window
2. User enters all info in oauth provider.
3. User is redirected back from provider to child window
4. child window sends to parent `window.opener` message with URL info
5. parent window receives the info and continues processing

## Recommended reading order
1. `airbyte-webapp/src/hooks/services/useConnectorAuth.tsx`
2. `airbyte-webapp/src/core/jsonSchema/utils.ts`
image

### CODE REVIEW

**Comment by ChristopheDuong** [comment]
The UI is blocking me because i didn't fill up oauth fields `client_id` / `client_secret`

(they should not appear in the screen as per https://github.com/airbytehq/airbyte/issues/5644)

Screenshot 2021-09-23 at 23 13 47

I worked around it anyway but writing random value in the fields (they'll be overwritten with proper values by backend anyway)

**Comment by Jamakase** [comment]
> The UI is blocking me because i didn't fill up oauth fields `client_id` / `client_secret` so I can't click on "setup source"
> I worked around it anyway by writing random value in the fields so I could click on "set up source" button (they'll be overwritten with proper values by backend anyway)

Feature was implemented according to the task you are referring to - any fields from the path are excluded. According your screen, path to the property doesn't match google ads one ( `credentials. developer_token` ). Could you please share what spec are you testing?

**Comment by ChristopheDuong** [comment]
> > The UI is blocking me because i didn't fill up oauth fields `client_id` / `client_secret` so I can't click on "setup source"
> > I worked around it anyway by writing random value in the fields so I could click on "set up source" button (they'll be overwritten with proper values by backend anyway)
> 
> Feature was implemented according to the task you are referring to - any fields from the path are excluded. According your screen, path to the property doesn't match google ads one ( `credentials. developer_token` ). Could you please share what spec are you testing?

My example is with google analytics: https://github.com/airbytehq/airbyte/blob/a8261f474219c7664c9e886b73c68394928c94b3/airbyte-integrations/connectors/source-google-analytics-v4/source_google_analytics_v4/spec.json#L79

**Comment by ChristopheDuong** [comment]
The OAuth fields are now properly hidden but when I hit the set up source, it fails to check connection and can't create the source connector.

When I look at the source_config.json in the workspace of the check_connection job, I don't see the refresh_token (but i do see the client_id/client_secret and some other fields (not injected by web backend) in the nested credentials (oneOf) field:

```
{
..., 
"credentials": {
    "option_title": "Default OAuth2.0 authorization",
    "client_id": "blabla",
    "client_secret": "***mysecret***"
  }
}
```

**Comment by ChristopheDuong** [comment]
btw if i start filling up the fields for my connector and click "re-authenticate" afterward to complete my consent etc

all the inputs i entered are flushed and i have to enter them again

**Comment by Jamakase** [comment]
> btw if i start filling up the fields for my connector and click "re-authenticate" afterward to complete my consent etc
> 
> all the inputs i entered are flushed and i have to enter them again

This one is fixed

**Review by ChristopheDuong — APPROVED** [review]

**Pull request merged**
