### PR TITLE
🎉 🐛 Source Airtable: cast native Airtable Types to  JSONSchema Types

### PR DESCRIPTION
**Pull request by bazarnov**
## What
Resolving: https://github.com/airbytehq/alpha-beta-issues/issues/299

## How
- refactored the `schema_helpers.py` to provide the functionality to cast data types automatically

## 🚨 User Impact 🚨

@erica-airbyte 
This is the BREAKING CHANGE. 

But what should customer do? :
After the update, the customers should `Refresh Schema` and reset the data to pick up the correct schema types and avoid issues on the destination side. Unfortunately. 

Reason for the breaking change:
The reason for the breaking change is this one: https://github.com/airbytehq/alpha-beta-issues/issues/299

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Comment by erohmensing** [comment]
@bazarnov one of your merges looks like it went wrong - same happened to me earlier (see all the frontend changes in the diff), or perhaps you maybe ran `format` on the whole repo, and things went awry? 

Happy to take a look over the PR when that's resolved

**Comment by bazarnov** [comment]
I'll rebase this one and fix this tomorrow, thanks a lot for your time.

**Comment by bazarnov** [comment]
This PR Is messed up with files that are not related to the changes. Closing this one, the new  will be created.

**Pull request closed without merging**
