### PR TITLE
Publish 1.0.45 source-postgres-strict-encrypt

### PR DESCRIPTION
**Pull request by rodireich**
## What
Publish 1.0.45 source-postgres-strict-encrypt to match the version of source-postgres.

### CODE REVIEW

**Review by pedroslopez — APPROVED** [review]

**Comment by rodireich** [comment]
/publish connector=connectors/source-postgres-strict-encrypt auto-bump-version=false

**Comment by octavia-approvington** [comment]
Lets do it! <br/> giddddy-up

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
