### PR TITLE
Switch to shared code for actions

### PR DESCRIPTION
**Pull request by bleonard**
* no longer need project code for platform and frontend
* moved shared code for community tagging to shared actions

### CODE REVIEW

**Comment by bleonard** [comment]
@pmossman @timroes please confirm this project assigning it no longer needed
happy to put either back if you still want it to put things in those projects.

**Comment by pmossman** [comment]
@bleonard confirmed that we don't need the project assigning in Cloud anymore, we're happy with Zenhub moving forward. I added @benmoriceau as a reviewer so that he can confirm that it's ok to remove the automation for OSS project assignment

**Comment by benmoriceau** [comment]
@bleonard It is ok for OSS as well.

**Comment by timroes** [comment]
The FE project code assignment is still needed. We haven't started evaluating zenhub yet due to all the login bugs. We'll be evaluating it over the next sprints, but I'd like to keep the assign action running until after the evaluation, when we know what tool we're moving forward with.

**Review by davinchia — COMMENTED** [review]
LGTM in general. I want to make sure @harshithmullapudi @marcosmarxm confirm they no longer need the community label.

**Comment by marcosmarxm** [comment]
> LGTM in general. I want to make sure @harshithmullapudi @marcosmarxm confirm they no longer need the community label.

we need. it is how we control and manage community contributions for PR and issues.
image

@harshithmullapudi can you check with @bleonard what is needed here?

**Comment by bleonard** [comment]
@harshithmullapudi to be clear, I've moved the community code to the shared labeling code that we've done in the `workflow-actions` repo

**Comment by bleonard** [comment]
> The FE project code assignment is still needed. We haven't started evaluating zenhub yet due to all the login bugs. We'll be evaluating it over the next sprints, but I'd like to keep the assign action running until after the evaluation, when we know what tool we're moving forward with.

No problem, putting it back.

**Pull request merged**
