### PR TITLE
migrate live-test to a different repo

### PR DESCRIPTION
**Pull request by alafanechere**
Migrating to our internal repo as the connection retriever tool is there.

### CODE REVIEW

**Comment by alafanechere** [comment]
* **#35948** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/35948?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alafanechere and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by clnoll — APPROVED** [review]
LGTM. Any reason not to delete [this](https://github.com/airbytehq/airbyte/blob/27d9207ce4e662deef9438b225629456368fca79/airbyte-ci/connectors/pipelines/pipelines/airbyte_ci/test/__init__.py#L15) too?

**Comment by natikgadzhi** [comment]
Can you tell me why this is needed? Is the regression tool useful for situations where you want to compare two versions of a connector with sandbox account instead of ext credentials? It so, should the tool remain public?

If the tool needs credentials-tool in the same repo — I understand. Okay to move forward, we can always put that back later if we decide to.

**Comment by clnoll** [comment]
@natikgadzhi per [this conversation](https://airbytehq-team.slack.com/archives/C06GNN6BERK/p1709919250251829), organizationally it's easier to keep it here right now, and we probably don't want to advertise to the world that we may be running syncs against production accounts.

To answer your question, it definitely makes sense to run this against our test accounts, and perhaps even to give the tool in some form to enterprise customers in the future (e.g. they could run the tool, and it would zip up the output which they could send to us for help with debugging). But for now I think it makes sense to keep it internal. We can definitely revisit that once it's more polished.

**Pull request merged**
