### PR TITLE
🎉 octavia-cli: Add ability to get existing resources

### PR DESCRIPTION
**Pull request by danieldiamond**
## What
- add `get` commands to get the existing configurations for sources, destinations and connections

## How
- Add `octavia get source RESOURCE_ID` which leverages `get_source` method from the open-client resources.

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

```
➜ pytest unit_tests/test_get/
====================================================== test session starts =======================================================
platform darwin -- Python 3.9.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /Users/danieldiamond/repos/airbyte/octavia-cli, configfile: pytest.ini
plugins: requests-mock-1.9.3, mock-3.7.0, cov-3.0.0
collected 10 items

unit_tests/test_get/test_commands.py::test_commands_in_get_group PASSED                                                    [ 10%]
unit_tests/test_get/test_commands.py::test_available_commands PASSED                                                       [ 20%]
unit_tests/test_get/test_commands.py::test_source[command0-my_resource_id] PASSED                                          [ 30%]
unit_tests/test_get/test_commands.py::test_destination[command0-my_resource_id] PASSED                                     [ 40%]
unit_tests/test_get/test_commands.py::test_connection[command0-my_resource_id] PASSED                                      [ 50%]
unit_tests/test_get/test_resources.py::TestBaseResource::test_init PASSED                                                  [ 60%]
unit_tests/test_get/test_resources.py::TestBaseResource::test_get_config PASSED                                            [ 70%]
unit_tests/test_get/test_resources.py::TestSource::test_init PASSED                                                        [ 80%]
unit_tests/test_get/test_resources.py::TestDestination::test_init PASSED                                                   [ 90%]
unit_tests/test_get/test_resources.py::TestConnection::test_init PASSED                                                    [100%]

======================================================= 10 passed in 0.09s =======================================================
```

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by danieldiamond** [comment]
@alafanechere any chance you can help me out here. Added a series of `get` commands, and looking to call the `generate` commands over these `get` commands.

e.g.
```python
def generate_existing_source(ctx: click.Context, resource_id: str):
    resource = Source(ctx.obj["API_CLIENT"], ctx.obj["WORKSPACE_ID"], resource_id)
    config = resource.get_config()
    generate_source_or_destination("source", ctx.obj["API_CLIENT"], ctx.obj["WORKSPACE_ID"], config["source_definition_id"], config["source_name"])
```
the above will just generate a templated yaml spec, thinking to either:
- pass the `config` (source details) into a modified `generate_source_or_destination` function
- first do this `generate_source_or_destination` and generate a template YAML, then overwrite that yaml file with the `config` details

**Comment by alafanechere** [comment]
Hi @danieldiamond, thank you very much for this contribution! 
Before giving a thorough review I'd like to discuss the following items with you:
* I originally considered this feature as being `import`, do you mind changing `get` to `import`? If you want this PR to only add a command which prints remote configuration in YAML I'm fine sticking with `get`, but if the goal is to actually create a configuration file from an existing resource I'd prefer to use `import`. 
* If you end up writing configuration files from existing remote sources / destinations /connections I think you will also have to create a `state.yaml` file for these resources so that `apply` will not try to re-create these resources.


> first do this generate_source_or_destination and generate a template YAML, then overwrite that yaml file with the config details

I'm wondering if you could completely not call any `generate` related function and only dump the config response to YAML. You will have to keep the "headers" of the current YAML files such as `resource_name`, `definition_type`, `definition_id` etc. to have a valid config but the actual config could maybe just be a YAML dump? What do you think?

I'm suggesting this to reduce interdependency between these `generate` and `import`. And I think that the current renderer are not transforming the configuration structure very much compared to the raw response.

If it's a dead-end I would indeed suggest something like first `generate` then overwrite with config details.

**Comment by danieldiamond** [comment]
> I originally considered this feature as being import, do you mind changing get to import? If you want this PR to only add a command which prints remote configuration in YAML I'm fine sticking with get, but if the goal is to actually create a configuration file from an existing resource I'd prefer to use import.

i agree with you unfortunately `import` is a reserved word in python. not sure how you intended to implement this. i've updated to include `get` as well as `update` (to update existing yaml configuraitons)

> I'm suggesting this to reduce interdependency between these generate and import. And I think that the current renderer are not transforming the configuration structure very much compared to the raw response.

again, i agree, lets avoid interdependency, however i do notice `generate` does depend on `apply`
https://github.com/airbytehq/airbyte/blob/16de42fde3ad4af35d830791e0bc4552f7b0fb72/octavia-cli/octavia_cli/generate/commands.py#L7

in the interest of DRY, i dont want to copy half of `generate` and `apply` to `update`. so i'm thinking its more appropriate to abstract these out into a `utils` direction (a bunch of helper files). thoughts?

this latest commit allows a user to `update` existing yaml files but 
1. this removes the templating (with comments etc) that currently exists in the `renderers` section
2. it assumes a user already has "generated" all the necessary templates.

the next commit is most likely `octavia update sources` (plural) to automatically generate and update all sources. thoughts?

**Comment by danieldiamond** [comment]
this last commit adds commands to pull and update all sources + destinations. it creates a ton of interdependency for the `update` commands. 2 things i noticed:

- resource names can be poorly names i.e. include `:` which breaks yaml spec. Need to add quotes around `resource_name` in the rendered template
- the directory structure doesn't really make sense to me, why have `sources/my_custom_source_name/configuration.yaml` instead of the _type_ of source e.g. `sources/github/github_pull_request_only.yaml` and `sources/github/repositories.yaml` instead of `sources/github_pull_request_only_source/configuration.yaml` and `sources/github_repositories/configuration.yaml`

to do: add _all_ connections

**Comment by alafanechere** [comment]
> > I originally considered this feature as being import, do you mind changing get to import? If you want this PR to only add a command which prints remote configuration in YAML I'm fine sticking with get, but if the goal is to actually create a configuration file from an existing resource I'd prefer to use import.
> 
> i agree with you unfortunately `import` is a reserved word in python. not sure how you intended to implement this. i've updated to include `get` as well as `update` (to update existing yaml configurations)

Oh yes, you are right. What do you think about naming the function `_import` or `import_command` and use the decorator `@click.command(name='import')`? 

> > I'm suggesting this to reduce interdependency between these generate and import. And I think that the current renderer are not transforming the configuration structure very much compared to the raw response.
> 
> again, i agree, lets avoid interdependency, however i do notice `generate` does depend on `apply`
> 
> https://github.com/airbytehq/airbyte/blob/16de42fde3ad4af35d830791e0bc4552f7b0fb72/octavia-cli/octavia_cli/generate/commands.py#L7
> 
> in the interest of DRY, i dont want to copy half of `generate` and `apply` to `update`. so i'm thinking its more appropriate to abstract these out into a `utils` direction (a bunch of helper files). thoughts?

You are right, there's an interdependency because `apply.resources.Source` and `apply.resources.Destination` are required to generate a connection configuration. I would suggest to move the declaration of `BaseResource` an its child classes to a `resources.py` module at the root of `octavia_cli` and keep `ResourceState` in a `state.py` module in the `apply` submodule. What do you think? I'd love to avoid `utils` or `commons` as they are prone to grow unreasonably large in the future and mess up with a clear project architecture. 

> this latest commit allows a user to `update` existing yaml files but
> 
> 1. this removes the templating (with comments etc) that currently exists in the `renderers` section
> 2. it assumes a user already has "generated" all the necessary templates.
> 
> the next commit is most likely `octavia update sources` (plural) to automatically generate and update all sources. thoughts?

Do you think you can dedicate a separate PR for an `update` command? I'd love to make the PR as atomic as possible and it will make it easier for me to review this original one.

**Comment by alafanechere** [comment]
> Do you think you can dedicate a separate PR for an update command? I'd love to make the PR as atomic as possible and it will make it easier for me to review this original one.

If the `update` command is what I would call `import` you can keep it in this PR 😄

**Comment by alafanechere** [comment]
> resource names can be poorly names i.e. include : which breaks yaml spec. Need to add quotes around resource_name in the rendered template

Feel free to sanitize the `resource_name` to snake_case

> the directory structure doesn't really make sense to me, why have sources/my_custom_source_name/configuration.yaml instead of the type of source e.g. sources/github/github_pull_request_only.yaml and sources/github/repositories.yaml instead of sources/github_pull_request_only_source/configuration.yaml and sources/github_repositories/configuration.yaml

Could you explain why your suggestion makes more sense to you? I originally tried to mimic a bit the logic available in the UI on which resources are categorized according to their types (sources, destinations, connections) and under each resource type there are no extra categorizations for each connector type. I prefer to keep the `configuration.yaml` file along with the `state.yaml` and any other file we might need to add on a resource basis.

**Comment by alafanechere** [comment]
@danieldiamond we have an interesting related discussion about `octavia get` and `octavia import` with @evantahler on https://github.com/airbytehq/airbyte/pull/13070

**Comment by danieldiamond** [comment]
hey @alafanechere thanks for the link. it seems like your last comment  https://github.com/airbytehq/airbyte/pull/13070#issuecomment-1156682095 is aligned with the general philosophy behind this PR yes?
`get` being "read-only" capability
and `import` (or as it is in this PR "`update`" due to import being a reserved word) overriding these.

**Comment by alafanechere** [comment]
We decided with @danieldiamond to split this PR in two. The current one should only be for the `get` command implementation. I iterated on it on this branch https://github.com/airbytehq/airbyte/pull/14119

**Comment by alafanechere** [comment]
My iteration on #14119 surfaced two things:
* We can make  `apply.resources.BaseResource` even more abstract and so that we avoid repeating the API interaction related code in `apply.resources.get` and `apply.resources.apply`. This can be done in the future.
* The `get.resourses.BaseResource.get_remote_resource` function can be reused by the future `import` command to retrieve a valid model instance that can be dumped to a YAML file.

**Comment by alafanechere** [comment]
@danieldiamond feel free to pull my commits from #14119 and I'll 👍 ! All your suggestions are welcomed of course.

**Review by alafanechere — APPROVED** [review]
Thank you @danieldiamond for this initiative and pulling my suggestions 🙏 
Let's merge now.

**Pull request merged**
