### PR TITLE
source-circleci contribution from btkcodedev

### PR DESCRIPTION
**Pull request by btkcodedev**
## What

This PR adds a new connector for source Circleci (source-circleci).

Contributor-provided connector description:

Website: https://app.circleci.com/
API Docs: 
- v1-https://circleci.com/docs/api/v1/index.html
- v2-https://circleci.com/docs/api/v2/index.html
API page: https://app.circleci.com/settings/user/tokens
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key.  |  |
| `org_id` | `string` | Organization ID. The org ID found in `https://app.circleci.com/settings/organization/circleci/xxxxx/overview` |  |
| `start_date` | `string` | Start date.  |  |
| `organizational_slug` | `string` | Organizational slug. Organizational slug |  |
| `project_slug` | `string` | Project slug. Project slug for getting information about it |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| context | id | DefaultPaginator | ✅ |  ✅  |
| self_ids | id | DefaultPaginator | ✅ |  ❌  |
| self_collaborations | id | DefaultPaginator | ✅ |  ❌  |
| me | analytics_id | DefaultPaginator | ✅ |  ✅  |
| projects | vcs_url | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by natikgadzhi** [comment]
This one needs a lot more work. 

In a CI platform, we'd want things like jobs, workflows, run statuses, timeseries data etc.

**Comment by natikgadzhi** [comment]
It could be that you'd have to find someone who is using CircleCI extensively and work with them. I can try and reach out to my friends at Circle, maybe they can introduce us to some of their users so they can be our design partners.

**Comment by btkcodedev** [comment]
I thought of it.
It would be so much helpful if someone has a working circleci account creds. 
It's so hard to manually seed streams. 🫡

**Comment by natikgadzhi** [comment]
@btkcodedev so far, haven't found anyone who would bite ;(

**Comment by btkcodedev** [comment]
🤔I'll figure some workaround for streams. 
There has to be a hard way for seeding streams

**Comment by natikgadzhi** [comment]
Someone just volunteered on Slack!

**Comment by btkcodedev** [comment]
@natikgadzhi, New streams added and tested, Contain workflows, pipelines, jobs, insights - totaling of 12 strems :partying_face:

**Comment by btkcodedev** [comment]
All tested and verified

**Comment by natikgadzhi** [comment]
Strong work!

**Pull request merged**
