### PR TITLE
Google drive: Use smart_open library

### PR DESCRIPTION
**Pull request by flash1293**
Based on https://github.com/airbytehq/airbyte/pull/31458

This PR is using the smart_open library instead of the native Google SDK helpers to download the file.
The advantage is the ability to read the file incrementally (which is a feature of smart_open), the downside is that it requires the usage of undocumented parts of the Google library to put together the right headers for the request.

### CODE REVIEW

**Comment by aaronsteers** [comment]
I'm a fan of `smart_open` so overall, I'd be inclined for this. But for context, don't we need to read the full file anyway? I don't see yet why reading incrementally is helpful for our use cases. Can you clarify for me?

**Comment by flash1293** [comment]
>  I don't see yet why reading incrementally is helpful for our use cases. Can you clarify for me?

cc @clnoll in case I'm missing something here, but reading incrementally allows us to process huge files that wouldn't fit into memory at once (like a multi-gb csv file). I agree that for the use cases we imagined (reading a large number of smaller files with a little bit of text in them), it doesn't matter too much, that's why I split it out and don't see it as a blocker.

**Comment by aaronsteers** [comment]
> > I don't see yet why reading incrementally is helpful for our use cases. Can you clarify for me?
> 
> cc @clnoll in case I'm missing something here, but reading incrementally allows us to process huge files that wouldn't fit into memory at once (like a multi-gb csv file). I agree that for the use cases we imagined (reading a large number of smaller files with a little bit of text in them), it doesn't matter too much, that's why I split it out and don't see it as a blocker.

I see! I just wasn't thinking about file-types that emit multiple records per file. For document-type files, we generally have to read the whole thing into memory anyway to get the (singular) record data, but yes 100% - I agree that with CSV's and any source that can send a record at a time, we definitely should parse it serially rather than all at once.

So, yes, I'm in favor of this approach for the reasons you mention. 👍 Thanks!

**Comment by clnoll** [comment]
@flash1293 just curious - are you no longer planning to use `smart_open` for google drive?

**Comment by flash1293** [comment]
Still planning to do this, but I ran into some issues and had to switch to other things. I created an issue to track this work here: https://github.com/airbytehq/airbyte/issues/32136

**Pull request closed without merging**
