### PR TITLE
Fail connection manager workflow on non-deterministic exception

### LINKED ISSUE #13973: Automatically handle non-deterministic temporal errors
## What

One of the conclusions from the Quarantined State discussion (notes [here](https://docs.google.com/document/d/1xpVBCoVfeDfuVVFEdKyICpQl6G3XiFvwq1W7DPKe-cY/edit)) was that we do not want connection manager workflows to be blocked due to non-deterministic errors, as we can always just safely terminate and restart the workflows in that case.

Therefore, the goal of this issue is to modify our temporal logic to automatically terminate and restart connection manager workflows that run into non-deterministic exceptions. 

## How

Some pre-investigation was done on how to do this, and unfortunately it looks like Temporal does not offer much configurability on the behavior that should happen in the case of NonDeterministicExceptions, as these occur at a higher level up than our ConnectionManagerWorkflow code -- these errors happen when Temporal is trying to restore or replay a stored workflow, all of which happens deep inside the temporal library code.

Here are a few potential options for how to mitigate this:
1. Use the [WorkflowImplementationOptions.setFailWorkflowExceptionTypes()](https://www.javadoc.io/static/io.temporal/temporal-sdk/1.0.0/io/temporal/worker/WorkflowImplementationOptions.Builder.html#setFailWorkflowExceptionTypes-java.lang.Class...-) to have temporal automatically set workflows to `Failed` when they run into NonDeterministicExceptions, rather than looping over and over indefinitely. Then, we would need to add some process that finds failed temporal workflows and terminates + restarts them. (Micronaut could help with scheduled tasks here)
2. Fork the temporal library to change what the behavior is in the NonDeterministicException case. This is probably not a great option since we would need to maintain a fork of temporal.
3. Send a signal to all workflows on deploy, causing them to restart. This would need to be tested if it even works in all cases (i.e. could a NonDeterministicException be encountered when processing that signal?) and if the temporal cluster can handle signaling every open workflow at once.
4. Explore other options / ask Temporal folks how we can address this

**From grooming: we have decided to fail workflows that run into non-deterministic exceptions (option 1). This should be done after completing this separate issue to automatically find and fix failed and terminated workflows: https://github.com/airbytehq/airbyte/issues/14043**

### PR DESCRIPTION
**Pull request by lmossman**
## What
Resolves https://github.com/airbytehq/airbyte/issues/13973

## How
Uses the temporal api to have non-deterministic exceptions cause workflows to be marked as failed, rather than retrying indefinitely.

Note: This should probably only be merged once this other issue has been completed, so that the failed workflows are automatically restarted when this occurs: https://github.com/airbytehq/airbyte/issues/14043

### CODE REVIEW

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Review by gosusnp — APPROVED** [review]
I am wondering, how complex would it be to write a test for this?

**Comment by lmossman** [comment]
I'm not exactly sure what a test for this would look like, since it would require changing the order or names of activities for a running workflow, which I've only done by changing code. Might be possible though - probably worth having someone spend some time looking into that.

**Comment by lmossman** [comment]
@benmoriceau I added a note to the description of this ticket - it's up to you all, but we may want to wait to wait to merge this until the issue to find and restart failed workflows has been completed (https://github.com/airbytehq/airbyte/issues/14043).

If we merge this first, then non-deterministic exceptions will cause workflows to be set to Failed without anything automatically fixing them. Though, I'm not sure if this is actually worse or better than the current behavior (Temporal just retrying the workflows indefinitely, running into the non-deterministic exception over and over). So I'll leave that decision up to the team!

**Comment by evantahler** [comment]
https://github.com/airbytehq/airbyte/issues/14043 has been merged.  @jdpgrailsdev / @benmoriceau it it time to merge this?

**Comment by lmossman** [comment]
@evantahler if we merge this before we have the process in place that automatically restarts failed workflows (I think this ticket https://github.com/airbytehq/airbyte/issues/15218 ?), then non-deterministic exceptions will result in workflows being set to `Failed` with nothing automatically restarting them.

See my comment [here](https://github.com/airbytehq/airbyte/pull/14758#issuecomment-1208496820) - I think it may be slightly preferable to keep the current behavior until we have that, but its up to you all

**Comment by benmoriceau** [comment]
This is ready to be merged, I will do it once green.

**Pull request merged**
