### PR TITLE
Source Intercom: updated test_switch_to_standard_endpoint and test_companies_scroll

### PR DESCRIPTION
**Pull request by darynaishchenko**
updated test_switch_to_standard_endpoint and test_companies_scroll: changed len(records) and total time
added TypeTransformer for stream companies

### CODE REVIEW

**Comment by bazarnov** [comment]
@lazebnyi @darynaishchenko 
FYI, these tests fixed are omitted along with the Intercom (Low Code) release, since there is no need to test switch between 2 endpoints, because it creates throttling on the connector's side. Low Code's version uses the scroll endpoint effectively as the only option to fetch the companies.

**Review by bazarnov — APPROVED** [review]

**Review by lazebnyi — CHANGES_REQUESTED** [review]
Please add allowedHosts

**Review by lazebnyi — APPROVED** [review]

**Pull request merged**
