### PR TITLE
Source Netsuite: add upper cursor end and concurrency retry support

### PR DESCRIPTION
**Pull request by maximum-pixels**
## What
Adding upper cursor end as an optional parameter to the source config lets larger syncs finish easier to prevent the connector from spinning its wheels and re-extracting already extracted data from the same sync. Another optional boolean parameter lets the user decide whether concurrency issues are retryable. Even with a dedicated concurrency channel in NetSuite, airbyte runs into this error sometimes. With the error set as retryable, it further reduces the chances of a wrongful error stop.

## How
The combination of a start & end date for the sync means that you can run multiple smaller syncs from say 2010-01-01 to 2015-01-01. Then you change the end date to say 2020-01-01 and re-run the sync (incremental). Airbyte will now only go from 2015-01-01 to 2020-01-01. Then again and again and again until you can just remove the end-date parameter which will make it default to the previous automatic upper end `date.today()`.

## Recommended reading order
1. `spec.yaml`
2. `source.py`
3. `streams.py`
4. `errors.py`

## 🚨 User Impact 🚨
No breaking changes, new parameters are optional and have the default behavior (no end-date & retry 429 errors = false) would run the connector the same as before.

Semantic bump from 0.1.3 to 0.1.4.

I saw the guide specifies new optional parameters as a minor bump (e.g. 0.2.0) but these are really more small performance / reliability patches, so 0.1.4 seems more appropriate.

## Pre-merge Actions

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing.

There aren't any existing unit tests for the source, but this screenshot shows the connector running against a real netsuite instance with 3 syncs:
1. start & end-date --> 12 records extracted
2. extended end-date and re-run -->  3 more records extracted
3. no change to config and re-run --> no new records extracted

image

- Documentation updated
    - Connector's `README.md` -- changelog

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added 

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/resources/pull-requests-handbook)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

<details><summary><strong>Updating the Python CDK</strong></summary>

### Airbyter

Before merging:
- Pull Request description explains what problem it is solving
- Code change is unit tested
- Build and my-py check pass
- Smoke test the change on at least one affected connector
   - On Github: Run [this workflow](https://github.com/airbytehq/airbyte/actions/workflows/connectors_tests.yml), passing `--use-local-cdk --name=source-<connector>` as options
   - Locally: `airbyte-ci connectors --use-local-cdk --name=source-<connector> test`
- PR is reviewed and approved
      
After merging:
- [Publish the CDK](https://github.com/airbytehq/airbyte/actions/workflows/publish-cdk-command-manually.yml)
   - The CDK does not follow proper semantic versioning. Choose minor if this the change has significant user impact or is a breaking change. Choose patch otherwise.
   - Write a thoughtful changelog message so we know what was updated.
- Merge the platform PR that was auto-created for updating the Connector Builder's CDK version
   - This step is optional if the change does not affect the connector builder or declarative connectors.

</details>

### CODE REVIEW

**Comment by maximum-pixels** [comment]
Related [issue](https://github.com/airbytehq/airbyte/issues/35745)

**Comment by marcosmarxm** [comment]
Thanks for the contribution @maximum-pixels and sorry the lack of updates. At the moment there are some work to implement a new version of Netsuite using ODBC backend. I asked to the connector team an update of the status and if we're going to continue accepting contributions for the existing Netsuite connector (the one you're doing changes).

**Comment by maximum-pixels** [comment]
Thanks for the update @marcosmarxm . I've heard of the ODBC connector development, but supporting an upper end cursor for large historical syncs would enable workflows for a couple of clients of mine now, instead of waiting for the ODBC connector to make it to GA.

Since the change consists of two optional arguments where the defaults don't change the behavior of the current connector version, I was hoping we could get this deployed so this can be run for my clients through Airbyte cloud. 

Alternatively, is there a way to export the sync state & history from the open source stack, give it to Airbyte support to import into a connection in the airbyte cloud workspace? That way I could run the modified code locally and once its finished cloud could just pick up where the local system left off (i.e. ongoing syncs for changed records)?

**Comment by maximum-pixels** [comment]
@marcosmarxm any news here on when this can be merged?

**Comment by 2m** [comment]
@marcosmarxm would it be possible to reconsider this PR? We are very interested in retries on 429 errors. Recently we started to see an increased 429 response rates from Netsuite which causes Airbyte Cloud jobs to fail.

image

All of the failed jobs have the same error:

```
reason: HTTPError('429 Client Error: Too Many Requests for url: https://****.suitetalk.api.netsuite.com/services/rest/record/v1/creditmemo?limit=1')
```

**Pull request closed without merging**
