### PR TITLE
✨ Source TikTok Marketing: add Ad Report level conversion metrics

### LINKED ISSUE #31979: Source TikTok Marketing: Add missing conversion metrics
### What area the feature impact?

Connectors

### Relevant Information

When i pull Ads Daily level reporting data, i would like for the following metrics from TikTok Marketing to be available:
* "registration"
* "total_registration"
* "user_registration"
* "skan_registration"
* "skan_total_registration"
* "complete_payment"
* "purchase"
* "total_purchase"
* "skan_purchase"
* "skan_total_purchase"

### PR DESCRIPTION
**Pull request by MaxKrog**
## What

This PR ads the following metrics to the Ad Report Level for TikTok Marketing:
* "registration"
* "total_registration"
* "user_registration"
* "skan_registration"
* "skan_total_registration"
* "complete_payment"
* "purchase"
* "total_purchase"
* "skan_purchase"
* "skan_total_purchase"

closes #31979

## How
*Describe the solution*

By adding the new metrics to:
* airbyte-integrations/connectors/source-tiktok-marketing/source_tiktok_marketing/streams.py
  * This makes the metrics be pulled from TikToks API
* airbyte-integrations/connectors/source-tiktok-marketing/source_tiktok_marketing/schemas/basic_reports.json
  *    This makes it so the metrics can be normalized into table format from raw JSON

## 🚨 User Impact 🚨
No breaking changes. Users will have access to more conversion metrics.

### Community member or Airbyter

- ✅  Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- ✅ Unit & integration tests added

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks @MaxKrog I'm going to run tests during the week.

**Comment by MaxKrog** [comment]
Thanks @marcosmarxm , any update? :)

**Comment by marcosmarxm** [comment]
@MaxKrog sorry the delay in review. Can you check the unit tests, right now they're failing.

**Comment by MaxKrog** [comment]
Hi @marcosmarxm ,

Thanks for looking into this PR.

It is not possible for me to check the boxes in the checklist. Sometimes i am able to check one, but not then i am not able to check the rest of the boxes. This gets reset on page refresh.

If you are able to click them for me that would make me very grateful.

**Comment by MaxKrog** [comment]
Unit tests are successful now @marcosmarxm 

The only test that is failing is the one below, but i assume that is because of my credentials.
```
=================================== FAILURES ===================================
_____________ test_source_streams[secrets/sandbox_config.json-28] ______________

config = {'credentials': {'access_token': 'XXX', 'app_id': '7276014632727216129', 'auth_type': 'oauth2.0', 'secret': 'XXX'}}
stream_len = 28

    @pytest.mark.parametrize(
        "config, stream_len",
        [
            (PROD_CONFIG_FILE, 36),
            (SANDBOX_CONFIG_FILE, 28),
        ],
    )
    def test_source_streams(config, stream_len):
        with open(config) as f:
            config = json.load(f)
        streams = SourceTiktokMarketing().streams(config=config)
>       assert len(streams) == stream_len
E       assert 36 == 28
E        +  where 36 = len([, , , ...])
```

**Comment by marcosmarxm** [comment]
Thanks @MaxKrog I'll run integration tests and return asap to you.

**Review by lazebnyi — CHANGES_REQUESTED** [review]
Look like CAT failed and some issue with provided metrics

**Comment by marcosmarxm** [comment]
I'm closing this as it is outdated. @MaxKrog, sorry for not being able to get this merged in time.

**Pull request closed without merging**
