### PR TITLE
Source Mailchimp: fix primary key for email activities

### LINKED ISSUE #5130: Mailchimp "email_activity" table is causing a normalization error on initial sync
## Enviroment
- **Airbyte version**:  0.29.0-alpha
- **Source Connector and version**: Mailchimp 0.2.6
- **Severity**: Medium

## Current Behavior
The other two tables worked fine, only the "email_activity" table failed.

## Logs
[logs-1792-0.txt](https://github.com/airbytehq/airbyte/files/6913303/logs-1792-0.txt)

### LINKED ISSUE #5142: SAT: Fix configured_catalog stream field fulfillment
## Enviroment
- **Airbyte version**:  0.29.0-alpha
- **Severity**: Medium

## Current Behavior
SAT reads `configured_catalog` from config file and does not fill it with python-specified fields. Though `discover` command add these fields to the catalog output.

## Expected Behavior
`configured_catalog` arg in SAT should be filled the same way, as the catalog generated by `discover`.

## Steps to Reproduce
1. Specify the `primary_key` in any stream
2. Does not specify `source_defined_primary_key` in configured catalog
3. Run `discover` command
4. Debug SAT to see the `configured_catalog` values
5. Compare the output from the steps 3 and 4

## Additional Info
This issue may be very important. 
Discover command [generates](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/abstract_source.py#L76-#L79) catalog with 
```
streams = [stream.as_airbyte_stream() for stream in self.streams(config=config)]
return AirbyteCatalog(streams=streams)
```
Where the `as_airbyte_stream()` method actually fills the fields with python specified data.

So I believe that we may call discover command and get its results to then use in another tests (especially `test_read` where we need generated values, but it may be needed for other tests in future).

### PR DESCRIPTION
**Pull request by vovavovavovavova**
## What
Closes #5130 

## How
I was not able to reproduce the following error with our data (the sync was successful), however it looks clear. The activities have not neither the id field, neither any other unique one could be used as source defined primary key. This commit removes default "id" from this 
stream and should close the following issue.

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the checklist which is relevant for this PR. 

<details><summary> <strong> Connector checklist </strong> </summary>
<p>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Secrets are annotated with `airbyte_secret` in the connector's spec
- [ ] Credentials added to Github CI if needed and not already present. [instructions for injecting secrets into CI](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#using-credentials-in-ci). 
- [ ] Unit & integration tests added as appropriate (and are passing)
    * Community members: please provide proof of this succeeding locally e.g: screenshot or copy-paste acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] `/test connector=connectors/<name>` command as documented [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-an-existing-connector) is passing. 
    * Community members can skip this, Airbyters will run this for you. 
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] `README.md`
    - [ ] `docs/SUMMARY.md` if it's a new connector
    - [ ] Created or updated reference docs in `docs/integrations/<source or destination>/<name>`.
    - [ ] Changelog in the appropriate page in `docs/integrations/...`. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md` contains a reference to the new connector
    - [ ] Build status added to [build page](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md)
- [ ] Build is successful
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] No major blockers
- [ ] PR merged into master branch
- [ ] Follow up tickets have been created
- [ ] Associated tickets have been closed & stakeholders notified
</p>
</details>

<details><summary> <strong> Connector Generator checklist </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by vitaliizazmic — COMMENTED** [review]
That would make sense, but it should be tested.

**Comment by vovavovavovavova** [comment]
> That would make sense, but it should be tested.

Vadim said, he created a separate issue, that SAT will test primary key (issue is lined above). From Connector MailChimp side, I fixed the primary key.

**Review by vitaliizazmic — APPROVED** [review]

**Review by sherifnada — APPROVED** [review]

**Pull request merged**
