### PR TITLE
:bug: Source Gitlab: fix OAuth token expiry date

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/alpha-beta-issues/issues/911

## How
Calculate token expiry date as created_at + expires_in instead of now() + expires_in. This is a matter of seconds, or even less, but very likely will fix the issue

### CODE REVIEW

**Comment by davydov-d** [comment]
@alafanechere fyi on potential `SingleUseRefreshTokenOauth2Authenticator` extension, though I don't think this is needed in CDK now as only one connector differs from the default bevavior

**Comment by davydov-d** [comment]
:point_up: test fail because of dependency on https://github.com/airbytehq/airbyte/pull/27350

**Comment by alafanechere** [comment]
I'm updating the PR to get fresh CI run. CF https://airbytehq-team.slack.com/archives/C02UF50V9HA/p1686758235881369

**Comment by octavia-squidington-iii** [comment]
##  source-gitlab test report (commit [`f20e3dde29`](https://github.com/airbytehq/airbyte/pull/27351/commits/f20e3dde290ace1cf81b609c762f1aacc5f091fc)) - ✅

⏲️  Total pipeline duration: 776 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-gitlab/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-gitlab docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5271690561)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Review by lazebnyi — APPROVED** [review]

**Pull request merged**
