### PR TITLE
✨ source-zendesk-chat + source-auth0: update the base image

### PR DESCRIPTION
**Pull request by alafanechere**
## What
I originally tried out the base image migration with `source-auth0` and `source-zendesk-chat`.
Now that we have released a new base image version (1.1.0) we want these connector to use it.

## How
`airbyte-ci` commands only:

```bash
 airbyte-ci connectors --name=source-auth0 --name=source-zendesk-chat upgrade_base_image
 airbyte-ci connectors --name=source-auth0 --name=source-zendesk-chat bump_version patch 31643 "Upgrade base image to airbyte/python-connector-base:1.1.0"
```

### CODE REVIEW

**Comment by alafanechere** [comment]
Current dependencies on/for this PR:
* master
  * **PR #31643** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/31643" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/airbytehq/airbyte/31643?utm_source=stack-comment).

**Comment by airbyte-oss-build-runner** [comment]
##  source-auth0 test report (commit [`6225810366`](https://github.com/airbytehq/airbyte/pull/31643/commits/622581036693591d297a2ae02a496dce065abff3)) - ✅

⏲️  Total pipeline duration: 01mn41s 

| Step                                                         | Result   |
|:-------------------------------------------------------------|:---------|
| Build source-auth0 docker image for platform(s) linux/x86_64 | ✅       |
| Acceptance tests                                             | ✅       |
| Code format checks                                           | ✅       |
| Validate metadata for source-auth0                           | ✅       |
| Connector version semver check                               | ✅       |
| QA checks                                                    | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/augustin_10-20-source-zendesk-chat_source-auth0_update_the_base_image/1697792240/622581036693591d297a2ae02a496dce065abff3/source-auth0/0.5.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:622581036693591d297a2ae02a496dce065abff3)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-auth0 test
```

**Comment by bazarnov** [comment]
@alafanechere We need first to merge this in [Source [Hubspot, Zendesk-Support]: fix stream schemas](https://github.com/airbytehq/airbyte/pull/31606#top)

**Comment by alafanechere** [comment]
@bazarnov it's `source-zendesk-chat` in this PR, not `source-zendesk-support`

**Comment by airbyte-oss-build-runner** [comment]
##  source-auth0 test report (commit [`a6c9bee94c`](https://github.com/airbytehq/airbyte/pull/31643/commits/a6c9bee94c7e9544f2614f49a05bafd8bd8695ab)) - ✅

⏲️  Total pipeline duration: 39.94s 

| Step                                                         | Result   |
|:-------------------------------------------------------------|:---------|
| Build source-auth0 docker image for platform(s) linux/x86_64 | ✅       |
| Acceptance tests                                             | ✅       |
| Code format checks                                           | ✅       |
| Validate metadata for source-auth0                           | ✅       |
| Connector version semver check                               | ✅       |
| QA checks                                                    | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/augustin_10-20-source-zendesk-chat_source-auth0_update_the_base_image/1697793404/a6c9bee94c7e9544f2614f49a05bafd8bd8695ab/source-auth0/0.5.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:a6c9bee94c7e9544f2614f49a05bafd8bd8695ab)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-auth0 test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-zendesk-chat test report (commit [`a6c9bee94c`](https://github.com/airbytehq/airbyte/pull/31643/commits/a6c9bee94c7e9544f2614f49a05bafd8bd8695ab)) - ❌

⏲️  Total pipeline duration: 01mn10s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Build source-zendesk-chat docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                          | ✅       |
| Acceptance tests                                                    | ❌       |
| Code format checks                                                  | ✅       |
| Validate metadata for source-zendesk-chat                           | ✅       |
| Connector version semver check                                      | ✅       |
| QA checks                                                           | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/augustin_10-20-source-zendesk-chat_source-auth0_update_the_base_image/1697793404/a6c9bee94c7e9544f2614f49a05bafd8bd8695ab/source-zendesk-chat/0.2.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:a6c9bee94c7e9544f2614f49a05bafd8bd8695ab)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-chat test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-paypal-transaction test report (commit [`a6c9bee94c`](https://github.com/airbytehq/airbyte/pull/31643/commits/a6c9bee94c7e9544f2614f49a05bafd8bd8695ab)) - ✅

⏲️  Total pipeline duration: 01mn11s 

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Build source-paypal-transaction docker image for platform(s) linux/x86_64 | ✅       |
| Acceptance tests                                                          | ✅       |
| Code format checks                                                        | ✅       |
| Validate metadata for source-paypal-transaction                           | ✅       |
| Connector version semver check                                            | ✅       |
| QA checks                                                                 | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/augustin_10-20-source-zendesk-chat_source-auth0_update_the_base_image/1697793404/a6c9bee94c7e9544f2614f49a05bafd8bd8695ab/source-paypal-transaction/2.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:a6c9bee94c7e9544f2614f49a05bafd8bd8695ab)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Review by bazarnov — APPROVED** [review]

**Comment by alafanechere** [comment]
Merging as the `source-zendesk-chat` failure looks related to an "expected records" drift. The difference between base image 1.0.0 and 1.1.0 is only that socat is installed on 1.1.0, which does not relate on how the connector handles records.

**Pull request merged**
