### PR TITLE
:sparkles: Source Gitlab: spec: start date is optional, groups and projects to array

### PR DESCRIPTION
**Pull request by darynaishchenko**
## What
Certification:
- required start date
- groups and projects is string value

## How
- start date marked as optional, in case it's empty all data will be replicated
- added migration for groups and projects to show it array-like on UI (see screenshot bellow)

image

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-gitlab test report (commit [`1bfa640868`](https://github.com/airbytehq/airbyte/pull/31375/commits/1bfa6408688490a3c91f5ee48a76007eebbea04e)) - ❌

⏲️  Total pipeline duration: 40.11s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Build source-gitlab docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ❌        |
| Code format checks                                            | ✅        |
| Validate metadata for source-gitlab                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-gitlab_spec-improvents/1697187717/1bfa6408688490a3c91f5ee48a76007eebbea04e/source-gitlab/1.7.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1bfa6408688490a3c91f5ee48a76007eebbea04e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-gitlab test report (commit [`05a6b0d392`](https://github.com/airbytehq/airbyte/pull/31375/commits/05a6b0d3924d2bd65a1dc128348feb9c169c66a8)) - ✅

⏲️  Total pipeline duration: 12mn28s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Build source-gitlab docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ✅        |
| Acceptance tests                                              | ✅        |
| Code format checks                                            | ✅        |
| Validate metadata for source-gitlab                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-gitlab_spec-improvents/1697198598/05a6b0d3924d2bd65a1dc128348feb9c169c66a8/source-gitlab/1.7.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:05a6b0d3924d2bd65a1dc128348feb9c169c66a8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Review by bazarnov — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-gitlab test report (commit [`ab852ca8bd`](https://github.com/airbytehq/airbyte/pull/31375/commits/ab852ca8bd10aa0476afe16a3279819b15b07ca8)) - ✅

⏲️  Total pipeline duration: 12mn54s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Build source-gitlab docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ✅        |
| Acceptance tests                                              | ✅        |
| Code format checks                                            | ✅        |
| Validate metadata for source-gitlab                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-gitlab_spec-improvents/1697209735/ab852ca8bd10aa0476afe16a3279819b15b07ca8/source-gitlab/1.8.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ab852ca8bd10aa0476afe16a3279819b15b07ca8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-gitlab test report (commit [`43bdf9e8a0`](https://github.com/airbytehq/airbyte/pull/31375/commits/43bdf9e8a05048e42c0aa100ec267cfb87a3872a)) - ✅

⏲️  Total pipeline duration: 12mn47s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Build source-gitlab docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ✅        |
| Acceptance tests                                              | ✅        |
| Code format checks                                            | ✅        |
| Validate metadata for source-gitlab                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-gitlab_spec-improvents/1697211119/43bdf9e8a05048e42c0aa100ec267cfb87a3872a/source-gitlab/1.8.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:43bdf9e8a05048e42c0aa100ec267cfb87a3872a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Pull request merged**
