### PR TITLE
source-hoorayhr contribution from JoeriSmits

### PR DESCRIPTION
**Pull request by JoeriSmits**
## What

This PR adds a new connector for source HoorayHR (source-hoorayhr).

Contributor-provided connector description:

Source connector for HoorayHR (https://hoorayhr.io). The connector uses https://api.hoorayhr.io
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `hoorayhrpassword` | `string` | HoorayHR Password.  |  |
| `hoorayhrusername` | `string` | HoorayHR Username.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| sick-leaves | id | No pagination | ✅ |  ❌  |
| time-off | id | No pagination | ✅ |  ❌  |
| leave-types | id | No pagination | ✅ |  ❌  |
| users | id | No pagination | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by natikgadzhi** [comment]
This is so nice! @JoeriSmits thank you for the connector! 

Can you grab a square SVG icon for HoorayHR and upload it to icon.svg? Once that's done, I'm happy to merge.

**Review by natikgadzhi — APPROVED** [review]

**Comment by JoeriSmits** [comment]
Hi @natikgadzhi ,

Thanks for the merge. Does it takes some time for the connector to appear in the marketplace? I cannot see the source in the marketplace on my Airbyte instance yet.

**Comment by natikgadzhi** [comment]
Around 15 minutes if things build correctly. On airbyte OSS you'd have to restart for it to pick up the new catalog.

**Comment by natikgadzhi** [comment]
But it's alive! https://docs.airbyte.com/integrations/sources/hoorayhr#hoorayhr

**Pull request merged**
