### PR TITLE
source-repairshopr contribution from ombhardwajj

### LINKED ISSUE #47709: [connector-request] Repairshopr
This is a suggestion to create a connector for Repairshopr using the UI Connector Builder.
The website for the connector is https://repairshopr.com/

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to step 3).
3. Describe steps to get credentials.
4. Create the connector using the UI Builder.   

> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> This is a suggestion, and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend following the steps above.

### PR DESCRIPTION
**Pull request by ombhardwajj**
This closes #47709
## What

This PR adds a new connector for source Repairshopr (source-repairshopr).

Contributor-provided connector description:

Repairshopr is a CRM and an integrated marketing platform.
With this connector we can extract data from various streams such as customers , invoices and payments.
Docs : https://api-docs.repairshopr.com/#/
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key.  |  |
| `subdomain` | `string` | subdomain.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| appointment types | id | No pagination | ✅ |  ❌  |
| appointments | id | DefaultPaginator | ✅ |  ❌  |
| customer assets | id | DefaultPaginator | ✅ |  ❌  |
| contacts | id | DefaultPaginator | ✅ |  ❌  |
| contracts | id | DefaultPaginator | ✅ |  ❌  |
| customers | id | DefaultPaginator | ✅ |  ❌  |
| estimates | id | DefaultPaginator | ✅ |  ❌  |
| invoices | id | DefaultPaginator | ✅ |  ❌  |
| items | id | DefaultPaginator | ✅ |  ❌  |
| line items | id | DefaultPaginator | ✅ |  ❌  |
| leads | id | DefaultPaginator | ✅ |  ❌  |
| payments | id | DefaultPaginator | ✅ |  ❌  |
| products | id | DefaultPaginator | ✅ |  ❌  |
| tickets | id | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by ombhardwajj** [comment]
Repairshopr icon is not available as svg , only png is available.

**Comment by marcosmarxm** [comment]
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

Make sure you have pagination properly working, the API doesn't have pagination please left a comment making my review easier.
Make sure have a square svg icon
Make sure credentials are valid.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Connector must have a subdomain and not hard code your sandbox.

`/appointment_types` doesn't have pagination and you added...
`/appointments` has pagination and you didn't implement...

Please check again all endpoints and make sure pagination, limits and incremental are properly configured.

Moving next check to Monday Nov 11

**Comment by ombhardwajj** [comment]
1) I've added a user input for  subdomain instead of it being hardcoded.

2) I think pagination is either not working correctly or docs are outdated.
Currently in docs they've mentioned each page returns 25 results but in practice it is not being followed.(
appointments stream)

3) Please try to review this on priority , if possible today itself as my access to this API is gonna get lost very soon
@marcosmarxm

**Comment by ombhardwajj** [comment]
@marcosmarxm Please review it today 🙏

**Review by marcosmarxm — APPROVED** [review]
Looks `appointments` endpoint has some issue with pagination but I was able to test using `customers` and other endpoints. Connector Looks good

**Pull request merged**
