### PR TITLE
:bug: Source Zendesk Support: use `CDK v.0.1.60` to handle `ConnectionResetError`, increase test coverage

### LINKED ISSUE #12155: 🐛 Source Zendesk Support: Zendesk Support <> Redshift `ConnectionResetError`
## Environment

- **Airbyte version**: 0.35.12
- **OS Version / Instance**: Linux/  AWS EC2
- **Deployment**: example are Docker
- **Source Connector and version**: Zendesk 0.2.5
- **Destination Connector and version**: Redshift 0.3.28
- **Severity**:  Critical
- **Step where error happened**:  Sync job

## [Current``](url)
[logs-37.txt](https://github.com/airbytehq/airbyte/files/8516711/logs-37.txt)

### LINKED ISSUE #12591: 🐛  Source Zendesk Support/Chat: got stuck after 100k records
Is this your first time deploying Airbyte: No
OS Version / Instance: Ubuntu 20.04
Memory / Disk: 8Gb / 100 GB ssd
Deployment: Docker
Airbyte Version: 0.35.61-alpha
Source name/version: airbyte/source-zendesk-chat:0.1.6 (latest)
Destination name/version: airbyte/destination-bigquery: 1.0.5 (latest)
Step: normal sync.
Description: everytime the process starts to sync it freezes after some hours, the same happens with source-zendesk-support:0.2.3 (latest).

See discussion in Discourse: https://discuss.airbyte.io/t/zendesk-chat-and-zendesk-support-freezes-after-some-hours/455

### LINKED ISSUE #13167: 📝 Label `Zendesk Support` as GA in UI

### LINKED ISSUE #13223: 🎉 Source Zendesk Support: Increase `unit_test` coverage up to 90% + edit `docs` to reflect `standard template`
Subtasks:
- [x] increase unit_test coverage up to 90%
- [x] refactor public docs to reflect standard template

### PR DESCRIPTION
**Pull request by davydov-d**
## What
- Update CDK verison in `setup.py` to handle `requests.exceptions.ChunkedEncodingError`
- Increased `unit_test` coverage up to 90%
- Re-factored public docs to reflect `standard template`

### CODE REVIEW

**Review by lazebnyi — CHANGES_REQUESTED** [review]
Need to add more tests to increase tests coverage. Now according to test above - 79%.

**Comment by bazarnov** [comment]
> Need to add more tests to increase tests coverage. Now according to test above - 79%.

These are in progress, will be added to this PR ASAP.

**Review by lazebnyi — APPROVED** [review]

**Pull request merged**
