### PR TITLE
✨ Source Facebook Marketing: Include socat binary in docker image

### PR DESCRIPTION
**Pull request by git-phu**
## What
- Similar to https://github.com/airbytehq/airbyte/pull/30560

This is for
- https://github.com/airbytehq/airbyte-internal-issues/issues/5298
- https://github.com/airbytehq/airbyte-platform-internal/pull/8870

## How
Build and publish source Facebook Marketing to include socat in the docker image.
This will then be used in https://github.com/airbytehq/airbyte-platform-internal/pull/8870

## 🚨 User Impact 🚨
None from this PR alone (socat will be added to the image but won't be used until https://github.com/airbytehq/airbyte-platform-internal/pull/8870 is merged.)

### CODE REVIEW

**Review by gosusnp — COMMENTED** [review]
LGTM but I'd rather make sure someone from connectors take a look.
Looking at the dockerfile, shouldn't we have a base image for python cdk based connectors instead of rebuilding everything from scratch?

**Comment by git-phu** [comment]
> Looking at the dockerfile, shouldn't we have a base image for python cdk based connectors instead of rebuilding everything from scratch?

@gosusnp yes, connector ops is actually in the middle of recreating the bases too, so for general rollout we'll need to add it there.  This is just for testing on specific existing connector Dockerfiles

**Review by erohmensing — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-facebook-marketing test report (commit [`aa32310b16`](https://github.com/airbytehq/airbyte/pull/30706/commits/aa32310b1690e6bf8fd6520e19877369519b2180)) - ✅

⏲️  Total pipeline duration: 102mn27s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ✅        |
| Code format checks                                                               | ✅        |
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/peter_socat-fb-marketing/1695423552/aa32310b1690e6bf8fd6520e19877369519b2180/source-facebook-marketing/1.1.13/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:aa32310b1690e6bf8fd6520e19877369519b2180)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Pull request merged**
