### PR TITLE
documentation(feat): updating collecting metrics page

### PR DESCRIPTION
**Pull request by Jagrutiti**
## What
Updating the `Datadog` section on [Collecting metrics page](https://docs.airbyte.com/operator-guides/collecting-metrics/) page with the help of [ this comment](https://github.com/airbytehq/airbyte/issues/15772#issuecomment-1223090442).

## Closes
Update Collecting metrics page #15772

### CODE REVIEW

**Comment by Jagrutiti** [comment]
Hey @Amruta-Ranade,

Do I have to sign the CLA agreement again? I signed it last time for my first PR.

**Review by Amruta-Ranade — APPROVED** [review]
Thanks for the contribution!

**Comment by Amruta-Ranade** [comment]
> Hey @Amruta-Ranade,
> 
> Do I have to sign the CLA agreement again? I signed it last time for my first PR.

Checking with the team.

**Comment by harshithmullapudi** [comment]
Hey can you check if the account you are using is the same you used to commit?

**Comment by Jagrutiti** [comment]
Hey @harshithmullapudi 

This could be an issue. I did make this PR on my work laptop (I do not have it for the weekend). It must have used my work email id. 

Do I have to make a new PR for this to work?

**Comment by marcosmarxm** [comment]
> Hey @harshithmullapudi
> 
> This could be an issue. I did make this PR on my work laptop (I do not have it for the weekend). It must have used my work email id.
> 
> Do I have to make a new PR for this to work?

Would be simpler I think.

**Comment by Amruta-Ranade** [comment]
@Jagrutiti Hey! Did you open a second PR for this? Or you could add your email to the commit I think

**Comment by Jagrutiti** [comment]
Hey @Amruta-Ranade 

Made this new PR: https://github.com/airbytehq/airbyte/pull/16227

**Pull request closed without merging**
