### PR TITLE
:bug: Source Google Sheets: updated handling 404 and 403 error while discover

### PR DESCRIPTION
**Pull request by darynaishchenko**
## What
resolved: https://github.com/airbytehq/oncall/issues/2635
`Could not run discovery: <HttpError 403 when requesting...`

## How
Handled 404 and 403 error in discover as config error and added user-friendly message.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-google-sheets test report (commit [`7755996890`](https://github.com/airbytehq/airbyte/pull/29327/commits/7755996890a68708b9de3915388c4c914cf84405)) - ✅

⏲️  Total pipeline duration: 04mn29s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-google-sheets/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ✅        |
| QA checks                                                                   | ✅        |
| Code format checks                                                          | ✅        |
| Connector package install                                                   | ✅        |
| Build source-google-sheets docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Acceptance tests                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-google-sheets_403-while-requesting-sheet/1691669440/7755996890a68708b9de3915388c4c914cf84405/source-google-sheets/0.3.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7755996890a68708b9de3915388c4c914cf84405)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-sheets test
```

**Comment by octavia-squidington-iii** [comment]
##  source-google-sheets test report (commit [`a5262e5a3a`](https://github.com/airbytehq/airbyte/pull/29327/commits/a5262e5a3acb02ec336c1a7ac3d423f5795cd03a)) - ✅

⏲️  Total pipeline duration: 04mn19s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-google-sheets/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ✅        |
| QA checks                                                                   | ✅        |
| Code format checks                                                          | ✅        |
| Connector package install                                                   | ✅        |
| Build source-google-sheets docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Acceptance tests                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-google-sheets_403-while-requesting-sheet/1691669844/a5262e5a3acb02ec336c1a7ac3d423f5795cd03a/source-google-sheets/0.3.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:a5262e5a3acb02ec336c1a7ac3d423f5795cd03a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-sheets test
```

**Review by bazarnov — APPROVED** [review]
LGTM, right after the unit_test is added to cover these cases.

**Comment by octavia-squidington-iii** [comment]
##  source-google-sheets test report (commit [`389ee787d3`](https://github.com/airbytehq/airbyte/pull/29327/commits/389ee787d39d3d1139fa0c1d47a6463123019464)) - ✅

⏲️  Total pipeline duration: 06mn07s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-google-sheets/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ✅        |
| QA checks                                                                   | ✅        |
| Code format checks                                                          | ✅        |
| Connector package install                                                   | ✅        |
| Build source-google-sheets docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Acceptance tests                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-google-sheets_403-while-requesting-sheet/1691741794/389ee787d39d3d1139fa0c1d47a6463123019464/source-google-sheets/0.3.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:389ee787d39d3d1139fa0c1d47a6463123019464)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-sheets test
```

**Review by bazarnov — APPROVED** [review]

**Pull request merged**
