### PR TITLE
🎉 Source Square: Update airbyte-cdk version to >=0.51.31

### PR DESCRIPTION
**Pull request by yevhenii-ldv**
## What
*Update `airbyte-cdk` version to `>=0.51.31` for connector Square.*
*(part of #23926 issue)*

## How
*Update `setup.py`*

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Unit & integration tests added
- [x] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [x] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-square test report (commit [`4d11b01bda`](https://github.com/airbytehq/airbyte/pull/30960/commits/4d11b01bda057868d310bf074fbb77764c13fe18)) - ✅

⏲️  Total pipeline duration: 30mn30s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Connector package install                                  | ✅        |
| Build source-square docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                 | ✅        |
| Acceptance tests                                           | ✅        |
| Code format checks                                         | ✅        |
| Validate metadata for source-square                        | ✅        |
| Connector version semver check                             | ✅        |
| Connector version increment check                          | ✅        |
| QA checks                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ykurochkin_source-square-set-token-expiry-is-time-of-expiration/1696113126/4d11b01bda057868d310bf074fbb77764c13fe18/source-square/1.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:4d11b01bda057868d310bf074fbb77764c13fe18)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-square test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-square test report (commit [`b01c1244e8`](https://github.com/airbytehq/airbyte/pull/30960/commits/b01c1244e8ffec0a7c5c674d603ff2fc9717880d)) - ✅

⏲️  Total pipeline duration: 29mn45s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Connector package install                                  | ✅        |
| Build source-square docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                 | ✅        |
| Acceptance tests                                           | ✅        |
| Code format checks                                         | ✅        |
| Validate metadata for source-square                        | ✅        |
| Connector version semver check                             | ✅        |
| Connector version increment check                          | ✅        |
| QA checks                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ykurochkin_source-square-set-token-expiry-is-time-of-expiration/1696241910/b01c1244e8ffec0a7c5c674d603ff2fc9717880d/source-square/1.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b01c1244e8ffec0a7c5c674d603ff2fc9717880d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-square test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-square test report (commit [`85418d211a`](https://github.com/airbytehq/airbyte/pull/30960/commits/85418d211a1f24ddcfda203e15cb92f7e3e59a11)) - ❌

⏲️  Total pipeline duration: 37.05s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Connector package install                                     | ✅        |
| Build source-square docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ❌        |
| Code format checks                                            | ✅        |
| Validate metadata for source-square                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ykurochkin_source-square-set-token-expiry-is-time-of-expiration/1696950250/85418d211a1f24ddcfda203e15cb92f7e3e59a11/source-square/1.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:85418d211a1f24ddcfda203e15cb92f7e3e59a11)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-square test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-square test report (commit [`5042278a42`](https://github.com/airbytehq/airbyte/pull/30960/commits/5042278a42a4790ceeb0d43a7cdb93ec45f9b302)) - ❌

⏲️  Total pipeline duration: 01mn26s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Connector package install                                     | ✅        |
| Build source-square docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ❌        |
| Code format checks                                            | ✅        |
| Validate metadata for source-square                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ykurochkin_source-square-set-token-expiry-is-time-of-expiration/1696950574/5042278a42a4790ceeb0d43a7cdb93ec45f9b302/source-square/1.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:5042278a42a4790ceeb0d43a7cdb93ec45f9b302)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-square test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-square test report (commit [`57287f0078`](https://github.com/airbytehq/airbyte/pull/30960/commits/57287f0078d44c88bdba1103aa7c3b01b77d5bd8)) - ❌

⏲️  Total pipeline duration: 12mn18s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Connector package install                                     | ✅        |
| Build source-square docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ✅        |
| Acceptance tests                                              | ❌        |
| Code format checks                                            | ✅        |
| Validate metadata for source-square                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ykurochkin_source-square-set-token-expiry-is-time-of-expiration/1696968603/57287f0078d44c88bdba1103aa7c3b01b77d5bd8/source-square/1.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:57287f0078d44c88bdba1103aa7c3b01b77d5bd8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-square test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-square test report (commit [`893421332c`](https://github.com/airbytehq/airbyte/pull/30960/commits/893421332ceaa7efb478d0bf2cd1221d1e4279b6)) - ✅

⏲️  Total pipeline duration: 31mn17s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Connector package install                                     | ✅        |
| Build source-square docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ✅        |
| Acceptance tests                                              | ✅        |
| Code format checks                                            | ✅        |
| Validate metadata for source-square                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ykurochkin_source-square-set-token-expiry-is-time-of-expiration/1697023973/893421332ceaa7efb478d0bf2cd1221d1e4279b6/source-square/1.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:893421332ceaa7efb478d0bf2cd1221d1e4279b6)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-square test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-square test report (commit [`57287f0078`](https://github.com/airbytehq/airbyte/pull/30960/commits/57287f0078d44c88bdba1103aa7c3b01b77d5bd8)) - ❌

⏲️  Total pipeline duration: 12mn15s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Build source-square docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ✅        |
| Acceptance tests                                              | ❌        |
| Code format checks                                            | ✅        |
| Validate metadata for source-square                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ykurochkin_source-square-set-token-expiry-is-time-of-expiration/1697032928/57287f0078d44c88bdba1103aa7c3b01b77d5bd8/source-square/1.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:57287f0078d44c88bdba1103aa7c3b01b77d5bd8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-square test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-pokeapi test report (commit [`453e9745c7`](https://github.com/airbytehq/airbyte/pull/30960/commits/453e9745c7c216d3b773a9b910de3d656f465e54)) - ✅

⏲️  Total pipeline duration: 51.95s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build source-pokeapi docker image for platform(s) linux/x86_64 | ✅        |
| Acceptance tests                                               | ✅        |
| Code format checks                                             | ✅        |
| Validate metadata for source-pokeapi                           | ✅        |
| Connector version semver check                                 | ✅        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ykurochkin_source-square-set-token-expiry-is-time-of-expiration/1697045071/453e9745c7c216d3b773a9b910de3d656f465e54/source-pokeapi/0.2.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:453e9745c7c216d3b773a9b910de3d656f465e54)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-pokeapi test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-square test report (commit [`453e9745c7`](https://github.com/airbytehq/airbyte/pull/30960/commits/453e9745c7c216d3b773a9b910de3d656f465e54)) - ✅

⏲️  Total pipeline duration: 31mn12s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Build source-square docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ✅        |
| Acceptance tests                                              | ✅        |
| Code format checks                                            | ✅        |
| Validate metadata for source-square                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ykurochkin_source-square-set-token-expiry-is-time-of-expiration/1697045071/453e9745c7c216d3b773a9b910de3d656f465e54/source-square/1.1.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:453e9745c7c216d3b773a9b910de3d656f465e54)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-square test
```

**Review by girarda — APPROVED** [review]

**Pull request merged**
