### PR TITLE
🎉 New Destination: bit.io

### PR DESCRIPTION
**Pull request by adamf**
## What
Adds a connector for bit.io, a serverless database platform based on Postgres.

## How
Creates a `SpecModifiyingDestination` from the Postgres destination which hardcodes the host, port, and ssl options to the bit.io service. 

Also fixes a bug in the PostgresDestination where the database name wasn't been URI escaped during the creation of the JDBC URL. Database names can and do have characters that must be URI escaped (such as `/` or `~`). It's likely this bug exists for all Postgres-compatible connectors (and others; I'm not sure the database name limitations on Oracle/MySQL/etc). 

## Recommended reading order
1. `BitDotIoDestination.java`

## User Impact 
No breaking changes.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [X] Secrets in the connector's spec are annotated with `airbyte_secret`
- [X] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [X] Documentation updated
    - [X] Connector's `README.md`
    - [X] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [X] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [X ] `docs/integrations/README.md`
    - [X] `airbyte-integrations/builds.md`
- [ X] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

https://gist.github.com/adamf/aa7a9f125ebd9e3098a053945f76fdea

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks for the contribution @adamf my suggestion is to break the PR first to solve the JDBC URI encoding and adding the bit.io if not the review can become messy.

**Comment by adamf** [comment]
> Thanks for the contribution @adamf my suggestion is to break the PR first to solve the JDBC URI encoding and adding the bit.io if not the review can become messy.

Will do!

**Comment by adamf** [comment]
> Thanks for the contribution @adamf my suggestion is to break the PR first to solve the JDBC URI encoding and adding the bit.io if not the review can become messy.

Put the Postgres fix in https://github.com/airbytehq/airbyte/pull/16046

**Comment by marcosmarxm** [comment]
Thanks @adamf I asked the team to review the other contribution first. I'll create the sandbox account for bit.io to run integration tests here.

**Comment by marcosmarxm** [comment]
Waiting #16046 to be merged.

**Comment by marcosmarxm** [comment]
@adamf only one test is not passing: `testSpecGet` besides that the PR looks great! I'm OOO today so I'll finish monday this review.

**Review by marcosmarxm — APPROVED** [review]

**Comment by marcosmarxm** [comment]
@adamf the connector is working! only a small problem with publish command.

**Pull request merged**
