### PR TITLE
🎉 New Destination: Convex

### PR DESCRIPTION
**Pull request by emmaling27**
## What
I work at Convex, where we're building a platform for building apps. We already have a Convex source connector, and we'd like to add a Convex destination connector.

This PR adds a new destination connector to import data into Convex (https://convex.dev/).

## How
1. Generate a new connector from the [Python CDK tutorial](https://docs.airbyte.com/connector-development/tutorials/cdk-tutorial-python-http/getting-started)
2. Created new endpoints in the Convex API: `/clear_tables`, `/airbyte_ingress`
3. Updated the new connector to use the APIs, until `check` and `write` work
4. Wrote unit tests with mock responses for Convex API.

## Recommended reading order
1. `destination_convex/spec.json`
2. `destination_convex/destination.py`
3. `destination_convex/writer.py`
4. `destination_convex/client.py`
5. `integration_tests/integration_test.py`

## 🚨 User Impact 🚨
New destination connector in release stage "alpha".

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [X] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [X] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

Unit test output:
```
=========================================================================================================== test session starts ===========================================================================================================
platform darwin -- Python 3.9.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/emmaling/Projects/airbyte/airbyte-integrations/connectors/destination-convex/.venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/emmaling/Projects/airbyte, configfile: pytest.ini
collected 2 items                                                                                                                                                                                                                         

unit_tests/unit_test.py::test_check PASSED
unit_tests/unit_test.py::test_write PASSED

============================================================================================================ 2 passed in 0.22s ===========================================================================================================
```
</details>

### CODE REVIEW

**Comment by emmaling27** [comment]
In addition to the unit tests, I've run airbyte locally to test end-to-end. I ran into an issue while testing with a Postgres source connector with CDC enabled. Would love some help since it does not seem like a destination bug! See the conversation [here](https://airbytehq.slack.com/archives/C021JANJ6TY/p1673388124360209)

**Comment by natalyjazzviolin** [comment]
@emmaling27 could you double check that edit access has been granted to maintainers?

**Comment by emmaling27** [comment]
> @emmaling27 could you double check that edit access has been granted to maintainers?

yep, maintainers should already have access, assuming this is the correct setting:
Screenshot 2023-03-03 at 2 03 25 PM

**Comment by natalyjazzviolin** [comment]
@emmaling27 got it, thanks! I'm checking the build on a non-forked PR and adding credentials on the CI. Could you run this to fix the formatting errors?
`./gradlew --no-daemon  :airbyte-integrations:connectors:<connector_name>:airbytePythonFormat`

**Comment by emmaling27** [comment]
> @emmaling27 got it, thanks! I'm checking the build on a non-forked PR and adding credentials on the CI. Could you run this to fix the formatting errors? `./gradlew --no-daemon :airbyte-integrations:connectors:<connector_name>:airbytePythonFormat`

@natalyjazzviolin done! thanks for taking the time to review. I was trying to double check everything works after a rebase by running the platform locally myself, and I got stuck because I couldn't manage to get the platform running with the local catalog with my connector added. More details [here](https://airbytehq.slack.com/archives/C027KKE4BCZ/p1678128871621819). Seems like a lot has changed since the platform has been pulled out into a separate repo!

**Comment by grishick** [comment]
@natalyjazzviolin correct me if I am wrong - I think we don't need new connector contribution to include changes to seed files until we run `publish` command. AFAIK, CI will fail, because it will look for connector specified in `destination_definitions.yaml` on Dockerhub and will not find it - that's why `publish` command adds that information to `destination_definitions.yaml` after it successfully publishes the new image to Dockerhub. It's been a while since I added a new connector though, so I defer to you.

**Comment by emmaling27** [comment]
> @natalyjazzviolin correct me if I am wrong - I think we don't need new connector contribution to include changes to seed files until we run `publish` command. AFAIK, CI will fail, because it will look for connector specified in `destination_definitions.yaml` on Dockerhub and will not find it - that's why `publish` command adds that information to `destination_definitions.yaml` after it successfully publishes the new image to Dockerhub. It's been a while since I added a new connector though, so I defer to you.

Hmm, adding the new connector to `destination_definitions.yaml` appears to be a step in [docs](https://docs.airbyte.com/connector-development/tutorials/building-a-python-source#creating-a-source) for making a new source connector, but not a destination connector. I don't understand why they would be different, and I don't know how the platform would be able to list the new destination in the catalog without it in the `destination_definitions.yaml` file based on [these docs](https://docs.airbyte.com/connector-development/testing-connectors/testing-a-local-catalog-in-development).

**Comment by grishick** [comment]
> > @natalyjazzviolin correct me if I am wrong - I think we don't need new connector contribution to include changes to seed files until we run `publish` command. AFAIK, CI will fail, because it will look for connector specified in `destination_definitions.yaml` on Dockerhub and will not find it - that's why `publish` command adds that information to `destination_definitions.yaml` after it successfully publishes the new image to Dockerhub. It's been a while since I added a new connector though, so I defer to you.
> 
> Hmm, adding the new connector to `destination_definitions.yaml` appears to be a step in [docs](https://docs.airbyte.com/connector-development/tutorials/building-a-python-source#creating-a-source) for making a new source connector, but not a destination connector. I don't understand why they would be different, and I don't know how the platform would be able to list the new destination in the catalog without it in the `destination_definitions.yaml` file based on [these docs](https://docs.airbyte.com/connector-development/testing-connectors/testing-a-local-catalog-in-development).

OK, I checked with the ops team and I take back my comment. These changes are needed when adding a new connector

**Comment by grishick** [comment]
CI checks passed in this pr: https://github.com/airbytehq/airbyte/pull/23889. Running integration tests

**Review by grishick — APPROVED** [review]

**Comment by grishick** [comment]
@natalyjazzviolin I am out for a week. Feel free to publish this new connector and merge this PR in the meantime if you have the time. Otherwise, I will publish and merge when I get back on 3/16

**Comment by emmaling27** [comment]
> @natalyjazzviolin I am out for a week. Feel free to publish this new connector and merge this PR in the meantime if you have the time. Otherwise, I will publish and merge when I get back on 3/16

@natalyjazzviolin I would want to confirm that dedup sync mode is working (see the bug I reported [here](https://github.com/airbytehq/airbyte/pull/21287#issuecomment-1379709424)) before merging. Unfortunately, I haven't been able to rebase and successfully access the connector locally (see my comment [here](https://github.com/airbytehq/airbyte/pull/21287#issuecomment-1457254548)). Have you been able to successfully run a sync to a convex deployment in incremental dedup mode from this PR?

**Comment by grishick** [comment]
publishing here: https://github.com/airbytehq/airbyte/pull/23889#issuecomment-1472429885

**Review by grishick — CHANGES_REQUESTED** [review]
Failing test:
```
> Task :airbyte-integrations:connectors:destination-convex:_unitTestCoverage FAILED
[python] .venv/bin/python -m coverage run --data-file=unit_tests/.coverage.unitTest --rcfile=/actions-runner/_work/airbyte/airbyte/pyproject.toml -m pytest -s unit_tests -c /actions-runner/_work/airbyte/airbyte/pyproject.toml
	 ============================= test session starts ==============================
	 platform linux -- Python 3.9.16, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /actions-runner/_work/airbyte/airbyte/airbyte-integrations/connectors/destination-convex/.venv/bin/python
	 cachedir: .pytest_cache
	 rootdir: /actions-runner/_work/airbyte/airbyte/airbyte-integrations/connectors/destination-convex/unit_tests, configfile: ../../../../pyproject.toml
	 collecting ... collected 3 items
	 
	 unit_tests/unit_test.py::test_bad_write ERROR
	 unit_tests/unit_test.py::test_check ERROR
	 unit_tests/unit_test.py::test_write ERROR
	 
	 ==================================== ERRORS ====================================
	 _______________________ ERROR at setup of test_bad_write _______________________
	 
	     @pytest.fixture(name="config")
	     def config_fixture() -> ConvexConfig:
	 >       with open("secrets/local_config.json", "r") as f:
	 E       FileNotFoundError: [Errno 2] No such file or directory: 'secrets/local_config.json'
	 
	 unit_tests/unit_test.py:32: FileNotFoundError
	 _________________________ ERROR at setup of test_check _________________________
	 
	     @pytest.fixture(name="config")
	     def config_fixture() -> ConvexConfig:
	 >       with open("secrets/local_config.json", "r") as f:
	 E       FileNotFoundError: [Errno 2] No such file or directory: 'secrets/local_config.json'
	 
	 unit_tests/unit_test.py:32: FileNotFoundError
	 _________________________ ERROR at setup of test_write _________________________
	 
	     @pytest.fixture(name="config")
	     def config_fixture() -> ConvexConfig:
	 >       with open("secrets/local_config.json", "r") as f:
	 E       FileNotFoundError: [Errno 2] No such file or directory: 'secrets/local_config.json'
	 
	 unit_tests/unit_test.py:32: FileNotFoundError
	 =========================== short test summary info ============================
	 ERROR unit_tests/unit_test.py::test_bad_write - FileNotFoundError: [Errno 2] ...
	 ERROR unit_tests/unit_test.py::test_check - FileNotFoundError: [Errno 2] No s...
	 ERROR unit_tests/unit_test.py::test_write - FileNotFoundError: [Errno 2] No s...
	 ============================== 3 errors in 0.51s ===============================

FAILURE: Build failed with an exception.
```

**Comment by emmaling27** [comment]
@grishick that test should be fixed now! @ldanilek and I also updated the destination to use a new API endpoint `replace_tables` in overwrite sync mode. We are still seeing this [airbyte bug](https://discuss.airbyte.io/t/incremental-dedup-sync-hangs-until-timeout-after-sync-is-complete/3656) while running a sync from a postgres source to a convex destination locally. Is this good to merge?

**Comment by grishick** [comment]
I merged master and re-running tests here: https://github.com/airbytehq/airbyte/pull/23889

**Comment by grishick** [comment]
Thank you for the contribution! I merged these changes in this PR: https://github.com/airbytehq/airbyte/pull/23889

**Pull request closed without merging**
