### PR TITLE
🎉  Source Facebook Marketing: Added level into custom ads insights

### PR DESCRIPTION
**Pull request by carlonuccio**
## What
By default, we have 'ad' as level for custom ads insights. This PR will enable to choice which level we want data, account/campaign/adset/ad level. By default still remain ad.

## How
In custom ads insights, added a parameter Level.

## Recommended reading order
1. `spec.py`
2. `source.py`
3. `base_insights_streams.py`
4. `test_base_insights_streams.py`

## 🚨 User Impact 🚨
By default, it will have the same behaviour as is.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by carlonuccio** [comment]
`Name                                                        Stmts   Miss  Cover
-------------------------------------------------------------------------------
source_facebook_marketing/utils.py                             24      0   100%
source_facebook_marketing/streams/common.py                    44      0   100%
source_facebook_marketing/streams/async_job.py                217      0   100%
source_facebook_marketing/streams/__init__.py                   2      0   100%
source_facebook_marketing/spec.py                              42      0   100%
source_facebook_marketing/__init__.py                           2      0   100%
source_facebook_marketing/source.py                            49      1    98%
source_facebook_marketing/streams/async_job_manager.py         78      3    96%
source_facebook_marketing/api.py                               96      9    91%
source_facebook_marketing/streams/base_insight_streams.py     137     14    90%
source_facebook_marketing/streams/base_streams.py             138     30    78%
source_facebook_marketing/streams/streams.py                  118     27    77%
-------------------------------------------------------------------------------
TOTAL                                                         947     84    91%
`

**Comment by sathiscode** [comment]
Hi @carlonuccio  Can you please sign CLA.

**Comment by carlonuccio** [comment]
> Hi @carlonuccio Can you please sign CLA.

Signed

**Comment by sathiscode** [comment]
Hi @carlonuccio Looks like you have used 2 logins for code commit and only one of them is CLA signed. Can you please CLA sign the other login also. Please refer https://github.com/airbytehq/airbyte/pull/19116#issuecomment-1307066916

image

**Comment by carlonuccio** [comment]
> Hi @carlonuccio Looks like you have used 2 logins for code commit and only one of them is CLA signed. Can you please CLA sign the other login also. Please refer [#19116 (comment)](https://github.com/airbytehq/airbyte/pull/19116#issuecomment-1307066916)
> 
> image

Signed also with other account. Sorry for this.

**Comment by sathiscode** [comment]
@carlonuccio Can you please check the CLA signing again. Still the automated test shows one cla pending. Apart from that, the code looks good to me.

**Comment by mk-nuccioc** [comment]
> @carlonuccio Can you please check the CLA signing again. Still the automated test shows one cla pending. Apart from that, the code looks good to me.

It's still me but probably I didn't set the email for the commit. Can I fix it? or if you want, I will close this PR and open new one.

**Comment by mk-nuccioc** [comment]
@sathiscode I've opened another PR with correct committers https://github.com/airbytehq/airbyte/pull/19141

**Pull request closed without merging**
