### PR TITLE
throw exception if we close engine before snapshot is complete + increase timeout for subsequent records

### PR DESCRIPTION
**Pull request by subodh1810**
In this slack thread, https://airbytehq.slack.com/archives/C01MFR03D5W/p1626126903240900?thread_ts=1626122544.233800&cid=C01MFR03D5W a user reported that for postgres CDC their connector doesnt sync complete data and just dies off. On observing the logs we see that 
```
2021-07-12 21:41:46 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-12 21:41:46 [32mINFO[m i.d.e.EmbeddedEngine(stop):996 - {} - Stopping the embedded engine
2021-07-12 21:41:46 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-12 21:41:46 [32mINFO[m i.d.e.EmbeddedEngine(stop):1004 - {} - Waiting for PT5M for connector to stop
2021-07-12 21:41:46 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-12 21:41:46 [32mINFO[m i.d.c.c.BaseSourceTask(stop):192 - {} - Stopping down connector
2021-07-12 21:41:47 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-12 21:41:47 [33mWARN[m i.d.p.s.AbstractSnapshotChangeEventSource(execute):77 - {} - Snapshot was interrupted before completion
2021-07-12 21:41:47 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-12 21:41:47 [32mINFO[m i.d.p.s.AbstractSnapshotChangeEventSource(execute):85 - {} - Snapshot - Final stage
2021-07-12 21:41:47 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-12 21:41:47 [33mWARN[m i.d.p.ChangeEventSourceCoordinator(lambda$start$0):118 - {} - Change event source executor was interrupted
2021-07-12 21:41:47 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - java.lang.InterruptedException: Interrupted while snapshotting table webapp.loan_applications
2021-07-12 21:41:47 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.debezium.relational.RelationalSnapshotChangeEventSource.createDataEventsForTable(RelationalSnapshotChangeEventSource.java:327) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
2021-07-12 21:41:47 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.debezium.relational.RelationalSnapshotChangeEventSource.createDataEvents(RelationalSnapshotChangeEventSource.java:284) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
2021-07-12 21:41:47 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.debezium.relational.RelationalSnapshotChangeEventSource.doExecute(RelationalSnapshotChangeEventSource.java:137) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
2021-07-12 21:41:47 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:71) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
2021-07-12 21:41:47 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:105) ~[debezium-core-1.4.2.Final.jar:1.4.2.Final]
2021-07-12 21:41:47 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
2021-07-12 21:41:47 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
2021-07-12 21:41:47 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
2021-07-12 21:41:47 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
2021-07-12 21:41:47 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at java.lang.Thread.run(Thread.java:832) [?:?]
```
The debezium engine is being closed while in snapshot mode and as a result this stacktrace pops up. 

I and @Phlair looked into it together and we were able to reproduce it. Our hypothesis is that for some reason debezium engine doesnt return records within 5 seconds and as a result, Airbyte asks debezium to shut down. Thats why we are increasing the timeout from 5 seconds to 1 minute. 

Secondly we would want the connector to fail in case the engine shutsdown before snapshot is complete and thats why we have added an extra check

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the checklist which is relevant for this PR. 

<details><summary> <strong> Connector checklist </strong> </summary>
<p>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Secrets are annotated with `airbyte_secret` in the connector's spec
- [ ] Credentials added to Github CI if needed and not already present. [instructions for injecting secrets into CI](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#using-credentials-in-ci). 
- [ ] Unit & integration tests added as appropriate (and are passing)
    * Community members: please provide proof of this succeeding locally e.g: screenshot or copy-paste acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] `/test connector=connectors/<name>` command as documented [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-an-existing-connector) is passing. 
    * Community members can skip this, Airbyters will run this for you. 
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] `README.md`
    - [ ] `docs/SUMMARY.md` if it's a new connector
    - [ ] Created or updated reference docs in `docs/integrations/<source or destination>/<name>`.
    - [ ] Changelog in the appropriate page in `docs/integrations/...`. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md` contains a reference to the new connector
    - [ ] Build status added to [build page](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md)
- [ ] Build is successful
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] No major blockers
- [ ] PR merged into master branch
- [ ] Follow up tickets have been created
- [ ] Associated tickets have been closed & stakeholders notified
</p>
</details>

<details><summary> <strong> Connector Generator checklist </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by Phlair — APPROVED** [review]
Code changes lgtm. Should we run the tests against cdc sources just to be safe?

**Comment by subodh1810** [comment]
I did run the cdc tests for postgres, they passed, anyway while publishing the image for postgres all the tests would run

**Review by sherifnada — APPROVED** [review]
this LGTM but could you add comments to the code explaining the context behind our closing logic? Specifically the items we discussed offline: 

- debezium is meant more for always-on syncs so it doesn't have strong mechanisms to notify of a sync's ending
- we use targetPos to know when to end the sync, but there are situaions where it doesn't work
- so we use timeouts. but because this is not perfect (timeout != sync is complete) we also check if snapshot is false and use that to end the sync. See the debezium docs for more info on what snapshot means and when it is set to true vs false

**Pull request merged**
