### PR TITLE
source-google-ads: Fix type of `google_ads_campaign_budget`.`status`

### LINKED ISSUE #30988: Bigquery Paritions should only be on the first PK

### PR DESCRIPTION
**Pull request by evantahler**
Closes https://github.com/airbytehq/airbyte/issues/30988
Closes https://github.com/airbytehq/oncall/issues/3103 (source-google-ads)
Closes https://github.com/airbytehq/oncall/issues/3036 (source-google-ads)
Closes https://github.com/airbytehq/oncall/issues/3109 (source-google-ads)

Learn more in [Slack](https://airbytehq-team.slack.com/archives/C02U9R3AF37/p1696273664990779)

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-google-ads test report (commit [`f2cbfd1911`](https://github.com/airbytehq/airbyte/pull/30997/commits/f2cbfd19114ac27de3504f8468efcb4e5aa763ab)) - ❌

⏲️  Total pipeline duration: 09mn18s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Connector package install                                      | ✅        |
| Build source-google-ads docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                     | ✅        |
| Acceptance tests                                               | ❌        |
| Code format checks                                             | ✅        |
| Validate metadata for source-google-ads                        | ✅        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ✅        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_source-goolge-adds-array/1696282434/f2cbfd19114ac27de3504f8468efcb4e5aa763ab/source-google-ads/1.0.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f2cbfd19114ac27de3504f8468efcb4e5aa763ab)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-ads test
```

**Comment by evantahler** [comment]
Hmm... the failing tests does imply that campaign_budget.type really might be an array 🤔 

```
E                   'campaign_budget.type':     'campaign_budget.type':  
E                 [                           [                          
E                    'STANDARD',                 'STANDARD',             
E                   ],                          ],             
```

**Comment by evantahler** [comment]
I guess... this is a breaking chnage?

```
E                   'campaign_budget.status'    'campaign_budget.status' 
E                 : ^'REMOVED',                : ^[                        
E                                             +   'REMOVED',              
E                                             +  ],         
```

**Review by jbfbell — APPROVED** [review]

**Comment by tolik0** [comment]
@evantahler Thank you for your PR. However, the issue stems from `segments.budget_campaign_association_status.status`. I'll create a new PR and a few other fixes to address this. So that you know, this is a breaking change.

**Comment by evantahler** [comment]
Thanks @tolik0 - please close this PR then and link your new one!

**Comment by evantahler** [comment]
Ping! @tolik0 do you have that other PR?

**Comment by tolik0** [comment]
@evantahler yes, PR is ready, but I am still waiting for review

**Comment by tolik0** [comment]
@evantahler yes, PR is ready, but I am still waiting for review https://github.com/airbytehq/airbyte/pull/31048

**Comment by evantahler** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/pull/31048

**Pull request closed without merging**
