### PR TITLE
🐛 Change null cursor value query to not use IIF sql function

### PR DESCRIPTION
**Pull request by rodireich**
## What
Our null cursor value query is using the `IIF` sql function that is not available on Azure Synapse Analytics sql servers (see https://learn.microsoft.com/en-us/sql/t-sql/functions/logical-functions-iif-transact-sql?view=sql-server-ver16#remarks)
This PR changes the query to use a simpler sql avoiding this command.

## How
Edit the null cursor value query to syntax that is acceptable by all sql servers.

### CODE REVIEW

**Review by stephane-airbyte — APPROVED** [review]

**Comment by rodireich** [comment]
> we really should think of ways to add tests for all those different flavors of SQL server. This comes just after a community PR about fixing our handling of azure servers.

Connector acceptance test is I think the answer. architecture uses an external server and is designed to be a minimal functional pass - a smoke test.
Having it run against each supported version should make similar regression visible.

The work we need to do is:
1. Part of that test suite is not working with java connectors.
2. I'm not sure how to make it work with multiple servers as it is built I think as 1:1

**Comment by rodireich** [comment]
In the meantime @evantahler , @postamar , @stephane-airbyte can I ask one of you to merge this PR in to update the beta

**Comment by octavia-approvington** [comment]
Our work here is done <br/> done

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
