### PR TITLE
use COPY for Postgres

### PR DESCRIPTION
**Pull request by jrhizor**
Uses copy manager for Postgres. Even in smaller files (500k rows / 50mb) this results in a 25% speedup. This would likely improve if we could get our actual batch size closer to our max batch size.

The insert in `DefaultSqlOperations` is already Postgres-specific, which is why I stuck it here. I'm treating that refactor as beyond the scope of this PR.

Fortunately/unfortunately this is a much simpler PR than what I started with. Since there doesn't seem to be a downside for smallish files I'm dropping the optionality and making this the main way of copying for postgres.

### CODE REVIEW

**Comment by davinchia** [comment]
Drive-by as Subodh and I were discussing the MySQL destination's COPY and peeked at this PR. This looks great!

Are there any planned follow up to this? From Redshift experience, I think we'll quickly run into users asking for more configurability around Copy operations as the table sizes get bigger and bigger.

**Review by ChristopheDuong — APPROVED** [review]

**Comment by jrhizor** [comment]
> Are there any planned follow up to this? From Redshift experience, I think we'll quickly run into users asking for more configurability around Copy operations as the table sizes get bigger and bigger.

There's simple refactor followup: https://github.com/airbytehq/airbyte/issues/3208

There are still a ton of scalability improvements we can do. When reading from a file, we aren't remotely close to hitting the 10k max batch size limit in most writes. We should probably be more aggressive to push towards larger batches, especially if we're going to go for higher (100k, 1mil, 1bil) limits.

Thread parallelism is another lever we can use. The most obvious case is to parallelize between streams.

Another big problem is resource management. Especially as we head towards Kubernetes, we're going to have to be able to recommend disk/memory settings based on what is configured.

**Review by michel-tricot — COMMENTED** [review]
I think writing to the local disk of the container will bite us in the future.

Do you have a sense of the limitations of this approach? (both on local docker & K8s)

**Comment by jrhizor** [comment]
This is only writing individual batches at the moment, not anything close to the full file, so I would expect that it wouldn't hit into many limits on local docker or k8s. Here we could use something in-memory to hold it, but it seems like we've run into fewer disk space issues than memory issues which is why I chose this direction.

I think the only way we start hitting limits is if we significantly increase our batch sizes or process streams in parallel. Then we will have to revisit some of the queueing mechanisms everywhere.

**Comment by michel-tricot** [comment]
Keep in mind that it might be inefficient because when you write on the local FS, it writes through the `overlay` driver

For something with a lot of reads and writes that could become a no go

**Pull request merged**
