### PR TITLE
source-missive contribution from btkcodedev

### PR DESCRIPTION
**Pull request by btkcodedev**
## What

This PR adds a new connector for source Missive (source-missive).

Contributor-provided connector description:

Website: https://missiveapp.com/
API Docs: https://missiveapp.com/help/api-documentation/rest-endpoints
Auth Docs: https://missiveapp.com/help/api-documentation/getting-started
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key.  |  |
| `limit` | `string` | Limit. Max records per page limit | 50 |
| `start_date` | `string` | Start date.  |  |
| `kind` | `string` | Kind. Kind parameter for `contact_groups` stream | group |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| contact_books | id | DefaultPaginator | ✅ |  ❌  |
| contacts | id | DefaultPaginator | ✅ |  ✅  |
| contact_groups | id | DefaultPaginator | ✅ |  ❌  |
| users | id | DefaultPaginator | ✅ |  ❌  |
| teams | id | DefaultPaginator | ✅ |  ❌  |
| shared_labels | id | DefaultPaginator | ✅ |  ❌  |
| organizations | id | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by natikgadzhi** [comment]
This needs the conversations stream. If we can't make it via builder because of testing data, I'd settle on the manifest file uploaded directly to the PR via export @btkcodedev

**Comment by btkcodedev** [comment]
That a statement which I could live with, relaxed: 
I am missing out some streams because it couldn't be seeded


`Conversations` stream on its way

**Comment by btkcodedev** [comment]
Done

**Comment by natikgadzhi** [comment]
@btkcodedev only do this on case by case basis where I explicitly asked to. Overall, we should stick with Builder validation in 99% of cases.

**Comment by btkcodedev** [comment]
Sure!

**Pull request merged**
