### PR TITLE
doc: describe how to enable a test suite in metadata

### PR DESCRIPTION
**Pull request by alafanechere**
Update our user facing doc to explain how to enable a test suite in the `connectorTestSuitesOptions`

### CODE REVIEW

**Comment by alafanechere** [comment]
* **#38858** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/38858?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alafanechere and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by aaronsteers** [comment]
This is super helpful, thanks @alafanechere. 

Can we also add a table of expected paths or conventions?

E.g.

```
## Default paths and conventions

| Path Type | Python | Java |
|--------|--------|--------|
| Unit Tests | `./unit_tests/**` | `./unitTests/**` |
| Integration Tests | `./integration_tests/**` | `./integrationTests/**` |
| Acceptance Tests | ... TODO ... | ... TODO ... |
| Default Secrets Path | `./secrets/{file-name}` | ... TODO ... |
```

Or if this needs to link to `airbyte-ci` docs, we can link to an external page.

The secrets path just threw me for a loop on another PR, and I think it is worth calling out that on Python the `unitTests` key in confix actually corresponds to a `unit_tests` directory path.

Wdyt?

**Comment by alafanechere** [comment]
Thanks for the suggestion @aaronsteers , I updated the doc!
I believe this kind of information is better suited for a different document which would be focused on connector testing, but it's better to have it here than nowhere.

**Review by aaronsteers — APPROVED** [review]
Sweet! Thanks for these updates!

**Comment by aaronsteers** [comment]
> I believe this kind of information is better suited for a different document which would be focused on connector testing, but it's better to have it here than nowhere.

Agreed! I've also been thinking we should have a 'connector contributing guide' that covers all of the above and removes the need for so much redundant content to live in each connectors' `REAMDE.md`. I think we should move all the generic contributing content to another central page and then each connector's respective section could link to that doc - unless/except it has interesting overrides.

Wdyt, @alafanechere and @natikgadzhi

**Pull request merged**
