### PR TITLE
:bug: Source HubSpot: fix cast string as boolean using string comparison

### LINKED ISSUE #24222: Source Hubspot: Bad casting in _cast_record_fields_if_needed
## Environment
- **Airbyte version**:  0.40.23
- **Deployment**: Docker
- **Source Connector and version**: Hubspot 0.3.2

Same error locally.

## Current Behavior
*Tell us what happens.*
Some properties are badly processed, resulting in wrong value.

Boolean value like hs_is_closed_won in the Deals streams is always True due a bad data casting.

## Expected Behavior
*Tell us what should happen.*
Match same value as in the raw data.

## Steps to Reproduce
1. Launch the Deals stream

### PR DESCRIPTION
**Pull request by aballiet**
## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

Closes https://github.com/airbytehq/airbyte/issues/24222, boolean properties are parsed incorrectly : 

`Deal` object  :
- `hs_is_closed`
- `hs_is_closed_won`
- `hs_is_deal_split`
- `hs_read_only`

`Contact` object :
- `hs_is_unworked`
- `hs_is_contact`

`Company` object :
- `is_public`

Because of the code ending up doing : `bool("False") -> True` for these properties.
Thus, these properties are unusable which can be a blocker to adopt official HubSpot connector.

## How
*Describe the solution*

Parse bool string values : "true" or "false" using string comparison instead.

## Recommended reading order
1. `streams.py` L462-465
2. `Dockerfile`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@aballiet are you able to run unit test locally? With this change you'll need to update all fields in schema files to correct data type... maybe to something `["null", "string", "boolean"]
https://github.com/airbytehq/airbyte/blob/d0fa40c30793386318e1ddef184e97099a6123d0/airbyte-integrations/connectors/source-hubspot/source_hubspot/schemas/deals.json#L189-L191

**Comment by aballiet** [comment]
> @aballiet are you able to run unit test locally? With this change you'll need to update all fields in schema files to correct data type... maybe to something `["null", "string", "boolean"]
> 
> https://github.com/airbytehq/airbyte/blob/d0fa40c30793386318e1ddef184e97099a6123d0/airbyte-integrations/connectors/source-hubspot/source_hubspot/schemas/deals.json#L189-L191

Thank you for the review 👍

Yes tests are passing.

image

Just updated to `["null", "boolean"]` as there are boolean or null fields only.

**Review by marcosmarxm — APPROVED** [review]
The change looks good but I think this will be a breaking change to existing connections.

**Comment by aballiet** [comment]
Ran some checks and apparently, there are incorrect values set in `expected_records.json` file because of this boolean cast problem @marcosmarxm 

I don't know how to access your HubSpot account 😅, can you please confirm that for :

Companies :
- 4992593519 
- 5000526215
- 5000787595

-> you have : `is_public` = false in HubSpot instead of true specified in `expected_records.json`

Contacts & Deals should be the same problem for properties :

Deal object :
`hs_is_closed`
`hs_is_closed_won`
`hs_is_deal_split`
`hs_read_only`

Contact object :
`hs_is_unworked`
`hs_is_contact`

We have to fix the values to be consistent with what is defined in HubSpot account

**Comment by marcosmarxm** [comment]
@sajarin for this one we must update the expected records.

**Comment by aballiet** [comment]
Thank you very much @sajarin

**Review by lazebnyi — CHANGES_REQUESTED** [review]
LGTM! Request changes to block breaking changes. Once the breaking changes procedure are finished, I will give my approval.

**Comment by aballiet** [comment]
> LGTM! Request changes to block breaking changes. Once the breaking changes procedure are finished, I will give my approval.

Do you mean I should change [airbyte/airbyte-integrations/connectors/source-hubspot/source_hubspot/schemas/deals.json](https://github.com/airbytehq/airbyte/blob/d0fa40c30793386318e1ddef184e97099a6123d0/airbyte-integrations/connectors/source-hubspot/source_hubspot/schemas/deals.json#L189-L191) back to the type it was originally to avoid breaking changes ? @lazebnyi

**Comment by lazebnyi** [comment]
@aballiet Everything is fine on your end. @marcosmarxm will assume responsibility for finishing procedure.

**Comment by marcosmarxm** [comment]
@aballiet I'm doing some tests in my local setup using Hubspot 0.6.2 version and during the discover schema step the fields you mentioned already are cast to boolean.
image

image

And the output in the database also is boolean:
image


@lazebnyi do you think this code will make more clear declarations to boolean types?

**Comment by marcosmarxm** [comment]
@lazebnyi The deal table using 0.6.2 all fields are been cast to bool already are in the sync. I don't think this change is a breaking change but is more a fix to the actual casting of values and the specification of the schema to correct type.
image

**Comment by lazebnyi** [comment]
Hm...intersting 
I guess our schema is source of truth for data types actually 🙂

Btw, I agree with you that in this particular case, it does not qualify as a breaking change.

**Review by lazebnyi — APPROVED** [review]

**Comment by jrolom** [comment]
@lazebnyi what else is required to merge this PR? CC/ @marcosmarxm

**Comment by marcosmarxm** [comment]
> @lazebnyi what else is required to merge this PR? CC/ @marcosmarxm

The contribution is amazing but I'm finishing some tests to ensure the change won't break existing connections.

**Comment by aballiet** [comment]
> Running integration tests locally after done will merge the contribution.

Thanks !

**Pull request merged**
