### PR TITLE
✨ Source Recharge: add new stream Events

### PR DESCRIPTION
**Pull request by jamhouston**
## What

This pull request adds a new Events stream to the Recharge source connector, enabling it to retrieve data from Recharge’s recently introduced API endpoint for Events. Since the current Recharge connector does not support an Events stream, this update ensures access to Events data directly through the connector.

For details on the Events documentation and response structure, refer to Recharge's official guide: https://developer.rechargepayments.com/2021-11/events/event_object

## How
Since the Event structure does not have `updated_at` fields and a `sort_by` parameter, the `base_incremental_events_stream` has been added with a built-in `DatetimeBasedCursor` to handle incremental updates effectively.

## Review guide

1. `manifest.yaml`
2. `schemas/events.json`
3. `test_events.py`
4. `request_builder.py`
5. `unit_tests/*`
6.  `unit_tests/*`
7.  `acceptance-test-config.yml`

## User Impact
If a user is on the Recharge Pro plan, they’ll be able to retrieve Events data.

## Can this PR be safely reverted and rolled back?
- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@jamhouston need you to sign the CLA.

**Comment by jamhouston** [comment]
@marcosmarxm could you please give me a list of users we need to provide access to?

**Comment by marcosmarxm** [comment]
@jamhouston can be to me I can push the changes.

**Comment by jamhouston** [comment]
@marcosmarxm hi! please check if you have required permissions granted

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
