### PR TITLE
Jamkase/workspace slug

### LINKED ISSUE #5227: Add workspace slug to url in webapp
[slack convo](https://airbytehq.slack.com/archives/C0229LM09T4/p1628157317094300) with unanimous agreement.

### LINKED ISSUE #6807: "Current workspace" meaning is unclear when the browser has multiple tabs open to multiple workspaces
## Enviroment
- **Airbyte version**:  dev cloud
- **OS Version / Instance**: mac chrome
- **Deployment**: kubernetes
- **Severity**: Medium
- **Step where error happened**: Onboarding

## Current Behavior
When a user has multiple airbyte browser tabs open, and switches workspace in some tab, and then tries to continue with a workflow in progress in another tab, it's unclear what workspace should be used, and what the side effects of the user's actions are, such as if they're currently creating a connection/sync in a workspace.

## Expected Behavior
When the user switches workspace, any other tabs which reference the old workspace should either have their session invalidated, or should clearly and consistently show what workspace they're actually on so the user isn't confused.

### LINKED ISSUE #7643: attempting to access a workspace you don't have access to should show an error
Right now you just see a blank page if you can't access a workspace. In the console you can see `{error":"Project doesn't exist or is not active"}`. 

We should still show the sidebar and have a message in the body saying that the page can't be accessed. This might also be related to how we handle 404s.

### LINKED ISSUE #7721: Cloud UI: redirect to the initially visited URL after login
## Tell us about the problem you're trying to solve
If I visit `<cloud_url>/connections/<id>` when not signed in I am taken to the login page. Fair enough. 
But after i login, I am not taken to the page I initially tried to visit. 

## Describe the solution you’d like
I would like the Ui to remember which page i was trying to visit and take me there after login

### PR DESCRIPTION
**Pull request by jamakase**
## What
*Upgrade react-router to v6*
*Add redirect to the visited path in cloud version*
*Support workspace Slugs* ( currently disabled and used ids instead )
*Add ErrorBoundaries for absent resources*

*Comment indicators for connector update in cloud version*

Closes #5227
Closes #7643 
Closes #7721
Closes #6807

## How
- Add `StartOverErrorView` with ResourceNotFoundErrorBoundary.
- Restructure application use relative routing from react-router v6

### CODE REVIEW

**Comment by jrhizor** [comment]
I'm having trouble running this at all on docker-compose OSS.

When I started with an old installation (just rebuilt images) I got the following:
Screen Shot 2021-12-15 at 7 59 53 PM

I could see the sidebar, just going to http://localhost:8000/ redirected me to http://localhost:8000/<workspace-id>, not an actual browsable page. If I go to http://localhost:8000/<workspace-id>/connections or other pages like that it works though.

However, if I start from scratch (not the old docker volumes) I still get redirected from http://localhost:8000/ to http://localhost:8000/<workspace-id> but I don't even see the sidebar:
Screen Shot 2021-12-15 at 8 02 48 PM

It also doesn't allow me to view anything at all and keeps on showing this page even on http://localhost:8000/36da2c49-861f-4fb4-8bb8-27d0c5a83afa/connections

I assume this is just because the initial setup wizard isn't set up for this. 

My initial playing around looked good on my old Docker volumes except for these issues.

**Comment by Jamakase** [comment]
@jrhizor indeed there was a problem with redirects: fixed it.

Also fixed unit tests for ServiceForm that were skipped for a long time.

**Review by jrhizor — APPROVED** [review]
Looks good. Think it's mergable as is. 

It would be nice if `http://localhost:8000/doesnotexist` showed as a 404 instead of "Unknown error occurred".

Also, some of the setting pages may end up on different routes eventually, since a lot of the settings are instance-wide and not workspace-specific. However I think it's worth it to just merge as is and figure that out later.

**Comment by Jamakase** [comment]
-> It would be nice if http://localhost:8000/doesnotexist showed as a 404 instead of "Unknown error occurred".

I think it's actually not necessary. e.g. github doesn't modify URL. I suppose seeing something like `prod-airbyte.us-east-1.com/default-workspace/connection/pg-to-json` makes much more sense than just having `url/not-found`

**Pull request merged**
