### PR TITLE
Airbyte CDK: move deprecated decorator

### PR DESCRIPTION
**Pull request by artem1205**
## What

Resolve https://github.com/airbytehq/airbyte-internal-issues/issues/8862

`@deprecated` decorator is initialized on every function call. This puts unnecessary load on the heavily used method `get_updated_state` in incremental syncs .

## How

Move `@deprecated` decorator for function `get_updated_state` to class level. 

## Review guide

1. `airbyte-cdk/python/airbyte_cdk/sources/streams/core.py`

## Performance Impact

According to the Profiler Stats, removing them can save us about 4-5% of execution time, see https://github.com/airbytehq/airbyte-internal-issues/issues/8862#issue-2433380004

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by maxi297** [comment]
Can we add a bit more information on the impact? How much time do we expect to save per method call? Per sync?

**Comment by maxi297** [comment]
Should we do that for the methods in HttpStream as well?

**Comment by artem1205** [comment]
>  Can we add a bit more information on the impact? How much time do we expect to save per method call? Per sync?
Update description with link to issue description. I expect about 4-5% of execution time (per sync).

> Should we do that for the methods in HttpStream as well?
These methods are used only in adapters and not very frequently during the sync, so their impact will be minimal.

**Review by tolik0 — APPROVED** [review]

**Review by maxi297 — APPROVED** [review]
LGTM! Thanks for linking the impacts in the PR

**Pull request merged**
