### PR TITLE
octavia-cli: per workspace state

### LINKED ISSUE #13748: octavia-cli: cannot apply a connection on multiple workspaces
In the current octavia version user can switch between Airbyte instance/workspace using the --airbyte-url or --workspace-id option. But, when user generate configurations for connection, a reference to a source_id and a destination_id is hardcoded in the configuration.yaml. As the source_id and destination_id are workspace specific it leads to errors when users try to apply a connection on multiple workspace.

### PR DESCRIPTION
**Pull request by alafanechere**
## What
In the current octavia version user can switch between Airbyte instance/workspace using the `--airbyte-url` or `--workspace-id` option. But, when user `generate` configurations for connection, a reference to a `source_id` and a `destination_id` is hardcoded in the `configuration.yaml`. As the `source_id` and `destination_id` are workspace specific it leads to errors when users try to `apply` a connection on multiple workspace.

## How
* Replace the `source_id` and `destination_id` field in connection `configuration.yaml` by `source_configuration_path` and `destination_configuration_path`. These are the path to the local configuration yaml file for source and destination that will be connected.
* On `apply` save *a state file per workspace*  and store the `resource_id` in these state file
* On connection `apply` the `source_id` and `destination_id` are read from the state file corresponding to the current Airbyte workspace.

### Changes in the connection configuration `renderer` (`generate` command):
1. [octavia-cli/octavia_cli/generate/templates/connection.yaml.j2](https://github.com/airbytehq/airbyte/pull/13070/files#diff-8bed616cfe18183cfef92767589354e526771e768081483c1f2ea69554630da5)
2. [octavia-cli/octavia_cli/generate/renderers.py](https://github.com/airbytehq/airbyte/pull/13070/files#diff-88550c802cbab8b870e254553f7ea9c015e8c742ae78b7f64c9e770f3a0305d3)

### Changes in `resources` (`apply` command):

1. `ResourceState`: make the state workspace specific [octavia-cli/octavia_cli/apply/resources.py](https://github.com/airbytehq/airbyte/pull/13070/files#diff-7667f25ac662725c089e581128312f38cd66f25a7a760d4502f660753e6ed123L72)
2. `BaseResource`: load state file according to current workspace and migrate legacy state if found.  [octavia-cli/octavia_cli/apply/resources.py](https://github.com/airbytehq/airbyte/pull/13070/files#diff-7667f25ac662725c089e581128312f38cd66f25a7a760d4502f660753e6ed123L138)
3. `Connection`: Check for legacy `source_id`, `destination_id` keys in configuration, retrieve `source_id`, `destination_id` from state file [octavia-cli/octavia_cli/apply/resources.py](https://github.com/airbytehq/airbyte/pull/13070/files#diff-7667f25ac662725c089e581128312f38cd66f25a7a760d4502f660753e6ed123R563).

## 🚨 User Impact 🚨
* Legacy `state.yaml` file will be automatically migrated to `state_<workspace_id>.yaml` file.
* On `apply` of a legacy connection configuration an `InvalidConfigurationError` will be raised to ask user to change the `source_id` and `destination_id` fields to `source_configuration_path` and `destination_configuration_path`.

### CODE REVIEW

**Comment by alafanechere** [comment]
@evantahler faces this problem in https://github.com/airbytehq/airbyte/issues/13203

**Review by evantahler — COMMENTED** [review]
Awesome! This is an important step on the way to being able to use `octavia` to deploy a deterministic cluster! 

I'm having trouble seeing where source_configuration_path is created, and determining the name of the YAML file.  Is the filename based on the name of the source/destination/connection, or something else?

How do these changes interact with the `octavia get` commands?  Assuming an Airbyte instance that's already running and no state locally, we would need to `octavia get *` to load all the connections.  From there, would the API become `octavia get /path/to/connection` rather than using the IDs?

**Comment by evantahler** [comment]
Got it!

In your example, could the command be simplified to: `octavia generate connection --source poke --destination pg poke-to-pg`?  Since you know destinations will be in the "destinations" folder, and the filename will always be called "configuration.yaml"?

I think I disagree with `octavia get` only returning information about connections created from the CLI. One of the main use cases for a CLI like this is backup.  Regardless of if I made my connections with the CLI or not, being able to fully backup and re-create my instance seems like a good goal.  Ignoring cross environment deployments (test,staging,prod), maybe I just want to use this tool to backup an AWS server that I have Airbyte installed on in case the server crashes.

**Comment by alafanechere** [comment]
> In your example, could the command be simplified to: octavia generate connection --source poke --destination pg poke-to-pg? Since you know destinations will be in the "destinations" folder, and the filename will always be called "configuration.yaml"?
Yes we could definitely simplify the command! Do you mind opening an issue to suggest this enhancement?

> I think I disagree with the distinction between octavia get and octavia import - in what cases would the state of the server not be reflected in the CLI after either command?

> in what cases would the state of the server not be reflected in the CLI after either command?
The local configuration can be different from the remote one if the user did not run `octavia apply` yet.

I think that `octavia get` should be a  convenience read-only command which is not changing anything on the local project. We could make it able to read local configuration state (in a json output for convenience when it's used in combination with other system such as Airflow) and remote configuration state.
e.g ```
octavia get local <resource-type> <resource-name>
octavia get remote <resource-type> <resource-id> #useful for backup of non octavia managed resources
```

I see `octavia import` as a command which would benefit from the same logic of `octavia get remote` but it will additionally store locally a `configuration.yaml` file which will now make the resource managed by the `octavia apply` command.

**Review by evantahler — APPROVED** [review]

**Comment by evantahler** [comment]
> open a new issue
 Ok! 

I've approved the PR, because we certainly need per-workspace state.  I think there's work to do about the ergonomics of the commands to get and set state, but we can talk about that in another PR/issue.  Thanks!

**Pull request merged**
