### PR TITLE
🐛 Source MSSQL: fix data type (smalldatetime, smallmoney) conversion from mssql source (#5609)

### LINKED ISSUE #5609: Source MSSQL to S3 Failed to convert JSON to Avro
## Enviroment
- Is this your first time deploying Airbyte: no
- OS Version / Instance: Linux EC2 t3.xlarge
- Deployment: Docker
- Airbyte Version: 0.29.11-alpha
- Source name: MSSQL 0.3.4 (latest)
- destination: S3 0.1.3 (latest)
- Description: I tried to ingest data from MSQQL database to S3 bucket, using CDC mode. Job was failling with Exception in thread "main" tech.allegro.schema.json2avro.converter.AvroConversionException: Failed to convert JSON to Avro: Could not evaluate union, field dtm_Creation_Date is expected to be one of these: NULL, STRING. If this is a complex type, check if offending field: dtm_Creation_Date adheres to schema

## Current Behavior
*Tell us what happens.*

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*
```
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 - Exception in thread "main" tech.allegro.schema.json2avro.converter.AvroConversionException: Failed to convert JSON to Avro: Could not evaluate union, field dtm_Creation_Date is expected to be one of these: NULL, STRING. If this is a complex type, check if offending field: dtm_Creation_Date adheres to schema.
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:60)
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:49)
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    at tech.allegro.schema.json2avro.converter.JsonAvroConverter.convertToGenericDataRecord(JsonAvroConverter.java:58)
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    at io.airbyte.integrations.destination.s3.avro.AvroRecordFactory.getAvroRecord(AvroRecordFactory.java:63)
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    at io.airbyte.integrations.destination.s3.parquet.S3ParquetWriter.write(S3ParquetWriter.java:110)
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    at io.airbyte.integrations.destination.s3.S3Consumer.acceptTracked(S3Consumer.java:133)
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.accept(FailureTrackingAirbyteMessageConsumer.java:66)
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:167)
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:148)
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    at io.airbyte.integrations.destination.s3.S3Destination.main(S3Destination.java:49)
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 - Caused by: org.apache.avro.AvroTypeException: Could not evaluate union, field dtm_Creation_Date is expected to be one of these: NULL, STRING. If this is a complex type, check if offending field: dtm_Creation_Date adheres to schema.
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    at tech.allegro.schema.json2avro.converter.AvroTypeExceptions.unionException(AvroTypeExceptions.java:28)
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.readUnion(JsonGenericRecordReader.java:162)
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:98)
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.lambda$readRecord$0(JsonGenericRecordReader.java:71)
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    at java.base/java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:710)
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.readRecord(JsonGenericRecordReader.java:68)
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:58)
2021-08-23 04:37:55 ERROR () LineGobbler(voidCall):85 -    ... 9 more

```

## Steps to Reproduce
1. 
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

### PR DESCRIPTION
**Pull request by yurii-bidiuk**
## What
Fixed data type (`smalldatetime`, `smallmoney`) conversion from mssql source (#5609)

## How
Created custom MSSQLConverter that implements CustomConverter

## Recommended reading order
1. `MSSQLConverter.java`
2. `DebeziumConverterUtils.java`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [x] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Connector strict-encrypt version bumped and published
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by irynakruk — APPROVED** [review]
LGTM

**Review by DoNotPanicUA — CHANGES_REQUESTED** [review]
Good PR.
I'm only worrying about DebeziumConverterUtils.java and possible conflicts.

**Review by alexandr-shegeda — APPROVED** [review]
LGTM. we can proceed with publish/merge without airbyte review

**Review by DoNotPanicUA — APPROVED** [review]

**Pull request merged**
