### PR TITLE
Debug mySql integration tests

### PR DESCRIPTION
**Pull request by akashkulk**

### CODE REVIEW

**Comment by akashkulk** [comment]
/legacy-test connector=connectors/source-mysql-strict-encrypt

**Comment by octavia-squidington-iii** [comment]
##  source-mysql-strict-encrypt test report (commit [`a5fa62caf8`](https://github.com/airbytehq/airbyte/pull/28937/commits/a5fa62caf83ec744de11b21499039ac15316f890)) - ❌

⏲️  Total pipeline duration: 15mn22s 

| Step                                                                                   | Result   |
|:---------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                         | ✅        |
| QA checks                                                                              | ✅        |
| Build connector tar                                                                    | ✅        |
| Build source-mysql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mysql-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/integ_test/1691010127/a5fa62caf83ec744de11b21499039ac15316f890/source-mysql-strict-encrypt/2.1.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:a5fa62caf83ec744de11b21499039ac15316f890)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mysql test report (commit [`a5fa62caf8`](https://github.com/airbytehq/airbyte/pull/28937/commits/a5fa62caf83ec744de11b21499039ac15316f890)) - ❌

⏲️  Total pipeline duration: 18mn07s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql/metadata.yaml     | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ❌        |
| QA checks                                                               | ✅        |
| Build connector tar                                                     | ✅        |
| Build source-mysql docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mysql:integrationTest | ❌        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/integ_test/1691010127/a5fa62caf83ec744de11b21499039ac15316f890/source-mysql/2.1.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:a5fa62caf83ec744de11b21499039ac15316f890)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mysql-strict-encrypt test report (commit [`a5fa62caf8`](https://github.com/airbytehq/airbyte/pull/28937/commits/a5fa62caf83ec744de11b21499039ac15316f890)) - ❌

⏲️  Total pipeline duration: 13mn41s 

| Step                                                                                   | Result   |
|:---------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                         | ✅        |
| QA checks                                                                              | ✅        |
| Build connector tar                                                                    | ✅        |
| Build source-mysql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mysql-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/integ_test/1691012240/a5fa62caf83ec744de11b21499039ac15316f890/source-mysql-strict-encrypt/2.1.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:a5fa62caf83ec744de11b21499039ac15316f890)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mysql test report (commit [`a5fa62caf8`](https://github.com/airbytehq/airbyte/pull/28937/commits/a5fa62caf83ec744de11b21499039ac15316f890)) - ❌

⏲️  Total pipeline duration: 18mn16s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql/metadata.yaml     | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ❌        |
| QA checks                                                               | ✅        |
| Build connector tar                                                     | ✅        |
| Build source-mysql docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mysql:integrationTest | ❌        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/integ_test/1691012240/a5fa62caf83ec744de11b21499039ac15316f890/source-mysql/2.1.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:a5fa62caf83ec744de11b21499039ac15316f890)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mysql-strict-encrypt test report (commit [`3fc3e0703b`](https://github.com/airbytehq/airbyte/pull/28937/commits/3fc3e0703bfb916cddec676f55e814ce0030691d)) - ❌

⏲️  Total pipeline duration: 18.14s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/integ_test/1691084832/3fc3e0703bfb916cddec676f55e814ce0030691d/source-mysql-strict-encrypt/2.1.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:3fc3e0703bfb916cddec676f55e814ce0030691d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mysql test report (commit [`3fc3e0703b`](https://github.com/airbytehq/airbyte/pull/28937/commits/3fc3e0703bfb916cddec676f55e814ce0030691d)) - ❌

⏲️  Total pipeline duration: 11.13s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/integ_test/1691084832/3fc3e0703bfb916cddec676f55e814ce0030691d/source-mysql/2.1.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:3fc3e0703bfb916cddec676f55e814ce0030691d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mysql test report (commit [`747cb0a1ee`](https://github.com/airbytehq/airbyte/pull/28937/commits/747cb0a1eec286cb0fb4be21a1582c23d89f0c93)) - ❌

⏲️  Total pipeline duration: 11.91s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/integ_test/1691093893/747cb0a1eec286cb0fb4be21a1582c23d89f0c93/source-mysql/2.1.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:747cb0a1eec286cb0fb4be21a1582c23d89f0c93)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mysql test report (commit [`dd74884289`](https://github.com/airbytehq/airbyte/pull/28937/commits/dd74884289d0cf109f345de3674c07d32d0e7c7a)) - ❌

⏲️  Total pipeline duration: 21mn21s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql/metadata.yaml     | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ❌        |
| QA checks                                                               | ✅        |
| Build connector tar                                                     | ✅        |
| Build source-mysql docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mysql:integrationTest | ❌        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/integ_test/1691096650/dd74884289d0cf109f345de3674c07d32d0e7c7a/source-mysql/2.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:dd74884289d0cf109f345de3674c07d32d0e7c7a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Pull request closed without merging**
