### PR TITLE
fix: airbyte export for undefined table

### PR DESCRIPTION
**Pull request by ifokeev**

### CODE REVIEW

**Comment by jrhizor** [comment]
Did you run into an issue where a table was undefined and it raised a `IllegalArgumentException`? I'm curious what the underlying issue is and if we can recreate it.

**Comment by ifokeev** [comment]
@jrhizor I was getting problems with `airbyte-server`, we have internal implementation where we have shared db with airbyte, I mean we have one database for all tables. Airbyte is trying to export all tables by default. That's the issue and export doesn't work for us 

https://github.com/airbytehq/airbyte/issues/2733#issuecomment-822566729

**Comment by jrhizor** [comment]
Ah interesting. In that case it might be best to whitelist tables that we want to copy over.

**Comment by ifokeev** [comment]
I tried but had a lot of failed tests

**Comment by jrhizor** [comment]
I think if you use the following changes it should probably work:

update the function in `DefaultJobPersistence`:
```
  private List<String> listTables(final String schema) throws IOException {
    if (schema != null) {
      return database.query(context -> context.meta().getSchemas(schema).stream()
          .flatMap(s -> context.meta(s).getTables().stream())
          .map(Named::getName)
          .filter(table -> DatabaseSchema.getTableNames().contains(table))
          .collect(Collectors.toList()));
    } else {
      return List.of();
    }
  }
```

add this in `DatabaseSchema`:
```
  public static List<String> getTableNames() {
    return Stream.of(DatabaseSchema.values()).map(Enum::name).collect(Collectors.toList());
  }
```

and update `testUnknownTableExport` in `DatabaseArchiverTest` to check that the output `tempFolder` has a directory called `airbyte_db` that contains all of the table names from `DatabaseSchema.getTableNames()` but not `id_and_name`. At that point we should also be able to remove the `assertThrows` check.

If these changes fix your problem we'd be happy to merge the fix in.

**Comment by ifokeev** [comment]
> and update testUnknownTableExport in DatabaseArchiverTest to check that the output tempFolder has a directory called airbyte_db that contains all of the table names from DatabaseSchema.getTableNames() but not id_and_name. At that point we should also be able to remove the assertThrows check.

Sorry I'm not familiar with JAVA. It will take a lot of time for me.
I pushed some fixes, please check

**Comment by ifokeev** [comment]
@jrhizor could you help here?

**Comment by jrhizor** [comment]
I need to prepare some changes to update tests, but we can get this merged in today.

**Comment by jrhizor** [comment]
I changed the base to my own branch. I'm going to merge this, fix the tests, and have a new PR to merge that into master, which will be picked up in our next core release.

**Comment by ifokeev** [comment]
@jrhizor big thanks

**Pull request merged**
