### PR TITLE
SAT: enforce `bypass_reason` declaration on `empty_streams` when `test_strictness_level == high`

### LINKED ISSUE #18221: SAT [strict_mode]: no `basic_read.empty_streams`
## Tell us about the problem you're trying to solve
We want to ensure a read operation is tested on all the streams exposed by a GA connector. 
If this is not possible the connector maintainer must document why.

## Describe the solution you’d like
In `basic_read` test SAT should fail if an `empty_stream` without  a `bypass_reason`is filled when `strict_mode == strict`.

```yaml
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      empty_streams: 
        - name: orders
          bypass_reason: "We don't have data for the orders stream on our sandbox account"
```

**If a `bypass_reason` is filled SAT should log a warning.**

### PR DESCRIPTION
**Pull request by alafanechere**
**🚨 The target branch of this PR is temporary set  to [augustin/sat/strict-mode/all-tests2](https://github.com/airbytehq/airbyte/tree/augustin/sat/strict-mode/all-tests2) until merge of https://github.com/airbytehq/airbyte/pull/18414**

## What
Closes #18221 

Enforce documentation of `empty_streams` by making filling a `bypass_reason` field mandatory when `test_strictness_level == high`.

## How
1. Change the structure of `BasicReadTestConfig` to accept a `bypass_reason` field on each `empty_stream` item
2. Make `test_read` consume the `test_strictness_level` fixture and call a new `enforce_strictness_level` function
3. Implement `BasicReadTestConfig.enforce_strictness_level` to make fail the test if no `bypass_reason` is set on `empty_stream` item when `test_strictness_level == high`
4. Adapt `migrate_legacy_to_current_config` to convert legacy configuration structure to the new config structure of `BasicReadTestConfig`
## Recommended reading order
1. https://github.com/airbytehq/airbyte/blob/18e2d7647da74dfcdd01e62eb56eb8143a3e3026/docs/connector-development/testing-connectors/source-acceptance-tests-reference.md#L283
2. https://github.com/airbytehq/airbyte/blob/18e2d7647da74dfcdd01e62eb56eb8143a3e3026/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/config.py#L107
3. https://github.com/airbytehq/airbyte/blob/18e2d7647da74dfcdd01e62eb56eb8143a3e3026/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py#L472
4. https://github.com/airbytehq/airbyte/blob/18e2d7647da74dfcdd01e62eb56eb8143a3e3026/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py#L586
5. https://github.com/airbytehq/airbyte/blob/18e2d7647da74dfcdd01e62eb56eb8143a3e3026/airbyte-integrations/bases/source-acceptance-test/unit_tests/test_core.py#L282
6. https://github.com/airbytehq/airbyte/blob/18e2d7647da74dfcdd01e62eb56eb8143a3e3026/airbyte-integrations/bases/source-acceptance-test/unit_tests/test_core.py#L882

## 🚨 User Impact 🚨
No impact. The "legacy" configuration format is still supported.

### CODE REVIEW

**Comment by alafanechere** [comment]
☝️ Expect SAT to fail on `source-recharge` because no `bypass_reason` was filled on the `empty_streams`

**Comment by alafanechere** [comment]
☝️ Expect SAT to succeed on source-recharge because a bypass_reason was filled on the empty_streams (I've temporary set test_strictness_level to high)

**Comment by alafanechere** [comment]
☝️ Expect SAT to succeed on `source-recharge` after I revert it to its original structure (legacy).

**Review by evantahler — APPROVED** [review]
Love the in-chat examples

**Comment by alafanechere** [comment]
/publish connector=bases/source-acceptance-test auto-bump-version=false

**Pull request merged**
