### PR TITLE
:bug: Source Klaviyo: do not store state in the future

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/oncall/issues/2132
Klaviyo API allows a cursor field hold values from the future. If one record has a value from the future, and by the next sync there are new records that come after the moment the previous sync started, we won't notice them because we have state stored in the future, and will only make queries starting from this date.

## How
If a cursor value is in the future - override it with the timestamp of the moment the sync started at.

## 🚨 User Impact 🚨
Data **may** be duplicated when using incremental sync mode. To get rid of this side effect, users can use "dedup" mode.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-klaviyo test report (commit [`f41767f8dc`](https://github.com/airbytehq/airbyte/pull/27498/commits/f41767f8dc9d17b23745bbf9e69821a13707e8c6)) - ❌

⏲️  Total pipeline duration: 222 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-klaviyo/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ❌        |
| Connector package install                                             | ✅        |
| Build source-klaviyo docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5323220521)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-klaviyo test
```

**Comment by octavia-squidington-iii** [comment]
##  source-klaviyo test report (commit [`7d0fe6a7d2`](https://github.com/airbytehq/airbyte/pull/27498/commits/7d0fe6a7d218e5ebde265922c4bf3f1f2229b6d6)) - ❌

⏲️  Total pipeline duration: 208 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-klaviyo/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ❌        |
| Connector package install                                             | ✅        |
| Build source-klaviyo docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5323228483)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-klaviyo test
```

**Review by bnchrch — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-klaviyo test report (commit [`96a14e4d46`](https://github.com/airbytehq/airbyte/pull/27498/commits/96a14e4d460b11048a71f890cba98756fadad894)) - ❌

⏲️  Total pipeline duration: 220 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-klaviyo/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-klaviyo docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5331095675)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-klaviyo test
```

**Comment by octavia-squidington-iii** [comment]
##  source-klaviyo test report (commit [`61804966e9`](https://github.com/airbytehq/airbyte/pull/27498/commits/61804966e90f74e8ee65536598e5e15344b94fdc)) - ✅

⏲️  Total pipeline duration: 164 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-klaviyo/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-klaviyo docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5331326891)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-klaviyo test
```

**Pull request merged**
