### PR TITLE
Remove quarantined

### PR DESCRIPTION
**Pull request by benmoriceau**
## What
The possibility of setting a job in quarantine has been remove in https://github.com/airbytehq/airbyte/pull/13779.

This PR removes to the quarantine state in the other parts of the codebase since it is not needed.

### CODE REVIEW

**Review by gosusnp — APPROVED** [review]

**Comment by benmoriceau** [comment]
I want to check with Lake if there is some connection that could benefit from the old behavior before merging.

**Comment by lmossman** [comment]
@benmoriceau do you know how this will affect any connections that are currently in a quarantined state? There could still be some on cloud or on OSS deployments that are currently in quarantined

**Comment by cgardens** [comment]
@benmoriceau is this a PR we are still trying to move forward with?

**Comment by benmoriceau** [comment]
> @benmoriceau is this a PR we are still trying to move forward with?

Yes, I would prefer to merge it when the epic about the manual operation related to quarantine is done. @lmossman is right about the potential problem that can occur if we have workflow that are in quarantine. We should avoid that.

**Comment by cgardens** [comment]
@benmoriceau is this PR still blocked?

**Comment by benmoriceau** [comment]
> @benmoriceau is this PR still blocked?

Yes. The airbyte-cron app need to be updated with a call to the temporal service. It was blocked by having the temporal client to be injectable through micronaut. I am working on syncing with @jdpgrailsdev to check if some work needs to happen here.

**Comment by benmoriceau** [comment]
@cgardens it will be unblocked once https://github.com/airbytehq/airbyte/pull/16414 and https://github.com/airbytehq/airbyte/pull/16447 are merged

**Comment by benmoriceau** [comment]
Draft because of the conflicts

**Pull request closed without merging**
