### PR TITLE
🐛 Source Mixpanel : Fix Export HTTP Response Parsing

### PR DESCRIPTION
**Pull request by guillaume-chech**
Testing!!!## What
Export stream processing could fail in some edge cases where individual Export text properties would contains line breaks causing the json parser to fail. As reported [here #11018](https://github.com/airbytehq/airbyte/issues/11018)

## How
The solution replaces the usage of `response.text.splitlines()` by the use of the HTTP response `response.iter_lines()` method. No other changes implemented.

## Recommended reading order
1. `source_mixpanel/souce.py`

## 🚨 User Impact 🚨
No impact expected. Change should be transparent.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

```
Results (0.20s):
       1 passed
 ```

</details>

<details><summary><strong>Integration</strong></summary>

```
Test session starts (platform: darwin, Python 3.8.2, pytest 6.2.5, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /Users/guillaume/Shotgun/airbyte, configfile: pytest.ini
plugins: sugar-0.9.4, timeout-1.4.2
collecting ... 

Results (0.01s):
```

</details>

<details><summary><strong>Acceptance</strong></summary>

I did not manage to run those likely that something is wrong with my setup.

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Can you sign the CLA @guillaume-chech ? Also can you share the integration tests or a screenshoot showing the modification solves the issue?

**Comment by marcosmarxm** [comment]
Overall the change looks great thanks @guillaume-chech

**Comment by guillaume-chech** [comment]
> Can you sign the CLA @guillaume-chech ? Also can you share the integration tests or a screenshoot showing the modification solves the issue?

Hi @marcosmarxm ! Looks like it's already signed . I got this warning message : 
>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=11318) it.

**Comment by guillaume-chech** [comment]
Sure here is a proof of the fix working ,I ran this command to test on a faulty day of data :
`python3 main.py read  --config secrets/config.json --catalog integration_tests/configured_catalog_export.json`
Screenshot 2022-03-23 at 16 32 41

Screenshot 2022-03-23 at 16 30 01

And without the fix : 
Screenshot 2022-03-23 at 16 34 38

**Comment by guillaume-chech** [comment]
@marcosmarxm Looks like something went wrong with the acceptance test run. Do you have more logs of the run, it's just saying that the instance was killed :)

**Comment by marcosmarxm** [comment]
Our Mixpanel CI is broke @guillaume-chech I'm working to fix it and run tests with your changes

**Comment by marcosmarxm** [comment]
> Our Mixpanel CI is broke @guillaume-chech I'm working to fix it and run tests with your changes

@guillaume-chech I'm working to remove data from our integration accoun,  hope tomorrow I can test your changes and merged it.

**Comment by guillaume-chech** [comment]
@[marcosmarxm](https://github.com/marcosmarxm) Did you manage to implement a fix for the CI ?

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
