### PR TITLE
fix(source-teradata): fixing bug in host port definition

### PR DESCRIPTION
**Pull request by Fabrizib**
## What
Fixing Teradata source connector bug for host URL construction and default port used.

This should fix also issue: https://github.com/airbytehq/airbyte/issues/33655
## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hello @Fabrizib can you sign the CLA and link Teradata documentation showing this is the right format to parse the host?

**Comment by Fabrizib** [comment]
Hi @marcosmarxm after discussing with Teradata it seems that an early contribution overlooked that the DBS_PORT can be set up as a JDBC URL parameter: https://teradata-docs.s3.amazonaws.com/doc/connectivity/jdbc/reference/current/jdbcug_chapter_2.html#URL_DBS_PORT

Therefore there is no need to add it as an input value and rather just needs to be removed from all the constructions.

I build and tested it from my side and it works with no issues.

**Comment by Fabrizib** [comment]
hey @marcosmarxm fixed the formatting as per the airbyte-ci format fix all :)

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
