### PR TITLE
use PAT instead of GITHUB_TOKEN for test_reporter action

### PR DESCRIPTION
**Pull request by c-p-b**
## What
By default this action uses GITHUB_TOKEN which has a pretty low rate limit. Sometimes it fails for exceeding that rate limit

## How
use env.PAT which is derived from find a pat script instead

### CODE REVIEW

**Review by supertopher — APPROVED** [review]
looks fly to me.

**Review by edmundito — APPROVED** [review]

**Comment by perangel** [comment]
Testing a comment

**Comment by evantahler** [comment]
@cpdeethree can we close this PR?

**Comment by cpdeethree** [comment]
I think so, it looks like after monorepo we stopped hitting the rate limit for this

**Pull request closed without merging**
