### PR TITLE
Renamed and cleaned up CSV and Azure connector docs

### PR DESCRIPTION
**Pull request by Amruta-Ranade**

### CODE REVIEW

**Review by evantahler — CHANGES_REQUESTED** [review]
Looking good! There are 2 lines to change here too https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-csv/src/main/resources/spec.json#L2-L15

**Comment by Amruta-Ranade** [comment]
> Looking good! There are 2 lines to change here too https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-csv/src/main/resources/spec.json#L2-L15

Fixed!

**Review by evantahler — APPROVED** [review]

**Comment by evantahler** [comment]
@Amruta-Ranade I updated your branch to pull in the latest test fixes

**Review by grishick — APPROVED** [review]

**Comment by Amruta-Ranade** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/pull/23314/files

**Pull request closed without merging**
