### PR TITLE
Source Public APIs: Migrate to manifest-only with components

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
Source Public APIs: Migrate to manifest only formats with components

## How
Migrated to inline schemas
Migrated spec
Migrated to manifest only with ci

### CODE REVIEW

**Comment by btkcodedev** [comment]
Migration report
image

**Comment by ChristoGrab** [comment]
I think this API is deprecated? There's no authentication required but every request I send is returning 404s, both in the connector and Postman 🤔 @btkcodedev are you able to successfully query either of these endpoints?

https://api.publicapis.org/categories
https://api.publicapis.org/health

**Comment by btkcodedev** [comment]
Yep this is deprecated

**Comment by btkcodedev** [comment]
Farewell Public API's connector,
You had a good run

**Comment by ChristoGrab** [comment]
[We will bury it with full honors](https://github.com/airbytehq/airbyte-internal-issues/issues/10425) 🫡

**Pull request closed without merging**
