### PR TITLE
🎉Categorized Config Errors Accurately for Google Analytics 4 (GA4) and Google Ads

### LINKED ISSUE #25689: Categorize Google Ads config erros
These errors should be recategorized to be config errors, not system errors:

- incorrect GAQL query statement: '"SELECT campaign.id, campaign.name FROM campaign"'
- incorrect GAQL query statement: 'customer_query_2'
- incorrect GAQL query statement: 'keyword_stats'

### LINKED ISSUE #25692: Categorize Google Analytics 4 (GA4) config errors
These errors returned for GAv4 should be categorized as config errors, not system errors.
- 403 Client Error: Forbidden for url: https://analyticsdata.googleapis.com/v1beta/properties/164523383/metadata
- 400 Client Error: Bad Request for url: https://analyticsdata.googleapis.com/v1beta/properties/UA-164523383-1/metadata
- 400 Client Error: Bad Request for url: https://analyticsdata.googleapis.com/v1beta/properties/a164523383w230249301p216691667/metadata

The error message should read: Access was denied to the property ID entered. Check your access to the Property ID or use Google Analytics' [docs](https://developers.google.com/analytics/devguides/reporting/data/v1/property-id#what_is_my_property_id) to find your Property ID. 

Additional improvements to the spec:
- The tooltip does not show an example value, and should include an example value:

- The Property ID field is a numeric value and should not allow values like "UA-165496" to be entered.

### PR DESCRIPTION
**Pull request by lazebnyi**
#### Google Analytics 4 (GA4)
The errors encountered with GAv4 should be classified as configuration errors rather than system errors.

`Error 403: Client Error - Forbidden for URL: https://analyticsdata.googleapis.com/v1beta/properties/164523383/metadata`
`Error 400: Client Error - Bad Request for URL: https://analyticsdata.googleapis.com/v1beta/properties/UA-164523383-1/metadata`
`Error 400: Client Error - Bad Request for URL: https://analyticsdata.googleapis.com/v1beta/properties/a164523383w230249301p216691667/metadata`

The error message should be revised to: "Access was denied to the entered Property ID. Please verify your access to the Property ID or refer to Google Analytics' [documentation](https://developers.google.com/analytics/devguides/reporting/data/v1/property-id#what_is_my_property_id) to find your Property ID."

Further enhancements to the specification:
The tooltip should display an example value. 
The Property ID field should only accept numeric values and disallow entries such as "UA-165496".

#### Google Ads
The classification of these errors should be changed from system errors to configuration errors:

`Error: Incorrect GAQL query statement: '"SELECT campaign.id, campaign.name FROM campaign"'`
`Error: Incorrect GAQL query statement: 'customer_query_2'`
`Error: Incorrect GAQL query statement: 'keyword_stats'`

## How
With `try..except` catch error and raise `AirbyteTracedException` with `config_error` failure type.

### CODE REVIEW

**Review by bazarnov — APPROVED** [review]
Looks good, but the question about using the list instead of an `or` statement.

For `Google-Analytics-data-api`,  please check the `flakeCheck errors` https://github.com/airbytehq/airbyte/actions/runs/4947619403/jobs/8847290268#step:11:717

**Comment by lazebnyi** [comment]
/publish connector=connectors/source-google-analytics-data-api

**Pull request merged**
