### PR TITLE
live-tests: handle multiple connections

### PR DESCRIPTION
**Pull request by alafanechere**
## What
Closes https://github.com/airbytehq/airbyte-internal-issues/issues/10794

The goal of this PR is to:
* Make the live test suite able to run on multiple connections. 
* Persist connection details in a separate HTML file.

## How
* Refactor `conftest` and `reports` modules to handle multiple connection
* Leverage `pytest_generate_tests` and indirect fixtures to parametrize a test for each connections
* Refactor `<command>_execution_results` fixture declaration to DRY:  declare them dynamically and inject them at runtime 

## Suggested review flow
* `conftest.py`: 
  * How execution results fixtures are generated
  * How we parametrize tests per connection
  * How we generate a private connection details report
* `reports.py` and `*.j2`: How we create two different HTML file, one with test execution results, an other one with connection details which is supposed to be private

### CODE REVIEW

**Comment by natikgadzhi** [comment]
Um. 2 weeks without a review?

**Comment by artem1205** [comment]
LGTM!
tested on source-intercom in https://github.com/airbytehq/airbyte/actions/runs/12412625430/job/34652805606

should we also extend `Command execution metrics` to extend which connection these numbers refer to?
image

**Comment by alafanechere** [comment]
@artem1205 I think we should keep overall execution metrics, but could definitely add a breakdown by connection in a followup

**Review by artem1205 — APPROVED** [review]
APPROVED!

**Pull request merged**
