### PR TITLE
Add explicit registry to metadata file for langchain and gainsight

### PR DESCRIPTION
**Pull request by bnchrch**
## What
These metadata files are already on GCS as I pushed them out of band.

This brings master up to date

### CODE REVIEW

**Comment by octavia-approvington** [comment]
Enough! Let's do this <br/> goooooo!

**Review by octavia-approvington — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  destination-langchain test report (commit [`1078ef48c9`](https://github.com/airbytehq/airbyte/pull/28296/commits/1078ef48c99988980c0556ae3b6516fefc3d9513)) - ✅

⏲️  Total pipeline duration: 01mn29s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-langchain/metadata.yaml | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Code format checks                                                           | ✅        |
| Connector package install                                                    | ✅        |
| Build destination-langchain docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                   | ✅        |
| Integration tests                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/bnchrch_fix-upload/1689279655/1078ef48c99988980c0556ae3b6516fefc3d9513/destination-langchain/0.0.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-langchain test
```

**Comment by octavia-squidington-iii** [comment]
##  source-gainsight-px test report (commit [`1078ef48c9`](https://github.com/airbytehq/airbyte/pull/28296/commits/1078ef48c99988980c0556ae3b6516fefc3d9513)) - ✅

⏲️  Total pipeline duration: 02mn00s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-gainsight-px/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| QA checks                                                                  | ✅        |
| Code format checks                                                         | ✅        |
| Connector package install                                                  | ✅        |
| Build source-gainsight-px docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/bnchrch_fix-upload/1689279655/1078ef48c99988980c0556ae3b6516fefc3d9513/source-gainsight-px/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gainsight-px test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-langchain test report (commit [`8205ce9e6c`](https://github.com/airbytehq/airbyte/pull/28296/commits/8205ce9e6c10e5776c2e1e69182447fd9dd6c624)) - ✅

⏲️  Total pipeline duration: 01mn32s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-langchain/metadata.yaml | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Code format checks                                                           | ✅        |
| Connector package install                                                    | ✅        |
| Build destination-langchain docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                   | ✅        |
| Integration tests                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/bnchrch_fix-upload/1689282230/8205ce9e6c10e5776c2e1e69182447fd9dd6c624/destination-langchain/0.0.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-langchain test
```

**Comment by octavia-squidington-iii** [comment]
##  source-gainsight-px test report (commit [`8205ce9e6c`](https://github.com/airbytehq/airbyte/pull/28296/commits/8205ce9e6c10e5776c2e1e69182447fd9dd6c624)) - ✅

⏲️  Total pipeline duration: 01mn59s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-gainsight-px/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| QA checks                                                                  | ✅        |
| Code format checks                                                         | ✅        |
| Connector package install                                                  | ✅        |
| Build source-gainsight-px docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/bnchrch_fix-upload/1689282230/8205ce9e6c10e5776c2e1e69182447fd9dd6c624/source-gainsight-px/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gainsight-px test
```

**Pull request merged**
