### PR TITLE
🐛Source Greenhouse: Move spec to inline and fix Readme

### PR DESCRIPTION
**Pull request by btkcodedev**
Closes https://github.com/airbytehq/PyAirbyte-Hackathon/issues/8
## Scenario: 
While testing PyAirbyte with Source-greenhouse, sync is perfect, but has some issues with documentation and needs updates

## Improvement areas:
- CDK version is old - Fixed by pinning to ^1
- Spec is found outside manifest - Migrated inside manifest
- Readme command to read records aren't working - Fixed using correct directory path

Sync Ref:
image

### CODE REVIEW

**Comment by aaronsteers** [comment]
@btkcodedev - All the changes make sense. It looks like [some tests](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/btkcodedev_greenhousefixes/1718821366/1cb062ce2e8c5a906bf82867cf43dc85f80d3c15/source-greenhouse/0.5.5/output.html) are failing due to breaking changes in CDK. Also, there was a concurrent PR here:

- https://github.com/airbytehq/airbyte/pull/39968

Which might be somewhat overlapping with this scope and creating some merge conflicts. Can you take a look? Thanks!

**Comment by btkcodedev** [comment]
Yes sure

**Comment by btkcodedev** [comment]
Hi, @aaronsteers, Reverted the CDK version change as there is a reason for pinning it in 0.80.0, for compatibility issues with other packages. Ref PR: https://github.com/airbytehq/airbyte/pull/36640
Other changes are fine to move on

**Comment by btkcodedev** [comment]
Ready for review 
CC: @aaronsteers @marcosmarxm

**Comment by aaronsteers** [comment]
@btkcodedev - Sorry to have not gotten to this sooner, but I see a conflicting auto-bump of dependencies has caused a merge conflict. By chance are you able to bump the version in this PR to avoid the version number collision, and pull in upstream changes? I'll be on hand to review and re-test this week. Thanks!

**Comment by btkcodedev** [comment]
@aaronsteers Resolved conflicts and ready for review :)

**Comment by natikgadzhi** [comment]
We've had a bug in CI yesterday. Merging fresh master in, re-running CI.

**Comment by natikgadzhi** [comment]
@btkcodedev Python team just released CDK 3.0 ☠️ — when you work on conectors, it's a good idea to opportunistically try to update them to next major and see if it still works.

**Review by natikgadzhi — APPROVED** [review]
Looks good, just waiting on tests to pass.

**Pull request merged**
