### PR TITLE
✨ Source Primatric: migrating python CDK to low-code

### PR DESCRIPTION
**Pull request by puru-khedre**
## What
Migrating source primetric from python CDK to Low-code CDK
Issue: #30871 

## How
Migrating the Primatric source connector from the python CDK to configuration based connectors (Low-code CDK).

## Recommended reading order
1. `README.md`
2. `spec.yml`
3. `menifest.yml`
4. `schema/*`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/resources/pull-requests-handbook)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

<details><summary><strong>Updating the Python CDK</strong></summary>

### Airbyter

Before merging:
- Pull Request description explains what problem it is solving
- Code change is unit tested
- Build and my-py check pass
- Smoke test the change on at least one affected connector
   - On Github: Run [this workflow](https://github.com/airbytehq/airbyte/actions/workflows/connectors_tests.yml), passing `--use-local-cdk --name=source-<connector>` as options
   - Locally: `airbyte-ci connectors --use-local-cdk --name=source-<connector> test`
- PR is reviewed and approved
      
After merging:
- [Publish the CDK](https://github.com/airbytehq/airbyte/actions/workflows/publish-cdk-command-manually.yml)
   - The CDK does not follow proper semantic versioning. Choose minor if this the change has significant user impact or is a breaking change. Choose patch otherwise.
   - Write a thoughtful changelog message so we know what was updated.
- Merge the platform PR that was auto-created for updating the Connector Builder's CDK version
   - This step is optional if the change does not affect the connector builder or declarative connectors.

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Sorry the long delay to get into your contribution. Probably this week or next one the team will start the process. Are you able to run the tests in your local setup? It can speed up a lot the process if you share the integration tests results

**Comment by puru-khedre** [comment]
> Sorry the long delay to get into your contribution. Probably this week or next one the team will start the process. Are you able to run the tests in your local setup? It can speed up a lot the process if you share the integration tests results

The python connector don't have any tests written. So I apply `read`, `spec`, and `check` operations.

And also, We Don't have the test credentials. So I setup one mock API server for similar kind of streams and then apply integration tests

Streams Included in tests:
- assignments,
- rag_ratings

### `spec` command
Screenshot from 2023-10-25 11-27-02

### `check` command
Screenshot from 2023-10-25 11-36-11

### `read` command
```logs
~/Desktop/Coding/airbyte-hachathon/forked-airbyte/airbyte-integrations/connectors/source-primetric (connector-migration/primetric*) » python main.py read --config secrets/config.json --catalog integration_tests/mock_configured_catalog.json
{"type": "LOG", "log": {"level": "INFO", "message": "Starting syncing SourcePrimetric"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Marking stream assignments as STARTED"}}
{"type": "TRACE", "trace": {"type": "STREAM_STATUS", "emitted_at": 1698214797168.268, "stream_status": {"stream_descriptor": {"name": "assignments", "namespace": null}, "status": "STARTED"}}}
{"type": "LOG", "log": {"level": "INFO", "message": "Syncing stream: assignments "}}
{"type": "LOG", "log": {"level": "INFO", "message": "Marking stream assignments as RUNNING"}}
{"type": "TRACE", "trace": {"type": "STREAM_STATUS", "emitted_at": 1698214797199.812, "stream_status": {"stream_descriptor": {"name": "assignments", "namespace": null}, "status": "RUNNING"}}}
{"type": "RECORD", "record": {"stream": "assignments", "data": {"uuid": "8c434be0144b4202ac3525fd1b1b58fd", "created_at": "2022-05-06T18:51:39.999551+02:00", "starts_at": "2022-06-01T00:00:00+02:00", "ends_at": "2022-06-07T23:59:59.999999+02:00", "end_local_date": "2022-06-07", "start_local_date": "2022-06-01", "updated_at": "2022-05-06T18:51:39.999991+02:00", "status": 0, "employee_id": "6b1cfb58b5c241b38ae14d44f74f117e", "label": "Label1", "note": "Assignment for full time only on fridays", "scheduling_mode": 3, "affects_capacity": false, "billable": true, "project_role_id": ["00e045cc6c2647619ed408696141da17"], "hash_tag_ids": ["2da6415a48904e13b827a516e6b2499e"], "color": "#E33B3B", "project_id": "6d0ab59e1348426d8d85746d452438cb", "project_phase_id": "165100162d6f4423bd49e0382859fe88", "total_tracked": 0, "total_scheduled": 480, "is_settled": false, "daily_data": {"start": "2022-05-31", "end": "2022-06-07", "tracked": [0, 0, 0, 0, 0, 0, 0], "scheduled": [0, 0, 480, 0, 0, 0, 0]}, "custom_attributes": [{"slug": "custom_attribute_for_assignment", "value": ["test2"]}], "background": false, "volatile_work_settings": false, "only_billable_work": false, "scheduling_time_frame": null, "scheduled_work_per_time_frame": null, "adjust_scheduling_to_time_off": false, "reduce_utilization_by_time_off": null, "adjust_scheduling_to_public_holidays": false, "reduce_utilization_by_public_holidays": null, "capacity_based_load": null, "use_billable_capacity": null, "work_by_capacity_per_monday": null, "work_by_capacity_per_tuesday": null, "work_by_capacity_per_wednesday": null, "work_by_capacity_per_thursday": null, "work_by_capacity_per_friday": null, "work_by_capacity_per_saturday": null, "work_by_capacity_per_sunday": null, "work_per_monday": 0, "work_per_tuesday": 0, "work_per_wednesday": 0, "work_per_thursday": 0, "work_per_friday": 480, "work_per_saturday": 0, "work_per_sunday": 0, "work_on_monday": null, "work_on_tuesday": null, "work_on_wednesday": null, "work_on_thursday": null, "work_on_friday": null, "work_on_saturday": null, "work_on_sunday": null, "financial_budget_mode": 0, "financial_client_currency": "PLN", "financial_client_currency_exchange_rate": "1.0000", "financial_total_scheduled_income": {"amount": 800, "currency": "PLN", "exchange_rate": 1}, "financial_total_scheduled_cost": {"amount": 238.1, "currency": "PLN", "exchange_rate": 1}, "financial_total_tracked_cost": {"amount": 0, "currency": "PLN", "exchange_rate": 1}, "financial_total_tracked_income": {"amount": 0, "currency": "PLN", "exchange_rate": 1}, "financial_settled_income": null, "financial_settled_cost": null, "financial_total_work_for_cost": 0, "financial_contractor_hour_cost": null, "financial_hour_rate": {"amount": 100, "currency": "PLN", "exchange_rate": 1}, "financial_employee_default_hour_cost": {"amount": 29.76, "currency": "PLN", "exchange_rate": 1}, "financial_use_default_hour_cost": null, "financial_default_hour_rate_source": 4, "financial_total_work_for_income": 0}, "emitted_at": 1698214797198}}
{"type": "RECORD", "record": {"stream": "assignments", "data": {"uuid": "23bdd9a0c6cd446886ede7253bcaf165", "created_at": "2022-05-06T18:52:50.372982+02:00", "starts_at": "2022-07-01T00:00:00+02:00", "ends_at": "2022-07-07T23:59:59.999999+02:00", "end_local_date": "2022-07-07", "start_local_date": "2022-07-01", "updated_at": "2022-05-06T18:52:50.373355+02:00", "status": 2, "employee_id": "2557a7e59c9146f585e43f4a930e9cd1", "label": "Label1", "note": "Assignment for full time only on fridays", "scheduling_mode": 3, "affects_capacity": false, "billable": true, "project_role_id": "00e045cc6c2647619ed408696141da17", "hash_tag_ids": ["2da6415a48904e13b827a516e6b2499e"], "color": "#E33B3B", "project_id": "6d0ab59e1348426d8d85746d452438cb", "project_phase_id": "165100162d6f4423bd49e0382859fe88", "total_tracked": 0, "total_scheduled": 480, "is_settled": false, "daily_data": {"start": "2022-06-30", "end": "2022-07-07", "tracked": [0, 0, 0, 0, 0, 0, 0], "scheduled": [480, 0, 0, 0, 0, 0, 0]}, "custom_attributes": [{"slug": "custom_attribute_for_assignment", "value": ["test2"]}], "background": false, "volatile_work_settings": false, "only_billable_work": false, "scheduling_time_frame": null, "scheduled_work_per_time_frame": null, "adjust_scheduling_to_time_off": false, "reduce_utilization_by_time_off": null, "adjust_scheduling_to_public_holidays": false, "reduce_utilization_by_public_holidays": null, "capacity_based_load": null, "use_billable_capacity": null, "work_by_capacity_per_monday": null, "work_by_capacity_per_tuesday": null, "work_by_capacity_per_wednesday": null, "work_by_capacity_per_thursday": null, "work_by_capacity_per_friday": null, "work_by_capacity_per_saturday": null, "work_by_capacity_per_sunday": null, "work_per_monday": 0, "work_per_tuesday": 0, "work_per_wednesday": 0, "work_per_thursday": 0, "work_per_friday": 480, "work_per_saturday": 0, "work_per_sunday": 0, "work_on_monday": null, "work_on_tuesday": null, "work_on_wednesday": null, "work_on_thursday": null, "work_on_friday": null, "work_on_saturday": null, "work_on_sunday": null, "financial_budget_mode": 0, "financial_client_currency": "PLN", "financial_client_currency_exchange_rate": "1.0000", "financial_total_scheduled_income": {"amount": 800, "currency": "PLN", "exchange_rate": 1}, "financial_total_scheduled_cost": {"amount": 238.1, "currency": "PLN", "exchange_rate": 1}, "financial_total_tracked_cost": {"amount": 0, "currency": "PLN", "exchange_rate": 1}, "financial_total_tracked_income": {"amount": 0, "currency": "PLN", "exchange_rate": 1}, "financial_settled_income": null, "financial_settled_cost": null, "financial_total_work_for_cost": 0, "financial_contractor_hour_cost": null, "financial_hour_rate": {"amount": 100, "currency": "PLN", "exchange_rate": 1}, "financial_employee_default_hour_cost": {"amount": 29.76, "currency": "PLN", "exchange_rate": 1}, "financial_use_default_hour_cost": null, "financial_default_hour_rate_source": 4, "financial_total_work_for_income": 0}, "emitted_at": 1698214797206}}
{"type": "RECORD", "record": {"stream": "assignments", "data": {"uuid": "8c434be0144b4202ac3525fd1b1b58f1", "created_at": "2022-05-06T18:51:39.999551+02:00", "starts_at": "2022-06-01T00:00:00+02:00", "ends_at": "2022-06-07T23:59:59.999999+02:00", "end_local_date": "2022-06-07", "start_local_date": "2022-06-01", "updated_at": "2022-05-06T18:51:39.999991+02:00", "status": 0, "employee_id": "6b1cfb58b5c241b38ae14d44f74f117e", "label": "Label1", "note": "Assignment for full time only on fridays", "scheduling_mode": 3, "affects_capacity": false, "billable": true, "project_role_id": ["00e045cc6c2647619ed408696141da17"], "hash_tag_ids": ["2da6415a48904e13b827a516e6b2499e"], "color": "#E33B3B", "project_id": "6d0ab59e1348426d8d85746d452438c2", "project_phase_id": "165100162d6f4423bd49e0382859fe88", "total_tracked": 0, "total_scheduled": 480, "is_settled": false, "daily_data": {"start": "2022-05-31", "end": "2022-06-07", "tracked": [0, 0, 0, 0, 0, 0, 0], "scheduled": [0, 0, 480, 0, 0, 0, 0]}, "custom_attributes": [{"slug": "custom_attribute_for_assignment", "value": ["test2"]}], "background": false, "volatile_work_settings": false, "only_billable_work": false, "scheduling_time_frame": null, "scheduled_work_per_time_frame": null, "adjust_scheduling_to_time_off": false, "reduce_utilization_by_time_off": null, "adjust_scheduling_to_public_holidays": false, "reduce_utilization_by_public_holidays": null, "capacity_based_load": null, "use_billable_capacity": null, "work_by_capacity_per_monday": null, "work_by_capacity_per_tuesday": null, "work_by_capacity_per_wednesday": null, "work_by_capacity_per_thursday": null, "work_by_capacity_per_friday": null, "work_by_capacity_per_saturday": null, "work_by_capacity_per_sunday": null, "work_per_monday": 0, "work_per_tuesday": 0, "work_per_wednesday": 0, "work_per_thursday": 0, "work_per_friday": 480, "work_per_saturday": 0, "work_per_sunday": 0, "work_on_monday": null, "work_on_tuesday": null, "work_on_wednesday": null, "work_on_thursday": null, "work_on_friday": null, "work_on_saturday": null, "work_on_sunday": null, "financial_budget_mode": 0, "financial_client_currency": "PLN", "financial_client_currency_exchange_rate": "1.0000", "financial_total_scheduled_income": {"amount": 800, "currency": "PLN", "exchange_rate": 1}, "financial_total_scheduled_cost": {"amount": 238.1, "currency": "PLN", "exchange_rate": 1}, "financial_total_tracked_cost": {"amount": 0, "currency": "PLN", "exchange_rate": 1}, "financial_total_tracked_income": {"amount": 0, "currency": "PLN", "exchange_rate": 1}, "financial_settled_income": null, "financial_settled_cost": null, "financial_total_work_for_cost": 0, "financial_contractor_hour_cost": null, "financial_hour_rate": {"amount": 100, "currency": "PLN", "exchange_rate": 1}, "financial_employee_default_hour_cost": {"amount": 29.76, "currency": "PLN", "exchange_rate": 1}, "financial_use_default_hour_cost": null, "financial_default_hour_rate_source": 4, "financial_total_work_for_income": 0}, "emitted_at": 1698214797231}}
{"type": "RECORD", "record": {"stream": "assignments", "data": {"uuid": "23bdd9a0c6cd446886ede7253bcaf166", "created_at": "2022-05-06T18:52:50.372982+02:00", "starts_at": "2022-07-01T00:00:00+02:00", "ends_at": "2022-07-07T23:59:59.999999+02:00", "end_local_date": "2022-07-07", "start_local_date": "2022-07-01", "updated_at": "2022-05-06T18:52:50.373355+02:00", "status": 2, "employee_id": "2557a7e59c9146f585e43f4a930e9cd1", "label": "Label1", "note": "Assignment for full time only on fridays", "scheduling_mode": 3, "affects_capacity": false, "billable": true, "project_role_id": "00e045cc6c2647619ed408696141da17", "hash_tag_ids": ["2da6415a48904e13b827a516e6b2499e"], "color": "#E33B3B", "project_id": "6d0ab59e1348426d8d85746d452438cb", "project_phase_id": "165100162d6f4423bd49e0382859fe88", "total_tracked": 0, "total_scheduled": 480, "is_settled": false, "daily_data": {"start": "2022-06-30", "end": "2022-07-07", "tracked": [0, 0, 0, 0, 0, 0, 0], "scheduled": [480, 0, 0, 0, 0, 0, 0]}, "custom_attributes": [{"slug": "custom_attribute_for_assignment", "value": ["test2"]}], "background": false, "volatile_work_settings": false, "only_billable_work": false, "scheduling_time_frame": null, "scheduled_work_per_time_frame": null, "adjust_scheduling_to_time_off": false, "reduce_utilization_by_time_off": null, "adjust_scheduling_to_public_holidays": false, "reduce_utilization_by_public_holidays": null, "capacity_based_load": null, "use_billable_capacity": null, "work_by_capacity_per_monday": null, "work_by_capacity_per_tuesday": null, "work_by_capacity_per_wednesday": null, "work_by_capacity_per_thursday": null, "work_by_capacity_per_friday": null, "work_by_capacity_per_saturday": null, "work_by_capacity_per_sunday": null, "work_per_monday": 0, "work_per_tuesday": 0, "work_per_wednesday": 0, "work_per_thursday": 0, "work_per_friday": 480, "work_per_saturday": 0, "work_per_sunday": 0, "work_on_monday": null, "work_on_tuesday": null, "work_on_wednesday": null, "work_on_thursday": null, "work_on_friday": null, "work_on_saturday": null, "work_on_sunday": null, "financial_budget_mode": 0, "financial_client_currency": "PLN", "financial_client_currency_exchange_rate": "1.0000", "financial_total_scheduled_income": {"amount": 800, "currency": "PLN", "exchange_rate": 1}, "financial_total_scheduled_cost": {"amount": 238.1, "currency": "PLN", "exchange_rate": 1}, "financial_total_tracked_cost": {"amount": 0, "currency": "PLN", "exchange_rate": 1}, "financial_total_tracked_income": {"amount": 0, "currency": "PLN", "exchange_rate": 1}, "financial_settled_income": null, "financial_settled_cost": null, "financial_total_work_for_cost": 0, "financial_contractor_hour_cost": null, "financial_hour_rate": {"amount": 100, "currency": "PLN", "exchange_rate": 1}, "financial_employee_default_hour_cost": {"amount": 29.76, "currency": "PLN", "exchange_rate": 1}, "financial_use_default_hour_cost": null, "financial_default_hour_rate_source": 4, "financial_total_work_for_income": 0}, "emitted_at": 1698214797238}}
{"type": "RECORD", "record": {"stream": "assignments", "data": {"uuid": "8c434be0144b4202ac3525fd1b1b58f3", "created_at": "2022-05-06T18:51:39.999551+02:00", "starts_at": "2022-06-01T00:00:00+02:00", "ends_at": "2022-06-07T23:59:59.999999+02:00", "end_local_date": "2022-06-07", "start_local_date": "2022-06-01", "updated_at": "2022-05-06T18:51:39.999991+02:00", "status": 0, "employee_id": "6b1cfb58b5c241b38ae14d44f74f117e", "label": "Label1", "note": "Assignment for full time only on fridays", "scheduling_mode": 3, "affects_capacity": false, "billable": true, "project_role_id": ["00e045cc6c2647619ed408696141da17"], "hash_tag_ids": ["2da6415a48904e13b827a516e6b2499e"], "color": "#E33B3B", "project_id": "6d0ab59e1348426d8d85746d452438cb", "project_phase_id": "165100162d6f4423bd49e0382859fe88", "total_tracked": 0, "total_scheduled": 480, "is_settled": false, "daily_data": {"start": "2022-05-31", "end": "2022-06-07", "tracked": [0, 0, 0, 0, 0, 0, 0], "scheduled": [0, 0, 480, 0, 0, 0, 0]}, "custom_attributes": [{"slug": "custom_attribute_for_assignment", "value": ["test2"]}], "background": false, "volatile_work_settings": false, "only_billable_work": false, "scheduling_time_frame": null, "scheduled_work_per_time_frame": null, "adjust_scheduling_to_time_off": false, "reduce_utilization_by_time_off": null, "adjust_scheduling_to_public_holidays": false, "reduce_utilization_by_public_holidays": null, "capacity_based_load": null, "use_billable_capacity": null, "work_by_capacity_per_monday": null, "work_by_capacity_per_tuesday": null, "work_by_capacity_per_wednesday": null, "work_by_capacity_per_thursday": null, "work_by_capacity_per_friday": null, "work_by_capacity_per_saturday": null, "work_by_capacity_per_sunday": null, "work_per_monday": 0, "work_per_tuesday": 0, "work_per_wednesday": 0, "work_per_thursday": 0, "work_per_friday": 480, "work_per_saturday": 0, "work_per_sunday": 0, "work_on_monday": null, "work_on_tuesday": null, "work_on_wednesday": null, "work_on_thursday": null, "work_on_friday": null, "work_on_saturday": null, "work_on_sunday": null, "financial_budget_mode": 0, "financial_client_currency": "PLN", "financial_client_currency_exchange_rate": "1.0000", "financial_total_scheduled_income": {"amount": 800, "currency": "PLN", "exchange_rate": 1}, "financial_total_scheduled_cost": {"amount": 238.1, "currency": "PLN", "exchange_rate": 1}, "financial_total_tracked_cost": {"amount": 0, "currency": "PLN", "exchange_rate": 1}, "financial_total_tracked_income": {"amount": 0, "currency": "PLN", "exchange_rate": 1}, "financial_settled_income": null, "financial_settled_cost": null, "financial_total_work_for_cost": 0, "financial_contractor_hour_cost": null, "financial_hour_rate": {"amount": 100, "currency": "PLN", "exchange_rate": 1}, "financial_employee_default_hour_cost": {"amount": 29.76, "currency": "PLN", "exchange_rate": 1}, "financial_use_default_hour_cost": null, "financial_default_hour_rate_source": 4, "financial_total_work_for_income": 0}, "emitted_at": 1698214797270}}
{"type": "RECORD", "record": {"stream": "assignments", "data": {"uuid": "23bdd9a0c6cd446886ede7253bcaf164", "created_at": "2022-05-06T18:52:50.372982+02:00", "starts_at": "2022-07-01T00:00:00+02:00", "ends_at": "2022-07-07T23:59:59.999999+02:00", "end_local_date": "2022-07-07", "start_local_date": "2022-07-01", "updated_at": "2022-05-06T18:52:50.373355+02:00", "status": 2, "employee_id": "2557a7e59c9146f585e43f4a930e9cd1", "label": "Label1", "note": "Assignment for full time only on fridays", "scheduling_mode": 3, "affects_capacity": false, "billable": true, "project_role_id": "00e045cc6c2647619ed408696141da17", "hash_tag_ids": ["2da6415a48904e13b827a516e6b2499e"], "color": "#E33B3B", "project_id": "6d0ab59e1348426d8d85746d452438cb", "project_phase_id": "165100162d6f4423bd49e0382859fe88", "total_tracked": 0, "total_scheduled": 480, "is_settled": false, "daily_data": {"start": "2022-06-30", "end": "2022-07-07", "tracked": [0, 0, 0, 0, 0, 0, 0], "scheduled": [480, 0, 0, 0, 0, 0, 0]}, "custom_attributes": [{"slug": "custom_attribute_for_assignment", "value": ["test2"]}], "background": false, "volatile_work_settings": false, "only_billable_work": false, "scheduling_time_frame": null, "scheduled_work_per_time_frame": null, "adjust_scheduling_to_time_off": false, "reduce_utilization_by_time_off": null, "adjust_scheduling_to_public_holidays": false, "reduce_utilization_by_public_holidays": null, "capacity_based_load": null, "use_billable_capacity": null, "work_by_capacity_per_monday": null, "work_by_capacity_per_tuesday": null, "work_by_capacity_per_wednesday": null, "work_by_capacity_per_thursday": null, "work_by_capacity_per_friday": null, "work_by_capacity_per_saturday": null, "work_by_capacity_per_sunday": null, "work_per_monday": 0, "work_per_tuesday": 0, "work_per_wednesday": 0, "work_per_thursday": 0, "work_per_friday": 480, "work_per_saturday": 0, "work_per_sunday": 0, "work_on_monday": null, "work_on_tuesday": null, "work_on_wednesday": null, "work_on_thursday": null, "work_on_friday": null, "work_on_saturday": null, "work_on_sunday": null, "financial_budget_mode": 0, "financial_client_currency": "PLN", "financial_client_currency_exchange_rate": "1.0000", "financial_total_scheduled_income": {"amount": 800, "currency": "PLN", "exchange_rate": 1}, "financial_total_scheduled_cost": {"amount": 238.1, "currency": "PLN", "exchange_rate": 1}, "financial_total_tracked_cost": {"amount": 0, "currency": "PLN", "exchange_rate": 1}, "financial_total_tracked_income": {"amount": 0, "currency": "PLN", "exchange_rate": 1}, "financial_settled_income": null, "financial_settled_cost": null, "financial_total_work_for_cost": 0, "financial_contractor_hour_cost": null, "financial_hour_rate": {"amount": 100, "currency": "PLN", "exchange_rate": 1}, "financial_employee_default_hour_cost": {"amount": 29.76, "currency": "PLN", "exchange_rate": 1}, "financial_use_default_hour_cost": null, "financial_default_hour_rate_source": 4, "financial_total_work_for_income": 0}, "emitted_at": 1698214797278}}
{"type": "LOG", "log": {"level": "INFO", "message": "Read 6 records from assignments stream"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Marking stream assignments as STOPPED"}}
{"type": "TRACE", "trace": {"type": "STREAM_STATUS", "emitted_at": 1698214797283.0342, "stream_status": {"stream_descriptor": {"name": "assignments", "namespace": null}, "status": "COMPLETE"}}}
{"type": "LOG", "log": {"level": "INFO", "message": "Finished syncing assignments"}}
{"type": "LOG", "log": {"level": "INFO", "message": "SourcePrimetric runtimes:\nSyncing stream assignments 0:00:00.115337"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Marking stream rag_ratings as STARTED"}}
{"type": "TRACE", "trace": {"type": "STREAM_STATUS", "emitted_at": 1698214797284.219, "stream_status": {"stream_descriptor": {"name": "rag_ratings", "namespace": null}, "status": "STARTED"}}}
{"type": "LOG", "log": {"level": "INFO", "message": "Syncing stream: rag_ratings "}}
{"type": "LOG", "log": {"level": "INFO", "message": "Marking stream rag_ratings as RUNNING"}}
{"type": "TRACE", "trace": {"type": "STREAM_STATUS", "emitted_at": 1698214797318.6392, "stream_status": {"stream_descriptor": {"name": "rag_ratings", "namespace": null}, "status": "RUNNING"}}}
{"type": "RECORD", "record": {"stream": "rag_ratings", "data": {"project_url": "https://api.primetric.com/beta/projects/00e045cc6c2647619ed408696141da17/", "project_id": "00e045cc6c2647619ed408696141da17", "rag_ratings": [{"text": "First_RAG", "value": 3, "rag_scope_uuid": "2da6415a48904e13b827a516e6b2499e"}]}, "emitted_at": 1698214797317}}
{"type": "RECORD", "record": {"stream": "rag_ratings", "data": {"project_url": "https://api.primetric.com/beta/projects/00e045cc6c2647619ed408696141da17/", "project_id": "00e045cc6c2647619ed408696141da17", "rag_ratings": [{"text": "First_RAG", "value": 1, "rag_scope_uuid": "6d0ab59e1348426d8d85746d452438cb"}]}, "emitted_at": 1698214797323}}
{"type": "LOG", "log": {"level": "INFO", "message": "Read 2 records from rag_ratings stream"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Marking stream rag_ratings as STOPPED"}}
{"type": "TRACE", "trace": {"type": "STREAM_STATUS", "emitted_at": 1698214797324.355, "stream_status": {"stream_descriptor": {"name": "rag_ratings", "namespace": null}, "status": "COMPLETE"}}}
{"type": "LOG", "log": {"level": "INFO", "message": "Finished syncing rag_ratings"}}
{"type": "LOG", "log": {"level": "INFO", "message": "SourcePrimetric runtimes:\nSyncing stream assignments 0:00:00.115337\nSyncing stream rag_ratings 0:00:00.040726"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Finished syncing SourcePrimetric"}}
```

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
I'm trying to get a Primetric account to run tests @puru-khedre sorry the delay to review your contribution.

**Comment by puru-khedre** [comment]
Do I need to do anything here?

**Comment by marcosmarxm** [comment]
Not yet @puru-khedre I'll return next week with an update.

**Comment by marcosmarxm** [comment]
Unfortunately, Airbyte couldn't obtain a sandbox account to perform integration tests, which is crucial for maintaining high-quality connectors in the catalog. Due to this issue, I am closing this pull request.

**Pull request closed without merging**
