### PR TITLE
Use Ruff for Python linting and auto-fix (draft)

### PR DESCRIPTION
**Pull request by aaronsteers**
## PR and Ruff Overview

[Ruff](https://beta.ruff.rs/docs/) is a very fast python linter and auto-fixer/auto-formatter written in Rust, replacing Flake8, isort, and a number of [others](https://beta.ruff.rs/docs/faq/#how-does-ruff-compare-to-flake8).

Rust is also very customizable - and you can find the rules config in `pyproject.toml` at the root of the repo.

To the question of speed, the entire repo can be scanned and patched in <3 seconds on my local machine, generating in this PR a couple thousand updates. All IDEs should support Ruff (lmk if yours doesn't), and Ruff is very fast in 'format-on-save' mode in VS Code for instance.

After this is merged, the entirety of our Python linting and formatting would be handled by `black`+`mypy`+`ruff`, with `isort` and `flake8` no longer needed.

## Call for feedback

Please review and provide suggestions by **Thursday August 31**. 

Since this touched so many files, we'll want to schedule the change at a time when it is minimally disruptive. If you have a pending PR you want this to wait for, or if you would like to initially exclude a specific set of directories that are being actively updated, please drop a comment below in this PR. Thanks!

Please see the Ruff documentation pages:

1. Ruff philoosphy: https://beta.ruff.rs/docs/
2. Ruff list of rules: https://beta.ruff.rs/docs/rules/

From their website:

> - ⚡️ 10-100x faster than existing linters
> - 🐍 Installable via pip
> - 🛠️ pyproject.toml support
> - 🤝 Python 3.11 compatibility
> - 📦 Built-in caching, to avoid re-analyzing unchanged files
> - 🔧 Autofix support, for automatic error correction (e.g., automatically remove unused imports)
> - 📏 Over 600 built-in rules
> - ⚖️ Near-parity with the built-in Flake8 rule set
> - 🔌 Native re-implementations of dozens of Flake8 plugins, like flake8-bugbear
> - ⌨️ First-party editor integrations for VS Code and more
> - 🌎 Monorepo-friendly, with hierarchical and cascading configuration

### Phase One

1. One-time auto-fix of all fixable rules (this PR, or a repeat of this PR).
2. Replace isort auto-fix in gradle with Ruff autofix. (Black remains in place as well.)
3. Developers get auto-fixes automatically when they run `format` in gradle, and/or by enabling Ruff in their IDE.
4. As per (2) above, CI-based auto-fix/auto-format tasks will additionally run Ruff (`ruff check --fix .`) going forward. (When/if we replace the auto-format with a slash command, those actions would move to the appropriate workflow as expected.)

Checklist for this PR:

- [x] Add PyProject.toml config.
- [x] Run auto-fix on our repo. (`ruff check --fix .`)
- [ ] Integrate with Gradle `format` command and the `airbyte-ci` CLI (replaces call to `isort` and `flake8`).

### Phase Two

1. We roll out a subset of rules that will fail the CI pipeline.
2. We ensure those rules selected are passing in the entire codebase.

### Phase Three

1. We organically expand the set of rules that will fail the CI pipeline.
2. We team up to burn down some of the tech debt by incrementally fixing specific sets of rules and optionally on specific code directories that we are actively developing on.

### CODE REVIEW

**Comment by postamar** [comment]
Wow, 3 seconds is very fast! If you make this part of the `format` and `airbytePythonFormat` tasks instead of `isort` and `black` and friends, we'll find that the ruff formatting itself is faster than pip-installing the ruff package itself.

I don't have strong opinions on python but if one linter can replace the 3 or 4 that we currently use then this should be a no-brainer.

**Comment by aaronsteers** [comment]
If anyone wants to test this out ahead of us merging this giant PR, or if you want to just see the config settings, I've created a smaller PR for that here:

- https://github.com/airbytehq/airbyte/pull/29866

**Comment by bnchrch** [comment]
Coming back to the python ecosystem after a long hiatus, the fragmentation of our linters felt wrong, and the fact that flake8 does not have a `--fix` flag was irksome. Thank you for taking the time to improve this.

**This has one huge 👍 from me, and Im particularly interested if inside of this year we can also replace black with this tool (once they implement the Ruff formatted)**


## Appendix
I had a couple questions coming in which I answered with some googling. Figured others would benefit

### Does this support "nearest config file discovery"
Yes. https://beta.ruff.rs/docs/configuration/#pyprojecttoml-discovery

### Does this support "config file inheritance"
Yes. 
```toml
# Extend the `pyproject.toml` file in the parent directory.
extend = "../pyproject.toml"
# But use a different line length.
line-length = 100
```

### Can this replace black and bring us from 4 tools to 1
No, but it is [coming soon](https://github.com/astral-sh/ruff/issues/1904), and currently it works with black.

**Comment by aaronsteers** [comment]
Replaced by:

- https://github.com/airbytehq/airbyte/pull/33251

**Pull request closed without merging**
