### PR TITLE
connector-templates: move generated code from `src` so `airbyte-ci` builds it

### LINKED ISSUE #35893: Connector generator: Investigate build issues
After moving the connector generator over to poetry, there is some cleanup that needs to be done. This was [reported by a community user](https://airbytehq-team.slack.com/archives/C027KKE4BCZ/p1709571981428719?thread_ts=1709151644.541239&cid=C027KKE4BCZ), I haven't reproduced yet. 

These are issues with [Step 7: building/running the connector in docker](https://docs.airbyte.com/connector-development/tutorials/cdk-tutorial-python-http/use-connector-in-airbyte)

## Option A: Building the docker image with airbyte-ci

`airbyte-ci build` build fails with 
```
Failed to build connector image for platform linux/amd64: lstat main.py: no such file or directory
```
This is likely because we have nested the generated connector into a `src` directory, but don't have handling for that in `airbyte-ci build`. Moving the generated files out of the src directory into the root fixes the issue as a workaround. 

## Option B: Building the docker image with a Dockerfile

Based on changes, the dockerfile here likely needs to be updated.

### PR DESCRIPTION
**Pull request by natikgadzhi**
### What

For newly generated python and low-code connectors, move sources from `src` to `source_%CONN_NAME%` so `airbyte-ci build` can pick them up correctly. Closes #35893.

### What changed?

- Moved the sources from `src`
- Updated package paths in `pyproject.toml` templates

### How to test?

You can make a new connector with `./generate.sh` and verify that it works with Poetry and that it builds with `airbyte-ci build --name source-test`

---

### CODE REVIEW

**Comment by natikgadzhi** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/36428?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#36428** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/36428?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#36427** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/36427?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @natikgadzhi and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alafanechere — APPROVED** [review]
@natikgadzhi I originally wanted to make connectors follow the [`src` layout as its a good python practice](https://py-pkgs.org/04-package-structure.html#the-source-layout). I might have done it too agressively and the build logic in airbyte-ci might not support it correctly indeed. 
I think the bug can be solved with a one line change [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/pipelines/airbyte_ci/connectors/build_image/steps/python_connectors.py#L84): including `src` instead of `connector_snake_case_name`. But if we want to support `flat` and `src`layout the logic has to change a bit more. So I'll 👍 this one 😄 

Can you please re-generate the scaffolds?
(or delete them? - I think no test are actually checking scaffolds are consistent with the generated code anymore).
```
 ./gradlew --no-daemon :airbyte-integrations:connector-templates:generator:generateScaffolds
```

I noticed you also deleted the java + configuration-based generator.
I'd suggest doing it in a separate PR in case we'd want to revert it.
And you should also remove `source-singer` as it's legacy too. I'd also challenge the usefulness `source-python` generator. If anyone wants to build a non-http python connector they can start off from the http one and remove the http related code.

**Comment by natikgadzhi** [comment]
### Merge activity

* **Mar 25, 1:01 PM EDT**: @natikgadzhi merged this pull request with [Graphite](https://app.graphite.dev/github/pr/airbytehq/airbyte/36428).

**Comment by natikgadzhi** [comment]
Whooops, this got merged with Graphite automatically on approval, but I will follow-up on @alafanechere's asks: 

- Removing `source-singer` is here: https://github.com/airbytehq/airbyte/pull/36427 — can you please give this one thumbs up so it also gets merged? They were stacked together, so I think it will need to be rebased.
- `Can you please re-generate the scaffolds?` — will do in a separate PR then!

**Comment by sukolenvo** [comment]
Seems like java connector has been removed in this PR. Tried to follow steps and it didn't work: https://docs.airbyte.com/connector-development/tutorials/building-a-java-destination

**Pull request merged**
