### PR TITLE
fix(source-zendesk-support) check `start_date` exists during check operation

### LINKED ISSUE #48890: [source-zendesk-support] Getting "Configuration check failed KeyError('start_date')" error
### Connector Name

N/A

### Connector Version

N/A

### What step the error happened?

Other

### Relevant information

I am unable to create a Connector as I am unable to add "Zendesk Support" as a data source. 

When trying to add the source, I enter my subdomain and verify with oAuth just fine.  When I click on "Set up source", it loads for a while then returns with this error:

```
Configuration check failed
KeyError('start_date')
```

Looking at your documentation, it seems "Start Date" is a parameter.  I am wondering if your logic handling the parameter is not configured correctly as it seems like an optional parameter.  Maybe it is not optional or that the underlying logic is written in such a way that is assumes it is always given.

### Relevant log output

```shell
I was able to grab this from the response to the POST call to https://cloud.airbyte.com/api/v1/scheduler/sources/check_connection as it appeared to be the logs.

        "logs": {
            "events": [
                {
                    "timestamp": 1733865933607,
                    "message": "",
                    "level": "info",
                    "logSource": "platform",
                    "caller": {
                        "className": "io.airbyte.commons.io.LineGobbler",
                        "methodName": "voidCall",
                        "lineNumber": 177,
                        "threadName": "pool-2-thread-1"
                    }
                },
                {
                    "timestamp": 1733865933699,
                    "message": "----- START CHECK -----",
                    "level": "info",
                    "logSource": "platform",
                    "caller": {
                        "className": "io.airbyte.commons.io.LineGobbler",
                        "methodName": "voidCall",
                        "lineNumber": 177,
                        "threadName": "pool-2-thread-1"
                    }
                },
                {
                    "timestamp": 1733865933700,
                    "message": "",
                    "level": "info",
                    "logSource": "platform",
                    "caller": {
                        "className": "io.airbyte.commons.io.LineGobbler",
                        "methodName": "voidCall",
                        "lineNumber": 177,
                        "threadName": "pool-2-thread-1"
                    }
                },
                {
                    "timestamp": 1733865935113,
                    "message": "Connector exited, processing output",
                    "level": "info",
                    "logSource": "platform",
                    "caller": {
                        "className": "io.airbyte.connectorSidecar.ConnectorWatcher",
                        "methodName": "processConnectorOutput",
                        "lineNumber": 116,
                        "threadName": "main"
                    }
                },
                {
                    "timestamp": 1733865935114,
                    "message": "Output file jobOutput.json found",
                    "level": "info",
                    "logSource": "platform",
                    "caller": {
                        "className": "io.airbyte.connectorSidecar.ConnectorWatcher",
                        "methodName": "getConnectorOutputStream",
                        "lineNumber": 153,
                        "threadName": "main"
                    }
                },
                {
                    "timestamp": 1733865935116,
                    "message": "Connector exited with exit code 0",
                    "level": "info",
                    "logSource": "platform",
                    "caller": {
                        "className": "io.airbyte.connectorSidecar.ConnectorWatcher",
                        "methodName": "processConnectorOutput",
                        "lineNumber": 119,
                        "threadName": "main"
                    }
                },
                {
                    "timestamp": 1733865935119,
                    "message": "Reading messages from protocol version 0.2.0",
                    "level": "info",
                    "logSource": "platform",
                    "caller": {
                        "className": "io.airbyte.workers.internal.VersionedAirbyteStreamFactory",
                        "methodName": "create",
                        "lineNumber": 195,
                        "threadName": "main"
                    }
                },
                {
                    "timestamp": 1733865935120,
                    "message": "MetricClient has not been initialized. Must call MetricClientFactory.CreateMetricClient before using MetricClient. Using a dummy client for now. Ignore this if Airbyte is configured to not publish any metrics.",
                    "level": "warn",
                    "logSource": "platform",
                    "caller": {
                        "className": "io.airbyte.metrics.lib.MetricClientFactory",
                        "methodName": "getMetricClient",
                        "lineNumber": 43,
                        "threadName": "main"
                    }
                },
                {
                    "timestamp": 1733865935188,
                    "message": "Check failed",
                    "level": "error",
                    "logSource": "platform",
                    "caller": {
                        "className": "io.airbyte.workers.internal.VersionedAirbyteStreamFactory",
                        "methodName": "internalLog",
                        "lineNumber": 310,
                        "threadName": "main"
                    }
                },
                {
                    "timestamp": 1733865935190,
                    "message": "Checking for optional control message...",
                    "level": "info",
                    "logSource": "platform",
                    "caller": {
                        "className": "io.airbyte.connectorSidecar.ConnectorMessageProcessor",
                        "methodName": "updateConfigFromControlMessage",
                        "lineNumber": 232,
                        "threadName": "main"
                    }
                },
                {
                    "timestamp": 1733865935191,
                    "message": "Optional control message not found. Skipping...",
                    "level": "info",
                    "logSource": "platform",
                    "caller": {
                        "className": "io.airbyte.connectorSidecar.ConnectorMessageProcessor",
                        "methodName": "updateConfigFromControlMessage",
                        "lineNumber": 254,
                        "threadName": "main"
                    }
                },
                {
                    "timestamp": 1733865935193,
                    "message": "Writing output of 79c1aa37-dae3-42ae-b333-d1c105477715_f21b66f2-9fd9-4c02-bf76-df1723ec16b5_0_check to the doc store",
                    "level": "info",
                    "logSource": "platform",
                    "caller": {
                        "className": "io.airbyte.connectorSidecar.ConnectorWatcher",
                        "methodName": "saveConnectorOutput",
                        "lineNumber": 164,
                        "threadName": "main"
                    }
                },
                {
                    "timestamp": 1733865935362,
                    "message": "Marking workload 79c1aa37-dae3-42ae-b333-d1c105477715_f21b66f2-9fd9-4c02-bf76-df1723ec16b5_0_check as successful",
                    "level": "info",
                    "logSource": "platform",
                    "caller": {
                        "className": "io.airbyte.connectorSidecar.ConnectorWatcher",
                        "methodName": "markWorkloadSuccess",
                        "lineNumber": 169,
                        "threadName": "main"
                    }
                },
                {
                    "timestamp": 1733865935441,
                    "message": "",
                    "level": "info",
                    "logSource": "platform",
                    "caller": {
                        "className": "io.airbyte.commons.io.LineGobbler",
                        "methodName": "voidCall",
                        "lineNumber": 177,
                        "threadName": "pool-4-thread-1"
                    }
                },
                {
                    "timestamp": 1733865935441,
                    "message": "Deliberately exiting process with code 0.",
                    "level": "info",
                    "logSource": "platform",
                    "caller": {
                        "className": "io.airbyte.connectorSidecar.ConnectorWatcher",
                        "methodName": "exitProperly",
                        "lineNumber": 213,
                        "threadName": "main"
                    }
                },
                {
                    "timestamp": 1733865935442,
                    "message": "----- END CHECK -----",
                    "level": "info",
                    "logSource": "platform",
                    "caller": {
                        "className": "io.airbyte.commons.io.LineGobbler",
                        "methodName": "voidCall",
                        "lineNumber": 177,
                        "threadName": "pool-4-thread-1"
                    }
                },
                {
                    "timestamp": 1733865935442,
                    "message": "",
                    "level": "info",
                    "logSource": "platform",
                    "caller": {
                        "className": "io.airbyte.commons.io.LineGobbler",
                        "methodName": "voidCall",
                        "lineNumber": 177,
                        "threadName": "pool-4-thread-1"
                    }
                }
            ],
```

### Contribute

- [ ] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by brian-pinwheel**
Fixes #48890 
…it is and than assuming it is, parsing it and then discarding it.

## What
`start_date` [is optional for the Zendesk Connector](https://docs.airbyte.com/integrations/sources/zendesk-support#reference) but the current code requires it, but then never even uses it.

## How
Check if the data is passed.  If so, validate it and use it, otherwise, use None, which is the existing behavior.

## Review guide
Sorry, I have no idea what this means

## User Impact
Users will be able to use the Zendesk Support connector again as right now it fails.

## Can this PR be safely reverted and rolled back?
- [ X ] YES 💚
- [ ] NO ❌

Note: I am not a Python developer and haven't spent more than 40 minutes with this repo, but I can tell where the issue is.  I was able to piece together what I think should work, but don't have Python installed on my machine.  I would REALLY appreciate anyone's help to correct any and all mistakes I may have made.  I figured trying to solve it was better than pointing a finger at the code.

### CODE REVIEW

**Comment by brian-pinwheel** [comment]
Issue https://github.com/airbytehq/airbyte/issues/48890

**Comment by marcosmarxm** [comment]
@brian-pinwheel need you to sign the CLA to continue the review process. Thanks

**Comment by brian-pinwheel** [comment]
> @brian-pinwheel need you to sign the CLA to continue the review process. Thanks

I think it should be signed now.  I am very curious about the code review as since I am not a Python dev nor understand how to run it, I am not user if it actually solves the issue or not.

**Comment by natikgadzhi** [comment]
Nice patch, thank you! 

What is interesting is that this does not seem to be super wide-spread, and the code that does this `datetime.strptime` thing in check basically only validates it's format (which is a very weird way to do it, we have better tools today). 

I.e. previously, we could request `UserSettingsStream` without start_date and things were fine, but for you — it clearly fails. 

Still looking.

**Comment by natikgadzhi** [comment]
> start_date [is optional for the Zendesk Connector](https://docs.airbyte.com/integrations/sources/zendesk-support#reference) but the current code requires it

That's the thing — it generally should not. I.e. previous check code does not seem to require it, but I wonder if there was a recent underlying change in the base stream class, looking into it now.

**Comment by natikgadzhi** [comment]
The code change in this PR itself would not affect any other syncs in a negative way, so we can merge this.

@brian-pinwheel Ideally, this fixes your problem. Worst case scenario is if there was some underlying code change on the base stream classes that triggers this, but did not show up on the trace. 

Once the new version is published, we should see it pretty soon.

**Review by natikgadzhi — APPROVED** [review]

**Pull request merged**
