### PR TITLE
🎉 JDBC source: adjust fetch size based on max memory and max row size

### PR DESCRIPTION
**Pull request by tuliren**
## What
- Relate to https://github.com/airbytehq/alpha-beta-issues/issues/107.
- Relate to https://github.com/airbytehq/airbyte/issues/13299.

## How
- Allocate 50% of max heap as JDBC buffer.
- Calculate fetch size based on the max row size to be safer.

## 🚨 User Impact 🚨
- So far, this update is only published for MS SQL.
- This PR should reduce the possibility of OOME.
- The fetch size will continue to go down in one sync. This could theoretically slow down Postgres sync.
    - This is mitigated by a total buffer size that can grow with the max heap.
    - The ultimate change we can do to mitigate the impact is to checkpoint the states more frequently, and replace a big and long sync with shorter syncs.

### CODE REVIEW

**Review by edgao — APPROVED** [review]

**Comment by tuliren** [comment]
Postgres will be published in a follow-up PR.

**Pull request merged**
