### PR TITLE
:sparkles: Source Slack Source Linkedin Ads: connector health: fix unit tests

### PR DESCRIPTION
**Pull request by darynaishchenko**
## What
`TypeError: expected str, bytes or os.PathLike object, not NoneType�[0m`

## How
*Describe the solution*
added request cache path env var for unittests

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-linkedin-ads test report (commit [`2e3b8bc528`](https://github.com/airbytehq/airbyte/pull/31052/commits/2e3b8bc528df3bbe31a020f473f65aa09abf7e29)) - ❌

⏲️  Total pipeline duration: 10mn06s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Connector package install                                        | ✅        |
| Build source-linkedin-ads docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                       | ✅        |
| Acceptance tests                                                 | ❌        |
| Code format checks                                               | ✅        |
| Validate metadata for source-linkedin-ads                        | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-slack_source-linkedin-ads_fix-unittests/1696426014/2e3b8bc528df3bbe31a020f473f65aa09abf7e29/source-linkedin-ads/0.6.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:2e3b8bc528df3bbe31a020f473f65aa09abf7e29)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-linkedin-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-linkedin-ads test report (commit [`fa0cee0ce9`](https://github.com/airbytehq/airbyte/pull/31052/commits/fa0cee0ce907505ea394e62ac90fde04b36084d8)) - ❌

⏲️  Total pipeline duration: 04mn33s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Connector package install                                        | ✅        |
| Build source-linkedin-ads docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                       | ✅        |
| Acceptance tests                                                 | ❌        |
| Code format checks                                               | ✅        |
| Validate metadata for source-linkedin-ads                        | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-slack_source-linkedin-ads_fix-unittests/1696426854/fa0cee0ce907505ea394e62ac90fde04b36084d8/source-linkedin-ads/0.6.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:fa0cee0ce907505ea394e62ac90fde04b36084d8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-linkedin-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-slack test report (commit [`fa0cee0ce9`](https://github.com/airbytehq/airbyte/pull/31052/commits/fa0cee0ce907505ea394e62ac90fde04b36084d8)) - ✅

⏲️  Total pipeline duration: 71mn52s 

| Step                                                      | Result   |
|:----------------------------------------------------------|:---------|
| Connector package install                                 | ✅        |
| Build source-slack docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                | ✅        |
| Acceptance tests                                          | ✅        |
| Code format checks                                        | ✅        |
| Validate metadata for source-slack                        | ✅        |
| Connector version semver check                            | ✅        |
| QA checks                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-slack_source-linkedin-ads_fix-unittests/1696426854/fa0cee0ce907505ea394e62ac90fde04b36084d8/source-slack/0.3.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:fa0cee0ce907505ea394e62ac90fde04b36084d8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-slack test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-slack test report (commit [`39d29d5f4a`](https://github.com/airbytehq/airbyte/pull/31052/commits/39d29d5f4ad69f42c8168cd85891ecdf0fd090fa)) - ✅

⏲️  Total pipeline duration: 12mn58s 

| Step                                                      | Result   |
|:----------------------------------------------------------|:---------|
| Connector package install                                 | ✅        |
| Build source-slack docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                | ✅        |
| Acceptance tests                                          | ✅        |
| Code format checks                                        | ✅        |
| Validate metadata for source-slack                        | ✅        |
| Connector version semver check                            | ✅        |
| QA checks                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-slack_source-linkedin-ads_fix-unittests/1696432355/39d29d5f4ad69f42c8168cd85891ecdf0fd090fa/source-slack/0.3.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:39d29d5f4ad69f42c8168cd85891ecdf0fd090fa)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-slack test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-linkedin-ads test report (commit [`45009b80ba`](https://github.com/airbytehq/airbyte/pull/31052/commits/45009b80bafaa93210f85814381eecc29e749afb)) - ✅

⏲️  Total pipeline duration: 10mn30s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Connector package install                                           | ✅        |
| Build source-linkedin-ads docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                          | ✅        |
| Acceptance tests                                                    | ✅        |
| Code format checks                                                  | ✅        |
| Validate metadata for source-linkedin-ads                           | ✅        |
| Connector version semver check                                      | ✅        |
| QA checks                                                           | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-slack_source-linkedin-ads_fix-unittests/1696513233/45009b80bafaa93210f85814381eecc29e749afb/source-linkedin-ads/0.6.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:45009b80bafaa93210f85814381eecc29e749afb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-linkedin-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-slack test report (commit [`45009b80ba`](https://github.com/airbytehq/airbyte/pull/31052/commits/45009b80bafaa93210f85814381eecc29e749afb)) - ✅

⏲️  Total pipeline duration: 71mn55s 

| Step                                                         | Result   |
|:-------------------------------------------------------------|:---------|
| Connector package install                                    | ✅        |
| Build source-slack docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                   | ✅        |
| Acceptance tests                                             | ✅        |
| Code format checks                                           | ✅        |
| Validate metadata for source-slack                           | ✅        |
| Connector version semver check                               | ✅        |
| QA checks                                                    | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryna_source-slack_source-linkedin-ads_fix-unittests/1696513233/45009b80bafaa93210f85814381eecc29e749afb/source-slack/0.3.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:45009b80bafaa93210f85814381eecc29e749afb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-slack test
```

**Review by artem1205 — APPROVED** [review]

**Pull request merged**
