### PR TITLE
🐛 Source Salesforce: fix string with only digits inferred as float

### PR DESCRIPTION
**Pull request by jeremySrgt**
## What
Currently if field marked as a string in a Salesforce object contain only digits, it's inferred as float during the sync.
For example, if we have a ZipCode filed with value in Salesforce "01234" during the extraction it will be converted to a float with value 1234.0
So it leads to inconsistent data types between the source and the destination
related issue https://github.com/airbytehq/airbyte/issues/25350

## How
The part responsible for such a conversion of data types is pandas when reading a csv file during the reading of chunks
By explicitly adding dtype to the _read_csv()_ method we avoid pandas inferring the wrong data types
```
  try:
      with open(path, "r", encoding=file_encoding) as data:
          chunks = pd.read_csv(data, chunksize=chunk_size, iterator=True, dialect="unix", dtype=object)
          for chunk in chunks:
              chunk = chunk.replace({nan: None}).to_dict(orient="records")
              for row in chunk:
                  yield row
  except pd.errors.EmptyDataError as e:
      self.logger.info(f"Empty data received. {e}")
      yield from []
```

At first all the data will have the same type but the rights data type is enforced later in the process thanks to the generated schema so records will have the correct data type once the extraction is finished and the data loaded in the destination

## Recommended reading order
1. `airbyte-integrations/connectors/source-salesforce/source_salesforce/streams.py`
2. `airbyte-integrations/connectors/source-salesforce/unit_tests/api_test.py`

## 🚨 User Impact 🚨
No breaking change

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

### CODE REVIEW

**Comment by dancook-doxo** [comment]
Will this PR by chance also fix the issue where "N/A" in a string is converted to NULL?

**Comment by jeremySrgt** [comment]
> Will this PR by chance also fix the issue where "N/A" in a string is converted to NULL?

Yes it will since a string value with "N/A" is different than no value (null)

**Comment by marcosmarxm** [comment]
@jeremySrgt I escalated this to the connector team to get a second opinion. The code change will impact in other parts of the code.

**Comment by bazarnov** [comment]
I've checked the changes. It looks meaningful, but I'm afraid this change will break existing connections, and the Customers are required to reset the data and re-sync all over again. 

@jeremySrgt have you tested the transition between the existing connector version and your changes locally by creating the connection with `source-salesforce 2.0.12` and then upgrading it to your version and re-running the sync? this is important because `source-salesforce` is a `generally available` connector used widely across users, this behavior should be tested along with normalization. It's expected that sync will fail due to the actual data types coming from the source now will be different from what is declared in catalog and stream schemas.

**Comment by bazarnov** [comment]
@marcosmarxm @jeremySrgt 
I'll continue with the review and finish it after the previous comment is resolved either way.

**Comment by dancook-doxo** [comment]
As one of the affected customers (indeed, the customer who originally
reported the core issue <https://github.com/airbytehq/airbyte/issues/25350>)
I would be more than happy to reset and re-sync our Salesforce data if it
gets me away from this annoying bug.

**Comment by bazarnov** [comment]
@jeremySrgt @marcosmarxm Please poke me once the upgrade flow is tested, and I'll go with the review again. Thanks!

**Comment by jeremySrgt** [comment]
@bazarnov wil do !
I will try to find the time today or during the week end :)

**Comment by bnchrch** [comment]
@jeremySrgt Just chiming in to say thank you for taking the time to submit this PR. The whole Airbyte community is made better by contributions like this. 🙏 

And @dancook-doxo thanks for being as engaged and helpful as always.

Ping me as well when this is ready for a rereview!

**Comment by jeremySrgt** [comment]
@bazarnov @marcosmarxm 

I have tested the transition between the existing connector version and the version with the changes made by this PR
As you said, I created the connection with source-salesforce 2.0.13 and then upgraded it to my version called "fix-salesforce" and re-ran the sync with several sync modes **without resetting the stream**
Here is the results :

| connector version | previous connector version | sync mode |normalization passed | success |
|--------|--------|--------|--------|--------|
| 2.0.13 | null | full refresh - overwrite | ✅  | ✅  |
| fix-salesforce | 2.0.13 | full refresh - overwrite | ✅ | ✅ |
| fix-salesforce | 2.0.13 | full refresh - append | ✅ | ✅ |

All passed without needing a stream and data reset
Indeed, I checked my columns type in my destination (redshift) and they remained the same for each test I made.
So, after upgrading from version 2.0.13 to "fix-salesforce" the _varchar_ remained _varchar_, _boolean_ remained _boolean_, _timestamp_ remained _timestamp_, and so on...
That's why the connection didn't fail despite not resetting the stream

**Comment by bazarnov** [comment]
awesome approach! thanks for the effort!

**Review by bazarnov — APPROVED** [review]
LGTM! But the metadata.yaml inside salesforce dir should also have the same tag version as Dockerfile, please correct this.

**Comment by jeremySrgt** [comment]
@bazarnov 
I made the changes 👍

**Comment by bazarnov** [comment]
@marcosmarxm Could you please assist further here? 
There should be CAT passed as well as a pre-merge checklist checked, before this could be merged in.

**Comment by dancook-doxo** [comment]
As a customer of Airbyte Cloud, how will I be made aware that the Salesforce connector was silently upgraded to version `2.0.14` or higher and therefore this bug no longer affects my syncs? At that point we can remove the bogus formula fields that we had to add in Salesforce to 'spoof' older versions of the connector.

**Comment by dancook-doxo** [comment]
Still wondering when Airbyte Cloud will upgrade to 2.0.14+ and also how I can know this happened other than periodically checking my `/settings/source` page or the tables written to by Salesforce.

**Pull request merged**
