### PR TITLE
:rotating_light: :rotating_light: Source Stripe: fix schemas

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://airbyte-globallogic.slack.com/archives/C02U9R3AF37/p1698084318157189

## How
Fix the `default_tax_rates` schema in the `Invoices`, `Subscriptions`, `SubscriptionSchedule` streams

## 🚨 User Impact 🚨
This is a breaking change as the stream schemas are changed. Users will have to refresh their schemas

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-stripe test report (commit [`1b6f36b50b`](https://github.com/airbytehq/airbyte/pull/31767/commits/1b6f36b50b6f1c26cdff3ff2ea65f19b7d02368f)) - ✅

⏲️  Total pipeline duration: 09mn35s 

| Step                                                         | Result   |
|:-------------------------------------------------------------|:---------|
| Build source-stripe docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                   | ✅       |
| Acceptance tests                                             | ✅       |
| Check our base image is used                                 | ✅       |
| Code format checks                                           | ✅       |
| Validate metadata for source-stripe                          | ✅       |
| Connector version semver check                               | ✅       |
| Connector version increment check                            | ✅       |
| QA checks                                                    | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_source-stripe-fix-default-tax-rates-schema/1698143663/1b6f36b50b6f1c26cdff3ff2ea65f19b7d02368f/source-stripe/5.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1b6f36b50b6f1c26cdff3ff2ea65f19b7d02368f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Review by bazarnov — APPROVED** [review]

**Review by tolik0 — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-stripe test report (commit [`a87c299a3c`](https://github.com/airbytehq/airbyte/pull/31767/commits/a87c299a3c342bb7cd40b1df130a77a59a84361f)) - ✅

⏲️  Total pipeline duration: 04mn39s 

| Step                                                         | Result   |
|:-------------------------------------------------------------|:---------|
| Build source-stripe docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                   | ✅       |
| Acceptance tests                                             | ✅       |
| Check our base image is used                                 | ✅       |
| Code format checks                                           | ✅       |
| Validate metadata for source-stripe                          | ✅       |
| Connector version semver check                               | ✅       |
| Connector version increment check                            | ✅       |
| QA checks                                                    | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_source-stripe-fix-default-tax-rates-schema/1698145213/a87c299a3c342bb7cd40b1df130a77a59a84361f/source-stripe/5.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:a87c299a3c342bb7cd40b1df130a77a59a84361f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-stripe test report (commit [`fa1aaa0a4c`](https://github.com/airbytehq/airbyte/pull/31767/commits/fa1aaa0a4c63433bfe09303483e385dd154272e2)) - ✅

⏲️  Total pipeline duration: 08mn22s 

| Step                                                         | Result   |
|:-------------------------------------------------------------|:---------|
| Build source-stripe docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                   | ✅       |
| Acceptance tests                                             | ✅       |
| Check our base image is used                                 | ✅       |
| Code format checks                                           | ✅       |
| Validate metadata for source-stripe                          | ✅       |
| Connector version semver check                               | ✅       |
| Connector version increment check                            | ✅       |
| QA checks                                                    | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_source-stripe-fix-default-tax-rates-schema/1698320493/fa1aaa0a4c63433bfe09303483e385dd154272e2/source-stripe/5.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:fa1aaa0a4c63433bfe09303483e385dd154272e2)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by kev-datams** [comment]
Linked to this issue https://github.com/airbytehq/airbyte/issues/32273

**Comment by kev-datams** [comment]
Hello @davydov-d,

You mentioned https://airbyte-globallogic.slack.com/archives/C02U9R3AF37/p1698084318157189 in your **What** PR description but this link is not reachable for non `airbyte.io` / `globallogic.com` domains.

How can we access original issue and discussions behind this PR ?

Thanks !

**Comment by davydov-d** [comment]
> Hello @davydov-d,
> 
> You mentioned https://airbyte-globallogic.slack.com/archives/C02U9R3AF37/p1698084318157189 in your **What** PR description but this link is not reachable for non `airbyte.io` / `globallogic.com` domains.
> 
> How can we access original issue and discussions behind this PR ?
> 
> Complementary question: do we have an ETA for the merge of this PR ?
> 
> Thanks !

:wave: @kev-datams 
I'm afraid you can not access this slack thread, but it only contains links to failed jobs in cloud env with the same exact problem you have described in the issue above.

Regarding the ETA - I'm hoping to release this PR along with https://github.com/airbytehq/airbyte/pull/32286 when I get one more approve (hope it should take a day or two) as a single update to decrease the number of breaking changes

**Comment by davydov-d** [comment]
Closing in favour of merging this update with https://github.com/airbytehq/airbyte/pull/32286

**Pull request closed without merging**
