### PR TITLE
[airbyte-cdk] Fix: Java CDK version.properties file

### PR DESCRIPTION
**Pull request by assaadhjb**
## What

Fixing `version.properties` gradle file in Airbyte Java CDK.

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by stephane-airbyte — APPROVED** [review]

**Comment by stephane-airbyte** [comment]
We really should prevent the CDK from compiling with a wrong version.properties

**Comment by theyueli** [comment]
@marcosmarxm is it possible to publish the java cdk using the command above for community PR like this?

**Comment by stephane-airbyte** [comment]
There’s no need. Just merge it, it’ll get auto-published

**Pull request merged**
