### PR TITLE
🐛 Source Airtable: fix `API Key` authentication

### PR DESCRIPTION
**Pull request by bazarnov**
## What
Resolving: 
- https://github.com/airbytehq/oncall/issues/1433
- https://github.com/airbytehq/oncall/issues/1432

## How
- added missing `api_key` authentication part with new `credentials` input config structure.

## 🚨 User Impact 🚨
No impact is expected.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Review by pedroslopez — APPROVED** [review]

**Comment by TBernstein4** [comment]
@bazarnov I noticed you unlinked the PR from the two OC issues. Was there a reason why, will this PR still fix those issues?

**Comment by bazarnov** [comment]
> @bazarnov I noticed you unlinked the PR from the two OC issues. Was there a reason why, will this PR still fix those issues?

Unlinked to avoid `auto-close` after the PR is merged into OSS master.

**Comment by TBernstein4** [comment]
That makes sense, I didn't realize that was the behavior, thank you for explaining! Do you know when this will be merged?

**Pull request merged**
