### PR TITLE
fix(source-klaus-api): replace png icon with real svg

### PR DESCRIPTION
**Pull request by lmossman**
## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by lmossman** [comment]
The change files still looks borked because it can't show the "deleted lines", as the original file had a `.svg` extension despite having PNG contents

So for the reviewer I would recommend just checking out this branch locally and looking at the new icon

**Comment by natikgadzhi** [comment]
The icon preview looks sus, but I think it's ok tbh.

**Comment by lmossman** [comment]
@natikgadzhi see my comment above, if you want to see the new icon you'll need to check it out locally

**Review by natikgadzhi — APPROVED** [review]
low risk, let's merge and see if the icon upload works without version bump (I believe it does)

**Pull request merged**
