### PR TITLE
Update specs and definitions files for destination-postgres 0.3.19

### PR DESCRIPTION
**Pull request by noahkawasaki-airbyte**
## What
Previously I could not publish a PR due to another inflight PR having already done a version bump but that has now merged. I have published this version and this is a PR to update the definitions and spec files to make the version usable.

Previous PR: https://github.com/airbytehq/airbyte/pull/12195 0.3.19

## Recommended reading order
1. `x.java`
2. `y.python`

### CODE REVIEW

**Comment by noahkawasaki-airbyte** [comment]
/publish connector=connectors/destination-postgres auto-bump-version=false

**Review by edgao — APPROVED** [review]
it looks like 0.3.19 already exists? not sure if that's expected.

also, did your changes affect destination-postgres-strict-encrypt? (if yes, you should publish it as well)

**Comment by noahkawasaki-airbyte** [comment]
0.3.19 already exists yeah, I had previously published. Release workflow for this was confusing me lol.

This change would affect strict encrypt postgres destinations, I dont see any YAML entries for this destination though, should I just bump the Dockerfile for strict encrypt destination postgres?

**Comment by noahkawasaki-airbyte** [comment]
/publish connector=connectors/destination-postgres-strict-encrypt

**Comment by noahkawasaki-airbyte** [comment]
/publish connector=connectors/destination-postgres-strict-encrypt auto-bump-version=false

**Pull request merged**
