### PR TITLE
Source Github: workflows and workflow_jobs: updated expected records

### PR DESCRIPTION
**Pull request by darynaishchenko**
workflows and workflow_jobs: updated expected records

### CODE REVIEW

**Review by bazarnov — CHANGES_REQUESTED** [review]
Based on this test results: https://github.com/airbytehq/airbyte/actions/runs/4193134586/jobs/7269644677#step:15:61

We should not have the `http` links used for connectors, please check and fix this.

**Review by lazebnyi — APPROVED** [review]

**Comment by darynaishchenko** [comment]
> Based on this test results: https://github.com/airbytehq/airbyte/actions/runs/4193134586/jobs/7269644677#step:15:61
> 
> We should not have the `http` links used for connectors, please check and fix this.

removed `http` links

**Review by bazarnov — APPROVED** [review]

**Pull request closed without merging**
