### PR TITLE
source-lightspeed-retail contribution from aazam-gh

### LINKED ISSUE #46010: [connector-request] Lightspeed Retail
This is a **suggestion** to create a connector for **Lightspeed Retail** using the UI Connector Builder.
The website for the connector is https://www.lightspeedhq.com/pos/retail.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

### PR DESCRIPTION
**Pull request by aazam-gh**
## What

This PR adds a new connector for source Lightspeed Retail (source-lightspeed-retail).

Contributor-provided connector description:

Lightspeed Retail is a one-stop commerce platform empowering merchants around the world to simplify, scale and provide exceptional customer experiences. This source connector ingests data from the lightspeed retail API https://www.lightspeedhq.com/

In order to use this source, you must first create an account.
Note down the store url name as this will be needed for your subdomain name in the source. 
After logging in, you can create your personal token by navigating to Setup -&gt; Personal Token. You can learn more about the API here https://x-series-api.lightspeedhq.com/reference/listcustomers

 
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key. API key or access token |  |
| `subdomain` | `string` | Subdomain. The subdomain for the retailer, e.g., &#39;example&#39; in &#39;example.retail.lightspeed.app&#39;. |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| users | id | DefaultPaginator | ✅ |  ❌  |
| customers | id | DefaultPaginator | ✅ |  ❌  |
| audit | id | DefaultPaginator | ✅ |  ❌  |
| brands | id | DefaultPaginator | ✅ |  ❌  |
| attributes | id | DefaultPaginator | ✅ |  ❌  |
| tax | id | DefaultPaginator | ✅ |  ❌  |
| tags | id | DefaultPaginator | ✅ |  ❌  |
| suppliers | id | DefaultPaginator | ✅ |  ❌  |
| serial_numbers | id | DefaultPaginator | ✅ |  ❌  |
| sales | id | DefaultPaginator | ✅ |  ❌  |
| registers | id | DefaultPaginator | ✅ |  ❌  |
| quotes | id | DefaultPaginator | ✅ |  ❌  |
| services | id | DefaultPaginator | ✅ |  ❌  |
| promotions | id | DefaultPaginator | ✅ |  ❌  |
| products | id | DefaultPaginator | ✅ |  ❌  |
| product_categories | id | DefaultPaginator | ✅ |  ❌  |
| price_books | id | DefaultPaginator | ✅ |  ❌  |
| payment_types | id | DefaultPaginator | ✅ |  ❌  |
| outlets | id | DefaultPaginator | ✅ |  ❌  |
| outlet_taxes | outlet_id.product_id.tax_id | DefaultPaginator | ✅ |  ❌  |
| inventory | id | DefaultPaginator | ✅ |  ❌  |
| fulfillments | id | DefaultPaginator | ✅ |  ❌  |
| customer_groups | id | DefaultPaginator | ✅ |  ❌  |
| consignments | id | DefaultPaginator | ✅ |  ❌  |
| consignment_products | product_id | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hello 👋 Due to the numerous contributions happening, I decided to create this [view](https://github.com/orgs/airbytehq/projects/104/views/3) to help you know when I plan to review your contribution. If your connector has some limited-time credential feel free to reach me out.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
It looks credentials got expired. @aazam-gh can you provide new credentials to run tests? Asking because it looks current implementation is not correct.

One example is the customer endpoint doing Incremental Paginatoin and docs say it uses offset.
image


I'm moving the review to November. If you get credentials please reach me out in Slack to speed up the process.

**Comment by marcosmarxm** [comment]
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

Make sure you have pagination properly working, the API doesn't have pagination please left a comment making my review easier.
Make sure have a square svg icon
Make sure credentials are valid.

**Comment by aazam-gh** [comment]
Noted. Will try to get credentials again and update the changes 👍🏾

**Comment by aazam-gh** [comment]
Changes have been addressed.

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
