### PR TITLE
ref(source-facebook-marketing): raise exception on missing stream

### PR DESCRIPTION
**Pull request by artem1205**
## What

Following https://github.com/airbytehq/airbyte/pull/46310
Resolving https://github.com/airbytehq/airbyte-internal-issues/issues/10082

## How
set `raise_exception_on_missing_stream` to `True`

state format is changed `set` -> `list` because set cannot be serialized by default (was handled by Pydantic in previous version)

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by artem1205** [comment]
Hey @brianjlai , 
could take a quick look at this PR, I got failed unit tests here (`test_given_multiple_account_ids_when_read_then_state_produced_by_account_id_and_state_match_start_interval`) possibly due to RFR, latest working CDK version is 3.7.0 (failed on 3.8.0 +).

Am I missing something?

**Comment by brianjlai** [comment]
@artem1205 

Good questions and thanks for pinging me on this. I dug into this a bit my morning and it's an edge case my auto-RFR for Python accounted for. Basically the problem I see is that the `AdInsightsActionProductID` stream is implemented in a way where it has implementations for both the legacy `get_updated_state()` method and the modern `state()` setter and getter methods. 

Looking at this block of code within `core.py` [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/streams/core.py#L588-L593) where we decide whether to use legacy or modern state setters and getters. Because the way this stream is structured:

- It inherits the `AdsInsights` parent class which provides concrete implementations for `state` setter and getters
- The `AdsInsights` class inherits from the `FBMarketingIncrementalStream` which itself implements a `get_updated_state()` method


And this causes us to default to the legacy method and therefore not invoking `self.state = blah blah` that contains all the necessarily logic to update state accordingly. So that explains why upon the bump to `3.8.0`, we don't see state get updated and we end up failing the test with the missing date.

I did some basic testing and by changing the condition in the code snippet above to always use the state setter, the test seemed to pass. 

@artem1205 I think the path forward here is to look into deprecating this legacy state method from the Facebook connector. We did not intend to have streams that were designed to implement both forms and that is causing the bug. 

The auto-RFR work required some very specific checks to get working so it doesn't surprise me that these types of cases come up, but we also should prioritize getting rid of legacy flows rather than adding more hacks to the CDK.

Let me know if this all makes sense or want to talk more

**Comment by artem1205** [comment]
@brianjlai, thanks for clarifying! Sounds like it's time for state migration 😢

**Comment by lazebnyi** [comment]
Overall, it looks good to me.

Btw, do you think we need to add a note to the migration file that some syncs are expected to fail after the release?

**Review by lazebnyi — APPROVED** [review]

**Comment by artem1205** [comment]
> Btw, do you think we need to add a note to the migration file that some syncs are expected to fail after the release?

Sync will not fail completely, customer should see yellow sign with warning message and `partially succeeded` status

**Pull request merged**
