### PR TITLE
airbyte-ci: disable update check in the pre-push hook for formatting

### PR DESCRIPTION
**Pull request by alafanechere**
## What
We don't want to force folks to auto-update airbyte CI if they're using the pre-push hook.

## How
Pass the `--disable-update-check` to the pre-push hook.

### CODE REVIEW

**Comment by alafanechere** [comment]
Current dependencies on/for this PR:
* `master`
  * **PR #33410** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33410?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/airbytehq/airbyte/33410?utm_source=stack-comment).

**Review by bnchrch — COMMENTED** [review]
Just want to gut check:

Are we sure we want this behaviour?

If we disable the check entirely they will never know they are behind.

If they are behind there is a change CI format check fails but Local Format Hook passes

and if they dont know they are behind and are a dev that doesn't use `airbyte-ci` daily then how do they know to update?

Alternatively we could pursue an always update?

**Comment by alafanechere** [comment]
@bnchrch on the other hand updating silently will conflict with developers' will to pin `airbyte-ci` to a specific version. (Staying behind because we've a known bug in the latest version).
I don't know what the ideal approach is. Maybe prompting users for the update mode they want on airbyte-ci install once for all?

**Comment by bnchrch** [comment]
Lets give these two names
* Error Case UN: A users airbyte-ci version is unintentially behind
* Error Case INT: A users airbyte-ci is intentionally behind

Now here are some feelings/thoughts I'm working from
1. Error Case UN would be more common that Error Case INT
2. Error Case INT being related to "latest is broken" our team is aware, and in control of communication and how to roll out fixes/workaround. That cant be said about UN where our team will be unaware.
3. Hooks are optin and less likely to be installed

Perhaps we should
1. Auto update by default
1. Add an ENV var that when set overrides the airbyte-ci version from latest during install

Then during an outage we are left with these options
1. Have them set the env var
2. Or rollback the troublesome commit
3. Or have them uninstall the hooks

**Comment by alafanechere** [comment]
Thanks for the detailed walk of thought.

> Perhaps we should
Auto update by default
Add an ENV var that when set overrides the airbyte-ci version from latest during install

This sound good to me. Can it be an env var to pin airbyte-ci to a specific version?

In any case, do you agree that this should be managed by airbyte-ci itself and not at the `pre-push` hook level, so I can close this PR?

**Pull request closed without merging**
