### PR TITLE
13539 Fix integration tests source-clickhouse Mac OS

### LINKED ISSUE #13539: Fix integration tests source-clickhouse Mac OS
After updating testcontainers lib to 1.17.1 version integration tests failed for Mac OS with next error:

```
2022-06-03 12:31:54 source > 2022-06-03 12:31:54 ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.
2022-06-03 12:31:54 source > java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30001ms.
```

### PR DESCRIPTION
**Pull request by suhomud**
## What
1. The connection refused issue for mac os
2. Clickhouse docker image incompatibility with Mac M1

## How
1. Resolved host/port for mac os. 
2. The yandex/clickhouse-server image does not support arm architecture. Did update to clickhouse/clickhouse-server:22.5
3. Testcontainer version 1.16.2 does not support clickhouse/clickhouse-server. Did update to 1.17.3
4. Updated clickhouse-jdbc to the latest 0.3.2-patch10 version

### CODE REVIEW

**Review by edgao — APPROVED** [review]
lgtm - does destination-clickhouse have the same issues?

**Comment by grishick** [comment]
> lgtm - does destination-clickhouse have the same issues?

destination-clickhouse is already fixed. I verified that I can run`./gradlew :airbyte-integrations:connectors:destination-clickhouse:integrationTestJava` on my M1 Mac yesterday

**Review by grishick — APPROVED** [review]

**Comment by suhomud** [comment]
@grishick @edgao , this PR resolving most of the tests issues for Mac intel/m1 but the `SslClickHouseJdbcSourceAcceptanceTest.java` is still failing. It looks like new image for click house required another ssl configuration. Currently working on the solution

**Review by alexandr-shegeda — APPROVED** [review]
great job

**Comment by suhomud** [comment]
@mzitnik Did an update to the latest clickhouse-jdbc

**Review by grishick — APPROVED** [review]
Great job!

**Comment by suhomud** [comment]
/publish connector=connectors/source-clickhouse-strict-encrypt auto-bump-version=false

**Comment by suhomud** [comment]
/publish connector=connectors/destination-clickhouse-strict-encrypt auto-bump-version=false

**Comment by suhomud** [comment]
/publish connector=connectors/source-clickhouse-strict-encrypt auto-bump-version=false

**Pull request merged**
