### PR TITLE
🎉 New Destination: Timeplus

### LINKED ISSUE #20195: Timeplus destination connector: send data to Timeplus for real-time analysis/visualization/alerting
## Tell us about the new connector you’d like to have
Timeplus Overview
It'll be great to have a **destination connector** for Timeplus, so that as a developer they can collect data from database/file/social and send them to Timeplus with Airbyte. http://timeplus.com/ is an end-to-end streaming analytics platform, offering both fully-managed cloud service as well as on-prem deployment. Users can load real-time data from Kafka/Pulsar/Ably/etc and explore them visually, run streaming SQL to gain real-time insights, and visualize them with real-time charts and take actions with real-time alerts.

* **Which source and which destination?** Destination
* **Do you need a specific version?** The connector just needs to work with the latest Timeplus version (in public beta, biweekly release)

## Describe the context around this new connector
* **Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.**
Airbyte is a great platform to move data from A to B. In Timeplus, only a limited number of streaming data sources are supported. When the user needs to run a query to enrich real-time data with data in database or file, they need to push the data to us with the ingest REST API. With the new timeplus destination connector, our users can access hundreds of sources on airbyte ecosystem and push those data to Timeplus for analysis/visualization/alert
* **How often do you want to run syncs?**
Ideally as soon as possible, even sub-second. But the current 5-minute minimal sync interval is fine. We are looking forwards to the new streaming support from AirByte, so that more amazing use cases can be done, such as once a new contacts in HubSpot, in the next minute, the data will update the chart/alert in Timeplus 
* **If the connector is for a paid service, can we name you as a mutual user when we subscribe for an account? Which company should we name?** 
Timeplus Cloud now is in public beta, free to sign up and use. Feel free to sign up one on https://beta.timeplus.cloud with Google/Microsoft social account or use an email to create password. At `Timeplus`, we will be more than happy to partner with AirByte

## Describe the alternative you are considering or using
**What are you considering doing if you don’t have this integration through Airbyte?**
Data could be collected by Airbyte then sent to Kafka or Pulsar, but this will require extra configuration effort, infra cost. I also found the current AirByte doesn't work well with Confluent Cloud or StreamNative Cloud.

## Are you willing to submit a PR?
Yes, this is the plan. I just forked the code and created a branch for that. https://github.com/timeplus-io/airbyte/blob/feature/timeplus-destination/airbyte-integrations/connectors/destination-timeplus/destination_timeplus/destination.py Hopefully to get the PR ready later this month.

### PR DESCRIPTION
**Pull request by jovezhong**
## What
A new destination connector for Timeplus (works for any cloud deployment or onprem deployment of Timeplus)

close #20195 

## How
This python based destination connector will send data to Timeplus. It will create streams in Timeplus if necessary, with the exactly same schema from the source (kind of normalization, but not based on DBT). For example, if there are 4 columns in the CSV, then there will be 4 columns in the Timeplus stream.

## Recommended reading order
airbyte-integrations/connectors/destination-timeplus/destination_timeplus/destination.py

## 🚨 User Impact 🚨
no breaking change

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

To test this connector, you can create a free account at https://beta.timeplus.cloud, sign in with Google/MS SSO, then create a workspace, create an API key,  then set them in the secret/UI to push data to it (tested with CSV and db)

## Tests

<details><summary><strong>Unit</strong></summary>

```
pytest -s unit_tests
================================================== test session starts ==================================================
platform darwin -- Python 3.9.16, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/jove/Dev/timeplus-io/airbyte/airbyte-integrations/connectors/destination-timeplus/.venv/bin/python3.9
cachedir: .pytest_cache
rootdir: /Users/jove/Dev/timeplus-io/airbyte, configfile: pytest.ini
collected 1 item

unit_tests/unit_test.py::test_type_mapping PASSED

=================================================== 1 passed in 0.71s ===================================================
```

</details>

<details><summary><strong>Integration</strong></summary>

```
================================================== test session starts ==================================================
platform darwin -- Python 3.9.16, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/jove/Dev/timeplus-io/airbyte/airbyte-integrations/connectors/destination-timeplus/.venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/jove/Dev/timeplus-io/airbyte, configfile: pytest.ini
collected 0 items

================================================= no tests ran in 0.01s =================================================
```

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by jovezhong** [comment]
@marcosmarxm , would you please share your review feedbacks? Thanks

**Comment by itaseskii** [comment]
@jovezhong Is this work in progress? I don't see any test coverage in the PR.

**Comment by jovezhong** [comment]
> @jovezhong Is this work in progress? I don't see any test coverage in the PR.

Hi @itaseskii , thanks for the comments (during holiday break :))
The PR is ready to review. There is one unit test and I checked in the sample messages and run command line to push them to remote Timeplus. Sorry that part is not automated in the integration test, since I am now sure how the airbyte CI will handle the sensitive information such as api token on Timeplus Cloud (feel free to create a free account on timeplus.cloud then create an api key)

If you can guide me how to configure CI to store/fetch the secrets and other integration test in other sinks, I will be more than happy to add the integration test in this week.

Again, this is my first PR to airbyte community. Sorry if I miss anything. Thanks for the review and happy holiday.

**Comment by marcosmarxm** [comment]
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

**Comment by jovezhong** [comment]
Sure, no problem. 

In my previous organziation, we also had similar rules that no deployment on Friday afternoon or right before the holiday. Otherwise we may just bring more risk/trouble to us, without a strong business need.

Peace~

**Comment by jovezhong** [comment]
Happy New Year, everyone!

Hi @itaseskii and @marcosmarxm, not sure whether you have bandwidth to review this PR. I made some refinements and added more tests.

**Comment by geekwhocodes** [comment]
@sajarin I can review this PR.

**Comment by itaseskii** [comment]
Hey @jovezhong have you allowed edits and access to secrets by maintainers on the PR? :)

**Comment by jovezhong** [comment]
> Hey @jovezhong have you allowed edits and access to secrets by maintainers on the PR? :) image

Hi @itaseskii , can you guide me where to enable this? You can go https://timeplus.cloud to sign up a free account and generate the API token.

**Comment by itaseskii** [comment]
> > Hey @jovezhong have you allowed edits and access to secrets by maintainers on the PR? :) image
> 
> Hi @itaseskii , can you guide me where to enable this? You can go https://timeplus.cloud to sign up a free account and generate the API token.

@jovezhong its on the right hand side on the current page.
image

**Comment by jovezhong** [comment]
Oops, there is no such option "Lock conversation" in my github page
image

**Comment by jovezhong** [comment]
Is that because no code reviewers are assigned to the PR? I am happy to share the secrets for testing

**Comment by itaseskii** [comment]
> Is that because no code reviewers are assigned to the PR? I am happy to share the secrets for testing

@jovezhong no, it has nothing to do with the PR not having a reviewer nor the secrets for testing. I think that you have the similar issue mentioned here https://github.com/airbytehq/airbyte/pull/20368#issuecomment-1377217194. Most likely you will need to open the PR from a personal repo.

**Comment by jovezhong** [comment]
I see. I will do the same 

> "I guess the problem is the "personal account", because .. is an org. I will fork the repo into my personal account and create another PR."

It should be ready within half an hour

**Comment by jovezhong** [comment]
Can I close this comment? A new PR is ready from my own account https://github.com/airbytehq/airbyte/pull/21226 Pls review

**Comment by jovezhong** [comment]
I am about to close this PR in 48 hours if no one objects. Please review the PR sent from my personal account https://github.com/airbytehq/airbyte/pull/21226

**Comment by jovezhong** [comment]
Close this PR. Pls review PR #21226

**Pull request closed without merging**
