### PR TITLE
✨URL encode username and password fields

### LINKED ISSUE #10569: Source MongoDB: connector fail with password which contains special character
Dears
I found one bug when creating MongoDB connector with password which contains special character such as %
## Environment
- **Airbyte version**:  0.35.3-alpha
- **OS Version / Instance**: Centos7
- **Deployment**:  Docker
- **Source Connector and version**: source-mongodb-v2  0.1.10
- **Severity**:  Low
- **Step where error happened**: Create connector

## Current Behavior
It appears error when creating MongoDB source connector with password which contains special character such as % + / ?

## Expected Behavior
Password can contain special characters, for example % + / ?

## Steps to Reproduce
1. Create MongoDB connector
2. Input all necessary information  
3. Input password which consist of special character

## Are you willing to submit a PR?
Currently, do not have this plan.

### PR DESCRIPTION
**Pull request by rodireich**
## What
Adopting code change from https://github.com/airbytehq/airbyte/pull/31371.
Fixes https://github.com/airbytehq/airbyte/issues/10569

This code change also integrates with the latest CDK, adding debezium 2.4 and fixes https://github.com/airbytehq/oncall/issues/3203
## How
URL encode the user and password fields as described in mongodb documentation
h/t to @aglucky for the original change

### CODE REVIEW

**Review by stephane-airbyte — APPROVED** [review]

**Comment by postamar** [comment]
That's odd, I did validate those changes against that connector. Evidently not well enough. I'll look into it.

**Comment by rodireich** [comment]
🤔
Does running ci test on master working for you?

**Comment by aglucky** [comment]
Hi, I saw the URI encoding for the MongoDB connector was removed. I’m not sure if things have changed since the original issue was created but the lack of encoding for passwords was what caused the issue to be made.

**Comment by octavia-approvington** [comment]
Lets merge it <br/> sheep thumbs up

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
