### PR TITLE
🐛[source-confluence] 'expand' request parameter converted to comma separated string

### PR DESCRIPTION
**Pull request by cjkindel**
Atlassian APIs like Confluence support an `expand` request parameter that expands the response to include the requested fields. The documentation for this parameter states that it must be a comma separated string. The Page and Blogpost `expand` parameters were not strings. I updated all 3 `expand` parameters (including the functional but out-of-spec Space's) to meet the specification of comma separated string.

Atlassian Documentation: https://developer.atlassian.com/server/confluence/expansions-in-the-rest-api/

Related Issue: https://github.com/airbytehq/airbyte/issues/33347

### CODE REVIEW

**Comment by marcosmarxm** [comment]
I'm going to run integration tests and validate the change @cjkindel thanks for the contribution.

**Review by talweissler — APPROVED** [review]

**Comment by cjkindel** [comment]
It appears I need someone w/ permissions to rebase/run tests/merge or else I will be stuck in a rebase loop

**Comment by marcosmarxm** [comment]
@cjkindel I need to create a duplicated non-forked branch to run tests properly to your contribution. I'm going to this week, sorry the delay!

**Review by marcosmarxm — APPROVED** [review]
Waiting CI to merge the contribution @cjkindel thanks for this!

**Comment by marcosmarxm** [comment]
Hello @cjkindel your feedback matters a lot to us. Can you spare just 3 minutes to complete a [survey](https://form.typeform.com/to/DOBqejte)? We're dedicated to making the contributor experience even better, and your input is key to achieving excellence. Thank you for helping us improve!

**Pull request merged**
