### PR TITLE
🎉 Postgres source: make initial cdc waiting time configurable

### LINKED ISSUE #12776: Make CDC debezium first record wait time configurable
## Environment
- **Airbyte version**:  0.36.7-alpha
- **OS Version / Instance**: GCP n2.
- **Deployment**: GCP Compute Engine
- **Source Connector and version**: Postgres 
- **Destination Connector and version**: BigQuery 
- **Severity**: Medium
- **Step where error happened**:Sync job

## Current Behavior
*Tell us what happens.*
With logical replication, even when no new records are found the sync job takes greater than 5mins to complete. This seems to be the wait time set by [FIRST_RECORD_WAIT_TIME_MINUTES](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/debezium/src/main/java/io/airbyte/integrations/debezium/internals/DebeziumRecordIterator.java#L37)
As a result, the sync job which should take less time when no new records are found, takes longer than when records are actually found.

## Expected Behavior
*Tell us what should happen.*
Sync job should take less time when no new records are found

## Logs
NA

</details>

## Steps to Reproduce
1. Configure replication with CDC 
2. Observe that Sync job takes greater than 5 mins when no new records are found 

## Are you willing to submit a PR?

Sure, but just need confirmation whether changing the wait time to something like ~1 min, doesn't have any other implications.

### PR DESCRIPTION
**Pull request by tuliren**
## What
- This is one of the PRs to accelerate Postgres CDC initial waiting time.
- This one simply makes the initial waiting time configurable.
- It does not change the default 5 minutes.
- It updates tests to use a much shorter time (10 seconds).
- Resolve https://github.com/airbytehq/airbyte/issues/12776.

### CODE REVIEW

**Comment by alexandr-shegeda** [comment]
@tuliren Since Postgres Source connector is already in beta in addition to integration testing, I need you to perform the following manual test:

1. Create a connection with the previous version of source-postgres-strict-encrypt connector and run a full refresh (destination does not matter as long as the connection is configured for 'incremental dedupe' mode)
2. Add some data to the source DB and run an incremental sync
3. Upgrade source-postgres-strict-encrypt to a version with these changes. Don't change any configuration.
4. Run an incremental sync
5. Add some data to the source DB
6. Downgrade the connector to the previous version
7. Run an incremental sync
8. Upgrade source-postgres-strict-encrypt to a version with these changes.
9. Change initial_waiting_seconds to require
10. Add some data to the source DB
11. Run an incremental sync
12. Downgrade the connector to the previous version
13. Add some data to the source DB
14. Run an incremental sync

The expectation for the test is that all syncs succeed

**Comment by tuliren** [comment]
@alexandr-shegeda, thanks for the instructions. However, I have some questions about these steps:

> 9. Change initial_waiting_seconds to require

This step seems unnecessary. This field will not be required. Actually in my opinion, all new fields should always be optional.

> 6. Downgrade the connector to the previous version
> 12. Downgrade the connector to the previous version

Currently the spec has `additionalProperties: false`. So downgrading from a version with a new field will always result in schema validation failure. How about I do the following:
1. Publish a new version with `additionalProperties: true` (V1).
2. Publish a new version for changes in this PR (V2).

In this way, if there is anything wrong with this PR, users can still downgrade to a V1 without breaking their connection.

**Review by subodh1810 — CHANGES_REQUESTED** [review]
I think we should build a safety check that the max wait time can be 5 minutes so that if a user mistakenly sets it to more than 5 minutes, we default to 5. 
5 minutes has worked in 100% of cases so as of now we dont need it to be more than 5 minutes.

**Comment by grishick** [comment]
> I think we should build a safety check that the max wait time can be 5 minutes so that if a user mistakenly sets it to more than 5 minutes, we default to 5. 5 minutes has worked in 100% of cases so as of now we dont need it to be more than 5 minutes.

Given that we haven't done sufficient testing of this timeout value "in the wild" I would actually argue on the side of allowing users to set it to whatever they want. If we see people shooting themselves in the foot with values that are too large - we'll introduce a safety check based on what those "too large" values end up being.

**Comment by subodh1810** [comment]
@grishick Am open to increasing the max allowed value to be more than 5 minutes but we should definitely have an upper cap even if its 30 minutes.

**Review by grishick — APPROVED** [review]

**Comment by grishick** [comment]
this PR needs a rebase

**Comment by tuliren** [comment]
Will merge after https://github.com/airbytehq/airbyte/pull/14574 is published and merged for safety. In that way, if there is anything wrong, users can downgrade without breaking their existing connections.

**Comment by lmossman** [comment]
@tuliren any update on this change? Once this is out we should be able to speed up the platform build a bit which would be nice

**Comment by tuliren** [comment]
Oh, the dependent PR has been merged. I will work on merging this PR now.

**Pull request merged**
