### PR TITLE
source-outreach: fix record parsing and cursor field access

### LINKED ISSUE #14385: 🐛 source-outreach: cursor field is not properly defined
The `cursor_field` for `IncrementalOutreachStream` is defined as `attributes/properties/updatedAt`.
This field does not exist in the schema and should be `updatedAt` instead.

An example of an error can be found [here](https://discuss.airbyte.io/t/normalization-process-wasnt-successful-for-the-outreach-source-and-snowflake-destinatoin/1700)

### PR DESCRIPTION
**Pull request by alafanechere**
## What
I think the schemas and the record parsing in this connectors were defined wrongly: 
* The source API returns records in the following structures: 
```
{
  "data": [{
    "type": "prospect",
    "id": 1,
    "attributes": {
      "firstName": "Sally",
      "lastName": null,
      ...
    },
    "relationships": {
      "account": {
        "data": {
          "type": "account",
          "id": 1
        }
      },
      "mailings": {
        "links": {
          "related": "https://api.outreach.io/api/v2/mailings?filter[prospect][id]=1"
        }
      },
      ...
    }
  },
  ...]
}
```

The connector defined the right schema for the streams but did not unnest the `attributes` field in the `parse_response` function. The connector was working because of the abuse of `additional_properties = True` set in the stream schemas.
Moreover the `cursor_field` path was not declared in a valid manner.

### CODE REVIEW

**Comment by alafanechere** [comment]
@lgomezm feel free to review as these are some structural changes from your original new connector contribution, let me know if I missed a specific context.

**Comment by alafanechere** [comment]
Assiging review to @harshithmullapudi too because you reviewed https://github.com/airbytehq/airbyte/pull/7507

**Review by harshithmullapudi — APPROVED** [review]
🔥

**Comment by alafanechere** [comment]
/publish connector=connectors/source-outreach run-tests=false

**Comment by alafanechere** [comment]
/publish connector=connectors/source-outreach run-tests=false

**Pull request merged**
