### PR TITLE
:tada: Source facebook marketing/add action report time enum to adinsights class

### PR DESCRIPTION
**Pull request by pnavarromuttdata**
## What
In the `AdInsights` [class](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/base_insight_streams.py) is not available the `action_report_time` enumeration as the [Facebook Marketing docs](https://developers.facebook.com/docs/marketing-api/reference/adgroup/insights/#:~:text=value%20is%20%5B%22action_type%22%5D.-,action_report_time,-enum%7Bimpression%2C%20conversion) suggest. 

[Issue](https://github.com/airbytehq/airbyte/issues/20197)

## How
Add new `action_report_time` attribute to `AdInsights` class, so when someone creates a new source connector, it could specify the custom `action_report_time` needed (`mixed`, `conversion` or `impression`) having as a default value `mixed`.
image

## Recommended reading order
1. airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/base_insight_streams.py
2. airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/source.py
3. airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/spec.py
4. airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/integration_tests/spec.json
5. airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/unit_tests/test_async_job.py
6. airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/unit_tests/test_source.py
7. airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/unit_tests/test_streams.py

## 🚨 User Impact 🚨
By default, it will have the same behaviour as is (`action_report_time` current default value is `mixed` according to this [FB docs](https://developers.facebook.com/docs/graph-api/changelog/non-versioned-changes/dec-16-2020/#:~:text=New%20mixed%20option%20for%20action_report_time)).

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

**Comment by pnavarromuttdata** [comment]
> Hello wave:skin-tone-2: and thank you for your contribution!
> 
> Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. Because of this, reviewing and merging your contribution may take longer than usual. We apologize for the delay, but we want everyone to have a quiet and happy holiday.
> 
> If you have any questions or need further clarification, please don't hesitate to ping via Slack.

Hello @marcosmarxm ! I hope all is well! I'm interesting in continue with this issue, are the airbyte team reviewers available?

**Comment by gvillafanetapia** [comment]
Hi! also interested in this feature 🙌 

anyway to push it forward?

**Comment by pnavarromuttdata** [comment]
Hello @marcosmarxm @sh4sh! can you review this issue/PR to complete the contribution please?

**Comment by marcosmarxm** [comment]
Closing because user didn't sign the CLA

**Comment by pnavarromuttdata** [comment]
@marcosmarxm Good morning! sorry we didn't realize about it, now, we already have signed the CLA, is still possible to reopen this PR?

**Comment by marcosmarxm** [comment]
@pnavarromuttdata can you open a sign PR and make sure the code is even with latest version?

**Comment by pnavarromuttdata** [comment]
@marcosmarxm Okay, I'll open another sign PR :ok_hand:

**Comment by pnavarromuttdata** [comment]
@marcosmarxm FYI this is the new [PR](https://github.com/airbytehq/airbyte/pull/26345)

**Pull request closed without merging**
