### PR TITLE
🐛Destination Postgres - Fix Conflicting relations and truncation causing streams to write raw streams to same table

### PR DESCRIPTION
**Pull request by williamkaper**
## What
* This PR proposes a fix for [Issue 455345](https://github.com/airbytehq/airbyte/issues/45345). Since version 2.2.1 of the postgres destination connector, V2 functionality has turned the raw table vs just hard replacing it by first creating a table named `{namespace}_raw__stream_{streamname}_airbyte_tmp`, and then dropping {`namespace}_raw__stream_{streamname}`. The issue stems from the fact that PostgreSQL entity naming is limited to 64 characters, so any streams with long namespaces or long stream names (or both), when combined with all the placeholder indicators described above, wind up exceeding 64 characters. The truncation logic in the the Postgres connector did nothing but truncate the combined` {namespace}_raw__stream_{streamname}` off at 64 characters. 

* **_Description of Problem:_** There are a few problems with this approach. First, even if the CDK tries to do something to add few characters to make it unique, making the string 64 characters leaves zero (0) characters to append anything, let alone the `airbtye_tmp` temp table suffix. Second, when any other objects were trying to be created, they too would have no additional characters to derive uniqueness, causing things like indexes to fail blocking the turning of the data. Lastly, in certain instances, such as the gsheet source connector, I was able to get Airbyte to write two different streams data to the same airbyte_internal.__raw__stream raw table. When the data would then get copied from raw to the landed stream team, each stream would get its own data and a mess of from the other table that it would try to apply to its own ERD. 

* **_How to Reproduce_** Take a source like google sheets or another connector with similar stream names and a long namespace (or give it a long custom namespace). Make sure the combined length of both is something over 50 characters with the most recent version of the destination-postgres connector. 

## How
*  I am not skilled enough to make or proposed changes to the CDK, so I took the truncate helper method in PostgresSQLNameTransformer, and changed it instead. Now instead of hard truncating anything over 64 characters, I take anything over 60 characters and truncate it to 52, and apply a base36 hash of the untruncated string and take that 6 character hash and append it to the 52 characters, leaving 5 for any suffix to be added. This table naming scheme is both deterministic and guarantees uniqueness over the amount of tables any database in airbyte would expect to handle (and certainly more unique than the current logic). While that doesn't leave enough for _airbyte_tmp to be fully appended, it is enough that what does get appended separates the temp table from the raw table. I'd personally make that suffix `_tmp` instead of `_airbyte_tmp` and I would also shrink the middle stuff from `_raw__stream_` to just `_raw__` (but that can be a different discussion for a different time :-D) 

* _**I wasn't able to get my unit tests fully working.**_ I suspect the failures are related to test case tables that are more than 60 characters in length that, when truncated, don't match the original string. I tried putting what I think would be the correct overriden property in `AbstractPostgresTypingDedupingTest`, but I'm clearly still missing something. On manual testing, all the scenarios where I saw data getting co-mingled and objects failing to get created all went away. 

I'm offering this up as a potential solution, but understand if its not the solution that the team feels is best or gets to the root of this problem, but if it is, all I'll need help with is the test cases to make sure there isn't an edge of the problem I'm not solving, or solving one problem and making another. 

## Review guide
1. `PostgresSQLNameTransformer.kit` - modified the truncate method to truncate and add uniqueness
2. `AbstractPostgresTypingDedupingTest.java` - Added override for NameTransformer property declared in ancestor JdbcTypingDedupingTest

## User Impact
* What is the end result perceived by the user? Streams with long names and/or long namespaces work as expected without any issues with db object collisions or data getting written/read from unintended co-mingled locations. 
* If there are negative side effects, please list them. None I can think of, but I am not skilled enough in Kotlin or Java to figure out why some of the text fixtures or failing and how to fix them. 

## Can this PR be safely reverted and rolled back?
- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Thanks for the contribution, @williamkaper. I have asked the destination team to review it during the next grooming or sprint session. Please be patient, as changes to destinations can significantly impact many users. We need to handle them with great care.

**Comment by williamkaper** [comment]
> Thanks for the contribution, @williamkaper. I have asked the destination team to review it during the next grooming or sprint session. Please be patient, as changes to destinations can significantly impact many users. We need to handle them with great care.

Fully understood. If I help on the troubleshooting of the base issue please let me know.

**Comment by williamkaper** [comment]
You can this rearing its ugly head again - we just got this when we tried adding the application_refunds stream to one of our customer's connections:

**Comment by williamkaper** [comment]
@marcosmarxm @natikgadzhi Any update on this?

**Comment by marcosmarxm** [comment]
@williamkaper I'm returning to review community contribution this week. I'll keep you posted!

**Comment by marcosmarxm** [comment]
@davinchia can this be added to the next destination sprint to someone review it?

**Comment by davinchia** [comment]
Thank you for your contribution and for bringing this up to our attention @williamkaper ! 

After some discussion, we decided we aren't going to move forward with this approach. Instead we'll implement this in the CDK so this issue is handled for all destinations, and not just one single destination. 

I expect this bug to be sustainably fixed within 1 - 3 months.

**Comment by davinchia** [comment]
I'm going to close this PR, and we'll resume discussions in the linked issue. Thanks again!

**Comment by williamkaper** [comment]
> I'm going to close this PR, and we'll resume discussions in the linked issue. Thanks again!

Understood. Thank you for the update. I'm looking forward to this being fixed for all DB destinations

**Pull request closed without merging**
