### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by suhomud**
## What
Formatting fix. 

Spotless failed to format next files: 
`airbyte-integrations/connectors/**/integration_tests/expected_records.json`,
With: 
```
Execution failed for task ':spotlessStyling'.
> Unexpected response status code at /prettier/format [HTTP 501] -- (Error while formatting: SyntaxError: Unexpected token (2:1)
    1 | {"stream": "sat_basic_dataset", "data": {"id": 1, "test_column_1": -128, "test_column_10": -128, "test_column_11": -128, "test_column_12": -128.0, "test_column_13": true, "test_column_15": "2021-10-20T00:00:00Z", "test_column_16": "2021-10-20T11:22:33Z", "test_column_17": "2021-10-20T11:22:33Z", "test_column_19": "qwe", "test_column_2": -128, "test_column_21": "15:30:00", "test_column_3": -128, "test_column_4": -128, "test_column_5": -128, "test_column_6": -128, "test_column_7": -128, "test_column_8": -128, "test_column_9": -128 }, "emitted_at": 1669643054045 }
  > 2 | {"stream": "sat_basic_dataset", "data": {"id": 2, "test_column_1": 127, "test_column_10": 127, "test_column_11": 127, "test_column_12": 127.0, "test_column_13": false, "test_column_15": "9999-12-31T00:00:00Z", "test_column_16": "9999-12-31T11:22:33Z", "test_column_17": "2021-10-20T11:22:33Z", "test_column_19": "\u0439\u0446\u0443", "test_column_2": 127, "test_column_21": "15:30:00", "test_column_3": 127, "test_column_4": 127, "test_column_5": 127, "test_column_6": 127, "test_column_7": 127, "test_column_8": 127, "test_column_9": 127 }, "emitted_at": 1669643054045 }
      | ^
```

## How
As a workaround it was excluded from Spotless check : 
```
            '**/integration_tests/expected_records.json',
```
Ticket for revisiting the issue is created https://github.com/airbytehq/airbyte/issues/20569

## 🚨 User Impact 🚨
No impact

### CODE REVIEW

**Review by edgao — APPROVED** [review]
I think the problem with the two sql files is that we're using snowflake-specific string escape syntax, so spotlessSql doesn't understand it. Can you try replacing the `\'` with `''` and doing a `/test connector=connectors/source-snowflake`?

feel free to :ship: if that doesn't work though

**Review by ryankfu — APPROVED** [review]
While not familiar with Snowflake string index issues, I would agree with what Ed has mentioned with converting the quotes and retrying to see if that alleviates the formatting issues

Otherwise, the rest of the changes make sense since it's mostly formatting issues

**Comment by edgao** [comment]
going to just kick this off since yevhen might be asleep and I want to get this in before the code freeze :P

**Comment by edgao** [comment]
was able to run `./gradlew spotlessStyling` locally, and tests are passing. going to just merge this in.

**Pull request merged**
