### PR TITLE
[Docs] altered the chargebee docs

### LINKED ISSUE #17687: Documentation: Edit the Chargebee source connector doc
**Note:** If you'd like to work on this issue, please read the [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation) and comment on the issue to confirm it is still up for grabs.

The current [Chargebee source connector doc](https://docs.airbyte.com/integrations/sources/chargebee/) needs to be edited for consistency per our [Writing Guidelines](https://hackmd.io/Bz75cgATSbm7DjrAqgl4rw#Writing-guidelines)

Good examples to follow:
https://docs.airbyte.com/integrations/sources/amplitude
https://docs.airbyte.com/integrations/sources/bing-ads

### PR DESCRIPTION
**Pull request by digambar-t7**
## What
Updated the Documentation for Chargebee connector.

fixes #17687

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Can you sign the CLA?

**Comment by digambar-t7** [comment]
I just signed the CLA

**Comment by digambar-t7** [comment]
I have signed the CLA successfully but it is still showing a Pending status.

**Comment by marcosmarxm** [comment]
Also did you contribute using the same email/account? Sometimes people sign the CLA with one account but locally git is configured using their work/other account.

**Comment by marcosmarxm** [comment]
Ops! clicked in the wrong button :p

**Comment by digambar-t7** [comment]
Looks like my email id was missing.I am ok with it now.
What should I do now to resolve the license issue?

**Comment by marcosmarxm** [comment]
@digambar-t7 can you close this and reopen a new PR?

**Comment by digambar-t7** [comment]
Sure I'll do that

**Pull request closed without merging**
