### PR TITLE
Simplify PostHog source connector

### PR DESCRIPTION
**Pull request by mariusandra**
## What

Hi from PostHog. We had a user report they can't use your connector to get data out of PostHog.

## How

Turns out you were hitting some old API endpoints. I removed them from the source. 

Can someone help get this PR over the line?

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

### CODE REVIEW

**Review by nthbooth-feedr — APPROVED** [review]

**Comment by alafanechere** [comment]
Thank you @mariusandra for looking into it! Our team will review it as soon as possible. End-of-the-year vacations could delay the review a bit. I just went through it quickly, are the old API endpoints replaced by new ones that could allow our connectors user to get the same data? Or PostHog completely discarded these data?

**Comment by mariusandra** [comment]
Hey @alafanechere, the ones I removed were:

- `EventsSessions` - was a complicated view over `Events` which is now completely removed. Your integration didn't really fetch deep here anyway.

- `Insights`, `InsightsPath`, `InsightsSessions`, `Trends` -- these all belong under an API called "insights", which is basically a wrapper around SQL that lets you run queries like "show all events by unique user by day for the last 30 days", "show me a funnel x, y, z", etc. I'm really not sure what the current implementation was pulling... just the default queries for the four different insight types I guess? In any case, that's probably not really what you want to download. 

- `Sessions` / sessions.json -- This wasn't used anywhere, and we don't have this endpoint either.

**Comment by marcosmarxm** [comment]
Thanks for the contribution @mariusandra. I opened the issue https://github.com/airbytehq/airbyte/issues/9088 to correct our CI tests and after we're good to review your changes.

**Comment by avida** [comment]
@marcosmarxm This PR removes EventsSession  stream that was using already removed events/session endpoint which was the reason why CI failed. Ive created fork of this PR #9099, updated SAT and run tests, it work fine. @mariusandra could you plese cherry pick 978b4c8077e90170e516b521cce555fe404159ce commit (or grant me write access to mariusandra/airbyte repo) so we could have test passed.

**Comment by mariusandra** [comment]
@avida access invite sent, thanks!

**Review by avida — APPROVED** [review]

**Comment by avida** [comment]
Published image in fork [PR](https://github.com/airbytehq/airbyte/pull/9099#issuecomment-1000765996)  @mariusandra Thanks for contribution!

**Pull request merged**
