### PR TITLE
Source Github: rewrite source connection error messages

### LINKED ISSUE #26625: Improve GitHub source connection errors
Improve the errors of the Github source. These errors are seen in the connection logs. 

Type of error: Credentials expired
> 'Bad credentials, re-authentication or access token renewal is required'

Suggestion: The credentials for GitHub have expired or changed.  Review the configuration for GitHub.

Type of error: Invalid entry of Repositories
> 'Invalid repositories. Valid examples: airbytehq/airbyte airbytehq/another-repo airbytehq/* airbytehq/airbyte'
> "Exception('You provided invalid format of repositories config: /leethub. Valid examples: airbytehq/airbyte airbytehq/another-repo airbytehq/* airbytehq/airbyte')"
> "Config validation error: 'xxx' does not match '^([\\\\w.-]+/(\\\\*|[\\\\w.-]+(?<!\\\\.git))\\\\s+)*[\\\\w.-]+/(\\\\*|[\\\\w.-]+(?<!\\\\.git))$'"

Suggestion: The GitHub Repositories {GitHub Repositories} is invalid. Verify it follows the following format: airbytehq/airbyte airbytehq/another-repo airbytehq/* 

Type of error:
> HTTPError('401 Client Error: Unauthorized for url: https://api.github.com/orgs/xxx/repos"

Suggestion: The authenticated user does not have access to GitHub repository `{Github repositories}`. Try authenticating with a different user or give the user permission to the included repositories.

### PR DESCRIPTION
**Pull request by arsenlosenko**
## What
Rewrite error messages related to source connection as described in this issue:
https://github.com/airbytehq/airbyte/issues/26625

## How
Error messages already had appropriate phrasing, rewrote it based on suggestions provided in the linked issue.

### CODE REVIEW

**Review by davydov-d — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-github test report (commit [`e2ef8d3236`](https://github.com/airbytehq/airbyte/pull/30654/commits/e2ef8d32367d5d59c986606b8d4160c78316440e)) - ❌

⏲️  Total pipeline duration: 05mn51s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Connector package install                                            | ✅        |
| Build source-github docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |
| Code format checks                                                   | ❌        |
| Validate airbyte-integrations/connectors/source-github/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_26625-source-github-rewrite-source-connection-errors/1695295907/e2ef8d32367d5d59c986606b8d4160c78316440e/source-github/1.0.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e2ef8d32367d5d59c986606b8d4160c78316440e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-github test report (commit [`55a522068e`](https://github.com/airbytehq/airbyte/pull/30654/commits/55a522068e7c782fdfce5a0e6f35ece5487707e5)) - ❌

⏲️  Total pipeline duration: 05mn27s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Connector package install                                            | ✅        |
| Build source-github docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |
| Code format checks                                                   | ❌        |
| Validate airbyte-integrations/connectors/source-github/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_26625-source-github-rewrite-source-connection-errors/1695296405/55a522068e7c782fdfce5a0e6f35ece5487707e5/source-github/1.0.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:55a522068e7c782fdfce5a0e6f35ece5487707e5)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-github test report (commit [`61386608c5`](https://github.com/airbytehq/airbyte/pull/30654/commits/61386608c557ed31c6cb14b616414236a5e8ceb5)) - ❌

⏲️  Total pipeline duration: 05mn15s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Connector package install                                            | ✅        |
| Build source-github docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |
| Code format checks                                                   | ❌        |
| Validate airbyte-integrations/connectors/source-github/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_26625-source-github-rewrite-source-connection-errors/1695307472/61386608c557ed31c6cb14b616414236a5e8ceb5/source-github/1.0.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:61386608c557ed31c6cb14b616414236a5e8ceb5)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

**Review by lazebnyi — APPROVED** [review]
Good to go, leave some minor comments.

**Comment by airbyte-oss-build-runner** [comment]
##  source-github test report (commit [`e2f995a868`](https://github.com/airbytehq/airbyte/pull/30654/commits/e2f995a868c48ece0133252bce796ea34302603d)) - ✅

⏲️  Total pipeline duration: 05mn47s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Connector package install                                            | ✅        |
| Build source-github docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |
| Code format checks                                                   | ✅        |
| Validate airbyte-integrations/connectors/source-github/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_26625-source-github-rewrite-source-connection-errors/1695396583/e2f995a868c48ece0133252bce796ea34302603d/source-github/1.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e2f995a868c48ece0133252bce796ea34302603d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

**Pull request merged**
