### PR TITLE
:sparkles: Source Gilab: Deployments Streams

### LINKED ISSUE #29184: GitLab Source - Deployments Stream
### Connector Name

gitlab

### What type of integration

Source

### Revelant Information

Currently the GitLab source connector does not include [Deployments data](https://docs.gitlab.com/ee/api/deployments.html) as a [supported stream](https://docs.airbyte.com/integrations/sources/gitlab/#supported-streams), which can be helpful for tracking DORA metrics.

The connector can be extended to include a new deployments stream and fetch which build was deployed to a given environment at a certain time.

Engineers at [Urban Jungle](https://myurbanjungle.com) have produced a working implementation on a [branch I have created in a repository fork](https://github.com/benshaaw/airbyte/tree/master) - we will open a Pull Request if the "needs-triage" label is removed and this is a wanted feature for the GitLab source connector.

### Contribute

- [X] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by darynaishchenko**
This Pull Request initiates the process of executing CI checks on the source named Gitlab. The PR number associated with the contributor is https://github.com/airbytehq/airbyte/pull/29203

resolved: https://github.com/airbytehq/airbyte/issues/29184

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-gitlab test report (commit [`75a6b502aa`](https://github.com/airbytehq/airbyte/pull/31183/commits/75a6b502aa9d66a93ec88d4e9d98407c4a1fd0b3)) - ❌

⏲️  Total pipeline duration: 04mn35s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Connector package install                                     | ✅        |
| Build source-gitlab docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ✅        |
| Acceptance tests                                              | ❌        |
| Code format checks                                            | ❌        |
| Validate metadata for source-gitlab                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryba_source-gitlab_ci-checks-for-29203-pr/1696932283/75a6b502aa9d66a93ec88d4e9d98407c4a1fd0b3/source-gitlab/1.7.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:75a6b502aa9d66a93ec88d4e9d98407c4a1fd0b3)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-gitlab test report (commit [`ca63502585`](https://github.com/airbytehq/airbyte/pull/31183/commits/ca63502585d44278c24d53ea12f96c477f6b8f15)) - ❌

⏲️  Total pipeline duration: 03mn46s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Connector package install                                     | ✅        |
| Build source-gitlab docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ✅        |
| Acceptance tests                                              | ❌        |
| Code format checks                                            | ✅        |
| Validate metadata for source-gitlab                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryba_source-gitlab_ci-checks-for-29203-pr/1696933090/ca63502585d44278c24d53ea12f96c477f6b8f15/source-gitlab/1.7.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ca63502585d44278c24d53ea12f96c477f6b8f15)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-gitlab test report (commit [`8551004620`](https://github.com/airbytehq/airbyte/pull/31183/commits/85510046201f00a7ebacd372feb43a35cb50dd4a)) - ❌

⏲️  Total pipeline duration: 03mn37s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Connector package install                                     | ✅        |
| Build source-gitlab docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ✅        |
| Acceptance tests                                              | ❌        |
| Code format checks                                            | ✅        |
| Validate metadata for source-gitlab                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryba_source-gitlab_ci-checks-for-29203-pr/1696933728/85510046201f00a7ebacd372feb43a35cb50dd4a/source-gitlab/1.7.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:85510046201f00a7ebacd372feb43a35cb50dd4a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-gitlab test report (commit [`cb592036b3`](https://github.com/airbytehq/airbyte/pull/31183/commits/cb592036b39dc290549899e1a0f10c2b07954c51)) - ❌

⏲️  Total pipeline duration: 05mn38s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Connector package install                                     | ✅        |
| Build source-gitlab docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ✅        |
| Acceptance tests                                              | ❌        |
| Code format checks                                            | ✅        |
| Validate metadata for source-gitlab                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryba_source-gitlab_ci-checks-for-29203-pr/1696953094/cb592036b39dc290549899e1a0f10c2b07954c51/source-gitlab/1.7.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:cb592036b39dc290549899e1a0f10c2b07954c51)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-gitlab test report (commit [`cb592036b3`](https://github.com/airbytehq/airbyte/pull/31183/commits/cb592036b39dc290549899e1a0f10c2b07954c51)) - ✅

⏲️  Total pipeline duration: 08mn13s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Connector package install                                     | ✅        |
| Build source-gitlab docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ✅        |
| Acceptance tests                                              | ✅        |
| Code format checks                                            | ✅        |
| Validate metadata for source-gitlab                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryba_source-gitlab_ci-checks-for-29203-pr/1696954981/cb592036b39dc290549899e1a0f10c2b07954c51/source-gitlab/1.7.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:cb592036b39dc290549899e1a0f10c2b07954c51)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Review by bazarnov — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-gitlab test report (commit [`5aa2606f96`](https://github.com/airbytehq/airbyte/pull/31183/commits/5aa2606f968bd1bb19cf0cb6a3c8f94ae118633b)) - ❌

⏲️  Total pipeline duration: 09mn50s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Build source-gitlab docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ✅        |
| Acceptance tests                                              | ❌        |
| Code format checks                                            | ✅        |
| Validate metadata for source-gitlab                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryba_source-gitlab_ci-checks-for-29203-pr/1697098992/5aa2606f968bd1bb19cf0cb6a3c8f94ae118633b/source-gitlab/1.7.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:5aa2606f968bd1bb19cf0cb6a3c8f94ae118633b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-gitlab test report (commit [`5aa2606f96`](https://github.com/airbytehq/airbyte/pull/31183/commits/5aa2606f968bd1bb19cf0cb6a3c8f94ae118633b)) - ❌

⏲️  Total pipeline duration: 09mn39s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Build source-gitlab docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ✅        |
| Acceptance tests                                              | ❌        |
| Code format checks                                            | ✅        |
| Validate metadata for source-gitlab                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryba_source-gitlab_ci-checks-for-29203-pr/1697099988/5aa2606f968bd1bb19cf0cb6a3c8f94ae118633b/source-gitlab/1.7.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:5aa2606f968bd1bb19cf0cb6a3c8f94ae118633b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-gitlab test report (commit [`5aa2606f96`](https://github.com/airbytehq/airbyte/pull/31183/commits/5aa2606f968bd1bb19cf0cb6a3c8f94ae118633b)) - ✅

⏲️  Total pipeline duration: 08mn11s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Build source-gitlab docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                    | ✅        |
| Acceptance tests                                              | ✅        |
| Code format checks                                            | ✅        |
| Validate metadata for source-gitlab                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ✅        |
| QA checks                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/daryba_source-gitlab_ci-checks-for-29203-pr/1697101540/5aa2606f968bd1bb19cf0cb6a3c8f94ae118633b/source-gitlab/1.7.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:5aa2606f968bd1bb19cf0cb6a3c8f94ae118633b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gitlab test
```

**Pull request merged**
