### PR TITLE
🐛 Destination Weaviate: Multi Tenancy Support

### LINKED ISSUE #33992: Destination Weaviate: Weaviate multitenancy is not supported
### Connector Name

destination-weaviate 

### Connector Version

0.2.13

### What step the error happened?

Other

### Relevant information

Weaviate multi tenancy is not enabled or configurable. 
Weaviate has a very good approach on isolating different tenant data. Can this be configured or enabled from airbyte destination?

### Relevant log output

_No response_

### Contribute

- [X] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by Marcus0086**
## What
*Currently there is no way to enable multi-tenancy in weaviate through the configuration. Which disallows certain use cases like sharding and data isolation in db level.*

it fixes https://github.com/airbytehq/airbyte/issues/33992#issue-2069290039

## How
*The solution is relatively simple, added an optional field in config object which can take user input as `tenant_id`*
*If tenand_id is empty then the schema would be without multitenancy enabled and vice-versa*

More on this topic: https://weaviate.io/developers/weaviate/api/rest/schema#enable-multi-tenancy

## 🚨 User Impact 🚨
*No, there is no as such merge conflicts and breaking changes. Just a new field is added as optional field*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/resources/pull-requests-handbook)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

<details><summary><strong>Updating the Python CDK</strong></summary>

### Airbyter

Before merging:
- Pull Request description explains what problem it is solving
- Code change is unit tested
- Build and my-py check pass
- Smoke test the change on at least one affected connector
   - On Github: Run [this workflow](https://github.com/airbytehq/airbyte/actions/workflows/connectors_tests.yml), passing `--use-local-cdk --name=source-<connector>` as options
   - Locally: `airbyte-ci connectors --use-local-cdk --name=source-<connector> test`
- PR is reviewed and approved
      
After merging:
- [Publish the CDK](https://github.com/airbytehq/airbyte/actions/workflows/publish-cdk-command-manually.yml)
   - The CDK does not follow proper semantic versioning. Choose minor if this the change has significant user impact or is a breaking change. Choose patch otherwise.
   - Write a thoughtful changelog message so we know what was updated.
- Merge the platform PR that was auto-created for updating the Connector Builder's CDK version
   - This step is optional if the change does not affect the connector builder or declarative connectors.

</details>

### CODE REVIEW

**Review by flash1293 — COMMENTED** [review]
Hi @Marcus0086 , this looks mostly good to me, only thing missing seems to be handling the tenant id to the `delete` method. Could you add that and a test for it? Then it should be ready to merge.

I bumped the version number and added the changelog entry.

Thanks for the contribution

**Comment by flash1293** [comment]
CI PR here: https://github.com/airbytehq/airbyte/pull/34269

**Comment by Marcus0086** [comment]
Sure adding that

**Comment by Marcus0086** [comment]
@flash1293 I have added test and tenant_id to delete method, Thanks

**Comment by flash1293** [comment]
Hi @Marcus0086 , thanks for your changes. I changed some things:
* Fixed the unit tests
* Add some basic documentation

Could you check the documentation?

Also, something I'm a little unsure in terms of the feature itself - in the current logic, the configured tenant is only added to the class if it doesn't exist yet: https://github.com/airbytehq/airbyte/blob/87cd86e7973c13d7bed705b097ec8a02d2eee541/airbyte-integrations/connectors/destination-weaviate/destination_weaviate/indexer.py#L103

This means that if a class exists already for `tenant_1` and you configure another connection for `tenant_2`, it won't work because `tenant_2` won't be added to the class - instead, the user has to do this manually.

Would it make sense to check this in the pre_sync and add a missing tenant to the list? Seems like it would be more convenient to use.

**Comment by Marcus0086** [comment]
Thanks for the changes @flash1293.
I see the current logic is wrong and yes what you mentioned is true.
Current usecase is that we create a schema out of stream name and then add tenant_id to it.
But if user create another connection with tenant_2, we create same schema but the id won't be added. 
I think we should add tenant_id's instead of single id which can be added to the class.
Also I will try with pre_sync as well.

**Comment by Marcus0086** [comment]
Hey @flash1293 , can you review the changes?
I added the condition to check if tenant_id is not associated to the class for multiple connectors.
Thanks

**Comment by Marcus0086** [comment]
### Getting this error when trying to do sync on another connection with different tenant_id

`Delete in batch! Unexpected status code: 422, with response body: {'error': [{'message': 'batch delete objects: cannot find objects: tenant not found: "45678"'}]}.`

image

**Comment by flash1293** [comment]
@Marcus0086 What do you mean by "escape"? I would have expected that prior to deleting you add the currently configured tenant id to all the classes.

Basically execute https://github.com/airbytehq/airbyte/pull/34229/files?diff=unified&w=1#diff-605751b53927fd85aee9d14cf7cc427ddc74aad7c986c31bffc1b06e528a5923R105 even if the class exists already - because we always need to make sure the tenant is added to the classes

**Comment by Marcus0086** [comment]
> @Marcus0086 What do you mean by "escape"? I would have expected that prior to deleting you add the currently configured tenant id to all the classes.
> 
> Basically execute https://github.com/airbytehq/airbyte/pull/34229/files?diff=unified&w=1#diff-605751b53927fd85aee9d14cf7cc427ddc74aad7c986c31bffc1b06e528a5923R105 even if the class exists already - because we always need to make sure the tenant is added to the classes

By ‘escape’ I wanted to meant skipping the whole deletion part if tenant is not in the class tenants list. 
But we can add it before deletion too that way we are making sure tenant is associated with the class.

**Review by flash1293 — APPROVED** [review]
Adjusted the unit test but LGTM now. Merging...

**Pull request merged**
