### PR TITLE
Fix: Add airbyte-metrics to list of charts to be packaged

### PR DESCRIPTION
**Pull request by milesarmstrong**
## What
Ensure we package the new `airbyte-metrics` chart before we try to package the main chart.

A follow up to https://github.com/airbytehq/airbyte/pull/16166

Fixes the failure seen in https://github.com/airbytehq/airbyte/commit/a43c098acb687d19bb090d37bc349709924b93f2

### CODE REVIEW

**Comment by milesarmstrong** [comment]
@xpuska513 Thanks for approving / merging https://github.com/airbytehq/airbyte/pull/16166

This PR fixes the packaging of the new Helm chart that I missed in the previous PR.

**Comment by xpuska513** [comment]
I already fixed this one in my #16131

**Comment by milesarmstrong** [comment]
@xpuska513 thanks, however would you mind merging this PR first? It seems like yours will take a little while to get reviewed/merged, and Helm chart releases are failing on master until this is fixed (also it's blocking us at Duffel as we need the metrics chart in place!)

**Comment by marcosmarxm** [comment]
@xpuska513 do you think we can merge this contribution?

**Comment by xpuska513** [comment]
Sure, don't see problem at all

**Comment by xpuska513** [comment]
Just make sure you started https://github.com/airbytehq/airbyte/actions/workflows/publish-helm-charts.yml so the chart will be released

**Comment by xpuska513** [comment]
Started after merging ofc 😉

**Review by marcosmarxm — APPROVED** [review]
thanks @milesarmstrong

**Comment by milesarmstrong** [comment]
@xpuska513 @marcosmarxm could one of you run the release action please? Looks like it was [cancelled](https://github.com/airbytehq/airbyte/actions/runs/2996175112) last night 😕?

**Pull request merged**
