### PR TITLE
fix a bug where the OAuthAuthenticator was misnamed

### PR DESCRIPTION
**Pull request by brianjlai**
## What
https://github.com/airbytehq/airbyte/pull/20422#issuecomment-1358660835

Fixes a small bug where the correct component name in our existing code was `OAuthAuthenticator`, but in the handwritten schema I accidentally named it `DeclarativeOauthAuthenticator` which impacted someone developing an integration using that component.

## How
Correctly renames the component in the schema used to validate manifests:

Example of correct manifest which was tested against:
```
authenticator:
  type: "OAuthAuthenticator"
  token_refresh_endpoint: "{{ config['token_refresh_endpoint'] }}"
  client_id: "{{ config['client_id'] }}"
  client_secret: "{{ config['client_secret'] }}"
  refresh_token: ""
  refresh_request_body: 
    audience: "{{ config['graphql_endpoint'] }}"
  grant_type: "client_credentials"
```

### CODE REVIEW

**Review by girarda — APPROVED** [review]
🚢

**Review by clnoll — APPROVED** [review]
LGTM!

**Comment by octavia-approvington** [comment]
Approve this <br/> imagine the commander saying yes

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
