### PR TITLE
source-postgres : Remove FULL_REFRESH mode and include INCREMENTAL mode for all streams when configured in xmin replication mode. 

### LINKED ISSUE #27723: source-postgres : Enable incremental sync for all tables in xmin & cdc mode
Currently, we remove the option for incremental syncs for a stream in the catalog if there are no fields in the table that can be compared : https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-jdbc/src/main/java/io/airbyte/integrations/source/jdbc/AbstractJdbcSource.java#L198

This issue encompasses two changes : 
1. We need to update this to always allow the incremental option for xmin as there is no cursor. In fact - this is one of the main use cases of the xmin sync (not having a good cursor field), so this should definitely be re-added. e.g. Loom : https://www.loom.com/share/8fe33d9ceafb4f8eb575f068e6ccc1e8
2. Remove the FULL_REFRESH option from xmin syncs as they are redundant

The fix here is to override the cursor check for non-standard incremental modes.

### PR DESCRIPTION
**Pull request by akashkulk**
Closes https://github.com/airbytehq/airbyte/issues/27723

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`34ad7ee818`](https://github.com/airbytehq/airbyte/pull/27771/commits/34ad7ee81868c4b95bd62e8e13fa2d4fa968d4d9)) - ❌

⏲️  Total pipeline duration: 1544 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ❌        |
| QA checks                                                              | ✅        |
| Build connector tar                                                    | ✅        |
| Build source-postgres docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Integration tests                                                      | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_xmin-no-full-refresh/1687886467/34ad7ee81868c4b95bd62e8e13fa2d4fa968d4d9/source-postgres/2.0.34/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Review by subodh1810 — APPROVED** [review]

**Comment by rodireich** [comment]
Grooming meeting:
This is a product question on how we want to deal with full refresh streams within an incremental Xmin or CDC sync.
@Hesperide

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`e65767e88e`](https://github.com/airbytehq/airbyte/pull/27771/commits/e65767e88edde5ed5080601c6931985b6e893722)) - ❌

⏲️  Total pipeline duration: 714 seconds

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ❌        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ✅        |
| Build source-postgres docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres:integrationTest | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_xmin-no-full-refresh/1687982544/e65767e88edde5ed5080601c6931985b6e893722/source-postgres/2.0.34/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by octavia-approvington** [comment]
This is really good <br/> simply the best

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
