### PR TITLE
renaming s3 state region to be consistent

### LINKED ISSUE #18412: Environment name inconsistency leads to State Storage Configuration Failure
## Environment
- **Airbyte version**:  0.40.16
- **OS Version / Instance**: kubernetes
- **Deployment**: EKS
- **Step where error happened**: Sync Job

## Current Behavior
The [application yaml](https://github.com/airbytehq/airbyte/blob/master/airbyte-workers/src/main/resources/application.yml#L49) looks for an environment variable called `STATE_STORAGE_S3_BUCKET_REGION` while the [EnvConfig model](https://github.com/airbytehq/airbyte/blob/182f2c6fba1bdc1050a2e20fb8402c5bf26f0bfb/airbyte-config/config-models/src/main/java/io/airbyte/config/EnvConfigs.java#L111) looks for a variable called `STATE_STORAGE_S3_REGION`.

## Expected Behavior
Environment variable names should be consistent.

## Steps to Reproduce
1. Deploy airbyte using the standard helm chart
2. Enable the container orchestrator and use s3 state storage
3. Container orchestrator will fail to boot.

## Are you willing to submit a PR?
yes.

### PR DESCRIPTION
**Pull request by gfeldman**
## What
Correct configuration of state storage when using the container orchestrator

## How
Make environment variable names consistent. resolves [issue 18412](https://github.com/airbytehq/airbyte/issues/18412)

## Recommended reading order
1. `EnvConfigs.java`
2. `OrchestratorConstants.java`

## 🚨 User Impact 🚨
None assuming users are using the correct environment variable

### CODE REVIEW

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
I think change is acceptable but need to have care to not make others deployments start to break.

@benmoriceau can you review this contribution?

**Comment by gfeldman** [comment]
FWIW, our deployment already broke because the environment variable in the [application yaml](https://github.com/airbytehq/airbyte/blob/master/airbyte-workers/src/main/resources/application.yml#L49) was changed in a previous commit.

**Comment by gfeldman** [comment]
Any movement on this?

**Comment by hao-bolt** [comment]
+1 We are blocked by this code especially this line

**Comment by marcosmarxm** [comment]
Hello :wave:, first thank you for this amazing contribution. 

We really appreciate the effort you've made to improve the project.
We ask you patience for the code review. Last month our team was focused on Hacktoberfest event and that probably left some PR without the proper feedback. And this week, due to the Thanksgiving US Holiday, most our team is out of office with their families. Another important piece of information why code won't be merge this week is: as a safety measure the core team has decided to freeze merging code to main branch to keep the release stable. Next week we'll return to you with the proper code review and update the status of your contribution.

If you have any questions feel free to send me a message in Slack!
Thanks!

**Comment by marcosmarxm** [comment]
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

**Comment by jasonicarter** [comment]
Hi...Still an issue in `0.40.29` - I'm using Kustomize and like others mentioned, when using S3 for state config this issue prevents `airbyte-worker` from starting up.

**Comment by DanSiegel-BO** [comment]
+1

**Comment by malikdiarra** [comment]
Hi @gfeldman, thanks for the PR! The issue has been fixed in a different [PR](https://github.com/airbytehq/airbyte-platform/commit/34ecd83d5ccc769d66c8fdbb06dd442c590f2dfe) though, so I'm going to close this.

Feel free to reopen this if you think the issue is not fully resolved.

**Pull request closed without merging**
