### PR TITLE
🐛 Source Hubspot: fix owners_archived stream

### LINKED ISSUE #33524: Source Hubspot: owners_archive stream API changes
### Connector Name

source-hubspot

### Connector Version

2.0.0

### What step the error happened?

Other

### Relevant information

The `owners_archived` stream is pulling from this [Owners](https://developers.hubspot.com/docs/api/crm/owners) endpoint, with the query parameter `archived` set to `true`. According to the docs this flag is to set:

> Whether to return only results that have been archived.

The behaviour of the API has recently (around 2023-11-13) has changed, and `archived=True` returns both archived and non-archived users, changing the output of this stream. This change has been acknowledged by HubSpot (as I've checked with them), but not that the docs are now incorrect.

AirByte should likely either:
- keep the original behaviour of `owners` / `owners_archived` streams, or
- make this change explicit as well (in docs).

### Relevant log output

_No response_

### Contribute

- [X] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by imrehg**
## What

The Hubspot Owners API had a change where the Owners endpoint started to return both archived and non-archived users when the `archived` flag as True has been passed in. This is in contradiction of the docs and previous behaviour that only archived accounts are returned.

This change updates the connector to retain the original behaviour.

Fixes #33524

## How

The API returns whether a user is archived or not, thus apply an additional filter to only return the archived users as per previous behaviour.

## Recommended reading order
1. `streams.py`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

This change adds a regression fix, thus without this fix there's a breaking change. 

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

This is likely a patch version change, because of these considerations.

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/resources/pull-requests-handbook)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

<details><summary><strong>Updating the Python CDK</strong></summary>

### Airbyter

Before merging:
- Pull Request description explains what problem it is solving
- Code change is unit tested
- Build and my-py check pass
- Smoke test the change on at least one affected connector
   - On Github: Run [this workflow](https://github.com/airbytehq/airbyte/actions/workflows/connectors_tests.yml), passing `--use-local-cdk --name=source-<connector>` as options
   - Locally: `airbyte-ci connectors --use-local-cdk --name=source-<connector> test`
- PR is reviewed and approved
      
After merging:
- [Publish the CDK](https://github.com/airbytehq/airbyte/actions/workflows/publish-cdk-command-manually.yml)
   - The CDK does not follow proper semantic versioning. Choose minor if this the change has significant user impact or is a breaking change. Choose patch otherwise.
   - Write a thoughtful changelog message so we know what was updated.
- Merge the platform PR that was auto-created for updating the Connector Builder's CDK version
   - This step is optional if the change does not affect the connector builder or declarative connectors.

</details>

### CODE REVIEW

**Comment by imrehg** [comment]
I think Hubspot has reversed their API behaviour change that _required_ this code change. Probably it's still more robust to keep, but it's no longer required to keep past Airbyte stream behaviour.

Would you prefer to drop this or keep it, then?

**Comment by marcosmarxm** [comment]
@imrehg sorry the missing review to your contribution. I requested to our team take a look and return to you as soon as possible!

**Comment by midavadim** [comment]
@imrehg 
Could you please confirm that this problem still exists for a basic Hubspot connector (latest version - 4.0.0)

The reason why I am asking is that my local tests on our Hubspot account showed that Owners and OwnersArchived streams are working as expected. In my case OwnersArchived retrieve only 'Archived' owners.

**Comment by imrehg** [comment]
> @imrehg Could you please confirm that this problem still exists for a basic Hubspot connector (latest version - 4.0.0)
> 
> The reason why I am asking is that my local tests on our Hubspot account showed that Owners and OwnersArchived streams are working as expected. In my case OwnersArchived retrieve only 'Archived' owners.

Hey, cheers for checking! As mentioned above https://github.com/airbytehq/airbyte/pull/33525#issuecomment-1884490521 while Hubspot support first didn't acknowledge the change, later silently reverted the functionality. Thus this change is IMHO goes either way: 
a) the changes allowsa more defensive mode of data pull in case they mess things up again
b) the changes can be skipped / PR closed since they backtracked (for now)

It depends on how much do you trust Hubspot in doing the right things :) Based on the interaction with their support, I would value defensiveness (if it's not too expensive), it's up to you, though.

Does this clarify things?

**Comment by midavadim** [comment]
I close this PR since API is working as expected,

**Pull request closed without merging**
