### PR TITLE
Remove `automaticMigrationAcceptanceTest`

### PR DESCRIPTION
**Pull request by evantahler**
This test is currently *very* flaky and breaking the build

After a chat with @davinchia, we don't feel that this test is providing much value, so we are comfortable disabling it for now to get the build green.

In general, now that we use Flyaway for migrations, what is the benefit of this test?  If there are particularly complex migrations in which we modify data, having a unit test makes sense for that migration, but testing that our migrations work all the way back to X version (v0.17.0 in this case) seems to be like we are testing the migration engine itself, and isn't necessary.  If we trust our migration engine, and each incremental migration, we should be in a safe place.

Reviewers: In the comments below, please let us know what you think about removing this test entirely, or should we just disable it for now until we can solve the flakiness?

* This commit just disables the test - https://github.com/airbytehq/airbyte/pull/15418/commits/177596b4d97c964e3e3c2f4d86d52279f56ebfba
* This commit removes the test entirely (along with related resources) -  https://github.com/airbytehq/airbyte/pull/15418/commits/977f06f3c453a9ea36bfe7b2fa37b0b8dd2906e2

### CODE REVIEW

**Review by davinchia — APPROVED** [review]
I'm okay with disabling the test. Deleting the test is okay with me as long as we make sure we have some follow up.

One reasonable path forward we discussed was an issue to test the case of 'the latest minor version should always be upgradable to this latest dev version i.e. ./gradlew build`.

**Review by cgardens — COMMENTED** [review]
* Testing back to 0.17.0 is probably not useful at this point.
* I do think that having some sanity check that we are able to upgrade from version X to version Y is useful. It is something that I think is worth having an acceptance test for because there is a little more to the migration than just running a flyway migration. 
* Do we know which part is flakey? If the part from 0.32.0 to current is solid, then I would keep that. If the flake is somewhere in these, then I would be in favor of figuring out how to reenable.
 
So I would be in favor of reducing the scope of the test to more modern versions of airbyte, but still having some sort of acceptance test.

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Comment by evantahler** [comment]
Something happened with this PR... Github got very mad when I force-pushed... recreating

**Comment by evantahler** [comment]
https://github.com/airbytehq/airbyte/pull/15497 has the modified/simpler test

**Pull request closed without merging**
