### PR TITLE
Destination Bigquery: Update `Dataset location` field description

### PR DESCRIPTION
**Pull request by girarda**
## What
* Update dataset location field description to make it clear that the field is required and has no default value

### CODE REVIEW

**Review by brianjlai — APPROVED** [review]

**Comment by girarda** [comment]
/publish connector=connectors/destination-bigquery-denormalized

**Comment by girarda** [comment]
/publish connector=connectors/destination-bigquery-denormalized

**Comment by girarda** [comment]
/publish connector=connectors/destination-bigquery-denormalized

**Pull request merged**
