### PR TITLE
live-tests: improve error message on connection retrieval

### PR DESCRIPTION
**Pull request by alafanechere**
## What
Closes https://github.com/airbytehq/airbyte-internal-issues/issues/9419

The connection retriever is used to fetch live connection from connection ID passed by the test suite:
* The connection ID can be static:
  * Manually passed by a developer
  * Set from the `connectorTestSuitesOptions` in `metadata.yaml`
* It can be dynamic when the connection selection is automatic (when the `--auto-select-connection` suite is passed to the test suite):
  * It's used in manual run of the test suite in workflow dispatch or local run.

The connection retriever can't guarantee it will find a connection whose control version matches the one passed to the test suite. The error messaging was not very helpful for developers to understand what's happening.

This PR centralizes retrieved connection validation and improves error messaging.

### CODE REVIEW

**Comment by alafanechere** [comment]
* **#44809** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/44809?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alafanechere and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by natikgadzhi — COMMENTED** [review]
So it's not that the docker image doesn't exist, it's that there was a retrieved connection, but no syncs in the past that we can take the docker image from? 

Should the error say that this connection did not have syncs lately? We can even make a link to the workspace + connection so you can click and check?

**Comment by alafanechere** [comment]
> So it's not that the docker image doesn't exist, it's that there was a retrieved connection, but no syncs in the past that we can take the docker image from?
> 
> Should the error say that this connection did not have syncs lately? We can even make a link to the workspace + connection so you can click and check?

It should be something like: `Could not find the docker image the latest job ran on. Please double check that the connection has run job with the control version`.  And yes we could display an url to the connection.
Thanks for you inputs

**Comment by alafanechere** [comment]
@natikgadzhi I improved multiple error messages and added connection url to ease the debugging.

## Something to keep in mind:
* When live test run automatically on PR they use test connections that are declared under the `connectorTestSuitesOptions` in `metadata.yaml`:
e.g: 
```
  connectorTestSuitesOptions:
    - suite: liveTests
      testConnections:
        - name: aha_config_dev_null
          id: 38f3c440-135f-4ca6-9d97-c68104b28cfa
```

Most of these connection are set in a [workspace](https://cloud.airbyte.com/workspaces/112412bb-78aa-4ca6-aace-ae0b83be2215/) seeded by @clnoll .
If a breaking change is released the connection will be pinned to an old version or deactivated. 
Which means they will not use the latest version we consider as the control version on runs following the breaking change. 
Manual intervention on the workspace to upgrade the connector or re-enable syncs is required.
In any case automatic regression tests results are currently ignored from the final CI status so it should not block anyone ATM.

**Review by clnoll — APPROVED** [review]
Thank you @alafanechere!

**Pull request merged**
