### PR TITLE
🎉 Destination Databricks: Support Azure storage (#15140)

### LINKED ISSUE #15140: 🎉 Destination Databricks: Support Azure storage
## Tell us about the problem you're trying to solve
I'd like to use the Databricks destination with Azure storage.

## Describe the solution you’d like
I'd like the option to specify an Azure storage location as an alternative to S3 storage.

## Describe the alternative you’ve considered or used
None.

## Additional context
None.

## Are you willing to submit a PR?
Yes.

### PR DESCRIPTION
**Pull request by abaerptc**
## What
Adds Azure storage as an option for Databricks destination.
This PR resolves #15140.

## How
Adds Azure storage as an alternative to S3.

## Recommended reading order
1. `*.json` - spec and sample configs
2. `Databricks*Config.java` - abstracted cloud storage, with two implementations (S3 and Azure)
3. `Databricks*Destination.java` - switches between S3 and Azure implementations depending on config
4. `Databricks*StreamCopierFactory.java` - abstracted, with two implementations (S3 and Azure)
5. `Databricks*StreamCopier.java` - abstracted, with existing S3 implementation refactored and Azure implementation added
6. `DatabricksSqlOperations.java` - minor change to allow execution of multiple statements
7. `Dockerfile` - bumped version
8. `build.gradle` - new deps
9. `AzureBlobStorageConnectionChecker.java` - adding new constructor to allow reuse in Databricks connector
10. `*Test.java`
11. `*.md` - docs

## 🚨 User Impact 🚨
No breaking changes.

## Pre-merge Checklist

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

Screen Shot 2022-08-04 at 3 17 46 PM

</details>

<details><summary><strong>Integration</strong></summary>

None.

</details>

<details><summary><strong>Acceptance</strong></summary>

Screen Shot 2022-08-04 at 3 18 46 PM

Cannot run S3 acceptance test locally.
</details>

### CODE REVIEW

**Comment by abaerptc** [comment]
The Azure integration test passes, but I don't have access to Databricks on AWS, and it's proving difficult to configure Azure Databricks to write to S3, so I'm not able to fully run the S3 integration tests. I have confirmed that the data gets written to S3 fine, but still need to confirm that the tables can be created from the S3 location in Databricks. Could someone from Airbyte please trigger the integration tests to run from this PR?

**Comment by abaerptc** [comment]
I pushed a new commit that should fix the error seen in the previous run of the S3 acceptance test.

The Azure acceptance test will require the addition of a new secrets file by an Airbyte member (see sample_secrets/azure_config.json).

**Comment by marcosmarxm** [comment]
> /test connector=connectors/destination-databricks
> 
> >

I added azure_config to Airbyte secret manager.

**Comment by tuliren** [comment]
@abaerptc, thank you for the PR! Could you add me as a collaborator to your fork? In this way I can push changes to this branch if needed as I am working on merging it.

@marcosmarxm, there is another PR pending merging for Databricks. Would you mind me doing the coordination and merging it later?

**Comment by marcosmarxm** [comment]
> @marcosmarxm, there is another PR pending merging for Databricks. Would you mind me doing the coordination and merging it later?

Sure @tuliren I'd just to confirm tests are running properly here.

**Comment by abaerptc** [comment]
@tuliren You're added as a collaborator.

**Comment by marcosmarxm** [comment]
@abaerptc now the integration tests are running with your changes!

**Comment by abaerptc** [comment]
> @abaerptc now the integration tests are running with your changes!

@marcosmarxm I see a few failures with messages like "Invalid configuration value detected for fs.azure.account.key". I think you need to give your Databricks instance access to your Azure account via the Spark configuration property `fs.azure.account.key`.

**Comment by TamGB** [comment]
Awesome PR @abaerptc !

Just a side note, the AWS version supports destination pattern matching (see airbyte-integrations/connectors/destination-databricks/src/main/java/io/airbyte/integrations/destination/databricks/DatabricksS3StorageConfig.java), is this something you would consider adding? (of course, I am happy to help!)

**Comment by abaerptc** [comment]
> Awesome PR @abaerptc !
> 
> Just a side note, the AWS version supports destination pattern matching (see airbyte-integrations/connectors/destination-databricks/src/main/java/io/airbyte/integrations/destination/databricks/DatabricksS3StorageConfig.java), is this something you would consider adding? (of course, I am happy to help!)

@TamGB I don't object to having pattern matching added. However, I don't have the availability to work on it. Please go ahead and implement it if you'd find it valuable.

**Comment by pkudinov** [comment]
Is this abstracted enough to add support for Databricks on Google Cloud (i.e. add GCS as a target bucket along with AWS S3, and Azure Blob)?

**Comment by abaerptc** [comment]
> Is this abstracted enough to add support for Databricks on Google Cloud (i.e. add GCS as a target bucket along with AWS S3, and Azure Blob)?

You should be able to add another implementation of the data storage method pretty easily based on what I've done here, yes.

**Comment by abaerptc** [comment]
@marcosmarxm @tuliren Any update on getting this merged in?

**Comment by natalyjazzviolin** [comment]
@abaerptc looks like there are conflicts, could you resolve them please?

@tuliren there is a lot of community interest for this PR, would you be able to move it up in your queue for review/merging? Thank you in advance :)

**Comment by abaerptc** [comment]
@natalyjazzviolin Conflicts are resolved.

**Comment by marcosmarxm** [comment]
So sorry @abaerptc for the long delay to reply. @tuliren is actively working to improve databricks destination for other features and to implement your contribution too. Soon he will return to you!

**Comment by tuliren** [comment]
Sorry about the delay.

To test the Azure integration, we would need a separate Databricks cluster. I was not able to do that so far. Given that it has been delayed for a long time, I will do some local testing, and mute the integration test related to Azure for now.

I target to merge it today.

**Review by tuliren — APPROVED** [review]
🎉

**Comment by tuliren** [comment]
/publish connector=connectors/destination-databricks run-tests=false

**Comment by tuliren** [comment]
@abaerptc, thank you very much for your contribution. Sorry about the long delay.

Please don't forget to remove me from your repo.

**Pull request merged**
