### PR TITLE
🎉 New Destination: Vectara (Vector Database)

### LINKED ISSUE #29012: ✨ Add Destination Vectara
https://docs.vectara.com/docs/
https://docs.vectara.com/docs/api-reference/api-overview

**Rules for the Connectors Hackathon**
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

## Some explanation of how this connector should work

For this destination connector, incoming records should be loaded into Vectara using the indexing API: https://docs.vectara.com/docs/api-reference/indexing-apis/indexing

Airbyte's unit of data is a "record", which is a JSON object with very little additional structure (in most cases there is a defined primary key that's guaranteed to be unique per record, but not always). A destination connector in the Airbyte sense receives records and needs to load them into the destination somehow.

OTOH, Vectara's unit of data is a "document". It has an id which can be mapped to the primary key of an Airbyte record, but there are no natural title/description/sections concepts in Airbyte.

To map a record to a document, the user should configure text fields and metadata fields as part of the connector configuration.

For each text field, create a corresponding section of the document, and copy the text of the field into that section.
Set metadata on the section, e.g. source_type with the value being the name of the text field.

Ideally, the corpus needs to be created with source_type specified as a filterable column. This will allow customers to run searches over some columns, and exclude others.

Fields specified as metadata field will be attached to the document as metadata.

### PR DESCRIPTION
**Pull request by topefolorunso**
## What
Adding a new vector destination - Vectara resolves #29012

## How
Generated the Python destination boilerplate codes and wrote the logic for connecting and writing to the database

## Recommended reading order
1. `destination.py`
2. `config.py`
3. `indexer.py`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Review by flash1293 — CHANGES_REQUESTED** [review]

**Review by flash1293 — COMMENTED** [review]
@topefolorunso Is this PR ready to review? I took a basic look and the following things seem off:
* There is still stuff around from the vector db cdk usage
* When building the docker image, the spec command is failing with `ModuleNotFoundError: No module named 'langchain'` (most likely related to the above)
* Basic documentation on how to set up a destination this way
* I'm not sure whether OAuth is the right approach here - isn't this more of a use case for API keys? I will reach out to the vectara devs for this question

**Comment by flash1293** [comment]
@topefolorunso Just chatted with vectara devs and going with oauth only for now makes sense. Please let me know once I can take a look, really excited for this connector :)

**Comment by topefolorunso** [comment]
> @topefolorunso Is this PR ready to review?

@flash1293 No it is not, still working on it. I will take note of your comments and update once complete. Please bear with me. Thanks.

**Comment by topefolorunso** [comment]
Please review now @flash1293

**Review by flash1293 — CHANGES_REQUESTED** [review]
Besides some smaller notes, this PR doesn't implement this part specified in the issue:

> To map a record to a document, the user should configure text fields and metadata fields as part of the connector configuration.

> For each text field, create a corresponding section of the document, and copy the text of the field into that section.
Set metadata on the section, e.g. source_type with the value being the name of the text field.

> Ideally, the corpus needs to be created with source_type specified as a filterable column. This will allow customers to run searches over some columns, and exclude others.

> Fields specified as metadata field will be attached to the document as metadata.

It shouldn't just drop everything the record as-is into the first section, there should be a user-configurable text vs. metadata field configuration like in the vector db destinations (just two fields with array of strings).

Then, each text field should become the `text` field of one seaprate section in the document sent to vectara and all the metadata fields should be added to the metadatajson (not just the stream name).

Also, if a stream has a configured primary key, it should be used as the `documentId`, concatenating all of these:
* Namespace
* Stream name
* all parts of the primary key

This needs to be done to make sure if the record gets updated and loaded again, it will replace the old version instead of creating a new document.

**Comment by marcosmarxm** [comment]
@topefolorunso are you still planning to work on this?

**Comment by topefolorunso** [comment]
> @topefolorunso are you still planning to work on this?

Yes I will work on it @marcosmarxm.

**Comment by flash1293** [comment]
@topefolorunso as it laid bare a while, @ofermend  from Vectara took over to bring it I’ve Ruhe finish line.

**Comment by topefolorunso** [comment]
> @topefolorunso as it laid bare a while, @ofermend from Vectara took over to bring it I’ve Ruhe finish line.

Oh alright. That's fine I guess. Well done @ofermend.
Sorry for the delay on my part. Though I just pushed some changes just in case.

**Comment by ofermend** [comment]
Thanks @topefolorunso - will pull your latest and try to get it to the finale. Appreciate your work so far and I'll reach out if I need any further help here.

**Comment by marcosmarxm** [comment]
Close in favor of https://github.com/airbytehq/airbyte/pull/33616

**Pull request closed without merging**
