### PR TITLE
docs: Add Glob, Schema, and File Format Setting to Microsoft Sharepoint and Onedrive

### PR DESCRIPTION
**Pull request by nataliekwong**
## What
- The docs contained references to glob patterns, schema and file format settings, but that content was missing.

## How
- Taken from Google Drive docs

### CODE REVIEW

**Review by jnr0790 — COMMENTED** [review]
looks good to me

**Review by lazebnyi — APPROVED** [review]
lgtm

**Comment by nataliekwong** [comment]
@lazebnyi I don't have the ability to check connector tests myself with my setup as I'm not developing locally, and since I'm only editing docs I don't expect them to fail. Are you able to help me bypass those tests?

**Comment by nataliekwong** [comment]
Thank you!!

**Pull request merged**
