### PR TITLE
Google Sheets: add row_id to rows and use as primary key

### PR DESCRIPTION
**Pull request by mdibaiee**
## What
Google Sheets connector does not have a primary key and there is no information on the row_id (changes to a row are not easily distinguishable)

## How
- Add row_id to data emitted by google sheets source and use this value as the primary key

## Recommended reading order
1. `airbyte-integrations/connectors/source-google-sheets/google_sheets_source/google_sheets_source.py`
2. `airbyte-integrations/connectors/source-google-sheets/google_sheets_source/helpers.py`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

Not sure if addition of a new data field is considered a breaking change, it might be.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<strong>Updating a connector</strong>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

## Tests

<details><summary><strong>Unit</strong></summary>

image

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by koconder** [comment]
@mdibaiee thanks for your contribution. I'm one of the Airbyte maintainers and will take a look and review your PR.

**Comment by koconder** [comment]
/publish connector=connectors/source-google-sheets run-tests=false

**Review by vincentkoc — APPROVED** [review]

**Comment by koconder** [comment]
/publish connector=connectors/source-google-sheets run-tests=false

**Comment by philippeboyd** [comment]
@koconder Not sure how you reviewed the code... Why did we jump from `0.2.21` to `0.2.30` ?

**Comment by danieldiamond** [comment]
@koconder @mdibaiee i'm experiencing issues now on version `0.2.30` with full-refresh overwrite tables only pulling half the rows

**Comment by danieldiamond** [comment]
Screenshot 2022-11-18 at 10 28 09 am

**Comment by danieldiamond** [comment]
Created discussion here: https://discuss.airbyte.io/t/google-sheets-0-2-30-missing-rows/3237

**Comment by koconder** [comment]
@philippeboyd we are rolling this back as we speak.

**Comment by danieldiamond** [comment]
@koconder please add regression tests.

**Comment by koconder** [comment]
@danieldiamond agree we need better tests to catch this. I have flagged with the team. Sorry for the inconvenience caused, we will be more diligent with such changes in future.

**Comment by mdibaiee** [comment]
@danieldiamond I don't see how this change would cause the connector to "pull half the rows", unless it used to pull duplicate documents (two for each row) and now that it knows the primary key it's only pulling them once. With that said, I don't know what the test is doing so I don't have all the context.

**Comment by mdibaiee** [comment]
@danieldiamond I don't see how this change would cause the connector to "pull half the rows", unless it used to pull duplicate documents (two for each row) and now that it knows the primary key it's only pulling them once. With that said, I don't know what the test is doing so I don't have all the context.

**Pull request merged**
