### PR TITLE
🐛 Destinations V2: fix bug with time types

### PR DESCRIPTION
**Pull request by cynthiaxyin**

### CODE REVIEW

**Review by edgao — APPROVED** [review]
:pasta:

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`0eb81dc12d`](https://github.com/airbytehq/airbyte/pull/28495/commits/0eb81dc12d39e1201fa250ea04b55debd4cbe803)) - ❌

⏲️  Total pipeline duration: 28mn30s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cynthia_time_types/1689808329/0eb81dc12d39e1201fa250ea04b55debd4cbe803/destination-bigquery/1.5.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery-denormalized test report (commit [`0eb81dc12d`](https://github.com/airbytehq/airbyte/pull/28495/commits/0eb81dc12d39e1201fa250ea04b55debd4cbe803)) - ❌

⏲️  Total pipeline duration: 17mn23s 

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ✅        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-bigquery-denormalized docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery-denormalized:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cynthia_time_types/1689808329/0eb81dc12d39e1201fa250ea04b55debd4cbe803/destination-bigquery-denormalized/1.5.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

**Comment by octavia-approvington** [comment]
What are we doing again? <br/> merge and squash

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
