### PR TITLE
Source Github: add workflow_jobs stream

### PR DESCRIPTION
**Pull request by Mainara**
## What
This PR adds a new stream for github source: `workflow_jobs`

## How
Used the endpoint: https://docs.github.com/pt/rest/actions/workflow-jobs#list-jobs-for-a-workflow-run to lists jobs for a workflow run and create a stream.

## Recommended reading order
1. `x.java`
2. `y.python`

##  User Impact 
There is no breakchanges, just a new stream was added.

## Pre-merge Checklist
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
</details>

## Tests

<details><summary><strong>Unit</strong></summary>

airbyte-integrations/connectors/source-github/unit_tests/test_stream.py::test_stream_workflow_jobs_read_incremental ✓                                             
 airbyte-integrations/connectors/source-github/unit_tests/test_stream.py::test_stream_workflow_jobs_full_refresh ✓                                                 
</details>

### CODE REVIEW

**Comment by sajarin** [comment]
Hi, thanks for the PR. This PR will be reviewed by one of our community maintainers as part our of Community Maintainer Program. Someone will be assigned shortly, thanks for being patient!

**Comment by Mainara** [comment]
This PR is related to this issue: https://github.com/airbytehq/airbyte/issues/16360

**Comment by YiyangLi** [comment]
@Mainara Thanks for your contribution. It looks like the `Workflow_jobs` stream supports incremental sync, which will run the test called TestStateWithAbnormallyLargeValues, [here](https://docs.airbyte.com/connector-development/testing-connectors/source-acceptance-tests-reference/#teststatewithabnormallylargevalues) is the documentation. 

Basically, it will read the file abnormal state from [the json file](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-github/integration_tests/abnormal_state.json), and it expects to return zero results because the state value is abnormally huge. Can you add a state value for workflow_jobs?

**Comment by py-paulo** [comment]
@YiyangLi we made the required changes, can you please validate it?

**Review by sajarin — APPROVED** [review]

**Comment by Mainara** [comment]
@sajarin we already followed [this 4 steps ](https://docs.airbyte.com/connector-development/#publishing-a-connector) but failed on definition generation.

**Comment by Mainara** [comment]
/publish connector=connectors/source-github auto-bump-version=false

**Comment by sajarin** [comment]
/publish connector=connectors/source-github auto-bump-version=false

**Comment by Mainara** [comment]
@sajarin We verify that the image of the new version has already been published: [airbyte/source-github:0.3.0](https://hub.docker.com/layers/airbyte/source-github/0.3.0/images/sha256-4ef99259655f[%E2%80%A6]519fe66f9d03f4fe9200a12d324c24198cc6cbd1ef589?context=explore), and the error is precisely because he tried to publish again this version. What can we do with this situation?

**Comment by davydov-d** [comment]
hey @sajarin can we please merge this PR? looks like it's completed.
it currently blocks from testing new ones(https://github.com/airbytehq/airbyte/actions/runs/3096389815/jobs/5011926155) as the image is published but not merged

**Comment by sajarin** [comment]
Should be good to go @davydov-d. 

Thanks for the PR @Mainara and @py-paulo and thanks for the review @YiyangLi!

**Pull request merged**
