### PR TITLE
🎉 New Source: Bamboo HR

### PR DESCRIPTION
**Pull request by haliva-firmbase**
## What
New source for bamboo hr: https://documentation.bamboohr.com/docs
Solve this issue: https://github.com/airbytehq/airbyte/issues/4931

Currently, it only supports Employees Directory API which is the only thing my company needs for now, in the future we might add additional APIs.

## Pre-merge Checklist
Expand the checklist which is relevant for this PR. 

<details><summary> <strong> Connector checklist </strong> </summary>
<p>

- [ ] Issue acceptance criteria met
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [x] Secrets are annotated with `airbyte_secret` in the connector's spec
- [ ] Credentials added to Github CI if needed and not already present. [instructions for injecting secrets into CI](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#using-credentials-in-ci). 
- [ ] Unit & integration tests added as appropriate (and are passing)
    * Community members: please provide proof of this succeeding locally e.g: screenshot or copy-paste acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] `/test connector=connectors/<name>` command as documented [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-an-existing-connector) is passing. 
    * Community members can skip this, Airbyters will run this for you. 
- [x] Code reviews completed
- [ ] Documentation updated 
    - [x] `README.md`
    - [x] `docs/SUMMARY.md` if it's a new connector
    - [x] Created or updated reference docs in `docs/integrations/<source or destination>/<name>`.
    - [x] Changelog in the appropriate page in `docs/integrations/...`. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md` contains a reference to the new connector
    - [x] Build status added to [build page](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md)
- [ ] Build is successful
- [x] Connector version bumped like described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] No major blockers
- [ ] PR merged into master branch
- [ ] Follow up tickets have been created
- [ ] Associated tickets have been closed & stakeholders notified
</p>
</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@haliva-firmbase thanks for the contribution! There anything you need help?

**Comment by haliva-firmbase** [comment]
@marcosmarxm @tuliren 
I see you didn't CR my code yet, did I miss something?

**Comment by marcosmarxm** [comment]
@haliva-firmbase oh! it's ready to review? can you change your PR from draft to ready?

**Comment by haliva-firmbase** [comment]
@marcosmarxm I asked in slack what should I do next and you guys told me that will CR my code and let me know if I need to change anything. sorry for the confusion.

**Comment by tuliren** [comment]
@haliva-firmbase, I am reviewing this PR. Would you mind giving me permission to your Airbyte fork? I'd like to push changes directly, such as resolving the conflicts. Otherwise, can you resolve the conflict in `source_definitions.yaml` yourself? Thank you.

**Comment by haliva-firmbase** [comment]
> @haliva-firmbase, I am reviewing this PR. Would you mind giving me permission to your Airbyte fork? I'd like to push changes directly, such as resolving the conflicts. Otherwise, can you resolve the conflict in `source_definitions.yaml` yourself? Thank you.

gave you permissions yesterday, you can also find me on slack (@orenhaliva) if you need anything else

**Review by tuliren — APPROVED** [review]
@haliva-firmbase, this PR looks good. I have made some changes to fix the integration test. It should be ready to go now.

After merging this PR, I will create another PR to publish it.

Thank you for your contribution!

(Also don't forget to remove me from your repo.)

**Pull request merged**
