### PR TITLE
connectors-ci: only run `integrationTest` gradle task for Java connectors

### PR DESCRIPTION
**Pull request by alafanechere**
## What
In our connector CI test pipeline I originally tried to split the run of  unit test and integration test in different steps.
For Java connectors my assumption was:
- run `./gradlew --dry-run :airbyte-integrations:connectors:source-postgres:test` to run **unit tests**
- run `./gradlew --dry-run :airbyte-integrations:connectors:source-postgres:integrationTestJava` to run **integration tests**

Following the problems encountered on https://github.com/airbytehq/airbyte/pull/27737 I believe this assumption is not correct as the `test` runs nothing and idles forever for some connectors...

To simplify things until we get a clear understanding of which gradle task we can run to split out unit and integration tests I suggest to stick to what /test was doing: only run the `integrationTest` task for java connectors.

## How
* Remove the unit test step on java connectors
* Replace the `integrationTestJava` task with `integrationTest`

### CODE REVIEW

**Comment by alafanechere** [comment]
I'm running the test pipeline on this branch for the same connectors as #27737 in https://github.com/airbytehq/airbyte/actions/runs/5400243312

**Comment by alafanechere** [comment]
@evantahler the[ workflow tested](https://github.com/airbytehq/airbyte/actions/runs/5400676807) all the sources connectors you modified on https://github.com/airbytehq/airbyte/pull/27737 in 2hours. I suggest we merge this in, update your branches and 🙏

**Review by evantahler — APPROVED** [review]
👍 from me, but lets see what @rodireich and @edgao have to say about this... I've always just been running `:test` myself

**Comment by alafanechere** [comment]
> do you know which connectors were getting stuck in unit tests

@edgao `./gradlew :airbyte-integrations:connectors:source-mssql-strict-encrypt:test` is stuck on my end.

**Comment by edgao** [comment]
is that on ci or local? iirc the mssql testcontainer version we're currently using doesn't launch on m1 macs

I tried running it on my laptop and got this jstack:
```
$ jstack 14842
<snip....>
"Test worker" #1 prio=5 os_prio=31 cpu=9139.19ms elapsed=73.29s tid=0x00007fed90010a00 nid=0x1e03 waiting on condition  [0x000000030cb31000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(java.base@17/Native Method)
	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:143)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:440)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
	at org.testcontainers.containers.GenericContainer$$Lambda$569/0x0000000800f96688.call(Unknown Source)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at io.airbyte.integrations.source.mssql.MssqlStrictEncryptJdbcSourceAcceptanceTest.init(MssqlStrictEncryptJdbcSourceAcceptanceTest.java:46)
```

**Pull request merged**
