### PR TITLE
Normalization: remove ssh errors if ssh is not being used

### LINKED ISSUE #6359: Normalization step throwing ERROR message: `cat: /data/2/0/normalize/localsshport.json: No such file or directory`
## Enviroment
- **Airbyte version**:  0.29.21-alpha
- **OS Version / Instance**: ˜
- **Deployment**: Docker
- **Source Connector and version**: Any
- **Destination Connector and version**: Postgres
- **Severity**: Very Low / **Low** / Medium / High / Critical
- **Step where error happened**: Deploy / **Sync job** / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
There is a ERROR message in normalization step:
```
2021-09-21 22:44:48 ERROR () LineGobbler(voidCall):85 - cat: /data/2/0/normalize/localsshport.json: No such file or directory
```

## Expected Behavior
As a User, I don't want to see an ERROR in successful sync.

## Logs

<details>
<summary>sync log</summary> 

```

2021-09-21 22:44:44 INFO () WorkerRun(call):62 - Executing worker wrapper. Airbyte version: 0.29.21-alpha
2021-09-21 22:44:44 INFO () TemporalAttemptExecution(get):114 - Executing worker wrapper. Airbyte version: 0.29.21-alpha
2021-09-21 22:44:44 WARN () Databases(createPostgresDatabaseWithRetry):58 - Waiting for database to become available...
2021-09-21 22:44:44 INFO () JobsDatabaseInstance(lambda$static$2):45 - Testing if jobs database is ready...
2021-09-21 22:44:44 INFO () Databases(createPostgresDatabaseWithRetry):75 - Database available!
2021-09-21 22:44:44 INFO () DefaultReplicationWorker(run):102 - start sync worker. job id: 2 attempt id: 0
2021-09-21 22:44:44 INFO () DefaultReplicationWorker(run):111 - configured sync modes: {null.calls=incremental - append_dedup}
2021-09-21 22:44:44 INFO () DefaultAirbyteDestination(start):78 - Running destination...
2021-09-21 22:44:44 INFO () LineGobbler(voidCall):85 - Checking if airbyte/destination-postgres:0.3.11 exists...
2021-09-21 22:44:44 INFO () LineGobbler(voidCall):85 - airbyte/destination-postgres:0.3.11 was found locally.
2021-09-21 22:44:44 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/2/0 --network host --log-driver none airbyte/destination-postgres:0.3.11 write --config destination_config.json --catalog destination_catalog.json
2021-09-21 22:44:44 INFO () LineGobbler(voidCall):85 - Checking if airbyte/source-zendesk-talk:0.1.2 exists...
2021-09-21 22:44:44 INFO () LineGobbler(voidCall):85 - airbyte/source-zendesk-talk:0.1.2 was found locally.
2021-09-21 22:44:44 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/2/0 --network host --log-driver none airbyte/source-zendesk-talk:0.1.2 read --config source_config.json --catalog source_catalog.json
2021-09-21 22:44:44 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):246 - Destination output thread started.
2021-09-21 22:44:44 INFO () DefaultReplicationWorker(run):139 - Waiting for source thread to join.
2021-09-21 22:44:44 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):210 - Replication thread started.
2021-09-21 22:44:45 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Starting syncing SourceZendeskTalk
2021-09-21 22:44:45 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Syncing calls stream
2021-09-21 22:44:45 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Advancing bookmark for Calls stream from None to 2021-04-01T14:23:15+00:00
2021-09-21 22:44:45 INFO () DefaultAirbyteStreamFactory(internalLog):110 - Finished syncing SourceZendeskTalk

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

### PR DESCRIPTION
**Pull request by Phlair**
## What
Closes https://github.com/airbytehq/airbyte/issues/6359

### notes
need to bump normalization even though only sshtunneling script in airbyte-workers is changed since normalization copies this file as part of its build.

### CODE REVIEW

**Review by ChristopheDuong — APPROVED** [review]

**Comment by Phlair** [comment]
not sure why Oracle failing tests above, will look into.

Also waiting on https://github.com/airbytehq/airbyte/pull/6496 to be merged as it bumped normalization version

**Comment by Phlair** [comment]
Going to merge this in without publishing new version of normalization.
It doesn't directly affect normalization (only ssh tunneling) and will get picked up on next normalization version bump.

**Pull request merged**
