### PR TITLE
🐛 Source Mongo: Revert recent changes

### PR DESCRIPTION
**Pull request by jdpgrailsdev**
## What
* Revert recent changes

## How
* Revert all recent changes

### CODE REVIEW

**Review by colesnodgrass — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-mysql-strict-encrypt test report (commit [`25499a1cfd`](https://github.com/airbytehq/airbyte/pull/28815/commits/25499a1cfd9ba7e0d4b22e8b95586df21fe5242d)) - ❌

⏲️  Total pipeline duration: 14mn57s 

| Step                                                                                   | Result   |
|:---------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                         | ✅        |
| QA checks                                                                              | ✅        |
| Build connector tar                                                                    | ✅        |
| Build source-mysql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mysql-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_revert-mongo-changes/1690485514/25499a1cfd9ba7e0d4b22e8b95586df21fe5242d/source-mysql-strict-encrypt/2.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-cockroachdb-strict-encrypt test report (commit [`25499a1cfd`](https://github.com/airbytehq/airbyte/pull/28815/commits/25499a1cfd9ba7e0d4b22e8b95586df21fe5242d)) - ❌

⏲️  Total pipeline duration: 07mn49s 

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-cockroachdb-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ✅        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build source-cockroachdb-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-cockroachdb-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                             | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_revert-mongo-changes/1690485514/25499a1cfd9ba7e0d4b22e8b95586df21fe5242d/source-cockroachdb-strict-encrypt/0.1.22/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-cockroachdb-strict-encrypt test
```

**Comment by octavia-approvington** [comment]
Myomoto says it looks good <br/> thats a niiice

**Review by octavia-approvington — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  destination-kafka test report (commit [`25499a1cfd`](https://github.com/airbytehq/airbyte/pull/28815/commits/25499a1cfd9ba7e0d4b22e8b95586df21fe5242d)) - ❌

⏲️  Total pipeline duration: 09mn51s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-kafka/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build destination-kafka docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-kafka:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_revert-mongo-changes/1690485514/25499a1cfd9ba7e0d4b22e8b95586df21fe5242d/destination-kafka/0.1.10/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-kafka test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-postgres test report (commit [`ca89baf93d`](https://github.com/airbytehq/airbyte/pull/28815/commits/ca89baf93dad040ca54e60e5502f36e611cbf08f)) - ❌

⏲️  Total pipeline duration: 47mn37s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-postgres docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-postgres:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_revert-mongo-changes/1690488464/ca89baf93dad040ca54e60e5502f36e611cbf08f/destination-postgres/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-postgres test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-strict-encrypt test report (commit [`ca89baf93d`](https://github.com/airbytehq/airbyte/pull/28815/commits/ca89baf93dad040ca54e60e5502f36e611cbf08f)) - ❌

⏲️  Total pipeline duration: 04mn12s 

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                           | ✅        |
| QA checks                                                                                | ❌        |
| Build connector tar                                                                      | ✅        |
| Build source-mongodb-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_revert-mongo-changes/1690488464/ca89baf93dad040ca54e60e5502f36e611cbf08f/source-mongodb-strict-encrypt/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mysql test report (commit [`ca89baf93d`](https://github.com/airbytehq/airbyte/pull/28815/commits/ca89baf93dad040ca54e60e5502f36e611cbf08f)) - ❌

⏲️  Total pipeline duration: 50mn06s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mysql/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build destination-mysql docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mysql:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mysql:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_revert-mongo-changes/1690488464/ca89baf93dad040ca54e60e5502f36e611cbf08f/destination-mysql/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mysql test
```

**Comment by dougludlow** [comment]
Is there any context around why these changes needed to be reverted? Am I missing an issue/discussion anywhere? I believe we were able to perform incremental syncs after #28733 was released, but now that it has been reverted, our incremental syncs are not longer working.

**Comment by mickaelandrieu** [comment]
Same here : ok you guys are maintainers but your job is also to communicate what you do and why you do it.
Else this project is not open source :/

**Pull request merged**
