### PR TITLE
Source Amplitude: handle null values and ampty strings in datetimefields

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/oncall/issues/1347

## How
If a datetime field contains a null value or empty string - do not try to convert it, just leave it as is

### CODE REVIEW

**Comment by davydov-d** [comment]
I'm gonna publish this change without running tests because our previous test account has been deactivated in GSM (probably due to real/live data in it) and our new account produces an error during a test run.
I have run the tests locally using previous creds:
image

**Review by bazarnov — APPROVED** [review]

**Comment by davydov-d** [comment]
/publish connector=connectors/source-amplitude run-tests=false

**Pull request merged**
