### PR TITLE
Avro destinations: map airbyte_type: integer to long

### LINKED ISSUE #23760: Source MySql Destination S3 (parquet) Support: Negative IDs / integers for MySql Source to AWS S3 Destination in parquet file format
## Environment
- **Airbyte version**:  0.40.30
- **OS Version / Instance**: Ubuntu, AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: airbyte/source-mysql:1.0.21
- **Destination Connector and version**: airbyte/destination-s3:0.3.19
- **Step where error happened**: 
- 1. Create a connection between Zendesk Support and S3, in a parquet format.
- 2. Load the data from parquet to DataFrame (pyspark/pandas) or any other.

## Current Behavior
* It will be possible to see IDs as negative floats when it should be integers. Also, the numbers don’t match the original ID on MySql*

## Expected Behavior
* IDs should come as in source, exact values*

## Logs
image

### PR DESCRIPTION
**Pull request by edgao**
## What
Closes https://github.com/airbytehq/airbyte/issues/23760

https://github.com/airbytehq/airbyte/pull/23466 only fixed this behavior for `{type: integer}`. This PR adds the fix for `{type: number, airbyte_type: integer}`.

Also updated test cases:
* add a test case for `{type: integer}`
* update the avroSchema for `{type: number, airbyte_type: integer}` to be `long`

(also, submitted an issue to clean up the data types stuff - it's a pretty messy change so will do it separately https://github.com/airbytehq/airbyte-internal-issues/issues/1726)

### CODE REVIEW

**Review by evantahler — APPROVED** [review]
Tests pass, so :shipit:!

**Comment by edgao** [comment]
/publish connector=connectors/destination-bigquery,connectors/destination-bigquery-denormalized,connectors/destination-gcs,connectors/destination-s3,connectors/destination-snowflake

**Comment by TBernstein4** [comment]
@edgao is there a chance that this would change the datatype format in the following manner:

`1676500610` now formatted as `1.678177401E9`?

**Comment by edgao** [comment]
I would not expect that - that actually sounds like it's being treated as a number/float. Probably easier to discuss over slack / separate issue though

**Pull request merged**
