### PR TITLE
source-you-need-a-budget-ynab contribution from bnmry

### PR DESCRIPTION
**Pull request by bnmry**
Auto-generated PR by the Connector Builder for source-you-need-a-budget-ynab

### CODE REVIEW

**Comment by natikgadzhi** [comment]
Whoa! Did not expect to see a Ynab connector, but hey, thank you @bnmry!

**Comment by natikgadzhi** [comment]
Can you please upload the icon? Needs to be a squared centered SVG. Go to this PR changed files, icon.svg, and click three dots → edit, put the new icon there. 

Once we have the icon, I'm going to run formatters and merge this!

**Comment by bnmry** [comment]
> Can you please upload the icon? Needs to be a squared centered SVG. Go to this PR changed files, icon.svg, and click three dots → edit, put the new icon there.
> 
> Once we have the icon, I'm going to run formatters and merge this!

Ok logo should be added now. I'm glad it's appreciated!  I've been using it for awhile now privately, but hope others can make use of it. Thanks for your patience with my first ever contribution.

**Pull request merged**
