### PR TITLE
connector-acceptance-tests: Bump PyYaml to 6.0

### PR DESCRIPTION
**Pull request by girarda**
## What
* Upgrade pyyaml to 6.0 to solve the [cython dependency issue](https://github.com/yaml/pyyaml/issues/601)

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`4a2e4ba37b`](https://github.com/airbytehq/airbyte/pull/28432/commits/4a2e4ba37bd012a9ceff256ab763ac4d62918979)) - ❌

⏲️  Total pipeline duration: 01mn10s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ❌        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_stripe_cdk46/1689718013/4a2e4ba37bd012a9ceff256ab763ac4d62918979/source-stripe/3.12.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`4a2e4ba37b`](https://github.com/airbytehq/airbyte/pull/28432/commits/4a2e4ba37bd012a9ceff256ab763ac4d62918979)) - ❌

⏲️  Total pipeline duration: 01mn26s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ❌        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_stripe_cdk46/1689718188/4a2e4ba37bd012a9ceff256ab763ac4d62918979/source-stripe/3.12.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`84856dbba3`](https://github.com/airbytehq/airbyte/pull/28432/commits/84856dbba3247e1c59b50aa2f06c3b56663ef866)) - ❌

⏲️  Total pipeline duration: 11mn51s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ❌        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/alex_stripe_cdk46/1689718749/84856dbba3247e1c59b50aa2f06c3b56663ef866/source-stripe/3.12.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Review by pedroslopez — APPROVED** [review]
👍🏼 Looks like everything passed for stripe and just the increment version check failed, as expected

Thanks!

**Comment by octavia-approvington** [comment]
Check that box <br/> TODO complete

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
