### PR TITLE
connectors-ci: dynamic dagger pipeline name

### PR DESCRIPTION
**Pull request by alafanechere**
## What
For logging/viz improvement we should create name dagger pipeline dynamically by connector.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-pokeapi test report (commit [`976feeb584`](https://github.com/airbytehq/airbyte/pull/26886/commits/976feeb5843a1da80cebb08e5c6e232e93aba2cc)) - ❌

⏲️  Total pipeline duration: 83 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-pokeapi/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ❌        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-pokeapi docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5141604943)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-pokeapi test
```

**Comment by octavia-squidington-iii** [comment]
##  source-openweather test report (commit [`976feeb584`](https://github.com/airbytehq/airbyte/pull/26886/commits/976feeb5843a1da80cebb08e5c6e232e93aba2cc)) - ❌

⏲️  Total pipeline duration: 93 seconds

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-openweather/metadata.yaml | ✅        |
| Connector version semver check.                                           | ✅        |
| Connector version increment check.                                        | ❌        |
| QA checks                                                                 | ✅        |
| Code format checks                                                        | ✅        |
| Connector package install                                                 | ✅        |
| Build source-openweather docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                | ✅        |
| Acceptance tests                                                          | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5141604943)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-openweather test
```

**Comment by octavia-approvington** [comment]
Jerry would be proud <br/> Spongebob

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
