### PR TITLE
Remove `additionalProperties: false` from JDBC destination connectors

### LINKED ISSUE #14550: Remove `additionalProperties: false` from JDBC destination connectors
## Problem
As discovered in https://github.com/airbytehq/oncall/issues/289, a spec declaring "additionalProperties": false introduces the risk of accidental breaking changes. Specifically, when removing a property from the spec, existing connector configs will no longer be valid.

To make these upgrades/rollbacks smoother, we need to remove `additionalProperties` from connectors affected by these changes.  

## Action items

- [ ] remove `additionalProperties:false` (or replace it with `additionalProperties:true`, whichever is the correct approach)
- [ ] publish new versions of JDBC-based connectors
- [ ] merge changes

### PR DESCRIPTION
**Pull request by VitaliiMaltsev**
## What
As discovered in [airbytehq/oncall#289](https://github.com/airbytehq/oncall/issues/289), a spec declaring "additionalProperties": false introduces the risk of accidental breaking changes. Specifically, when removing a property from the spec, existing connector configs will no longer be valid.

To make these upgrades/rollbacks smoother, we need to remove additionalProperties from connectors affected by these changes.

## How
Remove additionalProperties: false

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
none

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Review by alexandr-shegeda — APPROVED** [review]
LGTM

**Review by sashaNeshcheret — APPROVED** [review]

**Review by edgao — APPROVED** [review]
is the plan to have a couple other PRs for related connectors? I'm aware of destination-databricks and destination-mssql both being affected, not sure if there are others

**Review by grishick — APPROVED** [review]
please don't forget the remaining destinations

**Comment by VitaliiMaltsev** [comment]
@edgao @grishick added databricks and mssql connectors. All other JDBC destinations have additionalProperties: true in their spec. Are there any other connectors that need to be added to the scope of this ticket?

**Comment by edgao** [comment]
It looks like this PR covers all the JDBC destinations. This is the list that I found (maybe outdated, I don't have latest master checked out)
```
8:12:53 edgao:~/code/airbyte/airbyte-integrations/connectors(edgao/normalization_dats () U)$ grep -i -F '"additionalProperties": false' */**/spec.json | uniq
destination-amazon-sqs/destination_amazon_sqs/spec.json:    "additionalProperties": false,
destination-aws-datalake/destination_aws_datalake/spec.json:    "additionalProperties": false,
destination-azure-blob-storage/src/main/resources/spec.json:    "additionalProperties": false,
destination-csv/src/main/resources/spec.json:    "additionalProperties": false,
destination-databricks/src/main/resources/spec.json:    "additionalProperties": false,
destination-dynamodb/src/main/resources/spec.json:    "additionalProperties": false,
destination-elasticsearch/src/main/resources/spec.json:    "additionalProperties": false,
destination-elasticsearch/src/main/resources/spec.json:            "additionalProperties": false,
destination-firebolt/destination_firebolt/spec.json:    "additionalProperties": false,
destination-firebolt/destination_firebolt/spec.json:            "additionalProperties": false,
destination-firestore/destination_firestore/spec.json:    "additionalProperties": false,
destination-google-sheets/destination_google_sheets/spec.json:    "additionalProperties": false,
destination-keen/src/main/resources/spec.json:    "additionalProperties": false,
destination-kvdb/destination_kvdb/spec.json:    "additionalProperties": false,
destination-local-json/src/main/resources/spec.json:    "additionalProperties": false,
destination-mongodb/src/main/resources/spec.json:            "additionalProperties": false,
destination-mssql/build/resources/main/spec.json:            "additionalProperties": false,
destination-mssql/src/main/resources/spec.json:            "additionalProperties": false,
destination-oracle/build/resources/main/spec.json:            "additionalProperties": false,
destination-oracle/src/main/resources/spec.json:            "additionalProperties": false,
destination-rabbitmq/destination_rabbitmq/spec.json:    "additionalProperties": false,
destination-redis/src/main/resources/spec.json:    "additionalProperties": false,
destination-rockset/src/main/resources/spec.json:    "additionalProperties": false,
destination-scaffold-destination-python/destination_scaffold_destination_python/spec.json:    "additionalProperties": false,
destination-sftp-json/destination_sftp_json/spec.json:    "additionalProperties": false,
destination-snowflake/build/resources/main/spec.json:            "additionalProperties": false,
destination-snowflake/build/resources/main/spec.json:        "additionalProperties": false,
destination-snowflake/src/main/resources/spec.json:            "additionalProperties": false,
destination-snowflake/src/main/resources/spec.json:        "additionalProperties": false,
source-airtable/source_airtable/spec.json:    "additionalProperties": false,
source-amazon-ads/integration_tests/spec.json:        "additionalProperties": false,
source-amazon-seller-partner/integration_tests/spec.json:        "additionalProperties": false,
source-amazon-sqs/source_amazon_sqs/spec.json:    "additionalProperties": false,
source-amplitude/source_amplitude/spec.json:    "additionalProperties": false,
source-apify-dataset/source_apify_dataset/spec.json:    "additionalProperties": false,
source-appsflyer/source_appsflyer/spec.json:    "additionalProperties": false,
source-appstore-singer/source_appstore_singer/spec.json:    "additionalProperties": false,
source-azure-table/source_azure_table/spec.json:    "additionalProperties": false,
source-bamboo-hr/source_bamboo_hr/spec.json:    "additionalProperties": false,
source-bigcommerce/source_bigcommerce/spec.json:    "additionalProperties": false,
source-bigquery/src/main/resources/spec.json:    "additionalProperties": false,
source-bing-ads/source_bing_ads/spec.json:        "additionalProperties": false,
source-chargebee/source_chargebee/spec.json:    "additionalProperties": false,
source-chargify/source_chargify/spec.json:    "additionalProperties": false,
source-chartmogul/source_chartmogul/spec.json:    "additionalProperties": false,
source-clickhouse/src/main/resources/spec.json:    "additionalProperties": false,
source-close-com/source_close_com/spec.json:    "additionalProperties": false,
source-cockroachdb/src/main/resources/spec.json:    "additionalProperties": false,
source-commercetools/source_commercetools/spec.json:    "additionalProperties": false,
source-confluence/source_confluence/spec.json:    "additionalProperties": false,
source-db2/src/main/resources/spec.json:    "additionalProperties": false,
source-db2/src/main/resources/spec.json:            "additionalProperties": false,
source-delighted/source_delighted/spec.json:    "additionalProperties": false,
source-dixa/source_dixa/spec.json:    "additionalProperties": false,
source-e2e-test/src/main/resources/spec.json:    "additionalProperties": false,
source-elasticsearch/src/main/resources/spec.json:    "additionalProperties": false,
source-elasticsearch/src/main/resources/spec.json:            "additionalProperties": false,
source-faker/source_faker/spec.json:    "additionalProperties": false,
source-file-secure/integration_tests/spec.json:    "additionalProperties": false,
source-file/source_file/spec.json:    "additionalProperties": false,
source-firebolt/source_firebolt/spec.json:    "additionalProperties": false,
source-flexport/source_flexport/spec.json:    "additionalProperties": false,
source-freshdesk/source_freshdesk/spec.json:    "additionalProperties": false,
source-freshsales/source_freshsales/spec.json:    "additionalProperties": false,
source-freshservice/source_freshservice/spec.json:    "additionalProperties": false,
source-github/source_github/spec.json:        "additionalProperties": false,
source-gitlab/source_gitlab/spec.json:    "additionalProperties": false,
source-google-analytics-data-api/source_google_analytics_data_api/spec.json:    "additionalProperties": false,
source-google-search-console/source_google_search_console/spec.json:    "additionalProperties": false,
source-google-workspace-admin-reports/source_google_workspace_admin_reports/spec.json:    "additionalProperties": false,
source-greenhouse/source_greenhouse/spec.json:    "additionalProperties": false,
source-harvest/source_harvest/spec.json:            "additionalProperties": false,
source-harvest/source_harvest/spec.json:        "additionalProperties": false,
source-hellobaton/source_hellobaton/spec.json:    "additionalProperties": false,
source-iterable/source_iterable/spec.json:    "additionalProperties": false,
source-jdbc/build/resources/main/spec.json:    "additionalProperties": false,
source-jdbc/src/main/resources/spec.json:    "additionalProperties": false,
source-kafka/src/main/resources/spec.json:    "additionalProperties": false,
source-kyriba/source_kyriba/spec.json:    "additionalProperties": false,
source-lemlist/source_lemlist/spec.json:    "additionalProperties": false,
source-lever-hiring/integration_tests/spec.json:        "additionalProperties": false,
source-lever-hiring/source_lever_hiring/spec.json:        "additionalProperties": false,
source-linnworks/source_linnworks/spec.json:    "additionalProperties": false,
source-looker/source_looker/spec.json:    "additionalProperties": false,
source-mailchimp/source_mailchimp/spec.json:        "additionalProperties": false,
source-microsoft-teams/source_microsoft_teams/spec.json:            "additionalProperties": false,
source-microsoft-teams/source_microsoft_teams/spec.json:        "additionalProperties": false,
source-monday/source_monday/spec.json:        "additionalProperties": false,
source-mongodb-v2/src/main/resources/spec.json:            "additionalProperties": false,
source-mongodb/lib/spec.json:    "additionalProperties": false,
source-mssql/src/main/resources/spec.json:            "additionalProperties": false,
source-my-hours/source_my_hours/spec.json:    "additionalProperties": false,
source-mysql/src/main/resources/spec.json:    "additionalProperties": false,
source-notion/source_notion/spec.json:    "additionalProperties": false,
source-okta/source_okta/spec.json:    "additionalProperties": false,
source-onesignal/source_onesignal/spec.json:    "additionalProperties": false,
source-openweather/source_openweather/spec.json:    "additionalProperties": false,
source-oracle/src/main/resources/spec.json:    "additionalProperties": false,
source-oracle/src/main/resources/spec.json:            "additionalProperties": false,
source-orb/source_orb/spec.json:    "additionalProperties": false,
source-outreach/source_outreach/spec.json:    "additionalProperties": false,
source-pardot/source_pardot/spec.json:    "additionalProperties": false,
source-paystack/source_paystack/spec.json:    "additionalProperties": false,
source-persistiq/source_persistiq/spec.json:    "additionalProperties": false,
source-pivotal-tracker/source_pivotal_tracker/spec.json:    "additionalProperties": false,
source-plaid/source_plaid/spec.json:    "additionalProperties": false,
source-pokeapi/source_pokeapi/spec.json:    "additionalProperties": false,
source-postgres/build/resources/main/spec.json:    "additionalProperties": false,
source-postgres/build/resources/main/spec.json:            "additionalProperties": false,
source-postgres/src/main/resources/spec.json:    "additionalProperties": false,
source-postgres/src/main/resources/spec.json:            "additionalProperties": false,
source-posthog/source_posthog/spec.json:    "additionalProperties": false,
source-prestashop/source_prestashop/spec.json:    "additionalProperties": false,
source-python-http-tutorial/source_python_http_tutorial/spec.json:    "additionalProperties": false,
source-quickbooks-singer/source_quickbooks_singer/spec.json:    "additionalProperties": false,
source-recharge/source_recharge/spec.json:    "additionalProperties": false,
source-recurly/source_recurly/spec.json:    "additionalProperties": false,
source-redshift/src/main/resources/spec.json:    "additionalProperties": false,
source-retently/source_retently/spec.json:            "additionalProperties": false,
source-retently/source_retently/spec.json:        "additionalProperties": false,
source-rki-covid/source_rki_covid/spec.json:    "additionalProperties": false,
source-salesloft/source_salesloft/spec.json:    "additionalProperties": false,
source-scaffold-java-jdbc/src/main/resources/spec.json:    "additionalProperties": false,
source-sendgrid/source_sendgrid/spec.json:    "additionalProperties": false,
source-sentry/source_sentry/spec.json:    "additionalProperties": false,
source-shopify/source_shopify/spec.json:        "additionalProperties": false,
source-shortio/source_shortio/spec.json:    "additionalProperties": false,
source-smartsheets/source_smartsheets/spec.json:        "additionalProperties": false,
source-snapchat-marketing/source_snapchat_marketing/spec.json:    "additionalProperties": false,
source-snowflake/src/main/resources/spec.json:        "additionalProperties": false,
source-square/source_square/spec.json:        "additionalProperties": false,
source-stock-ticker-api-tutorial/spec.json:    "additionalProperties": false,
source-strava/source_strava/spec.json:    "additionalProperties": false,
source-strava/source_strava/spec.json:        "additionalProperties": false,
source-talkdesk-explore/source_talkdesk_explore/spec.json:    "additionalProperties": false,
source-tempo/source_tempo/spec.json:    "additionalProperties": false,
source-tidb/src/main/resources/spec.json:    "additionalProperties": false,
source-tplcentral/source_tplcentral/spec.json:    "additionalProperties": false,
source-twilio/source_twilio/spec.json:    "additionalProperties": false,
source-us-census/source_us_census/spec.json:    "additionalProperties": false,
source-woocommerce/source_woocommerce/spec.json:    "additionalProperties": false,
source-yahoo-finance-price/source_yahoo_finance_price/spec.json:    "additionalProperties": false,
source-youtube-analytics/source_youtube_analytics/spec.json:    "additionalProperties": false,
source-youtube-analytics/source_youtube_analytics/spec.json:        "additionalProperties": false,
source-zendesk-chat/source_zendesk_chat/spec.json:        "additionalProperties": false,
source-zendesk-sunshine/source_zendesk_sunshine/spec.json:        "additionalProperties": false,
source-zendesk-support/source_zendesk_support/spec.json:        "additionalProperties": false,
source-zenloop/source_zenloop/spec.json:    "additionalProperties": false,
source-zoho-crm/source_zoho_crm/spec.json:    "additionalProperties": false,
source-zoom-singer/source_zoom_singer/spec.json:    "additionalProperties": false,
8:12:54 edgao:~/code/airbyte/airbyte-integrations/connectors(edgao/normalization_dats () U)$
```

**Comment by grishick** [comment]
> @edgao should I create a separate task for all other non-JDBC connectors?

Yes, please create a separate issue for non-JDBC connectors and link it here

**Comment by VitaliiMaltsev** [comment]
> > @edgao should I create a separate task for all other non-JDBC connectors?
> 
> Yes, please create a separate issue for non-JDBC connectors and link it here
https://github.com/airbytehq/airbyte/issues/14718

**Comment by VitaliiMaltsev** [comment]
/publish connector=connectors/destination-oracle-strict-encrypt auto-bump-version=false

**Comment by VitaliiMaltsev** [comment]
> https://github.com/airbytehq/airbyte/actions/runs/2671652639

@grishick seems like publish of oracle-destination was cancelled after 4 hours. Please advice how to avoid this behaviour

**Comment by grishick** [comment]
I pulbished destination oracle here: https://github.com/airbytehq/airbyte/pull/14736

**Comment by edgao** [comment]
@VitaliiMaltsev I forgot about source-tidb in this PR. It's definitely lower-priority so feel free to just combine it with the followup issue. (unless @grishick you think it's worth handling separately)

**Comment by VitaliiMaltsev** [comment]
> @VitaliiMaltsev I forgot about source-tidb in this PR. It's definitely lower-priority so feel free to just combine it with the followup issue. (unless @grishick you think it's worth handling separately)

@edgao created [PR](https://github.com/airbytehq/airbyte/pull/14996) for source-tidb

**Pull request merged**
