### PR TITLE
🎉 Snowflake destination: reduce memory footprint

### PR DESCRIPTION
**Pull request by tuliren**
- Estimate record message size by string length, instead of byte length. This significantly reduce the amount of memory usage.
- To further reduce redundant string serialization, the size estimation only sample the string size very N records, instead of doing it for every record.
- See rationales in https://github.com/airbytehq/airbyte/issues/10260.

### CODE REVIEW

**Review by subodh1810 — COMMENTED** [review]
Am not sure I understand how this will reduce heap consumption. The only difference I see is that with previous logic we were calculating the size for each record using `s.getBytes(StandardCharsets.UTF_8).length;` but with new logic  we do it via `Jsons.serialize(data).length() * 4L` but for every 20th record. How does this help with lesser heap consumption?

**Comment by tuliren** [comment]
@subodh1810, calculating the bytes of the serialized json strings creates lots of byte array objects.  So switching away from generating the byte array is the fix. Before this change, the connector will run out of memory when the max heap size is 500 MB. After this change, it works even with just 300 MB heap size.

See [here](https://github.com/airbytehq/airbyte/issues/10260#issuecomment-1042631919) for raw data.

**Review by subodh1810 — APPROVED** [review]

**Review by edgao — APPROVED** [review]

**Pull request merged**
