### PR TITLE
remove strict encrypt variant of cockroack db 

### PR DESCRIPTION
**Pull request by erohmensing**
The strict encrypt variant of cockroachdb has never had any use in cloud. It has also already been hidden from cloud for a while (so users haven't been able to create new connections with it). We are deleting it. Bye!

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-cockroachdb test report (commit [`9202585064`](https://github.com/airbytehq/airbyte/pull/31148/commits/920258506479ffb3f107095587699f07a176a617)) - ❌

⏲️  Total pipeline duration: 304mn06s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build connector tar                                                | ✅        |
| Build source-cockroachdb docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                          | ❌        |
| Java Connector Integration Tests                                   | ❌        |
| Acceptance tests                                                   | ✅        |
| Validate metadata for source-cockroachdb                           | ✅        |
| Connector version semver check                                     | ✅        |
| QA checks                                                          | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_axe-cockroach-db-strict-encrypt/1696631012/920258506479ffb3f107095587699f07a176a617/source-cockroachdb/0.1.22/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:920258506479ffb3f107095587699f07a176a617)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-cockroachdb test
```

**Review by bnchrch — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-cockroachdb test report (commit [`b9f1ca5a20`](https://github.com/airbytehq/airbyte/pull/31148/commits/b9f1ca5a207394da7b548109dee6f65e072ba516)) - ❌

⏲️  Total pipeline duration: 603mn18s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build connector tar                                                | ✅        |
| Build source-cockroachdb docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                          | ❌        |
| Java Connector Integration Tests                                   | ❌        |
| Acceptance tests                                                   | ✅        |
| Validate metadata for source-cockroachdb                           | ✅        |
| Connector version semver check                                     | ✅        |
| QA checks                                                          | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_axe-cockroach-db-strict-encrypt/1696973836/b9f1ca5a207394da7b548109dee6f65e072ba516/source-cockroachdb/0.1.22/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b9f1ca5a207394da7b548109dee6f65e072ba516)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-cockroachdb test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-cockroachdb test report (commit [`297badd647`](https://github.com/airbytehq/airbyte/pull/31148/commits/297badd647365e842956955ba52a0606879b5339)) - ❌

⏲️  Total pipeline duration: 302mn08s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build connector tar                                                | ✅       |
| Java Connector Unit Tests                                          | ❌       |
| Build source-cockroachdb docker image for platform(s) linux/x86_64 | ✅       |
| Acceptance tests                                                   | ✅       |
| Java Connector Integration Tests                                   | ❌       |
| Validate metadata for source-cockroachdb                           | ✅       |
| Connector version semver check                                     | ✅       |
| QA checks                                                          | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_axe-cockroach-db-strict-encrypt/1697742446/297badd647365e842956955ba52a0606879b5339/source-cockroachdb/0.1.22/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:297badd647365e842956955ba52a0606879b5339)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-cockroachdb test
```

**Comment by octavia-approvington** [comment]
A crack team of mammals has made a decision.  <br/> imagine a seal of approval

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
