### PR TITLE
publish: run QA checks

### PR DESCRIPTION
**Pull request by alafanechere**
## What
The QA checks should run on publish. They are not part of the integration test suite, this is why they were not triggered on publish. 
[They are a seperate step in /test workflow
](https://github.com/airbytehq/airbyte/blob/master/.github/workflows/test-command.yml#L165) that we shall also declared on /publish.

More context about why we fixing it now is important [here](https://airbytehq-team.slack.com/archives/C056HGD1QSW/p1683711184017929).
## How
Run QA check before actual publish flow started by  `manage.sh`

### CODE REVIEW

**Comment by alafanechere** [comment]
Artificial pokeapi publish

**Comment by alafanechere** [comment]
Artificial pokeapi publish

**Comment by alafanechere** [comment]
[I ran /publish on this branch for source-pokeapi](https://github.com/airbytehq/airbyte/actions/runs/4937631550/jobs/8826539063). The QA checks run 🎉

**Review by bnchrch — APPROVED** [review]
Great Catch!

**Pull request merged**
