### PR TITLE
CI checks for #26203

### PR DESCRIPTION
**Pull request by sh4sh**
Running checks for community pr https://github.com/airbytehq/airbyte/pull/26203

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`ffbd346120`](https://github.com/airbytehq/airbyte/pull/27417/commits/ffbd346120f690d09724ed9dab19c19318a9547f)) - ❌

⏲️  Total pipeline duration: 67 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check.                                          | ✅        |
| Connector version increment check.                                       | ✅        |
| QA checks                                                                | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5281933547)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`9f72fe8f41`](https://github.com/airbytehq/airbyte/pull/27417/commits/9f72fe8f41e61d9d720d8cdb63498eb8079d657d)) - ❌

⏲️  Total pipeline duration: 48 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check.                                          | ✅        |
| Connector version increment check.                                       | ✅        |
| QA checks                                                                | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5281935974)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`c9c326b572`](https://github.com/airbytehq/airbyte/pull/27417/commits/c9c326b5722d254be5665c54f6b28dfcfbc991a2)) - ❌

⏲️  Total pipeline duration: 37 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check.                                          | ✅        |
| Connector version increment check.                                       | ✅        |
| QA checks                                                                | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5282040170)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`64e54aca17`](https://github.com/airbytehq/airbyte/pull/27417/commits/64e54aca17fbfd80f790e0a325dc0083215b16cc)) - ❌

⏲️  Total pipeline duration: 14.47s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ❌        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/amazondisplay/1688052475/64e54aca17fbfd80f790e0a325dc0083215b16cc/source-amazon-ads/2.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`526746c454`](https://github.com/airbytehq/airbyte/pull/27417/commits/526746c454cb5edb965ede34cc6e9dfb62645a70)) - ❌

⏲️  Total pipeline duration: 49.13s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ❌        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/amazondisplay/1688053862/526746c454cb5edb965ede34cc6e9dfb62645a70/source-amazon-ads/2.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`d351000326`](https://github.com/airbytehq/airbyte/pull/27417/commits/d351000326bf377d2706d7797d6bdb2dd650d009)) - ❌

⏲️  Total pipeline duration: 01mn23s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/amazondisplay/1688054253/d351000326bf377d2706d7797d6bdb2dd650d009/source-amazon-ads/2.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`0f5f6de0b1`](https://github.com/airbytehq/airbyte/pull/27417/commits/0f5f6de0b193a764a7533c9e6bbb6d3d9e91ef6c)) - ❌

⏲️  Total pipeline duration: 01mn24s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/amazondisplay/1688407645/0f5f6de0b193a764a7533c9e6bbb6d3d9e91ef6c/source-amazon-ads/2.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`9de92422f5`](https://github.com/airbytehq/airbyte/pull/27417/commits/9de92422f532907062f2e4f60ed1cce63b2f1b97)) - ❌

⏲️  Total pipeline duration: 01mn28s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/amazondisplay/1688580947/9de92422f532907062f2e4f60ed1cce63b2f1b97/source-amazon-ads/2.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-amazon-ads test report (commit [`ab3c48b516`](https://github.com/airbytehq/airbyte/pull/27417/commits/ab3c48b5166985b255f0ea99f64a2c018311e59f)) - ❌

⏲️  Total pipeline duration: 51.80s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Connector package install                                      | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                     | ❌        |
| Code format checks                                             | ✅        |
| Validate metadata for source-amazon-ads                        | ✅        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ✅        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/amazondisplay/1696370538/ab3c48b5166985b255f0ea99f64a2c018311e59f/source-amazon-ads/3.4.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ab3c48b5166985b255f0ea99f64a2c018311e59f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-amazon-ads test report (commit [`2c68d65fdd`](https://github.com/airbytehq/airbyte/pull/27417/commits/2c68d65fdd6586d9f87038d2e21fb12cba4c0ab8)) - ❌

⏲️  Total pipeline duration: 01mn03s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Connector package install                                      | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                     | ❌        |
| Code format checks                                             | ✅        |
| Validate metadata for source-amazon-ads                        | ✅        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ✅        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/amazondisplay/1696371596/2c68d65fdd6586d9f87038d2e21fb12cba4c0ab8/source-amazon-ads/3.4.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:2c68d65fdd6586d9f87038d2e21fb12cba4c0ab8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-amazon-ads test report (commit [`72bbc3af7b`](https://github.com/airbytehq/airbyte/pull/27417/commits/72bbc3af7bfab1ab38e30afe120c172aefac4362)) - ❌

⏲️  Total pipeline duration: 01mn01s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Connector package install                                      | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                     | ❌        |
| Code format checks                                             | ✅        |
| Validate metadata for source-amazon-ads                        | ✅        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ✅        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/amazondisplay/1696374411/72bbc3af7bfab1ab38e30afe120c172aefac4362/source-amazon-ads/3.4.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:72bbc3af7bfab1ab38e30afe120c172aefac4362)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-amazon-ads test report (commit [`85ad5da3e2`](https://github.com/airbytehq/airbyte/pull/27417/commits/85ad5da3e21f6a30d437e4740561bb8a7b0db90b)) - ❌

⏲️  Total pipeline duration: 47.92s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Connector package install                                      | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                     | ❌        |
| Code format checks                                             | ✅        |
| Validate metadata for source-amazon-ads                        | ✅        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ✅        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/amazondisplay/1696375503/85ad5da3e21f6a30d437e4740561bb8a7b0db90b/source-amazon-ads/3.4.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:85ad5da3e21f6a30d437e4740561bb8a7b0db90b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-amazon-ads test report (commit [`cdf876cbe7`](https://github.com/airbytehq/airbyte/pull/27417/commits/cdf876cbe77d338b056cd4fe77ba8f2b2ae44170)) - ✅

⏲️  Total pipeline duration: 02mn25s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Connector package install                                      | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                     | ✅        |
| Acceptance tests                                               | ✅        |
| Code format checks                                             | ✅        |
| Validate metadata for source-amazon-ads                        | ✅        |
| Connector version semver check                                 | ✅        |
| Connector version increment check                              | ✅        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/amazondisplay/1696375681/cdf876cbe77d338b056cd4fe77ba8f2b2ae44170/source-amazon-ads/3.4.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:cdf876cbe77d338b056cd4fe77ba8f2b2ae44170)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-amazon-ads test report (commit [`0b4cf19b42`](https://github.com/airbytehq/airbyte/pull/27417/commits/0b4cf19b42bb4db4c120c95f665150189670b2c4)) - ❌

⏲️  Total pipeline duration: 37.59s 

| Step                                                              | Result   |
|:------------------------------------------------------------------|:---------|
| Connector package install                                         | ✅        |
| Build source-amazon-ads docker image for platform(s) linux/x86_64 | ❌        |
| Code format checks                                                | ❌        |
| Validate metadata for source-amazon-ads                           | ✅        |
| Connector version semver check                                    | ✅        |
| Connector version increment check                                 | ✅        |
| QA checks                                                         | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/amazondisplay/1696435326/0b4cf19b42bb4db4c120c95f665150189670b2c4/source-amazon-ads/3.4.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:0b4cf19b42bb4db4c120c95f665150189670b2c4)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-amazon-ads test report (commit [`f54621b531`](https://github.com/airbytehq/airbyte/pull/27417/commits/f54621b5317f0d40d094f3159a6399f745204125)) - ✅

⏲️  Total pipeline duration: 03mn03s 

| Step                                                              | Result   |
|:------------------------------------------------------------------|:---------|
| Connector package install                                         | ✅        |
| Build source-amazon-ads docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                        | ✅        |
| Acceptance tests                                                  | ✅        |
| Code format checks                                                | ✅        |
| Validate metadata for source-amazon-ads                           | ✅        |
| Connector version semver check                                    | ✅        |
| Connector version increment check                                 | ✅        |
| QA checks                                                         | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/amazondisplay/1696631470/f54621b5317f0d40d094f3159a6399f745204125/source-amazon-ads/3.4.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f54621b5317f0d40d094f3159a6399f745204125)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Pull request closed without merging**
