### PR TITLE
Add additional destination-bigquery datacenters

### LINKED ISSUE #25116: BiqQuery destination missing datacenter
From [slack thread](https://airbytehq-team.slack.com/archives/C03GD9SV36E/p1681306654080369)

`europe-west9` is missing!

### PR DESCRIPTION
**Pull request by evantahler**
Add missing Datacenters from https://cloud.google.com/bigquery/docs/locations

Closes https://github.com/airbytehq/airbyte/issues/25116

### CODE REVIEW

**Comment by evantahler** [comment]
Question for the @airbytehq/destinations team when publishing: I think I need to publish 3 connectors here: `destination-bigquery`, `destination-bigquery-strict-encrypt`, and `destination-bigquery-denormalized`.  Did I miss any?

**Review by jbfbell — APPROVED** [review]

**Review by edgao — APPROVED** [review]
I _think_ normalization accepts this transparently, but that might be worth testing.

transform_config just passes the string into dbt (https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/normalization/transform_config/transform.py#L157)

and dbt doesn't seem to do any additional validation https://github.com/dbt-labs/dbt-core/pull/1151/files

**Comment by evantahler** [comment]
ummmmm `You're trying to push a version that was already released (airbyte/destination-bigquery:1.2.20). Make sure you bump it up.`. Any tips?

**Comment by edgao** [comment]
something spooky is happening.... https://hub.docker.com/r/airbyte/destination-bigquery/tags says the newest tag is `linux-amd64-1.2.20` (rather than the previous tag `1.2.19`). And certainly the timing _looks_ like it got pushed from your `/publish` run (i.e. it was pushed 40 minutes ago)

maybe related to @alafanechere 's dagger work...? but that's just a wild guess

**Comment by evantahler** [comment]
/publish connector=connectors/destination-bigquery-denormalized

**Comment by alafanechere** [comment]
> maybe related to @alafanechere 's dagger work...? but that's just a wild guess

@edgao my pipelines are not yet publishing anything to dockerhub :)

**Pull request merged**
