### PR TITLE
13541 Fixed integration tests source-db2 Mac OS

### LINKED ISSUE #13541: Fix integration tests source-db2 Mac OS
After updating testcontainers lib to 1.17.1 version integration tests failed for Mac OS with next error:

```
2022-06-03 12:44:45 source > 2022-06-03 12:44:45 ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.
2022-06-03 12:44:45 source > java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30002ms.
```

### PR DESCRIPTION
**Pull request by suhomud**
## What
Fixed failed integration tests for Mac OS

### CODE REVIEW

**Comment by suhomud** [comment]
The tests retailed to mac os was fixed. There are some fails with incremental testing but it's separate [issue](https://github.com/airbytehq/airbyte/issues/14144)

**Review by alexandr-shegeda — APPROVED** [review]
LGTM

**Pull request merged**
