### PR TITLE
feat(docs): update metric icon

### PR DESCRIPTION
**Pull request by bnchrch**
## What
Updates the metrics icon to show all possible levels

### CODE REVIEW

**Comment by bnchrch** [comment]
* **#39449** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/39449?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @bnchrch and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by bnchrch — COMMENTED** [review]
/approve-and-merge reason="docs icon update"

**Comment by octavia-approvington** [comment]
It's time <br/> fine lets go

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
