### PR TITLE
Airbyte OSS to Airbyte Open Source

### PR DESCRIPTION
**Pull request by nehanawar025**
Documentation: Change all instances of Airbyte OSS to Airbyte Open Source #15483

Made changes to Airbyte 'docs' folder--> changed all instances of Airbyte OSS to Airbyte Open Source.

### CODE REVIEW

**Review by tuliren — CHANGES_REQUESTED** [review]
Thank you for submitting a PR!

However, this PR has too many irrelevant changes:
- Lots of files are wrongly deleted.
- Many files have their mode changed from 755 to 644, which are unnecessary.

Please revert those irrelevant changes first.

**Comment by Amruta-Ranade** [comment]
Thanks for the review, @tuliren !!

@nehanawar025 As explained in the issue, please update only the contents of the docs folder. It might be easier to close this PR and open a new one.

**Comment by sherifnada** [comment]
assigning @Amruta-Ranade as the reviewer since it's a docs ticket

**Comment by Amruta-Ranade** [comment]
Closing this PR due to lack of activity

**Pull request closed without merging**
