### PR TITLE
feat(registry): add cdk version

### PR DESCRIPTION
**Pull request by bnchrch**
## What
Adds the cdk version for python connectors to the regisry

closes https://github.com/airbytehq/airbyte-internal-issues/issues/7462

### CODE REVIEW

**Comment by bnchrch** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/37809?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#37809** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/37809?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#37804** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/37804?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#37803** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/37803?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#37802** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/37802?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @bnchrch and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alafanechere — CHANGES_REQUESTED** [review]
If this is to power docs I'd  appreciate a dedicated `docs` field or a `cdk_version` top level field.
I'm concerned about introducing a `dependencies` field which just has the CDK ATM. I'd prefer `dependencies` to contain all dependencies, and find a language agnostic way of expressing them. 
So I'd be fine with both or either one of these approaches:
* Add all connectors dependencies to `dependencies` (basically copying the information available in [these files](https://storage.googleapis.com/prod-airbyte-cloud-connector-metadata-service/connector_dependencies/source-airtable/4.2.0/dependencies.json)
* Add a `doc` specific field to the registry entry which would show the CDK version (after searching it from the `dependencies` field or directly from `dependencies.json`).

**Comment by bnchrch** [comment]
Fair point!

What are your thoughts on cdk_version as a top level field?

or moving `cdk_version` under `generated`?

**Comment by alafanechere** [comment]
> Fair point!
> 
> What are your thoughts on cdk_version as a top level field?
> 
> or moving `cdk_version` under `generated`?

Happy to move `cdk_version` to a top level field and find a way to tell if it's the python or java cdk version.
Could be two, mutually exclusive, top level fields: `python_cdk_version`, `java_cdk_version`

**Comment by bnchrch** [comment]
Im thinking we avoid adding `cdk_version` to the top level of the registry for the following reasons:

1. Not all connectors will have a CDK version
1. If we keep adding info like this to the top level it will get messy

So I wanted to ask you is there a top level field we could use to contain this that:
1. Would make sense to put `cdk_version` under
1. Would not be prescriptive to where its used/consumed? (This was why I wasnt immediately happy with `docs`)
1. We likely would put future fields under

?

**Review by alafanechere — APPROVED** [review]

**Comment by bnchrch** [comment]
### Merge activity

* **May 9, 10:18 AM EDT**: @bnchrch started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/airbytehq/airbyte/37809).

**Pull request merged**
