### PR TITLE
✨ Destinations V2: open up early access for BigQuery via spec toggle

### LINKED ISSUE #28634: Open up V2 Beta to all users!
Maybe it is time to mainline the option to try our destinations v2 and loose the dev images.

The main goal of an early release / beta is to de-risk the main rollout: if we stay on this trajectory, would we be comfortable making Destinations V2 the default without a transition period?

PROS
* [GTM] anyone can goin the beta! more testers! more volume! more sources!
* [GTM] easier onboarding for beta customers
* [GTM] can start rolling out documentation for Destinations V2 more publicly
* [ENG] easier to share newer 'dev' images / update

CONS
* users might opt in early and be confused (alex - we can mitigate this with documentation)

### PR DESCRIPTION
**Pull request by cynthiaxyin**
closes #28634

### CODE REVIEW

**Comment by cynthiaxyin** [comment]
Waiting for https://docs.airbyte.com/understanding-airbyte/typing-deduping to go live. cc @Hesperide

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`2b5b5190fc`](https://github.com/airbytehq/airbyte/pull/28894/commits/2b5b5190fcec66507a4f235748e28e2cc3493295)) - ✅

⏲️  Total pipeline duration: 04mn45s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cynthia_dest-v2-open-beta/1690852943/2b5b5190fcec66507a4f235748e28e2cc3493295/destination-bigquery/1.7.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery-denormalized test report (commit [`2b5b5190fc`](https://github.com/airbytehq/airbyte/pull/28894/commits/2b5b5190fcec66507a4f235748e28e2cc3493295)) - ❌

⏲️  Total pipeline duration: 04mn09s 

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml | ✅        |
| Connector version semver check                                                           | ✅        |
| QA checks                                                                                | ✅        |
| Build connector tar                                                                      | ✅        |
| Build destination-bigquery-denormalized docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cynthia_dest-v2-open-beta/1690852943/2b5b5190fcec66507a4f235748e28e2cc3493295/destination-bigquery-denormalized/1.5.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery-denormalized test report (commit [`2b5b5190fc`](https://github.com/airbytehq/airbyte/pull/28894/commits/2b5b5190fcec66507a4f235748e28e2cc3493295)) - ✅

⏲️  Total pipeline duration: 24mn31s 

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ✅        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-bigquery-denormalized docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery-denormalized:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cynthia_dest-v2-open-beta/1690853623/2b5b5190fcec66507a4f235748e28e2cc3493295/destination-bigquery-denormalized/1.5.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`2b5b5190fc`](https://github.com/airbytehq/airbyte/pull/28894/commits/2b5b5190fcec66507a4f235748e28e2cc3493295)) - ❌

⏲️  Total pipeline duration: 37mn54s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cynthia_dest-v2-open-beta/1690853623/2b5b5190fcec66507a4f235748e28e2cc3493295/destination-bigquery/1.7.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`2b5b5190fc`](https://github.com/airbytehq/airbyte/pull/28894/commits/2b5b5190fcec66507a4f235748e28e2cc3493295)) - ❌

⏲️  Total pipeline duration: 39mn53s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cynthia_dest-v2-open-beta/1690873279/2b5b5190fcec66507a4f235748e28e2cc3493295/destination-bigquery/1.7.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery-denormalized test report (commit [`2b5b5190fc`](https://github.com/airbytehq/airbyte/pull/28894/commits/2b5b5190fcec66507a4f235748e28e2cc3493295)) - ✅

⏲️  Total pipeline duration: 02mn37s 

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ✅        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-bigquery-denormalized docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery-denormalized:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cynthia_dest-v2-open-beta/1690873279/2b5b5190fcec66507a4f235748e28e2cc3493295/destination-bigquery-denormalized/1.5.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

**Review by edgao — APPROVED** [review]

**Comment by octavia-approvington** [comment]
Send it! <br/> rocket socks

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
