### PR TITLE
Destination Google Sheets: Add instructions for Airbyte OSS

### PR DESCRIPTION
**Pull request by andreaslillebo**
## What
Adds instructions for how to use the Google Sheets destination with the self-hosted version of Airbyte.

## How
The integration already supports manually adding the oauth login credentials. However, it is not obvious how one would go about doing this.

The user experience could be further improved by only prompting the user for a client id, client secret and spreadsheet URL, and then show a sign-in with Google-button which would replace the oauth playground steps. This appears however to be somewhat complex and beyond what I'm able to contribute for the time being.

## 🚨 User Impact 🚨
No breaking changes or impact for existing users.

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Review by marcosmarxm — APPROVED** [review]
Thanks @andreaslillebo. This week the codebase is freeze to merge so I'll handle the merge process next week.

**Comment by marcosmarxm** [comment]
@andreaslillebo can you solve the conflict exists today?

**Comment by andreaslillebo** [comment]
> @andreaslillebo can you solve the conflict exists today?

@marcosmarxm, I've resolved the conflict. Please let me know if any other changes are required.

**Comment by octavia-approvington** [comment]
This code is at peace with itself <br/> imagine karate kid approving

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
