### PR TITLE
Destinations V2: move create raw tables earlier

### LINKED ISSUE #27921: Destinations V2: Bugs creating initial tables within custom namespaces + standard inserts
To reproduce:

1. Have a destination with a custom namespace (e.g. `v2' in this example) [Screenshot 2023-07-03 at 8.53.20 AM.png](https://images.zenhubusercontent.com/625848c232857a5abeb89721/8e3434ad-c704-467a-b2da-68bac8704e8c) 
2. Empty or remove the destination schema and the `airbyte` schema
2. run a v2 sync
3. see errors like: `com.google.cloud.bigquery.BigQueryException: Not found: Table destinationsv2-perf-testing:airbyte.v2_purchases was not found in location US`!

### PR DESCRIPTION
**Pull request by cynthiaxyin**
closes #27921

BigQuery was complaining about raw tables not being found for sources with many rows (ex: source faker with 10M rows) when loaded via standard inserts. Moved raw table creation from consumer close to consumer startTracked.

Tested on localhost with 10M row faker source and shared test workspace.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`2cc4353848`](https://github.com/airbytehq/airbyte/pull/28255/commits/2cc43538482850dcc59f04c9732e6e74531dfefe)) - ✅

⏲️  Total pipeline duration: 22.08s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cynthia_create_raw_tables/1689205705/2cc43538482850dcc59f04c9732e6e74531dfefe/destination-bigquery/1.5.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Review by evantahler — APPROVED** [review]
👍 make the table at the beginning of the stream... that works for me!

**Comment by evantahler** [comment]
A philosophical question for the Destinations team: Should branching logic like this be in Java or SQL?  e.g. we first do a read to see if a table exists, and then if it doesn't we create the table.  Alternatively, we could always issue a `CREATE TABLE IF NOT EXISTS`.  

Which way is better and why?

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery-denormalized test report (commit [`2cc4353848`](https://github.com/airbytehq/airbyte/pull/28255/commits/2cc43538482850dcc59f04c9732e6e74531dfefe)) - ❌

⏲️  Total pipeline duration: 21mn16s 

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ✅        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-bigquery-denormalized docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery-denormalized:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cynthia_create_raw_tables/1689205705/2cc43538482850dcc59f04c9732e6e74531dfefe/destination-bigquery-denormalized/1.5.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`2cc4353848`](https://github.com/airbytehq/airbyte/pull/28255/commits/2cc43538482850dcc59f04c9732e6e74531dfefe)) - ✅

⏲️  Total pipeline duration: 23.30s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cynthia_create_raw_tables/1689207092/2cc43538482850dcc59f04c9732e6e74531dfefe/destination-bigquery/1.5.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery-denormalized test report (commit [`2cc4353848`](https://github.com/airbytehq/airbyte/pull/28255/commits/2cc43538482850dcc59f04c9732e6e74531dfefe)) - ✅

⏲️  Total pipeline duration: 17mn44s 

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ✅        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-bigquery-denormalized docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery-denormalized:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cynthia_create_raw_tables/1689207092/2cc43538482850dcc59f04c9732e6e74531dfefe/destination-bigquery-denormalized/1.5.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery-denormalized test report (commit [`d0056c1007`](https://github.com/airbytehq/airbyte/pull/28255/commits/d0056c100736e10dce5571050d6ccd209b7d4298)) - ✅

⏲️  Total pipeline duration: 19mn04s 

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ✅        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-bigquery-denormalized docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery-denormalized:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cynthia_create_raw_tables/1689269074/d0056c100736e10dce5571050d6ccd209b7d4298/destination-bigquery-denormalized/1.5.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`d0056c1007`](https://github.com/airbytehq/airbyte/pull/28255/commits/d0056c100736e10dce5571050d6ccd209b7d4298)) - ❌

⏲️  Total pipeline duration: 29mn27s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cynthia_create_raw_tables/1689269074/d0056c100736e10dce5571050d6ccd209b7d4298/destination-bigquery/1.5.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Review by edgao — APPROVED** [review]
:shipit:

I think java is basically unavoidable - e.g. once we start building migration stuff, we'll (probably?) want more complex logic like `if (!findExistingTable().hasColumn("_airbyte_raw_id")) { doSomething() }`. That would be pretty annoying in pure sql

e.g. BigQuerySqlGenerator.alterTable, which depends on us querying the db + use java to generate a sql statement

though... whether we prefer `bigquery.createTable` vs `bigquery.execute("create table...")` is also a question 🤔

**Comment by cynthiaxyin** [comment]
The failing test was:
```
#36 292.8 BigQueryGcsTypingDedupingTest > incrementalDedupIdenticalName() FAILED
#36 292.8     io.airbyte.workers.exception.TestHarnessException: Destination process exit with code 1. This warning is normal if the job was cancelled.
#36 292.8         at app//io.airbyte.workers.internal.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:133)
#36 292.8         at app//io.airbyte.integrations.base.destination.typing_deduping.BaseTypingDedupingTest.runSync(BaseTypingDedupingTest.java:566)
#36 292.8         at app//io.airbyte.integrations.base.destination.typing_deduping.BaseTypingDedupingTest.incrementalDedupIdenticalName(BaseTypingDedupingTest.java:427)
```

I ran it locally and it was fine so I'm going to merge.

**Pull request merged**
