### PR TITLE
source-upstox contribution from bala-ceg

### LINKED ISSUE #48058: [New-Connector request] upstox
### Topic

New Topic

### Relevant information

Topic
This is a suggestion to create a connector for Uptox using the UI Connector Builder. The website for the connector is https://upstox.com/developer/api-documentation/get-market-holidays

Relevant information
No response

### PR DESCRIPTION
**Pull request by bala-ceg**
## What

This PR adds a new connector for source upstox (source-upstox).

Contributor-provided connector description:

Upstox is a leading online brokerage platform in India that offers a seamless way to trade and invest in stocks, commodities, currencies, and mutual funds. Known for its user-friendly interface and affordable pricing, Upstox provides advanced charting tools, real-time market data, and analytics to help investors and traders make informed decisions.
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `to_date` | `string` | to_date.  |  |
| `interval` | `string` | interval.  |  |
| `from_date` | `string` | from_date.  |  |
| `instrumentKey` | `array` | instrumentKey.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| marketholidays | date | No pagination | ✅ |  ❌  |
| historicalcandle |  | No pagination | ✅ |  ❌  |
| intradaycandle |  | No pagination | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by marcosmarxm** [comment]
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

**Comment by bala-ceg** [comment]
@marcosmarxm getting this error while updating the connector using webui
Screenshot 2024-11-07 at 9 04 13 PM

**Comment by bala-ceg** [comment]
Hi @marcosmarxm,
Updated this connector with icon.svg and the endpoints i use don't have pagination

**Comment by marcosmarxm** [comment]
After some analysis it doesn't look the connector add much to the catalog as it doesn't allow run incremental syncs and has only 3 endpoints. Thanks for the proposal @bala-ceg but I decided to declined it.

**Pull request closed without merging**
