### PR TITLE
🐛 Source Intercom: Fix "updated_at" data type

### PR DESCRIPTION
**Pull request by ReptilianBrain**
The Intercom API send a integer for the "updated_at" field in the companies endpoint. Which cause issue later on when dbt tries to create the table.

## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated 
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [x] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks @ReptilianBrain could you share the logs from the failures?

**Comment by ReptilianBrain** [comment]
here's the log I recveived from airbyte.

`2021-09-15 14:25:54 INFO () LineGobbler(voidCall):85 - Completed with 2 errors and 0 warnings:
2021-09-15 14:25:54 INFO () LineGobbler(voidCall):85 - 
2021-09-15 14:25:54 INFO () LineGobbler(voidCall):85 - Database Error in model intercom__company_attributes (models/generated/airbyte_tables/dev_sandbox/intercom__company_attributes.sql)
2021-09-15 14:25:54 INFO () LineGobbler(voidCall):85 -   Invalid data
2021-09-15 14:25:54 INFO () LineGobbler(voidCall):85 -   DETAIL:  
2021-09-15 14:25:54 INFO () LineGobbler(voidCall):85 -     -----------------------------------------------
2021-09-15 14:25:54 INFO () LineGobbler(voidCall):85 -     error:  Invalid data
2021-09-15 14:25:54 INFO () LineGobbler(voidCall):85 -     code:      8001
2021-09-15 14:25:54 INFO () LineGobbler(voidCall):85 -     context:   Invalid format or data given: 1507831043
2021-09-15 14:25:54 INFO () LineGobbler(voidCall):85 -     query:     132707242
2021-09-15 14:25:54 INFO () LineGobbler(voidCall):85 -     location:  funcs_timestamp.cpp:274
2021-09-15 14:25:54 INFO () LineGobbler(voidCall):85 -     process:   query3_46_132707242 [pid=2261]
2021-09-15 14:25:54 INFO () LineGobbler(voidCall):85 -     -----------------------------------------------
2021-09-15 14:25:54 INFO () LineGobbler(voidCall):85 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/dev_sandbox/intercom__company_attributes.sql`

also here's a response from the intercom api if it can help:

`{
  "type": "company",
  "company_id": "<REDACTED>",
  "id": "<REDACTED>",
  "app_id": "<REDACTED>",
  "name": "<REDACTED>",
  "created_at": 1507897642,
  "updated_at": 1631306673,
  "last_request_at": 1631306303,
  "monthly_spend": 0,
  "session_count": 0,
  "user_count": <REDACTED>,
  "tags": {
    "type": "tag.list",
    "tags": []
  },
  "segments": {
    "type": "segment.list",
    "segments": []
  },
  "plan": {},
  "custom_attributes": {}
}`

**Comment by prasrvenkat** [comment]
@marcosmarxm  FYI, this could be for all intercom streams having `updated_at` btw. We had similar problem with some other streams, we are not using `dbt` so we handle it ourselves in our flow downstream (pubsub destination -> our services). 

This PR https://github.com/airbytehq/airbyte/pull/5908 changed most such `data-time` references when it was coming as integer from API, but it did not touch `updated_at`. I am not sure if its because it's used as a cursor and changing would impact incremental sync in someway or just missed.

**Comment by marcosmarxm** [comment]
Hi @ReptilianBrain we're going to review this later monday! thanks for the contribution again.

**Review by lazebnyi — APPROVED** [review]

**Pull request merged**
