### PR TITLE
Revert "Update to Micronaut 3.8.0 (#20716)"

### PR DESCRIPTION
**Pull request by gosusnp**
This reverts commit a28f93747ffb7c8ad9e30a4a90ceada9d0d7dc0e and 8d658b76a58ebf59afa1bee3f09935563cc22800

## What

The previous change introduced some dependencies conflict, reverting while we investigate.

### CODE REVIEW

**Comment by benmoriceau** [comment]
This skips the build 🤦

**Comment by gosusnp** [comment]
@benmoriceau, https://github.com/airbytehq/airbyte/pull/21040 fixes this.
Locally, this solves one issue, I think we may have more in master currently.

**Comment by benmoriceau** [comment]
@gosusnp Could we try to update the file`gradle.yml` by adding the dep.toml in the line 68

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Pull request merged**
