### PR TITLE
:tada: New Source: AppFollow Service

### PR DESCRIPTION
**Pull request by dtt101**
## What
This introduces a new source connector for the [Appfollow](https://appfollow.io) service.

It allows users to gather mobile application data from multiple app stores.

This initial version contains support for one API endpoint: `ratings` as documented [here](https://appfollow.docs.apiary.io/#reference/0/9.-ratings)

## How
The connector exposes a number of config params, api secret, client ID, app store (i,e play / apple) ID and country and reads ratings data from the source API

## 🚨 User Impact 🚨
There are no breaking changes - the PR should provide a new connector option for airbyte users

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

```
Test session starts (platform: darwin, Python 3.9.12, pytest 6.2.5, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /Users/vs/projects/data/airbyte, configfile: pytest.ini
plugins: requests-mock-1.9.3, sugar-0.9.4, mock-3.6.1, timeout-1.4.2
collecting ...
 airbyte-integrations/connectors/source-appfollow/unit_tests/test_source.py::test_check_connection ✓  9% ▉
 airbyte-integrations/connectors/source-appfollow/unit_tests/test_source.py::test_streams ✓          18% █▊
 airbyte-integrations/connectors/source-appfollow/unit_tests/test_streams.py::test_request_params ✓  27% ██▊
 airbyte-integrations/connectors/source-appfollow/unit_tests/test_streams.py::test_parse_response ✓  36% ███▋
 airbyte-integrations/connectors/source-appfollow/unit_tests/test_streams.py::test_request_headers ✓ 45% ████▋
 airbyte-integrations/connectors/source-appfollow/unit_tests/test_streams.py::test_http_method ✓     55% █████▌
 airbyte-integrations/connectors/source-appfollow/unit_tests/test_streams.py::test_should_retry[HTTPStatus.OK-False] ✓64% ██████▍
 airbyte-integrations/connectors/source-appfollow/unit_tests/test_streams.py::test_should_retry[HTTPStatus.BAD_REQUEST-False] ✓73% ███████▍
 airbyte-integrations/connectors/source-appfollow/unit_tests/test_streams.py::test_should_retry[HTTPStatus.TOO_MANY_REQUESTS-True] ✓82% ████████▎
 airbyte-integrations/connectors/source-appfollow/unit_tests/test_streams.py::test_should_retry[HTTPStatus.INTERNAL_SERVER_ERROR-True] ✓91% █████████▏
 airbyte-integrations/connectors/source-appfollow/unit_tests/test_streams.py::test_backoff_time ✓   100% ██████████
================================================ warnings summary =================================================
airbyte-integrations/connectors/source-appfollow/unit_tests/test_source.py::test_check_connection
airbyte-integrations/connectors/source-appfollow/unit_tests/test_source.py::test_check_connection
  /Users/vs/projects/data/airbyte/airbyte-integrations/connectors/source-appfollow/.venv/lib/python3.9/site-packages/requests/auth.py:36: DeprecationWarning: Non-string usernames will no longer be supported in Requests 3.0.0. Please convert the object you've passed in (<MagicMock name='mock.__getitem__()' id='4425779328'>) to a string or bytes object in the near future to avoid problems.
    warnings.warn(

airbyte-integrations/connectors/source-appfollow/unit_tests/test_source.py::test_check_connection
airbyte-integrations/connectors/source-appfollow/unit_tests/test_source.py::test_check_connection
  /Users/vs/projects/data/airbyte/airbyte-integrations/connectors/source-appfollow/.venv/lib/python3.9/site-packages/requests/auth.py:46: DeprecationWarning: Non-string passwords will no longer be supported in Requests 3.0.0. Please convert the object you've passed in (<class 'unittest.mock.MagicMock'>) to a string or bytes object in the near future to avoid problems.
    warnings.warn(

airbyte-integrations/connectors/source-appfollow/unit_tests/test_source.py::test_streams
  /Users/vs/projects/data/airbyte/airbyte-integrations/connectors/source-appfollow/source_appfollow/source.py:111: DeprecationWarning: Call to deprecated class TokenAuthenticator. (Use airbyte_cdk.sources.streams.http.requests_native_auth.TokenAuthenticator instead) -- Deprecated since version 0.1.20.
    auth = BasicHttpAuthenticator(username=config["api_secret"], password=config["api_secret"])

airbyte-integrations/connectors/source-appfollow/unit_tests/test_source.py::test_streams
airbyte-integrations/connectors/source-appfollow/unit_tests/test_source.py::test_streams
  /Users/vs/projects/data/airbyte/airbyte-integrations/connectors/source-appfollow/.venv/lib/python3.9/site-packages/deprecated/classic.py:173: DeprecationWarning: Call to deprecated class HttpAuthenticator. (Use requests.auth.AuthBase instead) -- Deprecated since version 0.1.20.
    return old_new1(cls, *args, **kwargs)

airbyte-integrations/connectors/source-appfollow/unit_tests/test_source.py::test_streams
  /Users/vs/projects/data/airbyte/airbyte-integrations/connectors/source-appfollow/.venv/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py:41: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    self._authenticator: HttpAuthenticator = NoAuth()

-- Docs: https://docs.pytest.org/en/stable/warnings.html

Results (0.37s):
      11 passed
```

</details>

<details><summary><strong>Integration</strong></summary>

```
Test session starts (platform: darwin, Python 3.9.12, pytest 6.2.5, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /Users/vs/projects/data/airbyte, configfile: pytest.ini
plugins: requests-mock-1.9.3, sugar-0.9.4, mock-3.6.1, timeout-1.4.2
collecting ...

Results (0.01s):
```

</details>

<details><summary><strong>Acceptance</strong></summary>

```
Test session starts (platform: darwin, Python 3.9.12, pytest 6.2.5, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /Users/vs/projects/data/airbyte, configfile: pytest.ini
plugins: requests-mock-1.9.3, sugar-0.9.4, mock-3.6.1, timeout-1.4.2
collecting ...
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_config_match_spec[inputs0] ✓5% ▌
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_match_expected[inputs0] ✓10% ▉
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_docker_env[inputs0] ✓14% █▌
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_oneof_usage[inputs0] ✓19% █▉
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_required[inputs0] ✓24% ██▍
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_optional[inputs0] ✓29% ██▉
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_has_secret[inputs0] ✓33% ███▍
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_secret_never_in_the_output[inputs0] ✓38% ███▊
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_defined_refs_exist_in_json_spec_file[inputs0] ✓43% ████▍
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestSpec.test_oauth_flow_parameters[inputs0] ✓48% ████▊
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestConnection.test_check[inputs0] ✓52% █████▎
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestConnection.test_check[inputs1] ✓57% █████▊
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_discover[inputs0] ✓62% ██████▎
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_cursors_exist_in_schema[inputs0] ✓67% ██████▋
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_refs_exist_in_schema[inputs0] ✓71% ███████▎
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_keyword_exist_in_schema[inputs0-allOf] ✓76% ███████▋
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_defined_keyword_exist_in_schema[inputs0-not] ✓81% ████████▏
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestDiscovery.test_primary_keys_exist_in_schema[inputs0] ✓86% ████████▋
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestBasicRead.test_read[inputs0] ✓90% █████████▏{"type": "LOG", "log": {"level": "ERROR", "message": "Docker container was failed, code 1, error:\n{\"type\": \"TRACE\", \"trace\": {\"type\": \"ERROR\", \"emitted_at\": 1657035716483.1519, \"error\": {\"message\": \"Something went wrong in the connector. See the logs for more details.\", \"internal_message\": \"2 validation errors for ConfiguredAirbyteCatalog\\nstreams -> 0 -> sync_mode\\n  value is not a valid enumeration member; permitted: 'full_refresh', 'incremental' (type=type_error.enum; enum_values=[<SyncMode.full_refresh: 'full_refresh'>, <SyncMode.incremental: 'incremental'>])\\nstreams -> 0 -> destination_sync_mode\\n  value is not a valid enumeration member; permitted: 'append', 'overwrite', 'append_dedup' (type=type_error.enum; enum_values=[<DestinationSyncMode.append: 'append'>, <DestinationSyncMode.overwrite: 'overwrite'>, <DestinationSyncMode.append_dedup: 'append_dedup'>])\", \"stack_trace\": \"Traceback (most recent call last):\\n  File \\\"/airbyte/integration_code/main.py\\\", line 13, in <module>\\n    launch(source, sys.argv[1:])\\n  File \\\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\\\", line 118, in launch\\n    for message in source_entrypoint.run(parsed_args):\\n  File \\\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\\\", line 106, in run\\n    config_catalog = self.source.read_catalog(parsed_args.catalog)\\n  File \\\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/source.py\\\", line 28, in read_catalog\\n    return ConfiguredAirbyteCatalog.parse_obj(self.read_config(catalog_path))\\n  File \\\"/usr/local/lib/python3.9/site-packages/pydantic/main.py\\\", line 521, in parse_obj\\n    return cls(**obj)\\n  File \\\"/usr/local/lib/python3.9/site-packages/pydantic/main.py\\\", line 341, in __init__\\n    raise validation_error\\npydantic.error_wrappers.ValidationError: 2 validation errors for ConfiguredAirbyteCatalog\\nstreams -> 0 -> sync_mode\\n  value is not a valid enumeration member; permitted: 'full_refresh', 'incremental' (type=type_error.enum; enum_values=[<SyncMode.full_refresh: 'full_refresh'>, <SyncMode.incremental: 'incremental'>])\\nstreams -> 0 -> destination_sync_mode\\n  value is not a valid enumeration member; permitted: 'append', 'overwrite', 'append_dedup' (type=type_error.enum; enum_values=[<DestinationSyncMode.append: 'append'>, <DestinationSyncMode.overwrite: 'overwrite'>, <DestinationSyncMode.append_dedup: 'append_dedup'>])\\n\", \"failure_type\": \"system_error\"}}}\n"}}

 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py::TestBasicRead.test_airbyte_trace_message_on_failure[inputs0] ✓95% █████████▌
 airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_full_refresh.py::TestFullRefresh.test_sequential_reads[inputs0] ✓100% ██████████
{"type": "LOG", "log": {"level": "INFO", "message": "/Users/vs/projects/data/airbyte/airbyte-integrations/connectors/source-appfollow - SAT run - a8760e28aefc5352d7d6b21038ba0dee097d5983 - PASSED"}}

================================================ warnings summary =================================================
airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py: 17 warnings
airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_full_refresh.py: 1 warning
  /Users/vs/projects/data/airbyte/airbyte-integrations/connectors/source-appfollow/.venv/lib/python3.9/site-packages/docker/utils/utils.py:52: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    s1 = StrictVersion(v1)

airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py: 17 warnings
airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_full_refresh.py: 1 warning
  /Users/vs/projects/data/airbyte/airbyte-integrations/connectors/source-appfollow/.venv/lib/python3.9/site-packages/docker/utils/utils.py:53: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    s2 = StrictVersion(v2)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================================= short test summary info =============================================
SKIPPED [1] ../../bases/source-acceptance-test/source_acceptance_test/plugin.py:56: Skipping TestIncremental.test_two_sequential_reads because not found in the config

Results (19.74s):
      21 passed
```

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks for the contributin @dtt101 ! Soon someone from the team will review it

**Comment by dtt101** [comment]
Thanks @marcosmarxm - appreciated - the first one I have written so advice is definitely welcome!

**Comment by igrankova** [comment]
@dtt101 
Hi, David,
We asked the Appfollow support to give us the sandbox account and they want to know who requested the Appfollow connector? I think they want to know is it their customer. Can you share some information about this contribution?

**Comment by dtt101** [comment]
@igrankova - awesome - is there an email address I could use to send the customer details to - I can send from my work address!

**Comment by igrankova** [comment]
@dtt101 
David, thank you very much. 
Use this email olga@appfollow.io
I've informed Olga about your email.

**Comment by dtt101** [comment]
@igrankova - email sent with confirmation we are a customer

**Comment by igrankova** [comment]
@dtt101 Thank you very much!
We received the sandbox with API access

**Comment by marcosmarxm** [comment]
@harshithmullapudi you can review and publish without the sandbox account.

**Comment by dtt101** [comment]
@harshithmullapudi - thanks for the commits!
For the failed publish - is there a way I can run this process locally to debug? Or do you have any suggestions on where I could start looking for the failed test in the workflow?

**Comment by dtt101** [comment]
@harshithmullapudi - thanks for running the publish - bumping the version has resolved the failing test.
The [exception](https://github.com/airbytehq/airbyte/runs/7816816713?check_suite_focus=true#step:14:3193) raised by the publish workflow now is `INTERNALERROR>   Config expected dict not NoneType (type=type_error)`  

This looks like because the acceptance test config is missing - is this because you commented out, or is there some other config I need to add?

**Comment by dtt101** [comment]
Ok - great it is building and publishing! I am not sure of the next step (apols if I am being dense). 

Would welcome any suggestions - thanks for the time so far.

**Comment by harshithmullapudi** [comment]
Hey @dtt101 you can go ahead and use the connector

**Comment by wallies** [comment]
@dtt101 first thanks for building this connector. Did you manage to get this working. All i get is json in the ratings column no matter what destination I try.

**Comment by dtt101** [comment]
@wallies - yes - rating is the only endpoint it supports (or do you mean you get an error in the expected response)?

**Pull request merged**
