### PR TITLE
Fix for nullable top-level schemas

### PR DESCRIPTION
**Pull request by johnny-schmidt**
## What

Bugfix for https://github.com/airbytehq/oncall/issues/6269

### CODE REVIEW

**Review by evantahler — APPROVED** [review]
👍 
You'll need to bump the connector version & docs too

**Review by edgao — COMMENTED** [review]
blegh. if you have an easy way to test - what happens if the top-level schema is `type: [string, object]`? (we've seen that in the past also)

**Comment by johnny-schmidt** [comment]
> blegh. if you have an easy way to test - what happens if the top-level schema is `type: [string, object]`? (we've seen that in the past also)

@edgao we would not be able to handle that in avro anyway. What would the top-level string field be called? The field names come from the object properties.

**Pull request merged**
