### PR TITLE
Enable the Connector Builder server in the platform

### PR DESCRIPTION
**Pull request by lmossman**
## What
This PR enables the connector builder in the platform's docker-compose, and removes the mock data in the frontend so that the connector builder UI is actually making calls to the backend connector-builder-server.

### CODE REVIEW

**Comment by lmossman** [comment]
I thought that adding `airbyte-connector-builder-server` to these two places would ensure it is built as part of the platform and the image would therefore be useable in later github action steps:
https://github.com/airbytehq/airbyte/pull/19269/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R533
https://github.com/airbytehq/airbyte/blob/524e2744be3f50269960a7b1f65110452d54f48c/settings.gradle#L91

But, CI is still failing for the Octavia CLI And Frontend E2E test steps with [this error](https://github.com/airbytehq/airbyte/actions/runs/3438980390/jobs/5735754025#step:9:36):
```
Pulling airbyte-connector-builder-server (airbyte/connector-builder-server:dev)...
The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

pull access denied for airbyte/connector-builder-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
despite both having a step to build the platform right before that step: https://github.com/airbytehq/airbyte/blob/0ee55af0202abc2cf841fda2fe3573e9038aedfc/.github/workflows/gradle.yml#L434-L435

So I am confused why it is trying to pull a dev image, as it should have a locally-built dev image from that last step.

@sherifnada @girarda @brianjlai @davinchia any ideas why this is failing?

**Comment by girarda** [comment]
> any ideas why this is failing?

@lmossman I should've added a comment, but you'll need to uncomment this block https://github.com/airbytehq/airbyte/blob/master/docker-compose.build.yaml#L32-L38

**Comment by lmossman** [comment]
> > any ideas why this is failing?
> 
> @lmossman I should've added a comment, but you'll need to uncomment this block https://github.com/airbytehq/airbyte/blob/master/docker-compose.build.yaml#L32-L38

Argh I thought I had uncommented that, my bad. Thanks!

**Comment by lmossman** [comment]
> > any ideas why this is failing?
> 
> @lmossman I should've added a comment, but you'll need to uncomment this block https://github.com/airbytehq/airbyte/blob/master/docker-compose.build.yaml#L32-L38

@girarda I did uncomment that, so I don't think that is the issue: https://github.com/airbytehq/airbyte/pull/19269/files#diff-0ce8bef957945e9177ad1e2cff06c468a320d89d0b94ce35e25cca391e477a92R32-R38

**Comment by lmossman** [comment]
Something I noticed is that the other images seem to be running a task called `buildDockerImage`, but the connector-builder-server build.gradle does not have that task defined. Let me try adding that

**Comment by sherifnada** [comment]
@lmossman doesn't it have the `airbyteDocker` task?

**Review by girarda — APPROVED** [review]

**Pull request merged**
