### PR TITLE
source-mysql: bump debezium to 2.7.0.Final

### LINKED ISSUE #41282: [source-mysql] Possible wrong type conversion
@michel-tricot observed an issue reported on reddit:

https://www.reddit.com/r/dataengineering/comments/1dz1onq/weird_mysql_cdc_binlog_behavior/

### PR DESCRIPTION
**Pull request by postamar**
## What
Bumps debezium to latest version.

closes https://github.com/airbytehq/airbyte/issues/41282

## User Impact
Bug fixes.

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by rodireich — APPROVED** [review]

**Comment by theyueli** [comment]
hi @postamar, could we publish an image and test this on that particular workspace?

**Comment by postamar** [comment]
@theyueli shouldn't we trust our tests enough that if they are green, we're comfortable releasing this change? I may be wrong -- what is it we did recently with the other connectors who underwent a debezium minor version upgrades? I lost track

**Comment by rodireich** [comment]
I think we ran also a manual simple test to see that it doesn't explode out of the box - a smoke test

**Comment by theyueli** [comment]
> @theyueli shouldn't we trust our tests enough that if they are green, we're comfortable releasing this change? I may be wrong -- what is it we did recently with the other connectors who underwent a debezium minor version upgrades? I lost track

right, I just wondered whether the upgrade resolves that workspace's error with the new debezium so we can just be more confident to upgrade... 

yes, I did a smoke test on MySQL last time when I upgraded to 2.5.4. 

From @rodireich's investigation, here's another ticket that could be tested against:

https://github.com/airbytehq/airbyte/issues/41282

**Comment by postamar** [comment]
Looks like moving to 2.7 isn't as straightforward as I would have liked. These test failures are legit.

**Comment by evantahler** [comment]
From Enterprise WBR: We should stop working on this for now, and stick to our regularly scheduled roadmap work.  Fixing https://github.com/airbytehq/oncall/issues/5738 will be an option to consider for Q3A.

**Pull request closed without merging**
