### PR TITLE
Postgres file reader now assumes UTF8

### PR DESCRIPTION
**Pull request by evantahler**
This fixes a failing test, `:airbyte-integrations:bases:base-java:spotbugsMain`

So, 
bailey-computer1

but I think that assuming that all of our users/servers will be using a UTF8 is reasonable in 2022...

### CODE REVIEW

**Review by rodireich — APPROVED** [review]

**Comment by evantahler** [comment]
Hmm... @edgao I don't really get how my changes caused those compilation errors.  Any tips?

**Comment by edgao** [comment]
looks like master's PostgresSource is just broken, copied in the fix from another branch https://github.com/airbytehq/airbyte/pull/15317/files#diff-f14bc8e9216a505150004f54d41ca7aeeba9a9460fc4a660b11225dd7abb274f

**Comment by evantahler** [comment]
cool, cool... thanks for the fix!

**Comment by ryankfu** [comment]
Ed covered it already but if you go into the [failed Postgres Source integration test](https://github.com/airbytehq/airbyte/actions/runs/2871588185) and click on `Annotations > integration-test` you can see the error that there was an issue with `import com.google.common.collect.ImmutableMap.Builder;` was missing for posterity

It existed before in `PostgresSource.java` https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSource.java#L18 so not sure how it got removed

**Review by tuliren — APPROVED** [review]

**Comment by edgao** [comment]
tests are green; merging

**Comment by edgao** [comment]
(not going to publish, since I think this is actually default behavior - if anyone disagrees just LMK)

**Comment by evantahler** [comment]
Looks like mySQl has the same problem https://github.com/airbytehq/airbyte/pull/15709

**Pull request merged**
