### PR TITLE
🎉 New Source : Avni (Low Code Cdk)

### PR DESCRIPTION
**Pull request by avirajsingh7**
## What
*Describe what the change is solving*

AVNI is an open source platform for on field service and data collection. A three-level adjustable data structure given by Avni enables modelling of the services offered (or data collected). Setting up topics, enrolling subjects in programmes, and establishing encounters for enrollments/subjects are all possible with Avni.
For organizations using Avni having a native Airbyte connector to import data will allow for ingestion into their data warehouses and use of the data for analysis.

*It helps to add screenshots if it affects the frontend.*

doesn't effect the frontend

## How
*Describe the solution*

The current version of the connector provides for ingesting data through Airbyte from multiple streams . The implemented version of the connector will allow for all sync modes - full refresh and incremental including de-duped mode.
[Avni Api Docs](https://avni.readme.io/docs/api-guide)
[Avni Api Endpoints](https://app.swaggerhub.com/apis-docs/samanvay/avni-external/1.0.0)

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.

- [x] Connector version is set to `0.1.0`

    - `Dockerfile` has version `0.1.0`
- [ ]  Documentation updated

    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

## Tests>

<details><summary><strong>Acceptance Test</strong></summary>
Screenshot 2023-09-07 at 1 40 33 AM

</details>

### CODE REVIEW

**Comment by avirajsingh7** [comment]
@marcosmarxm Any update on this one?

**Comment by marcosmarxm** [comment]
@avirajsingh7 right now our team is dedicated to review Hackathon contributions. I added it to the backlog and return as soon as possible to review it.

**Comment by avirajsingh7** [comment]
@marcosmarxm can you review this new source pr(pending from long time)?

**Comment by siddhant3030** [comment]
@marcosmarxm hey. This PR is pending for so long. What can we do to help you push this PR?

**Comment by marcosmarxm** [comment]
Hello @avirajsingh7 and @siddhant3030 Airbyte team wasn't able to get a sandbox account to run proper tests. All connectors need to have sandbox to get approved and merged. I'll give another try to get a sandbox account.

**Comment by siddhant3030** [comment]
@avirajsingh7 can you please provide that soon?

**Comment by avirajsingh7** [comment]
@marcosmarxm I have dm you sandbox account id and password on slack please check.

**Review by marcosmarxm — APPROVED** [review]
Thanks for the contribution @avirajsingh7

**Comment by siddhant3030** [comment]
@marcosmarxm great. can we merge this now?

**Comment by marcosmarxm** [comment]
Need svg icon to get it merged.

**Comment by avirajsingh7** [comment]
@marcosmarxm added icon

**Comment by siddhant3030** [comment]
@marcosmarxm we've updated the svg icon for this one.

**Comment by marcosmarxm** [comment]
@avirajsingh7 can you please not update or merge master?

**Comment by siddhant3030** [comment]
@marcosmarxm sorry I was doing that. Thanks for bringing that up

**Comment by marcosmarxm** [comment]
Hello @siddhant3030 and @avirajsingh7  your feedback matters a lot to us. Can you spare just 3 minutes to complete a [survey](https://form.typeform.com/to/DOBqejte)? We're dedicated to making the contributor experience even better, and your input is key to achieving excellence. Thank you for helping us improve!

**Comment by siddhant3030** [comment]
@marcosmarxm Thanks for merging the PR. We've completed the survey :)

**Pull request merged**
