### PR TITLE
Bump faker version to test M1 Connector builds

### PR DESCRIPTION
**Pull request by evantahler**
No actual changes to the connector other than the version number.  This is a test of https://github.com/airbytehq/airbyte/pull/13004

### CODE REVIEW

**Review by sherifnada — APPROVED** [review]

**Comment by evantahler** [comment]
Soar Scan seems like a buggy test reporter... I don't think that failure should prevent this PR merge

**Comment by davinchia** [comment]
@evantahler I confirmed this is still using the old AMI: https://github.com/airbytehq/airbyte/runs/6624320419?check_suite_focus=true#step:3:59

I believe we can test this by explicitly setting the AMI here. If this works, we modify the workflow to default to the previous AMI in a follow up PR.

**Comment by davinchia** [comment]
Looks like that isn't working and we have to merge from master.

**Comment by evantahler** [comment]
Making progress with the default image:

```
+ echo '--- docker info ---'
+ docker --version
--- docker info ---
Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2
+ docker buildx version
github.com/docker/buildx v0.8.2 6224def4dd2c3d347eee19db595348c50d7cb491
```

Now the build is failing building the normalization image:
```
+ docker buildx build -t airbyte/integration-base-java:dev --platform linux/arm64 --load airbyte-integrations/bases/base-java

...

#6 [stage-2 1/7] WORKDIR /airbyte/integration_code
#6 DONE 0.2s

#7 [builder 2/4] RUN apk --no-cache upgrade     && pip install --upgrade pip     && apk --no-cache add tzdata build-base
#7 0.281 standard_init_linux.go:219: exec user process caused: exec format error
#7 ERROR: executor failed running [/bin/sh -c apk --no-cache upgrade     && pip install --upgrade pip     && apk --no-cache add tzdata build-base]: exit code: 1
------
 > [builder 2/4] RUN apk --no-cache upgrade     && pip install --upgrade pip     && apk --no-cache add tzdata build-base:
#7 0.281 standard_init_linux.go:219: exec user process caused: exec format error
------
error: failed to solve: executor failed running [/bin/sh -c apk --no-cache upgrade     && pip install --upgrade pip     && apk --no-cache add tzdata build-base]: exit code: 1
Error: Process completed with exit code 1.
##[debug]Finishing: Publish connectors/source-faker
```

**Pull request merged**
