### PR TITLE
Chore: Pin CDK refs for sources with unpinned refs

### PR DESCRIPTION
**Pull request by aaronsteers**
## What

CDK v5 broke these connectors and they are now failing in our nightly tests.

## How

Pinning to pre-v5 refs.

## Review guide

We're good to merge if CI passes.

## User Impact

None expected

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by natikgadzhi** [comment]
@aaronsteers bruh ;) 

```
process "poetry check" did not complete successfully: exit code: 1
Stdout:

Stderr:
Error: poetry.lock is not consistent with pyproject.toml. Run `poetry lock [--no-update]` to fix it.
```

I tried! I even bumped all your versions! poetry lock please ;)

**Comment by aaronsteers** [comment]
Downgrading to 'draft' because poetry update needs to run. I tried this from a codespace but ran into an issue with gpg signature not working - had to abandon that codespace. Will pick this up after my oncall shift.

**Comment by natikgadzhi** [comment]
I mean, I'm happy to do poetry locks for these, it's virtually five minutes.

**Pull request closed without merging**
