### PR TITLE
Creating license-faq

### PR DESCRIPTION
**Pull request by johnlafleur**
We need to put the license faq a lot more forward in the docs.

### CODE REVIEW

**Review by michel-tricot — APPROVED** [review]
LGTM % the asset change.

DO you want to drop it from airbyte.io and redirect to the docs isntead?

**Review by michel-tricot — COMMENTED** [review]
I wonder if we should have a very simple mention of the license in the main readme and a link to the FAQ

**Comment by michel-tricot** [comment]
yes something really simple. At the end of the Readme, we already have a license section. Maybe just add a quick note like: "For any question you have about ELv2, just visit xxx"

**Comment by johnlafleur** [comment]
New suggestion on this.

**Pull request merged**
