### PR TITLE
🐛 Source Mixpanel: Fix schemas and UI issues

### LINKED ISSUE #8062: Source Mixpanel: failed during normalization
## Enviroment
- **Airbyte version**: Cloud
- **Source Connector and version**: Mixpanel 0.1.5
- **Destination Connector and version**: Snowflake 0.3.17
- **Severity**: Very Low / Low / Medium / High / **Critical**
- **Step where error happened**: Deploy / **Sync job** / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Mixpanel to Snowflake normalization is not working.

## Expected Behavior
*Tell us what should happen.*

## Logs
Complete logs: [logs-9619-0.txt](https://github.com/airbytehq/airbyte/files/7557572/logs-9619-0.txt)
```
[32mnormalization[0m - 2021-11-16 23:36:15 INFO LineGobbler(voidCall):82 - 23:36:15 | 1 of 8 START incremental model AIRBYTE_SCHEMA.MIXPANEL_REVENUE............................................... [RUN]
[32mnormalization[0m - 2021-11-16 23:36:15 INFO LineGobbler(voidCall):82 - 23:36:15 | 2 of 8 START incremental model AIRBYTE_SCHEMA.MIXPANEL_FUNNELS............................................... [RUN]
[32mnormalization[0m - 2021-11-16 23:36:15 INFO LineGobbler(voidCall):82 - 23:36:15 | 3 of 8 START incremental model AIRBYTE_SCHEMA.MIXPANEL_ANNOTATIONS........................................... [RUN]
[32mnormalization[0m - 2021-11-16 23:36:17 INFO LineGobbler(voidCall):82 - 23:36:17 | 4 of 8 START incremental model AIRBYTE_SCHEMA.MIXPANEL_COHORTS............................................... [RUN]
[32mnormalization[0m - 2021-11-16 23:36:25 INFO LineGobbler(voidCall):82 - 23:36:25 | 5 of 8 START incremental model AIRBYTE_SCHEMA.MIXPANEL_ENGAGE................................................ [RUN]
[32mnormalization[0m - 2021-11-16 23:36:25 INFO LineGobbler(voidCall):82 - 23:36:25 | 6 of 8 START incremental model AIRBYTE_SCHEMA.MIXPANEL_COHORT_MEMBERS........................................ [RUN]
[32mnormalization[0m - 2021-11-16 23:36:30 INFO LineGobbler(voidCall):82 - 23:36:30 + "AIRBYTE_DATABASE".AIRBYTE_SCHEMA."MIXPANEL_ENGAGE"._AIRBYTE_AB_ID does not exist. The table needs to be rebuilt in full_refresh
[32mnormalization[0m - 2021-11-16 23:36:30 INFO LineGobbler(voidCall):82 - 23:36:30 + "AIRBYTE_DATABASE".AIRBYTE_SCHEMA."MIXPANEL_COHORT_MEMBERS"._AIRBYTE_AB_ID does not exist. The table needs to be rebuilt in full_refresh
[32mnormalization[0m - 2021-11-16 23:36:32 INFO LineGobbler(voidCall):82 - 23:36:32 | 1 of 8 OK created incremental model AIRBYTE_SCHEMA.MIXPANEL_REVENUE.......................................... [[32mSUCCESS 1[0m in 16.91s]
[32mnormalization[0m - 2021-11-16 23:36:32 INFO LineGobbler(voidCall):82 - 23:36:32 | 4 of 8 OK created incremental model AIRBYTE_SCHEMA.MIXPANEL_COHORTS.......................................... [[32mSUCCESS 1[0m in 14.64s]
[32mnormalization[0m - 2021-11-16 23:36:32 INFO LineGobbler(voidCall):82 - 23:36:32 | 3 of 8 OK created incremental model AIRBYTE_SCHEMA.MIXPANEL_ANNOTATIONS...................................... [[32mSUCCESS 1[0m in 17.11s]
[32mnormalization[0m - 2021-11-16 23:36:33 INFO LineGobbler(voidCall):82 - 23:36:33 | 5 of 8 ERROR creating incremental model AIRBYTE_SCHEMA.MIXPANEL_ENGAGE....................................... [[31mERROR[0m in 8.41s]
[32mnormalization[0m - 2021-11-16 23:36:35 INFO LineGobbler(voidCall):82 - 23:36:35 | 6 of 8 ERROR creating incremental model AIRBYTE_SCHEMA.MIXPANEL_COHORT_MEMBERS............................... [[31mERROR[0m in 9.78s]
[32mnormalization[0m - 2021-11-16 23:36:36 INFO LineGobbler(voidCall):82 - 23:36:36 | 2 of 8 OK created incremental model AIRBYTE_SCHEMA.MIXPANEL_FUNNELS.......................................... [[32mSUCCESS 1[0m in 21.00s]
[32mnormalization[0m - 2021-11-16 23:36:46 INFO LineGobbler(voidCall):82 - 23:36:46 | 7 of 8 START incremental model AIRBYTE_SCHEMA.MIXPANEL_FUNNELS_ANALYSIS...................................... [RUN]
[32mnormalization[0m - 2021-11-16 23:36:50 INFO LineGobbler(voidCall):82 - 23:36:50 | 8 of 8 START incremental model AIRBYTE_SCHEMA.MIXPANEL_EXPORT................................................ [RUN]
[32mnormalization[0m - 2021-11-16 23:36:55 INFO LineGobbler(voidCall):82 - 23:36:55 | 7 of 8 OK created incremental model AIRBYTE_SCHEMA.MIXPANEL_FUNNELS_ANALYSIS................................. [[32mSUCCESS 1[0m in 8.20s]
[32mnormalization[0m - 2021-11-16 23:37:08 INFO LineGobbler(voidCall):82 - 23:37:08 | 8 of 8 OK created incremental model AIRBYTE_SCHEMA.MIXPANEL_EXPORT........................................... [[32mSUCCESS 1[0m in 18.12s]
[32mnormalization[0m - 2021-11-16 23:37:08 INFO LineGobbler(voidCall):82 - 23:37:08 | 
[32mnormalization[0m - 2021-11-16 23:37:08 INFO LineGobbler(voidCall):82 - 23:37:08 | Finished running 8 incremental models in 79.62s.
[32mnormalization[0m - 2021-11-16 23:37:08 INFO LineGobbler(voidCall):82 - 
[32mnormalization[0m - 2021-11-16 23:37:08 INFO LineGobbler(voidCall):82 - [31mCompleted with 2 errors and 0 warnings:[0m
[32mnormalization[0m - 2021-11-16 23:37:08 INFO LineGobbler(voidCall):82 - 
[32mnormalization[0m - 2021-11-16 23:37:08 INFO LineGobbler(voidCall):82 - [33mDatabase Error in model MIXPANEL_ENGAGE (models/generated/airbyte_incremental/AIRBYTE_SCHEMA/MIXPANEL_ENGAGE.sql)[0m
[32mnormalization[0m - 2021-11-16 23:37:08 INFO LineGobbler(voidCall):82 -   100038 (22018): Numeric value '89.0.4389.90' is not recognized
[32mnormalization[0m - 2021-11-16 23:37:08 INFO LineGobbler(voidCall):82 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/AIRBYTE_SCHEMA/MIXPANEL_ENGAGE.sql
[32mnormalization[0m - 2021-11-16 23:37:08 INFO LineGobbler(voidCall):82 - 
[32mnormalization[0m - 2021-11-16 23:37:08 INFO LineGobbler(voidCall):82 - [33mDatabase Error in model MIXPANEL_COHORT_MEMBERS (models/generated/airbyte_incremental/AIRBYTE_SCHEMA/MIXPANEL_COHORT_MEMBERS.sql)[0m
[32mnormalization[0m - 2021-11-16 23:37:08 INFO LineGobbler(voidCall):82 -   100038 (22018): Numeric value '88.0.4324.104' is not recognized
[32mnormalization[0m - 2021-11-16 23:37:08 INFO LineGobbler(voidCall):82 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/AIRBYTE_SCHEMA/MIXPANEL_COHORT_MEMBERS.sql
[32mnormalization[0m - 2021-11-16 23:37:08 INFO LineGobbler(voidCall):82 - 
``` 

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

### PR DESCRIPTION
**Pull request by lazebnyi**
## What
#8062 - Source Mixpanel: failed during normalization

> Shortly about the problem.
Mixpanel 'engage' stream has a dynamic schema. There are some 'standard' fields but users can create custom fields as well.
I have tried to create such 'custom' fields but there is no way to specify the type for such custom fields. I tried to create fields with different values: ABC or 1. Such attrs are reported as a string for me. I was not able to find any way to change this.
The customer has a problem with the 'browser_version' field, which is a 'standard' field. It is reported as:
'number' - for customer
'string' - for our account.
The customer and I have similar values in this field, like "86.3.112.2", which is definitely a string.
So it is not clear what to do in this situation.

## How
- Normalization fix:
For `engage` stream already fixed bug here [PR](https://github.com/airbytehq/airbyte/pull/7505), need refresh schemas on the cloud. For `cohort_members` stream hard-code types for known 'standard' fields, but rely on API for other 'custom' fields. Also was enabled DefaultSchemaNormalization for `engage` and `cohort_members` streams.

- UI fix:
Fixed schema `anyOf` construction issue for `export` and `funnel` streams. Added titles and deleted `date_window_size` from `spec.json` according to UX handbook. 

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

### CODE REVIEW

**Review by sherifnada — COMMENTED** [review]
@lazebnyi how does this fix the normalization issue?

**Comment by lazebnyi** [comment]
@sherifnada As I said in the status, unfortunately, I could not reproduce the issue with normalization. 

In the contributor's log, I found this row: 

```
[32mnormalization[0m - 2021-11-16 23:36:30 INFO LineGobbler(voidCall):82 - 23:36:30 + "AIRBYTE_DATABASE".AIRBYTE_SCHEMA."MIXPANEL_ENGAGE"._AIRBYTE_AB_ID does not exist. The table needs to be rebuilt in full_refresh
[32mnormalization[0m - 2021-11-16 23:36:30 INFO LineGobbler(voidCall):82 - 23:36:30 + "AIRBYTE_DATABASE".AIRBYTE_SCHEMA."MIXPANEL_COHORT_MEMBERS"._AIRBYTE_AB_ID does not exist. The table needs to be rebuilt in full_refresh
```

I think the problem is with destination tables and data types there. Maybe changes were made manually by the cotributor.

**Review by midavadim — APPROVED** [review]

**Review by sherifnada — APPROVED** [review]
LGTM - can you add an explanation in the PR description of why this fixes the problem for historical context based on our slack convo?

**Pull request merged**
