### PR TITLE
Source File: specify pyxlsb as engine for Excel file parsing

### LINKED ISSUE #5622: Document & add tests for XLSB format in source-file
https://github.com/airbytehq/airbyte/pull/5613 adds the [pyxlsb](https://pypi.org/project/pyxlsb/) library which allows users to download a binary excel file. We'd like to: 
1. make this very obvious on the docs website for the source-file (it doesn't explicitly say it supports this)
2. Add it as a dedicated file-format which when set, sets the reader_options to the correct option
3. add tests for it

### PR DESCRIPTION
**Pull request by arsenlosenko**
Resolving:
https://github.com/airbytehq/airbyte/issues/5622

### CODE REVIEW

**Review by bazarnov — APPROVED** [review]
Do we have the unit_test to cover this `Excel` file parser?

**Review by bazarnov — APPROVED** [review]

**Review by lazebnyi — APPROVED** [review]

**Pull request merged**
