### PR TITLE
source-mssql*: fix integration tests

### PR DESCRIPTION
**Pull request by postamar**
This PR fixes tests in mssql source connectors which have been broken since the testcontainers upgrade in https://github.com/airbytehq/airbyte/pull/30493

### CODE REVIEW

**Review by nguyenaiden — APPROVED** [review]
Thank you for taking care of this!

**Comment by octavia-approvington** [comment]
This code is at peace with itself <br/> imagine karate kid approving

**Review by octavia-approvington — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-mssql-strict-encrypt test report (commit [`eb6d151867`](https://github.com/airbytehq/airbyte/pull/31504/commits/eb6d151867d78f9000780ecd791bf0779804594b)) - ❌

⏲️  Total pipeline duration: 301mn06s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build connector tar                                                         | ✅       |
| Java Connector Unit Tests                                                   | ❌       |
| Build source-mssql-strict-encrypt docker image for platform(s) linux/x86_64 | ✅       |
| Acceptance tests                                                            | ❌       |
| Java Connector Integration Tests                                            | ✅       |
| Validate metadata for source-mssql-strict-encrypt                           | ✅       |
| Connector version semver check                                              | ✅       |
| QA checks                                                                   | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/postamar_fix-mssql-tests/1697557893/eb6d151867d78f9000780ecd791bf0779804594b/source-mssql-strict-encrypt/2.0.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:eb6d151867d78f9000780ecd791bf0779804594b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mssql-strict-encrypt test
```

**Pull request merged**
