### PR TITLE
Revert "Better formatting/logging for pre-sync data"

### PR DESCRIPTION
**Pull request by akashkulk**
Reverts airbytehq/airbyte#25459

### CODE REVIEW

**Review by rodireich — APPROVED** [review]

**Comment by akashkulk** [comment]
/publish connector=connectors/source-postgres run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-postgres-strict-encrypt run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-postgres-strict-encrypt run-tests=false

**Comment by octavia-approvington** [comment]
This is really good <br/> simply the best

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
