### PR TITLE
Use shared workflow action on issues

### PR DESCRIPTION
**Pull request by bleonard**
Tags issues to route to correct teams.

### CODE REVIEW

**Review by davinchia — COMMENTED** [review]
Same thought here on not getting too confused with all the issues related workflows.

With the addition of this workflow, we will have 3 issue workflows. There is a general one that [assigns to project](https://github.com/airbytehq/airbyte/blob/master/.github/workflows/assign-issue-to-project.yml) and another one that is [community specific](https://github.com/airbytehq/airbyte/blob/master/.github/workflows/github-community-label-bot.yaml).

Would it make sense to consolidate all these for now? I'm not too opinionated about the eventual form. I mainly want to avoid confusion if these are too scattered around and want us to treat this intentionally.

**Comment by bleonard** [comment]
Once this gets merged to this shared code is running, I can consolidate the community tag that @harshithmullapudi added so we don't miss any of those into the workflow-actions code. The platform project routing workflow can be deleted when we verify with @pmossman and @benmoriceau that they are no longer using it.

**Comment by bleonard** [comment]
Combining or deleting those are definitely next steps @davinchia

**Review by davinchia — APPROVED** [review]
Thanks for following up on the workflows. I'll leave it to you then!

**Pull request merged**
