### PR TITLE
add hasCompletedSync in web backend get workspace endpoint

### LINKED ISSUE #5884: create a backend property for "completed first sync"
In order for us to show the :+1: / :-1: display on the frontend after completing the first sync, we need to expose the value to the frontend. We could do this by augmenting the user's response to include this property. We could do this at the user level and look it up at in their workspaces to ensure they've successfully completed a sync.

### PR DESCRIPTION
**Pull request by jrhizor**
fixes https://github.com/airbytehq/airbyte/issues/5884

I was considering adding it at the user level in the cloud project, but there were a few hurdles there.

The idea here is that the frontend could call this web backend endpoint and get an idea if a sync succeeded. If it has, show the :+1:/:-1: modal to ask a user to verify the data in their destination and say if their setup was good or not.

This doesn't look at a specific sync, it's purely for any sync in the first page of results. That should work since we're caching this completion on the frontend side. @cgardens does this place look reasonable? If so I'll add a test and merge.

I think later on we'll want to add this to the user model and not store the state on the frontend, but this seems like the easiest impl pre-launch.

### CODE REVIEW

**Comment by cgardens** [comment]
@jared Couple questions: 
1. How will we avoid showing the 👍 /👎  to the user multiple times in this schema?
2. so is the idea that the UI is going to poll for this endpoint for this?

**Comment by jrhizor** [comment]
1. it'll be device specific for a bit
2. yes

Originally I was thinking we could store the value as part of the user model in cloud, and then we wouldn't have to recompute after the first time and it would persist across sessions. However, there are a few issues. The main one is that we wouldn't be able to have the thumbs up/down modal in the OSS version, which will be pretty useful imo. If that's accepted as an assumption, then we need to put this in the OSS api somewhere, which means it should go at the workspace level.

We could modify the workspace persistence to hold this value or cache the value better, or we could have the completion of a sync push out a notification-style update that changes this value at the workspace level.

**Comment by cgardens** [comment]
I'm a little worried about us spamming them with asking for feedback. I think I would prefer the other option that you mentioned: 

> We could modify the workspace persistence to hold this value or cache the value better

just throw another boolean in the workspace model and call it a day. solves it for OSS, and is already close to other weird flags that we set, and pretty easy to do.

**Comment by jrhizor** [comment]
I guess we can add it as another boolean. I think updating after a sync is probably best even if it's a little harder. In the future we're going to want to be able to update individual fields so we don't run into a race condition.

**Pull request closed without merging**
