### PR TITLE
✨ source-s3:  migrate to the python base image

### PR DESCRIPTION
**Pull request by alafanechere**
## What
`source-s3` has a custom Dockerfile instruction downloading NLTK data.
To migrate this connector to use our base image we have to implement a post-install hook to download the NLTK data.

## How
- Add a `build_customization.py` module
- Implement a `post_connector_install` function which execute the nltk download script
- Run  `airbyte-ci connectors --name=source-s3 migrate-to-base-image 31601` to remove the Dockerfile and bump the connector version.

### CODE REVIEW

**Review by bazarnov — APPROVED** [review]
LGTM!

**Comment by flash1293** [comment]
@alafanechere  Before merging this let me do a manual test of the unstructured source please (just to make sure it works as intended)

**Review by artem1205 — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-s3 test report (commit [`829e239442`](https://github.com/airbytehq/airbyte/pull/31601/commits/829e239442299aa29df53c6f0a2c49014bfa47cf)) - ✅

⏲️  Total pipeline duration: 22mn03s 

| Step                                                      | Result   |
|:----------------------------------------------------------|:---------|
| Build source-s3 docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                | ✅       |
| Acceptance tests                                          | ✅       |
| Code format checks                                        | ✅       |
| Validate metadata for source-s3                           | ✅       |
| Connector version semver check                            | ✅       |
| Connector version increment check                         | ✅       |
| QA checks                                                 | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/augustin_10-19-source-s3_migrate_to_the_python_base_image/1697706313/829e239442299aa29df53c6f0a2c49014bfa47cf/source-s3/4.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:829e239442299aa29df53c6f0a2c49014bfa47cf)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by alafanechere** [comment]
> @alafanechere  Before merging this let me do a manual test of the unstructured source please (just to make sure it works as intended)

Would you mind adding a config in the acceptance test config that will use an unstructured source?

**Review by flash1293 — APPROVED** [review]
Tested and works as expected - confirmed that it picks up the nltk cache and doesn't download it on demand as part of the sync.

I will add an acceptance test for this parser in a follow-up PR to not hold this one back

**Pull request merged**
