### PR TITLE
Advanced options for source-s3 CSV without header

### PR DESCRIPTION
**Pull request by iamzjk**
## What
Solving #7012

## How
- Added `advanced_options` to source-s3 csv to allow passing in more Pyarrow [ReadOptions](https://arrow.apache.org/docs/python/generated/pyarrow.csv.ReadOptions.html#pyarrow.csv.ReadOptions)
- In addition, I fixed the code to work with airbyte-cdk 0.1.27 changes and resolved a deprecation warning

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated 
    - [x] Connector's `README.md`
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [x] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

### CODE REVIEW

**Comment by iamzjk** [comment]
`python -m pytest unit_tests`
```
Test session starts (platform: darwin, Python 3.7.11, pytest 6.2.5, pytest-sugar 0.9.4)
rootdir: /Users/jzhuan/Forks/airbyte, configfile: pytest.ini
plugins: sugar-0.9.4, timeout-1.4.2
collecting ... 
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓                                                                         2% ▎ 
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓                                                                        3% ▍ 
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓✓                                                                       5% ▌ 
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓✓✓                                                                      6% ▋ 
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓✓✓✓                                                                     8% ▊ 
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓✓✓✓✓                                                                   10% ▉ 
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓✓✓✓✓✓                                                                  11% █▎
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓✓✓✓✓✓✓                                                                 13% █▍
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓✓✓✓✓✓✓✓                                                                14% █▌
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓✓✓✓✓✓✓✓✓                                                               16% █▋   
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓✓✓✓✓✓✓✓✓✓                                                              17% █▊ 
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓✓✓✓✓✓✓✓✓✓✓                                                             19% █▉  
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓✓✓✓✓✓✓✓✓✓✓✓                                                            21% ██▏
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                           22% ██▎
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                          24% ██▍ 
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                      30% ███ 
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                    33% ███▍ 
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                 38% ███▊
 airbyte-integrations/connectors/source-s3/unit_tests/test_abstract_file_parser.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                               41% ████▎
 airbyte-integrations/connectors/source-s3/unit_tests/test_csv_parser.py ✓                                                                                  43% ████▍
 airbyte-integrations/connectors/source-s3/unit_tests/test_csv_parser.py ✓✓                                                                                 44% ████▌
 airbyte-integrations/connectors/source-s3/unit_tests/test_parquet_parser.py ✓                                                                              46% ████▋
 airbyte-integrations/connectors/source-s3/unit_tests/test_parquet_parser.py ✓✓                                                                             48% ████▊     
 airbyte-integrations/connectors/source-s3/unit_tests/test_s3file.py ✓✓✓✓✓✓✓                                                                                59% █████▉    
 airbyte-integrations/connectors/source-s3/unit_tests/test_stream.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                            100% ██████████

Results (24.37s):
      63 passed
```

**Comment by iamzjk** [comment]
`python -m pytest integration_tests `
```                              
Test session starts (platform: darwin, Python 3.7.11, pytest 6.2.5, pytest-sugar 0.9.4)
rootdir: /Users/jzhuan/Forks/airbyte, configfile: pytest.ini
plugins: sugar-0.9.4, timeout-1.4.2
collecting ... 
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓                                                                           5% ▌         
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓                                                                         10% ▉         
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓                                                                        14% █▌        
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓                                                                       19% █▉        
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓✓                                                                      24% ██▍       
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓✓✓                                                                     29% ██▉       
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓✓✓✓                                                                    33% ███▍      
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓✓✓✓✓                                                                   38% ███▊      
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓✓✓✓✓✓                                                                  43% ████▍     
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓✓✓✓✓✓✓                                                                 48% ████▊     
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓✓✓✓✓✓✓✓                                                                52% █████▎    
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓✓✓✓✓✓✓✓✓                                                               57% █████▊    
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓✓✓✓✓✓✓✓✓✓                                                              62% ██████▎   
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                             67% ██████▋   
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                            71% ███████▎  
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                           76% ███████▋  
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                          81% ████████▏ 
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                         86% ████████▋ 
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                        90% █████████▏
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                       95% █████████▌
 airbyte-integrations/connectors/source-s3/integration_tests/integration_test.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                     100% ██████████

Results (636.93s):
      21 passed

**Comment by iamzjk** [comment]
@Phlair ready for review

**Review by Phlair — APPROVED** [review]
Awesome! Thanks for the contribution, this is a great addition!

I also have some s3 source changes in https://github.com/airbytehq/airbyte/pull/6615 that is just about ready to publish, so I'll merge from your PR into that and release with those updates into v0.1.6 altogether, sound good?

**Pull request closed without merging**
