### PR TITLE
Publish Destination Firestore

### PR DESCRIPTION
**Pull request by harshithmullapudi**
## What
publish new destination #7231

### CODE REVIEW

**Comment by harshithmullapudi** [comment]
@marcosmarxm I have not published this in destination-definitions and specs. Reason is just playing safe as I am not aware why this destination is not automatically added to definition. Happy to create a new PR on this.

**Comment by marcosmarxm** [comment]
the error is the gcc wasn't able to compile, maybe something related to a lib dependency. it's weird test worked and publish failed.

**Comment by harshithmullapudi** [comment]
Hey @marcosmarxm I figured out the issue. Looking into it.

**Comment by harshithmullapudi** [comment]
@marcosmarxm let me know on this https://github.com/airbytehq/airbyte/pull/8158#issuecomment-974812052. For now I am merging this.

**Pull request merged**
