### PR TITLE
Source MSSQL: Added event_serial_no to cdc metadata

### PR DESCRIPTION
**Pull request by plenti-jacob-roe**
## What
This change adds the event_serial_no as cdc metadata for the sql server souce connector. This allows for cases when multiple updates or inserts are performed within the one transaction to know the order the updates occurred. Currently we would have to guess which is the latest updated row.

## How
The [Debezium](https://debezium.io/documentation/reference/stable/connectors/sqlserver.html#_change_data_event_enrichment) change data events already contain this information and airbyte already exposes the commit_lsn from it. Pulling from the same source data, adding the extra column for `event_serial_no`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

No breaking changes

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ x ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ x ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by plenti-jacob-roe** [comment]
This is solves sequence order for this issue https://github.com/airbytehq/airbyte/issues/16625

**Review by subodh1810 — APPROVED** [review]
The changes look fine. Just need to make sure the tests and the build is green before merging.

**Comment by plenti-jacob-roe** [comment]
So two issues that I am not sure how to fix: 

1. The test that is failing the only diff I can see in my testing is that the full refresh doesn't contain the cdc metadata but the data matches
2. Another Issue I have found in testing is the first sync doesn't provide the event_serial_no but the next sync will. Is there any difference in behavior for the first sync of a table?

**Comment by marcosmarxm** [comment]
Sorry the delay to assistance you here @plenti-jacob-roe I hope to have time next week to give some feedback

**Comment by plenti-jacob-roe** [comment]
@marcosmarxm any updates?

**Comment by marcosmarxm** [comment]
Sorry I missed this one! I'll take a look next week @plenti-jacob-roe this week we're receiving a lot of contributions for hacktoberfest.

**Comment by plenti-jacob-roe** [comment]
@marcosmarxm Any updates

**Comment by marcosmarxm** [comment]
Hello :wave:, first thank you for this amazing contribution. 

We really appreciate the effort you've made to improve the project.
We ask you patience for the code review. Last month our team was focused on Hacktoberfest event and that probably left some PR without the proper feedback. And this week, due to the Thanksgiving US Holiday, most our team is out of office with their families. Another important piece of information why code won't be merge this week is: as a safety measure the core team has decided to freeze merging code to main branch to keep the release stable. Next week we'll return to you with the proper code review and update the status of your contribution.

If you have any questions feel free to send me a message in Slack!
Thanks!

**Comment by marcosmarxm** [comment]
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

**Comment by plenti-jacob-roe** [comment]
@marcosmarxm can I please get an update on this

**Comment by subodh1810** [comment]
hey @plenti-jacob-roe I will work on getting the PR across the finish line. Trying to understand how this change affects the current connector and if `event_serial_no` is always present or not

**Comment by plenti-jacob-roe** [comment]
@subodh1810 `event_serial_no` should be there for any cdc enabled stream. Its debezium way of handling `__$seqval` in the cdc tables. See https://debezium.io/documentation/reference/stable/connectors/sqlserver.html#_data_change_events in the payload and https://learn.microsoft.com/en-us/sql/relational-databases/system-functions/cdc-fn-cdc-get-all-changes-capture-instance-transact-sql?view=sql-server-ver16

**Comment by plenti-jacob-roe** [comment]
@subodh1810 Any updates?

**Comment by subodh1810** [comment]
hey @plenti-jacob-roe we had few issues with our CI and for a brief period merging was blocked for PRs. We have fixed that issue and now we can merge PRs. 

One thing to note about this PR is that it seems the value for new field `event_serial_no` will be null for the data that will be fetched during the first sync. This is cause during the first sync we do a snapshot i.e. fetch data using `select` statement. Once thats finished then we switch to the processing of the events from the change data capture. 

I will work on fixing the test cases on this PR but it will take some time (occupied with other work as well). I think this should be done by the end of next week (23rd Feb).

**Comment by subodh1810** [comment]
@plenti-jacob-roe thank you again for your contribution and I apologise that it took so long to get this across the finish line. I have published a new version with your changes for mssql.

**Pull request merged**
