### PR TITLE
🐛 Source Zenloop: update following state management changes in the CDK

### PR DESCRIPTION
**Pull request by maxi297**
## What
Breaking changes were done as part of https://github.com/airbytehq/airbyte/commit/a45a1e33413eacccb2b8a83450d1638c48fd2042. This PR fixes the breaking changes for zenloop.

## How
Updating the interfaces that were affected by breaking changes.

## 🚨 User Impact 🚨
None as the code should have the exact same behavior

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-zenloop test report (commit [`0bc8d4af62`](https://github.com/airbytehq/airbyte/pull/27761/commits/0bc8d4af623bfe05b9704d54b66434adda988075)) - ❌

⏲️  Total pipeline duration: 101 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zenloop/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ❌        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ❌        |
| Connector package install                                             | ✅        |
| Build source-zenloop docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_zenloop/1687892190/0bc8d4af623bfe05b9704d54b66434adda988075/source-zenloop/0.1.8/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zenloop test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zenloop test report (commit [`e8eaa3ba85`](https://github.com/airbytehq/airbyte/pull/27761/commits/e8eaa3ba855574cf276d9df7d3db5e2b7dd3fc9c)) - ❌

⏲️  Total pipeline duration: 197 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zenloop/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ❌        |
| Connector package install                                             | ✅        |
| Build source-zenloop docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_zenloop/1687895754/e8eaa3ba855574cf276d9df7d3db5e2b7dd3fc9c/source-zenloop/0.1.9/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zenloop test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zenloop test report (commit [`e8eaa3ba85`](https://github.com/airbytehq/airbyte/pull/27761/commits/e8eaa3ba855574cf276d9df7d3db5e2b7dd3fc9c)) - ❌

⏲️  Total pipeline duration: 173 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zenloop/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ❌        |
| Connector package install                                             | ✅        |
| Build source-zenloop docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_zenloop/1687896085/e8eaa3ba855574cf276d9df7d3db5e2b7dd3fc9c/source-zenloop/0.1.9/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zenloop test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zenloop test report (commit [`57917d4fd2`](https://github.com/airbytehq/airbyte/pull/27761/commits/57917d4fd2c0b7e7982e96ebdec27ad3effa57f9)) - ❌

⏲️  Total pipeline duration: 180 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zenloop/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ❌        |
| Connector package install                                             | ✅        |
| Build source-zenloop docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_zenloop/1687899792/57917d4fd2c0b7e7982e96ebdec27ad3effa57f9/source-zenloop/0.1.9/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zenloop test
```

**Comment by octavia-squidington-iii** [comment]
##  source-zenloop test report (commit [`cb48ee219a`](https://github.com/airbytehq/airbyte/pull/27761/commits/cb48ee219ac506358a30d0d98a6dfec6c516a4d4)) - ✅

⏲️  Total pipeline duration: 181 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zenloop/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-zenloop docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_zenloop/1687968301/cb48ee219ac506358a30d0d98a6dfec6c516a4d4/source-zenloop/0.1.9/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zenloop test
```

**Review by artem1205 — APPROVED** [review]

**Pull request merged**
