### PR TITLE
fix-cdc: errors retry debezium property should be less than max retry

### PR DESCRIPTION
**Pull request by subodh1810**
Issue : https://github.com/airbytehq/oncall/issues/1783

### CODE REVIEW

**Review by akashkulk — APPROVED** [review]
I would just say leave a comment on that particular property

**Comment by edgao** [comment]
/publish connector=connectors/source-postgres,connectors/source-postgres-strict-encrypt,connectors/source-mysql,connectors/source-mysql-strict-encrypt,connectors/source-mssql,connectors/source-mssql-strict-encrypt

**Comment by edgao** [comment]
/publish connector=connectors/source-alloydb,connectors/source-alloydb-strict-encrypt

**Comment by edgao** [comment]
/publish connector=connectors/source-mssql-strict-encrypt run-tests=false

**Pull request merged**
