### PR TITLE
De-duplicate config parameters

### PR DESCRIPTION
**Pull request by ryankfu**
## What
De-duplicating and consolidating config parameters to be referenced *only* from `JdbcUtils.java`. Currently there are several files that are using constants of the same string so this change will help to move all those constants in a single file accessible by all JDBC connections. Original Github Issue: https://github.com/airbytehq/airbyte/issues/14698 

## How
Refactor most of the JDBC connections to move `ssl`, `jdbc_url`, `host`, `post`, `password`, `username`, `schema`, `schemas`, etc config parameters to be placed in `JdbcUtils.java`

## Recommended reading order:
Each of these files have overlapping config parameter constants that are consolidated into `JdbcUtils.java`
1. `JdbcUtils.java`
2. `ClickhouseDestination.java`
3. `MariadbColumnstoreDestination.java`
4. `MongodbDestinationStrictEncryptAcceptanceTest.java`
5. `MongodbDestination.java`
6. `MongodbDestinationAcceptanceTest.java`
7. `MSSQLDestination.java`
8. `MySQLDestination.java`
9. `SshMySQLDestinationAcceptanceTest.java`
10. `OracleDestination.java`
11. `PostgresDestination.java`
12. `RedshiftInsertDestination.java`
13. `RedshiftStagingS3Destination.java`
14. `CockroachDbSource.java`
15. `Db2Source.java`
16. `Db2SourceAcceptanceTest.java`
17. `MongoDbSource.java`
18. `MssqlSource.java`
19. `RedshiftSource.java`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

There are no breaking changes, it is mainly a refactor to keep the diverging constants for JDBC config parameters centralized in one file that can be referenced across `Source` and `Destination` connectors

NOTE: there seems to be an inconsistency with the naming of our connectors (e.g. `MssqlSource.java` vs `MSSQLDestination.java`)

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by grishick** [comment]
@ryankfu I doubt that your changes caused any of these test failures, but to be sure, can you run the same tests on master via CI?

**Comment by ryankfu** [comment]
For all the failed integration tests, tested on the `master` branch to confirm if these failures were already existing and here are the runs that failed on `master` branch to showcase the changes in this PR are not the cause of the failures:
* `destination-mongodb-strict-encrypt`: https://github.com/airbytehq/airbyte/actions/runs/2701067513
* `destination-mongodb`: https://github.com/airbytehq/airbyte/actions/runs/2701372869
* `source-cockroachdb`: https://github.com/airbytehq/airbyte/actions/runs/2701669504
* `source-mongodb-strict-encrypt`: https://github.com/airbytehq/airbyte/actions/runs/2701670716
* `source-oracle-strict-encrypt`: https://github.com/airbytehq/airbyte/actions/runs/2701671553
* `source-snowflake`: https://github.com/airbytehq/airbyte/actions/runs/2701672188

**Comment by ryankfu** [comment]
Created github issues for each of the failures for GL to take a further look into:
* `destination-mongodb-strict-encrypt`: https://github.com/airbytehq/airbyte/issues/14895
* `destination-mongodb`: https://github.com/airbytehq/airbyte/issues/14896
* `source-cockroachdb`: https://github.com/airbytehq/airbyte/issues/14898
* `source-mongodb-strict-encrypt`: https://github.com/airbytehq/airbyte/issues/14899
* `source-oracle-strict-encrypt`: https://github.com/airbytehq/airbyte/issues/14900
* `source-snowflake`: https://github.com/airbytehq/airbyte/issues/14901

**Review by grishick — APPROVED** [review]

**Pull request merged**
