### PR TITLE
GitHub Source: Ensure request_params() in incremental streams use stream_state at start of sync

### PR DESCRIPTION
**Pull request by cjwooo**
## What
Streams that extend IncrementalMixin read stream_state when determining the HTTP request params in request_params(), via get_starting_point(). This function is called before each HTTP request pagination loop. However, get_updated_state() is called after the processing of each record, which currently mutates the same state dictionary that is passed into that function.

When only GitHub repository is specified in the source configuration, this works as intended. However, when multiple repositories are specified, once the second stream_slice (repository) begins processing, get_updated_state() updates the same state dictionary that is passed into request_params() and therefore get_starting_point(). This results in the request params having a `since` value = the timestamp of the most recently processed stream record during each pagination loop, instead of the state value that was given at the beginning of read_records(). So, both the page number param and the `since` param are increased during each pagination loop, when only the page number param should be incremented.

I believe this also happens if a state dictionary exists and is passed into the sync, i.e. not the first sync for a connection, because the mutable state is passed into read_records() right away instead of starting from undefined state.

## How
Change the get_updated_state() for IncrementalMixin streams to return an updated copy of the given state dictionary instead of mutating the passed in state directly.

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by alafanechere** [comment]
Thank you for this contribution @cjwooo! 
I'll run the tests on our CI to make sure they pass and will go for a first review afterward.
FYI the latest CDK offers an `IncrementalMixin` class which is making the `get_updated_state` function deprecated, let me know if you think using it might be a good alternative to your solution. https://docs.airbyte.com/connector-development/cdk-python/incremental-stream/

**Comment by alafanechere** [comment]
I'll be off until next Monday so bare with me if there's a bit of delay reviewing / merging this.

**Review by alafanechere — CHANGES_REQUESTED** [review]
Hey @cjwooo,
I think your changes broke some custom unit tests:
* `test_stream_commits_incremental_read`:
* `test_stream_comments`
* `test_stream_commits_state_upgrade`
```python
	 >       assert stream_state == ***"organization/repository": ***"updated_at": "2022-02-02T10:10:04Z"***
	 E       AssertionError: assert *** == ***'organization/repository': ***'updated_at': '2022-02-02T10:10:04Z'***
	 E         Right contains 1 more item:
	 E         ***'organization/repository': ***'updated_at': '2022-02-02T10:10:04Z'***
	 E         Full diff:
	 E         - ***'organization/repository': ***'updated_at': '2022-02-02T10:10:04Z'***
	 E         + ***
```

Could you please make the changes required to make these tests pass? 🙏

**Comment by grubberr** [comment]
Good catch I think this PR https://github.com/airbytehq/airbyte/pull/13531 has to fix this `request_params` problem

**Comment by alafanechere** [comment]
@grubberr do you mean #13531 fixes the same bug?

**Comment by alafanechere** [comment]
@cjwooo I'm closing it because our internal team already fixed this in #13531 . Feel free to post on #13527 if the fix does not work for you.

**Pull request closed without merging**
