### PR TITLE
:bug: Source Notion: migrated to advancedAuth

### PR DESCRIPTION
**Pull request by darynaishchenko**
## What
https://github.com/airbytehq/airbyte/issues/26242

## How
- Replace deprecated `authSpecification` with `advancedAuth` in the connector spec

### CODE REVIEW

**Comment by bnchrch** [comment]
@darynaishchenko I tried reproducing this locally with no success.

So what ive done (I hope you dont mind) is
1. Updated your branch to latest master
2. Which is rerunning the new test ci https://github.com/airbytehq/airbyte/actions/runs/5273620075/jobs/9537254967

Note that if this passes we should be goood!

also as of today `/test` has been deprecated and is no longer required.

**Comment by octavia-squidington-iii** [comment]
##  source-notion test report (commit [`9f8677f81c`](https://github.com/airbytehq/airbyte/pull/26535/commits/9f8677f81c07d0fa669080ff2e610d52f331cfa1)) - ✅

⏲️  Total pipeline duration: 225 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-notion/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-notion docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5273620075)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-notion test
```

**Comment by davydov-d** [comment]
thanks @bnchrch!

**Review by davydov-d — APPROVED** [review]

**Pull request merged**
