### PR TITLE
Source Sendgrid: fix contacts missing records; Remove Messages stream

### PR DESCRIPTION
**Pull request by artem1205**
## What

- Fix contacts missing records https://github.com/airbytehq/alpha-beta-issues/issues/778 + schema
- Remove messages stream https://github.com/airbytehq/alpha-beta-issues/issues/214
- Add datetime selector https://github.com/airbytehq/alpha-beta-issues/issues/470

## How
*Describe the solution*

## Recommended reading order
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Review by lazebnyi — APPROVED** [review]

**Comment by visnup** [comment]
> * Remove messages stream https://github.com/airbytehq/alpha-beta-issues/issues/214

Hi, is there documentation or reasoning on why the Messages stream was removed? I can't access this repo, so don't know if it's already been discussed somewhere that I'm missing. We currently use the stream and have found it useful.

**Comment by apallin** [comment]
+1 why was this removed?  This is for sure the most useful stream from sendgrid for our analytics.  Would love to understand why and see if we can advocate to get this readded.

**Comment by artem1205** [comment]
@visnup , @apallin 

During SendGrid migration to GA [Messages](https://docs.sendgrid.com/api-reference/e-mail-activity/filter-all-messages) stream was removed, due to limitation on Sendgrid side (returns only first 1 000 records regardless of query parameters). Problem was described on [stackoverflow](https://stackoverflow.com/questions/72429114/is-there-a-workaround-for-retrieving-data-for-more-than-1000-messages-using-send) , still no solution. This means, that even with the use of slicer (e.g. filter by day interval) we cannot guarantee that we will obtain all records (if `count(records) > 1000`).

To make it work in a proper way (return all records) we need to use another [endpoint](https://docs.sendgrid.com/api-reference/e-mail-activity/request-a-csv), which will send a link to email (quiet strange flow for API), this flow is not supported.

**Comment by jcomo** [comment]
@artem1205 thanks for explanation, and agree that it's a poor API design. Could I propose a few thoughts as a workaround?

While I'm sure that this is a problem that would be exacerbated with scale, I'm having a hard time imagining scenarios (other than scale) in which last_event_time would be the same for > 1000 messages. I would love your input here, as someone who is a bit closer to it, but my current view of the situation is that it would be a pretty rare edge case.

That being said, it _is_ still a case to consider, so I was thinking about a solution along the lines of:

* Add an option to the settings that is effectively a checkbox that enables the messages stream. This could provide a warning / link to the problem, so that users can enable at their own risk
* Potentially emit some sort of warning (if airbyte's infra supports this) if there are 1000 messages retrieved with the same last_event_time, to at least provide _some_ visibility into the issue.

If that's doable, I think it would solve the use case for the majority of customers (us included), while still being aware of the edge case (at least if/until sendgrid decides to improve this).

This is, of course, unless I'm missing an obvious scenario where > 1000 messages would commonly have the same last_event_time.

**Comment by salja03-t21** [comment]
> @artem1205 thanks for explanation, and agree that it's a poor API design. Could I propose a few thoughts as a workaround?
> 
> While I'm sure that this is a problem that would be exacerbated with scale, I'm having a hard time imagining scenarios (other than scale) in which last_event_time would be the same for > 1000 messages. I would love your input here, as someone who is a bit closer to it, but my current view of the situation is that it would be a pretty rare edge case.
> 
> That being said, it _is_ still a case to consider, so I was thinking about a solution along the lines of:
> 
>     * Add an option to the settings that is effectively a checkbox that enables the messages stream. This could provide a warning / link to the problem, so that users can enable at their own risk
> 
>     * Potentially emit some sort of warning (if airbyte's infra supports this) if there are 1000 messages retrieved with the same last_event_time, to at least provide _some_ visibility into the issue.
> 
> 
> If that's doable, I think it would solve the use case for the majority of customers (us included), while still being aware of the edge case (at least if/until sendgrid decides to improve this).
> 
> This is, of course, unless I'm missing an obvious scenario where > 1000 messages would commonly have the same last_event_time.

This would absolutely help us, and would work for all of our use-cases.

**Pull request merged**
