### PR TITLE
🐛 Source Braintree: Adds pagination to braintree streams

### PR DESCRIPTION
**Pull request by AGPapa**
## What
Issue #32197 identified that the braintree connector only syncs 50 records at a time. This is because the connector does not paginate the results for more streams.

## How
The DisputeExtractor had pagination set up, so I copied that configuration to the other incremental streams that use braintree's "advanced search" endpoint.

## Review guide

1. `airbyte-integrations/connectors/source-braintree/source_braintree/manifest.yaml`

## User Impact
This is what a sync looked like before this change:
Screenshot 2024-07-18 at 8 49 21 AM

And this is what it looks like afterwards:
Screenshot 2024-07-18 at 8 42 24 AM

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by marcosmarxm — APPROVED** [review]
LGTM thanks for the fix @AGPapa running CI tests now.

**Comment by marcosmarxm** [comment]
Hello your feedback matters a lot to us. Can you spare just 2 minutes to complete a [survey](https://form.typeform.com/to/DOBqejte)? We’re dedicated to making the contributor experience even better, and your input is key to achieving excellence. Thank you for helping us improve!

**Comment by valentinfily** [comment]
Hello @AGPapa,
I started experiencing failed syncs (about 90% of the time) since this was merged. This used to work perfectly.
Syncs fail after 2 hours (they used to take about 2 mins) and it outputs the following message : 
image
Thanks

**Comment by AGPapa** [comment]
> I started experiencing failed syncs (about 90% of the time) since this was merged. This used to work perfectly.

Agh, that's not good.

When you say "this used to work perfectly" - did it sync more than 50 records at a time prior to this change? Or was it capped at 50? If you revert the version number to 0.3.4 can you check? 

From the error message it looks like there's some kind of bad response it gets back on page 543. Without this change I think it would have only grabbed the data from page 1. I think it's possible that there is some kind of transaction on page 543 that is failing for a reason unrelated to this PR, but that this PR exposed because it wasn't previously getting far enough to find it.

**Comment by valentinfily** [comment]
As you can see it fails at any random page after a while :
image
I cannot confirm wether it used to sync more than 50 records at once previously as I have it running multiple times a day and it would grab < 50 new records each time.

**Comment by AGPapa** [comment]
OK

I think the 422 code is related to [a timeout](https://github.com/braintree/braintree_ruby/issues/46#issuecomment-24360838), which explains why it appears randomly.

If each sync was <50 records before then I would have expected that to continue. Perhaps it's trying to resync everything instead of finding only the incremental new records? I don't know why it would do that.

@marcosmarxm I'm not sure what the best solution is here.

**Comment by AGPapa** [comment]
I've put up a revert PR. @marcosmarxm let me know what you think is best. Ideally we'd be able to sync more than 50 records at a time, but it sounds like this is causing issues for other users. I don't know if you have statistics to see if other Airbyte Cloud users are seeing similar problems or not.

**Comment by AGPapa** [comment]
@valentinfily - are you in an "Incremental" sync mode for this connector, or are you in "Full Refresh"?

I'm trying to recreate the behavior that you're seeing.

**Comment by valentinfily** [comment]
> @valentinfily - are you in an "Incremental" sync mode for this connector, or are you in "Full Refresh"?
> 
> I'm trying to recreate the behavior that you're seeing.

I'm only syncing one stream in incremental mode :
image

**Pull request merged**
