### PR TITLE
[airbyte-cdk] add incomplete status to availability check during read

### PR DESCRIPTION
**Pull request by lazebnyi**
## What
When trying to retrieve a stream, if the stream is not available from the source, the source should return a status of INCOMPLETE.

Fixed https://github.com/airbytehq/airbyte-internal-issues/issues/8385

## How
Return the Airbyte stream status as INCOMPLETE after issuing a warning that the stream was skipped.

For concurrent streams, collect them during the process of fetching streams to read, and afterwards, return a warning and set their status to INCOMPLETE.

## User Impact
No

## Can this PR be safely reverted and rolled back?
- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by brianjlai — COMMENTED** [review]
in addition to the `INCOMPLETE` stream status, similar to how we emit per stream error messages for streams that fail during a sync, can we also emit a config error message and append a config error for the missing stream to the `stream_name_to_exception` map. We then continue the sync and at the end we fail the sync

**Comment by lazebnyi** [comment]
@brianjlai, in that case, we will fail sync when we have at least one empty stream. I don't think we need to fail the sync if we have unavailable streams.

**Comment by brianjlai** [comment]
@lazebnyi let me think about this a bit. I think there is an argument that we are in an error state because the catalog + config are not in alignment and should be rectified either by the user or the platform and just silently skipping is not great. Natalie and I originally discussed adding a config error, but maybe let's discuss this on slack

**Review by brianjlai — APPROVED** [review]
ah sorry. my original comment was probably intended for the catalog/config misalignment. And this is purely just for unavailable streams. 

Codewise everything looks good and no comments so I'll approve. However, I have two questions before we merge:

- Is there a GH issue to track raising INCOMPLETE + config error for streams in the catalog that don't exist in the source?
- With @artem1205 's [PR](https://github.com/airbytehq/airbyte/pull/40682) to deprecate availability strategy, do we still need to do this work at all since we no longer have `stream_is_available` and we would now expect permissions or other errors to just be raised during the `read()` and per-stream errors to be reported?

**Comment by lazebnyi** [comment]
@brianjlai yes, this issue already close as we merge PR, but here is the link - https://github.com/airbytehq/airbyte-internal-issues/issues/8384

**Pull request merged**
