### PR TITLE
Python CDK: remove "deprecated" package

### PR DESCRIPTION
**Pull request by erohmensing**
## What
* Delete code
* This code has been under a `deprecated` folder and untouched for at least 3 years (blame history gets hard to track before that). 🪓 it

## User Impact
No one should be using this. 

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by erohmensing** [comment]
* **#37497** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/37497?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @erohmensing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by natikgadzhi — APPROVED** [review]
Noice! Let's 🚢. 

Did you cmd+f connectors in our repo to see if _we_ are using it anywhere? I'd say even if we are, still shipit. 

I've restarted formatters, but I'm honestly cool to merge as is. Formatters died after 10 and a half minutes with a dagger error :lolsob:

**Comment by erohmensing** [comment]
@natikgadzhi thanks, thought i did but apparently just looked at usages. Was only used in one connector, have pinned the connector's CDK version to the latest version it was on which seems to be giving it a good success rate.

**Review by octavia-approvington — APPROVED** [review]

**Comment by octavia-approvington** [comment]
A job well done <br/> nice job

**Pull request merged**
