### PR TITLE
Migrate Dockerhub Source Connector to Low Code

### LINKED ISSUE #29270: DockerHub

### PR DESCRIPTION
**Pull request by topefolorunso**
## What
Migrating Source Dockerhub to Low-Code CDK resolves #29270 

## How
Created the connector using the connector buider UI, then imported the manifest.yaml to the low code cdk.

## Recommended reading order
1. `manifest.yaml`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hello 👋 , right now Airbyte's integration tests are failing for this connector and I'm going to work during the week to fix them. Due a high number of contributions we have a backlog and your contribution will be review next week. We ask to you share the integration test from your side whatever possible and if you don't have credentials to run tests to get in touch with @RealChrisSean as soon as possible. Also some common missing steps contributors does migrating to low code are (and you can double check to make sure you implemented this): 
* adding paginator
* update the documentation changelog + metadata file and dockerfile version
* if the connector has `start_date` parameter you must implement incremental syncs

**Comment by archangelic** [comment]
Thanks for your contribution! Can you resolve the merge conflicts so we can continue with the review?

**Comment by topefolorunso** [comment]
> Thanks for your contribution! Can you resolve the merge conflicts so we can continue with the review?

merge conflicts resolved @archangelic

**Review by archangelic — CHANGES_REQUESTED** [review]
I've looked over this, and it all looks good. All that is left is to fix the release date in `metadata.yaml` and add a changelog entry to `docs/integrations/sources/dockerhub.md`.

**Comment by topefolorunso** [comment]
Fixed @archangelic, please review

**Review by archangelic — APPROVED** [review]

**Comment by archangelic** [comment]
This all looks good! Going to merge this!

**Pull request merged**
