### PR TITLE
🎉  New Source: Hellobaton

### PR DESCRIPTION
**Pull request by dluftspring**
## What
Creating a new python HTTP source for [hellobaton](https://www.hellobaton.com/) based on this [API spec](https://app.hellobaton.com/api/redoc/)

## How
Using the python CDK to implement full refresh streams for every available endpoint listed in the redoc

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
None

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>

#### Community member or Airbyter
   
- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
thanks for the contribution @dluftspring we're going to review soon. I had create one issue to get credentials to run our integration tests https://github.com/airbytehq/airbyte/issues/8476, is it possible for you share yours so we can anticipate the review?

**Comment by dluftspring** [comment]
@marcosmarxm let me ask for a set of dummy credentials from the baton folks. Mine are attached to real company data and i'd prefer not to expose them unless it's absolutely necessary. I'll reply to this conversation with more details

**Comment by marcosmarxm** [comment]
> @marcosmarxm let me ask for a set of dummy credentials from the baton folks. Mine are attached to real company data and i'd prefer not to expose them unless it's absolutely necessary. I'll reply to this conversation with more details

Not a problem! So we need to wait the team to have a sandbox account.

**Comment by marcosmarxm** [comment]
@dluftspring can you share the unit test and integration test output?

**Comment by dluftspring** [comment]
@marcosmarxm which commands are used to run the unit and integration tests? Was searching through the docs but couldn't seem to find the right ones.

**Comment by marcosmarxm** [comment]
you can run `./gradlew airbyte-integrations:connectors:soruce-hellobaton:integrationTest`

**Comment by marcosmarxm** [comment]
@dluftspring make sure this commands works in your local machine, right now there are some failures building the docker container because of Flake/Black formatting files and the integration tests are not working.

**Comment by dluftspring** [comment]
Okay running the integration tests I can see two task failures. Here are the two failures

```
2021-12-16T08:28:15.961-0500 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Run main tasks' completed
2021-12-16T08:28:15.965-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
2021-12-16T08:28:15.967-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build completed with 2 failures.
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 1: Task failed with an exception.
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] -----------
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':airbyte-integrations:connectors:source-hellobaton:flakeCheck'.
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Python call failed: .venv/bin/python -m flake8 . --config /Users/dluftspring/repos/airbyte/tools/python/.flake8
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] ==============================================================================
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 2: Task failed with an exception.
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] -----------
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':tools:code-generator:airbyteDocker'.
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Process 'command '/Users/dluftspring/repos/airbyte/tools/bin/build_image.sh'' finished with non-zero exit value 1
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
2021-12-16T08:28:15.968-0500 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] ==============================================================================
```

Do you need the full stacktrace? Any places I should start looking for linting errors?

**Comment by dluftspring** [comment]
Might need a little help chasing down the issues in `build_image.sh`

**Comment by marcosmarxm** [comment]
@dluftspring are you still having problems? You can use the command I sent to you or the ones in the README.md file created with the generator.

**Comment by dluftspring** [comment]
@marcosmarxm I fixed the linter errors with this [commit](https://github.com/airbytehq/airbyte/pull/8461/commits/ce0ad6225a31f2532e470b13298381898bf8fe05) but I don't really have a good idea of why `build_image.sh` is failing. It just says theres a nonzero exit code but no other logging that I can find easily. Any help would be very appreciated :)

**Comment by marcosmarxm** [comment]
@dluftspring what command are you executing?

**Comment by dluftspring** [comment]
From the repo root im running `./gradlew airbyte-integrations:connectors:soruce-hellobaton:integrationTest`

**Comment by marcosmarxm** [comment]
> From the repo root im running `./gradlew airbyte-integrations:connectors:source-hellobaton:integrationTest`

can you send me a message in Slack. I can help you debugging the problem there.

**Review by marcosmarxm — APPROVED** [review]
awesome work @dluftspring 📟

**Pull request merged**
