### PR TITLE
airbyte-ci: re-enable caching on source-postgres CI

### PR DESCRIPTION
**Pull request by alafanechere**
## What
We disabled dagger caching for source-postgres while we were working on the improving its CI.
The main reason was to not bias our metrics during performance benchmarking. 

## How
* Remove the cachebuster
* Remove the tmp job which frequently ran the CI on source-postgres
* Remove hack functions

### CODE REVIEW

**Comment by alafanechere** [comment]
Current dependencies on/for this PR:
* master
  * **PR #32427** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/32427?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/airbytehq/airbyte/32427?utm_source=stack-comment).

**Review by postamar — APPROVED** [review]
LGTM but please don't merge just yet I want to see the pretty graph in metabase go down over the weekend.

**Comment by alafanechere** [comment]
> LGTM but please don't merge just yet I want to see the pretty graph in metabase go down over the weekend.
The graph went down by 2mn (8mn) over the weekend

**Comment by postamar** [comment]
Yes it's very pretty! Thanks for indulging me.

**Pull request merged**
