### PR TITLE
add oracle to registry

### PR DESCRIPTION
**Pull request by cgardens**

### CODE REVIEW

**Comment by ericsgagnon** [comment]
@cgardens 

I'm not an expert in this, so I can't give a ton of feedback on if it's actually a connection configuration issue, but I've run into oracle connection timezone issues before as well. Have you tried setting ORA_SDTZ? In addition to common timzeone names, if the database's timezone is configured, I believe you can set it to 'DB_TZ' to just align the connection to the DB.
Otherwise, I think you can use timezone before establishing your connection.
TimeZone timeZone = TimeZone.getTimeZone("UTC");
TimeZone.setDefault(timeZone);
then drivermanager.getconnection...

**Comment by davinchia** [comment]
@cgardens I took a stab at this since I was also perplexed and wasn't too successful. 

You can take a look at the commit history to see what I tried.. all of which are from various stackoverflow answers.

One thing that did work for me was setting the env variable in the terminal before running the gradle command.

I ended up creating a [GCP Ubuntu](https://console.cloud.google.com/compute/instances?authuser=1&project=ab-analytics-308500&folder=&organizationId=) instance so I would not have to wait forever for the builds. It's powered off now, but feel free to use it for build purposes. The builds times were 5 mins on ubuntu vs 30 mins on Github.

**Pull request merged**
