### PR TITLE
[source-google-sheets] - Migrate to CDK v3.9.0

### PR DESCRIPTION
**Pull request by pnilan**
## What
- unpin on ^3
- bump minor version

## User Impact
- None

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by pnilan** [comment]
Reg test 1: https://github.com/airbytehq/airbyte/actions/runs/10011341788

**Comment by pnilan** [comment]
Reg Test 2: https://github.com/airbytehq/airbyte/actions/runs/10011748680

**Comment by pnilan** [comment]
Reg Test 3: https://github.com/airbytehq/airbyte/actions/runs/10011879757

**Review by brianjlai — APPROVED** [review]
no issues w/ the bump, but how come we're not bumping to `^3` plus?

**Pull request merged**
