### PR TITLE
Use new github action runner ami with 100 gb disk

### PR DESCRIPTION
**Pull request by tuliren**
This change is [Reviewable](https://reviewable.io/reviews/airbytehq/airbyte/9450)

### CODE REVIEW

**Comment by grubberr** [comment]
@tuliren any plans to merge this ?
I see that it really helps for 
"Airbyte CI" -> "Connectors Base: Build"
which constantly failed with `not enough space` error

**Comment by tuliren** [comment]
Oh, I did not realize that the connector base build passed on this PR.

This PR has one issue. It looks like the new AMI breaks `test` command. So I still need to look into that.

Will merge later today.

**Pull request merged**
