### PR TITLE
✨ Source LinkedIn Ads: Add new analytics streams

### LINKED ISSUE #26934: Source LinkedIn Ads: Is there any way to extract `impression_device_type` via LinkedIn Ads Marketing API?
### Topic

Request a dimension breakdown

### Revelant information

According to their **Ad Analytics API**, starting with the 202304 version, we should be able to get `IMPRESSION_DEVICE_TYPE` pivot, and the results will be grouped by the device type the ad made an impression on, such as MOBILE_APP and DESKTOP_WEB .

image

image
reference link: https://learn.microsoft.com/en-us/linkedin/marketing/integrations/ads-reporting/ads-reporting?view=li-lms-2023-05&tabs=http&#:~:text=IMPRESSION_DEVICE_TYPE

### PR DESCRIPTION
**Pull request by artem1205**
## What

Resolve
 https://github.com/airbytehq/airbyte/issues/26934

## How

add new streams:

- AdImpressionDeviceAnalytics
- AdMemberCompanySizeAnalytics
- AdMemberCountryAnalytics
- AdMemberJobFunctionAnalytics
- AdMemberJobTitleAnalytics,
- AdMemberIndustryAnalytics
- AdMemberSeniorityAnalytics
- AdMemberRegionAnalytics
- AdMemberCompanyAnalytics

## Recommended reading order
1. `streams.py`

## 🚨 User Impact 🚨

no breaking changes

## Pre-merge Actions
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-linkedin-ads test report (commit [`80b07ec5c1`](https://github.com/airbytehq/airbyte/pull/29175/commits/80b07ec5c15b406d66af460b6c17e572637e0dbf)) - ❌

⏲️  Total pipeline duration: 93mn09s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-linkedin-ads/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ✅        |
| QA checks                                                                  | ✅        |
| Code format checks                                                         | ❌        |
| Connector package install                                                  | ✅        |
| Build source-linkedin-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                 | ✅        |
| Acceptance tests                                                           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-linkedin-ads-analytics-stream/1691503943/80b07ec5c15b406d66af460b6c17e572637e0dbf/source-linkedin-ads/0.4.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:80b07ec5c15b406d66af460b6c17e572637e0dbf)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-linkedin-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-linkedin-ads test report (commit [`5c3347b3c9`](https://github.com/airbytehq/airbyte/pull/29175/commits/5c3347b3c985d0bd01848ff4533ce4c88d01d3b6)) - ❌

⏲️  Total pipeline duration: 88mn35s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-linkedin-ads/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ✅        |
| QA checks                                                                  | ✅        |
| Code format checks                                                         | ✅        |
| Connector package install                                                  | ✅        |
| Build source-linkedin-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                 | ✅        |
| Acceptance tests                                                           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-linkedin-ads-analytics-stream/1691511208/5c3347b3c985d0bd01848ff4533ce4c88d01d3b6/source-linkedin-ads/0.4.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:5c3347b3c985d0bd01848ff4533ce4c88d01d3b6)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-linkedin-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-linkedin-ads test report (commit [`b91b9bccff`](https://github.com/airbytehq/airbyte/pull/29175/commits/b91b9bccff3c6aba877c7a787800f5cb87acb9ea)) - ❌

⏲️  Total pipeline duration: 107mn11s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-linkedin-ads/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ✅        |
| QA checks                                                                  | ✅        |
| Code format checks                                                         | ✅        |
| Connector package install                                                  | ✅        |
| Build source-linkedin-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                 | ✅        |
| Acceptance tests                                                           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-linkedin-ads-analytics-stream/1691522739/b91b9bccff3c6aba877c7a787800f5cb87acb9ea/source-linkedin-ads/0.4.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b91b9bccff3c6aba877c7a787800f5cb87acb9ea)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-linkedin-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-linkedin-ads test report (commit [`20465e93df`](https://github.com/airbytehq/airbyte/pull/29175/commits/20465e93df787f1c29d8a20c8b3b8106706d4723)) - ❌

⏲️  Total pipeline duration: 30mn21s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-linkedin-ads/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ✅        |
| QA checks                                                                  | ✅        |
| Code format checks                                                         | ✅        |
| Connector package install                                                  | ✅        |
| Build source-linkedin-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                 | ✅        |
| Acceptance tests                                                           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-linkedin-ads-analytics-stream/1691576677/20465e93df787f1c29d8a20c8b3b8106706d4723/source-linkedin-ads/0.4.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:20465e93df787f1c29d8a20c8b3b8106706d4723)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-linkedin-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-linkedin-ads test report (commit [`8fe17dd453`](https://github.com/airbytehq/airbyte/pull/29175/commits/8fe17dd453dedc6e42099c126d5d13ac4ceb143f)) - ❌

⏲️  Total pipeline duration: 31mn42s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-linkedin-ads/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ✅        |
| QA checks                                                                  | ✅        |
| Code format checks                                                         | ✅        |
| Connector package install                                                  | ✅        |
| Build source-linkedin-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                 | ✅        |
| Acceptance tests                                                           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-linkedin-ads-analytics-stream/1691582655/8fe17dd453dedc6e42099c126d5d13ac4ceb143f/source-linkedin-ads/0.4.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8fe17dd453dedc6e42099c126d5d13ac4ceb143f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-linkedin-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-linkedin-ads test report (commit [`34666579fe`](https://github.com/airbytehq/airbyte/pull/29175/commits/34666579fe90843fdf68a164897d53439b9bd353)) - ✅

⏲️  Total pipeline duration: 30mn17s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-linkedin-ads/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| Connector version increment check                                          | ✅        |
| QA checks                                                                  | ✅        |
| Code format checks                                                         | ✅        |
| Connector package install                                                  | ✅        |
| Build source-linkedin-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                 | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-linkedin-ads-analytics-stream/1691585552/34666579fe90843fdf68a164897d53439b9bd353/source-linkedin-ads/0.4.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:34666579fe90843fdf68a164897d53439b9bd353)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-linkedin-ads test
```

**Review by bazarnov — APPROVED** [review]
LGTM!

**Comment by Escen13** [comment]
#26934 
Hi, I have encounter some issues in the `..ad_impression_device_analytics` table and hope you may check it out in the following.

I found that the data in `_airbyte_raw_ad_impression_device_analytics` is not consistent, e.g., some of the objects in the json data is missing. Please refer ss below:
image
the json data in 1 has 48 objects whereas the data in 2 only has 18 objects, as below:
[1]
image

[2]
image

I also noticed that there's an empty value in the device column (i.e., `pivotValues`), please refer the ss below:
image

Besides, I'm not sure if the value in the `pivotValues` object is missing, because I only get one record in one date, if not mistaken I should get 3 row in the same date.. please refer the ss below:
[Query result]
image

[Linkedin Campaign Manager]
image

Please look at the record on 5/29/2022, as you can see that I only get 'Mobile Web' on that day but I should get 3 device breakdown, i.e. 'Desktop Web', 'Mobile App', 'Mobile Web', which shown in the Linkedin Campaign Manager. The sum value of the device breakdown (e.g., Mobile Web) shown in the query is correct, the problem is the other device breakdown is missing. Other than that, I'm not sure if you noticed that the query result only show one record per date and If I'm not wrong, I should get 3 row per date.

Much appreciate if you could help identify the exact issue. Look forward to your feedback.

**Pull request merged**
