### PR TITLE
SAT: migrate to CDK

### PR DESCRIPTION
**Pull request by keu**
## What
Don't use base python docker-based build.

## How
*Describe the solution*

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

### CODE REVIEW

**Review by sherifnada — COMMENTED** [review]
Are there any imports needed to change?

**Comment by keu** [comment]
> Are there any imports needed to change?

@sherifnada nope, it was already using CDK

**Review by sherifnada — APPROVED** [review]

**Pull request merged**
