### PR TITLE
redelete connector dockerfiles

### PR DESCRIPTION
**Pull request by edgao**
connectors shouldn't (?) need explicit dockerfiles anymore. https://github.com/airbytehq/airbyte/pull/30743 attempted to delete them, but accidentally re-added some in a merge commit (https://github.com/airbytehq/airbyte/pull/30743/commits/0e946d2c88b0abe6b9aa66c312678420b85c1cd7). This PR just re-deletes those dockerfiles.

`find airbyte-integrations/connectors -name Dockerfile` still shows a lot of dockerfiles, and it's not clear to me why they need to remain. In the interest of making forward progress, I'm just deleting the ones that we tried to delete earlier.

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-github test report (commit [`8776bbbae6`](https://github.com/airbytehq/airbyte/pull/31228/commits/8776bbbae6abfcb50534d06b7198f08ab3f0243f)) - ❌

⏲️  Total pipeline duration: 42.64s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Connector package install                                     | ✅        |
| Build source-github docker image for platform(s) linux/x86_64 | ❌        |
| Code format checks                                            | ✅        |
| Validate metadata for source-github                           | ✅        |
| Connector version semver check                                | ✅        |
| Connector version increment check                             | ❌        |
| QA checks                                                     | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dockerfile_deletions/1696964708/8776bbbae6abfcb50534d06b7198f08ab3f0243f/source-github/1.4.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8776bbbae6abfcb50534d06b7198f08ab3f0243f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-google-ads test report (commit [`8776bbbae6`](https://github.com/airbytehq/airbyte/pull/31228/commits/8776bbbae6abfcb50534d06b7198f08ab3f0243f)) - ❌

⏲️  Total pipeline duration: 48.79s 

| Step                                                              | Result   |
|:------------------------------------------------------------------|:---------|
| Connector package install                                         | ✅        |
| Build source-google-ads docker image for platform(s) linux/x86_64 | ❌        |
| Code format checks                                                | ✅        |
| Validate metadata for source-google-ads                           | ✅        |
| Connector version semver check                                    | ✅        |
| Connector version increment check                                 | ❌        |
| QA checks                                                         | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dockerfile_deletions/1696964708/8776bbbae6abfcb50534d06b7198f08ab3f0243f/source-google-ads/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8776bbbae6abfcb50534d06b7198f08ab3f0243f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-mixpanel test report (commit [`8776bbbae6`](https://github.com/airbytehq/airbyte/pull/31228/commits/8776bbbae6abfcb50534d06b7198f08ab3f0243f)) - ❌

⏲️  Total pipeline duration: 30.87s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Connector package install                                       | ✅        |
| Build source-mixpanel docker image for platform(s) linux/x86_64 | ❌        |
| Code format checks                                              | ✅        |
| Validate metadata for source-mixpanel                           | ✅        |
| Connector version semver check                                  | ✅        |
| Connector version increment check                               | ❌        |
| QA checks                                                       | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dockerfile_deletions/1696964708/8776bbbae6abfcb50534d06b7198f08ab3f0243f/source-mixpanel/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8776bbbae6abfcb50534d06b7198f08ab3f0243f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mixpanel test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-pinecone test report (commit [`8776bbbae6`](https://github.com/airbytehq/airbyte/pull/31228/commits/8776bbbae6abfcb50534d06b7198f08ab3f0243f)) - ❌

⏲️  Total pipeline duration: 01mn29s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Connector package install                                            | ✅        |
| Build destination-pinecone docker image for platform(s) linux/x86_64 | ❌        |
| Code format checks                                                   | ✅        |
| Validate metadata for destination-pinecone                           | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ❌        |
| QA checks                                                            | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dockerfile_deletions/1696964708/8776bbbae6abfcb50534d06b7198f08ab3f0243f/destination-pinecone/0.0.15/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8776bbbae6abfcb50534d06b7198f08ab3f0243f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-pinecone test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-qdrant test report (commit [`8776bbbae6`](https://github.com/airbytehq/airbyte/pull/31228/commits/8776bbbae6abfcb50534d06b7198f08ab3f0243f)) - ❌

⏲️  Total pipeline duration: 01mn44s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Connector package install                                          | ✅        |
| Build destination-qdrant docker image for platform(s) linux/x86_64 | ❌        |
| Code format checks                                                 | ✅        |
| Validate metadata for destination-qdrant                           | ✅        |
| Connector version semver check                                     | ✅        |
| Connector version increment check                                  | ❌        |
| QA checks                                                          | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dockerfile_deletions/1696964708/8776bbbae6abfcb50534d06b7198f08ab3f0243f/destination-qdrant/0.0.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8776bbbae6abfcb50534d06b7198f08ab3f0243f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-qdrant test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-chroma test report (commit [`8776bbbae6`](https://github.com/airbytehq/airbyte/pull/31228/commits/8776bbbae6abfcb50534d06b7198f08ab3f0243f)) - ❌

⏲️  Total pipeline duration: 01mn45s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Connector package install                                          | ✅        |
| Build destination-chroma docker image for platform(s) linux/x86_64 | ❌        |
| Code format checks                                                 | ✅        |
| Validate metadata for destination-chroma                           | ✅        |
| Connector version semver check                                     | ✅        |
| Connector version increment check                                  | ❌        |
| QA checks                                                          | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dockerfile_deletions/1696964708/8776bbbae6abfcb50534d06b7198f08ab3f0243f/destination-chroma/0.0.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8776bbbae6abfcb50534d06b7198f08ab3f0243f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-chroma test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-google-analytics-data-api test report (commit [`8776bbbae6`](https://github.com/airbytehq/airbyte/pull/31228/commits/8776bbbae6abfcb50534d06b7198f08ab3f0243f)) - ❌

⏲️  Total pipeline duration: 38.86s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Connector package install                                                        | ✅        |
| Build source-google-analytics-data-api docker image for platform(s) linux/x86_64 | ❌        |
| Code format checks                                                               | ✅        |
| Validate metadata for source-google-analytics-data-api                           | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ❌        |
| QA checks                                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dockerfile_deletions/1696964708/8776bbbae6abfcb50534d06b7198f08ab3f0243f/source-google-analytics-data-api/2.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8776bbbae6abfcb50534d06b7198f08ab3f0243f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-analytics-data-api test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-milvus test report (commit [`8776bbbae6`](https://github.com/airbytehq/airbyte/pull/31228/commits/8776bbbae6abfcb50534d06b7198f08ab3f0243f)) - ❌

⏲️  Total pipeline duration: 01mn17s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Connector package install                                          | ✅        |
| Build destination-milvus docker image for platform(s) linux/x86_64 | ❌        |
| Code format checks                                                 | ✅        |
| Validate metadata for destination-milvus                           | ✅        |
| Connector version semver check                                     | ✅        |
| Connector version increment check                                  | ❌        |
| QA checks                                                          | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_dockerfile_deletions/1696964708/8776bbbae6abfcb50534d06b7198f08ab3f0243f/destination-milvus/0.0.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8776bbbae6abfcb50534d06b7198f08ab3f0243f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-milvus test
```

**Review by alafanechere — CHANGES_REQUESTED** [review]
Python connector Dockerfile can't be deleted unless the connector declares the baseImage version it's using ([eg](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-auth0/metadata.yaml#L11)).
Removing python connector dockerfile is part of [this epic](https://github.com/airbytehq/airbyte/issues/30231). I'm actively working on it. I'll take care about documenting the migration process once the new build process is 💯 ready.

**Pull request closed without merging**
