### PR TITLE
`AirbyteEstimateTraceMessage` and UI sync Estimates - Progress Bars

### PR DESCRIPTION
**Pull request by evantahler**
HACK THE PLANET!

Closes https://github.com/airbytehq/airbyte-internal-issues/issues/1095

## Connector Notes
* Since we didn't really publish a new version of the CDK, we can't use the built-in types to generate our new message... so we are hacking by building up the `AirbyteEstimateTraceMessage` dict manually
* For this to run, we needed to publish a hacky release of the source-faker connector.  Here are the steps:

```
docker buildx build . --platform "linux/amd64,linux/arm64" --tag airbyte/source-faker:hack-day-2022  --push
```

The image to use is `airbyte/source-faker:hack-day-2022`

## Logging Notes:

You can have the worker log all AirbyteMessages it gets to the console with `LOG_CONNECTOR_MESSAGES=true`, e.g. 
```
LOG_CONNECTOR_MESSAGES=true VERSION=dev docker-compose -f docker-compose.yaml -f docker-compose.debug.yaml up
```

### CODE REVIEW

**Comment by sherifnada** [comment]
@evantahler do you want a review on this?

**Comment by evantahler** [comment]
@sherifnada not yet!

**Review by jdpgrailsdev — APPROVED** [review]
:shipit: conditionally that changing the case of the enum values doesn't cause a breaking change in existing code (e.g. does this require a protocol version bump?)

**Comment by evantahler** [comment]
@davinchia think we should close this PR now that the "real" PRs are almost done?

**Comment by davinchia** [comment]
Yeap. Let's close this for cleanliness.

I have 2 more PRs after https://github.com/airbytehq/airbyte/pull/19814/files. However can still use this as a reference as we close.

**Pull request closed without merging**
