### PR TITLE
Source Amazon Ads: remove "report_wait_timeout", "report_generation_max_retries" from config

### LINKED ISSUE #18948: Source Amazon Ads: Deprecate report_wait_timeout and report_generation_max_retries fields
## Tell us about the problem you're trying to solve
The report_wait_timeout and report_generation_max_retries configuration fields for the Amazon Ads source are used to configure how long the connector will wait for the report to be generated, and how often we'll retry in case of failures.

Both of these concerns are implementation details the users shouldn't have to worry about. Setting the wait timeout too low can lead to [on-call issues due to the endpoint being intermittently slow](https://github.com/airbytehq/oncall/issues/899).

## Describe the solution you’d like
We should set the default values of these two fields to the max allowed and remove the fields from the spec. This will lower the mental load on the user, and will make the connector more resistant to the endpoint being slow at times.

### PR DESCRIPTION
**Pull request by grubberr**
Signed-off-by: Sergey Chvalyuk <grubberr@gmail.com>

## What
1. Remove "report_wait_timeout", "report_generation_max_retries" - there is not reason to bother customer with this internal settings
2. get `REPORT_WAIT_TIMEOUT=180`, `REPORT_GENERATION_MAX_RETRIES=5` from environment if variable are not defined get default values.
3. Change "get_error_display_message" message

## Recommended reading order
1. `x.java`
5. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [x] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [x] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Review by girarda — APPROVED** [review]

**Comment by grubberr** [comment]
/publish connector=connectors/source-amazon-ads run-tests=false

**Pull request merged**
