### PR TITLE
Improve SubstreamResumableFullRefreshCursor performance

### PR DESCRIPTION
**Pull request by szubster**
## What
After https://github.com/airbytehq/airbyte/pull/42966 performance of github source dropped dramatically

## How
Put partition information in values of `_per_partition_state` so it does not have to be deserialised every time.

## Review guide
1. substream_resumable_full_refresh_cursor.py

## User Impact
Better performance

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by szubster** [comment]
It's hard for me to work on numbers right now, but I can bring them if needed.
The `_to_dict` method is unused now. I can remove it if needed.
Similar functionality is in `per_partition_cursor.py` in declarative streams package.
I can work on it in this PR, if you like the direction here.

**Comment by szubster** [comment]
@girarda Could you also take a look at this one?

**Comment by szubster** [comment]
@brianjlai What are your thoughts?
The `to_partition` method (but in a declarative stream) currently can take >50 percent of CPU time on some streams of jira source (transitions in a case I measured).
I can take a stab on improving speed of incremental cursor in declarative source also, if you like the direction.

**Comment by szubster** [comment]
@brianjlai @girarda I am going on vacation and might be not responding for next two weeks.
Please take a look and share your opinion on the direction.

**Comment by szubster** [comment]
@brianjlai @girarda  pinging :)

**Comment by szubster** [comment]
@brianjlai @girarda any interest here?

**Comment by williamkaper** [comment]
+1 on wanting to see these performance improvements reviewed and approved.

**Comment by girarda** [comment]
I need to defer to @brianjlai and @maxi297

**Comment by brianjlai** [comment]
@szubster so sorry for the very long delay on getting this reviewed. Things look good to me and thank you for the contribution! I tested this a little bit locally and unit testing didn't indicate regressions. I'll kick off our CI build and verify our formatting

**Review by brianjlai — APPROVED** [review]

**Comment by brianjlai** [comment]
Thank you for the contribution @szubster ! Tests are all 🟢 and did a little more testing against an existing connector. Going to merge this in now

**Comment by szubster** [comment]
Superb. I will try to create a separate pr fro declarative streams then.

pt., 11 paź 2024, 01:39 użytkownik Brian Lai ***@***.***>
napisał:

**Comment by szubster** [comment]
Do you have maybe some number to share?

pt., 11 paź 2024, 11:48 użytkownik Tomasz Szuba ***@***.***>
napisał:

**Pull request merged**
