### PR TITLE
Source SFTP Bulk: update spec.json schema

### PR DESCRIPTION
**Pull request by ChristoGrab**
## What
The input fields for the SFTP Bulk source connector had a few inconsistencies in terms of what fields were required/optional.

1. Both auth methods were hidden in the collapsible optional fields section, with no indication of an "either-or" choice.
2. Folder Path was titled as optional, but marked as required in the json schema.
3. File Type was hidden in optional fields. This one is a bit less straightforward. A user can technically complete the connection without configuring this field, since it has a default value of CSV.  However, a user who wants to replicate JSON files could miss this option if they choose not to open the optional fields or closely read the documentation, resulting in a seeming silent failure.

old-sftp-bulk-layout

## How
1. Originally I intended to nest the password and primary key in a `oneOf` array in the json schema. However, my understanding of how this is typically handled is that they would need to be values of a parent object (say "auth" or "credentials"), which is what the connector's logic would use as a parameter when sending the connection request to the server. This is how the standard SFTP connector seems to operate.

In this Bulk connector though, `password` and `pkey` are distinct attributes of the `SFTPClient` Class, and are treated individually as optional methods of authentication (ie, you are able to provide one of either or both as parameters). So, I instead moved both the `password` and `private_key` properties in the schema into an "Authentication" group, and added an instruction to select one method in the title.  I also created a "Connection Parameters" group for the `Username`, `Host Address` and `Port` fields so they wouldn't be superseded in the order by the `Authentication` group.

It's not an ideal solution, but making changes to the actual connector's code felt like it would step outside the scope of the docs project, so this is a potential temporary fix. Let me know if there's a different approach you'd recommend!

2. I removed `folder_path` from the list of required properties. There is logic to handle this field being empty in `client.py`:

```py
if prefix is None or prefix == "":
    prefix = "."
```

So I'm confident this was just a mixup and can be safely made optional. I didn't have any issues leaving this field blank in the tests I ran.

3. I marked `file_type` as required to ensure all users encounter it during the setup. Since there is no way to leave this field blank, I'm confident it shouldn't be able to have any effect on existing users' connections.

4. Lastly I added the usual small fixes to titles and descriptions. I mostly pulled these from the changes we made to the SFTP.

Here's what the new layout looks like:

new-sftp-bulk-layout

## Recommended reading order
1. `spec.json`
2. Everything else

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-sftp-bulk test report (commit [`ad85339d73`](https://github.com/airbytehq/airbyte/pull/28579/commits/ad85339d73ee1a7be52c114e6d6a120aefc4ff96)) - ❌

⏲️  Total pipeline duration: 03mn55s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-sftp-bulk/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-sftp-bulk docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Integration tests                                                       | ❌        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sftp-bulk-spec-update/1689978214/ad85339d73ee1a7be52c114e6d6a120aefc4ff96/source-sftp-bulk/0.1.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-sftp-bulk test
```

**Comment by octavia-squidington-iii** [comment]
##  source-sftp-bulk test report (commit [`cea037d476`](https://github.com/airbytehq/airbyte/pull/28579/commits/cea037d476857ef1cee6ed8f2e32235bb73d69ac)) - ❌

⏲️  Total pipeline duration: 07mn31s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-sftp-bulk/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-sftp-bulk docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Integration tests                                                       | ❌        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sftp-bulk-spec-update/1690225987/cea037d476857ef1cee6ed8f2e32235bb73d69ac/source-sftp-bulk/0.1.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-sftp-bulk test
```

**Review by sherifnada — APPROVED** [review]
LGTM! Working on fixing the sandbox issue

**Comment by octavia-squidington-iii** [comment]
##  source-sftp-bulk test report (commit [`5829d551d9`](https://github.com/airbytehq/airbyte/pull/28579/commits/5829d551d94f69222aac6961c486f700cbbc8a02)) - ❌

⏲️  Total pipeline duration: 07mn06s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-sftp-bulk/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ❌        |
| Connector package install                                               | ✅        |
| Build source-sftp-bulk docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Integration tests                                                       | ❌        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sftp-bulk-spec-update/1690253666/5829d551d94f69222aac6961c486f700cbbc8a02/source-sftp-bulk/0.1.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-sftp-bulk test
```

**Comment by octavia-squidington-iii** [comment]
##  source-sftp-bulk test report (commit [`9232a08a75`](https://github.com/airbytehq/airbyte/pull/28579/commits/9232a08a75959cd4df3d450d281cd9794c5700f3)) - ❌

⏲️  Total pipeline duration: 10mn06s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-sftp-bulk/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-sftp-bulk docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Integration tests                                                       | ✅        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/sftp-bulk-spec-update/1690315184/9232a08a75959cd4df3d450d281cd9794c5700f3/source-sftp-bulk/0.1.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-sftp-bulk test
```

**Pull request closed without merging**
