### PR TITLE
source-mssql: enable heartbeats and checkpointing

### PR DESCRIPTION
**Pull request by postamar**
The implementation of heartbeat support for MS SQL Server is very much not mysterious. 

This is not ready to merge as there is still at least one bug out there: `CdcMssqlSourceTest.testRecordsProducedDuringAndAfterSync` fails because the second `read` contains a duplicate record (namely, the last record of the previous batch) when heartbeats are enabled. I haven't been able to fix this. All I've noticed is that the state that's passed to the second `read` is different when heartbeats are enabled than when they're not.

Another noticeable difference, probably related to the state difference: with heartbeats enabled (i.e. `heartbeat.interval.ms` is set to > 0), the first `read` ends with a heartbeat event.

### CODE REVIEW

**Comment by postamar** [comment]
Current dependencies on/for this PR:
* `master`
  * **PR #33510** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33510?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #33511** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/33511?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/airbytehq/airbyte/33511?utm_source=stack-comment).

**Comment by postamar** [comment]
This PR will have to wait until we implement initial snapshots ourselves for source-mssql.

I'm finally beginning to understand what's going on here. For a reason that's still mysterious to me, when heartbeats are enabled the initial `read` completes with a debezium state (in the offset file) that does not include fields indicating the completion of the snapshot. This causes the Debezium Engine in the subsequent `read` to include the record at the starting LSN, instead of skipping to the next WAL offset. This effectively reads that record a second time.

The solution is to skip debezium's snapshotting entirely. We mean to implement it ourselves anyway. After that, let's set `snapshot.mode` to `schema_only` in the debezium properties at all times and the problem should never manifest itself.

cc @rodireich @xiaohansong

**Comment by postamar** [comment]
You're right that at that point we won't need debezium to capture a snapshot anymore. However we still need to capture all the schema changes somehow, at least that was the case for mysql: https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/debezium/internals/mysql/MySqlDebeziumStateUtil.java#L234

**Comment by xiaohansong** [comment]
I read the code more carefully - it appears I understood the mysql workflow wrong. The same problem occurs in mssql too - to hack debezium and make it run without incremental sync, we need to provide offset file and schema file. 

@akashkulk can keep me honest, but here's my finding: in Mysql, the solution is: 

1) run debezium with `snapshot.mode=schema_recovery` to capture the schema file; then load the result into state
2) hack the offset file by checking the latest binlog directly from mysql; 
3) run mysql initial load with our own recoverable PK query
4) then run debezium with incremental sync mode

Borrowing this idea and apply it to MSSQL - we indeed need `snapshot.mode=schema_only` property and run a mini schema only "snapshot" before running any syncs.

**Pull request closed without merging**
