### PR TITLE
Source Typeform: certify to GA

### PR DESCRIPTION
**Pull request by arsenlosenko**
## What
Updating releaseStage for Source Typeform in scope of this epic:
https://github.com/airbytehq/airbyte/issues/26255

## How
* Updated `releaseStage` in `metadata.yml` from `beta` to `generally_available`
* Add high strictness

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-typeform test report (commit [`1cc85743d3`](https://github.com/airbytehq/airbyte/pull/27836/commits/1cc85743d32761df04ab8e3ecc022491b8be70d7)) - ✅

⏲️  Total pipeline duration: 03mn15s 

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-typeform/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| QA checks                                                              | ✅        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-typeform docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_source-typeform-to-ga/1688050498/1cc85743d32761df04ab8e3ecc022491b8be70d7/source-typeform/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-typeform test
```

**Review by lazebnyi — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-typeform test report (commit [`f78c246e1a`](https://github.com/airbytehq/airbyte/pull/27836/commits/f78c246e1adb253fdfc88d5e74a8d647ac5e5f5b)) - ✅

⏲️  Total pipeline duration: 02mn34s 

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-typeform/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| QA checks                                                              | ✅        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-typeform docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_source-typeform-to-ga/1688109470/f78c246e1adb253fdfc88d5e74a8d647ac5e5f5b/source-typeform/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-typeform test
```

**Comment by octavia-squidington-iii** [comment]
##  source-typeform test report (commit [`91d2a7c1b2`](https://github.com/airbytehq/airbyte/pull/27836/commits/91d2a7c1b26c0d65a33ab00f6b62b1f9400d56e0)) - ✅

⏲️  Total pipeline duration: 02mn42s 

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-typeform/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| QA checks                                                              | ✅        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-typeform docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_source-typeform-to-ga/1688111711/91d2a7c1b26c0d65a33ab00f6b62b1f9400d56e0/source-typeform/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-typeform test
```

**Comment by octavia-squidington-iii** [comment]
##  source-typeform test report (commit [`5504b1b7aa`](https://github.com/airbytehq/airbyte/pull/27836/commits/5504b1b7aa5d0764d021798c1eb1c494ca19ffe7)) - ✅

⏲️  Total pipeline duration: 02mn44s 

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-typeform/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| QA checks                                                              | ✅        |
| Code format checks                                                     | ✅        |
| Connector package install                                              | ✅        |
| Build source-typeform docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Acceptance tests                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_source-typeform-to-ga/1688113405/5504b1b7aa5d0764d021798c1eb1c494ca19ffe7/source-typeform/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-typeform test
```

**Pull request merged**
