### PR TITLE
(Draft) Update GitHbub JSON Schema with GPT

### PR DESCRIPTION
**Pull request by aaronsteers**
This is an experiment in using GPT to update our JSON schema annotations, especially 'description' properties and foreign key annotations.

ChatGPT convo: https://chat.openai.com/share/c9a65430-d4cb-4dd7-9871-1dd2593d4907

### CODE REVIEW

**Comment by aaronsteers** [comment]
A few observations on this first draft. cc @flash1293 

1. There are other foreign keys that appear to be missed. Probably with some prompting the GPT can fix the omissions.
2. (Nit.) The added `description` field should ideally be rendered before the `properties` declaration of subnodes.

Overall, descriptions look good.

**Comment by flash1293** [comment]
Some thoughts from an information-theoretical perspective:

* If the descriptions are created solely based on the existing schema (plus a static prompt), then they have to be derived from the schema itself plus whatever "internal" knowledge the LLM has
* When these descriptions are used for SQL generation by an LLM, it has access to the schema via the table structure plus the internal knowledge of the LLM
* Assuming the same LLM is used for description generation and SQL generation (e.g. OpenAI), no net-new information is injected into the system, it just becomes a special prompting technique ("describe the schema in your own words, then use your own description to generate the SQL query", but in two different places in the pipeline)
* While such a prompting technique can help a little bit, there's a certain upper limit of the performance enhancements that can be achieved this way. By giving the description-generating LLM access to the docs via RAG, we can add "real" new information to the process that should make these descriptions more relevant.

Or did you imagine this to be an "assistant" use case, where the LLM comes up with the first draft and then the user edits and fixes issues (which is the actual information add)?

**Comment by zurferr** [comment]
@flash1293 great comment. I thought a lot about that and have some additional thoughts on why it's useful to have this "self-feeding" documentation.

- using LLMs to generate documentation is usually a win because you invested compute to present the information with more clarity
- it's easier for the human in the loop to see and correct "understanding" problems of the LLM

that being said I love the idea to enrich the generation process with some ground truth/fundamental documentation (e.g. docs from the API that were used to pull the data)


@aaronsteers the documentation in general looks good. I like that FK relationships are also modelled. However, as an outside consumer I'm not sure how I would get access to it. Will this be propaged to the target system, e.g. as Snowflake comments and constraints?

**Comment by natikgadzhi** [comment]
I'll close this. This is pretty cool, and @bleonard clearly got the memo and started the whole script that automates fetching descriptions using chatGPT API.

See [these](https://github.com/airbytehq/airbyte/pulls?q=is%3Aopen+is%3Apr+label%3Aautopull) for output.

**Pull request closed without merging**
