### PR TITLE
Remove duplicate S3 regions from destination specs

### PR DESCRIPTION
**Pull request by evantahler**

### CODE REVIEW

**Review by JonsSpaghetti — APPROVED** [review]
Ty!

**Comment by evantahler** [comment]
As expected, the redshift tests pass (yay!), but databricks and iceberd don't.  That's ok.

**Review by gisripa — APPROVED** [review]

**Review by octavia-approvington — APPROVED** [review]

**Comment by octavia-approvington** [comment]
Approve this <br/> imagine the commander saying yes

**Pull request merged**
