### PR TITLE
🎉 Source Github: use GraphQL for `pull_request_stats` stream

### PR DESCRIPTION
**Pull request by grubberr**
Signed-off-by: Sergey Chvalyuk <grubberr@gmail.com>

## What
Trying to fix this https://github.com/airbytehq/alpha-beta-issues/issues/34

OLD REST API implementation of `pull_request_stats` stream did 1 HTTP request for 1 record because it needed [detailed-representations](https://docs.github.com/en/github-ae@latest/rest/overview/resources-in-the-rest-api#detailed-representations) (a large payload) of Object

From github [docs](https://docs.github.com/en/graphql/guides/migrating-from-rest-to-graphql):

Determining if a pull request is `mergeable` requires retrieving each pull request individually for its [detailed representation](https://docs.github.com/en/github-ae@latest/rest/overview/resources-in-the-rest-api#detailed-representations) (a large payload) and checking whether its mergeable attribute is true or false

## How
With GraphQL, we can retrieve all detailed attributes for multiple pull requests with 1 HTTP query.

SCHEMA MIGRATION:

**FIELDS REMOVED**:
rebaseable
mergeable_state
merged_by.events_url
merged_by.followers_url
merged_by.following_url
merged_by.gists_url
merged_by.gravatar_id
merged_by.organization
merged_by.organizations_url
merged_by.received_events_url
merged_by.repos_url
merged_by.starred_url
merged_by.subscriptions_url
merged_by.url

**FIELDS ADDED**:
can_be_rebased
merge_state_status

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [x] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [x] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [x] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Review by arsenlosenko — APPROVED** [review]

**Review by arsenlosenko — CHANGES_REQUESTED** [review]
Seems like there are no tests to cover new GraphQL logic, at least I cannot find them here, can you please specify if this new change covered by tests?

**Review by arsenlosenko — APPROVED** [review]
Checked the test coverage for this stream, looks like it is covered, so the PR is OK.

**Review by lazebnyi — APPROVED** [review]

**Review by evantahler — APPROVED** [review]
I love any PR that makes the rate limits go further!  I see that other reviewers already checked that existing test coverage is sufficient, so 👍

**Pull request merged**
