### PR TITLE
🐛 Destination Meilisearch: fix incomplete data indexing

### LINKED ISSUE #19205: Destination Meilisearch: incomplete data indexed
## Environment
- **Airbyte version**:  0.40.18 
- **OS Version / Instance**: macOs
- **Deployment**: Docker
- **Source Connector and version**: MySQL v1.0.11 
- **Destination Connector and version**: Meilisearch v1.0.0 
- **Step where error happened**: Sync job (although it says 'succeeded')

## Current Behavior
The operation appears as successful: "Sync Succeeded" but only one table of my database is synced (the first on the list). 
All the indexes are created in Meilisearch (each corresponding to a MySQL table) but only one contains documents.
I have checked Meilisearch tasks, and only one task of type `documentAdditionOrUpdate` exists.

## Expected Behavior
All data should have been indexed in Meilisearch.

## Logs

[airbyte_sync_4a59f152_262a_40ed_b27a_83f029b8a05e_logs_1.txt](https://github.com/airbytehq/airbyte/files/9969485/airbyte_sync_4a59f152_262a_40ed_b27a_83f029b8a05e_logs_1.txt)

## Steps to Reproduce
1. Create a connexion between MySQL and Meilisearch
2. Try to sync several tables of a database
3. When sync says 'succeeded' check Meilisearch, all indexes corresponding to the tables have been created, but only one contains documents. Check Meilisearch tasks, only one documentAddition task exists.

### PR DESCRIPTION
**Pull request by alallema**
## What
Even if all the indexes were created in Meilisearch, only one was correctly synchronized with its data. 
Closes #19205

## How
- Removing the message loop from the configured_catalog stream loop
- Add debug log
- Fix typo from `steam_name` to `stream_name`
- Move the writing buffer from Class to initialization of the Class
- Add a method for flushing all streams at once
- Remove the `wait_for_task` method from the code
- Adapt the tests

## Recommended reading order
1. `destination.py`
2. `writer.py`
3. `unit_test.py`
4. `meilisearch.md`

## 🚨 User Impact 🚨
I hope none other than that it should work properly.
Bump versioning as Patch: `1.0.0` to `1.0.1` due to simple bug fixes.

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by gmanninglive** [comment]
Hey @alallema I don't want to step on your toes on this. I ran into this problem myself and for some reason missed the gh issue and this PR :sweat_smile: 

I've created a solution as well, taking a slightly different approach, that I think is a bit simpler. You can see in this PR on my fork https://github.com/gmanninglive/airbyte/pull/1

Anyway I fully endorse this fix being released as it's an annoying bug :bug:

**Comment by alallema** [comment]
Hi @gmanninglive,
No worries, on the contrary, thanks for trying to fix it too 😄 
And I agree, this bug is annoying 😞

**Comment by marcosmarxm** [comment]
Sorry for the long delay in getting this reviewed and merged. Our team is currently finishing the August Hackathon review contributions over the next two weeks, and after that, we will return to the community backlog.

**Comment by marcosmarxm** [comment]
Hello @alallema I'll start the review during this week. Sorry the lack of updates. Thanks for the patience.

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
