### PR TITLE
fix connector base versioning

### PR DESCRIPTION
**Pull request by jrhizor**
Our Python connectors have not picked up changes from the bases. This leads to problems like JSON decoding errors if a configured catalog has something like primary key configuration which wasn't present in an older base version.

This PR changes everything to use versions and will require testing/publishing all Python-based connectors.

### CODE REVIEW

**Comment by jrhizor** [comment]
My plan is to serially run the following slash commands:
```
/publish connector=bases/airbyte-protocol
/publish connector=bases/base-python
/publish connector=bases/base-singer
/publish connector=bases/base-python
/publish connector=bases/base-python-test
/publish connector=bases/base-normalization
/publish connector=connectors/source-exchangeratesapi-singer
```

Then I'll bump the version on the demo instance for exchangeratesapi and check to see if it works properly with PK configuration. If so, I'll work through the rest of these.

**Review by cgardens — APPROVED** [review]
you are a hero.

**Comment by jrhizor** [comment]
I manually deleted the images I pushed up to this point so they can pick up new versions from  https://github.com/airbytehq/airbyte/pull/2726/commits/9ede7f627b075e9ec0943fc5b4e0ff4be45eb3fd, which is the piece that is truly responsible for this problem.

**Review by michel-tricot — APPROVED** [review]

**Comment by jrhizor** [comment]
Yay! It fixed the problem with exchangeratesapi.

**Comment by jrhizor** [comment]
/publish connector=connectors/source-google-workspace-admin-reports

**Comment by jrhizor** [comment]
Looks like all pushed except for:
- [ ] source-mixpanel-singer
- [ ] source-zendesk-support-singer
- [ ] source-greenhouse
- [ ] source-facebook-marketing
- [ ] source-googleanalytics-singer
- [ ] source-salesforce-singer
- [ ] source-google-adwords-singer

**Pull request merged**
