### PR TITLE
🎉 New Source: Sentry

### PR DESCRIPTION
**Pull request by koji-m**
## What
* Add new source Sentry
* Participating in hacktoberfest-2021 https://github.com/airbytehq/hacktoberfest-2021/issues/9
* This PR closes https://github.com/airbytehq/airbyte/issues/5692

## How

Added support for the following streams:

* Events
* Issues
* ProjectDetail (for check_connection only)

## Recommended reading order
1. bootstrap.md
1. spec.json
1. Schemas under schemas/*.json
1. source.py
1. streams.py

### Integration Test
screenshot 2021-10-12 23 33 24

### Unit Test
screenshot 2021-10-12 21 46 03

#### Community member or Airbyter
   
- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated 
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/SUMMARY.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [x] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [x] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

### CODE REVIEW

**Review by harshithmullapudi — CHANGES_REQUESTED** [review]

**Comment by harshithmullapudi** [comment]
Also can you run `./gradlew format`

**Review by harshithmullapudi — CHANGES_REQUESTED** [review]

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
small comments, but overall great work! @harshithmullapudi execute tests and makes sure it's passing CI (format and tests)

**Review by marcosmarxm — APPROVED** [review]
Congratulations for this work! @koji-m LGTM @harshithmullapudi please submit the test/publish and merge this contirbution.

**Comment by harshithmullapudi** [comment]
@koji-m is this resolved and are test cases passing in local ?

**Comment by koji-m** [comment]
Not yet resolved, but if https://github.com/airbytehq/airbyte/pull/7491 is merged, I would assume the test case will pass. I'll let you know when the test is complete.

**Comment by avida** [comment]
@koji-m  #7491 merged, please check it out

**Comment by koji-m** [comment]
Thank you @avida .
@harshithmullapudi I merged master and passed source-acceptance-test in local. Would you check it out again?

**Comment by karinakuz** [comment]
Examples of issue and event are added, tested APIs for:
- evens https://sentry.io/api/0/projects/airbyte-09/airbyte-09/events/
- issues https://sentry.io/api/0/projects/airbyte-09/airbyte-09/issues/
- project details https://sentry.io/api/0/projects/airbyte-09/airbyte-09/

**Comment by unity** [comment]
OneSignal is now a duplicate source, prevents usage.

https://github.com/airbytehq/airbyte/blob/3928c0c7e7739cc59ef1229421ed86b0c022b666/airbyte-config/init/src/main/resources/seed/source_definitions.yaml#L604

https://github.com/airbytehq/airbyte/blob/3928c0c7e7739cc59ef1229421ed86b0c022b666/airbyte-config/init/src/main/resources/seed/source_definitions.yaml#L355

**Comment by koji-m** [comment]
Sorry for the omission in the confirmation when merging master into this PR. I'll thoroughly check for conflicts.

**Pull request merged**
