### PR TITLE
Source Postgres: Fix not being able to configure wal2json plugin

### PR DESCRIPTION
**Pull request by edgao**
https://github.com/airbytehq/airbyte/pull/18779/files#diff-144a4a0053518cdd47b47a03ce984697ca4081a3d49e8d70505915ab7650dadaL266-R250 accidentally switched the `plugin` config option to `const: pgoutput`. Switch it back to `default`, assuming it still passes SATs.

### CODE REVIEW

**Comment by smartpierre** [comment]
Hi, is this why I get these errors on my Postgresql syncs ? If yes, how can I fix ? 

```
2022-12-01 18:31:04 INFO i.a.v.j.JsonSchemaValidator(test):130 - JSON schema validation failed. 
errors: $.method: must be a constant value Standard
2022-12-01 18:31:04 INFO i.a.v.j.JsonSchemaValidator(test):130 - JSON schema validation failed. 
errors: $.plugin: must be a constant value pgoutput
2022-12-01 18:31:04 INFO i.a.v.j.JsonSchemaValidator(test):130 - JSON schema validation failed. 
errors: $.method: does not have a value in the enumeration [Standard]
```

Here the source configuration in Airbyte database :

```
{
    "host": "redacted",
    "port": 5432,
    "database": "redacted",
    "password": {
        "_secret": "redacted"
    },
    "username": "airbyte",
    "replication_method": {
        "method": "CDC",
        "plugin": "wal2json",
        "publication": "airbyte_publication_dataupload",
        "replication_slot": "airbyte_replication_slot_dataupload"
    }
}
```

Best regards, Pierre.

**Comment by edgao** [comment]
@smartpierre yeah, that sounds related. As a workaround, I think you can downgrade source-postgres to 1.0.23. But also I'm hoping to get this PR merged in the next couple days, if you're ok with waiting til then.

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:  we should probably move the system-stubs version into the dependency catalog so we can update it in one place, but that can happen in a follow on PR.

**Review by akashkulk — APPROVED** [review]
Thanks for the refactor!

**Comment by edgao** [comment]
there's some unrelated test failures about `check` error messages. @akashkulk lmk if you want me to extract the system-stubs into a separate PR to get it merged earlier, otherwise I'll just bundle all the test fixes into this one PR

**Comment by akashkulk** [comment]
> there's some unrelated test failures about `check` error messages. @akashkulk lmk if you want me to extract the system-stubs into a separate PR to get it merged earlier, otherwise I'll just bundle all the test fixes into this one PR

If it's a quick fix, we can do it in the same PR if that's more convenient for you. If it might take longer (e.g. >3 hrs), could you break it up? This is blocking merging PRs for some folks on the team.

**Comment by edgao** [comment]
tests are broken after https://github.com/airbytehq/airbyte/pull/19711 so publish is blocked regardless, but I'll make a separate PR for the system-stubs stuff.

**Comment by edgao** [comment]
tagged you on https://github.com/airbytehq/airbyte/pull/20026

**Comment by edgao** [comment]
@smartpierre - `source-postgres:1.0.31` has also been released, so you can upgrade to the latest version and it will include this fix.

**Comment by smartpierre** [comment]
Hello @edgao we updated airbyte and our connectors, however, now **it doesn't block** the execution, but I can still see the errors.
Here's the output from one of our connections : 

```
2022-12-19 14:26:17 INFO i.a.v.j.JsonSchemaValidator(test):130 - JSON schema validation failed. 
errors: $.method: must be a constant value Standard
2022-12-19 14:26:17 INFO i.a.v.j.JsonSchemaValidator(test):130 - JSON schema validation failed. 
errors: $.access_token: is missing but it is required, $.refresh_token: is missing but it is required
2022-12-19 14:26:17 INFO i.a.v.j.JsonSchemaValidator(test):130 - JSON schema validation failed. 
errors: $.private_key: is missing but it is required
2022-12-19 14:26:17 INFO i.a.v.j.JsonSchemaValidator(test):130 - JSON schema validation failed. 
errors: $.password: object found, string expected
2022-12-19 14:26:17 INFO i.a.v.j.JsonSchemaValidator(test):130 - JSON schema validation failed. 
errors: $.method: does not have a value in the enumeration [Standard]
```

Airbyte version : 0.40.26
Postgresql source : 1.0.34
Snowflake destination : 0.4.40

Hope that helps, thanks for the fix 😄

**Comment by smartpierre** [comment]
No, the syncs are running properly ! 

But I was wondering why the log messages are still here. Marking validation errors as INFO are kinda misleading I guess.

**Comment by edgao** [comment]
yeah... maybe makes sense to shift this to debug level https://github.com/airbytehq/airbyte/blob/1a6a1c67ed5706235b16c4a39b0093b208831b19/airbyte-json-validation/src/main/java/io/airbyte/validation/json/JsonSchemaValidator.java#L126-L134

it's generally safe to ignore though - there are a number of cases where schema validation is actually expected to fail (e.g. after a connector spec change)

**Pull request merged**
