### PR TITLE
destination acceptance tests: get normalization and dbt support from definition

### LINKED ISSUE #21303: Destination acceptance tests should not use `supportsDbt` and `supportsNormalization`
In our efforts to decouple normalization version from platform version (https://github.com/airbytehq/airbyte/issues/16671) we now expose the normalization version (and normalization/dbt support) in the destination definition and not in its spec.
https://github.com/airbytehq/airbyte/pull/20245 changed the `DestinationAcceptanceTest` to retrieve the normalization configuration from the definition.
We now want to update the rest of the test to discard the retrieval of normalization/dbt support from the spec and assess normlization/dbt support from the definition.

### PR DESCRIPTION
**Pull request by alafanechere**
## What
Closes https://github.com/airbytehq/airbyte/issues/21303
In our efforts to decouple normalization version from platform version (https://github.com/airbytehq/airbyte/issues/16671) we  now expose the normalization version (and normalization/dbt support) in the destination definition and not in its spec.
https://github.com/airbytehq/airbyte/pull/20245 changed the DestinationAcceptanceTest to retrieve the normalization configuration from the definition.
We now want to update the rest of the test to discard the retrieval of normalization/dbt support from the spec and assess normlization/dbt support from the definition. 

## How
* Remove `supportsDbt` and `supportsNormalization` methods from `DestinationAcceptanceTest`
* Use `normalizationFromDefinition`

## Suggested review order
https://github.com/airbytehq/airbyte/blob/6b78d1fed6d34e6c8ba55003c4c847852a55babc/airbyte-integrations/bases/standard-destination-test/src/main/java/io/airbyte/integrations/standardtest/destination/DestinationAcceptanceTest.java#L1763

Then review the connector specific acceptance tests.

### CODE REVIEW

**Comment by alafanechere** [comment]
Hey @airbytehq/jdbc-connectors could you please let me know if the failing tests could be related to my PR?

**Comment by ryankfu** [comment]
@alafanechere your changes _shouldn't_ be the reason that the integration tests are failing, that said Ed and I created two different integration test runs on `main` to verify if the integration tests were already failing
* [destination-mysql](https://github.com/airbytehq/airbyte/actions/runs/3941047509)
* [destination-oracle-strict-encrypt](https://github.com/airbytehq/airbyte/actions/runs/3941498899)

**Review by edgao — APPROVED** [review]
yeah, I think these changes look fine. E.g. one of the failing tests is the recently-added column selection test, which is also failing on master.

**Review by evantahler — APPROVED** [review]
Screenshot 2023-01-17 at 4 03 34 PM
The best kind of PR!

Approval contigent on the tests passing, of course.

**Pull request merged**
