### PR TITLE
allow nullable columns to be used as cursor

### PR DESCRIPTION
**Pull request by subodh1810**
Issue : https://github.com/airbytehq/oncall/issues/641

### CODE REVIEW

**Review by edgao — APPROVED** [review]
:shipit:, maybe useful followup: should we throw an error if we detect a null in the cursor column?

**Review by ryankfu — COMMENTED** [review]
Should there also be the removal of `NOT NULL` in the setup for tests like in [PostgresJdbcSourceAcceptanceTest](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/PostgresJdbcSourceAcceptanceTest.java#L74-L79) as well as [PostgresSourceTest](https://github.com/airbytehq/airbyte/blob/871929de1541343c4c17c92ebf977d2b1878ab60/airbyte-integrations/connectors/source-postgres/src/test/java/io/airbyte/integrations/source/postgres/PostgresSourceTest.java#L144-L156) based on the files changed in the #14356?

**Comment by subodh1810** [comment]
@ryankfu I think its fine. There is a dedicated test to make sure that nullable columns are allowed as cursor

**Comment by grishick** [comment]
I don't see a test that verifies the behavior, which caused the OC issue: user has a view on top of a table where the cursor field is non-nullable in the source table.

**Comment by subodh1810** [comment]
@grishick the test `testDiscoverDifferentGrantAvailability` in `PostgresSourceTest` covers that. We create a bunch of views in that test and I added an assertion to make sure all of em have FULL_REFRESH and INCREMENTAL mode available for selection. This [part](https://github.com/airbytehq/airbyte/pull/17131/files#diff-9a2f4a12610e583beb3c4b9531634f1e2a41066e4a84aac9dfd9d9991be6d917R435)

**Comment by edgao** [comment]
publishing strict-encrypt in https://github.com/airbytehq/airbyte/pull/17147

**Pull request merged**
