### PR TITLE
Connector templates: Publish by default

### PR DESCRIPTION
**Pull request by flash1293**
Currently, our connector templates have all "publish" flags set to off.

This already caused issue in the past with connectors not published after the initial merge to master: https://github.com/airbytehq/airbyte/pull/31160/files#diff-110e24d902ed804a2da7b4c542e3bd84131e7688831f92c46b6cd81ed3aa7e0fR6

As connectors are written to be used, let's be more bold about this and set all publish flags (cloud, remote and python) to on by default and disabled them during the review process if necessary.

I can be convinced of disabling cloud by default as there is a slight risk to this, but for OSS and python I think the downside of forgetting to publish connectors is bigger than the downside of having to pull a connector in the off-case

### CODE REVIEW

**Comment by flash1293** [comment]
The CI failure seems to be a flaky thing in the concurrent CDK

**Review by girarda — APPROVED** [review]
I'm ok with this change. 

@alafanechere or @pedroslopez are there additional restrictions required before releasing connectors to Cloud? If yes, we should leave the cloud flag to false

**Review by alafanechere — COMMENTED** [review]
I'm slightly concerned about enabling cloud deployment by default.
The idea in disabling it by default was to not clutter Airbyte Cloud with alpha /  deceptive connectors.

I'd love @katmarkham  take on it. 
IMO it's safer to enable OSS - disable cloud by default.

**Comment by flash1293** [comment]
Yeah, I can see that. Disabled cloud again

**Review by katmarkham — APPROVED** [review]

**Pull request merged**
