### PR TITLE
Hide cloud status indicator in mobile view

### PR DESCRIPTION
**Pull request by timroes**
Hide the status indicator of the Cloud Status in mobile view (i.e. when the link is in the sidebar). Docusaurus clones the link from the header into the sidebar, thus it's a duplicate (thus switching from `id` to `class`), however it does this async, thus we don't really know when it is there, so I decided it's just easier to hide the status badge for now (it also looked better when the links render below each other).

Also cleans up some CSS to make sure the links in the top nav only render in their special style while in the top navigation and not in the mobile sidemenu.

### CODE REVIEW

**Review by lmossman — COMMENTED** [review]
@timroes I'm a bit confused - I don't see the cloud status indicator cloned into the sidebar when I turn on mobile view in my browser dev tools:

Screenshot 2023-09-19 at 1 46 09 PM 
Screenshot 2023-09-19 at 1 46 44 PM

The issue I _do_ see is that the Cloud status indicator is partially hidden underneath the search button, and your PR doesn't fix that issue

**Comment by timroes** [comment]
@lmossman on your second screenshot click: Back to main menu on the top.

**Review by lmossman — APPROVED** [review]
@timroes I'm approving since the mobile view looks fine to me now, but I wanted to understand better why we are making this change.

This view (on master) doesn't look bad to me:
Screenshot 2023-09-20 at 10 19 01 AM

But I noticed that the dot on the left side of the Cloud Status is grey - is it grey and not colored due to the link cloning? (if yes, why?) 

And we can't just hide the dot only in this case because you said we can't tell when it is being put in the sidebar vs at the top?

If the answer to both of those is yes then I agree with hiding it, otherwise it would be preferable to just hide the dot if we can't get the color correct, or ideally get it to have the correct color.

**Comment by timroes** [comment]
Regarding the correct color: I think I'd prefer not hiding the doc after we load the status (since it will cause text to jump around, which I think is not very favorable UX). We can't (or not as easy as I felt would value the doc system atm :D) attach the class to this menu, since the link is not existing in DOM when initially load the status, since Docusaurus needs "some undefined time" to clone all elements and put them into the sidebar. It also doesn't have a callback method that we could link into "onAfterMenuRendered", so basically we'd need to listen to DOM changes (not completely cheap), or attach the status class to the `body` so we can write the CSS for the element in a way that doesn't matter that this element exists (i.e. `body.cloudStatus-up .cloudStatusLink::before`), which both ways I didn't really fully like, why I decided to hide. I'm happy though if you feel there's a significant value on the indicator in the mobile sidebar to change to either one of those approaches (like the latter one, since it's more performant).

**Comment by lmossman** [comment]
I don't have super strong feelings here so I'm fine with just hiding it, both solutions sound a bit icky

**Pull request merged**
