### PR TITLE
Security update of default docker images

### PR DESCRIPTION
**Pull request by vr**
Because there is a lot of CVEs in those releases.

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@supertopher can you take a look in this contribution?

**Comment by supertopher** [comment]
thanks for the contribution @vr.  this looks pretty no-brainer but I want to run the test suite and ask the other large teams if there are any other tests we want to run before we merge

I want to make sure we don't drop prod because an argument flag also changed somewhere.

**Comment by supertopher** [comment]
our secret system is afraid of forks, I'll verify on a personal fork and come back
I believe our testing system is happier if you have a branch from airbyte if you want to re-open a PR, but that isn't necessary

**Review by supertopher — APPROVED** [review]
After rebasing on [my copy of your branch](https://github.com/airbytehq/airbyte/pull/21527#issuecomment-1387267310) everything looks green.  I'll rebase and merge here

We appreciate the contribution @vr.

thank you for your time and energy

**Pull request merged**
