### PR TITLE
airbyte-lib: Add testing to connectors

### PR DESCRIPTION
**Pull request by flash1293**
Building on the `airbyte-lib-validate-source` command to validate whether a python connector works with airbyte-lib, this PR introduces a new optional test step to run this command with the current connector under test.

To test:
* Install dev airbyte-ci tools via `make tools.airbyte-ci-dev.install`
* Run tests for connector where they will work: `airbyte-ci connectors --name=source-apify-dataset test`

### CODE REVIEW

**Review by alafanechere — CHANGES_REQUESTED** [review]
This code looks good to me and I like the fact that the validation happens in the airbyte-lib package. 
I'm a bit more concern by the footprint of this new check on the connector tests in CI.
Could we make the following part of the validation optional to not overlap the test with CAT parts?
```
    * Answers according to the Airbyte protocol when called with spec, check, discover and read.
````

**Comment by flash1293** [comment]
@alafanechere Maybe this is worded badly - what it means to say is that airbyte-lib can use the connector as expected, which includes getting the spec to statically validate the config the user has provided, running check to fully validate it, and running discover and read to actually fetch data and give it to the user.

The check is not doing any protocol-specific checks, it's just trying to use airbyte-lib with the connector: https://github.com/airbytehq/airbyte/blob/f95e0c8d67d35858cf53fc70df8bd323c5d98d61/airbyte-lib/airbyte_lib/validate.py#L60

When you say footprint, are you talking about test runtimes? Because this is relatively lightweight in this sense, it calls spec, check, discover and read only once and stops after the very first record.

The reason why I would like to actually call read in this test is that some connectors do things only if a read is actually triggered (e.g. lazily loading some modules or static files) and I want to validate that this works correctly. If airbyte-lib managed to get a record out of the connector, there is a very good chance the other ones will work too

**Comment by flash1293** [comment]
For example for pokeapi the validation took only 13s (and other connectors shouldn't be much slower as it will stop as soon as it has its record):

Screenshot 2024-02-02 at 17 09 30

**Comment by alafanechere** [comment]
> The reason why I would like to actually call read in this test is that some connectors do things only if a read is actually triggered (e.g. lazily loading some modules or static files) and I want to validate that this works correctly. If airbyte-lib managed to get a record from a single stream out of the connector, there is a very good chance the other ones will work too

This makes sense to me, and I'm 🆗 with it if it's not significantly slowing down the full test suite. One concern remains: calling read or discover on a connector with short lived access token means these operation can lead to an update of the access token that has to be updated on the GSM side. Is your validation code performing this update?

**Comment by flash1293** [comment]
@alafanechere good point, I changed this PR to only implement the basic check of "install works and spec can be fetched" for now. I will create an issue to track the more complete setup

**Comment by flash1293** [comment]
The failing test looks unrelated to the changes to me (and also passes locally) - maybe it's flaky?

**Review by alafanechere — APPROVED** [review]
Thanks for the change. 
Would you mind manually testing it on a couple of connectors by dispatching this [workflow](https://github.com/airbytehq/airbyte/actions/workflows/connectors_tests.yml)?

**Comment by flash1293** [comment]
Pokeapi: https://github.com/airbytehq/airbyte/actions/runs/7786827008
Google Sheets: https://github.com/airbytehq/airbyte/actions/runs/7786834735
Facebook marketing: https://github.com/airbytehq/airbyte/actions/runs/7786843721
Shopify: https://github.com/airbytehq/airbyte/actions/runs/7786856167

**Comment by flash1293** [comment]
Second try: https://github.com/airbytehq/airbyte/actions/runs/7787418433

**Comment by flash1293** [comment]
Ran tests for a bunch of connectors (see above) and the airbyte-lib validation passed for all of them, merging and crafting a message to connector devs so they are aware

**Pull request merged**
