### PR TITLE
Google Sheets Destination connector licenses to Elv2

### PR DESCRIPTION
**Pull request by evantahler**
See https://github.com/airbytehq/airbyte/issues/27724

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  destination-google-sheets test report (commit [`f3ee83e7ab`](https://github.com/airbytehq/airbyte/pull/27780/commits/f3ee83e7abadfff2d9edf7dcfbb7d7ef38b2ec6b)) - ❌

⏲️  Total pipeline duration: 187 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-google-sheets/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ❌        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build destination-google-sheets docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-google-sheets-destination/1687900108/f3ee83e7abadfff2d9edf7dcfbb7d7ef38b2ec6b/destination-google-sheets/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-google-sheets test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-google-sheets test report (commit [`ffb8b76f1f`](https://github.com/airbytehq/airbyte/pull/27780/commits/ffb8b76f1fdb3664c6f05ccc07ae70ed2f5cd7ea)) - ❌

⏲️  Total pipeline duration: 127 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-google-sheets/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ❌        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build destination-google-sheets docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-google-sheets-destination/1687900403/ffb8b76f1fdb3664c6f05ccc07ae70ed2f5cd7ea/destination-google-sheets/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-google-sheets test
```

**Comment by evantahler** [comment]
I can't see the QA check failure on CI, but locally:

```
 process "run-qa-checks connectors/destination-google-sheets" did not complete successfully: exit code: 1                                                                                                                                 │ │
│ │ Stdout:                                                                                                                                                                                                                                  │ │
│ │ Running QA checks for destination-google-sheets:0.2.0                                                                                                                                                                                    │ │
│ │ The following files have http:// URLs:                                                                                                                                                                                                   │ │
│ │         - airbyte-integrations/connectors/destination-google-sheets/destination_google_sheets/helpers.py                                                                                                                                 │ │
│ │ QA checks failed for destination-google-sheets:0.2.0:                                                                                                                                                                                    │ │
│ │ ✅ - check_documentation_file_exists                                                                                                                                                                                                     │ │
│ │ ✅ - check_migration_guide                                                                                                                                                                                                               │ │
│ │ ✅ - check_changelog_entry_is_updated                                                                                                                                                                                                    │ │
│ │ ✅ - check_connector_icon_is_available                                                                                                                                                                                                   │ │
│ │ ❌ - check_connector_https_url_only                                                                                                                                                                                                      │ │
│ │ ✅ - check_connector_has_no_critical_vulnerabilities                                                                                                                                                                                     │ │
│ │ ✅ - check_metadata_version_matches_dockerfile_label                                                                                                                                                                                     │ │
│ │ Stderr:
```

This is an Alpha destination, and this same test is failing on master

**Comment by octavia-approvington** [comment]
Enough! Let's do this <br/> goooooo!

**Review by octavia-approvington — APPROVED** [review]

**Comment by evantahler** [comment]
Problem addressed in https://github.com/airbytehq/airbyte/pull/27782

**Pull request merged**
