### PR TITLE
Bump ejs from 3.1.6 to 3.1.7 in /airbyte-webapp

### PR DESCRIPTION
**Pull request by supertopher**
Bumps [ejs](https://github.com/mde/ejs) from 3.1.6 to 3.1.7.
- [Release notes](https://github.com/mde/ejs/releases)
- [Changelog](https://github.com/mde/ejs/blob/main/CHANGELOG.md)
- [Commits](https://github.com/mde/ejs/compare/v3.1.6...v3.1.7)

---
updated-dependencies:
- dependency-name: ejs
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>

topher runs to make tests work

### CODE REVIEW

**Review by git-phu — APPROVED** [review]
is it worth letting the frontend team know about changes like this?

**Comment by supertopher** [comment]
@git-phu good question, I'll check in

**Comment by timroes** [comment]
When I get those updates I usually check how that library effects us to estimate how much testing is done. E.g. if it's a traversive library of any dev tool library only I usually just merge as long as the CI is green, e.g. for `ejs`:

```
> npm why ejs                    
ejs@3.1.6 dev
node_modules/ejs
  ejs@"^3.1.6" from @surma/rollup-plugin-off-main-thread@2.2.3
  node_modules/@surma/rollup-plugin-off-main-thread
    @surma/rollup-plugin-off-main-thread@"^2.2.3" from workbox-build@6.4.2
    node_modules/workbox-build
      workbox-build@"6.4.2" from workbox-webpack-plugin@6.4.2
      node_modules/workbox-webpack-plugin
        workbox-webpack-plugin@"^6.4.1" from react-scripts@5.0.1
        node_modules/react-scripts
          dev react-scripts@"^5.0.1" from the root project
          peer react-scripts@">=3.0.0" from @storybook/preset-create-react-app@4.1.0
          node_modules/@storybook/preset-create-react-app
            dev @storybook/preset-create-react-app@"^4.1.0" from the root project
```

This is pulled in by workbox, which is a toolkit to build service workers which we're not using at all, thus this library isn't used at all by us, thus fine to merge without problems.

Usuaully I've look regularily through the dependabot PRs, so ideally the platform team won't need to address any dependabot PR for the platform at all. If you anyway want to do, please feel free to also ask in `#dev-frontend` for any feedback on a library :)

**Comment by timroes** [comment]
@supertopher Also wondering, why not just use the depandapot PR itself? https://github.com/airbytehq/airbyte/pull/12403

**Comment by supertopher** [comment]
@timroes I think Peter may have worked some magic, but Depdendabot's PRs can't see our secrets by default, so re-opening the PR as your own allows access to GitHub secrets for testing.  

To be fair that exact PR seems to be happy, but I was going through a few of these and many of them were upset by a lack of access to secrets so I just opened them as myself to make testing happy without allowing dependabot code to play with our secrets

**Pull request merged**
