### PR TITLE
web: Upgrade Rest Hooks to v5

### PR DESCRIPTION
**Pull request by ntucker**
## What
Updating the RH upgrade pr with
- latest master
- two patch releases of rest hooks
- some more type fixes

## How
Was able to get docker running locally and do all the tests. (It's fun to run webapp in dev mode and use redux devtools too :)).

It seems to be working, but not sure how to run integration tests locally. If this only runs on your CI - is there a way I can look at the failures to help debug?

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

### CODE REVIEW

**Comment by ntucker** [comment]
Looking into making compatibility with super old v2 line of estlint parser

**Comment by michel-tricot** [comment]
@ntucker thank you!! Adding @Jamakase to review. He is on PTO at the moment.

**Comment by ntucker** [comment]
I'm still trying to figure out the eslint parser problem so no need to review yet.

**Comment by Jamakase** [comment]
@ntucker we can't currently merge your PR. I tried once and faced some problems during CI so I have to revert the changes. 

There is a draft PR based on your changes that includes some fixes for problems I faced after increasing react-scripts and rest-hooks version.

**Comment by ntucker** [comment]
Oh can you link that pr and issues?

**Comment by ntucker** [comment]
My goal is to make this work with older versions of react-scripts and typescript. This will help others upgrade as well. 5.0.2 should have typescript 3.7+ support restored, but there's some kind of eslint parse issue with the 2-line from react-scripts that I'm trying to figure out.

**Comment by ntucker** [comment]
The weird thing is, I can't reproduce this simply by running old react scripts version and the resource files from the project on its own. (`Line 0:  Parsing error: Cannot read property 'map' of undefined` is known to be an issue with eslint-parser for some modern javascript/typescript things)

**Comment by ntucker** [comment]
https://github.com/facebook/create-react-app/issues/9515 is the tracking

**Comment by ntucker** [comment]
Found out the issue has to do with babel runtime and this change: https://github.com/babel/babel/pull/10853. Some import compatibility changes going on

**Comment by ntucker** [comment]
Reverted all upgrades, and instead hoisted `@babel/runtime`. It should all work now

**Comment by ntucker** [comment]
https://github.com/coinbase/rest-hooks/pull/513 should make upgrades run smoother for legacy tooling situations like this

**Comment by ntucker** [comment]
Eliminated need to force new runtime version with release of 5.0.3. Build and dev run work

**Comment by Jamakase** [comment]
@ntucker Is it correct, that we do not need to update our runtime and you have some changes that address those problem within new rest-hooks released version?

**Comment by ntucker** [comment]
Yes, this branch has now been updated to use the latest rest-hooks which has been tested to be backwards compatible with all the tooling including:
- eslint-typescript-parser
- typescript 3
- babel/runtime

You can observe now in the package-lock.json that only rest-hooks packages were changed/added.

**Comment by ntucker** [comment]
I have tested locally by both building a production and running dev mode (npm start) with the docker running and a small sample project. It's by no means comprehensive but ensures that

1) build is not broken
2) The most common flows work correctly

**Comment by Jamakase** [comment]
Wow! @ntucker Thank you so much for making sure that upgrade will go fine. That is really awesome as I am pretty packed for the next sprint and was not sure when I have time to check the issue.

Let's try and merge it and see how CI goes. Just to make sure there are no lint errors anymore? As actually the problem we had was that `yarn lint` was failing for that case with `map`.

**Review by jamakase — APPROVED** [review]
Thank's a lot for all the work! I understand that it could have taken a significant amount of time as you have to change some things not only here, but in `rest-hooks` lib too.

**Comment by ntucker** [comment]
```
ntucker@GLaDOS:~/src/airbyte/airbyte-webapp$ npm run lint

> airbyte-webapp@0.1.0 lint /home/ntucker/src/airbyte/airbyte-webapp
> eslint --ext js,ts,tsx src
```

Lint passes. Oddly enough the linting issue was related to @babel/runtime being installed as a nested dependency. (Joys of packaging)

**Comment by ntucker** [comment]
I tend to obsessively keep packages up to date, so this was a good opportunity to ensure smooth upgrades for all users of [Rest Hooks](https://resthooks.io). I suspect many people are stuck on react-scripts v3 as well.

**Pull request merged**
