### PR TITLE
fix (airbyte-ci): include advanced_auth in spec migration

### PR DESCRIPTION
**Pull request by ChristoGrab**
## What

Following up on [48375](https://github.com/airbytehq/airbyte/pull/48375), we caught that advanced_auth config was not being migrated to the inlined spec in manifest-only migrations. Whoops 😬

## How

- Includes the advanced_auth object when grabbing a non-inlined spec to copy into the manifest.
- Fixed a failing publish unit test
- Added unit_tests folder to the list of resources not to nuke

### CODE REVIEW

**Review by maxi297 — COMMENTED** [review]
Do we have tests for this migration? I'm very unfamiliar with airbyte-ci and can't say for sure this would work. Else, do you have a manual test to share?

**Comment by ChristoGrab** [comment]
@maxi297 Here's some local results from running the migration on Facebook Pages, which uses advanced_auth:

## Exhibit A: Current behavior

Screenshot 2024-11-07 at 9 43 41 AM

## Exhibit B: Fixed behavior

Screenshot 2024-11-07 at 9 38 12 AM

**Review by maxi297 — APPROVED** [review]
With the manual test, I'm fine with this change. Thanks @ChristoGrab !

**Pull request merged**
