### PR TITLE
feat: enable sorting in sources and destinations page

### PR DESCRIPTION
**Pull request by harshithmullapudi**
## What
Enable sorting for the name in sources and destination page

### CODE REVIEW

**Comment by timroes** [comment]
The linked issue here is asking for sorting also on the Connector and Destination column. We should either make sure this functionality is added to this PR, or not close the original issue with this PR, please.

**Comment by harshithmullapudi** [comment]
Makes sense not closing it.

**Comment by harshithmullapudi** [comment]
@timroes If you can help with this question: In the sources page if a source has multiple destinations is there any good way to handle sorting?

**Comment by timroes** [comment]
@harshithmullapudi It's a good question, and I think we might not want to have sorting on it, but I'd let Andy answer that on the issue where you posted the question.

**Pull request closed without merging**
