### PR TITLE
SAT: make `future_state` configuration mandatory in `high` test strictness level

### LINKED ISSUE #18223: SAT [strict_mode]: `future_state` for all incremental streams
## Tell us about the problem you're trying to solve
In incremental tests, the `future_state_path` file is used to assess the correct behavior of incremental streams when there is no data to read. No enforcement on the content of this file currently exists. For maximal test coverage, each connector must declare a future state **for each incremental stream** to assert working checkpointing and data correctness. If this is not technically possible for all incremental streams a `bypass_reason` should be filled by the maintainer.

## Describe the solution you’d like
```yaml
strict_mode: strict
tests:
  incremental:
    - config_path: "secrets/config.json"
      configured_catalog_path: "sample_files/configured_catalog.json"
      future_states: 
        - stream_name: stream_a
          state_path: "sample_files/stream_a_abnormal_state.json"
        - stream_name: stream_b
          bypass_reason: "This stream can't be queried in the future"
```

SAT should check all streams in the configured catalog are declared under `future_states`. If no `state_path` is filled a `bypass_reason` should be filled.

This will require changing the current structure of `future_state_path` to get stream granularity.
Current structure:
```
  incremental:
    - config_path: "secrets/config.json"
      configured_catalog_path: "sample_files/configured_catalog.json"
      future_state_path: "sample_files/abnormal_state.json"
```

### PR DESCRIPTION
**Pull request by alafanechere**
## What
Closes https://github.com/airbytehq/airbyte/issues/18223
In `high_test_strictness` level we want to have the new following rules in the `incremental` test:
1. `future_state` to be mandatory
2. The `future_state` file must declare all existing streams. 
3. Missing streams can declared with a valid bypass_reason
 
## How
* Change the config structure for incremental tests  
* Change `future_state_path` and `future_state` fixture to make tests using it fail if the rules described above are not followed. 
* Unit tests the two edited fixtures

### CODE REVIEW

**Comment by alafanechere** [comment]
☝️ The test above should not fail: 
* high test strictness level
* A `future_state` with `future_state_path` is declared. All the missing streams are declared under `missing_streams`.

**Comment by alafanechere** [comment]
☝️ The test above should fail. 
Acceptance test config changed for Source GitHub in https://github.com/airbytehq/airbyte/pull/19085/commits/ffe33de9356c9242ff760c6b0b23008b6cecfed9
* high test strictness level
* A `future_state` with `future_state_path` is declared but a stream is missing under `missing_streams`.

**Comment by alafanechere** [comment]
☝️ The test above should not fail, I reverted source github's acceptance-test-config.yaml to its original form.

**Comment by evantahler** [comment]
_... eagerly waits for https://github.com/airbytehq/airbyte/pull/19085#issuecomment-1306384001 to report an error..._

**Comment by alafanechere** [comment]
> ... eagerly waits for https://github.com/airbytehq/airbyte/pull/19085#issuecomment-1306384001 to report an error...

Ok let's try again 😄

**Comment by alafanechere** [comment]
☝️ The test above should fail. 
Acceptance test config changed for Source GitHub in https://github.com/airbytehq/airbyte/pull/19085/commits/a5b7ff2fd2c11021f8daf518a988edaae77e62f3
* high test strictness level
* A `future_state` with `future_state_path` is declared **but a stream is missing under `missing_streams`.**

**Review by evantahler — APPROVED** [review]

**Comment by alafanechere** [comment]
/publish connector=bases/source-acceptance-test auto-bump-version=false

**Pull request merged**
