### PR TITLE
Source Shopify: Added new streams

### PR DESCRIPTION
**Pull request by lazebnyi**
## What
This pull request adds new streams to the Shopify connector. The following streams have been implemented:

- CustomerSavedSearch - https://github.com/airbytehq/airbyte/issues/26543
- CustomerAddress - https://github.com/airbytehq/airbyte/issues/26542
- Countries - https://github.com/airbytehq/airbyte/issues/26541

## Recommended reading order
1. `y.python`

## 🚨 User Impact 🚨

no breaking changes

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-shopify test report (commit [`86582ef1e1`](https://github.com/airbytehq/airbyte/pull/27315/commits/86582ef1e1d438ee30f836eb0ce6927c62ffefb3)) - ❌

⏲️  Total pipeline duration: 1452 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-shopify/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Connector package install                                             | ✅        |
| Build source-shopify docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5269986825)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-shopify test
```

**Comment by octavia-squidington-iii** [comment]
##  source-shopify test report (commit [`0961f272a6`](https://github.com/airbytehq/airbyte/pull/27315/commits/0961f272a64ab3fd246460f05b80f3368f30d24e)) - ❌

⏲️  Total pipeline duration: 1709 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-shopify/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ❌        |
| Connector package install                                             | ✅        |
| Build source-shopify docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/lazebnyi_26543-source-shopify-add-new-streams/1687431344/0961f272a64ab3fd246460f05b80f3368f30d24e/source-shopify/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-shopify test
```

**Comment by octavia-squidington-iii** [comment]
##  source-shopify test report (commit [`9d1b5d01d8`](https://github.com/airbytehq/airbyte/pull/27315/commits/9d1b5d01d88f4c153938650fa21032dc638a469c)) - ❌

⏲️  Total pipeline duration: 1816 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-shopify/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ❌        |
| Connector package install                                             | ✅        |
| Build source-shopify docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/lazebnyi_26543-source-shopify-add-new-streams/1687436004/9d1b5d01d88f4c153938650fa21032dc638a469c/source-shopify/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-shopify test
```

**Comment by octavia-squidington-iii** [comment]
##  source-shopify test report (commit [`ca5f0e7659`](https://github.com/airbytehq/airbyte/pull/27315/commits/ca5f0e765946917956c33b706ea108de1229a5e0)) - ✅

⏲️  Total pipeline duration: 1796 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-shopify/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-shopify docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/lazebnyi_26543-source-shopify-add-new-streams/1687443842/ca5f0e765946917956c33b706ea108de1229a5e0/source-shopify/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-shopify test
```

**Review by davydov-d — APPROVED** [review]
Please add new streams to the doc file

**Comment by octavia-squidington-iii** [comment]
##  source-shopify test report (commit [`6695be3024`](https://github.com/airbytehq/airbyte/pull/27315/commits/6695be3024c129a19a2c6a15f94c74124dfc3a81)) - ✅

⏲️  Total pipeline duration: 1761 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-shopify/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-shopify docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/lazebnyi_26543-source-shopify-add-new-streams/1687448291/6695be3024c129a19a2c6a15f94c74124dfc3a81/source-shopify/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-shopify test
```

**Pull request merged**
