### PR TITLE
:rotating_light: :rotating_light: Source Google Analytics: fix stream naming

### PR DESCRIPTION
**Pull request by davydov-d**
## What
Fix duplicate stream names
https://github.com/airbytehq/oncall/issues/3093

## How
- Append "property_<propertyID>" to stream names if there's more than 1 property in the config (so that customers with 1 property would not be affected). This is a temporary solution to fix oncall issue. The long term solution should be implemented in a follow up issue https://github.com/airbytehq/airbyte-internal-issues/issues/2143 (should be planned next quarter)

## 🚨 User Impact 🚨
Users with more than 1 property ID will have to reset the connector. Users with 1 property ID will not be affected.

### CODE REVIEW

**Comment by davydov-d** [comment]
will link the breaking change doc soon

**Review by artem1205 — APPROVED** [review]

**Review by clnoll — APPROVED** [review]
The change LGTM @davydov-d. Thank you for the code comments, very helpful!

**Comment by airbyte-oss-build-runner** [comment]
##  source-google-analytics-data-api test report (commit [`24e544263d`](https://github.com/airbytehq/airbyte/pull/30930/commits/24e544263d02763f53b8068c61613c48f2678716)) - ✅

⏲️  Total pipeline duration: 91mn32s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Connector package install                                                     | ✅        |
| Build source-google-analytics-data-api docker image for platform linux/x86_64 | ✅        |
| Unit tests                                                                    | ✅        |
| Acceptance tests                                                              | ✅        |
| Code format checks                                                            | ✅        |
| Validate metadata for source-google-analytics-data-api                        | ✅        |
| Connector version semver check                                                | ✅        |
| Connector version increment check                                             | ✅        |
| QA checks                                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_3093-source-google-analytics-fix-stream-naming/1696251562/24e544263d02763f53b8068c61613c48f2678716/source-google-analytics-data-api/2.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:24e544263d02763f53b8068c61613c48f2678716)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-analytics-data-api test
```

**Comment by davydov-d** [comment]
the breaking change doc https://docs.google.com/document/d/1i0wnxVZUwLLrpaoHnwOGDFO96IA1LIKrmF4H4v1W0Ew/edit

**Pull request merged**
