### PR TITLE
#2084 src appstore: bugfix sync modes to correctly display incremental instead of full refresh

### LINKED ISSUE #2084: Source Appstore connector: only supports incremental syncs
## Expected Behavior
@matthewtpowers reported the Appstore connector only supports Full refresh in the Airbyte UI. However, it should support incremental sync. 

## Steps to Reproduce
1. Setup a connection with the Appstore connector and any destination that supports incremental
1. In the schema selection page, the sync mode displayed is full refresh

## Severity of the bug for you
medium

## Connector Version
0.1.1

### PR DESCRIPTION
**Pull request by sherifnada**
Closes #2084

### CODE REVIEW

**Comment by sherifnada** [comment]
/publish connector=connectors/source-appstore-singer --ref=master

**Comment by sherifnada** [comment]
/publish connector=connectors/source-appstore-singer ref=master

**Comment by jrhizor** [comment]
Don't forget to publish successfully before merging!

**Comment by sherifnada** [comment]
RIP

**Comment by jrhizor** [comment]
I'm trying in https://github.com/airbytehq/airbyte/pull/2133

**Comment by jrhizor** [comment]
Oh I forgot this wasn't related to build fixes.

It's `Task 'integrationTest' not found in project ':airbyte-integrations:connectors:source-appstore-singer'.`

**Pull request merged**
