### PR TITLE
Skip onboarding button

### LINKED ISSUE #1431: As a user I want to be able to skip the onboarding flow
## Tell us about the problem you're trying to solve
* Some users would like to be able to skip the onboarding flow. e.g. they already know how to user airbyte
* They are following a tutorial that assumes onboarding has already happened (this is the case for the build a new connector tutorial that @sherifnada is working on).

## Describe the solution you’d like
* Add a skip onboarding wizard button. Specifically let's add a button at the bottom of the wizard that says "Skip Onboarding"

### PR DESCRIPTION
**Pull request by jamakase**
## What
Add "Skip Onboarding" button at the bottom of the wizard

Closes #1431

### CODE REVIEW

**Comment by Jamakase** [comment]
Example of step with Skip Onboarding button. This button is added on each step

skip button

**Review by cgardens — APPROVED** [review]
looks good

@Jamakase - with this change, do we still need to keep the `onboardingComplete` flag or can I remove it from the API?

**Comment by Jamakase** [comment]
> with this change, do we still need to keep the `onboardingComplete` flag or can I remove it from the API?

We do not need it, but let's delete it after next release, what do you think?

**Comment by cgardens** [comment]
Yup that's fine. I'll create an issue to remember it (issue https://github.com/airbytehq/airbyte/issues/1642). This PR is good to merge.

**Pull request merged**
