### PR TITLE
Revert "Update CI credentials docs to point to new GCP project (#30813)"

### PR DESCRIPTION
**Pull request by girarda**
## What
* Reverting instructions to old google cloud project since the new one doesn't have all the secrets we expect. FYI @wennergr since you mentioned `dataline-integration-testing` was supposed to be deprecated.

### CODE REVIEW

**Review by stephane-airbyte — APPROVED** [review]

**Comment by octavia-approvington** [comment]
Trying to merge your PR using a bot?
Comment this on the PR:
```
/approve-and-merge reason="<STATE YOUR REASON HERE>"
```
Make sure you've reviewed the [docs](https://internal-docs.airbyte.io/How-Tos/Overriding-PR-Merge-Rules)!

**Comment by octavia-approvington** [comment]
Approve this <br/> imagine the commander saying yes

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
