### PR TITLE
Java DB Destination connector licenses to Elv2

### PR DESCRIPTION
**Pull request by evantahler**
See https://github.com/airbytehq/airbyte/issues/27724

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  destination-oracle-strict-encrypt test report (commit [`53310c5a28`](https://github.com/airbytehq/airbyte/pull/27781/commits/53310c5a28eb9d0ae265d78649006ca6504c304e)) - ❌

⏲️  Total pipeline duration: 2861 seconds

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-oracle-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                           | ✅        |
| Connector version increment check                                                        | ✅        |
| QA checks                                                                                | ✅        |
| Build connector tar                                                                      | ✅        |
| Build destination-oracle-strict-encrypt docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                               | ✅        |
| Build airbyte/normalization-oracle:dev                                                   | ✅        |
| Integration tests                                                                        | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1687901479/53310c5a28eb9d0ae265d78649006ca6504c304e/destination-oracle-strict-encrypt/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-oracle-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mysql-strict-encrypt test report (commit [`53310c5a28`](https://github.com/airbytehq/airbyte/pull/27781/commits/53310c5a28eb9d0ae265d78649006ca6504c304e)) - ❌

⏲️  Total pipeline duration: 2056 seconds

| Step                                                                                    | Result   |
|:----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mysql-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                          | ✅        |
| Connector version increment check                                                       | ✅        |
| QA checks                                                                               | ✅        |
| Build connector tar                                                                     | ✅        |
| Build destination-mysql-strict-encrypt docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                              | ✅        |
| Build airbyte/normalization-mysql:dev                                                   | ✅        |
| Integration tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1687901479/53310c5a28eb9d0ae265d78649006ca6504c304e/destination-mysql-strict-encrypt/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mysql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mssql-strict-encrypt test report (commit [`53310c5a28`](https://github.com/airbytehq/airbyte/pull/27781/commits/53310c5a28eb9d0ae265d78649006ca6504c304e)) - ❌

⏲️  Total pipeline duration: 1849 seconds

| Step                                                                                    | Result   |
|:----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mssql-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                          | ✅        |
| Connector version increment check                                                       | ✅        |
| QA checks                                                                               | ✅        |
| Build connector tar                                                                     | ✅        |
| Build destination-mssql-strict-encrypt docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                              | ✅        |
| Build airbyte/normalization-mssql:dev                                                   | ✅        |
| Integration tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1687901479/53310c5a28eb9d0ae265d78649006ca6504c304e/destination-mssql-strict-encrypt/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mssql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-redshift test report (commit [`53310c5a28`](https://github.com/airbytehq/airbyte/pull/27781/commits/53310c5a28eb9d0ae265d78649006ca6504c304e)) - ❌

⏲️  Total pipeline duration: 1879 seconds

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-redshift/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ❌        |
| QA checks                                                                   | ❌        |
| Build connector tar                                                         | ✅        |
| Build destination-redshift docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Build airbyte/normalization-redshift:dev                                    | ✅        |
| Integration tests                                                           | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1687901479/53310c5a28eb9d0ae265d78649006ca6504c304e/destination-redshift/0.4.9/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redshift test
```

**Comment by alafanechere** [comment]
I believe we're in the same situation I mentioned [here](https://github.com/airbytehq/airbyte/pull/27737#issuecomment-1610975893) but for `destination-mssql`

**Comment by octavia-squidington-iii** [comment]
##  destination-redshift test report (commit [`af678d0b2d`](https://github.com/airbytehq/airbyte/pull/27781/commits/af678d0b2d8908eff055277d1ae96b7f1a3f3070)) - ❌

⏲️  Total pipeline duration: 324 seconds

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-redshift/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-redshift docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-redshift:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-redshift:integrationTest | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1687976808/af678d0b2d8908eff055277d1ae96b7f1a3f3070/destination-redshift/0.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redshift test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mysql test report (commit [`af678d0b2d`](https://github.com/airbytehq/airbyte/pull/27781/commits/af678d0b2d8908eff055277d1ae96b7f1a3f3070)) - ❌

⏲️  Total pipeline duration: 323 seconds

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mysql/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| Connector version increment check                                            | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build destination-mysql docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mysql:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mysql:integrationTest | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1687976808/af678d0b2d8908eff055277d1ae96b7f1a3f3070/destination-mysql/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mysql test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-snowflake test report (commit [`af678d0b2d`](https://github.com/airbytehq/airbyte/pull/27781/commits/af678d0b2d8908eff055277d1ae96b7f1a3f3070)) - ❌

⏲️  Total pipeline duration: 396 seconds

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-snowflake/metadata.yaml     | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Build connector tar                                                              | ✅        |
| Build destination-snowflake docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-snowflake:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-snowflake:integrationTest | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1687976808/af678d0b2d8908eff055277d1ae96b7f1a3f3070/destination-snowflake/1.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-postgres test report (commit [`af678d0b2d`](https://github.com/airbytehq/airbyte/pull/27781/commits/af678d0b2d8908eff055277d1ae96b7f1a3f3070)) - ❌

⏲️  Total pipeline duration: 252 seconds

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-postgres docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-postgres:integrationTest | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1687976808/af678d0b2d8908eff055277d1ae96b7f1a3f3070/destination-postgres/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-postgres test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-postgres-strict-encrypt test report (commit [`af678d0b2d`](https://github.com/airbytehq/airbyte/pull/27781/commits/af678d0b2d8908eff055277d1ae96b7f1a3f3070)) - ❌

⏲️  Total pipeline duration: 229 seconds

| Step                                                                                           | Result   |
|:-----------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-postgres-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                                 | ✅        |
| Connector version increment check                                                              | ✅        |
| QA checks                                                                                      | ✅        |
| Build connector tar                                                                            | ✅        |
| Build destination-postgres-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                                | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-postgres-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1687976808/af678d0b2d8908eff055277d1ae96b7f1a3f3070/destination-postgres-strict-encrypt/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-postgres-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mongodb test report (commit [`af678d0b2d`](https://github.com/airbytehq/airbyte/pull/27781/commits/af678d0b2d8908eff055277d1ae96b7f1a3f3070)) - ❌

⏲️  Total pipeline duration: 171 seconds

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mongodb/metadata.yaml     | ✅        |
| Connector version semver check                                                 | ✅        |
| Connector version increment check                                              | ✅        |
| QA checks                                                                      | ✅        |
| Build connector tar                                                            | ✅        |
| Build destination-mongodb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mongodb:integrationTest | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1687976808/af678d0b2d8908eff055277d1ae96b7f1a3f3070/destination-mongodb/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mongodb test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-oracle test report (commit [`af678d0b2d`](https://github.com/airbytehq/airbyte/pull/27781/commits/af678d0b2d8908eff055277d1ae96b7f1a3f3070)) - ❌

⏲️  Total pipeline duration: 365 seconds

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-oracle/metadata.yaml     | ✅        |
| Connector version semver check                                                | ✅        |
| Connector version increment check                                             | ✅        |
| QA checks                                                                     | ✅        |
| Build connector tar                                                           | ✅        |
| Build destination-oracle docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-oracle:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-oracle:integrationTest | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1687976808/af678d0b2d8908eff055277d1ae96b7f1a3f3070/destination-oracle/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-oracle test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery-denormalized test report (commit [`af678d0b2d`](https://github.com/airbytehq/airbyte/pull/27781/commits/af678d0b2d8908eff055277d1ae96b7f1a3f3070)) - ❌

⏲️  Total pipeline duration: 233 seconds

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ✅        |
| Connector version increment check                                                            | ✅        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-bigquery-denormalized docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery-denormalized:integrationTest | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1687976808/af678d0b2d8908eff055277d1ae96b7f1a3f3070/destination-bigquery-denormalized/1.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mysql-strict-encrypt test report (commit [`af678d0b2d`](https://github.com/airbytehq/airbyte/pull/27781/commits/af678d0b2d8908eff055277d1ae96b7f1a3f3070)) - ❌

⏲️  Total pipeline duration: 260 seconds

| Step                                                                                        | Result   |
|:--------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mysql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                              | ✅        |
| Connector version increment check                                                           | ✅        |
| QA checks                                                                                   | ✅        |
| Build connector tar                                                                         | ✅        |
| Build destination-mysql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mysql:dev                                                       | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mysql-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1687976808/af678d0b2d8908eff055277d1ae96b7f1a3f3070/destination-mysql-strict-encrypt/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mysql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-oracle-strict-encrypt test report (commit [`af678d0b2d`](https://github.com/airbytehq/airbyte/pull/27781/commits/af678d0b2d8908eff055277d1ae96b7f1a3f3070)) - ❌

⏲️  Total pipeline duration: 289 seconds

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-oracle-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ✅        |
| Connector version increment check                                                            | ✅        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-oracle-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-oracle:dev                                                       | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-oracle-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1687976808/af678d0b2d8908eff055277d1ae96b7f1a3f3070/destination-oracle-strict-encrypt/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-oracle-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`af678d0b2d`](https://github.com/airbytehq/airbyte/pull/27781/commits/af678d0b2d8908eff055277d1ae96b7f1a3f3070)) - ❌

⏲️  Total pipeline duration: 311 seconds

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery:integrationTest | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1687976808/af678d0b2d8908eff055277d1ae96b7f1a3f3070/destination-bigquery/1.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mssql-strict-encrypt test report (commit [`af678d0b2d`](https://github.com/airbytehq/airbyte/pull/27781/commits/af678d0b2d8908eff055277d1ae96b7f1a3f3070)) - ❌

⏲️  Total pipeline duration: 391 seconds

| Step                                                                                        | Result   |
|:--------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mssql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                              | ✅        |
| Connector version increment check                                                           | ✅        |
| QA checks                                                                                   | ✅        |
| Build connector tar                                                                         | ✅        |
| Build destination-mssql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mssql:dev                                                       | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mssql-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1687976808/af678d0b2d8908eff055277d1ae96b7f1a3f3070/destination-mssql-strict-encrypt/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mssql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mssql test report (commit [`af678d0b2d`](https://github.com/airbytehq/airbyte/pull/27781/commits/af678d0b2d8908eff055277d1ae96b7f1a3f3070)) - ❌

⏲️  Total pipeline duration: 312 seconds

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mssql/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| Connector version increment check                                            | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build destination-mssql docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mssql:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mssql:integrationTest | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1687976808/af678d0b2d8908eff055277d1ae96b7f1a3f3070/destination-mssql/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mssql test
```

**Review by edgao — APPROVED** [review]

**Comment by octavia-approvington** [comment]
Trying to merge your PR using a bot?
Comment this on the PR:
```
/approve-and-merge reason="<STATE YOUR REASON HERE>"
```
Make sure you've reviewed the [docs](https://internal-docs.airbyte.io/How-Tos/Overriding-PR-Merge-Rules)!

**Comment by octavia-approvington** [comment]
Check that box <br/> TODO complete

**Review by octavia-approvington — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  destination-mssql-strict-encrypt test report (commit [`ea607379b7`](https://github.com/airbytehq/airbyte/pull/27781/commits/ea607379b7b5aaff0d40b98e55d58f5a110869af)) - ❌

⏲️  Total pipeline duration: 25mn22s 

| Step                                                                                        | Result   |
|:--------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mssql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                              | ✅        |
| Connector version increment check                                                           | ❌        |
| QA checks                                                                                   | ✅        |
| Build connector tar                                                                         | ✅        |
| Build destination-mssql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mssql:dev                                                       | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mssql-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_elv2-destinations/1688059492/ea607379b7b5aaff0d40b98e55d58f5a110869af/destination-mssql-strict-encrypt/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mssql-strict-encrypt test
```

**Pull request merged**
