### PR TITLE
[fix] Zendesk Talk: normalization failure #2930

### LINKED ISSUE #2930: Zendesk Talk: normalization failure
## Expected Behavior
I expect the zendesk talk connector to work when being written to a destination with normalization turned on. 

## Current Behavior

one issue with the the greetings.sql table: `invalid input syntax for type bigint: "voicemail_en"`
From the user: 
> when syncing data for the first time. i see that in the logs --> all the tables appear to work except that one.
appears to be a dbt run on the backend (FYI did you want to upgrade to 19.1?)
EDIT: inspected the raw data for that table and found some records where the “id” are (probably incorrectly) set to strings and not INTs e.g. “voicemail_en” 

## Logs
user will send 

## Severity of the bug for you
Medium

### PR DESCRIPTION
**Pull request by danieldiamond**
## What
Closes #2930

## How
Modify greeting.json id to type string

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

## Recommended reading order
1. `test.java`
1. `component.ts`
1. the rest

### CODE REVIEW

**Comment by danieldiamond** [comment]
Note: I experienced the error in the mentioned issue i.e. `invalid input syntax for type bigint: "voicemail_en"`. However, I'm not entirely convinced this change should be made.
Should we store the id as string or fail to notify the user that the data is not as expected.
The data in the greetings table is:
| id           | type | audio_url          |
|--------------|------|--------------------|
| 11141        | a    | my_greeting.mp3    |
| 144421       | b    | other_greeting.mp3 |
| voicemail_en | c    | bad_greeting_entry?.mp3           |

cc'ing @sherifnada

**Comment by sherifnada** [comment]
thanks @danieldiamond! we'll review this in the morning.

**Review by yevhenii-ldv — APPROVED** [review]

**Comment by yevhenii-ldv** [comment]
closed by #3022

**Comment by sherifnada** [comment]
Thanks a ton @danieldiamond !

We just merged this fix into master a released a new version of the connector. 

Upgrade your connector to version 0.1.1 and get started. To upgrade your connector version, go to the admin panel in the left hand side of the UI, find this connector in the list, and input the latest connector version. Make sure to reset the schema of your source from the connection settings page. 

Please let us know if you have any further questions. 

Enjoy!

**Pull request closed without merging**
