### PR TITLE
🤖 publish command: fix for version bumping multiple connectors in same PR 

### PR DESCRIPTION
**Pull request by Phlair**
## What
https://github.com/airbytehq/airbyte/issues/12276

## How
add a pull from the current branch @ origin just before we add and commit the automated changes.

## Notes
Doing some dummy bumping on connectors to test, choosing lesser used ones

### CODE REVIEW

**Comment by Phlair** [comment]
To run publish command with changes I have to run manually from actions page.

I'll manually link to comments below.

**Comment by Phlair** [comment]
Faker publish

**Comment by Phlair** [comment]
Openweather publish

**Review by alafanechere — APPROVED** [review]
👍 
Can we trigger multiple publish commands in parallel or shall we run publish command sequentially?

**Comment by Phlair** [comment]
@alafanechere for now it's still just one connector per publish command, but this minor fix should mean they can all run at the same time and still auto-bump successfully. (technically there is still a window of failure but it's very very small)

**Comment by Phlair** [comment]
Not sure why faker failed to publish, going to bump openweather again and test alongside a different connector

**Comment by Phlair** [comment]
apify

**Comment by Phlair** [comment]
openweather

**Comment by Phlair** [comment]
apify

**Comment by Phlair** [comment]
openweather

**Pull request merged**
