### PR TITLE
Helm: Add missing hooks for serviceaccount

### PR DESCRIPTION
**Pull request by mamalovesyou**
## What
This add the missing helm hooks to create the serviceaccount before the bootloader is created. Issue was described in #10336

## How
Updated default helm values

## 🚨 User Impact 🚨
No breaking changes.

## Tests
Tested on my EKS cluster using argocd for deployment

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hello @matthieuberger thanks for the contribution, can you sign the CLA?

**Comment by yoavo-datricks** [comment]
Hi. This is not a helm best practice since users will not be able to append additional annotations.
I guess the right solution will be to add this to the serviceaccount's template.

**Review by alafanechere — CHANGES_REQUESTED** [review]
> Hi. This is not a helm best practice since users will not be able to append additional annotations.
> I guess the right solution will be to add this to the serviceaccount's template.

I agree with @yoavo-datricks, these annotations should be moved to the serviceaccount template, and we'd rather prefer user to not change this in their values.

**Comment by alafanechere** [comment]
@yoavo-datricks / @matthieuberger I opened a https://github.com/airbytehq/airbyte/pull/10630:  it makes a similar modification but at the template level. Feel free to review.

**Comment by alafanechere** [comment]
@matthieuberger I could not push on your branch as I'm not part of your organization.

**Pull request closed without merging**
