### PR TITLE
Deprecate PART_SIZE_MB in connectors using S3/GCS storage

### LINKED ISSUE #11389: Connector UX: deprecate PART_SIZE_MB in connectors specs using S3/GCS storage
## Tell us about the problem you're trying to solve
Following up on work from https://github.com/airbytehq/airbyte/issues/10260, we changed the buffering logic to set some upper limits on the buffer size while buffering a stream before invoking the upload operations using `StreamTransferManager`.

Therefore, the amount of data being transferred is not unknown anymore (fixed to [200MB](https://github.com/airbytehq/airbyte/blob/bcbed0a9a03c12ff91b8b04315765e9eabe1b9fc/airbyte-integrations/bases/base-java/src/main/java/io/airbyte/integrations/destination/record_buffer/FileBuffer.java#L26)), and we don't need to configure an optimal number of part sizes as described here:

> Server allows up to 10,000 parts to be uploaded for a single object, and each part must be identified by a unique number from 1 to 10,000.
> Therefore the maximum amount of data that can be written to a stream is 10000/numStreams * partSize. 
> The total object size can be at most 5 TB, so there is no reason to set this higher than 525MB. 

## Describe the solution you’d like
Deprecate and remove `PART_SIZE_MB` fields from connectors based on `StreamTransferManager`

### PR DESCRIPTION
**Pull request by VitaliiMaltsev**
## What
Following up on work from [#10260](https://github.com/airbytehq/airbyte/issues/10260), we changed the buffering logic to set some upper limits on the buffer size while buffering a stream before invoking the upload operations using StreamTransferManager.

## How
Deprecate and remove PART_SIZE_MB fields from connectors based on StreamTransferManager

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
There should not be any user impact

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Review by alexandr-shegeda — APPROVED** [review]
LGTM. we can proceed with publishing and merging without airbyte review

**Comment by VitaliiMaltsev** [comment]
/publish connector=connectors/destination-bigquery-denormalized

**Comment by danieldiamond** [comment]
FYI snowflake destination version `0.4.29` is failing. confirmed that `0.4.28` still works:
```
Verification error(s) occurred for CHECK. Errors: [$.loading_method: should be valid to one and only one of the schemas ]
```

note: we hit the destination API to update the snowflake credentials programmatically. could that be the reason why this version if failing?

**Comment by danieldiamond** [comment]
cc @VitaliiMaltsev 
```
Airbyte Version: 0.39.21-alpha
Source: MySQL (0.5.12)
Destination: Snowflake (0.4.29)
```

**Comment by VitaliiMaltsev** [comment]
@danieldiamond this message is due to the _part_size_ parameter being removed from the spec.

Snowflake credentials should not contain part_size parameter also

**Comment by edgao** [comment]
@VitaliiMaltsev I think we should remove the `additionalProperties: false` entries from the specs. Currently we don't have a way to migrate old-style specs (which contain the part_size property), so preexisting connections will fail until they're manually fixed.

**Comment by VitaliiMaltsev** [comment]
@edgao do you want me to create a PR for this?
Which connectors require `additionalProperties: false` field to be removed?

**Comment by edgao** [comment]
let's just do the ones in this PR for now (bigquery, bigquery-denormalized, gcs, redshift, snowflake) so that users can upgrade them safely. The other ones can be handled later.

**Comment by VitaliiMaltsev** [comment]
> let's just do the ones in this PR for now (bigquery, bigquery-denormalized, gcs, redshift, snowflake) so that users can upgrade them safely. The other ones can be handled later.

@edgao please review https://github.com/airbytehq/airbyte/pull/14114

**Pull request merged**
