### PR TITLE
cleanup: delete debezium 1-4-2 module

### PR DESCRIPTION
**Pull request by subodh1810**
The module is not used. All the 3 DBs (Postgres, MySQL and MSSQL) have been upgraded to use the 1-9-6 module so this can be deleted. This PR makes me happy! :D 

Should only be merged after https://github.com/airbytehq/airbyte/pull/18732 is merged

### CODE REVIEW

**Review by rodireich — APPROVED** [review]

**Comment by rodireich** [comment]
🥳

**Comment by rodireich** [comment]
woohoo!

**Review by akashkulk — APPROVED** [review]
Nice! Unrelated question : I see a directory for dbz v-1-9-2 here. Where exactly is that used (if at all)?

**Comment by subodh1810** [comment]
@akashkulk where do you see 1-9-2? We were on 1-9-2 before but it shouldnt exist anymore. Can you point it out

**Comment by akashkulk** [comment]
> @akashkulk where do you see 1-9-2? We were on 1-9-2 before but it shouldnt exist anymore. Can you point it out

Nevermind, I think it's some local generated files that haven't gotten deleted:
https://www.loom.com/i/8a3417bd3a8c456283b562ba990394cf

**Review by tuliren — APPROVED** [review]
🎉

**Pull request merged**
