### PR TITLE
✨Source Cart.com: Migrate Python CDK to Low-code CDK

### PR DESCRIPTION
**Pull request by VICIWUOHA**
## What
*Migrate Cart.com source to Low Code CDK*

## How
*Developed Using Low Code CDK and Connector UI*

## Recommended reading order
1. `spec.yaml`
2. `manifest.yaml`

## 🚨 User Impact 🚨
*Are there any breaking changes? Some New streams Added and One Authenticator removed.*
*Some things yet to be fixed*
This change  closes #28929 
**Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
The current Cart connector has two type of Auth. @VICIWUOHA how are you planning to implement the second one? As described in the code [here](https://github.com/airbytehq/airbyte/blob/690479d221210f9510eef35b30ad85b0dcc6283c/airbyte-integrations/connectors/source-cart/source_cart/source.py#L31-L83)

**Comment by VICIWUOHA** [comment]
> Hello 👋 , right now Airbyte's integration tests are failing for this connector and I'm going to work during the week to fix them. Due a high number of contributions we have a backlog and your contribution will be review next week. We ask to you share the integration test from your side whatever possible and if you don't have credentials to run tests to get in touch with @RealChrisSean as soon as possible. Also some common missing steps contributors does migrating to low code are (and you can double check to make sure you implemented this):
> 
> * adding paginator
> * update the documentation changelog + metadata file and dockerfile version
> * if the connector has `start_date` parameter you must implement incremental syncs

@marcosmarxm , sure would review the test cases.
- At the moment, i can confirm that a paginator has been added, I would validate the documentation changelog in /docs/integrations/sources/cart.md . I think a bump to 0.3.0 should do.

- Incremental syncs were implemented, would also uncomment the tests for this.

**Comment by VICIWUOHA** [comment]
> The current Cart connector has two type of Auth. @VICIWUOHA how are you planning to implement the second one? As described in the code [here](https://github.com/airbytehq/airbyte/blob/690479d221210f9510eef35b30ad85b0dcc6283c/airbyte-integrations/connectors/source-cart/source_cart/source.py#L31-L83)

@marcosmarxm , I have checked the developer docs thoroughly for a recommendation or implementation of the **Central API Router** as previously seen, but cannot find any implementation or notes on this . What do you recommend? As i am not sure of how to go about implementing it in spec.yaml.

**Comment by marcosmarxm** [comment]
> > The current Cart connector has two type of Auth. @VICIWUOHA how are you planning to implement the second one? As described in the code [here](https://github.com/airbytehq/airbyte/blob/690479d221210f9510eef35b30ad85b0dcc6283c/airbyte-integrations/connectors/source-cart/source_cart/source.py#L31-L83)
> 
> @marcosmarxm , I have checked the developer docs thoroughly for a recommendation or implementation of the **Central API Router** as previously seen, but cannot find any implementation or notes on this . What do you recommend? As i am not sure of how to go about implementing it in spec.yaml.

You will need to use a custom component to have two different type of auth. You can keep the same class and only transfer to the low code component.

**Comment by VICIWUOHA** [comment]
> @VICIWUOHA are you planning to continue the work here?

@marcosmarxm, sure I am. Was going to ask for clarity on how exactly I should implement a custom component for the auth. Also, note that I have embedded the streams as part of the manifest.py as against having a seperate streams folder with json files.

**Comment by marcosmarxm** [comment]
> > @VICIWUOHA are you planning to continue the work here?
> 
> @marcosmarxm, sure I am. Was going to ask for clarity on how exactly I should implement a custom component for the auth. Also, note that I have embedded the streams as part of the manifest.py as against having a seperate streams folder with json files.

Yes, you must implement a custom component for the auth. For the streams great! :D The most complicated part is to migrate the auth. Make sure you solve the conflicts too.

**Comment by marcosmarxm** [comment]
@VICIWUOHA checking if you continue the work here

**Comment by marcosmarxm** [comment]
@VICIWUOHA are you planning to continue the work here?

**Comment by VICIWUOHA** [comment]
> @VICIWUOHA are you planning to continue the work here?

@marcosmarxm Yes  i am still on it. was Just going to ask if you have any connectors implementing such Custom auth with the Low Code CDK.

What i have tried:

- Adding two auth specifications to the `spec.yaml`
   - The challenge now is how to implement the former python logic that was used for this.
   - If there are any clear docs that could guide , this would be fine for me.

**Comment by marcosmarxm** [comment]
> > @VICIWUOHA are you planning to continue the work here?
> 
> @marcosmarxm Yes i am still on it. was Just going to ask if you have any connectors implementing such Custom auth with the Low Code CDK.
> 
> What i have tried:
> 
> * Adding two auth specifications to the `spec.yaml`
>   
>   * The challenge now is how to implement the former python logic that was used for this.
>   * If there are any clear docs that could guide , this would be fine for me.

Check Retently connector implementation it will give you some idea about how to implement it.

**Comment by VICIWUOHA** [comment]
> > > @VICIWUOHA are you planning to continue the work here?
> > 
> > 
> > @marcosmarxm Yes i am still on it. was Just going to ask if you have any connectors implementing such Custom auth with the Low Code CDK.
> > What i have tried:
> > 
> > * Adding two auth specifications to the `spec.yaml`
> >   
> >   * The challenge now is how to implement the former python logic that was used for this.
> >   * If there are any clear docs that could guide , this would be fine for me.
> 
> Check Retently connector implementation it will give you some idea about how to implement it.

@marcosmarxm  , so i have checked this as recommended. The only challenge is that there is no means to validate this based on what is spcified by [cart.com authentication docs](https://developers.cart.com/docs/rest-api/ZG9jOjU4NjM4-cart-com-online-store-api-authentication).

1) Do i simply move the previous logic from source.py into components.py  and restructure the entire manifest.yaml ?

2) Cart.com supports either an API token or OAUTH2 method, not sure how you implemented this [CentralRouter Class](https://github.com/airbytehq/airbyte/blob/399b4d1fca169a3d1df48b569f28fd9eefdabecf/airbyte-integrations/connectors/source-cart/source_cart/source.py#L47C1-L47C7) in the past based on a ticket request. It's been uneasy for me at this point. Perharps you could help from here ?? I could just simply fix the streams for backward compatibility as that's one of the issues on my PR.

**Comment by marcosmarxm** [comment]
Hello @VICIWUOHA I'll try pushing some changes during the week.

**Comment by marcosmarxm** [comment]
Hello, and thank you so much for contributing to the project during the Hackathon. Due to the high complexity of the code migration, we still have a few contributions open. I'm sending this message to update you that this contribution will be added to the final points we're going to announce tomorrow. With that said, we ask for your help to continue the process and finish the review.

**Comment by VICIWUOHA** [comment]
This duly noted @marcosmarxm . Would look forward to another session.
Would be onboarding a new connector soon.

**Pull request closed without merging**
