### PR TITLE
Revert back to erroring out on a null cursor value

### LINKED ISSUE #17150: Database Sources: Handle when a cursor value is NULL
[This PR](https://github.com/airbytehq/airbyte/pull/17131) adds the ability for nullable columns to be the cursor. This is to handle the case where the user doesn't really have control over the schema there (or is a view). However, we still need actual values in these columns to reliably sync.

For example, Airbyte sorts the table based on the cursor field and have a where clause `> lastCursorValue`, and different SQL databases put null values differently in sorting. Postgres puts them after non-null values, while SQL Server and MySQL puts them before non-null values.
So it means if there are new null values:
* Postgres connector can sync them, at the price of duplicating all null values each time.
* SQL Server and MySQL cannot sync them, because of the “>” where clause will filter them all out.

We should consider throwing an error to be less surprising and prevent users from getting into a bad state.

### PR DESCRIPTION
**Pull request by rodireich**
## What
Put back the original change that stopped a sync when a null cursor value is discovered.
This will reverse the temporary fix we put in [#oncall/1159](https://github.com/airbytehq/oncall/issues/1159#issuecomment-1379106478).

### CODE REVIEW

**Review by ryankfu — APPROVED** [review]
LGTM

**Comment by rodireich** [comment]
/publish connector=connectors/source-alloydb-strict-encrypt auto-bump-version=false

**Comment by rodireich** [comment]
/publish connector=connectors/source-postgres-strict-encrypt auto-bump-version=false

**Pull request merged**
