### PR TITLE
doc (fix): updated changelog version in Bigquery

### PR DESCRIPTION
**Pull request by Jagrutiti**
## What
*Describe what the change is solving*

Updated changelog version from 0.6.8  to 0.6.10 in Bigquery file.

## Closes
Destination Bigquery: the changelog is not up to date airbytehq/airbyte-internal-issues#451

### CODE REVIEW

**Comment by marcosmarxm** [comment]
This is not solving the issue. You must see the dockerfile changes from 0.6.8 TO 0.6.10

**Comment by Jagrutiti** [comment]
Hey @marcosmarxm 

Which is that PR? I am unable to find it.

**Comment by marcosmarxm** [comment]
You must check the Dockerfile history of Bigquery and see what PR change from that versions.

**Comment by marcosmarxm** [comment]
Close due inactivity.

**Pull request closed without merging**
