### PR TITLE
airbyte server: ignore aws secret manager value for default secret persistence

### PR DESCRIPTION
**Pull request by mohitreddy1996**
## What
Fix Airbyte server crashing due to multiple instances of Persistent Secret instance provider when secret.persistence is set as AWS_SECRET_MANAGER

## How
First instance is from `awsSecretPersistence` and the second instance being provided is from `defaultSecretPersistence`. 

## Recommended reading order
1. `SecretPersistenceBeanFactory.java`

## 🚨 User Impact 🚨
Fixes bug when secret manager is set as AWS_SECRET_MANAGER

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

Fixes bug on Airbyte server. Fails with - 

```
2023-01-17 02:25:44 ERROR i.m.r.Micronaut(handleStartupException):338 - Error starting Micronaut server: Bean definition [io.airbyte.server.apis.SourceDefinitionApiController] could not be loaded: Failed to inject value for parameter [secretPersistence] of method [secretsHydrator] of class: io.airbyte.config.persistence.split_secrets.SecretsHydrator

Message: Multiple possible bean candidates found: [io.airbyte.config.persistence.split_secrets.SecretPersistence, io.airbyte.config.persistence.split_secrets.SecretPersistence]
Path Taken: new SourceDefinitionApiController(SourceDefinitionsHandler sourceDefinitionsHandler) --> new SourceDefinitionApiController([SourceDefinitionsHandler sourceDefinitionsHandler]) --> new SourceDefinitionsHandler(ConfigRepository configRepository,Supplier uuidSupplier,SynchronousSchedulerClient schedulerSynchronousClient,AirbyteGithubStore githubStore,[SourceHandler sourceHandler],AirbyteProtocolVersionRange protocolVersionRange) --> new SourceHandler(ConfigRepository configRepository,[SecretsRepositoryReader secretsRepositoryReader],SecretsRepositoryWriter secretsRepositoryWriter,JsonSchemaValidator integrationSchemaValidation,ConnectionsHandler connectionsHandler,Supplier uuidGenerator,JsonSecretsProcessor secretsProcessor,ConfigurationUpdate configurationUpdate,OAuthConfigSupplier oAuthConfigSupplier) --> SecretsRepositoryReader.secretsRepositoryReader(ConfigRepository configRepository,[SecretsHydrator secretsHydrator]) --> SecretsHydrator.secretsHydrator([SecretPersistence secretPersistence])
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.airbyte.server.apis.SourceDefinitionApiController] could not be loaded: Failed to inject value for parameter [secretPersistence] of method [secretsHydrator] of class: io.airbyte.config.persistence.split_secrets.SecretsHydrator

Message: Multiple possible bean candidates found: [io.airbyte.config.persistence.split_secrets.SecretPersistence, io.airbyte.config.persistence.split_secrets.SecretPersistence]
Path Taken: new SourceDefinitionApiController(SourceDefinitionsHandler sourceDefinitionsHandler) --> new SourceDefinitionApiController([SourceDefinitionsHandler sourceDefinitionsHandler]) --> new SourceDefinitionsHandler(ConfigRepository configRepository,Supplier uuidSupplier,SynchronousSchedulerClient schedulerSynchronousClient,AirbyteGithubStore githubStore,[SourceHandler sourceHandler],AirbyteProtocolVersionRange protocolVersionRange) --> new SourceHandler(ConfigRepository configRepository,[SecretsRepositoryReader secretsRepositoryReader],SecretsRepositoryWriter secretsRepositoryWriter,JsonSchemaValidator integrationSchemaValidation,ConnectionsHandler connectionsHandler,Supplier uuidGenerator,JsonSecretsProcessor secretsProcessor,ConfigurationUpdate configurationUpdate,OAuthConfigSupplier oAuthConfigSupplier) --> SecretsRepositoryReader.secretsRepositoryReader(ConfigRepository configRepository,[SecretsHydrator secretsHydrator]) --> SecretsHydrator.secretsHydrator([SecretPersistence secretPersistence])
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1921) ~[micronaut-inject-3.8.0.jar:3.8.0]
```

## Tests

<details><summary><strong>Unit</strong></summary>

N/A

</details>

<details><summary><strong>Integration</strong></summary>

N/A

</details>

<details><summary><strong>Acceptance</strong></summary>

N/A

</details>

### CODE REVIEW

**Comment by mohitreddy1996** [comment]
@jdpgrailsdev @benmoriceau @pmossman Could you please take a look at this change?

I believe this was missed out in - https://github.com/airbytehq/airbyte/pull/21073

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Comment by mohitreddy1996** [comment]
@jdpgrailsdev thanks a lot for the review. Sorry the branch was out of date, so I updated it. Looks like I might need your approvals again to kick off the merge workflow?

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Comment by jdpgrailsdev** [comment]
@mohitreddy1996 Thanks for the fix!

**Pull request merged**
