### PR TITLE
mysql test int types

### PR DESCRIPTION
**Pull request by cgardens**
## What
* trying to debug a user issue where int2 is being treated as a boolean in MySQL. haven't been able to recreate yet. Hoping that he can share the type he has set in MySQL so that I can add it to the test. ([slack](https://airbytehq.slack.com/archives/C01MFR03D5W/p1618437872017500))

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368225212657) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by cgardens** [comment]
@ChristopheDuong @davinchia reminder to review this please.

**Comment by marcosmarxm** [comment]
Just a few ideas that pop out of my head:
- which MySQL version is used;
- if source data is stored with some special notion (int2 zerofill, int2 unsigned, etc)

I've run some tests myself and always got the result in postgres as float (double precision);
Another test: Mysql stores boolean as tinyint(1) and in this case Airbyte could transfer correctly as boolean into Postgres.

**Review by davinchia — APPROVED** [review]
It's a good start!

**Review by jrhizor — APPROVED** [review]

**Comment by davinchia** [comment]
@cgardens merge this in?

**Pull request merged**
