### PR TITLE
Upgrade to JDK 15

### PR DESCRIPTION
**Pull request by sherifnada**
## What
JDK15 introduces [Text blocks](https://openjdk.java.net/jeps/378) aka multiline strings. It is also a LTS supported version of java, unlike 14. 

Apart from Jacoco (which we don't use much and will release JDK 15 support soon), it seems like all our dependencies work with this version. 

## How
Use java v15 in github workflow runners and docker images.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368203536911) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by michel-tricot** [comment]
Any downside to migrating?

**Comment by sherifnada** [comment]
Other than potential compatibility with libraries, nothing that I can see. We'd need to stop using jacoco but imo that's not an issue.

**Comment by sherifnada** [comment]
will get back to this after Jan launch

**Pull request closed without merging**
