### PR TITLE
 🎉  Source Google Ads: Add fields to the campaign stream 🚨 

### LINKED ISSUE #18070: source-google-ads: 🎉  Add fields to the campaign stream
## Tell us about the problem you're trying to solve

- There are some missing key metrics, such as 
- Records in campaigns lack granularity since it doesn't include the "segment.hour" field.

## Describe the solution you’d like

- Add segments.hour field to increase granularity
- Add key metric fields to the stream such as metrics.ctr, metrics.conversions and metrics.conversions_value

## Describe the alternative you’ve considered or used
 
If its not that feasible, we could make a new stream with the new granularity?

## Are you willing to submit a PR?

Yes! number of PR is #18069

### PR DESCRIPTION
**Pull request by mutt-santiago-stachuk**
## What

- Add segments.hour field to increase granularity
- Add key metric fields to the stream such as `metrics.ctr`, `metrics.conversions` and `metrics.conversions_value`

## How
 Add fields to the schema

## Recommended reading order
1. `airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/campaigns.json`

## 🚨 User Impact 🚨
Maybe some changes may be expected as granularity will increase from date to hour

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

closes #18070

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks for the contribution @mutt-santiago-stachuk someone will review this during the week.

**Comment by sajarin** [comment]
Thanks for the PR @mutt-santiago-stachuk, this PR is part of AIrbyte's Community Maintainer program and someone from our community will be assigned to help get this PR merged into our main branch. Please ping me if you don't hear anything back within 48 hours! 

Happy Hacktober! :)

**Review by vincentkoc — APPROVED** [review]
@mutt-santiago-stachuk thanks for your contribution, i added one or two minor changes to make your build ready. Will approve now and get this PR merged.

**Comment by pietrobon** [comment]
Hi!
I've realized that after this update, I'm not being able to load the stream from campaign if I choose to use all available fields.

Looking into the error I've found that the metrics.conversions and metrics.conversions_value was designed as integer by default but looking into the google ads documentation those fields are configured as double.

When the etl ends and start to run the dbt default transforms it raises an error with incompatible data format. The data from the api arrives as double and the table created by airbyte are configured as integer.

Thanks in advance.

**Comment by mutt-santiago-stachuk** [comment]
Thanks for the catch @pietrobon, I'm gonna create an issue about it, and mention you there! If you want to author or don't want to be mentioned, just tell me :)

**Comment by pietrobon** [comment]
> Thanks for the catch @pietrobon, I'm gonna create an issue about it, and mention you there! If you want to author or don't want to be mentioned, just tell me :)

Hey! Thanks for replying so fast. I think you can go an Author, I'm glad with a mention <3

**Comment by tigitz** [comment]
@mutt-santiago-stachuk @koconder I believe this introduced a [regression explained here](https://github.com/airbytehq/airbyte/issues/20283), had to downgrade in the meantime.

**Pull request merged**
