### PR TITLE
🐛  Source Zoom Bugfix: declare correct types to match data coming from API

### LINKED ISSUE #2927: Zoom Source fails to load data
## Expected Behavior
Connector executes well. My destination (BigQuery) shows the zoom tables. 

## Current Behavior
- Connector fails, see logs.
- Target db contains raw tables (like `_airbyte_raw_zoom_meeting_files`, `_airbyte_raw_zoom_meetings`)
- Target db raw tables contain raw json data

## Logs
[logs-244-2.txt](https://github.com/airbytehq/airbyte/files/6329495/logs-244-2.txt)

## Steps to Reproduce
Nothing special.

1. Create Zoom Connector as described in the [tutorial](https://docs.airbyte.io/tutorials/zoom-activity-dashboard)
2. Creator connector

## Severity of the bug for you
Very low

## Airbyte Version
Found in the .env file in the root of the project.

## Connector Version (if applicable)
Found in the admin page in the UI in the respective Source or Destination tab.

## Additional context
*Environment, version, integration...*

### PR DESCRIPTION
**Pull request by vovavovavovavova**
## What
closes #2927 .

## How
Bumping zoom-tap library version that includes fix.

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

## Recommended reading order
1. `test.java`
1. `component.ts`
1. the rest

### CODE REVIEW

**Review by keu — APPROVED** [review]
please make sure to reproduce scenario that @sherifnada mentioned

**Comment by sherifnada** [comment]
here: https://github.com/airbytehq/airbyte/issues/2927

**Review by po3na4skld — APPROVED** [review]

**Comment by keu** [comment]
@vovavovavovavova what do you need to proceed with this? I think you probably forgot about this ticket

**Pull request merged**
