### PR TITLE
🐛 Source Amplitude : Updates cursor_field in the Amplitude Events stream to the proper field server_upload_time

### PR DESCRIPTION
**Pull request by mariamthiam**
## What
Addressing Issue https://github.com/airbytehq/airbyte/issues/16943 - Source amplitude uses wrong field as "cursor_field"  
Set cursor to server_upload_time

## How
Updates "cursor_field" in the Amplitude Events stream to the proper field server_upload_time

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*
This is a fix PR, it should be a minor release.

## Pre-merge Checklist
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Connector version has been incremented
    - [x] Version has been bumped according to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/semantic-versioning-for-connectors) guidelines
    - [x] `Dockerfile` has updated version
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` with an entry for the new version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)

- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Comment by mariamthiam** [comment]
@Nmaxime  and @bazarnov , I'm reopening the PR https://github.com/airbytehq/airbyte/pull/17268 here! 
We need  this to be merged to continue using the connector.

**Comment by bazarnov** [comment]
@evantahler @marcosmarxm Are you able to check this PR from your side? 

@mariamthiam Did we answer the question here:  https://github.com/airbytehq/airbyte/pull/17268#discussion_r999877191?
In particular, https://github.com/airbytehq/airbyte/pull/17268#discussion_r1002186720 this comment.

**Comment by mariamthiam** [comment]
@bazarnov  yes I did the changes with `stream_state.get(self.cursor_field, stream_state.get("event_time"))`

**Comment by mariamthiam** [comment]
@evantahler @marcosmarxm can you please help with the CI errors  ?

**Comment by evantahler** [comment]
Adding some detail to @bazarnov's comment above - the full error is:

```
E       connector_acceptance_test.utils.backward_compatibility.NonBackwardCompatibleError: BackwardIncompatibilityContext.DISCOVER - The value of 'default_cursor_field' was changed. Diff: Value of root['events'][0] changed from "event_time" to "server_upload_time".
```

... which is true.  This means that users upgrading from the old version of the connector to this version will be re-importing old data for incremental syncs.  We've got 2 choices:
1. This should be a breaking change
2. This warning should be ignored, and re-importing data is OK in this intance.

I think I'm comfortable with option 2 in this case - Airbyte doesn't guarantee at-once delivery, and this is fixing a bug.  @bazarnov, what do you think?  

@mariamthiam to tell our CAT test suite to ignore this change, you'll be modifying [acceptance-test-config.yml](https://github.com/airbytehq/airbyte/blob/fcbf6d1c539b9f1cc0296046f44470c0392d1e0b/airbyte-integrations/connectors/source-amplitude/acceptance-test-config.yml) and adding a [bypass reason](https://docs.airbyte.com/connector-development/testing-connectors/connector-acceptance-tests-reference/#test-basic-read)

**Comment by bazarnov** [comment]
@evantahler thanks for the question,
I'm totally agree with option 2, if this it is ok for the product side of the question and overall customers satisfaction.

**Comment by mariamthiam** [comment]
@evantahler and  @bazarnov I have done it !

**Comment by mariamthiam** [comment]
should be fix by  #22362

**Pull request closed without merging**
