### PR TITLE
Fix incorrect documentation url.

### LINKED ISSUE #2341: Webapp's Http Request Source documentation link is not correct.
## Expected Behavior
When I try click for instructions on how to connect the Http Request, I should be redirected to https://docs.airbyte.io/integrations/sources/http-request.

Screen Shot 2021-03-06 at 7 28 37 PM

## Current Behavior
I am instead redirected to https://docs.airbyte.io/integrations/sources/rest-api, which is none existent.

## Steps to Reproduce
1. Open the app, select the http request source in the onboarding flow.
2. Click on the link offers to bring user to instructions.

## Severity of the bug for you
Medium

## Connector Version (if applicable)
Found in the admin page in the UI in the respective Source or Destination tab.

## Additional context
*Environment, version, integration...*

### PR DESCRIPTION
**Pull request by davinchia**
## What
Bad documentation url.

## How
Update to the right url.

## Pre-merge Checklist
- [ ] *Run integration tests*
- [ ] *Publish Docker images*

### CODE REVIEW

**Review by sherifnada — CHANGES_REQUESTED** [review]
Nice! 

For this change to be shipped to Airbyte users we need to bump the connector version and publish it. To do that do the following:
1. Bump the version of the connector inside the Dockerfile in its module root 
2. Bump the version of the connector in the source_definitions yaml and the corresponding generated JSON
3. Push your changes to this PR (you should have bumped the version in 3 different locations at this point)
4. Comment on this PR with "/publish connector=connectors/source-http". This will launch a workflow that runs integration tests and publishes the new image version if they succeed. 
5. Merge!

**Comment by sherifnada** [comment]
i mistyped the name in my comment, the full name is `source-http-request`

**Comment by sherifnada** [comment]
so you'll need `/publish connector=connectors/source-http-request`

**Review by sherifnada — APPROVED** [review]

**Comment by davinchia** [comment]
I checked the logs, spent some time scratching my head and decided to defer to today since it was late my side - I am a dumbass for not checking the command itself heh

**Pull request merged**
