### PR TITLE
🐛 Source E-Commerce: fix start date parameter in spec

### PR DESCRIPTION
**Pull request by theomarshanti**
## What
Right now it is impossible to register a new CommerceTools source. This is because the `json-schema` for `start-date` specifies two mutually incompatible conditions. It declares the type be a start-date, which *requires* HHMMSS _and_  it declares the type to be a date format. This causes JSON-Schema failures like the following:

POST http://localhost:8000/api/v1/sources/create
```
{
    "name": "Commercetools",
    "sourceDefinitionId": "008b2e26-11a3-11ec-82a8-0242ac130003",
    "workspaceId": "4853dbc7-d665-4c32-844e-a48156633689",
    "connectionConfiguration": {
        "start_date": "2024-01-01",
        "client_id": "<>",
        "client_secret": "<>",
        "project_key": "<>",
        "region": "<>",
        "host": "<>"
    }
}
```

```
{
    "message": "The provided configuration does not fulfill the specification. Errors: json schema validation failed when comparing the data to the json schema. \nErrors: $.start_date: is missing but it is required \nSchema: \n{\n  \"type\" : \"object\",\n  \"$schema\" : \"http://json-schema.org/draft-07/schema#\",\n  \"required\" : [ \"start_date\", \"client_id\", \"client_secret\", \"host\", \"project_key\", \"region\" ],\n  \"properties\" : {\n    \"host\" : {\n      \"enum\" : [ \"gcp\", \"aws\" ],\n      \"type\" : \"string\",\n      \"order\" : 3,\n      \"title\" : \"Host\",\n      \"description\" : \"The cloud provider your shop is hosted. See: https://docs.commercetools.com/api/authorization\"\n    },\n    \"region\" : {\n      \"type\" : \"string\",\n      \"order\" : 5,\n      \"title\" : \"Region\",\n      \"examples\" : [ \"us-central1\", \"australia-southeast1\" ],\n      \"description\" : \"The region of the platform.\"\n    },\n    \"client_id\" : {\n      \"type\" : \"string\",\n      \"order\" : 1,\n      \"title\" : \"Client ID\",\n      \"description\" : \"Id of API Client.\",\n      \"airbyte_secret\" : true\n    },\n    \"start_date\" : {\n      \"type\" : \"string\",\n      \"order\" : 0,\n      \"title\" : \"Start date\",\n      \"format\" : \"date-time\",\n      \"pattern\" : \"^[0-9]{4}-[0-9]{2}-[0-9]{2}$\"\n    },\n    \"project_key\" : {\n      \"type\" : \"string\",\n      \"order\" : 4,\n      \"title\" : \"Project key\",\n      \"description\" : \"The project key\"\n    },\n    \"client_secret\" : {\n      \"type\" : \"string\",\n      \"order\" : 2,\n      \"title\" : \"Client secret\",\n      \"description\" : \"The password of secret of API Client.\",\n      \"airbyte_secret\" : true\n    }\n  },\n  \"additionalProperties\" : true\n}",
    "exceptionClassName": "io.airbyte.commons.server.errors.BadObjectSchemaKnownException",
    "exceptionStack": [
        "io.airbyte.commons.server.errors.BadObjectSchemaKnownException: The provided configuration does not fulfill the specification. Errors: json schema validation failed when comparing the data to the json schema. ",
        "Errors: $.start_date: is missing but it is required ",
        "Schema: ",
        "{",
        "  \"type\" : \"object\",",
        "  \"$schema\" : \"http://json-schema.org/draft-07/schema#\",",
        "  \"required\" : [ \"start_date\", \"client_id\", \"client_secret\", \"host\", \"project_key\", \"region\" ],",
        "  \"properties\" : {",
        "    \"host\" : {",
        "      \"enum\" : [ \"gcp\", \"aws\" ],",
        "      \"type\" : \"string\",",
        "      \"order\" : 3,",
        "      \"title\" : \"Host\",",
        "      \"description\" : \"The cloud provider your shop is hosted. See: https://docs.commercetools.com/api/authorization\"",
        "    },",
        "    \"region\" : {",
        "      \"type\" : \"string\",",
        "      \"order\" : 5,",
        "      \"title\" : \"Region\",",
        "      \"examples\" : [ \"us-central1\", \"australia-southeast1\" ],",
        "      \"description\" : \"The region of the platform.\"",
        "    },",
        "    \"client_id\" : {",
        "      \"type\" : \"string\",",
        "      \"order\" : 1,",
        "      \"title\" : \"Client ID\",",
        "      \"description\" : \"Id of API Client.\",",
        "      \"airbyte_secret\" : true",
        "    },",
        "    \"start_date\" : {",
        "      \"type\" : \"string\",",
        "      \"order\" : 0,",
        "      \"title\" : \"Start date\",",
        "      \"format\" : \"date-time\",",
        "      \"pattern\" : \"^[0-9]{4}-[0-9]{2}-[0-9]{2}$\"",
        "    },",
        "    \"project_key\" : {",
        "      \"type\" : \"string\",",
        "      \"order\" : 4,",
        "      \"title\" : \"Project key\",",
        "      \"description\" : \"The project key\"",
        "    },",
        "    \"client_secret\" : {",
        "      \"type\" : \"string\",",
        "      \"order\" : 2,",
        "      \"title\" : \"Client secret\",",
        "      \"description\" : \"The password of secret of API Client.\",",
        "      \"airbyte_secret\" : true",
        "    }",
        "  },",
        "  \"additionalProperties\" : true",
        "}",
        "\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:40)",
        "\tat io.airbyte.server.apis.SourceApiController.createSource(SourceApiController.java:101)",
        "\tat io.airbyte.server.apis.$SourceApiController$Definition$Exec.dispatch(Unknown Source)",
        "\tat io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)",
        "\tat io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)",
        "\tat io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)",
        "\tat io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)",
        "\tat io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)",
        "\tat io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)",
        "\tat reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)",
        "\tat reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)",
        "\tat reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)",
        "\tat io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)",
        "\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)",
        "\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)",
        "\tat io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)",
        "\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)",
        "\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)",
        "\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)",
        "\tat java.base/java.lang.Thread.run(Thread.java:1583)",
        "Caused by: io.airbyte.validation.json.JsonValidationException: json schema validation failed when comparing the data to the json schema. ",
        "Errors: $.start_date: is missing but it is required ",
        "Schema: ",
        "{",
        "  \"type\" : \"object\",",
        "  \"$schema\" : \"http://json-schema.org/draft-07/schema#\",",
        "  \"required\" : [ \"start_date\", \"client_id\", \"client_secret\", \"host\", \"project_key\", \"region\" ],",
        "  \"properties\" : {",
        "    \"host\" : {",
        "      \"enum\" : [ \"gcp\", \"aws\" ],",
        "      \"type\" : \"string\",",
        "      \"order\" : 3,",
        "      \"title\" : \"Host\",",
        "      \"description\" : \"The cloud provider your shop is hosted. See: https://docs.commercetools.com/api/authorization\"",
        "    },",
        "    \"region\" : {",
        "      \"type\" : \"string\",",
        "      \"order\" : 5,",
        "      \"title\" : \"Region\",",
        "      \"examples\" : [ \"us-central1\", \"australia-southeast1\" ],",
        "      \"description\" : \"The region of the platform.\"",
        "    },",
        "    \"client_id\" : {",
        "      \"type\" : \"string\",",
        "      \"order\" : 1,",
        "      \"title\" : \"Client ID\",",
        "      \"description\" : \"Id of API Client.\",",
        "      \"airbyte_secret\" : true",
        "    },",
        "    \"start_date\" : {",
        "      \"type\" : \"string\",",
        "      \"order\" : 0,",
        "      \"title\" : \"Start date\",",
        "      \"format\" : \"date-time\",",
        "      \"pattern\" : \"^[0-9]{4}-[0-9]{2}-[0-9]{2}$\"",
        "    },",
        "    \"project_key\" : {",
        "      \"type\" : \"string\",",
        "      \"order\" : 4,",
        "      \"title\" : \"Project key\",",
        "      \"description\" : \"The project key\"",
        "    },",
        "    \"client_secret\" : {",
        "      \"type\" : \"string\",",
        "      \"order\" : 2,",
        "      \"title\" : \"Client secret\",",
        "      \"description\" : \"The password of secret of API Client.\",",
        "      \"airbyte_secret\" : true",
        "    }",
        "  },",
        "  \"additionalProperties\" : true",
        "}",
        "\tat io.airbyte.validation.json.JsonSchemaValidator.ensure(JsonSchemaValidator.java:157)",
        "\tat io.airbyte.commons.server.handlers.SourceHandler.validateSource(SourceHandler.java:444)",
        "\tat io.airbyte.commons.server.handlers.SourceHandler.createSource(SourceHandler.java:162)",
        "\tat io.airbyte.commons.server.handlers.SourceHandler.createSourceWithOptionalSecret(SourceHandler.java:129)",
        "\tat io.airbyte.server.apis.SourceApiController.lambda$createSource$4(SourceApiController.java:101)",
        "\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:28)",
        "\t... 19 more"
    ],
    "rootCauseExceptionClassName": "java.lang.Class",
    "rootCauseExceptionStack": [
        "io.airbyte.validation.json.JsonValidationException: json schema validation failed when comparing the data to the json schema. ",
        "Errors: $.start_date: is missing but it is required ",
        "Schema: ",
        "{",
        "  \"type\" : \"object\",",
        "  \"$schema\" : \"http://json-schema.org/draft-07/schema#\",",
        "  \"required\" : [ \"start_date\", \"client_id\", \"client_secret\", \"host\", \"project_key\", \"region\" ],",
        "  \"properties\" : {",
        "    \"host\" : {",
        "      \"enum\" : [ \"gcp\", \"aws\" ],",
        "      \"type\" : \"string\",",
        "      \"order\" : 3,",
        "      \"title\" : \"Host\",",
        "      \"description\" : \"The cloud provider your shop is hosted. See: https://docs.commercetools.com/api/authorization\"",
        "    },",
        "    \"region\" : {",
        "      \"type\" : \"string\",",
        "      \"order\" : 5,",
        "      \"title\" : \"Region\",",
        "      \"examples\" : [ \"us-central1\", \"australia-southeast1\" ],",
        "      \"description\" : \"The region of the platform.\"",
        "    },",
        "    \"client_id\" : {",
        "      \"type\" : \"string\",",
        "      \"order\" : 1,",
        "      \"title\" : \"Client ID\",",
        "      \"description\" : \"Id of API Client.\",",
        "      \"airbyte_secret\" : true",
        "    },",
        "    \"start_date\" : {",
        "      \"type\" : \"string\",",
        "      \"order\" : 0,",
        "      \"title\" : \"Start date\",",
        "      \"format\" : \"date-time\",",
        "      \"pattern\" : \"^[0-9]{4}-[0-9]{2}-[0-9]{2}$\"",
        "    },",
        "    \"project_key\" : {",
        "      \"type\" : \"string\",",
        "      \"order\" : 4,",
        "      \"title\" : \"Project key\",",
        "      \"description\" : \"The project key\"",
        "    },",
        "    \"client_secret\" : {",
        "      \"type\" : \"string\",",
        "      \"order\" : 2,",
        "      \"title\" : \"Client secret\",",
        "      \"description\" : \"The password of secret of API Client.\",",
        "      \"airbyte_secret\" : true",
        "    }",
        "  },",
        "  \"additionalProperties\" : true",
        "}",
        "\tat io.airbyte.validation.json.JsonSchemaValidator.ensure(JsonSchemaValidator.java:157)",
        "\tat io.airbyte.commons.server.handlers.SourceHandler.validateSource(SourceHandler.java:444)",
        "\tat io.airbyte.commons.server.handlers.SourceHandler.createSource(SourceHandler.java:162)",
        "\tat io.airbyte.commons.server.handlers.SourceHandler.createSourceWithOptionalSecret(SourceHandler.java:129)",
        "\tat io.airbyte.server.apis.SourceApiController.lambda$createSource$4(SourceApiController.java:101)",
        "\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:28)",
        "\tat io.airbyte.server.apis.SourceApiController.createSource(SourceApiController.java:101)",
        "\tat io.airbyte.server.apis.$SourceApiController$Definition$Exec.dispatch(Unknown Source)",
        "\tat io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)",
        "\tat io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)",
        "\tat io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)",
        "\tat io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)",
        "\tat io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)",
        "\tat io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)",
        "\tat reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)",
        "\tat reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)",
        "\tat reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)",
        "\tat io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)",
        "\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)",
        "\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)",
        "\tat io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)",
        "\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)",
        "\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)",
        "\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)",
        "\tat java.base/java.lang.Thread.run(Thread.java:1583)"
    ]
}
```
 

*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/resources/pull-requests-handbook)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:generateScaffolds` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

<details><summary><strong>Updating the Python CDK</strong></summary>

### Airbyter

Before merging:
- Pull Request description explains what problem it is solving
- Code change is unit tested
- Build and my-py check pass
- Smoke test the change on at least one affected connector
   - On Github: Run [this workflow](https://github.com/airbytehq/airbyte/actions/workflows/connectors_tests.yml), passing `--use-local-cdk --name=source-<connector>` as options
   - Locally: `airbyte-ci connectors --use-local-cdk --name=source-<connector> test`
- PR is reviewed and approved
      
After merging:
- [Publish the CDK](https://github.com/airbytehq/airbyte/actions/workflows/publish-cdk-command-manually.yml)
   - The CDK does not follow proper semantic versioning. Choose minor if this the change has significant user impact or is a breaking change. Choose patch otherwise.
   - Write a thoughtful changelog message so we know what was updated.
- Merge the platform PR that was auto-created for updating the Connector Builder's CDK version
   - This step is optional if the change does not affect the connector builder or declarative connectors.

</details>

### CODE REVIEW

**Comment by theomarshanti** [comment]
Responds to this issue:
https://github.com/airbytehq/airbyte/issues/34133

**Comment by marcosmarxm** [comment]
Closed as inactive.

**Comment by twest-nuts** [comment]
@marcosmarxm  - was there a reason why this PR was closed and not merged? We are running into a similar issue and was wondering if you found a work-around? 

cc: @datasurfergtx

**Comment by mombrea** [comment]
@marcosmarxm is it possible to get this pull request re-opened? We're also unable to use the connector because of the issue.

**Pull request closed without merging**
