### PR TITLE
Update Salesforce API version to fix missing columns problem

### LINKED ISSUE #23253: Source: Salesforce - missing columns because of old API version is used
## Environment
- **Airbyte version**:  0.40.28
- **OS Version / Instance**: n1-standard-4
- **Deployment**: Kubernetes
- **Source Connector and version**: Salesforce 1.0.29
- **Destination Connector and version**: BigQuery 1.2.9
- **Step where error happened**: Sync job

## Current Behavior
*Tell us what happens.*
When we sync data from Salesforce to BQ, some columns are missing compared to our legacy ETLs which uses different tech. After analyzing Salesforce REST API, I noticed that those columns are missing if I use v52.0 version of the API (like Airbyte does now) but they appear if I use a newer Salesforce REST API version (v57.0).

If I use v52.0 (like Airbyte does now):
https://openx.my.salesforce.com/services/data/v52.0 
Then some columns are missing

But when I use the newest version of API:
https://openx.my.salesforce.com/services/data/v57.0
Then all the expected columns show up. 

## Expected Behavior
I expect to see all the columns. 

## Logs
There is probably nothing interesting in the logs from the technical point of view because the operation succeeds. Also, I would probably need to work on redacting some of internal information if I were to share it.

## Steps to Reproduce
I can't tell exactly what do affected columns have in common (I can't share exact schema), but my experiment prove that updating schema version makes the problem go away.

## Are you willing to submit a PR?

Yes, I already found the line to change https://github.com/airbytehq/airbyte/blob/f1bab07d25a118e0f347869e6bc8b3820ba757e4/airbyte-integrations/connectors/source-salesforce/source_salesforce/api.py#L209

Plus some tests

### PR DESCRIPTION
**Pull request by Bisk1**
## What
- this change will fix the problem with some columns being skipped for Salesforce source - these columns are not compatible with the older version of Salesforce REST API used so far in Salesforce connector.
- fix https://github.com/airbytehq/airbyte/issues/23253

## How
Updating Salesforce API endpoint version to the newest Salesforce API version: v57.0

## Recommended reading order
N/A, it's a trivial change - just changed v52.0 to v57.0 everywhere.

## 🚨 User Impact 🚨
No negative user impact. Some existing Salesforce connections should be able to pick up schema change when requested.

## Pre-merge Checklist
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Comment by Bisk1** [comment]
Unit tests passed: 
image
Some integration tests fail on my environment, but so do they on master branch. I suppose that's because the Salesforce instance that I use for integration tests is configured differently.
image

**Comment by Bisk1** [comment]
To be honest the error message from the build looks cryptic: 
image
I don't know what is there for me to do to fix it.

**Comment by marcosmarxm** [comment]
Hello @Bisk1 thanks for the request. The connector team is going to work in updating the Salesforce API version next week and hope to use your code as a base.

**Comment by marcosmarxm** [comment]
Hello @Bisk1 https://github.com/airbytehq/airbyte/pull/25352 updated the API to v53 for now. Hope in the future we can update to a more recent version of Salesforce but for now this is the safest decision to keep the connector working without breaking changes.

**Pull request closed without merging**
