### PR TITLE
Use bmuschko plugin for some connector builds

### PR DESCRIPTION
**Pull request by edgao**
## What
Partly addresses https://github.com/airbytehq/airbyte-internal-issues/issues/373

This puts us in a better position WRT our docker builds. E.g. airbyteDocker's change detection is broken (again); the bmuschko plugin should be better in that regard.

## How
Create a new plugin to wrap around the bmuschko plugin, which sets airbyte-specific defaults. This is based on the [tasks](https://github.com/airbytehq/airbyte/blob/f6141871247abb3ecebf12de7af1af3fd3a07b8a/build.gradle#L147) that Platform is using, but extracted into a plugin.

### Testing
Verified against a few connectors. After approval, I'll run `/publish` against base-normalization, source-mongodb, and destination-redshift to verify that it works, and then merge.

See the three test comments starting at https://github.com/airbytehq/airbyte/pull/13565#issuecomment-1171760396

### Future work
* Migrate all connectors away from the legacy airbyte-docker plugin
* Migrate core modules (e.g. `source-acceptance-test`)
* delete the legacy airbyte-docker plugin
* (maybe) migrate platform modules - the only benefit of this is that it consolidates all our docker build logic

## Recommended reading order
1. airbyte-docker-bmuschko.gradle
2. The other files in buildSrc (build.gradle, integration-test-java, performance-test-java, source-acceptance-test, standard-source-test-file)
3. destination-s3, source-mongodb, source-stripe (these are using the new plugin)
4. base-normalization build.gradle + dockerignore, destination-redshift/build.gradle - note that base-normalization now depends on `destination-redshift:buildDockerImage`, and that destination-redshift's integration tests depend solely on `base-normalization:buildDockerImage-redshift.Dockerfile'
5. all the other `build.gradle`s, e.g. destination-bigquery/build.gradle, destination-mysql/build.gradle - these now depend on base-normalization's new buildDockerImage-XYZ tasks
6. `tools/*`

## 🚨 User Impact 🚨
None; this is purely a change to our build pipeline

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hello :wave:, first thank you for this amazing contribution. 

We really appreciate the effort you've made to improve the project.
We ask you patience for the code review. Last month our team was focused on Hacktoberfest event and that probably left some PR without the proper feedback. And this week, due to the Thanksgiving US Holiday, most our team is out of office with their families. Another important piece of information why code won't be merge this week is: as a safety measure the core team has decided to freeze merging code to main branch to keep the release stable. Next week we'll return to you with the proper code review and update the status of your contribution.

If you have any questions feel free to send me a message in Slack!
Thanks!

**Comment by sherifnada** [comment]
closing to remove notification noise, will likely revisit as part of the effort to improve our build

**Pull request closed without merging**
