### PR TITLE
fix(connectors docs): updated connectors to follow standard template

### PR DESCRIPTION
**Pull request by darynaishchenko**
## What
as part of https://github.com/airbytehq/airbyte-internal-issues/issues/2887

## How
Updated source connectors with sl >= 300 to follow standard template and pass qa check that is implemented [here](https://github.com/airbytehq/airbyte/pull/39326) 

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by natikgadzhi — APPROVED** [review]

**Review by girarda — APPROVED** [review]
:shipit:

**Review by girarda — APPROVED** [review]
looks good @darynaishchenko !

**Comment by octavia-approvington** [comment]
Send it! <br/> rocket socks

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
