### PR TITLE
🐛 Source Mongo: fix potential npe when collecting stats

### PR DESCRIPTION
**Pull request by colesnodgrass**
## What
- avoid NPE in `getCollectionStats` call
   ```
   Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
        at java.util.ImmutableCollections$MapN.<init>(ImmutableCollections.java:1186) ~[?:?]</init>
        at java.util.Map.of(Map.java:1373) ~[?:?]
        at io.airbyte.db.mongodb.MongoDatabase.getCollectionStats(MongoDatabase.java:140) ~[io.airbyte.airbyte-db-db-lib-24.0.2.jar:?]
   ```
- update version; `0.2.3` -> `0.2.4`

## How
- ensure values pulled from `collectionStats` `Document` are not `null` before calling `Map.of`
- update `catch` statement in `getCollectionStats` to catch all exceptions, not only `MongoCommandException`
    - an failure to collect these stats should not result in a sync failing 

## Recommended reading order
1. `MongoDatabase.java`
2. everything else

### CODE REVIEW

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:  Also update the release notes with a pointer to this PR.

**Comment by octavia-squidington-iii** [comment]
##  destination-vertica test report (commit [`d760258fe6`](https://github.com/airbytehq/airbyte/pull/28760/commits/d760258fe61ca2d3a84273e54c9094d69dddc831)) - ❌

⏲️  Total pipeline duration: 01mn32s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-vertica/metadata.yaml | ✅        |
| Connector version semver check                                             | ✅        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690412126/d760258fe61ca2d3a84273e54c9094d69dddc831/destination-vertica/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-vertica test
```

**Comment by octavia-squidington-iii** [comment]
##  source-postgres test report (commit [`d760258fe6`](https://github.com/airbytehq/airbyte/pull/28760/commits/d760258fe61ca2d3a84273e54c9094d69dddc831)) - ✅

⏲️  Total pipeline duration: 14mn47s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ✅        |
| Build source-postgres docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-postgres:integrationTest | ✅        |
| Acceptance tests                                                           | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690412126/d760258fe61ca2d3a84273e54c9094d69dddc831/source-postgres/3.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-redpanda test report (commit [`d760258fe6`](https://github.com/airbytehq/airbyte/pull/28760/commits/d760258fe61ca2d3a84273e54c9094d69dddc831)) - ❌

⏲️  Total pipeline duration: 06mn02s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-redpanda/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-redpanda docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-redpanda:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690412126/d760258fe61ca2d3a84273e54c9094d69dddc831/destination-redpanda/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redpanda test
```

**Comment by octavia-squidington-iii** [comment]
##  source-db2 test report (commit [`d760258fe6`](https://github.com/airbytehq/airbyte/pull/28760/commits/d760258fe61ca2d3a84273e54c9094d69dddc831)) - ❌

⏲️  Total pipeline duration: 06mn40s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-db2/metadata.yaml     | ✅        |
| Connector version semver check                                        | ✅        |
| QA checks                                                             | ✅        |
| Build connector tar                                                   | ✅        |
| Build source-db2 docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-db2:integrationTest | ❌        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690412126/d760258fe61ca2d3a84273e54c9094d69dddc831/source-db2/0.1.20/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-db2 test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-kinesis test report (commit [`d760258fe6`](https://github.com/airbytehq/airbyte/pull/28760/commits/d760258fe61ca2d3a84273e54c9094d69dddc831)) - ✅

⏲️  Total pipeline duration: 10mn05s 

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-kinesis/metadata.yaml     | ✅        |
| Connector version semver check                                                 | ✅        |
| QA checks                                                                      | ✅        |
| Build connector tar                                                            | ✅        |
| Build destination-kinesis docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-kinesis:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690412126/d760258fe61ca2d3a84273e54c9094d69dddc831/destination-kinesis/0.1.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-kinesis test
```

**Comment by octavia-squidington-iii** [comment]
##  source-oracle-strict-encrypt test report (commit [`d760258fe6`](https://github.com/airbytehq/airbyte/pull/28760/commits/d760258fe61ca2d3a84273e54c9094d69dddc831)) - ❌

⏲️  Total pipeline duration: 20mn27s 

| Step                                                                                    | Result   |
|:----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-oracle-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                          | ✅        |
| QA checks                                                                               | ✅        |
| Build connector tar                                                                     | ✅        |
| Build source-oracle-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-oracle-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690412126/d760258fe61ca2d3a84273e54c9094d69dddc831/source-oracle-strict-encrypt/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-oracle-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-azure-blob-storage test report (commit [`d760258fe6`](https://github.com/airbytehq/airbyte/pull/28760/commits/d760258fe61ca2d3a84273e54c9094d69dddc831)) - ❌

⏲️  Total pipeline duration: 09mn23s 

| Step                                                                                      | Result   |
|:------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-azure-blob-storage/metadata.yaml     | ✅        |
| Connector version semver check                                                            | ✅        |
| QA checks                                                                                 | ✅        |
| Build connector tar                                                                       | ✅        |
| Build destination-azure-blob-storage docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-azure-blob-storage:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690412126/d760258fe61ca2d3a84273e54c9094d69dddc831/destination-azure-blob-storage/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-azure-blob-storage test
```

**Comment by octavia-approvington** [comment]
Send it! <br/> rocket socks

**Review by octavia-approvington — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  destination-exasol test report (commit [`f405b97da6`](https://github.com/airbytehq/airbyte/pull/28760/commits/f405b97da6e7c1702fbc73445b77acff790382c7)) - ❌

⏲️  Total pipeline duration: 10mn46s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-exasol/metadata.yaml     | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ❌        |
| Build connector tar                                                           | ✅        |
| Build destination-exasol docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-exasol:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690498578/f405b97da6e7c1702fbc73445b77acff790382c7/destination-exasol/0.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-exasol test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-dynamodb test report (commit [`f405b97da6`](https://github.com/airbytehq/airbyte/pull/28760/commits/f405b97da6e7c1702fbc73445b77acff790382c7)) - ✅

⏲️  Total pipeline duration: 20mn20s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-dynamodb/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-dynamodb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-dynamodb:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690498578/f405b97da6e7c1702fbc73445b77acff790382c7/destination-dynamodb/0.1.7/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-dynamodb test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-databricks test report (commit [`f405b97da6`](https://github.com/airbytehq/airbyte/pull/28760/commits/f405b97da6e7c1702fbc73445b77acff790382c7)) - ❌

⏲️  Total pipeline duration: 55mn08s 

| Step                                                                              | Result   |
|:----------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-databricks/metadata.yaml     | ✅        |
| Connector version semver check                                                    | ✅        |
| QA checks                                                                         | ✅        |
| Build connector tar                                                               | ✅        |
| Build destination-databricks docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-databricks:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690498578/f405b97da6e7c1702fbc73445b77acff790382c7/destination-databricks/1.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-databricks test
```

**Comment by octavia-squidington-iii** [comment]
##  source-tidb test report (commit [`f405b97da6`](https://github.com/airbytehq/airbyte/pull/28760/commits/f405b97da6e7c1702fbc73445b77acff790382c7)) - ❌

⏲️  Total pipeline duration: 10mn32s 

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-tidb/metadata.yaml     | ✅        |
| Connector version semver check                                         | ✅        |
| QA checks                                                              | ✅        |
| Build connector tar                                                    | ✅        |
| Build source-tidb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-tidb:integrationTest | ✅        |
| Acceptance tests                                                       | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690498578/f405b97da6e7c1702fbc73445b77acff790382c7/source-tidb/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tidb test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-selectdb test report (commit [`f405b97da6`](https://github.com/airbytehq/airbyte/pull/28760/commits/f405b97da6e7c1702fbc73445b77acff790382c7)) - ❌

⏲️  Total pipeline duration: 22mn49s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-selectdb/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ❌        |
| Build connector tar                                                             | ✅        |
| Build destination-selectdb docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-selectdb:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690498578/f405b97da6e7c1702fbc73445b77acff790382c7/destination-selectdb/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-selectdb test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mysql test report (commit [`f405b97da6`](https://github.com/airbytehq/airbyte/pull/28760/commits/f405b97da6e7c1702fbc73445b77acff790382c7)) - ❌

⏲️  Total pipeline duration: 51mn13s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mysql/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build destination-mysql docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mysql:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mysql:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690498578/f405b97da6e7c1702fbc73445b77acff790382c7/destination-mysql/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mysql test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-postgres test report (commit [`f405b97da6`](https://github.com/airbytehq/airbyte/pull/28760/commits/f405b97da6e7c1702fbc73445b77acff790382c7)) - ❌

⏲️  Total pipeline duration: 47mn09s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-postgres/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-postgres docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-postgres:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690498578/f405b97da6e7c1702fbc73445b77acff790382c7/destination-postgres/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-postgres test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-e2e-test test report (commit [`f405b97da6`](https://github.com/airbytehq/airbyte/pull/28760/commits/f405b97da6e7c1702fbc73445b77acff790382c7)) - ❌

⏲️  Total pipeline duration: 08mn31s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-e2e-test/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-e2e-test docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-e2e-test:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690498578/f405b97da6e7c1702fbc73445b77acff790382c7/destination-e2e-test/0.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-e2e-test test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-pubsub test report (commit [`f405b97da6`](https://github.com/airbytehq/airbyte/pull/28760/commits/f405b97da6e7c1702fbc73445b77acff790382c7)) - ✅

⏲️  Total pipeline duration: 19mn11s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-pubsub/metadata.yaml     | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Build connector tar                                                           | ✅        |
| Build destination-pubsub docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-pubsub:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690498578/f405b97da6e7c1702fbc73445b77acff790382c7/destination-pubsub/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-pubsub test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mariadb-columnstore test report (commit [`f405b97da6`](https://github.com/airbytehq/airbyte/pull/28760/commits/f405b97da6e7c1702fbc73445b77acff790382c7)) - ❌

⏲️  Total pipeline duration: 95mn59s 

| Step                                                                                       | Result   |
|:-------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mariadb-columnstore/metadata.yaml     | ✅        |
| Connector version semver check                                                             | ✅        |
| QA checks                                                                                  | ✅        |
| Build connector tar                                                                        | ✅        |
| Build destination-mariadb-columnstore docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mariadb-columnstore:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690498578/f405b97da6e7c1702fbc73445b77acff790382c7/destination-mariadb-columnstore/0.1.7/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mariadb-columnstore test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-tidb test report (commit [`f405b97da6`](https://github.com/airbytehq/airbyte/pull/28760/commits/f405b97da6e7c1702fbc73445b77acff790382c7)) - ✅

⏲️  Total pipeline duration: 28mn05s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-tidb/metadata.yaml     | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |
| Build connector tar                                                         | ✅        |
| Build destination-tidb docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-tidb:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-tidb:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690498578/f405b97da6e7c1702fbc73445b77acff790382c7/destination-tidb/0.1.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-tidb test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-gcs test report (commit [`f405b97da6`](https://github.com/airbytehq/airbyte/pull/28760/commits/f405b97da6e7c1702fbc73445b77acff790382c7)) - ✅

⏲️  Total pipeline duration: 15mn25s 

| Step                                                                       | Result   |
|:---------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-gcs/metadata.yaml     | ✅        |
| Connector version semver check                                             | ✅        |
| QA checks                                                                  | ✅        |
| Build connector tar                                                        | ✅        |
| Build destination-gcs docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-gcs:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690498578/f405b97da6e7c1702fbc73445b77acff790382c7/destination-gcs/0.4.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-gcs test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-mysql-strict-encrypt test report (commit [`f405b97da6`](https://github.com/airbytehq/airbyte/pull/28760/commits/f405b97da6e7c1702fbc73445b77acff790382c7)) - ❌

⏲️  Total pipeline duration: 40mn29s 

| Step                                                                                        | Result   |
|:--------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-mysql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                              | ✅        |
| QA checks                                                                                   | ✅        |
| Build connector tar                                                                         | ✅        |
| Build destination-mysql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-mysql:dev                                                       | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-mysql-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690498578/f405b97da6e7c1702fbc73445b77acff790382c7/destination-mysql-strict-encrypt/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-mysql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery-denormalized test report (commit [`f405b97da6`](https://github.com/airbytehq/airbyte/pull/28760/commits/f405b97da6e7c1702fbc73445b77acff790382c7)) - ✅

⏲️  Total pipeline duration: 26mn16s 

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ✅        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-bigquery-denormalized docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery-denormalized:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690498578/f405b97da6e7c1702fbc73445b77acff790382c7/destination-bigquery-denormalized/1.5.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-keen test report (commit [`f405b97da6`](https://github.com/airbytehq/airbyte/pull/28760/commits/f405b97da6e7c1702fbc73445b77acff790382c7)) - ✅

⏲️  Total pipeline duration: 14mn13s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-keen/metadata.yaml     | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |
| Build connector tar                                                         | ✅        |
| Build destination-keen docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-keen:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690498578/f405b97da6e7c1702fbc73445b77acff790382c7/destination-keen/0.2.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-keen test
```

**Comment by octavia-squidington-iii** [comment]
##  source-oracle-strict-encrypt test report (commit [`f405b97da6`](https://github.com/airbytehq/airbyte/pull/28760/commits/f405b97da6e7c1702fbc73445b77acff790382c7)) - ❌

⏲️  Total pipeline duration: 20mn34s 

| Step                                                                                    | Result   |
|:----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-oracle-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                          | ✅        |
| QA checks                                                                               | ✅        |
| Build connector tar                                                                     | ✅        |
| Build source-oracle-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-oracle-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/cole_mongo-npe-fix/1690498578/f405b97da6e7c1702fbc73445b77acff790382c7/source-oracle-strict-encrypt/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-oracle-strict-encrypt test
```

**Pull request merged**
