### PR TITLE
Integrate Sentry for performance and errors tracking.

### LINKED ISSUE #7958: Sentry: Obfuscation and dealing with sensitive data
Here we explore all options that Sentry provides for obfuscation and dealing with sensitive data

### PR DESCRIPTION
**Pull request by avida**
Draft PR for #7959 

This is a prototype PR of integrating Sentry into connectors for automatic exception reporting and performance monitoring.

It have been tested on couple of connectors by running locally with DSN passed over SENTRY_DSN environment variable. 

Here is a link to browse issues created by Sentry https://sentry.io/organizations/zazmic-wl
 @sherifnada You should have received an invite to access this link

### CODE REVIEW

**Comment by sherifnada** [comment]
@avida thanks for sharing. I like how simple this implementation is. I took a look at sentry -- my guess is that performance monitoring might be the most useful thing for us, since logs can _typically_ tell us what the exceptions were. WDYT? 

Also, do you have an idea of what pricing might look like for our cases?

**Comment by avida** [comment]
To enable sentry for any of connector that using cdk you need:
1. Install proper version of cdk.
2. set sentry DSN over "SENTRY_DSN" environment variable

**Comment by tuliren** [comment]
@avida, could you add to that Sentry project as well? My username is `liren@airbyte.io` on Sentry. Thank you.

**Review by sherifnada — COMMENTED** [review]
@sergei-solonitcyn can you manage taking this to the finish line? i won't have bandwidth to review

**Review by sergei-solonitcyn — APPROVED** [review]

**Comment by VasylLazebnyk** [comment]
closes #7958

**Pull request merged**
