### PR TITLE
Fix/destination s3 default provider

### PR DESCRIPTION
**Pull request by xorl**
## What
- Updates destination-s3 connector to support AWSDefaultProfileCredentials provider.
- This new provider uses [DefaultAWSCredentialsProviderChain](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html) which looks for credential in the following order:
  - Environment Variables
  - Java System Properties
  - Web Identity Token credentials from the environment or container
  - Credential profiles file at the default location
  - Credentials delivered through the Amazon EC2 container service
  - Instance profile credentials delivered through the Amazon EC2 metadata service

## How
Removes INSTANCE_PROFILE and replaces it with DEFAULT_PROVIDER allowing proper STS authentication with ServiceAccounts and credentials chain.

## 🚨 User Impact 🚨
- Users will be able to use S3 with more credential providers.

### CODE REVIEW

**Comment by xorl** [comment]
> [CLA assistant check](https://cla-assistant.io/airbytehq/airbyte?pullRequest=14231) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/airbytehq/airbyte?pullRequest=14231) before we can accept your contribution.**1** out of **3** committers have signed the CLA.✅ xorl❌ Ryan Lewon❌ remlabm
> 
> **Ryan Lewon** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/airbytehq/airbyte?pullRequest=14231) it.

**Comment by marcosmarxm** [comment]
@xorl can you @remlabm to sign the CLA too?

**Comment by tuliren** [comment]
Great, thank you very much! I will publish a new version including this change.

**Review by tuliren — APPROVED** [review]

**Comment by xorl** [comment]
> 

Done!

**Comment by KPhans** [comment]
What airbyte version is this available for? i am running on 0.40.0-alpha and still required to input not empty values for both secret key and Access id

**Comment by joekor** [comment]
@xorl Hi, i tried installing airbyte into EKS, with a service account and an IRSA role.
i'm getting a similar error, where the worker is expecting values for AWS within helm, and not starting up properly.
version: 0.45.20
2023-05-22 12:46:06 INFO i.a.w.ApplicationInitializer(initializeCommonDependencies):191 - Initializing common worker dependencies.
26
2023-05-22 12:46:06 ERROR i.m.r.Micronaut(handleStartupException):338 - Error starting Micronaut server: null
25
java.lang.IllegalArgumentException: null
24
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:131) ~[guava-31.1-jre.jar:?]
23
	at io.airbyte.config.storage.DefaultS3ClientFactory.validateBase(DefaultS3ClientFactory.java:36) ~[io.airbyte.airbyte-config-config-models-0.44.4.jar:?]
22
	at io.airbyte.config.storage.DefaultS3ClientFactory.validate(DefaultS3ClientFactory.java:31) ~[io.airbyte.airbyte-config-config-models-0.44.4.jar:?]
21
	at io.airbyte.config.storage.DefaultS3ClientFactory.<init>(DefaultS3ClientFactory.java:24) ~[io.airbyte.airbyte-config-config-models-0.44.4.jar:?]
20
	at io.airbyte.config.helpers.CloudLogs.createCloudLogClient(CloudLogs.java:51) ~[io.airbyte.airbyte-config-config-models-0.44.4.jar:?]
19
	at io.airbyte.config.helpers.LogClientSingleton.createCloudClientIfNull(LogClientSingleton.java:226) ~[io.airbyte.airbyte-config-config-models-0.44.4.jar:?]
18
	at io.airbyte.config.helpers.LogClientSingleton.setWorkspaceMdc(LogClientSingleton.java:213) ~[io.airbyte.airbyte-config-config-models-0.44.4.jar:?]
17
	at io.airbyte.workers.ApplicationInitializer.initializeCommonDependencies(ApplicationInitializer.java:194) ~[io.airbyte-airbyte-workers-0.44.4.jar:?]
16
	at io.airbyte.workers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:161) ~[io.airbyte-airbyte-workers-0.44.4.jar:?]
15
	at io.airbyte.workers.ApplicationInitializer.onApplicationEvent(ApplicationInitializer.java:63) ~[io.airbyte-airbyte-workers-0.44.4.jar:?]
14
	at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:262) ~[micronaut-inject-3.9.0.jar:3.9.0]
13
	at io.micronaut.context.event.ApplicationEventPublisherFactory.access$200(ApplicationEventPublisherFactory.java:60) ~[micronaut-inject-3.9.0.jar:3.9.0]
12
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:229) ~[micronaut-inject-3.9.0.jar:3.9.0]
11
	at io.micronaut.http.server.netty.NettyHttpServer.lambda$fireStartupEvents$15(NettyHttpServer.java:587) ~[micronaut-http-server-netty-3.9.0.jar:3.9.0]
10
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]

**Comment by xorl** [comment]
I'll take a look and verify that a front-end change doesn't require credentials, something possibly changed since I patched this.

**Comment by yepher** [comment]
How do we setup an S3 destination using env vars instead of entering the S3 access key in the UI?

image

**Pull request merged**
