### PR TITLE
[source-postgres + CDK] use BigInteger instead of BigInt

### PR DESCRIPTION
**Pull request by theyueli**
## What

Fixes: https://github.com/airbytehq/oncall/issues/6780

We were using BigInt, which is long for the numeric type of Postgres. When the numeric type goes beyond int, we will yield null. This patch will use BigInteger instead, which will support those very large numbers. 

I tested with Snowflake, and it fixes the issue mentioned above.

### CODE REVIEW

**Review by postamar — APPROVED** [review]

**Comment by hkazmicrediblex** [comment]
@theyueli , this resolves the issue that numerice types getting converted to nulls right ?

**Comment by theyueli** [comment]
> @theyueli , this resolves the issue that numerice types getting converted to nulls right ?

hi @hkazmicrediblex , yes, did you see the same problem? it should be fixed in the latest version.

**Comment by hkazmicrediblex** [comment]
> > @theyueli , this resolves the issue that numerice types getting converted to nulls right ?
> 
> hi @hkazmicrediblex , yes, did you see the same problem? it should be fixed in the latest version.

@theyueli , yes i see the same problem i am doing postgres to postgres replication and still got NULLs can you suggest which version should i use

**Pull request merged**
