### PR TITLE
Fix ssh tunneling for normalization

### PR DESCRIPTION
**Pull request by Phlair**
## What
New lines as part of OAuth were added into `/airbyte-integrations/bases/base-normalization/entrypoint.sh` that remove the config file so we don't expose secrets to non-airbyte docker images during custom dbt transformations.

As a side-effect this broke ssh tunnelling in normalisation because it relied on using the config file to get relevant parameters to create the tunnel.

## How
Creating a config `ssh.json` specific for ssh tunnelling in normalization's `transform.py` and using that instead to get parameters for tunnel. This only contains necessary params for tunnelling and no OAuth secrets.

## Recommended reading order
`transform.py`
`sshtunneling.sh`
others

### CODE REVIEW

**Review by ChristopheDuong — APPROVED** [review]
It'd be nice to at least add it to normalization unit_test `TestTransformConfig` for the generated file for ssh too

**Comment by Phlair** [comment]
Looks like [same problem as this](https://github.com/airbytehq/airbyte/pull/6052#issuecomment-925120639) on /publish command but the new version is up on [docker hub](https://hub.docker.com/r/airbyte/normalization/tags?page=1&ordering=last_updated).

**Pull request merged**
