### PR TITLE
Source Oracle: remove TZ env var from CI workflow

### LINKED ISSUE #3010: TZ env variable is an inadvertent dependency of the Airbyte build
## Current Behavior
```
Hi
I am building Airbyte using " ./gradlew build " command but it gave me below error
"OracleSourceTest > testReadSuccess() FAILED
    java.sql.SQLException: Cannot create PoolableConnectionFactory (ORA-00604: error occurred at recursive SQL level 1
    ORA-01882: timezone region not found"
Any solution to resolve this error ?
```

* `./gradlew build` now depends on the host machine having `TZ=UTC` as an env variable. we should not require this and should have the build system handle setting this internally.
* `CORE_ONLY=1 ./gradlew build` seems to be running oracle tests. I haven't been able to reproduce this when running `--dry-run`

convo: https://airbytehq.slack.com/archives/C019WEENQRM/p1618931467288000

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368103202282) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by marcosmarxm**
## What
Closes https://github.com/airbytehq/airbyte/issues/3010

## How
Remove the TZ env var and add system property to Oracle source connector

## Recommended reading order
1. `x.java`
2. `y.python`

### CODE REVIEW

**Review by sherifnada — APPROVED** [review]

**Comment by marcosmarxm** [comment]
@sherifnada this is not working yet

**Comment by marcosmarxm** [comment]
Removing the TZ from CI file break the Oracle source building :(

**Comment by cgardens** [comment]
Weird. There's got to be some way we can set the enviornment variable in docker without having to do it on the host system.

**Pull request closed without merging**
