### PR TITLE
include a list of available timezones for cron string scheduling

### PR DESCRIPTION
**Pull request by mfsiega-airbyte**
## What
Include a list of available timezones for cron string scheduling in the frontend.

## How
- Added a log line in the server (which does the validation) to dump the available IDs in JSON
- Removed the `Etc/` timezones, which we specifically filter out
- Pasted the output into the frontend package

## Recommended reading order
1. `airbyte-webapp/src/config/AvailableTimeZones.json`

## 🚨 User Impact 🚨
No

### CODE REVIEW

**Comment by mfsiega-airbyte** [comment]
This is the lightest-weight solution to unblock frontend work on the scheduling UX.

Some additional possible testing:
- Put this file in some common location between server and webapp
- Add a test in the server package that checks that every timezone in the list is still available.

This can either be added to this PR or done in a follow-up.

Further possible step: generate the list dynamically in the build process.

**Comment by timroes** [comment]
Could we maybe name the file lowercase. Despite some other files in this folder, this is kind of the standard we're going for, if it's not a component/class.

Also maybe we can include that it's about cron, e.g. `availableCronTimeZones.json`?

**Comment by mfsiega-airbyte** [comment]
Updated, please take a look!

**Review by timroes — APPROVED** [review]
LGTM

**Pull request merged**
