### PR TITLE
🐛 Source Mongo: Fix failing acceptance tests

### PR DESCRIPTION
**Pull request by jdpgrailsdev**
## What
* Re-apply fixes to failing acceptance tests for the source-mongodb-v2 connector

## How
* Ensure that the configuration is properly set for Java-based acceptance tests

## Recommended reading order
1. `MongoDbSourceAtlasAcceptanceTest.java`
2. `MongodbSourceStrictEncryptAcceptanceTest.java`

### CODE REVIEW

**Review by colesnodgrass — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-v2 test report (commit [`5bb3c2a52f`](https://github.com/airbytehq/airbyte/pull/28816/commits/5bb3c2a52f0301f7bc589068e2a10bf26ca49f4b)) - ❌

⏲️  Total pipeline duration: 16mn40s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-v2:integrationTest | ❌        |
| Acceptance tests                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_fix-mongo-acceptance-tests/1690488946/5bb3c2a52f0301f7bc589068e2a10bf26ca49f4b/source-mongodb-v2/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-strict-encrypt test report (commit [`5bb3c2a52f`](https://github.com/airbytehq/airbyte/pull/28816/commits/5bb3c2a52f0301f7bc589068e2a10bf26ca49f4b)) - ❌

⏲️  Total pipeline duration: 06mn19s 

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                           | ✅        |
| QA checks                                                                                | ❌        |
| Build connector tar                                                                      | ✅        |
| Build source-mongodb-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_fix-mongo-acceptance-tests/1690488946/5bb3c2a52f0301f7bc589068e2a10bf26ca49f4b/source-mongodb-strict-encrypt/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-strict-encrypt test report (commit [`674c70630f`](https://github.com/airbytehq/airbyte/pull/28816/commits/674c70630f817f43d6c1e3481da85c1c7e7bc8f8)) - ❌

⏲️  Total pipeline duration: 06mn03s 

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                           | ✅        |
| QA checks                                                                                | ❌        |
| Build connector tar                                                                      | ✅        |
| Build source-mongodb-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-strict-encrypt:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_fix-mongo-acceptance-tests/1690807752/674c70630f817f43d6c1e3481da85c1c7e7bc8f8/source-mongodb-strict-encrypt/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-v2 test report (commit [`674c70630f`](https://github.com/airbytehq/airbyte/pull/28816/commits/674c70630f817f43d6c1e3481da85c1c7e7bc8f8)) - ❌

⏲️  Total pipeline duration: 16mn43s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-v2:integrationTest | ❌        |
| Acceptance tests                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_fix-mongo-acceptance-tests/1690807752/674c70630f817f43d6c1e3481da85c1c7e7bc8f8/source-mongodb-v2/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-strict-encrypt test report (commit [`66b4a4abb1`](https://github.com/airbytehq/airbyte/pull/28816/commits/66b4a4abb145c7a8db028d2a4d05bd0ca0c50a5f)) - ❌

⏲️  Total pipeline duration: 06mn45s 

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                           | ✅        |
| QA checks                                                                                | ❌        |
| Build connector tar                                                                      | ✅        |
| Build source-mongodb-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-strict-encrypt:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_fix-mongo-acceptance-tests/1690809873/66b4a4abb145c7a8db028d2a4d05bd0ca0c50a5f/source-mongodb-strict-encrypt/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-v2 test report (commit [`66b4a4abb1`](https://github.com/airbytehq/airbyte/pull/28816/commits/66b4a4abb145c7a8db028d2a4d05bd0ca0c50a5f)) - ❌

⏲️  Total pipeline duration: 15mn21s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-v2:integrationTest | ❌        |
| Acceptance tests                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_fix-mongo-acceptance-tests/1690809873/66b4a4abb145c7a8db028d2a4d05bd0ca0c50a5f/source-mongodb-v2/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

**Comment by jdpgrailsdev** [comment]
The source-mongodb-v2 test failures are not reproducible locally.  I have executed them both via the command line (`./gradlew :airbyte-integrations:connectors:source-mongodb-v2:integrationTest`) and via Intellij and they pass.  I have also run them on this PR using the legacy runner and all of the tests pass, so I assume that there is an issue with the current test execution apparatus.

**Comment by jdpgrailsdev** [comment]
@colesnodgrass Could you please re-review, as I had to fix a few issues with the strict encrypt tests.  Thanks!

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-strict-encrypt test report (commit [`5e827dd583`](https://github.com/airbytehq/airbyte/pull/28816/commits/5e827dd583d7ecb91dcf0cda9b04ada40aeac7ec)) - ❌

⏲️  Total pipeline duration: 02mn22s 

| Step                                                                                 | Result   |
|:-------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                       | ✅        |
| QA checks                                                                            | ❌        |
| Build connector tar                                                                  | ✅        |
| Build source-mongodb-strict-encrypt docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_fix-mongo-acceptance-tests/1690833865/5e827dd583d7ecb91dcf0cda9b04ada40aeac7ec/source-mongodb-strict-encrypt/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-v2 test report (commit [`5e827dd583`](https://github.com/airbytehq/airbyte/pull/28816/commits/5e827dd583d7ecb91dcf0cda9b04ada40aeac7ec)) - ❌

⏲️  Total pipeline duration: 02mn20s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| QA checks                                                                | ✅        |
| Build connector tar                                                      | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_fix-mongo-acceptance-tests/1690833865/5e827dd583d7ecb91dcf0cda9b04ada40aeac7ec/source-mongodb-v2/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-strict-encrypt test report (commit [`c0a6fec651`](https://github.com/airbytehq/airbyte/pull/28816/commits/c0a6fec6512e6f04fc6f9a0c1249239170617350)) - ❌

⏲️  Total pipeline duration: 06mn42s 

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                           | ✅        |
| QA checks                                                                                | ❌        |
| Build connector tar                                                                      | ✅        |
| Build source-mongodb-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-strict-encrypt:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_fix-mongo-acceptance-tests/1690896727/c0a6fec6512e6f04fc6f9a0c1249239170617350/source-mongodb-strict-encrypt/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-v2 test report (commit [`c0a6fec651`](https://github.com/airbytehq/airbyte/pull/28816/commits/c0a6fec6512e6f04fc6f9a0c1249239170617350)) - ❌

⏲️  Total pipeline duration: 12mn03s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-v2:integrationTest | ❌        |
| Acceptance tests                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_fix-mongo-acceptance-tests/1690896727/c0a6fec6512e6f04fc6f9a0c1249239170617350/source-mongodb-v2/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-strict-encrypt test report (commit [`0ece0612f7`](https://github.com/airbytehq/airbyte/pull/28816/commits/0ece0612f7b1ee2493889aa00ab8b15f25cd13f6)) - ❌

⏲️  Total pipeline duration: 02mn58s 

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                           | ✅        |
| QA checks                                                                                | ❌        |
| Build connector tar                                                                      | ✅        |
| Build source-mongodb-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-strict-encrypt:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/jonathan_fix-mongo-acceptance-tests/1690905692/0ece0612f7b1ee2493889aa00ab8b15f25cd13f6/source-mongodb-strict-encrypt/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-v2 test report (commit [`0ece0612f7`](https://github.com/airbytehq/airbyte/pull/28816/commits/0ece0612f7b1ee2493889aa00ab8b15f25cd13f6)) - ❌

⏲️  Total pipeline duration: 09mn14s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-v2:integrationTest | ❌        |
| Acceptance tests                                                             | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/jonathan_fix-mongo-acceptance-tests/1690905692/0ece0612f7b1ee2493889aa00ab8b15f25cd13f6/source-mongodb-v2/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-strict-encrypt test report (commit [`8ba431c10d`](https://github.com/airbytehq/airbyte/pull/28816/commits/8ba431c10d3ce676fd30c57a443b9cacfadd9750)) - ❌

⏲️  Total pipeline duration: 05mn36s 

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                           | ✅        |
| QA checks                                                                                | ❌        |
| Build connector tar                                                                      | ✅        |
| Build source-mongodb-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-strict-encrypt:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/jonathan_fix-mongo-acceptance-tests/1691007378/8ba431c10d3ce676fd30c57a443b9cacfadd9750/source-mongodb-strict-encrypt/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-v2 test report (commit [`8ba431c10d`](https://github.com/airbytehq/airbyte/pull/28816/commits/8ba431c10d3ce676fd30c57a443b9cacfadd9750)) - ❌

⏲️  Total pipeline duration: 12mn04s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-v2:integrationTest | ❌        |
| Acceptance tests                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/jonathan_fix-mongo-acceptance-tests/1691007378/8ba431c10d3ce676fd30c57a443b9cacfadd9750/source-mongodb-v2/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-strict-encrypt test report (commit [`8ba431c10d`](https://github.com/airbytehq/airbyte/pull/28816/commits/8ba431c10d3ce676fd30c57a443b9cacfadd9750)) - ❌

⏲️  Total pipeline duration: 24.84s 

| Step                                                                                 | Result   |
|:-------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-strict-encrypt/metadata.yaml | ✅        |
| Connector version semver check                                                       | ✅        |
| QA checks                                                                            | ❌        |
| Build connector tar                                                                  | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/jonathan_fix-mongo-acceptance-tests/1691009471/8ba431c10d3ce676fd30c57a443b9cacfadd9750/source-mongodb-strict-encrypt/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-v2 test report (commit [`8ba431c10d`](https://github.com/airbytehq/airbyte/pull/28816/commits/8ba431c10d3ce676fd30c57a443b9cacfadd9750)) - ❌

⏲️  Total pipeline duration: 11mn34s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mongodb-v2/metadata.yaml     | ✅        |
| Connector version semver check                                               | ✅        |
| QA checks                                                                    | ✅        |
| Build connector tar                                                          | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mongodb-v2:integrationTest | ❌        |
| Acceptance tests                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/jonathan_fix-mongo-acceptance-tests/1691009471/8ba431c10d3ce676fd30c57a443b9cacfadd9750/source-mongodb-v2/0.2.5/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

**Review by jpefaur — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-mongodb-v2 test report (commit [`48c6059aba`](https://github.com/airbytehq/airbyte/pull/28816/commits/48c6059abad668e804b88da114b300c9a04b2407)) - ❌

⏲️  Total pipeline duration: 19.71s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_fix-mongo-acceptance-tests/1691071763/48c6059abad668e804b88da114b300c9a04b2407/source-mongodb-v2/0.2.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:48c6059abad668e804b88da114b300c9a04b2407)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
