### PR TITLE
:bug:  Source S3: timestamp parquet data

### LINKED ISSUE #6594: Source S3 is not able to read Parquet file
## Enviroment
- **Airbyte version:**  0.30.2-alpha
- **OS Version / Instance**: Ubuntu 18.04.5 LTS, AWS EC2, t3a.medium, 4 GB ram, 50 GB Disk.
- **Deployment**: Docker
- **Source Connector and version**:  S3 | airbyte/source-s3 | 0.1.5. 
- **Destination Connector and version**: Snowflake | airbyte/source-snowflake | 0.1.1 
- **Severity**: High ( impacting ingestion capability )
- **Step where error happened**: Sync Job ( while read parquet file in S3 )

## Current Behavior
Failing while reading parquet file from S3.

## Expected Behavior
S3 reader should able to read parquet format and insert normalised format data into Snowflake.

## Logs

```

2021-10-01 05:11:10 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Syncing stream: sf_parquet 
2021-10-01 05:11:10 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Iterating S3 bucket 'airbyte-staging-dotpe' with prefix: 'parquet_test/delivery_order' 
2021-10-01 05:11:10 INFO () DefaultAirbyteStreamFactory(internalLog):90 - determined master schema: {'_airbyte_ab_id': 'string', '_airbyte_emitted_at': 'integer', 'rider': 'string', 'callback': 'string', 'order_id': 'number', 'store_id': 'number', 'created_at': 'string', 'store_type': 'string', 'updated_at': 'string', 'curr_status': 'number', 'merchant_id': 'number', 'is_timed_out': 'number', 'curr_merchant': 'string', 'delivery_state': 'string', 'client_order_id': 'string', 'auto_retry_count': 'number', 'manual_retry_count': 'number'}
2021-10-01 05:11:10 INFO () DefaultAirbyteStreamFactory(internalLog):90 - found 1 row groups
2021-10-01 05:11:10 ERROR () DefaultAirbyteStreamFactory(internalLog):88 - Encountered an exception while reading stream SourceS3
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 124, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 154, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 226, in _read_full_refresh
    for record in records:
  File "/airbyte/integration_code/source_s3/source_files_abstract/stream.py", line 355, in read_records
    for record in file_reader.stream_records(f):
  File "/airbyte/integration_code/source_s3/source_files_abstract/formats/parquet_parser.py", line 113, in stream_records
    batch_dict = batch.to_pydict()
  File "pyarrow/table.pxi", line 938, in pyarrow.lib.RecordBatch.to_pydict
  File "pyarrow/array.pxi", line 1193, in pyarrow.lib.Array.to_pylist
  File "pyarrow/scalar.pxi", line 459, in pyarrow.lib.TimestampScalar.as_py
  File "pyarrow/types.pxi", line 1893, in pyarrow.lib.string_to_tzinfo
  File "pyarrow/error.pxi", line 141, in pyarrow.lib.pyarrow_internal_check_status
ModuleNotFoundError: No module named 'pytz'

2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 - Traceback (most recent call last):
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -   File "/airbyte/integration_code/main.py", line 33, in <module>
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -     launch(source, sys.argv[1:])
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 125, in launch
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -     for message in source_entrypoint.run(parsed_args):
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 116, in run
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -     for message in generator:
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 128, in read
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -     raise e
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 124, in read
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -     internal_config=internal_config,
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 154, in _read_stream
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -     for record in record_iterator:
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 226, in _read_full_refresh
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -     for record in records:
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -   File "/airbyte/integration_code/source_s3/source_files_abstract/stream.py", line 355, in read_records
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -     for record in file_reader.stream_records(f):
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -   File "/airbyte/integration_code/source_s3/source_files_abstract/formats/parquet_parser.py", line 113, in stream_records
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -     batch_dict = batch.to_pydict()
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -   File "pyarrow/table.pxi", line 938, in pyarrow.lib.RecordBatch.to_pydict
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -   File "pyarrow/array.pxi", line 1193, in pyarrow.lib.Array.to_pylist
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -   File "pyarrow/scalar.pxi", line 459, in pyarrow.lib.Timestam
[logs-33-0.txt](https://github.com/airbytehq/airbyte/files/7264299/logs-33-0.txt)
pScalar.as_py
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -   File "pyarrow/types.pxi", line 1893, in pyarrow.lib.string_to_tzinfo
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 -   File "pyarrow/error.pxi", line 141, in pyarrow.lib.pyarrow_internal_check_status
2021-10-01 05:11:10 ERROR () LineGobbler(voidCall):65 - ModuleNotFoundError: No module named 'pytz'
2021-10-01 05:11:11 INFO () DefaultReplicationWorker(run):121 - Source thread complete.
2021-10-01 05:11:11 INFO () DefaultReplicationWorker(run):122 - Waiting for destination thread to join.
 

```

</details>

## Steps to Reproduce
1. Read file from MySql and dumped it them S3 in parquet format.
2. Tried to read parquet format from S3 and then tried to dump into snowflake.
3. While doing 2nd step AirByte is throwing error.

## Are you willing to submit a PR?
I am not sure of the code but logs says there is some issue with pytz module of python.
I am using following package and python 3.7.12, I able to read file in pandas:
Package         Version
--------------- -------
numpy           1.21.2
pandas          1.3.3
pip             21.2.4
pyarrow         5.0.0
python-dateutil 2.8.2
pytz            2021.1
setuptools      47.1.0
six             1.16.0

### PR DESCRIPTION
**Pull request by antixar**
## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 
<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

### CODE REVIEW

**Review by Phlair — CHANGES_REQUESTED** [review]
Looks good technically, but maybe it could be slightly better structured to be more readable? Feels like this is creating another location where parquet types are being defined on top of the PARQUET_TYPES map. Could this all be unified to be a bit more clear + some comments/docstrings on this logic?

**Comment by antixar** [comment]
@Phlair , I've moved all type mappings (pyarrow, json) to a single place.

**Review by Phlair — APPROVED** [review]
Like it, nice one!

**Pull request merged**
