### PR TITLE
🐛 Only take table size info for streams syncing via primary key

### LINKED ISSUE #30363: [source-mysql] Error when reading table size causing syncs to fail
### Connector Name

source-mysql

### Connector Version

3.0.4

### What step the error happened?

During the sync

### Revelant information

https://cloud.airbyte.com/workspaces/b226d62a-38b8-4cfb-84d6-b03c654358d9/connections/a6804b51-08aa-4e79-a6c5-dcfd40d787cc/job-history#4583693::4

### Relevant log output

```shell
2023-09-11 14:44:24 source > ERROR i.a.i.b.s.SshWrappedSource(read):77 Exception occurred while getting the delegate read iterator, closing SSH tunnel java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asLong()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null
        at io.airbyte.integrations.source.mysql.MySqlQueryUtils.lambda$getTableSizeInfoForStreams$5(MySqlQueryUtils.java:119) ~[io.airbyte.airbyte-integrations.connectors-source-mysql-24.0.2.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at io.airbyte.integrations.source.mysql.MySqlQueryUtils.getTableSizeInfoForStreams(MySqlQueryUtils.java:111) ~[io.airbyte.airbyte-integrations.connectors-source-mysql-24.0.2.jar:?]
        at io.airbyte.integrations.source.mysql.initialsync.MySqlInitialReadUtil.getCdcReadIterators(MySqlInitialReadUtil.java:138) ~[io.airbyte.airbyte-integrations.connectors-source-mysql-24.0.2.jar:?]
        at io.airbyte.integrations.source.mysql.MySqlSource.getIncrementalIterators(MySqlSource.java:339) ~[io.airbyte.airbyte-integrations.connectors-source-mysql-24.0.2.jar:?]
        at io.airbyte.integrations.source.mysql.MySqlSource.getIncrementalIterators(MySqlSource.java:77) ~[io.airbyte.airbyte-integrations.connectors-source-mysql-24.0.2.jar:?]
        at io.airbyte.integrations.source.relationaldb.AbstractDbSource.read(AbstractDbSource.java:161) ~[io.airbyte.airbyte-integrations.connectors-source-relational-db-24.0.2.jar:?]
        at io.airbyte.integrations.base.ssh.SshWrappedSource.read(SshWrappedSource.java:75) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.spec_modification.SpecModifyingSource.read(SpecModifyingSource.java:50) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.readSerial(IntegrationRunner.java:271) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:170) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:125) ~[io.airbyte.airbyte-integrations.bases-base-java-24.0.2.jar:?]
        at io.airbyte.integrations.source.mysql_strict_encrypt.MySqlStrictEncryptSource.main(MySqlStrictEncryptSource.java:79) ~[io.airbyte.airbyte-integrations.connectors-source-mysql-strict-encrypt-24.0.2.jar:?]
```

### Contribute

- [ ] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by rodireich**
## What
If at least one stream is syncing via primary key, we attempt to get table info size for _all_,
including full refresh streams and views.
Because views don't have physical byte size we run into an error.
Closes #30363.

## How
Only take table info size for the streams that need it, namely primary key syncing streams.

### CODE REVIEW

**Review by subodh1810 — CHANGES_REQUESTED** [review]
We should just swallow any exception in the method `getTableSizeInfoForStreams` in class `MySqlQueryUtils`. We are already swallowing SQLException.

Also add a null check in that method for values before trying to parse them to long

**Comment by rodireich** [comment]
I see that in case there is no table size info, MySqlInitialLoadHandler would fall back to a default chunk size of 1m rows
```
    if (tableSizeInfo == null || tableSizeInfo.tableSize() == 0 || tableSizeInfo.avgRowLength() == 0) {
      LOGGER.info("Chunk size could not be determined for pair: {}, defaulting to {} rows", pair, DEFAULT_CHUNK_SIZE);
      return DEFAULT_CHUNK_SIZE;
    }
```
I'll add the suggested change so we never fail a sync due to table size failure

**Comment by rodireich** [comment]
All tests passing locally

**Review by prateekmukhedkar — APPROVED** [review]

**Review by subodh1810 — APPROVED** [review]
I pushed a commit as discussed over call. Please make sure to the tests are green locally (CI is broken) before merging.

**Comment by octavia-approvington** [comment]
Lets merge it <br/> sheep thumbs up

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
