### PR TITLE
Ship a breaking change to faker 

### PR DESCRIPTION
**Pull request by erohmensing**
To test the breaking change publish and have an example of a diff with regards to the metadata and the migration file. 

faker only changes from https://github.com/airbytehq/airbyte/pull/28414. Does not include formatting changes as formatting fail got introduced by the comment that I don't actually want to add.

### CODE REVIEW

**Comment by erohmensing** [comment]
Currently in draft because it will not pass until changes in here are merged, i'd appreciate an approval though!

**Review by bnchrch — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`52b112db6d`](https://github.com/airbytehq/airbyte/pull/28485/commits/52b112db6db50ad5385f6f3c5aa786b10047e809)) - ✅

⏲️  Total pipeline duration: 02mn08s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| QA checks                                                           | ✅        |
| Code format checks                                                  | ✅        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ✅        |
| Acceptance tests                                                    | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_faker40/1689806068/52b112db6db50ad5385f6f3c5aa786b10047e809/source-faker/4.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`434b35b2a8`](https://github.com/airbytehq/airbyte/pull/28485/commits/434b35b2a864a42acdfe9d41e2cde3a68e34013c)) - ✅

⏲️  Total pipeline duration: 56.56s 

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| QA checks                                                           | ✅        |
| Code format checks                                                  | ✅        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ✅        |
| Acceptance tests                                                    | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_faker40/1689806290/434b35b2a864a42acdfe9d41e2cde3a68e34013c/source-faker/4.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Pull request merged**
