### PR TITLE
Source Salesforce: perform call to objects list in connection check

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/oncall/issues/629

## How
Perform the call to objects list which causes 403 error in a `check` stage

### CODE REVIEW

**Review by bazarnov — APPROVED** [review]
Only one concern here about the check time, how that changed with this change?

**Review by girarda — APPROVED** [review]

**Comment by davydov-d** [comment]
> Only one concern here about the check time, how that changed with this change?

@bazarnov in average 0.5 sec vs 1.5 sec on my local machine using integration test creds

**Pull request merged**
