### PR TITLE
Connector acceptance test: Fix discovered catalog caching for different configs

### PR DESCRIPTION
**Pull request by grubberr**
## What

- for different configs keep different cached values of discovered catalog
- always reset cache dict if `cache_discovered_catalog=True` (in previous implementation we overwrite on top of old cache - which is not good)

### CODE REVIEW

**Review by evantahler — APPROVED** [review]
👍 pending the connector tests above ^

**Comment by grubberr** [comment]
/publish connector=bases/connector-acceptance-test auto-bump-version=false

**Pull request merged**
