### PR TITLE
🐛 Source [Trello, Zendesk-Support]: Update to the latest CDK Version, update `cursor pagination`

### PR DESCRIPTION
**Pull request by bazarnov**
## What
Resolving:
- https://github.com/airbytehq/airbyte-internal-issues/issues/8402

## How
- bumped `cdk version >= 2.0.0`
- updated `manifest.yml` with updated `cursor pagination` logic

## User Impact
No impact is expected.

## Can this PR be safely reverted and rolled back?
- [X] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by bazarnov** [comment]
TODO:
- fix `unit tests` for `zendesk-support`

**Review by maxi297 — COMMENTED** [review]
The fix looks fine to me. Do we have substreams for those? If so, I think they would be affected by the RFR bug and we need to wait before releasing this

**Review by darynaishchenko — APPROVED** [review]

**Comment by bazarnov** [comment]
Working on the fix for `zendesk-support` pagination.

**Comment by darynaishchenko** [comment]
> Working on the fix for `zendesk-support` pagination.

@bazarnov Maybe this slack [thread](https://airbytehq-team.slack.com/archives/C02TYE9QL9M/p1718877671866279?thread_ts=1718854595.860109&cid=C02TYE9QL9M) will be helpful for zendesk-support fix.

**Review by lazebnyi — APPROVED** [review]

**Pull request merged**
