### PR TITLE
Destination Bigquery: Scaffolding for destinations v2

### PR DESCRIPTION
**Pull request by edgao**
## What
Add a bunch of stuff to run destinations v2. Doesn't affect anything in the normal code path.

See [branch](https://github.com/airbytehq/airbyte/compare/destinations-v2-beta) for the new spec option that triggers the new behavior.

## How
...

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
No impact.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`28ca767cd5`](https://github.com/airbytehq/airbyte/pull/27268/commits/28ca767cd53a7d0798dc92c13c7d8685f2782a42)) - ❌

⏲️  Total pipeline duration: 497 seconds

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml | ✅        |
| Connector version semver check.                                             | ✅        |
| Connector version increment check.                                          | ❌        |
| QA checks                                                                   | ✅        |
| Build connector tar                                                         | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5335770357)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-gcs test report (commit [`a88283168f`](https://github.com/airbytehq/airbyte/pull/27268/commits/a88283168fbc4a86c76f8a178c3678cd2c337c3c)) - ❌

⏲️  Total pipeline duration: 347 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-gcs/metadata.yaml | ✅        |
| Connector version semver check                                         | ❌        |
| Connector version increment check                                      | ❌        |
| QA checks                                                              | ✅        |
| Build connector tar                                                    | ✅        |
| Build destination-gcs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/destination-v2-irl/1687963483/a88283168fbc4a86c76f8a178c3678cd2c337c3c/destination-gcs/0.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-gcs test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`a88283168f`](https://github.com/airbytehq/airbyte/pull/27268/commits/a88283168fbc4a86c76f8a178c3678cd2c337c3c)) - ❌

⏲️  Total pipeline duration: 1906 seconds

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ✅        |
| QA checks                                                                   | ❌        |
| Build connector tar                                                         | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Build airbyte/normalization:dev                                             | ✅        |
| Integration tests                                                           | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/destination-v2-irl/1687963483/a88283168fbc4a86c76f8a178c3678cd2c337c3c/destination-bigquery/1.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`b1f8e237d4`](https://github.com/airbytehq/airbyte/pull/27268/commits/b1f8e237d42f75b989cac70b4c5eb685b335b925)) - ❌

⏲️  Total pipeline duration: 1960 seconds

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ✅        |
| QA checks                                                                   | ❌        |
| Build connector tar                                                         | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Build airbyte/normalization:dev                                             | ✅        |
| Integration tests                                                           | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/destination-v2-irl/1687967155/b1f8e237d42f75b989cac70b4c5eb685b335b925/destination-bigquery/1.4.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-gcs test report (commit [`b1f8e237d4`](https://github.com/airbytehq/airbyte/pull/27268/commits/b1f8e237d42f75b989cac70b4c5eb685b335b925)) - ❌

⏲️  Total pipeline duration: 702 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-gcs/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ✅        |
| QA checks                                                              | ❌        |
| Build connector tar                                                    | ✅        |
| Build destination-gcs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Integration tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/destination-v2-irl/1687967155/b1f8e237d42f75b989cac70b4c5eb685b335b925/destination-gcs/0.4.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-gcs test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-gcs test report (commit [`95ba692175`](https://github.com/airbytehq/airbyte/pull/27268/commits/95ba6921757eeecfe68818b134ff83a625cb5ea0)) - ✅

⏲️  Total pipeline duration: 669 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-gcs/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ✅        |
| QA checks                                                              | ✅        |
| Build connector tar                                                    | ✅        |
| Build destination-gcs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Integration tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/destination-v2-irl/1687969908/95ba6921757eeecfe68818b134ff83a625cb5ea0/destination-gcs/0.4.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-gcs test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`5d3ae4f111`](https://github.com/airbytehq/airbyte/pull/27268/commits/5d3ae4f1113476b517cacaca8c9f78723a4f8082)) - ❌

⏲️  Total pipeline duration: 1872 seconds

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ✅        |
| QA checks                                                                   | ✅        |
| Build connector tar                                                         | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Build airbyte/normalization:dev                                             | ✅        |
| Integration tests                                                           | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/destination-v2-irl/1687972385/5d3ae4f1113476b517cacaca8c9f78723a4f8082/destination-bigquery/1.4.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-gcs test report (commit [`5d3ae4f111`](https://github.com/airbytehq/airbyte/pull/27268/commits/5d3ae4f1113476b517cacaca8c9f78723a4f8082)) - ✅

⏲️  Total pipeline duration: 692 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-gcs/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ✅        |
| QA checks                                                              | ✅        |
| Build connector tar                                                    | ✅        |
| Build destination-gcs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Integration tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/destination-v2-irl/1687972385/5d3ae4f1113476b517cacaca8c9f78723a4f8082/destination-gcs/0.4.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-gcs test
```

**Comment by edgao** [comment]
can't repro the test failure locally. rerunning.

for posterity:
```
#13 736.4 BigQueryDestinationTest > testWriteSuccess(String) > io.airbyte.integrations.destination.bigquery.BigQueryDestinationTest.testWriteSuccess(String)[3] FAILED
#13 736.4     java.lang.RuntimeException: Failed to upload buffer to stage and commit to destination
#13 736.4         at io.airbyte.integrations.destination.bigquery.BigQueryStagingConsumerFactory.lambda$flushBufferFunction$5(BigQueryStagingConsumerFactory.java:281)
#13 736.4         at io.airbyte.integrations.destination.record_buffer.SerializedBufferingStrategy.flushAllBuffers(SerializedBufferingStrategy.java:138)
#13 736.4         at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:292)
#13 736.4         at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:82)
#13 736.4         at io.airbyte.integrations.destination.bigquery.BigQueryDestinationTest.testWriteSuccess(BigQueryDestinationTest.java:303)
#13 736.4 
#13 736.4         Caused by:
#13 736.4         java.lang.RuntimeException: [JobId{project=dataline-integration-testing, job=29226c1b-f977-4470-94a1-7cdc6b2e5d96, location=US}] Failed to upload staging files to destination table GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=bq_dest_integration_test_eqnllkon, tableId=_airbyte_raw_users}} (bq_dest_integration_test_eqnllkon)
#13 736.4             at io.airbyte.integrations.destination.bigquery.BigQueryGcsOperations.lambda$copyIntoTableFromStage$0(BigQueryGcsOperations.java:156)
#13 736.4             at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
#13 736.4             at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
#13 736.4             at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
#13 736.4             at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
#13 736.4             at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
#13 736.4             at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
#13 736.4             at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
#13 736.4             at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
#13 736.4             at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
#13 736.4             at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
#13 736.4             at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
#13 736.4             at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
#13 736.4             at io.airbyte.integrations.destination.bigquery.BigQueryGcsOperations.copyIntoTableFromStage(BigQueryGcsOperations.java:136)
#13 736.4             at io.airbyte.integrations.destination.bigquery.BigQueryStagingConsumerFactory.lambda$flushBufferFunction$5(BigQueryStagingConsumerFactory.java:276)
#13 736.4             ... 4 more
#13 736.4 
#13 736.4             Caused by:
#13 736.4             com.google.cloud.bigquery.BigQueryException: Error is happened during execution for job: Job{job=JobId{project=dataline-integration-testing, job=29226c1b-f977-4470-94a1-7cdc6b2e5d96, location=US}, status=JobStatus{state=RUNNING, error=null, executionErrors=null}, statistics=LoadStatistics{creationTime=1687973136561, endTime=null, startTime=1687973136725, numChildJobs=null, parentJobId=null, scriptStatistics=null, reservationUsage=null, transactionInfo=null, sessionInfo=null, inputBytes=null, inputFiles=null, outputBytes=null, outputRows=null, badRecords=null}, userEmail=test-bigquery-user@dataline-integration-testing.iam.gserviceaccount.com, etag=1Lm65tObrUIDqz+AWHPGfg==, generatedId=dataline-integration-testing:US.29226c1b-f977-4470-94a1-7cdc6b2e5d96, selfLink=https://www.googleapis.com/bigquery/v2/projects/dataline-integration-testing/jobs/29226c1b-f977-4470-94a1-7cdc6b2e5d96?location=US, configuration=LoadJobConfiguration{type=LOAD, destinationTable=GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=bq_dest_integration_test_eqnllkon, projectId=dataline-integration-testing, tableId=_airbyte_raw_users}}, decimalTargetTypes=null, destinationEncryptionConfiguration=null, createDisposition=null, writeDisposition=WRITE_APPEND, formatOptions=AvroOptions{type=AVRO, useAvroLogicalTypes=null}, nullMarker=null, maxBadRecords=null, schema=Schema{fields=[Field{name=_airbyte_ab_id, type=STRING, mode=null, description=null, policyTags=null, maxLength=null, scale=null, precision=null, defaultValueExpression=null, collation=null}, Field{name=_airbyte_emitted_at, type=TIMESTAMP, mode=null, description=null, policyTags=null, maxLength=null, scale=null, precision=null, defaultValueExpression=null, collation=null}, Field{name=_airbyte_data, type=STRING, mode=null, description=null, policyTags=null, maxLength=null, scale=null, precision=null, defaultValueExpression=null, collation=null}]}, ignoreUnknownValue=null, sourceUris=[gs://airbyte-integration-test-destination-gcs/test_path/bq_dest_integration_test_eqnllkon_users/2023/06/28/17/80405056-c473-42cf-adbf-77b526163f75/0.avro], schemaUpdateOptions=null, autodetect=null, timePartitioning=null, clustering=null, useAvroLogicalTypes=true, labels=null, jobTimeoutMs=null, rangePartitioning=null, hivePartitioningOptions=null, referenceFileSchemaUri=null, connectionProperties=null, createSession=null}}, 
#13 736.4              For more details see Big Query Error collection: BigQueryError{reason=invalid, location=gs://airbyte-integration-test-destination-gcs/test_path/bq_dest_integration_test_eqnllkon_users/2023/06/28/17/80405056-c473-42cf-adbf-77b526163f75/0.avro, message=Error while reading data, error message: Failed to expand table _airbyte_raw_users_bb3b02ea_6452_4aeb_bca3_4c3f98d2eb4c_source with file pattern gs://airbyte-integration-test-destination-gcs/test_path/bq_dest_integration_test_eqnllkon_users/2023/06/28/17/80405056-c473-42cf-adbf-77b526163f75/0.avro: matched no files. File: gs://airbyte-integration-test-destination-gcs/test_path/bq_dest_integration_test_eqnllkon_users/2023/06/28/17/80405056-c473-42cf-adbf-77b526163f75/0.avro}:
#13 736.4                 at app//io.airbyte.integrations.destination.bigquery.BigQueryUtils.waitForJobFinish(BigQueryUtils.java:443)
#13 736.4                 at app//io.airbyte.integrations.destination.bigquery.BigQueryGcsOperations.lambda$copyIntoTableFromStage$0(BigQueryGcsOperations.java:151)
#13 736.4                 ... 18 more
#13 736.4 
#13 736.4                 Caused by:
#13 736.4                 com.google.cloud.bigquery.BigQueryException: Error while reading data, error message: Failed to expand table _airbyte_raw_users_bb3b02ea_6452_4aeb_bca3_4c3f98d2eb4c_source with file pattern gs://airbyte-integration-test-destination-gcs/test_path/bq_dest_integration_test_eqnllkon_users/2023/06/28/17/80405056-c473-42cf-adbf-77b526163f75/0.avro: matched no files. File: gs://airbyte-integration-test-destination-gcs/test_path/bq_dest_integration_test_eqnllkon_users/2023/06/28/17/80405056-c473-42cf-adbf-77b526163f75/0.avro
#13 736.4                     at app//com.google.cloud.bigquery.Job.reload(Job.java:419)
#13 736.4                     at app//com.google.cloud.bigquery.Job.waitFor(Job.java:252)
#13 736.4                     at app//io.airbyte.integrations.destination.bigquery.BigQueryUtils.waitForJobFinish(BigQueryUtils.java:438)
#13 736.4                     ... 19 more
<snip...>

#13 1865.9 87 tests completed, 1 failed, 2 skipped
```

**Comment by octavia-squidington-iii** [comment]
##  destination-gcs test report (commit [`5d3ae4f111`](https://github.com/airbytehq/airbyte/pull/27268/commits/5d3ae4f1113476b517cacaca8c9f78723a4f8082)) - ✅

⏲️  Total pipeline duration: 730 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-gcs/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ✅        |
| QA checks                                                              | ✅        |
| Build connector tar                                                    | ✅        |
| Build destination-gcs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Integration tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/destination-v2-irl/1687981818/5d3ae4f1113476b517cacaca8c9f78723a4f8082/destination-gcs/0.4.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-gcs test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`5d3ae4f111`](https://github.com/airbytehq/airbyte/pull/27268/commits/5d3ae4f1113476b517cacaca8c9f78723a4f8082)) - ✅

⏲️  Total pipeline duration: 1902 seconds

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ✅        |
| QA checks                                                                   | ✅        |
| Build connector tar                                                         | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Build airbyte/normalization:dev                                             | ✅        |
| Integration tests                                                           | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/destination-v2-irl/1687981818/5d3ae4f1113476b517cacaca8c9f78723a4f8082/destination-bigquery/1.4.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`1b2756beb0`](https://github.com/airbytehq/airbyte/pull/27268/commits/1b2756beb0b66199d7103a4706b10bbbc6c5131b)) - ✅

⏲️  Total pipeline duration: 1939 seconds

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ✅        |
| QA checks                                                                   | ✅        |
| Build connector tar                                                         | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Build airbyte/normalization:dev                                             | ✅        |
| Integration tests                                                           | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/destination-v2-irl/1687988006/1b2756beb0b66199d7103a4706b10bbbc6c5131b/destination-bigquery/1.4.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-gcs test report (commit [`1b2756beb0`](https://github.com/airbytehq/airbyte/pull/27268/commits/1b2756beb0b66199d7103a4706b10bbbc6c5131b)) - ✅

⏲️  Total pipeline duration: 772 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-gcs/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ✅        |
| QA checks                                                              | ✅        |
| Build connector tar                                                    | ✅        |
| Build destination-gcs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Integration tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/destination-v2-irl/1687988006/1b2756beb0b66199d7103a4706b10bbbc6c5131b/destination-gcs/0.4.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-gcs test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`7288461b70`](https://github.com/airbytehq/airbyte/pull/27268/commits/7288461b70aa3bc597064c424377e10e38fd030c)) - ✅

⏲️  Total pipeline duration: 1820 seconds

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ✅        |
| QA checks                                                                   | ✅        |
| Build connector tar                                                         | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Build airbyte/normalization:dev                                             | ✅        |
| Integration tests                                                           | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/destination-v2-irl/1687990851/7288461b70aa3bc597064c424377e10e38fd030c/destination-bigquery/1.4.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-gcs test report (commit [`7288461b70`](https://github.com/airbytehq/airbyte/pull/27268/commits/7288461b70aa3bc597064c424377e10e38fd030c)) - ✅

⏲️  Total pipeline duration: 657 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-gcs/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ✅        |
| QA checks                                                              | ✅        |
| Build connector tar                                                    | ✅        |
| Build destination-gcs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Integration tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/destination-v2-irl/1687990851/7288461b70aa3bc597064c424377e10e38fd030c/destination-gcs/0.4.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-gcs test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-gcs test report (commit [`bef3f895a5`](https://github.com/airbytehq/airbyte/pull/27268/commits/bef3f895a5d11b52227462101b749b8283b671ea)) - ✅

⏲️  Total pipeline duration: 701 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-gcs/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ✅        |
| QA checks                                                              | ✅        |
| Build connector tar                                                    | ✅        |
| Build destination-gcs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Integration tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/destination-v2-irl/1687993682/bef3f895a5d11b52227462101b749b8283b671ea/destination-gcs/0.4.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-gcs test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`bef3f895a5`](https://github.com/airbytehq/airbyte/pull/27268/commits/bef3f895a5d11b52227462101b749b8283b671ea)) - ✅

⏲️  Total pipeline duration: 1771 seconds

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ✅        |
| QA checks                                                                   | ✅        |
| Build connector tar                                                         | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Build airbyte/normalization:dev                                             | ✅        |
| Integration tests                                                           | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/destination-v2-irl/1687993682/bef3f895a5d11b52227462101b749b8283b671ea/destination-bigquery/1.4.6/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Review by jbfbell — APPROVED** [review]

**Pull request merged**
