### PR TITLE
Revert a change made to enhance snowflake test stability as it broke …

### LINKED ISSUE #20018: Source Snowflake - connector Schema not used
## Environment
- **Airbyte version**:  0.40.18
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker
- **Source Connector and version**: Snowflake source 0.1.24
- **Step where error happened**:Setup new connection

## Current Behavior
schema is one of the credentials while configuring snowflake source.
but it discovers all the tables from all the schema's in the current database.

## Expected Behavior
only tables in provided schema should get discovered.

## Steps to Reproduce
1. configure Snowflake source for particular schema for a database with multiple schemas
2. during discover_schema , we get streams/tables from all the schemas in that database

### PR DESCRIPTION
**Pull request by rodireich**
## What
A previous change for snowflake broke postgres, mysql and mssql integration tests.
Undo change.

### CODE REVIEW

**Review by akashkulk — COMMENTED** [review]
Do the snowflake tests pass?

**Review by akashkulk — APPROVED** [review]
Approving on integration tests passing

**Comment by rodireich** [comment]
It should pass. The reverted change made it more resilient to garbage data left over on our test instance.
running all 4 to make sure

**Pull request merged**
