### PR TITLE
✨ Source Mailchimp: add new stream Unsubscribes

### LINKED ISSUE #17025: Source Mailchimp: new stream Unsubscribes
## Tell us about the problem you're trying to solve
[Unsubscribes](https://mailchimp.com/developer/marketing/api/unsub-reports/)
Get information about list members who unsubscribed from a specific campaign.

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

### PR DESCRIPTION
**Pull request by ChristoGrab**
## What
Added Unsubscribes stream
Docs: https://mailchimp.com/developer/marketing/api/unsub-reports/list-unsubscribed-members/

## How
- Each stream_slice consists of a separate campaign (similar to EmailActivity stream)
- The _links field contains "A list of link types and descriptions for the API schema documents." This data isn't pertinent to the user, so has been filtered out in request_params
- This API endpoint does not support sorting by timestamp in params, so records are filtered in parse_reponse
- Similar to EmailActivity, each slice uses its own state value with the campaign_id serving as a key to compare record timestamps against

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-mailchimp test report (commit [`c8df7f9a59`](https://github.com/airbytehq/airbyte/pull/31675/commits/c8df7f9a5931666f369c3a9848447c71c1a05f5f)) - ❌

⏲️  Total pipeline duration: 02mn08s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build source-mailchimp docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                      | ✅       |
| Acceptance tests                                                | ❌       |
| Check our base image is used                                    | ❌       |
| Code format checks                                              | ❌       |
| Validate metadata for source-mailchimp                          | ✅       |
| Connector version semver check                                  | ✅       |
| Connector version increment check                               | ✅       |
| QA checks                                                       | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/christo_mailchimp-unsubscribes-stream/1697831556/c8df7f9a5931666f369c3a9848447c71c1a05f5f/source-mailchimp/0.5.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:c8df7f9a5931666f369c3a9848447c71c1a05f5f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mailchimp test
```

**Review by lazebnyi — APPROVED** [review]
LGTM!

**Comment by airbyte-oss-build-runner** [comment]
##  source-mailchimp test report (commit [`1f1091e81c`](https://github.com/airbytehq/airbyte/pull/31675/commits/1f1091e81cfa44f2f450316e1d368f5af9d54d32)) - ✅

⏲️  Total pipeline duration: 01mn43s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build source-mailchimp docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                      | ✅       |
| Acceptance tests                                                | ✅       |
| Check our base image is used                                    | ✅       |
| Code format checks                                              | ✅       |
| Validate metadata for source-mailchimp                          | ✅       |
| Connector version semver check                                  | ✅       |
| Connector version increment check                               | ✅       |
| QA checks                                                       | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/christo_mailchimp-unsubscribes-stream/1698180910/1f1091e81cfa44f2f450316e1d368f5af9d54d32/source-mailchimp/0.5.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1f1091e81cfa44f2f450316e1d368f5af9d54d32)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mailchimp test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-mailchimp test report (commit [`b93c3961e3`](https://github.com/airbytehq/airbyte/pull/31675/commits/b93c3961e348ebdbbce706fb7a75dd496262d5b2)) - ✅

⏲️  Total pipeline duration: 01mn47s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build source-mailchimp docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                      | ✅       |
| Acceptance tests                                                | ✅       |
| Check our base image is used                                    | ✅       |
| Code format checks                                              | ✅       |
| Validate metadata for source-mailchimp                          | ✅       |
| Connector version semver check                                  | ✅       |
| Connector version increment check                               | ✅       |
| QA checks                                                       | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/christo_mailchimp-unsubscribes-stream/1698182583/b93c3961e348ebdbbce706fb7a75dd496262d5b2/source-mailchimp/0.5.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b93c3961e348ebdbbce706fb7a75dd496262d5b2)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mailchimp test
```

**Pull request merged**
