### PR TITLE
🐛 Fix URL pattern regex in Google PageSpeed Insights connector

### LINKED ISSUE #22285: Source Google PageSpeed Insights - PatternSyntaxException
## Environment
- **Airbyte version**:  0.40.26
- **OS Version / Instance**: Docker image
- **Deployment**: k8s on GKE via official Helm chart
- **Source Connector and version**: Google PageSpeed Insights 0.1.0
- **Destination Connector and version**: n/a
- **Step where error happened**: Setup new source or connection

## Current Behavior
1. Fill out form
2. Connection tests run and I see "All connection tests passed!"
3. The call to `/api/v1/sources/create` to create the source fails with a PatternSyntaxException

## Expected Behavior

No failures

## Logs

```
{
    "message": "Internal Server Error: java.util.regex.PatternSyntaxException: Unclosed character class near index 87\n^(?:origin:)?(http(s)?:\\/\\/)[\\w.-]+(?:\\.[\\w\\.-]+)+[\\w\\-\\._~:\\/?#[\\]@!\\$&'\\(\\)\\*\\+,;=.]+$\n                                                                                       ^",
    "exceptionClassName": "com.networknt.schema.JsonSchemaException",
    "exceptionStack": [
        "com.networknt.schema.JsonSchemaException: java.util.regex.PatternSyntaxException: Unclosed character class near index 87",
        "^(?:origin:)?(http(s)?:\\/\\/)[\\w.-]+(?:\\.[\\w\\.-]+)+[\\w\\-\\._~:\\/?#[\\]@!\\$&'\\(\\)\\*\\+,;=.]+$",
        "                                                                                       ^",
        "\tat com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:290)",
        "\tat com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:57)",
        "\tat com.networknt.schema.JsonSchema.read(JsonSchema.java:203)",
        "\tat com.networknt.schema.JsonSchema.getValidators(JsonSchema.java:479)",
        "\tat com.networknt.schema.JsonSchema.validate(JsonSchema.java:278)",
        "\tat com.networknt.schema.ItemsValidator.doValidate(ItemsValidator.java:99)",
        "\tat com.networknt.schema.ItemsValidator.validate(ItemsValidator.java:86)",
        "\tat com.networknt.schema.JsonSchema.validate(JsonSchema.java:279)",
        "\tat com.networknt.schema.PropertiesValidator.validate(PropertiesValidator.java:69)",
        "\tat com.networknt.schema.JsonSchema.validate(JsonSchema.java:279)",
        "\tat com.networknt.schema.JsonSchema.validate(JsonSchema.java:262)",
        "\tat io.airbyte.validation.json.JsonSchemaValidator.validateInternal(JsonSchemaValidator.java:123)",
        "\tat io.airbyte.validation.json.JsonSchemaValidator.ensure(JsonSchemaValidator.java:137)",
        "\tat io.airbyte.server.handlers.SourceHandler.validateSource(SourceHandler.java:275)",
        "\tat io.airbyte.server.handlers.SourceHandler.createSource(SourceHandler.java:88)",
        "\tat io.airbyte.server.apis.SourceApiController.lambda$createSource$3(SourceApiController.java:48)",
        "\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:18)",
        "\tat io.airbyte.server.apis.SourceApiController.createSource(SourceApiController.java:48)",
        "\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)",
        "\tat java.base/java.lang.reflect.Method.invoke(Method.java:578)",
        "\tat org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)",
        "\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)",
        "\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)",
        "\tat org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)",
        "\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)",
        "\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)",
        "\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)",
        "\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)",
        "\tat org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)",
        "\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)",
        "\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)",
        "\tat org.glassfish.jersey.internal.Errors.process(Errors.java:292)",
        "\tat org.glassfish.jersey.internal.Errors.process(Errors.java:274)",
        "\tat org.glassfish.jersey.internal.Errors.process(Errors.java:244)",
        "\tat org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)",
        "\tat org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)",
        "\tat org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)",
        "\tat org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)",
        "\tat org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)",
        "\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)",
        "\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)",
        "\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)",
        "\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)",
        "\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)",
        "\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)",
        "\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)",
        "\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)",
        "\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)",
        "\tat org.eclipse.jetty.server.Server.handle(Server.java:501)",
        "\tat org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)",
        "\tat org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)",
        "\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)",
        "\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)",
        "\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)",
        "\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)",
        "\tat org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)",
        "\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)",
        "\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)",
        "\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)",
        "\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)",
        "\tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)",
        "\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)",
        "\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)",
        "\tat java.base/java.lang.Thread.run(Thread.java:1589)",
        "Caused by: java.util.regex.PatternSyntaxException: Unclosed character class near index 87",
        "^(?:origin:)?(http(s)?:\\/\\/)[\\w.-]+(?:\\.[\\w\\.-]+)+[\\w\\-\\._~:\\/?#[\\]@!\\$&'\\(\\)\\*\\+,;=.]+$",
        "                                                                                       ^",
        "\tat java.base/java.util.regex.Pattern.error(Pattern.java:2045)",
        "\tat java.base/java.util.regex.Pattern.clazz(Pattern.java:2709)",
        "\tat java.base/java.util.regex.Pattern.sequence(Pattern.java:2156)",
        "\tat java.base/java.util.regex.Pattern.expr(Pattern.java:2086)",
        "\tat java.base/java.util.regex.Pattern.compile(Pattern.java:1798)",
        "\tat java.base/java.util.regex.Pattern.<init>(Pattern.java:1445)",
        "\tat java.base/java.util.regex.Pattern.compile(Pattern.java:1084)",
        "\tat com.networknt.schema.PatternValidator$PatternValidatorJava.<init>(PatternValidator.java:76)",
        "\tat com.networknt.schema.PatternValidator.<init>(PatternValidator.java:45)",
        "\tat java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)",
        "\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)",
        "\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)",
        "\tat com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:158)",
        "\tat com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:283)",
        "\t... 67 more"
    ],
    "rootCauseExceptionClassName": "java.lang.Class",
    "rootCauseExceptionStack": [
        "java.util.regex.PatternSyntaxException: Unclosed character class near index 87",
        "^(?:origin:)?(http(s)?:\\/\\/)[\\w.-]+(?:\\.[\\w\\.-]+)+[\\w\\-\\._~:\\/?#[\\]@!\\$&'\\(\\)\\*\\+,;=.]+$",
        "                                                                                       ^",
        "\tat java.base/java.util.regex.Pattern.error(Pattern.java:2045)",
        "\tat java.base/java.util.regex.Pattern.clazz(Pattern.java:2709)",
        "\tat java.base/java.util.regex.Pattern.sequence(Pattern.java:2156)",
        "\tat java.base/java.util.regex.Pattern.expr(Pattern.java:2086)",
        "\tat java.base/java.util.regex.Pattern.compile(Pattern.java:1798)",
        "\tat java.base/java.util.regex.Pattern.<init>(Pattern.java:1445)",
        "\tat java.base/java.util.regex.Pattern.compile(Pattern.java:1084)",
        "\tat com.networknt.schema.PatternValidator$PatternValidatorJava.<init>(PatternValidator.java:76)",
        "\tat com.networknt.schema.PatternValidator.<init>(PatternValidator.java:45)",
        "\tat java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)",
        "\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)",
        "\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)",
        "\tat com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:158)",
        "\tat com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:283)",
        "\tat com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:57)",
        "\tat com.networknt.schema.JsonSchema.read(JsonSchema.java:203)",
        "\tat com.networknt.schema.JsonSchema.getValidators(JsonSchema.java:479)",
        "\tat com.networknt.schema.JsonSchema.validate(JsonSchema.java:278)",
        "\tat com.networknt.schema.ItemsValidator.doValidate(ItemsValidator.java:99)",
        "\tat com.networknt.schema.ItemsValidator.validate(ItemsValidator.java:86)",
        "\tat com.networknt.schema.JsonSchema.validate(JsonSchema.java:279)",
        "\tat com.networknt.schema.PropertiesValidator.validate(PropertiesValidator.java:69)",
        "\tat com.networknt.schema.JsonSchema.validate(JsonSchema.java:279)",
        "\tat com.networknt.schema.JsonSchema.validate(JsonSchema.java:262)",
        "\tat io.airbyte.validation.json.JsonSchemaValidator.validateInternal(JsonSchemaValidator.java:123)",
        "\tat io.airbyte.validation.json.JsonSchemaValidator.ensure(JsonSchemaValidator.java:137)",
        "\tat io.airbyte.server.handlers.SourceHandler.validateSource(SourceHandler.java:275)",
        "\tat io.airbyte.server.handlers.SourceHandler.createSource(SourceHandler.java:88)",
        "\tat io.airbyte.server.apis.SourceApiController.lambda$createSource$3(SourceApiController.java:48)",
        "\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:18)",
        "\tat io.airbyte.server.apis.SourceApiController.createSource(SourceApiController.java:48)",
        "\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)",
        "\tat java.base/java.lang.reflect.Method.invoke(Method.java:578)",
        "\tat org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)",
        "\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)",
        "\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)",
        "\tat org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)",
        "\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)",
        "\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)",
        "\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)",
        "\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)",
        "\tat org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)",
        "\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)",
        "\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)",
        "\tat org.glassfish.jersey.internal.Errors.process(Errors.java:292)",
        "\tat org.glassfish.jersey.internal.Errors.process(Errors.java:274)",
        "\tat org.glassfish.jersey.internal.Errors.process(Errors.java:244)",
        "\tat org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)",
        "\tat org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)",
        "\tat org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)",
        "\tat org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)",
        "\tat org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)",
        "\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)",
        "\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)",
        "\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)",
        "\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)",
        "\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)",
        "\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)",
        "\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)",
        "\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)",
        "\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)",
        "\tat org.eclipse.jetty.server.Server.handle(Server.java:501)",
        "\tat org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)",
        "\tat org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)",
        "\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)",
        "\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)",
        "\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)",
        "\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)",
        "\tat org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)",
        "\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)",
        "\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)",
        "\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)",
        "\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)",
        "\tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)",
        "\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)",
        "\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)",
        "\tat java.base/java.lang.Thread.run(Thread.java:1589)"
    ]
}
```

## Steps to Reproduce
1. Fill out form to set up a Google PageSpeed Insights connection
2. Connection tests run and I see "All connection tests passed!"
3. The call to `/api/v1/sources/create` to create the source fails with a PatternSyntaxException

## Are you willing to submit a PR?
Yes

### PR DESCRIPTION
**Pull request by reidab**
## What
Without this `[` escaped, setting up a new source results in `java.util.regex.PatternSyntaxException: Unclosed character class`

Fixes #22285

## How

Escapes an opening `[` inside an open character class.

## Recommended reading order

Please read the single `\` character first. 😁 

## 🚨 User Impact 🚨

Fixes a breaking bug.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Comment by reidab** [comment]
To get this working locally, I also had to make a matching change in the source_specs.yaml here:

https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/seed/source_specs.yaml#L5872-L5877

…but since that file says it's auto-generated, I'm assuming that happens somewhere later in the build process?

**Comment by carlonuccio** [comment]
I have the same problem too and this is a breaking bug. Solved with your changes @reidab, thank you. Hope they can merge asap

**Review by carlonuccio — APPROVED** [review]

**Comment by tylerdigital** [comment]
@marcosmarxm I see you tagged this `pr-alpha-beta`, does this mean it will be in the next release? or is there an additional step?

I'm stuck on this error and am hoping that this PR fixes it :)

**Comment by lukebussey** [comment]
What's the process for using this version locally?

**Comment by marcosmarxm** [comment]
@sajarin can you fix the integration test and make this release?

**Review by sajarin — APPROVED** [review]

**Pull request merged**
