### PR TITLE
source-wasabi contribution from dainiussa

### LINKED ISSUE #46085: [connector-request] Wasabi
This is a **suggestion** to create a connector for **Wasabi** using the UI Connector Builder.
The website for the connector is https://wasabi.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

### PR DESCRIPTION
**Pull request by dainiussa**
## What

This PR adds a new connector for source Wasabi (source-wasabi).

Contributor-provided connector description:

Connector for https://www.wasabi.com API. API docs: https://docs.wasabi.com/docs/wasabi-stats-api
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `start_date` | `string` | Start date.  |  |
| `api_key` | `string` | API Key. The API key format is `AccessKey:SecretKey` |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| Standalone Utilizations |  | DefaultPaginator | ✅ |  ✅  |
| Standalone Bucket Utilizations |  | DefaultPaginator | ✅ |  ✅  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Is there a way to use one endpoint to get all buckets? Need to provide a bucket name will make this connector very limit @dainiussa

**Comment by dainiussa** [comment]
> Is there a way to use one endpoint to get all buckets? Need to provide a bucket name will make this connector very limit @dainiussa

You're right. Those endpoints which require bucket name or bucket number actually return the same data as the ones already implemented just for specific buckets. Therefore, those endpoints do not provide any additional value and are unnecessary. I removed them and left only the ones which gather all of the data.

**Comment by marcosmarxm** [comment]
Hello 👋 Due to the numerous contributions happening, I decided to create this [view](https://github.com/orgs/airbytehq/projects/104/views/3) to help you know when I plan to review your contribution. If your connector has some limited-time credential feel free to reach me out.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
The connector looks good @dainiussa but can I suggest to submit a new connector with name `wasabi-stats-api`? This way make clear this only collect stats and not file content from Wasabi service.

**Comment by dainiussa** [comment]
> The connector looks good @dainiussa but can I suggest to submit a new connector with name `wasabi-stats-api`? This way make clear this only collect stats and not file content from Wasabi service.

Hey @marcosmarxm, I submitted the same PR with `wasabi-stats-api` name here: https://github.com/airbytehq/airbyte/pull/47364

**Pull request closed without merging**
