### PR TITLE
Source Stripe: Add new Streams

### LINKED ISSUE #16981: Source Stripe: new stream Transfer Reversals
## Tell us about the problem you're trying to solve
[Transfer Reversals](https://stripe.com/docs/api/transfer_reversals)
[Stripe Connect](https://stripe.com/docs/connect) platforms can reverse transfers made to a connected account, either entirely or partially, and can also specify whether to refund any related application fees. Transfer reversals add to the platform's balance and subtract from the destination account's balance.

Reversing a transfer that was made for a [destination charge](https://stripe.com/docs/connect/destination-charges) is allowed only up to the amount of the charge. It is possible to reverse a [transfer_group](https://stripe.com/docs/connect/charges-transfers#transfer-options) transfer only if the destination account has enough balance to cover the reversal. 

[Permission](https://stripe.com/docs/security/permissions)

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

### LINKED ISSUE #16982: Source Stripe: new stream Usage Records
## Tell us about the problem you're trying to solve
[Usage Records](https://stripe.com/docs/api/usage_records)
Usage records allow you to report customer usage and metrics to Stripe for metered billing of subscription prices. 

[Permission](https://stripe.com/docs/security/permissions) _usage_record_read, usage_record_write_ Grants access to [Usage Records](https://stripe.com/docs/api/usage_records)

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

### LINKED ISSUE #26480: Source Stripe: new stream SetupAttempts
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[SetupAttempts](https://stripe.com/docs/api/setup_attempts)
A SetupAttempt describes one attempted confirmation of a SetupIntent, whether that confirmation was successful or unsuccessful. You can use SetupAttempts to inspect details of a specific attempt at setting up a payment method using a SetupIntent.
[The SetupAttempt object](https://stripe.com/docs/api/setup_attempts/object)

## Describe the solution you’d like
Research pros and cons for implementing this stream

### LINKED ISSUE #26483: Source Stripe: new stream Transactions
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[Transactions](https://stripe.com/docs/api/issuing/transactions)
Any use of an [issued card](https://stripe.com/docs/issuing) that results in funds entering or leaving your Stripe account, such as a completed purchase or refund, is represented by an Issuing `Transaction` object.
[The Transaction object](https://stripe.com/docs/api/issuing/transactions/object)

## Describe the solution you’d like
Research pros and cons for implementing this stream

### PR DESCRIPTION
**Pull request by artem1205**
## What
Resolve
- https://github.com/airbytehq/oncall/issues/1996
- https://github.com/airbytehq/airbyte/issues/16981
- https://github.com/airbytehq/airbyte/issues/16982
- https://github.com/airbytehq/airbyte/issues/26480
- https://github.com/airbytehq/airbyte/issues/26483

## How

Add new Streams:

- Transactions
- Transfer Reversals
- Setup Attempts
- Usage Records

Fix schemas:

- invoice items

## Recommended reading order
1. `y.python`

## 🚨 User Impact 🚨

schemas changes => schema refresh will be needed; 
affect only customer from https://github.com/airbytehq/oncall/issues/1996

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by alafanechere** [comment]
@artem1205 I'm updating the branch so that you get fresh CI run. cf https://airbytehq-team.slack.com/archives/C02UF50V9HA/p1686758235881369

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`7e4e1e8c9d`](https://github.com/airbytehq/airbyte/pull/27362/commits/7e4e1e8c9dc45c5700061256ba10d74e4a6519b8)) - ❌

⏲️  Total pipeline duration: 36 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5269661320)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`6f25d75eb9`](https://github.com/airbytehq/airbyte/pull/27362/commits/6f25d75eb96ceba6228fb5d2d9e4de15bd4063d2)) - ❌

⏲️  Total pipeline duration: 66 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5272679452)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`8f62a4f349`](https://github.com/airbytehq/airbyte/pull/27362/commits/8f62a4f349a536bf68bfa83b8cedd9d2e310f598)) - ❌

⏲️  Total pipeline duration: 570 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5277147970)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`8f62a4f349`](https://github.com/airbytehq/airbyte/pull/27362/commits/8f62a4f349a536bf68bfa83b8cedd9d2e310f598)) - ❌

⏲️  Total pipeline duration: 484 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5277154624)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`03bd02e468`](https://github.com/airbytehq/airbyte/pull/27362/commits/03bd02e468e3a9f4719997e5b6dd0712be491ee4)) - ✅

⏲️  Total pipeline duration: 467 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5277478476)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Review by lazebnyi — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`1d6ec50d9c`](https://github.com/airbytehq/airbyte/pull/27362/commits/1d6ec50d9c151f868cd856a4b27320b3388fee98)) - ❌

⏲️  Total pipeline duration: 38 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5313328689)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`b6befb51f9`](https://github.com/airbytehq/airbyte/pull/27362/commits/b6befb51f979ceb511d8df4c3668b4873af7695a)) - ❌

⏲️  Total pipeline duration: 508 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5313608772)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`a2e4ea4363`](https://github.com/airbytehq/airbyte/pull/27362/commits/a2e4ea436362892c6d6fee10a14552adcf3483b2)) - ❌

⏲️  Total pipeline duration: 506 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5313616081)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Review by bnchrch — APPROVED** [review]

**Pull request merged**
