### PR TITLE
auto-request reviewers for builder contributions

### PR DESCRIPTION
**Pull request by erohmensing**
## What

* Close https://github.com/airbytehq/airbyte-internal-issues/issues/8600
* Auto-request either the marketplace team or the python team on builder contributions

## How

* For any PR that affects a manifest-only connector (does not distinguish between builder contributions and regular PRs), if the connector is certified, request a review from the python team. if it is community, request a review from the marketplace team. 

## Other
I've created a new connector's metadata file. If it works as expected it should request the marketplace team 🤞🏻 
- [ ] TODO: remove added metadata file

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by erohmensing** [comment]
* **#42881** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/42881?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @erohmensing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alafanechere — APPROVED** [review]
LGTM
Please bump the `connector-ops` package version 🙏

**Comment by erohmensing** [comment]
I'm testing some review requests to make sure this works as expected, if you get multiple requests or notice it opening/closing @airbytehq/dev-marketplace-contributions

**Review by bnchrch — APPROVED** [review]
Thanks Ella! Happy that this reuses our ci definition of manifest only!

Added via Giphy

**Pull request merged**
