### PR TITLE
p0-stripe-object-nodes-23-08-02 - revert stripe to 3.17.1

### PR DESCRIPTION
**Pull request by clnoll**

### CODE REVIEW

**Review by maxi297 — APPROVED** [review]
:shipit:

**Comment by octavia-approvington** [comment]
Send it! <br/> rocket socks

**Review by octavia-approvington — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`8bde78ef45`](https://github.com/airbytehq/airbyte/pull/29004/commits/8bde78ef457f0d2c29c315605f332cc7c569e37c)) - ✅

⏲️  Total pipeline duration: 09mn48s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/stripe-p0-revert-cloud/1691006552/8bde78ef457f0d2c29c315605f332cc7c569e37c/source-stripe/3.17.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`bbdce4664a`](https://github.com/airbytehq/airbyte/pull/29004/commits/bbdce4664a9b2283247d6d6e8bb50b6e80973776)) - ✅

⏲️  Total pipeline duration: 09mn31s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/stripe-p0-revert-cloud/1691009228/bbdce4664a9b2283247d6d6e8bb50b6e80973776/source-stripe/3.17.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Pull request merged**
