### PR TITLE
🐛 Source Salesforce: Fix getting `anyType` fields using BULK API

### LINKED ISSUE #6886: Source Salesforce: NewValue and OldValue columns are not getting pulled for OpportunityFieldHistory
## Enviroment
- **Airbyte version**:  0.30.2-alpha
- **OS Version / Instance**: GCP n1-standard-8
- **Deployment**: Docker compose
- **Source Connector and version**: Salesforce 0.1.2
- **Destination Connector and version**: BigQuery 0.4.1
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
"OldValue" and "NewValue" fields from `OpportunityFieldHistory` are not being pulled into BigQuery.
Checking BigQuery, none of the rows in `_airbyte_raw_OpportunityFieldHistory` have OldValue or NewValue in the `_airbyte_data` column.

In the connection settings page the Data types for these two columns are being considered as `array` which might be incorrect [Salesforce ref](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_opportunityfieldhistory.htm).

## Expected Behavior
Would expect to see those two columns fetched and stored as strings containing the values. These two columns are critical to our adoption of Airbyte.

## Logs

<details>
<summary>Potentially relevant parts of the LOG</summary> 

```
2021-10-08 08:02:45 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Syncing stream: OpportunityFieldHistory 
2021-10-08 08:02:45 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Created Job: 7504x000007iBROAA2 to sync OpportunityFieldHistory
2021-10-08 08:02:45 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Sleeping 2 seconds while waiting for Job: 7504x000007iBROAA2 to complete
2021-10-08 08:02:45 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):203 - Records read: 10000
2021-10-08 08:02:45 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):203 - Records read: 11000
2021-10-08 08:02:45 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):203 - Records read: 12000
2021-10-08 08:02:48 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Read 3020 records from OpportunityFieldHistory stream

...

2021-10-08 08:03:27 INFO () DefaultAirbyteStreamFactory(lambda$create$0):53 - 2021-10-08 08:03:27 INFO i.a.i.d.b.BigQueryRecordConsumer(copyTable):339 - {} - successfully copied tmp table: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=salesforce_airbyte, tableId=_airbyte_tmp_rot_OpportunityFieldHistory}} to final table: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=salesforce_airbyte, tableId=_airbyte_raw_OpportunityFieldHistory}}
2021-10-08 08:03:27 INFO () JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $: null found, object expected
2021-10-08 08:03:27 ERROR () DefaultAirbyteStreamFactory(lambda$create$1):63 - Validation failed: null

...

2021-10-08 08:03:30 INFO () LineGobbler(voidCall):65 -   Ignoring stream 'NewValue' from OpportunityFieldHistory/NewValue because properties list is empty
2021-10-08 08:03:30 INFO () LineGobbler(voidCall):65 -   Ignoring stream 'OldValue' from OpportunityFieldHistory/OldValue because properties list is empty

```

</details>

## Steps to Reproduce
1. Add a Salesforce Source
2. Set BigQuery Destination
3. Select `OpportunityFieldHistory` with Full refresh | Overwrite
4. Run the sync

## Are you willing to submit a PR?

Not technically capable

### PR DESCRIPTION
**Pull request by yevhenii-ldv**
## What
*resolves #6886.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by htrueman — APPROVED** [review]

**Review by sherifnada — COMMENTED** [review]
let's close the PR after testing the new version with the user reporting the issue

**Comment by yevhenii-ldv** [comment]
@sherifnada Could you provide information from the user if it appears, since I can't see the message for the ticket author in the github?
If everything goes well, I will update the specification for the specification and close the issue.

**Comment by sherifnada** [comment]
@yevhenii-ldv the fix worked great! you're good to move forward :)

**Pull request merged**
