### PR TITLE
Source Chargebee: fix transaction schema to be consistent with S3

### PR DESCRIPTION
**Pull request by roman-yermilov-gl**
## What
*Fixed transaction stream to be consistent with `S3` destination. Make `transaction` stream to use type transformer*

### CODE REVIEW

**Review by arsenlosenko — APPROVED** [review]

**Review by lazebnyi — COMMENTED** [review]
This changes based on which docs? And maybe better use Transform class?

**Comment by roman-yermilov-gl** [comment]
> This changes based on which docs? And maybe better use Transform class?

Indeed is better. I reverted types back and started using transformer

**Review by arsenlosenko — APPROVED** [review]

**Review by lazebnyi — APPROVED** [review]

**Review by bazarnov — APPROVED** [review]

**Pull request merged**
