### PR TITLE
bump log4j2 version

### PR DESCRIPTION
**Pull request by jrhizor**

### CODE REVIEW

**Comment by yu-iskw** [comment]
@jrhizor Thank you for quickly improving.

**Comment by feluelle** [comment]
Shouldn't we bump it again to [2.16.0](https://logging.apache.org/log4j/2.x/changes-report.html#a2.16.0)?

**Comment by derekbar90** [comment]
Agreed, is there a plan/timeline to re-patch?

**Comment by davinchia** [comment]
This has been done with https://github.com/airbytehq/airbyte/releases/tag/v0.33.12-alpha.

**Pull request merged**
