### PR TITLE
:bug: Source Google Ads: fix stream *Campaigns* primary keys for incremental load

### PR DESCRIPTION
**Pull request by hanslemm**
## What
The current version of the GAds API returns, for the *Campaigns* stream, the `segments.hour` field. This field is part of the composite key that uniquely identifies each row, but currently is not considered, leading to a wrong incremental process. 

## How
I've simply added the `segments.hour` field to the stream code that pre-selects the candidate columns to be used for the SCD strategy.

## Recommended reading order
1. `/airbyte-integrations/connectors/source-google-ads/source_google_ads/streams.py`

## 🚨 User Impact 🚨
No user impact. 

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Review by evantahler — CHANGES_REQUESTED** [review]
Thanks @hanslemm!

Can you link to the spot in the Google Ads docs/API which indicates the primary key should be a composite of these 3 properties? It's something we should probably add to the changelog (see note below)

I've just run the connector's acceptance test - let's see if there are any additional changes needed. 

Also, for PRs that change a connector:
* Bump the version in the Dockerfile to the new version (this would likely be a patch semver change, as it is a bugfix)
* Add an entry for the change in the connector's docs/changelog

**Comment by hanslemm** [comment]
Hi @evantahler, thanks for reviewing!

Regarding the GAds docs, there is no documentation (that I could find of) explicitly telling which combination of columns resembles a composite key for each of our streams.

But there is an easy way of checking if any of our incremental strategy composite keys are correct for any stream, we just have to check if the count of rows match between the "complete table data" and the "unique key table data", such as the following code template (written for a POSTGRES backend):

```
WITH count_all_records AS (
  SELECT COUNT(*) AS count_rows
  FROM <YOUR_SCHEMA>.<YOUR_TABLE>
),

count_key_records AS (
  SELECT COUNT(DISTINCT <KEY_1> || <KEY_2> || ... || <KEY_N>) AS count_rows
  FROM <YOUR_SCHEMA>.<YOUR_TABLE>
),

final AS (
  SELECT 
    count_all_records.count_rows = count_key_records.count_rows AS is_unique_key
  FROM count_all_records
  CROSS JOIN count_key_records
)

SELECT * FROM final
```

If I fill out this template for my backend, it would be:
```
WITH count_all_records AS (
  SELECT COUNT(*) AS count_rows
  FROM raw.google_ads__campaigns
),

count_key_records AS (
  SELECT COUNT(DISTINCT "campaign.id" || "segments.date"::TEXT || "segments.hour") AS count_rows
  FROM raw.google_ads__campaigns
),

final AS (
  SELECT 
    count_all_records.count_rows = count_key_records.count_rows AS is_unique_key
  FROM count_all_records
  CROSS JOIN count_key_records
)

SELECT * FROM final

-- Returns TRUE
```

If the `segments.hour` is removed from the composite key, the return of this code is `FALSE`.

**Comment by evantahler** [comment]
@hanslemm you've got some merge conflicts now.  You don't need to update `source_specs.yaml` `source_definitions.yaml` (the bot will handle that).  Can you please revert those changes?

**Pull request closed without merging**
