### PR TITLE
✨Source BrainTree: Migrate Python CDK to LOW-code CDK

### LINKED ISSUE #28987: braintree
Please use the [connector builder](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/?_gl=1*13hxonw*_gcl_au*MTI0NTMzNjM3OS4xNjkwODM4MzE0*_ga*MTg2NTc3OTc0Ni4xNjUxNTk0NTQw*_ga_HDBMVFQGBH*MTY5MTAwNDEzMy4yNzIuMC4xNjkxMDA0MTMzLjAuMC4w&_ga=2.197654767.1978878.1690818922-1865779746.1651594540) for this.

### PR DESCRIPTION
**Pull request by masyagin1998**
## What
* add low-code version of BrainTree connector (closes #28987)

## How
* BrainTree low-code version in Airbyte Connector Builder and then put it to new source

## Recommended reading order
* manifest.yaml
* source.py

## 🚨 User Impact 🚨
* no

## Pre-merge Actions
* review

### CODE REVIEW

**Comment by masyagin1998** [comment]
@marcosmarxm could you please tell me if it's okay to still use `braintree` library in low-code connector (because there is no other way to parse XML)?

**Comment by marcosmarxm** [comment]
> @marcosmarxm could you please tell me if it's okay to still use `braintree` library in low-code connector (because there is no other way to parse XML)?

It's OK but please make sure to add unit test to any custom component.

**Comment by marcosmarxm** [comment]
@masyagin1998 this is a WIP, can you move to draft instead?

**Comment by masyagin1998** [comment]
@marcosmarxm thank you for response!
I'll add unit-tests and publish final version in few days)

**Comment by masyagin1998** [comment]
@marcosmarxm @sajarin ready for review!

**Comment by masyagin1998** [comment]
Screenshot from 2023-08-12 11-57-16
Image error was introduced after Airbyte update

**Comment by masyagin1998** [comment]
Screenshot from 2023-08-12 11-57-26
Screenshot from 2023-08-12 11-57-31
I don't know how to add data to disputes stream, but I've created it, and all other streams work.

**Review by sh4sh — APPROVED** [review]

**Comment by sh4sh** [comment]
Thanks for your contribution!

**Comment by valentinfily** [comment]
FYI could be related to this, but my Braintree connection was dead in Airbyte Cloud since August 17th (I'm connector v0.2.0) with this error :

```
2023-08-21 00:42:04 replication-orchestrator > failures: [ {
  "failureOrigin" : "source",
  "failureType" : "system_error",
  "internalMessage" : "time data '' does not match format '%Y-%m-%dT%H:%M:%SZ'",
  "externalMessage" : "Something went wrong in the connector. See the logs for more details.",
  "metadata" : {
    "attemptNumber" : 1,
    "jobId" : 4148767,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
```

After I reset the start date in the UI, everything worked fine again.

**Comment by masyagin1998** [comment]
Hey @valentinfily !
Yes, sadly I had to change datetime format in connector's status to support Low-Code CDK.
Hope everything is fine after resertting the data.

**Comment by nataliekwong** [comment]
There is an issue (perhaps due to pagination) with being able to load more than 50 records. This is on the `transaction` stream.  https://github.com/airbytehq/airbyte/issues/32197

**Pull request merged**
