### PR TITLE
Fail sync when Debezium fails to shutdown properly

### PR DESCRIPTION
**Pull request by akashkulk**
If debezium has not shutdown correctly, it can indicate an error with the connector configuration or a partial sync success. In situations like these, the preference is to fail loud and clear.

Reasoning behind this : 
1. In some cases, a silent failure causes the sync to appear to succeed (with 0 records) when it has actually failed : https://airbytehq-team.slack.com/archives/C043JHEEYKG/p1696637590900289
2. In some cases, a silent failure creates a different exception unrelated to the actual failure reason : https://app.zenhub.com/workspaces/db--dw-source-connectors-6333360e0a41155061efbcbd/issues/gh/airbytehq/airbyte/31290 

Reference to discussion in DBZ community : https://debezium.zulipchat.com/#narrow/stream/302529-community-general/topic/.E2.9C.94.20Invalid.20Connector.20configuration.20not.20throwing.20an.20exception

### CODE REVIEW

**Review by rodireich — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-mysql test report (commit [`590d5e5d41`](https://github.com/airbytehq/airbyte/pull/31674/commits/590d5e5d412232bb508c38a2ebbf2bed96346420)) - ❌

⏲️  Total pipeline duration: 03mn30s 

| Step                               | Result   |
|:-----------------------------------|:---------|
| Build connector tar                | ❌       |
| Validate metadata for source-mysql | ✅       |
| Connector version semver check     | ✅       |
| QA checks                          | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698183415/590d5e5d412232bb508c38a2ebbf2bed96346420/source-mysql/3.1.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:590d5e5d412232bb508c38a2ebbf2bed96346420)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`590d5e5d41`](https://github.com/airbytehq/airbyte/pull/31674/commits/590d5e5d412232bb508c38a2ebbf2bed96346420)) - ❌

⏲️  Total pipeline duration: 01mn26s 

| Step                                  | Result   |
|:--------------------------------------|:---------|
| Build connector tar                   | ❌       |
| Validate metadata for source-postgres | ✅       |
| Connector version semver check        | ✅       |
| QA checks                             | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_dbz-silent-failure/1698183415/590d5e5d412232bb508c38a2ebbf2bed96346420/source-postgres/3.2.14/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:590d5e5d412232bb508c38a2ebbf2bed96346420)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Pull request merged**
