### PR TITLE
Sources Jira, Github: update CDK authenticator

### PR DESCRIPTION
**Pull request by ChristoGrab**
## What
Migrates the authenticators for sources Jira and Github from the deprecated `auth` package to the current `requests_native_auth` package. Batching these as the three connectors that did not complain after the update.

## User Impact
No impact

## Can this PR be safely reverted and rolled back?
- [✓ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by aldogonzalez8** [comment]
This looks good to me, how did you test authentication changes for these 3 sources?

**Comment by ChristoGrab** [comment]
> This looks good to me, how did you test authentication changes for these 3 sources?

@aldogonzalez8 Glad you asked! I was going to say that for a small change like this it felt like successfully running the `read` interface on each connector locally and having a green pipeline is enough. However, I'm realizing that for at least Amazon Ads there are streams we cannot populate in our sandbox account which include additional authentication steps that could cause issues that our pipeline won't catch.

I'll remove Amazon Ads from this PR for now, but I think Jira and Github should still be safe since they use the same logic consistently across all streams and we are able to fetch all the `expected_records` in our sandbox accounts.

**Review by bazarnov — APPROVED** [review]

**Review by aldogonzalez8 — APPROVED** [review]
APPROVED

**Comment by aldogonzalez8** [comment]
Not sure if this is important but it shows two failing jobs and "Squash and merge" button looks enabled

image

**Pull request merged**
