### PR TITLE
✨ Slack source: add support for optional private channels

### PR DESCRIPTION
**Pull request by irvingpop**
This PR adds support to optionally include Slack private channels for the new Slack low-code connector.  Here's how it appears:

image

### CODE REVIEW

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Can you bump the metadata connector version, run poetry and also add the entry in the changelog?

**Comment by irvingpop** [comment]
Done @marcosmarxm !  Thanks for taking a look

**Review by marcosmarxm — APPROVED** [review]
LGTM Thanks for this contribution @irvingpop

**Comment by irvingpop** [comment]
thanks for the approval @marcosmarxm !  What's the next step to getting this merged? I noticed some of the PR workflows still need approval.

**Pull request merged**
