### PR TITLE
Source-Mssql : Information schema included 

### LINKED ISSUE #14481: Source-mssql: export meta data from INFORMATION_SCHEMA
## Tell us about the problem you're trying to solve

I want to export meta data from mssql to snowflake to normalize the data using dbt jobs. 

## Describe the solution you’d like

 We have CDC jobs which exporting json row incrementally. We have job which calculate scd 2 and  need to infer the json row datatype from source meta 

## Describe the alternative you’ve considered or used

need to write a airflow job which export the meta every day to snowflake ( i do not want to do) and want to keep everything in airbyte

### PR DESCRIPTION
**Pull request by sivankumar86**
## What
  We want to sync information schema from mssql to snowflake to infer schema conversion in dbt job

## 🚨 User Impact 🚨
     I can stop jdbc job which is running outside airbyte to sync information schema 

it would resolve #14481

### CODE REVIEW

**Review by subodh1810 — CHANGES_REQUESTED** [review]
I dont think we should go ahead and sync information_schema as a general implementation. Its not a common practice that users want to sync information schema. I would advice you to create a custom connector (all you have to do is build the image with this change and add it in Airbyte console) and use it

**Comment by subodh1810** [comment]
@grishick what do you think of my [comment](https://github.com/airbytehq/airbyte/pull/15341#pullrequestreview-1063052391)

**Comment by sivankumar86** [comment]
@subodh1810 As I mentioned description, we want to know the datatype of source table columns so that , we can map at target system and we donot want to maintain separate repo with custom connector's

**Comment by subodh1810** [comment]
@sivankumar86 I understand but touching system tables/columns should be avoided in general. I would like to get @grishick 's opinion

**Pull request closed without merging**
