### PR TITLE
[source-linkedin-ads] `approximateUniqueImpressions` field has been deprecated and is replaced by the new API field `approximateMemberReach`

### PR DESCRIPTION
**Pull request by lkazberova**
## What
Issue: https://github.com/airbytehq/airbyte/issues/42846
LinkedIn Ads API has made breaking changes regarding the approximateUniqueImpressions field:
https://learn.microsoft.com/en-us/linkedin/marketing/integrations/recent-changes?view=li-lms-2024-06#reminders

As communicated in January 2024, approximateUniqueImpressions field has been deprecated and is replaced by the new API field approximateMemberReach. If you are still utilizing the old field, please note that we will be updating the approximateUniqueImpressions measurement methodology to align more closely with approximateMemberReach. When this transition takes place in July, you may notice a change in the approximateUniqueImpressions field and we recommend that you switch to approximateMemberReach as soon as possible.

It means that

https://github.com/airbytehq/airbyte/blob/b34d531bac085ce48967d7776bb49cad65ef39bf/airbyte-integrations/connectors/source-linkedin-ads/source_linkedin_ads/analytics_streams.py#L23C1-L26C36

should be updated with a new field approximateMemberReach 

## How
I have added the new field `approximateMemberReach` to the list of Reporting Metrics fields available for fetch

## User Impact
End users should be aware of LinkedIn Breaking changes
>  If you are still utilizing the old field, please note that we will be updating the approximateUniqueImpressions measurement methodology to align more closely with approximateMemberReach. 

## Can this PR be safely reverted and rolled back?
- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by marcosmarxm — COMMENTED** [review]
Thanks for contributing @lkazberova I'm going to run tests to check your changes. The contribution also requires an additional approval from the connector team as this is a breaking change.

Do you mind updating the connector version in the metadata, pyproject and add a doc entry in the changelog section?

**Comment by lkazberova** [comment]
hello @marcosmarxm
thank you for your feedback, I have added those changes!

**Comment by marcosmarxm** [comment]
Running CI tests let's wait for the results.

**Comment by lkazberova** [comment]
Interesting. I see that [Connectors CI tests](https://github.com/airbytehq/airbyte/actions/runs/10179734570) are passed
Screenshot
but here they are marked as failed 
Screenshot

**Comment by marcosmarxm** [comment]
Some unit tests are failing. @lkazberova I'll take a look and return to you!

**Comment by lkazberova** [comment]
> Some unit tests are failing. @lkazberova I'll take a look and return to you!

@marcosmarxm thank you! Please let me know if I can fix something 🙏

**Comment by lkazberova** [comment]
Sorry, I see a lot of new changes regarding this connector. I will refactor according to them and re-open the pr

**Comment by marcosmarxm** [comment]
Let me know when you have the new pull request.

**Comment by lkazberova** [comment]
@marcosmarxm Hello! Could you please take a look? 
I also run unit_tests locally and they are succeeded.

**Comment by lkazberova** [comment]
@marcosmarxm I see that there is only **Connector Regression Tests: ❌ failed** others are ok
could you please help with understanding of this 
```bash
  at /usr/local/lib/python3.10/site-packages/dulwich/client.py:2290 in _http_request
      2286│         except urllib3.exceptions.HTTPError as e:
      2287│             raise GitProtocolError(str(e)) from e
      2288│ 
      2289│         if resp.status == 404:
    → 2290│             raise NotGitRepository
      2291│         if resp.status == 401:
      2292│             raise HTTPUnauthorized(resp.headers.get("WWW-Authenticate"), url)
      2293│         if resp.status == 407:
```

`NotGitRepository` what does it mean?

**Comment by lkazberova** [comment]
@marcosmarxm hey, do you have any updates about my question? https://github.com/airbytehq/airbyte/pull/42847#issuecomment-2277963564

**Comment by lkazberova** [comment]
@marcosmarxm kindly ping 👀

**Pull request closed without merging**
