### PR TITLE
🐛 Source Posthog: update following state management changes in the CDK

### PR DESCRIPTION
**Pull request by maxi297**
## What
Breaking changes were done as part of https://github.com/airbytehq/airbyte/commit/a45a1e33413eacccb2b8a83450d1638c48fd2042. This PR fixes the breaking changes for posthog.

## How
Updating the interfaces that were affected by breaking changes.

## 🚨 User Impact 🚨
None as the code should have the exact same behavior

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-posthog test report (commit [`d4ae093e12`](https://github.com/airbytehq/airbyte/pull/27764/commits/d4ae093e12f905c8d12cf849cd3d62edd3763bf7)) - ❌

⏲️  Total pipeline duration: 57 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-posthog/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ❌        |
| Connector package install                                             | ✅        |
| Build source-posthog docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_posthog/1687977457/d4ae093e12f905c8d12cf849cd3d62edd3763bf7/source-posthog/0.1.12/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-posthog test
```

**Comment by octavia-squidington-iii** [comment]
##  source-posthog test report (commit [`9e79f40568`](https://github.com/airbytehq/airbyte/pull/27764/commits/9e79f4056818040892a6a5755fb4fb53372f806d)) - ❌

⏲️  Total pipeline duration: 319 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-posthog/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-posthog docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_posthog/1687979774/9e79f4056818040892a6a5755fb4fb53372f806d/source-posthog/0.1.12/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-posthog test
```

**Comment by octavia-squidington-iii** [comment]
##  source-posthog test report (commit [`ecb200c1da`](https://github.com/airbytehq/airbyte/pull/27764/commits/ecb200c1dad51a06bdaabb073158e760f7505f7c)) - ✅

⏲️  Total pipeline duration: 363 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-posthog/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-posthog docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_posthog/1687981358/ecb200c1dad51a06bdaabb073158e760f7505f7c/source-posthog/0.1.12/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-posthog test
```

**Review by artem1205 — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-posthog test report (commit [`0ee8ace5c8`](https://github.com/airbytehq/airbyte/pull/27764/commits/0ee8ace5c8bee90cd698fbc96572d19526224491)) - ❌

⏲️  Total pipeline duration: 263 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-posthog/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-posthog docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_posthog/1687991052/0ee8ace5c8bee90cd698fbc96572d19526224491/source-posthog/0.1.12/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-posthog test
```

**Comment by octavia-squidington-iii** [comment]
##  source-posthog test report (commit [`f2e4381af4`](https://github.com/airbytehq/airbyte/pull/27764/commits/f2e4381af456824f8abbea2e9f108d7e28d06233)) - ❌

⏲️  Total pipeline duration: 644 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-posthog/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-posthog docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_posthog/1688042737/f2e4381af456824f8abbea2e9f108d7e28d06233/source-posthog/0.1.12/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-posthog test
```

**Comment by octavia-squidington-iii** [comment]
##  source-posthog test report (commit [`37254cdae8`](https://github.com/airbytehq/airbyte/pull/27764/commits/37254cdae88c82d12fd971a9f562956a9ae1ef1a)) - ✅

⏲️  Total pipeline duration: 391 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-posthog/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-posthog docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_posthog/1688051488/37254cdae88c82d12fd971a9f562956a9ae1ef1a/source-posthog/0.1.12/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-posthog test
```

**Pull request merged**
