### PR TITLE
:bug: Source Bing Ads: remove primary key for the geographic performance reports

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/oncall/issues/3068
In [version 1.0.0](https://github.com/airbytehq/airbyte/pull/31277) there was an attempt to remove the primary key from the geographic performance reports.
It wasn't successful because I missed that the mixin the reports are inherited from declares it's own primary key :cry: 

## How
Override the primary key with `None`, add unit tests

## 🚨 User Impact 🚨
Same as in the previous update - users will get rid of primary keys, will have more data and will need to reset the data + refresh the schemas

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-bing-ads test report (commit [`2fd11d2594`](https://github.com/airbytehq/airbyte/pull/31432/commits/2fd11d2594a7d524edc3b6540cfac0f8f3b36f95)) - ❌

⏲️  Total pipeline duration: 22mn49s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build source-bing-ads docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                      | ✅       |
| Acceptance tests                                                | ❌       |
| Code format checks                                              | ✅       |
| Validate metadata for source-bing-ads                           | ✅       |
| Connector version semver check                                  | ✅       |
| Connector version increment check                               | ❌       |
| QA checks                                                       | ❌       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_3068-remove-pk-completely/1697442728/2fd11d2594a7d524edc3b6540cfac0f8f3b36f95/source-bing-ads/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:2fd11d2594a7d524edc3b6540cfac0f8f3b36f95)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-bing-ads test
```

**Review by lazebnyi — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-bing-ads test report (commit [`be3905619e`](https://github.com/airbytehq/airbyte/pull/31432/commits/be3905619ea3b8aac12e4b5df041c39620e99296)) - ❌

⏲️  Total pipeline duration: 22mn33s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build source-bing-ads docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                      | ✅       |
| Acceptance tests                                                | ✅       |
| Code format checks                                              | ✅       |
| Validate metadata for source-bing-ads                           | ✅       |
| Connector version semver check                                  | ✅       |
| Connector version increment check                               | ✅       |
| QA checks                                                       | ❌       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_3068-remove-pk-completely/1697446261/be3905619ea3b8aac12e4b5df041c39620e99296/source-bing-ads/2.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:be3905619ea3b8aac12e4b5df041c39620e99296)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-bing-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-bing-ads test report (commit [`88aa84fdcf`](https://github.com/airbytehq/airbyte/pull/31432/commits/88aa84fdcffa12d2087fd806d6b2a07a3410116d)) - ✅

⏲️  Total pipeline duration: 11mn54s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build source-bing-ads docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                      | ✅       |
| Acceptance tests                                                | ✅       |
| Code format checks                                              | ✅       |
| Validate metadata for source-bing-ads                           | ✅       |
| Connector version semver check                                  | ✅       |
| Connector version increment check                               | ✅       |
| QA checks                                                       | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_3068-remove-pk-completely/1697448677/88aa84fdcffa12d2087fd806d6b2a07a3410116d/source-bing-ads/2.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:88aa84fdcffa12d2087fd806d6b2a07a3410116d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-bing-ads test
```

**Review by bazarnov — APPROVED** [review]

**Comment by brianjlai** [comment]
@davydov-d 
The code changes look good to me. But one thing that strikes me as a little bit of a concern is that we're rapidly incrementing the major version from `0.2.3` -> `1.0.0` -> `2.0.0`. Given the context I have from the past 2 PRs, this latest one feels more like a bug fix that came from `1.0.0`. Is there a reason why you opted for this breaking change designation? Is it so that its more clear that users will need to refresh their schemas?

My concern here is that the customer in question saw a degraded behavior on their sync using `1.0.0`. And I'm not sure we have a good use case where we want to retain this major version if its basically not functional. And if that were the case, a normal patch fix to `1.0.1` should hopefully ensure users don't use the version with the defect?

Before we approve and ship this, we should make sure we're all aligned with the version bump

**Review by brianjlai — CHANGES_REQUESTED** [review]
@davydov-d
The code changes look good to me. But one thing that strikes me as a little bit of a concern is that we're rapidly incrementing the major version from 0.2.3 -> 1.0.0 -> 2.0.0. Given the context I have from the past 2 PRs, this latest one feels more like a bug fix that came from 1.0.0. Is there a reason why you opted for this breaking change designation? Is it so that its more clear that users will need to refresh their schemas?

My concern here is that the customer in question saw a degraded behavior on their sync using 1.0.0. And I'm not sure we have a good use case where we want to retain this major version if its basically not functional. And if that were the case, a normal patch fix to 1.0.1 should hopefully ensure users don't use the version with the defect?

I temporarily marked this a Request changes just to make sure we're all aligned with the version bump before we ship this. I could be missing context on why the major bump is necessary and would like to know more

**Comment by davydov-d** [comment]
> @davydov-d The code changes look good to me. But one thing that strikes me as a little bit of a concern is that we're rapidly incrementing the major version from 0.2.3 -> 1.0.0 -> 2.0.0. Given the context I have from the past 2 PRs, this latest one feels more like a bug fix that came from 1.0.0. Is there a reason why you opted for this breaking change designation? Is it so that its more clear that users will need to refresh their schemas?
> 
> My concern here is that the customer in question saw a degraded behavior on their sync using 1.0.0. And I'm not sure we have a good use case where we want to retain this major version if its basically not functional. And if that were the case, a normal patch fix to 1.0.1 should hopefully ensure users don't use the version with the defect?
> 
> I temporarily marked this a Request changes just to make sure we're all aligned with the version bump before we ship this. I could be missing context on why the major bump is necessary and would like to know more

@brianjlai yes, this is a bug fix for v1.0.0. And yes, I decided it should be a breaking change for users to refresh their schemas and reset the data.
On the other hand, I can not dispute that this change is non-funcitonal, thus changed the major version bump to a patch.

**Review by brianjlai — APPROVED** [review]
@davydov-d thanks for clarifying. I can see the reasoning behind going either way. But I think we're aligned on using the patch. Though it might be clearer in the short run with the breaking change, for customers that write in, we can tell them to reset. And in the long run its probably better for us not to have a major version that contains the regression in it. Especially for OSS users who can dictate the version being used.

**Pull request merged**
