### PR TITLE
Destination Definitions: move normalization fields to normalizationConfig

### LINKED ISSUE #20559: `Removal of NormalizationRunnerFactory` introduced a bug - "this.normalizationIntegrationType" is null
Releasing https://github.com/airbytehq/airbyte/pull/20245 to Airbyte Cloud caused a number of syncs to fail. The relevant stack trace is:

```
2022-12-16 00:42:30 normalization-orchestrator > Normalization failed for job 967706.
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "this.normalizationIntegrationType" is null
	at io.airbyte.workers.normalization.DefaultNormalizationRunner.normalize(DefaultNormalizationRunner.java:107) ~[io.airbyte-airbyte-commons-worker-dev-6b86f5024c.jar:?]
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:77) ~[io.airbyte-airbyte-commons-worker-dev-6b86f5024c.jar:?]
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:34) ~[io.airbyte-airbyte-commons-worker-dev-6b86f5024c.jar:?]
	at io.airbyte.container_orchestrator.orchestrator.NormalizationJobOrchestrator.runJob(NormalizationJobOrchestrator.java:82) ~[io.airbyte-airbyte-container-orchestrator-dev-6b86f5024c.jar:?]
	at io.airbyte.container_orchestrator.Application.run(Application.java:79) ~[io.airbyte-airbyte-container-orchestrator-dev-6b86f5024c.jar:?]
	at io.airbyte.container_orchestrator.Application.main(Application.java:38) ~[io.airbyte-airbyte-container-orchestrator-dev-6b86f5024c.jar:?]
Log4j2Appender says: Normalization executed in 0 seconds for job 967706.
2022-12-16 00:42:30 normalization-orchestrator > Normalization executed in 0 seconds for job 967706.
Log4j2Appender says: Killing orchestrator because of an Exception
2022-12-16 00:42:30 ERROR i.a.c.Application(run):81 - Killing orchestrator because of an Exception
io.airbyte.workers.exception.WorkerException: Normalization Failed.
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:103) ~[io.airbyte-airbyte-commons-worker-dev-6b86f5024c.jar:?]
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:34) ~[io.airbyte-airbyte-commons-worker-dev-6b86f5024c.jar:?]
	at io.airbyte.container_orchestrator.orchestrator.NormalizationJobOrchestrator.runJob(NormalizationJobOrchestrator.java:82) ~[io.airbyte-airbyte-container-orchestrator-dev-6b86f5024c.jar:?]
	at io.airbyte.container_orchestrator.Application.run(Application.java:79) ~[io.airbyte-airbyte-container-orchestrator-dev-6b86f5024c.jar:?]
	at io.airbyte.container_orchestrator.Application.main(Application.java:38) ~[io.airbyte-airbyte-container-orchestrator-dev-6b86f5024c.jar:?]
```

The working theory is that the migration didn't alter existing configs, so we end up hitting null strings when trying to lookup old configs.  
```
public enum DestinationType {
    BIGQUERY,
    MSSQL,
    MYSQL,
    ORACLE,
    POSTGRES,
    REDSHIFT,
    SNOWFLAKE,
    CLICKHOUSE,
    TIDB
  }
```
This ^ was removed, and it looks like we should use those values to fill in any nulls in the config db.  The fix likely looks like another migration to populate the missing values.  

As https://github.com/airbytehq/airbyte/pull/20245 has already been deployed to Airbyte Cloud, we don't want to roll back that code unless absolutely necessary.

Deploying to Airbyte Cloud is frozen until this issue is resolved.

### Tasks:
1. Reproduce the bug to confirm the hypothesis that a sync which was started before the migration would produce the error above after the migration is applied, as the sync transitions from the replication phase to the normalization phase.  The best reproduction of this is a test.
2. Fix the bug! 
3. Work with @airbytehq/platform-cloud to re-enable Cloud deploys and deploy Airbyte Cloud

### PR DESCRIPTION
**Pull request by pedroslopez**
## What

Fixes https://github.com/airbytehq/airbyte/issues/20559

https://github.com/airbytehq/airbyte/pull/20245 introduced a change to the StandardDestinationDefintion definition that moved the normalization fields into a `normalizationConfig` object within the definition. Some code was added to the ActorDefinitionsMigrator to handle this, but Cloud does not go through the ActorDefinitionsMigrator. This means that Cloud would not properly load the values of these normalization fields into the database, leading to null pointer exceptions.

## How

- Update the destination definitions to the new format
- Remove the code that handles this from the migrator

### CODE REVIEW

**Review by andriikorotkov — COMMENTED** [review]
Can we test this changes on cloud?

**Comment by pedroslopez** [comment]
> Can we test this changes on cloud?

On it!

**Review by andriikorotkov — APPROVED** [review]

**Review by evantahler — APPROVED** [review]
Nice. 
Note: don't forget to make the same changes to yamls in the cloud repo

**Comment by pedroslopez** [comment]
> Note: don't forget to make the same changes to yamls in the cloud repo

This will happen automatically once this is merged - it'll trigger a regereration of the applied masks

**Review by git-phu — APPROVED** [review]
thanks!

**Pull request merged**
