### PR TITLE
source-simfin contribution from ombhardwajj

### LINKED ISSUE #47395: [connector-request] SimFin
This is a suggestion to create a connector for Simfin using the UI Connector Builder.
The website for the connector is https://simfin.com/

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to step 3).
3. Describe steps to get credentials.
4. Create the connector using the UI Builder.   

> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> This is a suggestion, and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend following the steps above.

### PR DESCRIPTION
**Pull request by ombhardwajj**
This closes #47395
## What

This PR adds a new connector for source SimFin (source-simfin).

Contributor-provided connector description:

Simfin provides financial data .
With this connector we can extract data from price data , financial statements and company info streams .
Docs https://simfin.readme.io/reference/getting-started-1
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| Company Info  | id | No pagination | ✅ |  ❌  |
| Financial Statements |  | No pagination | ✅ |  ❌  |
| Price Data |  | No pagination | ✅ |  ❌  |
| companies |  | No pagination | ✅ |  ❌  |
| common_shares_outstanding |  | No pagination | ✅ |  ❌  |
| weighted_shares_outstanding |  | No pagination | ✅ |  ❌  |
| filings_by_company | filingIdentifier | No pagination | ✅ |  ❌  |
| filings_list | filingIdentifier | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Missing couples endpoints as this is a very simple API. Without missing endpoints and implementing a better way to retrieve data from symbols.

**Comment by marcosmarxm** [comment]
Moving review to nov 13

**Comment by marcosmarxm** [comment]
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

Make sure you have pagination properly working, the API doesn't have pagination please left a comment making my review easier.
Make sure have a square svg icon
Make sure credentials are valid.

**Comment by ombhardwajj** [comment]
I've added companies, commonshares outstanding , weighted shares outstanding , filings by company and filings list streams.
I dont think Utils streams serve any practical value since the companies are already listed by their latest/current name.
Also for company info and financial statements only verbose endpoint has been implemented since it contains all the data (compact endpoint has a subset of the data returned by verbose endpoint)

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
