### PR TITLE
🐛 Source SalesForce: Fix date filter behaviour

### PR DESCRIPTION
**Pull request by artem1205**
## What

Resolve https://github.com/airbytehq/oncall/issues/3838

## How

change data comparison in WHERE clause:
before (returns duplicates):
```
{self.cursor_field} >= {start_date} AND {self.cursor_field} < {end_date}
```
after:
```
{self.cursor_field} > {start_date} AND {self.cursor_field} <= {end_date}
```

## Recommended reading order
1. `airbyte-integrations/connectors/source-salesforce/source_salesforce/streams.py`

## 🚨 User Impact 🚨

no breaking changes

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by maxi297** [comment]
Can we do this? Can we guarantee that if one record with a specific datetime is returned, all the records with this datetime will be returned? Given the granularity is "seconds", could we have records that were created at `2024-01-01T00:00:00:000000` and `2024-01-01T00:00:00:999999` and we sync only the first one and not the second during the sync?

**Comment by artem1205** [comment]
@maxi297,

> Can we do this?

I don't see any reason not to do it. 
> Can we guarantee that if one record with a specific datetime is returned, all the records with this datetime will be returned?

Absolutely. SOQL date-time filtering works similar to relational DB queries.

> Given the granularity is "seconds", could we have records that were created at 2024-01-01T00:00:00:000000 and 2024-01-01T00:00:00:999999 and we sync only the first one and not the second during the sync?

We have granularity in `microseconds` (3 digits) in our connector. We can confirm this from [SalesForce docs](https://help.salesforce.com/s/articleView?id=sf.c360_a_data_types_and_date_formats.htm&type=5) and our [expected records](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-salesforce/integration_tests/expected_records.jsonl).
Another option to solve this was to add this `granularity` == `0.001` to [initial date in method stream_slices ](https://github.com/airbytehq/airbyte/pull/34107/files#diff-0572edeedd561901f8110c0f88b48efde87d1ed91247c0eb189c7229da12090dR687).

> Why isn't it sufficient to ask the user to use dedup?

Already asked to.

**Comment by maxi297** [comment]
The problem with datetime is that those are not cursors that points to one record only, they point to buckets of records. The fear I have is that the bucket we are pointing to is not filled entirely when we do the query. The following sequence of event could occur:
* Record #1 is made available on 2024-01-01T00:00:00:000000
* We query the API at 2024-01-01T00:00:00:000500
* Record #2 is made available on 2024-01-01T00:00:00:000999

In that case, we would lose record #2 because we assume that because we have one record in the bucket `2024-01-01T00:00:00:000`, we therefore have all the records. Can you confirm that this situation is not possible and explain why? Repro steps would be also nice

**Review by tolik0 — APPROVED** [review]

**Comment by artem1205** [comment]
> Can you confirm that this situation is not possible and explain why? Repro steps would be also nice

This is not possible, and here is the reasons: 
1. We use the same `granurality` level in requests and records (`milliseconds`)
2. Salesforce uses SOQL query language, making it work very similarly to traditional relational databases. This means that a record with a timestamp _smaller_ than our request time cannot appear in the database.



Closing this PR for now as this behaviour is expected for our sources: 
https://docs.airbyte.com/using-airbyte/core-concepts/sync-modes/incremental-append#:~:text=When%20replicating%20data%20incrementally%2C%20Airbyte,cursor%20is%20not%20very%20granular.

**Comment by maxi297** [comment]
> We use the same granurality level in requests and records (milliseconds)

Yes but the real life world time is more granular than the Salesforce API which means that we can have multiple records that share the same cursor field but are inserted at different time. In [the example I shared earlier](https://github.com/airbytehq/airbyte/pull/34107#issuecomment-1892183362), both records would have a cursor value of `2024-01-01T00:00:00:000` but it does not mean they are inserted at the same time and hence it does not mean that if we query for `2024-01-01T00:00:00:000` the API will return both

**Pull request closed without merging**
