### PR TITLE
source delighted: change 'date since' title to 'replication start date'

### PR DESCRIPTION
**Pull request by ChristoGrab**
## What
- Changed "Date Since" title to "Replication Start Date".

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-delighted test report (commit [`a7f491c3d6`](https://github.com/airbytehq/airbyte/pull/27946/commits/a7f491c3d6ff1fbc2a854afc6065b602b00c78a5)) - ❌

⏲️  Total pipeline duration: 06mn48s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-delighted/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ❌        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-delighted docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/christograb-delighted-title-change/1688479662/a7f491c3d6ff1fbc2a854afc6065b602b00c78a5/source-delighted/0.2.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-delighted test
```

**Comment by octavia-squidington-iii** [comment]
##  source-delighted test report (commit [`cbc885e5bf`](https://github.com/airbytehq/airbyte/pull/27946/commits/cbc885e5bfc5f44ffa69d09bec83b857a19ee8af)) - ❌

⏲️  Total pipeline duration: 06mn08s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-delighted/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-delighted docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/christograb-delighted-title-change/1688590931/cbc885e5bfc5f44ffa69d09bec83b857a19ee8af/source-delighted/0.2.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-delighted test
```

**Comment by octavia-squidington-iii** [comment]
##  source-delighted test report (commit [`cbc885e5bf`](https://github.com/airbytehq/airbyte/pull/27946/commits/cbc885e5bfc5f44ffa69d09bec83b857a19ee8af)) - ❌

⏲️  Total pipeline duration: 05mn43s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-delighted/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-delighted docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/christograb-delighted-title-change/1688596752/cbc885e5bfc5f44ffa69d09bec83b857a19ee8af/source-delighted/0.2.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-delighted test
```

**Review by sherifnada — APPROVED** [review]
@ChristoGrab sweet, thanks for making the change!

once [this PR](https://github.com/airbytehq/airbyte/pull/27872/files) is merged, the failure you are encountering should resolve itself and you should merge this

**Pull request merged**
