### PR TITLE
Convert Async Destination Framework to Kotlin

### PR DESCRIPTION
**Pull request by jdpgrailsdev**
Converts the existing async destination framework from Java to Kotlin without any logic changes.  This also includes all existing unit tests.  This PR does NOT include any dependency injection changes -- those will be layered on in a follow on PR.  This change has been tested against the `destination-redshift` to make sure that the Kotlin version of the code can be used from Java (those changes are not included in this PR).

### CODE REVIEW

**Review by stephane-airbyte — APPROVED** [review]
automatic change, let's merge it. Can you also submit a PR for the changes required to the destination?

**Comment by jdpgrailsdev** [comment]
> automatic change, let's merge it. Can you also submit a PR for the changes required to the destination?

@stephane-airbyte Yes, though we should probably merge and publish this first, correct?  I can push up a placeholder PR that uses the cdk local stuff if we want to see it it first before we merge this PR.  Let me know how you want to proceed.

**Comment by stephane-airbyte** [comment]
@jdpgrailsdev you need to first make sure all the checks pass, update version.properties and the CDK changelog, then execute /publish-java-cdk from here, and then we can merge this. Or we can wait a bit for the better CDK workflow to move forward a bit. Up to you

**Comment by jdpgrailsdev** [comment]
@gisripa Could you please take a look at this PR to make sure that I properly converted the newly added data transformer code?  I converted the util from a static method to an instance to better prepare it for DI.

**Comment by gisripa** [comment]
@jdpgrailsdev  Yes that looks good.

**Comment by gisripa** [comment]
@jdpgrailsdev  One more modification coming unfortunately in cdk from me, hopefully it doesn't touch the already converted classes.

**Review by postamar — APPROVED** [review]

**Review by gisripa — APPROVED** [review]

**Pull request merged**
