### PR TITLE
Test lang.Process blocks on calls to STDOUT as expected

### PR DESCRIPTION
**Pull request by cgardens**
## What
* It does.

## How
* Created a source that sends infinite records at high speed.
* Created a destination that can be throttled to guarantee it consumes records more slowly than the source is producing them.
* Added a bunch of log lines so it was very clear when buffering was happening.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368107038068) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by cgardens** [comment]
@michel-tricot - I checked the "paused" part very carefully and feel very good about that. I was not looking at closely that all records landed. I can add a test for latter case.

**Comment by michel-tricot** [comment]
Terrific!

**Comment by cgardens** [comment]
I added an assertion to check that the record received by the destination is "one greater" than the previous one to guarantee that no records are lost.  Looks good to me!

**Comment by michel-tricot** [comment]
Great!

**Comment by cgardens** [comment]
this was added to the acceptance tests here: https://github.com/airbytehq/airbyte/pull/4151

**Pull request closed without merging**
