### PR TITLE
source-branch contribution from itsxdamdam

### PR DESCRIPTION
**Pull request by itsxdamdam**
## What

This PR adds a new connector for source Branch (source-branch).

Contributor-provided connector description:

Branch Connector
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `url` | `string` | url.  The deep link url against which the details are to be fetched. |  |
| `limit` | `integer` | limit. The maximum number of results to return. | 1 |
| `app_id` | `string` | app_id. The App Id |  |
| `fields` | `array` | fields. An array representing fields/columns available in your report |  |
| `job_id` | `string` | job_id. Unique identifier for job. Obtained from POST Export Cohort Analytics API. |  |
| `end_date` | `string` | end_date. The end of the interval time range represented as an ISO-8601 complete datetime including Hours, Minutes, Seconds, and Milliseconds. |  |
| `measures` | `array` | measures. The cohort measures to return. |  |
| `branch_key` | `string` | branch_key. branch key |  |
| `start_date` | `string` | start_date. The start of the interval time range represented as an ISO-8601 complete datetime including Hours, Minutes, Seconds, and Milliseconds. Datetime must be within the last 120 days. |  |
| `data_source` | `string` | data source. A string value representing the cohort type |  |
| `export_date` | `string` | export_date. export date |  |
| `report_type` | `string` | report_type. An array representing event type of your report. |  |
| `access_token` | `string` | access-token. Access Token  |  |
| `branch_secret` | `string` | branch_secret. branch secret |  |
| `request_handle` | `string` | request_handle. The ID returned by the log export queue. |  |
| `granularity_band_count` | `integer` | granularity band count. Number of time units since the cohort event to return to the user. | 7 |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| GET Export Request |  | No pagination | ✅ |  ❌  |
| Create Export Request |  | No pagination | ✅ |  ❌  |
| Read Existing Deep Link |  | No pagination | ✅ |  ❌  |
| Export Cohort Analytics |  | DefaultPaginator | ✅ |  ❌  |
| Get Export Download Status |  | No pagination | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Hello @itsxdamdam I don't believe this is a good connector to build using the Connector Builder. The API service doesn't expose important endpoints to get good information only export reports.

**Comment by itsxdamdam** [comment]
> Hello @itsxdamdam I don't believe this is a good connector to build using the Connector Builder. The API service doesn't expose important endpoints to get good information only export reports.

Oh I see, what do you suggest?

**Comment by marcosmarxm** [comment]
Unfortunately, I don't think using the Builder is the best approach to create this connector. For that reason, I'm going to decline the contribution. However, it is still eligible for prizes and rewards.

**Pull request closed without merging**
