### PR TITLE
Staging destinations: Simplify default namespace handling

### PR DESCRIPTION
**Pull request by edgao**
Instead of doing namespace==null checks everywhere, just set namespace=defaultNamespace at the earliest possible moment:
* Mutate the catalog at the connector entrypoint (i.e. getConsumer)
* Mutate messages when we deserialize them

At some point we should clean up all the existing null checks, but I think this is sufficient to unblock interesting 1s1t work.

(leaving redshift untouched for now, but most likely will do the same thing when we start doing redshift 1s1t. Leaving snowflake s3/gcs untouched because we want to deprecate them anyway)

### CODE REVIEW

**Review by tryangul — APPROVED** [review]
LGTM

**Comment by octavia-squidington-iii** [comment]
##  destination-snowflake test report (commit [`c88c0dee02`](https://github.com/airbytehq/airbyte/pull/29188/commits/c88c0dee02ff948d1da51058870ee247b5d94542)) - ✅

⏲️  Total pipeline duration: 43mn54s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-snowflake/metadata.yaml     | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Build connector tar                                                              | ✅        |
| Build destination-snowflake docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-snowflake:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-snowflake:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_default_namespace/1691442707/c88c0dee02ff948d1da51058870ee247b5d94542/destination-snowflake/1.2.10/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:c88c0dee02ff948d1da51058870ee247b5d94542)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-redshift test report (commit [`c88c0dee02`](https://github.com/airbytehq/airbyte/pull/29188/commits/c88c0dee02ff948d1da51058870ee247b5d94542)) - ❌

⏲️  Total pipeline duration: 22mn00s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-redshift/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-redshift docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-redshift:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-redshift:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_default_namespace/1691442707/c88c0dee02ff948d1da51058870ee247b5d94542/destination-redshift/0.6.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:c88c0dee02ff948d1da51058870ee247b5d94542)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redshift test
```

**Review by jbfbell — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  destination-redshift test report (commit [`8e934219f0`](https://github.com/airbytehq/airbyte/pull/29188/commits/8e934219f011f35f21828437c912e94d1e599408)) - ✅

⏲️  Total pipeline duration: 34mn07s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-redshift/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ✅        |
| Connector version increment check                                               | ✅        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-redshift docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-redshift:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-redshift:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_default_namespace/1691536661/8e934219f011f35f21828437c912e94d1e599408/destination-redshift/0.6.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8e934219f011f35f21828437c912e94d1e599408)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redshift test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-snowflake test report (commit [`8e934219f0`](https://github.com/airbytehq/airbyte/pull/29188/commits/8e934219f011f35f21828437c912e94d1e599408)) - ✅

⏲️  Total pipeline duration: 41mn40s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-snowflake/metadata.yaml     | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Build connector tar                                                              | ✅        |
| Build destination-snowflake docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization-snowflake:dev                                        | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-snowflake:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_default_namespace/1691536661/8e934219f011f35f21828437c912e94d1e599408/destination-snowflake/1.2.10/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8e934219f011f35f21828437c912e94d1e599408)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Pull request merged**
