### PR TITLE
CI/CD check for community PR #19493

### PR DESCRIPTION
**Pull request by natalyjazzviolin**
The purpose of this PR is to run a CI/CD check for PR https://github.com/airbytehq/airbyte/pull/19493 as currently non members cannot run all checks.

### CODE REVIEW

**Comment by marcelopio** [comment]
There is a test failing, but this is my output:

```
JAVA_HOME=/usr/lib/jvm/java-17-openjdk ./gradlew :airbyte-proxy:bashTest
Building all of Airbyte.
/home/marcelopio/repos/mrv/airbyte/airbyte-integrations/connectors
Type-safe dependency accessors is an incubating feature.

> Configure project :
configuring docker task for airbyte-bootloader
configuring docker task for airbyte-container-orchestrator
configuring docker task for airbyte-cron
configuring docker task for airbyte-proxy
configuring docker task for airbyte-server
configuring docker task for airbyte-temporal
configuring docker task for airbyte-webapp
configuring docker task for airbyte-workers
configuring docker task for init
configuring docker task for db-lib
configuring docker task for reporter

> Task :airbyte-proxy:bashTest
testing with proxy container airbyte/proxy:dev
Testing airbyte proxy...
Stopping airbyte-proxy-test-container
Error response from daemon: Cannot kill container: airbyte-proxy-test-container: No such container: airbyte-proxy-test-container
Error: No such container: airbyte-proxy-test-container
Starting airbyte-proxy-test-container
docker run -d -p 18000:8000 --env BASIC_AUTH_USERNAME=airbyte --env BASIC_AUTH_PASSWORD=password --env BASIC_AUTH_PROXY_TIMEOUT=120 --env PROXY_PASS_WEB=http://localhost --env PROXY_PASS_API=http://localhost --name airbyte-proxy-test-container airbyte/proxy:dev
a706057efdf97977e71562368dc7dde12dd469ca63d1da31da659a7dbae9d8fb
Testing access without auth
✔️  access without auth blocked
Testing access with auth
✔️  access with auth worked
Stopping airbyte-proxy-test-container
airbyte-proxy-test-container
airbyte-proxy-test-container
Starting airbyte-proxy-test-container with updated password
docker run -d -p 18000:8000 --env BASIC_AUTH_USERNAME=airbyte --env BASIC_AUTH_PASSWORD=pa55w0rd --env BASIC_AUTH_PROXY_TIMEOUT=120 --env PROXY_PASS_WEB=http://localhost --env PROXY_PASS_API=http://localhost --name airbyte-proxy-test-container airbyte/proxy:dev
29ff4fe7637e54a7af30bc4093b34ba2a3316c3570525c3f3514f9743242a60c
Testing access with orignial paassword
✔️  access with original auth blocked
Testing access updated auth
✔️  access with updated auth worked
Stopping airbyte-proxy-test-container
airbyte-proxy-test-container
airbyte-proxy-test-container
Starting airbyte-proxy-test-container with no password
docker run -d -p 18000:8000 --env BASIC_AUTH_USERNAME= --env BASIC_AUTH_PASSWORD= --env BASIC_AUTH_PROXY_TIMEOUT= --env PROXY_PASS_WEB=http://localhost --env PROXY_PASS_API=http://localhost --name airbyte-proxy-test-container airbyte/proxy:dev
ddcd07caaa1566a8978a472a9c19881b2b694f153e5fc9a7be7d76e767e42ccb
Testing access without auth
✔️  access without auth allowed when configured
Stopping airbyte-proxy-test-container
Error response from daemon: Cannot kill container: airbyte-proxy-test-container: Container ddcd07caaa1566a8978a472a9c19881b2b694f153e5fc9a7be7d76e767e42ccb is not running
airbyte-proxy-test-container
Tests Passed ✅

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 23s
14 actionable tasks: 1 executed, 13 up-to-date
```

**Comment by murat-cetinkaya** [comment]
@natalyjazzviolin any progress on this one?

**Comment by murat-cetinkaya** [comment]
Any update on this one?

**Comment by marcosmarxm** [comment]
@evantahler any idea WHY I need to add the commandLine chmod to make the `test.sh` executable. The `./gradlew airbyte-proxy:bashTest` was failing before.

**Comment by marcosmarxm** [comment]
Closed here, tested in https://github.com/airbytehq/airbyte/pull/20361

**Pull request closed without merging**
