### PR TITLE
Update fields in source-connectors specifications: freshservice

### LINKED ISSUE #8925: Update fields in source-connectors specifications: freshservice
Add title and description properties to each field in source-connectors specifications:
source-freshservice

[EPIC] Add title and description properties to each field in connectors specifications and order input fields appropriately #8324

### PR DESCRIPTION
**Pull request by ycherniaiev**

### CODE REVIEW

**Comment by ycherniaiev** [comment]
@sherifnada Unable to test. We need to reactivate paid plan

**Review by antixar — APPROVED** [review]
please publish this

**Review by bazarnov — APPROVED** [review]

**Comment by bazarnov** [comment]
/publish connector=connectors/source-freshservice run-tests=false

**Comment by bazarnov** [comment]
We are publishing this connector without tests for now. 
@sherifnada comment: 

https://github.com/airbytehq/airbyte/pull/9101
`
 for the reasons mentioned in the “implementation” section of the parent ticket it is safe to publish this connector without running tests, so it’s not required at the moment.
`

**Pull request merged**
