### PR TITLE
Clickable onboarding steps

### LINKED ISSUE #279: Onboarding steps should be clickable, once completed
During onboarding experience, user should be able to go back to previous steps, in the case they made a mistake. 
That means in the screenshot below, user should be able to click on step 1 and step 2. 
Screen Shot 2020-09-15 at 12 13 45 PM

However, user shouldn't be able to future steps if not already completed. 

@cgardens

### PR DESCRIPTION
**Pull request by jamakase**
## What
Made onboarding steps clickable, once completed. User can update source and destination data in onboarding

### CODE REVIEW

**Review by michel-tricot — COMMENTED** [review]
Why is the pattern to recreate?

Couldn't we keep the state in the browser and only create a the end?

**Comment by Jamakase** [comment]
> Why is the pattern to recreate?
> 
> Couldn't we keep the state in the browser and only create a the end?

@michel-tricot you can find more info here #279 

In a few words: we can't just keep the state in the browser, because we want to check connection when we create source or destination. Because of this appears a new problem - as a source implementation is immutable when we change connector - we have to create a new implementation and check it. If the connection fails - we do not want an old source to be lost, so we do not delete it at the beginning of the flow.

**Review by michel-tricot — APPROVED** [review]

**Comment by johnlafleur** [comment]
I tested this part. 
Unfortunately, I met a few issues. Here are the steps to reproduce:
* in step 1 with source, add a exchangerate API and move to setting up destination
* when in destination, click on Step 1 to change the source setup
* in step 1, I see "Save changes" and "cancel", instead of "Set up source". "Save changes" is disabled if I don't make any changes. So this is NOT intuitive at all for the user how they can go back to step 2, without actually changing the source. It should be back to "Set up source" button, as if the source wasn't set at the start IMO. 
* If I select another connector like Postgres, fill the fields and click on "Save changes", I see an error, I can't actually change the source. 

In any case, this is a LOW-priority issue. I suggest we make the onboarding steps back to unclickable, and change again once we have fixed the issues above. @cgardens

**Comment by Jamakase** [comment]
Looks like there is some strange CORS error. I will have a quick look at what can be broken.

**Pull request merged**
