### PR TITLE
Source Sentry: Add incremental for issues stream

### PR DESCRIPTION
**Pull request by lazebnyi**
## What
Users get an rate limit error if running few connections in parallel.  

https://github.com/airbytehq/oncall/issues/2448

## How
Add incremental support for issues stream to reduce requests. 

## 🚨 User Impact 🚨
No

## Pre-merge Actions
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-sentry test report (commit [`f5c862d7c8`](https://github.com/airbytehq/airbyte/pull/29023/commits/f5c862d7c80192edb64eb025bf9c1807cd8a14cd)) - ✅

⏲️  Total pipeline duration: 03mn34s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-sentry/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-sentry docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/lazebnyi_2448-source-sentry-add-incremental-sunc-for-issues-stream/1691021019/f5c862d7c80192edb64eb025bf9c1807cd8a14cd/source-sentry/0.2.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f5c862d7c80192edb64eb025bf9c1807cd8a14cd)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-sentry test
```

**Review by bazarnov — APPROVED** [review]

**Comment by clnoll** [comment]
Nice @lazebnyi! Can you create a pre-release version and test it on an internal workspace?

**Comment by clnoll** [comment]
Update: I started a pre-release build https://github.com/airbytehq/airbyte/actions/runs/5755626992.

**Comment by octavia-squidington-iii** [comment]
##  source-sentry test report (commit [`6aa611ff93`](https://github.com/airbytehq/airbyte/pull/29023/commits/6aa611ff931e35dfd11e10c5edf88d1479f9f871)) - ❌

⏲️  Total pipeline duration: 01mn03s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-sentry/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ❌        |
| Connector package install                                            | ✅        |
| Build source-sentry docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/lazebnyi_2448-source-sentry-add-incremental-sunc-for-issues-stream/1691524047/6aa611ff931e35dfd11e10c5edf88d1479f9f871/source-sentry/0.2.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6aa611ff931e35dfd11e10c5edf88d1479f9f871)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-sentry test
```

**Comment by octavia-squidington-iii** [comment]
##  source-sentry test report (commit [`ebc5b7df36`](https://github.com/airbytehq/airbyte/pull/29023/commits/ebc5b7df36435ae00c02237374b8c98da054c798)) - ❌

⏲️  Total pipeline duration: 02mn56s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-sentry/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-sentry docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/lazebnyi_2448-source-sentry-add-incremental-sunc-for-issues-stream/1691524529/ebc5b7df36435ae00c02237374b8c98da054c798/source-sentry/0.2.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ebc5b7df36435ae00c02237374b8c98da054c798)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-sentry test
```

**Comment by octavia-squidington-iii** [comment]
##  source-sentry test report (commit [`905f474ea2`](https://github.com/airbytehq/airbyte/pull/29023/commits/905f474ea2155bdddfd11a079e4cdab282f9d084)) - ✅

⏲️  Total pipeline duration: 03mn29s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-sentry/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-sentry docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/lazebnyi_2448-source-sentry-add-incremental-sunc-for-issues-stream/1691526484/905f474ea2155bdddfd11a079e4cdab282f9d084/source-sentry/0.2.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:905f474ea2155bdddfd11a079e4cdab282f9d084)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-sentry test
```

**Review by clnoll — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-sentry test report (commit [`6fca8363f5`](https://github.com/airbytehq/airbyte/pull/29023/commits/6fca8363f527f982ae384d179b48cbfaa14080b0)) - ✅

⏲️  Total pipeline duration: 03mn13s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-sentry/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-sentry docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/lazebnyi_2448-source-sentry-add-incremental-sunc-for-issues-stream/1691576936/6fca8363f527f982ae384d179b48cbfaa14080b0/source-sentry/0.2.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6fca8363f527f982ae384d179b48cbfaa14080b0)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-sentry test
```

**Pull request merged**
