### PR TITLE
.github: delete pull_request_template.md

### PR DESCRIPTION
**Pull request by postamar**
The pull request template needs to go:
- Our upcoming version bumping workflow requires us to carry the PR description forward as the squashed commit message, because the description is going to contain magical keywords.
- In any case, it's not friendly to https://graphite.dev/ .
- Too many PRs by Airbyters who don't bother filling in the template already.
- Its contents are stale and out-of-date
- As of now, OSS contributions require forking the repo, creating a forked PR and getting in touch with an Airbyter; if the PR description is lacking, we can just as well reference CONTRIBUTING.md instead or something like that.

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thank you!

**Review by marcosmarxm — APPROVED** [review]
LGTM! I'm going to work and update the Contributing.MD + docs

**Comment by postamar** [comment]
Thanks @marcosmarxm! That's a great idea. 

I'll wait a bit for everyone to have a chance to see this change before merging.

**Review by evantahler — APPROVED** [review]
The new spirt we have is also to move anything that would have been in the checklist into airybte-ci - so 👍

**Pull request merged**
