### PR TITLE
Bulk Load CDK: Process Records Unit Tests; Test cleanup

### PR DESCRIPTION
**Pull request by johnny-schmidt**
## What
* Unit tests for process records
* Some test cleanup, factoring out common mocks

### CODE REVIEW

**Comment by stephane-airbyte** [comment]
looks like there's some duplicated code from https://github.com/airbytehq/airbyte/pull/45841/files

**Comment by johnny-schmidt** [comment]
> looks like there's some duplicated code from https://github.com/airbytehq/airbyte/pull/45841/files

Sorry, it should be stacked.

**Comment by johnny-schmidt** [comment]
> > looks like there's some duplicated code from https://github.com/airbytehq/airbyte/pull/45841/files
> 
> Sorry, it should be stacked.

@stephane-airbyte it's fixed now

**Comment by johnny-schmidt** [comment]
rebased and reformatted

**Review by stephane-airbyte — APPROVED** [review]

**Pull request merged**
