### PR TITLE
Fail the connection state instead of throwing an exception

### PR DESCRIPTION
**Pull request by benmoriceau**
## What
Throwing an exception instead of returning a failed status will result in the workflow to be in a quarantined state. This will make sure that the job will fail instead of being in quarantined state.

### CODE REVIEW

**Review by evantahler — APPROVED** [review]
This is great, assuming that the `StandardCheckConnectionOutput`'s message will be used to fill in the FailureReason later on.  We want to keep this experience in the UI: 

Screen Shot 2022-06-13 at 10 34 45 AM

**Comment by benmoriceau** [comment]
THanks for the quick review @evantahler, I'm waiting for a review from someone in the platform team, then I'll merge and deploy.

**Review by lmossman — APPROVED** [review]
Sorry, meant to approve this earlier today. LGTM!

**Comment by benmoriceau** [comment]
> Sorry, meant to approve this earlier today. LGTM!

All good. I'll release when I land.

**Comment by lmossman** [comment]
> This is great, assuming that the `StandardCheckConnectionOutput`'s message will be used to fill in the FailureReason later on. We want to keep this experience in the UI

I believe this will be the behavior with this change, as [this logic](https://github.com/airbytehq/airbyte/blob/00bf49e6a56ca1f8c2f1dc73ae74e1488c8a05be/airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowImpl.java#L200) adds the error message you screenshotted when `isFailed()` is true on the `syncCheckConnectionFailure`, which just requires both the output and the failure origin to be set, which are set when the status is FAILED here: https://github.com/airbytehq/airbyte/blob/00bf49e6a56ca1f8c2f1dc73ae74e1488c8a05be/airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/ConnectionManagerWorkflowImpl.java#L349-L350

**Pull request merged**
