### PR TITLE
fix-postgres: fix strict encrypt spec

### PR DESCRIPTION
**Pull request by subodh1810**
See this slack thread https://airbytehq-team.slack.com/archives/C043JHEEYKG/p1680694218839859

### CODE REVIEW

**Comment by rodireich** [comment]
This looks good.
I wonder how `/test` passed prior to this fix

**Review by rodireich — APPROVED** [review]

**Comment by subodh1810** [comment]
> I wonder how /test passed prior to this fix
Cause the test was referring to the incorrect expected specs

**Review by nguyenaiden — APPROVED** [review]
Thanks for making the change. I wonder how integration tests were passing.

**Review by lmossman — APPROVED** [review]
LGTM

**Pull request merged**
