### PR TITLE
Source Stripe: Add properties to customer_shipping field in invoices stream

### PR DESCRIPTION
**Pull request by lazebnyi**
## What
Broken schema for invoices stream
Fixed: https://github.com/airbytehq/oncall/issues/2609

## How
Moved all the properties of customer shipping filed in invoices stream under a properties field. 

## 🚨 User Impact 🚨
No

## Pre-merge Actions
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by lazebnyi** [comment]
/publish connector=connectors/source-stripe pre-release=true run-tests=false

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`ea013c8741`](https://github.com/airbytehq/airbyte/pull/28887/commits/ea013c8741e3be9a1da379c37690b410f65de808)) - ❌

⏲️  Total pipeline duration: 09mn22s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ❌        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/lazebnyi_2609-source-stripe-broken-schema/1690841250/ea013c8741e3be9a1da379c37690b410f65de808/source-stripe/3.17.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by lazebnyi** [comment]
Manually tested with pre-release version [3.17.0-dev.ea013c8741](https://github.com/airbytehq/airbyte/actions/runs/5720249261/job/15499796373) in [workspace](https://cloud.airbyte.com/workspaces/bed3b473-1518-4461-a37f-730ea3d3a848/connections/bf8a6698-8c1d-4b1d-a023-7bd59d6a227f/job-history#3693528::0).

**Review by sherifnada — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`2fb7a12d4c`](https://github.com/airbytehq/airbyte/pull/28887/commits/2fb7a12d4c26b78aadd4a478db6adb1bc290165a)) - ✅

⏲️  Total pipeline duration: 12mn05s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/lazebnyi_2609-source-stripe-broken-schema/1690845033/2fb7a12d4c26b78aadd4a478db6adb1bc290165a/source-stripe/3.17.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Pull request merged**
