### PR TITLE
:sparkles: :sparkles: Source Stripe: add missing fields

### PR DESCRIPTION
**Pull request by davydov-d**
## What
#24672 

## How
Modify schemas of the following streams:
 - accounts
 - charges
 - disputes
 - credit notes
 - invoices
 - invoice items
 - invoice line items
 - payouts
 - plans
 - products
 - promotion codes
 - setup attempts
 - balance transactions
 - cardholders
 - customers
 - payment intents
 - setup intents
 - subscriptions
 - subscription items
 - subscription schedules
 
Remove `fail_on_extra_columns: false` from the CAT config

### CODE REVIEW

**Review by roman-yermilov-gl — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`4097dccdb0`](https://github.com/airbytehq/airbyte/pull/28776/commits/4097dccdb07973307c8b7f510221faeb19299144)) - ❌

⏲️  Total pipeline duration: 12mn07s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_24672-source-stripe-add-missing-fields/1690459068/4097dccdb07973307c8b7f510221faeb19299144/source-stripe/3.16.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`77b2ef909b`](https://github.com/airbytehq/airbyte/pull/28776/commits/77b2ef909b2f0d813c404733302b18842ecd77e9)) - ❌

⏲️  Total pipeline duration: 11mn22s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_24672-source-stripe-add-missing-fields/1690459925/77b2ef909b2f0d813c404733302b18842ecd77e9/source-stripe/3.16.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`786ebadc2c`](https://github.com/airbytehq/airbyte/pull/28776/commits/786ebadc2c4429876b52ba99c4f962f535636c9f)) - ❌

⏲️  Total pipeline duration: 10mn18s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_24672-source-stripe-add-missing-fields/1690461299/786ebadc2c4429876b52ba99c4f962f535636c9f/source-stripe/3.16.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`f8d1332794`](https://github.com/airbytehq/airbyte/pull/28776/commits/f8d1332794175cce881efec90293cdb3cf3593f1)) - ✅

⏲️  Total pipeline duration: 10mn08s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |
| Code format checks                                                   | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_24672-source-stripe-add-missing-fields/1690462577/f8d1332794175cce881efec90293cdb3cf3593f1/source-stripe/3.16.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Pull request merged**
