### PR TITLE
Add metadata to connector logs (log level, class name, method name and line number)

### PR DESCRIPTION
**Pull request by prateekmukhedkar**
## What
We are adding labels (INFO, WARN, ERROR), class name, method name and line numbers to the pattern for connector logs. 

With this change the logs generated by Postgres source appear like this

`2023-02-15 19:05:21 source > INFO i.a.i.s.p.PostgresSource(discoverRawTables):254 Found table: public.cities`
`2023-02-15 19:05:21 source > INFO i.a.i.s.p.PostgresUtils(isCdc):53 using CDC: false`
`2023-02-15 19:05:21 source > INFO i.a.i.s.j.AbstractJdbcSource(queryTableFullRefresh):148 Queueing query for table: cities`

Currently we see logs without any log labels (INFO) or class/method names

> 2022-10-06 21:24:25 [44msource[0m > Found table: public.table_table

Fix for https://github.com/airbytehq/airbyte/issues/17861 

## How
`AirbyteLogMessageTemplate.json` contains the template for generating json that confirms to AirbyteMessage protocol. This change replaces `message` in the json template file with a log4j `resolver pattern` so that we are able to finely control additional metadata appearing in a log, in addition to the actual message logged by code.

## Recommended reading order
1. `AirbyteLogMessageTemplate.json`
2. `AirbyteLogMessageTemplateTest.java`

## 🚨 User Impact 🚨
This change makes it easier for a developer to debug using logs because we have the name of the class that generated the log message as well as the method and line number. There should be no change in the functionality provided by source connector.

### CODE REVIEW

**Comment by prateekmukhedkar** [comment]
@grishick can you guide how can I look into the failing Destinations? ([link](https://github.com/airbytehq/airbyte/pull/23105#issuecomment-1431889239))

**Review by grishick — APPROVED** [review]

**Comment by grishick** [comment]
> @grishick can you guide how can I look into the failing Destinations? ([link](https://github.com/airbytehq/airbyte/pull/23105#issuecomment-1431889239))

you can ignore these. I files separate issues to address version mismatches

**Review by subodh1810 — APPROVED** [review]

**Pull request merged**
