### PR TITLE
🎉 JDBC sources: emit cursor counts

### LINKED ISSUE #14732: SQL Sources should include previous sync's cursor value in SELECT statement as not to skip rows added mid-sync
## Description

Consider the following `users` table.

| id | email             | name  | created_at          | updated_at          |
|----|-------------------|-------|---------------------|---------------------|
| 1  | evan@example.com  | Evan  | 2022-01-01 00:00:00 | 2022-01-01 00:00:00 |
| 2  | brian@example.com | Brian | 2022-01-02 00:00:00 | 2022-01-02 00:00:00 |
| 3  | andy@example.com  | Andy  | 2022-01-03 00:00:00 | 2022-01-03 00:00:00 |

A common sync would be to create in incremental sync, using the `updated_at` timestamp column + de-duped history.  As users are added or updated the `updated_at` column is changed and the next sync will pick them up as the cursor can only move forward in time.

There's a problem however at the boundary of the sync.  If the sync itself was running at `2022-01-03 00:00:00`, right when a new user was added, they would be not be included in the sync:

| id | email             | name  | created_at          | updated_at          |
|----|-------------------|-------|---------------------|---------------------|
| 1  | evan@example.com  | Evan  | 2022-01-01 00:00:00 | 2022-01-01 00:00:00 |
| 2  | brian@example.com | Brian | 2022-01-02 00:00:00 | 2022-01-02 00:00:00 |
| 3  | andy@example.com  | Andy  | 2022-01-03 00:00:00 | 2022-01-03 00:00:00 |
| 4  | greg@example.com  | Greg  | 2022-01-03 00:00:00 | 2022-01-03 00:00:00 |

We won't pick up user 4 (at least until something about them changes and their `updated_at` is bumped) because in subsequent syncs, we use the [greater-than comparison](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-jdbc/src/main/java/io/airbyte/integrations/source/jdbc/AbstractJdbcSource.java#L274-L278) to choose which records to import.  **This can lead to missing records if they were inserted as the sync was running**.

## Local confirmation

To confirm this behavior, create a source table with the 3 rows listed in the first example, and run the sync.  You will have 3 records in your destination.  Then add a 4th row with the an `updated_at` matching the current cursor ("2022-01-03 00:00:00" in this example).  Sync again, and see that user 4 did not make it to the destination. 

## Possible Solutions

1. Rather than selecting records from SQL sources matching `"SELECT %s FROM %s WHERE %s > ?"`, we could use `>=`, e.g. `"SELECT %s FROM %s WHERE %s >= ?"`.  This solution is the most robust because it also works for numeric (vs time) cursors as well. This will have the negative side effect of almost always creating a duplicate entry (the previous sync's most recent record is very likely to be returned again at the start of a subsequent sync), and normalization will need to deal with it. This is not a problem with de-duped history, but is weird in all other sync modes. 

2. Building from solution 1 above (using `>=`), we could store both the cursor value and the offset in the STATE.  This solves the duplicate row problem introduced above. The state stored could remember the previous sync's cursor and OFFSET.  In this way, the next sync could continue from the same cursor position + offset to be sure that now new records appeared within the same cursor that we haven't seen yet:

```sql
SELECT * from users LIMIT 100 # got some records
SELECT * from users LIMIT 100 OFFSET 3 # got 0 records after using offset
# first sync ends, cursor is {value: "2022-01-03 00:00:00" + offset: 0}

# Next sync starts
SELECT * from users WHERE updated_at >= "2022-01-03 00:00:00" LIMIT 100 OFFSET 1 # use previous offset + 1 # 1 new row found!
```

So, the state for an incremental SQL cursor source should look like:

```js
{ users: { offset: 0, cursor: "2022-01-03 00:00:00"}}
```

## Probably bad solutions

1. If we could detect that the cursor was a time field, we could append `AND ${cursor} >= NOW() - INTERVAL '2 seconds'`.  In this way, we would ignore "too recent" values that might be inserted at the time of the sync. This doesn't solve the problem with numeric cursors, only "time"-like cursors.
2. Introduce a sleep and one more read before the sync is determined to be complete, e.g.:
```sql
SELECT * from users LIMIT 100 # got some records
SELECT * from users LIMIT 100 OFFSET 3 # got 0 records after using offset
# SLEEP 2. Sleep enough time to ensure that the cursor's minimum resolution (often 1 second) has passed
SELECT * from users LIMIT 100  OFFSET 3 # got 1 record that was inserted during the sleep
# LOOP or END if still 0 rows
```
3. Don't ever send any RECORDS from the latest cursor value.  You'll never see any duplicates, but the destination will always be some level of "behind" the source

## Misc

This approach assumes that our source database have an implicit, static sort which will return rows in the same order without needing an `ORDER BY`.  This is true for postgres and mysql... is it true for all DB sources?  We may also need to add an `ORDER BY` clause.

### PR DESCRIPTION
**Pull request by tuliren**
## What
- Resolve https://github.com/airbytehq/airbyte/issues/14732
- Depend on https://github.com/airbytehq/airbyte/pull/15538
- Will only publish `source-postgres` and `source-postgres-strict-encrypt`.

## 🚨 User Impact 🚨
- This PR fixes a bug when new data is inserted at the same time as the sync starts, (non-dedup) incremental syncs can miss the records whose cursor value fall on the boundary.
- The downside is such incremental syncs will now duplicate records with the boundary cursor values.

## Review order
- `db_models.yaml`
- `AbstractJdbcSource.java`
- `AbstractJdbcSourceTest.java` - specifically `testIncrementalWithConcurrentInsertion`
- `StateManager.java` and implementations of the abstract state manager
- `StateDecoratingIterator.java`
- The reset of the changes

## TODO
- [x] Switch count field in `CursorInfo` to `long` to avoid the type conversion.
- [x] Update changelogs and mark this change as unpublished.
- [x] Update MS SQL which currently does not sort incremental streams based on the cursor field (because it overrides the query method).
- [x] Think about more unit tests.

## Integration tests
- [ ] ~source-scaffold-java-jdbc~
  - Already broken. Will not fix.
- [x] source-tidb
- [x] source-jdbc
- [x] source-mongodb-v2
- [x] source-mongodb-strict-encrypt
- [x] source-clickhouse
- [x] source-clickhouse-strict-encrypt
- [x] source-mysql
- [x] source-mysql-strict-encrypt
- [x] source-mssql
- [x] source-mssql-strict-encrypt
- [x] source-db2
- [x] source-db2-strict-encrypt
- [x] source-postgres
- [x] source-postgres-strict-encrypt
- [x] source-alloydb
- [x] source-alloydb-strict-encrypt
- [x] source-oracle
- [x] source-oracle-strict-encrypt
- [x] source-cockroachdb
- [x] source-cockroachdb-strict-encrypt
- [x] source-bigquery
- [x] source-redshift
- [ ] ~source-snowflake~
  - Already failing on master: https://github.com/airbytehq/airbyte/pull/17981

### CODE REVIEW

**Review by akashkulk — APPROVED** [review]

**Comment by tuliren** [comment]
/publish connector=connectors/source-postgres run-tests=false

**Comment by tuliren** [comment]
/publish connector=connectors/source-postgres-strict-encrypt run-tests=false

**Comment by tuliren** [comment]
/publish connector=connectors/source-postgres-strict-encrypt run-tests=false

**Comment by Kopiczek** [comment]
@jdbranham I think this missed a bunch of version updates? I only see an update to postgres. Meaning all the other connectors are actually missing this change until a new version is deployed?

**Comment by Kopiczek** [comment]
@tuliren ^

**Comment by tuliren** [comment]
> all the other connectors are actually missing this change until a new version is deployed?

@Kopiczek Yes. All the other connectors are tested, but not published. The change will be available with the next version bump.

Do you need this for another connector?

This is intentional because I think this record count is not a critical feature. It is only useful for a subset of an edge case.
- The edge case is that when some records are inserted into the database at the same time as the sync kicks off, and the insertion timestamp is used as the cursor.
- It only solves a subset of the edge case because if there are deletions together with insertions, the solution won't work.

So at the end of the day, only a small number of users will benefit from it, and does not worth the effort of publishing all the connectors.

To guarantee zero data loss, CDC is a better way.

**Comment by Kopiczek** [comment]
@tuliren 
Yes, we would need this for: BigQuery, Snowflake and RedShift connectors
We have some unfortunate tables that are syncs that have a very bad cursor field (some with hour granularity and some even a data rather then datetime). We currently support those doing a more sparse full syncs on them rather then incremental ones (since current versions simply skip data on cursor clash) but want to move to incremental as it is cheaper.

**Comment by tuliren** [comment]
@Kopiczek, got it. Thank you for this feedback. I am publishing these connectors in #18954.

**Pull request merged**
