### PR TITLE
add a timeout to junit test

### PR DESCRIPTION
**Pull request by stephane-airbyte**
Today there's no clear timeout for tests. The only one that exists is at the github action level, and it has to be conservative at 1h.
This change introduces a timeout per test method. The default value is set at 5 minutes per method, and can be overriden on a per method basis via the use of the junit @Timeout annotation.

We're also fixing a regression in the test ContainerFactory that was sharing less container than was possible. Finally, we're introducing a MdcScope.doNothing to allow using MdcScope in try blocks without triggering a compiler warning

### CODE REVIEW

**Comment by stephane-airbyte** [comment]
* **#35767** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/35767?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @stephane-airbyte and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by rodireich — APPROVED** [review]

**Pull request merged**
