### PR TITLE
Source PayPal: mark `Client ID` and `Client Secret` as required fields

### LINKED ISSUE #27900: Paypal source: mark fields as required
The Paypal source currently shows the following fields as optional

- Client ID
- Client Secret
- Refresh token

Suggestion is to make Client ID and Client Secret required as those are needed for setup.

Screen Shot 2023-06-30 at 5 09 45 PM

### PR DESCRIPTION
**Pull request by artem1205**
## What

 Resolve https://github.com/airbytehq/airbyte/issues/27900

## How

- mark `Client ID` and `Client Secret` as required fields

## Recommended reading order
1. `spec.json`

## 🚨 User Impact 🚨

no breaking changes

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-paypal-transaction test report (commit [`a11edac81a`](https://github.com/airbytehq/airbyte/pull/27968/commits/a11edac81a2c66a3e93439aef19e5fb84e045ca2)) - ❌

⏲️  Total pipeline duration: 01mn51s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-paypal-transaction/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-paypal-transaction docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-paypal-27900-spec/1688553244/a11edac81a2c66a3e93439aef19e5fb84e045ca2/source-paypal-transaction/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Comment by octavia-squidington-iii** [comment]
##  source-paypal-transaction test report (commit [`a11edac81a`](https://github.com/airbytehq/airbyte/pull/27968/commits/a11edac81a2c66a3e93439aef19e5fb84e045ca2)) - ❌

⏲️  Total pipeline duration: 01mn50s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-paypal-transaction/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-paypal-transaction docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-paypal-27900-spec/1688553464/a11edac81a2c66a3e93439aef19e5fb84e045ca2/source-paypal-transaction/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Review by lazebnyi — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-paypal-transaction test report (commit [`e137ee0e9b`](https://github.com/airbytehq/airbyte/pull/27968/commits/e137ee0e9b087a6972c99a916c87eb35dfdec556)) - ❌

⏲️  Total pipeline duration: 04mn16s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-paypal-transaction/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-paypal-transaction docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/artem1205_source-paypal-27900-spec/1688553908/e137ee0e9b087a6972c99a916c87eb35dfdec556/source-paypal-transaction/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Comment by artem1205** [comment]
@alafanechere , could we merge this PR with approve and merge command?

**Comment by alafanechere** [comment]
@artem1205 do you know why tests are failing?

**Comment by artem1205** [comment]
@alafanechere , right now `test_read` has failed due to no record in `balances` stream (on our `live` account). 
If I use our sandbox creds (as in https://github.com/airbytehq/airbyte/pull/27916) , an error with the schema will occur.

**Review by alafanechere — APPROVED** [review]
Feel free to use "approve and merge" as you understand the CAT failure reason and its not related

**Comment by octavia-approvington** [comment]
This code is at peace with itself <br/> imagine karate kid approving

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
