### PR TITLE
.github: bump python-version from 3.9 to 3.10

### PR DESCRIPTION
**Pull request by postamar**
I recently merged https://github.com/airbytehq/airbyte/pull/30743 which bumped the required python version from 3.9 to 3.10. Unfortunately, this broke some of the github workflows which are not part of CI. For instance: https://github.com/airbytehq/airbyte/actions/runs/6410814446/job/17404912512

This PR fixes the workflows by changing the `python-version` field of `actions/setup-python@v4` where appropriate.

### CODE REVIEW

**Comment by postamar** [comment]
https://github.com/airbytehq/airbyte/actions/runs/6412202314/job/17409317505 ran successfully! thanks for your help @flash1293 and @bnchrch 

I'm going to merge this now as the CDK has actually been published.

**Comment by flash1293** [comment]
Yay!

**Comment by octavia-approvington** [comment]
Myomoto says it looks good <br/> thats a niiice

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
