### PR TITLE
Spec and doc fixes to prepare MySQL Source for Beta

### LINKED ISSUE #17162: Certify MySQL Source for Beta
- [x] [Create a certification spreadsheet](https://docs.google.com/spreadsheets/d/1PIHkHKeIG-uW2kkHYf3uSjC0H-o9rgtDa89FDu7ll_k/edit#gid=1700962388)
- [x] Link spreadsheet in the issue description
- [x] Checklist filled up by engineering team
- [x] Move checklist to the product team for review
- [x] Reviewed/Updated by product team
- [x] Update connector documentation according to the comments in the checklist
- [ ] Update connector label to Beta
- [ ] Deploy beta connector version to Airbyte Cloud

### PR DESCRIPTION
**Pull request by grishick**
issue: [17162](https://github.com/airbytehq/airbyte/issues/17162)
## What
- rename _JDBC URL Params_ to _JDBC URL Parameters (Advanced)_ for consistency wth Postgres documentation
- Add a link to MySQL JDBC URL documentation
- Fix a broken link in mysql.md

### CODE REVIEW

**Review by ryankfu — APPROVED** [review]
LGTM

minor question, isn't example usually abbreviated as `e.g.`? I do see that the same change is in the `postgres/spec.json` so if anything this change is fine for consistency

**Comment by grishick** [comment]
> LGTM
> 
> minor question, isn't example usually abbreviated as `e.g.`? I do see that the same change is in the `postgres/spec.json` so if anything this change is fine for consistency

Thank you for catching this. I have copied the description from Postgres and by doing so copied the typo as well.

**Comment by Amruta-Ranade** [comment]
@ryankfu @grishick "example" is the right usage. "e.g." is engineering-speak and not used in user docs :)

**Comment by grishick** [comment]
> @ryankfu @grishick "example" is the right usage. "e.g." is engineering-speak and not used in user docs :)

Thanks Amruta. I changed `e.g.` to `example` in the spec file

**Comment by grishick** [comment]
/publish connector=connectors/source-mysql,connectors/source-mysql-strict-encrypt

**Review by misteryeo — APPROVED** [review]

**Pull request merged**
