### PR TITLE
🎉 Sources Facebook Marketing and Google Ads: not raise an exception if a stream is not found

### PR DESCRIPTION
**Pull request by yevhenii-ldv**
## What
*Resolve issue #30701.*

## How
*Set `raise_exception_on_missing_stream=False` for Source classes*

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Actions

- Unit & integration tests added
- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-facebook-marketing test report (commit [`d8d39a77c6`](https://github.com/airbytehq/airbyte/pull/30758/commits/d8d39a77c66615b5196985b1890beb3ad4ded952)) - ❌

⏲️  Total pipeline duration: 03mn34s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ykurochkin_source-facebook-marketing-and-google-ads-should-not-raise-an-exception-if-a-stream-is-not-found/1695740521/d8d39a77c66615b5196985b1890beb3ad4ded952/source-facebook-marketing/1.1.13/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d8d39a77c66615b5196985b1890beb3ad4ded952)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-google-ads test report (commit [`d8d39a77c6`](https://github.com/airbytehq/airbyte/pull/30758/commits/d8d39a77c66615b5196985b1890beb3ad4ded952)) - ❌

⏲️  Total pipeline duration: 08mn50s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Connector package install                                                | ✅        |
| Build source-google-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |
| Code format checks                                                       | ✅        |
| Validate airbyte-integrations/connectors/source-google-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ykurochkin_source-facebook-marketing-and-google-ads-should-not-raise-an-exception-if-a-stream-is-not-found/1695740521/d8d39a77c66615b5196985b1890beb3ad4ded952/source-google-ads/0.11.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d8d39a77c66615b5196985b1890beb3ad4ded952)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-google-ads test report (commit [`9a6627c435`](https://github.com/airbytehq/airbyte/pull/30758/commits/9a6627c4356df1d4e1bb7a153d2d23a28cdf3290)) - ❌

⏲️  Total pipeline duration: 07mn45s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Connector package install                                                | ✅        |
| Build source-google-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |
| Code format checks                                                       | ✅        |
| Validate airbyte-integrations/connectors/source-google-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ykurochkin_source-facebook-marketing-and-google-ads-should-not-raise-an-exception-if-a-stream-is-not-found/1695741376/9a6627c4356df1d4e1bb7a153d2d23a28cdf3290/source-google-ads/0.11.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:9a6627c4356df1d4e1bb7a153d2d23a28cdf3290)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-facebook-marketing test report (commit [`9a6627c435`](https://github.com/airbytehq/airbyte/pull/30758/commits/9a6627c4356df1d4e1bb7a153d2d23a28cdf3290)) - ✅

⏲️  Total pipeline duration: 101mn38s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ✅        |
| Code format checks                                                               | ✅        |
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ykurochkin_source-facebook-marketing-and-google-ads-should-not-raise-an-exception-if-a-stream-is-not-found/1695741376/9a6627c4356df1d4e1bb7a153d2d23a28cdf3290/source-facebook-marketing/1.1.14/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:9a6627c4356df1d4e1bb7a153d2d23a28cdf3290)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Review by girarda — APPROVED** [review]
change looks good. looking into why CI is failing...

**Comment by airbyte-oss-build-runner** [comment]
##  source-google-ads test report (commit [`b7d971ece9`](https://github.com/airbytehq/airbyte/pull/30758/commits/b7d971ece98740a3fd0b87655086cb36b83e66ef)) - ❌

⏲️  Total pipeline duration: 02mn52s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Connector package install                                                | ✅        |
| Build source-google-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |
| Code format checks                                                       | ✅        |
| Validate airbyte-integrations/connectors/source-google-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ykurochkin_source-facebook-marketing-and-google-ads-should-not-raise-an-exception-if-a-stream-is-not-found/1695750161/b7d971ece98740a3fd0b87655086cb36b83e66ef/source-google-ads/0.11.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b7d971ece98740a3fd0b87655086cb36b83e66ef)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-facebook-marketing test report (commit [`b7d971ece9`](https://github.com/airbytehq/airbyte/pull/30758/commits/b7d971ece98740a3fd0b87655086cb36b83e66ef)) - ✅

⏲️  Total pipeline duration: 94mn34s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Connector package install                                                        | ✅        |
| Build source-facebook-marketing docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Integration tests                                                                | ✅        |
| Acceptance tests                                                                 | ✅        |
| Code format checks                                                               | ✅        |
| Validate airbyte-integrations/connectors/source-facebook-marketing/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ykurochkin_source-facebook-marketing-and-google-ads-should-not-raise-an-exception-if-a-stream-is-not-found/1695750161/b7d971ece98740a3fd0b87655086cb36b83e66ef/source-facebook-marketing/1.1.14/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b7d971ece98740a3fd0b87655086cb36b83e66ef)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Comment by octavia-approvington** [comment]
Lets do it! <br/> giddddy-up

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
