### PR TITLE
🚨🚨🐛Source Quickbooks - Change datatype for RemainingCredit and Balance fields in creditmemo

### PR DESCRIPTION
**Pull request by believe-Mahesh**
…mount fields.

## What
The datatype for Balance and RemainingCredit is fixed as integer. The API is sending double currency values. Sync fails during normalization. Please check the below logs for more information.
```
2 of 281 ERROR creating table model quickbooks_4047_9130356487104946.credit_memos....................................... [ERROR in 0.72s]
Database Error in model credit_memos (models/generated/airbyte_tables/quickbooks_4047_9130356487104946/credit_memos.sql)
  invalid input syntax for type bigint: "942.0"
  compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/quickbooks_4047_9130356487104946/credit_memos.sql
Database Error in model credit_memos (models/generated/airbyte_tables/quickbooks_4047_9130356487104946/credit_memos.sql)
  invalid input syntax for type bigint: "942.0"
  compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/quickbooks_4047_9130356487104946/credit_memos.sql,retryable=<null>,timestamp=1687502786399,additionalProperties={}], io.airbyte.config.FailureReason@e652324[failureOrigin=normalization,failureType=system_error,internalMessage=invalid input syntax for type bigint: "942.0",externalMessage=Normalization failed during the dbt run. This may indicate a problem with the data itself.,metadata=io.airbyte.config.Metadata@1197fc2c[additionalProperties={attemptNumber=0, jobId=7244, from_trace_message=true}],stacktrace=AirbyteDbtError: 
2 of 281 ERROR creating table model quickbooks_4047_9130356487104946.credit_memos....................................... [ERROR in 0.72s]
Database Error in model credit_memos (models/generated/airbyte_tables/quickbooks_4047_9130356487104946/credit_memos.sql)
  invalid input syntax for type bigint: "942.0"
  compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/quickbooks_4047_9130356487104946/credit_memos.sql
Database Error in model credit_memos (models/generated/airbyte_tables/quickbooks_4047_9130356487104946/credit_memos.sql)
  invalid input syntax for type bigint: "942.0"
  compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/quickbooks_4047_9130356487104946/credit_memos.sql,retryable=<null>,times

```

## How
Data type of the two fields are changed to number.

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
No breaking changes!

### CODE REVIEW

**Comment by archangelic** [comment]
Thanks for your contribution! Looks like a good change to me. I'm going to be making some fixes, and update the version. This will be a breaking change as it changes the data type for those columns. You can find more information in our documentation on semantic versioning here: https://docs.airbyte.com/contributing-to-airbyte/resources/pull-requests-handbook/#semantic-versioning-for-connectors

**Comment by marcosmarxm** [comment]
Sorry for the long delay in getting this reviewed and merged. Our team is currently finishing the August Hackathon review contributions over the next two weeks, and after that, we will return to the community backlog.

**Comment by archangelic** [comment]
Thank you for your patience! I am going to be working on getting this merged.

**Comment by archangelic** [comment]
Thank you so much for your contribution! It has been merged as part of #30770!

**Pull request closed without merging**
