### PR TITLE
[source-google-analytics-data-api] - Migrate to CDK v5

### PR DESCRIPTION
**Pull request by pnilan**
## What
- Migrates to CDK v5
    - References models from `airbyte_cdk.models`
    - Adds orjson library reference in config_migrations
    - Updates `request_body_json` to directly reference start and end dates from stream_slice instead of stream_slice dictionary.
- Minor version bump

## Reading Order
1. `source.py`
2. `config_migrations.py`
3. `test_streams.py`

### CODE REVIEW

**Comment by pnilan** [comment]
/approve-regression-tests 

No sandbox account, but just updates per migration guide (orjson and model imports)

**Review by aldogonzalez8 — APPROVED** [review]
APPROVED

**Review by lazebnyi — APPROVED** [review]

**Review by bazarnov — APPROVED** [review]

**Pull request merged**
