### PR TITLE
add jmx to all long running apps

### PR DESCRIPTION
**Pull request by jrhizor**
This PR adds JMX to all long-running apps. This is so we can debug memory usage with VisualVM for long running applications.

### CODE REVIEW

**Review by benmoriceau — APPROVED** [review]

**Comment by jrhizor** [comment]
After setting this up and running:
```
./gradlew clean build -x test
VERSION=dev docker-compose -f docker-compose.yaml -f docker-compose.debug.yaml up
```

In VisualVM locally I have:

**Comment by jrhizor** [comment]
@cgardens any opinions if we should add this to the standard build/release or if we should only build this for debugging images?

**Comment by cgardens** [comment]
@jrhizor Is it considered good practice to have this running for production apps. I vaguely recall that it came with 1. security concerns and 2. performance issues. If I'm wrong about that, it seems nice, but if those a concern, then we should focus on it for debugging.

**Comment by jrhizor** [comment]
Yeah this is better as a debugging template than anything.

**Pull request closed without merging**
