### PR TITLE
feat: Filter out system views out of system namespaces

### PR DESCRIPTION
**Pull request by sergio-ropero**
Reopening #22221 after rollbacked due to error in the deploy process.

This changes allows to filter out system views created out of system namespaces.
Issue: [#1323](https://github.com/airbytehq/oncall/issues/1323)

As the only impacted DB is **Postgres**, we will bump only that image.

# TEST
## Current version (1.0.42)
Screenshot 2023-02-02 at 15 03 37

## PR version (dev)
Screenshot 2023-02-02 at 15 02 48

### CODE REVIEW

**Review by rodireich — APPROVED** [review]

**Comment by sergio-ropero** [comment]
/publish connector=connectors/source-postgres run-tests=false

**Pull request merged**
