### PR TITLE
Destination snowflake: Add support to set the number of (dbt) threads utilised to perform transformation or basic normalization

### PR DESCRIPTION
**Pull request by bittercoder**
## What
This change introduces the ability to adjust the number threads used by DBT in base-normalization for the following destination connectors:

* destination-bigquery
* destination-clickhouse
* destination-duckdb
* destination-mysql
* destination-mssql
* destination-oracle
* destination-postgres
* destination-redshift
* destination-snowflake
* destination-tidb

This PR aims to allow increasing the number of threads utilised by DBT when working with sources that have a large number of smaller tables, so that more of the normalization (or custom transformation) DBT processes can run in parallel, allowing the ability to significantly decrease the time spent running the transformation steps (which can often take longer than the actual sync).

Resolves issue #24388  

*Example of config option*

image

image

Base normalization transformation tests passing.

```
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_pick_a_port port 50001 is free
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_transform_bigquery transform_bigquery
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_transform_bigquery_no_credentials transform_bigquery
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_transform_bigquery_with_embedded_project_id transform_bigquery
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_transform_bigquery_with_embedded_mismatched_project_id transform_bigquery
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_transform_bigquery_with_invalid_format transform_bigquery
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_transform_postgres transform_postgres
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_transform_postgres_ssh port 50001 is free
transform_postgres
port 50001 is free
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_transform_snowflake transform_snowflake
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_transform_snowflake_oauth transform_snowflake
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_transform_snowflake_key_pair transform_snowflake
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_transform_mysql transform_mysql
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_transform_mssql transform_mysql
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_transform_clickhouse transform_clickhouse
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_transform transform_postgres
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_transform_tidb transform_tidb
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_transform_duckdb_schema transform_duckdb
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_transform_duckdb_no_schema transform_duckdb
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_parse Namespace(config='config.json', integration_type=<DestinationType.POSTGRES: 'postgres'>, out='out.yml')
PASSED
unit_tests/test_transform_config.py::TestTransformConfig::test_write_ssh_config PASSED

============================= 200 passed in 1.58s ==============================
```

## How

This change introduces the ability to configure an additional property `transformation_threads` for the snowflake destination connection, which allows adjusting the number threads used by DBT (the `thread` dbt property).  The snowflake connector previously always set this value at 5 threads, where as this will now default to 5, but allow specifying a value between 1 and 64.

The implementation will still assume the previous number of threads as the number of threads, if the `transformation_threads` value is not present (like what it used to be hard-coded in config for each connector).  For any connector where the threads was not explicitly set, it now sets the threads to 4 - which is the default number of threads for dbt if not configured explicitly (https://docs.getdbt.com/docs/core/connection-profiles#understanding-threads)

## Recommended reading order
1. `spec.json` (for each connection)
2. `Dockerfile` (for each connection)
3. `transform.py`
4. `test_transform_config.py`

## 🚨 User Impact 🚨
This PR does not introduce any breaking changes to the Snowflake destination connector, but it does necessitate a *Minor* semantic version bump for the connector because it introduces a new non-required property.  The default of the non-required property does mirror the previous hard coded `threads` value of `5` to ensure there are no regressions introduced for connectors which are already configured, to retain backwards compatibility in terms of behaviour.

## Pre-merge Checklist

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ n/a ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Connector version has been incremented
    - [x] Version has been bumped according to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines
    - [x] `Dockerfile` has updated version
- [x] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` with an entry for the new version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)

- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

### CODE REVIEW

**Comment by evantahler** [comment]
Thanks for the contribution, @bittercoder!  This is great.

A few requests before we can get this merged in:

1. A bunch of destinations use the same shared `base-normalization` code.  You don't need to update them all, but could you at least make the same changes in the SPEC for the following destinations (in addition to snowflake):
    * postgres
    * mysql
    * bigquery
    * redshift
2. For every destination you change, you'll need to bump it's version so we can publish it to dockerhub. That's done by editing the version label in each connector's dockerfile.  As this is a feature addition, this should be a minor semver version bump.  For [example](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-snowflake/Dockerfile#L23), this would make destination-snowflake v0.5.0
3. Each connector also needs a corresponding [change log entry](https://github.com/airbytehq/airbyte/blob/master/docs/integrations/destinations/snowflake.md) for the new version

**Review by evantahler — CHANGES_REQUESTED** [review]
Thanks for the contribution, @bittercoder!  This is great.

A few requests before we can get this merged in:

1. A bunch of destinations use the same shared `base-normalization` code.  You don't need to update them all, but could you at least make the same changes in the SPEC for the following destinations (in addition to snowflake):
    * postgres
    * mysql
    * bigquery
    * redshift
2. For every destination you change, you'll need to bump it's version so we can publish it to dockerhub. That's done by editing the version label in each connector's dockerfile.  As this is a feature addition, this should be a minor semver version bump.  For [example](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-snowflake/Dockerfile#L23), this would make destination-snowflake v0.5.0
3. Each connector also needs a corresponding [change log entry](https://github.com/airbytehq/airbyte/blob/master/docs/integrations/destinations/snowflake.md) for the new version

**Comment by bittercoder** [comment]
@evantahler Hi Evan, I've made the suggested changes, if you would like to give it another look 😄

**Review by evantahler — APPROVED** [review]
Thank you for all this work!

**Comment by evantahler** [comment]
@marcosmarxm This PR is a 👍 from me! Can you help me test and publish all these connectors?

**Comment by bittercoder** [comment]
@evantahler @marcosmarxm is there anything I can do to help move this PR along? Happy to rebase as necessary etc.

**Comment by evantahler** [comment]
Per https://github.com/airbytehq/airbyte/issues/26028, we are doing away with dbt-based normalization.  We are not accepting any PRs for normalization at this time.

**Pull request closed without merging**
