### PR TITLE
Revert source-zendesk-support

### PR DESCRIPTION
**Pull request by clnoll**
Fixes P0 https://github.com/airbytehq/oncall/issues/2530

### CODE REVIEW

**Review by pedroslopez — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-zendesk-support test report (commit [`71307a2b9d`](https://github.com/airbytehq/airbyte/pull/28478/commits/71307a2b9d8b7c3a507ff6aef9773cd687d70121)) - ❌

⏲️  Total pipeline duration: 17mn00s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zendesk-support/metadata.yaml | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build source-zendesk-support docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ✅        |
| Acceptance tests                                                              | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/revert-source-zendesk-support/1689787135/71307a2b9d8b7c3a507ff6aef9773cd687d70121/source-zendesk-support/0.10.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-support test
```

**Review by artem1205 — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-zendesk-support test report (commit [`71307a2b9d`](https://github.com/airbytehq/airbyte/pull/28478/commits/71307a2b9d8b7c3a507ff6aef9773cd687d70121)) - ❌

⏲️  Total pipeline duration: 18mn10s 

| Step                                                                          | Result   |
|:------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-zendesk-support/metadata.yaml | ✅        |
| Connector version semver check                                                | ✅        |
| QA checks                                                                     | ✅        |
| Code format checks                                                            | ✅        |
| Connector package install                                                     | ✅        |
| Build source-zendesk-support docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                    | ✅        |
| Acceptance tests                                                              | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/revert-source-zendesk-support/1689790459/71307a2b9d8b7c3a507ff6aef9773cd687d70121/source-zendesk-support/0.10.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-support test
```

**Comment by octavia-approvington** [comment]
Trying to merge your PR using a bot?
Comment this on the PR:
```
/approve-and-merge reason="<STATE YOUR REASON HERE>"
```
Make sure you've reviewed the [docs](https://internal-docs.airbyte.io/How-Tos/Overriding-PR-Merge-Rules)!

**Comment by octavia-approvington** [comment]
This is really good <br/> simply the best

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
