### PR TITLE
✨Source Recurly: migrate to low-code

### PR DESCRIPTION
**Pull request by pabloescoder**
## What
Migrating Source Recurly to YamlDeclarativeSource (Low-code) Airbyte CDK
Resolves https://github.com/airbytehq/airbyte-internal-issues/issues/7278

## How
By using the Connector Builder and the Low Code CDK

## Review guide
1. `manifest.yaml`
2. `components.py`

## User Impact
No breaking changes

## Can this PR be safely reverted and rolled back?

- [x] YES 💚

### CODE REVIEW

**Comment by natikgadzhi** [comment]
Assigning @ChristoGrab to review.

**Comment by ChristoGrab** [comment]
@pabloescoder So sorry for the slow turnaround, I let this PR fall off my radar entirely. Thanks for another solid contribution! Couple suggestions to fix the failing tests:

1. Let's update the cdk tag in `metadata.yaml` from `python` to `low-code`
2. It looks like there are a number of references in the schemas to the original schema json files, which is why the discover test is failing, ie:

```
user:
  description: The user who created the note.
  $ref: users.json
```

If you're feeling up for it you could grab the schemas from the deleted `shared` json files, add them as schemas in the manifest, then simply replace the refs: 

```
user:
  description: The user who created the note.
  $ref: #/schemas/users
```

If that feels like a long, boring task you could also just replace the json refs with object fields, and set `additionalProperties` to `true`:

```
user:
  description: The user who created the note.
  type:
    - "null"
    - object
  additionalProperties: true
```

I'll leave the decision up to you, but let me know if you have any questions!

**Comment by pabloescoder** [comment]
@ChristoGrab Thanks for the suggestions! I added them as schemas in the manifest and changed the ref to point to those schemas. 
Even though they're community connectors, why compromise on quality :D

The CI is green now, and the connector is ready for review.

**Review by natikgadzhi — APPROVED** [review]
Let's do this!

**Comment by aarif** [comment]
Hi there,

It should be noted somewhere for people upgrading to this version of the connector v1.1.1 from a previous version, in my case v1.0.12, that there is an update to the Connection State required.  Specifically, the `streamState->updated_at` format changed.

**From:**
- `2024-08-09T16:58:24`
- `2023-04-27T20:05:33+00:00`

**To:**
- `2024-08-09T16:58:24Z`
- `2023-04-27T20:05:33Z`

Other formats fail with an error such as:
- **No format in ['%Y-%m-%dT%H:%M:%SZ'] matching 2024-08-09T16:58:24**

**Pull request merged**
