### PR TITLE
Pin file-based sources to airbyte-cdk version 0.59.2 

### PR DESCRIPTION
**Pull request by clnoll**
Pinned until they can be made compatible with https://github.com/airbytehq/airbyte/pull/34411, which runs full refreshes concurrently.

### CODE REVIEW

**Comment by clnoll** [comment]
I'm skipping S3 because it's in the process of being upgraded.

**Review by flash1293 — COMMENTED** [review]
You need to bump the version in metadata.yaml

**Comment by clnoll** [comment]
Thank you @flash1293! I felt like I was missing something.

**Review by maxi297 — COMMENTED** [review]
Are there CDK features we fear might be blocked by this? When do we expect a fix?

**Review by flash1293 — APPROVED** [review]
LGTM, thanks!

**Comment by clnoll** [comment]
@maxi297 the fix should be straightforward and I'll either reach out to GL or do it quickly this afternoon.

**Review by maxi297 — APPROVED** [review]
Assuming we have a plan for the fix, LGTM!

**Pull request merged**
