### PR TITLE
Add schema change attrs to connection create

### PR DESCRIPTION
**Pull request by alovew**
Allow users to specify non-breaking schema change preference on Connection Create

### CODE REVIEW

**Review by gosusnp — APPROVED** [review]
LGTM.
Probably out of scope for this PR, but I'll ask since you may have more context. A long list of duplicated properties like this feels very error prone, how complex do you think it would be to refactor `WebBackendConnectionCreate` so that it can use `ConnectionCreate`?

**Comment by alovew** [comment]
I'm really not sure why it was built this way. But it seems we have this pattern for all of our objects that are passed to the WebBackendConnectionHandler - there's a version of the object for WebBackendConnectionHandler (e.g. WebBackendConnectionUpdate, WebBackendConnectionPatch, etc) and then a new object is created to pass to the ConnectionHandler. @benmoriceau do you know why this was done this way?

**Comment by cgardens** [comment]
>  how complex do you think it would be to refactor WebBackendConnectionCreate so that it can use ConnectionCreate?

we've looked in the past and it's hard to merge the definitions of 2 structs in openapi. we have tried to use `allof` but apparently that's considered bad practice. 🤷‍♀️

**Comment by gosusnp** [comment]
> > how complex do you think it would be to refactor WebBackendConnectionCreate so that it can use ConnectionCreate?
> 
> we've looked in the past and it's hard to merge the definitions of 2 structs in openapi. we have tried to use `allof` but apparently that's considered bad practice. 🤷‍♀️

What about nesting? (like having `WebBackendConnectionCreate` contain a `ConnectionCreate`) It may not be as elegant but I'd say it would be probably more practical for us.

**Comment by cgardens** [comment]
sure. given our new public api strategy, i feel like we can be a little less precious about these webbackend apis.

**Pull request merged**
