### PR TITLE
source-clinicaltrials contribution from ombhardwajj

### LINKED ISSUE #48085: [connector-request] Clinicaltrials
This is a suggestion to create a connector for Clinicaltrials using the UI Connector Builder.
The website for the connector is https://clinicaltrials.gov/

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to step 3).
3. Describe steps to get credentials.
4. Create the connector using the UI Builder.   

> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> This is a suggestion, and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend following the steps above.

### PR DESCRIPTION
**Pull request by ombhardwajj**
This closes #48085
## What

This PR adds a new connector for source Clinicaltrials (source-clinicaltrials).

Contributor-provided connector description:

Clinicaltrials provides data related to clinical studies.
Using this connector we can extract data from various streams such as studies and stats.
Docs : https://clinicaltrials.gov/data-api/api
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `conditions_or_disease` | `string` | Conditions or disease.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| studies |  | DefaultPaginator | ✅ |  ❌  |
| metadata_studies |  | No pagination | ✅ |  ❌  |
| stats |  | No pagination | ✅ |  ❌  |
| stats_field_values |  | No pagination | ✅ |  ❌  |
| stats_field_sizes |  | No pagination | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by marcosmarxm** [comment]
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Missing pagination
image


Also can you provide a use case of to use this data? Thanks

**Comment by ombhardwajj** [comment]
Although it supports a pageSize of 1000, I've deliberately set it to 100 otherwise the response was too large too handle for browser. 🙇 

Regarding some use cases :
The data from clinical trials offers a rich source of validated, evidence-based practices.

First it can be used by people / companies in pharma sector to analyze trial outcomes and methodologies to design better studies or improve drug formulations.

Second use case can be for research organizations where they use the data for meta-analyses and systematic reviews.

Third Digital Health Companies/Startups can leverage such insights to create or enhance digital tools that address specific healthcare challenges.

@marcosmarxm

**Comment by ombhardwajj** [comment]
@marcosmarxm Please review it today!

**Comment by marcosmarxm** [comment]
Only one endpoint return actual data users can analyze specific to studies and not user or actual clinical data. For that reason I'm declining the contribution

**Pull request closed without merging**
