### PR TITLE
Apply pmd to airbyte-config

### PR DESCRIPTION
**Pull request by alovew**
## What
- Add pmd gradle plugin and fail the build on failures
- Add a pmd rules XML file updated to exclude all rules that we are currently violating (for now)
- Exclude the airbyte-integrations subproject to exclude connectors
- Apply pmd changes to airbyte-config subproject

## How to Review

Adding the plugin & creating rules for it:
- Look at build.gradle
- Look at rules.xml

Fixing rule violations for airbyte-config:
- All the other files
- Pay attention to places where I use SuppressWarning (in case you think I shouldn't suppress it)

### CODE REVIEW

**Comment by alovew** [comment]
To be clear, this PR applies the PMD changes to the airbyte-config subproject since I was originally going to split up tickets to apply the rules one sub-project at a time. Instead, I've switched it so that we'll apply rules one ruleset at at time, but since I already did the work for airbyte-config I figured I should keep that one.

**Comment by jdpgrailsdev** [comment]
> * Exclude the airbyte-integrations subproject to exclude connectors

@alovew I didn't see this in the `build.gradle` script.  Did this get missed or not committed (or am I just overlooking it)?

**Comment by jdpgrailsdev** [comment]
> @jdpgrailsdev the connectors exclusion is added as an exclude-pattern in rules.xml

Ah...thanks.  We may want to move that into the build.gradle and use Gradle's support to filter out classes before it ever feeds them to PMD.  My thought is that when we need to add/remove excludes, it will probably be across all of the tools, not just PMD, so having the excludes all in the same file (build.gradle), though spread out, would be easier to find.  Not necessary for this PR, as we can do it when we add the next module to PMD, etc.

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Pull request merged**
