### PR TITLE
🐛 Source AppsFlyer: add source to API/UI

### PR DESCRIPTION
**Pull request by cameronwtaylor**
## What
The [AppsFlyer source](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-appsflyer) was not added to the [source definitions file](https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/seed/source_definitions.yaml). Therefore, the source does not show up in the API/UI. 

## How
* Added source to source_definitions.yaml
* Added AppsFlyer icon to icon folder

**Note:** Despite these changes, I have not gotten the source to show up for me locally. I'm not sure if this is something wrong with my local dev environment, or if I haven't made all the required changes to allow the source to appear.

## Recommended reading order
No recommended reading order.

## 🚨 User Impact 🚨
AppsFlyer source should show up in UI as an available source.

## Pre-merge Checklist
No relevant checklists.

## Tests
No relevant tests yet.

### CODE REVIEW

**Comment by harshithmullapudi** [comment]
Hey @cameronwtaylor sure team will check and get back to you.

**Comment by harshithmullapudi** [comment]
Changes look good to me you can move it out of draft

**Comment by cameronwtaylor** [comment]
@harshithmullapudi - thank you, I moved it out of draft. FYI - the docs link in this source is broken, because the docs were never added. I would take a shot at the docs, but I know nothing about this source :)

**Comment by harshithmullapudi** [comment]
This is not as simple as we expected there are some integration tests to fix. Thus created an issue and closing this will take this commits into the later PR

**Pull request closed without merging**
