### PR TITLE
Base Java S3: Update Avro TimeWithTimezone schema mapping

### LINKED ISSUE #21908: Base Java S3: Update Avro TimeWithTimezone schema mapping
## Issue
Current mapping for S3 Avro TimeWithTimezone type is:
`TIME_WITH_TIMEZONE_V1("WellKnownTypes.json#/definitions/TimeWithTimezone", Schema.Type.LONG)`
However for most of destinations the time with time zone is stored as a String type since most of those connectors does not support the format like: `01:23:45.678-10:30` .  
This become an issue when we use upload Avro files for Bigquery Denormalized. For storing time with time zone we have to use STRING type in Bigquery and Avro used LONG and as a result sync will fail with type mismatch.

## Solution 
Update the S3 Avro TimeWithTimezone mapping to: 
`TIME_WITH_TIMEZONE_V1("WellKnownTypes.json#/definitions/TimeWithTimezone", Schema.Type.String)`

Here is an example how normalization handle time with time zone: 
```
{% macro default__type_time_with_timezone() %}
    time with time zone
{% endmacro %}

{%- macro mysql__type_time_with_timezone() -%}
    char(1024)
{%- endmacro -%}

{%- macro sqlserver__type_time_with_timezone() -%}
    NVARCHAR(max)
{%- endmacro -%}

{% macro bigquery__type_time_with_timezone() %}
    STRING
{% endmacro %}

{% macro oracle__type_time_with_timezone() %}
    varchar2(4000)
{% endmacro %}

{% macro snowflake__type_time_with_timezone() %}
    varchar
{% endmacro %}

{% macro redshift__type_time_with_timezone() %}
    TIMETZ
{% endmacro %}

{% macro clickhouse__type_time_with_timezone() %}
    String
{% endmacro %}

{%- macro tidb__type_time_with_timezone() -%}
    char(1000)
{%- endmacro -%}

```
Most of normilized connectors using string/varchar type so maybe we could do the same way for Avro staging.

### PR DESCRIPTION
**Pull request by suhomud**
## What
Current mapping for S3 Avro TimeWithTimezone type is:
`TIME_WITH_TIMEZONE_V1("WellKnownTypes.json#/definitions/TimeWithTimezone", Schema.Type.LONG)`
However for most of destinations the time with time zone is stored as a String type since most of those connectors does not support the format like: `01:23:45.678-10:30` .  
This become an issue when we use upload Avro files for Bigquery Denormalized. For storing time with time zone we have to use STRING type in Bigquery and Avro used LONG and as a result sync will fail with type mismatch.

## How
Update the S3 Avro TimeWithTimezone mapping to: 
`TIME_WITH_TIMEZONE_V1("WellKnownTypes.json#/definitions/TimeWithTimezone", Schema.Type.String)`
Here is an example how normalization handle time with time zone: 
```
{% macro default__type_time_with_timezone() %}
    time with time zone
{% endmacro %}

{%- macro mysql__type_time_with_timezone() -%}
    char(1024)
{%- endmacro -%}

{%- macro sqlserver__type_time_with_timezone() -%}
    NVARCHAR(max)
{%- endmacro -%}

{% macro bigquery__type_time_with_timezone() %}
    STRING
{% endmacro %}

{% macro oracle__type_time_with_timezone() %}
    varchar2(4000)
{% endmacro %}

{% macro snowflake__type_time_with_timezone() %}
    varchar
{% endmacro %}

{% macro redshift__type_time_with_timezone() %}
    TIMETZ
{% endmacro %}

{% macro clickhouse__type_time_with_timezone() %}
    String
{% endmacro %}

{%- macro tidb__type_time_with_timezone() -%}
    char(1000)
{%- endmacro -%}

```
Most of normilized connectors using string/varchar type so maybe we could do the same way for Avro staging.

## Recommended reading order
1. `JsonSchemaType.java` - new type mapping 
2. `JsonToAvroSchemaConverter.java` - removed `LogicalTypes` for TIME_WITH_TIMEZONE_V1
3. Other just tests adaptation 

## 🚨 User Impact 🚨
Since the V1 protocol is not yet used no user impact

### CODE REVIEW

**Comment by grishick** [comment]
Because V1 protocol is not yet enabled, this change will not have to publish any new connector versions.

**Review by edgao — APPROVED** [review]
can you try running the s3 tests with protocolv1 enabled? I'm curious if this breaks anything

**Comment by suhomud** [comment]
@edgao It is already enabled for s3
```
  @Override
  public ProtocolVersion getProtocolVersion() {
    return ProtocolVersion.V1;
  }
```

**Review by grishick — APPROVED** [review]

**Review by ryankfu — APPROVED** [review]

**Pull request merged**
