### PR TITLE
🎉 Source Pinterest: increase `unit_test` coverage up to 90%

### LINKED ISSUE #16073: Source Pinterest: increase test coverage to 90%
Current test coverage is 80%:
```
Name                         Stmts   Miss  Cover
------------------------------------------------
source_pinterest/source.py     175     36    79%
source_pinterest/utils.py        4      0   100%
------------------------------------------------
TOTAL                          179     36    80%

```
Coverage should be increased to 90% for the certification to be passed.

### PR DESCRIPTION
**Pull request by bazarnov**
## What
Resolving: https://github.com/airbytehq/airbyte/issues/16073

## How
- added missing unit_tests to get coverage up to 90%

### CODE REVIEW

**Review by davydov-d — APPROVED** [review]

**Review by lazebnyi — APPROVED** [review]

**Comment by bazarnov** [comment]
Here we are facing the `429 - Exceeded Rate Limits per user / day`, for trial accounts it's only up to 300. requests / user / day. 
I'm merging this change, since unit tests are fine, based on this `_unitTestCoverage` report: https://github.com/airbytehq/airbyte/runs/8133958280?check_suite_focus=true#step:11:1431

**Pull request merged**
