### PR TITLE
✨Destination Cumul.io: Rebrand to Luzmo

### PR DESCRIPTION
**Pull request by jooststessens**
## What
Cumul.io has recently rebranded to Luzmo (https://luzmo.com). This PR aims to replace all references of Cumul.io in the code and documentation to reflect the rebranding.

## How
/

## Recommended reading order
/

## 🚨 User Impact 🚨
There are no breaking changes in the implementation of the connector. However, as the connector itself has changed name, it might be required to replace all current setups with the Cumul.io destination connector to use the Luzmo destination connector instead. 
I'm not sure if this is considered a breaking change, I tagged the release with a new version 0.2.0 and included this information in the changelog documentation of the destination connector.

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks for the refactor @jooststessens it isn't going to be possible to review this week your contribution. I'll add it to the next sprint.

**Review by marcosmarxm — APPROVED** [review]
The change looks good @jooststessens I'll work to get this merge next week. This week the codebase is freeze because of holidays.

**Comment by jooststessens** [comment]
Thanks a lot @marcosmarxm for your response and assistance here! I've just added another small commit to slightly change the connector documentation (as the rebranding has happened a few months ago, we decided to actually get rid of the "Formerly Cumul.io" reference), I hope that's okay? 🙏
Enjoy the upcoming holidays!

**Comment by jooststessens** [comment]
Hi @marcosmarxm,

First of all, Happy New Year to you and the Airbyte team! 
I wanted to quickly check in on this PR to see if there's anything I can do to get it merged? I e.g. notice there a merge conflict for the README file of the connector, as it seems to have been modified by commit [368ba78](https://github.com/airbytehq/airbyte/commit/368ba78b64d6474261926782479d15260462414f) ~ two months ago :-)

Kind regards,
Joost

**Comment by jooststessens** [comment]
@marcosmarxm This PR has been open for >5 months now, is there any update or timeline when this could finally be merged?

Thanks in advance for your assistance here!

**Comment by marcosmarxm** [comment]
@jooststessens the destination Luzmo (Cumul.io) was archived and won't receive more updates until the destination team release an stable CDK to build custom connectors. I'll work to update the documentation to reflect the current state and sorry for the trouble and lack of updates here.

**Comment by jooststessens** [comment]
@marcosmarxm Thank you for the update. We're quite interested in understanding what the current requirements are to get the Luzmo destination connector unarchived again? 🙂
From what I understand, this would require changes to your Airbyte Python CDK to support destination connectors, correct? If so, is there already any timeline for this on your end? And related to that, are there any other changes required from (y)our end?

Thanks in advance for your response!

**Pull request closed without merging**
