### PR TITLE
feat(destination-snowflake): Update host regex to allow connecting to LocalStack Snowflake

### PR DESCRIPTION
**Pull request by whummer**
First of all, big kudos for building Airbyte - it's really an awesome product! 🚀 🤩  

## What

This PR updates the host regex for Snowflake destinations, to allow connecting to LocalStack Snowflake.

**Motivation:** At LocalStack, we have recently started building a Snowflake emulator that allows running SF queries entirely on the local machine: https://blog.localstack.cloud/2024-05-22-introducing-localstack-for-snowflake/ . As part of building out a repo with sample applications (see [here](https://github.com/localstack-samples/localstack-snowflake-samples)), we are putting together an illustrative Airbyte application that connects to the local Snowflake emulator (running on `localhost`) and performs various data transformations / migrations.

The LocalStack Snowflake emulator is accessible on `snowflake.localhost.localstack.cloud`, which is a domain name that maps to a local IP address. Currently, when attempting to configure this host in the Airbyte destination settings, the UI raises an error message as it doesn't match the expected pattern:
image

## How

In this PR, we update the regular expression in `spec.json` to allow specifying subdomains pointing to the LocalStack Snowflake emulator, in particular also `snowflake.localhost.localstack.cloud`.

## Review guide

Looking forward to getting your feedback! Please let me know if I should add any unit tests, provide more details, etc. 🙌 Thank you

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by whummer** [comment]
Update: FWIW, connecting LocalStack Snowflake as a **source** already works out of the box, see screenshot: 🚀 
image

So, the scope of this PR is primarily to enable the same configuration for LocalStack Snowflake as a **destination** as well.

**Review by evantahler — COMMENTED** [review]
This change is OK in spirit, but needs a version bump and changelog entry

**Comment by whummer** [comment]
Thanks for the feedback @evantahler ! I've updated the PR, I took inspiration from a recent [previous PR](https://github.com/airbytehq/airbyte/commit/4fc7f1a82d16548ab4ecc159f796c9e5a19c4bc0) that was updating the same destination. 

I've bumped the version in `metadata.yaml` (I'm assuming a patch version bump is ok, since it is only a minor change, and shouldn't break existing functionality), and added an entry to the changelog in `snowflake.md`. 👍 

Please let me know if anything is missing or should be updated/extended. Thanks for your support!

**Review by marcosmarxm — APPROVED** [review]
LGTM! Thanks @whummer

**Review by evantahler — APPROVED** [review]

**Comment by marcosmarxm** [comment]
Hello your feedback matters a lot to us. Can you spare just 2 minutes to complete a [survey](https://form.typeform.com/to/DOBqejte)? We’re dedicated to making the contributor experience even better, and your input is key to achieving excellence. Thank you for helping us improve!

**Pull request merged**
