### PR TITLE
:tada: Python CDK: handle `requests.exceptions.ChunkedEncodingError` for broken connections

### PR DESCRIPTION
**Pull request by davydov-d**
## What
According to this [ticket](https://github.com/airbytehq/airbyte/issues/12591), the `requests.exceptions.ChunckedEncodingError` is not handled, though it probably should be. Now fixing it in airbyte-cdk

### CODE REVIEW

**Review by bazarnov — CHANGES_REQUESTED** [review]
The `CHANGELOG.md` should also be updated
https://github.com/airbytehq/airbyte/blob/ddavydov/%2312591-retry-chunked-encoding-error-in-cdk/airbyte-cdk/python/CHANGELOG.md

**Comment by davydov-d** [comment]
> The `CHANGELOG.md` should also be updated https://github.com/airbytehq/airbyte/blob/ddavydov/%2312591-retry-chunked-encoding-error-in-cdk/airbyte-cdk/python/CHANGELOG.md

thanks, done

**Review by bazarnov — APPROVED** [review]

**Review by evantahler — APPROVED** [review]
Nice!

**Pull request merged**
