### PR TITLE
🐛 Source Chargebee, Delighted: disabled Incremental tests 

### PR DESCRIPTION
**Pull request by bazarnov**
## What
In order to maintain a good percentage of the `connector-health` report, some sources like `Chargebee` and `Delighted` stopped passing the `incremental tests` due to the errors in certain `test methods` of the CAT. Here is the related Slack thread: https://airbyte-globallogic.slack.com/archives/C02U9R3AF37/p1690810513681859

## How
- disabled the `Incremental` tests due to the inability to compare `str` and `int` values

## 🚨 User Impact 🚨
No impact is expected.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-chargebee test report (commit [`b9f182e43d`](https://github.com/airbytehq/airbyte/pull/28905/commits/b9f182e43d615aaff76753bdb908d35a2b5e1c83)) - ❌

⏲️  Total pipeline duration: 03mn17s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-chargebee/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ❌        |
| QA checks                                                               | ❌        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-chargebee docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-chargebee-delighted-disable-incremental-cat/1690879974/b9f182e43d615aaff76753bdb908d35a2b5e1c83/source-chargebee/0.2.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-chargebee test
```

**Comment by octavia-squidington-iii** [comment]
##  source-delighted test report (commit [`b9f182e43d`](https://github.com/airbytehq/airbyte/pull/28905/commits/b9f182e43d615aaff76753bdb908d35a2b5e1c83)) - ❌

⏲️  Total pipeline duration: 03mn23s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-delighted/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| QA checks                                                               | ❌        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-delighted docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-chargebee-delighted-disable-incremental-cat/1690879974/b9f182e43d615aaff76753bdb908d35a2b5e1c83/source-delighted/0.2.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-delighted test
```

**Comment by octavia-squidington-iii** [comment]
##  source-chargebee test report (commit [`b9f182e43d`](https://github.com/airbytehq/airbyte/pull/28905/commits/b9f182e43d615aaff76753bdb908d35a2b5e1c83)) - ❌

⏲️  Total pipeline duration: 07mn13s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-chargebee/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ❌        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-chargebee docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-chargebee-delighted-disable-incremental-cat/1690880287/b9f182e43d615aaff76753bdb908d35a2b5e1c83/source-chargebee/0.2.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-chargebee test
```

**Comment by octavia-squidington-iii** [comment]
##  source-chargebee test report (commit [`d8a4f16a56`](https://github.com/airbytehq/airbyte/pull/28905/commits/d8a4f16a56d72d805d260918d5b774d707af1d7b)) - ✅

⏲️  Total pipeline duration: 4.28s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-chargebee-delighted-disable-incremental-cat/1690881074/d8a4f16a56d72d805d260918d5b774d707af1d7b/source-chargebee/0.2.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-chargebee test
```

**Comment by octavia-squidington-iii** [comment]
##  source-delighted test report (commit [`d8a4f16a56`](https://github.com/airbytehq/airbyte/pull/28905/commits/d8a4f16a56d72d805d260918d5b774d707af1d7b)) - ❌

⏲️  Total pipeline duration: 02mn08s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-delighted/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-delighted docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-chargebee-delighted-disable-incremental-cat/1690881074/d8a4f16a56d72d805d260918d5b774d707af1d7b/source-delighted/0.2.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-delighted test
```

**Review by lazebnyi — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-chargebee test report (commit [`58327400d0`](https://github.com/airbytehq/airbyte/pull/28905/commits/58327400d0f8cf3803e751431708ec6c8d71f0f8)) - ✅

⏲️  Total pipeline duration: 06mn30s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-chargebee/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-chargebee docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-chargebee-delighted-disable-incremental-cat/1690882286/58327400d0f8cf3803e751431708ec6c8d71f0f8/source-chargebee/0.2.4/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-chargebee test
```

**Pull request merged**
