### PR TITLE
CDK: improve TypeTransformer to convert simple types to array of simple types

### PR DESCRIPTION
**Pull request by grubberr**
Signed-off-by: Sergey Chvalyuk <grubberr@gmail.com>

## What
I think we can improve TypeTransformer to convert simple type (`string`, `number`, `integer`, `boolean`, `null`) values
to array of this values if schema requires array of simple type

For example: 
```
schema = {
    "type": "object",
    "properties": {
        "value": {"type": "array"}
    }
}

{"value": 1} -> {"value": [1]}
{"value": "string"} -> {"value": ["string"]}
{"value": "string"} -> {"value": ["string"]}
{"value": True} -> {"value": [True]}
{"value": 1.5} -> {"value": [1.5]}
```

1. If value is not simple type ("array", "object") we DON'T DO such conversion:

```
{"value": {"key": "value"}} -> {"value": {"key": "value"}}  #  nothing changed
```

2. if array-items is complex type DO nothing 

```
schema = {
    "type": "object",
    "properties": {
        "value": {
            "type": "array",
            "items": {"type": ["object"]}   # <- complex type
        }
    }
}

{"value": 10} -> {"value": 10}  # nothing changed 
```

3. additional conversions inside array still works as before 

```
schema = {
    "type": "object",
    "properties": {
        "value": {
            "type": "array",
            "items": {"type": ["string"]}
        }
    }
}

{"value": 10} -> {"value": ["10"]}
```

### CODE REVIEW

**Review by sherifnada — APPROVED** [review]
Good addition! Just for simplicity, could you release only 1 version of the CDK containing all 2-3 changes you recently made in the separate PRs?

**Comment by grubberr** [comment]
@sherifnada ok I will publish together with https://github.com/airbytehq/airbyte/pull/16695

**Pull request merged**
