### PR TITLE
[airbyte-cdk] - Update JSON Error Message Parser to return additional error message fields or default to dict

### PR DESCRIPTION
**Pull request by pnilan**
## What
- Updates the JSON error message parser to check for additional error message properties, if none, then returns the string representation of the response body.
- Closes https://github.com/airbytehq/airbyte-internal-issues/issues/9020

## Can this PR be safely reverted and rolled back?

- [X] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by natikgadzhi** [comment]
@alafanechere note: CDK changes regression tests are failing here: https://fff942bf5099f1330556ce7fdc9c8473e612d2cc255905901f6214e-apidata.googleusercontent.com/download/storage/v1/b/airbyte-ci-reports-multi/o/airbyte-ci%2Fconnectors%2Ftest%2Fpull_request%2Fpnilan_airbyte-cdk-improve-error-messages-parsing%2F1723582353%2F24b2e4fa50925f9d42b4636ec86f4435cbba5cd8%2Fsource-shopify%2F2.4.20%2Foutput.html?jk=AXZI6JxzKrkkrA9ZobZjFyIqybP76A3l-aTkgkzFGo8OXrRX5V_er9qRYS29Is-Cfl4pAA8g4W5XJ9LsmkXDLuV05qaJLceuat7hzY0J9iXx9oGr-hpvu5mvSV6JkrKUwiaO53tvLC-5WHwIYKpztrZOKtF180DVyU7r4oy-P-saSohugvWxPNGjbeb1Oo2_5RqfhtTxJajQuWjrSDZUZ8_ctnH8SbGd8XpoRpiN18Z1cb5x23ylrgmTWJGMdCLspZVPOPs8ArhQS_i10HJ134qFZhsAgWge-dmDiBF0gzjXiI31oWr9xEXqdLEDZMx3QlpqtEAu06NVBA6Qgbq0ppR5-PItDOKzjPgyBHHWxVUkfrIi1GipPhl6xBTUTwcIkysGYceUVDBxwVUF-l_y5HSM_zuW2Ax6CDlLC_2m4kfdE-rWirSIixGXZdv3tPbsoIiOnUWTK1kjct7o-ZjylZgMro57__9q0GcJ3MA3wAnFWi7IEDmUkNJJJzDi4rhqhpevEHivYYsGiw5C4hFJ6i-BJ_3ZC2tBFTPkPJ9Y3kTXD6Z4B1RBBeop5AVmyZClPlL-BWMf0BS1C2iZ8ge_gz3-qUEgIhuI-0kqtMMy_s29FbBH-_np4rU1jbKRaGkMJQpOAU6Q-5pWRmW-bAsopEzJj7_IQUYbk0jesHAwsYqC-C7J4c-c5EXXPbFLpvP4VVNiUXm33yocEb3-l5wq3QYXfqwtO23Q1kciAsZQ8U8JHNq0rJtIMysnYszNCkjjbTSUAUxdv6Lxp3X9Ur9mwABMxK2udmKyXQWDc-7MnwofA2jnPNos13YJ7SsCgXws56IkmyH-PcW5oDbZiznTQblO__b2WNgUPW3QsCn5v60omqCs3dA_EcoefDTljSkE4TP3caLGlELhT69N1WaJgH246tsE2cgPNI3hJlij1PrTbHDi3nN9j1K1RgxweousJZJCboxPQSE7c574ZbOoJDHDsdAbbCpxzG2Cjp3Xp_j13suW_k5Nfu1LMx-I3FRUGsyJxedOZgoQUKnxXLpKkivDj3gowtSXoFJcV1E-j4cF-P6uyd87aDrn3jOgt71HWKQR8z14WF0xhuiXU7A_3T9r1jcqbR1DRCuvtxWxwoUXJrrbcEetEAROKLIWirNQ3gEZA-L1IEHgP5H6o9oqKCRbyZcpreFoMXSzqoe_6C-iAMd_wLu7KfNP80BCGUlwZGnEa27ELTLaeLlzdUluJgMfCxazkeoZYpJOHyzSVOvDVM5EREiO1XzBZHySnIVVr5Yput9Bb80tFBRwEsytAOv6GXj4nROzszWNgBUtB4bxY3kJzBNCocr2Upe4Vs96Ny_xGQswkMQCQxD9aL9WYG2PmnxYPRT6Roj6xOtYQbykAnNfnPWkrKPvGM5WQHor2DVB-UpQCDfjIG3WH3gWHz-8Dw&isca=1 says it doesn't have a folder?

**Comment by alafanechere** [comment]
> @alafanechere note: CDK changes regression tests are failing here.

@clnoll I'm not 100% sure. Do we want to skip or run these regression tests on CDK change? If we want to run them  there's indeed a bug to fix. I think we should disable them until fixed to not block the python team.

**Comment by natikgadzhi** [comment]
To confirm, we want to fix them, but it’s ok to file an issue with details
and prioritize with the other regression tests related work in a batch.

**Review by girarda — APPROVED** [review]
@pnilan can you add some unit tests covering these cases?

**Pull request merged**
