### PR TITLE
🐛 Source google ads: mark custom query fields required

### PR DESCRIPTION
**Pull request by tuliren**
## What
- Currently users can add custom queries without specifying any field.
- This can lead to missing key error.
- Sample Sentry issue: https://sentry.io/organizations/airbytehq/issues/3522206562/?project=6527718
- Resolve https://github.com/airbytehq/oncall/issues/467.

### CODE REVIEW

**Comment by tuliren** [comment]
I am not 100% sure this is the correct solution. Will pause until getting some review from the API team first.

**Review by sherifnada — APPROVED** [review]

**Review by alafanechere — COMMENTED** [review]
@tuliren, this introduces a backward incompatibility that will be detected by SAT: adding required fields makes the previous connector config incompatible. 
In this situation, if I understood the problem well, having empty `query` or `table_name` is causing a problem, so I  think we can bypass backward compatible tests. I'll commit changes to the `acceptance-test-config.yml` to bypass backward compatibility tests.

**Comment by sherifnada** [comment]
@tuliren you should assign this as an OC to GL, seems like there is a non-trivial issue here maybe

**Comment by tuliren** [comment]
@sherifnada, yes, I realized that. Will do.

**Pull request merged**
