### PR TITLE
Upgraded normalization DBT to 0.19.1

### PR DESCRIPTION
**Pull request by MarcBuch**
## What
Solves #2931 

## How
- Changed the required DBT version in airbyte-integrations/bases/base-normalization/setup.py

## Pre-merge Checklist
- [x] *Run integration tests*
- [x] *Publish Docker images*

### CODE REVIEW

**Comment by davinchia** [comment]
Thanks for this!

**Review by davinchia — APPROVED** [review]

**Review by danieldiamond — APPROVED** [review]
👍

**Review by ChristopheDuong — CHANGES_REQUESTED** [review]
Upgrading the DBT version shipped in Airbyte normalization docker images will probably require a change to the associated dbt-utils version too:
https://github.com/fishtown-analytics/dbt-utils/blob/0.6.2/dbt_project.yml

(dbt-utils 0.6.2 requires a DBT "<0.19.0" so we should also bump the version in https://github.com/airbytehq/airbyte/blob/3e6843808e484a99e53843458c308a195779ebf7/airbyte-integrations/bases/base-normalization/dbt-project-template/packages.yml#L5 to 0.6.4 at least)

**Comment by MarcBuch** [comment]
Will do

**Review by danieldiamond — APPROVED** [review]
If you wanted to update relevant documentation, the normalization project overrides the `cross_db_utils` macro and the comments (on line 3) still specify version `0.6.2` 
```
airbyte-integrations/bases/base-normalization/dbt-project-template/macros/cross_db_utils/concat.sql
3:        https://github.com/fishtown-analytics/dbt-utils/blob/0.6.2/macros/cross_db_utils/concat.sql
```

**Review by ChristopheDuong — APPROVED** [review]

**Comment by ChristopheDuong** [comment]
> If you wanted to update relevant documentation, the normalization project overrides the `cross_db_utils` macro and the comments (on line 3) still specify version `0.6.2`
> 
> ```
> airbyte-integrations/bases/base-normalization/dbt-project-template/macros/cross_db_utils/concat.sql
> 3:        https://github.com/fishtown-analytics/dbt-utils/blob/0.6.2/macros/cross_db_utils/concat.sql
> ```

Thanks for the reminder!

**Comment by michel-tricot** [comment]
Thanks a lot @MarcBuch !!

**Pull request merged**
