### PR TITLE
fix(connector-builder): update deps

### PR DESCRIPTION
**Pull request by artem1205**
## What

Fix missing deps: `pytz`
Was needed to be added in https://github.com/airbytehq/airbyte/pull/38026

## How
add `pytz` to main group in poetry

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by alafanechere — CHANGES_REQUESTED** [review]
I think you should bump the CDK version. Can you share where this dependency was missing?

**Review by natikgadzhi — APPROVED** [review]
This one, assuming it's the fix for pytz not being available and failing, looks good to me. I'm assuming that the way we bump CDK versions have not changed yet, and the release workflow will do it for you.

I have a question, though. Given that the https://github.com/airbytehq/airbyte/pull/38026 PR changed `macros.py` and that we have tests for this that you also changed, how the hell did these tests pass on CI if the dependency was not declared and was not included in the virtual env? 

Why wasn't this caught? 

Nitpicks: 
- Please use semantic PR titles, i.e. [`#proj-conventional-commits`](https://airbytehq-team.slack.com/archives/C071RBS82HM)
- Just be more explicit about what the change is and why. In this case, link to the PR that was borked and how this fixes it.

**Comment by artem1205** [comment]
@alafanechere ,
> Can you share where this dependency was missing?

was missed in macros.py: https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/declarative/interpolation/macros.py#L11
> I think you should bump the CDK version.

Will be bumped using the GHA after PR merge.

**Comment by artem1205** [comment]
@natikgadzhi ,

> I have a question, though. Given that the https://github.com/airbytehq/airbyte/pull/38026 PR changed macros.py and that we have tests for this that you also changed, how the hell did these tests pass on CI if the dependency was not declared and was not included in the virtual env?
Why wasn't this caught?

Airbyte CI installs `all` dependencies during the test run. `Pytz` was mentioned as a 3-rd party dependency package for some of the test library.

**Review by alafanechere — APPROVED** [review]

**Pull request merged**
