### PR TITLE
feat(source-s3): add excel file support to S3

### PR DESCRIPTION
**Pull request by lazebnyi**
## What
Add excel file support

## How
migrate to v4 CDK

## User Impact
No

## Can this PR be safely reverted and rolled back?
- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by lazebnyi** [comment]
regression tests - https://github.com/airbytehq/airbyte/actions/runs/10394949973

**Review by girarda — APPROVED** [review]
this is great @lazebnyi :shipit: 

side question: do you know why the regression tests timeout?

**Comment by lazebnyi** [comment]
> this is great @lazebnyi :shipit:
> 
> side question: do you know why the regression tests timeout?

may be to much records. I'll try find another connection for tests

**Comment by girarda** [comment]
@lazebnyi were you able to run the regression tests with another config? If yes, I'm ✅ . If that's the only account we were able to test with, I'm a little suspicious.

For what it's worth, our test account are probably fine for filebased connectors since we can seed them with the data we want

**Comment by lazebnyi** [comment]
I have run tests with our test account, but an issue has occurred. 
Current status: blocked due to a regression test issue. - https://github.com/airbytehq/airbyte-internal-issues/issues/9320

**Comment by lazebnyi** [comment]
blocked - https://github.com/airbytehq/airbyte-internal-issues/issues/9419

**Comment by lazebnyi** [comment]
regression tests - https://github.com/airbytehq/airbyte/actions/runs/10605480648

**Pull request closed without merging**
