### PR TITLE
Greg/teradata vantage

### LINKED ISSUE #21141: Assist teradata destination contribution
A community member submitted a new destination connector for [Teradata Vantage](https://www.teradata.com/Vantage). This issue tracks assisting this contribution, getting it published and merged.
Original community PR: https://github.com/airbytehq/airbyte/pull/20428
My PR for testing and small edits: https://github.com/airbytehq/airbyte/pull/21093

### PR DESCRIPTION
**Pull request by grishick**
Fixes https://github.com/airbytehq/airbyte/issues/21141

## What
Copy of this community PR: https://github.com/airbytehq/airbyte/pull/20428

### CODE REVIEW

**Comment by grishick** [comment]
@SatishChGit in order to address the CLA mismatch that is caused by some of the commits that came from your local git user, could you please take the files from this PR and submit them as a single clean commit overwriting your original PR.

**Comment by SatishChGit** [comment]
> @SatishChGit in order to address the CLA mismatch that is caused by some of the commits that came from your local git user, could you please take the files from this PR and submit them as a single clean commit overwriting your original PR.

@grishick I did this change to  original PR as asked. Now, its clean and can see single commit with my @SatishChGit  git user. Thank You

**Pull request closed without merging**
