### PR TITLE
Source salesforce: handle japanese characters

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/oncall/issues/454
Do not decode response when writing to file since the chunk can start/end right in the middle of a 2/3/4 byte sequence which represents a single character thus makes text unreadable

### CODE REVIEW

**Comment by davydov-d** [comment]
hey @Nakachi-S 
if you dont mind I have created this PR based on [yours](https://github.com/airbytehq/airbyte/pull/16684) but also added changes that would make all the tests pass

**Comment by koconder** [comment]
@davydov-d cant see where this code is different from the original PR?

**Comment by davydov-d** [comment]
> @davydov-d cant see where this code is different from the original PR?

@koconder it differs in the [source.py](https://github.com/airbytehq/airbyte/pull/17001/files#diff-1180da547d1ffa8dbd6c895174d912b0023e3ccfce51920fab55913a0629baa8) file but tests keep on failing so I will go on working on the PR

**Review by bazarnov — APPROVED** [review]

**Review by vincentkoc — APPROVED** [review]
LGTM

**Pull request merged**
