### PR TITLE
✨Source Commcare: Migrate Python CDK to Low-code CDK

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
*Migrating Source Commcare to Low-Code CDK*
Closes airbytehq/airbyte-internal-issues#2027

## How
*Developed using (Configuration Based Source) low-code CDK*

## Recommended reading order
1. `spec.yaml`
2. `manifest.yaml`
3. `schemas/*`

## 🚨 User Impact 🚨
- No breaking changes, migration to low-code

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [x] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

</details>

### CODE REVIEW

**Comment by btkcodedev** [comment]
For the reviewers, I have got the credentials but it requires professional plan for all the streams
Thus so far, I've managed to migrate to low code with general template and setting up streams, but can't test it

Please test it with airbyte's own credentials and point out if any changes are required :)

**Comment by siddhant3030** [comment]
I can test this. We're using commcare heavily. If someone can assign this to me I can do this with our credentials. Also, the old connector is pushed by me.

**Comment by sh4sh** [comment]
Hey @siddhant3030 thanks for offering to test, it would be awesome if you could post the test results for this PR. We're still in the process of getting creds so it would make things faster. Let me know if I can help

**Comment by siddhant3030** [comment]
So we've built Commcare differently. So Commcare has a case that has a lot of Forms and all the forms we have as a stream and currently,

 This connector makes only 3 streams for application, case, and forms which is also not working. but I don't think this approach will work because for any Commcare user because of the complexity of the api's

Screenshot 2023-08-30 at 10 40 13 PM

**Comment by siddhant3030** [comment]
@sh4sh to give you an idea here we have different forms which is from same same case

Screenshot 2023-08-30 at 10 56 35 PM

Screenshot 2023-08-30 at 10 56 43 PM

**Comment by btkcodedev** [comment]
@siddhant3030 It's not built with connector builder UI, as each stream is coded individually, connector builder can't read it correctly I think.
Could you please share the creds with @sh4sh So that they can check whether it works :)
Thank you in advance

**Comment by siddhant3030** [comment]
> @siddhant3030 It's not built with connector builder UI, as each stream is coded individually, connector builder can't read it correctly I think. Could you please share the creds with @sh4sh So that they can check whether it works :) Thank you in advance

@btkcodedev  hey. We won't be able to share the credentials for this because I was testing with the client data. We built this initially to support our use case but we'll have to find some other way

**Comment by btkcodedev** [comment]
@sh4sh Your thoughts please :)

**Comment by marcosmarxm** [comment]
Hello, and thank you so much for contributing to the project during the Hackathon. Due to the high complexity of the code migration, we still have a few contributions open. I'm sending this message to update you that this contribution will be added to the final points we're going to announce tomorrow. With that said, we ask for your help to continue the process and finish the review.

**Comment by btkcodedev** [comment]
Thank you @marcosmarxm

**Comment by sh4sh** [comment]
Since the current Commcare connector built with the Python CDK uses a dynamic schema, which isn't currently possible to implement with the low code framework, this pull request will be closed. In the future when it's possible to implement in low code, we can look at re-opening. Thanks for your efforts and sorry that we can't merge this.

**Pull request closed without merging**
