### PR TITLE
source-datadog: ensure inline schemas, updated cdk, poetry (where possible)

### PR DESCRIPTION
**Pull request by bleonard**
This was created from a set of automated scripts. In each case, not every update was needed for every connector, but overall here is what happened:

 * `auto-schema update -s all description`: added descriptions to json and inline schemas
 * `connector-code migrate_to_yaml -c all --type source`: migrates json schemas to connectors with a manifest
 * `airbyte-ci connectors --name=<all modified connectors from above> migrate_to_base_image`: makes sure that each is using a base docker image and updates docs
 * `airbyte-ci connectors --name=<all modified connectors from above> migrate-to-poetry`: moves connectors not already using poetry to do so and updates documentation
 * `airbyte-ci connectors --name=<all modified connectors from above> up_to_date`: updated the CDK to newer (0.80.0) version

The version number and changelogs were also bumped using the `connector-code pulls` command.

### CODE REVIEW

**Comment by bleonard** [comment]
I can't figure out what's going on with this. There's a schema validation, but it's validating the `$parameters` 
The YAML looks right. @girarda @lmossman ?

```
cls = <class 'jsonschema.validators.Draft7Validator'>
schema = {'$parameters': {'name': 'monitors', 'path': 'monitor', 'primary_key': 'id'}, '$schema': 'http://json-schema.org/draft-07/schema#', 'additionalProperties': True, 'name': 'monitors', ...}
format_checker = <FormatChecker checkers=['date', 'email', 'idn-email', 'idn-hostname', 'ipv4', 'ipv6', 'regex']>
```

**Comment by lmossman** [comment]
@bleonard this seems like the same issue we discussed on slack [here](https://airbytehq-team.slack.com/archives/C02TL38U5L7/p1713478386846199) right? Inline schema loader not playing nicely with `$parameters` when on an old CDK version

**Comment by bleonard** [comment]
I think this is different. For the most part the other issue went away when I upgraded to `0.80.0`

**Comment by lmossman** [comment]
Oh, I saw that the manifest.yaml in this PR still had `version: "0.29.0"` so I thought it hadn't been upgraded

**Pull request closed without merging**
