### PR TITLE
✨source-outreach: add additional stream `sequenceSteps`

### PR DESCRIPTION
**Pull request by joel-olazagasti**
Apologies for the huge diff in the JSON files, my autoformatter caught them before I noticed it. I ran the connector formatting tool, but it doesn't seem like it caught the JSON files. 

## What
Added a new stream `sequenceSteps` to Outreach source connector. Additionally, did a small documentation cleanup where multiple streams had the same copy/paste documentation.

## How
Added new stream config, added stream to source in `source.py`

## Recommended reading order
1. `sequence_steps.json`
2. `source.py`
3. tests and docs

## 🚨 User Impact 🚨
No breaking changes, just a new feature. Bumped up one minor version
 
## Pre-merge Actions

- **Community member?** ✅Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- ✅ Integration test:
image
- ✅Unit test:
image

- ❌ Connector version is set to `0.0.1`
    -  ❌ `Dockerfile` has version `0.0.1`
  
Is this relevant to new connectors only? I kept the 0.3.0 semantic version bump for now

- Documentation updated
    - ✅ Connector's `README.md`

    -  ✅`docs/integrations/source/outreach.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - ❌ `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@joel-olazagasti quick look the contribution looks good. Can you solve the conflict? These files were deleted yesterday. I'll add your contribution to next sprint (start next week)

**Comment by joel-olazagasti** [comment]
@marcosmarxm conflict is resolved! Thanks for the quick response.

**Review by marcosmarxm — APPROVED** [review]
Thanks @joel-olazagasti

**Pull request merged**
