### PR TITLE
Set debezium num retries property to zero

### PR DESCRIPTION
**Pull request by rodireich**
Configure debezium num retires to 0 (defaults to -1 which is unlimited)

### CODE REVIEW

**Review by akashkulk — APPROVED** [review]
Good catch - totally missed this!! Ahh I tried finding the documentation for debezium.retries but it isn't in any of the connector specific docs. 

Could you link it in the PR?

**Comment by rodireich** [comment]
Look for `errors.max.retries` in https://debezium.io/documentation/reference/stable/development/engine.html

**Pull request merged**
