### PR TITLE
Low code cdk to beta

### LINKED ISSUE #22330: [Low-Code CDK] Review low-code to beta changes once all changes have been merged
## What

We have had a lot of changes added into the `low_code_cdk_to_beta` branch. We review PRs before they merge into that branch, but we should collectively review things one more time to ensure that this is validated and smoothly released. It is a little hard to point this since it could be a lot or a little work.

We should also prepare a post to socialize to both our open source contributors and the global logic teams with the following information
- We have promoted the low-code CDK language to beta
- What this means for developers and the next steps they should take
- A list of all the language changes that are being made
- Examples of each change

## Acceptance Criteria
The following checks should be made against the latest version:
- [x] Sanity check that `spec` works for all low-code connectors: Run `./gradlew validateSourceYamlManifest`
- [x] Verify that we can construct all the stream components from a manifest (we can temporarily insert `self.streams({}` into spec to easily test this in the previous script mentioned
- [x] Verify 3 connectors that use `incremental_sync` successfully sync and are emitting state messages. Validated: [ `source-greenhouse`, `source-close-com`, `source-zenloop` ]
- [x] Verify that a connector implementing substream `partition_router` works for at least 2 connectors. Validated: [ `source-braze`, `source-close-com`, `source-square` ]
- [x] Verify that a connector implement list `partition_router` works for at least 1 connector. Validated: [ ~~source-google-pagespeed-insights~~ `source-survey-sparrow` ]
- [x] Verify a connector that inherits a field like `url_base` for a paginator from another node. Validated: [ `source-tempo` ]
- [x] Verify that unit tests pass for all declarative connectors
- [x] Verify CAT tests pass for at least 8 connectors. Validated: 
  - `source-chartmogul` - All passed
  - `source-delighted` - All passed
  - `source-greenhouse` - All passed
  - `source-monday` - All passed
  - `source-posthog` - `master` currently has 2 failing incremental tests, same for this branch
  - `source-prestashop` - Local runs of `master` and the branch fail the CAT schema validation. I checked the data types and records by running syncs on both and the data matches. Suspicious why it passes on the CI run, but this might be an issue w/ my local env since the same thing happens on master
  - `source-square` - All passed
  - `source-tempo` - All passed
  - `source-woocommerce` - All passed
  - `source-zenloop` - All passed
- [x] Verify that a connector built from the local CDK can be run successfully in a local instance of Airbyte [ `source-greenhouse` full refresh + incremental tested ]
- [x] Verify that a connector that there are no low-code manifests that contain the following fields or components: `request_options_provider`, `$options`, `*ref(`, `JsonSchema`, `stream_cursor_field`, `checkpoint_interval`, `inject_into: path`, `stream_slicer`
- [x] Verify that the following component + field do not exist: `DpathExtractor.field_pointer`, `DefaultPaginator.url_base`, `SimpleRetriever.primary_key`, `SimpleRetriever.name`, `HttpRequester.name`
- [ ] A post is written and communicated to the community and to the GL teams about the list of changes.

### PR DESCRIPTION
**Pull request by brianjlai**
Closes https://github.com/airbytehq/airbyte/issues/22330

## What
This includes all the breaking changes to the low-code language in order to promote the language to Beta. @clnoll @maxi297 and @brianjlai have implemented various parts of the breaking changes. @lmossman @flash1293 implemented the front end changes. This PR consolidates all of them so that we can do a single release of the airbyte-cdk.

## How
This PR includes the following:
- The breaking changes that have been reviewed and committed from other sub branches.
- Changes to the connector builder UI to support the changes to the language. They have been reviewed and committed from sub branches.
-  Migrating of all existing connectors to incorporate the aforementioned breaking changes (migration scripts are included but should have already been run)
- Documentation updates
- 

This GH issue summarizes the set of breaking changes pretty well: https://github.com/airbytehq/airbyte/issues/21926

## Recommended reading order
It will be a bit hard to actually read through this given the size of the changes. They have already been reviewed as part of other PRs. One thing to note is that we have a set of acceptance criteria for final certifications before we merge this into master: https://github.com/airbytehq/airbyte/issues/22330 . Once we have pulled the latest code and confirmed them, we will merge this code and publish a new version of the CDK.

### CODE REVIEW

**Comment by brianjlai** [comment]
Changes have been verified according to the checklist laid out in https://github.com/airbytehq/airbyte/issues/22330

**Review by sherifnada — APPROVED** [review]

**Comment by brianjlai** [comment]
welp, I'm getting `Error: client_payload is too large.` from the job dispatch. Saw on slack that this is a known issue. Gonna merge this in the old fashioned way since I'm blocked on the new way. For posterity:


approve-reason="Merges changes prior to a CDK publish. Should have no impact on the platform and revert for a connector is straightforward"

**Pull request merged**
