### PR TITLE
Fix snowflake destination spec

### PR DESCRIPTION
**Pull request by flash1293**
## What
According to https://docs.airbyte.com/connector-development/connector-specification-reference/#using-oneof there needs to be a shared `const` property if `oneOf` is used in the spec. The snowflake destination does not follow this rule - the simple password case is not featuring the `auth_type` prop.

This PR fixes the spec.

### CODE REVIEW

**Comment by flash1293** [comment]
Currently failing due to https://github.com/airbytehq/airbyte/issues/20559

**Review by lmossman — APPROVED** [review]
LGTM

**Comment by edgao** [comment]
(also submitted https://github.com/airbytehq/airbyte/issues/20660 for us to consume this new property)

**Pull request merged**
