### PR TITLE
New Source Salesforce Marketingcloud Singer

### PR DESCRIPTION
**Pull request by schlattk**
## What
Adding a new source for salesforce marketing cloud utilising an existing singer source. This connector has already been running successfully for several months
(this is a cleaned up version of #9080)

## How
Using an existing Singer source (tap-exacttarget).
https://github.com/singer-io/tap-exacttarget 

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>

#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
Screenshot 2021-12-23 at 10 59 58

#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>Screenshot 2021-12-23 at 10 59 58

### CODE REVIEW

**Comment by harshithmullapudi** [comment]
Thanks a lot. I will check with the team and credentials and merge it

**Comment by igrankova** [comment]
Hi, @harshithmullapudi, I'm trying to get the CI creds for the Marketing Cloud, but received the answer from the support: Marketing Cloud does not have a sandbox environment like Salesforce.
I asked @schlattk for help in one of the connected issues where he told that maybe he can help with the account (#4933) and waiting for the response. 
For now we only have dev and sandbox accounts, but we can't access Marketing Cloud from those accounts. I tried to investigate whether I can use API endpoints, but I can't without the account.

**Comment by harshithmullapudi** [comment]
Thanks for the update @igrankova.

**Comment by joaquin-orono** [comment]
Hello, i have an account to validate salesforce marketing, the credentials are from one customer of mine so i have to check by myself because i can't share with nobody, how can I use this connector to test?

**Comment by harshithmullapudi** [comment]
Hey @joaquin-orono you can also fork @schlattk and use it.

@igrankova is there any update on this?

**Comment by igrankova** [comment]
> @igrankova is there any update on this?
Now Andy is negotiating with SFMC according the discount for a sandbox account, still in progress.

**Comment by notsaman** [comment]
Big fan of this, cheers. The fork worked well enough for me, so would be cool to see this in an official release.

**Comment by igrankova** [comment]
@harshithmullapudi, today we have a call with FSCM team about the sandbox.

**Comment by joaquin-orono** [comment]
Hello @schlattk! Quick question, as i saw the connector is working, if I follow your instructions https://github.com/schlattk/airbyte/tree/mc_singer_source_squashed/airbyte-integrations/connectors/source-sf-marketingcloud-singer
It can work in my environment, i have airbyte 0.36.6-alpha?

Thanks a lot!

**Comment by schlattk** [comment]
Hi, yes it should be, I am on a lower airbyte version but that shouldn't be
a problem.

**Comment by joaquin-orono** [comment]
> 

Hello @schlattk, sorry for my unknowledge about how to make run salesforce marketing connector, maybe i have not all knowledges to make it run, can you explain a bit more  the steps before to the requirements, i'm trying to clone the url shared before but i get an error, maybe i'm doing something wrong. Thanks a lot!

**Comment by schlattk** [comment]
Hi @joaquin-orono If you fork the repo and follow the instructions in the readme (of sf-marketingcloud-singer source) and run docker you should be able to see this source as one of your connectors.

**Comment by igrankova** [comment]
Please, find creds for the SFMC sandbox in the LastPass: Salesforce Marketing Cloud sandbox

**Comment by harshithmullapudi** [comment]
@irynakruk were you able to open Installed Packages? I need to create client_id and client_secret https://developer.salesforce.com/docs/marketing/marketing-cloud/guide/mc-dev-setup.html

**Comment by igrankova** [comment]
> @irynakruk were you able to open Installed Packages? I need to create client_id and client_secret https://developer.salesforce.com/docs/marketing/marketing-cloud/guide/mc-dev-setup.html

Hi, @harshithmullapudi, I see that I can't login anymore, it looks like my verification app is not connected to the system and the codes are not valid anymore so I can't look to this problem. Maybe we can manage a call or something to find the way to solve this.

**Comment by igrankova** [comment]
@harshithmullapudi I've reinstalled the app. I'm is SFMC, looking to our issue. I'll let you know.

**Comment by igrankova** [comment]
@harshithmullapudi I've created a package Airbyte Cloud with read scopes.
image
Unfortunately it doesn't support local redirect URIs, but all the https URIs I've added. Let me know if I can do something else for you.
I guess you'll have to reinstall your authentication app once again to get the access to the instance.

**Comment by alafanechere** [comment]
@harshithmullapudi could you please update @schlattk with the latest status on this PR?

**Comment by harshithmullapudi** [comment]
Hey sorry lost this PR in my mess. I am off till Wednesday and will pick this back by EOW.

**Comment by harshithmullapudi** [comment]
@irynakruk I am able to get the credentials and authorize using the integration tests. Can you help me understand which of the stream has data in the account?

**Comment by igrankova** [comment]
Hi, @harshithmullapudi, I need some time to investigate.

**Comment by ycherniaiev** [comment]
@harshithmullapudi I filled streams as much as i can. Please let me know if it is enough

**Comment by schlattk** [comment]
Hi @harshithmullapudi let me know if I can assist in any way getting this over the line

**Comment by harshithmullapudi** [comment]
Hey @schlattk sure let me try running tests again and see if it passes otherwise will reach out to you. Thanks a lot 😃

**Comment by harshithmullapudi** [comment]
Screenshot 2022-07-15 at 1 44 30 PM
@schlattk I am getting this error while running tests locally with 3.9 version of python. Is there some fix?

**Comment by schlattk** [comment]
ok I'll try and replicate and see whether I can find a solution

**Comment by harshithmullapudi** [comment]
@schlattk Hey I have spent a lot of time trying to get the tests working but there are a lot of moving pieces. To run the tests we need to  **Make the whole source work with python 3.9** which we need to fix?

1. Problem with suds-judo installation with 3.9 - https://github.com/salesforce-marketingcloud/FuelSDK-Python/pull/138
2. Fixing that is we will also have to update the dependency in tap-exacttarget
3. Even then we have a dependency in singer-helper json-schema which is colliding with the airbyte-cdk which can't be resolved.

Ideally solution i could see is to push the docker image and then add to out source_definitions

cc: @marcosmarxm @jerri-airbyte

**Comment by igrankova** [comment]
I see the notification that the authenticator now works on the other hardware. Iryna GrankovaSystem Business Analyst (Unblocker)GlobalLogic Inc. and its affiliates at1741 Technology Drive, Suite 400, San Jose, CA 95110, USAwww.globallogic.com+380636306253 From: Harshith MullapudiSent: 24 травня 2022 р. 11:54To: airbytehq/airbyteCc: Iryna Grankova; MentionSubject: Re: [airbytehq/airbyte] New Source Salesforce Marketingcloud Singer (PR ***@***.*** I installed the app on my mobile to log in and check. I am uninstalling it now can you check if you can install i.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by igrankova** [comment]
Don’t know what’s wrong.  Iryna GrankovaSystem Business Analyst (Unblocker)GlobalLogic Inc. and its affiliates at1741 Technology Drive, Suite 400, San Jose, CA 95110, USAwww.globallogic.com+380636306253 From: Harshith MullapudiSent: 24 травня 2022 р. 11:54To: airbytehq/airbyteCc: Iryna Grankova; MentionSubject: Re: [airbytehq/airbyte] New Source Salesforce Marketingcloud Singer (PR ***@***.*** I installed the app on my mobile to log in and check. I am uninstalling it now can you check if you can install i.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by marcosmarxm** [comment]
Hello :wave:, first thank you for this amazing contribution. 

We really appreciate the effort you've made to improve the project.
We ask you patience for the code review. Last month our team was focused on Hacktoberfest event and that probably left some PR without the proper feedback. And this week, due to the Thanksgiving US Holiday, most our team is out of office with their families. Another important piece of information why code won't be merge this week is: as a safety measure the core team has decided to freeze merging code to main branch to keep the release stable. Next week we'll return to you with the proper code review and update the status of your contribution.

If you have any questions feel free to send me a message in Slack!
Thanks!

**Comment by marcosmarxm** [comment]
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

**Comment by sherifnada** [comment]
closing since we are no longer accepting Singer-based connectors into the Airbyte monorepo

**Pull request closed without merging**
