### PR TITLE
remove un-used update/delete custom connector api

### PR DESCRIPTION
**Pull request by xiaohansong**
## What
https://github.com/airbytehq/airbyte/issues/19670
https://github.com/airbytehq/airbyte-cloud/issues/3642

remove un-used update/delete custom connector api and create connector api

### CODE REVIEW

**Comment by pmossman** [comment]
@marcelopio I know you mentioned working on CLI custom connectors in an issue comment earlier, can you verify that this PR is ok with your changes as well?

**Review by pmossman — APPROVED** [review]
Looks good to me, assuming builds pass!

**Comment by xiaohansong** [comment]
@pmossman Took another pass and I think it should be straightforward to remove the creation in the same PR - PTAL if you got a chance!

And for @marcelopio's PR - I commented in your PR, the update path needs to be changed

**Comment by marcelopio** [comment]
> @marcelopio I know you mentioned working on CLI custom connectors in an issue comment earlier, can you verify that this PR is ok with your changes as well?

It is ok for me. Actually this solves a doubt I was having if I should use custom or not. 

Now I just have the question if I should manage connectors version for non custom connectors, but that is to be discussed on my PR. Thanks!

**Comment by pmossman** [comment]
@xiaohansong looks like there may be some broken tests in the build after removing those endpoints, maybe some tests need to be converted to the `createCustom` version of the endpoint?

**Comment by josephkmh** [comment]
Just confirming that we are not using any of these endpoints on the frontend anymore 👍

**Pull request merged**
