### PR TITLE
CockroachDb source: Add only encrypted version for the connector

### LINKED ISSUE #6717: Create a secure-only CockroachDb source
## Tell us about the problem you're trying to solve
We want to create secure-only versions of connectors that can be used in the Airbyte cloud. The idea is that these connectors inherently prevent certain insecure connections such as connecting to a database over the public internet without encryption.

## Describe the solution you’d like
The acceptance criteria for this ticket is: 

- [ ] Create a new connector `source-<name>-strict-encrypt` based on the current connector
- [ ] modify the connector's spec to hide any options which allow the user to disable TLS
- [ ] change the connector to enable TLS by default if the TLS option is not specified
- [ ] update connector documentation
- [ ] Encrypted connections are tested as part of either a custom integration test or acceptance test. Where possible, test it using a test container. If that's impossible and it must be tested on a real DB instance, create a DB instance in AWS ideally using terraform (but if TF is too hard just create it manually and make a ticket to encode it in TF)
- [ ] Create a PR 

## Implementation hints
[This PR](https://github.com/airbytehq/airbyte/pull/6362) contains an example of modifying a DB to only allow using TLS connections. 

**Note**: to perform this task for any given connector, it must first support TLS as described in #5628

### PR DESCRIPTION
**Pull request by DoNotPanicUA**
Add strict SSL source version for the CockroachDb source

### CODE REVIEW

**Review by alexandr-shegeda — APPROVED** [review]
LGTM. we can proceed with publishing and merge without airbyte review

**Comment by DoNotPanicUA** [comment]
/publish connector=connectors/source-cockroachdb-strict-encrypt

**Pull request merged**
