### PR TITLE
🐛 Source Paypal Transaction: add missing required fields

### PR DESCRIPTION
**Pull request by joeykmh**
## What
Related to https://github.com/airbytehq/oncall/issues/2064

This PR marks Client ID, Client secret and Refresh token as required fields for the Paypal Transaction source.

image

### CODE REVIEW

**Comment by josephkmh** [comment]
@sherifnada looks like tests are failing? I ran into the same failures when I attempted to fix the backwards compat locally. I'm not really sure how to proceed here (but would be interested to learn).

**Comment by octavia-squidington-iii** [comment]
##  source-paypal-transaction test report (commit [`af162c8050`](https://github.com/airbytehq/airbyte/pull/26352/commits/af162c805098eb7b535402cfa8ec68f6fcb04def)) - ❌

⏲️  Total pipeline duration: 02mn42s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-paypal-transaction/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-paypal-transaction docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/joey_paypal-transactions-required-fields/1688171354/af162c805098eb7b535402cfa8ec68f6fcb04def/source-paypal-transaction/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Comment by octavia-squidington-iii** [comment]
##  source-paypal-transaction test report (commit [`97b2ce2c78`](https://github.com/airbytehq/airbyte/pull/26352/commits/97b2ce2c78d3ae7624effca810437ed16ecc6a9c)) - ❌

⏲️  Total pipeline duration: 01mn29s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-paypal-transaction/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-paypal-transaction docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/joey_paypal-transactions-required-fields/1688172300/97b2ce2c78d3ae7624effca810437ed16ecc6a9c/source-paypal-transaction/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Comment by octavia-squidington-iii** [comment]
##  source-paypal-transaction test report (commit [`0832047cc4`](https://github.com/airbytehq/airbyte/pull/26352/commits/0832047cc494f2e957b6242107440a43895a3bc8)) - ❌

⏲️  Total pipeline duration: 02mn21s 

| Step                                                                             | Result   |
|:---------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-paypal-transaction/metadata.yaml | ✅        |
| Connector version semver check                                                   | ✅        |
| Connector version increment check                                                | ✅        |
| QA checks                                                                        | ✅        |
| Code format checks                                                               | ✅        |
| Connector package install                                                        | ✅        |
| Build source-paypal-transaction docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                       | ✅        |
| Acceptance tests                                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/joey_paypal-transactions-required-fields/1688173730/0832047cc494f2e957b6242107440a43895a3bc8/source-paypal-transaction/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Pull request closed without merging**
