### PR TITLE
fix(source-declarative-manifest): allow Python 3.10

### PR DESCRIPTION
**Pull request by natikgadzhi**
## What

This bumps Python to allow 3.10 in source declarative manifest. And updates it's test deps while we're at it, so Dependabot stops screaming at us.

This should unblock CDK update to 4.0.1 for source declarative manifest. Right now, [it can't install](https://github.com/airbytehq/airbyte/actions/runs/10148997178/job/28063145085#step:5:907).

### CODE REVIEW

**Review by aldogonzalez8 — APPROVED** [review]
APPROVED

**Comment by natikgadzhi** [comment]
Ah well, lockfile incoming

**Comment by natikgadzhi** [comment]
Alright, the static check wants a CHANGELOG entry, but I don't know if source-declarative-manifest has one — no docs file? /cc @girarda 

If this is fine, just merge this manually and move one

**Review by artem1205 — APPROVED** [review]

**Comment by girarda** [comment]
there's indeed no changelog for source-declarative-manifest. :shipit:

**Review by girarda — APPROVED** [review]

**Pull request merged**
