### PR TITLE
🐛Source Facebook Marketing: user_tos_accepted is an object

### LINKED ISSUE #11800: Source Facebook Marketing: user_tos_accepted is an object, not number in the schema
## Environment
* **Airbyte version**:  N/A
* **OS Version / Instance**: macOS
* **Deployment**: Docker
* **Source Connector and version**: source-facebook-marketing@[0.2.42](https://hub.docker.com/layers/source-facebook-marketing/airbyte/source-facebook-marketing/0.2.42/images/sha256-3a6fe9f6f7bd5274de946008d6a4788bc893b0c9d1f1660c13805871c0f3029d?context=explore)
* **Destination Connector and version**: N/A
* **Severity**: High
* **Step where error happened**: Sync Job

## Current Behavior
In the current [`ad_account` schema definition](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/schemas/ad_account.json), `user_tos_accepted` is defined as `number,null`. This leads to an error when reading data:

```
Encountered an exception while reading stream ad_account
TypeError: float() argument must be a string or a number, not 'dict'
```

## Expected Behavior
if you look at the examples [here](https://developers.facebook.com/docs/marketing-api/audiences/reference/custom-audience-terms-of-service) at the end of the page, it's an object:

Also see Facebook Business SDK's definition of this field:

* https://github.com/facebook/facebook-python-business-sdk/blob/main/facebook_business/adobjects/adaccount.py#L3964
* Which comes from this specification: https://github.com/facebook/facebook-business-sdk-codegen/blob/2c2c48483d5b33e2759aca68d7ed92dc9b1775ea/api_specs/specs/AdAccount.json#L3730-L3731

And there should be no errors.

## Logs
<details>
<summary>LOG</summary> 

```
Encountered an exception while reading stream ad_account^
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 119, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 159, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 249, in _read_full_refresh
    yield self._as_airbyte_record(configured_stream.stream.name, record)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 281, in _as_airbyte_record
    transformer.transform(data, schema)  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/utils/transform.py", line 172, in transform
    for e in normalizer.iter_errors(record):
  File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/utils/transform.py", line 152, in normalizator
    instance[k] = self.__normalize(instance[k], subschema)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/utils/transform.py", line 79, in __normalize
    original_item = self.default_convert(original_item, subschema)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/utils/transform.py", line 110, in default_convert
    return float(original_item)
TypeError: float() argument must be a string or a number, not 'dict'"
```

</details>

## Steps to Reproduce
1. Run an Airbyte connector on a Facebook account with Custom TOS

## Are you willing to submit a PR?
Opened PR: https://github.com/airbytehq/airbyte/pull/11801

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537093687) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by mdibaiee**
## What
Fixes `user_tos_accepted` to be an object, see issue #11800 

## How
Define `user_tos_accepted` with the same schema as `tos_accepted`

## :rotating_light: User Impact :rotating_light:
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the :rotating_light::rotating_light: emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter
* [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
* [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
* [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
* [ ] Code reviews completed
* [ ] Documentation updated
  * [ ] Connector's `README.md`
  * [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
  * [ ] `docs/SUMMARY.md`
  * [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
  * [ ] `docs/integrations/README.md`
  * [ ] `airbyte-integrations/builds.md`
* [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter
If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

* [ ] Create a non-forked branch based on this PR and test the below items on it
* [ ] Build is successful
* [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
* [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
* [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
* [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
* [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter
* [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
* [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
* [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
* [ ] Code reviews completed
* [ ] Documentation updated
  * [ ] Connector's `README.md`
  * [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
  * [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
* [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter
If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

* [ ] Create a non-forked branch based on this PR and test the below items on it
* [ ] Build is successful
* [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
* [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
* [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
* [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
* [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

* [ ] Issue acceptance criteria met
* [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
* [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
* [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
* [ ] Documentation which references the generator is updated as needed

</details>

## Tests
<details><summary><strong>Unit</strong></summary>

_Put your unit tests output here._

</details>

<details><summary><strong>Integration</strong></summary>

_Put your integration tests output here._

</details>

<details><summary><strong>Acceptance</strong></summary>

_Put your acceptance tests output here._

</details>

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537093205) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by alafanechere** [comment]
Thank you @mdibaiee for this contribution. I will need a review from the connector team as this connector is GA. Could you please also bump the version of this connector in the Dockerfile and update the changelog if `facebook-marketing.md`?

**Comment by mdibaiee** [comment]
@alafanechere bumped the version and added changelog entry 👍🏽

**Review by lazebnyi — APPROVED** [review]

**Comment by alafanechere** [comment]
/publish connector=connectors/source-facebook-marketing auto-bump-version=false

**Comment by alafanechere** [comment]
/publish connector=connectors/source-facebook-marketing auto-bump-version=false

**Pull request merged**
