### PR TITLE
test

### PR DESCRIPTION
**Pull request by rodireich**
## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by rodireich** [comment]
I still don't see this rollout on the connector rollout manager on retool.
@clnoll  Would this happen because:
```
  registryOverrides:
    cloud:
      enabled: false
```
?

The connector was not released yet.

**Comment by clnoll** [comment]
@rodireich yes it needs to be enabled on cloud. cc @alafanechere any chance there's a manual workaround for this? It doesn't need to be permanently in the cloud registry, just long enough to create an actor definition version and rollout entry.

**Comment by alafanechere** [comment]
@clnoll @rodireich the connector should be enabled on cloud to end up in the cloud registry.
You should first enable the main version, then the rc version. Release candidates are nested under the main versions in the registry, so a main version must be declared.

**Comment by clnoll** [comment]
@rodireich I think another solution to this would be to use the same actor definition version, instead of giving your connector a new one. From talking to you last week, it sounded like that would be possible, right?

**Comment by alafanechere** [comment]
@rodireich a approach could be to:
On `source-mysql-v2/metadata.yaml`:
* Continue disabling the `source-mysql-v2` in cloud / oss and use a rc suffix in its version
On `source-mysql/metadata.yaml`:
* Declare a new version with a RC suffix which matches the one set in `source-mysql`
* Set `releases.rolloutConfiguration.enableProgressiveRollout` to `true`
* Set `registryOverrides.dockerRegistry` and set it to `airbyte/source-mysql-v2`

I think that should work

**Comment by rodireich** [comment]
OK
I'll float the idea of using the same actor id for mysql-v2. Maybe there's some ramifications I'm not aware of.
As we discussed this is stretching the use case you built this tool for, so I didn't expect this to work without bumps.
Thank you Catherine and Augustin for the deep dive. I appreciate the help

**Comment by rodireich** [comment]
Hi
@theyueli  and I discussed this and wanted to see how we find a way to make this work.
Since we're migrating a major db source with a lot of usage, we would really benefit from being able to gradually rolling out.

Would that work If we change the definition id of mysql-v2 to match the existing mysql?

Ideally we should have a new mysql-v2 connector,
But it sounds like as a fallback scenario, if nothing else works we can just replace the existing source-mysql project with mysql-v2 classes and make it a version change rather than a new connector. 

Should I try with changing a definition id? is there a way you think I can roll out to my test workspace without publishing ?
thanks

**Comment by rodireich** [comment]
We will replace the existing v1 source-mysql with the new project to make it easier to gradually roll out.
I'm closing this for a new PR.

**Pull request closed without merging**
