### PR TITLE
🐛 Source Zendesk Support: stream sla_policies fix data type error (events.value)

### LINKED ISSUE #24052: Source Zendesk Support: stream `sla_policies` schema data type error (events.value)
## Environment
- **Airbyte version**:  0.42.0
- **OS Version / Instance**: macOS (M1)
- **Deployment**: Docker
- **Source Connector and version**: Zendesk Support 0.2.25 
- **Destination Connector and version**: S3 0.3.21
- **Step where error happened**: Sync job

## Current Behavior

The Sync for stream `sla_policies` fails because of a schema error.

`Caused by: org.apache.avro.AvroTypeException: Could not evaluate union, field events is expected to be one of these: NULL, ARRAY. If this is a complex type, check if offending field (path: events.value) adheres to schema: [{id=13000000127067, type=Create, value=Jogador, field_name=sla_policy}, {id=13636900000007, type=ChatStartedEvent, value={visitor_id=13000000-1ErlfSQLZcAqrc8, chat_id=0000.10000580.TYTbg7GsD5czx, chat_start_url=https://chat-fakesubdomain.zendesk.com/hc/pt-br/p/chat, tags=[MyTag], backend=chat, history=[], webpath=[], channel=chat}, attachments=[]}, {id=10000005700005, type=Comment, author_id=13500000008123, body=Conversa com Daiane`

## Expected Behavior

According to the [Zendesk documentation](https://developer.zendesk.com/documentation/ticketing/reference-guides/ticket-audit-events-reference/), the value field could be a `string`, `array`, or `object` depending on the event type.
So `sla_policies` field `events.value` schema should be able to handle `string`, `array`, or `object`.

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Yes.

### PR DESCRIPTION
**Pull request by brunofaustino**
## What

Resolves #24052

## How

Changed `sla_policies` schema field `events.value` added `object` type.

Notice that it keeps `oneOf` because of: [#15036](https://github.com/airbytehq/airbyte/pull/15036#pullrequestreview-1052930200).

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@brunofaustino can you check test failures?

**Review by marcosmarxm — APPROVED** [review]

**Review by bazarnov — APPROVED** [review]

**Comment by marcosmarxm** [comment]
Currently the Zendesk Support connector is break on master. I'm waiting to fix our tests to continue the merge process of this contribution.

**Comment by bazarnov** [comment]
> Currently the Zendesk Support connector is break on master. I'm waiting to fix our tests to continue the merge process of this contribution.

I'm about  to fix this now: https://github.com/airbytehq/airbyte/pull/25619

**Pull request merged**
