### PR TITLE
Update connector certification table with new sources

### PR DESCRIPTION
**Pull request by avaidyanatha**
## Main Changes
- Adds missing sources from the certification table

### CODE REVIEW

**Comment by avaidyanatha** [comment]
@sherifnada So the GitHub, GitLab, and Twilio connectors are now Airbyte native. Are any of them `Certified` now?

**Comment by sherifnada** [comment]
Nope still in beta since they were just released

**Review by sherifnada — APPROVED** [review]
thanks for catching it, added this to the checklist so it's not missed again

**Comment by avaidyanatha** [comment]
> Nope still in beta since they were just released

> thanks for catching it, added this to the checklist so it's not missed again

Cool, thanks for the heads up. and no prob :)

**Pull request merged**
