### PR TITLE
SAT: make all tests mandatory when `test_strictness_level` == `high`

### LINKED ISSUE #18219: SAT[strict_mode]: validate that all `tests` are enabled
## Tell us about the problem you're trying to solve
All the tests declared in `acceptance-test-config.yml`, under the `tests` field are optional:
```python
class TestConfig(BaseConfig):
    spec: Optional[List[SpecTestConfig]] = Field(description="TODO")
    connection: Optional[List[ConnectionTestConfig]] = Field(description="TODO")
    discovery: Optional[List[DiscoveryTestConfig]] = Field(description="TODO")
    basic_read: Optional[List[BasicReadTestConfig]] = Field(description="TODO")
    full_refresh: Optional[List[FullRefreshConfig]] = Field(description="TODO")
    incremental: Optional[List[IncrementalConfig]] = Field(description="TODO")
``` 

**I want all these tests not to be optional when `strict_mode = strict`.**

## Describe the solution you’d like
When `strict_mode = strict` I want all the test configuration to be declared, a pydantic.ValidationError should be raised otherwise. If a specific test can be configured on the connector it can be bypassed by declaring a `bypass_reason`.
 
```yaml 
connector_image: airbyte/source-pokeapi:dev
strict_mode: strict
tests:
  spec:
    bypass_reason: "Explain the reason why spec tests are disabled"
  connection:
    - config_path: "integration_tests/config.json"
      status: "succeed"
  discovery:
    - config_path: "integration_tests/config.json"
  basic_read:
    - config_path: "integration_tests/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
  full_refresh:
    - config_path: "integration_tests/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
  incremental:
    bypass_reason: "Explain the reason why spec tests are disabled"
```

**If a `bypass_reason` is filled SAT should log a warning.**

### PR DESCRIPTION
**Pull request by alafanechere**
## What
Closes #18219
We want to make all acceptance tests mandatory when `test_strictness_level` == `high`.
A `bypass_reason` must be filled in to skip a mandatory test.

## How
* Set `MANDATORY_FOR_TEST_STRICTNESS_LEVELS = [Config.TestStrictnessLevel.high]` class attribute on `BaseTest`
* Change test discovery logic in `pytest_generate_tests`:  this is where the strictness level from the test configuration is compared against the `MANDATORY_FOR_TEST_STRICTNESS_LEVELS` for each discovered test class.
* Parametrize, skip or fail a test after this comparison:
  * We parametrize a test if `tests` were found in the configuration
  * We skip a test if `bypass_reason` was filled in
  * We fail a test if no `tests` nor `bypass_reason`
  
## Recommended reading order
0. https://github.com/airbytehq/airbyte/blob/50a7ecc32c1d00315101e8a86bf5de03df2d9efa/docs/connector-development/testing-connectors/source-acceptance-tests-reference.md#L237
1. https://github.com/airbytehq/airbyte/blob/26062adce192e022036ba5804c2897a1f56e5add/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/base.py#L21
2. https://github.com/airbytehq/airbyte/blob/26062adce192e022036ba5804c2897a1f56e5add/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/plugin.py#L68
3. https://github.com/airbytehq/airbyte/blob/26062adce192e022036ba5804c2897a1f56e5add/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/plugin.py#L47
4. https://github.com/airbytehq/airbyte/blob/26062adce192e022036ba5804c2897a1f56e5add/airbyte-integrations/bases/source-acceptance-test/unit_tests/test_plugin.py#L24

## 🚨 User Impact 🚨
No direct impact while `test_strictness_level` is not set on a connector: `test_strictness_level` defaults to `low` and no enforcement exists on this strictness level.

### CODE REVIEW

**Comment by alafanechere** [comment]
☝️ Expect `source-pokeapi` tests to fail when `test_strictness_level` == `high` because it's missing `incremental` and `spec` tests.

**Comment by alafanechere** [comment]
☝️ Expect source-pokeapi tests to succeed when test_strictness_level == high because it now has  `bypass_reason` for `spec` and `incremental` tests

**Comment by alafanechere** [comment]
☝️ Test on a GA connector without `test_strictness_level` set, for sanity and to ensure I did not break anything in the discovery logic.

**Review by evantahler — APPROVED** [review]
Nice! Good docs and the way things appear in the /slash commands on Github is great

**Comment by alafanechere** [comment]
/publish connector=bases/source-acceptance-test auto-bump-version=false

**Pull request merged**
