### PR TITLE
Separate platform and connector testcontainer versions

### PR DESCRIPTION
**Pull request by jdpgrailsdev**
## What
* Address issues with incompatible testcontainer versions for connector tests

## How
* Separate versions used for testcontainer libraries between connectors and platform

## Recommended reading order
1. `deps.toml`
2. All other `build.gradle` updates to use separated library versions

## 🚨 User Impact 🚨
N/A

## Tests

<details><summary><strong>Unit</strong></summary>

* All platform and base connector unit tests pass

</details>

### CODE REVIEW

**Review by etsybaev — CHANGES_REQUESTED** [review]
Just checked some of containers. Have no idea why, but we still have the same errors that we started having after that initial commit related to testcontainers.  Here are logs examples for source-mysql and destination-mariadb. These still fail like it was without adding "RuntimeClasspath" to build.gradle file.

UPD: it also seems that other connectors still work much slower than it was at the very beginning (before any global changes to testcntainers)
Selection_287


Selection_285

Selection_286

**Comment by jdpgrailsdev** [comment]
@etsybaev It looks like some of the failures are unrelated (like the Oracle ones).  However, I think I see what part of the issue is:  there are still newer transitive dependencies leaking in.  I am going to attempt to fix that also, which should address the issues.

**Comment by jdpgrailsdev** [comment]
PR has been updated with the transitive dependency fix.  I can confirm that the connectors are now using the versions from before the original PR.  From what I can tell, there are still some unrelated integration test failures/slowness that is not related to testcontainers.

**Review by alexandr-shegeda — APPROVED** [review]
checked locally, tests are passing with the current fix. thank you @jdpgrailsdev

**Pull request merged**
