### PR TITLE
Source/Destination TiDB: add connection attribute

### PR DESCRIPTION
**Pull request by Daemonxiao**
## What
For Source and Destination TiDB, I add a  connection attribute parameter in them.
```
program_name:airbyte
```
This is for the Airbyte TiDB connector to identify itself and help developers better adapt the application.
For more information about connection attributes, see [Performance Schema Connection Attribute Tables](https://dev.mysql.com/doc/refman/8.0/en/performance-schema-connection-attribute-tables.html).

## How
*Describe the solution*
Add `"connectionAttributes", "program_name:airbyte"` to `DEFAULT_JDBC_PARAMETERS`.
## Recommended reading order
1. `TiDBDestination.java`
2. `TiDBSource.java`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Review by subodh1810 — APPROVED** [review]
Hey @Daemonxiao thank you for your contribution. The change looks fine, approved once the test command and build is green.

**Comment by subodh1810** [comment]
Tagging @airbytehq/airbyte-support-eng team for the follow up

**Comment by subodh1810** [comment]
@natalyjazzviolin

**Comment by Daemonxiao** [comment]
Is this pr ready to be merged? Or is there anything else I can do?

**Review by grishick — APPROVED** [review]

**Comment by marcosmarxm** [comment]
I'd this to my to-do list and publish the contribution

**Comment by evantahler** [comment]
I've closed this pull request, as we won't be able to review it in a timely manner.  

For the moment, Airbyte is focused on improving the quality and performance of our existing connectors and the Airbyte platform itself.  We owe you a prompt response, and unfortunately that is a 'no' to this change, at this time.  We are also rapidly changing the Airbyte Protocol and our connector interfaces, which means that this PR will quickly become stale.

In the future, we will focus on growing our connector catalog and features from OSS contributors like yourself.  Please be sure to join our slack community so that you'll be able to learn when we are ready for more contributions like this again.

Learn more here: https://airbyte.com/blog/upgrading-our-community-pull-requests-experience

**Pull request closed without merging**
