### PR TITLE
🎉Source Sendgrid: increase unit test coverage at least 90%

### LINKED ISSUE #16331: Source Sendgrid: increase unit test coverage at least 90%
## Tell us about the problem you're trying to solve
Need to improve unit test coverage at least 90%

### PR DESCRIPTION
**Pull request by lazebnyi**
## What
https://github.com/airbytehq/airbyte/issues/16331

## How
Added unit tests

## Pre-merge Checklist
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
</details>

### CODE REVIEW

**Review by bazarnov — APPROVED** [review]
I think the `requests_mock` should be the part of `setup.py`, since unit_tests require it.
https://github.com/airbytehq/airbyte/blob/lazebnyi/source-sendgrid-coverage-unittest/airbyte-integrations/connectors/source-sendgrid/setup.py

**Review by grubberr — APPROVED** [review]

**Pull request merged**
