### PR TITLE
auto merge published connector PRs

### PR DESCRIPTION
**Pull request by sherifnada**
## What
Once a connector is successfully published, we want to close the PR. If the publish command fails, we want a slack notification. This will allow a more seamless publishing process.

### CODE REVIEW

**Review by michel-tricot — APPROVED** [review]

**Comment by michel-tricot** [comment]
Can you just confirm that the merge is guarded?

**Comment by sherifnada** [comment]
@michel-tricot yup, it is not possible to merge without having write access to the repo (can elevate to admin if we want as well).

**Comment by sherifnada** [comment]
for example @sherifnada2 is an impostor without write access. He can't use the `/publish` command.

**Pull request merged**
