### PR TITLE
Make error more descriptive in case of no encryption state

### LINKED ISSUE #16664: Improve user experience for cloud strict encrypt connector when configuring unsecured connection
## Tell us about the problem you're trying to solve
The strict encrypt postgres and mysql connectors correctly fail configuration check if the connection is effectively not guaranteed to be always encrypted (e.g with No Tunnel and with ssl set to "preferred").
Currently an error saying "Unsecured connection not allowed" is shown.

Improve user experience to reduce support calls from cloud customers.

## Describe the solution you’d like
We can add a more informative message. Suggested: "If you do not have SSH tunneling set up, please use one of these SSL modes:….".
In addition, if spec UI allows we can apply form validation and mark setting as red, similarly to how a missing host or database name is handled:
Screen Shot 2022-09-13 at 1 15 55 PM
This can provide visual guidance to users.
Need to see if spec allows creating a logic based on both tunnel and ssl setting.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

### PR DESCRIPTION
**Pull request by rodireich**
## What
Improve error wording:
Screen Shot 2022-09-27 at 10 27 53 PM

### CODE REVIEW

**Comment by rodireich** [comment]
test connector=connectors/source-postgres-strict-encrypt

**Review by edgao — APPROVED** [review]

**Comment by rodireich** [comment]
/publish connector=connectors/source-postgres,connectors/source-mysql,connectors/destination-postgres

**Comment by rodireich** [comment]
/publish connector=connectors/source-postgres-strict-encrypt,connectors/source-mysql-strict-encrypt,connectors/destination-postgres-strict-encrypt auto-bump-version=false

**Comment by rodireich** [comment]
/publish connector=connectors/source-postgres,connectors/source-mysql,connectors/destination-postgres run-tests=false

**Pull request merged**
