### PR TITLE
CDK: Fix regression in `_checkpoint_state` arg

### PR DESCRIPTION
**Pull request by grubberr**
Signed-off-by: Sergey Chvalyuk <grubberr@gmail.com>

## What
Fix incorrect use of `self._checkpoint_state`
we need to pass `stream_state` because `stream_instance.state` can be undefined

### CODE REVIEW

**Review by sherifnada — COMMENTED** [review]
@grubberr can you edit the PR description to include a description of the problem, an example, and why this code change fixes it?

**Comment by edgao** [comment]
@sherifnada I think the context is https://github.com/airbytehq/oncall/issues/466

I don't think I can competently review this PR, I have basically no experience with CDK internals; removing my review request. LMK if there's anything I can do to help get this deployed though.

couple drive-by comments while I'm here:
* is the plan to publish source-amplitude as part of this pr (and/or in a followup pr)?
* is it possible to add a unit test to catch whatever the problem was?

**Review by lazebnyi — APPROVED** [review]

**Review by davydov-d — APPROVED** [review]

**Review by bazarnov — APPROVED** [review]

**Review by sherifnada — APPROVED** [review]

**Comment by grubberr** [comment]
FYI @sherifnada @lazebnyi @bazarnov @davydov-d @roman-yermilov-gl

New pydantic released `1.10.0` and not it's behaviour changed for `const` keyword

```python
from pydantic import BaseModel, Field

class Choice1(BaseModel):
    field = Field("option1", const=True)
```

`pydantic==1.9.2`

```
{
    "properties": {
        "field": {"title": "Field", "const": "option1", "type": "string"}
    }
}
```

`pydantic==1.10.0`

```
{
    "properties": {
        "field": {"title": "Field", "default": "option1", "const": "option1", "type": "string"}
    }
}
```


Maybe we would need to return `default` keyword to common properties in spec again

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py#L122

**Comment by davydov-d** [comment]
> FYI @sherifnada @lazebnyi @bazarnov @davydov-d @roman-yermilov-gl
> 
> New pydantic released `1.10.0` and it's behaviour changed for `const` keyword
> 
> ```python
> from pydantic import BaseModel, Field
> 
> class Choice1(BaseModel):
>     field = Field("option1", const=True)
> ```
> 
> `pydantic==1.9.2`
> 
> ```
> {
>     "properties": {
>         "field": {"title": "Field", "const": "option1", "type": "string"}
>     }
> }
> ```
> 
> `pydantic==1.10.0`
> 
> ```
> {
>     "properties": {
>         "field": {"title": "Field", "default": "option1", "const": "option1", "type": "string"}
>     }
> }
> ```
> 
> Maybe we would need to return `default` keyword to common properties in spec again
> 
> https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py#L122

As an option we could pin pydantic version not to change/during the change will be made to all the models in the connectors

**Review by davydov-d — APPROVED** [review]

**Comment by sherifnada** [comment]
Yeah we can’t upgrade pydantic or it will cause issues.

**Comment by grubberr** [comment]
https://github.com/airbytehq/airbyte/pull/16172

**Comment by grubberr** [comment]
@sherifnada I have pinned `pydantic~=1.9.2`
we can put this PR https://github.com/airbytehq/airbyte/pull/16172 on-hold until we decide how to be with new pydantic

**Review by sherifnada — APPROVED** [review]

**Review by brianjlai — APPROVED** [review]

**Pull request merged**
