### PR TITLE
✨Source Aws Cloudtrail: Migrate Python CDK to Low-code CDK

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
*Migrating Source Aws Cloudtrail to Low-Code CDK*
Closes airbytehq/airbyte-internal-issues#7042

## How
*Developed using (Configuration Based Source) low-code CDK*

## Recommended reading order
1. `spec.yaml`
2. `manifest.yaml`
3. `schemas/*`

## Tests

<details open><summary><strong>Integration & Acceptance</strong></summary>

 - Test sucessfull
 
image

</details>

## 🚨 User Impact 🚨
- Spec Breaking changes, migration to low-code

### CODE REVIEW

**Comment by btkcodedev** [comment]
Inline Schema ✅
Poetry lock file ✅
Breaking change referred in metadata ✅
Add migration.md docs file ✅
Docs updated ✅
Incremental Sync :white_check_mark: 
Formatted :white_check_mark: 

`airbyte-ci test` All pass state:
Results:
image

**Comment by btkcodedev** [comment]
Marking PR as ready to merge

**Review by lazebnyi — CHANGES_REQUESTED** [review]
My testing with the regression test tool leads to the following conclusion:

-  In check connections phase connector have called urls with different region. Reason - `aws_region_name` is not configurable and it hardcoded to `us-east-1`
-  Record count is not correct on `management_events` streams, possible reason can be that in new implementation present filter with `LookupAttributes`. 
-  Record schemas are different for `EventTime` field , but it is expected as wrong type was in old schema.
-  There's indeed a breaking change on `management_events` stream as the field type have changed.

**Comment by btkcodedev** [comment]
The region is hardcoded as the other regions us-west cannot be used while using Rest endpoints,the previous connector was using boto3 client for creating sessions, it was changed to custom Rest API approach,
Thus the API URL could only use US-east region

**Comment by lazebnyi** [comment]
> The region is hardcoded as the other regions us-west cannot be used while using Rest endpoints,the previous connector was using boto3 client for creating sessions, it was changed to custom Rest API approach, The Aws documentation is very poor regarding this, Other regions were tested as API base URL but not found working correctly. Thus the API URL could only use US-east region

What do you mean when you say that it is not working properly for the REST API approach? I have used `us-west-2` for your implementation, with the `LookupAttributes` filter deleted, and it is working as expected.

**Comment by btkcodedev** [comment]
Oh I haven't tried with filter deleted 😅, thanks for the info, I'll fix the comments
🙇

**Comment by btkcodedev** [comment]
@lazebnyi Thanks for the info about the filter, I've removed it, 
Currently the CI is getting timeout due to the high amount of record fetch with incremental sync, 
image


There is a need to change the Start_Date in config to the current date to limit the records to pass the CI
Thanks!

**Comment by lazebnyi** [comment]
> There is a need to change the Start_Date in config to the today's date to limit the records to pass the CI
> Thanks!

@btkcodedev is today's date 17/04/2024 ?

**Comment by btkcodedev** [comment]
@lazebnyi The current date 25/04/2024 to fetch minimal records

**Comment by btkcodedev** [comment]
@lazebnyi, The connector is always getting timeout due to the high amount of records, Do you have any idea how to resolve this?
adding a filter or something

**Comment by btkcodedev** [comment]
Connector is working perfectly, only problem is high amount of records

**Comment by natikgadzhi** [comment]
> The region is hardcoded as the other regions us-west cannot be used while using Rest endpoints,the previous connector was using boto3 client for creating sessions, it was changed to custom Rest API approach

If it needs `boto3`, perhaps we should move that to be a file-based source instead? 

If using REST limits the connector to be available for just one region, that's bad and not what we want.

**Comment by btkcodedev** [comment]
No the problem is solved, it works on any regions, the problem here is its getting timed out as there are very high amount of records @natikgadzhi

**Comment by tolik0** [comment]
@btkcodedev The acceptance tests fail with timeout because the connector no longer limits the number of records during the tests. We need to find a new way to limit records.

**Comment by btkcodedev** [comment]
Yes okay, I will look into it

**Comment by btkcodedev** [comment]
I've added a new filtering capability and sent credentials via slack, hope that does the job

**Comment by btkcodedev** [comment]
I've updated the connector to take the default start date at the current date and sent the config to Daniel Jablonski.
Waiting for an update

**Review by tolik0 — APPROVED** [review]

**Comment by btkcodedev** [comment]
Finally!!!!
CI greeeen :white_check_mark: 

image

**Comment by btkcodedev** [comment]
image

Thanks @tolik0 
@natikgadzhi, Please merge if everything is fine

**Comment by tolik0** [comment]
@btkcodedev Please update the docs with the new default `start_date`.

**Comment by btkcodedev** [comment]
> @btkcodedev Please update the docs with the new default `start_date`.

Done

**Pull request merged**
