### PR TITLE
source-blogger contribution from bala-ceg

### LINKED ISSUE #48101: [New-Connector-request] Blogger
### Topic

New Topic

### Relevant information

**Topic**
This is a suggestion to create a connector for Blogger using the UI Connector Builder. The website for the connector is https://developers.google.com/blogger/docs/3.0/using

**Relevant information**
No response

### PR DESCRIPTION
**Pull request by bala-ceg**
## What

This PR adds a new connector for source Blogger (source-blogger).

Contributor-provided connector description:

Google Blogger is a free blogging platform by Google that allows users to create and manage their own blogs with ease. It offers customizable templates, user-friendly tools, and integration with other Google services, making it simple to publish content and reach a wide audience. 
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `client_id` | `string` | Client ID.  |  |
| `client_secret` | `string` | Client secret.  |  |
| `client_refresh_token` | `string` | Refresh token.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| users | id | DefaultPaginator | ✅ |  ❌  |
| blogs | id | DefaultPaginator | ✅ |  ❌  |
| posts |  | DefaultPaginator | ✅ |  ❌  |
| pages | id | DefaultPaginator | ✅ |  ❌  |
| comments | id | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by marcosmarxm** [comment]
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

**Comment by bala-ceg** [comment]
@marcosmarxm facing the same error, can you please help me with it
Screenshot 2024-11-08 at 11 23 16 AM

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Missing comments and pages.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Also include icon and couple more data points to test paginatgion.

**Comment by marcosmarxm** [comment]
Make sure changes are done by Nov Tue 12

**Comment by bala-ceg** [comment]
Hi @marcosmarxm ,
I have added the icon.svg, 2 streams - comments & pages, remove the hardcorded value of blog id and post id. Please review the connector , thanks!

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
