### PR TITLE
source-s3: delete integration tests using minio

### PR DESCRIPTION
**Pull request by alafanechere**
## What
More details in https://github.com/airbytehq/airbyte/issues/26907
TLDR: minio tests are hard to run in the context of Dagger and I'm challenging the usefulness of this tests. I'm removing this integration test so that this connector can be properly tested in the new Connectors CI with Dagger.

## How
* Remove the `test_big_file` integration test.

### CODE REVIEW

**Comment by alafanechere** [comment]
You can see in the CI checks lists that the CI tests with dagger passed.

**Review by evantahler — APPROVED** [review]
Fine with me.

Tagging @clnoll as an FYI, as she's thinking about a CDK for file-based sources... maybe some shared tooling for testing both big and small files is a good idea.

**Review by davydov-d — APPROVED** [review]

**Comment by clnoll** [comment]
Thanks @evantahler. Removing the test makes sense to me. The file-based source CDK will have tests for large files.

**Comment by alafanechere** [comment]
Relates to #25053

**Pull request merged**
