### PR TITLE
🎉 New Source: Datastax Astra

### PR DESCRIPTION
**Pull request by anomnaco**
Creating a source connector to read data from Datastax Astra's new JSON API. Requires python cdk because of the need to dynamically generate JSONSchema for tables since the JSON API is a document store and can have arbitrary schema.

### CODE REVIEW

**Comment by hc33brackles** [comment]
@flash1293 - we have updated this PR to reflect the changes you suggested on the Airbyte Destination PR you've been reviewing for us.

**Comment by hc33brackles** [comment]
Hi @marcosmarxm - for a little extra context here, this AstraDB source is a managed Cassandra provider - quite similar to the source you have for Apache Cassandra in function. Apologies if this is already info you have :-)

**Comment by marcosmarxm** [comment]
> Hi @marcosmarxm - for a little extra context here, this AstraDB source is a managed Cassandra provider - quite similar to the source you have for Apache Cassandra in function. Apologies if this is already info you have :-)

Thanks for the info, Cassandra is a destination using the Java JDBC base class.

**Comment by natikgadzhi** [comment]
@aaronsteers we have astra already, right? Cool to close this?

**Pull request closed without merging**
