### PR TITLE
✨Source Zendesk Support: New Stream - Topics

### LINKED ISSUE #16889: Source Zendesk Support: new stream Topics
## Tell us about the problem you're trying to solve
A [Topic](https://developer.zendesk.com/api-reference/help_center/help-center-api/topics/) represents a collection of community posts on a subject. 

[Allowed for:](https://developer.zendesk.com/api-reference/help_center/help-center-api/topics/#allowed-for)
- Agents
- End users
- Anonymous users

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
Closes #16889

## Enhancement
New streams: 

- Topics

## Recommended reading order
1. `source_zendesk_support/source.py`
2. `source_zendesk_support/streams.py`
3.  `source_zendesk_support/schemas/*`

## 🚨 User Impact 🚨
No breaking changes

## Pre-merge Checklist
<details open><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter [Yes]

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Issue acceptance criteria met
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)
- [x] Documentation which references the generator is updated as needed
+

### CODE REVIEW

**Review by darynaishchenko — CHANGES_REQUESTED** [review]
could you add expected_records for this stream?

**Comment by btkcodedev** [comment]
@darynaishchenko Added expected_records

**Comment by darynaishchenko** [comment]
@btkcodedev could you please fix AT, incremental sync test [failed](https://github.com/airbytehq/airbyte/pull/28143#issuecomment-1630476555)

**Comment by btkcodedev** [comment]
@darynaishchenko Sorry I don't have access to google cloud, But my local is showing up with incremental sync as passed,
Could you run it again

**Comment by darynaishchenko** [comment]
> @darynaishchenko Sorry I don't have access to google cloud, But my local is showing up with incremental sync as passed, Could you suggest some changes

ok, I will take a look

**Comment by bmcgilli** [comment]
@darynaishchenko can you follow up on this? I think they are waiting for your response to check the test

**Review by darynaishchenko — APPROVED** [review]

**Pull request merged**
