### PR TITLE
S3 and GCS connector license to Elv2

### PR DESCRIPTION
**Pull request by evantahler**
See https://github.com/airbytehq/airbyte/issues/27724

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-gcs test report (commit [`c77597f7ac`](https://github.com/airbytehq/airbyte/pull/27725/commits/c77597f7ac2a85ea2bb8af5cf24c29a175d6773a)) - ✅

⏲️  Total pipeline duration: 250 seconds

| Step                                                              | Result   |
|:------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-gcs/metadata.yaml | ✅        |
| Connector version semver check                                    | ✅        |
| Connector version increment check                                 | ✅        |
| QA checks                                                         | ✅        |
| Code format checks                                                | ✅        |
| Connector package install                                         | ✅        |
| Build source-gcs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                        | ✅        |
| Acceptance tests                                                  | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-gcs-s3/1687819534/c77597f7ac2a85ea2bb8af5cf24c29a175d6773a/source-gcs/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gcs test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-gcs test report (commit [`c77597f7ac`](https://github.com/airbytehq/airbyte/pull/27725/commits/c77597f7ac2a85ea2bb8af5cf24c29a175d6773a)) - ✅

⏲️  Total pipeline duration: 930 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-gcs/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ✅        |
| QA checks                                                              | ✅        |
| Build connector tar                                                    | ✅        |
| Build destination-gcs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Integration tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-gcs-s3/1687819534/c77597f7ac2a85ea2bb8af5cf24c29a175d6773a/destination-gcs/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-gcs test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`c77597f7ac`](https://github.com/airbytehq/airbyte/pull/27725/commits/c77597f7ac2a85ea2bb8af5cf24c29a175d6773a)) - ✅

⏲️  Total pipeline duration: 1151 seconds

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-gcs-s3/1687819534/c77597f7ac2a85ea2bb8af5cf24c29a175d6773a/source-s3/3.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-s3 test report (commit [`c77597f7ac`](https://github.com/airbytehq/airbyte/pull/27725/commits/c77597f7ac2a85ea2bb8af5cf24c29a175d6773a)) - ✅

⏲️  Total pipeline duration: 777 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-s3/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Build connector tar                                                   | ✅        |
| Build destination-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-gcs-s3/1687819534/c77597f7ac2a85ea2bb8af5cf24c29a175d6773a/destination-s3/0.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-s3 test
```

**Comment by octavia-approvington** [comment]
What are we doing again? <br/> merge and squash

**Review by octavia-approvington — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-gcs test report (commit [`ad00b9778f`](https://github.com/airbytehq/airbyte/pull/27725/commits/ad00b9778f33bad940efd44da322b1adabbbf42d)) - ❌

⏲️  Total pipeline duration: 206 seconds

| Step                                                              | Result   |
|:------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-gcs/metadata.yaml | ✅        |
| Connector version semver check                                    | ✅        |
| Connector version increment check                                 | ❌        |
| QA checks                                                         | ✅        |
| Code format checks                                                | ✅        |
| Connector package install                                         | ✅        |
| Build source-gcs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                        | ✅        |
| Acceptance tests                                                  | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-gcs-s3/1687822251/ad00b9778f33bad940efd44da322b1adabbbf42d/source-gcs/0.2.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-gcs test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-gcs test report (commit [`ad00b9778f`](https://github.com/airbytehq/airbyte/pull/27725/commits/ad00b9778f33bad940efd44da322b1adabbbf42d)) - ❌

⏲️  Total pipeline duration: 877 seconds

| Step                                                                   | Result   |
|:-----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-gcs/metadata.yaml | ✅        |
| Connector version semver check                                         | ✅        |
| Connector version increment check                                      | ❌        |
| QA checks                                                              | ✅        |
| Build connector tar                                                    | ✅        |
| Build destination-gcs docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                             | ✅        |
| Integration tests                                                      | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-gcs-s3/1687822251/ad00b9778f33bad940efd44da322b1adabbbf42d/destination-gcs/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-gcs test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`ad00b9778f`](https://github.com/airbytehq/airbyte/pull/27725/commits/ad00b9778f33bad940efd44da322b1adabbbf42d)) - ❌

⏲️  Total pipeline duration: 1083 seconds

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ❌        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-gcs-s3/1687822251/ad00b9778f33bad940efd44da322b1adabbbf42d/source-s3/3.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-s3 test report (commit [`ad00b9778f`](https://github.com/airbytehq/airbyte/pull/27725/commits/ad00b9778f33bad940efd44da322b1adabbbf42d)) - ❌

⏲️  Total pipeline duration: 781 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-s3/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ❌        |
| QA checks                                                             | ✅        |
| Build connector tar                                                   | ✅        |
| Build destination-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_elv2-gcs-s3/1687822251/ad00b9778f33bad940efd44da322b1adabbbf42d/destination-s3/0.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-s3 test
```

**Pull request merged**
