### PR TITLE
Remove black + isort from global pyproject.toml

### PR DESCRIPTION
**Pull request by natikgadzhi**
## What

This top PR removes black and isort from `pyproject.toml` as they're replaced with Ruff. 

~~Since this is "top of the stack", it includes the actual formatting and the switch to use ruff in airbyte-ci format (I think?)~~

This PR will be merged into the PR that's applying actual formatting —we should probably merge that one first as it's a one-off crazy amount of file change that is the most challenging to review. We should YOLO it.

## How

Three PRs on the stack are supposed to be:
1. use `ruff` in `airbyte-ci format`
2. manually ran `ruff format .`
3. this PR: remove `black` and `isort`. 
4. Next PR — remove mentions of black and isort configs in subdirectories, and remove black and isort dev dependencies in our projects, replace them with ruff if they wish to have formatter in their deps.

## Can this PR be safely reverted and rolled back?
- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by natikgadzhi** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/37521?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#37521** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/37521?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#37520** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/37520?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#37519** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/37519?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @natikgadzhi and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by aaronsteers — APPROVED** [review]
YOLO 🚢 it! 
🚀

**Review by alafanechere — COMMENTED** [review]
This PR is not just "removing black and isort form pyprojec.toml" , it also applied some formatting rules (ruff ones i believe).
I expected the new formatting to be applied in https://github.com/airbytehq/airbyte/pull/37520

**Comment by natikgadzhi** [comment]
@alafanechere yeah that is graphite fucking things up for me. I won't merge this as is, of course.

**Pull request closed without merging**
