### PR TITLE
destination-s3: Add stringify option for nested objects in JSON Lines output

### PR DESCRIPTION
**Pull request by quazi-h**
## What
*When creating JSON Lines output using the S3 connector, nested JSON objects are not being escaped as strings, causing issues downstream when attempting to query the data in the object.*

## How
*We have added a utility that will serialize nested documents as strings in the output before they are written to the S3 destination. This can be enabled as an option for Output Format settings for JSONL serialization.*

## Recommended reading order
1. `docs/integrations/destinations/s3.md`
2. `airbyte-integrations/bases/base-java-s3/src/main/java/io/airbyte/integrations/destination/s3/S3DestinationConstants.java`
3. `airbyte-integrations/connectors/destination-s3/src/main/resources/spec.json`
4. `airbyte-integrations/bases/base-java-s3/src/main/java/io/airbyte/integrations/destination/s3/jsonl/S3JsonlFormatConfig.java`
5. `airbyte-integrations/bases/base-java-s3/src/main/java/io/airbyte/integrations/destination/s3/util/Stringify.java`
6. `airbyte-integrations/bases/base-java-s3/src/main/java/io/airbyte/integrations/destination/s3/jsonl/JsonLSerializedBuffer.java`
7. `airbyte-integrations/bases/base-java-s3/src/test/java/io/airbyte/integrations/destination/s3/jsonl/JsonLSerializedBufferTest.java`
8. `airbyte-integrations/bases/base-java-s3/src/test/java/io/airbyte/integrations/destination/s3/jsonl/S3JsonlFormatConfigTest.java`
9. `airbyte-integrations/bases/s3-destination-base-integration-test/src/main/java/io/airbyte/integrations/destination/s3/S3BaseJsonlDestinationAcceptanceTest.java`
10. `airbyte-integrations/bases/s3-destination-base-integration-test/src/main/java/io/airbyte/integrations/destination/s3/S3BaseJsonlGzipDestinationAcceptanceTest.java`
11. `airbyte-integrations/connectors/destination-s3/Dockerfile`
12. `airbyte-ci/connectors/metadata_service/orchestrator/tests/fixtures/cloud_registry.json`
13. `airbyte-ci/connectors/metadata_service/orchestrator/tests/fixtures/oss_registry.json`

## 🚨 User Impact 🚨
*This is a minor version change that adds a non-required parameter to the Destination-S3 connector spec.
The additional option will be visible in the connector settings under the "Output Format" options.
Users will have the option to use the required parameter in the future.
This should not affect any existing implementations of the S3 connector because the default setting for this option will be not stringifying nested objects - preserving existing functionality.*

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by quazi-h** [comment]
Hi @marcosmarxm, here is the first of the two PRs split from https://github.com/airbytehq/airbyte/pull/25769 for the Destination-S3 connector.

**Comment by marcosmarxm** [comment]
> Hi @marcosmarxm, here is the first of the two PRs split from #25769 for the Destination-S3 connector.

Can you link a Github Issue of what you're trying to solve?

**Comment by quazi-h** [comment]
> > Hi @marcosmarxm, here is the first of the two PRs split from #25769 for the Destination-S3 connector.
> 
> Can you link a Github Issue of what you're trying to solve?
I have created this new issue to detail the problem and what we are trying to achieve with these changes: https://github.com/airbytehq/airbyte/issues/27171

**Comment by marcosmarxm** [comment]
Hello @quazi-h because the change touches a GA destination connector I asked to destination team to review your contribution. Right now they're completely focus in the change to normalization and it can take some time to review your contribution.

**Comment by evantahler** [comment]
Hello! Thank you for this PR. This message is to let you know that it will be a while until we can review your work. We will get back to reviewing community PRs for the S3 destination in a few months.

Learn more here: https://airbyte.com/blog/upgrading-our-community-pull-requests-experience

**Pull request closed without merging**
