### PR TITLE
source-ruddr contribution from bishalbera

### LINKED ISSUE #47701: [Connector-Request] Ruddr
### Topic

This is a suggestion to create a connector for Ruddr using the UI Connector Builder. The site for this is https://www.ruddr.com/

### Relevant information

_No response_

### PR DESCRIPTION
**Pull request by bishalbera**
## What

This PR adds a new connector for source Ruddr (source-ruddr).

Contributor-provided connector description:

Ruddr connector enables seamless data synchronization from Ruddr to various data warehouses, lakes, and destinations. It simplifies data pipelines by extracting projects and analytics data, ensuring reliable and efficient data integration for real-time insights.
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_token` | `string` | API Token. API token to use. Generate it in the API Keys section of your Ruddr workspace settings. |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| clients | id | DefaultPaginator | ✅ |  ❌  |
| projects | id | DefaultPaginator | ✅ |  ❌  |
| project_members | id | DefaultPaginator | ✅ |  ❌  |
| project_tasks | id | DefaultPaginator | ✅ |  ❌  |
| expense_reports | id | DefaultPaginator | ✅ |  ❌  |
| expense_items | id | DefaultPaginator | ✅ |  ❌  |
| expense_categories | id | DefaultPaginator | ✅ |  ❌  |
| project_expense | id | DefaultPaginator | ✅ |  ❌  |
| project_budget_expenses | id | DefaultPaginator | ✅ |  ❌  |
| workspace members |  | DefaultPaginator | ✅ |  ❌  |
| opportunity_stages | id | DefaultPaginator | ✅ |  ❌  |
| invoices | id | DefaultPaginator | ✅ |  ❌  |
| holidays | id | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by marcosmarxm** [comment]
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

Make sure you have pagination properly working, the API doesn't have pagination please left a comment making my review easier.
Make sure have a square svg icon
Make sure credentials are valid.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Please use a more stable way to paginate:
image

Implement limit to all endpoints

✅ endpoints are ok

**Comment by marcosmarxm** [comment]
Please fix this by Monday Nov 11

**Comment by bishalbera** [comment]
@marcosmarxm fixed pagination

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
