### PR TITLE
Source google spreadsheets: fix error during listing sheets with diagram only

### LINKED ISSUE #2202: Source Google Spreadsheet: charts in a separate google sheet break syncing
## Expected Behavior
If a Google spreadsheet has two pages:

1. data
1. dashbaord

Airbyte should be able to sync data from the first page. 

## Current Behavior
Currently the second page prevents the sync from taking place.

## Airbyte Version
This happened about 1mo ago, but it doesn't look like there have been any changes that would impact this.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368091924107) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by midavadim**
## What
ERROR during sync of sheets with diagram only

{"type": "LOG", "log": {"level": "INFO", "message": "Starting syncing spreadsheet 1cec2856fH1qsMXysi1pwDT-a3f_ZZRo0dPvw7ZC3GW4"}}
Traceback (most recent call last):
  File "main_dev.py", line 33, in <module>
    launch(source, sys.argv[1:])
  File "/home/vratniuk/air/airbyte/airbyte-integrations/bases/base-python/base_python/entrypoint.py", line 121, in launch
    AirbyteEntrypoint(source).start(args)
  File "/home/vratniuk/air/airbyte/airbyte-integrations/bases/base-python/base_python/entrypoint.py", line 112, in start
    for message in generator:
  File "/home/vratniuk/air/airbyte/airbyte-integrations/connectors/source-google-sheets/google_sheets_source/google_sheets_source.py", line 132, in read
    sheet_row_counts = Helpers.get_sheet_row_count(client, spreadsheet_id)
  File "/home/vratniuk/air/airbyte/airbyte-integrations/connectors/source-google-sheets/google_sheets_source/helpers.py", line 173, in get_sheet_row_count
    return {sheet.properties.title: sheet.properties.gridProperties["rowCount"] for sheet in spreadsheet_metadata.sheets}
  File "/home/vratniuk/air/airbyte/airbyte-integrations/connectors/source-google-sheets/google_sheets_source/helpers.py", line 173, in <dictcomp>
    return {sheet.properties.title: sheet.properties.gridProperties["rowCount"] for sheet in spreadsheet_metadata.sheets}
AttributeError: 'SheetProperties' object has no attribute 'gridProperties'

## How
Filter our sheets with no 'gridProperties' attr

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by antixar — APPROVED** [review]

**Review by lazebnyi — APPROVED** [review]

**Review by bazarnov — APPROVED** [review]

**Review by Phlair — APPROVED** [review]
LGTM

Lines up as described in [Sheets API doc here](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/sheets#sheetproperties) to only grab relevant sheets 👍

**Pull request merged**
