### PR TITLE
Vector DBs: Set subtype correctly

### PR DESCRIPTION
**Pull request by flash1293**
## What

https://github.com/airbytehq/airbyte/pull/31521 added the `vectorstore` connector subtype - this PR rolls this out to all connectors fitting the type.

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  destination-weaviate test report (commit [`1388554ec9`](https://github.com/airbytehq/airbyte/pull/31647/commits/1388554ec9a62257d46910fae96330961dc9b537)) - ✅

⏲️  Total pipeline duration: 01mn51s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build destination-weaviate docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                           | ✅       |
| Integration tests                                                    | ✅       |
| Acceptance tests                                                     | ✅       |
| Check our base image is used                                         | ✅       |
| Code format checks                                                   | ✅       |
| Validate metadata for destination-weaviate                           | ✅       |
| Connector version semver check                                       | ✅       |
| QA checks                                                            | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/flash1293_vectorstore-metadata/1697797983/1388554ec9a62257d46910fae96330961dc9b537/destination-weaviate/0.2.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1388554ec9a62257d46910fae96330961dc9b537)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-weaviate test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-pinecone test report (commit [`1388554ec9`](https://github.com/airbytehq/airbyte/pull/31647/commits/1388554ec9a62257d46910fae96330961dc9b537)) - ✅

⏲️  Total pipeline duration: 02mn38s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build destination-pinecone docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                           | ✅       |
| Integration tests                                                    | ✅       |
| Acceptance tests                                                     | ✅       |
| Check our base image is used                                         | ✅       |
| Code format checks                                                   | ✅       |
| Validate metadata for destination-pinecone                           | ✅       |
| Connector version semver check                                       | ✅       |
| QA checks                                                            | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/flash1293_vectorstore-metadata/1697797983/1388554ec9a62257d46910fae96330961dc9b537/destination-pinecone/0.0.17/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1388554ec9a62257d46910fae96330961dc9b537)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-pinecone test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-milvus test report (commit [`1388554ec9`](https://github.com/airbytehq/airbyte/pull/31647/commits/1388554ec9a62257d46910fae96330961dc9b537)) - ✅

⏲️  Total pipeline duration: 02mn46s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build destination-milvus docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                         | ✅       |
| Integration tests                                                  | ✅       |
| Acceptance tests                                                   | ✅       |
| Check our base image is used                                       | ✅       |
| Code format checks                                                 | ✅       |
| Validate metadata for destination-milvus                           | ✅       |
| Connector version semver check                                     | ✅       |
| QA checks                                                          | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/flash1293_vectorstore-metadata/1697797983/1388554ec9a62257d46910fae96330961dc9b537/destination-milvus/0.0.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1388554ec9a62257d46910fae96330961dc9b537)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-milvus test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-qdrant test report (commit [`1388554ec9`](https://github.com/airbytehq/airbyte/pull/31647/commits/1388554ec9a62257d46910fae96330961dc9b537)) - ❌

⏲️  Total pipeline duration: 02mn49s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build destination-qdrant docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                         | ✅       |
| Check our base image is used                                       | ❌       |
| Code format checks                                                 | ✅       |
| Validate metadata for destination-qdrant                           | ✅       |
| Connector version semver check                                     | ✅       |
| QA checks                                                          | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/flash1293_vectorstore-metadata/1697797983/1388554ec9a62257d46910fae96330961dc9b537/destination-qdrant/0.0.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1388554ec9a62257d46910fae96330961dc9b537)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-qdrant test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-chroma test report (commit [`1388554ec9`](https://github.com/airbytehq/airbyte/pull/31647/commits/1388554ec9a62257d46910fae96330961dc9b537)) - ❌

⏲️  Total pipeline duration: 03mn03s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build destination-chroma docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                         | ✅       |
| Check our base image is used                                       | ❌       |
| Code format checks                                                 | ✅       |
| Validate metadata for destination-chroma                           | ✅       |
| Connector version semver check                                     | ✅       |
| QA checks                                                          | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/flash1293_vectorstore-metadata/1697797983/1388554ec9a62257d46910fae96330961dc9b537/destination-chroma/0.0.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:1388554ec9a62257d46910fae96330961dc9b537)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-chroma test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-qdrant test report (commit [`6fee2d3436`](https://github.com/airbytehq/airbyte/pull/31647/commits/6fee2d34363626523a603e2b451a0c313de945f1)) - ✅

⏲️  Total pipeline duration: 01mn30s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build destination-qdrant docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                         | ✅       |
| Code format checks                                                 | ✅       |
| Validate metadata for destination-qdrant                           | ✅       |
| Connector version semver check                                     | ✅       |
| QA checks                                                          | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/flash1293_vectorstore-metadata/1697807635/6fee2d34363626523a603e2b451a0c313de945f1/destination-qdrant/0.0.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6fee2d34363626523a603e2b451a0c313de945f1)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-qdrant test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-chroma test report (commit [`6fee2d3436`](https://github.com/airbytehq/airbyte/pull/31647/commits/6fee2d34363626523a603e2b451a0c313de945f1)) - ✅

⏲️  Total pipeline duration: 01mn32s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build destination-chroma docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                         | ✅       |
| Code format checks                                                 | ✅       |
| Validate metadata for destination-chroma                           | ✅       |
| Connector version semver check                                     | ✅       |
| QA checks                                                          | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/flash1293_vectorstore-metadata/1697807635/6fee2d34363626523a603e2b451a0c313de945f1/destination-chroma/0.0.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6fee2d34363626523a603e2b451a0c313de945f1)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-chroma test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-weaviate test report (commit [`6fee2d3436`](https://github.com/airbytehq/airbyte/pull/31647/commits/6fee2d34363626523a603e2b451a0c313de945f1)) - ✅

⏲️  Total pipeline duration: 02mn07s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build destination-weaviate docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                           | ✅       |
| Integration tests                                                    | ✅       |
| Acceptance tests                                                     | ✅       |
| Check our base image is used                                         | ✅       |
| Code format checks                                                   | ✅       |
| Validate metadata for destination-weaviate                           | ✅       |
| Connector version semver check                                       | ✅       |
| QA checks                                                            | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/flash1293_vectorstore-metadata/1697807635/6fee2d34363626523a603e2b451a0c313de945f1/destination-weaviate/0.2.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6fee2d34363626523a603e2b451a0c313de945f1)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-weaviate test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-pinecone test report (commit [`6fee2d3436`](https://github.com/airbytehq/airbyte/pull/31647/commits/6fee2d34363626523a603e2b451a0c313de945f1)) - ✅

⏲️  Total pipeline duration: 02mn16s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build destination-pinecone docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                           | ✅       |
| Integration tests                                                    | ✅       |
| Acceptance tests                                                     | ✅       |
| Check our base image is used                                         | ✅       |
| Code format checks                                                   | ✅       |
| Validate metadata for destination-pinecone                           | ✅       |
| Connector version semver check                                       | ✅       |
| QA checks                                                            | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/flash1293_vectorstore-metadata/1697807635/6fee2d34363626523a603e2b451a0c313de945f1/destination-pinecone/0.0.17/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6fee2d34363626523a603e2b451a0c313de945f1)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-pinecone test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-milvus test report (commit [`6fee2d3436`](https://github.com/airbytehq/airbyte/pull/31647/commits/6fee2d34363626523a603e2b451a0c313de945f1)) - ✅

⏲️  Total pipeline duration: 03mn18s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build destination-milvus docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                         | ✅       |
| Integration tests                                                  | ✅       |
| Acceptance tests                                                   | ✅       |
| Check our base image is used                                       | ✅       |
| Code format checks                                                 | ✅       |
| Validate metadata for destination-milvus                           | ✅       |
| Connector version semver check                                     | ✅       |
| QA checks                                                          | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/flash1293_vectorstore-metadata/1697807635/6fee2d34363626523a603e2b451a0c313de945f1/destination-milvus/0.0.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6fee2d34363626523a603e2b451a0c313de945f1)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-milvus test
```

**Review by aaronsteers — APPROVED** [review]
👍

**Pull request merged**
