### PR TITLE
:bug: Postgres Source: fixed unsupported date-time datatypes during incremental sync

### LINKED ISSUE #13380: Unparseable date with Postgres source connector 0.4.19
## Environment
- **Airbyte version**:  0.38.4-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Postgres 0.4.19
- **Destination Connector and version**: Snowflake 0.4.26
- **Step where error happened**: Sync job

## Current Behavior

Incremental syncs are failing after updating the Postgres connector to 0.4.19.

The timestamp format (cursor) went from being in the `2022-05-27T17:48:56.925922Z` format to `2022-05-31T20:23:494` in Snowflake, and cannot be parsed by the Postgres source connector.

## Expected Behavior

Timestamps with no timezone should be parsed by the Postgres source connector. 

## Logs

```
2022-06-01 15:20:40 [44msource[0m > 2022-06-01 15:20:39 [1;31mERROR[m i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.
2022-06-01 15:20:40 [44msource[0m > java.lang.RuntimeException: java.text.ParseException: Unparseable date: "2022-05-31T20:23:494"
2022-06-01 15:20:40 [44msource[0m > 	at io.airbyte.db.jdbc.AbstractJdbcCompatibleSourceOperations.setTimestamp(AbstractJdbcCompatibleSourceOperations.java:167) ~[io.airbyte.airbyte-db-lib-0.39.5-alpha.jar:?]
```

## Steps to Reproduce

1. Setup a Postgres source 0.4.19 with incremental sync + deduped history and Snowflake destination 0.4.26
2. Sync
3. Sync again: failure

## Are you willing to submit a PR?

No.

### LINKED ISSUE #13603: source-postgres: TIMESTAMP_WITH_TIMEZONE column can't be used as cursor
## Environment

- **Source Connector and version**: source-postgres 0.4.21
- **Step where error happened**:  Sync job

## Current Behavior
https://github.com/airbytehq/airbyte/pull/13166 enabled the source postgres connector to replicate `TIMESTAMP_WITH_TIMEZONE` columns. But user can't use this kind of column as a cursor for incremental sync because this type is not handled in `setStatementField` [here](https://github.com/airbytehq/airbyte/blob/b4e43c2dddcbfc9092ef93de6ee724a83f9bf478/airbyte-db/db-lib/src/main/java/io/airbyte/db/jdbc/JdbcSourceOperations.java#L64).
Leading to the following error:
```
2022-06-08 07:08:55 e[44msourcee[0m > java.lang.IllegalArgumentException: TIMESTAMP_WITH_TIMEZONE is not supported.
2022-06-08 07:08:55 e[44msourcee[0m > 	at io.airbyte.db.jdbc.JdbcSourceOperations.setStatementField(JdbcSourceOperations.java:86) ~[io.airbyte.airbyte-db-db-lib-0.39.13-alpha.jar:?]
```

## Expected Behavior
Users should be able to use a `TIMESTAMP_WITH_TIMEZONE` field for cursor in incremental read.

## Steps to Reproduce
1. Create a table with a `TIMESTAMP_WITH_TIMEZONE` column
2. Create an incremental sync using this column as a cursor
3. Run the sync

### PR DESCRIPTION
**Pull request by VitaliiMaltsev**
## What
This PR is related to [on-call issue](https://github.com/airbytehq/oncall/issues/267)

## How
Override date-time datatypes for PreparedStatement

## Recommended reading order
1. `PostgresSourceOperations.java`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by grishick** [comment]
Is there a test to verify the fix?

**Comment by VitaliiMaltsev** [comment]
> Is there a test to verify the fix?

@grishick I have updated the bunch of tests to use the **timestamptz** and **timetz** types in incremental sync. You can verify the fix with _incrementalTimestampCheck()_, _incrementalTimeTzCheck(_) and _incrementalTimestampTzCheck()_ tests

**Review by alexandr-shegeda — APPROVED** [review]
looks good

**Comment by grishick** [comment]
@VitaliiMaltsev thank for adding the tests. Correct me if I am wrong, but I think we are missing tests where `updated_at` field includes a non-zero time and is used as a cursor. E.g., a schema that looks like this
`CREATE TABLE tmp_table id INTEGER, name VARCHAR(200), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()` - which is  likely to be used by customers. I have tested this scenario manually locally, but I would like us to have an integration test that confirms it as well.

**Comment by VitaliiMaltsev** [comment]
> @VitaliiMaltsev thank for adding the tests. Correct me if I am wrong, but I think we are missing tests where `updated_at` field includes a non-zero time and is used as a cursor and where `updated_at` is a `timestamp` type.
> 
> E.g., we need a test for a schema that looks like this, uses `updated_at` as a cursor, and has test cases where cursor time is increased in addition to cursor date. I think currently, all test cases have time as `00:00:00Z`.
> 
> ```
> CREATE TABLE public.tmp_table (
>    id INTEGER, 
>    name VARCHAR(200), 
>    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
> );
> ```
> 
> we also need a similar test for a schema that has `timestamp` cursor field (not timestamptz). E.g:
> 
> ```
> CREATE TABLE public.tmp_table (
> 	id INTEGER,
> 	"name" varchar NULL,
> 	updated_at timestamp NULL
> );
> ```
> 
> ideally, we would also have similar cursor tests for all types of date and date/time fields that Postgres supports.

@grishick please take a look at the table structure that we use for tests https://github.com/airbytehq/airbyte/pull/13655/files#:~:text=).toLowerCase()%3B-,COLUMN_CLAUSE_WITH_PK,-%3D
Currently we have 4 columns for different date-time Postgres datatypes

_updated_at_ ==> **DATE**,
_wakeup_at_ ==> **TIMETZ**,
_last_visited_at_ ==> **TIMESTAMPTZ**, 
_last_comment_at_ ==> **TIMESTAMP**

and incrementalCursor tests cover all these 4 scenarios

_incrementalDateCheck()_ for **DATE** cursor,
_incrementalTimeTzCheck()_ for **TIMETZ** cursor ,
_incrementalTimestampTzCheck()_ for **TIMESTAMPTZ** cursor,
_incrementalTimestampTzCheck()_ for **TIMESTAMP** cursor

**Review by grishick — APPROVED** [review]

**Comment by grishick** [comment]
/publish connector=connectors/source-postgres run-tests=false

**Comment by grishick** [comment]
@VitaliiMaltsev after deploying the new version to Cloud I am seeing a new error 
`failures=[io.airbyte.config.FailureReason@14615f4f[failureOrigin=source,failureType=system_error,internalMessage=java.time.format.DateTimeParseException: Text '2022-06-02T21:08:15.122472Z' could not be parsed, unparsed text found at index 26`

**Pull request merged**
