### PR TITLE
[JDBC sources] : Log database indexes per stream

### LINKED ISSUE #24794: Add versioning, indexed fields to db source connector logging
Currently, we don't have any visibility into:  
- The version of a DB a source connector is running against (e.g. Postgres 9.5.x)
- Current indices on the source schema. 

These would be helpful to debug problems in connectors as some of the bugs are version specific. Knowing what the DB has indexed on would help in debugging slow syncs (e.g. incremental sync with cursor might keep doing full table scans)

### PR DESCRIPTION
**Pull request by akashkulk**
Closes https://github.com/airbytehq/airbyte/issues/24794

Part of the work @nguyenaiden did earlier : https://github.com/airbytehq/airbyte/pull/24969. Thanks Duy!

Currently, we don't have any visibility into:

- Current indices on the source schema.

Furthermore, this is becoming more of an issue as initial incremental syncs are taking longer and longer. This will help us inform the customer to create an index for their tables if they want to perform an incremental sync. 

## How
Log db indexes prior to a sync. 

**_Note_**: Compound indexes will show up as its own log line but with the same index name. See screenshot below:
image

### CODE REVIEW

**Review by jcowanpdx — APPROVED** [review]
👍

**Comment by akashkulk** [comment]
/publish connector=connectors/source-postgres run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-postgres-strict-encrypt run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-mysql-strict-encrypt run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-mssql-strict-encrypt run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-postgres-strict-encrypt run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-mysql-strict-encrypt run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-mssql-strict-encrypt run-tests=false

**Pull request merged**
