### PR TITLE
✨ Source Hubspot: handle connection errors

### LINKED ISSUE #26515: Improve HubSpot source connection errors
These errors are emitted during connection sync attempts.

The full list of error responses are here: https://legacydocs.hubspot.com/docs/faq/api-error-responses

The suggestions would be emitted in the external message of the log. 

Type of error: bad URL endpoint
> 400 Client Error: Bad Request for url: https://api.hubapi.com/properties/v2/ttp_payments/properties\nSource didn't exit properly - check the logs!
> 401 Client Error: Unauthorized for url: https://api.hubapi.com/contacts/v1/lists/all/contacts/all?limit=100&vidOffset=17549902&showListMemberships=True
> 403 Client Error: Forbidden for url: https://api.hubapi.com/marketing/v3/forms...

Suggestion: The authenticated user does not have permissions to access the URL {{example endpoint}}. Verify your permissions to access this endpoint. 

Type of error: Oauth token expired
> The OAuth token used to make this call expired 0 second(s) ago.
> This oauth-token is expired! expiresAt: 1684892453714, now: 1684892453813\nSomething went wrong within the source connector
> Exception('Error while refreshing access token: 400 Client Error: Bad Request for url: https://api.hubapi.com/oauth/v1/token')
OAuth Credentials' was expected\nio.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!

Suggestion: The authentication to HubSpot has expired. Re-authenticate to restore access to HubSpot.

Type of error: stream removed from source
>io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!\n\The requested stream feedback_submissions was not found in the source. Available streams: dict_keys(['campaigns', 'companies', 'contact_lists', 'contacts', 'contacts_list_memberships', 'deal_pipelines', 'deals', 'email_events', 'engagements', 'engagements_calls', 'engagements_emails', 'engagements_meetings', 'engagements_notes', 'engagements_tasks', 'forms', 'form_submissions', 'line_items', 'marketing_emails', 'owners', 'products', 'property_history', 'subscription_changes', 'tickets', 'ticket_pipelines', 'workflows'])\"\njava.lang.RuntimeException: java.io.UncheckedIOException: java.net.SocketException: Socket closed"

Suggestion: The stream {stream_name} is no longer available in the source. Remove this stream from syncing or verify your permissions to this stream. 

Type of error: Rate limited
> HubspotRateLimited('429 Rate Limit Exceeded: API rate-limit has been reached until None seconds. See https://developers.hubspot.com/docs/api/usage-details')

Suggestion: You have reached your Hubspot API limit per Hubspot's [API usage guidelines](https://developers.hubspot.com/apps/api_guidelines). We will resume replication once the limit has elapsed.

### PR DESCRIPTION
**Pull request by arsenlosenko**
## What
Improve handling of common connection errors as it is described in this issue:
https://github.com/airbytehq/airbyte/issues/26515

## How
By relying on description of linked issue I have added slightly better phrasing to errors that may happen during connector setup, and wrapped it into `AirbyteTracedException`, so it could be treated as config error in UI.

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`5a1b13ac9f`](https://github.com/airbytehq/airbyte/pull/28909/commits/5a1b13ac9fc1fa1599e4ff669bfb04e2c3a6b5fd)) - ❌

⏲️  Total pipeline duration: 01mn29s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ❌        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_26515-source-hubspot-import-source-connection-errors/1690886210/5a1b13ac9fc1fa1599e4ff669bfb04e2c3a6b5fd/source-hubspot/1.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`b5cebbfa7d`](https://github.com/airbytehq/airbyte/pull/28909/commits/b5cebbfa7de4f4fe1b1d1d2bf471f61fd6db249d)) - ❌

⏲️  Total pipeline duration: 01mn27s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ❌        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_26515-source-hubspot-import-source-connection-errors/1690886523/b5cebbfa7de4f4fe1b1d1d2bf471f61fd6db249d/source-hubspot/1.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`f8c95b1db6`](https://github.com/airbytehq/airbyte/pull/28909/commits/f8c95b1db67db2f7ac4b9c5918e64da3b6cd0a45)) - ❌

⏲️  Total pipeline duration: 01mn21s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ❌        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_26515-source-hubspot-import-source-connection-errors/1690886708/f8c95b1db67db2f7ac4b9c5918e64da3b6cd0a45/source-hubspot/1.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`73dd220895`](https://github.com/airbytehq/airbyte/pull/28909/commits/73dd2208955f309c865e4583874d14a464f13233)) - ❌

⏲️  Total pipeline duration: 01mn23s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_26515-source-hubspot-import-source-connection-errors/1690892641/73dd2208955f309c865e4583874d14a464f13233/source-hubspot/1.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`5fb3737456`](https://github.com/airbytehq/airbyte/pull/28909/commits/5fb3737456c711575cc0b4ea1791a6112d5d71d2)) - ❌

⏲️  Total pipeline duration: 03mn13s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ❌        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_26515-source-hubspot-import-source-connection-errors/1690968120/5fb3737456c711575cc0b4ea1791a6112d5d71d2/source-hubspot/1.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`2f225b258f`](https://github.com/airbytehq/airbyte/pull/28909/commits/2f225b258f2dce1577a91a4b8345f9aac6297c35)) - ❌

⏲️  Total pipeline duration: 02mn58s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_26515-source-hubspot-import-source-connection-errors/1690968541/2f225b258f2dce1577a91a4b8345f9aac6297c35/source-hubspot/1.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`04291cd22f`](https://github.com/airbytehq/airbyte/pull/28909/commits/04291cd22f8c95b32602c4c81fa1f84bc7921962)) - ❌

⏲️  Total pipeline duration: 02mn42s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci-internal/connectors/test/pull_request/arsenlosenko_26515-source-hubspot-import-source-connection-errors/1690977957/04291cd22f8c95b32602c4c81fa1f84bc7921962/source-hubspot/1.3.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`047be356f2`](https://github.com/airbytehq/airbyte/pull/28909/commits/047be356f2458fb36503fb092e75d6d4144d3a76)) - ❌

⏲️  Total pipeline duration: 11mn17s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_26515-source-hubspot-import-source-connection-errors/1691058184/047be356f2458fb36503fb092e75d6d4144d3a76/source-hubspot/1.3.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:047be356f2458fb36503fb092e75d6d4144d3a76)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by bazarnov** [comment]
@arsenlosenko Please fix the `expected records` to pass the CAT. And re-request the review once the CAT is passed successfully. Thank you.

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`64b69da037`](https://github.com/airbytehq/airbyte/pull/28909/commits/64b69da0376441cd2ec7c5c7788ff8ab86148bd9)) - ❌

⏲️  Total pipeline duration: 11mn10s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_26515-source-hubspot-import-source-connection-errors/1691138491/64b69da0376441cd2ec7c5c7788ff8ab86148bd9/source-hubspot/1.3.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:64b69da0376441cd2ec7c5c7788ff8ab86148bd9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`c57afed2f1`](https://github.com/airbytehq/airbyte/pull/28909/commits/c57afed2f1d21760d83a81fb29f6a844dcde598f)) - ✅

⏲️  Total pipeline duration: 11mn27s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_26515-source-hubspot-import-source-connection-errors/1691139722/c57afed2f1d21760d83a81fb29f6a844dcde598f/source-hubspot/1.3.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:c57afed2f1d21760d83a81fb29f6a844dcde598f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Review by bazarnov — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`59a0c649d7`](https://github.com/airbytehq/airbyte/pull/28909/commits/59a0c649d7f24c4da32c503920569034900d235f)) - ❌

⏲️  Total pipeline duration: 11mn25s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_26515-source-hubspot-import-source-connection-errors/1691398063/59a0c649d7f24c4da32c503920569034900d235f/source-hubspot/1.3.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:59a0c649d7f24c4da32c503920569034900d235f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`42ba3e12f3`](https://github.com/airbytehq/airbyte/pull/28909/commits/42ba3e12f33cf88acc5d9607d6aa3ed44d4de91a)) - ✅

⏲️  Total pipeline duration: 11mn11s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_26515-source-hubspot-import-source-connection-errors/1691399414/42ba3e12f33cf88acc5d9607d6aa3ed44d4de91a/source-hubspot/1.3.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:42ba3e12f33cf88acc5d9607d6aa3ed44d4de91a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Pull request merged**
