### PR TITLE
🐛 Source Mailchimp: fix campaign's stream normalization

### LINKED ISSUE #8825: Source Mailchimp: AssertionError: Mismatched number of tables
## Environment
- **Airbyte version**:  0.33.12-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: Mailchimp 0.2.9
- **Destination Connector and version**: Postgres 0.3.13
- **Severity**: Very Low / Low / **Medium** / High / Critical
- **Step where error happened**: Deploy / **Sync job** / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Sync connector is not working with Normalization.

## Expected Behavior
*Tell us what should happen.*

## Logs
```
normalization - 2021-12-16 00:39:06 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/bin/transform-catalog", line 8, in <module>
normalization - 2021-12-16 00:39:06 ERROR () LineGobbler(voidCall):82 -     sys.exit(main())
normalization - 2021-12-16 00:39:06 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/transform.py", line 82, in main
normalization - 2021-12-16 00:39:06 ERROR () LineGobbler(voidCall):82 -     TransformCatalog().run(args)
normalization - 2021-12-16 00:39:06 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/transform.py", line 35, in run
normalization - 2021-12-16 00:39:06 ERROR () LineGobbler(voidCall):82 -     self.process_catalog()
normalization - 2021-12-16 00:39:06 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/transform.py", line 62, in process_catalog
normalization - 2021-12-16 00:39:06 ERROR () LineGobbler(voidCall):82 -     processor.process(catalog_file=catalog_file, json_column_name=json_col, default_schema=schema)
normalization - 2021-12-16 00:39:06 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/catalog_processor.py", line 63, in process
normalization - 2021-12-16 00:39:06 ERROR () LineGobbler(voidCall):82 -     for conflict in tables_registry.resolve_names():
[32mnormalization[0m - 2021-12-16 00:39:06 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/table_name_registry.py", line 196, in resolve_table_names
[32mnormalization[0m - 2021-12-16 00:39:06 ERROR () LineGobbler(voidCall):82 -     assert (table_count * 2) == registry_size, f"Mismatched number of tables {table_count * 2} vs {registry_size} being resolved"
[32mnormalization[0m - 2021-12-16 00:39:06 ERROR () LineGobbler(voidCall):82 - AssertionError: Mismatched number of tables 62 vs 60 being resolved

```
Complete logs: [logs-5-0 (2).txt](https://github.com/airbytehq/airbyte/files/7723735/logs-5-0.2.txt)

## Steps to Reproduce
1. create mailchimp with integration account
2. use postgres destination
3. run sync #:bomb: 

## Are you willing to submit a PR?

Remove this with your answer.

### PR DESCRIPTION
**Pull request by arimbr**
## What
Resolves https://github.com/airbytehq/airbyte/issues/8825

## How
The smallest possible fix I could test locally implies removing a "type" definition within the campaign's stream jsonschema.
- [failing-logs-1.txt](https://github.com/airbytehq/airbyte/files/8214187/fail-logs-1.txt)
- [success-logs-10.txt](https://github.com/airbytehq/airbyte/files/8214191/success-logs-10.txt)

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

### CODE REVIEW

**Review by ChristopheDuong — APPROVED** [review]

**Comment by arimbr** [comment]
@bazarnov do you know why the tests are failing here?

**Comment by bazarnov** [comment]
> @bazarnov do you know why the tests are failing here?

I believe there is a mismatch between two sequential reads (full-refresh sync), please, merge with master and try again.
If it fails one more time, don't worry - try again. Sometimes when the data is updated frequently on the resource, in this case Mailchimp, this tests are failed because there is a mismatch between two reads, they should be equal, or the first one should be a subset (non mutable) from the second one. 

So, try again, in the first place.

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
