### PR TITLE
use http 1.1 for worker

### PR DESCRIPTION
**Pull request by xiaohansong**
## What
Observed errors like this:

Screen Shot 2022-09-09 at 11 03 45 AM

Root cause was:

Our jetty server currently are configured to accept Http1.1 while the ApiClient by default is using HTTP/2.  We are facing either to ask apiclient to use http 1.1 or upgrade server to accept http 2 format. For now it's easier and less intrusive to downlevel to 1.1 than upgrading to 2.0 IMO so here is the approach.

https://stackoverflow.com/a/57510895/2967775

### CODE REVIEW

**Comment by git-phu** [comment]
what would it take to upgrade our jetty server to accept HTTP/2?

**Comment by xiaohansong** [comment]
> what would it take to upgrade our jetty server to accept HTTP/2?

@git-phu I think we just need to follow the following tutorial:

https://www.eclipse.org/jetty/documentation/jetty-11/programming-guide/index.html#pg-server-http-connector-protocol-http2-tls

I'm not really familiar with this category to fully understand the risk of applying the example in our code. Some searches from internet suggests http/2 is actually a much better choice though.

**Comment by davinchia** [comment]
Agree with Peter we should try upgrading to HTTP 2. Also agree no harm to giving this a shot for now.

**Review by davinchia — APPROVED** [review]

**Comment by davinchia** [comment]
@xiaohansong is this happening in the multi-cloud tests?

**Comment by xiaohansong** [comment]
Yes. It fixed 90% of the problems, but we still see `java.io.IOException: HTTP/1.1 header parser received no bytes` occasionally. I'll hold onto this PR and try the other approach to upgrade the server to 2.0 and see if that could fix the problem

**Comment by xiaohansong** [comment]
Realized this might open a can of worms because we are using http 1.1 between server to servers: https://github.com/airbytehq/airbyte/blob/master/airbyte-server/src/main/java/io/airbyte/server/ServerApp.java#L255

I think we should treat upgrading that to 2.0 as a separate ticket.

**Pull request merged**
