### PR TITLE
:bug: Source Harvest: migrate to advanced auth

### PR DESCRIPTION
**Pull request by davydov-d**
## What
#26235 

## How
Remove `authSpecification` from spec.json in favour of `advancedAuth`

_Note: this PR can not be tested locally because of invalid redirect URL_

### CODE REVIEW

**Review by bazarnov — APPROVED** [review]

**Review by lazebnyi — COMMENTED** [review]
Can we test this PR with pre-release tag?

**Comment by davydov-d** [comment]
@lazebnyi sure, will do

**Comment by davydov-d** [comment]
@lazebnyi sure, will do

**Pull request merged**
