### PR TITLE
🎉 Source Snowflake : Update JDBC driver for Snowflake to 3.13.22

### LINKED ISSUE #16552: Update JDBC driver for Snowflake source
## Current Behavior
Per this [build](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-snowflake/build.gradle), Airbyte is currently using version 3.13.9 of the JDBC drive for Snowflake.  That driver is almost a year old and should be updated to the latest version 3.13.22, as of the creation of this ticket.   We should consider updating our driver as well as putting in a mechanism to keep it updated on an ongoing basis.  

Link for the repo with all of the drivers:
https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/

### PR DESCRIPTION
**Pull request by akashkulk**
## What
🎉 Source Snowflake : Per this [build](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-snowflake/build.gradle), Airbyte is currently using version 3.13.9 of the JDBC drive for Snowflake. That driver is almost a year old and should be updated to the latest version 3.13.22, as of the creation of this ticket. We should consider updating our driver as well as putting in a mechanism to keep it updated on an ongoing basis.

Link for the repo with all of the drivers:
https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/

Resolve https://github.com/airbytehq/airbyte/issues/16552

## How
Update the driver to the latest version (3.13.22)

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

### CODE REVIEW

**Comment by tuliren** [comment]
@akashkulk, don't forget to sign the CLA.

**Review by tuliren — COMMENTED** [review]
Please also bump the connector version in the dockerfile.

**Review by tuliren — COMMENTED** [review]
- The version bump is correct~~
- You should also update the changelog in `source/snowflake.md` and `destination/snowflake.md`.
- The test failure seems persistent and related to the version bump. For example, the source always had two failed integration tests. Can you take a look into the root cause? Do they pass locally?

**Review by tuliren — APPROVED** [review]
Nice!

Can you go through the pre-merge checklist and check off the items accordingly? For example, you should update the `CHANGELOG` in `snowflake.md` to add the information about the new version.

**Comment by akashkulk** [comment]
> Nice!
> 
> Can you go through the pre-merge checklist and check off the items accordingly? For example, you should update the `CHANGELOG` in `snowflake.md` to add the information about the new version.

Thanks. I've checked off the relevant items. Just to confirm - after you approve these changes, I should (i) publish the new docker image and then (ii) merge the PR, correct?

**Comment by akashkulk** [comment]
/publish connector=connectors/source-snowflake run-tests=false

**Pull request merged**
