### PR TITLE
🎉 New Destination: HDFS

### PR DESCRIPTION
**Pull request by AetherUnbound**
## What

This PR adds a new destination: HDFS. Data received by this destination are written to a `jsonl` file on an HDFS cluster available over HTTP.

While this is pretty limited in its scope currently, the `hdfs` python library does provide options for more complex connection configurations that could be added in the future!

## Recommended reading order
1. `client.py`
1. `destination.py`
1. `unit_test.py`
1. All others

## Pre-merge Checklist
Expand the checklist which is relevant for this PR. 

<details><summary> <strong> Connector checklist </strong> </summary>
<p>

- [ ] Issue acceptance criteria met
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Secrets are annotated with `airbyte_secret` in the connector's spec
- [ ] Credentials added to Github CI if needed and not already present. [instructions for injecting secrets into CI](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#using-credentials-in-ci). 
- [x] Unit & integration tests added as appropriate (and are passing)
    * Community members: please provide proof of this succeeding locally e.g: screenshot or copy-paste acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] `/test connector=connectors/<name>` command as documented [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-an-existing-connector) is passing. 
    * Community members can skip this, Airbyters will run this for you. 
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [x] `README.md`
    - [x] `docs/SUMMARY.md` if it's a new connector
    - [x] Created or updated reference docs in `docs/integrations/<source or destination>/<name>`.
    - [ ] Changelog in the appropriate page in `docs/integrations/...`. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md` contains a reference to the new connector
    - [ ] Build status added to [build page](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md)
- [ ] Build is successful
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] No major blockers
- [ ] PR merged into master branch
- [ ] Follow up tickets have been created
- [ ] Associated tickets have been closed & stakeholders notified
</p>
</details>

<details><summary> <strong> Connector Generator checklist </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks a lot @AetherUnbound for the contribution :rocket:

**Comment by AetherUnbound** [comment]
Frankly I don't think this destination will be as much use as I initially thought. I'll go ahead and close this

**Comment by skt7** [comment]
Hi @AetherUnbound, I was checking if airbyte has support for HDFS as a destination and tumbled upon here. If you are okay to share, I wanted to explore more on your view that why you think it won't be useful. Where I am coming from is that we are working on designing a data pipeline and we were considering HDFS as one of the options for data lake. So would like to understand if there are any shortcomings specifically with HDFS compared to other systems when it comes to ETL or if it's more specific to Airbyte working and integration for HDFS as a destination for the same.

**Comment by AetherUnbound** [comment]
Hi @skt7! I was performing some exploratory development which resulted in this PR. The shortcoming I personally had was the merely the time & capacity I had to implement and flesh out this destination, not any inherent issues with HDFS. I'm not very experienced with HDFS, but that was the constraint of the system I was exploring this new solution for. We haven't moved forward with that approach yet for unrelated reasons. As such I didn't have the capacity to get this across the finish line for a system I had almost no familiarity with 😄 Sorry I can't be more helpful!

**Pull request closed without merging**
