### PR TITLE
🎉 Incremental Normalization

### LINKED ISSUE #4286: Improve normalization runtime
## Tell us about the problem you're trying to solve
We've received many reports in the past few weeks of normalization taking an incredibly long time to run. 

One example: 
[logs-42-0.txt](https://github.com/airbytehq/airbyte/files/6699579/logs-42-0.txt)
A user synced a few hundred records from Zendesk. The sync took about 25s. Normalization took about 50 minutes. For the record the destination contains >200k records but the individual sync read only a few hundred new records. [Slack thread](https://airbytehq.slack.com/archives/C01MFR03D5W/p1624276420212300)

One very likely root cause is that currently normalization reads the entire `_raw` table and recreates the normalized tables completely from scratch every time a sync happens. This means work scales with the size of the total dataset. We want work to scale with the size of the new data written to the destination. 

In the interest of complete intellectual honesty, I'm actually not 100% sure the issue is the size of the target dataset. The only reason I hesitate is because other users have reported syncing >100gb DBs into warehouses. If this problem was this bad on 200k records from an API, then surely it would have ground the large DB syncs to a halt. So there might be more nuance to this issue than I'm realizing. 

## Describe the solution you’d like
I would like normalization runtime to scale with the size of data written not total data set. Also I would like normalization to take a "reasonable" amount of time to run. ~300 new records and 200k total records taking 50m seems crazy. 5 minutes is acceptable. 1 minute would be amazing. 

## Describe the alternative you’ve considered or used
Not using normalization
Rolling out a custom connector which implements its own normalization

### PR DESCRIPTION
**Pull request by ChristopheDuong**
## What
Closes #4286 

## How
This PR is pretty "standard" when using dbt and is mostly following instructions from https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models (you will find many copy/paste parts between that doc page and this PR whether in the code or in the description)

### What is an incremental model?

Incremental models are built as tables in your data warehouse – the first time a model is run, the table is built by transforming all rows of source data. On subsequent runs, dbt transforms only the rows in your source data that you tell dbt to filter for, inserting them into the table that has already been built (the target table).

Often, the rows you filter for on an incremental run will be the rows in your source data that have been created or updated since the last time dbt ran. As such, on each dbt run, your model gets built incrementally.

Using an incremental model limits the amount of data that needs to be transformed, vastly reducing the runtime of your transformations. This improves warehouse performance and reduces compute costs.

To use incremental models, you also need to tell dbt:

 1. how to filter the rows on an incremental run.
 2. the uniqueness constraint of the model (if any).

### 1. Filtering rows on an incremental run

To tell dbt which rows it should transform on an incremental run, we append the `incremental_clause()` macro (defined in `airbyte-integrations/bases/base-normalization/dbt-project-template/macros/incremental.sql`) in `where` clauses at the end of every model generated by normalization.

This ensures that every model filters for "new" rows, as in, rows that have been created since the last time dbt ran this model. 

The best way to find the timestamp of the most recent run of this model is by checking the most recent timestamp in the target table. dbt makes it easy to query your target table by using the "{{ this }}" variable.

> and {{ col_emitted_at }} > (select max({{ col_emitted_at }}) from {{ this }})

This condition is surrounded in jinja by `{% if is_incremental() %}` statement to toggle the incremental behavior depending on the mode dbt is run with for that particular model: full_refresh vs incremental?

The is_incremental() macro will return True if:

    - the destination table already exists in the database
    - dbt is not running in full-refresh mode
    - the running model is configured with materialized='incremental'

### 2. Defining a uniqueness constraint (optional)

This is totally optional and we could completely ignore this (except in deduplicated tables that relies on primary keys)
However, we made the choice to always put a unique constraint on all models generated by normalization.

unique_key is an optional parameter for incremental models that specifies a field that should be unique within your model. If the unique key of an existing row in your target table matches one of your incrementally transformed rows, the existing row will be updated. This ensures that you don't have multiple rows in your target table for a single row in your source data.

You can define unique_key in a configuration block at the top of your model. The unique_key should be a single field name that is present in your model definition. While some databases support using expressions (eg. concat(user_id, session_number)), this syntax is not universally supported, so is not recommended. If you do not have a single field that is unique, consider first creating such a field in your model.

Building this model incrementally without the unique_key parameter would result in multiple rows in the target table for a single day – one row for each time dbt runs on that day. Instead, the inclusion of the unique_key parameter ensures the existing row is updated instead.
Without unique_key, the generated SQL would be a simple `insert into` whereas with the unique_key defined, it is generating (when possible) a `merge on unique_key` statement (or equivalent through `delete where unique_key; insert into where unique_key`)

For every stream, we do have a single field that is unique for each row: `_airbyte_ab_id` in the `_airbyte_raw` tables. 
Airbyte destination connectors always included a `randomUUID` value in the `_airbyte_ab_id` column when writing a new row. This was always present on the `_airbyte_raw` tables but unused in normalization until now.

Thus we can use that for every normalized table too. In the special case of deduplicated tables, we need to use (potentially composite) primary keys defined by the user, so we first generate a single column `_airbyte_unique_key` by hashing the primary keys together (in `generate_scd_type_2_model` function in `stream_processor.py`).

For these special tables that need to be deduplicated, if we don't specify the unique_key, we risk breaking the constraint of having only one row per primary key (not being fully deduplicated anymore). So, it is mandatory to have the unique_key = primary keys.

Because we rely on this new column `_airbyte_ab_id` column to be present on all normalized tables (which were not propagated before this PR). We are effectively introducing a schema change with a new "mandatory" field (non-nullable).

### So, how does dbt handle this schema change?

New on_schema_change config in dbt version v0.21.0

Incremental models can now be configured to include an optional on_schema_change parameter to enable additional control when incremental model columns change. These options enable dbt to continue running incremental models in the presence of schema changes,

The modes we could choose are (among other modes that raise exceptions or do nothing when detecting changes):

> - append_new_columns: Append new columns to the existing table. Note that this setting does not remove columns from the existing table that are not present in the new data.
> - sync_all_columns: Adds any new columns to the existing table, and removes any columns that are now missing. Note that this is inclusive of data type changes. On BigQuery, changing column types requires a full table scan; be mindful of the trade-offs when implementing.

Note: None of the on_schema_change behaviors backfill values in old records for newly added columns which is our case as we want `_airbyte_ab_id` to be always populated! Too bad, we can't leverage this... so FULL REFRESH!

To force dbt to rebuild the entire incremental model from scratch, we can use the --full-refresh flag on the command line. This flag will cause dbt to drop the existing target table in the database before rebuilding it for all-time for all rows. (basically, it reverts to behave like older versions of normalization)

But normalization is always run without that flag on the CLI (since we want incremental now!) and we can't tweak it from the UI or Airbyte worker. (plus we may run into scenarios where only certain models need full-refresh and others don't, so we need a more granular way to trigger full_refresh, aka per stream)

### Full refresh existing destinations tables (when migrating from older normalization version to this PR)

To implement this more granular full_refresh decision, we override dbt's special macro `should_full_refresh` in `airbyte-integrations/bases/base-normalization/dbt-project-template/macros/should_full_refresh.sql`

The macro tries to detect if there are existing normalized tables in the destination that were produced by older versions of normalization (ie that don't have a `_airbyte_ab_id` columns). In that case, it returns `true` to signal a need for full_refresh.

If we didn't choose to have a unique_key constraint by `_airbyte_ab_id`, we wouldn't need this logic at all. 

But introducing this column now allows users to make a clean join between the normalized tables and the raw tables and align how the JSON blob is expanded into tabular columns. As a result, we can also ensure that one row in the raw tables produces only one row in the normalized tables. We avoid the risk that multiple normalized rows are duplicated every time dbt is run. This is a new concern because we are now in incremental and not rebuilding the whole table from 0 every time dbt is run.

## Recommended reading order
In terms of code changes:
1.  The main implementation `airbyte-integrations/bases/base-normalization/normalization/transform_catalog/stream_processor.py`
2. The macro for incremental `airbyte-integrations/bases/base-normalization/dbt-project-template/macros/incremental.sql`
3. The macro to detect when to full-refresh (for migrating to new normalization version with incremental) `airbyte-integrations/bases/base-normalization/dbt-project-template/macros/should_full_refresh.sql`

Or in terms of changes to the generated SQL:
1. Normal tables built on top of raw tables directly: `airbyte-integrations/bases/base-normalization/integration_tests/normalization_test_output/postgres/test_simple_streams/models/generated/airbyte_incremental/test_normalization/exchange_rate.sql`
Screenshot 2021-10-22 at 11 57 21
2. Deduplicated tables (using different unique_key) built on top of the SCD tables: `airbyte-integrations/bases/base-normalization/integration_tests/normalization_test_output/postgres/test_simple_streams/models/generated/airbyte_incremental/test_normalization/dedup_exchange_rate.sql`
Screenshot 2021-10-22 at 11 57 43
3. SCD table where the unique_key column is built:
Screenshot 2021-10-22 at 11 58 02

## Under the (dbt) hood

2. for full refresh version or if table doesn't exist yet `airbyte-integrations/bases/base-normalization/integration_tests/normalization_test_output/postgres/test_simple_streams/first_output/airbyte_incremental/test_normalization/exchange_rate.sql`
Screenshot 2021-10-22 at 11 58 39
3. when incrementally updating it, dbt runs the incremental read query internally and probably built a temp table that contains only the new records to be transformed. Then, the SQL engine will incrementally overwrites in the destination table using the following query: `airbyte-integrations/bases/base-normalization/integration_tests/normalization_test_output/postgres/test_simple_streams/second_output/airbyte_incremental/test_normalization/exchange_rate.sql`
Screenshot 2021-10-22 at 11 58 57
- By using an `insert into ...` query, only the new data records are written = incrementally.
- When using a `create table ... as select ... from ...` query, it would rewrites the entire data = non-incremental
- the `delete ... from ...` query ensures unicity of records per `_airbyte_ab_id` or `_airbyte_unique_key`

## Known Issues or limitations

While implementing this PR, I ran into the following issues that need to be addressed in the future:
1. dbt incremental does not do well yet with special characters and quotes in columns names. Corresponding failing tests cases in normalization are therefore disabled.
2. dbt incremental does not work out of the box for dbt-community-contributed adapters for MySql and Oracle. Additional effort is required to make those work in incremental. (they are not based on dbt 0.21.0 which introduces quite some improvements over incremental & schema change)
3. This PR introduces performance optimizations for mostly WRITE operations by normalization. READ performance are still not optimal and requires additional changes in specific destination connectors to "index" (partition) efficiently the raw tables, so normalization can take advantage of it when retrieving the new data to be normalized.
4. An experimental PR to push limits on schema changes while running incremental normalization is proposed here: https://github.com/airbytehq/airbyte/pull/7277
5. incremental normalization produces partition keys on the final normalized tables by default, you can follow this guide (on any destinations supported by dbt) to add/edit/tweak them: https://airbyte.io/recipes/bigquery-partition-cluster. These may (or may not) have been used by destination connectors on the raw tables

### CODE REVIEW

**Review by cgardens — COMMENTED** [review]
one question. i think once it is answered i can approve it. going for comment so that i don't block it if someone with more context can approve.

**Review by sherifnada — COMMENTED** [review]
some questions to solidify understanding, will review again tomorrow

**Review by Phlair — COMMENTED** [review]
will leave as comment and not block

**Review by cgardens — APPROVED** [review]
thanks for the clarification. i have one question about the where clause for checking the timestamp (see below) that is important to address before merging (or tell me that i'm misunderstanding it). otherwise lgtm!

**Review by sherifnada — APPROVED** [review]
Thanks for adding the explanations! Could you document the meanings of the different "system" columns either in this module README or in the public facing normalization docs so we can retain that context? 

> dbt incremental does not work out of the box for dbt-community-contributed adapters for MySql and Oracle. Additional effort is required to make those work in incremental. (they are not based on dbt 0.21.0 which introduces quite some improvements over incremental & schema change)

is the impact that they don't get incremental and they still use full refresh? 

> dbt incremental does not do well yet with special characters and quotes in columns names. Corresponding failing tests cases in normalization are therefore disabled.

Do you have an idea of what's required to handle this properly? do we need a change in DBT itself? could you create an issue with any context on required solution?

**Pull request merged**
