### PR TITLE
🐛 Update Convex destination connector to fix overwrite sync mode

### PR DESCRIPTION
**Pull request by emmaling27**
## What
Convex stopped supporting the `replace_tables` endpoint that is used in `overwrite` sync mode. This PR updates the destination connector to use the `clear_tables` endpoint instead, so overwrite sync mode works again. This also fixes some broken links to documentation of the Convex streaming import API.

## How
Instead of writing to temporary tables and then replacing them at the end of the sync by calling `replace_tables`, this implementation of overwrite sync clears all records from the tables at the beginning of the sync by making a request to `clear_tables` and then writes airbyte records to them. This preserves existing Convex indexes and schemas.

## Recommended reading order
1. `client.py`
2. `destination.py`
The rest of the changes are airbyte copyright updates from formatting.

## 🚨 User Impact 🚨
All overwrite syncs are broken for users currently (returning 400 errors from Convex because the `replace_tables` API endpoint is no longer supported). This will fix it, so overwrite syncs should work again. No breaking changes!

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Currently the integration test for convex is not working @emmaling27.
We'll need some time to fix tests before get into your code change.

**Comment by emmaling27** [comment]
> Currently the integration test for convex is not working @emmaling27. We'll need some time to fix tests before get into your code change.

@marcosmarxm Thanks for the quick response! Is this integration test something I can help with? The unit test for the convex destination is passing for me locally, but I'm not sure if that's what you're referring to. If the integration test is failing because `replace_tables` is returning 400, this PR would help fix. Let me know what I can do to help!

**Comment by marcosmarxm** [comment]
@emmaling27 if you have a valid config for convex it's possible to run the integration tests.
Create a secret folder and add the config.json inside it using the sample config file.
After `./gradlew airbyte-integrations:connectors:destination-convex:integrationTest`

**Comment by emmaling27** [comment]
> @emmaling27 if you have a valid config for convex it's possible to run the integration tests. Create a secret folder and add the config.json inside it using the sample config file. After `./gradlew airbyte-integrations:connectors:destination-convex:integrationTest`

This test passes for me. Do you need me to upload these credentials, and if so, how can I do this securely? Test output:
```
> Task :airbyte-integrations:connectors:destination-convex:_customIntegrationTestsCoverage
[python] .venv/bin/python -m coverage run --data-file=integration_tests/.coverage.customIntegrationTests --rcfile=/Users/emmaling/Projects/airbyte/pyproject.toml -m pytest -s integration_tests -c /Users/emmaling/Projects/airbyte/pyproject.toml
         ============================= test session starts ==============================
         platform darwin -- Python 3.9.16, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/emmaling/Projects/airbyte/airbyte-integrations/connectors/destination-convex/.venv/bin/python
         cachedir: .pytest_cache
         rootdir: /Users/emmaling/Projects/airbyte/airbyte-integrations/connectors/destination-convex/integration_tests, configfile: ../../../../pyproject.toml
         collecting ... collected 1 item

         integration_tests/integration_test.py::test_example PASSED

         ============================== 1 passed in 0.01s ===============================
```

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
