### PR TITLE
source-shopify: Inconsistent Comparison Fix

### PR DESCRIPTION
**Pull request by ahmed-buksh**
## What
Shopify historic sync fails due to inconsistent comparisons of `none` to `str`
Issue [11976](https://github.com/airbytehq/airbyte/issues/11976)

## How
Get updated to return instead of default None

## Recommended reading order
1. `airbyte-integrations/connectors/source-shopify/source_shopify/source.py`

## 🚨 User Impact 🚨
No breaking changes.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Review by alafanechere — COMMENTED** [review]
Thank you @ahmed-buksh for the contribution. I allowed myself to make a change in the comparison logic. I think `record.get(self.cursor_field)` returns ISO strings that can be compared. To make it more explicit I setting the default value to the epoch time.

**Comment by alafanechere** [comment]
@ahmed-buksh could you share the output of the acceptance test run (with a screenshot)? I think our shopify sandbox account is missing a validation on shopify side to properly run the tests (https://github.com/airbytehq/airbyte/issues/11334) which is why the build of this connector is broken on master. I'll publish and merge this fix if you share a proof that the acceptance tests are passing 🙏

**Comment by alafanechere** [comment]
@ahmed-buksh could you please give an update about your test run? 🙏

**Comment by ahmed-buksh** [comment]
@alafanechere just pulling the updated master and running the tests, will update you in a while.

**Comment by ahmed-buksh** [comment]
@alafanechere I am facing the failure of acceptance test due to some issues with payment methods of my store. I start getting 404 on balance and transaction stuff and further findings on it revealed that one found this issue due to unavailability of payment methods in that region.

**Comment by alafanechere** [comment]
@ahmed-buksh are these errors happening during the connection check or on read? Feel free to share the test output.

**Comment by ahmed-buksh** [comment]
@alafanechere attached are the screenshots of tests failing on read.
image
image (1)

**Comment by alafanechere** [comment]
@ahmed-buksh Could you please attach your full test logs output?

**Comment by ahmed-buksh** [comment]
@alafanechere
[test_output.log](https://github.com/airbytehq/airbyte/files/8897745/test_output.log)

**Review by alafanechere — CHANGES_REQUESTED** [review]
@ahmed-buksh I'm not able to run tests, for the reason I explained above. 
I checked you changes and I think they are not appropriate for all streams. Some streams are using cursors that are not timestamps but id (`Collects`, `BalanceTransactions`, `OrderRisks`), which will make the comparison you created not work appropriately :) 
Could you please override the `filter_records_newer_than_state` on those streams and implement a valid comparison?

**Comment by alafanechere** [comment]
Hey @ahmed-buksh I'm closing this PR as we did not receive updates since my last change request. Feel free to open a new PR anytime with these changes!

**Pull request closed without merging**
