### PR TITLE
Pin cdk back to 0.1.0 for postgres, mysql, mssql

### PR DESCRIPTION
**Pull request by akashkulk**

### CODE REVIEW

**Review by postamar — APPROVED** [review]
If the CI is happy then I'm happy.

**Comment by airbyte-oss-build-runner** [comment]
##  source-mssql test report (commit [`e85e2a8db7`](https://github.com/airbytehq/airbyte/pull/31085/commits/e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9)) - ❌

⏲️  Total pipeline duration: 30.95s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_fix-postgres/1696460315/e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9/source-mssql/2.0.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mssql test
```

**Comment by octavia-approvington** [comment]
What are we doing again? <br/> merge and squash

**Review by octavia-approvington — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-mssql-strict-encrypt test report (commit [`e85e2a8db7`](https://github.com/airbytehq/airbyte/pull/31085/commits/e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9)) - ❌

⏲️  Total pipeline duration: 311mn07s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build connector tar                                                         | ✅        |
| Build source-mssql-strict-encrypt docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                   | ❌        |
| Java Connector Integration Tests                                            | ❌        |
| Acceptance tests                                                            | ❌        |
| Validate metadata for source-mssql-strict-encrypt                           | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_fix-postgres/1696460315/e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9/source-mssql-strict-encrypt/2.0.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mssql-strict-encrypt test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-mysql-strict-encrypt test report (commit [`e85e2a8db7`](https://github.com/airbytehq/airbyte/pull/31085/commits/e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9)) - ✅

⏲️  Total pipeline duration: 10mn32s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build connector tar                                                         | ✅        |
| Build source-mysql-strict-encrypt docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                   | ✅        |
| Java Connector Integration Tests                                            | ✅        |
| Acceptance tests                                                            | ✅        |
| Validate metadata for source-mysql-strict-encrypt                           | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_fix-postgres/1696460315/e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9/source-mysql-strict-encrypt/3.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql-strict-encrypt test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres-strict-encrypt test report (commit [`e85e2a8db7`](https://github.com/airbytehq/airbyte/pull/31085/commits/e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9)) - ❌

⏲️  Total pipeline duration: 05mn21s 

| Step                                                                           | Result   |
|:-------------------------------------------------------------------------------|:---------|
| Build connector tar                                                            | ✅        |
| Build source-postgres-strict-encrypt docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                                      | ❌        |
| Java Connector Integration Tests                                               | ❌        |
| Acceptance tests                                                               | ✅        |
| Validate metadata for source-postgres-strict-encrypt                           | ✅        |
| Connector version semver check                                                 | ✅        |
| QA checks                                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_fix-postgres/1696460315/e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9/source-postgres-strict-encrypt/3.1.8/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres-strict-encrypt test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-postgres test report (commit [`e85e2a8db7`](https://github.com/airbytehq/airbyte/pull/31085/commits/e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9)) - ❌

⏲️  Total pipeline duration: 11mn18s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build connector tar                                             | ✅        |
| Build source-postgres docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                       | ❌        |
| Java Connector Integration Tests                                | ❌        |
| Acceptance tests                                                | ✅        |
| Validate metadata for source-postgres                           | ✅        |
| Connector version semver check                                  | ✅        |
| QA checks                                                       | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_fix-postgres/1696460315/e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9/source-postgres/3.1.9/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-postgres test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-mysql test report (commit [`e85e2a8db7`](https://github.com/airbytehq/airbyte/pull/31085/commits/e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9)) - ❌

⏲️  Total pipeline duration: 03mn37s 

| Step                                                         | Result   |
|:-------------------------------------------------------------|:---------|
| Build connector tar                                          | ✅        |
| Build source-mysql docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                    | ❌        |
| Java Connector Integration Tests                             | ✅        |
| Acceptance tests                                             | ✅        |
| Validate metadata for source-mysql                           | ✅        |
| Connector version semver check                               | ✅        |
| QA checks                                                    | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/akash_fix-postgres/1696460315/e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9/source-mysql/3.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e85e2a8db7b51c02cf430a21c86ff51d2b5f85a9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Pull request merged**
