### PR TITLE
source-invoiceninja contribution from ombhardwajj

### LINKED ISSUE #47635: [connector-request] Invoiceninja
### Topic

_No response_

### Relevant information

This is a suggestion to create a connector for Invoiceninja using the UI Connector Builder.
The website for the connector is https://invoiceninja.com/

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to step 3).
3. Describe steps to get credentials.
4. Create the connector using the UI Builder.   

> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> This is a suggestion, and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend following the steps above.

### PR DESCRIPTION
**Pull request by ombhardwajj**
Closes #47635
## What

This PR adds a new connector for source Invoiceninja (source-invoiceninja).

Contributor-provided connector description:

Invoice Ninja is an invoicing, billing, and payment management software.
With this connector we can extract data from various streams such asproducts , invoice , payments and quotes.
Docs : https://api-docs.invoicing.co/#overview--introduction
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| clients | id | DefaultPaginator | ✅ |  ❌  |
| products | id | DefaultPaginator | ✅ |  ❌  |
| invoices | id | DefaultPaginator | ✅ |  ❌  |
| recurring invoices | id | DefaultPaginator | ✅ |  ❌  |
| payments | id | DefaultPaginator | ✅ |  ❌  |
| quotes | id | DefaultPaginator | ✅ |  ❌  |
| credits | id | DefaultPaginator | ✅ |  ❌  |
| projects | id | DefaultPaginator | ✅ |  ❌  |
| tasks | id | DefaultPaginator | ✅ |  ❌  |
| vendors | id | DefaultPaginator | ✅ |  ❌  |
| purchase_orders | id | DefaultPaginator | ✅ |  ❌  |
| expenses | id | DefaultPaginator | ✅ |  ❌  |
| recurring expenses | id | DefaultPaginator | ✅ |  ❌  |
| bank transactions | id | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by marcosmarxm** [comment]
I couldn't test the connector in your workspace, please check credentials and let me know.

**Comment by ombhardwajj** [comment]
Hey @marcosmarxm 
I've fixed that. You can now try to test the connector 😄

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Pagination is not right, it must be page incremental instead of offset.

**Comment by ombhardwajj** [comment]
Correction made 🙇 , apologies for the inadvertent oversight!
@marcosmarxm

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
