### PR TITLE
source-stockdata contribution from ombhardwajj

### LINKED ISSUE #47399: [connector-request] StockData
This is a suggestion to create a connector for StockData using the UI Connector Builder.
The website for the connector is https://stockdata.org/

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to step 3).
3. Describe steps to get credentials.
4. Create the connector using the UI Builder.   

> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> This is a suggestion, and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend following the steps above.

### PR DESCRIPTION
**Pull request by ombhardwajj**
This closes #47399
## What

This PR adds a new connector for source StockData (source-stockdata).

Contributor-provided connector description:

Stockdata provides access to market news for global exchanges, and trading data for US stocks.
With this connector we can extract data from EOD , Intraday and news feeds streams

## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key.  |  |
| `to` | `string` | To.  |  |
| `symbols` | `array` | Symbols.  |  |
| `industries` | `array` | Industries. Specify the industries of entities which have been identified within the article. |  |
| `filter_entities` | `boolean` | Filter Entities.  | false |
| `start_date` | `string` | Start date.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| symbols_news_feeds | uuid | DefaultPaginator | ✅ |  ✅  |
| eod_data |  | No pagination | ✅ |  ✅  |
| intraday_unadjusted_data | date.ticker | No pagination | ✅ |  ✅  |
| industries_news_feeds | uuid | DefaultPaginator | ✅ |  ✅  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
* News stream won't finish never with limit 2 and 170k+ records.
* Maybe introduce a search query or filter to the news based on industry or symbols
* Make symbols an array and create a parameterized request based on that
* to and from must be implement incremental format

**Comment by marcosmarxm** [comment]
Moving next review to nov 13

**Comment by ombhardwajj** [comment]
Hey @marcosmarxm , I've added Incremental Sync for EOD Data and Intraday Unadjusted Data , also I've added some query paramas to filter the news!

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Remove stock search.
Make news incremental and have a single Start Date. Move from Custom to User Input.
Don't include end date param keep as now as the builder will handle to now utc automatically.

Split the News Endpoint and create two streams:
* One uses Symbols to get news from companies
* Other users Industries

Make Industries an array user can select possible values.

**Comment by ombhardwajj** [comment]
The changes you required have been made . @marcosmarxm 
Please review 🙇

**Comment by ombhardwajj** [comment]
Please review it today @marcosmarxm !!

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
