### PR TITLE
add source mailgun singer

### PR DESCRIPTION
**Pull request by blotouta2**
## What
Added new source for Mailgun

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@blotouta2 can you add the checklist from PR template ([see here](https://github.com/airbytehq/airbyte/blob/master/.github/pull_request_template.md)) This help us reviewing your code and follow up the status. Let me know if you have any question.

**Comment by marcosmarxm** [comment]
@blotouta2 can you add the checklist from PR template ([see here](https://github.com/airbytehq/airbyte/blob/master/.github/pull_request_template.md)) This help us reviewing your code and follow up the status. Let me know if you have any questions.

**Comment by michel-tricot** [comment]
Thank you @blotouta2 !!

**Comment by blotouta2** [comment]
sure @marcosmarxm

**Comment by marcosmarxm** [comment]
Hi @blotouta2 could you update the PR content by adding the info to give us a better context in what step you are?

**Comment by blotouta2** [comment]
What
New Source Mailgun

How
Added Tap-Mailgun singer (https://github.com/streetteam/tap-mailgun)

Recommended reading order
y.python

**Pull request closed without merging**
