### PR TITLE
Postgres source: skipping columns with nullable values

### LINKED ISSUE #10230: Google Cloud Storage - Field will be removed when all records are NULL
## Environment
- **Airbyte version**:  0.35.5-alpha
- **OS Version / Instance**:  Ubuntu 20.04.3 LTS
- **Deployment**: Docker 
- **Source Connector and version**:  Postgres 0.3.13 
- **Destination Connector and version**: Google Cloud Storage (GCS) 0.1.20  
- **Severity**: Critical
- **Step where error happened**: Sync job

## Current Behavior
When any fields of the data sources that have all records as NULL value the field is removed from the destination output.

## Expected Behavior
All fields should be remain the same as source even they are all NULL 

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

2022-02-09 09:37:08 INFO i.a.w.DefaultReplicationWorker(run):135 - One of source or destination thread complete. Waiting on the other.
2022-02-09 09:37:08 destination > 2022-02-09 09:37:08 INFO i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):80 - {} - Airbyte message consumer: succeeded.
2022-02-09 09:37:08 destination > 2022-02-09 09:37:08 INFO i.a.i.d.g.w.BaseGcsWriter(close):129 - {} - Uploading remaining data for stream 'cmssupplier'.
2022-02-09 09:37:08 destination > 2022-02-09 09:37:08 INFO a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
2022-02-09 09:37:08 destination > 2022-02-09 09:37:08 INFO a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
2022-02-09 09:37:08 destination > 2022-02-09 09:37:08 WARN a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
2022-02-09 09:37:10 destination > 2022-02-09 09:37:10 INFO a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to ofm-data/test/private/cmssupplier/2022_02_09_1644399415821_0.csv with id ABPnzm5gf...enlB5-jIW]: Finished uploading [Part number 1 containing 11.22 MB]
2022-02-09 09:37:10 destination > 2022-02-09 09:37:10 INFO a.m.s.StreamTransferManager(complete):395 - {} - [Manager uploading to ofm-data/test/private/cmssupplier/2022_02_09_1644399415821_0.csv with id ABPnzm5gf...enlB5-jIW]: Completed
2022-02-09 09:37:10 destination > 2022-02-09 09:37:10 INFO i.a.i.d.g.w.BaseGcsWriter(close):131 - {} - Upload completed for stream 'cmssupplier'.
2022-02-09 09:37:10 INFO i.a.v.j.JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $: null found, object expected
2022-02-09 09:37:10 ERROR i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$1):70 - Validation failed: null
2022-02-09 09:37:10 destination > 2022-02-09 09:37:10 INFO i.a.i.b.IntegrationRunner(run):153 - {} - Completed integration: io.airbyte.integrations.destination.gcs.GcsDestination
2022-02-09 09:37:10 INFO i.a.w.DefaultReplicationWorker(run):137 - Source and destination threads complete.
2022-02-09 09:37:10 INFO i.a.w.DefaultReplicationWorker(run):200 - sync summary: io.airbyte.config.ReplicationAttemptSummary@727e6376[status=completed,recordsSynced=4787,bytesSynced=10166739,startTime=1644399404927,endTime=1644399430545,totalStats=io.airbyte.config.SyncStats@43a9ddfd[recordsEmitted=4787,bytesEmitted=10166739,stateMessagesEmitted=0,recordsCommitted=4787],streamStats=[io.airbyte.config.StreamSyncStats@397cdaca[streamName=cmssupplier,stats=io.airbyte.config.SyncStats@18406df6[recordsEmitted=4787,bytesEmitted=10166739,stateMessagesEmitted=<null>,recordsCommitted=4787]]]]
2022-02-09 09:37:10 INFO i.a.w.DefaultReplicationWorker(run):209 - Source did not output any state messages
2022-02-09 09:37:10 WARN i.a.w.DefaultReplicationWorker(run):217 - State capture: No new state, falling back on input state: io.airbyte.config.State@1924c85b[state={"cdc":false,"streams":[{"cursor":"2022-02-08T10:51:22Z","stream_name":"cmssupplier","cursor_field":["updateon"],"stream_namespace":"officemate"}]}]
2022-02-09 09:37:10 INFO i.a.w.t.TemporalAttemptExecution(get):144 - Stopping cancellation check scheduling...
2022-02-09 09:37:10 INFO i.a.w.t.s.ReplicationActivityImpl(replicate):144 - sync summary: io.airbyte.config.StandardSyncOutput@6ced3974[standardSyncSummary=io.airbyte.config.StandardSyncSummary@1b8abfbf[status=completed,recordsSynced=4787,bytesSynced=10166739,startTime=1644399404927,endTime=1644399430545,totalStats=io.airbyte.config.SyncStats@43a9ddfd[recordsEmitted=4787,bytesEmitted=10166739,stateMessagesEmitted=0,recordsCommitted=4787],streamStats=[io.airbyte.config.StreamSyncStats@397cdaca[streamName=cmssupplier,stats=io.airbyte.config.SyncStats@18406df6[recordsEmitted=4787,bytesEmitted=10166739,stateMessagesEmitted=<null>,recordsCommitted=4787]]]],state=io.airbyte.config.State@1924c85b[state={"cdc":false,"streams":[{"cursor":"2022-02-08T10:51:22Z","stream_name":"cmssupplier","cursor_field":["updateon"],"stream_namespace":"officemate"}]}],outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@7d3df984[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@2b0483e7[stream=io.airbyte.protocol.models.AirbyteStream@2e27396a[name=cmssupplier,jsonSchema={"type":"object","properties":{"poamt":{"type":"number"},"rebate":{"type":"string"},"sfaxno":{"type":"string"},"staxid":{"type":"string"},"country":{"type":"string"},"prepaid":{"type":"number"},"saddrno":{"type":"string"},"sfaxext":{"type":"string"},"sfaxoth":{"type":"string"},"sstatus":{"type":"string"},"altpayee":{"type":"string"},"bankacct":{"type":"string"},"bankname":{"type":"string"},"branchid":{"type":"string"},"createby":{"type":"string"},"createon":{"type":"string"},"currcode":{"type":"string"},"isimport":{"type":"string"},"leadtime":{"type":"number"},"minorder":{"type":"number"},"saddrsoi":{"type":"string"},"sauthfax":{"type":"string"},"sengname":{"type":"string"},"sfaxarea":{"type":"string"},"sfaxcomm":{"type":"string"},"sphoneno":{"type":"string"},"sreftype":{"type":"string"},"stitleid":{"type":"string"},"svatrate":{"type":"number"},"swebsite":{"type":"string"},"updateby":{"type":"string"},"updateon":{"type":"string"},"saddrroad":{"type":"string"},"sauthcomm":{"type":"string"},"sauthname":{"type":"string"},"sinvaddr1":{"type":"string"},"sinvaddr2":{"type":"string"},"sinvaddr3":{"type":"string"},"sinvaddr4":{"type":"string"},"sinvaddr5":{"type":"string"},"smanageid":{"type":"string"},"sphoneext":{"type":"string"},"sphoneno1":{"type":"string"},"sphoneno2":{"type":"string"},"sphoneoth":{"type":"string"},"ssuffixid":{"type":"string"},"lockreason":{"type":"string"},"lockstatus":{"type":"string"},"saddrfloor":{"type":"string"},"sauthphone":{"type":"string"},"semailaddr":{"type":"string"},"sloadaddr1":{"type":"string"},"sloadaddr2":{"type":"string"},"sloadaddr3":{"type":"string"},"sloadaddr4":{"type":"string"},"sloadfaxno":{"type":"string"},"slocalname":{"type":"string"},"sphonearea":{"type":"string"},"ssuppgrpid":{"type":"string"},"stitlename":{"type":"string"},"creditlimit":{"type":"number"},"saddramphur":{"type":"string"},"saddrtumbon":{"type":"string"},"sphonerefno":{"type":"string"},"ssuffixname":{"type":"string"},"ssupplierid":{"type":"string"},"bankaccttype":{"type":"string"},"creditremark":{"type":"string"},"rebateremark":{"type":"string"},"saddrvillage":{"type":"string"},"saddrzipcode":{"type":"string"},"sloadzipcode":{"type":"string"},"spaymentcode":{"type":"string"},"spaymenttype":{"type":"string"},"saddrbuilding":{"type":"string"},"saddrprovince":{"type":"string"},"sauthphoneext":{"type":"string"},"sauthposition":{"type":"string"},"slastsaledate":{"type":"string"},"sloadphoneno1":{"type":"string"},"sloadphoneno2":{"type":"string"},"ssupplieridod":{"type":"string"},"returncriteria":{"type":"string"},"sauthemailaddr":{"type":"string"},"sdiscountrate1":{"type":"number"},"sdiscountrate2":{"type":"number"},"sdiscountrate3":{"type":"number"},"sfirstsaledate":{"type":"string"},"ssupplieridb2s":{"type":"string"},"bankaccountname":{"type":"string"},"consignmentflag":{"type":"string"},"sbusinesstypeid":{"type":"string"},"bankguaranteeamt":{"type":"number"},"deliverylocation":{"type":"string"},"_airbyte_emitted_at":{"type":"string"},"aptrancontrolnature":{"type":"string"},"bankguaranteeremark":{"type":"string"},"aptrancontrolactcode":{"type":"string"},"bankguaranteeexpdate":{"type":"string"},"returncriteriaremark":{"type":"string"},"deliverylocationremark":{"type":"string"},"_airbyte_cmssupplier_hashid":{"type":"string"}}},supportedSyncModes=[full_refresh, incremental],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[updateon],destinationSyncMode=append,primaryKey=[],additionalProperties={}]],additionalProperties={}]]
2022-02-09 09:37:10 INFO i.a.c.p.ConfigRepository(updateConnectionState):545 - Updating connection eb63f52f-c184-458a-bf61-794c841dcf1b state: io.airbyte.config.State@7de9860b[state={"cdc":false,"streams":[{"cursor":"2022-02-08T10:51:22Z","stream_name":"cmssupplier","cursor_field":["updateon"],"stream_namespace":"officemate"}]}]

```

</details>

## Steps to Reproduce
1. Create source from Postgres 
```
| COL1 | COL2 | COL3 |
----------------------
| A    | NULL |  1   |
| B    | NULL |  1   |
| C    | NULL |  1   |
```

2. Set destination as Google Cloud Storage and format is jsonl
3. Run the job, the COL2 will be missing from the output.

### PR DESCRIPTION
**Pull request by sashaNeshcheret**
## What
During synchronizing with GCS all nullable columns are skipping
## How
Logic that skipping nullable columns was removed

## Recommended reading order
1. `x.java`

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by sashaNeshcheret** [comment]
@tuliren we have [issue](https://github.com/airbytehq/airbyte/issues/10230) and for fixing it we need to remove logic about skipping nullable value in PostgresSourceOperations. The same case with AbstractJdbcCompatibleSourceOperations for another jdbc source connectors.  Do you have any concerns about it?

**Review by alexandr-shegeda — APPROVED** [review]

**Comment by alexandr-shegeda** [comment]
@tuliren could you possibly take a look?

**Review by tuliren — CHANGES_REQUESTED** [review]
Sorry that the review request probably came when I was on PTO. So I totally missed it.

> @tuliren we have [issue](https://github.com/airbytehq/airbyte/issues/10230) and for fixing it we need to remove logic about skipping nullable value in `PostgresSourceOperations`. The same case with `AbstractJdbcCompatibleSourceOperations` for another jdbc source connectors. Do you have any concerns about it?

Yes. I have one concern. Currently `setJsonField` does not expect any `null` value. Simply removing this `null` check will probably cause it to fail at some point.

For the minimum, the Postgres integration test should be triggered to see if it works.

**Comment by tuliren** [comment]
Indeed `PostgresSourceDatatypeTest` failed due to `null` issue:

```
2022-04-23 18:16:44 source > Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because the return value of "java.sql.ResultSet.getString(int)" is null
2022-04-23 18:16:44 source > 	at io.airbyte.integrations.source.postgres.PostgresSourceOperations.putBoolean(PostgresSourceOperations.java:142)
2022-04-23 18:16:44 source > 	at io.airbyte.integrations.source.postgres.PostgresSourceOperations.setJsonField(PostgresSourceOperations.java:78)
2022-04-23 18:16:44 source > 	at io.airbyte.integrations.source.postgres.PostgresSourceOperations.rowToJson(PostgresSourceOperations.java:64)
2022-04-23 18:16:44 source > 	at io.airbyte.integrations.source.postgres.PostgresSourceOperations.rowToJson(PostgresSourceOperations.java:30)
```

**Review by tuliren — APPROVED** [review]
Nice. Thanks for the update.

**Comment by tuliren** [comment]
@sashaNeshcheret, when the publication of the connector fails, you should not just keep retrying. The publish command has side effect, and is not idempotent.

The `source-postgres-strict-encrypt` is already successfully published. The version bumping failed. So you just need to bump the version in the seed and update the spec manually.

**Comment by sashaNeshcheret** [comment]
@tuliren what should i do in such case, because i run test for it and it passed successfully, but publish is failed? For source-postgres-strict-encrypt i checked that image with new version is created and rerun it just for checking if it can skip publishing and bump version in specs, but it doesn't work so.

**Comment by grishick** [comment]
Looking at the logs from failed publish action it seems that publishing fails, because several acceptance tests failed:
`2022-05-05T21:03:05.6691046Z SshPasswordPostgresSourceAcceptanceTest > testIncrementalSyncWithState() FAILED`

`2022-05-05T21:03:05.6945658Z SshPasswordPostgresSourceAcceptanceTest > testEmptyStateIncrementalIdenticalToFullRefresh() FAILED`

`2022-05-05T21:03:05.8008249Z SshPasswordPostgresSourceAcceptanceTest > testDiscover() FAILED`

`2022-05-05T21:03:05.7412328Z SshPasswordPostgresSourceAcceptanceTest > testFullRefreshRead() FAILED`

`2022-05-05T21:03:05.7727516Z SshPasswordPostgresSourceAcceptanceTest > testCheckConnection() FAILED`

**Comment by grishick** [comment]
@sashaNeshcheret I don't think continuing to run publish tasks will help here. `SshPasswordPostgresSourceAcceptanceTest` is consistently failing when running publish command even though it is succeeding in test command.

**Comment by grishick** [comment]
I added a timeout to publish command here: https://github.com/airbytehq/airbyte/pull/12679

**Comment by tuliren** [comment]
@grishick, any idea why the publication worked when you tried it?

**Comment by grishick** [comment]
@tuliren I updated publish-command to add a timeout for `publish-image` step. After looking at logs of failed publish commands I theorized that the VM, which was running integration tests was randomly being killed about 20-25 minutes into the test run. I could not find any documentation that would confirm this theory, but adding a timeout to that step helped. This is the [PR](https://github.com/airbytehq/airbyte/pull/12679) where I added the timeout.

**Pull request merged**
