### PR TITLE
Source Klaviyo: Add field[metrics] to events stream

### LINKED ISSUE #44365: Klaviyo source: add `field[metrics]` to `events` stream
## Connector Name
source-klavyio

## ❓ What
Klaviyo users are frustrated when new events are published without the name of the actual metric that occurred. Instead, in the new API they are only given the metric ID and required to cross reference that with the metrics endpoint.

This makes reporting challenging especially when old metrics appear. This requires a big, costly backfill of the metrics data and often requires a start date that is unecessarily old for other streams (i.e. start date impacts all streams)

## 📈  Impact
Users of the Klavyio source can define optional parameters that define which metrics to pull in.

## 🤝 Proposed solution
`get_events` allows optional parameters that define additional data that should be included in the response.

Adding `fields[metrics]` will pull in the metrics metadata for each event.

https://developers.klaviyo.com/en/reference/get_events

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
Closes https://github.com/airbytehq/airbyte/issues/44365

## How
Added field[metrics], and include metric request parameter
Reference documentation: 
https://developers.klaviyo.com/en/reference/get_events

### CODE REVIEW

**Comment by btkcodedev** [comment]
Tested with postman and found no errors while adding the parameters

**Comment by natikgadzhi** [comment]
Good issue to use as an example and figure out transparent access to regression test reports. This PR drops 974 out of 2700ish records ;-) so it's broken, but to best show you what's broken, we should open up the reports. 

I'll see how to get this into your hands quickly.

**Comment by natikgadzhi** [comment]
@btkcodedev resolve the conflicts please — a sneaky deps update added 2.9.4 before this got merged. Could be easier to go for 2.10!

**Comment by btkcodedev** [comment]
@natikgadzhi Fixes applied and CI green, Please continue merge

**Review by natikgadzhi — APPROVED** [review]

**Pull request merged**
