### PR TITLE
Pubsub, Pulsar, Redis, Redshift, Rocket destinations : Enable DAT tests

### PR DESCRIPTION
**Pull request by DoNotPanicUA**
## What
Enable DAT tests https://github.com/airbytehq/airbyte/issues/9443

- Pubsub destination
- Pulsar destination
- Redis destination
- Redshift destination
- Rocket destination

## Recommended reading order
1. `x.java`
2. `y.python`

### CODE REVIEW

**Review by sashaNeshcheret — APPROVED** [review]

**Comment by DoNotPanicUA** [comment]
Followup ticket for the Redshift tests bug #12434

**Pull request merged**
