### PR TITLE
Community PR: Support CMEK or the GCS destination connector

### PR DESCRIPTION
**Pull request by grishick**
## What
rebase and test community PR: https://github.com/airbytehq/airbyte/pull/20351

### CODE REVIEW

**Comment by armsepehr** [comment]
> /publish connector=connectors/destination-gcs
> 
> > 🕑 Publishing the following connectors:connectors/destination-gcshttps://github.com/airbytehq/airbyte/actions/runs/3974170462
> 
> 
> Connector 	Did it publish? 	Were definitions generated?
> connectors/destination-gcs 	❌ 	❌
> 
> if you have connectors that successfully published but failed definition generation, follow [step 4 here ▶️](https://docs.airbyte.com/connector-development/#publishing-a-connector)

is there anything else i should do?

**Comment by marcosmarxm** [comment]
> > /publish connector=connectors/destination-gcs
> > > 🕑 Publishing the following connectors:connectors/destination-gcshttps://github.com/airbytehq/airbyte/actions/runs/3974170462
> > 
> > 
> > Connector 	Did it publish? 	Were definitions generated?
> > connectors/destination-gcs 	❌ 	❌
> > if you have connectors that successfully published but failed definition generation, follow [step 4 here ▶️](https://docs.airbyte.com/connector-development/#publishing-a-connector)
> 
> @grishick is there anything else i should do?

Only need to bump the connector version.

**Review by marcosmarxm — APPROVED** [review]

**Review by edgao — COMMENTED** [review]
I missed this review request earlier today, but LGTM - thanks for publishing+merging!

**Comment by grishick** [comment]
auto-merge FTW

**Pull request merged**
