### PR TITLE
fix(source-qualaroo): updated manifest with proper params

### PR DESCRIPTION
**Pull request by xandercovert**
## What

The Qualaroo connector is failing after a schema update occurred in the UI. Upon local testing, I observed the acceptance tests were failing due to an invalid manifest caused by no `primary_keys` found, stemming rom an invalid properties definition.
https://github.com/airbytehq/airbyte/issues/42538

```
2024-07-25 14:03:15 replication-orchestrator > failures: [ {
  "failureOrigin" : "replication",
  "internalMessage" : "No properties node in stream schema",
  "externalMessage" : "Something went wrong during replication",
  "metadata" : {
    "attemptNumber" : 5,
    "jobId" : 15188960
  },
  "stacktrace" : "java.lang.RuntimeException: No properties node in stream schema\n\tat io.airbyte.workers.internal.FieldSelector.populatedStreamToSelectedFields(FieldSelector.java:152)\n\tat io.airbyte.workers.internal.FieldSelector.populateFields(FieldSelector.java:66)\n\tat io.airbyte.workers.general.ReplicationWorkerHelper.startSource(ReplicationWorkerHelper.kt:254)\n\tat io.airbyte.workers.general.BufferedReplicationWorker.lambda$run$1(BufferedReplicationWorker.java:171)\n\tat io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:235)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\n",
  "timestamp" : 1721916182345
}, {
  "failureOrigin" : "replication",
  "internalMessage" : "io.airbyte.workers.exception.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.",
  "externalMessage" : "Something went wrong during replication",
  "metadata" : {
    "attemptNumber" : 5,
    "jobId" : 15188960
  },
  "stacktrace" : "java.lang.RuntimeException: io.airbyte.workers.exception.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.\n\tat io.airbyte.workers.general.BufferedReplicationWorker$CloseableWithTimeout.lambda$close$0(BufferedReplicationWorker.java:538)\n\tat io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithTimeout$5(BufferedReplicationWorker.java:263)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\nCaused by: io.airbyte.workers.exception.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.\n\tat io.airbyte.workers.internal.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:178)\n\tat io.airbyte.workers.general.BufferedReplicationWorker$CloseableWithTimeout.lambda$close$0(BufferedReplicationWorker.java:536)\n\t... 5 more\n",
```

## How

Updates the manifest structure to ensure it meets the validation requirements.

## User Impact

The sync will now work, instead of getting an invalid node error.

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌
Yes but then the connector will break (again)

### CODE REVIEW

**Comment by xandercovert** [comment]
@natikgadzhi Thanks for releasing the CI job. This is my first PR in Airbyte so please let me know if I am missing anything in this process. This failing integration is a blocker on a large project my team is working on so I am eager to get it resolved!

**Comment by natikgadzhi** [comment]
The integration tests seem to pass, what this thing needs is a version bump. I'm working on a slash command to do it, but for now: 
1. Go to `pyproject.toml` in this connector and bump it's patch version.
2. Same, but in `metadata.yaml`, key `dockerImageTag` — should match what's in pyproject.toml
3. Add a changelog entry with a link to this PR in `docs/integrations/qualaroo.md`. 

Commit those, I will rerun the CI and get this merged!

**Comment by xandercovert** [comment]
> The integration tests seem to pass, what this thing needs is a version bump. I'm working on a slash command to do it, but for now:
> 
> 1. Go to `pyproject.toml` in this connector and bump it's patch version.
> 2. Same, but in `metadata.yaml`, key `dockerImageTag` — should match what's in pyproject.toml
> 3. Add a changelog entry with a link to this PR in `docs/integrations/qualaroo.md`.
> 
> Commit those, I will rerun the CI and get this merged!

@natikgadzhi Done!

**Comment by xandercovert** [comment]
@natikgadzhi All are passing, can the green stamp be issued? 🍏

**Review by natikgadzhi — APPROVED** [review]
Looks good! Automerge is on, should be merged in a few mintes.

**Pull request merged**
