### PR TITLE
Remove debug mode for pytest config

### LINKED ISSUE #1234: Release 0.8.0
Headline features:
* K8s (on at least one cloud platform)
* Incremental can be announced
* First pass at ease of use

### LINKED ISSUE #27128: source-file: abusive debug log outputs
### Connector Name

source-file

### Connector Version

0.3.9

### What step the error happened?

Other

### Revelant information

When running integration tests the source-file connector outputs a lot of logs like:
```
{"type": "DEBUG", "message": "{'uri': 's3://aws_access_key_id:aws_secret_access_key@my_bucket/my_key', 'mode': 'r', 'buffering': -1, 'encoding': None, 'errors': None, 'newline': None, 'closefd': True, 'opener': None, 'compression': 'infer_from_extension', 'transport_params': None}", "data": {}}
```

It can potentially leak secrets.

### Relevant log output

_No response_

### Contribute

- [ ] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by lazebnyi**
## What:
This pull request suggests removing the debug mode from the `pyproject.toml` configuration file for tests. Developers can manually adjust the log level when they need to debug a test.

## How:
- Removed the debug log level from the `pyproject.toml` configuration file for tests.
- Force log level for smart open to `ERROR`

## Justification:
When working with source files, we utilize the `open()` method from the smart open library to open files - [here](https://github.com/airbytehq/airbyte/blob/9335a4d5101dd5ebecdb5f73781510d4737ff4fa/airbyte-integrations/connectors/source-file/source_file/client.py#L234). However, this method also logs local variables before opening the file - [here](https://github.com/RaRe-Technologies/smart_open/blob/7ab4dda19a34014199cba13fdfaa0794a071adad/smart_open/s3.py#L283) and [here](https://github.com/RaRe-Technologies/smart_open/blob/7ab4dda19a34014199cba13fdfaa0794a071adad/smart_open/smart_open_lib.py#L166). Simultaneously, we employ the `pyproject.toml` configuration file with the debug log level enabled to execute our `unit/coverage/integration tests` - [here](https://github.com/airbytehq/airbyte/blob/9335a4d5101dd5ebecdb5f73781510d4737ff4fa/pyproject.toml#L85). As a result, all the arguments passed to the `open()` method will be displayed in the output.

## Related Issues:
Fixes https://github.com/airbytehq/airbyte/issues/27128

### Checklist:
- [x] Removed debug mode from `pyproject.toml` for tests
- [x] Ran unit tests to ensure there are no regressions

### CODE REVIEW

**Comment by alafanechere** [comment]
Can we also force the log level of the `smart-open` logger and set it to error? I'm affraid that this problem can occur again on `source-file` if a context different than test also enables the debug log level?

**Review by alafanechere — APPROVED** [review]

**Review by davydov-d — APPROVED** [review]

**Pull request merged**
