### PR TITLE
Remove AlloyDB phase 1: Remove from registry

### PR DESCRIPTION
**Pull request by evantahler**
Cloud: no users
OSS: existing OSS users will already have an actor definition (version) and still be able to use the connector

Next Step: 
* remove the folder after this last registry publish
* tombstone the connector in Airbyte Cloud

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-alloydb test report (commit [`661a45bfb4`](https://github.com/airbytehq/airbyte/pull/31144/commits/661a45bfb4cb9d4524dac425f51061dfc727e22f)) - ❌

⏲️  Total pipeline duration: 38.46s 

| Step                                 | Result   |
|:-------------------------------------|:---------|
| Validate metadata for source-alloydb | ✅        |
| Connector version semver check       | ✅        |
| Connector version increment check    | ❌        |
| QA checks                            | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_no-more-alloydb/1696628352/661a45bfb4cb9d4524dac425f51061dfc727e22f/source-alloydb/3.1.8/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:661a45bfb4cb9d4524dac425f51061dfc727e22f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-alloydb test
```

**Review by erohmensing — APPROVED** [review]
bye, you will not be missed

**Comment by airbyte-oss-build-runner** [comment]
##  source-alloydb test report (commit [`9c096d53fa`](https://github.com/airbytehq/airbyte/pull/31144/commits/9c096d53fa833eb5fd8e68df2568d41ca1fe1ae2)) - ❌

⏲️  Total pipeline duration: 33.54s 

| Step                                 | Result   |
|:-------------------------------------|:---------|
| Validate metadata for source-alloydb | ✅        |
| Connector version semver check       | ✅        |
| Connector version increment check    | ❌        |
| QA checks                            | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_no-more-alloydb/1696628521/9c096d53fa833eb5fd8e68df2568d41ca1fe1ae2/source-alloydb/3.1.8/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:9c096d53fa833eb5fd8e68df2568d41ca1fe1ae2)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-alloydb test
```

**Comment by octavia-approvington** [comment]
Trying to merge your PR using a bot?
Comment this on the PR:
```
/approve-and-merge reason="<STATE YOUR REASON HERE>"
```
Make sure you've reviewed the [docs](https://internal-docs.airbyte.io/How-Tos/Overriding-PR-Merge-Rules)!

**Comment by octavia-approvington** [comment]
This is really good <br/> simply the best

**Review by octavia-approvington — APPROVED** [review]

**Comment by evantahler** [comment]
https://github.com/airbytehq/airbyte/pull/31145 is the next step

**Pull request merged**
