### PR TITLE
Source Orb: Migrate to manifest-only format with components

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
Source Orb: Migrate to manifest-only formats with components

## How
Migrated to inline schemas
Migrated spec
Migrated to manifest only with ci

## Migration report
image

### CODE REVIEW

**Comment by btkcodedev** [comment]
/bump-version type="minor" changelog="Migrate to manifest only format"

**Review by ChristoGrab — APPROVED** [review]
LGTM! The schema failure is due to the `description` field in `credits_ledger_entries` being listed as required despite not being returned from the API (their docs might be out of date, as they list it as required there as well).

Generally speaking we allow all fields to be nullable (as long as primary keys and cursor fields aren't flaky), so if more fields complain we can just remove them from the list of required fields in the stream schemas.

Approving and will keep an eye on CI 👀, thanks @btkcodedev!

**Comment by ChristoGrab** [comment]
CI is still moaning about required fields, so I nuked everything that wasn't an id or a cursor field; hopefully this will auto-merge now

**Pull request merged**
