### PR TITLE
🎉 New Source: Freshsales

### PR DESCRIPTION
**Pull request by tuanchris**
## What
 - Create a new source for Freshales. API document [here](https://developers.freshworks.com/crm/api/#introduction)
 - Participating in hacktoberfest-2021, [issue no 33](https://github.com/airbytehq/hacktoberfest-2021/issues/33)
## How
*Describe the solution*
image
Connection ran successfully in local env. 
image
Stream settings
image
Local JSON files
image
Example output

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Comment by tuanchris** [comment]
@marcosmarxm I actually did that with BigQuery, hope that it is fine too. All seems to be working well but this. 

```
2021-10-13 16:53:03 INFO () LineGobbler(voidCall):65 - 16:53:03 | 9 of 10 ERROR creating table model freshsales.open_tasks..................................................... [ERROR in 3.99s]
2021-10-13 16:53:03 INFO () LineGobbler(voidCall):65 - 16:53:03 | 
2021-10-13 16:53:03 INFO () LineGobbler(voidCall):65 - 16:53:03 | Finished running 10 table models in 6.65s.
2021-10-13 16:53:03 INFO () LineGobbler(voidCall):65 - 
2021-10-13 16:53:03 INFO () LineGobbler(voidCall):65 - Completed with 2 errors and 0 warnings:
2021-10-13 16:53:03 INFO () LineGobbler(voidCall):65 - 
2021-10-13 16:53:03 INFO () LineGobbler(voidCall):65 - Database Error in model completed_tasks (models/generated/airbyte_tables/freshsales/completed_tasks.sql)
2021-10-13 16:53:03 INFO () LineGobbler(voidCall):65 -   Bad bool value: 1
2021-10-13 16:53:03 INFO () LineGobbler(voidCall):65 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/freshsales/completed_tasks.sql
2021-10-13 16:53:03 INFO () LineGobbler(voidCall):65 - 
2021-10-13 16:53:03 INFO () LineGobbler(voidCall):65 - Database Error in model open_tasks (models/generated/airbyte_tables/freshsales/open_tasks.sql)
2021-10-13 16:53:03 INFO () LineGobbler(voidCall):65 -   Bad bool value: 0
2021-10-13 16:53:03 INFO () LineGobbler(voidCall):65 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/freshsales/open_tasks.sql
2021-10-13 16:53:03 INFO () LineGobbler(voidCall):65 - 
2021-10-13 16:53:03 INFO () LineGobbler(voidCall):65 - Done. PASS=8 WARN=0 ERROR=2 SKIP=0 TOTAL=10
```

Should I change the boolean schema to integer or what is the preferred way of dealing with this?

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Some comments, but overall looks good! I'll set up this locally and test. Can you check the comments?

**Comment by marcosmarxm** [comment]
Hi @tuanchris the unit tests are not passing, can you check them?

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Unit tests are not passing.
```
================================================================================ short test summary info ================================================================================
FAILED unit_tests/test_source.py::test_check_connection - assert (False,\n ConnectionError(MaxRetryError('HTTPSConnectionPool(host="%3cmagicmock%20name=\'mock.__getitem__()\'%20id=\'...
FAILED unit_tests/test_streams.py::test_request_params - TypeError: __init__() missing 1 required positional argument: 'domain_name'
FAILED unit_tests/test_streams.py::test_next_page_token - TypeError: __init__() missing 1 required positional argument: 'domain_name'
FAILED unit_tests/test_streams.py::test_parse_response - TypeError: __init__() missing 1 required positional argument: 'domain_name'
FAILED unit_tests/test_streams.py::test_request_headers - TypeError: __init__() missing 1 required positional argument: 'domain_name'
FAILED unit_tests/test_streams.py::test_http_method - TypeError: __init__() missing 1 required positional argument: 'domain_name'
FAILED unit_tests/test_streams.py::test_should_retry[HTTPStatus.OK-False] - TypeError: __init__() missing 1 required positional argument: 'domain_name'
FAILED unit_tests/test_streams.py::test_should_retry[HTTPStatus.BAD_REQUEST-False] - TypeError: __init__() missing 1 required positional argument: 'domain_name'
FAILED unit_tests/test_streams.py::test_should_retry[HTTPStatus.TOO_MANY_REQUESTS-True] - TypeError: __init__() missing 1 required positional argument: 'domain_name'
FAILED unit_tests/test_streams.py::test_should_retry[HTTPStatus.INTERNAL_SERVER_ERROR-True] - TypeError: __init__() missing 1 required positional argument: 'domain_name'
FAILED unit_tests/test_streams.py::test_backoff_time - TypeError: __init__() missing 1 required positional argument: 'domain_name'
```

**Comment by marcosmarxm** [comment]
Unit tests are passing but Integration tests aren't.
```
=========================== short test summary info ============================
FAILED test_core.py::TestBasicRead::test_read[inputs0] - AssertionError:  Rec...
FAILED test_full_refresh.py::TestFullRefresh::test_sequential_reads[inputs0]
=================== 2 failed, 10 passed, 1 skipped in 53.96s ===================
```

Make sure `./gradlew airbyte-integrations:connectors:source-freshsales:integrationTest` is working and share a screenshoot showing the result.

**Comment by tuanchris** [comment]
@marcosmarxm I removed the `fc_widget_collaboration` column and integration tests passed 
image

**Review by marcosmarxm — APPROVED** [review]
thanks @tuanchris now integration test are working.

**Pull request merged**
