### PR TITLE
🐛 Destination BigQuery: updated schema to keep the backward compatibility

### LINKED ISSUE #5959: Mysterious switch of data type for <_airbyte_emitted_at> field crashes incremental jobs
## Enviroment
- **Airbyte version**:  0.28.2 and 0.29.16
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Postgres 0.3.11, but potentially all connectors 
- **Destination Connector and version**: BigQuery 0.4.0 
- **Severity**: Medium 
- **Step where error happened**: Sync job (after attempt to Upgrade Airbyte)

## Current Behavior
This problem occurred after we attempted to upgrade Airbyte from 0.28.2 to 0.29.16, found that it wouldn't start, and took it back to 0.28.2.

Previous to the failed upgrade, the field `_airbyte_emitted_at ` was copied to BigQuery (into the `_airbyte_raw` tables) a TIMESTAMP.  After the failed upgrade, it started coming in as a STRING, which is not backwards compatible with the existing tables that were supporting incremental updates.  

## Expected Behavior

The change from type TIMESTAMP to STRING for the field `_airbyte_emitted_at ` shouldn't have occurred, or if it did, shouldn't have caused incremental jobs to fail.  `_airbyte_emitted_at ` is more useful as a TIMESTAMP in general.
[logs-786-0.txt](https://github.com/airbytehq/airbyte/files/7139628/logs-786-0.txt)

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

2021-09-08 21:58:32 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-08 21:58:32 [1;31mERROR[m i.a.i.d.b.BigQueryUtils(waitForQuery):77 - {} - Failed to wait for a query job:Job{job=JobId{project=tfc-warehouse, job=322cd030-b362-4b7c-8fa0-ceb211faf7c7, location=US}, status=JobStatus{state=DONE, error=BigQueryError{reason=invalid, location=null, message=Provided Schema does not match Table tfc-warehouse:tabella_ads_raw._airbyte_raw_daily_fb_advertisers_with_date. Field _airbyte_emitted_at has changed type from TIMESTAMP to STRING}, executionErrors=[BigQueryError{reason=invalid, location=null, message=Provided Schema does not match Table tfc-warehouse:tabella_ads_raw._airbyte_raw_daily_fb_advertisers_with_date. Field _airbyte_emitted_at has changed type from TIMESTAMP to STRING}]}, statistics=CopyStatistics{creationTime=1631138312224, endTime=1631138312263, startTime=1631138312263, numChildJobs=null, parentJobId=null, scriptStatistics=null, reservationUsage=null}, userEmail=airbyte-ingest@tfc-warehouse.iam.gserviceaccount.com, etag=3vRiAbImCRKezu0/B1qWbQ==, generatedId=tfc-warehouse:US.322cd030-b362-4b7c-8fa0-ceb211faf7c7, selfLink=https://www.googleapis.com/bigquery/v2/projects/tfc-warehouse/jobs/322cd030-b362-4b7c-8fa0-ceb211faf7c7?location=US, configuration=CopyJobConfiguration{type=COPY, sourceTables=[GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=tabella_ads_raw, projectId=tfc-warehouse, tableId=_airbyte_tmp_xjx_daily_fb_advertisers_with_date}}], destinationTable=GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=tabella_ads_raw, projectId=tfc-warehouse, tableId=_airbyte_raw_daily_fb_advertisers_with_date}}, destinationEncryptionConfiguration=null, createDisposition=CREATE_IF_NEEDED, writeDisposition=WRITE_APPEND, labels=null, jobTimeoutMs=null}}

```

</details>

## Steps to Reproduce
1.  Set up any incremental sync with new daily data, with an Airbyte version that writes `_airbyte_emitted_at ` as a TIMESTAMP
2.  Change to an Airbyte version that writes `_airbyte_emitted_at ` as a STRING
3.  Job fails

### PR DESCRIPTION
**Pull request by etsybaev**
## What
Recently emitted_at column was changed from Timestamp to String type

## How
Set it back to Timestamp.
Checked it on local PC for Standard and GCS uploading modes. See capture below

Selection_080
Selection_081
Selection_082
Selection_083
Selection_084
Selection_085
Selection_086

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

### CODE REVIEW

**Review by irynakruk — APPROVED** [review]
Please don't forget to bump version in docker file and other dependent files.

**Comment by etsybaev** [comment]
integration tests pass on CI and if I run them independently or even class by class locally, but we have some failures when running a whole set.
Since failures are not obvious as it doesn't say what exactly went wrong and it would take pretty much time for investigation - have to put it on hold and switch back when have time. 
Unless someone steps in and find the exact reason of conflicts between the tests
 ./gradlew clean :airbyte-integrations:connectors:destination-bigquery:integrationTest
 
 
https://github.com/airbytehq/airbyte/runs/3567861286?check_suite_focus=true

**Comment by sherifnada** [comment]
@etsybaev anything blocking review from my side?

**Comment by etsybaev** [comment]
> @etsybaev anything blocking review from my side?

Hi @sherifnada. Nope, nothing for now. I see it works on UI, but sometimes randomly fails on integration tests (at normalization step).  Would need to spend more time for investigation once finished with other tasks. Maybe some kind of race condition. 
Thanks

**Review by ChristopheDuong — CHANGES_REQUESTED** [review]
We could probably close this as the fix was done in https://github.com/airbytehq/airbyte/pull/7240

**Pull request closed without merging**
