### PR TITLE
:tada: New Destination: R2 Cloudflare

### LINKED ISSUE #13790: New Destination: R2 Cloudflare
## Tell us about the new connector you’d like to have
It will be great if we can use R2 as destination.
https://www.cloudflare.com/products/r2/

## Describe the context around this new connector
R2 is fully compatible with S3 api.

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

## Are you willing to submit a PR?

Remove this with your answer :-)

### PR DESCRIPTION
**Pull request by videnkz**
## What
- Closes #13790
- The connector is published in #17122.

## 🚨 User Impact 🚨
None expected.

## Tests
- [x] S3
- [x] GCS
- [x] Snowflake
- [x] Redshift
- [x] BigQuery
- [x] BigQuery Denormalized
- [x] Databricks

## Pre-merge checks
- See #17122.

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@kananindzya let us know when this contribution is ready to review.

**Comment by marcosmarxm** [comment]
@kananindzya can you check the commits, there are lot of files changes.

**Comment by kananindzya** [comment]
> @kananindzya can you check the commits, there are lot of files changes.

I moved all the current functionality of destination-s3 to the base-java-s3 module, since the functionality is completely identical for destination-r2. I also put integration tests in a separate module

**Comment by tuliren** [comment]
> I moved all the current functionality of destination-s3 to the base-java-s3 module

Thanks a ton for the refactoring! This is long overdue.

**Comment by tuliren** [comment]
@kananindzya, @knugusbayevps, please don't forget to sign the CLA.

**Comment by tuliren** [comment]
@kananindzya, there are compilation errors from `destination-snowflake`. Could you check all the related connectors and fix those errors?

**Comment by kananindzya** [comment]
> @kananindzya, there are compilation errors from `destination-snowflake`. Could you check all the related connectors and fix those errors?

Sorry, I fixed it

**Comment by kananindzya** [comment]
> @kananindzya, @knugusbayevps, please don't forget to sign the CLA.

is it ok now?

**Comment by kananindzya** [comment]
@tuliren I disabled `R2ParquetDestinationAcceptanceTest` test, because cloudflare R2 not supports s3a client.  I opened issue for this - https://community.cloudflare.com/t/r2-support-of-s3a/410663 .
Should I delete `PARQUET` format from R2 specification and documentation?

**Comment by tuliren** [comment]
> Should I delete PARQUET format from R2 specification and documentation?

That sounds good.

@kananindzya, I plan to merge this PR this week. Currently there are some merge conflicts. Would you mind granting me the write access to your fork? In that way, I can update this PR directly, and resolve some of the conflicts myself.

**Comment by kananindzya** [comment]
> > > Should I delete PARQUET format from R2 specification and documentation?
> > 
> > 
> > That sounds good.
> > @kananindzya, I plan to merge this PR this week. Currently there are some merge conflicts. Would you mind granting me the write access to your fork? In that way, I can update this PR directly, and resolve some of the conflicts myself.
> 
> Hi @tuliren
> 
> 1. I gave access to you.
> 2. Deleted `parquet` format from specification.
> 3. Updated branch
> 4. Added configuration for upload threads count. I've found limitations in R2 docs(https://developers.cloudflare.com/r2/platform/s3-compatibility/api/#implemented-object-level-operations).
>    On my environment I catch exception below:
> 
> ```
> 022-09-03 02:06:55 �[43mdestination�[0m > 2022-09-03 02:06:55 �[1;31mERROR�[m a.m.s.StreamTransferManager(abort):432 - Aborting [Manager uploading to path/to/my/bucket/xxx/2022_09_03_1662168027012_.csv with id AMAM7OnPp...esYGAxA==] due to error: com.amazonaws.services.s3.model.AmazonS3Exception: There was a problem with the multipart upload. (Service: Amazon S3; Status Code: 400; Error Code: InvalidPart; Request ID: null; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
> 2022-09-03 02:06:55 �[43mdestination�[0m > 2022-09-03 02:06:55 �[1;31mERROR�[m i.a.i.d.s.S3StorageOperations(uploadRecordsToBucket):128 - Failed to upload records into storage path/to/my/bucket/xxx/2022_09_03_1662168027012_
> 2022-09-03 02:06:55 �[43mdestination�[0m > java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.amazonaws.AbortedException: 
> 2022-09-03 02:06:55 �[43mdestination�[0m > 	at alex.mojaki.s3upload.ExecutorServiceResultsHandler$1.next(ExecutorServiceResultsHandler.java:72) ~[s3-stream-upload-2.2.2.jar:?]
> ```

Hi @tuliren ,
Today I tested multipart upload with concurrent thread count = 3. 
Uploading finished success for file with 30mb size(part size - 5mb)

**Review by tuliren — APPROVED** [review]

**Comment by tuliren** [comment]
All integration tests have passed. I will merge this PR, and publish the connector in a separate one.

**Comment by tuliren** [comment]
@kananindzya, the R2 connector has been published to docker:
https://hub.docker.com/r/airbyte/destination-r2/tags

Thanks a lot for your contribution.

Don't forget to remove me from your repo.

**Pull request merged**
