### PR TITLE
Source Aws-cloudtrail: Migrate to manifest-only format with components

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
Source AWS-Cloudtrail: Migrate to manifest-only formats with components

## How
Migrated to inline schemas
Migrated spec
Migrated to manifest only with ci

## Migration report
image

### CODE REVIEW

**Comment by btkcodedev** [comment]
/bump-version type="minor" changelog="Migrate to manifest only format"

**Comment by btkcodedev** [comment]
All checks passing other than spec error

**Review by ChristoGrab — APPROVED** [review]
Looks like we don't have usable sandbox creds, but I was able to test locally using my own AWS account. I don't have any seed data, but the auth flow succeeded; since the custom component in question is the authenticator, I'm gonna say "good enough for me". Thanks @btkcodedev!

**Pull request merged**
