### PR TITLE
🎉 Added new icons and updated old

### LINKED ISSUE #13491: Update logos to optimize UX
## What
#13357

## How
- find and add missing or not appropriate icons to `airbyte-config`
- edited each `source_difinitions.yaml` & `destination_definitions.yaml` with missing icons property
- edited each `seed` with missing icons property

### PR DESCRIPTION
**Pull request by lazebnyi**
## What
#13491 - Update logos to optimize UX

## How
Added new icons and updated old

### CODE REVIEW

**Review by Phlair — COMMENTED** [review]
The quality on some of these looks a bit funky. I'm going to say frontend team should review this rather than just me.

**Review by Phlair — APPROVED** [review]
I'm not entirely which team _owns_ the icons for connectors, hence the request to @airbytehq/frontend, but lgtm.

**Comment by tealjulia** [comment]
I'll have design take a look @Phlair & @lazebnyi, thanks!

**Review by Phlair — CHANGES_REQUESTED** [review]
Switching my review based on feedback from Design ^

**Comment by Upmitt** [comment]
@lazebnyi - I just sent you an invite, you should have access now

**Comment by lazebnyi** [comment]
@Phlair @Upmitt updated icons from figma

**Comment by sherifnada** [comment]
I think @Upmitt should approve here

**Comment by andyjih** [comment]
@Upmitt Will be back next week.

**Comment by Upmitt** [comment]
This logos need to be updated (bad quality or wrong padding) - This logos were not in my Figma file, I'll let you know as soon as I update Figma (will try to do that tomorrow morning)

Other logos seems ok :)

Screenshot 2022-08-11 at 16 16 50
Screenshot 2022-08-11 at 16 17 05
Screenshot 2022-08-11 at 16 17 10
Screenshot 2022-08-11 at 16 17 21
Screenshot 2022-08-11 at 16 17 25

Screenshot 2022-08-11 at 16 15 49
Screenshot 2022-08-11 at 16 15 57
Screenshot 2022-08-11 at 16 16 09
Screenshot 2022-08-11 at 16 16 14
Screenshot 2022-08-11 at 16 16 25
Screenshot 2022-08-11 at 16 16 32
Screenshot 2022-08-11 at 16 16 38
Screenshot 2022-08-11 at 16 16 46
Screenshot 2022-08-11 at 16 14 03
Screenshot 2022-08-11 at 16 14 16
Screenshot 2022-08-11 at 16 14 20
Screenshot 2022-08-11 at 16 14 36
Screenshot 2022-08-11 at 16 14 53
Screenshot 2022-08-11 at 16 14 59
Screenshot 2022-08-11 at 16 15 05
Screenshot 2022-08-11 at 16 15 18
Screenshot 2022-08-11 at 16 15 35
Screenshot 2022-08-11 at 16 15 44

**Comment by Upmitt** [comment]
@andyjih  here are the new .svg
Apify
bigcommerce
faker
firebolt
freshservice
Hellobaton
Lever
LinkedIn_Ads
Mailgun
Mariadb
Monday
Outreach
Prestashop
Redis
Retently
Salesloft
searchmetrics
sentry
talkdesk_explore
tidb
trello
webflow
zendesk_support
zenloop
zohocrm
:

**Comment by lmossman** [comment]
@Upmitt I don't see an icon for Orbit in [the figma](https://www.figma.com/file/gMNRYVJav25pdsoxAyW7Qp/00_01_WEB-APP-LIBRARIES?node-id=898%3A2025) - is this one okay as is or do you want to create a new icon for it?

image

**Comment by lmossman** [comment]
@Upmitt I don't see anything in the [icon figma](https://www.figma.com/file/gMNRYVJav25pdsoxAyW7Qp/00_01_WEB-APP-LIBRARIES?node-id=2%3A7329) for these connectors, which currently have icons that don't seem to match the padding that you have used in the updated icons above:

| Connector name | Current icon |
| ----------------- | ------------ |
| Orbit | https://github.com/airbytehq/airbyte/blob/f8273c5a6e06dfe00374da973850d3470e59d090/airbyte-config/init/src/main/resources/icons/orbit.svg |
| Cassandra | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/cassandra.svg |
| Chartmogul | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/chartmogul.svg |
| Close | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/close.svg |
| Cloudflare R2 | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/cloudflare-r2.svg |
| Commerce Tools | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/commercetools.svg |
| Delighted | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/delighted.svg |
| Dynamo DB | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/dynamodb.svg |
| Elasticsearch | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/elasticsearch.svg |
| Exchange Rates API | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/exchangeratesapi.svg |
| Firestore | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/firestore.svg |
| Flexport | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/flexport.svg |
| Freshsales | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/freshsales.svg |
| Glassfrog | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/glassfrog.svg |
| Google Directory | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/googledirectory.svg |
| Google Workspace | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/googleworkpace.svg |
| Harness | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/harness.svg |
| Jenkins | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/jenkins.svg |
| Kinesis | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/kinesis.svg |
| Lemlist | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/lemlist.svg |
| Linnworks | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/linnworks.svg |
| MQTT | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/mqtt.svg |
| My Hours | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/my-hours.svg |
| OneSignal | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/onesignal.svg |
| Paystack | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/paystack.svg |
| PersistIq | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/persistiq.svg |
| Primetric | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/primetric.svg |
| Pulsar | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/pulsar.svg | 
| Qualaroo | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/qualaroo.svg |
| Scylla | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/scylla.svg |
| Short.io | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/short.svg |
| Sqlite | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/sqlite.svg |
| Strava | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/strava.svg |
| Streamr | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/streamr.svg |
| Timely | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/timely.svg |
| VictorOps | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/victorops.svg |
| Zenefits | https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/icons/zenefits.svg |

**Comment by lmossman** [comment]
@Upmitt Also, the padding around the SVGs makes them look a little small to me in the UI with the current size of the icon:
Screen Shot 2022-09-26 at 5 39 25 PM

Is this desired? Or should we change increase/adjust size of the icon container at all to make these slightly larger?

**Comment by Upmitt** [comment]
AWESOME!! Thank you @lmossman  !! I'll create the missing icons :) regarding the size, I use those square Icons in all my designs, for example in the dropdowns: https://www.figma.com/file/gMNRYVJav25pdsoxAyW7Qp/00_01_WEB-APP-LIBRARIES?node-id=1406%3A2576 - I think you can reduce the space between icon and name, and increase the Icon size (34px in Figma) Thank you again !

**Comment by lazebnyi** [comment]
@Upmitt could you check PR again plz

**Comment by lazebnyi** [comment]
Hey @YowanR 
Could you please help prioritize this PR for Airbyte review 😊

**Comment by timroes** [comment]
Adding to what Lake said here: A lot of the icons now have a margin around them in the SVG. This should not be done. @Upmitt You mentioend we can increase them in the UI, but this PR adds this marging inside the SVGs, so we can't really do that. In general the icon files should imho not have any unnecessary padding around the actual icon (except in one dimension to make it squared).

COuld we please make sure that all icons in this PR are properly trimmed so the icon is touching the border?

**Review by timroes — CHANGES_REQUESTED** [review]
Couple of other things despite the padding, that I noticed:

* airbyte-config/init/src/main/resources/icons/azureblobstorage.svg has a white background behind the logo that it didn't had beforehand
* airbyte-config/init/src/main/resources/icons/zohocrm.svg has a white background as well, that should be transparent
* airbyte-config/init/src/main/resources/icons/orbit.svg has a white background. Also it looks to me like a really badly traced bitmap? Is there any chance we can get a proper SVG logo here?
* airbyte-config/init/src/main/resources/icons/openweather.svg has a white background
* airbyte-config/init/src/main/resources/icons/linkedinads.svg has a white background
* airbyte-config/init/src/main/resources/icons/github.svg We're using here the logo meant for larger presentation (the one that has the dots in the tail). Since we usually show them rather small I'd suggest we stay with the one that is meant for smaller screens (without dots in the tail)

Questions:
* Is there a specific reason we're going for Stripe from the nicely squared logo (that would fit well in our UI) to the more stretched text one, that will look worse in a squared context?

**Comment by timroes** [comment]
A note. A community member opened https://github.com/airbytehq/airbyte/pull/19346 which also corrects a lot of the squaring. I'd suggest we first merge the community PR, so we're not having that require too much more merge conflicts and then continue on this PR here, with the remaining icons.

**Comment by lazebnyi** [comment]
Hi @timroes
So we can close this PR?

**Comment by timroes** [comment]
@lazebnyi Yes I think we can close this PR. Nico is working on the full icon set, and we'd then open a new PR once we have the renewed icons.

**Pull request closed without merging**
