### PR TITLE
[WIP] Monorepo docs updates

### PR DESCRIPTION
**Pull request by Amruta-Ranade**
Addresses https://github.com/airbytehq/airbyte/issues/22515

The deployment docs and the OSS getting started guide don't seem to need any updates. Need confirmation on the following sections (all discuss adding a connector to Airbyte):
https://docs.airbyte.com/connector-development/tutorials/building-a-python-source#step-11-add-the-connector-to-the-apiui
https://docs.airbyte.com/integrations/custom-connectors#adding-your-connectors-in-the-ui
https://docs.airbyte.com/connector-development/tutorials/cdk-tutorial-python-http/use-connector-in-airbyte
https://docs.airbyte.com/contributing-to-airbyte/developing-locally#add-a-connector-under-development-to-airbyte

### CODE REVIEW

**Comment by cgardens** [comment]
- [ ] https://docs.airbyte.com/connector-development/tutorials/building-a-python-source#step-11-add-the-connector-to-the-apiui - @evantahler can you verify if this doc will still be right after the monorepo split?
- [x] https://docs.airbyte.com/integrations/custom-connectors#adding-your-connectors-in-the-ui - i am verifying that this will still be the same. **no change needed.**
- [ ] https://docs.airbyte.com/connector-development/tutorials/cdk-tutorial-python-http/use-connector-in-airbyte - pretty sure this will be the same after the monorepo split. @sherifnada to confirm.
- [ ] https://docs.airbyte.com/contributing-to-airbyte/developing-locally#add-a-connector-under-development-to-airbyte - this one will be out of date @sherifnada can you advice @Amruta-Ranade on how to update this one? i think the new guidance was to do it in the ui.

**Review by evantahler — APPROVED** [review]

**Comment by evantahler** [comment]
>  https://docs.airbyte.com/connector-development/tutorials/building-a-python-source#step-11-add-the-connector-to-the-apiui - @evantahler can you verify if this doc will still be right after the monorepo split?

I think the location of that actor definition files is likely to stay the same in short term, within the monorepo.  The plan is to remove them within a month or so, but that will be done by the connector metadata project, removing the composite actor definition YAMLs entirely.  I don't _think_ there will be an intermediate change in which we relocate those files while they still exist

CC @bnchrch

**Comment by sherifnada** [comment]
https://docs.airbyte.com/contributing-to-airbyte/developing-locally/#add-a-connector-under-development-to-airbyte cc @Amruta-Ranade suggested edits here is to remove the `gradlew build` command in those docs. otherwise it should be the same.

**Comment by Amruta-Ranade** [comment]
> https://docs.airbyte.com/contributing-to-airbyte/developing-locally/#add-a-connector-under-development-to-airbyte cc @Amruta-Ranade suggested edits here is to remove the `gradlew build` command in those docs. otherwise it should be the same.

cc @cpdeethree I think this is related to your [PR](https://github.com/airbytehq/airbyte/pull/22947)

**Review by c-p-b — APPROVED** [review]

**Pull request merged**
