### PR TITLE
Bump com.networknt:json-schema-validator to latest version

### LINKED ISSUE #16406: Upgrade json-schema-validator
At the time of writing, Airbyte is using version [1.0.42](https://github.com/airbytehq/airbyte/blob/master/airbyte-json-validation/build.gradle#L6) which is 2+ years old.

I currently have a spec which contains a pretty large `oneOf` (~30 subschemas) and I'm being affected by [this bug](https://github.com/networknt/json-schema-validator/pull/361) in the json-schema-validator library.

### PR DESCRIPTION
**Pull request by evantahler**
Closes https://github.com/airbytehq/airbyte/issues/16406

> I currently have a spec which contains a pretty large oneOf (~30 subschemas) and I'm being affected by https://github.com/networknt/json-schema-validator/pull/361 in the json-schema-validator library.

Bumps `com.networknt:json-schema-validator` to latest version.

... all the tests seem to be passing.

**Reviewers**: Other than ensuring all the tests pass, what else should I check?

### CODE REVIEW

**Review by jdpgrailsdev — APPROVED** [review]
:shipit: As this is used in multiple places, it may make sense to add it to the dependency bundles in `deps.toml` to only have to reference/update the version in one place going forward.

**Review by davinchia — APPROVED** [review]

**Comment by davinchia** [comment]
Same comment as Jonathan if you have time!

We can add an entry similar to [this](https://github.com/airbytehq/airbyte/blob/master/deps.toml#L74) and consume this just like [this](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-kafka/build.gradle#L33) to centralise the declarations.

**Comment by evantahler** [comment]
I couldn't get the TOML part to work.

```
// deps.toml
[versions]
json-schema-validator_version = "1.0.72"

[libraries]
json-schema-validator = { module = "com.networknt:json-schema-validator", version.ref = "json-schema-validator_version" }

// build.gradle
dependencies {
  implementation libs.json-schema-validator
}
```

produced

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/evan/workspace/airbyte/airbyte/airbyte-json-validation/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating project ':airbyte-json-validation'.
> Could not get unknown property 'schema' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

I'll merge this in as-is for now just to get things moving...

**Comment by jdpgrailsdev** [comment]
@evantahler It's a bit tricky.  The dashes become dots (`.`) when referencing it in the build.gradle file:  `implementation libs.json.schema.validator`.

**Pull request merged**
