### PR TITLE
:tada: Source Iterable - API key is passed in headers

### LINKED ISSUE #12669: Source Iterable: apikey should go through `request headers` instead as `query param`
## Environment
- **Airbyte version**:  latest
- **OS Version** : Ubuntu 22.04
- **Deployment**: N/A
- **Source Connector and version**: Iterable 0.1.15
- **Destination Connector and version**: N/A
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**:  Sync job 

## Current Behavior
Connector sync fails with 401 as response code status due to not set the api-key through request headers.
For more info [Iterable API-keys docs](https://support.iterable.com/hc/en-us/articles/360043464871-API-Keys-#using-api-keys)

## Logs

<details>
<summary>LOG</summary> 

```json
{
  "type": "LOG",
  "log": {
    "level": "INFO",
    "message": "Starting syncing SourceIterable"
  }
}
{
  "type": "LOG",
  "log": {
    "level": "INFO",
    "message": "Syncing stream: campaigns "
  }
}
{
  "type": "LOG",
  "log": {
    "level": "ERROR",
    "message": "Encountered an exception while reading stream campaigns\nTraceback (most recent call last):\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 114, in read\n    yield from self._read_stream(\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 159, in _read_stream\n    for record in record_iterator:\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 248, in _read_full_refresh\n    for record in records:\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 373, in read_records\n    response = self._send_request(request, request_kwargs)\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 337, in _send_request\n    return backoff_handler(user_backoff_handler)(request, request_kwargs)\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/backoff/_sync.py\", line 110, in retry\n    ret = target(*args, **kwargs)\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/backoff/_sync.py\", line 110, in retry\n    ret = target(*args, **kwargs)\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 299, in _send\n    response.raise_for_status()\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/requests/models.py\", line 960, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.iterable.com/api/campaigns?api_key=****"
  }
}
{
  "type": "LOG",
  "log": {
    "level": "INFO",
    "message": "Finished syncing campaigns"
  }
}
{
  "type": "LOG",
  "log": {
    "level": "INFO",
    "message": "SourceIterable runtimes:\nSyncing stream campaigns 0:00:00.587368"
  }
}
{
  "type": "LOG",
  "log": {
    "level": "FATAL",
    "message": "401 Client Error: Unauthorized for url: https://api.iterable.com/api/campaigns?api_key=****\nTraceback (most recent call last):\n  File \"/home/vremar/Work/Airbyte-projects/airbyte/airbyte-integrations/connectors/source-iterable/main.py\", line 13, in <module>\n    launch(source, sys.argv[1:])\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 127, in launch\n    for message in source_entrypoint.run(parsed_args):\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 118, in run\n    for message in generator:\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 123, in read\n    raise e\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 114, in read\n    yield from self._read_stream(\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 159, in _read_stream\n    for record in record_iterator:\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 248, in _read_full_refresh\n    for record in records:\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 373, in read_records\n    response = self._send_request(request, request_kwargs)\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 337, in _send_request\n    return backoff_handler(user_backoff_handler)(request, request_kwargs)\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/backoff/_sync.py\", line 110, in retry\n    ret = target(*args, **kwargs)\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/backoff/_sync.py\", line 110, in retry\n    ret = target(*args, **kwargs)\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 299, in _send\n    response.raise_for_status()\n  File \"/home/vremar/.virtualenvs/iterable/lib/python3.9/site-packages/requests/models.py\", line 960, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.iterable.com/api/campaigns?api_key=****"
  }
}
```

</details>

## Steps to Reproduce
1. set api key in config file
2. run 
```bash
python main.py  read --config secrets/config.json --catalog integration_tests/configured_catalog.json
```

## Are you willing to submit a PR?

Yeah sure

### PR DESCRIPTION
**Pull request by midavadim**
## What
Connector sync fails with 401 as response code status due to not set the api-key through request headers.
For more info [Iterable API-keys docs](https://support.iterable.com/hc/en-us/articles/360043464871-API-Keys-#using-api-keys)

## How
api key is passed via header instead of query param

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Review by lazebnyi — APPROVED** [review]

**Review by Phlair — APPROVED** [review]
Code changes lgtm. Could you edit the main comment of the PR to explain the _what_ and _why_ of this change please (for clarity) :)

**Pull request merged**
