### PR TITLE
removed unused props clickable and wasActive from button component

### LINKED ISSUE #17719: Remove unused properties from Button
The `Button` component has at the moment two unused properties `wasActive` and `clickable`. Both should be removed.

cc @edmundito

### PR DESCRIPTION
**Pull request by bgopikrishna**
## What
Fixes #17719.
Removed the following unused properties from the button component
* `clickable`
* `wasActive`

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks for the contribution @bgopikrishna 
@airbytehq/frontend can you check this community contribution and add to next sprint to review?

**Comment by natalyjazzviolin** [comment]
@edmundito looks like a community member has contributed a frontend fix :) would you be able to give this a review?

**Review by natalyjazzviolin — APPROVED** [review]
LGTM! Thanks for your contribution!

**Comment by marcosmarxm** [comment]
Hello :wave:, first thank you for this amazing contribution. 

We really appreciate the effort you've made to improve the project.
We ask you patience for the code review. Last month our team was focused on Hacktoberfest event and that probably left some PR without the proper feedback. And this week, due to the Thanksgiving US Holiday, most our team is out of office with their families. Another important piece of information why code won't be merge this week is: as a safety measure the core team has decided to freeze merging code to main branch to keep the release stable. Next week we'll return to you with the proper code review and update the status of your contribution.

If you have any questions feel free to send me a message in Slack!
Thanks!

**Review by krishnaglick — APPROVED** [review]
Did not test locally but Typescript would catch any errors from this.

**Comment by marcosmarxm** [comment]
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

**Comment by krishnaglick** [comment]
Heya! Our code freeze is over. Would you mind resolving conflicts with the current branch? Thanks so much!

**Comment by bgopikrishna** [comment]
> Heya! Our code freeze is over. Would you mind resolving conflicts with the current branch? Thanks so much!

Done

**Review by krishnaglick — APPROVED** [review]
LGTM assuming CI passes! 👍 
Thank you for your contribution!

**Comment by krishnaglick** [comment]
Since https://github.com/airbytehq/airbyte/pull/21624 is green I am going to merge this. Sorry about the wait and thank you again!

**Pull request merged**
