### PR TITLE
🎉 New Source: Plausible [low-code cdk]

### PR DESCRIPTION
**Pull request by scottleechua**
## What
This PR adds a source connector for [Plausible](https://plausible.io). Please see [this issue](https://github.com/airbytehq/connector-contest/issues/208) for more context.

## How
This PR uses the low-code CDK to create a source connector for the critical stream [Stats - Time Series](https://plausible.io/docs/stats-api#get-apiv1statstimeseries).

## Recommended reading order
1. `docs/integrations/sources/plausible.md`
2. `spec.yaml`
3. `plausible.yaml`
4. `schemas/stats.json`

## 🚨 User Impact 🚨
No changes to base code.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

<details><summary><strong>Acceptance</strong></summary>

Screenshot 2022-10-30 at 4 47 41 PM

</details>

### CODE REVIEW

**Review by marcosmarxm — DISMISSED** [review]
Hello @scottleechua, Marcos from Airbyte here 👋 . We received more than 25 new contributions along the weekend. One is yours 🎉  thank so much for! Our team is limited and maybe the review process can take longer than expected. As described in the Airbyte's Hacktoberfest your contribution was submitted before November 2nd and it is eligible to win the prize. The review process will validate other requirements. I ask to you patience until someone from the team review it. 

Because I reviewed some contributions for Hacktoberfest so far I saw some common patterns you can check in advance:
* [ ] Make sure you have added connector documentation to `/docs/integrations/`
* [ ] Remove the file `catalog` from `/integration_tests`
* [ ] Edit the `sample_config.json` inside `/integration_tests`
* [ ] For the `configured_catalog` you can use only `json_schema: {}`
* [ ] Add title to all properties in the `spec.yaml`
* [ ] Make sure the `documentationUrl` in the `spec.yaml` redirect to Airbyte's future connector page, eg: connector Airtable the `documentationUrl: https://docs.airbyte.com/integrations/sources/airtable`
* [ ] Review now new line at EOF (end-of-file) for all files.

If possible send to me a DM in Slack with the tests credentials, this process will make easier to us run integration tests and publish your connector. If you only has production keys, make sure to create a bootstrap.md explaining how to get the keys.

**Comment by tuanchris** [comment]
Hi @scottleechua, can you take a look at the items that @marcosmarxm suggested? Happy to review this PR when you are done.

**Comment by scottleechua** [comment]
Hello!

 * [x]  Make sure you have added connector documentation to `/docs/integrations/`
               -- Added [plausible.md](docs/integrations/sources/plausible.md) and linked to it in the integration [README](docs/integrations/README.md).
 * [x]  Remove the file `catalog` from `/integration_tests`
 * [x]  Edit the `sample_config.json` inside `/integration_tests`
 * [x]  For the `configured_catalog` you can use only `json_schema: {}`
 * [x]  Add title to all properties in the `spec.yaml`
               -- Updated.
 * [x]  Make sure the `documentationUrl` in the `spec.yaml` redirect to Airbyte's future connector page.
               -- Updated top-level domain from `airbyte.io` to `airbyte.com`
 * [x]  Review no new line at EOF (end-of-file) for all files.
               -- Updated.
 * [x]  Sent @marcosmarxm a Slack DM with API keys.
               -- These are my production keys though.
               -- I've also added [BOOTSTRAP.md](airbyte-integrations/connectors/source-plausible/BOOTSTRAP.md) with instructions on generating an API key.
               -- I've also reached out to Plausible if they are able to provide a sandbox account.

Thank you! 😄

**Review by tuanchris — CHANGES_REQUESTED** [review]
@scottleechua can you also remove some TODO blocks within the code, since we are not implementing incremental streams? 

The rest looks good and I was able to run locally.

**Review by tuanchris — APPROVED** [review]
@marcosmarxm @sajarin All good to merge now.

**Comment by scottleechua** [comment]
Hello! Just checking if there's anything left for merge -- I'd like to close this fork and start a fresh one to squash [this issue](https://github.com/airbytehq/airbyte/issues/18658)! 😄

**Comment by tuanchris** [comment]
@scottleechua Not from your end and mine. You can always create a different branch in your fork and solve the issue.  @sajarin will perform the next steps to merge this.

**Comment by sajarin** [comment]
/publish connector=connectors/source-workramp run-tests=false

**Comment by sajarin** [comment]
/publish connector=connectors/source-plausible run-tests=false

**Comment by marcosmarxm** [comment]
@sajarin it is missing the source definition in airbyte-config/init/seed file and format files too.

**Comment by sajarin** [comment]
/publish connector=connectors/source-plausible run-tests=false

**Comment by sajarin** [comment]
Thanks @scottleechua for the PR and @tuanchris for the review! :)

**Comment by ifielder** [comment]
Hello I don't see this as an option in the connectors list currently.

is this connector disabled?

**Comment by pahenn** [comment]
Also interested in using this as a source but it's missing from the source list. Any update on this being available?

**Pull request merged**
