### PR TITLE
🎨 Source MySQL: Add 'Recommended' before CDC description

### PR DESCRIPTION
**Pull request by lmossman**
## What
This is an ask from Alex Cuoci, to add a _Recommended_ indicator before the CDC description to tell our users that they should likely choose this option.

## How
Update the CDC description to include `Recommended - ` in italics at the beginning
Screenshot 2023-08-08 at 10 34 59 AM

### CODE REVIEW

**Review by subodh1810 — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-mysql-strict-encrypt test report (commit [`9abd70508f`](https://github.com/airbytehq/airbyte/pull/29220/commits/9abd70508f3bac8aa7bd68601e13575fa1ce6294)) - ❌

⏲️  Total pipeline duration: 15mn35s 

| Step                                                                                   | Result   |
|:---------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                         | ✅        |
| Connector version increment check                                                      | ✅        |
| QA checks                                                                              | ✅        |
| Build connector tar                                                                    | ✅        |
| Build source-mysql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mysql-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/lmossman_add-recommended-to-mysql/1691516755/9abd70508f3bac8aa7bd68601e13575fa1ce6294/source-mysql-strict-encrypt/2.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:9abd70508f3bac8aa7bd68601e13575fa1ce6294)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql-strict-encrypt test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mysql test report (commit [`9abd70508f`](https://github.com/airbytehq/airbyte/pull/29220/commits/9abd70508f3bac8aa7bd68601e13575fa1ce6294)) - ❌

⏲️  Total pipeline duration: 19mn54s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql/metadata.yaml     | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Build connector tar                                                     | ✅        |
| Build source-mysql docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mysql:integrationTest | ❌        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/lmossman_add-recommended-to-mysql/1691516755/9abd70508f3bac8aa7bd68601e13575fa1ce6294/source-mysql/2.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:9abd70508f3bac8aa7bd68601e13575fa1ce6294)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mysql test report (commit [`9abd70508f`](https://github.com/airbytehq/airbyte/pull/29220/commits/9abd70508f3bac8aa7bd68601e13575fa1ce6294)) - ❌

⏲️  Total pipeline duration: 19mn38s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql/metadata.yaml     | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Build connector tar                                                     | ✅        |
| Build source-mysql docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mysql:integrationTest | ❌        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/lmossman_add-recommended-to-mysql/1691519034/9abd70508f3bac8aa7bd68601e13575fa1ce6294/source-mysql/2.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:9abd70508f3bac8aa7bd68601e13575fa1ce6294)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mysql-strict-encrypt test report (commit [`9abd70508f`](https://github.com/airbytehq/airbyte/pull/29220/commits/9abd70508f3bac8aa7bd68601e13575fa1ce6294)) - ❌

⏲️  Total pipeline duration: 12mn38s 

| Step                                                                                   | Result   |
|:---------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mysql-strict-encrypt/metadata.yaml     | ✅        |
| Connector version semver check                                                         | ✅        |
| Connector version increment check                                                      | ✅        |
| QA checks                                                                              | ✅        |
| Build connector tar                                                                    | ✅        |
| Build source-mysql-strict-encrypt docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:source-mysql-strict-encrypt:integrationTest | ❌        |
| Acceptance tests                                                                       | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/lmossman_add-recommended-to-mysql/1691519034/9abd70508f3bac8aa7bd68601e13575fa1ce6294/source-mysql-strict-encrypt/2.1.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:9abd70508f3bac8aa7bd68601e13575fa1ce6294)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mysql-strict-encrypt test
```

**Comment by octavia-approvington** [comment]
All in!! <br/> all in baby

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
