### PR TITLE
📝 Docs: update navbar styling

### PR DESCRIPTION
**Pull request by ChristoGrab**
## What
- Increased space between each group
- Bold and darker group label
- Light grey background for group labels, so separation between groups is more clear
- Light blue background for selected section

## 🚨 User Impact 🚨
Minor docs improvements

### CODE REVIEW

**Review by timroes — APPROVED** [review]
Code LGTM, tested locally.

**Comment by timroes** [comment]
Merging since only doc system changes, and CI seems to be stuck ... again

**Comment by nataliekwong** [comment]
FYI @johnlafleur the visual updates to https://docs.airbyte.com/ were merged. If you feel there is additional improvement to be made to the navigation, feel free to share!

**Comment by johnlafleur** [comment]
Looks great!


*--*
*Jean Lafleur*
Co-Founder & COO
LinkedIn <https://www.linkedin.com/in/jeanhenrilafleur/> | Twitter
<https://twitter.com/JeanLafleur>

We're hiring, come work with us! <https://boards.greenhouse.io/airbyte>

**Pull request merged**
