### PR TITLE
Revert metadata service upload to use env var over json file for creds

### PR DESCRIPTION
**Pull request by bnchrch**
## What
Updates the metadata upload to use the env var value directly.

## Why
The new GHA didnt have a great story for creating a service account file from the env without it being malformatted.

### CODE REVIEW

**Comment by octavia-approvington** [comment]
Myomoto says it looks good <br/> thats a niiice

**Review by octavia-approvington — APPROVED** [review]

**Comment by alafanechere** [comment]
@bnchrch you changed the MetadataUpload signature but did not make the required change [here](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/publish.py#L182) to not break publish on merge :)

**Comment by bnchrch** [comment]
@alafanechere! Crap! Will update!

**Pull request merged**
