### PR TITLE
🎉 upgrade dbt to 1.0.0 (except for oracle and mysql)

### LINKED ISSUE #9394: Latest dbt clickhouse adapter for normalization
## Tell us about the problem you're trying to solve

Currently a forked version of dbt clickhouse adapter is used , instead of the original one from https://github.com/silentsokolov/dbt-clickhouse/

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/clickhouse.Dockerfile#L26 

According to the comment, there was some bugs (such as https://github.com/silentsokolov/dbt-clickhouse/issues/20) but those have been fixed quite a while ago

The problem of the forked adapter is it it using dbt 0.21.0, instead of latest dbt 1.0.0, and lack of those new features and bugfixes from the original repo, such as newer clickhouse driver, better csv support, advanced settings for connection, cluster support, etc

## Describe the solution you’d like
Please switch back to the original dbt-clickhouse adapter and upgrade the dbt to 1.0.0 (or newer version) and produce a new docker image for `airbyte/normalization-clickhouse`

It will be great to upgrade the docker image when there is a new release from https://github.com/silentsokolov/dbt-clickhouse

## Describe the alternative you’ve considered or used
The current version of `airbyte/normalization-clickhouse` works just fine (in most cases)

## Are you willing to submit a PR?
No, please go ahead change https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/clickhouse.Dockerfile and run related integration tests.

### PR DESCRIPTION
**Pull request by edgao**
## What
Upgrade DBT to 1.0.0 where possible. (it is not currently possible for Oracle and MySQL, as their adapters are still on 0.19.x)

## How
* Bump dockerfiles to `dbt:1.0.0` - I don't think there's an official image for 1.0.3 yet
* also bump dbt-utils to 0.8.2 (the 0.8.x upgrade requires dbt>=1.0)
* Switch clickhouse dbt adapter back to `silentsokolov`, as they fixed the bug that was blocking us
    * closes https://github.com/airbytehq/airbyte/issues/9394
* Rename fields in dbt project templates - https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-1-0-0#breaking-changes

## Recommended reading order
1. Dockerfiles
2. `dbt-project-template-*/dbt_project.yml` + `packages.yml` - focus on the renamed fields; everything else is autoformatting
4. test_normalization.py
5. integration test outputs

## 🚨 User Impact 🚨
None - integration test output is (effectively) unchanged

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [x] Create a non-forked branch based on this PR and test the below items on it
- [x] Build is successful
- [x] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [x] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

## Tests

integration tests pass on CI https://github.com/airbytehq/airbyte/pull/11051#issuecomment-1065230945

### CODE REVIEW

**Comment by ChristopheDuong** [comment]
You may want to look into upgrading the dbt packages [here](https://github.com/airbytehq/airbyte/blob/64948c69534bc5a5ddda13e92114482fc557352d/airbyte-integrations/bases/base-normalization/dbt-project-template/packages.yml#L5) too:

It doesn't complain yet, because it's on `1.0.0`:
https://github.com/dbt-labs/dbt-utils/blob/b42e6f94c1cbb296fee17a5e3e281278cfe99a17/dbt_project.yml#L4

**Review by ChristopheDuong — APPROVED** [review]
Did you re-run normalization integration tests on all destinations locally?
(then add to this PR whatever changes is made to the output files too as it is related to the version upgrade of dbt)

Thanks!

**Comment by edgao** [comment]
yep (except oracle/mysql, since they're not being bumped - should I run those as well?). Nothing unusual in there:
* the renamed config options (plus autoformat :/ ), e.g. https://github.com/airbytehq/airbyte/pull/11051/files#diff-e6bcb11f1de9c62852c7d1030f309234b6afa6ee6bbe7f6efc118679dda774aa
* a few changes to order of parameters https://github.com/airbytehq/airbyte/pull/11051/files#diff-c1796bc18797d162822bcff4c9e81a114da681ece13e7dbf406851b13e28bf7a
* misc whitespace changes https://github.com/airbytehq/airbyte/pull/11051/files#diff-0fd147c8d9dc5d2cbee3d36171d356b1de5bf2d4c72d0ee401cd02cca2653295

**Comment by ChristopheDuong** [comment]
> except oracle/mysql, since they're not being bumped - should I run those as well?)

No, it's fine since they are not really changing

**Pull request merged**
