### PR TITLE
:bug: Destination snowflake: updated snowflake query timeout

### LINKED ISSUE #4745: [DEST Snowflake] - Sync succeeded but destination tables are empty
## Environment
- **Airbyte version**:  0.27.2-alpha
- **OS Version / Instance**: GCP COS
- **Deployment**: Docker
- **Source Connector and version**: MSSQL 0.3.2
- **Destination Connector and version**: Snowflake 0.3.10 (with GCS stage)
- **Severity**: High
- **Step where error happened**: Sync

## Current Behavior
The sync appears to be successful but the tables (raw and normalized) in the destination (Snowflake) are empty. In the logs, there appear to be only 1 error during data transfer (I guess) which seems to makes the whole data transfer unsuccessful.

image

## Expected Behavior
There should be an exponential backoff on the all potential pitfalls during data transfers to retry the failed command.

## Logs

<details>
<summary>LOG</summary> 

```
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-13 23:56:30 [1;31mERROR[m i.a.i.d.b.BufferedStreamConsumer(close):203 - {} - on close failed.
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - net.snowflake.client.jdbc.SnowflakeSQLException: SQL execution canceled
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:124) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:64) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:434) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:338) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:501) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:229) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:167) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:749) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:292) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at net.snowflake.client.jdbc.SnowflakeStatementV1.execute(SnowflakeStatementV1.java:342) ~[snowflake-jdbc-3.12.14.jar:3.12.14]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.db.jdbc.JdbcDatabase.lambda$execute$0(JdbcDatabase.java:54) ~[io.airbyte-airbyte-db-0.27.1-alpha.jar:?]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.db.jdbc.DefaultJdbcDatabase.execute(DefaultJdbcDatabase.java:62) ~[io.airbyte-airbyte-db-0.27.1-alpha.jar:?]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.db.jdbc.JdbcDatabase.execute(JdbcDatabase.java:54) ~[io.airbyte-airbyte-db-0.27.1-alpha.jar:?]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.destination.snowflake.SnowflakeGcsStreamCopier.copyGcsCsvFileIntoTable(SnowflakeGcsStreamCopier.java:63) ~[io.airbyte.airbyte-integrations.connectors-destination-snowflake-0.27.1-alpha.jar:?]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.destination.jdbc.copy.gcs.GcsStreamCopier.copyStagingFileToTemporaryTable(GcsStreamCopier.java:121) ~[io.airbyte.airbyte-integrations.connectors-destination-jdbc-0.27.1-alpha.jar:?]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.destination.jdbc.copy.CopyConsumerFactory.closeAsOneTransaction(CopyConsumerFactory.java:152) ~[io.airbyte.airbyte-integrations.connectors-destination-jdbc-0.27.1-alpha.jar:?]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.destination.jdbc.copy.CopyConsumerFactory.lambda$onCloseFunction$2(CopyConsumerFactory.java:136) ~[io.airbyte.airbyte-integrations.connectors-destination-jdbc-0.27.1-alpha.jar:?]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.destination.buffered_stream_consumer.OnCloseFunction.accept(OnCloseFunction.java:29) ~[io.airbyte.airbyte-integrations.bases-base-java-0.27.1-alpha.jar:?]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:195) [io.airbyte.airbyte-integrations.bases-base-java-0.27.1-alpha.jar:?]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:82) [io.airbyte.airbyte-integrations.bases-base-java-0.27.1-alpha.jar:?]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:142) [io.airbyte.airbyte-integrations.bases-base-java-0.27.1-alpha.jar:?]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:117) [io.airbyte.airbyte-integrations.bases-base-java-0.27.1-alpha.jar:?]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 	at io.airbyte.integrations.destination.snowflake.SnowflakeDestination.main(SnowflakeDestination.java:82) [io.airbyte.airbyte-integrations.connectors-destination-snowflake-0.27.1-alpha.jar:?]
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-13 23:56:30 [32mINFO[m i.a.i.b.IntegrationRunner(run):122 - {} - Completed integration: io.airbyte.integrations.destination.snowflake.SnowflakeDestination
2021-07-13 23:56:30 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-13 23:56:30 [32mINFO[m i.a.i.d.s.SnowflakeDestination(main):83 - {} - completed destination: class io.airbyte.integrations.destination.snowflake.SnowflakeDestination
2021-07-13 23:56:31 INFO () DefaultReplicationWorker(run):144 - Destination thread complete.
2021-07-13 23:56:31 INFO () DefaultReplicationWorker(run):172 - sync summary: io.airbyte.config.ReplicationAttemptSummary@56a72bd4[status=completed,recordsSynced=42289296,bytesSynced=109522548726,startTime=1626186650362,endTime=1626220591157]
2021-07-13 23:56:31 INFO () DefaultReplicationWorker(run):181 - Source did not output any state messages
2021-07-13 23:56:31 WARN () DefaultReplicationWorker(run):189 - State capture: No new state, falling back on input state: io.airbyte.config.State@6ff49b54[state={}]
2021-07-13 23:56:31 INFO () TemporalAttemptExecution(get):133 - Stopping cancellation check scheduling...
2021-07-13 23:56:31 INFO () RetryingTemporalAttemptExecution(get):118 - Last output present: true. Should attempt again: false
2021-07-13 23:56:31 INFO () SyncWorkflow$ReplicationActivityImpl(replicate):202 - attempt summaries: <REDACTED>
2021-07-13 23:56:31 INFO () SyncWorkflow$ReplicationActivityImpl(replicate):203 - sync summary: <REDACTED>
2021-07-13 23:56:31 INFO () TemporalAttemptExecution(get):110 - Executing worker wrapper. Airbyte version: 0.27.2-alpha
2021-07-13 23:56:31 INFO () DefaultNormalizationWorker(run):61 - Running normalization.
2021-07-13 23:56:31 INFO () LineGobbler(voidCall):85 - Checking if airbyte/normalization:0.1.36 exists...
2021-07-13 23:56:31 INFO () LineGobbler(voidCall):85 - airbyte/normalization:0.1.36 was found locally.
2021-07-13 23:56:31 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/52/0/normalize --network host --log-driver none airbyte/normalization:0.1.36 run --integration-type snowflake --config destination_config.json --catalog destination_catalog.json
2021-07-13 23:56:31 INFO () LineGobbler(voidCall):85 - Running: transform-config --config destination_config.json --integration-type snowflake --out /data/52/0/normalize
2021-07-13 23:56:32 INFO () LineGobbler(voidCall):85 - Namespace(config='destination_config.json', integration_type=<DestinationType.snowflake: 'snowflake'>, out='/data/52/0/normalize')
2021-07-13 23:56:32 INFO () LineGobbler(voidCall):85 - transform_snowflake
2021-07-13 23:56:32 INFO () LineGobbler(voidCall):85 - Running: transform-catalog --integration-type snowflake --profile-config-dir /data/52/0/normalize --catalog destination_catalog.json --out /data/52/0/normalize/models/generated/ --json-column _airbyte_data
2021-07-13 23:56:32 INFO () LineGobbler(voidCall):85 - Processing destination_catalog.json...

 <REDACTED>

2021-07-13 23:56:52 INFO () LineGobbler(voidCall):85 - [32mCompleted successfully[0m
2021-07-13 23:56:52 INFO () LineGobbler(voidCall):85 - 
2021-07-13 23:56:52 INFO () LineGobbler(voidCall):85 - Done. PASS=22 WARN=0 ERROR=0 SKIP=0 TOTAL=22
2021-07-13 23:56:52 INFO () DefaultNormalizationWorker(run):77 - Normalization executed in 0.
2021-07-13 23:56:52 INFO () TemporalAttemptExecution(get):133 - Stopping cancellation check scheduling...
```

</details>

## Steps to Reproduce
1. Difficult to reproduce... Transfer 100GB+ of data from MSSQL to Snowflake

### PR DESCRIPTION
**Pull request by andriikorotkov**
## What
Sync succeeded but destination snowflake tables are empty

## How
Updated query timeout from 30 minutes to 3 hours. It is first part of fix this bug.

#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [x] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

### CODE REVIEW

**Review by etsybaev — APPROVED** [review]
LGTM, but please make sure all check\tests passed before moving forward. I would also add new timeout info to the main connector's documentation explicitly

**Review by irynakruk — APPROVED** [review]

**Review by subodh1810 — APPROVED** [review]

**Comment by sherifnada** [comment]
@andriikorotkov is there a follow up issue for later fixes?

**Comment by andriikorotkov** [comment]
@sherifnada No, no problem. I have successfully split one query into multiple ones with a user-specified batch size. I pushed these changes in this Pull Request - https://github.com/airbytehq/airbyte/pull/5783

**Pull request merged**
