### PR TITLE
source-salesflare contribution from ombhardwajj

### LINKED ISSUE #47438: [connector-request] Salesflare
This is a suggestion to create a connector for Salesflare using the UI Connector Builder.
The website for the connector is https://salesflare.com/

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to step 3).
3. Describe steps to get credentials.
4. Create the connector using the UI Builder.   

> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> This is a suggestion, and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend following the steps above.

### PR DESCRIPTION
**Pull request by ombhardwajj**
This closes #47438
## What

This PR adds a new connector for source Salesflare (source-salesflare).

Contributor-provided connector description:

Salesflare is a CRM tool for small and medium businesses.
Using this connector we can extract data from various streams such as opportunities , workflows and pipelines.
Docs : https://api.salesflare.com/docs
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `api_key` | `string` | API Key. Enter you api key like this : Bearer YOUR_API_KEY |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| tasks | id | DefaultPaginator | ✅ |  ❌  |
| accounts | id | DefaultPaginator | ✅ |  ❌  |
| contacts | id | DefaultPaginator | ✅ |  ❌  |
| opportunities | id | DefaultPaginator | ✅ |  ❌  |
| workflows | id | DefaultPaginator | ✅ |  ❌  |
| tags | id | DefaultPaginator | ✅ |  ❌  |
| persons | id | No pagination | ✅ |  ❌  |
| email data sources | id | No pagination | ✅ |  ❌  |
| custom field types | id | No pagination | ✅ |  ❌  |
| pipelines | id | No pagination | ✅ |  ❌  |
| users | id | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by ombhardwajj** [comment]
Salesflare icon is not available as svg , only png is available.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Missing pagination and limit to couple of streams (tasks, accounts)

**Comment by marcosmarxm** [comment]
Moving next review to nov-13

**Comment by marcosmarxm** [comment]
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

Make sure you have pagination properly working, the API doesn't have pagination please left a comment making my review easier.
Make sure have a square svg icon
Make sure credentials are valid.

**Comment by ombhardwajj** [comment]
Pagination added in all the streams where it was possible , credentials are valid.
I will look for an svg icon and try to add it.
@marcosmarxm

**Comment by ombhardwajj** [comment]
Its ready for review icon has been added !!
@marcosmarxm

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Please check 
image

**Comment by ombhardwajj** [comment]
Hey @marcosmarxm I've done the needful  , Please try again and it shall work fine!!

**Comment by ombhardwajj** [comment]
Hey @marcosmarxm please review this on priority today as I am about loose the API access very soon!

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
