### PR TITLE
Document rust as a local dev dependency

### PR DESCRIPTION
**Pull request by gordalina**
`gradlew build` fails saying that `cryptography`  needs rust
```
           error: Can not find Rust compiler
           ----------------------------------------
           ERROR: Failed building wheel for cryptography
```

### CODE REVIEW

**Review by michel-tricot — APPROVED** [review]
Which project requires this?

**Comment by gordalina** [comment]
This was either failing when running
```
./gradlew :airbyte-integrations:bases:base-normalization:installLocalReqs
or
./gradlew :airbyte-integrations:connectors:source-file:installLocalReqs
```

**Comment by sherifnada** [comment]
This is weird -- I definitely don't have rust installed on my computer 🤔 will look into this a bit more. @gordalina what OS were you running this on?

**Comment by gordalina** [comment]
OS X 11.2 (Big Sur)

**Comment by davinchia** [comment]
I need this to, in order to do `pip install cryptography` for the `source-file`

**Comment by sherifnada** [comment]
we should put this requirement in the README for source-file then, and potentially change the default behavior for `./gradlew build` to use `CORE_ONLY=true` (basically invert the behavior for `CORE_ONLY` flag)

**Comment by sherifnada** [comment]
created an issue here: https://github.com/airbytehq/airbyte/issues/2865

**Comment by sherifnada** [comment]
done here https://github.com/airbytehq/airbyte/pull/3426#pullrequestreview-660288729

**Pull request closed without merging**
