### PR TITLE
Fix Vector destination tests and move to Poetry

### PR DESCRIPTION
**Pull request by aaronsteers**
Destinations addressed in this pull request  
- Milvus: https://connectors.airbyte.com/files/generated_reports/test_summary/destination-milvus/index.html
- Pinecone: https://connectors.airbyte.com/files/generated_reports/test_summary/destination-pinecone/index.html
- Weaviate: https://connectors.airbyte.com/files/generated_reports/test_summary/destination-weaviate/index.html

### CODE REVIEW

**Comment by aaronsteers** [comment]
Milvus account has reached OpenAI quota:

- [Job result](https://ff262facab9f48b6fc9f33555fbfe8c204687d8116c3f5621790716-apidata.googleusercontent.com/download/storage/v1/b/airbyte-ci-reports-multi/o/airbyte-ci%2Fconnectors%2Ftest%2Fpull_request%2Faj_vector-db-patches%2F1709872165%2Fac3431c51cc5582254af877ee87983577be10e2c%2Fdestination-milvus%2F0.0.13%2Foutput.html?jk=ATxpoHe_XLZRNcH2QN-3vJoWxolT5Vp_MgdXCVjT9JBy-FENpMQ24W-Wn3fyGfRXBGFecesTAy-IGrQ90damUV_WUpu-xVsNX2NxWUA9jnAhlGqV1nC5m9FVJ3fucCgdzzl0kHnSBF1svbydpOBH85Mt2lRYb7PfAwsOeU-jkdIO83wKg92wjCQPe_nyavPn2tvjeAhOmpX6r8l5NWDHhSs6Xg1nwbdM6q1tb05Mzg1WpPSFXAn973rLrmUZ0oSHg22aGLHASMSEyzaaf7xkPNGUTPmAnbGmcw1yliHIX4fKtOicbHo-zgxlQ-oguylDeLrmF3-ubGA2CTmnm9nmIMBjERFI73XMfkTznhhNfrmSNfmd-kAx2WnAV9z4CSqcuSaG7Mzii2na-rdXQqgPTBjKt4K3cRLdtdHJaNo_H3jDoO9IORjQvd25fT3n6jsHH6iOmONSy6BmM9AqJJ6PtMuidNc4k357ao3A7YYi1teXnPKK3ebqR-HYVtiE3-9Rl1yDJnxBos65vOQKV0h0Y1szoK6OJU7YlbqKvixij2feYXq38giMqkGXf6cq86J2qLq9wiP4egc46VgmhSjFE-D2I7aMuxlgluSuNBMMHByTM0rD9dSwkfHeSIddEj4sFxlYI6o6fJ1UktNo6i1whS_Z6ahQoRtPrxXhnqq552N4kN9HCxBRLOms0VN3SR-x2W4h0HulIAHT8AdkO8OugkBsHtAzj7QghHx1GngNG63gNZwBu-kPOnKHEI3WphwxCUwQGECfWgsVVOdF7YsPkWeuoy4M5_X3sAvSgqAxD7twtHYKngfm-bWdV5XY557jvMDb8XWnWnUWiwdgodpvYSVEaXqdw1kv3sBRQ41q9zEqFlOPdI9VpDAKMVou7MLuKHGOc-9Glvg0Zyu-LGE7v_6U0-VwGdfHUmUgR8ijVlxfmuxIw1c0eOl7DKdZ5h-Sr8CbvusKBhMyQbmpZa_zOOLxXniXCy9GESc95EtAYFi9D-C-RsQBLAeQ1OaSzo9OdG4W1DWYn5pbku982Azuen8POg4_btMChgtnS-q8x5aCJ9INzus6w7NTuUcxIZIsZuRUiVi3cIPo7-RPgg4v8QGCR9noQtD7BSqdsJ7fN6K6_-15ciXNGe8-zZVnzBWIJRCh6qP5ZMz2d3ZE1KpTKsTlGh1Aeh-P-9DNjn7LipeGMktu-Q9S_Ct42g5Ds1m5_041qzwCbSnnoLIpoWZ5GXLADcxZbQ7MjREii2PuBxg8bvdAibnShXjPvaWoJfv05XdDP--jY4v-8DhZNvFHlCetSrq7ubizZvtW7ugCo0JPp4U80VS6dbRvfwY9ft3otXUMEK1PB-BgqZmHkv8ljd2XMA36tIm_3eA&isca=1): `RateLimitError: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors`

**Comment by aaronsteers** [comment]
Re: [Pinecone failures](https://ff0aa68796eab1c4f8ddceea9287345301a74a9002673c61eb8e86d-apidata.googleusercontent.com/download/storage/v1/b/airbyte-ci-reports-multi/o/airbyte-ci%2Fconnectors%2Ftest%2Fpull_request%2Faj_vector-db-patches%2F1709872165%2Fac3431c51cc5582254af877ee87983577be10e2c%2Fdestination-pinecone%2F0.0.23%2Foutput.html?jk=ATxpoHdC30Gu7N3rfPHKDuVwfSR_He0IfgZSX_NziXPI0NDF1RERn21Znvw7nRUzrzS7oTwLGgK2W0LlEEn_pVh0UxfsVVTOPUjd8q8iAcYp96J-rPy4oLC2VnI_n9PLAsSUPTTRB9Gt6thntRxFtoA12Osw1NKs5FJDmSUvFIn0box7TVuEAowywmGGpvLA7onnT6rY7l9NsqBRj_BGnkSCgL06EoTq57uvwr7p3K4gLXSLw2v-4He6drS40VocTifl_6oGtWgL9hRx71yvstCI5Zg15neKkKbT38M6Jn9UM39ZY6Qg7n72BZt5-6SgU1eMcnrLC90DKvrkk1d8WzWEjLOGJTftG6ZdOWX5DudwqWHxzZp2ib52ncsnJQTJgVP-KJ3OfiUY6skgk8u_qUOMuCCqPFQDzPRZaRioIyFNXYpfLz3_EruzDKhhR1rpQY0V9R5kEURPdefCqR8oVlsX6KWi5d57nvevLnswheqKXauYdyQZirW42ZK2TsfSBvi0Db1fvVghQvqs6H1r53QtHXbRGl0IWQrXFOvz8tUJfQ2RRuRvPIVzMs3uU1a-rK2eeLR30awPHGlkbY8LOflDYWgttlNLPbwXE9SBhmI8odK3cLQOH4vEcFRUCLr1f3DHxZoyi8NKsqDvgjuNYVGz7_Jdw4JzalFqwARm63MKniHw7FIpIomoD3sKI1RD7Iw5ntRTWkPJrhRjDei2ElmCulHVQu6kWVhk0S3-Q9gg_6-1wpN561VWp01EiavaxrjLvt8j8i0mxEI93Ztd7yo4yHVrziciZHsovlvmMBHUD8H8fzcoqlqFxFHBN0nW_nXEgk6SJIgfcJc-9b7AUvmnBZRzfBcKGGmYs2mjNP5ztGDFdcB7R8giczaQnfoOV6c0UVeIn7uGSHB4cZ10mD6S56NsXI9tFuS0sPNPHQ5DSqL0EOqG0Edum91Una2aRpwjnSFI2G0k1Lpc8Yo28cWZEbSCmJXAalRtKmDpqMY49qWaNDY94Dyws4E6fK_SO-zocXqRsBS5giNxb1pgOnNNrTuTjfhyaef6prgEFAQ3rexzkIwgfwwRPA4j4Oi12b2EeCdzbFVyv7RNHsVC1TWjf9QSg_g8XnX1mZyXaPj2UXfqRFFgu66UOAXDbQaqcPAowKxweC8gzu7a_ebdBWlCBkv6eSV4-gTNYqQO1d8a5VtZx20sTDk85-jhw3OPtXvHqwLFWOHlVPqAixYsmXVhqkZlwtNt3NDhiL3DYXtCpbl28xY_yWjThx8Kjx0_47uZsPfOeCRJbTOpv3-Xs7fsSencpUrryiIY3oj0VmjZvsKh8LJrvn-SxH_wbHlhrmhK3EZuWEiamAvBdUh-QRfrrTKYM7rDJwtvjjk&isca=1) looks like breaking changes in the pinecone library. Probably need to pin to prior version:

- `TypeError: <lambda>() got an unexpected keyword argument 'replicas'`
- `AttributeError: init is no longer a top-level attribute of the pinecone package.Please create an instance of the Pinecone class instead.Example:import os; from pinecone import Pinecone, ServerlessSpec; pc = Pinecone(api_key=os.environ.get("PINECONE_API_KEY"))... pc.create_index(...`

**Comment by aaronsteers** [comment]
I've updated the configs in GSM so that each of these three uses embeddings "mode": "fake" instead of "mode": "openai".

**Review by bindipankhudi — COMMENTED** [review]
Besides the OpenAI quota issues, are these all the changes we need to comply with the new connector requirements?

**Comment by bindipankhudi** [comment]
> I've updated the configs in GSM so that each of these three uses embeddings "mode": "fake" instead of "mode": "openai".

assuming we are good for now then?

**Review by bindipankhudi — APPROVED** [review]

**Comment by aaronsteers** [comment]
> > I've updated the configs in GSM so that each of these three uses embeddings "mode": "fake" instead of "mode": "openai".
> 
> assuming we are good for now then?

Still a bit more work to do. One connector (Vectara, I think) went green after this. Another (pinecone) appears to need a more specific version to be pinned, and the third (weaviate) had some integration tests that strictly required the OpenAI key.

All of these also have the (new) requirement to be on Poetry. If we don't fix that poetry failure, we'll be blind to other failure types because status will stay constantly red.

**Comment by bindipankhudi** [comment]
Tests for Milvus, Pinecone, and Weaviate destinations are green now.

Changes: 
- Poetry configuration for the destinations above
- Open AI key updated for all destinations (no longer using faker) 
- Milvus cluster re-enabled - this was causing the Milvus tests to fail

**Review by aaronsteers — COMMENTED** [review]
✅ Approved!

This is huge to have these passing tests again!


Two points for follow-up, but non-blocking:

1. The `run.run` CLI references in the `pyproject.toml` files won't work yet, but also they shouldn't hurt anything in the meanwhile.
2. It's probably worth looping back sometime soon to bump the CDK versions to latest. The version here is 57ish in most cases, whereas I think the latest version is around 75 now.

I think we can handle both in future cycles.

**Pull request merged**
