### PR TITLE
✨ Source Shopify: Update countries provinces.tax_percentage type based on newest API change

### PR DESCRIPTION
**Pull request by maxi297**
## What
Since today, the Shopify API return a number instead of an integer for https://airbyte-integration-test.myshopify.com/admin/api/2024-04/countries.json. The reason is unclear to me. At first, I thought it was because of the `Accept-Encoding: gzip, deflate` headers (see added note) but in the end, it isn't the reason.

[The API documentation](https://shopify.dev/docs/api/admin-rest/2023-07/resources/country#get-countries) has examples where `tax_percentage` is a number so I'm fine with updating this without understanding why we didn't identified this earlier.

## How
Updating the schema

## User Impact
This is a breaking change as the value for `tax_percentage` can be more precise than just a integer.

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [X] NO ❌ (as it is a breaking change)

## Added note

Don't trust jq!! Manually adding the requests library headers one by one, I got the following results:

*Without Accept-Encoding: gzip, deflate*
``` 
~% curl -X GET -H 'Connection: keep-alive' -H 'User-Agent: python-requests/2.32.2' -H 'Accept: */*' -H 'X-Shopify-Access-Token: <redacted>' 'https://airbyte-integration-test.myshopify.com/admin/api/2024-04/countries.json?limit=250&order=updated_at+asc&updated_at_min=2023-04-13' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   479    0   479    0     0   3063      0 --:--:-- --:--:-- --:--:--  3070
{
  "countries": [
    {
      "id": 417014841533,
      "name": "Rest of World",
      "code": "*",
      "tax_name": "Tax",
      "tax": 0,
      "provinces": []
    },
    {
      "id": 417014808765,
      "name": "Ukraine",
      "code": "UA",
      "tax_name": "PDV",
      "tax": 0.2,
      "provinces": []
    },
    {
      "id": 530151014589,
      "name": "United States",
      "code": "US",
      "tax_name": "Federal Tax",
      "tax": 0,
      "provinces": [
        {
          "id": 5688038064317,
          "country_id": 530151014589,
          "name": "California",
          "code": "CA",
          "tax_name": "State Tax",
          "tax_type": null,
          "shipping_zone_id": null,
          "tax": 0,
          "tax_percentage": 0
        }
      ]
    }
  ]
}
```

*With Accept-Encoding: gzip, deflate*

```
~% curl -X GET --compressed -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' -H 'User-Agent: python-requests/2.32.2' -H 'Accept: */*' -H 'X-Shopify-Access-Token: <redacted>' 'https://airbyte-integration-test.myshopify.com/admin/api/2024-04/countries.json?limit=250&order=updated_at+asc&updated_at_min=2023-04-13'
{"countries":[{"id":417014841533,"name":"Rest of World","code":"*","tax_name":"Tax","tax":0.0,"provinces":[]},{"id":417014808765,"name":"Ukraine","code":"UA","tax_name":"PDV","tax":0.2,"provinces":[]},{"id":530151014589,"name":"United States","code":"US","tax_name":"Federal Tax","tax":0.0,"provinces":[{"id":5688038064317,"country_id":530151014589,"name":"California","code":"CA","tax_name":"State Tax","tax_type":null,"shipping_zone_id":null,"tax":0.0,"tax_percentage":0.0}]}]}
```

However, I just got baited because `jq` cast `0.0` as `0` for a reason that is unknown to me. Lesson learned here I guess!

### CODE REVIEW

**Review by bazarnov — APPROVED** [review]

**Comment by bazarnov** [comment]
@maxi297 During the monitoring of the Shopify Errors here: 

A new error come up for `429`:
```
Giving up _send(...) after 1 tries (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: https://wellversed-health.myshopify.com/admin/api/2024-04/shop.json?limit=250&order=updated_at+asc&updated_at_min=2020-01-01, Response Code: 429, Response Text: {"errors":"Exceeded 2 calls per second for api client. Reduce request rates to resume uninterrupted service."})
2024-05-29 03:59:02 source > Request URL: https://wellversed-health.myshopify.com/admin/api/2024-04/shop.json?limit=250&order=updated_at+asc&updated_at_min=2020-01-01, Response Code: 429, Response Text: {"errors":"Exceeded 2 calls per second for api client. Reduce request rates to resume uninterrupted service."}
```

Connection: [link](https://cloud.airbyte.com/workspaces/1ee27b6b-57aa-46f5-a46b-bab7c4f246fa/connections/b37bdaaa-78df-496c-b935-06d9039d17b4/job-history)

The fix is straightforward, we should just increase this number [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-shopify/source_shopify/utils.py#L89) to `0.1 or 0.2`, as it was before this [contributor requested change](https://github.com/airbytehq/airbyte/pull/37589/files#diff-8741cc1cf1acf1daba4a77b89f8d9913e5e65bbd07fcf24606d52096a4d4c02a)

Another concern from my side is that it was never `retried` but It was supposed to, I believe, saying:
```
Giving up _send(...) after 1 tries 
```

There are no limits for retry; for the REST streams, the logic should totally rely on the default `max_retries` property from `CDK.` This seems odd to me.

**Comment by bazarnov** [comment]
I've pushed 2 fixes in addition to the one you did:

1) The check for `NoneType` for `{"access_scopes": None}` case. Related to the fact that when we check for `granted scopes`, we might have `None`, instead of `[]` as expected. 
Connection: [link](https://cloud.airbyte.com/workspaces/1ee27b6b-57aa-46f5-a46b-bab7c4f246fa/connections/b37bdaaa-78df-496c-b935-06d9039d17b4/job-history#12427436::0)

```
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 9, in <module>
    run()
  File "/airbyte/integration_code/source_shopify/run.py", line 19, in run
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 235, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.read(source_spec, config, config_catalog, state))
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 166, in read
    for message in self.source.read(self.logger, config, catalog, state):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 104, in read
    stream_instances = {s.name: s for s in self.streams(config)}
  File "/airbyte/integration_code/source_shopify/source.py", line 174, in streams
    scopes_manager: ShopifyScopes = ShopifyScopes(config)
  File "/airbyte/integration_code/source_shopify/scopes.py", line 86, in __init__
    self.user_scopes = self.get_user_scopes(config)
  File "/airbyte/integration_code/source_shopify/scopes.py", line 108, in get_user_scopes
    access_scopes = [scope.get("handle") for scope in response.get("access_scopes")]
TypeError: 'NoneType' object is not iterable
```

2) Another is related to the fact we make the API calls to frequently.
Connection: [link](https://cloud.airbyte.com/workspaces/1ee27b6b-57aa-46f5-a46b-bab7c4f246fa/connections/b37bdaaa-78df-496c-b935-06d9039d17b4/job-history)

```
Giving up _send(...) after 1 tries (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: https://wellversed-health.myshopify.com/admin/api/2024-04/shop.json?limit=250&order=updated_at+asc&updated_at_min=2020-01-01, Response Code: 429, Response Text: {"errors":"Exceeded 2 calls per second for api client. Reduce request rates to resume uninterrupted service."})
2024-05-29 03:59:02 source > Request URL: https://wellversed-health.myshopify.com/admin/api/2024-04/shop.json?limit=250&order=updated_at+asc&updated_at_min=2020-01-01, Response Code: 429, Response Text: {"errors":"Exceeded 2 calls per second for api client. Reduce request rates to resume uninterrupted service."}
```

**Comment by maxi297** [comment]
We purposely set the retries to 0 [here](https://github.com/airbytehq/airbyte/blob/8bbfe6bb77dd1f349c9450cb7161ef6b6d645463/airbyte-integrations/connectors/source-shopify/source_shopify/source.py#L75) so this behavior seems normal to me. Should we change that?

**Comment by maxi297** [comment]
> The check for NoneType for {"access_scopes": None} case. Related to the fact that when we check for granted scopes, we might have None, instead of [] as expected.
Connection: [link](https://cloud.airbyte.com/workspaces/1ee27b6b-57aa-46f5-a46b-bab7c4f246fa/connections/b37bdaaa-78df-496c-b935-06d9039d17b4/job-history#12427436::0)

I'm not sure I like [this fix](https://github.com/airbytehq/airbyte/pull/38746/commits/d1efa855ba86b6965c1e7abdad23aa61f0bea463#diff-9356ccb61812837d9bbdae9d93c88ab159c671485fcb5bd4772a15dceef4b04cR108-R109). We are only expected to have `None` when the request is not successful (like 429), right? If this is the case, [this](https://github.com/airbytehq/airbyte/pull/38678/files#diff-9356ccb61812837d9bbdae9d93c88ab159c671485fcb5bd4772a15dceef4b04cR108-R109) should fix the error and allow for better reporting (429 will be reported as transient error for example)

> Another is related to the fact we make the API calls to frequently.

Where is the fix for that error in [this commit](https://github.com/airbytehq/airbyte/pull/38746/commits/d1efa855ba86b6965c1e7abdad23aa61f0bea463#diff-9356ccb61812837d9bbdae9d93c88ab159c671485fcb5bd4772a15dceef4b04c)? I don't see it

**Pull request merged**
