### PR TITLE
remove [main] convention for python

### PR DESCRIPTION
**Pull request by jrhizor**
Moves `[main]` extras into `install_requires` for simplification.

### CODE REVIEW

**Review by sherifnada — APPROVED** [review]
EDIT: nvm LGTM

**Review by cgardens — APPROVED** [review]
thanks! it's like a java developer set up this original set up or something 😉 . i'll own it, main was my bad idea.

**Comment by jrhizor** [comment]
This is actually going to be a major hassle since the test image isn't singer-based. I don't want to copy py deps from other images, so I'm going to just close this.

**Pull request closed without merging**
