### PR TITLE
🐛  Publish strict-encrypt source-connectors: source-clickhouse-strict-encrypt, source-mysql-strict-encrypt, source-oracle-strict-encrypt

### LINKED ISSUE #9213: Publish strict-encrypt source-connectors due to the fields Titles/Descriptions changes in sources specifications: clickhouse-strict-encrypt, mysql-strict-encrypt, oracle-strict-encrypt
Publish connectors to implement changes of files title and description properties to each field in source-connectors specifications:
source-clickhouse-strict-encrypt
source-mysql-strict-encrypt
source-oracle-strict-encrypt 

[EPIC] Add title and description properties to each field in connectors specifications and order input fields appropriately #8324

### PR DESCRIPTION
**Pull request by bazarnov**
## What
Resolving: https://github.com/airbytehq/airbyte/issues/9213

## How
- Updated `expected_json.json` files and `Dockerfile` files for listed connectors

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Use should update the connector, because the specifications are changed a bit.

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 
<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter

- [X] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [X] Code reviews completed
- [X] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

### CODE REVIEW

**Comment by bazarnov** [comment]
/publish connector=connectors/source-clickhouse-strict-encrypt

**Review by antixar — APPROVED** [review]

**Pull request merged**
