### PR TITLE
Bmoric/extract healt api

### PR DESCRIPTION
**Pull request by benmoriceau**
## What
In order to be prepared for a smoother migration to Micronaut for the server, an effort must be made to break the ConfigurationApi into multiple classes. This PR is the first one of a series of PR to come.

## How
Extract the HealthCheckApi into its own class

## Recommended reading order
No specific order

### CODE REVIEW

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Comment by jdpgrailsdev** [comment]
@benmoriceau Looks like there are failing tests in `airbyte-server`.

**Comment by benmoriceau** [comment]
> @benmoriceau Looks like there are failing tests in `airbyte-server`.

Thanks, I'll have a look. I need to merge all the review because stacking them up start being painful.

**Review by jdpgrailsdev — APPROVED** [review]
re-:shipit:

**Pull request merged**
