### PR TITLE
remove strict encrypt variant of db2

### PR DESCRIPTION
**Pull request by erohmensing**
The strict encrypt variant of db2 has never had any use in cloud. It has also already been hidden from cloud for a while (so users haven't been able to create new connections with it). We are deleting it. Bye!

### CODE REVIEW

**Review by evantahler — APPROVED** [review]
Why no metadata thou 🤷

**Comment by airbyte-oss-build-runner** [comment]
##  source-db2 test report (commit [`5a948ba142`](https://github.com/airbytehq/airbyte/pull/31146/commits/5a948ba14266d645f6540ff6e747a4709d0424b8)) - ❌

⏲️  Total pipeline duration: 06mn04s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Build connector tar                                        | ✅        |
| Build source-db2 docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                  | ❌        |
| Java Connector Integration Tests                           | ❌        |
| Acceptance tests                                           | ✅        |
| Validate metadata for source-db2                           | ✅        |
| Connector version semver check                             | ✅        |
| QA checks                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_axe-db2-strict-encrypt/1696629570/5a948ba14266d645f6540ff6e747a4709d0424b8/source-db2/0.1.20/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:5a948ba14266d645f6540ff6e747a4709d0424b8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-db2 test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-db2 test report (commit [`6ac8ec43ce`](https://github.com/airbytehq/airbyte/pull/31146/commits/6ac8ec43cef25904665a3be4f8e6db07175cfe4d)) - ❌

⏲️  Total pipeline duration: 05mn03s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Build connector tar                                        | ✅        |
| Build source-db2 docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                  | ❌        |
| Java Connector Integration Tests                           | ❌        |
| Acceptance tests                                           | ✅        |
| Validate metadata for source-db2                           | ✅        |
| Connector version semver check                             | ✅        |
| QA checks                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_axe-db2-strict-encrypt/1696630413/6ac8ec43cef25904665a3be4f8e6db07175cfe4d/source-db2/0.1.20/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6ac8ec43cef25904665a3be4f8e6db07175cfe4d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-db2 test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-db2 test report (commit [`53352b9534`](https://github.com/airbytehq/airbyte/pull/31146/commits/53352b95340c8f58360c698107d21edfa56e80bf)) - ❌

⏲️  Total pipeline duration: 49mn03s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Build connector tar                                        | ✅        |
| Build source-db2 docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                  | ❌        |
| Java Connector Integration Tests                           | ❌        |
| Acceptance tests                                           | ✅        |
| Validate metadata for source-db2                           | ✅        |
| Connector version semver check                             | ✅        |
| QA checks                                                  | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ella_axe-db2-strict-encrypt/1696973854/53352b95340c8f58360c698107d21edfa56e80bf/source-db2/0.1.20/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:53352b95340c8f58360c698107d21edfa56e80bf)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-db2 test
```

**Comment by octavia-approvington** [comment]
A job well done <br/> nice job

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
