### PR TITLE
Normalization: handle nested objects correctly

### PR DESCRIPTION
**Pull request by edgao**
We're currently not prioritizing objects/arrays correctly in some cases. E.g. v0 schema:
```json
{"type": ["string", "object"], "properties": {}}
```

which becomes v1 schema:
```json
{
  "oneOf": [
    {"$ref": "....String"},
    {"type": "object", "properties": {}}
  ]
}
```

is being interpreted as a string, rather than object.

### CODE REVIEW

**Comment by etsybaev** [comment]
Tried to run tests locally, but got lots of fails :( 

/home/ievgeniit/Downloads/logs_normalization

Selection_264

**Comment by etsybaev** [comment]
:airbyte-integrations:bases:base-normalization:mypyCheck task seems to fail

**Comment by evantahler** [comment]
@edgao I'm going though stale PRs assigned to the team - what's the status of this one?

**Comment by edgao** [comment]
this was for protocol v1; closing

**Pull request closed without merging**
