### PR TITLE
Source Salesforce: drop ActivityMetricRollup stream

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/oncall/issues/1330

## How
Drop the stream, identically to https://github.com/airbytehq/airbyte/pull/20886

### CODE REVIEW

**Review by lazebnyi — APPROVED** [review]

**Review by roman-yermilov-gl — APPROVED** [review]

**Review by pedroslopez — APPROVED** [review]
Confirming that we have reached out to affected users about this change, more info in the oncall issue

**Pull request merged**
