### PR TITLE
🐛 Destination Redshift: Fix DATs blind spot - connection check

### LINKED ISSUE #12459: Fix DATs blind spot: connection check
https://github.com/airbytehq/airbyte/pull/9407 and https://github.com/airbytehq/airbyte/pull/9610 introduced a bug that destination-redshift's `check` operation always failed. Investigate why this did not fail our DATs, then fix DATs to catch that case.

The latest master-branch commit affected by those commits is https://github.com/airbytehq/airbyte/commit/6ef2f80eba24675e03a290e6acc368cf64e4c0e8; `git checkout` to that commit and see if the issue is reproducible.

### PR DESCRIPTION
**Pull request by alexandertsukanov**
## What
Investigating the issue I was able to find that problem appears due to `redshiftDataTmpTableMode` which was passed into RedshiftCopyS3Destination.java (Deprecated class) and subsequently fixed in the next PR:

https://github.com/airbytehq/airbyte/pull/12002/files
 
Looks like `getSqlOperations()` was called in some parent class (abstract class) and this was the root cause of the issue.
Currently, the CopyConsumerFactory approach was replaced with `StagingOperations`, and Redshift no longer uses CopyConsumerFactory. 
(PR https://github.com/airbytehq/airbyte/pull/12601/files#diff-d6c1570221cad1a2b3eeb081801329eb)

## How
Locally, I was not able to reproduce the issue with the latest Dest. redshift version. The only thing I have done is remove `redshiftDataTmpTableMode` as we don't need it anymore. The main purpose of mentioned ENUM was to support multiple 
DATA TMP table types (e.g. VARCHAR and SUPER) - this is not required, as we have only SUPER now. Let's follow the **KISS** principle.

Also, I found that we have the next integration tests:

- io/airbyte/integrations/destination/redshift/RedshiftS3StagingInsertDestinationAcceptanceTest.java (Designed to test S3 COPY)
- io/airbyte/integrations/destination/redshift/RedshiftInsertDestinationAcceptanceTest.java (Designed to test standard INSERTS)

Both are the child of  `DestinationAcceptanceTest` which contains `testCheckConnection()` method to verify whether the connection with the DB source was established successfully. ("Test connection button" on UI)

## Recommended reading order
1. `x.java`

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Review by edgao — APPROVED** [review]
:shipit:

I think the goal of the ticket was more focused on understanding why `DestinationAcceptanceTest#testCheckConnection` didn't fail. Were you able to checkout a broken version and investigate that? (the issue says https://github.com/airbytehq/airbyte/commit/6ef2f80eba24675e03a290e6acc368cf64e4c0e8 was the latest broken version)

**Comment by alexandertsukanov** [comment]
> :shipit:
> 
> I think the goal of the ticket was more focused on understanding why `DestinationAcceptanceTest#testCheckConnection` didn't fail. Were you able to checkout a broken version and investigate that? (the issue says [6ef2f80](https://github.com/airbytehq/airbyte/commit/6ef2f80eba24675e03a290e6acc368cf64e4c0e8) was the latest broken version)

@edgao 
Yep, I had also checked out `6ef2f80eba24675e03a290e6acc368cf64e4c0e8` and I tried to reproduce this issue but without success, on both combinations of options (With S3 Staging and without). All attempts of connection testing were successful.

Also, I think maybe it is somehow related to connection version bumping and the difference in the connector's specification (before the issue the version was `0.3.28`). I have tried to download 0.3.28, save the settings, and migrate to `6ef2f80eba24675e03a290e6acc368cf64e4c0e8`, but still without any result.

**Review by alexandr-shegeda — APPROVED** [review]

**Comment by edgao** [comment]
this was my bad, the issue had the wrong commit hash. I think `ae8c4f2b3a` should be broken, can you try again with that hash?

**Comment by alexandertsukanov** [comment]
@edgao I have switched to the commit, looks like the problem was here: 

https://github.com/airbytehq/airbyte/blob/ae8c4f2b3a9045380f47314b1ad2b10072b6395a/airbyte-integrations/connectors/destination-jdbc/src/main/java/io/airbyte/integrations/destination/jdbc/copy/CopyDestination.java#L60-L60

and here:

https://github.com/airbytehq/airbyte/blob/ae8c4f2b3a9045380f47314b1ad2b10072b6395a/airbyte-integrations/connectors/destination-redshift/src/main/java/io/airbyte/integrations/destination/redshift/RedshiftCopyS3Destination.java#L76-L79

As Destination Redshift operated RedshiftCopyS3Destination.java before, for S3 Staging processing - the reasonable exception was thrown. Also, I have tried `RedshiftCopyDestinationAcceptanceTest.testCheckConnection()` and test was failed, what is correct behaviour. So, I don't have an idea why this part of the code wasn't caught by the integration test before.

Screenshot 2022-05-26 at 11 22 46

The issue we faced.

**Comment by edgao** [comment]
something might be weird with how the CI tests work - I made a branch corresponding to that commit (https://github.com/airbytehq/airbyte/pull/13246), where `/test` succeeds but running tests locally fails. I think we should reopen https://github.com/airbytehq/airbyte/issues/12459 and investigate that behavior.

**Comment by alexandertsukanov** [comment]
@edgao found why this doesn't work on CI. The problem in GCM, the file SECRET_DESTINATION-REDSHIFT__CREDS doesn't contain info about the bucket that's why S3 flow never triggers. 🙂

Here is the log https://github.com/airbytehq/airbyte/runs/6621069306?check_suite_focus=true#step:11:8804
The logic in destination-redshift is pretty straightforward: 

https://github.com/airbytehq/airbyte/blob/ae8c4f2b3a9045380f47314b1ad2b10072b6395a/airbyte-integrations/connectors/destination-redshift/src/main/java/io/airbyte/integrations/destination/redshift/RedshiftDestination.java#L52-L72




__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by alexandertsukanov** [comment]
Updated secrets. Can now switch my job to the detective I think. 😁

**Comment by edgao** [comment]
nice catch! thanks for looking into it 👍

**Pull request merged**
