### PR TITLE
🎉 Source Google Ads: clarify setup fields

### LINKED ISSUE #7849: Clarify setup fields for Google Ads
## Tell us about the problem you're trying to solve
When setting up Google Ads as a source, a user generally has questions on what is required or not in the setup. 

## Describe the solution you’d like
The fields in the configuration should be listed in this order:
1. "Authenticate" should be at the very top of the configuration, right under the link to the Setup Guide. The user should complete this action first before filling in any other fields. 
2. Customer ID: this should be listed under the Authentication button. Configuration should go from general to specific as you go from top to bottom
3. Start Date - no changes
4. Custom GAQL Queries should be renamed to Custom GAQL Queries (Optional) with help text as to what it is. Users are confused on whether they should fill something in and don’t realize they don’t need to do anything.
5. Rename Login Customer ID to Login Customer ID for Managed Accounts (Optional)

### PR DESCRIPTION
**Pull request by grubberr**
Signed-off-by: Sergey Chvalyuk <grubberr@gmail.com>

## What
Screenshot 2021-11-22 at 18 28 33

## 🚨 User Impact 🚨
Are there any breaking changes? If yes, please make sure to include it here and in any changelogs with the 🚨🚨 emoji
What is the end result perceived by the user?

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

### CODE REVIEW

**Review by annalvova05 — APPROVED** [review]

**Review by midavadim — APPROVED** [review]

**Comment by nataliekwong** [comment]
@grubberr Is the Conversion window optional or required? 

If required: can you add an asterisk to the bolded part of the title, and move it to be under "Start Date"?

If optional: can you add "(optional)" to the title?

**Review by nataliekwong — APPROVED** [review]
LGTM!

**Comment by grubberr** [comment]
Screenshot 2021-11-29 at 22 21 40

@nataliekwong added

**Pull request merged**
