### PR TITLE
:bug: Source Hubspot: fix schema

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/oncall/issues/2135

## How
Change data type of the `browser.version` field of the `EmailEvents` stream

## 🚨 User Impact 🚨
Users will have to update that data type in their catalog, data that was being synced will have changed format

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`a064536b42`](https://github.com/airbytehq/airbyte/pull/27490/commits/a064536b42f018cc8e0cc711cad2d19a11029c27)) - ❌

⏲️  Total pipeline duration: 134 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5320461748)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by octavia-squidington-iii** [comment]
##  source-hubspot test report (commit [`3cc3fc8350`](https://github.com/airbytehq/airbyte/pull/27490/commits/3cc3fc83503e6dfe119a09c7b86e60062ce73a14)) - ❌

⏲️  Total pipeline duration: 129 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-hubspot/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ✅        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-hubspot docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Integration tests                                                     | ✅        |
| Acceptance tests                                                      | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5320466991)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by davydov-d** [comment]
temporarily blocked by https://github.com/airbytehq/airbyte/pull/27225, need to decide if we should revert it

**Review by lazebnyi — APPROVED** [review]

**Comment by bnchrch** [comment]
Do we have a link to the breaking change release playbook for this?

**Comment by davydov-d** [comment]
closing this PR in favour of https://github.com/airbytehq/airbyte/pull/27161/

**Pull request closed without merging**
