### PR TITLE
📝 improve error message when using unsupported JDBC type as cursor

### PR DESCRIPTION
**Pull request by edgao**
"OTHER is not supported" does not make it clear that the problem is specific to the cursor field. The error message will now be "OTHER cannot be used as a cursor" - this is still somewhat nonobvious, but will at least be easier to recognize. (discovered in https://github.com/airbytehq/oncall/issues/293)

are we still blocked on publishing source-postgres? @subodh1810

### CODE REVIEW

**Review by ryankfu — COMMENTED** [review]
LGTM, I see that this same `IllegalArgumentExcpetion` is also within `JdbcSourceOperations.java`. Should we also add this change there?

**Comment by edgao** [comment]
gah, nice catch.

**Review by ryankfu — APPROVED** [review]
LGTM, thanks for adding that last file in

**Review by grishick — APPROVED** [review]

**Comment by edgao** [comment]
/publish connector=connectors/source-cockroachdb,connectors/source-cockroachdb-strict-encrypt,connectors/source-db2,connectors/source-db2-strict-encrypt,connectors/source-mssql,connectors/source-mssql-strict-encrypt,connectors/source-mysql,connectors/source-mysql-strict-encrypt,connectors/source-postgres,connectors/source-postrges-strict-encrypt,connectors/source-snowflake,connectors/source-tidb

**Comment by edgao** [comment]
/publish connector=connectors/source-mysql,connectors/source-mysql-strict-encrypt

**Pull request merged**
