### PR TITLE
[source-mssql/postgres/mysql] fix rfr losing stream state

### PR DESCRIPTION
**Pull request by xiaohansong**
## What
On a resumed RFR attempt it seems we may lose some streams in streamStates. CDC mode only. This PR intends to fix that. 

Postgres does not have this issue but I also changed the behavior to align with other connectors.

## How

We will only report to platform with RFR streams that have been started, so the next attempt the initialLoadStream will work properly (not started streams will be recognized as initial load stream)

Now we only report resumable stream if there has been processed previously or in the current run. For example, if a sync has stream 1 and stream 2, when processing stream 1 we will only report on stream1, and when processing stream 2 we will report on both streams.

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by rodireich** [comment]
The fix LGTM
I just wonder the flip side. Was it correct that if stream state was null we didn't do initial sync?

**Comment by xiaohansong** [comment]
@rodireich I think sync is still fine but it would impact how platform does the count. They will only count the records of which stream name is in streamStates.

Still reusing the same example where first attempt ended with state

{
streamA: pk - 10
streamB: null
}

On second attempt when we initialize the state we would have

{
streamA: pk - 10
}

no streamB because of this [line](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/initialsync/MssqlInitialReadUtil.java#L358) has excluded that from showing up in initialLoadStream.

I think in the end we are just treating them as a [non rfr,](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/initialsync/MssqlInitialLoadGlobalStateManager.java#L73-L77) which does not show up in the state message for intermediate state message.

**Review by rodireich — APPROVED** [review]

**Comment by rodireich** [comment]
Thanks for elaborating. Interfacing with platform is always tricky with CDC

**Pull request merged**
