### PR TITLE
Format ConnectorMarkdownGenerator

### PR DESCRIPTION
**Pull request by evantahler**
https://github.com/airbytehq/airbyte/pull/23367 wasn't tested for formatting for some reason...

### CODE REVIEW

**Review by pedroslopez — APPROVED** [review]

**Comment by pedroslopez** [comment]
@evantahler it looks like changes to this file isn't triggering the connectors base build which is where the formatting check happens

**Comment by pedroslopez** [comment]
...or maybe that's not quite true? Upon merge this did run connectors base build but it didn't happen in this PR

**Comment by evantahler** [comment]
Looks like it always runs on master - https://github.com/airbytehq/airbyte/blob/master/.github/workflows/gradle.yml#L99

```
if: needs.changes.outputs.cli == 'true' || needs.changes.outputs.build == 'true' || (always() && github.ref == 'refs/heads/master')
```

**Comment by evantahler** [comment]
https://github.com/airbytehq/airbyte/pull/23370 should help

**Pull request merged**
