### PR TITLE
cdk: handle nullable input parameter passed from Java

### PR DESCRIPTION
**Pull request by theyueli**
fixes https://github.com/airbytehq/oncall/issues/5207

### CODE REVIEW

**Comment by stephane-airbyte** [comment]
that doesn't seem correct to me. Curious about the actual use case

**Review by stephane-airbyte — CHANGES_REQUESTED** [review]
I think it needs at least some tests with MySql and an empty namespace. As it stands, this seems to be doing something funky at best, and I'm really not sure it'll fix the problem

**Review by postamar — APPROVED** [review]
This PR LGTM, but deserves a companion PR in a connector (like Stephane said) which exercises this new code path.

Don't forget to `/publish-java-cdk` before merging. See https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/java/airbyte-cdk/README.md for details.

**Comment by theyueli** [comment]
> I think it needs at least some tests with MySql and an empty namespace. As it stands, this seems to be doing something funky at best, and I'm really not sure it'll fix the problem

@stephane-airbyte from sentry record:

```
java.lang.NullPointerException: Parameter specified as non-null is null: method io.airbyte.cdk.integrations.source.relationaldb.RelationalDbQueryUtils.getIdentifierWithQuoting, parameter identifier at io.airbyte.cdk.integrations.source.relationaldb.RelationalDbQueryUtils.getIdentifierWithQuoting(RelationalDbQueryUtils.kt) at io.airbyte.integrations.source.mysql.MySqlQueryUtils.lambda$getCursorBasedSyncStatusForStreams$8(MySqlQueryUtils.java:179) at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) at io.airbyte.integrations.source.mysql.MySqlQueryUtils.getCursorBasedSyncStatusForStreams(MySqlQueryUtils.java:164) at
```

it looks like the problem happens here from the function `getCursorBasedSyncStatusForStreams` at `MySqlQueryUtils.java`

```
        LOGGER.info("Cursor {}. Querying max cursor value for {}.{}", cursorField, namespace, name);
        final String quotedCursorField = getIdentifierWithQuoting(cursorField, quoteString);
```

Did I understand correctly? (The line number was no longer correct due to new changes I guess)

If so... does it make sense for `cursorField` to be null?

I was a bit confused when you say we need to test with empty namespace.. as it look like this was related to the `cursorField`? thanks!

**Comment by stephane-airbyte** [comment]
I don't think it makes sense for an identifier to be null. And I don't think that `''.tablename` is a valid SQL table name. 
So unless we have a connector test that executes the new codepath, I don't think this should be merged as is.
I don't know why the cursorField would be null, or what it means when the cursorField is null. this is something that needs to be understood before trying to fix the issue

**Comment by theyueli** [comment]
> I don't think it makes sense for an identifier to be null. And I don't think that `''.tablename` is a valid SQL table name. So unless we have a connector test that executes the new code path, I don't think this should be merged as is. I don't know why the cursorField would be null or what it means when the cursorField is null. This is something that needs to be understood before trying to fix the issue

After investigating, I found this issue actually probably has been fixed by another PR of @rodireich on his way of doing the resumable full refresh for MySQL.

https://github.com/airbytehq/airbyte/pull/37451/files#r1648028118

Therefore, the `getIdentifierWithQuote` function shall no longer get a null identifier anymore. 

Closing this PR and the on-call ticket. Thanks for the discussion!

**Pull request closed without merging**
