### PR TITLE
Source S3: always show S3 Access Key fields

### PR DESCRIPTION
**Pull request by ChristoGrab**
## What
- Changed S3 Access Key fields to always be visible since they are so commonly needed during setup.

## How
- Set `always-show` to True for both Access Key fields
- Removed comment about them being in Optional Fields from documentation

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`316366143d`](https://github.com/airbytehq/airbyte/pull/28639/commits/316366143d5128b829ac9ad9c0733e2b14887e4d)) - ❌

⏲️  Total pipeline duration: 02mn14s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/source-s3-show-key-fields/1690234223/316366143d5128b829ac9ad9c0733e2b14887e4d/source-s3/3.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`f687395d57`](https://github.com/airbytehq/airbyte/pull/28639/commits/f687395d57a343499e45519a3263c9152682d076)) - ❌

⏲️  Total pipeline duration: 01mn38s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/source-s3-show-key-fields/1690260755/f687395d57a343499e45519a3263c9152682d076/source-s3/3.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`2ed6b601fb`](https://github.com/airbytehq/airbyte/pull/28639/commits/2ed6b601fb8ac283ae6be25a33925a2e1525010c)) - ❌

⏲️  Total pipeline duration: 24mn27s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/source-s3-show-key-fields/1690261175/2ed6b601fb8ac283ae6be25a33925a2e1525010c/source-s3/3.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`09033ece20`](https://github.com/airbytehq/airbyte/pull/28639/commits/09033ece206d986ea15007709572aae692e48a0e)) - ❌

⏲️  Total pipeline duration: 24mn23s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/source-s3-show-key-fields/1690271254/09033ece206d986ea15007709572aae692e48a0e/source-s3/3.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`09581078fb`](https://github.com/airbytehq/airbyte/pull/28639/commits/09581078fbf18354939f053cf834bd565e643d2e)) - ❌

⏲️  Total pipeline duration: 03mn51s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| Connector version increment check                                | ❌        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/source-s3-show-key-fields/1690773997/09581078fbf18354939f053cf834bd565e643d2e/source-s3/3.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connector_ops/connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by sherifnada** [comment]
@ChristoGrab the build should be green now, feel free to proceed with merging this

**Comment by ChristoGrab** [comment]
Yup, we're green now! I think I still need approval, then should be good to merge

**Review by sherifnada — APPROVED** [review]

**Pull request merged**
