### PR TITLE
SurveyCTO: Docs Fix

### PR DESCRIPTION
**Pull request by siddhant3030**
## What
*Describe what the change is solving*

The SurveyCTO connector had some misinformation in the docs. This PR is to fix the docs for the SurveyCTO. 

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### CODE REVIEW

**Review by marcosmarxm — APPROVED** [review]

**Comment by marcosmarxm** [comment]
@siddhant3030 Airbyte is in code freeze. I'll able to merge your contribution next week only.

**Comment by siddhant3030** [comment]
@marcosmarxm can we merge this PR?

**Comment by siddhant3030** [comment]
@sajarin any update on this?

**Comment by siddhant3030** [comment]
@marcosmarxm any update on this?

**Comment by siddhant3030** [comment]
@marcosmarxm please merge this if this looks ok.

**Pull request merged**
