### PR TITLE
🐛 Allow mongodb-v2 discover operation to use temp disk file

### LINKED ISSUE #31514: [source-MongoDB] Connector throwing memory limit exceeded error during schema discovery
When setting up the MongoDB connector, user is running into an issue related to memory limit exceeded.

Workspace link https://cloud.airbyte.com/workspaces/f7e560e1-c7fc-4931-a354-813ac699cf37/source/81fa9d40-6824-40ae-9400-0dd2f73267e5

Error recieved
image

### PR DESCRIPTION
**Pull request by rodireich**

### CODE REVIEW

**Review by jdpgrailsdev — APPROVED** [review]
:shipit:

**Review by prateekmukhedkar — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-mongodb-v2 test report (commit [`bea05f88ff`](https://github.com/airbytehq/airbyte/pull/31629/commits/bea05f88ff3080c82a274289ca52202316c6bf0d)) - ❌

⏲️  Total pipeline duration: 10mn23s 

| Step                                                              | Result   |
|:------------------------------------------------------------------|:---------|
| Build connector tar                                               | ✅       |
| Java Connector Unit Tests                                         | ❌       |
| Build source-mongodb-v2 docker image for platform(s) linux/x86_64 | ✅       |
| Acceptance tests                                                  | ✅       |
| Java Connector Integration Tests                                  | ✅       |
| Validate metadata for source-mongodb-v2                           | ✅       |
| Connector version semver check                                    | ✅       |
| Connector version increment check                                 | ✅       |
| QA checks                                                         | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/31514-discover-source-mongodb-connector-throwing-memory-limit-exceeded-error-during-schema-discovery/1697752600/bea05f88ff3080c82a274289ca52202316c6bf0d/source-mongodb-v2/1.0.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:bea05f88ff3080c82a274289ca52202316c6bf0d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-mongodb-v2 test report (commit [`d0ea5cf442`](https://github.com/airbytehq/airbyte/pull/31629/commits/d0ea5cf442eedc518cb8fb92e0ff3e23539033c2)) - ✅

⏲️  Total pipeline duration: 10mn18s 

| Step                                                              | Result   |
|:------------------------------------------------------------------|:---------|
| Build connector tar                                               | ✅       |
| Java Connector Unit Tests                                         | ✅       |
| Build source-mongodb-v2 docker image for platform(s) linux/x86_64 | ✅       |
| Acceptance tests                                                  | ✅       |
| Java Connector Integration Tests                                  | ✅       |
| Validate metadata for source-mongodb-v2                           | ✅       |
| Connector version semver check                                    | ✅       |
| Connector version increment check                                 | ✅       |
| QA checks                                                         | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/31514-discover-source-mongodb-connector-throwing-memory-limit-exceeded-error-during-schema-discovery/1697753421/d0ea5cf442eedc518cb8fb92e0ff3e23539033c2/source-mongodb-v2/1.0.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d0ea5cf442eedc518cb8fb92e0ff3e23539033c2)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-mongodb-v2 test report (commit [`6bab496d6a`](https://github.com/airbytehq/airbyte/pull/31629/commits/6bab496d6a9b98c6b2b005f40a9bc4276683209c)) - ✅

⏲️  Total pipeline duration: 10mn07s 

| Step                                                              | Result   |
|:------------------------------------------------------------------|:---------|
| Build connector tar                                               | ✅       |
| Java Connector Unit Tests                                         | ✅       |
| Build source-mongodb-v2 docker image for platform(s) linux/x86_64 | ✅       |
| Acceptance tests                                                  | ✅       |
| Java Connector Integration Tests                                  | ✅       |
| Validate metadata for source-mongodb-v2                           | ✅       |
| Connector version semver check                                    | ✅       |
| Connector version increment check                                 | ✅       |
| QA checks                                                         | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/31514-discover-source-mongodb-connector-throwing-memory-limit-exceeded-error-during-schema-discovery/1697754692/6bab496d6a9b98c6b2b005f40a9bc4276683209c/source-mongodb-v2/1.0.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6bab496d6a9b98c6b2b005f40a9bc4276683209c)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

**Comment by octavia-approvington** [comment]
What are we doing again? <br/> merge and squash

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
