### PR TITLE
Unify lowcode tags

### PR DESCRIPTION
**Pull request by flash1293**
We have `language:lowcode` and `language:low-code` tags - let's unify that.

As `low-code` was used more commonly I went for that.

### CODE REVIEW

**Comment by flash1293** [comment]
FYI @alex-gron in case this has an effect on our warehouse transformations

**Review by girarda — APPROVED** [review]
:shipit:

**Comment by octavia-approvington** [comment]
What are we doing again? <br/> merge and squash

**Review by octavia-approvington — APPROVED** [review]

**Comment by natikgadzhi** [comment]
Oh, remember we talked about language tags for connectors that are supposed to be builder-compatible? I didn't quite realize we have lowcode tag with a similar purpose. Nice! /cc @ambirdsall

**Comment by ambirdsall** [comment]
@natikgadzhi yep! The initial idea was that a `language:builder` tag would be a proper subset of `language:low-code`, but in the course of the forking tech spec, Ben Church talked me around to the idea of a separate `builder` subsection, which is much more flexible/extensible in the face of future features.

**Pull request merged**
