### PR TITLE
🪟 :art: Show credit usage on chart's specific day

### LINKED ISSUE #9739: improve credit usage display
1. There's an error on the y-axis for the UI (overlapping labels / incorrect spacing)
2. Show how many credits have been purchased.
3. Tell the user how many credits they've used on a specific date.

From @nataliekwong:
```
The credits used should be shown on the row of the sync when viewing the sync history. I also think having both a compute and row threshold confuses some users, so we could make the calculation transparent (to show how it was done for each sync).

I think users would want a place to go with their billing history (date and quantity purchased), as well as a place to see what credit card is on file & change it. Essentially what the Stripe customer portal offers which could be embedded in a tab within the credits section.
```

From @erica-airbyte:
```
I have received quite a few questions on this as well. I think the big impact items here would be, seeing credit purchase history, granular breakdown by day with each sync and how many credits each sync cost, and explanation as to what a credit is.
```

### PR DESCRIPTION
**Pull request by dizel852**
## What
Closes [#9739](https://github.com/airbytehq/airbyte/issues/9739)

## How
Shows tooltip on chart with credit usage on a specific day

### CODE REVIEW

**Comment by dizel852** [comment]
@andyjih need to choose which color pallet we'd like to use (wasn't able to tag Nico also)

image

**Comment by andyjih** [comment]
@dizel852 @Upmitt I'm not sure what our options are, but what you have in the screenshot here is probably too light.

**Comment by dizel852** [comment]
> @dizel852 @Upmitt I'm not sure what our options are, but what you have in the screenshot here is probably too light. Can you make it a bit darker? Thanks!

Oh, okay. So I will just make it a little bit darker 😄 Deal

**Comment by Upmitt** [comment]
@dizel852 @andyjih excuse me for the late answer, I just see your message. Yes, the grey on the screenshot seems too light, here are our colors: https://www.figma.com/file/gMNRYVJav25pdsoxAyW7Qp/?node-id=2%3A335 - Maybe we could try the default grey. I didn't work on those screenshots since several month, if you need I can work on it next week @andyjih ?

**Comment by dizel852** [comment]
@andyjih @Upmitt I've updated the chart main color and tooltip text color using the default grey.
image

The reason why I've updated the main chart color is that if we have very low credit usage it's barely distinguished, here is an example:
image

so, WDYT?

**Comment by andyjih** [comment]
@dizel852 What are the two bars overlaid on top of one another?

**Comment by dizel852** [comment]
> What are the two bars overlaid on top of one another?

It's the default behavior after adding the `Tooltip` component. It's just slightly changing the background color of the item we currently hovering.
CPT2206081817-915x352 (1)

**Comment by andyjih** [comment]
Ah! Got it. That makes sense. Thanks!

**Comment by dizel852** [comment]
> Ah! Got it. That makes sense. Thanks!

But unfortunately, we can't use the default grey color for a chart, since it doesn't follow the WCAG, we still have a low contrast issue... Let's pick another color 😄 
image

**Comment by dizel852** [comment]
@Upmitt we need a color palette that satisfies WCAG

**Review by edmundito — APPROVED** [review]

**Review by edmundito — APPROVED** [review]

**Pull request merged**
