### PR TITLE
table => stream, column => field

### PR DESCRIPTION
**Pull request by cgardens**
## What
* We agreed on a name change. Consider the bullet bitten.

## Checklist
- [x] the compiler
- [x] ran unit tests
- [x] integration tests  (using ci)
- [x] acceptance tests (using ci)
- [x] read every instance of the word column, table in java, json, yaml and make sure they are gone or the remaining ones make sense.
- [x] do the same for ts and tsx
- [x] run it all locally

### CODE REVIEW

**Review by michel-tricot — APPROVED** [review]
How can you make sure that you didn't miss any place?

**Comment by cgardens** [comment]
* the compiler, ran unit tests and integration tests and acceptance tests

**Review by jrhizor — APPROVED** [review]
nice branch name

**Comment by cgardens** [comment]
added a checklist for how i am checking

**Pull request merged**
