### PR TITLE
docs(live-test): Update Readme

### PR DESCRIPTION
**Pull request by bnchrch**
### TL;DR
Updated Readme for live-test after using it for the first time

### What changed?
- Removed `--connection-id` from examples (since its automatic now)
- Added lints to Loom walkthrough and internal docs
- Updated CLI arguments for custom configurations

### CODE REVIEW

**Comment by bnchrch** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/37634?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#37634** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/37634?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#37633** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/37633?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#37632** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/37632?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @bnchrch and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by clnoll — APPROVED** [review]
Thank you @bnchrch!

**Comment by natikgadzhi** [comment]
`prettier --write` it, please!

**Comment by bnchrch** [comment]
### Merge activity

* **Apr 29, 12:06 PM EDT**: [Graphite](https://app.graphite.dev/github/pr/airbytehq/airbyte/37634) rebased this pull request as part of a merge.

**Pull request merged**
