### PR TITLE
Inline spec and schemas for source-activecampaign

### PR DESCRIPTION
**Pull request by ambirdsall**
## What
Moves the definitions that `source-activecampaign` currently holds in separate spec and schema files into its `manifest.yaml` file. Partially addresses https://github.com/airbytehq/oncall/issues/4085. This is separated out as a test case largely for my benefit, for better understanding the validation and publication steps for our connectors.

## How
After migrating the schema and spec files with the script code in https://github.com/airbytehq/airbyte/pull/34626, the files for this connector were separately committed into a fresh branch.

## Recommended reading order
I would think it would be easiest to go back and forth between each deleted spec and schema file and the corresponding section of `manifest.yaml`.

## 🚨 User Impact 🚨
This change should be completely undetectable to users.

## Pre-merge Actions
<strong>Updating a connector</strong>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

### CODE REVIEW

**Comment by ambirdsall** [comment]
This connector is OSS-only and does not appear to have integration tests implemented, which is (understandably enough) causing the integration tests CI check to fail. **Is `approve-and-merge` the appropriate way to handle this?** This PR is the first of a large batch of automated changes, so manually digging in and writing tests doesn't seem like an approach that will scale.

cc @alafanechere, @natikgadzhi, @girarda (apologies for blasting out a bulk notification; if there is a known best person or channel to direct questions like this in the future, do tell)

**Comment by alafanechere** [comment]
@ambirdsall it's CAT (Acceptance Tests) which is failing.
I'm seeing  the following test failures:
```
FAILED test_core.py::TestConnection::test_check[inputs0] - AssertionError: as...
FAILED test_core.py::TestConnection::test_check[inputs1] - Failed: Timeout >6...
FAILED test_core.py::TestDiscovery::test_streams_have_valid_json_schemas[inputs0]
FAILED test_core.py::TestBasicRead::test_read[inputs0] - AssertionError: At l...
```
Failing `checks`: 
This connectors has two test configs.
None of the two test config provided can accomplish a successful `check`

Failing `discovery`: invalid json schema. As your PR touches schema I'd suggest making sure this test is 🟢 .

 Failing `read`: The first test config can perform a read due to a `402` HTTP error.

In any case my recommandation would be to scope your changes to certified connectors which probably have a better testing state.

@natikgadzhi I feel like Acceptance test for non certified connectors is a recurring blocker to ship global connector changes.
Until we have greener CAT , could we consider skipping them if they fail in CI for a community connector?

**Comment by ambirdsall** [comment]
> Failing discovery: invalid json schema. As your PR touches schema I'd suggest making sure this test is 🟢 .
This test failure is because of incorrect property propagation behavior for inline schemas in the CDK, and is fixed by the changes in https://github.com/airbytehq/airbyte/pull/34853

**Comment by ambirdsall** [comment]
Now that https://github.com/airbytehq/airbyte/pull/34853 has been merged, `airbyte-ci connectors --name=source-activecampaign --use-remote-secrets test --only-step=acceptance --acceptance.-k=test_discover` is green for this branch. The remaining 3 CAT failures are also present on `master`, so they should not be blockers.

**Pull request closed without merging**
