### PR TITLE
Improve check connection performance for all JDBC-related DBs

### LINKED ISSUE #10376: Destination Snowflake: improve check connection performance
Relates to: https://github.com/airbytehq/airbyte/issues/10149

## Tell us about the problem you're trying to solve
As part of the [investigation into speeding up check connection](https://github.com/airbytehq/airbyte/issues/10149), our testing found that the check connection method (and discover schema method) for some connectors is slow (even after removing platform overhead)

Ideally, our 99 percentile for performing check connection is < 10 seconds. Given that the Kube overhead is ~5 seconds, we want the connector to finish in something like 3 seconds. This gives us 2 seconds of buffer to play with.

Results (does not include platform overhead):

* destination Postgres - ~ 4 seconds (I was using this as a generic RDS connector)
* destination Snowflake - ~ 14 seconds
* source salesforce - ~ 3 seconds

## Acceptance Criteria
* [x] Destination Snowflake check connection takes < 5 seconds

If it is necessary to remove some thoroughness in the check connection (i.e: do fewer operations and get a less granular failure message)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202102171868563/1202126527829517) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by alexandr-shegeda**
## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
Optimized `check` operation by removing the `SELECT SCHEMA` part.

## Recommended reading order
1. `AbstractJdbcDestination.java`
2. `CreateDropTableOperation.java`
3. `SnowflakeInternalStagingDestination.java`

## 🚨 User Impact 🚨
No user impact. Removed redundant schema retrieve operation in the scope of the `check` method.

## Pre-merge Checklist

- [x] Issue acceptance criteria met
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Review by grishick — APPROVED** [review]

**Comment by alexandr-shegeda** [comment]
/publish connector=connectors/destination-clickhouse-strict-encrypt

**Comment by alexandr-shegeda** [comment]
/publish connector=connectors/destination-postgres-strict-encrypt

**Comment by alexandr-shegeda** [comment]
/publish connector=connectors/destination-oracle-strict-encrypt

**Comment by alexandr-shegeda** [comment]
/publish connector=connectors/destination-mssql auto-bump-version=false

**Comment by alexandr-shegeda** [comment]
/publish connector=connectors/destination-redshift auto-bump-version=false

**Comment by marcosmarxm** [comment]
@alexandr-shegeda can you bump the redshift destination again? I didn't find information about the 35 version and excluded from Dockerhub and publish https://github.com/airbytehq/airbyte/pull/12940 with it.

**Comment by marcosmarxm** [comment]
Also would be better change the title of your PR. It's doing way more than editing Snowflake destination.

**Pull request merged**
