### PR TITLE
Remove `destination-bigquery-denormalized`

### PR DESCRIPTION
**Pull request by evantahler**
Following https://github.com/airbytehq/airbyte/pull/28488, this PR now removes the connector from the registries so that no new connections can be created with it.  This PR also removes all the code :D

### CODE REVIEW

**Comment by evantahler** [comment]
@benmoriceau what bad things will happen if I merge this PR, both setting the registries to false and removing the code.  It would be beneficial to the Destinations team remove the code early to stop having to worry about it...

**Comment by evantahler** [comment]
@bnchrch what bad things will happen if I merge this PR, both setting the registries to false and removing the code.  It would be beneficial to the Destinations team remove the code early to stop having to worry about it...

**Comment by bnchrch** [comment]
@evantahler You know what, Im not sure what exactly will happen here!

I do know nothing terribly bad as we dont do anything like delete docker images or spec caches

Ideally 
1. The publish pipeline notices its already published the version in the metadata
2. Skips the build step
3. But still publishes the metadata.yaml

Actually im pretty sure that will be what happens.

So lets merge.

Worst case scenario it doesnt do that and
1. I upload the metadata manually
2. Celebrate that someone found an edge case while Im working in that area of the codebase

**Review by edgao — APPROVED** [review]
do we need to modify anything in airbyte-ci? (I didn't find anything via grep, just doublechecking)

assuming not, :knife: kill this code

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery-denormalized test report (commit [`4229d6b00c`](https://github.com/airbytehq/airbyte/pull/30369/commits/4229d6b00c42015a4d452f9beba37e1f03ec6bd2)) - ❌

⏲️  Total pipeline duration: 25.83s 

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml | ✅        |
| Connector version semver check                                                           | ✅        |
| Connector version increment check                                                        | ❌        |
| QA checks                                                                                | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_delete-destination-bigquery-denormalized/1695660589/4229d6b00c42015a4d452f9beba37e1f03ec6bd2/destination-bigquery-denormalized/2.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:4229d6b00c42015a4d452f9beba37e1f03ec6bd2)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

**Comment by evantahler** [comment]
We haven't had a new destination-bigquery-denormalized connection on Cloud since Aug 1 ([metabase](https://airbyte.metabaseapp.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6NjMwNCwiZmlsdGVyIjpbImFuZCIsWyI9IixbImZpZWxkIiw2OTE2MyxudWxsXSwiQmlnUXVlcnkgKGRlbm9ybWFsaXplZCB0eXBlZCBzdHJ1Y3QpIl0sWyJ0aW1lLWludGVydmFsIixbImZpZWxkIiw2OTExMCxudWxsXSwtMTIsIm1vbnRoIix7ImluY2x1ZGVfY3VycmVudCI6ZmFsc2V9XSxbIj0iLFsiZmllbGQiLDI3NjMyNixudWxsXSx0cnVlXV0sImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdXSwiYnJlYWtvdXQiOltbImZpZWxkIiw2OTExMCx7InRlbXBvcmFsLXVuaXQiOiJkYXkifV1dfSwiZGF0YWJhc2UiOjJ9LCJkaXNwbGF5IjoibGluZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==)).  This should be safe to remove

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery-denormalized test report (commit [`8333df392c`](https://github.com/airbytehq/airbyte/pull/30369/commits/8333df392cefafc924031bb2bdd30b227a16279b)) - ❌

⏲️  Total pipeline duration: 23.55s 

| Step                                                                                     | Result   |
|:-----------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml | ✅        |
| Connector version semver check                                                           | ✅        |
| Connector version increment check                                                        | ❌        |
| QA checks                                                                                | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/evan_delete-destination-bigquery-denormalized/1695660914/8333df392cefafc924031bb2bdd30b227a16279b/destination-bigquery-denormalized/2.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8333df392cefafc924031bb2bdd30b227a16279b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

**Comment by octavia-approvington** [comment]
After a careful ML study, <br/> we think this looks okay.  <br/> imagine code being okay

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
