### PR TITLE
🐛 Source Google Search Console: Fix `data_state` config typo

### LINKED ISSUE #27152: Typo in `data_state` conf for google search console source
### Connector Name

source-google-search-console

### Connector Version

1.0.1

### What step the error happened?

During the sync

### Revelant information

There is a typo here and thus the `data_state` parameter is not passed.

https://github.com/airbytehq/airbyte/blob/87f2e4eb29ced14beb424bf71c5c4bee70807883/airbyte-integrations/connectors/source-google-search-console/source_google_search_console/source.py#L79

### Relevant log output

```shell
N/A
```

### Contribute

- [X] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by ciancullinan**
## What
* Fix the typo in the `data_state` config param used by the Google Search Console source.
* Closes https://github.com/airbytehq/airbyte/issues/27152

## How
* Fix typo

## Recommended reading order
1. `airbyte-integrations/connectors/source-google-search-console/source_google_search_console/source.py`

## 🚨 User Impact 🚨

No breaking changes from the documented functionality

## Pre-merge Actions

<summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

### CODE REVIEW

**Review by sajarin — CHANGES_REQUESTED** [review]
Thanks for the bug report and the PR! Can you add a line to the changelog in docs/integrations/sources/google-search-console.md

**Review by sajarin — APPROVED** [review]

**Review by marcosmarxm — APPROVED** [review]

**Comment by sajarin** [comment]
Thanks for the PR @ciancullinan!

**Pull request merged**
