### PR TITLE
Docs: mention custom objects in hubspot docs

### PR DESCRIPTION
**Pull request by sherifnada**

### CODE REVIEW

**Review by marcosmarxm — APPROVED** [review]
Thanks @sherifnada I wasn't aware of the need of this message and the additional steps.
To clarify any new Hubspot stream which needs additional scope we must add this info?

**Comment by sherifnada** [comment]
@marcosmarxm yes if we add a new stream which requires new oauth scopes the user needs to take those steps

**Comment by nataliekwong** [comment]
Note if the user is not using OAuth and instead a private key, they'll need to instead go into Hubspot and update the scopes the key has access to instead (rather than reauthenticating OAuth app permissions).

**Comment by sherifnada** [comment]
@nataliekwong good call, fixed that plus other things in https://github.com/airbytehq/airbyte/pull/26533

**Pull request merged**
