### PR TITLE
Source Freshservice API: add stream for customer satisfaction survey responses endpoint

### LINKED ISSUE #23804: Add Customer Satisfaction to Freshservice connector
## Tell us about the problem you're trying to solve
Please add customer satisfaction survey results as a stream

## Describe the solution you’d like
Customer satisfaction survey results as a new stream

## Describe the alternative you’ve considered or used
Not sure

### PR DESCRIPTION
**Pull request by aroder**
## What
Adds a stream for satisfaction survey responses. This is a distinct endpoint that is a subresource of the Tickets endpoint. 

Tickets stream already existed. This change adds a SatisfactionSurveyResponses stream.

This resolves #23804 and includes changes from PR #23945 (because I needed that bug fixed to test this PR)

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

No breaking changes

## Pre-merge Checklist
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed <-- who needs to do this?
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### CODE REVIEW

**Comment by bnchrch** [comment]
Hey @aroder Just checking in on that action run.

Looks like the python linting step failed.

You should be able to attempt that locally by running:

```
./gradlew :airbyte-integrations:connectors:source-freshservice:flakeCheck

**Comment by aroder** [comment]
@bnchrch thank you for the nudge. This is my first PR and I'm learning what to do. I corrected the flake linting errors locally, and that gradle command passes now. However the check is still failing. Any ideas what I should do from here?

**Comment by aroder** [comment]
@bnchrch @marcosmarxm it looks like I figured out what to do! All tests passing.

What is the merge and release process?

**Comment by bnchrch** [comment]
@aroder Let me run our connector acceptance tests for you and see how they do!

(unfortuantely only airbyte members can run these at the moment. Were hoping to change that soon.)

**Comment by sajarin** [comment]
Thanks for your contribution @aroder sorry that this has been taking so long. I'll try to help and get this across the finish line so we can get this merged.

**Comment by sajarin** [comment]
Merged in #25929. Thanks for the contribution @aroder!

**Pull request closed without merging**
