### PR TITLE
🎉  Source File: Added BOX provider

### LINKED ISSUE #4926: File Source: add Box storage provider
## Tell us about the problem you're trying to solve
Currently, the file source connector supports file providers such as GCS and S3.

[Box](https://www.box.com/en-ca/home) is also a cloud storage service where users can store/share files (similar to Google Drive)

Screen Shot 2021-07-22 at 4 42 40 PM

## Describe the solution you’d like
Allow users to download/sync box files from a given Box file URL. 

## Describe the alternatives you’ve considered or used
- Considered creating a new source for Box , however much of the logic from the file source would be shared.
- Adding a new provider to the file source for Box

## Are you willing to submit a PR?

Yes (in progress)

### PR DESCRIPTION
**Pull request by rdemianchuk**
## What
https://github.com/airbytehq/airbyte/issues/4926

## How
- Added new client for connect with BOX provider
- Created a custom class Box Client for get download url
- Added integration test for check private link

## 🚨 User Impact 🚨
No impact is expected

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Comment by grubberr** [comment]
@HALLOWe3n please resolve conflict and re-run tests

**Comment by lazebnyi** [comment]
@grubberr I will do that

**Review by arsenlosenko — APPROVED** [review]

**Pull request closed without merging**
