### PR TITLE
Snowflake source: keep session alive to avoid breaking connection

### LINKED ISSUE #6246: Error fetching chunk from Snowflake
## Enviroment
- **Airbyte version**: 0.29.19-alpha
- **OS Version / Instance**:  GCP c2-standard-16 (16 vCPUs, 64 GB memory)
- **Deployment**: Docker 
- **Source Connector and version**: airbyte/source-snowflake 0.1.1
- **Destination Connector and version**:  airbyte/destination-bigquery | 0.4.0 |  
- **Severity**:  Critical
- **Step where error happened**: Sync job 

## Current Behavior
Standard Insert enabled with 15M B chunk. However, I see following errors after 6 hours of Airbyte running

## Expected Behavior
Data mirrored in BigQuery but fails after mirroring few tables.

## Logs
The following is just snapshot of error. I have same error for almost 30 tables.
<details>
<summary>LOG</summary> 

```
2021-09-15 19:10:52 INFO  2021-09-15 19:10:51 [32mINFO[m i.a.i.s.r.AbstractRelationalDbSource(lambda$createReadIterator$6):315 - {} - Reading stream SAT_BDV_TEST. Records read: 43390000
2021-09-15 19:10:52 INFO  Records read: 69834000
2021-09-15 19:10:53 INFO  Records read: 69835000
2021-09-15 19:10:53 INFO  Records read: 69836000
2021-09-15 19:10:54 INFO  Records read: 69837000
2021-09-15 19:10:54 INFO  Records read: 69838000
2021-09-15 19:10:55 ERROR Sep 15, 2021 7:10:54 PM net.snowflake.client.jdbc.RestRequest execute
2021-09-15 19:10:55 ERROR SEVERE: Error response: HTTP Response code: 403, request: GET https://sfc-aus-ds1-5-customer-stage.s3.ap-southeast-2.amazonaws.com/50iy-s-auss7828/results/019ef6f0-3200-8140-0000-6f710018c1be_0/main/data_0_4_136?x-amz-server-side-encryption-customer-algorithm=AES256&response-content-encoding=gzip&AWSAccessKeyId=****&Expires=1631733039&Signature=**** HTTP/1.1
2021-09-15 19:10:55 ERROR Sep 15, 2021 7:10:55 PM net.snowflake.client.jdbc.SnowflakeChunkDownloader$2 getInputStream
2021-09-15 19:10:55 ERROR SEVERE: Error fetching chunk from: https://sfc-aus-ds1-5-customer-stage.s3.ap-southeast-2.amazonaws.com/50iy-s-auss7828/results/019ef6f0-3200-8140-0000-6f710018c1be_0/main/data_0_4_136?x-amz-server-side-encryption-customer-algorithm=AES256&response-content-encoding=gzip&AWSAccessKeyId=****&Expires=1631733039&Signature=****
2021-09-15 19:10:55 ERROR Sep 15, 2021 7:10:55 PM net.snowflake.client.jdbc.SnowflakeUtil logResponseDetails
2021-09-15 19:10:55 ERROR SEVERE: Response status line reason: Forbidden
2021-09-15 19:10:55 ERROR Sep 15, 2021 7:10:55 PM net.snowflake.client.jdbc.SnowflakeUtil logResponseDetails
2021-09-15 19:10:55 ERROR SEVERE: Response content: <?xml version="1.0" encoding="UTF-8"?>
2021-09-15 19:10:55 ERROR <Error><Code>AccessDenied</Code><Message>Request has expired</Message><Expires>2021-09-15T19:10:39Z</Expires><ServerTime>2021-09-15T19:10:55Z</ServerTime><RequestId>CBSG46H7P0PG82JC</RequestId><HostId>HrGRp2B5ufiSfgRNpGmJ914gxkTaqtD5bgKkkogYVTuamW6THiABokv1J8hQt1PT6sdNzabuDRM=</HostId></Error>
2021-09-15 19:10:55 ERROR Sep 15, 2021 7:10:55 PM net.snowflake.client.jdbc.RestRequest execute
2021-09-15 19:10:55 ERROR SEVERE: Error response: HTTP Response code: 403, request: GET https://sfc-aus-ds1-5-customer-stage.s3.ap-southeast-2.amazonaws.com/50iy-s-auss7828/results/019ef6f0-3200-8140-0000-6f710018c1be_0/main/data_0_4_136?x-amz-server-side-encryption-customer-algorithm=AES256&response-content-encoding=gzip&AWSAccessKeyId=****&Expires=1631733039&Signature=**** HTTP/1.1
2021-09-15 19:10:55 INFO  Records read: 69839000
2021-09-15 19:10:55 ERROR Sep 15, 2021 7:10:55 PM net.snowflake.client.jdbc.SnowflakeChunkDownloader$2 getInputStream
2021-09-15 19:10:55 ERROR SEVERE: Error fetching chunk from:
```
</details>

## Steps to Reproduce
1. Choose BiQuery as destination
2. Standard Insert with 15MB as chunk and transfer 1GB table from SnowFlake
3. Run job

## Are you willing to submit a PR?
No

### PR DESCRIPTION
**Pull request by sashaNeshcheret**
## What
After 6 hours of sync we got 403 error from snowflake.

## How
Added parameter CLIENT_SESSION_KEEP_ALIVE to avoid breaking connection before it closing

## Recommended reading order
1. `x.java`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>

#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by alexandertsukanov — APPROVED** [review]
LGTM

**Review by alexandr-shegeda — APPROVED** [review]
LGTM. we can proceed with publishing and merging without airbyte review

**Review by mkhokh-33 — APPROVED** [review]

**Comment by harshild** [comment]
Looks like this was fixed a while back, but our team is facing the same issue with snowflake source connector version `0.3.1`

**Pull request merged**
