### PR TITLE
🎉 Source bigcommerce: add brands and categories streams

### PR DESCRIPTION
**Pull request by PhilipCorr**
## What
Add two new streams. One for brands and one for categories.

## How
The endpoints for these are described here:
https://developer.bigcommerce.com/api-reference/c2610608c20c8-get-all-brands
https://developer.bigcommerce.com/api-reference/9cc3a53863922-get-all-categories

They are both very similar in that the url matches:
```
https://api.bigcommerce.com/stores/{store_hash}/v3/catalog/{data_field}
```
where the data field is either `brands` or `categories`.
Neither of these endpoints have a date field that can be used for incremental syncing.
Instead, similar to the existing `Pages` source, they have an `id` field.
This is why we need to override the `read_records` method and explicitly call the `filter_records_newer_than_state` method.

## Recommended reading order
Start with `source.py`.
Everything should make sense after that as the streams are reasonably standard. 

## 🚨 User Impact 🚨
No breaking changes. This just adds two new streams which the user can opt into pulling if they want.

## Pre-merge Checklist
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

There are no unit tests for the bigcommerce connector.

</details>

<details><summary><strong>Integration</strong></summary>

There are no integration tests for the bigcommerce connector.

</details>

<details><summary><strong>Acceptance</strong></summary>

===========================================================================================
../../bases/source-acceptance-test/source_acceptance_test/config.py:257: 30 warnings
airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py: 1 warning
  /Users/phil/Repos/phil/airbyte/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/config.py:257: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
    logging.warn("The acceptance-test-config.yml file is in a legacy format. Please migrate to the latest format.")

-- Docs: https://docs.pytest.org/en/stable/warnings.html

Results (26.17s):
      31 passed

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

**Comment by haithem-souala** [comment]
Hey @PhilipCorr, thank you for your contribution.
Ill review your PR very soon.

**Review by haithem-souala — APPROVED** [review]

**Comment by haithem-souala** [comment]
Your PR looks good, i will publish the connector soon.

**Comment by haithem-souala** [comment]
/publish connector=connectors/source-bigcommerce run-tests=false

**Comment by haithem-souala** [comment]
@sajarin this PR is ready to merge.
Thank you @PhilipCorr again, for your contribution!

**Comment by PhilipCorr** [comment]
Hi @haithem-souala and @sajarin, are we happy to merge this PR? Thanks!

**Comment by haithem-souala** [comment]
> Hi @haithem-souala and @sajarin it would be great to get this merged soon if possible. It's starting to block some work that I have ongoing. Thanks!

Hi @PhilipCorr, I am reaching out to some members of the Airbyte team to request the merging of this PR. As you may be aware, the merge process was on hold from December 19th to December 30th. I appreciate your patience.

**Comment by sajarin** [comment]
Thanks @PhilipCorr for the PR and thanks @haithem-souala for the review :)

**Pull request merged**
