### PR TITLE
Source Stripe: Files and TopUps stream

### LINKED ISSUE #26478: Source Stripe: new stream File Links
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[File Links](https://stripe.com/docs/api/file_links)
To share the contents of a File object with non-Stripe users, you can create a FileLink. FileLinks contain a URL that can be used to retrieve the contents of the file without authentication.
[The file link object](https://stripe.com/docs/api/file_links/object)

## Describe the solution you’d like
Research pros and cons for implementing this stream

### LINKED ISSUE #26479: Source Stripe: new stream Files
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[Files](https://stripe.com/docs/api/files)
This is an object representing a file hosted on Stripe's servers. The file may have been uploaded by yourself using the [create file](https://stripe.com/docs/api/files#create_file) request (for example, when uploading dispute evidence) or it may have been created by Stripe (for example, the results of a [Sigma scheduled query](https://stripe.com/docs/api/files#scheduled_queries)).
[The file object](https://stripe.com/docs/api/files/object)

## Describe the solution you’d like
Research pros and cons for implementing this stream

### LINKED ISSUE #26482: Source Stripe: new stream Top-ups
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[Top-ups](https://stripe.com/docs/api/topups)
To top up your Stripe balance, you create a top-up object. You can retrieve individual top-ups, as well as list all top-ups. Top-ups are identified by a unique, random ID.
[The top-up object](https://stripe.com/docs/api/topups/object)

## Describe the solution you’d like
Research pros and cons for implementing this stream

### PR DESCRIPTION
**Pull request by roman-yermilov-gl**
## What
- https://github.com/airbytehq/airbyte/issues/26482
- https://github.com/airbytehq/airbyte/issues/26479
- https://github.com/airbytehq/airbyte/issues/26478
- There is a bug in `next_page_token` method `if` statement that always returns True

## How
Added new sterams:
- TopUps ([doc](https://stripe.com/docs/api/topups))
- Files ([doc](https://stripe.com/docs/api/files))
- FileLinks ([doc](https://stripe.com/docs/api/file_links))
- Made refactoring

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`c4317c13de`](https://github.com/airbytehq/airbyte/pull/27238/commits/c4317c13deaa4df08e3014834c28dfd2a25071ca)) - ❌

⏲️  Total pipeline duration: 51 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ❌        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5271915078)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`3501707b5a`](https://github.com/airbytehq/airbyte/pull/27238/commits/3501707b5a471b1ae37d12ab7c16388c970f6f39)) - ❌

⏲️  Total pipeline duration: 42 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ❌        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5271927939)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`13e3956a32`](https://github.com/airbytehq/airbyte/pull/27238/commits/13e3956a320551601aa1ebc278168fffe53de31e)) - ❌

⏲️  Total pipeline duration: 59 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ❌        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5271951389)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`264718aac7`](https://github.com/airbytehq/airbyte/pull/27238/commits/264718aac73f0e77d11e8ee1714bd9b6b5c80dcd)) - ❌

⏲️  Total pipeline duration: 59 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ❌        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5271974846)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Comment by octavia-squidington-iii** [comment]
##  source-stripe test report (commit [`9479eb3040`](https://github.com/airbytehq/airbyte/pull/27238/commits/9479eb30401035b370b36c497880366befd67220)) - ✅

⏲️  Total pipeline duration: 373 seconds

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-stripe/metadata.yaml | ✅        |
| Connector version semver check.                                      | ✅        |
| Connector version increment check.                                   | ✅        |
| QA checks                                                            | ✅        |
| Connector package install                                            | ✅        |
| Build source-stripe docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5271992430)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Review by bnchrch — APPROVED** [review]
This is a REALLY well done PR.
1. The description was informative about what changed (WITH LINKS!)
2. The bypass reason that was added was clear.

Thank you this looks great to me.

**Pull request merged**
