### PR TITLE
Run CI checks for Source Mailchimp: Add new List Member & Member Info Streams

### PR DESCRIPTION
**Pull request by sajarin**
## What
Runs CI checks for #27177 

## How
Added two new streams to the mailchimp connector

## Recommended reading order
1. `y.python`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added
</details>

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-mailchimp test report (commit [`fda603b8b8`](https://github.com/airbytehq/airbyte/pull/27931/commits/fda603b8b810315dc9d6c3086fdfdaa91527b8d9)) - ❌

⏲️  Total pipeline duration: 05mn01s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mailchimp/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ❌        |
| Connector package install                                               | ✅        |
| Build source-mailchimp docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/saj_mailchimp-list/1688411819/fda603b8b810315dc9d6c3086fdfdaa91527b8d9/source-mailchimp/0.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mailchimp test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mailchimp test report (commit [`8a8ed0628a`](https://github.com/airbytehq/airbyte/pull/27931/commits/8a8ed0628a06aa4a96d6230e8a2c81b625b25297)) - ❌

⏲️  Total pipeline duration: 06mn02s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mailchimp/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-mailchimp docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/saj_mailchimp-list/1688755884/8a8ed0628a06aa4a96d6230e8a2c81b625b25297/source-mailchimp/0.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mailchimp test
```

**Comment by octavia-squidington-iii** [comment]
##  source-mailchimp test report (commit [`daf0587aac`](https://github.com/airbytehq/airbyte/pull/27931/commits/daf0587aac4347be96016a3cf8b9e4a570ccdd34)) - ❌

⏲️  Total pipeline duration: 04mn53s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-mailchimp/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-mailchimp docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Acceptance tests                                                        | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/saj_mailchimp-list/1689192507/daf0587aac4347be96016a3cf8b9e4a570ccdd34/source-mailchimp/0.5.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mailchimp test
```

**Comment by ChristoGrab** [comment]
Closing as this endpoint has been merged in #32032

**Pull request closed without merging**
