### PR TITLE
Remove legacy sentry code from cdk

### PR DESCRIPTION
**Pull request by Phlair**
## What
Part of https://github.com/airbytehq/airbyte/issues/13335, removing legacy sentry code in favour of the [new integration with sentry](https://github.com/airbytehq/airbyte/pull/13899/files) for the [connector incident management system](https://github.com/airbytehq/airbyte-cloud/issues/1506)

## How
Removed the code

### CODE REVIEW

**Review by sherifnada — APPROVED** [review]

**Review by pedroslopez — APPROVED** [review]
We can also remove anywhere we were setting `SENTRY_DSN` for CDK connectors, e.g. 

https://github.com/airbytehq/airbyte/blob/5aed8e214702539396ccfa8521c35483a16b06ae/airbyte-integrations/connectors/source-google-search-console/Dockerfile#L13

**Pull request merged**
