### PR TITLE
Python CDK: Add connector state to the streams() function so streams can utilize it when running nested streams in incremental mode

### PR DESCRIPTION
**Pull request by cjwooo**
## What
Some Source streams rely on the output of one or more other streams. Currently, this is done by running those nested streams in full refresh mode, even if those nested streams are usually run in incremental mode. This PR fixes that by adding the source state at the start of the sync to the streams() functions.

## How
By adding the state as a parameter to `streams()`, streams can pass stream states to their nested streams to run them in incremental mode, which should increase connector performance since the stream should make fewer API calls to the source system. Also, this should enable the results of the API calls to be cached (e.g. with the VCR library) for additional calls of those nested streams.

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Thanks @cjwooo! We're going to review this contribution tomorrow!

**Review by Phlair — CHANGES_REQUESTED** [review]
Thanks for the contribution @cjwooo! I could see giving stream instances their initial state as an attribute being useful.
I think these changes would break backwards compatibility though, as `connector_state` becomes a new parameter to define in the abstractmethod `streams`, which all existing connectors won't have and therefore they would fail. Maybe you could implement this in a way that avoids that problem? Otherwise it would definitely be worth creating an issue for so we can include it in a cdk v2 where breaking changes can happen. 

A note on the files changed here. Confusingly, this `abstract_source.py` is deprecated in favour of [this one](https://github.com/airbytehq/airbyte/blob/1773e41e47a69d22a1c575bb8a13f34aa4ed06a7/airbyte-cdk/python/airbyte_cdk/sources/abstract_source.py). That's where the cdk now lives and [we have an issue](https://github.com/airbytehq/airbyte/issues/6164) for clearing out the old base-python code. Any CDK changes will need to go there instead.

**Review by Phlair — COMMENTED** [review]
Hi @cjwooo, apologies for the delay, I had some time off and left this hanging, sorry!

I like this new approach, very clean, thanks for the changes. 

@sherifnada do you have any qualms with this going in?

**Comment by sherifnada** [comment]
@cjwooo quick question to make sure I understand the situation correctly: what is the API/endpoints that would benefit from this addition? Is there a concrete example that can help clarify the picture here? 

I'm asking because my mental model for state/nested stream interactions is in that situation, the parent stream state would generally be derived from the child stream's state rather than the child using whatever state the parent happened to have

Plus, I'm wary of using global state because it makes it difficult to do things like table-level resets, a feature which is currently WIP and will be used for things like schema evolution etc.. so there is an incentive to keep stream siloed per stream

would be super appreciative if you can help provide context on these things

**Comment by cjwooo** [comment]
One example that I believe would benefit from this addition is the IssueComments stream in the Jira source: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-jira/source_jira/streams.py#L276. Currently, it must first run the Issues stream in Full Refresh mode, even the Issues stream might be specified to run in incremental mode by the user. This could be a large performance hit as Jira projects can have thousands of issues. My thought process is, if the user specifies the Issues stream to run in incremental mode, they would probably prefer to run the IssueComments stream, and other issue-related streams like IssueVotes, in incremental mode as well.

With this addition, streams that depend on the Issues stream can simply pass the current Issues stream state to its `read_records` method, so that only the issue records by the Issues stream during its normal execution would be read by the IssueComments stream and other issue-related streams. Plus, I believe this means that only one round of Jira API requests would be sent by the Issues stream, as all subsequent uses of the stream would use the cached responses, since they all are based from the same stream state.

I had considered your model as well, where the child stream can derive a parent stream state from its own state, but I was worried of the possibility of creating timestamp discrepancies that would miss records in the parent stream. Although, thinking about it again, I can't think of a scenario that would force that to happen.

**Comment by cjwooo** [comment]
@sherifnada After re-thinking, I don't think this PR is needed. Like you said, the child stream can use its own state to determine a proper state for the parent stream.

**Pull request closed without merging**
