### PR TITLE
Source Linkedin Ads, Facebook Marketing, GSC: fix builds

### PR DESCRIPTION
**Pull request by davydov-d**
## What
Fix builds for GSC, FB Marketing and Linkedin Ads

## How
- Migrate to the new base image for GSC
- Update expected records for FB Marketing and Linkedin Ads

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-google-search-console test report (commit [`6afc65f405`](https://github.com/airbytehq/airbyte/pull/31863/commits/6afc65f40567efab31f35d8f4781545d67559f7d)) - ❌

⏲️  Total pipeline duration: 57.32s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build source-google-search-console docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                                  | ❌       |
| Code format checks                                                          | ✅       |
| Validate metadata for source-google-search-console                          | ✅       |
| Connector version semver check                                              | ✅       |
| Connector version increment check                                           | ✅       |
| QA checks                                                                   | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-fix-fb-gsc-notion-linkedin/1698317384/6afc65f40567efab31f35d8f4781545d67559f7d/source-google-search-console/1.3.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6afc65f40567efab31f35d8f4781545d67559f7d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-search-console test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-linkedin-ads test report (commit [`6afc65f405`](https://github.com/airbytehq/airbyte/pull/31863/commits/6afc65f40567efab31f35d8f4781545d67559f7d)) - ❌

⏲️  Total pipeline duration: 04mn42s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build source-linkedin-ads docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                         | ✅       |
| Acceptance tests                                                   | ❌       |
| Check our base image is used                                       | ✅       |
| Code format checks                                                 | ✅       |
| Validate metadata for source-linkedin-ads                          | ✅       |
| Connector version semver check                                     | ✅       |
| QA checks                                                          | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-fix-fb-gsc-notion-linkedin/1698317384/6afc65f40567efab31f35d8f4781545d67559f7d/source-linkedin-ads/0.6.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6afc65f40567efab31f35d8f4781545d67559f7d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-linkedin-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-google-search-console test report (commit [`6afc65f405`](https://github.com/airbytehq/airbyte/pull/31863/commits/6afc65f40567efab31f35d8f4781545d67559f7d)) - ❌

⏲️  Total pipeline duration: 27.82s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build source-google-search-console docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                                  | ❌       |
| Code format checks                                                          | ✅       |
| Validate metadata for source-google-search-console                          | ✅       |
| Connector version semver check                                              | ✅       |
| Connector version increment check                                           | ✅       |
| QA checks                                                                   | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-fix-fb-gsc-notion-linkedin/1698319245/6afc65f40567efab31f35d8f4781545d67559f7d/source-google-search-console/1.3.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6afc65f40567efab31f35d8f4781545d67559f7d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-search-console test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-linkedin-ads test report (commit [`6afc65f405`](https://github.com/airbytehq/airbyte/pull/31863/commits/6afc65f40567efab31f35d8f4781545d67559f7d)) - ❌

⏲️  Total pipeline duration: 03mn49s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build source-linkedin-ads docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                         | ✅       |
| Acceptance tests                                                   | ❌       |
| Check our base image is used                                       | ✅       |
| Code format checks                                                 | ✅       |
| Validate metadata for source-linkedin-ads                          | ✅       |
| Connector version semver check                                     | ✅       |
| QA checks                                                          | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-fix-fb-gsc-notion-linkedin/1698319245/6afc65f40567efab31f35d8f4781545d67559f7d/source-linkedin-ads/0.6.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:6afc65f40567efab31f35d8f4781545d67559f7d)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-linkedin-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-google-search-console test report (commit [`aa15d4ee35`](https://github.com/airbytehq/airbyte/pull/31863/commits/aa15d4ee35f6a7f370bf1796e1913446415cfe12)) - ❌

⏲️  Total pipeline duration: 26.80s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build source-google-search-console docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                                  | ❌       |
| Code format checks                                                          | ✅       |
| Validate metadata for source-google-search-console                          | ✅       |
| Connector version semver check                                              | ✅       |
| Connector version increment check                                           | ✅       |
| QA checks                                                                   | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-fix-fb-gsc-notion-linkedin/1698319661/aa15d4ee35f6a7f370bf1796e1913446415cfe12/source-google-search-console/1.3.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:aa15d4ee35f6a7f370bf1796e1913446415cfe12)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-search-console test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-linkedin-ads test report (commit [`aa15d4ee35`](https://github.com/airbytehq/airbyte/pull/31863/commits/aa15d4ee35f6a7f370bf1796e1913446415cfe12)) - ❌

⏲️  Total pipeline duration: 03mn43s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build source-linkedin-ads docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                         | ✅       |
| Acceptance tests                                                   | ❌       |
| Check our base image is used                                       | ✅       |
| Code format checks                                                 | ✅       |
| Validate metadata for source-linkedin-ads                          | ✅       |
| Connector version semver check                                     | ✅       |
| QA checks                                                          | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-fix-fb-gsc-notion-linkedin/1698319661/aa15d4ee35f6a7f370bf1796e1913446415cfe12/source-linkedin-ads/0.6.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:aa15d4ee35f6a7f370bf1796e1913446415cfe12)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-linkedin-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-google-search-console test report (commit [`880d694098`](https://github.com/airbytehq/airbyte/pull/31863/commits/880d694098613f6451fb4fa93badaf0e37bcdd36)) - ❌

⏲️  Total pipeline duration: 30.25s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build source-google-search-console docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                                  | ❌       |
| Code format checks                                                          | ✅       |
| Validate metadata for source-google-search-console                          | ✅       |
| Connector version semver check                                              | ✅       |
| Connector version increment check                                           | ✅       |
| QA checks                                                                   | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-fix-fb-gsc-notion-linkedin/1698321139/880d694098613f6451fb4fa93badaf0e37bcdd36/source-google-search-console/1.3.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:880d694098613f6451fb4fa93badaf0e37bcdd36)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-search-console test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-linkedin-ads test report (commit [`880d694098`](https://github.com/airbytehq/airbyte/pull/31863/commits/880d694098613f6451fb4fa93badaf0e37bcdd36)) - ✅

⏲️  Total pipeline duration: 03mn55s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build source-linkedin-ads docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                         | ✅       |
| Acceptance tests                                                   | ✅       |
| Check our base image is used                                       | ✅       |
| Code format checks                                                 | ✅       |
| Validate metadata for source-linkedin-ads                          | ✅       |
| Connector version semver check                                     | ✅       |
| QA checks                                                          | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-fix-fb-gsc-notion-linkedin/1698321139/880d694098613f6451fb4fa93badaf0e37bcdd36/source-linkedin-ads/0.6.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:880d694098613f6451fb4fa93badaf0e37bcdd36)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-linkedin-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-facebook-marketing test report (commit [`880d694098`](https://github.com/airbytehq/airbyte/pull/31863/commits/880d694098613f6451fb4fa93badaf0e37bcdd36)) - ✅

⏲️  Total pipeline duration: 17mn38s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build source-facebook-marketing docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                               | ✅       |
| Integration tests                                                        | ✅       |
| Acceptance tests                                                         | ✅       |
| Check our base image is used                                             | ✅       |
| Code format checks                                                       | ✅       |
| Validate metadata for source-facebook-marketing                          | ✅       |
| Connector version semver check                                           | ✅       |
| QA checks                                                                | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-fix-fb-gsc-notion-linkedin/1698321139/880d694098613f6451fb4fa93badaf0e37bcdd36/source-facebook-marketing/1.1.17/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:880d694098613f6451fb4fa93badaf0e37bcdd36)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Review by bazarnov — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-linkedin-ads test report (commit [`a8503b28c0`](https://github.com/airbytehq/airbyte/pull/31863/commits/a8503b28c05e254b07f4e5a440fe55658ca0f82a)) - ✅

⏲️  Total pipeline duration: 09mn41s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build source-linkedin-ads docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                         | ✅       |
| Acceptance tests                                                   | ✅       |
| Check our base image is used                                       | ✅       |
| Code format checks                                                 | ✅       |
| Validate metadata for source-linkedin-ads                          | ✅       |
| Connector version semver check                                     | ✅       |
| QA checks                                                          | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-fix-fb-gsc-notion-linkedin/1698333870/a8503b28c05e254b07f4e5a440fe55658ca0f82a/source-linkedin-ads/0.6.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:a8503b28c05e254b07f4e5a440fe55658ca0f82a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-linkedin-ads test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-google-search-console test report (commit [`a8503b28c0`](https://github.com/airbytehq/airbyte/pull/31863/commits/a8503b28c05e254b07f4e5a440fe55658ca0f82a)) - ✅

⏲️  Total pipeline duration: 12mn44s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build source-google-search-console docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                                  | ✅       |
| Acceptance tests                                                            | ✅       |
| Check our base image is used                                                | ✅       |
| Code format checks                                                          | ✅       |
| Validate metadata for source-google-search-console                          | ✅       |
| Connector version semver check                                              | ✅       |
| Connector version increment check                                           | ✅       |
| QA checks                                                                   | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-fix-fb-gsc-notion-linkedin/1698333870/a8503b28c05e254b07f4e5a440fe55658ca0f82a/source-google-search-console/1.3.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:a8503b28c05e254b07f4e5a440fe55658ca0f82a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-search-console test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-facebook-marketing test report (commit [`a8503b28c0`](https://github.com/airbytehq/airbyte/pull/31863/commits/a8503b28c05e254b07f4e5a440fe55658ca0f82a)) - ✅

⏲️  Total pipeline duration: 84mn57s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Build source-facebook-marketing docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                               | ✅       |
| Integration tests                                                        | ✅       |
| Acceptance tests                                                         | ✅       |
| Check our base image is used                                             | ✅       |
| Code format checks                                                       | ✅       |
| Validate metadata for source-facebook-marketing                          | ✅       |
| Connector version semver check                                           | ✅       |
| QA checks                                                                | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-fix-fb-gsc-notion-linkedin/1698333870/a8503b28c05e254b07f4e5a440fe55658ca0f82a/source-facebook-marketing/1.1.17/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:a8503b28c05e254b07f4e5a440fe55658ca0f82a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-facebook-marketing test
```

**Pull request merged**
