### PR TITLE
🐛 Source Jira: fix incorrect types in issue schema

### PR DESCRIPTION
**Pull request by archangelic**
## What
in the `issue` schema, the properties `aggregatetimeoriginalestimate` and `timeoriginalestimate` should be strings. This corrects those types

## How
*Describe the solution*

## Recommended reading order
1. `schemas/issue.json`

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`0cdfb34414`](https://github.com/airbytehq/airbyte/pull/31080/commits/0cdfb34414320e4d26d020c373bce3430f07dbe2)) - ❌

⏲️  Total pipeline duration: 01mn01s 

| Step                                                        | Result   |
|:------------------------------------------------------------|:---------|
| Connector package install                                   | ✅        |
| Build source-jira docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                  | ❌        |
| Code format checks                                          | ✅        |
| Validate metadata for source-jira                           | ✅        |
| Connector version semver check                              | ✅        |
| Connector version increment check                           | ❌        |
| QA checks                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/mal_jira-schema-fix/1696455201/0cdfb34414320e4d26d020c373bce3430f07dbe2/source-jira/0.9.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:0cdfb34414320e4d26d020c373bce3430f07dbe2)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`b86bc47d65`](https://github.com/airbytehq/airbyte/pull/31080/commits/b86bc47d65ab89c79ea0ff6b52c2439c7eda61c0)) - ❌

⏲️  Total pipeline duration: 10mn47s 

| Step                                                        | Result   |
|:------------------------------------------------------------|:---------|
| Connector package install                                   | ✅        |
| Build source-jira docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                  | ✅        |
| Integration tests                                           | ✅        |
| Acceptance tests                                            | ❌        |
| Code format checks                                          | ✅        |
| Validate metadata for source-jira                           | ✅        |
| Connector version semver check                              | ✅        |
| Connector version increment check                           | ❌        |
| QA checks                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/mal_jira-schema-fix/1696886015/b86bc47d65ab89c79ea0ff6b52c2439c7eda61c0/source-jira/0.9.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b86bc47d65ab89c79ea0ff6b52c2439c7eda61c0)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`ef021826ec`](https://github.com/airbytehq/airbyte/pull/31080/commits/ef021826ec3e223f9d25ddf681a40d2bcd850372)) - ❌

⏲️  Total pipeline duration: 10mn01s 

| Step                                                        | Result   |
|:------------------------------------------------------------|:---------|
| Connector package install                                   | ✅        |
| Build source-jira docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                  | ✅        |
| Integration tests                                           | ✅        |
| Acceptance tests                                            | ✅        |
| Code format checks                                          | ✅        |
| Validate metadata for source-jira                           | ✅        |
| Connector version semver check                              | ✅        |
| Connector version increment check                           | ❌        |
| QA checks                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/mal_jira-schema-fix/1696893369/ef021826ec3e223f9d25ddf681a40d2bcd850372/source-jira/0.9.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ef021826ec3e223f9d25ddf681a40d2bcd850372)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`a999ca681c`](https://github.com/airbytehq/airbyte/pull/31080/commits/a999ca681ce736ba1bd08594e93493a1c0c3fd9f)) - ❌

⏲️  Total pipeline duration: 09mn49s 

| Step                                                        | Result   |
|:------------------------------------------------------------|:---------|
| Connector package install                                   | ✅        |
| Build source-jira docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                  | ✅        |
| Integration tests                                           | ✅        |
| Acceptance tests                                            | ✅        |
| Code format checks                                          | ✅        |
| Validate metadata for source-jira                           | ❌        |
| Connector version semver check                              | ✅        |
| Connector version increment check                           | ✅        |
| QA checks                                                   | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/mal_jira-schema-fix/1696894887/a999ca681ce736ba1bd08594e93493a1c0c3fd9f/source-jira/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:a999ca681ce736ba1bd08594e93493a1c0c3fd9f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`76030c7225`](https://github.com/airbytehq/airbyte/pull/31080/commits/76030c72254e2cb5cd6e80c37b3716dfdb296919)) - ❌

⏲️  Total pipeline duration: 05mn32s 

| Step                                                        | Result   |
|:------------------------------------------------------------|:---------|
| Connector package install                                   | ✅        |
| Build source-jira docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                  | ✅        |
| Integration tests                                           | ✅        |
| Acceptance tests                                            | ✅        |
| Code format checks                                          | ✅        |
| Validate metadata for source-jira                           | ✅        |
| Connector version semver check                              | ✅        |
| Connector version increment check                           | ✅        |
| QA checks                                                   | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/mal_jira-schema-fix/1696895747/76030c72254e2cb5cd6e80c37b3716dfdb296919/source-jira/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:76030c72254e2cb5cd6e80c37b3716dfdb296919)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`f4ab999973`](https://github.com/airbytehq/airbyte/pull/31080/commits/f4ab9999733bc1bb42d7ca1e5abf9398aa83496c)) - ✅

⏲️  Total pipeline duration: 10mn14s 

| Step                                                        | Result   |
|:------------------------------------------------------------|:---------|
| Connector package install                                   | ✅        |
| Build source-jira docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                  | ✅        |
| Integration tests                                           | ✅        |
| Acceptance tests                                            | ✅        |
| Code format checks                                          | ✅        |
| Validate metadata for source-jira                           | ✅        |
| Connector version semver check                              | ✅        |
| Connector version increment check                           | ✅        |
| QA checks                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/mal_jira-schema-fix/1696953740/f4ab9999733bc1bb42d7ca1e5abf9398aa83496c/source-jira/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f4ab9999733bc1bb42d7ca1e5abf9398aa83496c)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Review by sajarin — APPROVED** [review]

**Review by marcosmarxm — DISMISSED** [review]
Right now all expected records have null values.
Is there an explicit documentation saying these fields are string type?
Is it possible to add some data into Airbyte integration account to validate the change?

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`02bab1d91c`](https://github.com/airbytehq/airbyte/pull/31080/commits/02bab1d91ca011de76b8b0c58846ac1306021ad6)) - ❌

⏲️  Total pipeline duration: 09mn47s 

| Step                                                        | Result   |
|:------------------------------------------------------------|:---------|
| Build source-jira docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                  | ✅        |
| Integration tests                                           | ✅        |
| Acceptance tests                                            | ❌        |
| Code format checks                                          | ✅        |
| Validate metadata for source-jira                           | ✅        |
| Connector version semver check                              | ✅        |
| Connector version increment check                           | ✅        |
| QA checks                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/mal_jira-schema-fix/1697144462/02bab1d91ca011de76b8b0c58846ac1306021ad6/source-jira/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:02bab1d91ca011de76b8b0c58846ac1306021ad6)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`2b6ad7503b`](https://github.com/airbytehq/airbyte/pull/31080/commits/2b6ad7503b0b249f9fce632fa3f1b2efe6daaffc)) - ✅

⏲️  Total pipeline duration: 09mn43s 

| Step                                                        | Result   |
|:------------------------------------------------------------|:---------|
| Build source-jira docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                  | ✅        |
| Integration tests                                           | ✅        |
| Acceptance tests                                            | ✅        |
| Code format checks                                          | ✅        |
| Validate metadata for source-jira                           | ✅        |
| Connector version semver check                              | ✅        |
| Connector version increment check                           | ✅        |
| QA checks                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/mal_jira-schema-fix/1697145719/2b6ad7503b0b249f9fce632fa3f1b2efe6daaffc/source-jira/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:2b6ad7503b0b249f9fce632fa3f1b2efe6daaffc)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Comment by archangelic** [comment]
Solved in #31385

**Pull request closed without merging**
