### PR TITLE
🎉 New CDK: Dotnet/.NET/C#  implementation + free exchange rates source connector

### PR DESCRIPTION
**Pull request by mrhamburg**
## What
Added 2 items:

1. A dotnet based CDK for connector development, including unit tests and a fluent stream builder. Should be on feature parity with the python based CDK, if not, please let me know where there are any gaps
2. A dotnet cdk implemented exchange rates api which 1. does not require an api key and 2. which allows for retrieval of all base symbols

While there are some open ends, see the list below, I already pushed this draft PR for early review by the internal Airbyte team. Fail fast 😉

## How
Implemented features and their dependencies:
- [X] Airbyte protocol
  - [ ] Not sure if I implemented the primary key type correctly, had some issues when trying out the exchange rates implementation, resolved it, but did not verify the solution
- [X] HttpStream
  - [X] Backoff and retry mechanism (using [Polly](https://github.com/App-vNext/Polly))
  - [X] Basic and Oauth authorization implementation (using [Flurl](https://github.com/tmenier/Flurl))
  - [X] Catalog schema validation (using [JsonSchema.Net](https://github.com/gregsdennis/json-everything))
- [X] CommandLine implementation read and to some extent write, but I saw that the python CDK does not have any helper classes for creating write connectors yet (using [CommandLineParser](https://github.com/commandlineparser/commandline))
- [X] A fluent Http stream builder, personal preference, off course you can implement classes as well, if you prefer
- [X] Unit tests where needed
- [X] Implements the "_limit" and "_page_size" general configuration

## Recommended reading order
1. C# CDK -> airbyte/airbyte-cdk/dotnet
2. C# CDK Implementation example -> airbyte/airbyte-integrations/connectors/source-exchange-rates-free

**Note, this is a draft PR. the following items are still open**
- [x] Integration with current build and release pipelines
- [x] The dotnet cdk has a dockerfile for testing and building a nuget package and pushing a new version of this nuget package to a nuget feed to host the CDK library. I doubt Airbyte already has a nuget feed, details for this feed will need be integrated with the CI/CD pipelines (done via ENV variables)
- [x] The placement of the gitignore for dotnet related items can be improved, currently all individual connectors will need to use their own gitignore to make sure build items are excluded from git
- [ ] Documentation: 
  - [x] Dotnet CDK
  - [x] Fluent stream builder
  - [ ] Free exchange rates source

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hey @mrhamburg this contribution is amazing!

**Comment by michel-tricot** [comment]
whoa 🎉 , thank you @mrhamburg!

**Comment by sherifnada** [comment]
@mrhamburg superb! Let us know how we can help

**Comment by mrhamburg** [comment]
@marcosmarxm, @sherifnada, @michel-tricot. I have added a connector generator, added some documentation, made a github actions pipeline (first time, so it still needs testing) and created a nuget account: [NuGet](https://www.nuget.org/packages/Airbyte.Cdk/0.0.2-preview)

My questions for now are:
- who(m) should I provide the api keys for nuget to push new versions of the cdk?

What I am still working on:
- Github action for releasing a new version of the CDK will need to be tested (I might concede this part, never done this before)
- Documentation, currently at 80%

**Comment by marcosmarxm** [comment]
@sherifnada can you help here?

**Comment by marcosmarxm** [comment]
@mrhamburg what do you think in release this in your repo like [Faros.ai is doing for the Typescript CDK](https://github.com/faros-ai/airbyte-connectors/tree/main/faros-airbyte-cdk)? We can add your contribution inside our docs for people who want to build connectors using C#.

**Comment by mrhamburg** [comment]
@marcosmarxm, will do, I will setup a separate repo and change this PR to documentation only.

**Comment by sherifnada** [comment]
@mrhamburg apologies for the late response, to add some context to marcos' comment: 

We discussed this a bit within the team. We would really love to maintain this, but we unfortunately don't yet have the skillset to maintain a production grade C# CDK (we are proficient in java/python/a little typescript). We're more than happy to provide a review and showcase this CDK in the docs etc.. and redirect to an external repository (and maybe in time, adopt the CDK and maintain it in-house). 

Please LMK when you've created the external repo and I'd be happy to take a look

**Review by marcosmarxm — APPROVED** [review]

**Comment by marcosmarxm** [comment]
awesome work @mrhamburg !

**Pull request merged**
