### PR TITLE
🎉 New Destination: Google Firestore

### PR DESCRIPTION
**Pull request by ad-m**
## What

That PR add connectors to write to [Google Firestore](https://firebase.google.com/docs/firestore). Connector have been implemented in Python.

That PR is part of [Airbyte hacktoberfest contest](https://github.com/airbytehq/hacktoberfest-2021)

## How
*Describe the solution*

I have implemented connectors in Python. It support application default credentials (including Google metadata service when Airbyte is running on Google-backed insfructure eg. virtual machines) and JSON credentials.

I have been inspired by existing kvdb destination to keep code coherent.

Considering the existing cooperation between Google and Airbyte, I am not sure how to proceed with the access data to the demo environment, and also to prove the operation.

```
$ python -m pytest integration_tests --full-trace
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.9.4, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /home/adas/Devel/airbyte/airbyte-integrations/connectors/destination-firestore/.venv/bin/python
cachedir: .pytest_cache
rootdir: /home/adas/Devel/airbyte, configfile: pytest.ini
collected 4 items                                                                                                                                                                                                 

integration_tests/integration_test.py::test_check_valid_config PASSED
integration_tests/integration_test.py::test_check_invalid_config PASSED
integration_tests/integration_test.py::test_write_append PASSED
integration_tests/integration_test.py::test_write_overwrite PASSED

================================================================================================ 4 passed in 5.80s ================================================================================================
```
## Recommended reading order

2. `y.python`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [x] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>

### CODE REVIEW

**Comment by ad-m** [comment]
@harshithmullapudi I believe I already shared credentials via Slack.

**Review by antixar — CHANGES_REQUESTED** [review]
Hi @ad-m,
Thank you for this PR.
Could you correct the following points?
- add Python annotation to your writer.py
- does this library support the native oauth2 auth (not system account)? I mean some refresh_token with client_id/client_secret. I ask because The Aitbyte project is planning to add support of Oauth2 user authorization for connectors which can use it.

**Comment by ad-m** [comment]
@marcosmarxm is there anything how I can push forward that PR?

**Comment by harshithmullapudi** [comment]
@antixar is it a +1 for you on this PR? can I process to publish this ?

**Comment by marcosmarxm** [comment]
@ad-m please share the acceptance tests screenshot showing those tests are passing too.

**Comment by ad-m** [comment]
@marcosmarxm is there any documentation regarding how to use acceptance tests for destination connector in Python? 

I can see that there are open issue to enable Destination Acceptance Tests cross-language support ( #4698 ) and improve documentation for DAT ( #6412 ).  However, these issues do not imply that such a standard exists for destinations connector already.

Tests pass despite of small tweaks since PR have been created:

image

**Comment by ad-m** [comment]
@marcosmarxm , according to @sherifnada :

> Currently the only available option is to write acceptance tests in java

As it stands, should I try to create a mixed connector that would run Java acceptance tests for the Python connector (I haven't analyzed whether it makes sense to accept acceptance tests due to the level of abstraction)? I do not have a full picture of the management and standards of the project yet, hence this question. I have the impression that mixing languages in one connector will be problematic in the long run.

**Review by antixar — APPROVED** [review]
Looks good! Sorry for delay of this review

**Comment by marcosmarxm** [comment]
Hello! Sorry to not finished your contribution before the date stipulated in the contest. All contributions made before 15-November are eligible to receive the award. We're trying to review your contribution as soon as possible.

**Comment by marcosmarxm** [comment]
@harshithmullapudi can you ship this one?

**Comment by ad-m** [comment]
> Hello! Sorry to not finished your contribution before the date stipulated in the contest. All contributions made before 15-November are eligible to receive the award. We're trying to review your contribution as soon as possible.

Is there anything how I can help to handle that PR?

**Comment by harshithmullapudi** [comment]
Yeah @marcosmarxm just trying to understand is there anything more we need to do other than publishing the connector ?

**Comment by harshithmullapudi** [comment]
@ad-m hey were you able to build docker image of this connector ?

**Pull request merged**
