### PR TITLE
[source-mysql-v2] Don't emit state message with null stream status

### PR DESCRIPTION
**Pull request by rodireich**
fixes https://github.com/airbytehq/airbyte-internal-issues/issues/10656

### CODE REVIEW

**Comment by rodireich** [comment]
@theyueli It looks like platform started validating stream states differently.
It fails to deserialize a global message containing stream states which only include a descriptor but not a stream state blob.
This used to be possible in the past.

**Comment by theyueli** [comment]
> @theyueli It looks like platform started validating stream states differently. It fails to deserialize a global message containing stream states which only include a descriptor but not a stream state blob. This used to be possible in the past.

The ticket I filed here should be a duplication of this issue? @rodireich 

https://github.com/orgs/airbytehq/projects/94/views/1?pane=issue&itemId=86618971&issue=airbytehq%7Cairbyte-internal-issues%7C10656

**Comment by theyueli** [comment]
> @theyueli It looks like platform started validating stream states differently. It fails to deserialize a global message containing stream states which only include a descriptor but not a stream state blob. This used to be possible in the past.

hi Ryan @tryangul could you confirm?

**Comment by rodireich** [comment]
>The ticket I filed here should be a duplication of this issue? @rodireich
>
>https://github.com/airbytehq/airbyte-internal-issues/issues/10656
This issue seems to still repro with a fixed version.
I have a vague idea why this is happening but I cannot see why the number of tables would matter.
Investigating

**Review by theyueli — APPROVED** [review]
is it possible to write a test?

**Comment by tryangul** [comment]
> > @theyueli It looks like platform started validating stream states differently. It fails to deserialize a global message containing stream states which only include a descriptor but not a stream state blob. This used to be possible in the past.
> 
> hi Ryan @tryangul could you confirm?

We haven't changed anything with stream status tracking since shipping it earlier this year.

**Pull request merged**
