### PR TITLE
extracted frontend and connector builder changes for low code to beta

### PR DESCRIPTION
**Pull request by brianjlai**
isolates the frontend and connector builder changes that were originally in `low_code_cdk_to_beta`

### CODE REVIEW

**Comment by flash1293** [comment]
@brianjlai Bumped the CDK_VERSION file and fixed a frontend issue

**Comment by flash1293** [comment]
@brianjlai looks like there are some formatting issues in the builder server.

**Comment by flash1293** [comment]
Important note: as there are so many breaking changes, the frontend will discard the currently saved form values from a previous version. We should probably advise our alpha testers to save it away somewhere so they can rebuild it.

**Comment by brianjlai** [comment]
That is a good point, we may want to give a heads up the start of next week on Monday to save WIP and then we can roll the change out on Wednesday after the freeze is over

**Comment by brianjlai** [comment]
closing this because of the platform monorepo split. Will be merged in https://github.com/airbytehq/airbyte-platform/pull/102

**Pull request closed without merging**
