### PR TITLE
🐛 Source Pinterest: update expected records

### PR DESCRIPTION
**Pull request by arsenlosenko**
## What
Fix failed build of Source Pinterest

## How
Updated expected records for stream `ad_accounts`, added new field `id`

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-pinterest test report (commit [`29165e7369`](https://github.com/airbytehq/airbyte/pull/27964/commits/29165e736912b096df13b35bc5a49d2f88cf9b0e)) - ✅

⏲️  Total pipeline duration: 05mn25s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-pinterest/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-pinterest docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_source-pinterest-fix-expected-records-05-07/1688547213/29165e736912b096df13b35bc5a49d2f88cf9b0e/source-pinterest/0.5.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-pinterest test
```

**Review by lazebnyi — CHANGES_REQUESTED** [review]
Why weren't the new fields added to the schema when they were added to the stream?

**Comment by arsenlosenko** [comment]
> Why weren't the new fields added to the schema when they were added to the stream?

@lazebnyi I'll add the new field to schema and reach out to you again

**Comment by octavia-squidington-iii** [comment]
##  source-pinterest test report (commit [`1a5a55bb42`](https://github.com/airbytehq/airbyte/pull/27964/commits/1a5a55bb428c0cd5553dc5d8927bc7dc1230acee)) - ✅

⏲️  Total pipeline duration: 05mn34s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-pinterest/metadata.yaml | ✅        |
| Connector version semver check                                          | ✅        |
| Connector version increment check                                       | ✅        |
| QA checks                                                               | ✅        |
| Code format checks                                                      | ✅        |
| Connector package install                                               | ✅        |
| Build source-pinterest docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                              | ✅        |
| Acceptance tests                                                        | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/arsenlosenko_source-pinterest-fix-expected-records-05-07/1688557970/1a5a55bb428c0cd5553dc5d8927bc7dc1230acee/source-pinterest/0.5.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-pinterest test
```

**Review by lazebnyi — APPROVED** [review]

**Pull request merged**
