### PR TITLE
🎉 New Source: NVD API [Python CDK]

### PR DESCRIPTION
**Pull request by StevenReitsma**
## What

Adds the [NVD APIs](https://nvd.nist.gov/developers) as a source in Airbyte 🎉

## How
Please note that a secret will need to be added to make the tests pass in CI, because otherwise the tests will encounter rate limits from the NVD API.

Add a secret in GSM that will be placed at `secrets/config.json` with the following contents:

```
{
  "apiKey": "...",
  "modStartDate": "2022-12-19T01:00:00"
}
```
The API key can be requested for the Airbyte CI/CD at https://nvd.nist.gov/developers/request-an-api-key

Also, the acceptance tests are a bit slow right now because of the requirement to do a full refresh. Is there a way to dynamically set the start_date based on the current time in the acceptance tests?

## Recommended reading order
1. Read `nvd.md` first
2. Then `source.py`
3. Then the unit tests

## 🚨 User Impact 🚨
No breaking changes.

## Pre-merge Checklist

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [x] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

```
Test session starts (platform: darwin, Python 3.10.6, pytest 6.2.5, pytest-sugar 0.9.5)
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/airbyte/airbyte-integrations/connectors/source-nvd/.hypothesis/examples')
rootdir: /airbyte, configfile: pytest.ini
plugins: sugar-0.9.5, requests-mock-1.9.3, mock-3.6.1, hypothesis-6.54.4, timeout-1.4.2, cov-3.0.0
collecting ...
 airbyte-integrations/connectors/source-nvd/unit_tests/test_source.py::test_check_connection ✓        7% ▊
 airbyte-integrations/connectors/source-nvd/unit_tests/test_source.py::test_streams ✓                14% █▌
 airbyte-integrations/connectors/source-nvd/unit_tests/test_streams.py::test_request_params ✓        21% ██▎
 airbyte-integrations/connectors/source-nvd/unit_tests/test_streams.py::test_next_page_token ✓       29% ██▉
 airbyte-integrations/connectors/source-nvd/unit_tests/test_streams.py::test_parse_response_cves ✓   36% ███▋
 airbyte-integrations/connectors/source-nvd/unit_tests/test_streams.py::test_parse_response_cpes ✓   43% ████▍
 airbyte-integrations/connectors/source-nvd/unit_tests/test_streams.py::test_should_retry[HTTPStatus.OK-False] ✓50% █████
 airbyte-integrations/connectors/source-nvd/unit_tests/test_streams.py::test_should_retry[HTTPStatus.BAD_REQUEST-False] ✓57% █████▊
 airbyte-integrations/connectors/source-nvd/unit_tests/test_streams.py::test_should_retry[HTTPStatus.TOO_MANY_REQUESTS-True] ✓64% ██████▌
 airbyte-integrations/connectors/source-nvd/unit_tests/test_streams.py::test_should_retry[HTTPStatus.INTERNAL_SERVER_ERROR-True] ✓71% ███████▎
 airbyte-integrations/connectors/source-nvd/unit_tests/test_streams.py::test_should_retry[HTTPStatus.FORBIDDEN-True] ✓79% ███████▉
 airbyte-integrations/connectors/source-nvd/unit_tests/test_streams.py::test_stream_slices ✓         86% ████████▋
 airbyte-integrations/connectors/source-nvd/unit_tests/test_streams.py::test_supports_incremental ✓  93% █████████▍
 airbyte-integrations/connectors/source-nvd/unit_tests/test_streams.py::test_source_defined_cursor ✓100% ██████████
================================================ warnings summary =================================================
airbyte-integrations/connectors/source-nvd/unit_tests/test_source.py: 3 warnings
airbyte-integrations/connectors/source-nvd/unit_tests/test_streams.py: 12 warnings
  /lib/python3.10/site-packages/airbyte_cdk/sources/streams/http/http.py:43: DeprecationWarning: Call to deprecated class NoAuth. (Set `authenticator=None` instead) -- Deprecated since version 0.1.20.
    self._authenticator: HttpAuthenticator = NoAuth()

airbyte-integrations/connectors/source-nvd/unit_tests/test_source.py: 3 warnings
airbyte-integrations/connectors/source-nvd/unit_tests/test_streams.py: 12 warnings
  /lib/python3.10/site-packages/deprecated/classic.py:173: DeprecationWarning: Call to deprecated class HttpAuthenticator. (Use requests.auth.AuthBase instead) -- Deprecated since version 0.1.20.
    return old_new1(cls, *args, **kwargs)

-- Docs: https://docs.pytest.org/en/stable/warnings.html

Results (2.35s):
      14 passed
```

</details>

<details><summary><strong>Integration</strong></summary>

No integration tests.

</details>

<details><summary><strong>Acceptance</strong></summary>

```
============================================= short test summary info =============================================
SKIPPED [1] ../../bases/source-acceptance-test/source_acceptance_test/tests/test_core.py:94: The previous and actual specifications are identical.
SKIPPED [1] ../../bases/source-acceptance-test/source_acceptance_test/tests/test_core.py:377: The previous and actual discovered catalogs are identical.

Results (71.19s):
      29 passed
       2 skipped
```

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

**Comment by haithem-souala** [comment]
Hey @StevenReitsma, i'am Airbyte maintainer, ill take a look at your PR very soon!
Thank you for your contribution!

**Comment by StevenReitsma** [comment]
Looks like I forgot flake8. I'll fix that tomorrow! Of course you can start the review regardless 😄 thanks!

**Comment by StevenReitsma** [comment]
Fixed! Could you rerun tests?

**Comment by StevenReitsma** [comment]
Please note that to make the tests pass, you need to add the secret first. Please see the opening post of this PR for more information.

**Comment by haithem-souala** [comment]
> Please note that to make the tests pass, you need to add the secret first. Please see the opening post of this PR for more information.

Indeed, i'am waiting the airbyte team to deploy NVD API secrets. (cc @sajarin)

**Comment by StevenReitsma** [comment]
Any news? @haithem-souala @sajarin

**Comment by StevenReitsma** [comment]
@haithem-souala looks like the credentials are created. Can you rerun the tests?

**Comment by StevenReitsma** [comment]
Unfortunately looks like the secret is not yet being written:

```
> Run source venv/bin/activate
[23/01/2023 12:14:13.659740] - WARNING - [site-packages/ci_credentials/secrets_manager.py:170] # not found any secrets of the connector 'source-nvd'
0 secret files were written: 
```

**Comment by StevenReitsma** [comment]
Interesting, looks like that's actually a bug at the source itself. There are records in the output that lie outside of the requested date range. I've contacted NVD about this. Let's see what they say.

**Comment by StevenReitsma** [comment]
Got a response from NVD. They say it's very probably a bug on their end and they are looking into it.

**Comment by StevenReitsma** [comment]
Looks like the bug might be fixed on their end. Can you rerun tests @haithem-souala ? Thanks!

**Comment by sh4sh** [comment]
Hey @StevenReitsma, tests are run in https://github.com/airbytehq/airbyte/pull/23032#issuecomment-1430427580 - could you look into the unit test failures?

**Comment by StevenReitsma** [comment]
@sh4sh my bad. I made some last-minute changes earlier and forgot to run the unit tests afterwards. I've fixed the tests now in my branch. Could you rerun the tests?

**Comment by StevenReitsma** [comment]
@sh4sh @haithem-souala any updates?

**Comment by haithem-souala** [comment]
@YowanR, @sh4sh could you please run the /test cmd.

**Comment by haithem-souala** [comment]
@marcosmarxm , can you help here!

**Comment by haithem-souala** [comment]
> /test connector=connectors/source-nvd

FYI, @sh4sh run tests in #23032, probably you need to include the last commits pushed by @StevenReitsma.

**Comment by marcosmarxm** [comment]
Hello, our team ended up losing track of reviewing your contribution and we're sorry about that. I'm cleaning up our backlog and closing it now. If you'd like to resubmit it, we'll be very happy and we'll do our best to prioritize the proper review. For new connectors, the project always aims to obtain integration accounts with the implemented service to ensure that the connector works effectively over time. Once again, I apologize, and feel free to send me a message on Slack if you have any further questions.

**Pull request closed without merging**
