### PR TITLE
🐛 Destination Oracle: Fix destination check for users without dba role

### LINKED ISSUE #4064: Allow oracle destination to be created without create user privilege
# Oracle destination throws a null pointer exception if the login schema user does not have create user privileges. 

###  Create user is a dba level privilege in many organizations and not necessary for the destination to sync data when the destination schema already exists.  If the default schema already exists then the destination should be created even if the login user does not have create user.

### PR DESCRIPTION
**Pull request by DoNotPanicUA**
## What
fix #4064 

## How
Use ALL_USERS table instead of DBA_USERS
## Pre-merge Checklist
<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

### CODE REVIEW

**Review by sherifnada — APPROVED** [review]
We also need to tell the user in the issue to use the destination connector settings configurable in the UI from here: 
Screen Shot 2021-08-10 at 2 44 26 PM

**Comment by DoNotPanicUA** [comment]
@marcosmarxm 
I've added a table with possible cases and required permissions to the destination documentation as we discussed under the issue.
Could you please review it?

**Review by marcosmarxm — APPROVED** [review]
LGTM @DoNotPanicUA thanks for this

**Review by yaroslav-hrytsaienko — APPROVED** [review]

**Pull request merged**
