### PR TITLE
Add missing java options

### PR DESCRIPTION
**Pull request by benmoriceau**
## What
Now that we have threads requesting memory even when the main thread is lock during GC with the async framework, it is likely that we run out of retries. This PR bump the number of retries from 2 to 100.

related to: https://github.com/airbytehq/airbyte/issues/30995

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`85baad3dab`](https://github.com/airbytehq/airbyte/pull/31153/commits/85baad3dab211f739cd49821ab847add893112c7)) - ❌

⏲️  Total pipeline duration: 03mn15s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅        |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ❌        |
| Validate metadata for destination-snowflake                           | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/bmoric_java-option-needed-by-async/1696635189/85baad3dab211f739cd49821ab847add893112c7/destination-snowflake/3.1.22/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:85baad3dab211f739cd49821ab847add893112c7)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`e29df069f3`](https://github.com/airbytehq/airbyte/pull/31153/commits/e29df069f352507f981ffb7add5534f9b5133652)) - ❌

⏲️  Total pipeline duration: 03mn20s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅        |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ❌        |
| Validate metadata for destination-snowflake                           | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/bmoric_java-option-needed-by-async/1696635514/e29df069f352507f981ffb7add5534f9b5133652/destination-snowflake/3.1.22/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e29df069f352507f981ffb7add5534f9b5133652)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-redshift test report (commit [`e29df069f3`](https://github.com/airbytehq/airbyte/pull/31153/commits/e29df069f352507f981ffb7add5534f9b5133652)) - ❌

⏲️  Total pipeline duration: 01mn42s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅        |
| Build destination-redshift docker image for platform(s) linux/x86_64 | ❌        |
| Validate metadata for destination-redshift                           | ✅        |
| Connector version semver check                                       | ✅        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/bmoric_java-option-needed-by-async/1696635514/e29df069f352507f981ffb7add5534f9b5133652/destination-redshift/0.6.7/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e29df069f352507f981ffb7add5534f9b5133652)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redshift test
```

**Review by tryangul — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  destination-redshift test report (commit [`e5c948c5ce`](https://github.com/airbytehq/airbyte/pull/31153/commits/e5c948c5cea3f24a65deeb86f9b84355a2b02b37)) - ✅

⏲️  Total pipeline duration: 21mn07s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅        |
| Build destination-redshift docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                            | ✅        |
| Build airbyte/normalization-redshift:dev                             | ✅        |
| Java Connector Integration Tests                                     | ✅        |
| Validate metadata for destination-redshift                           | ✅        |
| Connector version semver check                                       | ✅        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/bmoric_java-option-needed-by-async/1696635963/e5c948c5cea3f24a65deeb86f9b84355a2b02b37/destination-redshift/0.6.7/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e5c948c5cea3f24a65deeb86f9b84355a2b02b37)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redshift test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`e5c948c5ce`](https://github.com/airbytehq/airbyte/pull/31153/commits/e5c948c5cea3f24a65deeb86f9b84355a2b02b37)) - ❌

⏲️  Total pipeline duration: 09mn28s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅        |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                             | ✅        |
| Java Connector Integration Tests                                      | ✅        |
| Validate metadata for destination-snowflake                           | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/bmoric_java-option-needed-by-async/1696635963/e5c948c5cea3f24a65deeb86f9b84355a2b02b37/destination-snowflake/3.1.22/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e5c948c5cea3f24a65deeb86f9b84355a2b02b37)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`d9519f18ab`](https://github.com/airbytehq/airbyte/pull/31153/commits/d9519f18ab3e96001de5b6a023be2f1eee78fbb1)) - ✅

⏲️  Total pipeline duration: 03mn27s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build connector tar                                                   | ✅        |
| Build destination-snowflake docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                             | ✅        |
| Java Connector Integration Tests                                      | ✅        |
| Validate metadata for destination-snowflake                           | ✅        |
| Connector version semver check                                        | ✅        |
| Connector version increment check                                     | ✅        |
| QA checks                                                             | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/bmoric_java-option-needed-by-async/1696639971/d9519f18ab3e96001de5b6a023be2f1eee78fbb1/destination-snowflake/3.1.22/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d9519f18ab3e96001de5b6a023be2f1eee78fbb1)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-redshift test report (commit [`d9519f18ab`](https://github.com/airbytehq/airbyte/pull/31153/commits/d9519f18ab3e96001de5b6a023be2f1eee78fbb1)) - ✅

⏲️  Total pipeline duration: 02mn48s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Build connector tar                                                  | ✅        |
| Build destination-redshift docker image for platform(s) linux/x86_64 | ✅        |
| Java Connector Unit Tests                                            | ✅        |
| Build airbyte/normalization-redshift:dev                             | ✅        |
| Java Connector Integration Tests                                     | ✅        |
| Validate metadata for destination-redshift                           | ✅        |
| Connector version semver check                                       | ✅        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/bmoric_java-option-needed-by-async/1696639971/d9519f18ab3e96001de5b6a023be2f1eee78fbb1/destination-redshift/0.6.7/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:d9519f18ab3e96001de5b6a023be2f1eee78fbb1)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-redshift test
```

**Pull request merged**
