### PR TITLE
source-cin7 contribution from aazam-gh

### LINKED ISSUE #47995: [connector-request] Cin7
### Topic

_No response_

### Relevant information

Relevant information
This is a suggestion to create a connector for Cin7 using the UI Connector Builder. The website for the connector is https://cin7.com/.

### PR DESCRIPTION
**Pull request by aazam-gh**
## What

This PR adds a new connector for source Cin7 (source-cin7).

Contributor-provided connector description:

This is the Cin7 source that ingests data from the Cin7 API.

Cin7 (Connector Inventory Performance), If you’re a business that wants to grow, you need an inventory solution you can count on - both now and in the future. With Cin7 you get a real-time picture of your products across systems, channels, marketplaces and regions, plus NEW ForesightAI advanced inventory forecasting that empowers you to see around corners and stay three steps ahead of demand! https://www.cin7.com/

To use this source, you must first create an account. Once logged in, head to Integrations -&gt; API -&gt; Cin7 Core API.
Create an application and note down the Account Id and the API key, you will need to enter these in the input fields. You can find more information about the API here https://dearinventory.docs.apiary.io/#reference

## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `accountid` | `string` | AccountID. The ID associated with your account. |  |
| `api_key` | `string` | API Key. The API key associated with your account. |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| bank_accounts | AccountID | DefaultPaginator | ✅ |  ❌  |
| attribute_sets | ID | DefaultPaginator | ✅ |  ❌  |
| accounts | Code | DefaultPaginator | ✅ |  ❌  |
| brands | ID | DefaultPaginator | ✅ |  ❌  |
| carriers | CarrierID | DefaultPaginator | ✅ |  ❌  |
| customers | ID | DefaultPaginator | ✅ |  ❌  |
| deals | ID | No pagination | ✅ |  ❌  |
| locations |  | DefaultPaginator | ✅ |  ❌  |
| products | ID | DefaultPaginator | ✅ |  ❌  |
| purchases | ID | DefaultPaginator | ✅ |  ❌  |
| suppliers | ID | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Comment by aazam-gh** [comment]
Fixes #47995

**Comment by marcosmarxm** [comment]
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

Make sure you have pagination properly working, the API doesn't have pagination please left a comment making my review easier.
Make sure have a square svg icon
Make sure credentials are valid.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Missing endpoints like saleList, taxes, product category and family...
Upload svg square icon.

Pagination and limits are correct.

Please make changes asap, moving next check to monday

**Comment by aazam-gh** [comment]
Requested changes have been made.

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
