### PR TITLE
Running CI checks for Source Google Sheets  #30487

### PR DESCRIPTION
**Pull request by darynaishchenko**
Details: This Pull Request initiates the process of executing CI checks on the source named Google Sheets. 
The PR number associated with the contributor is https://github.com/airbytehq/airbyte/pull/30487.

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-google-sheets test report (commit [`05d6b8190a`](https://github.com/airbytehq/airbyte/pull/31125/commits/05d6b8190a60caafbb52316f6b59dc662bb756f6)) - ✅

⏲️  Total pipeline duration: 02mn29s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Connector package install                                            | ✅        |
| Build source-google-sheets docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |
| Code format checks                                                   | ✅        |
| Validate metadata for source-google-sheets                           | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/mspaloss_source-google-sheets_bugfix-update-range-on-retry-to-handle-batch-size-increase/1696601900/05d6b8190a60caafbb52316f6b59dc662bb756f6/source-google-sheets/0.3.10/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:05d6b8190a60caafbb52316f6b59dc662bb756f6)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-sheets test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-greenhouse test report (commit [`05d6b8190a`](https://github.com/airbytehq/airbyte/pull/31125/commits/05d6b8190a60caafbb52316f6b59dc662bb756f6)) - ❌

⏲️  Total pipeline duration: 03mn32s 

| Step                                                              | Result   |
|:------------------------------------------------------------------|:---------|
| Connector package install                                         | ✅        |
| Build source-greenhouse docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                        | ✅        |
| Acceptance tests                                                  | ❌        |
| Code format checks                                                | ✅        |
| Validate metadata for source-greenhouse                           | ✅        |
| Connector version semver check                                    | ✅        |
| Connector version increment check                                 | ❌        |
| QA checks                                                         | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/mspaloss_source-google-sheets_bugfix-update-range-on-retry-to-handle-batch-size-increase/1696601900/05d6b8190a60caafbb52316f6b59dc662bb756f6/source-greenhouse/0.4.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:05d6b8190a60caafbb52316f6b59dc662bb756f6)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-greenhouse test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-google-sheets test report (commit [`8262d3ab30`](https://github.com/airbytehq/airbyte/pull/31125/commits/8262d3ab3015105af8a98a63487578d748bf3f0f)) - ✅

⏲️  Total pipeline duration: 01mn42s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Connector package install                                            | ✅        |
| Build source-google-sheets docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |
| Code format checks                                                   | ✅        |
| Validate metadata for source-google-sheets                           | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/mspaloss_source-google-sheets_bugfix-update-range-on-retry-to-handle-batch-size-increase/1696846590/8262d3ab3015105af8a98a63487578d748bf3f0f/source-google-sheets/0.3.10/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:8262d3ab3015105af8a98a63487578d748bf3f0f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-sheets test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-google-sheets test report (commit [`668abcd330`](https://github.com/airbytehq/airbyte/pull/31125/commits/668abcd330d3da00824307140ec84f14f64034fb)) - ✅

⏲️  Total pipeline duration: 05mn01s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Connector package install                                            | ✅        |
| Build source-google-sheets docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |
| Code format checks                                                   | ✅        |
| Validate metadata for source-google-sheets                           | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/mspaloss_source-google-sheets_bugfix-update-range-on-retry-to-handle-batch-size-increase/1696850729/668abcd330d3da00824307140ec84f14f64034fb/source-google-sheets/0.3.10/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:668abcd330d3da00824307140ec84f14f64034fb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-sheets test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-google-sheets test report (commit [`b6b48f9eec`](https://github.com/airbytehq/airbyte/pull/31125/commits/b6b48f9eecc5dd499c98aa697cede2b98149a382)) - ✅

⏲️  Total pipeline duration: 03mn56s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Connector package install                                            | ✅        |
| Build source-google-sheets docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |
| Code format checks                                                   | ✅        |
| Validate metadata for source-google-sheets                           | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/mspaloss_source-google-sheets_bugfix-update-range-on-retry-to-handle-batch-size-increase/1696861936/b6b48f9eecc5dd499c98aa697cede2b98149a382/source-google-sheets/0.3.10/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b6b48f9eecc5dd499c98aa697cede2b98149a382)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-sheets test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-google-sheets test report (commit [`f8dd048b73`](https://github.com/airbytehq/airbyte/pull/31125/commits/f8dd048b73ac82df686dea06dce1d97ac927f9ab)) - ✅

⏲️  Total pipeline duration: 02mn20s 

| Step                                                                 | Result   |
|:---------------------------------------------------------------------|:---------|
| Connector package install                                            | ✅        |
| Build source-google-sheets docker image for platform(s) linux/x86_64 | ✅        |
| Unit tests                                                           | ✅        |
| Acceptance tests                                                     | ✅        |
| Code format checks                                                   | ✅        |
| Validate metadata for source-google-sheets                           | ✅        |
| Connector version semver check                                       | ✅        |
| Connector version increment check                                    | ✅        |
| QA checks                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/mspaloss_source-google-sheets_bugfix-update-range-on-retry-to-handle-batch-size-increase/1696926738/f8dd048b73ac82df686dea06dce1d97ac927f9ab/source-google-sheets/0.3.10/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f8dd048b73ac82df686dea06dce1d97ac927f9ab)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-google-sheets test
```

**Comment by darynaishchenko** [comment]
PR #30487 merged

**Pull request closed without merging**
