### PR TITLE
It's 2023!

### PR DESCRIPTION
**Pull request by evantahler**
After https://github.com/airbytehq/airbyte/pull/22576, it seems we need to update *every* file...

### CODE REVIEW

**Comment by timroes** [comment]
Thanks for opening this. I think I just ran into that on trying to build an OSS release :D

**Comment by alafanechere** [comment]
How we did it for 2022: https://github.com/airbytehq/airbyte/pull/13191

**Review by alafanechere — APPROVED** [review]
If I look at every file we will be in 2024...

**Comment by evantahler** [comment]
Please feel free to meter this whenever or make changes. I'll be in brainstorms all day...

**Comment by evantahler** [comment]
closing in favor of https://github.com/airbytehq/airbyte/pull/22594 - @colesnodgrass has the ball now!

**Pull request closed without merging**
