### PR TITLE
🚨 Source woocommerce: Add srcset field to products stream

### PR DESCRIPTION
**Pull request by girarda**
## What
* Woocommerce's products stream has an additional nested field, which is causing the acceptance tests to fail.
* This PR updates the adds the field to the schema and updates the expected records
* This is adding a field to the stream, which is a breaking change

This is a breaking change, but [there are no cloud users](https://airbyte.metabaseapp.com/dashboard/328-debug-source?is_cloud=true&source_connector_name=2a2552ca-9f78-4c1c-9eb7-4d0dc66d72df) so there is no need to coordinate a migration.

## How
* Add the field to the schema
* Update the expected records

## Recommended reading order
1. `airbyte-integrations/connectors/source-woocommerce/source_woocommerce/schemas/products.json`
2. `airbyte-integrations/connectors/source-woocommerce/integration_tests/expected_records.jsonl`
3. `docs/integrations/sources/woocommerce.md`
4. `airbyte-integrations/connectors/source-woocommerce/metadata.yaml`
5. `airbyte-integrations/connectors/source-woocommerce/Dockerfile`

## 🚨 User Impact 🚨
* Add a new field to the products stream
* Users who want to leverage this change will need to refresh their connection source

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-woocommerce test report (commit [`49506af6b1`](https://github.com/airbytehq/airbyte/pull/27596/commits/49506af6b1e3e309235b8fdcab627cb2da10ccbf)) - ✅

⏲️  Total pipeline duration: 468 seconds

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-woocommerce/metadata.yaml | ✅        |
| Connector version semver check.                                           | ✅        |
| QA checks                                                                 | ✅        |
| Code format checks                                                        | ✅        |
| Connector package install                                                 | ✅        |
| Build source-woocommerce docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                          | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/alex_fix_woocommerce_cat/1687397375/49506af6b1e3e309235b8fdcab627cb2da10ccbf/source-woocommerce/0.2.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-woocommerce test
```

**Comment by octavia-squidington-iii** [comment]
##  source-woocommerce test report (commit [`d02e73c086`](https://github.com/airbytehq/airbyte/pull/27596/commits/d02e73c086e8c24e04050cf6a2845127911f6d52)) - ❌

⏲️  Total pipeline duration: 452 seconds

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-woocommerce/metadata.yaml | ✅        |
| Connector version semver check.                                           | ✅        |
| Connector version increment check.                                        | ✅        |
| QA checks                                                                 | ❌        |
| Code format checks                                                        | ✅        |
| Connector package install                                                 | ✅        |
| Build source-woocommerce docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                          | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/alex_fix_woocommerce_cat/1687400217/d02e73c086e8c24e04050cf6a2845127911f6d52/source-woocommerce/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-woocommerce test
```

**Comment by octavia-squidington-iii** [comment]
##  source-woocommerce test report (commit [`a46bb425ed`](https://github.com/airbytehq/airbyte/pull/27596/commits/a46bb425edfb32c18ad07f8749984950cfb139da)) - ✅

⏲️  Total pipeline duration: 423 seconds

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-woocommerce/metadata.yaml | ✅        |
| Connector version semver check.                                           | ✅        |
| Connector version increment check.                                        | ✅        |
| QA checks                                                                 | ✅        |
| Code format checks                                                        | ✅        |
| Connector package install                                                 | ✅        |
| Build source-woocommerce docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                          | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/alex_fix_woocommerce_cat/1687401210/a46bb425edfb32c18ad07f8749984950cfb139da/source-woocommerce/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-woocommerce test
```

**Comment by octavia-squidington-iii** [comment]
##  source-woocommerce test report (commit [`ffba0fbd7d`](https://github.com/airbytehq/airbyte/pull/27596/commits/ffba0fbd7d2be03e20e56e804d6e142fc031ba18)) - ✅

⏲️  Total pipeline duration: 467 seconds

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-woocommerce/metadata.yaml | ✅        |
| Connector version semver check.                                           | ✅        |
| Connector version increment check.                                        | ✅        |
| QA checks                                                                 | ✅        |
| Code format checks                                                        | ✅        |
| Connector package install                                                 | ✅        |
| Build source-woocommerce docker image for platform linux/x86_64           | ✅        |
| Acceptance tests                                                          | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/alex_fix_woocommerce_cat/1687402209/ffba0fbd7d2be03e20e56e804d6e142fc031ba18/source-woocommerce/1.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-woocommerce test
```

**Comment by maxi297** [comment]
> This is a breaking change, but [there are no cloud users](https://airbyte.metabaseapp.com/dashboard/328-debug-source?is_cloud=true&source_connector_name=2a2552ca-9f78-4c1c-9eb7-4d0dc66d72df) so there is no need to coordinate a migration.

The link use the source definition ID of woocommerce as the value for `source_connector_name`. It should filter on `source_definition_id` instead. Doing [this](https://airbyte.metabaseapp.com/dashboard/328-debug-source?source_definition_id=2a2552ca-9f78-4c1c-9eb7-4d0dc66d72df&is_cloud=true), we can see that we have users in production in cloud right now. Therefore, we should probably fill the [Connector Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit)

**Review by maxi297 — APPROVED** [review]
Just a concern regarding the breaking change and the affected users

**Pull request closed without merging**
