### PR TITLE
:bug: Source Bing Ads: fix null values in Keyword report

### PR DESCRIPTION
**Pull request by LuliRib**
Fix for receiving null values in keyword field
added new keyword field to the source.py
This should fix the problem that we receive null values to the recently added keyword field to the keyword_performance_report

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@LuliRib please bump connector version (dockerfile, documentation and seed file)

**Comment by LuliRib** [comment]
Can you guide me on how to do that?

**Comment by marcosmarxm** [comment]
> Can you guide me on how to do that?

https://docs.airbyte.com/connector-development/#publishing-a-connector

**Comment by LuliRib** [comment]
I dont have access to the docker..

**Comment by LuliRib** [comment]
LABEL io.airbyte.version=0.1.17

**Comment by LuliRib** [comment]
@marcosmarxm hi, is it ok?

**Comment by LuliRib** [comment]
@marcosmarxm hi

**Comment by LuliRib** [comment]
@marcosmarxm hi, I get for the past few hours failure messages, which I have no idea what I should do [LuliRib/airbyte] Run failed: .github/workflows/publish-connector-command.yml - fix-keyword-bing-ads (2652970)

**Comment by marcosmarxm** [comment]
@grubberr can you review this? @LuliRib you need to wait until the review is approved. Be Patience.

**Review by marcosmarxm — APPROVED** [review]

**Comment by marcosmarxm** [comment]
@archangelic Can you test the latest version of Bing Ads and check if the null value is still happening?

**Comment by sajarin** [comment]
@LuliRib thank you so much for the contribution. Sorry for the long delay in reviewing this change. It seems like the keyword column has been added to the keyword report and should no longer be null. We appreciate the contribution and we're working on reviewing contributions faster. 

We hope we see more contributions from you in the future! :)

**Pull request closed without merging**
