### PR TITLE
fix order not to randomly fail backward compatibility check

### LINKED ISSUE #19244: 🐛 [SAT] json_schema_helper.find_nodes() doesn't correctly parse lists of dicts
I think this is an issue with `find_nodes()` but it appears when trying to `get_node()`. When inspecting the list of `variant_paths` you can see that the path contains an entire dict instead of just the traversal keys as expected. Here is the error I run into: 
```
chema = {'description': 'Tests that keys can be found inside lists of dicts', 'properties': {'credentials': {'oneOf': [{'prope...'properties': {'common': {...}}, 'type': 'object'}], 'type': 'object'}}, 'title': 'Key_inside_oneOf', 'type': 'object'}, key = 'option1'

    @pytest.mark.parametrize(
        "schema, key",
        [({
            "title": "Key_inside_oneOf",
            "description": "Tests that keys can be found inside lists of dicts",
            "type": "object",
            "properties": {
              "credentials": {
                "type": "object",
                "oneOf": [
                  {
                    "type": "object",
                    "properties": {
                      "common": {"type": "string", "const": "option1", "default": "option1"},
                      "option1": {"type": "string"},
                    },
                  },
                  {
                    "type": "object",
                    "properties": {
                      "common": {"type": "string", "const": "option2", "default": "option2"},
                    },
                  },
                ],
              }
            },
          },
          "option1"
        )],
    )
    def test_get_node(schema, key):
        schema_helper = JsonSchemaHelper(schema)
        variant_paths = schema_helper.find_nodes(keys=[key])
    
        for path in variant_paths:
>           assert schema_helper.get_node(path)

unit_tests/test_json_schema_helper.py:247: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <source_acceptance_test.utils.json_schema_helper.JsonSchemaHelper object at 0x10582afe0>, path = ['properties', 'credentials', 'oneOf', {'properties': {'common': {'const': 'option1', 'default': 'option1', 'type': 'string'}, 'option1': {'type': 'string'}}, 'type': 'object'}, 'properties', 'option1']

    def get_node(self, path: List[str]) -> Any:
        """Return part of schema by specified path
    
        :param path: list of fields in the order of navigation
        """
    
        node = self._schema
        for segment in path:
            if "$ref" in node:
                node = self.get_ref(node["$ref"])
>           node = node[segment]
E           TypeError: list indices must be integers or slices, not dict

source_acceptance_test/utils/json_schema_helper.py:121: TypeError
```

Add the following test to `test_json_schema_helper.py` to reproduce the issue: 
```
@pytest.mark.parametrize(
    "schema, key",
    [({
        "title": "Key_inside_oneOf",
        "description": "Tests that keys can be found inside lists of dicts",
        "type": "object",
        "properties": {
          "credentials": {
            "type": "object",
            "oneOf": [
              {
                "type": "object",
                "properties": {
                  "common": {"type": "string", "const": "option1", "default": "option1"},
                  "option1": {"type": "string"},
                },
              },
              {
                "type": "object",
                "properties": {
                  "common": {"type": "string", "const": "option2", "default": "option2"},
                },
              },
            ],
          }
        },
      },
      "option1"
    )],
)
def test_get_node(schema, key):
    schema_helper = JsonSchemaHelper(schema)
    variant_paths = schema_helper.find_nodes(keys=[key])

    for path in variant_paths:
        assert schema_helper.get_node(path)
```

### LINKED ISSUE #19353: Java sources fail after adding a new SAT SPEC test by #19243
Java sources fail after adding a new SAT SPEC test by #19243

[Example](https://github.com/airbytehq/airbyte/pull/13755#issuecomment-1311515235).

### Execution plan:
1) run integration tests for the sources:
- bigquery
- clickhouse
- cockroachdb
- db2 
- mssql 
- mysql
- oracle
- postgres
- redshift
- snowflake
- tidb
- elasticsearch
- kafka
- mongodb-v2
- sftp
2) Fix files for failed source:

- <source_folder>/src/main/resources/spec.json
- <source_folder>/src/test-integration/resources/expected_spec.json

### PR DESCRIPTION
**Pull request by DoNotPanicUA**
## What
The original purpose was to check that all source works after fix #19244.
All sources pass the validation but found an issue in the Postgres spec. Which leads to random SAT fails.
So, the PR only fixes the postgres issue.

### CODE REVIEW

**Review by evantahler — APPROVED** [review]
Things still appear to be in order!

**Review by rodireich — APPROVED** [review]

**Pull request merged**
