### PR TITLE
:bug: Destination Snowflake and Redshift : missing records when using S3 staging

### LINKED ISSUE #10646: 🐛 Redshift Destination: copies only 1 csv stream part from S3
## Environment
- **Airbyte version**:  example is 0.35.36-alpha
- **OS Version / Instance**: Amazon Linux 2 AMI, EC2 t3a.large
- **Deployment**: Docker
- **Source Connector and version**: Redshift 0.3.8
- **Destination Connector and version**: Redshift 0.3.25
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
- Only the last stream part from S3 gets actually copied into Redshift destination
- "Succeeded" summary in status web page falsely indicates that all records got emitted and committed

## Expected Behavior
- All parts get copied into Redshift destination
- "Succeeded" summary in status web page correctly indicates that all records got emitted and committed

## Logs
Logging and S3 bucket shows that the multiple CSV staging files contain full data. Log output doesn't mention copying individual files but only that RedshiftStreamCopier(copyStagingFileToTemporaryTable) Copy to tmp table complete.

## Steps to Reproduce
1. Use a data source >150MB (larger than S3 Stream Part Size)
2. Configure Redshift destination with S3 staging
3. Trigger connection
4. All csv parts are loaded into S3 correctly
5. observe how quickly RedshiftStreamCopier(copyStagingFileToTemporaryTable) completes
6. verify that only the last part has actually been copied to Redshift

## Are you willing to submit a PR?
No, as I don't have context on the surrounding recent changes.

Additional observations: Seems to be related to changes in #9920 affecting entries in "stagingWritersByFile" https://github.com/airbytehq/airbyte/blob/2157b47b60edcbb728d2e0921d42972f4969f290/airbyte-integrations/connectors/destination-jdbc/src/main/java/io/airbyte/integrations/destination/jdbc/copy/s3/S3StreamCopier.java#L130-L141
"stagingWritersByFile" gets used in RedshiftStreamCopier to generate the manifest of which csv files to copy to Redshift https://github.com/airbytehq/airbyte/blob/9fe804aac3e2998bfa38b4322bbf7213ec1f8508/airbyte-integrations/connectors/destination-redshift/src/main/java/io/airbyte/integrations/destination/redshift/RedshiftStreamCopier.java#L124

Another user experienced similar issues with Snowflake using S3 intermediary: https://airbytehq.slack.com/archives/C01MFR03D5W/p1645735115553539?thread_ts=1645734289.113269&cid=C01MFR03D5W

Temporary work-around: Disable S3 bucket + copy for Redshift Destination, using inefficient batch insert instead.

### LINKED ISSUE #11052: Missing Records when using S3 staging to Snowflake Destination
## Environment
- **Airbyte version**:  0.35.46-alpha
- **OS Version / Instance**: AWS EC2 Amazon Linux 2 AMI (HVM) - Kernel 4.14
- **Deployment**: Docker
- **Source Connector and version**:  MSSQL 0.3.17
- **Destination Connector and version**: Snowflake 0.4.17
- **Severity**: Critical
- **Step where error happened**:  Sync job 

## Current Behavior
*Tell us what happens.* I am trying to loading the data to Snowflake and had few issues. Airbyte read and committed 256,000 data. I am using S3 staging so was able to see the files which are created so it creates 4 diff files 3 with 65K+ records and the latest file with 58K records it just load the latest file to snowflake which is 58K records the job run is successful and no error .

## Expected Behavior
*Tell us what should happen.* It should load all the 256,000 records to Snowflake.

## Logs
[logs-47.txt](https://github.com/airbytehq/airbyte/files/8227564/logs-47.txt)

<details>
<summary>LOG</summary> 

```


```

</details>

## Steps to Reproduce
1. Create a S3 stage 
2. Run Airbyte pipeline with more than 250K records and it will create 4 diff files in S3.
3. Only the file with latest records on S3 will load into snowflake.

### LINKED ISSUE #11158: Missing records at Redshift destination on replication from Postgres
## Environment
- **Airbyte version**:  0.35.54-alpha
- **OS Version / Instance**: AWS EC2 (t3.large instance with amzn2-ami-hvm-2.0.20220218.3-x86_64-ebs AMI)
- **Deployment**: Docker on EC2
- **Source Connector and version**: Postgres 0.4.9 
- **Destination Connector and version**: Redshift 0.3.27 
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
Replicating table `shortened_urls` from Heroku Postgres to Redshift. There are 88,701 records in the source table. After running the sync job, there are only 41,008 records in the destination table. This happens with other tables in our full replication as well. I've done a full rebuild of the EC2 and Airbyte docker-compose, I've changed the sync mode between "Full refresh | Overwrite" and "Incremental | Deduped + History", I've tried two different custom namespaces, and I've tried increasing the stream part size on the Redshift destination from 10 to 20. In all scenarios, it seems like the same number of records make it into the destination. This seems similar to [#2599](https://github.com/airbytehq/airbyte/issues/2599).

## Expected Behavior
I run the sync job and there are 88,701 records in the destination.

## Logs

[logs-28.txt](https://gist.github.com/drewfustin/9146fc29aaeb66515fd4009450e89bdf)

## Steps to Reproduce
1. Create Postgres source and Redshift destination
2. Create connection:
  - **Replication frequency:** Manual
  - **Destination Namespace:** Custom format
  - **Namespace Custom Format:** airbyte
3. Select Sync with "Full refresh | Overwrite" Sync mode for the table `shortened_urls`
4. Run sync

## Are you willing to submit a PR?

No

### PR DESCRIPTION
**Pull request by VitaliiMaltsev**
## What
After running the sync job, there are only records from the last csv file in the destination table. This happens with Destination Snowflake S3 staging and Destination Redshift S3 staging as well.

## How
Fixed bug with files list generation

## Recommended reading order
1. `S3StreamCopier.java`
2. `RedshiftStreamCopier.java`
3. `SnowflakeS3StreamCopier.java`

## 🚨 User Impact 🚨
There should not be any user impact

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Review by ChristopheDuong — APPROVED** [review]

**Comment by ChristopheDuong** [comment]
Is there a way to simulate this in test?

**Comment by VitaliiMaltsev** [comment]
> Is there a way to simulate this in test?
@CLAassistant add
**Assertions.assertTrue(stagingFiles.size()>1);** in SnowflakeS3StreamCopierTest to check if we use not only the last csv file for staging

**Comment by drewfustin** [comment]
Thank you!

**Pull request merged**
