### PR TITLE
source-google-classroom contribution from bishalbera

### LINKED ISSUE #47393: [Connector-Request] Google Classroom
### Topic

This is a suggestion to create a connector for Google Classroom using the UI Connector Builder. The api docs for this is https://developers.google.com/classroom/reference/rest

### Relevant information

_No response_

### PR DESCRIPTION
**Pull request by bishalbera**
## What
Closes #47393 

This PR adds a new connector for source Google Classroom (source-google-classroom).

Contributor-provided connector description:

Google Classroom connector enables seamless data integration between Google Classroom and various destinations. This connector facilitates the synchronization of course information, rosters, assignments empowering educators to automate reporting and streamline classroom data management efficiently.
## Details

<details><summary>Expand for list of spec properties and streams</summary>

### Configuration

| Input | Type | Description | Default Value |
|-------|------|-------------|---------------|
| `client_id` | `string` | OAuth Client ID.  |  |
| `client_secret` | `string` | OAuth Client Secret.  |  |
| `client_refresh_token` | `string` | Refresh token.  |  |

### Streams
| Stream Name | Primary Key | Pagination | Supports Full Sync | Supports Incremental |
|-------------|-------------|------------|---------------------|----------------------|
| courses | id | DefaultPaginator | ✅ |  ❌  |
| teachers | userId | DefaultPaginator | ✅ |  ❌  |
| students | userId | DefaultPaginator | ✅ |  ❌  |
| announcements | id | DefaultPaginator | ✅ |  ❌  |
| coursework | id | DefaultPaginator | ✅ |  ❌  |
| studentsubmissions | id | DefaultPaginator | ✅ |  ❌  |

</details>

## Reviewer checklist
- [ ] Run `/format-fix` to resolve any formatting errors
- [ ] Help the contributor upload an icon that follows our icon design guidelines
- [ ] Click into the CI workflows that wait for a maintainer to run them, which should trigger CI runs

### CODE REVIEW

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
I couldn't test the connector in your workspace. Please make sure you have valid credentials.

**Comment by marcosmarxm** [comment]
Moving next review to Nov 12th, please ping me when this is done.

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Where I can find information about the pagination you're using in Google Classroom connector?

**Comment by bishalbera** [comment]
> Where I can find information about the pagination you're using in Google Classroom connector?

https://developers.google.com/classroom/reference/rest/v1/courses/list check this @marcosmarxm

**Comment by marcosmarxm** [comment]
All contributions must be merged by Nov-14. I'm going to work to provide a first review by Friday to give users the weekend to fix any comment. Please be aware of this.

Make sure you have pagination properly working, the API doesn't have pagination please left a comment making my review easier.
Make sure have a square svg icon
Make sure credentials are valid.

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
