### PR TITLE
refactor source harness and GitHub action to add source-mysql

### PR DESCRIPTION
**Pull request by rodireich**

### CODE REVIEW

**Comment by rodireich** [comment]
/connector-performance connector=connectors/source-mysql ref=rodi/mysql-harness

**Comment by rodireich** [comment]
/connector-performance connector=connectors/source-mysql ref=rodi/mysql-harness

**Comment by rodireich** [comment]
/connector-performance connector=connectors/source-mysql ref=rodi/mysql-harness

**Comment by rodireich** [comment]
/connector-performance connector=connectors/source-mysql ref=rodi/mysql-harness

**Comment by rodireich** [comment]
/connector-performance connector=connectors/source-mysql ref=rodi/mysql-harness

**Comment by rodireich** [comment]
/connector-performance connector=connectors/source-mysql ref=rodi/mysql-harness

**Comment by rodireich** [comment]
/connector-performance connector=connectors/source-mysql ref=rodi/mysql-harness

**Comment by rodireich** [comment]
/connector-performance connector=connectors/source-mysql ref=rodi/mysql-harness

**Comment by rodireich** [comment]
/connector-performance connector=connectors/source-postgres ref=rodi/mysql-harness

**Comment by rodireich** [comment]
/connector-performance connector=connectors/source-snowflake ref=rodi/mysql-harness

**Comment by rodireich** [comment]
/connector-performance connector=connectors/source-postgres ref=rodi/mysql-harness dataset=10m

**Comment by rodireich** [comment]
/connector-performance connector=connectors/source-postgres ref=rodi/mysql-harness dataset=10m

**Comment by rodireich** [comment]
/connector-performance connector=connectors/source-mysql ref=rodi/mysql-harness

**Comment by rodireich** [comment]
/connector-performance connector=connectors/source-mysql ref=rodi/mysql-harness dataset=10m

**Comment by rodireich** [comment]
/connector-performance connector=connectors/source-mysql ref=rodi/mysql-harness dataset=bottleneck_stream1

**Comment by rodireich** [comment]
/connector-performance connector=connectors/source-postgres dataset=10m

**Review by akashkulk — APPROVED** [review]

**Comment by prateekmukhedkar** [comment]
> /connector-performance connector=connectors/source-mysql ref=rodi/mysql-harness dataset=bottleneck_stream1

did this command pick up the changes to harness from this PR also? As in, does this command do an acceptance test on harness?

**Review by prateekmukhedkar — APPROVED** [review]

**Pull request merged**
