### PR TITLE
Bulk load cdk: split the destination process stuff into multiple files in their own package

### PR DESCRIPTION
**Pull request by edgao**
no code change, there's no point reviewing this in-depth. Literally just intellij refactor -> move to new file, plus manually fixing a few imports + airbyte-ci format.

### CODE REVIEW

**Comment by edgao** [comment]
* **#46363** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46363?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#46362** <a href="https://app.graphite.dev/github/pr/airbytehq/airbyte/46362?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @edgao and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by johnny-schmidt** [comment]
Is there any reason not to put this into operation?

**Comment by edgao** [comment]
sorry, like name the package `operation` instead of `destination_process`? I feel like operation is more for under-the-hood stuff, where this is explicitly wrapping the entire connector

(... or if you're asking if there's any reason not to merge this immediately - nope, this is entirely safe to merge)

**Comment by johnny-schmidt** [comment]
> sorry, like name the package `operation` instead of `destination_process`? I feel like operation is more for under-the-hood stuff, where this is explicitly wrapping the entire connector
> 
> (... or if you're asking if there's any reason not to merge this immediately - nope, this is entirely safe to merge)

Ignore me. I was tired last night. I meant "write", but on closer look that's obviously not appropriate for this.

**Review by johnny-schmidt — APPROVED** [review]

**Pull request merged**
