### PR TITLE
fix: add testcases for cron util

### PR DESCRIPTION
**Pull request by harshithmullapudi**
## What
Adding testcases for the cron validation util added in [PR](https://github.com/airbytehq/airbyte/pull/16375)

### CODE REVIEW

**Comment by lmossman** [comment]
@harshithmullapudi are these test cases coming from the library that you pulled the cron util code from? I wonder if it would be better to just pull in that cron library package instead of adding the util code and these tests, so that we don't have to maintain this code and so that we can get any updates or fixes they make to the package?

**Comment by harshithmullapudi** [comment]
Hey @lmossman thought the same but they are not maintaining the code. Also, they don't have the support for seconds and it's breaking with some of the testcases. 

https://github.com/GuillaumeRochat/cron-validator here is the package. 

I did make the change in our code and added the test cases for that change. But yeah if you think we should create a PR in the repo and wait for it we can. 

WDYT?

**Comment by lmossman** [comment]
@harshithmullapudi you said they don't have support for seconds, but reading through the [readme](https://github.com/GuillaumeRochat/cron-validator) on that github repo it looks like it does support seconds? So I'm not entirely understanding the issue

**Comment by lmossman** [comment]
@timroes do you have any thoughts on depending on third-party packages like this that may not be actively maintained? Not sure what our general frontend approach to this is

**Comment by harshithmullapudi** [comment]
Hey sorry I edited the post after writing. There is no year support so we will need to add this piece 

```js
const isValidYearValue = function (year: string) {
  if (isWildcard(year)) {
    return true;
  } else if (year.includes("/")) {
    const startingYearOptionArr = year.split("/");
    const isValidYear = isValidateYear([startingYearOptionArr[0]]);
    const isValidRepeatOccurrence =
      parseInt(startingYearOptionArr[1]) >= 0 && parseInt(startingYearOptionArr[1]) <= 129;
    if (!isValidYear) {
      return false;
    }
    if (!isValidRepeatOccurrence) {
      return false;
    }
    return isValidYear && isValidRepeatOccurrence;
  } else if (year.includes("-")) {
    const yearRangeArr = year.split("-");
    const isValidYear = isValidateYear(yearRangeArr);
    const isValidRange = parseInt(yearRangeArr[0]) <= parseInt(yearRangeArr[1]);
    if (!isValidYear) {
      return false;
    }
    if (!isValidRange) {
      return false;
    }
    return isValidYear && isValidRange;
  } else if (year.includes(",")) {
    const multiYearArr = year.split(",");
    if (!isValidateYear(multiYearArr)) {
      return false;
    }
    return isValidateYear(multiYearArr);
  } else if (parseInt(year) >= 1970 && parseInt(year) <= 2099) {
    return true;
  }
  return false;
};
```

**Comment by harshithmullapudi** [comment]
And yeah the test cases also for this. I am unsure if someone uses year but I can see some examples in the shared documentation.

In case we are not using year then we can use the package. 

cc: @lmossman @timroes

**Pull request closed without merging**
