### PR TITLE
Source Google Analytics v4: fix expected records

### PR DESCRIPTION
**Pull request by roman-yermilov-gl**
## What
*Expected records do not match. `isDataGolden` changed from false to true*

## How
*Changed expected records as data become golden*

### CODE REVIEW

**Comment by roman-yermilov-gl** [comment]
> /test connector=connectors/source-google-analytics-v4
> 
> > clock2 connectors/source-google-analytics-v4 https://github.com/airbytehq/airbyte/actions/runs/5089816275
> > x connectors/source-google-analytics-v4 https://github.com/airbytehq/airbyte/actions/runs/5089816275
> > bug https://gradle.com/s/mcjywacb32dyo
> 
> ### Build Failed
> Test summary info:
> 
> ```
> =========================== short test summary info ============================
> FAILED test_core.py::TestConnection::test_check[inputs0] - docker.errors.Cont...
> FAILED test_core.py::TestBasicRead::test_read[inputs0] - AssertionError: At l...
> FAILED test_full_refresh.py::TestFullRefresh::test_sequential_reads[inputs0]
> FAILED test_incremental.py::TestIncremental::test_two_sequential_reads[inputs0]
> FAILED test_incremental.py::TestIncremental::test_read_sequential_slices[inputs0]
> SKIPPED [1] ../usr/local/lib/python3.9/site-packages/connector_acceptance_test/tests/test_core.py:578: The previous and actual discovered catalogs are identical.
> ============= 5 failed, 34 passed, 1 skipped in 129.26s (0:02:09) ==============
> ```

Quota Error: exceeded the daily request limit

**Review by lazebnyi — APPROVED** [review]

**Pull request merged**
