### PR TITLE
Rename directories to deduplicate on artifact ids.

### LINKED ISSUE #5188: Deduplicate all directory names to avoid producing jars with conflicting names.
## Tell us about the problem you're trying to solve
As title.

This is only a problem when Cloud modules try to depend on jars with the same name. The jars override each other and produce a mess.

This unblocks letting us properly depend on the OSS repo.

## Describe the solution you’d like
Directories with identical names will take on the parent directory name to dedup.

### PR DESCRIPTION
**Pull request by davinchia**
## What
We have several inner-level directories with identical names. This causes jar name conflicts in imports e.g. we have several `model` directories that provide jars named `model-x.jar` that step on each other when imported.

It is possible to configure this via Gradle, but the configuration is messy and will exist in each subproject's gradle file.

An easier solution is to rename the child directories to so that they are named parent-child instead of just child. e.g. `init` -> `configs-init`.

Names are slightly longer, but this will definitely let us deconflict on names.

Closes #5188 .

Also added logic in Gradle to error on duplicate Java directories in the future.

Related Cloud PR: https://github.com/airbytehq/airbyte-cloud/pull/114

## Recommended reading order
1. `build.gradle` to see the modules names that have changed as well as logic to prevent duplicate directories.

## Pre-merge Checklist
Expand the checklist which is relevant for this PR. 

<details><summary> <strong> Connector checklist </strong> </summary>
<p>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Secrets are annotated with `airbyte_secret` in the connector's spec
- [ ] Credentials added to Github CI if needed and not already present. [instructions for injecting secrets into CI](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#using-credentials-in-ci). 
- [ ] Unit & integration tests added as appropriate (and are passing)
    * Community members: please provide proof of this succeeding locally e.g: screenshot or copy-paste acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] `/test connector=connectors/<name>` command as documented [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-an-existing-connector) is passing. 
    * Community members can skip this, Airbyters will run this for you. 
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] `README.md`
    - [ ] `docs/SUMMARY.md` if it's a new connector
    - [ ] Created or updated reference docs in `docs/integrations/<source or destination>/<name>`.
    - [ ] Changelog in the appropriate page in `docs/integrations/...`. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md` contains a reference to the new connector
    - [ ] Build status added to [build page](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md)
- [ ] Build is successful
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector#updating-a-connector)
- [ ] No major blockers
- [ ] PR merged into master branch
- [ ] Follow up tickets have been created
- [ ] Associated tickets have been closed & stakeholders notified
</p>
</details>

<details><summary> <strong> Connector Generator checklist </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Review by jrhizor — CHANGES_REQUESTED** [review]
Main blocker: It isn't safe to move the source and destination definition files, right? 

Second concern (a bit nitpicky / definitely not a blocker): I don't think this really achieves a great naming scheme over all. We'll end up with `io.airbyte:config-models` instead of `io.airbyte:airbyte-config-models` which matches the structure of `io.airbyte:airbyte-server` and such. To get the latter we'd probably have to un-nest. Maybe `io.airbyte:config-models` is better, but then it probably makes more sense to rename the root models as well. 

Regardless of the actual naming, wouldn't a better way of doing this be to specify the actual names for the artifacts we're creating in each of the modules we're publishing instead of renaming the directories? We should still have the verification you added, but on the artifact name instead of inferred name based off of directory structure. This also might be the easiest way to make this change given that we're reading from github locations for definition files as well.

What do you think?

**Comment by cgardens** [comment]
> Main blocker: It isn't safe to move the source and destination definition files, right?

Jared is right about this. though at some point we need to tear off the bandaid on this. it does not have to be now.

> It is possible to configure this via Gradle, but the configuration is messy and will exist in each subproject's gradle file.

Is it possible to set up a rule or something at the root gradle project that says the jar name should be the concatenation of the whole file path? e.g. `airbyte:airbyte-config:models` -> `airbyte-airbyte-config-models.jar` (or something, pruning off the initial airbyte would probably look less silly). I appreciate that you've added the check in the root build so at least we won't mess this up, but it going to be a sorta weird gotcha (specifying that child names must be unique).

**Comment by jrhizor** [comment]
I think I'd prefer explicitly specifying names in each subproject instead of using a non-standard "magic" naming convention. If this seems easier to do though it's probably worth it.

**Comment by cgardens** [comment]
Screen Shot 2021-08-06 at 12 17 59 PM

Could you point out how to reproduce this issue? I'm looking at what is built by gradle and the jar names seems to be unique (it already includes the full file path in the name and the version number). How can I find the jars that have the ambiguous naming?

**Comment by jrhizor** [comment]
My understanding was that it doesn't know how to publish the jar since it's published by the name (models-*) instead of the actual jar name.

**Comment by davinchia** [comment]
> Jared is right about this. though at some point we need to tear off the bandaid on this. it does not have to be now.

Good catch. I can put these back. The main conflicts were within the `models` and `persistence` submodules, I can leave init untouched. This is because of the `GithubStore` yes?

> Could you point out how to reproduce this issue? I'm looking at what is built by gradle and the jar names seems to be unique (it already includes the full file path in the name and the version number). How can I find the jars that have the ambiguous naming?

Yeap! The local jar name doesn't match what is actually published. See [the jars published ](https://admin.cloudrepo.io/repository/airbyte-public-jars/io/airbyte/airbyte-config)to cloud repo as an example. This causes the following problem:
```
config-models-0.29.2-alpha.jar
io.airbyte-cloud.cloud-config-cloud-config-models-0.29.2-alpha.jar
models-0.29.2-alpha.jar
scheduler-models-0.29.2-alpha.jar
```
This is the cloud-server jar that I've unpacked. You see that only the project dependency has the dedup full name, the remote jars are named by their artifact ids (Gradle defaults to directory name). Here, the remaining `models` jar is from the airbyte-protocol, which I've not renamed since it affects a bunch of connectors. Without the artifact ids being dedup (achieved via uniq dir names) the jars were overriding each other.

> Is it possible to set up a rule or something at the root gradle project that says the jar name should be the concatenation of the whole file path? e.g. airbyte:airbyte-config:models -> airbyte-airbyte-config-models.jar (or something, pruning off the initial airbyte would probably look less silly)

> Regardless of the actual naming, wouldn't a better way of doing this be to specify the actual names for the artifacts we're creating in each of the modules we're publishing instead of renaming the directories?

I tried for an hour and a half the other day and wasn't able to get it working. Specifying in the individual modules works - I didn't like it because it's annoying to have to do this for all submodules, and confusing if we only do it for some. If we do it for all submodules, there is also potential for some configuration drift.

> Second concern (a bit nitpicky / definitely not a blocker): I don't think this really achieves a great naming scheme over all. We'll end up with io.airbyte:config-models instead of io.airbyte:airbyte-config-models which matches the structure of io.airbyte:airbyte-server and such. To get the latter we'd probably have to un-nest. Maybe io.airbyte:config-models is better, but then it probably makes more sense to rename the root models as well.

I don't understand this completely, can you explain more? Definitely open to different naming or package changes.

Because I prefer centralising the publishing info to make things easy to keep track of, I'm leaning toward having unique directory names rather than specifying artifact ids in each project.

Also thinking we should have a convention that Java core modules don't go more than 2 levels deep (with the exception of the integrations modules since all those modules are self contained)

**Comment by cgardens** [comment]
> Specifying in the individual modules works - I didn't like it because it's annoying to have to do this for all submodules, and confusing if we only do it for some. If we do it for all submodules, there is also potential for some configuration drift, since things aren't centralised. I can try to look at this again, but felt this is low marginal value vs the urgency of getting OSS -> Cloud deps working.

Yeah. Agreed. Having to do this for every java submodule is dangerous. I guess I'd like to understand why if it was working for submodules why it can't be a configuration at the root level. Would you mind sharing a code snippet of what you tried at the submodule level so I can understand a little better?

**Comment by davinchia** [comment]
Sure.

This is from the main `build.gradle` file. I left `#` comments here to indicate where I was trying to do stuff.
```
configure(subprojects.findAll { toPublish.contains(it.getPath()) }) {
    apply plugin: 'maven-publish'
    
    # adding this block to the submodule level will define publishing info for each submodule
    publishing {
        repositories {
            publications {
                // This block is present so Gradle knows to publish a Maven jar.
                maven(MavenPublication) {
                    from components.java
                    // Gradle will by default use the subproject path as the group id and the subproject name as the artifact id.
                    // e.g. the subproject :airbyte-scheduler:scheduler-models is imported at io.airbyte.airbyte-config:persistence:<version-number>.
                    # I was trying to dynamically set the artifactId here based on the project name.
                }
            }

            maven {
                credentials {
                    name 'cloudrepo'
                    username System.getenv('CLOUDREPO_USER')
                    password System.getenv('CLOUDREPO_PASSWORD')
                }
                url 'https://airbyte.mycloudrepo.io/repositories/airbyte-public-jars'
            }

            mavenLocal()
        }
    }
}
```

I couldn't find a good way to map project -> artifact name inside the configure block.

Maybe we can try with the `allProjects` block?

**Comment by cgardens** [comment]
@davinchia should we close this? sounds like infra team is working on this in another branch anyway?

**Pull request closed without merging**
