### PR TITLE
Source Tiktok: Add missing metrics and add AdsAudienceReportsByCountry and AdsAudienceReportsByProvince streams

### PR DESCRIPTION
**Pull request by iberchid**
## What
Relates to #17402 

## How
1- Add below metrics missing in the connector:
- profile_visits_rate
- purchase
- purchase_rate
- registration
- registration_rate
- sales_lead
- sales_lead_rate
- cost_per_app_install
- cost_per_purchase
- cost_per_registration
- total_purchase_value
- cost_per_sales_lead
- cost_per_total_sales_lead
- cost_per_total_app_event_add_to_cart
- total_app_event_add_to_cart

2- Add `AdsAudienceReportsByCountry` and `AdsAudienceReportsByProvince`

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by koconder** [comment]
All unit tests should be patched for the exception of:
```
	 FAILED unit_tests/unit_test.py::test_source_streams[secrets/prod_config.json-26]
	 FAILED unit_tests/unit_test.py::test_source_streams[secrets/config.json-19]
```

The failing test `test_source_streams` which is currently returning:
```
(PROD_CONFIG_FILE, 26),
(SANDBOX_CONFIG_FILE, 19),
```

For `test_source_streams` the contexts of the two secrets files should assert as follows:
```
(PROD_CONFIG_FILE, 29),
(SANDBOX_CONFIG_FILE, 22),
```

Seems there are length/count of streams which need to be updated in the secrets `SourceTiktokMarketing().streams(config=config)`

**Review by vincentkoc — DISMISSED** [review]

**Comment by koconder** [comment]
@sajarin tbis fix is required on the airbyte secrets sidd

**Comment by iberchid** [comment]
Hello @koconder , any update on this PR :) ?

**Comment by sajarin** [comment]
@iberchid can you update the configured_catalog.json file with the new streams?

**Comment by iberchid** [comment]
The ads report by province is not compatible with any time dimension, that's why I only put `full_refresh` as `supported_sync_mode` in `ads_audience_reports_by_province` and `ads_audience_reports_by_province_daily` streams.

**Comment by marcosmarxm** [comment]
Hello :wave:, first thank you for this amazing contribution. 

We really appreciate the effort you've made to improve the project.
We ask you patience for the code review. Last month our team was focused on Hacktoberfest event and that probably left some PR without the proper feedback. And this week, due to the Thanksgiving US Holiday, most our team is out of office with their families. Another important piece of information why code won't be merge this week is: as a safety measure the core team has decided to freeze merging code to main branch to keep the release stable. Next week we'll return to you with the proper code review and update the status of your contribution.

If you have any questions feel free to send me a message in Slack!
Thanks!

**Comment by marcosmarxm** [comment]
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

**Comment by koconder** [comment]
@iberchid i saw you pushed some changes, there are also some merge conflicts. Let me know when you are OK for me to take a look

**Comment by iberchid** [comment]
Hi @koconder you can take a look.

**Comment by koconder** [comment]
@iberchid there is an issue with the github actions, im unable to merge in from main branch to test again. Are you able to resolve the merge conflicts so i can properly test these changes?

**Comment by iberchid** [comment]
> @iberchid there is an issue with the github actions, im unable to merge in from main branch to test again. Are you able to resolve the merge conflicts so i can properly test these changes?

I rebased my branch with master but I believe something went wrong :see_no_evil:

**Comment by koconder** [comment]
@iberchid can you copy the connector code out of this PR and start a new PR, no idea what has gone wrong here. And I’ll review the new PR

**Comment by koconder** [comment]
@iberchid rebase resolved

**Comment by natalyjazzviolin** [comment]
Hey @iberchid the integration tests are failing at 
`Execution failed for task ':airbyte-integrations:connectors:source-tiktok-marketing:_unitTestCoverage'.`

Please look into this - we can't merge the PR until all tests are passing. Thanks for your contribution!

**Comment by koconder** [comment]
@natalyjazzviolin take another look at the error. There is an assertion on the config file which i can’t see. I believe this config/statefile is stored on the airbyte test side and not in the code. We updated the streams but the stream count is stored in the config based on the code.

image

**Comment by koconder** [comment]
@iberchid @natalyjazzviolin one option is i drop this assertion, but clearly its been put there for some reason.

**Comment by iberchid** [comment]
@koconder @natalyjazzviolin Any updates on this PR?

**Comment by iberchid** [comment]
I will submit a new PR for it @marcosmarxm

**Pull request closed without merging**
