### PR TITLE
Remove read() overrides from inheritors of AbstractDbSource

### PR DESCRIPTION
**Pull request by akashkulk**
This is a redundant, as the platform already calls check() before read(). Also has the benefit of speeding up syncs for Postgres and CockroachDB

### CODE REVIEW

**Review by ryankfu — APPROVED** [review]
LGTM following a republish to these connectors and their strict-encrypt variants

**Review by evantahler — COMMENTED** [review]
🥳 This just made the boot time of all DB sources faster!

I would expect this PR to also want to bump some connector versions and /test and /publish them perhaps?

**Comment by akashkulk** [comment]
> 🥳 This just made the boot time of all DB sources faster!
> 
> I would expect this PR to also want to bump some connector versions and /test and /publish them perhaps?

Yup! They're tested above and waiting on more DB sources folks to take a look before bumping connector versions + publishing + updating docs

**Review by subodh1810 — CHANGES_REQUESTED** [review]
So we used to run check before read because in cdc mode if debezium would not find a publication, it would try to create a publication by default (in check we make sure whether a publication exists or not). We should use https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-publication-autocreate-mode property and set it to `disabled` so that debezium doesnt try to create publication

**Comment by akashkulk** [comment]
> https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-publication-autocreate-mode

Seems like it is already set here : https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresCdcProperties.java#L42

**Comment by akashkulk** [comment]
Seems like we still need this check before read here. For whatever reason, with the wal2json plugin (without publication) doesn't actually throw an exception, but fails silently. Not quite sure what the final result would be, but we could display a succesful sync to the user when in fact nothing occurred

**Review by rodireich — APPROVED** [review]

**Pull request closed without merging**
