### PR TITLE
`source-faker`: cursor = updated_at & remove records_per_sync

### PR DESCRIPTION
**Pull request by evantahler**

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`9d938ad61b`](https://github.com/airbytehq/airbyte/pull/27684/commits/9d938ad61bf9968d1ad732caad573487878ea63a)) - ❌

⏲️  Total pipeline duration: 40 seconds

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check.                                     | ✅        |
| Connector version increment check.                                  | ✅        |
| QA checks                                                           | ✅        |
| Code format checks                                                  | ❌        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_faker-updated-at-cursor/1687565250/9d938ad61bf9968d1ad732caad573487878ea63a/source-faker/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Review by edgao — APPROVED** [review]
thanks! doublechecking my understanding:
* if an incremental sync succeeds, the next sync will reemit the entire set of the same users
* but if an incremental sync crashes, the next sync will pick up at the previous state message

?

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`9d938ad61b`](https://github.com/airbytehq/airbyte/pull/27684/commits/9d938ad61bf9968d1ad732caad573487878ea63a)) - ❌

⏲️  Total pipeline duration: 55 seconds

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check.                                     | ✅        |
| Connector version increment check.                                  | ✅        |
| QA checks                                                           | ✅        |
| Code format checks                                                  | ❌        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_faker-updated-at-cursor/1687565453/9d938ad61bf9968d1ad732caad573487878ea63a/source-faker/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by evantahler** [comment]
> thanks! doublechecking my understanding:
> 
> * if an incremental sync succeeds, the next sync will reemit the entire set of the same users
> * but if an incremental sync crashes, the next sync will pick up at the previous state message
> 
> ?

Exactly!

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`29852f6343`](https://github.com/airbytehq/airbyte/pull/27684/commits/29852f6343be5443b1cb0f26ebb64209a378d5e2)) - ❌

⏲️  Total pipeline duration: 31 seconds

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check.                                     | ✅        |
| Connector version increment check.                                  | ✅        |
| QA checks                                                           | ✅        |
| Code format checks                                                  | ✅        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_faker-updated-at-cursor/1687565701/29852f6343be5443b1cb0f26ebb64209a378d5e2/source-faker/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`45d840e0d1`](https://github.com/airbytehq/airbyte/pull/27684/commits/45d840e0d1f3956d2ad00cf00491f2853a7b1f8b)) - ❌

⏲️  Total pipeline duration: 1314 seconds

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check.                                     | ✅        |
| Connector version increment check.                                  | ✅        |
| QA checks                                                           | ✅        |
| Code format checks                                                  | ✅        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ✅        |
| Acceptance tests                                                    | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_faker-updated-at-cursor/1687588184/45d840e0d1f3956d2ad00cf00491f2853a7b1f8b/source-faker/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`f40fbf170e`](https://github.com/airbytehq/airbyte/pull/27684/commits/f40fbf170efa07fd19172681bcb4bfc598e3e156)) - ❌

⏲️  Total pipeline duration: 1294 seconds

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| Connector version increment check                                   | ✅        |
| QA checks                                                           | ✅        |
| Code format checks                                                  | ✅        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ✅        |
| Acceptance tests                                                    | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_faker-updated-at-cursor/1687626924/f40fbf170efa07fd19172681bcb4bfc598e3e156/source-faker/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`b50113ddc7`](https://github.com/airbytehq/airbyte/pull/27684/commits/b50113ddc75f4359cf2c00858edc231bc60222a0)) - ❌

⏲️  Total pipeline duration: 1327 seconds

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| Connector version increment check                                   | ✅        |
| QA checks                                                           | ✅        |
| Code format checks                                                  | ✅        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ✅        |
| Acceptance tests                                                    | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_faker-updated-at-cursor/1687631202/b50113ddc75f4359cf2c00858edc231bc60222a0/source-faker/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`3a53311823`](https://github.com/airbytehq/airbyte/pull/27684/commits/3a533118238d41953a5d2af215f1e1492ec32763)) - ❌

⏲️  Total pipeline duration: 130 seconds

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| Connector version increment check                                   | ✅        |
| QA checks                                                           | ✅        |
| Code format checks                                                  | ✅        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ✅        |
| Acceptance tests                                                    | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_faker-updated-at-cursor/1687634029/3a533118238d41953a5d2af215f1e1492ec32763/source-faker/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`3bf10685ff`](https://github.com/airbytehq/airbyte/pull/27684/commits/3bf10685ffedda5ce2f27c6bdc89a48cafac9e81)) - ❌

⏲️  Total pipeline duration: 100 seconds

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| Connector version increment check                                   | ✅        |
| QA checks                                                           | ✅        |
| Code format checks                                                  | ✅        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ✅        |
| Acceptance tests                                                    | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_faker-updated-at-cursor/1687634686/3bf10685ffedda5ce2f27c6bdc89a48cafac9e81/source-faker/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Comment by octavia-squidington-iii** [comment]
##  source-faker test report (commit [`46b93997f1`](https://github.com/airbytehq/airbyte/pull/27684/commits/46b93997f1da487f9d307b88babce9037bb58cc6)) - ✅

⏲️  Total pipeline duration: 101 seconds

| Step                                                                | Result   |
|:--------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-faker/metadata.yaml | ✅        |
| Connector version semver check                                      | ✅        |
| Connector version increment check                                   | ✅        |
| QA checks                                                           | ✅        |
| Code format checks                                                  | ✅        |
| Connector package install                                           | ✅        |
| Build source-faker docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                          | ✅        |
| Acceptance tests                                                    | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/evan_faker-updated-at-cursor/1687634985/46b93997f1da487f9d307b88babce9037bb58cc6/source-faker/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-faker test
```

**Pull request merged**
