### PR TITLE
Source Zendesk Chat: passing timeout in request to prevent a stuck connection

### PR DESCRIPTION
**Pull request by RobertoBonnet**
## What
Resolving the problem that occurs when we are getting to much rows from Zendesk chat

https://github.com/airbytehq/airbyte/issues/12591

## How
Setting a timeout for requests.

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by harshithmullapudi** [comment]
@RobertoBonnet thanks for the contribution. Can you share the screenshot of sourceAcceptanceTests and also follow these https://docs.airbyte.com/connector-development/#updating-an-existing-connector

**Comment by RobertoBonnet** [comment]
@harshithmullapudi Is this?
image

**Comment by marcosmarxm** [comment]
@RobertoBonnet could add the link to Zendesk documentation about the timeout parameter? Did you have a connection with more than 100k records did you try it with dev image?

**Comment by RobertoBonnet** [comment]
@marcosmarxm I didn't find anything in the documentation regarding the timeout, but in my tests I saw that it was happening. Apparently there is no timeout on either the server or the client side. 


Here's the print of what I processed with this image
image

**Comment by RobertoBonnet** [comment]
On a fresh install I am getting pendulum error. I decided to update to "pendulum >= 2,<3" and it worked. Should I do this in this PR?

image

**Comment by RobertoBonnet** [comment]
[original-requirements-logs-402.txt](https://github.com/airbytehq/airbyte/files/8720505/original-requirements-logs-402.txt)
[upgraded-pendulum-requirements-logs-402.txt](https://github.com/airbytehq/airbyte/files/8720506/upgraded-pendulum-requirements-logs-402.txt)

**Comment by RobertoBonnet** [comment]
@marcosmarxm Is there any way to run similar test locally? I'll check it

**Comment by marcosmarxm** [comment]
you can run `./gradlew airbyte-integrations:connectors:source-zendesk-chat:integrationTest`

**Comment by harshithmullapudi** [comment]
@RobertoBonnet any update here?

**Comment by jablonskijakub** [comment]
@RobertoBonnet have you tested it for ticket_metrics in Zendesk Support as well?

**Comment by RobertoBonnet** [comment]
@harshithmullapudi I was working with zendesk support. I'll check chat now.

@jablonskijakub Yes, but the problem with support is other. I have commented here https://github.com/airbytehq/airbyte/issues/12591

**Comment by RobertoBonnet** [comment]
@marcosmarxm @harshithmullapudi Can you run the test again?

**Comment by harshithmullapudi** [comment]
/publish connector=connectors/source-zendesk-chat auto-bump-version=false

**Pull request merged**
