### PR TITLE
Source Marketo: set high test strictness level

### LINKED ISSUE #19055: Source Marketo: enable `high` test strictness level in SAT
## What
A `test_strictness_level` field was introduced to Source Acceptance Tests (SAT).
Marketo is a generally_available connector, we want it to have a `high` test strictness level.

**This will help**:
- maximize the SAT coverage on this connector.
- document its potential weaknesses in term of test coverage.

## How
1. Migrate the existing `acceptance-test-config.yml` file to the latest configuration format. (See instructions [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/source-acceptance-test/README.md#L61))
2. Enable `high` test strictness level in `acceptance-test-config.yml`. (See instructions [here](https://github.com/airbytehq/airbyte/blob/master/docs/connector-development/testing-connectors/source-acceptance-tests-reference.md#L240))
3. Commit changes on `acceptance-test-config.yml` and open a PR.
4. Run SAT with the `/test` command on the branch.
5. If tests are failing please fix the failing test or use `bypass_reason` fields to explain why a specific test can't be run.

### PR DESCRIPTION
**Pull request by lazebnyi**
## What
https://github.com/airbytehq/airbyte/issues/19055

## How
- Modify full_refresh catalog
- Modify incremental catalog
- Add expected records
- Refactor acceptance test config

### CODE REVIEW

**Comment by lazebnyi** [comment]
Note: PR has been approved and merged. After that it was reverted because it has braking changes and we need communicate with customers before merge it. After Erica approve will be merged.

**Comment by lazebnyi** [comment]
Hi @erica-airbyte 
This PR will be affect all users what use source marketo, because it change schema field data type. 
Can you help us to communicate with users and let me know when I can merge it.

**Comment by erica-airbyte** [comment]
@lazebnyi there is only one customer that is using this connector. 

I will reach out to let them know of the changes. 

Can we have this go out next Tuesday January 31st?

**Comment by erica-airbyte** [comment]
@lazebnyi also will the customer need to refresh source schema and reset affected streams?

**Comment by lazebnyi** [comment]
@erica-airbyte Ok, let's do that in next Tuesday January 31st. Thanks! Yeah, you are right. The customer need to refresh source schema and reset affected streams.

**Review by grubberr — APPROVED** [review]

**Comment by erica-airbyte** [comment]
@lazebnyi this is going out today correct?

**Comment by lazebnyi** [comment]
@erica-airbyte yes, it is already deployed.

**Pull request merged**
