### PR TITLE
Extend low code OAuthAuthenticator with token refresh capabilities

### PR DESCRIPTION
**Pull request by flash1293**
## What

Related to https://github.com/airbytehq/airbyte/issues/26342

Allow a user to specify a refresh token updater object as part of the `OAuthAuthenticator` low code component:
```
    authenticator:
      type: OAuthAuthenticator
      client_id: "some_client_id"
      client_secret: "some_client_secret"
      token_refresh_endpoint: "https://api.sendgrid.com/v3/auth"
      refresh_token: "{{ config['apikey'] }}"
      refresh_request_body:
        body_field: "yoyoyo"
        interpolated_body_field: "{{ config['apikey'] }}"
      refresh_token_updater:
        refresh_token_name: "the_refresh_token"
        refresh_token_config_path:
          - apikey
```

If specified, the refresh token, access token and access token expiry time returned from the authentication response is written back to the config object. This is important if a refresh token can only be used once.

## How

* Add refresh_token_updater object to the existing oauth configuration
* If set, instantiate a SingleUseRefreshTokenOAuth2Authenticator instead

Following changes were necessary in the CDK class:
* Replace config id and client config paths params with regular string params (resolve in factory) - if not set they still grab it from the config automatically (required to adapt the xero connector because it uses custom config paths - see https://github.com/airbytehq/airbyte/pull/27007)
* Add expiry format if it's not a number of seconds for feature compatibility as the regular oauth authenticator already allowed this
* Do not fail if config values are not available

On the low code CDK side, the jinja interpolation happens in the factory at creation time.

Changes to quickbooks and removing the existing low code component will happen on a separate PR.

Long term, it's planned to merge the functionality in a single class, this has been split out of the initial phase to reduce risk and scope.

## 🚨 User Impact 🚨

SingleUseRefreshTokenOAuth2Authenticator interface does not support custom config paths anymore for client id and client secret, needs to be adapted by resolving them before creating an instance.

### CODE REVIEW

**Review by girarda — APPROVED** [review]
lgtm! 🚢

**Comment by flash1293** [comment]
@girarda Could you take another quick look? Adjusted as discussed in grooming: Make work with empty config values (remove validation and do not fail on empty config values)

The discussed removal of the direct SingleUseRefreshTokenOAuthAuthenticator in low code will be done in a follow-up PR: https://github.com/airbytehq/airbyte/pull/27053

**Review by girarda — APPROVED** [review]

**Pull request merged**
