### PR TITLE
🐛 Source Braintree: Reverts braintree pagination

### PR DESCRIPTION
**Pull request by AGPapa**
## What
An issue with pagination in Braintree was reported here: https://github.com/airbytehq/airbyte/pull/42096#issuecomment-2245860946

This PR reverts #42096 so we have it as an option to fix the problem. I'm not able to replicate the problem on my side, so I'm not sure how to fix it.

## How
Reverts #42096

## Review guide

`airbyte-integrations/connectors/source-braintree/source_braintree/manifest.yaml`

## User Impact
Users will once again be limited to a maximum of 50 records per sync. The seemingly full resyncs it's attempting now should stop.

## Can this PR be safely reverted and rolled back?

- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Geeeh, what about adding an error handler when get a 422 error? This looks more a problem of Braintree API of not being able to handle old pagination and timeout. I don't have knowledge about Braintree API and... looking into their API Reference docs wasn't simple. @natikgadzhi any insights or thoughts?

**Comment by AGPapa** [comment]
> what about adding an error handler when get a 422 error?

I think that would let it pass, but it still sounds like it's trying to do a full new sync. (there are over 1000 pages it's returning where it sounds like normally for this user the incremental data should fit into one page). Catching the 422 error wouldn't fix that.

**Comment by AGPapa** [comment]
Maybe we could try rebuilding the connector using the GraphQL api instead?

**Comment by AGPapa** [comment]
I've asked if this behavior is in incremental mode or in full refresh mode. I'm trying to recreate the issue myself to debug it.

If we're only getting this issue in full refresh mode then I think I agree with you that we can probably catch that 422 error and retry just the one page.

**Comment by AGPapa** [comment]
Closing this - PR #42848 fixed the pagination issue

**Pull request closed without merging**
