### PR TITLE
🎉 Remove deprecated Google  connectors: Adwords, Search Console, Analytics

### LINKED ISSUE #6165: Remove deprecated singer connectors
## Tell us about the problem you're trying to solve
We've replaced a bunch of singer connectors with airbyte native ones. We should remove those connectors from the repo, making sure to remove any build references to them (basically doing the new connector checklist but in "undo" mode) 

## Describe the solution you’d like
Removing the following connectors: 

1. Google Adwords 
2. google search console singer
3. google analytics singer

### PR DESCRIPTION
**Pull request by yevhenii-ldv**
## What
*resolves #6165 .*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

### CODE REVIEW

**Review by htrueman — APPROVED** [review]

**Review by sherifnada — APPROVED** [review]
Please also remove any secrets from Github CI to make room for new ones!

**Review by Zirochkaa — APPROVED** [review]

**Pull request merged**
