### PR TITLE
Update sl metadata for python sources

### PR DESCRIPTION
**Pull request by ChristoGrab**
## What
Updates the value of metadata `sl` tag to 300 for the following connectors owned by the Python Sources team, for paging purposes in Sentry:

- Airtable
- Azure Blob Storage
- Bing Ads
- File
- Github
- Instagram
- Jira
- Klaviyo
- Microsoft Sharepoint
- SFTP Bulk

## Note on CI Failure
Source Instagram failed to build in the CI. It looks like I'd have to re-run the entire test suite on all 10 connectors to retry this. Given the fact that this is a metadata-only update and the failure was likely a CI glitch, my vote is to approve-and-merge despite the failure.

## Can this PR be safely reverted and rolled back?
- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by natikgadzhi — APPROVED** [review]
I'm personally happy, I want @alafanechere to give us his blessing to a metadata change without a version bump. Any reason that's not cool? CI thinks it's cool (aside from Instagram huh)

**Review by alafanechere — APPROVED** [review]

**Comment by alafanechere** [comment]
> I'm personally happy, I want @alafanechere to give us his blessing to a metadata change without a version bump. Any reason that's not cool? CI thinks it's cool (aside from Instagram huh)

It's 🆗 to not bump the version as not connector code changed and this metadata field has no impact on the build.

**Comment by ChristoGrab** [comment]
The build for Instagram failed again, I'm reverting that change to unblock the pipeline on this PR and will take a look at Instagram separately.

**Pull request merged**
