### PR TITLE
Source Hubspot, Source Salesforce - fix builds

### PR DESCRIPTION
**Pull request by davydov-d**
## What
Fix builds for the Source Hubspot and Source Salesforce

## How
- Update expected records

### CODE REVIEW

**Review by bazarnov — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-hubspot test report (commit [`fe8c5790a8`](https://github.com/airbytehq/airbyte/pull/31773/commits/fe8c5790a82ecf69028f4d4e5f7fad4e46d9cf59)) - ✅

⏲️  Total pipeline duration: 13mn01s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Build source-hubspot docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                    | ✅       |
| Integration tests                                             | ✅       |
| Acceptance tests                                              | ✅       |
| Check our base image is used                                  | ✅       |
| Code format checks                                            | ✅       |
| Validate metadata for source-hubspot                          | ✅       |
| Connector version semver check                                | ✅       |
| QA checks                                                     | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_fix-hubspot-salesforce-builds/1698151335/fe8c5790a82ecf69028f4d4e5f7fad4e46d9cf59/source-hubspot/1.6.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:fe8c5790a82ecf69028f4d4e5f7fad4e46d9cf59)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-hubspot test report (commit [`e678ad7d7c`](https://github.com/airbytehq/airbyte/pull/31773/commits/e678ad7d7cbeade2fb76947efd462206a4107e30)) - ✅

⏲️  Total pipeline duration: 08mn37s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Build source-hubspot docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                    | ✅       |
| Integration tests                                             | ✅       |
| Acceptance tests                                              | ✅       |
| Check our base image is used                                  | ✅       |
| Code format checks                                            | ✅       |
| Validate metadata for source-hubspot                          | ✅       |
| Connector version semver check                                | ✅       |
| QA checks                                                     | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_fix-hubspot-salesforce-builds/1698153519/e678ad7d7cbeade2fb76947efd462206a4107e30/source-hubspot/1.6.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e678ad7d7cbeade2fb76947efd462206a4107e30)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-salesforce test report (commit [`e678ad7d7c`](https://github.com/airbytehq/airbyte/pull/31773/commits/e678ad7d7cbeade2fb76947efd462206a4107e30)) - ❌

⏲️  Total pipeline duration: 54mn47s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Build source-salesforce docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                       | ✅       |
| Integration tests                                                | ✅       |
| Acceptance tests                                                 | ❌       |
| Check our base image is used                                     | ✅       |
| Code format checks                                               | ✅       |
| Validate metadata for source-salesforce                          | ✅       |
| Connector version semver check                                   | ✅       |
| QA checks                                                        | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_fix-hubspot-salesforce-builds/1698153519/e678ad7d7cbeade2fb76947efd462206a4107e30/source-salesforce/2.1.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e678ad7d7cbeade2fb76947efd462206a4107e30)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-salesforce test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-hubspot test report (commit [`b106adf113`](https://github.com/airbytehq/airbyte/pull/31773/commits/b106adf113d380356d9a89e14d67092964e01361)) - ✅

⏲️  Total pipeline duration: 07mn50s 

| Step                                                          | Result   |
|:--------------------------------------------------------------|:---------|
| Build source-hubspot docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                    | ✅       |
| Integration tests                                             | ✅       |
| Acceptance tests                                              | ✅       |
| Check our base image is used                                  | ✅       |
| Code format checks                                            | ✅       |
| Validate metadata for source-hubspot                          | ✅       |
| Connector version semver check                                | ✅       |
| QA checks                                                     | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_fix-hubspot-salesforce-builds/1698157361/b106adf113d380356d9a89e14d67092964e01361/source-hubspot/1.6.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b106adf113d380356d9a89e14d67092964e01361)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-salesforce test report (commit [`b106adf113`](https://github.com/airbytehq/airbyte/pull/31773/commits/b106adf113d380356d9a89e14d67092964e01361)) - ✅

⏲️  Total pipeline duration: 26mn02s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Build source-salesforce docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                       | ✅       |
| Integration tests                                                | ✅       |
| Acceptance tests                                                 | ✅       |
| Check our base image is used                                     | ✅       |
| Code format checks                                               | ✅       |
| Validate metadata for source-salesforce                          | ✅       |
| Connector version semver check                                   | ✅       |
| QA checks                                                        | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_fix-hubspot-salesforce-builds/1698157361/b106adf113d380356d9a89e14d67092964e01361/source-salesforce/2.1.5/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b106adf113d380356d9a89e14d67092964e01361)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-salesforce test
```

**Pull request merged**
