### PR TITLE
✨ Source Facebook Marketing: Added fields in campaign schema

### PR DESCRIPTION
**Pull request by mlavoie-sm360**
## What
- Solves #8255

## How
- Added fields to campaigns json schema

## 🚨 User Impact 🚨
- Adds new fields to stream

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated 
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</p>
</details>

### CODE REVIEW

**Comment by harshithmullapudi** [comment]
Hey @mlavoie-sm360 thanks for the contribution. Can you check this doc https://docs.airbyte.io/connector-development#updating-an-existing-connector and do later steps so that it's ready for review ?

**Comment by mlavoie-sm360** [comment]
@harshithmullapudi, not a problem. I have completed the few remaining steps, except for the code review. Is that something that someone from airbyte will do?

**Review by avida — APPROVED** [review]
Good job! For the future we would need to create a script to generate all missed fields from facebook specs: https://github.com/facebook/facebook-business-sdk-codegen/tree/65d97be34890e15057c0bac43504f0d34ca86318/api_specs/specs

**Comment by avida** [comment]
Looks like there is already such kind of script for fb pages connector #8267 @midavadim  Would it work for fb marketing? I noticed it doesnt support nested types like list<AdGroup>, am I right?

**Comment by mlavoie-sm360** [comment]
Thanks @avida, regarding generating all missed fields, I think that's a really good idea, perhaps we open a separate issue specifically for that request.

**Comment by midavadim** [comment]
> 

Hi, I think it would be possible top generate full schemas for this connector as well. 

I noticed it doesn't support nested types like list, am I right? -
It supports nested types but only 1 level inside, because nested type refers to other nested types and could refer to itself and create 'reference loops'.

**Pull request merged**
