### PR TITLE
🚨🚨 e2e-test: Standardize e2e testing destination spec

### PR DESCRIPTION
**Pull request by terencecho**
## What
Standardize the spec for the e2e testing destination aka destination-dev-null by wrapping the configurations in `test_destination` field under a `properties` field. We also change the name of a field from `type` to `test_destination_type` to avoid overloading JSON keywords.

## 🚨 User Impact 🚨
*Are there any breaking changes? What is the end result perceived by the user?*

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- Connector version is set to `0.0.1`
    - `Dockerfile` has version `0.0.1`
- Documentation updated
    - Connector's `README.md`
    - Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - `docs/integrations/<source or destination>/<name>.md` including changelog with an entry for the initial version. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - `docs/integrations/README.md`

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

<details><summary><strong>Connector Generator</strong></summary>

- Issue acceptance criteria met
- PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests#pull-request-title-convention)
- If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- Documentation which references the generator is updated as needed

</details>

### CODE REVIEW

**Review by erohmensing — APPROVED** [review]
If these changes are tested to make sure you can still set up the connector, then 👍🏻 from me. A few points: 

* This is a breaking change (change format of a connector's spec), but since its a testing destination, I don't expect it to break any production syncs - you can't actually move data by using it - so I think that we don't need to have outreach about this 
* I still think in the future that some connectors might use "type" as a property name/oneOf name and we should probably be able to handle that. I have no gripes changing it here though.

**Comment by terencecho** [comment]
it looks like the test that is failing is:
```
TestingSilentDestinationAcceptanceTest > testSyncNotFailsWithNewFields() FAILED
    org.opentest4j.AssertionFailedError: expected: <1> but was: <0>
```

however, it also fails when there are no changes from master
https://github.com/airbytehq/airbyte/pull/25943

@erohmensing would you say this is safe to publish even if it fails that test? I think this is failing because we don't expect any messages to be sent to a real output since it writes everything into dev-null

**Comment by erohmensing** [comment]
I don't know anything about the destination acceptance tests 😅 

In general, yeah, if I'm editing something and it's failing with something that is failing on master, I tend to think it is safe. I usually check against #connector-health, and don't see any destinations failing there - might be worth quickly asking the destinations team if they're aware of it

**Comment by terencecho** [comment]
I'm being told that `airbyte-config-oss/init-oss/src/main/resources/seed/oss_catalog.json` is being deprecated, so we are okay with it being out of sync with the actual spec.

**Comment by terencecho** [comment]
/publish connector=connectors/destination-e2e-test auto-bump-version=false

**Comment by terencecho** [comment]
/publish connector=connectors/destination-e2e-test auto-bump-version=false

**Comment by terencecho** [comment]
/publish connector=connectors/destination-e2e-test auto-bump-version=false run-tests=false

**Comment by terencecho** [comment]
/publish connector=connectors/destination-dev-null auto-bump-version=false run-tests=false

**Comment by terencecho** [comment]
/publish connector=connectors/destination-dev-null auto-bump-version=false run-tests=false

**Pull request merged**
