### PR TITLE
Increase memory allocation for JDBC buffers in source DB connectors

### PR DESCRIPTION
**Pull request by akashkulk**
Work is part of https://github.com/airbytehq/airbyte/issues/20417. 

- Follow-up to https://github.com/airbytehq/airbyte/pull/19514 where allocation of source's total memory for JDBC buffers was bumped from 50% -> 60%
- Increases `MAX_FETCH_SIZE` frpm 1,000,000 -> 2,000,000
- Removes concept of `MAX_BUFFER_BYTE_SIZE`, which was hard coded to `1GB`. The memory allocation now has an upper bound of  `TARGET_BUFFER_SIZE_RATIO * MAX_HEAP_SPACE`. This is so we can take advantage of the increased memory for source containers. 

Tested locally, and hasn't caused any additional OOMs

### CODE REVIEW

**Comment by akashkulk** [comment]
@evantahler / @davinchia I was trying to follow the comments from the previous PR. What's a good way to test this increase?

**Comment by evantahler** [comment]
> @evantahler / @davinchia I was trying to follow the comments from the previous PR. What's a good way to test this increase?

... I didn't come up with a good way to test this kind of change 😢 
I think for now, the best we can do is to publish the change (OSS) and run a few syncs with it on a local or staging K8s cluster and compare new vs old memory consumption for a sync. In the future, we'll be looking into blue/green connector deployments to try this connector out on a few cloud workspaces before rolling it out to everyone.

**Comment by davinchia** [comment]
@akashkulk you should be able to build the image locally, load it into a local airbyte deployment (either docker or K8s) and inspect memory usage as the sync runs. This all can be done before we merge this change into OSS.

Alternatively, you can also build the connector locally and run the connector's read command and inspect local memory usage. I'm going to find some time over the next few days to draft our a local test harness for this. Till then, I would recommend either of these two options.

**Review by evantahler — APPROVED** [review]
Approving.... but you probably want to test it first

**Comment by akashkulk** [comment]
> @akashkulk you should be able to build the image locally, load it into a local airbyte deployment (either docker or K8s) and inspect memory usage as the sync runs. This all can be done before we merge this change into OSS.
> 
> Alternatively, you can also build the connector locally and run the connector's read command and inspect local memory usage. I'm going to find some time over the next few days to draft our a local test harness for this. Till then, I would recommend either of these two options.

@davinchia What do you recommend to inspect docker memory usage in a local airbyte deployment?

**Comment by akashkulk** [comment]
Actually, I've realized that increasing this ration doesn't actually increase the memory allocation for JDBC buffers in source DB connectors. The algorithm is : 

`Math.min(1GB, Math.max(0.7*JVM_max_memory, 250MB))`

Where 0.7 is the defined target buffer ration. For our source container pods with ~2GB of memory, the JDBC buffer will always be at 1GB, so we'd have to remove that.

**Comment by evantahler** [comment]
Remove it!

**Comment by akashkulk** [comment]
/publish connector=connectors/source-postgres-strict-encrypt run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-postgres run-tests=false

**Comment by akashkulk** [comment]
/publish connector=connectors/source-mysql-strict-encrypt run-tests=false

**Pull request merged**
