### PR TITLE
Destination snowflake: Fix regression from cdk publish race condition

### LINKED ISSUE #30492: Destination snowflake (and maybe bigquery?): Create staging area with namespace
snowflake's `create stage` query is doing roughly `create stage airbyte_internal.<stream_name>`. If there are multiple streams with the same name but different namespace, they will clobber each other. We should give the stage name the same name as the raw table, i.e. `create stage airbyte_internal.<namespace>_raw__stream_<name>`.

Check if bigquery has a similar problem for its GCS files.

Errors look like:

```
ERROR i.a.i.d.s.SnowflakeInternalStagingSqlOperations(uploadRecordsToStage):85 Failed to upload records into stage 2023/09/14/14/720F6F38-07B5-48A6-A757-D348B352174A/ net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
Stage 'XXX."airbyte_internal"."sales"' does not exist or not authorized.
```

### PR DESCRIPTION
**Pull request by edgao**
0.1.0 ran into the publish race condition :(

publish 0.1.1 to include `bases-destination-jdbc` changes from https://github.com/airbytehq/airbyte/pull/30599

closes https://github.com/airbytehq/airbyte/issues/30492

### CODE REVIEW

**Review by evantahler — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`368efa0a6a`](https://github.com/airbytehq/airbyte/pull/30835/commits/368efa0a6ab5576442cf348909f8aa32bb7cfa83)) - ✅

⏲️  Total pipeline duration: 10mn13s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build connector tar                                                | ✅        |
| Build destination-snowflake docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                          | ✅        |
| Java Connector Integration Tests                                   | ✅        |
| Validate metadata for destination-snowflake                        | ✅        |
| Connector version semver check                                     | ✅        |
| Connector version increment check                                  | ✅        |
| QA checks                                                          | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_java_cdk_republish/1695917172/368efa0a6ab5576442cf348909f8aa32bb7cfa83/destination-snowflake/3.1.16/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:368efa0a6ab5576442cf348909f8aa32bb7cfa83)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`4648ab0f0a`](https://github.com/airbytehq/airbyte/pull/30835/commits/4648ab0f0abd2c64b0199d560a852fbca02137e5)) - ✅

⏲️  Total pipeline duration: 10mn35s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build connector tar                                                | ✅        |
| Build destination-snowflake docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                          | ✅        |
| Java Connector Integration Tests                                   | ✅        |
| Validate metadata for destination-snowflake                        | ✅        |
| Connector version semver check                                     | ✅        |
| Connector version increment check                                  | ✅        |
| QA checks                                                          | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_java_cdk_republish/1695924223/4648ab0f0abd2c64b0199d560a852fbca02137e5/destination-snowflake/3.1.16/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:4648ab0f0abd2c64b0199d560a852fbca02137e5)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Comment by airbyte-oss-build-runner** [comment]
##  destination-snowflake test report (commit [`b6aa114603`](https://github.com/airbytehq/airbyte/pull/30835/commits/b6aa114603b97ef7671c545ea274c035392b937b)) - ✅

⏲️  Total pipeline duration: 11mn06s 

| Step                                                               | Result   |
|:-------------------------------------------------------------------|:---------|
| Build connector tar                                                | ✅        |
| Build destination-snowflake docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                          | ✅        |
| Java Connector Integration Tests                                   | ✅        |
| Validate metadata for destination-snowflake                        | ✅        |
| Connector version semver check                                     | ✅        |
| Connector version increment check                                  | ✅        |
| QA checks                                                          | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_java_cdk_republish/1695925234/b6aa114603b97ef7671c545ea274c035392b937b/destination-snowflake/3.1.16/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b6aa114603b97ef7671c545ea274c035392b937b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-snowflake test
```

**Pull request merged**
