### PR TITLE
Clarify the postgres connector supports replicating views

### PR DESCRIPTION
**Pull request by sherifnada**

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@sherifnada this should work for other JDBC connectors (Mysql, MSSQL, Oracle)?

**Comment by sherifnada** [comment]
created https://github.com/airbytehq/airbyte/issues/4369 to track

**Comment by sherifnada** [comment]
@tuliren branch was deleted - was there a reason you wanted to run this test?

**Comment by tuliren** [comment]
Sorry, I just need to run the base-normalization test on the master, and I randomly picked a PR. I created my own PR later on: #4372.

Cannot believe that it has already been two hours since I tried that. It feels like 20 minutes...

**Pull request merged**
