### PR TITLE
✨ Source MongoDB V2: Refactor common offset loading logic

### PR DESCRIPTION
**Pull request by jdpgrailsdev**
## What
* DRY common setup logic for retrieving Debezium offset state from file

## How
* Extract common logic to a shared interface

## Recommended reading order
1. `DebeziumStateUtil.java`
2. `MongoDbDebeziumStateUtil.java`
3. `MySqlDebeziumStateUtil.java`
4. `PostgresDebeziumStateUtil.java`

### CODE REVIEW

**Review by subodh1810 — COMMENTED** [review]
This looks good! Can we run the tests for both MySQL and Postgres to make sure nothing breaks. The CI for Postgres and MySQL both are broken so the tests need to run locally! :( 

Also lets hold on to this PR until we merged the cdc-integration branch on master. Then we can merge this directly in master!

**Comment by airbyte-oss-build-runner** [comment]
##  destination-bigquery test report (commit [`ad38feca25`](https://github.com/airbytehq/airbyte/pull/30029/commits/ad38feca25bd686cac90d531746e535e0372a059)) - ❌

⏲️  Total pipeline duration: 07mn44s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Build connector tar                                                         | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64           | ✅        |
| Java Connector Unit Tests                                                   | ✅        |
| Java Connector Integration Tests                                            | ✅        |
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| Connector version increment check                                           | ❌        |
| QA checks                                                                   | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_refactor-debezium-state-util/1695401192/ad38feca25bd686cac90d531746e535e0372a059/destination-bigquery/2.0.15/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ad38feca25bd686cac90d531746e535e0372a059)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-mongodb-v2 test report (commit [`01eccdfdbd`](https://github.com/airbytehq/airbyte/pull/30029/commits/01eccdfdbd0d02504c53043610d729202362faf8)) - ✅

⏲️  Total pipeline duration: 12mn28s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build connector tar                                            | ✅        |
| Build source-mongodb-v2 docker image for platform linux/x86_64 | ✅        |
| Java Connector Unit Tests                                      | ✅        |
| Java Connector Integration Tests                               | ✅        |
| Acceptance tests                                               | ✅        |
| Validate metadata for source-mongodb-v2                        | ✅        |
| Connector version semver check                                 | ✅        |
| QA checks                                                      | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/jonathan_refactor-debezium-state-util/1696352158/01eccdfdbd0d02504c53043610d729202362faf8/source-mongodb-v2/1.0.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:01eccdfdbd0d02504c53043610d729202362faf8)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-mongodb-v2 test
```

**Comment by jdpgrailsdev** [comment]
@subodh1810 I have verified that both the `CdcPostgresSourceTest` and `CdcMysqlSourceTest` tests pass from this branch.  The check failure on this PR is not reproducible locally and I have seen similar failures on other PR's, including ones that just update documentation.  I would like to merge this today if there are no other outstanding concerns.

**Review by subodh1810 — APPROVED** [review]
Looks good, lets make sure tests for mysql and postgres are green before merging

**Pull request merged**
