### PR TITLE
:rotating_light: :rotating_light: Source Amazon Ads: fix schemas

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/oncall/issues/1955

## How
Fix attribution report stream schemas:
 - exclude current upper level properties (cusrorId, size)
 - dynamically include metrics

## 🚨 User Impact 🚨
This is a breaking change because schemas of 4 streams are changing dramatically

### CODE REVIEW

**Comment by davydov-d** [comment]
I'll link the breaking change doc asap

**Comment by alafanechere** [comment]
@davydov-d please start a breaking change procedure: https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`b6ff7082c4`](https://github.com/airbytehq/airbyte/pull/27868/commits/b6ff7082c47316783843488a544383d8bcbcf4f6)) - ❌

⏲️  Total pipeline duration: 03mn15s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_1955-source-amazon-ads-fix-schemas/1688126765/b6ff7082c47316783843488a544383d8bcbcf4f6/source-amazon-ads/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`3ad046085c`](https://github.com/airbytehq/airbyte/pull/27868/commits/3ad046085c3632b26de488a75bd7baff9b74453c)) - ❌

⏲️  Total pipeline duration: 03mn10s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_1955-source-amazon-ads-fix-schemas/1688127069/3ad046085c3632b26de488a75bd7baff9b74453c/source-amazon-ads/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`12a4d49550`](https://github.com/airbytehq/airbyte/pull/27868/commits/12a4d49550f90799253bdeea0a1ea14a21e6244f)) - ✅

⏲️  Total pipeline duration: 03mn25s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_1955-source-amazon-ads-fix-schemas/1688130247/12a4d49550f90799253bdeea0a1ea14a21e6244f/source-amazon-ads/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Review by alafanechere — COMMENTED** [review]
Waiting for the breaking change doc to be linked and ratified to approve.

**Comment by davydov-d** [comment]
@alafanechere here is the doc https://docs.google.com/document/d/1toF5-5z4em07lK20uxgxV4EZY8m0l5k8afRcu2P0MSI/edit#heading=h.2198e4qioqm2

**Review by alafanechere — APPROVED** [review]
You mentioned in the doc that the destination table are empty, is it a breaking change if the empty table are now populated?

**Comment by davydov-d** [comment]
> You mentioned in the doc that the destination table are empty, is it a breaking change if the empty table are now populated?

Yep, just replied in the doc. This is not gonna be a breaking change for the connection reported in the issue, but I'm bot sure if all other destinations behave the same way

**Comment by alafanechere** [comment]
@davydov-d given the unknown I would prefer we follow the breaking change procedure.

**Review by lazebnyi — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`6b557d7d27`](https://github.com/airbytehq/airbyte/pull/27868/commits/6b557d7d27498e88cc4b3b6d1add5172db7ba782)) - ❌

⏲️  Total pipeline duration: 03mn19s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_1955-source-amazon-ads-fix-schemas/1688999060/6b557d7d27498e88cc4b3b6d1add5172db7ba782/source-amazon-ads/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`be6fa1c657`](https://github.com/airbytehq/airbyte/pull/27868/commits/be6fa1c657958aaa638ee29abdbe7c1a30c589ee)) - ✅

⏲️  Total pipeline duration: 03mn16s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_1955-source-amazon-ads-fix-schemas/1688999521/be6fa1c657958aaa638ee29abdbe7c1a30c589ee/source-amazon-ads/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`1c2c9e320d`](https://github.com/airbytehq/airbyte/pull/27868/commits/1c2c9e320de7d625220e7627adb1fe76930c5cde)) - ✅

⏲️  Total pipeline duration: 4.68s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_1955-source-amazon-ads-fix-schemas/1689930677/1c2c9e320de7d625220e7627adb1fe76930c5cde/source-amazon-ads/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`3eb3e6725c`](https://github.com/airbytehq/airbyte/pull/27868/commits/3eb3e6725c9aed04d19e405f12136b61d5e7940a)) - ❌

⏲️  Total pipeline duration: 03mn15s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| QA checks                                                                | ❌        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_1955-source-amazon-ads-fix-schemas/1689932719/3eb3e6725c9aed04d19e405f12136b61d5e7940a/source-amazon-ads/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`6385619f5b`](https://github.com/airbytehq/airbyte/pull/27868/commits/6385619f5baccc9f2a289eb2dc5ffdf78ff35f51)) - ❌

⏲️  Total pipeline duration: 02mn48s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| QA checks                                                                | ❌        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_1955-source-amazon-ads-fix-schemas/1689933181/6385619f5baccc9f2a289eb2dc5ffdf78ff35f51/source-amazon-ads/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Comment by octavia-squidington-iii** [comment]
##  source-amazon-ads test report (commit [`5d9d706483`](https://github.com/airbytehq/airbyte/pull/27868/commits/5d9d7064838626ec229080f54a0d598d824728fd)) - ✅

⏲️  Total pipeline duration: 05mn00s 

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-amazon-ads/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-amazon-ads docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_1955-source-amazon-ads-fix-schemas/1689933608/5d9d7064838626ec229080f54a0d598d824728fd/source-amazon-ads/3.0.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amazon-ads test
```

**Pull request merged**
