### PR TITLE
🐛 Source [Salesforce, Jira, Hubspot]: update `expected records`

### PR DESCRIPTION
**Pull request by bazarnov**
## What
Based on this tests:
- Salesforce: [test](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/nightly_builds/master/1697329072/99b9fc94fde1fc2fedd372165687aa4bbd8c4f28/source-salesforce/2.1.4/output.html)
- Jira: [test](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/nightly_builds/master/1697329072/99b9fc94fde1fc2fedd372165687aa4bbd8c4f28/source-jira/0.10.0/output.html)
- Hubspot: [test](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/nightly_builds/master/1697329072/99b9fc94fde1fc2fedd372165687aa4bbd8c4f28/source-hubspot/1.5.1/output.html)

Need to update `expected records` to pass the CAT.

## How
- updated `expected records.jsonl`

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-salesforce test report (commit [`cf2edd0915`](https://github.com/airbytehq/airbyte/pull/31446/commits/cf2edd09158d28c9c032be520ce3ba1d79112ee9)) - ❌

⏲️  Total pipeline duration: 02mn23s 

| Step   | Result   |
|--------|----------|

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_sources_fix-expected-records/1697454732/cf2edd09158d28c9c032be520ce3ba1d79112ee9/source-salesforce/2.1.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:cf2edd09158d28c9c032be520ce3ba1d79112ee9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-salesforce test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`cf2edd0915`](https://github.com/airbytehq/airbyte/pull/31446/commits/cf2edd09158d28c9c032be520ce3ba1d79112ee9)) - ✅

⏲️  Total pipeline duration: 08mn58s 

| Step                                                        | Result   |
|:------------------------------------------------------------|:---------|
| Build source-jira docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                  | ✅       |
| Integration tests                                           | ✅       |
| Acceptance tests                                            | ✅       |
| Code format checks                                          | ✅       |
| Validate metadata for source-jira                           | ✅       |
| Connector version semver check                              | ✅       |
| QA checks                                                   | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_sources_fix-expected-records/1697454732/cf2edd09158d28c9c032be520ce3ba1d79112ee9/source-jira/0.10.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:cf2edd09158d28c9c032be520ce3ba1d79112ee9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-hubspot test report (commit [`cf2edd0915`](https://github.com/airbytehq/airbyte/pull/31446/commits/cf2edd09158d28c9c032be520ce3ba1d79112ee9)) - ✅

⏲️  Total pipeline duration: 13mn07s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build source-hubspot docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                     | ✅       |
| Integration tests                                              | ✅       |
| Acceptance tests                                               | ✅       |
| Code format checks                                             | ✅       |
| Validate metadata for source-hubspot                           | ✅       |
| Connector version semver check                                 | ✅       |
| QA checks                                                      | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_sources_fix-expected-records/1697454732/cf2edd09158d28c9c032be520ce3ba1d79112ee9/source-hubspot/1.5.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:cf2edd09158d28c9c032be520ce3ba1d79112ee9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Review by tolik0 — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`cf2edd0915`](https://github.com/airbytehq/airbyte/pull/31446/commits/cf2edd09158d28c9c032be520ce3ba1d79112ee9)) - ✅

⏲️  Total pipeline duration: 04mn55s 

| Step                                                        | Result   |
|:------------------------------------------------------------|:---------|
| Build source-jira docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                  | ✅       |
| Integration tests                                           | ✅       |
| Acceptance tests                                            | ✅       |
| Code format checks                                          | ✅       |
| Validate metadata for source-jira                           | ✅       |
| Connector version semver check                              | ✅       |
| QA checks                                                   | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_sources_fix-expected-records/1697456431/cf2edd09158d28c9c032be520ce3ba1d79112ee9/source-jira/0.10.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:cf2edd09158d28c9c032be520ce3ba1d79112ee9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-hubspot test report (commit [`cf2edd0915`](https://github.com/airbytehq/airbyte/pull/31446/commits/cf2edd09158d28c9c032be520ce3ba1d79112ee9)) - ✅

⏲️  Total pipeline duration: 12mn55s 

| Step                                                           | Result   |
|:---------------------------------------------------------------|:---------|
| Build source-hubspot docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                     | ✅       |
| Integration tests                                              | ✅       |
| Acceptance tests                                               | ✅       |
| Code format checks                                             | ✅       |
| Validate metadata for source-hubspot                           | ✅       |
| Connector version semver check                                 | ✅       |
| QA checks                                                      | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_sources_fix-expected-records/1697456431/cf2edd09158d28c9c032be520ce3ba1d79112ee9/source-hubspot/1.5.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:cf2edd09158d28c9c032be520ce3ba1d79112ee9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-hubspot test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-salesforce test report (commit [`cf2edd0915`](https://github.com/airbytehq/airbyte/pull/31446/commits/cf2edd09158d28c9c032be520ce3ba1d79112ee9)) - ✅

⏲️  Total pipeline duration: 116mn48s 

| Step                                                              | Result   |
|:------------------------------------------------------------------|:---------|
| Build source-salesforce docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                        | ✅       |
| Integration tests                                                 | ✅       |
| Acceptance tests                                                  | ✅       |
| Code format checks                                                | ✅       |
| Validate metadata for source-salesforce                           | ✅       |
| Connector version semver check                                    | ✅       |
| QA checks                                                         | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_sources_fix-expected-records/1697456431/cf2edd09158d28c9c032be520ce3ba1d79112ee9/source-salesforce/2.1.4/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:cf2edd09158d28c9c032be520ce3ba1d79112ee9)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-salesforce test
```

**Pull request merged**
