### PR TITLE
connector-templates: Cleanup connector generator

### PR DESCRIPTION
**Pull request by natikgadzhi**
## What

Follows up #36193 and actually removes singer from plopfile.

This commit cleans up connector generator, specifically:
- Removes java sources and destinations from plopfile
- Removes singer source from plopfile
- Removes generic and python (non-http) source from plopfile
- Cleans up documentation

## Next steps

Now that the cleanup is done, next step is to go into `airbyte-ci/connectors/pipelines/build/` and figure out how to account for `src` in templates in #35893.

### CODE REVIEW

**Review by postamar — COMMENTED** [review]
LGTM as far as I can understand.

**Review by alafanechere — APPROVED** [review]
Please make sure @marcosmarxm is aware of this change (mainly the renaming of `source-http-api` to `source-python`

**Review by marcosmarxm — APPROVED** [review]
It's more aligned with our current docs. Thanks @natikgadzhi

**Comment by natikgadzhi** [comment]
I think Graphite got this into master with the other one. Closing.

**Pull request closed without merging**
