### PR TITLE
add destinatin-s3-parquet-singer

### PR DESCRIPTION
**Pull request by blotouta2**
## What
Destination-s3 based on target-s3 singer

## How
Wrote a python library to connect with S3 and sync data in s3 buckets in parquet format.

## Recommended reading order
2. `*.python`

<details><summary> <strong> Destination-S3-Parquet-Singer </strong></summary>

</details>

### CODE REVIEW

**Comment by sherifnada** [comment]
@blotouta2 thanks for your contribution! Could you help me understand what features this offers over the existing S3 destination? (which provides parquet support)

**Comment by blotouta2** [comment]
@sherifnada S3 Destination is not working as a data parquet conversion for many sources so i decided to use  target-s3 singer parquet format.
https://github.com/airbytehq/airbyte/issues/4608
I tried to solve but was not be able to fix issue in current S3 Destination because i don't know AVRO much.

**Comment by Dharminder315** [comment]
How to increase to Android phone RAM and Memory

**Comment by Dharminder315** [comment]
My phone is very slow and internet connection very week perform

**Comment by sherifnada** [comment]
@blotouta2 I see, thanks for the context! We would love to improve current S3 destination as using the Singer destination is not favorable for licensing reasons (GPL licensed). I totally understand if you are not interested in doing that since you already built out this awesome destination :) So my recommendation for a path forward for you would be: 
1. If you want to use this destination in your Airbyte instance, is to add it as a custom connector from the UI and use it in your workflows. 
2. If you want to share it with the community, maintain a fork of Airbyte (or put this module in its own repo) and publish the Docker image to Dockerhub and we'd be more than happy to share this with the community via the docs or slack
How does this sound to you?

**Comment by blotouta2** [comment]
sure @sherifnada

**Comment by sherifnada** [comment]
great - I'll close this PR then

**Pull request closed without merging**
