### PR TITLE
chore(source-prestashop): Upgrade to CDK 3.4 and base image 2.0

### PR DESCRIPTION
**Pull request by natikgadzhi**
## What

Update source-prestashop to CDK 3.4 so it can run on Python 3.11.

## How

- Bump CDK 
- Bump pytest
- Bump base image

## Can this PR be safely reverted and rolled back?
- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by natikgadzhi** [comment]
Oh, very interesting, looks like we don't have an account for Prestashop to test on. huh.

**Comment by natikgadzhi** [comment]
@alafanechere and @clnoll, what should be a good next step here? Prestashop is popular, but we don't have test accounts to do acceptanceTests.

I will attempt regression tests now, see if I'm lucky, and if so — publish. But what's the general idea here?

**Comment by clnoll** [comment]
@natikgadzhi if the connector is popular enough I imagine we want to create a sandbox account. Maybe that's something that the API connectors team has an opinion on?

If you do create a Sandbox account, you'll want to store the credentials in GSM, create a connection in [this workspace](https://cloud.airbyte.com/workspaces/112412bb-78aa-4ca6-aace-ae0b83be2215/connections), and then update the metadata.yaml with an entry for acceptance tests that includes location of the credentials in GSM, and an entry for live tests which includes the connection ID. (Side note: the documentation needs to be updated with some of this info, I'll take care of that.)

Does that answer your question?

**Comment by natikgadzhi** [comment]
Yep, it does! 

I'm always on the lookout for ways to speed up connector development, especially in cases when we're blocked by access.

Given the obfuscator is merged, @clnoll, is it reasonable to:
1. Post a new GH check status on the target PR when live regression tests are performed from the GH Action Dispatch? 
2. Make the reports public, given no data is leaked in obfuscated reports?

**Comment by clnoll** [comment]
> Given the obfuscator is merged, @clnoll, is it reasonable to:
> 
> 1. Post a new GH check status on the target PR when live regression tests are performed from the GH Action Dispatch?
> 2. Make the reports public, given no data is leaked in obfuscated reports?

@natikgadzhi regarding 1, we should already be doing that. If you aren't seeing it here it could be because a new commit was pushed and the regression tests weren't run on it, or there's a bug :).

Regarding 2, I think we'd want to understand why the reports are private - keeping in mind that they were private before regression tests were even added. And re making regression tests public, I _think_ that could be okay but would personally want someone to do a once-over of the report to see what's being surfaced (including in error scenarios) and discuss that info with Tobias first.

**Pull request closed without merging**
