### PR TITLE
Fix builds: Github, Amplitude, Jira, Zendesk-support

### PR DESCRIPTION
**Pull request by davydov-d**
- Migrate to python based image
- Update expected records

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-amplitude test report (commit [`f763047b2f`](https://github.com/airbytehq/airbyte/pull/31702/commits/f763047b2f99dfff117e81c7c63c62382957fcdf)) - ❌

⏲️  Total pipeline duration: 09mn07s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build source-amplitude docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                      | ✅       |
| Integration tests                                               | ✅       |
| Acceptance tests                                                | ❌       |
| Check our base image is used                                    | ✅       |
| Code format checks                                              | ✅       |
| Validate metadata for source-amplitude                          | ✅       |
| Connector version semver check                                  | ✅       |
| Connector version increment check                               | ✅       |
| QA checks                                                       | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698069747/f763047b2f99dfff117e81c7c63c62382957fcdf/source-amplitude/0.3.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f763047b2f99dfff117e81c7c63c62382957fcdf)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amplitude test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-stripe test report (commit [`f763047b2f`](https://github.com/airbytehq/airbyte/pull/31702/commits/f763047b2f99dfff117e81c7c63c62382957fcdf)) - ❌

⏲️  Total pipeline duration: 09mn22s 

| Step                                                         | Result   |
|:-------------------------------------------------------------|:---------|
| Build source-stripe docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                   | ✅       |
| Acceptance tests                                             | ❌       |
| Check our base image is used                                 | ✅       |
| Code format checks                                           | ✅       |
| Validate metadata for source-stripe                          | ✅       |
| Connector version semver check                               | ✅       |
| Connector version increment check                            | ✅       |
| QA checks                                                    | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698069747/f763047b2f99dfff117e81c7c63c62382957fcdf/source-stripe/4.4.2/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:f763047b2f99dfff117e81c7c63c62382957fcdf)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-stripe test
```

**Review by bazarnov — APPROVED** [review]

**Comment by airbyte-oss-build-runner** [comment]
##  source-zendesk-support test report (commit [`88eb492c11`](https://github.com/airbytehq/airbyte/pull/31702/commits/88eb492c11c9a8c7998b60edbfa4a5537d945935)) - ✅

⏲️  Total pipeline duration: 02mn08s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build source-zendesk-support docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                            | ✅       |
| Acceptance tests                                                      | ✅       |
| Check our base image is used                                          | ✅       |
| Code format checks                                                    | ✅       |
| Validate metadata for source-zendesk-support                          | ✅       |
| Connector version semver check                                        | ✅       |
| Connector version increment check                                     | ✅       |
| QA checks                                                             | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698070750/88eb492c11c9a8c7998b60edbfa4a5537d945935/source-zendesk-support/2.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:88eb492c11c9a8c7998b60edbfa4a5537d945935)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-support test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-amplitude test report (commit [`88eb492c11`](https://github.com/airbytehq/airbyte/pull/31702/commits/88eb492c11c9a8c7998b60edbfa4a5537d945935)) - ❌

⏲️  Total pipeline duration: 02mn27s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build source-amplitude docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                      | ✅       |
| Integration tests                                               | ✅       |
| Acceptance tests                                                | ❌       |
| Check our base image is used                                    | ✅       |
| Code format checks                                              | ✅       |
| Validate metadata for source-amplitude                          | ✅       |
| Connector version semver check                                  | ✅       |
| Connector version increment check                               | ✅       |
| QA checks                                                       | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698070750/88eb492c11c9a8c7998b60edbfa4a5537d945935/source-amplitude/0.3.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:88eb492c11c9a8c7998b60edbfa4a5537d945935)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amplitude test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-github test report (commit [`88eb492c11`](https://github.com/airbytehq/airbyte/pull/31702/commits/88eb492c11c9a8c7998b60edbfa4a5537d945935)) - ❌

⏲️  Total pipeline duration: 02mn48s 

| Step                                                         | Result   |
|:-------------------------------------------------------------|:---------|
| Build source-github docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                   | ✅       |
| Acceptance tests                                             | ❌       |
| Check our base image is used                                 | ✅       |
| Code format checks                                           | ✅       |
| Validate metadata for source-github                          | ✅       |
| Connector version semver check                               | ✅       |
| Connector version increment check                            | ✅       |
| QA checks                                                    | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698070750/88eb492c11c9a8c7998b60edbfa4a5537d945935/source-github/1.5.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:88eb492c11c9a8c7998b60edbfa4a5537d945935)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`88eb492c11`](https://github.com/airbytehq/airbyte/pull/31702/commits/88eb492c11c9a8c7998b60edbfa4a5537d945935)) - ❌

⏲️  Total pipeline duration: 05mn27s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Build source-jira docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                 | ✅       |
| Integration tests                                          | ✅       |
| Acceptance tests                                           | ❌       |
| Check our base image is used                               | ✅       |
| Code format checks                                         | ✅       |
| Validate metadata for source-jira                          | ✅       |
| Connector version semver check                             | ✅       |
| Connector version increment check                          | ✅       |
| QA checks                                                  | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698070750/88eb492c11c9a8c7998b60edbfa4a5537d945935/source-jira/0.10.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:88eb492c11c9a8c7998b60edbfa4a5537d945935)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-github test report (commit [`0bc984c536`](https://github.com/airbytehq/airbyte/pull/31702/commits/0bc984c5365ea11cbecd4b63540089f61385a4eb)) - ❌

⏲️  Total pipeline duration: 07mn13s 

| Step                                                         | Result   |
|:-------------------------------------------------------------|:---------|
| Build source-github docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                   | ✅       |
| Acceptance tests                                             | ❌       |
| Check our base image is used                                 | ✅       |
| Code format checks                                           | ✅       |
| Validate metadata for source-github                          | ✅       |
| Connector version semver check                               | ✅       |
| Connector version increment check                            | ✅       |
| QA checks                                                    | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698143941/0bc984c5365ea11cbecd4b63540089f61385a4eb/source-github/1.5.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:0bc984c5365ea11cbecd4b63540089f61385a4eb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-zendesk-support test report (commit [`0bc984c536`](https://github.com/airbytehq/airbyte/pull/31702/commits/0bc984c5365ea11cbecd4b63540089f61385a4eb)) - ✅

⏲️  Total pipeline duration: 08mn18s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build source-zendesk-support docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                            | ✅       |
| Acceptance tests                                                      | ✅       |
| Check our base image is used                                          | ✅       |
| Code format checks                                                    | ✅       |
| Validate metadata for source-zendesk-support                          | ✅       |
| Connector version semver check                                        | ✅       |
| Connector version increment check                                     | ✅       |
| QA checks                                                             | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698143941/0bc984c5365ea11cbecd4b63540089f61385a4eb/source-zendesk-support/2.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:0bc984c5365ea11cbecd4b63540089f61385a4eb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-support test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`0bc984c536`](https://github.com/airbytehq/airbyte/pull/31702/commits/0bc984c5365ea11cbecd4b63540089f61385a4eb)) - ❌

⏲️  Total pipeline duration: 09mn08s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Build source-jira docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                 | ✅       |
| Integration tests                                          | ✅       |
| Acceptance tests                                           | ❌       |
| Check our base image is used                               | ✅       |
| Code format checks                                         | ✅       |
| Validate metadata for source-jira                          | ✅       |
| Connector version semver check                             | ✅       |
| Connector version increment check                          | ✅       |
| QA checks                                                  | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698143941/0bc984c5365ea11cbecd4b63540089f61385a4eb/source-jira/0.10.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:0bc984c5365ea11cbecd4b63540089f61385a4eb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-amplitude test report (commit [`0bc984c536`](https://github.com/airbytehq/airbyte/pull/31702/commits/0bc984c5365ea11cbecd4b63540089f61385a4eb)) - ❌

⏲️  Total pipeline duration: 15mn17s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build source-amplitude docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                      | ✅       |
| Integration tests                                               | ✅       |
| Acceptance tests                                                | ❌       |
| Check our base image is used                                    | ✅       |
| Code format checks                                              | ✅       |
| Validate metadata for source-amplitude                          | ✅       |
| Connector version semver check                                  | ✅       |
| Connector version increment check                               | ✅       |
| QA checks                                                       | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698143941/0bc984c5365ea11cbecd4b63540089f61385a4eb/source-amplitude/0.3.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:0bc984c5365ea11cbecd4b63540089f61385a4eb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amplitude test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-zendesk-support test report (commit [`e6e634d26d`](https://github.com/airbytehq/airbyte/pull/31702/commits/e6e634d26d3b3cbd68c862416d156e8d04670c8f)) - ✅

⏲️  Total pipeline duration: 02mn09s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build source-zendesk-support docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                            | ✅       |
| Acceptance tests                                                      | ✅       |
| Check our base image is used                                          | ✅       |
| Code format checks                                                    | ✅       |
| Validate metadata for source-zendesk-support                          | ✅       |
| Connector version semver check                                        | ✅       |
| Connector version increment check                                     | ✅       |
| QA checks                                                             | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698147619/e6e634d26d3b3cbd68c862416d156e8d04670c8f/source-zendesk-support/2.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e6e634d26d3b3cbd68c862416d156e8d04670c8f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-support test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-github test report (commit [`e6e634d26d`](https://github.com/airbytehq/airbyte/pull/31702/commits/e6e634d26d3b3cbd68c862416d156e8d04670c8f)) - ✅

⏲️  Total pipeline duration: 03mn28s 

| Step                                                         | Result   |
|:-------------------------------------------------------------|:---------|
| Build source-github docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                   | ✅       |
| Acceptance tests                                             | ✅       |
| Check our base image is used                                 | ✅       |
| Code format checks                                           | ✅       |
| Validate metadata for source-github                          | ✅       |
| Connector version semver check                               | ✅       |
| Connector version increment check                            | ✅       |
| QA checks                                                    | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698147619/e6e634d26d3b3cbd68c862416d156e8d04670c8f/source-github/1.5.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e6e634d26d3b3cbd68c862416d156e8d04670c8f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`e6e634d26d`](https://github.com/airbytehq/airbyte/pull/31702/commits/e6e634d26d3b3cbd68c862416d156e8d04670c8f)) - ✅

⏲️  Total pipeline duration: 05mn16s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Build source-jira docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                 | ✅       |
| Integration tests                                          | ✅       |
| Acceptance tests                                           | ✅       |
| Check our base image is used                               | ✅       |
| Code format checks                                         | ✅       |
| Validate metadata for source-jira                          | ✅       |
| Connector version semver check                             | ✅       |
| Connector version increment check                          | ✅       |
| QA checks                                                  | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698147619/e6e634d26d3b3cbd68c862416d156e8d04670c8f/source-jira/0.10.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e6e634d26d3b3cbd68c862416d156e8d04670c8f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-amplitude test report (commit [`e6e634d26d`](https://github.com/airbytehq/airbyte/pull/31702/commits/e6e634d26d3b3cbd68c862416d156e8d04670c8f)) - ❌

⏲️  Total pipeline duration: 09mn18s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build source-amplitude docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                      | ✅       |
| Integration tests                                               | ✅       |
| Acceptance tests                                                | ❌       |
| Check our base image is used                                    | ✅       |
| Code format checks                                              | ✅       |
| Validate metadata for source-amplitude                          | ✅       |
| Connector version semver check                                  | ✅       |
| Connector version increment check                               | ✅       |
| QA checks                                                       | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698147619/e6e634d26d3b3cbd68c862416d156e8d04670c8f/source-amplitude/0.3.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e6e634d26d3b3cbd68c862416d156e8d04670c8f)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amplitude test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-amplitude test report (commit [`ea5708af84`](https://github.com/airbytehq/airbyte/pull/31702/commits/ea5708af84d8d433422a707096b84dc74b8f40cb)) - ✅

⏲️  Total pipeline duration: 03mn44s 

| Step                                                            | Result   |
|:----------------------------------------------------------------|:---------|
| Build source-amplitude docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                      | ✅       |
| Integration tests                                               | ✅       |
| Acceptance tests                                                | ✅       |
| Check our base image is used                                    | ✅       |
| Code format checks                                              | ✅       |
| Validate metadata for source-amplitude                          | ✅       |
| Connector version semver check                                  | ✅       |
| Connector version increment check                               | ✅       |
| QA checks                                                       | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698148791/ea5708af84d8d433422a707096b84dc74b8f40cb/source-amplitude/0.3.6/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ea5708af84d8d433422a707096b84dc74b8f40cb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-amplitude test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-zendesk-support test report (commit [`ea5708af84`](https://github.com/airbytehq/airbyte/pull/31702/commits/ea5708af84d8d433422a707096b84dc74b8f40cb)) - ✅

⏲️  Total pipeline duration: 04mn52s 

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Build source-zendesk-support docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                            | ✅       |
| Acceptance tests                                                      | ✅       |
| Check our base image is used                                          | ✅       |
| Code format checks                                                    | ✅       |
| Validate metadata for source-zendesk-support                          | ✅       |
| Connector version semver check                                        | ✅       |
| Connector version increment check                                     | ✅       |
| QA checks                                                             | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698148791/ea5708af84d8d433422a707096b84dc74b8f40cb/source-zendesk-support/2.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ea5708af84d8d433422a707096b84dc74b8f40cb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-zendesk-support test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`ea5708af84`](https://github.com/airbytehq/airbyte/pull/31702/commits/ea5708af84d8d433422a707096b84dc74b8f40cb)) - ✅

⏲️  Total pipeline duration: 05mn20s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Build source-jira docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                 | ✅       |
| Integration tests                                          | ✅       |
| Acceptance tests                                           | ✅       |
| Check our base image is used                               | ✅       |
| Code format checks                                         | ✅       |
| Validate metadata for source-jira                          | ✅       |
| Connector version semver check                             | ✅       |
| Connector version increment check                          | ✅       |
| QA checks                                                  | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698148791/ea5708af84d8d433422a707096b84dc74b8f40cb/source-jira/0.10.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ea5708af84d8d433422a707096b84dc74b8f40cb)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-github test report (commit [`559a89e267`](https://github.com/airbytehq/airbyte/pull/31702/commits/559a89e267139ded541a61564e64e059c272b84a)) - ✅

⏲️  Total pipeline duration: 03mn32s 

| Step                                                         | Result   |
|:-------------------------------------------------------------|:---------|
| Build source-github docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                   | ✅       |
| Acceptance tests                                             | ✅       |
| Check our base image is used                                 | ✅       |
| Code format checks                                           | ✅       |
| Validate metadata for source-github                          | ✅       |
| Connector version semver check                               | ✅       |
| Connector version increment check                            | ✅       |
| QA checks                                                    | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698153474/559a89e267139ded541a61564e64e059c272b84a/source-github/1.5.3/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:559a89e267139ded541a61564e64e059c272b84a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-github test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-jira test report (commit [`559a89e267`](https://github.com/airbytehq/airbyte/pull/31702/commits/559a89e267139ded541a61564e64e059c272b84a)) - ✅

⏲️  Total pipeline duration: 05mn34s 

| Step                                                       | Result   |
|:-----------------------------------------------------------|:---------|
| Build source-jira docker image for platform(s) linux/amd64 | ✅       |
| Unit tests                                                 | ✅       |
| Integration tests                                          | ✅       |
| Acceptance tests                                           | ✅       |
| Check our base image is used                               | ✅       |
| Code format checks                                         | ✅       |
| Validate metadata for source-jira                          | ✅       |
| Connector version semver check                             | ✅       |
| Connector version increment check                          | ✅       |
| QA checks                                                  | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_health-migrate-to-base-image/1698153474/559a89e267139ded541a61564e64e059c272b84a/source-jira/0.10.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:559a89e267139ded541a61564e64e059c272b84a)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-jira test
```

**Pull request merged**
