### PR TITLE
🐛 Source Google Ads: Fix wrong schema for `ad_group_criterion.topic.path` and shifted `Campaigns` stream to non-managers stream list

### PR DESCRIPTION
**Pull request by lazebnyi**
## What
1. https://github.com/airbytehq/oncall/issues/368 - wrong schema for ad_group_criterion.topic.path

The field `ad_group_criterion.topic.path` is in the `display_topics_performance_report` stream. Looks like we're getting an array, but it's defined in the schema as a string.

2. https://github.com/airbytehq/oncall/issues/361 - REQUESTED_METRICS_FOR_MANAGER error 

Stream with metrics, can only be requested against client account, not manager account. 

## How
1. Updated `ad_group_criterion.topic.path` is in the `display_topics_performance_report` schema. 2. 

2. Shifted `Campaigns` to non-managers stream list, because stream have `metrics.clicks`, `metrics.cost_micros` and others. 

## Pre-merge Checklist
<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
</details>

### CODE REVIEW

**Review by girarda — APPROVED** [review]
lgtm. @lazebnyi do you know if the path is always an array or if it's a Union[string ,array]?

**Comment by lazebnyi** [comment]
hey @girarda 

added fix for https://github.com/airbytehq/oncall/issues/361

according to [google doc](https://developers.google.com/google-ads/api/fields/v11/ad_group_criterion) below and definition of [repeated](https://developers.google.com/google-ads/api/fields/v11/overview)

image

**Review by girarda — APPROVED** [review]

**Pull request merged**
