### PR TITLE
🎉  Source Amplitude: label as `generally_available` in UI

### LINKED ISSUE #13597: 🎉 Source Amplitude: label as `generally_available` in UI

### LINKED ISSUE #13598: 🐛 Source Amplitude: correct `Annotations` schema to avoid JSON Validator errors
Need to switch back to `date-time` in `annotations` schema to avoid JSON validator errors, since the `date` column actually holds the `date-time` string, not `date`.

### PR DESCRIPTION
**Pull request by bazarnov**
## What
Resolving: https://github.com/airbytehq/airbyte/issues/13598

## How
- changed the `releaseStage` to `generally_available` for UI

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [X] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [X] Code reviews completed
- [X] Documentation updated
    - [X] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [X] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

### CODE REVIEW

**Review by lazebnyi — APPROVED** [review]

**Comment by sherifnada** [comment]
@bazarnov how come this passed SATs, do you know? ideally a wrong `format` should fail there

**Comment by bazarnov** [comment]
> @bazarnov how come this passed SATs, do you know? ideally a wrong `format` should fail there

Good question, I'll dive into it

**Comment by bazarnov** [comment]
> > @bazarnov how come this passed SATs, do you know? ideally a wrong `format` should fail there
> 
> Good question, I'll dive into it

The answer could be very simple, the `CustomFormatChecker(FormatChecker)` seems like doesn't check for `date` format, but for `date-time` only...
 
Check this code part for more:
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/asserts.py#L34-L39

**Pull request merged**
