### PR TITLE
destination-langchain: fix build

### PR DESCRIPTION
**Pull request by alafanechere**
## What
The connector build was failing with `.buildkit_qemu_emulator: /bin/sh: Invalid ELF image for this architecture`
We believe this is due to an unusual alpine image being used as a base image.

## How
Use python:3.9-slim as the base image

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  destination-langchain test report (commit [`93ea60a5af`](https://github.com/airbytehq/airbyte/pull/28509/commits/93ea60a5af0d390473cc4459b2504b7111124f97)) - ❌

⏲️  Total pipeline duration: 05mn07s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-langchain/metadata.yaml | ✅        |
| Connector version semver check                                               | ✅        |
| Connector version increment check                                            | ❌        |
| QA checks                                                                    | ✅        |
| Code format checks                                                           | ✅        |
| Connector package install                                                    | ✅        |
| Build destination-langchain docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                   | ✅        |
| Integration tests                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/augustin_destination-langchain_fix-build/1689849418/93ea60a5af0d390473cc4459b2504b7111124f97/destination-langchain/0.0.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-langchain test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-langchain test report (commit [`f816cbb49b`](https://github.com/airbytehq/airbyte/pull/28509/commits/f816cbb49b43fcd1d9ec2b773892523eaea3b242)) - ❌

⏲️  Total pipeline duration: 02mn13s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-langchain/metadata.yaml | ✅        |
| Connector version semver check                                               | ✅        |
| Connector version increment check                                            | ❌        |
| QA checks                                                                    | ✅        |
| Code format checks                                                           | ✅        |
| Connector package install                                                    | ✅        |
| Build destination-langchain docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/augustin_destination-langchain_fix-build/1689850199/f816cbb49b43fcd1d9ec2b773892523eaea3b242/destination-langchain/0.0.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-langchain test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-langchain test report (commit [`6c6fe67e44`](https://github.com/airbytehq/airbyte/pull/28509/commits/6c6fe67e442b551b9d9e2a4f43d1eee834148751)) - ❌

⏲️  Total pipeline duration: 01mn06s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-langchain/metadata.yaml | ✅        |
| Connector version semver check                                               | ✅        |
| Connector version increment check                                            | ❌        |
| QA checks                                                                    | ✅        |
| Code format checks                                                           | ✅        |
| Connector package install                                                    | ✅        |
| Build destination-langchain docker image for platform linux/x86_64           | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/augustin_destination-langchain_fix-build/1689850413/6c6fe67e442b551b9d9e2a4f43d1eee834148751/destination-langchain/0.0.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-langchain test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-langchain test report (commit [`e5b41c126b`](https://github.com/airbytehq/airbyte/pull/28509/commits/e5b41c126be42389e22a2561ae7c351a25eec03d)) - ❌

⏲️  Total pipeline duration: 02mn02s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-langchain/metadata.yaml | ✅        |
| Connector version semver check                                               | ✅        |
| Connector version increment check                                            | ❌        |
| QA checks                                                                    | ✅        |
| Code format checks                                                           | ✅        |
| Connector package install                                                    | ✅        |
| Build destination-langchain docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                   | ✅        |
| Integration tests                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/augustin_destination-langchain_fix-build/1689850555/e5b41c126be42389e22a2561ae7c351a25eec03d/destination-langchain/0.0.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-langchain test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-langchain test report (commit [`e381c4b3ef`](https://github.com/airbytehq/airbyte/pull/28509/commits/e381c4b3efed7fa1675a243bac15d731ccdae0d9)) - ✅

⏲️  Total pipeline duration: 12.41s 

| Step                                                                         | Result   |
|:-----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-langchain/metadata.yaml | ✅        |
| Connector version semver check                                               | ✅        |
| Connector version increment check                                            | ✅        |
| QA checks                                                                    | ✅        |
| Code format checks                                                           | ✅        |
| Connector package install                                                    | ✅        |
| Build destination-langchain docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                   | ✅        |
| Integration tests                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/augustin_destination-langchain_fix-build/1689850753/e381c4b3efed7fa1675a243bac15d731ccdae0d9/destination-langchain/0.0.3/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-langchain test
```

**Review by flash1293 — APPROVED** [review]
LGTM, thanks for fixing this!

**Pull request merged**
