### PR TITLE
Fix CDK `source-db` integration-tests

### PR DESCRIPTION
**Pull request by aaronsteers**
This fixes a couple issues found in the integration tests of the db-sources CDK module.

```console
./gradlew :airbyte-cdk:java:airbyte-cdk:db-sources:integrationTestJava
```

1. The `db-sources` integration tests rely on `acceptance-test-harness`, which has now been declared as an integration test dependency. (Previously was only a test fixture dependency.)
2. The `JdbcSourceSourceAcceptanceTest` is disabled now, due to relying on `airbyte-docker`, and `source-jdbc`, both of which are phased out. We probably should consider deleting this altogether if it is not needed. For now, we want to prioritize getting tests runing successfully.

### CODE REVIEW

**Review by postamar — CHANGES_REQUESTED** [review]
I didn't realize source-jdbc was dead. Indeed it is. In that case, this test should be removed completely, and db-sources should not have the integrations test plugin applied to it.

**Comment by aaronsteers** [comment]
@postmar - Okay, I'll proceed with that change then...

**Comment by aaronsteers** [comment]
@postamar - I think this is ready to merge. I basically just undid the changes.

Since it doesn't change the runtime for the CDK at all, I don't think it merits a release.

**Review by postamar — APPROVED** [review]
Completely agree!

**Pull request merged**
