### PR TITLE
✨Source SurveyCTO: Migrate Python CDK to Low-code CDK

### LINKED ISSUE #30874: SurveyCTO
https://docs.airbyte.com/integrations/sources/statuspage

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
*Migrating Source SurveyCTO to Low-Code CDK*
Closes airbytehq/airbyte-internal-issues#2140

## How
*Developed using (Configuration Based Source) low-code CDK*

## Recommended reading order
1. `spec.yaml`
2. `manifest.yaml`
3. `schemas/*`

## Tests

<details open><summary><strong>Integration & Acceptance</strong></summary>
Full Test Results

</details>

## 🚨 User Impact 🚨
- No breaking changes, migration to low-code
<details><summary><strong>Migrate Connector: Source SurveyCTO</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [x] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

</details>

### CODE REVIEW

**Comment by btkcodedev** [comment]
Test result (Full refresh): Full pass state

image

**Comment by btkcodedev** [comment]
Ps: I've included the incremental sync base, but confused regarding the format,
Currently, the builder only shows support for 4 formats:
image

But the cursor has format of Oct 5, 2023 6:16:47 PM which is %b %d, %Y %I:%M:%S %p
I am not sure whether low-code supports that format, 
It would be great if reviewers could comment on what to do in this 😄

**Comment by btkcodedev** [comment]
Ping via slack for config creds

**Comment by marcosmarxm** [comment]
Sorry the long delay to get into your contribution. Probably this week or next one the team will start the process. Are you able to run the tests in your local setup? It can speed up a lot the process if you share the integration tests results

**Comment by marcosmarxm** [comment]
Hello @btkcodedev thanks for the contribution but the SurveyCTO uses dynamic schema and this isn't supported yet by the low-code framework. I'm closing the contribution for now.

**Comment by btkcodedev** [comment]
Oh, Thanks :)

**Pull request closed without merging**
