### PR TITLE
🎉 Destination MSSQL: added custom JDBC parameters support.

### PR DESCRIPTION
**Pull request by pcsoni89**
## What
Add support for MSSQL Destinations to take in a JDBC URL Params input to specify any additional JDBC parameters for the connection.

This is a follow up to https://github.com/airbytehq/airbyte/pull/10421
This is part of https://github.com/airbytehq/airbyte/issues/9501

## How
AbstractJdbcDestination can already handle jdbc parameters via the jdbc_url_params field, but the MSSQLDestination spec does not specify that field. We should update the spec to support additional jdbc parameters for MSSQL destination

## Recommended reading order
1.AbstractJdbcDestination.java
2.MSSQLDestination.java

## 🚨 User Impact 🚨
For existing destination oracle connections, a new parameter i.e. JDBC URL Params will be displayed.It is an optional field and accepts key=value data. There won't be any impact on existing operations.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by alexandertsukanov** [comment]
@pcsoni89 I don't see changes on the UI specification regarding additional JDBC params, does this parameter exist?

**Comment by alexandertsukanov** [comment]
@pcsoni89 I don't see changes on the UI specification regarding additional JDBC params, does this parameter exist?

**Comment by alexandertsukanov** [comment]
@pcsoni89 cannot approve until the next things won't be done:
1. Bumping of the version
2. Update the `changelog.md`
3. Tests will successfully pass 

Thanks.

**Comment by pcsoni89** [comment]
> @pcsoni89 cannot approve until the next things won't be done:
> 
> 1. Bumping of the version
> 2. Update the `changelog.md`
> 3. Tests will successfully pass
> 
> Thanks.

Added bump files and changelog.
Waiting for integration test issue to be resolved (another issue going on for integration).

**Comment by alexandertsukanov** [comment]
> > @alexandertsukanov do you approve now that @pcsoni89 has made the changes?
> 
> @alafanechere Looks like the version in Dockerfile is still not bumped here

Bumped looks like this could be published and merged. But I want to re-run the tests again.

**Review by alexandr-shegeda — APPROVED** [review]

**Comment by grubberr** [comment]
/publish connector=connectors/destination-mssql-strict-encrypt

**Comment by alexandertsukanov** [comment]
/publish connector=connectors/destination-mssql-strict-encrypt

**Pull request merged**
