### PR TITLE
Source GitHub: #970 handle 502 Bad Gateway

### PR DESCRIPTION
**Pull request by roman-yermilov-gl**
## What
*Handle 502 Bad Gateway with proper message*

## How
*If there is an 502 error then we try to do few more delayed requests and finally (if not succeeded) provide a client with proper log message*

## Recommended reading order
1. `x.java`
2. `y.python`

### CODE REVIEW

**Review by lazebnyi — COMMENTED** [review]
Need add record to change log

**Review by bazarnov — APPROVED** [review]

**Comment by roman-yermilov-gl** [comment]
> Need add record to change log

Done. I didn't do it before since I was waiting for another PR in which version also bumped to 0.3.12

**Review by lazebnyi — APPROVED** [review]

**Pull request merged**
