### PR TITLE
Destination Bigquery: 1s1t: handle raw name collisions

### LINKED ISSUE #27798: 1s1t CatalogParser should handle raw table name collisions

### PR DESCRIPTION
**Pull request by edgao**
closes https://github.com/airbytehq/airbyte/issues/27798

Slightly different logic after discussing with @jbfbell . Instead of just using a double-underscore, we're now generating a name based on each individual stream. This is to make the raw tablename unambiguous.

best to review commit-by-commit:
* https://github.com/airbytehq/airbyte/commit/69cd76389061526ad257cd599c08037abc4cf6dc - move inner classes to their own files
* https://github.com/airbytehq/airbyte/commit/2d3b86aa5b0ac5e37001a042f23f6bb8b3a60f6a - runtime code change
* https://github.com/airbytehq/airbyte/commit/8154cb60b13a5d522c3d3db566e36a92e794c545 - update tests with new tablenames

### CODE REVIEW

**Review by jbfbell — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`8154cb60b1`](https://github.com/airbytehq/airbyte/pull/28366/commits/8154cb60b13a5d522c3d3db566e36a92e794c545)) - ❌

⏲️  Total pipeline duration: 36mn22s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ❌        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery:integrationTest | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_1s1t_raw_collisions/1689617276/8154cb60b13a5d522c3d3db566e36a92e794c545/destination-bigquery/1.5.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery-denormalized test report (commit [`8154cb60b1`](https://github.com/airbytehq/airbyte/pull/28366/commits/8154cb60b13a5d522c3d3db566e36a92e794c545)) - ❌

⏲️  Total pipeline duration: 22mn05s 

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ❌        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-bigquery-denormalized docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery-denormalized:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_1s1t_raw_collisions/1689617276/8154cb60b13a5d522c3d3db566e36a92e794c545/destination-bigquery-denormalized/1.5.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery test report (commit [`bcc7582297`](https://github.com/airbytehq/airbyte/pull/28366/commits/bcc758229763537a8ed9d170393e0029a9ef39b9)) - ❌

⏲️  Total pipeline duration: 36mn26s 

| Step                                                                            | Result   |
|:--------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery/metadata.yaml     | ✅        |
| Connector version semver check                                                  | ❌        |
| QA checks                                                                       | ✅        |
| Build connector tar                                                             | ✅        |
| Build destination-bigquery docker image for platform linux/x86_64               | ✅        |
| Build airbyte/normalization:dev                                                 | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_1s1t_raw_collisions/1689620912/bcc758229763537a8ed9d170393e0029a9ef39b9/destination-bigquery/1.5.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery test
```

**Comment by octavia-squidington-iii** [comment]
##  destination-bigquery-denormalized test report (commit [`bcc7582297`](https://github.com/airbytehq/airbyte/pull/28366/commits/bcc758229763537a8ed9d170393e0029a9ef39b9)) - ❌

⏲️  Total pipeline duration: 22mn08s 

| Step                                                                                         | Result   |
|:---------------------------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/destination-bigquery-denormalized/metadata.yaml     | ✅        |
| Connector version semver check                                                               | ❌        |
| QA checks                                                                                    | ✅        |
| Build connector tar                                                                          | ✅        |
| Build destination-bigquery-denormalized docker image for platform linux/x86_64               | ✅        |
| ./gradlew :airbyte-integrations:connectors:destination-bigquery-denormalized:integrationTest | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/edgao_1s1t_raw_collisions/1689620912/bcc758229763537a8ed9d170393e0029a9ef39b9/destination-bigquery-denormalized/1.5.2/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=destination-bigquery-denormalized test
```

**Comment by octavia-approvington** [comment]
Approve this <br/> imagine the commander saying yes

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
