### PR TITLE
Source Recurly: Remove definition redundancy, schema redundancy, update to latest CDK and make compatibility with builder

### LINKED ISSUE #48479: 🐛Source-recurly: Stream Unique_coupons: SubstreamPartitionRouter's parent stream doesn't match any other stream
### Connector Name

source-recurly

### Connector Version

1.2.0

### What step the error happened?

Configuring a new connector

### Relevant information

Stream Unique_coupons: SubstreamPartitionRouter's parent stream doesn't match any other stream

### Contribute

- [x] Yes, I want to contribute

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
Closes https://github.com/airbytehq/airbyte/issues/48479
Fix for `Stream Unique_coupons: SubstreamPartitionRouter's parent stream doesn't match any other stream`

Cause:
Record filter:

> record_filter:
>    condition: "{{ record['coupon_type'] == 'bulk' }}"

Other problems:
1. The manifest had unwanted repetitions totalling 25000+ lines.
2. Two definitions were present for all streams
3. Dual Schema definitions
4. Non builder compatible

## How
1. Use refs for partition router and append the record_filter
2. Removed redundancy manually
3. Added another parent stream with record_filter for unique_coupons stream

### CODE REVIEW

**Comment by btkcodedev** [comment]
/bump-version type="minor" changelog="Remove definition and schema redundancy, update to latest CDK and make compatibility with builder"

**Review by erohmensing — APPROVED** [review]
These changes make sense to me, thanks for the clever fix with the separate parent stream. 

Does the `unique_coupon_codes` stream resolve as its own stream? If so, can you test it in builder and commit back the stream hash?

**Comment by btkcodedev** [comment]
Verified the stream via builder and updated hash :heavy_check_mark:

**Pull request merged**
