### PR TITLE
Fix schema transformation false warnings.

### LINKED ISSUE #7076: Source Facebook: print tons of WARN message during sync
## Enviroment
- **Airbyte version**:  Cloud
- **Source Connector and version**: Facebook Marketing 0.2.20
- **Destination Connector and version**: Snowflake ~
- **Severity**: Very Low / Low / Medium / **High** / Critical
- **Step where error happened**: Deploy / **Sync job** / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
The connection logs keep printing WARN rows about values not being in correct data type.
```
2021-10-14 19:30:51 WARN  '9' is not of type 'null', 'integer'
2021-10-14 19:30:51 WARN  '0' is not of type 'null', 'number'
2021-10-14 19:30:51 WARN  '0' is not of type 'null', 'integer'
2021-10-14 19:30:51 WARN  '0' is not of type 'null', 'number'
2021-10-14 19:30:51 WARN  '0' is not of type 'null', 'integer'
2021-10-14 19:30:51 WARN  '0' is not of type 'null', 'number'
2021-10-14 19:30:51 WARN  '0' is not of type 'null', 'integer'
2021-10-14 19:30:51 WARN  '0.01' is not of type 'null', 'number'
2021-10-14 19:30:51 WARN  '10' is not of type 'null', 'number'
2021-10-14 19:30:51 WARN  '10' is not of type 'null', 'number'
2021-10-14 19:30:51 WARN  '0' is not of type 'null', 'number'
2021-10-14 19:30:51 WARN  '100' is not of type 'null', 'number'
2021-10-14 19:30:51 WARN  '1' is not of type 'null', 'number'
2021-10-14 19:30:51 WARN  '1' is not of type 'null', 'number'
```

## Expected Behavior
*Tell us what should happen.*

## Logs

[logs-2857-0 (2).txt](https://github.com/airbytehq/airbyte/files/7354022/logs-2857-0.2.txt)

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

### PR DESCRIPTION
**Pull request by avida**
Resolves #7076

Change  object transformation procedure so now type casting taking place before type checking.

### CODE REVIEW

**Review by htrueman — APPROVED** [review]

**Comment by avida** [comment]
blocked by #7823

**Pull request merged**
