### PR TITLE
🐌 Optimize incremental normalization runtime with snowflake

### LINKED ISSUE #7775: Improve incremental normalization
## Tell us about the problem you're trying to solve
Clean-up incremental normalization (https://github.com/airbytehq/airbyte/issues/4286) that produces additional intermediate steps in dedupe history sync mode.

In order to run incremental normalization, especially on more complex pipelines involving SCD tables, some models need to be temporarily materialized in the destination. 
This is currently done in a temporary schema `_airbyte_<namespace name>.<stream name>_ab3` for the moment as views. 
This allows the next model in the pipeline that depends on them (the `<stream name>_scd` tables) to inspect the schema of the incremental batch and compare it with the schema of the previous run.

## Describe the solution you’d like
Once the incremental run is finished, these temporary views could be dropped as not to pollute destinations and confuse end-users.

Note that in Postgres destination cases, these temp views are actually materialized as tables instead and are being dropped once SCD tables are updated: https://github.com/airbytehq/airbyte/blob/109461b7223089d45dec18eca781651dfde35536/airbyte-integrations/bases/base-normalization/normalization/transform_catalog/stream_processor.py#L956

I realize now that dropping the intermediate tables is breaking the incremental aspects of the temp tables and the incremental clause for the `_ab3` tables should be rewritten to:
```
where _airbyte_emitted_at > (select max(_airbyte_emitted_at) from ref('<stream_name>_scd') )
```
instead of:
```
where _airbyte_emitted_at > (select max(_airbyte_emitted_at) from {{ this }})
```
So the intermediate tables can be materialized and safely dropped while processing only new incremental batch data for the `_scd` tables.

## Describe the alternative you’ve considered or used
Keep the temporary views in the "technical" namespace `_airbyte_`.

### LINKED ISSUE #7987: Destination Snowflake timed out during normalization step
## Enviroment
- **Airbyte version**:  0.30.20-alpha
- **OS Version / Instance**: GCP
- **Deployment**: Docker
- **Source Connector and version**: Facebook Marketing 0.2.25
- **Destination Connector and version**: Snowflake 0.3.16
- **Severity**: Very Low / Low / Medium / **High** / Critical
- **Step where error happened**: Deploy / **Sync job** / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Using Facebook Marketing to Snowflake now is causing the normalization failed with timeout. If I run the sync again, the timeout happens in the same place.
image

## Expected Behavior
*Tell us what should happen.*

## Logs
```
2021-11-13 23:37:42 INFO () LineGobbler(voidCall):65 -   250003: Failed to execute request: HTTPSConnectionPool(host='SNOWFLAKE_HOST', port=443): Max retries exceeded with url: /session/v1/login-request?request_id=id&databaseName=AIRBYTE_DATABASE&schemaName=AIRBYTE_SCHEMA&warehouse=AIRBYTE_WAREHOUSE&roleName=AIRBYTE_ROLE&request_guid=id (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fee380dc910>, 'Connection to SNOWFLAKE_HOST timed out. (connect timeout=60)'))
```
Complete logs: [logs-6596-0 (1).txt](https://github.com/airbytehq/airbyte/files/7540673/logs-6596-0.1.txt)

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

### LINKED ISSUE #8093: Facebook Marketing Normalization failed with dbt compilation errors
## Enviroment
- **Airbyte version**:  0.32.1-alpha
- **OS Version / Instance**: AWS
- **Deployment**: Kubernetes
- **Source Connector and version**: Facebook Marketing 0.2.25
- **Destination Connector and version**: Redshift 0.3.20
- **Severity**: Critical
- **Step where error happened**: Sync job

## Current Behavior

Normalization of Facebook marketing data fails with dbt compilation errors

## Expected Behavior

Normalization succeeds

## Logs

[logs-2319-2.txt](https://github.com/airbytehq/airbyte/files/7563346/logs-2319-2.txt)

https://airbytehq.slack.com/archives/C01MFR03D5W/p1637237080207900

### PR DESCRIPTION
**Pull request by ChristopheDuong**
## What
Closes https://github.com/airbytehq/airbyte/issues/7987#event-5633773717
Closes https://github.com/airbytehq/airbyte/issues/8093
Closes https://github.com/airbytehq/airbyte/issues/7775

## How
1. Thanks to a user on [slack](https://airbytehq.slack.com/archives/C01MFR03D5W/p1637084758142700), I was able to confirm that this PR solves the snowflake runtime issues by forcing the left join with an empty table
2. Adding comments of what the models are depending on as recommended in error messages from dbt as reported in #8093 
3. Removing post-hook to delete `_ab3` tables in Postgres since this breaks incremental (force a full refresh since the table would not exist anymore). So I renamed it `_tmp` instead.

## Recommended reading order
1. `airbyte-integrations/bases/base-normalization/normalization/transform_catalog/stream_processor.py
2. the rest

## 🚨 User Impact 🚨
Not a breaking change but Postgres users will see "pollution" from an intermediate table on "dedupe history" mode that needs to be persisted (in a different staging schema) for incremental to work because of a limitation between dbt/Postgres. These tables will be suffixed with `_stg`
On the other hand, the impact on the speed of this trade-off is difficult to measure without https://github.com/airbytehq/airbyte/issues/7741

### CODE REVIEW

**Review by sherifnada — APPROVED** [review]
@ChristopheDuong thanks for listing the user impact! very helpful :) will these tables be removed automatically or is it something we'll need to remove over time? (or should they just never be removed? if they shouldn't be removed would it make sense to call them something other than `_tmp` maybe `_metadata`?)

**Comment by ChristopheDuong** [comment]
> @ChristopheDuong thanks for listing the user impact! very helpful :) will these tables be removed automatically or is it something we'll need to remove over time? (or should they just never be removed? if they shouldn't be removed would it make sense to call them something other than `_tmp` maybe `_metadata`?)

it has to be kept with at least the row that has the maximum `emitted_at`. For the moment we keep the whole table though... `_metadata` is a lot more character to add to table names where we have limited number of... can you think of something with only 3 letters?

**Comment by sherifnada** [comment]
`_info` seems reasonable? or does it have to be 3?

**Comment by ChristopheDuong** [comment]
> `_info` seems reasonable? or does it have to be 3?

Yes, it has to be 3, unless we increase the number of reserved characters here: 
https://github.com/airbytehq/airbyte/blob/ad3b7be4c0250cc49c36f8300bbe54a6ecfd6368/airbyte-integrations/bases/base-normalization/normalization/transform_catalog/destination_name_transformer.py#L32

**Comment by ChristopheDuong** [comment]
Closes https://github.com/airbytehq/airbyte/issues/7775

**Pull request merged**
