### PR TITLE
🎉 New Source: `firestore`

### PR DESCRIPTION
**Pull request by julienfouilhe**
#3323

## What
This PR adds a `firestore` source.
Creating the PR to get feedback on what is already done: ie a working source connector.

I never use Python so the code might not be the best, but happy to improve the code where needed

## How
- It uses the firestore REST API directly to leverage the python cdk `HTTPStream` base class. https://firebase.google.com/docs/firestore/use-rest-api
- For incremental updates, it uses a custom cursor field that is expected to be a timestamp value. Users will need to create the cursor field and add it to their documents. They will also need to create an index for it.
- Since firestore is a schemaless database, it doesn't declare a schema.

## Recommended reading order
It's a classic source.

## 🚨 User Impact 🚨
No breaking changes

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

## Tests

<details><summary><strong>Unit</strong></summary>

*Put your unit tests output here.*
Not passing yet

</details>

<details><summary><strong>Integration</strong></summary>

*Put your integration tests output here.*
Not passing yet

</details>

<details><summary><strong>Acceptance</strong></summary>

*Put your acceptance tests output here.*

</details>

### CODE REVIEW

**Comment by harshithmullapudi** [comment]
Hey @julienfouilhe thanks for the contribution, do let us know once you think the PR is ready for review

**Comment by marcosmarxm** [comment]
@julienfouilhe if this is ready to review please move from draft to review.

**Comment by harshithmullapudi** [comment]
Hey thanks a lot for the update. I will review it soon.

**Comment by harshithmullapudi** [comment]
@sajarin are we assigning someone for this or should I review this?

**Comment by sajarin** [comment]
@harshithmullapudi sorry meant to reply earlier. Feel free to review it yourself, I'll assign some maintainers on the other PRs.

**Comment by marcosmarxm** [comment]
Hello :wave:, first thank you for this amazing contribution. 

We really appreciate the effort you've made to improve the project.
We ask you patience for the code review. Last month our team was focused on Hacktoberfest event and that probably left some PR without the proper feedback. And this week, due to the Thanksgiving US Holiday, most our team is out of office with their families. Another important piece of information why code won't be merge this week is: as a safety measure the core team has decided to freeze merging code to main branch to keep the release stable. Next week we'll return to you with the proper code review and update the status of your contribution.

If you have any questions feel free to send me a message in Slack!
Thanks!

**Comment by marcosmarxm** [comment]
Hello :wave::skin-tone-2: and thank you for your contribution!

Airbyte has instituted a code freeze between 19 and 30 December, to make sure there are no disruptions during the holidays. 
Because of this, reviewing and merging your contribution may take longer than usual. 
We apologize for the delay, but we want everyone to have a quiet and happy holiday.

If you have any questions or need further clarification, please don't hesitate to ping via Slack.

**Comment by BubbaJoe** [comment]
@marcosmarxm can someone review this already?

**Comment by BubbaJoe** [comment]
I think it would make sense to add a collection field, or a collection regex field to specify which collections should be copied.

**Comment by julienfouilhe** [comment]
@BubbaJoe you can select the collections you want to copy from Airbyte's UI already, or if you use Octavia like I do, from configuration files.

**Comment by BubbaJoe** [comment]
@julienfouilhe Yes, you are correct, my mistake.

**Comment by BubbaJoe** [comment]
Screenshot 2023-03-04 at 20 20 37

Looks like this field is optional but it fails when i dont use it.

**Review by evantahler — CHANGES_REQUESTED** [review]
Thank you for this contribution, and I'm sorry that it has taken us so long to get back to you.

To get this merged in a few things are still needed:
* Docs! Add some [here](https://github.com/airbytehq/airbyte/tree/master/docs/integrations/sources) following the format of the others.  Be sure to keep the headers matching and include a changelog
* Icon - Add a square SVG [here](https://github.com/airbytehq/airbyte/tree/master/airbyte-config/init/src/main/resources/icons) 
* Testing
  * You've got a lot of TODOs and fix-mes in your sample config and sample states.  We'll need those updated. 
  * Can you update `airbyte-integrations/connectors/source-firestore/acceptance-test-config.yml` to the new format.  Check out the [MongoDB example](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-mongodb-v2/acceptance-test-config.yml) 
  * Part of the Connector Acceptance Test is that we need to seed a database with some test records to produce `expected_records` that we use as a snapshot test.  We'll get our own firestore instance up-and-running with our own credentials, but can you share a guide for seeding your test sandbox so we can populate ours in the same way?

I'll run our `/test` command now, which does the same thing as `./gradlew :airbyte-integrations:connectors:source-firestore:test`.  You can see the errors that are happening on CI, most of which will be caused by the lack of test credentials to hit a seeded test database.

**Pull request closed without merging**
