### PR TITLE
:bug: Source Shopify: fix wrong field type for tax_exemptions

### LINKED ISSUE #10379: Connecting Shopify connector to Postgres: Database Error in model abandoned_checkouts_customer
Hi,

I ran the Airbyte dashboard by cloning the repo and running `docker-compose up`.

I'm trying to establish a sync a Shopify connector to a Postgres DB locally. After around 10 hours of sync, I got an error stopping the process (see the logs below). It went into another attempt but with the same result. I then cancelled the process.

However, when I look at the DB, I see some data in it, which is probably incomplete.

End of the logs:

```
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.104722 (MainThread): 12:45:31 | 
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.104971 (MainThread): 12:45:31 | Finished running 220 incremental models in 113.21s.
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.105182 (MainThread): Connection 'master' was properly closed.
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.105394 (MainThread): Connection 'model.airbyte_utils.orders_refunds_refund_da3_presentment_money' was properly closed.
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.105546 (MainThread): Connection 'model.airbyte_utils.orders_refunds_refun__amount_set_shop_money' was properly closed.
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.105750 (MainThread): Connection 'model.airbyte_utils.orders_refunds_refund_15a_presentment_money' was properly closed.
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.105898 (MainThread): Connection 'model.airbyte_utils.orders_refunds_refund_line_i_d02_shop_money' was properly closed.
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.106035 (MainThread): Connection 'model.airbyte_utils.orders_fulfillments_line_ite_e79_shop_money' was properly closed.
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.106172 (MainThread): Connection 'model.airbyte_utils.orders_fulfillments_l_f44_presentment_money' was properly closed.
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.106309 (MainThread): Connection 'model.airbyte_utils.orders_fulfillments_line_ite_e79_shop_money_ab1' was properly closed.
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.106445 (MainThread): Connection 'model.airbyte_utils.orders_fulfillments_l_f44_presentment_money_ab3' was properly closed.
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.392717 (MainThread): 
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.393059 (MainThread): Completed with 1 error and 0 warnings:
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.393315 (MainThread): 
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.393564 (MainThread): Database Error in model abandoned_checkouts_customer (models/generated/airbyte_incremental/public/abandoned_checkouts_customer.sql)
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.393800 (MainThread):   invalid input syntax for type boolean: "[]"
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.394006 (MainThread):   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/public/abandoned_checkouts_customer.sql
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.395068 (MainThread): 
2022-02-15 12:45:37 normalization > Done. PASS=217 WARN=0 ERROR=1 SKIP=2 TOTAL=220
2022-02-15 12:45:37 normalization > 2022-02-15 12:45:31.395493 (MainThread): Flushing usage events
```

### LINKED ISSUE #10411: 🐛 Shopify => Snowflake: fails during normalization on table `ABANDONED_CHECKOUTS_CUSTOMER`
## Environment
- **Airbyte version**:  example is 0.35.30-alpha
- **OS Version / Instance**: GCP e2
- **Deployment**: docker
- **Source Connector and version**: Shopify 0.1.31
- **Destination Connector and version**: Snowflake 0.4.12
- **Severity**: High
- **Step where error happened**: Sync job (normalization)

## Current Behavior
We're syncing 2 Shopify sources (2 different clients) to Snowflake and we get the same error on the same table during normalization.

`Boolean value '[]' is not recognized` on the table `ABANDONED_CHECKOUTS_CUSTOMER`

In `_AIRBYTE_RAW_ABANDONED_CHECKOUTS` table we can see that customers have 
```json
{
  ...

  "customer": {
    ...
    "state": "enabled",
    "tags": "newsletter, prospect",
    "tax_exempt": false,
    "tax_exemptions": [], <- this seems to be problematic
    "total_spent": 6283.66,
    "updated_at": "2022-01-16T10:00:56-05:00",
    "verified_email": true
  },

  ...
}
```

However in the normalization SQL generated by Airbyte, it tries to cast that column into a boolean
```sql
...
) as TOTAL_SPENT,
    cast(ORDERS_COUNT as
    bigint
) as ORDERS_COUNT,
    cast(LAST_ORDER_ID as
    bigint
) as LAST_ORDER_ID,
    cast(TAX_EXEMPTIONS as boolean) as TAX_EXEMPTIONS,  # <- this seems to be problematic
    cast(VERIFIED_EMAIL as boolean) as VERIFIED_EMAIL,
    cast(DEFAULT_ADDRESS as
    variant
) as DEFAULT_ADDRESS,
    cast(LAST_ORDER_NAME as
    varchar
) as LAST_ORDER_NAME,
    cast(ACCEPTS_MARKETING as boolean) as ACCEPTS_MARKETING,
    cast(ADMIN_GRAPHQL_API_ID as
    varchar
) as ADMIN_GRAPHQL_API_ID,
    cast(MULTIPASS_IDENTIFIER as
    varchar
) as MULTIPASS_IDENTIFIER,
    ACCEPTS_MARKETING_UPDATED_AT,
    _AIRBYTE_AB_ID,
    _AIRBYTE_EMITTED_AT,
    convert_timezone('UTC', current_timestamp()) as _AIRBYTE_NORMALIZED_AT
from __dbt__cte__ABANDONED_CHECKOUTS_CUSTOMER_AB1
...
```

## Expected Behavior
SQL column should probably not be cast as a boolean

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```
...

2022-02-17 09:43:30 normalization > 2022-02-17 09:43:23.783167 (MainThread): Completed with 1 error and 0 warnings:
2022-02-17 09:43:30 normalization > 2022-02-17 09:43:23.783457 (MainThread): 
2022-02-17 09:43:30 normalization > 2022-02-17 09:43:23.783754 (MainThread): Database Error in model ABANDONED_CHECKOUTS_CUSTOMER (models/generated/airbyte_tables/RAW/ABANDONED_CHECKOUTS_CUSTOMER.sql)
2022-02-17 09:43:30 normalization > 2022-02-17 09:43:23.784064 (MainThread):   100037 (22018): Boolean value '[]' is not recognized
2022-02-17 09:43:30 normalization > 2022-02-17 09:43:23.784302 (MainThread):   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/RAW/ABANDONED_CHECKOUTS_CUSTOMER.sql
2022-02-17 09:43:30 normalization > 2022-02-17 09:43:23.785231 (MainThread): 
2022-02-17 09:43:30 normalization > Done. PASS=253 WARN=0 ERROR=1 SKIP=2 TOTAL=256
2022-02-17 09:43:30 normalization > 2022-02-17 09:43:23.785633 (MainThread): Flushing usage events
2022-02-17 09:43:30 INFO i.a.w.t.TemporalAttemptExecution(lambda$getWorkerThread$2):158 - Completing future exceptionally...
io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.35.30-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.35.30-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:155) ~[io.airbyte-airbyte-workers-0.35.30-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

...
```

</details>

## Steps to Reproduce
1. Setup Shopify source
2. Setup Snowflake destination
3. Sync data

### LINKED ISSUE #10451: SHOPIFY abandoned_checkouts_customer has a variable type error
I'm trying to take tables from a SHOPIFY api to SNOWFLAKE and it fails to use basic normalization with the endpoint abandoned checkouts in the field customer.
The only problem is that the tables from abandoned checkouts customer are empty or don't exist, everything else is ok.
i think that the problem is in abandoned_checkouts.customer.tax_excemptions.
Here are the logs of the error:

2022-02-04 13:34:00 [42mnormalization[0m > [31mCompleted with 1 error and 0 warnings:[0m
2022-02-04 13:34:00 [42mnormalization[0m > 
2022-02-04 13:34:00 [42mnormalization[0m > [33mDatabase Error in model ABANDONED_CHECKOUTS_CUSTOMER (models/generated/airbyte_incremental/SHOPIFY/ABANDONED_CHECKOUTS_CUSTOMER.sql)[0m
2022-02-04 13:34:00 [42mnormalization[0m >   100037 (22018): Boolean value '[]' is not recognized
2022-02-04 13:34:00 [42mnormalization[0m > 
2022-02-04 13:34:00 [42mnormalization[0m > Done. PASS=15 WARN=0 ERROR=1 SKIP=2 TOTAL=18
2022-02-04 13:34:00 [32mINFO[m i.a.w.t.TemporalAttemptExecution(lambda$getWorkerThread$2):177 - Completing future exceptionally...
io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:174) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:57) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
	... 3 more
	Suppressed: io.airbyte.workers.WorkerException: Normalization process wasn't successful
		at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:159) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:45) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:174) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
2022-02-04 13:34:00 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):144 - Stopping cancellation check scheduling...
2022-02-04 13:34:00 [33mWARN[m i.t.i.s.POJOActivityTaskHandler(activityFailureToResult):363 - Activity failure. ActivityId=173b5e3e-3a57-31f7-9920-462b0862ac2c, activityType=Normalize, attempt=1
java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Normalization Failed.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:142) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
	at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.normalize(NormalizationActivityImpl.java:106) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:286) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:252) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:209) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:193) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:151) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) ~[temporal-sdk-1.6.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:174) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
	... 1 more
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:57) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:174) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
	... 1 more
	Suppressed: io.airbyte.workers.WorkerException: Normalization process wasn't successful
		at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:159) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:45) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
		at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:174) ~[io.airbyte-airbyte-workers-0.35.2-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]

### PR DESCRIPTION
**Pull request by philippeboyd**
abandoned_checkouts customer tax_exemptions had the wrong field type

## What
Fixes https://github.com/airbytehq/airbyte/issues/10411

## How
change abandoned_checkouts customer tax_exemptions type to array of strings

## Recommended reading order
1. `x.java`
2. `y.python`

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [x] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the new connector version is published, connector version bumped in the seed directory as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

<details><summary><strong>Connector Generator</strong></summary>

- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed

</details>

### CODE REVIEW

**Comment by marcosmarxm** [comment]
image
thanks @philippeboyd

**Review by bazarnov — APPROVED** [review]

**Comment by bazarnov** [comment]
Please share any confirmation the `acceptance-tests` are successful locally, I think we're good to go with this afterwards.

**Comment by marcosmarxm** [comment]
@philippeboyd  the implementation looks great but we're having problem running the CI to do the final validation. After we correct the problem I'll return to you.

**Comment by philippeboyd** [comment]
I just updated the PR to fix conflicts.
For acceptance tests I don't have access to a testing shopify environment.

**Review by marcosmarxm — APPROVED** [review]

**Pull request merged**
