### PR TITLE
🪟 🎨 Update layout of create connection and replication settings pages to mach design

### PR DESCRIPTION
**Pull request by edmundito**
## What

Update the layout of the new connection and replication settings pages to match the design.

- Splits the different sections (name, transfer, streams, transformation) into separate cards
- Added separation between fields and stream table and made streams table title larger and bolder
- Moves buttons outside of the bottom card
- Improves placement of input fields on larger window sizes
- Remove ["Don't worry!"](https://www.youtube.com/watch?v=d-diB65scQU) text from the bottom of the create connection page

### Create Connection Before & After:
Screen Shot 2022-07-21 at 13 11 09

Screen Shot 2022-07-21 at 13 20 33

### Replication settings Before & After:
Screen Shot 2022-07-21 at 13 14 04

Screen Shot 2022-07-21 at 13 10 39

Resizing improvements:
https://www.loom.com/share/fbc793b50a4b4f54a71f7366075ce580

## How
Moved components around and updated CSS in styled-components.

### CODE REVIEW

**Comment by timroes** [comment]
@edmundito do you think we could as part of this PR when creating a new connection, prefill the name field with `{sourceName} ⇒ {destinationName}`, so the user is not forced to type one (this has come up a couple of times in the past).

**Comment by edmundito** [comment]
@timroes I was planning to apply that next but as a separate PR since this change only impacts layout and not functionality.

**Comment by edmundito** [comment]
I pushed changes that improve the layout on smaller window sizes after reviewing the design changes with @Upmitt. No more changes!

**Comment by tealjulia** [comment]
Haven't looked through the code in its entirety yet, but in manually testing, I noticed expanding one of the streams to see the list of fields, the white fields table overflows the grey stream box.

Screen Shot 2022-07-25 at 5 38 25 PM

**Review by timroes — APPROVED** [review]
Code LGTM, tested locally, looks good, added some small fixes.

**Pull request merged**
