### PR TITLE
Source S3: encoding validation fix, refactor and test

### PR DESCRIPTION
**Pull request by roman-yermilov-gl**
## What
*A user gets a traceback in return If optional `encoding` field is not set. Instead of this we need to display a human readable error description*

## How

- Fix an error with incorrect data type passed to `codecs.lookup`. `None` type is replaced with empty string
- Fix error message. There was a problem with `error_message` varibale which is empty in cases when for loop validations is successfull
- Fix version dependency conflict
- Made small refactoring and unit test

### CODE REVIEW

**Review by davydov-d — APPROVED** [review]
please bump version in Dockerfile and metadata.yaml, also add a record in the changelog

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`f53727d5a5`](https://github.com/airbytehq/airbyte/pull/28730/commits/f53727d5a50c36df04486818ee22272bb22877ff)) - ❌

⏲️  Total pipeline duration: 26mn06s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ❌        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ryermilov_source-s3-encoding-validation/1690383180/f53727d5a50c36df04486818ee22272bb22877ff/source-s3/3.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Review by darynaishchenko — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`f3b92b629f`](https://github.com/airbytehq/airbyte/pull/28730/commits/f3b92b629f3e5abb667188143536dca7ce8035a6)) - ❌

⏲️  Total pipeline duration: 17mn17s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ❌        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ryermilov_source-s3-encoding-validation/1690453365/f3b92b629f3e5abb667188143536dca7ce8035a6/source-s3/3.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Comment by octavia-squidington-iii** [comment]
##  source-s3 test report (commit [`327b0fa50a`](https://github.com/airbytehq/airbyte/pull/28730/commits/327b0fa50a63c64787818e11c4f67fc730f5d7d6)) - ✅

⏲️  Total pipeline duration: 23mn22s 

| Step                                                             | Result   |
|:-----------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-s3/metadata.yaml | ✅        |
| Connector version semver check                                   | ✅        |
| QA checks                                                        | ✅        |
| Code format checks                                               | ✅        |
| Connector package install                                        | ✅        |
| Build source-s3 docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                       | ✅        |
| Integration tests                                                | ✅        |
| Acceptance tests                                                 | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ryermilov_source-s3-encoding-validation/1690456882/327b0fa50a63c64787818e11c4f67fc730f5d7d6/source-s3/3.1.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-s3 test
```

**Pull request merged**
