### PR TITLE
🐛 Twilio Source Connector: Decrease page_size for Usage Records Stream

### LINKED ISSUE #23512: Source Twilio: 500 Error when syncing Usage Records Stream
## Environment
- **Airbyte version**:  0.40.4
- **OS Version / Instance**: GCP VM
- **Deployment**: Docker
- **Source Connector and version**: Twilio 0.1.15
- **Destination Connector and version**: BigQuery 1.1.16
- **Step where error happened**: Sync job
## Current Behavior
When Syncing the Usage Records Stream, we keep getting the following API error response
```
airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: https://api.twilio.com/2010-04-01/Accounts/****/Usage/Records.json?PageSize=1000&StartDate=2023-01-02&EndDate=2023-02-27, Response Code: 500, Response Text: {"code": 20500, "message": "An internal server error has occurred", "more_info": "https://www.twilio.com/docs/errors/20500", "status": 500}
```
I tried hitting this API endpoint with Curl and it seems that by changing the PageSize to a smaller value (e.g. 100) the API call succeeds. Im not too sure if this is an issue on the Twilio side but it seems like reducing the number of responses the call fetches at a time helps out.

## Expected Behavior
Usage Records Stream completes successfully. 

## Logs

```
2023-02-27 16:00:30 [43mdestination[0m > 2023-02-27 16:00:30 [32mINFO[m i.a.i.d.b.BigQueryStagingConsumerFactory(lambda$onStartFunction$3):107 - Preparing tmp tables in destination completed.
2023-02-27 16:00:32 [43mdestination[0m > 2023-02-27 16:00:32 [32mINFO[m i.a.i.d.r.SerializedBufferingStrategy(lambda$addRecord$0):47 - Starting a new buffer for stream usage_records (current state: 0 bytes in 0 buffers)
2023-02-27 16:00:32 [43mdestination[0m > 2023-02-27 16:00:32 [32mINFO[m i.a.i.d.g.u.GcsUtils(getDefaultAvroSchema):25 - Default schema.
2023-02-27 16:00:59 [44msource[0m > Backing off _send(...) for 5.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: https://api.twilio.com/2010-04-01/Accounts/****/Usage/Records.json?PageSize=1000&StartDate=2023-01-02&EndDate=2023-02-27, Response Code: 500, Response Text: {"code": 20500, "message": "An internal server error has occurred", "more_info": "https://www.twilio.com/docs/errors/20500", "status": 500})
2023-02-27 16:00:59 [44msource[0m > Caught retryable error 'Request URL: https://api.twilio.com/2010-04-01/Accounts/****/Usage/Records.json?PageSize=1000&StartDate=2023-01-02&EndDate=2023-02-27, Response Code: 500, Response Text: {"code": 20500, "message": "An internal server error has occurred", "more_info": "https://www.twilio.com/docs/errors/20500", "status": 500}' after 1 tries. Waiting 5 seconds then retrying...
2023-02-27 16:01:30 [44msource[0m > Backing off _send(...) for 10.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: https://api.twilio.com/2010-04-01/Accounts/****/Usage/Records.json?PageSize=1000&StartDate=2023-01-02&EndDate=2023-02-27, Response Code: 500, Response Text: {"code": 20500, "message": "An internal server error has occurred", "more_info": "https://www.twilio.com/docs/errors/20500", "status": 500})
2023-02-27 16:01:30 [44msource[0m > Caught retryable error 'Request URL: https://api.twilio.com/2010-04-01/Accounts/****/Usage/Records.json?PageSize=1000&StartDate=2023-01-02&EndDate=2023-02-27, Response Code: 500, Response Text: {"code": 20500, "message": "An internal server error has occurred", "more_info": "https://www.twilio.com/docs/errors/20500", "status": 500}' after 2 tries. Waiting 10 seconds then retrying...
2023-02-27 16:02:06 [44msource[0m > Backing off _send(...) for 20.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: https://api.twilio.com/2010-04-01/Accounts/****/Usage/Records.json?PageSize=1000&StartDate=2023-01-02&EndDate=2023-02-27, Response Code: 500, Response Text: {"code": 20500, "message": "An internal server error has occurred", "more_info": "https://www.twilio.com/docs/errors/20500", "status": 500})
2023-02-27 16:02:06 [44msource[0m > Caught retryable error 'Request URL: https://api.twilio.com/2010-04-01/Accounts/****/Usage/Records.json?PageSize=1000&StartDate=2023-01-02&EndDate=2023-02-27, Response Code: 500, Response Text: {"code": 20500, "message": "An internal server error has occurred", "more_info": "https://www.twilio.com/docs/errors/20500", "status": 500}' after 3 tries. Waiting 20 seconds then retrying...
2023-02-27 16:02:52 [44msource[0m > Backing off _send(...) for 40.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: https://api.twilio.com/2010-04-01/Accounts/****/Usage/Records.json?PageSize=1000&StartDate=2023-01-02&EndDate=2023-02-27, Response Code: 500, Response Text: {"code": 20500, "message": "An internal server error has occurred", "more_info": "https://www.twilio.com/docs/errors/20500", "status": 500})
2023-02-27 16:02:52 [44msource[0m > Caught retryable error 'Request URL: https://api.twilio.com/2010-04-01/Accounts/****/Usage/Records.json?PageSize=1000&StartDate=2023-01-02&EndDate=2023-02-27, Response Code: 500, Response Text: {"code": 20500, "message": "An internal server error has occurred", "more_info": "https://www.twilio.com/docs/errors/20500", "status": 500}' after 4 tries. Waiting 40 seconds then retrying...
2023-02-27 16:03:58 [44msource[0m > Backing off _send(...) for 80.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: https://api.twilio.com/2010-04-01/Accounts/****/Usage/Records.json?PageSize=1000&StartDate=2023-01-02&EndDate=2023-02-27, Response Code: 500, Response Text: {"code": 20500, "message": "An internal server error has occurred", "more_info": "https://www.twilio.com/docs/errors/20500", "status": 500})
2023-02-27 16:03:58 [44msource[0m > Caught retryable error 'Request URL: https://api.twilio.com/2010-04-01/Accounts/****/Usage/Records.json?PageSize=1000&StartDate=2023-01-02&EndDate=2023-02-27, Response Code: 500, Response Text: {"code": 20500, "message": "An internal server error has occurred", "more_info": "https://www.twilio.com/docs/errors/20500", "status": 500}' after 5 tries. Waiting 80 seconds then retrying...
2023-02-27 16:05:44 [44msource[0m > Giving up _send(...) after 6 tries (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: https://api.twilio.com/2010-04-01/Accounts/****/Usage/Records.json?PageSize=1000&StartDate=2023-01-02&EndDate=2023-02-27, Response Code: 500, Response Text: {"code": 20500, "message": "An internal server error has occurred", "more_info": "https://www.twilio.com/docs/errors/20500", "status": 500})
2023-02-27 16:05:44 [44msource[0m > Encountered an exception while reading stream usage_records
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 120, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 189, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 305, in _read_full_refresh
    for record_data_or_message in record_data_or_messages:
  File "/airbyte/integration_code/source_twilio/streams.py", line 223, in read_records
    for record in super().read_records(sync_mode, cursor_field, stream_slice, stream_state):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 413, in read_records
    yield from self._read_pages(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 429, in _read_pages
    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 452, in _fetch_next_page
    response = self._send_request(request, request_kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 354, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 314, in _send
    raise DefaultBackoffException(request=request, response=response, error_message=error_message)
airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: https://api.twilio.com/2010-04-01/Accounts/****/Usage/Records.json?PageSize=1000&StartDate=2023-01-02&EndDate=2023-02-27, Response Code: 500, Response Text: {"code": 20500, "message": "An internal server error has occurred", "more_info": "https://www.twilio.com/docs/errors/20500", "status": 500}
2023-02-27 16:05:44 [44msource[0m > Finished syncing usage_records
2023-02-27 16:05:44 [44msource[0m > SourceTwilio runtimes:
Syncing stream usage_records 0:05:17.300131
2023-02-27 16:05:44 [44msource[0m > Request URL: https://api.twilio.com/2010-04-01/Accounts/****/Usage/Records.json?PageSize=1000&StartDate=2023-01-02&EndDate=2023-02-27, Response Code: 500, Response Text: {"code": 20500, "message": "An internal server error has occurred", "more_info": "https://www.twilio.com/docs/errors/20500", "status": 500}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 120, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 189, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 305, in _read_full_refresh
    for record_data_or_message in record_data_or_messages:
  File "/airbyte/integration_code/source_twilio/streams.py", line 223, in read_records
    for record in super().read_records(sync_mode, cursor_field, stream_slice, stream_state):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 413, in read_records
    yield from self._read_pages(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 429, in _read_pages
    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 452, in _fetch_next_page
    response = self._send_request(request, request_kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 354, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 314, in _send
    raise DefaultBackoffException(request=request, response=response, error_message=error_message)
airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: https://api.twilio.com/2010-04-01/Accounts/****/Usage/Records.json?PageSize=1000&StartDate=2023-01-02&EndDate=2023-02-27, Response Code: 500, Response Text: {"code": 20500, "message": "An internal server error has occurred", "more_info": "https://www.twilio.com/docs/errors/20500", "status": 500}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 133, in read
    raise AirbyteTracedException.from_exception(e, message=display_message) from e
airbyte_cdk.utils.traced_exception.AirbyteTracedException: Request URL: https://api.twilio.com/2010-04-01/Accounts/****/Usage/Records.json?PageSize=1000&StartDate=2023-01-02&EndDate=2023-02-27, Response Code: 500, Response Text: {"code": 20500, "message": "An internal server error has occurred", "more_info": "https://www.twilio.com/docs/errors/20500", "status": 500}
```
## Steps to Reproduce
1. Enable the Usage Records Stream with a high number of records to be synced.

## Are you willing to submit a PR?

Yes! I have made a change to the Page Size of the Usage Records stream on our fork and have been using that image to sync Twilio data.  I will create a PR with that change.

### PR DESCRIPTION
**Pull request by jitoquinto**
## What
Changes the default Page Size for the Usage Records Stream in the Twilio Source Connector. This is to resolve the following issue - Closes https://github.com/airbytehq/airbyte/issues/23512

After doing some local testing of the Twilio API, It seems like reducing the Page Size for the Usage Records endpoint resolved the 500 errors we were facing.

## How
Changed the default Page Size to 100 for only the Usage Records Stream as this was the only one running into errors.

## 🚨 User Impact 🚨
`Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.`

No breaking changes since its just modifying how many results each page will have. The connector will have to make more calls since there will be more pages to iterate through.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

### Community member or Airbyter

- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

### CODE REVIEW

**Comment by jitoquinto** [comment]
Unit Tests Screenshots:
Pasted Graphic 3

Pasted Graphic 4

**Comment by marcosmarxm** [comment]
@artem1205 can you check this contribution and the original issue? Looks Twilio is throwing error 500

**Comment by artem1205** [comment]
@marcosmarxm, taking a look, decreasing 1k->100 records will increase number of requests x10 times.
Not sure about hardcoding `page_size` for this stream, maybe more complex error handler with automatic decreasing page size should be used here.

**Review by evantahler — CHANGES_REQUESTED** [review]
Hi @jitoquinto, thank you for the contribution!

As others have commented, this change will likely _dramatically_ slow down this source.  We don't have other users with reporting bug, but I certainly can see how, given a certain dataset, a smaller payload could fix things.

With the conditional utility of this change in mind, I would suggest:
1. Implement a backoff strategy in the case of 500 errors.  Rather than limit all requests for this stream to 100/page, start with the default of 1K, and if you see a 500 error, try again with a smaller size.  
2. Make this setting an optional configuration value.  Would it be helpful to configure the page size for any other streams?
 
For PRs that change a connecor:
* Bump the version in the Dockerfile to the new version (this would likely be a minor semver change)
* Add an entry for the change in the connector's docs/changelog

**Comment by evantahler** [comment]
Thank you @jitoquinto for this contribution. While I'm glad to see that you were able to use Airbyte to create a connector that worked for you, I'm going to close this PR.  The change you added is not appropriate for all Airbyte users.  If you want to continue, please create a new PR with these changes being optional/configuration, along with the other changes requested in this issue.

Thank you!

**Pull request closed without merging**
