### PR TITLE
🎉 Source Shopify-OAuth: release for Cloud Review

### PR DESCRIPTION
**Pull request by bazarnov**
## What
Based on this Slack discussion with @sherifnada : https://airbyte-globallogic.slack.com/archives/C02TXT37Y3Y/p1689780230666159

In order to overcome the current limitations of the platform, it's decided to release the copy of the `source-shopify` that maintains the OAuth2.0-only authentication option and does not break the existing `source-shopify` cloud users. After the review is finished by the `Shopify Review Team` this source should be removed from the codebase and catalog.

## How
- duplicated the `source-shopify` 1:1 with small changes from this PR: https://github.com/airbytehq/airbyte/pull/28291, reflecting the latest changes we plan to release for OAuth flow.
- used the different UUID: `fc8132b4-848a-4b8c-8421-daacc4ea1345` to overcome the current Cloud limitations for OAuth procedures to allow this source for the specific `workspace` for the Shopify review in `Cloud`.
-  updated the public docs to reflect the `steps required` for connector setup.

### CODE REVIEW

**Review by darynaishchenko — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-shopify-oauth test report (commit [`9f2aad9c95`](https://github.com/airbytehq/airbyte/pull/28507/commits/9f2aad9c95d2941a2359ed28ac93dcfee3d13985)) - ❌

⏲️  Total pipeline duration: 30mn47s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-shopify-oauth/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |
| Code format checks                                                          | ✅        |
| Connector package install                                                   | ✅        |
| Build source-shopify-oauth docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Acceptance tests                                                            | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-shopify-oauth-candidate-review/1689845842/9f2aad9c95d2941a2359ed28ac93dcfee3d13985/source-shopify-oauth/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-shopify-oauth test
```

**Comment by octavia-squidington-iii** [comment]
##  source-shopify-oauth test report (commit [`9f2aad9c95`](https://github.com/airbytehq/airbyte/pull/28507/commits/9f2aad9c95d2941a2359ed28ac93dcfee3d13985)) - ❌

⏲️  Total pipeline duration: 17.61s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-shopify-oauth/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |
| Code format checks                                                          | ✅        |
| Connector package install                                                   | ✅        |
| Build source-shopify-oauth docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Acceptance tests                                                            | ❌        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-shopify-oauth-candidate-review/1689847776/9f2aad9c95d2941a2359ed28ac93dcfee3d13985/source-shopify-oauth/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-shopify-oauth test
```

**Comment by octavia-squidington-iii** [comment]
##  source-shopify-oauth test report (commit [`52aa5d0634`](https://github.com/airbytehq/airbyte/pull/28507/commits/52aa5d06344f7dcc135b922151639c5786bddb69)) - ✅

⏲️  Total pipeline duration: 30mn31s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-shopify-oauth/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |
| Code format checks                                                          | ✅        |
| Connector package install                                                   | ✅        |
| Build source-shopify-oauth docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Acceptance tests                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-shopify-oauth-candidate-review/1689849127/52aa5d06344f7dcc135b922151639c5786bddb69/source-shopify-oauth/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-shopify-oauth test
```

**Review by sherifnada — APPROVED** [review]
Do we need an external docs page? Could we just keep this as an "internal" connector?

**Comment by bazarnov** [comment]
> Do we need an external docs page? Could we just keep this as an "internal" connector?

I think we can leave this one edited specifically for the Cloud case: https://cloud.airbyte.com/workspaces/9ef0ca9a-d759-484c-8499-93565374eaea/source/new-source/253487c0-2246-43ba-a21f-5116b20a2c50 for this connector. No external page is required.

**Comment by octavia-squidington-iii** [comment]
##  source-shopify-oauth test report (commit [`282154bb2a`](https://github.com/airbytehq/airbyte/pull/28507/commits/282154bb2a8247b94828d3df74d58fc814a360b6)) - ✅

⏲️  Total pipeline duration: 30mn20s 

| Step                                                                        | Result   |
|:----------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-shopify-oauth/metadata.yaml | ✅        |
| Connector version semver check                                              | ✅        |
| QA checks                                                                   | ✅        |
| Code format checks                                                          | ✅        |
| Connector package install                                                   | ✅        |
| Build source-shopify-oauth docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                                  | ✅        |
| Acceptance tests                                                            | ✅        |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/baz_source-shopify-oauth-candidate-review/1689878678/282154bb2a8247b94828d3df74d58fc814a360b6/source-shopify-oauth/0.1.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-shopify-oauth test
```

**Pull request merged**
