### PR TITLE
Faker emits `AirbyteEstimateTraceMessage`

### PR DESCRIPTION
**Pull request by evantahler**
Extracted from https://github.com/airbytehq/airbyte/pull/18630, part of https://github.com/airbytehq/airbyte-internal-issues/issues/1095.

### CODE REVIEW

**Comment by evantahler** [comment]
cc @alafanechere can you give me a pointer to how to pass this failing SAT test?  Since I'm not really using the CDK tooling, I'm not sure how I'm supposed to exit the container in this case

**Comment by alafanechere** [comment]
Hey @evantahler, the problem was that in case of check failure the returned object was a generator (which is an iterable) because `yield` was used. And this generator does not have the `status` attribute accessed downstream.
I was able to make SAT run locally by:
* Return a status object instead of a generator
* Change the expected status to be `failed` instead of `exception`.
I also remove the `exit(1)` instruction. 
Are these changes impacting the logic you've been trying to implement in this PR? 
Moreover, I don't see anything preventing this connector to use the CDK, which will be better for long term maintenance. (Just changing `check` to `check_connection` and `discover` to `streams`, with adapted return value, would do the job I think).

**Comment by evantahler** [comment]
Thank you @alafanechere!

**Comment by evantahler** [comment]
These changes are not logical changes, other than the emitting of stream size estimates at the beginning of the sync. 

Yes, this connector should totally be moved to a more "normal" CDK connector.  I made it a long time ago back when I didn't know what I was doing 😇... but that's another PR!

**Review by davinchia — APPROVED** [review]

**Pull request merged**
