### PR TITLE
Source Klaviyo: Fix formatting

### PR DESCRIPTION
**Pull request by artem1205**
## What

Fix Source Klaviyo Connector health report

## How
Fix formatting

## Recommended reading order
1. `expected_records.jsonl`

## 🚨 User Impact 🚨

no breaking changes

## Pre-merge Actions

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-klaviyo test report (commit [`7244d31194`](https://github.com/airbytehq/airbyte/pull/27532/commits/7244d31194a41d1afa53c2d08b68c319aac9ecfc)) - ❌

⏲️  Total pipeline duration: 228 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-klaviyo/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ❌        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-klaviyo docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5327094052)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-klaviyo test
```

**Comment by octavia-squidington-iii** [comment]
##  source-klaviyo test report (commit [`7244d31194`](https://github.com/airbytehq/airbyte/pull/27532/commits/7244d31194a41d1afa53c2d08b68c319aac9ecfc)) - ❌

⏲️  Total pipeline duration: 219 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-klaviyo/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ❌        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-klaviyo docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5327095095)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-klaviyo test
```

**Comment by octavia-squidington-iii** [comment]
##  source-klaviyo test report (commit [`fdfa984749`](https://github.com/airbytehq/airbyte/pull/27532/commits/fdfa984749806be96db43cc8d5013f1e5694115b)) - ❌

⏲️  Total pipeline duration: 236 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-klaviyo/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-klaviyo docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5327555439)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-klaviyo test
```

**Comment by octavia-squidington-iii** [comment]
##  source-klaviyo test report (commit [`f80c062255`](https://github.com/airbytehq/airbyte/pull/27532/commits/f80c0622556a98b0151f7f1a8aed562e7ee1c1df)) - ❌

⏲️  Total pipeline duration: 193 seconds

| Step                                                                  | Result   |
|:----------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-klaviyo/metadata.yaml | ✅        |
| Connector version semver check.                                       | ✅        |
| Connector version increment check.                                    | ✅        |
| QA checks                                                             | ❌        |
| Code format checks                                                    | ✅        |
| Connector package install                                             | ✅        |
| Build source-klaviyo docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                            | ✅        |
| Acceptance tests                                                      | ✅        |

🔗 [View the logs here](https://github.com/airbytehq/airbyte/actions/runs/5327702547)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-klaviyo test
```

**Comment by davydov-d** [comment]
this PR already contains the same changes https://github.com/airbytehq/airbyte/pull/27498

**Pull request closed without merging**
