### PR TITLE
🎉 New Source: EmailOctopus [low-code cdk]

### PR DESCRIPTION
**Pull request by scottleechua**
## What
This PR adds a source connector for [EmailOctopus](https://emailoctopus.com/). Please see [this issue](https://github.com/airbytehq/connector-contest/issues/181) for more context.

## How
This PR uses the low-code CDK to create a source connector for the critical streams:
- [Get all lists](https://emailoctopus.com/api-documentation/lists/get-all)
- [Get all campaigns](https://emailoctopus.com/api-documentation/campaigns/get-all)

## Recommended reading order
1. `docs/integrations/sources/emailoctopus.md`
2. `spec.yaml`
3. `emailoctopus.yaml`
4. `schemas/campaigns.json` and `schemas/lists.json`

## 🚨 User Impact 🚨
No changes to base code.

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>New Connector</strong></summary>

### Community member or Airbyter

- [x] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [x] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [x] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [x] PR name follows [PR naming conventions](https://docs.airbyte.com/contributing-to-airbyte/issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
- [ ] After the connector is published, connector added to connector index as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
- [ ] Seed specs have been re-generated by building the platform and committing the changes to the seed spec files, as described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)

</details>

## Tests

<details><summary><strong>Acceptance</strong></summary>

Screenshot 2022-10-29 at 1 13 52 PM

</details>

### CODE REVIEW

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Hello @scottleechua, Marcos from Airbyte here 👋 . We received more than 25 new contributions along the weekend. One is yours 🎉  thank so much for! Our team is limited and maybe the review process can take longer than expected. As described in the Airbyte's Hacktoberfest your contribution was submitted before November 2nd and it is eligible to win the prize. The review process will validate other requirements. I ask to you patience until someone from the team review it. 

Because I reviewed some contributions for Hacktoberfest so far I saw some common patterns you can check in advance:
* [ ] Make sure you have added connector documentation to `/docs/integrations/`
* [ ] Remove the file `catalog` from `/integration_tests`
* [ ] Edit the `sample_config.json` inside `/integration_tests`
* [ ] For the `configured_catalog` you can use only `json_schema: {}`
* [ ] Add title to all properties in the `spec.yaml`
* [ ] Make sure the `documentationUrl` in the `spec.yaml` redirect to Airbyte's future connector page, eg: connector Airtable the `documentationUrl: https://docs.airbyte.com/integrations/sources/airtable`
* [ ] Review now new line at EOF (end-of-file) for all files.

If possible send to me a DM in Slack with the tests credentials, this process will make easier to us run integration tests and publish your connector. If you only has production keys, make sure to create a bootstrap.md explaining how to get the keys.

**Comment by marcosmarxm** [comment]
@scottleechua please ask my review when you solve all points I have made in my previous comment.

**Comment by marcosmarxm** [comment]
Hello! I'm going to be out of the office this Friday and won't be able to review your contribution again today, I return next Monday. So far, most contributions look solid and are almost done to be approved. As said in [Chris' comment](https://airbytehq.slack.com/archives/C0450PCSDB2/p1667430678866629) all contributions made before 2-November are eligible to receive the prize and have 2 weeks to merge the contributions. But I ensure next week we're going to have your contribution merged. If you have questions about the implementation you can send them in `#hacktoberfest-2022` in Airbyte's Slack.

Sorry the inconvenience and see you again next week, thank you so much for your contribution!

**Comment by scottleechua** [comment]
Hello @marcosmarxm , @sajarin !

* [x]  Make sure you have added connector documentation to `/docs/integrations/`
               -- Added [emailoctopus.md](https://github.com/airbytehq/airbyte/blob/5f57158b69e695ce318f4cac2bb0988f0f17fffc/docs/integrations/sources/emailoctopus.md) and linked to it in the integration [README](https://github.com/airbytehq/airbyte/blob/5f57158b69e695ce318f4cac2bb0988f0f17fffc/docs/integrations/README.md).
* [x]  Remove the file `catalog` from `/integration_tests`
* [x]  Edit the `sample_config.json` inside `/integration_tests`
* [x]  For the `configured_catalog` you can use only `json_schema: {}`
* [x]  Add title to all properties in the `spec.yaml`
               -- Updated.
* [x]  Make sure the `documentationUrl` in the `spec.yaml` redirect to Airbyte's future connector page
               -- Updated top-level domain from `airbyte.io` to `airbyte.com`
* [x]  Review no new line at EOF (end-of-file) for all files.
* [x] Added BOOTSTRAP.md with instructions on generating an API key.
               -- My production account contain subscriber personal information so I unfortunately can't share it.
               -- I have reached out to EmailOctopus if they are able to provide a sandbox account.

Also am not sure why the acceptance tests run by @koconder failed as `test_core` and `test_full_refresh` both run successfully on my local -- let me know if I can do anything about this!

Thank you! 😄

**Comment by koconder** [comment]
@scottleechua ignore the earlier test results from my side. They did have test credentials setup. Appologies for the confusion caused.

**Comment by scottleechua** [comment]
Ah, got it! All good @koconder 😄

**Comment by marcosmarxm** [comment]
Thanks @scottleechua I'm waiting EmailOctopus approve my account to test your connector. I'll return the review tomorrow.

**Review by marcosmarxm — APPROVED** [review]
Thanks @scottleechua for the contribution

**Pull request merged**
