### PR TITLE
🐛 Source Greenhouse: update following state management changes in the CDK

### PR DESCRIPTION
**Pull request by maxi297**
## What
Breaking changes were done as part of https://github.com/airbytehq/airbyte/commit/a45a1e33413eacccb2b8a83450d1638c48fd2042. This PR fixes the breaking changes for greenhouse.

## How
Updating the interfaces that were affected by breaking changes.

## 🚨 User Impact 🚨
None as the code should have the exact same behavior

### CODE REVIEW

**Comment by octavia-squidington-iii** [comment]
##  source-greenhouse test report (commit [`f70c2feaee`](https://github.com/airbytehq/airbyte/pull/27773/commits/f70c2feaee9c54698f82292c703e0c98f0074542)) - ❌

⏲️  Total pipeline duration: 207 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-greenhouse/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ❌        |
| Connector package install                                                | ✅        |
| Build source-greenhouse docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_greenhouse/1687892326/f70c2feaee9c54698f82292c703e0c98f0074542/source-greenhouse/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-greenhouse test
```

**Comment by octavia-squidington-iii** [comment]
##  source-greenhouse test report (commit [`105848d0d3`](https://github.com/airbytehq/airbyte/pull/27773/commits/105848d0d3c85a947a7435b879c8a4a3e601487e)) - ❌

⏲️  Total pipeline duration: 183 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-greenhouse/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ❌        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-greenhouse docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_greenhouse/1687896021/105848d0d3c85a947a7435b879c8a4a3e601487e/source-greenhouse/0.4.0/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-greenhouse test
```

**Comment by octavia-squidington-iii** [comment]
##  source-greenhouse test report (commit [`4a0e4ed5f7`](https://github.com/airbytehq/airbyte/pull/27773/commits/4a0e4ed5f735de1cbfd2d6be763061d4a4494bfb)) - ❌

⏲️  Total pipeline duration: 38 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-greenhouse/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-greenhouse docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_greenhouse/1687899848/4a0e4ed5f735de1cbfd2d6be763061d4a4494bfb/source-greenhouse/0.4.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-greenhouse test
```

**Comment by octavia-squidington-iii** [comment]
##  source-greenhouse test report (commit [`c770a7b94c`](https://github.com/airbytehq/airbyte/pull/27773/commits/c770a7b94c9cfe8a7ec03c39522f23dd5e91eea2)) - ❌

⏲️  Total pipeline duration: 201 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-greenhouse/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-greenhouse docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_greenhouse/1687909504/c770a7b94c9cfe8a7ec03c39522f23dd5e91eea2/source-greenhouse/0.4.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-greenhouse test
```

**Comment by octavia-squidington-iii** [comment]
##  source-greenhouse test report (commit [`0931ca9fb6`](https://github.com/airbytehq/airbyte/pull/27773/commits/0931ca9fb6649ea0a708f5585918cc5db16a8c81)) - ❌

⏲️  Total pipeline duration: 496 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-greenhouse/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ❌        |
| Connector package install                                                | ✅        |
| Build source-greenhouse docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_greenhouse/1687913405/0931ca9fb6649ea0a708f5585918cc5db16a8c81/source-greenhouse/0.4.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-greenhouse test
```

**Comment by octavia-squidington-iii** [comment]
##  source-greenhouse test report (commit [`b22c1b6470`](https://github.com/airbytehq/airbyte/pull/27773/commits/b22c1b647086de08e03a7531ab700c7c198d196b)) - ❌

⏲️  Total pipeline duration: 477 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-greenhouse/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ❌        |
| Connector package install                                                | ✅        |
| Build source-greenhouse docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_greenhouse/1687933302/b22c1b647086de08e03a7531ab700c7c198d196b/source-greenhouse/0.4.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-greenhouse test
```

**Comment by octavia-squidington-iii** [comment]
##  source-greenhouse test report (commit [`07461b3823`](https://github.com/airbytehq/airbyte/pull/27773/commits/07461b382337ed4265363c8ef69d26c254abace7)) - ❌

⏲️  Total pipeline duration: 562 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-greenhouse/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ❌        |
| Connector package install                                                | ✅        |
| Build source-greenhouse docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_greenhouse/1687968396/07461b382337ed4265363c8ef69d26c254abace7/source-greenhouse/0.4.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-greenhouse test
```

**Comment by octavia-squidington-iii** [comment]
##  source-greenhouse test report (commit [`f14f423ee4`](https://github.com/airbytehq/airbyte/pull/27773/commits/f14f423ee47c8a43ae97bcfc5a137e03f6783332)) - ✅

⏲️  Total pipeline duration: 522 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-greenhouse/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-greenhouse docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_greenhouse/1687969740/f14f423ee47c8a43ae97bcfc5a137e03f6783332/source-greenhouse/0.4.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-greenhouse test
```

**Review by artem1205 — APPROVED** [review]

**Comment by octavia-squidington-iii** [comment]
##  source-greenhouse test report (commit [`185610f630`](https://github.com/airbytehq/airbyte/pull/27773/commits/185610f630828ce51ecef6226f944c28a7d9a7ff)) - ❌

⏲️  Total pipeline duration: 299 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-greenhouse/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ❌        |
| Connector package install                                                | ✅        |
| Build source-greenhouse docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_greenhouse/1687990764/185610f630828ce51ecef6226f944c28a7d9a7ff/source-greenhouse/0.4.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-greenhouse test
```

**Comment by octavia-squidington-iii** [comment]
##  source-greenhouse test report (commit [`ee2d0787b1`](https://github.com/airbytehq/airbyte/pull/27773/commits/ee2d0787b1000f7e0b717d4ff9c19e0b1c68305d)) - ❌

⏲️  Total pipeline duration: 267 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-greenhouse/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-greenhouse docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_greenhouse/1687991415/ee2d0787b1000f7e0b717d4ff9c19e0b1c68305d/source-greenhouse/0.4.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-greenhouse test
```

**Comment by octavia-squidington-iii** [comment]
##  source-greenhouse test report (commit [`7a6352141e`](https://github.com/airbytehq/airbyte/pull/27773/commits/7a6352141e36204dd95b4cc42471a3f0363bafac)) - ❌

⏲️  Total pipeline duration: 57 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-greenhouse/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-greenhouse docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ❌        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_greenhouse/1688043133/7a6352141e36204dd95b4cc42471a3f0363bafac/source-greenhouse/0.4.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-greenhouse test
```

**Comment by octavia-squidington-iii** [comment]
##  source-greenhouse test report (commit [`395eb51a29`](https://github.com/airbytehq/airbyte/pull/27773/commits/395eb51a29ebf18fbe3e0aedfa7feb8e92964047)) - ✅

⏲️  Total pipeline duration: 517 seconds

| Step                                                                     | Result   |
|:-------------------------------------------------------------------------|:---------|
| Validate airbyte-integrations/connectors/source-greenhouse/metadata.yaml | ✅        |
| Connector version semver check                                           | ✅        |
| Connector version increment check                                        | ✅        |
| QA checks                                                                | ✅        |
| Code format checks                                                       | ✅        |
| Connector package install                                                | ✅        |
| Build source-greenhouse docker image for platform linux/x86_64           | ✅        |
| Unit tests                                                               | ✅        |
| Acceptance tests                                                         | ✅        |

🔗 [View the logs here](https://storage.googleapis.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/maxi297-state-changes_greenhouse/1688051284/395eb51a29ebf18fbe3e0aedfa7feb8e92964047/source-greenhouse/0.4.1/output.html)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-greenhouse test
```

**Pull request merged**
