### PR TITLE
Fix "android_last_seen_at" data type

### PR DESCRIPTION
**Pull request by ReptilianBrain**
Intercom API send a timestamp for the "android_last_seen_at" field.  Which cause issue later on when dbt tries to created the table.

2021-09-10 02:40:43 INFO () LineGobbler(voidCall):85 - Database Error in model intercom__contacts (models/generated/airbyte_tables/dev_sandbox/intercom__contacts.sql)
2021-09-10 02:40:43 INFO () LineGobbler(voidCall):85 -   Invalid digit, Value '-', Pos 4, Type: Long 
2021-09-10 02:40:43 INFO () LineGobbler(voidCall):85 -   DETAIL:  
2021-09-10 02:40:43 INFO () LineGobbler(voidCall):85 -     -----------------------------------------------
2021-09-10 02:40:43 INFO () LineGobbler(voidCall):85 -     error:  Invalid digit, Value '-', Pos 4, Type: Long 
2021-09-10 02:40:43 INFO () LineGobbler(voidCall):85 -     code:      1207
2021-09-10 02:40:43 INFO () LineGobbler(voidCall):85 -     context:   2021-09-03T00:45:55Z
2021-09-10 02:40:43 INFO () LineGobbler(voidCall):85 -     query:     131295371
2021-09-10 02:40:43 INFO () LineGobbler(voidCall):85 -     location:  :0
2021-09-10 02:40:43 INFO () LineGobbler(voidCall):85 -     process:   query3_51_131295371 [pid=0]
2021-09-10 02:40:43 INFO () LineGobbler(voidCall):85 -     -----------------------------------------------
2021-09-10 02:40:43 INFO () LineGobbler(voidCall):85 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/dev_sandbox/intercom__contacts.sql

## What
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*

## How
*Describe the solution*

## Recommended reading order
1. `x.java`
2. `y.python`

## Pre-merge Checklist
Expand the relevant checklist and delete the others. 

<details><summary> <strong> New Connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] **Community member?** Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] `docs/SUMMARY.md`
    - [ ] `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
    - [ ] `docs/integrations/README.md`
    - [ ] `airbyte-integrations/builds.md`
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector added to connector index like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)
   
</p>
</details>

<details><summary> <strong> Updating a connector </strong></summary>
<p>
   
#### Community member or Airbyter
   
- [ ] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [ ] Secrets in the connector's spec are annotated with `airbyte_secret` 
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [ ] Documentation updated 
    - [ ] Connector's `README.md`
    - [ ] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [ ] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] Connector version bumped like described [here](https://docs.airbyte.io/connector-development#publishing-a-connector)
   
#### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
   
- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] Credentials added to Github CI. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci). 
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing. 
- [ ] New Connector version released on Dockerhub by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</p>
</details>

<details><summary> <strong> Connector Generator </strong> </summary>
<p>
   
- [ ] Issue acceptance criteria met
- [ ] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)
- [ ] If adding a new generator, add it to the [list of scaffold modules being tested](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/generator/build.gradle#L41)
- [ ] The generator test modules (all connectors with `-scaffold` in their name) have been updated with the latest scaffold by running `./gradlew :airbyte-integrations:connector-templates:generator:testScaffoldTemplates` then checking in your changes
- [ ] Documentation which references the generator is updated as needed.
</p>
</details>

### CODE REVIEW

**Comment by lazebnyi** [comment]
@ReptilianBrain Thanks for PR. We get the timestamp from Intercom API and in the schema, we write type integer which matches with API response. So, I didn't think we need change the schema. Could you test your issue on the last version of Intercom connector  - #6087

**Review by lazebnyi — CHANGES_REQUESTED** [review]
@ReptilianBrain Thanks for PR. We get the timestamp from Intercom API and in the schema, we write type integer which matches with API response. So, I didn't think we need change the schema. Could you test your issue on the last version of Intercom connector - #6087

**Comment by ReptilianBrain** [comment]
Hello @lazebnyi

Thank you for your reply.

You are right the API documentation and response is giving the result as an integer.

My confusion comes from when I look at the content of _airbyte_raw_intercom__contacts (using the latest version of the connector)


The android_last_seen_at field data is shown as a timestamp.

here's a snippet of the data I see in the table

`{"type":"contact","id":"5f57802cad3fce89b236c587","created_at":1599569964,"updated_at":1632402541,"signed_up_at":1632402541,"last_seen_at":1632402541,"last_contacted_at":1629986236,"android_last_seen_at":"2021-09-19T18:24:28Z"}}`

Does this help investigating my issue ?

Thank you

**Comment by marcosmarxm** [comment]
@lazebnyi I tried to run Intercom with Integration Account and these fields are null so I can't validate it. Could you populate with some data to check it? 

@ReptilianBrain can you assign the CLA? Besides that we only need to add data to this fields and runs tests! Looks good to me! :D thanks

**Review by marcosmarxm — APPROVED** [review]
I'm approving based on user info! I'll wait @lazebnyi to merge this

**Review by lazebnyi — APPROVED** [review]
Bumped version

**Comment by lazebnyi** [comment]
@marcosmarxm need run tests and publish before merge

**Pull request merged**
