### PR TITLE
Destination Bigquery: delete unused methods

### PR DESCRIPTION
**Pull request by edgao**
not going to publish this change, it's pure code cleanup

### CODE REVIEW

**Review by evantahler — APPROVED** [review]
👍 if tests are green

**Comment by edgao** [comment]
airbyte-ci is complaining about version increment check but otherwise happy. Merging.

**Comment by octavia-approvington** [comment]
Lets do it! <br/> giddddy-up

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
