### PR TITLE
docs: Add plain-text info

### PR DESCRIPTION
**Pull request by nataliekwong**
## What
- Add note about plain-text, requested by @marcosmarxm 

## How
Screenshot 2024-08-02 at 5 10 14 PM

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Are we going to add a note in Quickstart too>?

**Comment by nataliekwong** [comment]
Can you remind me where you wanted that and what the verbiage you want there?  I couldn't find a good place for that just by scanning is this morning.

**Comment by marcosmarxm** [comment]
> :::tip When you're ready to put an Airbyte instance into production, you'll want to review our guides on deployment.
> For the best experience, we recommend [Deploying Airbyte on Kubernetes via Helm](https://github.com/airbytehq/airbyte/blob/master/docs/deploying-airbyte/deploying-airbyte.md). :::

:::tip 

When you're ready to put an Airbyte instance into production, you'll want to review our guides on deployment.

For the best experience, we recommend [Deploying Airbyte on Kubernetes via Helm](https://github.com/airbytehq/airbyte/blob/master/docs/deploying-airbyte/deploying-airbyte.md).

Airbyte's default behavior is to store connector secrets in your configured database. These secrets are stored in plain text and are not encrypted. Please refer to the Secret Management documentation to set up an external secret manager.

:::

What do you do think?

**Comment by nataliekwong** [comment]
@marcosmarxm how's this?
Screenshot 2024-08-05 at 8 18 51 PM

**Review by marcosmarxm — APPROVED** [review]
Awesome!

**Pull request merged**
