### PR TITLE
docs(postgres): remove postgres 13 limit

### PR DESCRIPTION
**Pull request by hongbo-miao**
## What

Remove postgres 13 limit.

Based on the info at https://airbytehq.slack.com/archives/C021JANJ6TY/p1714670231966129

We no longer need to use Postgres 13.
Postgres 15 and 16 both work well.

image

## Can this PR be safely reverted and rolled back?

- [x] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Comment by marcosmarxm** [comment]
@bgroff can you confirm this is safe to update the docs?

**Review by davinchia — APPROVED** [review]
Onboard with this. @bgroff and I had a conversation where we agreed we want to move to Postgres 15, and Deployments will pull the trigger, so I want to defer to him.

**Comment by hongbo-miao** [comment]
Hi @marcosmarxm @davinchia I can confirm Airbyte v0.63.1, Helm Chart v0.199.0 works with Postgres 16.3 😃

image

image

image
 
image

image

**Comment by hongbo-miao** [comment]
Hi @marcosmarxm @davinchia @bgroff I just succeed deploying Airbyte v0.63.1, Helm Chart v0.199.0. It works well with a clean Postgres 16.3

All my deployment code is at https://github.com/hongbo-miao/hongbomiao.com/pull/17475 😃

image

image

**Review by bgroff — APPROVED** [review]

**Pull request merged**
