### PR TITLE
Normalization: Fix incorrect jinja2 macro `json_extract_array` call

### LINKED ISSUE #13875: Destination Redshift broken integration tests in the master branch
Integration tests are permanently failing on the normalization step
`Error: 2-06-14 11:56:07 normalization > 11:56:05.559977 [error] [MainThread]: Database Error in model array_test_1 (models/generated/airbyte_tables/integration_test_spvsd/array_test_1.sql)`
Please see https://github.com/airbytehq/airbyte/runs/6879607021?check_suite_focus=true

### LINKED ISSUE #13876: Destination Snowflake broken integration tests in the master branch
Integration tests are permanently failing on the normalization step
`Error: 2-06-14 11:54:44 normalization > 11:54:41.524723 [error] [MainThread]: Database Error in model ARRAY_TEST_1 (models/generated/airbyte_tables/INTEGRATION_TEST_DCCAT/ARRAY_TEST_1.sql)`
Please see https://github.com/airbytehq/airbyte/runs/6879607198?check_suite_focus=true

### LINKED ISSUE #13891: HubSpot syncs failing normalization with Snowflake destination
## Environment
- **Airbyte version**:  0.39.19-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: HubSpot 0.1.70
- **Destination Connector and version**: Snowflake 0.4.28
- **Step where error happened**: Sync job

## Current Behavior

HubSpot syncs are failing during normalization "Failure Origin: normalization, Message: Something went wrong during normalization". Same issue happens when going back to HubSpot 0.1.69.

## Expected Behavior

Syncs not to fail when normalization is enabled.

## Logs

`Unknown function JSON_EXTRACT_ARRAY` seems to be the issue. This function does not exist in Snowflake: https://docs.snowflake.com/en/sql-reference/functions-all.html

```
2022-06-17 14:57:33 [42mnormalization[0m > 14:57:29.098489 [info ] [MainThread]: [31mCompleted with 1 error and 0 warnings:[0m
2022-06-17 14:57:33 [42mnormalization[0m > 14:57:29.098967 [info ] [MainThread]: 
2022-06-17 14:57:33 [42mnormalization[0m > 14:57:29.099661 [error] [MainThread]: [33mDatabase Error in model EMAIL_EVENTS (models/generated/airbyte_tables/HUBSPOT/EMAIL_EVENTS.sql)[0m
2022-06-17 14:57:33 [42mnormalization[0m > 14:57:29.100110 [error] [MainThread]:   002140 (42601): SQL compilation error:
2022-06-17 14:57:33 [42mnormalization[0m > 14:57:29.100924 [error] [MainThread]:   Unknown function JSON_EXTRACT_ARRAY
2022-06-17 14:57:33 [42mnormalization[0m > 14:57:29.101368 [error] [MainThread]:   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/HUBSPOT/EMAIL_EVENTS.sql
2022-06-17 14:57:33 [42mnormalization[0m > 14:57:29.102390 [info ] [MainThread]: 
2022-06-17 14:57:33 [42mnormalization[0m > 14:57:29.103189 [info ] [MainThread]: Done. PASS=0 WARN=0 ERROR=1 SKIP=5 TOTAL=6
2022-06-17 14:57:33 [32mINFO[m i.a.w.t.TemporalAttemptExecution(lambda$getWorkerThread$2):161 - Completing future exceptionally...
io.airbyte.workers.exception.WorkerException: Normalization Failed.
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:63) ~[io.airbyte-airbyte-workers-0.39.19-alpha.jar:?]
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:21) ~[io.airbyte-airbyte-workers-0.39.19-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:158) ~[io.airbyte-airbyte-workers-0.39.19-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.airbyte.workers.exception.WorkerException: Normalization Failed.

```

## Steps to Reproduce
1. Setup HubSpot 0.1.70 source and Snowflake 0.4.28 with incremental sync + normalization
2. Sync

## Are you willing to submit a PR?

No.

### PR DESCRIPTION
**Pull request by grubberr**
Signed-off-by: Sergey Chvalyuk <grubberr@gmail.com>

## What
In this PR https://github.com/airbytehq/airbyte/pull/13289 was introduced new bug
incorrect jinaj2 macro call `json_extract_array` from `default__json_extract_string_array`

## How
Fixing jinaj2 call

### CODE REVIEW

**Comment by grubberr** [comment]
base-normalization on local laptop:

```
pytest integration_tests - OK
...
27 passed, 9 skipped in 4929.62s (1:22:09)
```

**Review by bazarnov — APPROVED** [review]
Looks good!

**Review by etsybaev — APPROVED** [review]
Approved since Integration-connectors passed for connectors in PRs

**Comment by bazarnov** [comment]
@grubberr 
Have you bumped the normalization version correctly along with server side tag?

**Comment by Tomperez98** [comment]
Following this bug. I have problems moving data from Shopify to Snowflake for the same reason `JSON_EXTRACT_ARRAY`.

This fix should solve the problem. Right? @bazarnov

**Comment by grubberr** [comment]
@bazarnov yes, my fault,  we need to bump version in 
airbyte-workers/src/main/java/io/airbyte/workers/normalization/NormalizationRunnerFactory.java

**Comment by grubberr** [comment]
@Tomperez98 yes this fix sould solve `JSON_EXTRACT_ARRAY` problem

**Comment by Tomperez98** [comment]
@grubberr I just bumped the version manually in the file `airbyte-workers/src/main/java/io/airbyte/workers/normalization/NormalizationRunnerFactory.java` and then build the application locally.

Still getting the error `Unknown function JSON_EXTRACT_ARRAY` when loading data to Snowflake :snowflake: :cry: 

Any idea what might be wrong? I opened this [issue](https://github.com/airbytehq/airbyte/issues/13920)

**Comment by Tomperez98** [comment]
Comparing against previous PRs related to normalization I see this file is also changed `airbyte-integrations/bases/base-normalization/snowflake.Dockerfile`

**Comment by grubberr** [comment]
@Tomperez98 show me your logs

**Comment by Tomperez98** [comment]
@grubberr It worked! Thanks.

Closing the [issue](https://github.com/airbytehq/airbyte/issues/13920) as well

**Comment by emilsedgh** [comment]
My connectors have stopped working as of 3 days ago. Im sending from Gitlab -> Postgres and I'm seeing this error:



Are they related? And if yes, when do you guys think when do you think the fix will be deployed on Aitbyte.com?

**Comment by grubberr** [comment]
@emilsedgh Can you please re-load your picture ? I cannot see it. I only can see message 
> Uploading Screen Shot 2022-06-20 at 9.10.19 PM.png…

**Comment by emilsedgh** [comment]
Oh sorry here you go:

Screen Shot 2022-06-20 at 9 54 26 PM

**Review by edgao — COMMENTED** [review]
one followup to improve our future test coverage, but good catch here!

**Pull request merged**
