### PR TITLE
Source bigcommerce: add channel and store stream

### LINKED ISSUE #16649: Source BigCommerce: Add Channel and Store Stream
## Tell us about the new connector you’d like to have
* Which source and which destination?

This will include the `channels` and `store` endpoint for the existing `bigcommerce` source

* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

The `store` endpoint is only support by `v2` of the BigCommerce API

## Describe the context around this new connector
* Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.

We want to enrich our bigcommerce pipelines with store and channel metadata. 

* How often do you want to run syncs?

Daily 

* If this is an API source connector, which entities/endpoints do you need supported?

`Store Information` - https://developer.bigcommerce.com/api-reference/bb1daaaeccae0-get-store-information
`Channels` - https://developer.bigcommerce.com/api-reference/d2298071793d6-get-all-channels

* If the connector is for a paid service, can we name you as a mutual user when we subscribe for an account? Which company should we name? 

N/A

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

Calling the API in another way

## Are you willing to submit a PR?

Yes!

### PR DESCRIPTION
**Pull request by roisinbolt**
## What

Add a source for `Channels` and `Store` to the source-bigcommerce integration

Closes https://github.com/airbytehq/airbyte/issues/16649

## How

Channels:
Channels has been added as a `IncrementalBigcommerceStream`.

I had to overwrite `order_field` bacause Channels API do not acept `asc` value

Store:
Channels has been added as a `BigcommerceStream`.

I had to overwrite `parse_response` to ensure the store record is passed the format expected by downstream functions.

## Recommended reading order
1. `configured_catalog.json`
2. `channels.json`
3. `store.json`
4. `source.py`

## Pre-merge Checklist
Expand the relevant checklist and delete the others.

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- [x] Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- [x] Secrets in the connector's spec are annotated with `airbyte_secret`
- [ ] Unit & integration tests added and passing. Community members, please provide proof of success locally e.g: screenshot or copy-paste unit, integration, and acceptance test output. To run acceptance tests for a Python connector, follow instructions in the README. For java connectors run `./gradlew :airbyte-integrations:connectors:<name>:integrationTest`.
- [ ] Code reviews completed
- [x] Documentation updated
    - [x] Connector's `README.md`
    - [x] Connector's `bootstrap.md`. See [description and examples](https://docs.google.com/document/d/1ypdgmwmEHWv-TrO4_YOQ7pAJGVrMp5BOkEVh831N260/edit?usp=sharing)
    - [x] Changelog updated in `docs/integrations/<source or destination>/<name>.md` including changelog. See changelog [example](https://docs.airbyte.io/integrations/sources/stripe#changelog)
- [x] PR name follows [PR naming conventions](https://docs.airbyte.io/contributing-to-airbyte/updating-documentation#issues-and-pull-requests)

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- [ ] Create a non-forked branch based on this PR and test the below items on it
- [ ] Build is successful
- [ ] If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).
- [ ] [`/test connector=connectors/<name>` command](https://docs.airbyte.io/connector-development#updating-an-existing-connector) is passing
- [ ] New Connector version released on Dockerhub and connector version bumped by running the `/publish` command described [here](https://docs.airbyte.io/connector-development#updating-an-existing-connector)

</details>

## Tests

<details><summary><strong>Unit</strong></summary>

There are currently no unit tests in the source-bigcommerce integration. Is it expected for me to add these tests along with this PR?

</details>

<details><summary><strong>Integration</strong></summary>

There are no integration tests present in the `source-bigcommerce `folder

</details>

<details><summary><strong>Acceptance</strong></summary>

The acceptance tests are all error out with a `404 Client Error` locally

</details>

### CODE REVIEW

**Comment by roisinbolt** [comment]
@marcosmarxm Thanks for running the integration tests! I have just pushed a fix for `test_core`, `test_incremental` looks related to the `customers` stream so I am unsure if this is related to the changes in this PR?

**Comment by roisinbolt** [comment]
Hey @marcosmarxm thanks for re-running! I'd appreciate a bit of guidance on how to recreate this failure locally if you have some time?

As I mentioned above, the `test_incremental` is failing on a `full_refresh` store stream so it would be good to understand what is causing this

**Comment by roisinbolt** [comment]
Am I able to re-run the tests from my side?

**Comment by marcosmarxm** [comment]
@sajarin can you request a maintainer to review this contribution?

**Comment by sajarin** [comment]
Thank you for the PR @roisinbolt. This PR is part of Airbyte's Community Maintainer program and will be reviewed by a member of our community. A maintainer will be assigned shortly to help review and get this PR merged into our main branch. Thank you for being patient, we hope to get this merged soon!

**Comment by roisinbolt** [comment]
Hey @sajarin, just wanted to check in if there was any progress on this?

**Comment by sajarin** [comment]
@roisinbolt, sorry for the wait. I'll prioritize assigning someone to this PR!

**Review by vincentkoc — APPROVED** [review]
I made a few changes to make unit tests pass, all good now

**Comment by roisinbolt** [comment]
@koconder Thanks for all your help! Is this ready to be merged?

**Comment by koconder** [comment]
@roisinbolt yes please merge

**Comment by roisinbolt** [comment]
@koconder I don't have permission to merge this PR, if you have a minute would you be okay to do so?

**Comment by koconder** [comment]
@sajarin can we please merge, some reason i am unable to merge

**Pull request merged**
