### PR TITLE
Clearer CSV placeholders

### PR DESCRIPTION
**Pull request by sherifnada**

### CODE REVIEW

**Review by cgardens — APPROVED** [review]
If you think this is important to do now, I'm okay with it. My preference would be to hold off on this. We need to get `required` and `default` values and right. We have an issue to do this https://github.com/airbytehq/airbyte/issues/343. I'm not too excited about doing it on an ad hoc basis because I think it'll be confusing. 

Also, I'm assuming this actually works, right? I assume this is relying on the defaults in the singer target, so everything is null and then the integration assigns a default?

**Comment by sherifnada** [comment]
This isn't meant to "set" the default value. It's to get around that in the UI it's hard to see the default value: 

Screen Shot 2020-09-21 at 4 13 37 PM

and replcae it instead with something like: 
Screen Shot 2020-09-21 at 4 31 32 PM

So I think we might need to make a distinction between the default value that gets passed to/used by the server and the placeholder that we put in the UI fields.

**Comment by cgardens** [comment]
To be clear, airbyte does not set any default values.

**Comment by sherifnada** [comment]
Also yes this works as is since the `examples` field is just used in the UI

**Comment by sherifnada** [comment]
Will merge and if needed we can make changes to this once we get to the default thing -- would prefer to have the more transparent UI for now.

**Comment by cgardens** [comment]
@sherifnada this doesn't actually work.

```
airbyte-scheduler | 2020-09-23 03:02:16 DEBUG i.a.w.p.s.DefaultSingerTap(close):140 - {job_id=2, job_log_filename=logs.log, job_root=/tmp/workspace/2/0} - Closing tap process
airbyte-scheduler | 2020-09-23 03:02:16 DEBUG i.a.w.p.s.DefaultSingerTarget(close):106 - {job_id=2, job_log_filename=logs.log, job_root=/tmp/workspace/2/0} - Closing target process
airbyte-scheduler | 2020-09-23 03:02:16 ERROR i.a.c.i.LineGobbler(voidCall):60 - {} - Traceback (most recent call last):
airbyte-scheduler | 2020-09-23 03:02:16 ERROR i.a.c.i.LineGobbler(voidCall):60 - {} -   File "/singer/env/bin/target-csv", line 11, in <module>
airbyte-scheduler | 2020-09-23 03:02:16 ERROR i.a.c.i.LineGobbler(voidCall):60 - {} -     load_entry_point('target-csv==0.3.0', 'console_scripts', 'target-csv')()
airbyte-scheduler | 2020-09-23 03:02:16 ERROR i.a.c.i.LineGobbler(voidCall):60 - {} -   File "/singer/env/lib/python3.7/site-packages/target_csv.py", line 144, in main
airbyte-scheduler | 2020-09-23 03:02:16 ERROR i.a.c.i.LineGobbler(voidCall):60 - {} -     config.get('destination_path', ''))
airbyte-scheduler | 2020-09-23 03:02:16 ERROR i.a.c.i.LineGobbler(voidCall):60 - {} -   File "/singer/env/lib/python3.7/site-packages/target_csv.py", line 82, in persist_messages
airbyte-scheduler | 2020-09-23 03:02:16 ERROR i.a.c.i.LineGobbler(voidCall):60 - {} -     quotechar=quotechar)
airbyte-scheduler | 2020-09-23 03:02:16 ERROR i.a.c.i.LineGobbler(voidCall):60 - {} -   File "/usr/local/lib/python3.7/csv.py", line 140, in __init__
airbyte-scheduler | 2020-09-23 03:02:16 ERROR i.a.c.i.LineGobbler(voidCall):60 - {} -     self.writer = writer(f, dialect, *args, **kwds)
airbyte-scheduler | 2020-09-23 03:02:16 ERROR i.a.c.i.LineGobbler(voidCall):60 - {} - TypeError: "delimiter" must be a 1-character string
airbyte-scheduler | 2020-09-23 03:02:16 ERROR i.a.w.p.s.SingerSyncWorker(run):86 - {job_id=2, job_log_filename=logs.log, job_root=/tmp/workspace/2/0} - Sync worker failed.
airbyte-scheduler | io.airbyte.workers.WorkerException: target process wasn't successful
airbyte-scheduler | 	at io.airbyte.workers.protocols.singer.DefaultSingerTarget.close(DefaultSingerTarget.java:109) ~[airbyte-workers-0.1.0.jar:?]
airbyte-scheduler | 	at io.airbyte.workers.protocols.singer.SingerSyncWorker.run(SingerSyncWorker.java:85) [airbyte-workers-0.1.0.jar:?]
airbyte-scheduler | 	at io.airbyte.workers.protocols.singer.SingerSyncWorker.run(SingerSyncWorker.java:44) [airbyte-workers-0.1.0.jar:?]
airbyte-scheduler | 	at io.airbyte.workers.wrappers.OutputConvertingWorker.run(OutputConvertingWorker.java:44) [airbyte-workers-0.1.0.jar:?]
airbyte-scheduler | 	at io.airbyte.workers.wrappers.JobOutputSyncWorker.run(JobOutputSyncWorker.java:32) [airbyte-workers-0.1.0.jar:?]
airbyte-scheduler | 	at io.airbyte.scheduler.WorkerRun.lambda$new$0(WorkerRun.java:53) [airbyte-scheduler-0.1.0.jar:?]
airbyte-scheduler | 	at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:61) [airbyte-scheduler-0.1.0.jar:?]
airbyte-scheduler | 	at io.airbyte.scheduler.WorkerRun.call(WorkerRun.java:42) [airbyte-scheduler-0.1.0.jar:?]
airbyte-scheduler | 	at io.airbyte.commons.concurrency.LifecycledCallable.execute(LifecycledCallable.java:114) [airbyte-commons-0.1.0.jar:?]
airbyte-scheduler | 	at io.airbyte.commons.concurrency.LifecycledCallable.call(LifecycledCallable.java:98) [airbyte-commons-0.1.0.jar:?]
airbyte-scheduler | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
airbyte-scheduler | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
airbyte-scheduler | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
airbyte-scheduler | 	at java.lang.Thread.run(Thread.java:832) [?:?]
airbyte-scheduler | 2020-09-23 03:02:16 INFO i.a.s.p.DefaultSchedulerPersistence(updateStatus):190 - {job_id=2, job_log_filename=logs.log, job_root=/tmp/workspace/2/0} - Setting job status to FAILED for job 2
```

**Pull request merged**
