### PR TITLE
[source-stripe] added expanded values for coupons, charges and prices objects

### PR DESCRIPTION
**Pull request by dramirez-bluon**
## What
Users will get additional columns on the next objects corresponding to expanded data:

- Coupons:
  - [Applies To](https://docs.stripe.com/api/coupons/object#coupon_object-applies_to)
- Charges:
  - [Balance Transaction](https://docs.stripe.com/api/charges/object#charge_object-balance_transaction)
  - [Customer](https://docs.stripe.com/api/charges/object#charge_object-customer)
  - [Invoice](https://docs.stripe.com/api/charges/object#charge_object-invoice)
  - [Payment Intent](https://docs.stripe.com/api/charges/object#charge_object-payment_method_details)
  - [Failure Balance Transaction](https://docs.stripe.com/api/charges/object#charge_object-failure_balance_transaction)
- Prices:
  - [Tiers](https://docs.stripe.com/api/prices/object#price_object-tiers)

## How
Added expanded items in each stream

## User Impact
No user impact,  users will get additional columns coupons, prices, charges

## Can this PR be safely reverted and rolled back?
- [ ] YES 💚
- [ ] NO ❌

### CODE REVIEW

**Review by marcosmarxm — CHANGES_REQUESTED** [review]
Can you provide the Stripe documentation link showing these stream have these fields?
Were you able to build the connector locally and run using this version?

Please bump the connector version in the metadata file and changelog documentation version.

**Comment by aaronsteers** [comment]
@marcosmarxm and @dramirez-bluon - Just FYI, I'm using this PR to test some of our new CI check improvements. You will want to re-pull the latest before adding new commits, and otherwise please disregard any other noise on the PR. Thanks! 🙏

**Comment by dramirez-bluon** [comment]
Hi, @marcosmarxm 

Yes I tested by running as documentation described:
```
docker run --rm airbyte/source-stripe:dev spec
docker run --rm -v $(pwd)/secrets:/secrets airbyte/source-stripe:dev check --config /secrets/config.json
docker run --rm -v $(pwd)/secrets:/secrets airbyte/source-stripe:dev discover --config /secrets/config.json
docker run --rm -v $(pwd)/secrets:/secrets -v $(pwd)/integration_tests:/integration_tests airbyte/source-stripe:dev 
```
Version bumped and changelog modified.

**Comment by aaronsteers** [comment]
@dramirez-bluon - Thanks for your patience as we worked through the needed CI improvements. A few notes for your reference:

1. You can now see results of format and lint checks under the "Check for formatting errors" job.
2. Maintainers can now run `/format-fix` to apply simple fixes, which I've done above.
3. You'll need to repull one more time the latest commits if you want to add any additional commits.
4. @marcosmarxm will work with you to ensure the final test suite is passing. (One more action item on our side to get those running.)

Thanks for contributing to Airbyte - please let us know if you have any questions or feedback. 🙏

**Comment by marcosmarxm** [comment]
Hello @dramirez-bluon sorry the delay. I included this change to the Connector team backlog to them priority the review in next sprint. It can take some time, for that reason ask your patience until they don't review your contribution. Feel free anytime to ping me here or in Slack to get an update about the status of your PR.

**Comment by dramirez-bluon** [comment]
Hi, @marcosmarxm how can I build and publish the dev version of the connector??

Can you expand a little bit more on this? My understandment is that if I build and push to a private repo I would have to create it a new connector since the repo for this sources is airbyte/source-stripe.

**Comment by maxi297** [comment]
@dramirez-bluon we've learned recently that expandable fields are only working in some very specific conditions during incremental syncs. [This ticket](https://github.com/airbytehq/airbyte/issues/38039) discuss this point. 

Can you confirm that the added fields are available in the most recent version of the API and provide a stack trace here? Else, is your use case full_refresh only?

**Pull request closed without merging**
