### PR TITLE
🐛 Destination Teradata: fix Parameter 2 length size issue  #27929 

### PR DESCRIPTION
**Pull request by sc250072**
## What

- Destination teradata sync is failing when _airbyte_data exceeds 64000 bytes and issue is logged with https://github.com/airbytehq/airbyte/issues/27929. _airbyte_data is defined as String to handle JSON data and teradata JDBC throwing this limitation error if json data is more than 64K bytes. Teradata JDBC provides a way to handle large JSON data with JSONStruct class object as specified at [Teradata JDBC JSON Handling](https://teradata-docs.s3.amazonaws.com/doc/connectivity/jdbc/reference/current/samp/T21507JD.java.txt) . As per this handling, _airbyte_data is modified to handle as JSONStruct instead of String. 

- Added unit tests [TeradataSqlOperationsTest.java](https://github.com/airbytehq/airbyte/pull/29465/files#diff-60d1c5b343bdc689fc4f0ff4fc1305b810f7ae44fcd7e991cbe210cd3e253236) for TeradataSqlOperations.java

## How
JSON data types needs to be handled with JSONStruct format in teradata. Airbyte jsonData field is JSON type and modified handling of this column with JSONStruct object.

## Recommended reading order
1. `io.airbyte.integrations.destination.teradata.util.JSONStruct.java`
2. `io.airbyte.integrations.destination.teradata.TeradataSqlOperations.java`
3. `io.airbyte.integrations.destination.teradata.TeradataSqlOperationsTest`

## 🚨 User Impact 🚨
User doesn't see below error with this fix
`Destination-Teradata gives error of Parameter 2 length is 70437 bytes, which is greater than the maximum 64000 bytes that can be set if the size of column exceeds 64K`

*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit).***

*If there are breaking changes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.*

## Pre-merge Actions
*Expand the relevant checklist and delete the others.*

<details><summary><strong>Updating a connector</strong></summary>

### Community member or Airbyter

- Grant edit access to maintainers ([instructions](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests))
- Unit & integration tests added

### Airbyter

If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items.

- Create a non-forked branch based on this PR and test the below items on it
- Build is successful
- If new credentials are required for use in CI, add them to GSM. [Instructions](https://docs.airbyte.io/connector-development#using-credentials-in-ci).

</details>

image
image

### CODE REVIEW

**Comment by marcosmarxm** [comment]
Please follow guidance about title and description for your PR https://docs.airbyte.com/contributing-to-airbyte/resources/pull-requests-handbook

**Comment by marcosmarxm** [comment]
Right now Airbyte team is dedicated to review August Hackathon contribution and can be slow to return to your contribution review. Hope you understand.

**Comment by SatishChGit** [comment]
> Please follow guidance about title and description for your PR https://docs.airbyte.com/contributing-to-airbyte/resources/pull-requests-handbook

Updated title and description as per handbook guide

**Comment by SatishChGit** [comment]
> Right now Airbyte team is dedicated to review August Hackathon contribution and can be slow to return to your contribution review. Hope you understand.

Thank you @marcosmarxm for the update. Sure we will wait for review.

**Comment by evantahler** [comment]
There's certainly a merge conflict now :D Please try and clean that up, or make a new branch and PR

**Comment by SatishChGit** [comment]
Closing this PR as many conflicts

**Pull request closed without merging**
