### PR TITLE
:sparkles: Source TikTok Marketing: add new streams

### PR DESCRIPTION
**Pull request by davydov-d**
## What
https://github.com/airbytehq/airbyte/issues/28658
New streams:
 - [Audiences](https://business-api.tiktok.com/portal/docs?id=1739940506015746)
 - [Images](https://business-api.tiktok.com/portal/docs?id=1740052016789506)
 - [Music](https://business-api.tiktok.com/portal/docs?id=1740053909509122)
 - [Portfolios](https://business-api.tiktok.com/portal/docs?id=1766324010279938)
 - [Videos](https://business-api.tiktok.com/portal/docs?id=1740050472224769)

## How
Add new streams, cover them with acceptance tests

### CODE REVIEW

**Comment by airbyte-oss-build-runner** [comment]
##  source-tiktok-marketing test report (commit [`ae0a6aea7e`](https://github.com/airbytehq/airbyte/pull/31610/commits/ae0a6aea7e7bc4fdc4c52fb9f5e2053afbcd284b)) - ❌

⏲️  Total pipeline duration: 49mn12s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Build source-tiktok-marketing docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                              | ✅       |
| Acceptance tests                                                        | ❌       |
| Code format checks                                                      | ✅       |
| Validate metadata for source-tiktok-marketing                           | ✅       |
| Connector version semver check                                          | ✅       |
| Connector version increment check                                       | ✅       |
| QA checks                                                               | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_28658-source-tiktok-marketing-add-new-streams/1697726298/ae0a6aea7e7bc4fdc4c52fb9f5e2053afbcd284b/source-tiktok-marketing/3.8.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:ae0a6aea7e7bc4fdc4c52fb9f5e2053afbcd284b)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-tiktok-marketing test report (commit [`b3eca4f153`](https://github.com/airbytehq/airbyte/pull/31610/commits/b3eca4f153c1a3c5779ef22f926c3a112fc9ef95)) - ❌

⏲️  Total pipeline duration: 49mn57s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Build source-tiktok-marketing docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                              | ✅       |
| Acceptance tests                                                        | ❌       |
| Code format checks                                                      | ✅       |
| Validate metadata for source-tiktok-marketing                           | ✅       |
| Connector version semver check                                          | ✅       |
| Connector version increment check                                       | ✅       |
| QA checks                                                               | ❌       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_28658-source-tiktok-marketing-add-new-streams/1697732157/b3eca4f153c1a3c5779ef22f926c3a112fc9ef95/source-tiktok-marketing/3.8.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:b3eca4f153c1a3c5779ef22f926c3a112fc9ef95)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-tiktok-marketing test report (commit [`7db0730501`](https://github.com/airbytehq/airbyte/pull/31610/commits/7db073050133582dcbbc6fa40f89554b63501cb4)) - ❌

⏲️  Total pipeline duration: 43mn16s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Build source-tiktok-marketing docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                              | ✅       |
| Acceptance tests                                                        | ❌       |
| Code format checks                                                      | ✅       |
| Validate metadata for source-tiktok-marketing                           | ✅       |
| Connector version semver check                                          | ✅       |
| Connector version increment check                                       | ✅       |
| QA checks                                                               | ❌       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_28658-source-tiktok-marketing-add-new-streams/1697736256/7db073050133582dcbbc6fa40f89554b63501cb4/source-tiktok-marketing/3.8.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7db073050133582dcbbc6fa40f89554b63501cb4)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-tiktok-marketing test report (commit [`73538cbaea`](https://github.com/airbytehq/airbyte/pull/31610/commits/73538cbaea4eadad744668ef6bc45b04201bfc13)) - ❌

⏲️  Total pipeline duration: 47mn18s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Build source-tiktok-marketing docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                              | ✅       |
| Acceptance tests                                                        | ✅       |
| Code format checks                                                      | ✅       |
| Validate metadata for source-tiktok-marketing                           | ✅       |
| Connector version semver check                                          | ✅       |
| Connector version increment check                                       | ✅       |
| QA checks                                                               | ❌       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_28658-source-tiktok-marketing-add-new-streams/1697783053/73538cbaea4eadad744668ef6bc45b04201bfc13/source-tiktok-marketing/3.8.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:73538cbaea4eadad744668ef6bc45b04201bfc13)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-paypal-transaction test report (commit [`7c9faa2f30`](https://github.com/airbytehq/airbyte/pull/31610/commits/7c9faa2f30f044b9df86ecb9034cfcf5e2d53100)) - ✅

⏲️  Total pipeline duration: 01mn49s 

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Build source-paypal-transaction docker image for platform(s) linux/x86_64 | ✅       |
| Acceptance tests                                                          | ✅       |
| Code format checks                                                        | ✅       |
| Validate metadata for source-paypal-transaction                           | ✅       |
| Connector version semver check                                            | ✅       |
| QA checks                                                                 | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_28658-source-tiktok-marketing-add-new-streams/1697787969/7c9faa2f30f044b9df86ecb9034cfcf5e2d53100/source-paypal-transaction/2.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:7c9faa2f30f044b9df86ecb9034cfcf5e2d53100)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-paypal-transaction test report (commit [`e6e41a1e0b`](https://github.com/airbytehq/airbyte/pull/31610/commits/e6e41a1e0b2aaa6f2b544eed56da33d2ff0f8c8e)) - ✅

⏲️  Total pipeline duration: 01mn14s 

| Step                                                                      | Result   |
|:--------------------------------------------------------------------------|:---------|
| Build source-paypal-transaction docker image for platform(s) linux/x86_64 | ✅       |
| Acceptance tests                                                          | ✅       |
| Code format checks                                                        | ✅       |
| Validate metadata for source-paypal-transaction                           | ✅       |
| Connector version semver check                                            | ✅       |
| QA checks                                                                 | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_28658-source-tiktok-marketing-add-new-streams/1697788338/e6e41a1e0b2aaa6f2b544eed56da33d2ff0f8c8e/source-paypal-transaction/2.1.1/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e6e41a1e0b2aaa6f2b544eed56da33d2ff0f8c8e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-paypal-transaction test
```

**Comment by airbyte-oss-build-runner** [comment]
##  source-tiktok-marketing test report (commit [`e6e41a1e0b`](https://github.com/airbytehq/airbyte/pull/31610/commits/e6e41a1e0b2aaa6f2b544eed56da33d2ff0f8c8e)) - ✅

⏲️  Total pipeline duration: 17mn07s 

| Step                                                                    | Result   |
|:------------------------------------------------------------------------|:---------|
| Build source-tiktok-marketing docker image for platform(s) linux/x86_64 | ✅       |
| Unit tests                                                              | ✅       |
| Acceptance tests                                                        | ✅       |
| Code format checks                                                      | ✅       |
| Validate metadata for source-tiktok-marketing                           | ✅       |
| Connector version semver check                                          | ✅       |
| Connector version increment check                                       | ✅       |
| QA checks                                                               | ✅       |

🔗 [View the logs here](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/pull_request/ddavydov_28658-source-tiktok-marketing-add-new-streams/1697788338/e6e41a1e0b2aaa6f2b544eed56da33d2ff0f8c8e/source-tiktok-marketing/3.8.0/output.html)

☁️ [View runs for commit in Dagger Cloud](https://alpha.dagger.cloud/changeByPipelines?filter=dagger.io/git.ref:e6e41a1e0b2aaa6f2b544eed56da33d2ff0f8c8e)

*Please note that tests are only run on PR ready for review. Please set your PR to draft mode to not flood the CI engine and upstream service on following commits.*
**You can run the same pipeline locally on this branch with the [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/pipelines/README.md) tool with the following command**
```bash
airbyte-ci connectors --name=source-tiktok-marketing test
```

**Review by bazarnov — APPROVED** [review]

**Pull request merged**
