### PR TITLE
Revert Convert the server to micronaut

### PR DESCRIPTION
**Pull request by benmoriceau**
Reverts airbytehq/airbyte#19194

It is blocking a p0 resolution, reverting + there is some CORS issues detected bu @krishnaglick

### CODE REVIEW

**Review by pedroslopez — APPROVED** [review]

**Comment by octavia-approvington** [comment]
Enough! Let's do this <br/> goooooo!

**Comment by octavia-approvington** [comment]
Lets do it! <br/> giddddy-up

**Comment by octavia-approvington** [comment]
A crack team of mammals has made a decision.  <br/> imagine a seal of approval

**Comment by octavia-approvington** [comment]
After a careful ML study, <br/> we think this looks okay.  <br/> imagine code being okay

**Review by octavia-approvington — APPROVED** [review]

**Pull request merged**
