### PR TITLE
🚨Source Wikipedia Pageviews: Migrate to poetry

### PR DESCRIPTION
**Pull request by btkcodedev**
## What
Migrating to poetry

## Can this PR be safely reverted and rolled back?
- [x] YES 💚

### CODE REVIEW

**Comment by btkcodedev** [comment]
Creds are expired, But all other checks are passed

**Comment by natikgadzhi** [comment]
@btkcodedev it's sus that there are _new_ failures compared to previous ones: 

```
2 new failing acceptance tests detected:
-test_core.py::TestBasicRead::test_read[inputs0]
-test_core.py::TestDiscovery::test_defined_cursors_exist_in_schema[inputs0]
-test_core.py::TestConnection::test_check[inputs0]
Please fix the new failing tests before merging this PR.
Please also check the original 3 acceptance tests failures and assess how critical they are.
```

**Comment by ChristoGrab** [comment]
Looks like there's at least one issue with date formatting:

```
"No format in ['%Y%m%d'] matching 2020010100\"
```

The spec descriptions state that start dates can match either [YYYYMMDD] or [YYYYMMDDHH], but the manifest only allows "%Y%m%d", guessing the issue might be with a value we use in our sandbox config?

**Comment by ChristoGrab** [comment]
@btkcodedev @natikgadzhi There were a couple issues with the existing implementation of the connector, the main one being that one of the streams was configured incrementally despite not having a cursor field. I had a bit of a brainfart while looking into this and pulled from the wrong branch 🫠 But the good news is the [fix is up at this PR, also by btkcodedev](https://github.com/airbytehq/airbyte/pull/38724), so we can get the poetry migration and the builder compatibility changes by merging that PR instead of this one.

**Comment by natikgadzhi** [comment]
Alright, @ChristoGrab merged the PR you linked and closing this one.

**Pull request closed without merging**
