### PR TITLE
🐛Source LinkedIn Ads: Fix Readme commands, change spec from json to yaml

### PR DESCRIPTION
**Pull request by btkcodedev**
Closes https://github.com/airbytehq/PyAirbyte-Hackathon/issues/26
## Scenario: 
Syncs with PyAirbyte with Source-Linkedin Ads has no problems, but the readme documentation and schemas need a little updation

## Found issues:
 - README command mistakes - Corrected the read command
 - Spec in JSON format - Converted to YAML
 - Schemas won't be empty - Changed null, object to object for correct state output

image

## Proposing fix:
- Corrected the read command
- Converted Spec to YAML
- Changes schema property null, object to object for correct state output

### CODE REVIEW

**Comment by maxi297** [comment]
@lazebnyi schemas have been updated. I'm wondering how this impact the migration to low-code and vice-versa

**Comment by btkcodedev** [comment]
> @lazebnyi schemas have been updated. I'm wondering how this impact [the migration to low-code](https://github.com/airbytehq/airbyte/pull/38314) and vice-versa

Oh, this won't make conflict with Migration PR I think as the state needs to be changed from ["null", "object"] to "object" to get correct state output

**Comment by btkcodedev** [comment]
CI all pass, Ready to merge

**Review by natikgadzhi — CHANGES_REQUESTED** [review]
Schemas including nulls are intentional. All fields aside from PKs and parent record FKs should be nullable. 

@aaronsteers is there an assumption in Pyairbyte that breaks

**Comment by btkcodedev** [comment]
Oh, I got a review comment from previous connectors that having ['null', "object"] will expose the `parameters` while running the `discover` command which could be bad, 
Ref: https://github.com/airbytehq/airbyte/pull/36951#discussion_r1567577214

If there isn't a problem, I'll revert the schema changes :bow: 
Thanks!!

**Comment by natikgadzhi** [comment]
Parameters and nulls are two different beasts. Nulls good, $parameters bad.

**Comment by btkcodedev** [comment]
Done, CI is showing formatting errors with close.com, which is not related to this PR
Its ready to merge

**Review by natikgadzhi — APPROVED** [review]

**Comment by natikgadzhi** [comment]
If close has formatting problems on master too, please fix them. @btkcodedev. Otherwise lgtm, let's get to green CI.

**Comment by btkcodedev** [comment]
Sure Linking PR: https://github.com/airbytehq/airbyte/pull/39477

**Pull request merged**
